opencv/opencv

modules/imgproc/src/hough.cpp

Related message:
```
Assertion failed: (e == 0), function unlock, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/libcxx/libcxx-307.5/src/mutex.cpp, line 102.
```

imgproc: don't call .unlock() on non-holded mutex in houghCircles()

---

modules/core/include/opencv2/core/persistence.hpp
modules/core/src/persistence_cpp.cpp

resolves #10506
possibly also [this](https://github.com/opencv/opencv_contrib/issues/1504)
New overload method **write**.
Now, there is no cast to double.

Solves issue #10506

---

modules/imgcodecs/test/test_grfmt.cpp

GDAL message:
- ERROR 1: The BMP file is probably corrupted or too large. Image width = 480
GDAL fails due `GDALOpen()` call, so it can't be fixed in OpenCV.
- Ubuntu 14.06 / 16.04 works fine
- Ubuntu 17.10 / upcoming 18.04 - doesn't work
resolves #10118

imgcodecs: exclude rle8.bmp from GDAL tests

---

modules/core/src/parallel.cpp

even with enabled C++11
Details: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58938
Error message:
```
/build/master_pack-android/opencv/modules/core/src/parallel.cpp:254:9: error: 'exception_ptr' in namespace 'std' does not name a type
std::exception_ptr pException;
^
```

android: std::exception_ptr is not available on some platforms

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp
modules/imgcodecs/src/grfmt_tiff.cpp

Verified to be working locally with a variety of settings used on a sample image. Written image was loaded into an external TIFF Tag viewer utility (Aware Systems TIFF Tag viewer) to verify that PR does indeed write out DPI related tags correctly.

Support for setting TIFF DPI info in imwrite

---

modules/imgproc/src/lsd.cpp
modules/imgproc/test/test_lsd.cpp

- According to the LineSegmentDetector's comment, supported result types are `vector<Vec4f>` and `vector<Vec4i>` (https://github.com/opencv/opencv/blob/master/modules/imgproc/include/opencv2/imgproc.hpp#L1237). However `drawSegment()` does not support Vec4i lines. This patch resolves the issue.
- I added an test to check that `detect()` can also support Vec4i result.

LSD: support vector<Vec4i> lines

---

modules/core/src/parallel.cpp

Message sample:
```
modules/core/src/parallel.cpp:378:23: warning: declaration of 'stripeRange' shadows a member of 'this' [-Wshadow]
cv::Range stripeRange = this->stripeRange();
^
```

tbb: fix build warnings -Wshadow

---

modules/imgproc/test/test_lsd.cpp

- A LSD test for LSD_REFINE_**NONE** detector uses LSD_REFINE_**STD**. This is a minor patch to resolve this issue.

imgproc: fix wrong parameter in LSD test

---

modules/core/src/parallel_impl.cpp

replaced to safe binary compatible 'rep; nop' asm instruction
resolves #11274

core: fix mm_pause() for non-SSE i386 builds

---

cmake/OpenCVPylint.cmake

CMake generated files is a part of target depends list.
Details: `cmake --help-policy CMP0058`

cmake: fix Ninja generator warning about pylintrc

---

cmake/OpenCVDetectCUDA.cmake
modules/core/include/opencv2/core/cuda/vec_math.hpp
modules/cudev/test/CMakeLists.txt

* resolves #11291 
* add --std=c++11 flag to nvcc definition
* remove not used abs functions
```
```

CUDA: fix CUDA build crash

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/perf/perf_net.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/layers/scale_layer.cpp
modules/dnn/src/layers/shift_layer.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/src/op_inf_engine.hpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_precomp.hpp

* Removed convolution weights duplication for Intel's Inference Engine backend.
Comparison of efficiency (median times):
<cut/>
| Test model      | master |  refactored fusion | refactored fusion vs master (x-factor) |
| AlexNet                           | 12.117  |   11.981     | 1.01   |
| DenseNet_121                      | 28.104  |   28.112     | 1.00   |
| GoogLeNet                         |  8.899  |   8.920      | 1.00   |
| Inception_v2_SSD_TensorFlow       | 37.372  |   37.259     | 1.00   |
| MobileNet_SSD_Caffe               |  8.876  |   8.958      | 0.99   |
| MobileNet_SSD_TensorFlow          | 17.078  |   16.793     | 1.02   |
| OpenFace                          |  2.633  |   2.625      | 1.00   |
| OpenPose_pose_coco                | 543.860  | 543.942 …

OpenCL GPU target for Inference Engine deep learning backend

---

modules/imgproc/src/imgwarp.cpp
modules/imgproc/test/test_imgwarp_strict.cpp

warpAffine accuracy test error tolerance set to zero for CV_8U

Updated warpAffine test to ensure bit-exactness for CV_8U

---

modules/core/include/opencv2/core/base.hpp
modules/core/include/opencv2/core/check.hpp
modules/core/src/check.cpp
modules/core/src/system.cpp
modules/core/test/test_misc.cpp

Proposal basics only without massive code changes.
<cut>
<details>
<summary>Proposal details</summary>
* Name: Check macros *for passed parameters validation or internal checks*
* Status: **Draft**
* Platforms: **All**
* Complexity: N/A
Current error reporting in OpenCV should be improved. There are a lot of complex "assertion" conditions, which are hard to understand without debugging (if debugging is possible and problem can be easily reproduced).
Informative error reporting should provide better experience for OpenCV users / developers.
Using of simple conditions with dumping of current values of checked parameters would significantly help to understand that wrong is happened.
None. Existed interfaces are preserved.
Debugging
- #9293
</details>
- `CV_CheckSizeEQ(value1, value2, …

core: add "check" macros

---

modules/dnn/src/layers/layers_common.cpp

Fix hyper-parameters parsing in case of repeated `kernel_size` or `pad` or `stride` from Caffe's `convolution_param`.
https://github.com/opencv/opencv/blob/10ba6a93a6fee952fb7812b28989eb209d4f49a1/modules/dnn/src/caffe/opencv-caffe.proto#L727-L731
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/457
related: http://answers.opencv.org/question/187725/when-loading-caffe-vgg-16-i-get-error-215-idx-1-size-1-idx-0-idx-size-in-function-get/
```
```

Parse repeated values of ConvolutionParameter

---

CMakeLists.txt
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/core/include/opencv2/core/vsx_utils.hpp

* remove unnecessary defines from vsx_utils
* fix v_load_expand, load lower 64bit
* use vec_ld, vec_st with alignment load/store on all types except 64bit
* map v_extract to v_rotate_right
* update license header
* enable VSX by default on clang since #11167
````
````

core:ppc Several improvements on VSX(1)

---

modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/drawing.cpp

use of InputOutputArray instead of Mat
```
buildworker:Linux x64=linux-1
```

Update the function rectangle

---

modules/dnn/perf/perf_net.cpp
modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/region_layer.cpp
modules/dnn/src/layers/resize_nearest_neighbor_layer.cpp
modules/dnn/test/test_darknet_importer.cpp
samples/dnn/object_detection.cpp
samples/dnn/object_detection.py

YOLOv3 support
resolves https://github.com/opencv/opencv/issues/11310
Efficiency measurements:
| Backend, Target | Median time per `416x416` image |
|---|---|
| `DNN_BACKEND_DEFAULT`, `DNN_TARGET_CPU` | 216.11ms |
| `DNN_BACKEND_DEFAULT`, `DNN_TARGET_OPENCL` | 353.77ms |
CPU: Intel&reg; Core&trade; i7-6700K CPU @ 4.00GHz x 8
GPU: Intel&reg; HD Graphics 530 (Skylake GT2)
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/459

YOLOv3 support

---

cmake/OpenCVCompilerOptimizations.cmake
modules/core/include/opencv2/core/cv_cpu_helper.h
modules/core/src/convert.cpp

Reproducer:
```
cmake -DCPU_BASELINE=AVX2 -DCV_DISABLE_OPTIMIZATION=ON ...
```
This build configuration is used to measure "compiler" optimizations on C++ code without manual intrinsic/vectorized code.
Related: #8899
```
buildworker:Linux x64=linux-2
```

core: fix FP16 conversion with CV_DISABLE_OPTIMIZATION option

---

modules/imgproc/src/color_hsv.cpp

I add the universal intrinsics for RGB2HLS_f().
```
```
<tr><th>srccn</th><th>n</th><th>Average Clocks (original code)</th><th>Average Clocks (new code)</th><th>Faster Rate (compared with original code)</th></tr>
<tr><td>3</td><td>24</td><td>663.4</td><td>660.2</td><td>100.5%</td></tr>
<tr><td>3</td><td>48</td><td>1286.6</td><td>1301.0</td><td> 98.9%</td></tr>
<tr><td>3</td><td>72</td><td>1991.8</td><td>1959.0</td><td>101.7%</td></tr>
<tr><td>4</td><td>24</td><td>687.6</td><td>691.2</td><td> 99.5%</td></tr>
<tr><td>4</td><td>48</td><td>1340.2</td><td>1345.6</td><td> 99.6%</td></tr>
<tr><td>4</td><td>72</td><td>1957.4</td><td>1967.4</td><td> 99.5%</td></tr>
</table>
OS : Ubuntu 17.10 …

add universal intrinsics for RGB2HLS_f

---

modules/core/include/opencv2/core/base.hpp

`CV_ErrorNoReturn` macro is deprecated in OpenCV code

core: CV_Error is marked as 'noreturn'

---

3rdparty/carotene/hal/tegra_hal.hpp
modules/imgproc/test/ocl/test_warp.cpp
modules/ts/include/opencv2/ts/ocl_test.hpp

* clean up the source code
* remove unused variable (eps)
* remove unused member function (Near)
* restore resize of carotene
* resolves #10871 
* As mainly described in #10871, ```opencv_test_imgproc``` was failing on ARM + GPU OpenCL platform.
* TinkerBoard (Arm Cortex A17 + Mali-T760)
* ODROID-XU4 (Arm Cortex A15 + A7 + Mali-T628)
* Firefly RK3399 (Arm Cortex A53 + Mali-T860)
* This was due to the rounding error, and the difference was relatively small, yet going over the ```eps```
* This PR adds comparison macro ```OCL_EXPECT_MAT_N_DIFF``` which counts the number of pixel which differs more than ```eps```
* Carotene implementation can now be stored back.

ARM: add new comparison to tolerate with rounding error

---

modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/core/test/test_intrin.cpp

resolve #11242 
replaces #11290 (11290 contains C++11 stuff)
Intrinsics v_extract, v_rotate improvement (remove type restrictions on SSE2 (128), use PALIGNR on SSSE3, compile to no-op when imm is 0 or nlanes). Updated tests and docs.
Should be C++98 clean, although I don't have a way to verify.
```
```

Issue 11242 (intrinsics v_extract...) branch 3.4, without C++11

---

modules/core/src/arithm.cpp

core: add a check for empty input in inRange()

---

modules/imgproc/src/morph.cpp

resolves #11296
Hotfix for IPP morphology crash on big images. 
Cause: internal error with integer overflow. IPP >= 2018 should work fine.

IPP morphology with big images hotfix.

---

modules/core/src/system.cpp

To dump contents of the last OpenCV error.
Related #11357

core: CV_Error with set_terminate() on Windows

---

cmake/OpenCVCompilerOptimizations.cmake
cmake/checks/cpu_popcnt.cpp

Compiler suggests SSE4.1 instructions on Mac mini (Late 2014 + macOS 10.13.3):
```
$ echo | clang -dM -E - | grep SSE
#define __SSE2_MATH__ 1
#define __SSE2__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE_MATH__ 1
#define __SSE__ 1
#define __SSSE3__ 1
```
```
```

cmake: change CPU_BASELINE=DETECT for MacOSX

---

modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/perf/perf_mat.cpp
modules/core/src/copy.cpp
modules/core/test/test_intrin_utils.hpp

Make `v_select()` eliment-wise (instead of bit-wise).
`v_select()` `mask` is restricted to these values only: `0` or `~0` (`0xff`/`0xffff`/etc)
`mask` in accuracy test is updated.
Requires build option: `cmake -DCPU_BASELINE=SSE4_1 ...`
Similar semantic is available in OpenCL: https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/select.html

core(hal): improve v_select() SSE4.1+

---

modules/imgproc/src/fixedpoint.inl.hpp

resolves #11393 
resolves #11330 
```
```

imgproc: fix fixedpoint

---

modules/core/src/parallel.cpp

std::exception_ptr requires enabled C++11 mode
resolves #11393 (part 2)

core: fix Intel Compiler std::exception_ptr detection

---

modules/core/src/norm.cpp

for cv::Mat with type=16UC3 and width < 16
related #11400
resolves #11399
```
buildworker:Linux x64=linux-3
```

core: disabled IPP AVX512 normL1(a, b, mask)

---

modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/mat.inl.hpp
modules/stitching/include/opencv2/stitching/detail/blenders.hpp
modules/stitching/src/blenders.cpp
modules/stitching/test/test_blenders.cuda.cpp

Blending using CUDA has been optimized quite a bit. New use case made possible. When blending multiple stitches from source images in which positions, ROIs and masks don't change in between stitches, e.g. when blending multiple video streams together from a set camera rig, some unnecessary recalculation and reinitialization is not done if not calling prepare in between the blends. This way one can call prepare once and after that call feed and blend over again if one doesn't want to change position, ROI or masks of the source images.
Another addition is that the blend function accepts GpuMat as destination InputOutputArray. If GpuMat is provided the images won't be downloaded from the GPU during blending and can be used for something else on the GPU right after.
On my computer with Intel …

Optimize MultiBandBlender to run faster

---

modules/core/include/opencv2/core/cvstd.inl.hpp
modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/mat.inl.hpp
modules/dnn/include/opencv2/dnn/shape_utils.hpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/op_halide.cpp

to avoid accessing of 'p[-1]' (static code analysers dislike this)

core: added MatSize::dims() method

---

modules/dnn/src/layers/elementwise_layers.cpp

fix bug that:
when use intel inference engine,the relu activation ：
max(0,x)+negative_slope×min(0,x)
in darknet ,the negative_slope is eq 0.1, but this value doesn't pass to inferenceengin.

FIX INF_ENGINE RELU ERROR

---

modules/core/include/opencv2/core/operations.hpp

`Matx<_Tp,m,n>::inv()` does not compile if `m != n`

fix bug in Matx::inv()

---

modules/videoio/src/cap_ffmpeg_impl.hpp

Allow to force the video codec when reading a video using FFMpeg backend
resolves #11480

Fixes 11480 : allow to force the video codec used to read videos

---

modules/cudafilters/src/cuda/column_filter.hpp
modules/cudafilters/src/cuda/row_filter.hpp
modules/cudaimgproc/src/canny.cpp
modules/cudaimgproc/src/cuda/canny.cu
modules/cudaimgproc/test/test_canny.cpp

Current implementation of CUDA Canny algorithm is not safe for concurrent execution with multiple streams for several reasons:
* There are several device variables that are declared as global which results in a race condition(`canny::counter`, `column_filter::c_kernel`, `row_filter::c_kernel`)
* Texture references `canny::tex_src` and `canny::tex_mag` are used and since texture references must be declared as static global variables, this results in a race condition
This PR fixes these issues by 1) converting global variables to class local variables, and 2) using texture objects instead of texture references when cc >= 3.0.
A new test suite `CUDA_ImgProc/Canny.Async` is introduced to check multi stream safety. This test fails if above issues are not handled. This test is disabled for cc < …

cuda_canny : multi stream safety

---

modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/test/test_intrin.cpp

'0' is specific case (make no sence as a standalone operation),
but it can be useful in template-based programming.
reverts commit: a58c9d4d630926ed81beda1a8f7f8ec52165949e
related #11474

core: fix ARM intrinsincs (v_rotate_left<0>)

---

modules/imgproc/src/color_hsv.cpp

I add universal intrinsics for RGB2HSV_f.
<br>
```
```
<br>
Intel measurement result
<tr><th>srccn</th><th>n</th><th>Average Clocks (original code)</th><th>Average Clocks (new code)</th><th>Faster Rate (compared with original code)</th></tr>
<tr><td>3</td><td>24</td><td>1744.2</td><td>596.2</td><td>292.6%</td></tr>
<tr><td>3</td><td>48</td><td>3424.0</td><td>1167.0</td><td>293.4%</td></tr>
<tr><td>3</td><td>72</td><td>5099.4</td><td>1699.4</td><td>300.1%</td></tr>
<tr><td>4</td><td>24</td><td>1743.2</td><td>647.6</td><td>269.2%</td></tr>
<tr><td>4</td><td>48</td><td>3474.4</td><td>1241.8</td><td>279.8%</td></tr>
<tr><td>4</td><td>72</td><td>5091.0</td><td>1870.8</td><td>272.1%</td></tr>
</table>
Measurement …

add universal intrinsics for RGB2HSV_f

---

modules/dnn/src/caffe/caffe_importer.cpp
modules/dnn/src/caffe/caffe_io.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/src/tensorflow/tf_graph_simplifier.hpp
modules/dnn/src/tensorflow/tf_importer.cpp

* Replace double precision weights introduced at https://github.com/opencv/opencv/pull/10821 to fusion multipliers.
* Avoid Caffe weights copying during network upgrade.
* Release weights memory after parsing protobuf layer (Caffe and TensorFlow importers).
Maximum resident size for a single image forward pass according to `/usr/bin/time --verbose`:
(Importer) Network | Weights (MB) | output/internal blobs (MB) | Import + forward (MB)<br>current | Import + forward (MB)<br>PR | X-factor<br>(PR vs. current)
-- | -- | -- | -- | -- | --
(Caffe) AlexNet | 233 | 3.4 | 726 | 398 | 0.5482093664
(Caffe) GoogLeNet | 52 | 14.9 | 169 | 81.7 | 0.4834319527
(Caffe) ResNet-50 | 98 | 12.6 | 404 | 221.7 | 0.5487623762
(Caffe) SqueezeNet v1.1 | 4.8 | 8.35 | 45 | 34.7 | 0.7711111111
(Caffe) MobileNet-SSD | …

Reduce dnn top memory consumption

---

modules/ml/src/knearest.cpp

resolves #11450
cache previous impl state vars, like defaultK, Emax, isClassifier, and set them again after creating a new impl object

ml: fix internal state when changing the impl in KNearest

---

platforms/android/build_sdk.py
platforms/js/build_js.py

Invalid Python string formatting into valid Python string formatting.  The current lines will raise [NameError](https://docs.python.org/3/library/exceptions.html#NameError) on 's' instead of raising the expected __Fail()__.
Also removed a couple of superfluous trailing semicolons.  (Python != JavaScript)
Discovered via flake8 testing of https://github.com/opencv/opencv
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./platforms/android/build_sdk.py:21:59: F821 undefined name 's'
raise Fail("Child was terminated by signal:" %s -retcode)
^
./platforms/js/build_js.py:17:59: F821 undefined name 's'
raise Fail("Child was terminated by signal:" %s -retcode)
^
```

Fix Python string formatting

---

modules/ts/misc/table_formatter.py

__ridx__ is an _undefined name_ in this context but __self.ridx__ is used three other times in this method and nine times in this class.  Undefined names may raise [NameError](https://docs.python.org/3/library/exceptions.html#NameError) at runtime.
flake8 testing of https://github.com/opencv/opencv
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./modules/ts/misc/table_formatter.py:50:23: F821 undefined name 'ridx'
self.rows[ridx + 1].props = properties
^
```

Don't forget self in table_formatter.py

---

doc/pattern_tools/svgfig.py
modules/dnn/test/imagenet_cls_test_alexnet.py
modules/ts/misc/trace_profiler.py
samples/python/_doc.py
samples/python/demo.py
samples/python/tutorial_code/core/AddingImages/adding_images.py

__execfile, file, long, raw_input, xrange__ were all removed in Python 3 so this PR defines them using the Python porting best practice [use feature detection instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection) which saves on imports and placates linters like PyLint and flake8.
flake8 testing of https://github.com/opencv/opencv on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./doc/pattern_tools/svgfig.py:603:24: F821 undefined name 'file'
return load_stream(file(fileName))
^
./doc/pattern_tools/svgfig.py:1914:22: F821 undefined name 'xrange'
for i in xrange(len(self.d)):
^
./doc/pattern_tools/svgfig.py:2861:22: F821 undefined name 'xrange'
for i in …
```

Define execfile, file, long, raw_input, xrange for Python 3

---

samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/Utils.cpp

resolves #11313 
Clarify the Euler angles convention and add reference links. Replace matrix inverse with matrix transpose for rotation matrix.
---
Validation code:
```
#include <iomanip>
#include <opencv2/core.hpp>
#include <opencv2/calib3d.hpp>
namespace {
// Converts a given Rotation Matrix to Euler angles
// Convention used is Y-Z-X Tait-Bryan angles
// Reference code implementation:
// https://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToEuler/index.htm
cv::Mat rot2euler(const cv::Mat & rotationMatrix)
{
cv::Mat euler(3,1,CV_64F);
double m00 = rotationMatrix.at<double>(0,0);
double m02 = rotationMatrix.at<double>(0,2);
double m10 = rotationMatrix.at<double>(1,0);
double m11 = rotationMatrix.at<double>(1,1);
double m12 = …
```

Clarify Euler angles convention in tutorial Real Time pose estimation of a textured object

---

modules/core/include/opencv2/core/cuda.hpp
modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/mat.inl.hpp
modules/core/misc/java/src/java/core+Mat.java
modules/core/misc/java/test/MatTest.java
modules/core/src/cuda_gpu_mat.cpp
modules/core/src/cuda_host_mem.cpp
modules/core/src/matrix.cpp
modules/core/src/matrix_c.cpp
modules/core/src/ocl.cpp
modules/core/src/precomp.hpp
modules/core/src/umatrix.cpp
modules/imgproc/test/test_thresh.cpp

make sure that the matrix with more than `INT_MAX` elements is marked as non-continuous, and thus all the pixel-wise functions process it correctly (i.e. row-by-row, not as a single row, where integer overflow may occur when computing the total number of elements).
resolves #10211
```
```

handle huge matrices correctly

---

modules/cudaarithm/src/reductions.cpp

Without this fix, following tests in opencv_test_cudaarithm will fail.
CUDA_Arithm/MeanStdDev.Accuracy
CUDA_Arithm/MeanStdDev.Async
`_dst.getGpuMat()` gives error when `_dst` is a `HostMem` whose `alloc_type` is not `SHARED`. More general approach is needed that covers various types of `_dst`.
This PR reverts a small part of f4e5d77.
```
```

cuda_meanStdDev : bug fix

---

modules/gpu/include/opencv2/gpu/gpu.hpp
modules/gpu/perf/perf_video.cpp
modules/gpu/src/cuda/pyrlk.cu
modules/gpu/src/pyrlk.cpp
modules/gpu/test/test_optflow.cpp

Issue: The function sparse of cv::gpu::PyrLKOpticalFlow class isn't thread-safe.
Resolution: This modification permits to call this function from different CPU threads and to use CUDA texture resources in 5 parallel execution lines. Critical section is also managed in this function (TBB intel*). In the future a dense function thread-safe version can be made.
Best regards
Juan María Gómez López
*Fixed: (first version used posix threads)
```
buildworker:Linux x64=linux-1
buildworker:Linux x64 Debug=linux-1
```

Thread-safe version of sparse function in cv::gpu::PyrLKOpticalFlow

---

modules/core/test/test_io.cpp
modules/core/test/test_mat.cpp
modules/imgproc/test/test_thresh.cpp
modules/ts/include/opencv2/ts/ts_ext.hpp
modules/ts/src/ts.cpp

Tests which use a large amount of memory 2+Gb (up to 14Gb).
- skipped by default
- Use `--test_bigdata` to allow launching of "BigData" tests.
related #11505
**Note**: Do not perform massive port of existed accuracy tests with different input types / multiple sizes.
Only simple, quite fast (up to 5-20 seconds), non-parametric (exact single flow), "regression" tests from fixed issues are allowed here.
```
```

tests: "Big data" tests category

---

modules/imgproc/src/connectedcomponents.cpp

fix wrong indentation on github page.
(tab => space)

fix wrong indentation on github page (tab to space)

---

modules/core/include/opencv2/core/private.cuda.hpp

related to #11063 #11064 
At last I got rid of unknown test failure of ```opencv_test_cudaarithm``` on each Jetson.

cuda: fix the test failure of CUDA_Arithm/MeanStdDev

---

cmake/OpenCVDetectCUDA.cmake

resolves #11552
- remove `-Wimplicit-fallthrough`
- remove custom options, specified via `OPENCV_CUDA_NVCC_FILTEROUT_OPTIONS` variable
```
```

cmake: filter NVCC compiler flags

---

modules/imgcodecs/src/loadsave.cpp
modules/imgcodecs/test/test_grfmt.cpp

resolves #11545
related #11548
```
```

 imgcodecs: fix imwrite handling of different OutputArray types

---

modules/core/include/opencv2/core/private.cuda.hpp

The destructor of NppStreamHandler should rollback NPP stream.
Without this fix, following tests in opencv_test_cudaimgproc fail.
CUDA_ImgProc/EqualizeHist.Async/1
CUDA_ImgProc/EqualizeHist.Accuracy/0
CUDA_ImgProc/EqualizeHist.Accuracy/1
Test environment:
* Branch: 3.4
* OS/Platform: Windows10/CUDA8.0
* GPU: GTX1080

NPP : NppStreamHandler fix

---

modules/videoio/src/cap_gstreamer.cpp

Looks like that `gst_sample_ref` was not needed.
See #5715 for details.
```
docker_image:Linux x64 Debug=gstreamer:16.04
docker_image:Custom=gstreamer:14.04
```

GStreamer backend: fixed memory leak and version check

---

modules/calib3d/src/calibration.cpp

resolves #11579
This is a bugfix as identified in #11579. 
I don't have time to write tests for this right now, but these should be written as suggested in the issue thread.

Bugfix to allow adjust3rdMatrix to be run

---

apps/interactive-calibration/frameProcessor.cpp

Size accessor raises errors in debug mode with empty cv::Mat.

interactive-calibration: use empty() method instead of checking dimension size

---

samples/dnn/tf_text_graph_ssd.py

Fix batch normalization subgraphs fusion.
resolves https://github.com/opencv/opencv/issues/11560
tested with 
[ssd_mobilenet_v1_coco_2017_11_17](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_17.tar.gz)
[ssd_mobilenet_v2_coco_2018_03_29](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz)
[ssd_inception_v2_coco_2017_11_17](http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2017_11_17.tar.gz)
from [TensorFlow Object Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)

Fix batch normalization fusion from TensorFlow's SSDs

---

modules/photo/src/merge.cpp

- leads to errors due 'const' modifier of getMat() method
- may be non-optimal with non-CPU data storage

avoid copyTo(outputarray.getMat()) coding pattern

---

samples/java/tutorial_code/ImgProc/erosion_dilatation/MorphologyDemo1.java
samples/java/tutorial_code/ImgProc/opening_closing_hats/MorphologyDemo2.java
samples/java/tutorial_code/ImgProc/tutorial_template_matching/MatchTemplateDemo.java

Use `HighGui.toBufferedImage()` instead.
Auto-format `MatchTemplateDemo.java` with Eclipse.

Remove custom toBufferedImage Java code in Java tutorials

---

modules/calib3d/src/calibinit.cpp

avoid image modification by cvFindContours()
Only adaptive mode works as expected (CV_CALIB_CB_ADAPTIVE_THRESH flag).
<cut>
Next iterations don't work as expected:
- new binarization:
`dilate(thresh_img_new, thresh_img_new, Mat(), Point(-1, -1), 1);` expects unmodified image
- old binarization:
- adaptiveThreshold is fine (reuses 'img' directly)
- without adaptiveThreshold:
`dilate(thresh_img, thresh_img, Mat(), Point(-1, -1), 1);` expects unmodified image

calib3d: chess board detector - avoid image modification by cvFindContours

---

modules/calib3d/src/calibinit.cpp

Problem can be detected without `if (iCntMaxima == 0)` handling code:
- `cmake -DENABLE_GNU_STL_DEBUG=ON ...`
- or MSVC debug builds

calib3d: chess board - properly detect/handle iCntMaxima=0 case

---

modules/core/include/opencv2/core/cvdef.h
modules/highgui/include/opencv2/highgui/highgui_c.h

- cvdef.h + cvRound (double only)
- highgui_c.h
fixes build: #10963
**Note**: There is no official support for C compilation mode (no automatic builds, no tests). This API just "keep" names for old programs which should be compiled with C++ compiler.
Since OpenCV 2.4.x (>5 years).

build: workaround issues with C compilation mode

---

modules/videoio/src/cap_ffmpeg_impl.hpp
modules/videoio/test/test_ffmpeg.cpp

Using `codec->time_base` is deprecated to specify muxer settings.
Resolves issue with FPS value for AVI files with FFmpeg 4.0.
resolves #11602
Related FFmpeg commits:
- https://github.com/FFmpeg/FFmpeg/commit/194be1f43ea391eb986732707435176e579265aa
- https://github.com/FFmpeg/FFmpeg/commit/91736025b2807995e29bd0661807c1c84f515fef
```
docker_image:Custom=ffmpeg-master
#docker_image:Custom=fedora:28
```
Probably related to #6905

videoio(ffmpeg): specify stream->time_base

---

modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/layers/mvn_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/opencl/mvn.cl
modules/dnn/test/test_tf_importer.cpp

related #11494 #11397 #10639 #10717
I realized that ocl4dnn kernel only works on Intel GPU.
I wrote a workaround in #11494 but the root of the cause was two points.
1. The kernel was using platform dependent behaviour of ```native_powr```
2. The fallback process when OpenCL failed on runtime, was doing wrong normalization
* I confirmed that ```Test_TensorFlow_layers.batch_norm``` and ```Test_TensorFlow_layers.pooling``` passes only on Intel GPU
* PASS : Intel GPU
* FAILURE: Intel CPU, NVIDIA Geforce, Arm Mali
* I digged in for a while and realized that after calculating the mean using OpenCL kernel, some of the elements became ```NaN```
* I googled a lot and realized that [this line](https://github.com/opencv/opencv/blob/6aec71d7ee02955d781ef57126693ec674976076/modules/dnn/src/opencl/mvn.c …

dnn: relax intel only ocl4 dnn

---

modules/videoio/src/cap_ffmpeg_impl.hpp

via `OPENCV_FFMPEG_DEBUG` environment variable.
<cut>
<details>
<summary>Output example</summary>
```
OpenCV: FFMPEG: tag 0x34363248/'H264' is not supported with codec id 27 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
[OPENCV:FFMPEG:48] using mv_range_thread = 184
[OPENCV:FFMPEG:32] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[OPENCV:FFMPEG:32] profile High, level 5.1
[OPENCV:FFMPEG:32] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 …
```

videoio(ffmpeg): add option to enable debug logs

---

cmake/OpenCVDetectInferenceEngine.cmake
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/perf/perf_net.cpp
modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/layers/prior_box_layer.cpp
modules/dnn/src/layers/region_layer.cpp
modules/dnn/src/layers/resize_nearest_neighbor_layer.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/src/op_inf_engine.hpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_common.hpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_precomp.hpp
samples/dnn/classification.cpp
samples/dnn/classification.py
samples/dnn/object_detection.cpp
samples/dnn/object_detection.py
samples/dnn/segmentation.cpp
samples/dnn/segmentation.py

* Update Intel's Inference Engine backend support ([OpenVINO](https://software.intel.com/openvino-toolkit)). (This PR is not compatible with beta releases of Inference Engine).
* Intel&reg; Movidius&trade; Neural Compute Stick computational target (`DNN_TARGET_MYRIAD`)
Measured efficiency in milliseconds (median times):
Model name | CV CPU | CV GPU, fp32 | CV GPU, fp16 | IE CPU | IE GPU, fp32 | IE GPU, fp16 | IE NCS | 
---|---|---|---|---|---|---|---
AlexNet                           | 13.896  |   17.253 |   11.999 |  11.784 |  12.074 |   8.554 | 82.426 |
DenseNet_121                      | 53.407  |   92.322 |  114.797 |  27.770 |  60.182 |   ---- | --- |
ENet                              | 43.899  |   45.791 |     ---  |     ---  |     --- |  ---- | --- |
GoogLeNet …

Update Intel's Inference Engine deep learning backend

---

modules/python/src2/cv2.cpp
modules/python/src2/gen2.py

Eliminates warnings like these (GCC 8):
> warning: cast between incompatible function types from 'PyObject* (*)(PyObject*, PyObject*, PyObject*)' {aka '_object* (*)(_object*, _object*, _object*)'} to 'PyCFunction' {aka '_object* (*)(_object*, _object*)'} [-Wcast-function-type]
related #11626
```
```

python: avoid direct cast PyCFunctionWithKeywords->PyCFunction

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_layers.cpp

Request output blob by a base layer name but not the reference layer which can be fused.

Fix Inference Engine graphs with fused output layers

---

modules/gpu/src/cuda/pyrlk.cu
samples/gpu/pyrlk_optical_flow_multithreading.cpp

Thread-safe version of sparse function in cv::gpu::PyrLKOpticalFlow 2
<cut>
This pullrequest is the continuation of the pullrequest (Thread-safe version of sparse function in cv::gpu::PyrLKOpticalFlow #11060 ), in order to add an example and fix a possible link error in the library libopencv_gpu
- Include header cvconfig.h in order to define (if it's necessary) HAVE_TBB macro in pyrlk.cu. 
- Add example of thread safe version of gpu::pyrlk::sparse function in:
samples/gpu/pyrlk_optical_flow_multithreading.cpp
Best regards
Juan María Gómez López
```
buildworker:Linux x64=linux-1
buildworker:Linux x64 Debug=linux-1
#with_tbb=ON
```

Thread-safe version of sparse function in cv::gpu::PyrLKOpticalFlow 2

---

modules/highgui/src/cap_ffmpeg_impl.hpp
modules/highgui/test/test_ffmpeg.cpp

backport #11617
FFmpeg 4.0 support
```
```

(2.4) videoio(ffmpeg): specify stream->time_base

---

modules/calib3d/src/calibinit.cpp

calib3d: cv::findContours() doesn't require to clone input

---

modules/calib3d/src/ptsetreg.cpp

I refactored out a dead code path in the RANSAC code. `checkPartialSubsets` was being set to `false` in the constructor and then never changed.

calib3d: Refactored out a dead code path.

---

CMakeLists.txt

cmake: ENABLE_PRECOMPILED_HEADERS for MSVC cross-compiling

---

doc/tutorials/core/adding_images/adding_images.markdown
doc/tutorials/core/basic_geometric_drawing/basic_geometric_drawing.markdown
doc/tutorials/core/basic_linear_transform/basic_linear_transform.markdown
doc/tutorials/core/discrete_fourier_transform/discrete_fourier_transform.markdown
doc/tutorials/core/how_to_use_OpenCV_parallel_for_/how_to_use_OpenCV_parallel_for_.markdown
doc/tutorials/core/mat-mask-operations/mat_mask_operations.markdown
doc/tutorials/dnn/dnn_googlenet/dnn_googlenet.markdown
doc/tutorials/dnn/dnn_yolo/dnn_yolo.markdown
doc/tutorials/imgproc/gausian_median_blur_bilateral_filter/gausian_median_blur_bilateral_filter.markdown
doc/tutorials/imgproc/hitOrMiss/hitOrMiss.markdown
doc/tutorials/imgproc/imgtrans/copyMakeBorder/copyMakeBorder.markdown
doc/tutorials/imgproc/imgtrans/filter_2d/filter_2d.markdown
doc/tutorials/imgproc/imgtrans/hough_circle/hough_circle.markdown
doc/tutorials/imgproc/imgtrans/hough_lines/hough_lines.markdown
doc/tutorials/imgproc/imgtrans/laplace_operator/laplace_operator.markdown
doc/tutorials/imgproc/imgtrans/sobel_derivatives/sobel_derivatives.markdown
doc/tutorials/imgproc/imgtrans/warp_affine/warp_affine.markdown
doc/tutorials/imgproc/morph_lines_detection/morph_lines_detection.md
doc/tutorials/imgproc/pyramids/pyramids.markdown
modules/dnn/test/pascal_semsegm_test_fcn.py
samples/dnn/README.md
samples/dnn/js_face_recognition.html

Other links:
- https://raw.githubusercontent.com/opencv/opencv/master
- https://github.com/opencv/opencv/blob/master
related #11638

documentation: avoid links to 'master' branch from 3.4 maintenance branch (2)

---

modules/viz/include/opencv2/viz/viz3d.hpp
modules/viz/src/viz3d.cpp

`Viz3d::getViewerPose()` method made const

Minor fix for Viz3d

---

modules/calib3d/src/stereobm.cpp
modules/calib3d/test/test_stereomatching.cpp

A check is not done before `findStereoCorrespondenceBM_SIMD` call whether outputting array should contain shorts or ints.
* A type of output disparity array is passed now through template parameter.
* Test modified to cover the case

StereoBM: fixed SIMD processing for fixed-type output arrays

---

modules/dnn/test/test_precomp.hpp
modules/ts/include/opencv2/ts/ts_gtest.h
modules/ts/src/ts_gtest.cpp

related #11626
<cut>
Eliminates warnings like these:
> modules/ts/include/opencv2/ts/ts_gtest.h:11547:7: warning: 'testing::internal::ParameterizedTestFactory<opencv_test::ocl::OCL_ThreshFixture_Threshold_Threshold_Test>' has a field 'testing::internal::ParameterizedTestFactory<opencv_test::ocl::OCL_ThreshFixture_Threshold_Threshold_Test>::parameter_' whose type uses the anonymous namespace [-Wsubobject-linkage]
Make global variable for `WithParamInterface<T>::parameter_` due issues with using of anonymous namespace in `T`.
```
```

ts: support parameters with types from anonymous namespace

---

doc/tools/html_functions.py

Beautiful Soup (bs4) preserves white space symbols in `<pre>` tags only.
We need to preserve for `<div>` tags too.
resolves #11597

docs: preserve space symbols during bs4 processing

---

modules/core/src/logger.cpp

should hide unnecessary 'info' messages

core: set default logger level to 'warning'

---

modules/dnn/perf/perf_net.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/test/test_backends.cpp

* Wrap some of Inference Engine functions with try-catch.
* Remove OpenCL->CPU target fallback from `setPreferableTarget` to `setUpNet` (do it only for OpenCV's layers implementation). So the question is should we allow to run Inference Engine networks on GPU if OpenCL is disabled for the rest of OpenCV?

Wrap Inference Engine init to try-catch

---

apps/interactive-calibration/main.cpp

related #11626 
> apps/interactive-calibration/main.cpp:220:31: warning: catching polymorphic type 'class std::runtime_error' by value [-Wcatch-value=]
```
```

apps: catch() with "const reference"

---

samples/tapi/clahe.cpp

related #11626 
> samples/tapi/clahe.cpp:52:75: warning: cast between incompatible function types from 'void (*)(int)' to 'cv::TrackbarCallback' {aka 'void (*)(int, void*)'} [-Wcast-function-type]
> samples/tapi/clahe.cpp:53:77: warning: cast between incompatible function types from 'void (*)(int)' to 'cv::TrackbarCallback' {aka 'void (*)(int, void*)'} [-Wcast-function-type]
```
```

samples: fix callback function type

---

modules/core/misc/java/test/CoreTest.java
modules/core/src/system.cpp

resolves #11676 
````
````
options for alternative buildbot for powerpc
https://ocv-power.imavr.com/#/opencv_pullrequests
````
pw_compilers=gcc-4.9, gcc-5, gcc-6, clang-4
pw_disable_tests=rgbd, shape
#pw_cmake_definitions=OPENCV_EXTRA_MODULES_PATH:OFF
###
#pw_disable_perf_tests=*
#pw_filter_tests=core:*Mahalanobis*, java
````

core:ppc Fix java CoreTest/testMahalanobis

---

modules/imgproc/src/morph.cpp
modules/imgproc/test/test_filter.cpp

resolves #11612
Fixed erosion processing in MORPH_HITMISS in case one of provided subkernels is zero

Fix for morphologyEx MORPH_HITMISS mode

---

cmake/OpenCVDetectPython.cmake
modules/python/CMakeLists.txt
modules/python/bindings/CMakeLists.txt
modules/python/common.cmake
modules/python/python2/CMakeLists.txt
modules/python/python3/CMakeLists.txt
modules/python/standalone.cmake

- requires OpenCV source directory
- requires OpenCV binary directory with built modules and 'python_bindings_generator' target

Python: support standalone build of Python bindings

---

modules/dnn/perf/perf_net.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_layers.cpp
samples/dnn/tf_text_graph_ssd.py

* Enable OpenCL targets for SSD-based models from TensorFlow using Inference Engine backend.
OpenCV rebuild is not required. Just rerun a text graph generation script tf_text_graph_ssd.py
As result, extra reshape layers after prior box layers are added to final model.
* Add tests for new  MobileNet-SSD models from TensorFlow
Median time performance tests with previously generated graphs / new graphs: ~0.4ms slower in average.
|                  | MobileNet-SSD v1 | MobileNet-SSD v2 | Inception-SSD v2 |
|------------------|------------------|------------------|------------------|
| OCV, CPU         | 22.211 / 22.457  |  30.795 / 31.208 |  43.059 / 42.606  |
| OCV, GPU FP32 | 20.357 / 20.417  |  45.109 / 45.380 |  63.649 / 64.083  |
| OCV, GPU FP16 | 25.034 / 25.095  |  51.012 / 51.401 | …

SSDs from TenorFlow with OpenCL plugin of Inference Engine

---

cmake/OpenCVFindLibRealsense.cmake
modules/videoio/src/cap_librealsense.cpp
modules/videoio/src/cap_librealsense.hpp

this enables the usage of current sensors, while dropping support for
legacy devices, see:
https://github.com/IntelRealSense/librealsense#overview
Given limited resources, and that the legacy sensors where not that
great, I think we should focus on v2.

videoio: update librealsense to API 2.0

---

doc/tutorials/introduction/java_eclipse/java_eclipse.markdown

This solve the issue when using OpenCV java code that depends on Intel MKL (OpenCV is built with Intel MKL as a BLAS library).
Error on Ubuntu and using Eclipse IDE:
> Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
Can be solved by exporting the variable:
`export LD_PRELOAD=/opt/intel/mkl/lib/intel64/libmkl_core.so:/opt/intel/mkl/lib/intel64/libmkl_sequential.so`
Error should disappear when running Eclipse from a terminal that has this variable exported.

Add LD_PRELOAD instruction in Java Eclipse tutorial for Intel MKL dependency

---

modules/highgui/src/window_w32.cpp

- use `cv::getTickCount()` instead of Win32 `GetTickCount()`
- process message queue before timeout exit
> The resolution of the GetTickCount function is limited to the resolution of the system timer, which is typically in the range of 10 milliseconds to 16 milliseconds.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724408(v=vs.85).aspx
For example, `waitKey(30)` can exit by timeout after 20 ms on Win32.

highgui(win32): improve waitKey() timeout condition

---

modules/dnn/src/dnn.cpp

to control `DNN_BACKEND_DEFAULT` enumeration value behavior

dnn: add runtime parameter OPENCV_DNN_BACKEND_DEFAULT

---

modules/videoio/src/cap_msmf.cpp

`camid` value is always -1 after close().

videoio(msmf): fix reopen confition in configureHW()

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_torch_importer.cpp

If layer has several outputs (like a max pooling layer) - retrieve all of them by 
```cpp
/** @brief Runs forward pass to compute output of layer with name @p outputName.
*  @param outputBlobs contains all output blobs for specified layer.
*  @param outputName name for layer which output is needed to get
*  @details If @p outputName is empty, runs forward pass for the whole network.
*/
CV_WRAP void forward(OutputArrayOfArrays outputBlobs, const String& outputName = String());
```
but not by 
```cpp
/** @brief Runs forward pass to compute output of layer with name @p outputName.
*  @param outputName name for layer which output is needed to get
*  @return blob for first output of specified layer.
*  @details By default runs forward pass for the whole network.
*/
CV_WRAP Mat forward(const …
```

Remove undocumented feature of dnn's forward

---

modules/core/include/opencv2/core/types.hpp

Aspect ratio computation is often needed when working with images. This is a convenience function to reduce the amount of code needed
1. Do we actually want to extend core type functionality like this?
2. Should we handle ``height == 0``, e.g. by returning -1 ?
3. Which (other) assertions do we want to impose (cf. ``area()``)
4. Should we handle larger types ``_TP`` where ``static_cast<double>(height)`` will fail?

Added Size_::aspectRatio

---

3rdparty/carotene/hal/tegra_hal.hpp

When building OpenCV on Arm, there are too many warnings about override
```
/home/linaro/opencv-fork/build/carotene/tegra_hal.hpp:1534:18: warning: ‘virtual void TegraCvtColor_rgb2bgr_Invoker::operator()(const cv::Range&) const’ can be marked override [-Wsuggest-override]
virtual void operator()(const cv::Range& range) const \
^
/home/linaro/opencv-fork/build/carotene/tegra_hal.hpp:1547:1: note: in expansion of macro ‘TegraCvtColor_Invoker’
TegraCvtColor_Invoker(rgb2bgr, rgb2bgr, src_data + static_cast<size_t>(range.start) * src_step, src_step, \
^~~~~~~~~~~~~~~~~~~~~
```
I guess this PR should fix this.
I pasted my local build log [here](https://gist.github.com/tomoaki0705/7a88f856f4da9cc8cf4c531b13b36e59)
The diff is too large to show in the gist but the lines of the log has reduced …

Arm: suppress warning on Arm platform

---

samples/data/dnn/object_detection_classes_yolov3.txt

11 classes were dropped from the coco dataset, see arXiv:1405.0312v3 (Table2), so yolov3 has 80 classes, but [rcnn](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/faster_rcnn_inception_v2_coco_2018_01_28.pbtxt) still has the original 90, also fill blank names in object_detection_classes_coco.txt [from here](https://github.com/nightrome/cocostuff/blob/master/labels.md)

dnn: add a coco labels file for yolov3

---

modules/videoio/src/cap_openni2.cpp

* added support for Kinect 2 drivers (`libfreenect2` and `kinect2` branch of OpenNI2)
* IR sensor support added
* checking available video modes added (before setting pre-defined one)
* less exceptions in case of unsupported options (for example getting baseline and focal length is used in case of disparity map generation only, there's no need to throw exception in other cases)
* a little refactoring

Kinect2 support added to OpenNI2 backend

---

samples/cpp/videocapture_basic.cpp

To avoid `EBUSY` errors in samples (some cameras/backends may require delay after `release()` call)

samples: don't call twice of VideoCapture::open()

---

modules/dnn/CMakeLists.txt
modules/dnn/src/dnn.cpp

Did that since some of the tests fail. At some point, OpenCV DNN OpenCL branch will be expanded to support more generic OpenCL implementations; since OpenCL on Mac is a bit old and, e.g. does not support all the vendors extensions, like Intel extensions, some less sophisticated variant of kernels should be used there

temporarily disabled OpenCL use in DNN module on Mac

---

modules/videoio/src/cap_msmf.cpp

resolves #11780
Removed fallback to existing camera in case provided index is out of camera id range

Disable MSMF VideoCapture fallback to existing camera

---

modules/core/include/opencv2/core.hpp
modules/core/src/count_non_zero.cpp
modules/core/src/norm.cpp
modules/core/test/test_arithm.cpp

Thanks to Tetragramm for #11364. While the extended LUT maybe too much for OpenCV (I'd prefer to have smaller, [bi- or tri-]linearly or [bi- or tri-]cubically interpolated LUTs), findNonZero and PSNR parts are much lighter additions and might be useful

a part of PR #11364 (extended findNonZero & PSNR)

---

modules/dnn/test/test_backends.cpp
modules/dnn/test/test_common.hpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_layers.cpp

* Modify thresholds for some of OpenCL fp16 tests.
* Change Myriad plugin checker.
The following tests are failed with prebuilt **cpu_extension** library using MKL-DNN CPU plugin:
```
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] DNNTestNetwork.MobileNet_SSD_v1_TensorFlow/0, where GetParam() = (DNN_BACKEND_INFERENCE_ENGINE, DNN_TARGET_CPU)
[  FAILED  ] DNNTestNetwork.MobileNet_SSD_v2_TensorFlow/0, where GetParam() = (DNN_BACKEND_INFERENCE_ENGINE, DNN_TARGET_CPU)
[  FAILED  ] DNNTestNetwork.Inception_v2_SSD_TensorFlow/0, where GetParam() = (DNN_BACKEND_INFERENCE_ENGINE, DNN_TARGET_CPU)
```
read https://github.com/opencv/opencv/wiki/Intel's-Deep-Learning-Inference-Engine-backend#troubleshooting for a workaround.

Update Inference Engine tests

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_layers.cpp
samples/dnn/object_detection.cpp
samples/dnn/object_detection.py

* For models in Inference Engine's intermediate representation, set up output layers names and types. It's useful to determine output layers types in samples, i.e. object detection where postprocessing depends on it.
* Update object detection sample: apply NMS for an every type of outputs but not only for YOLOs (it's useful for models with multiple outputs or to regularize output for single models).

Fix DLDT models import

---

modules/dnn/src/dnn.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp
modules/dnn/src/ocl4dnn/src/ocl4dnn_pool.cpp
modules/dnn/src/opencl/ocl4dnn_pooling.cl

Set global size with real output size, 128x128 may waste some work items if total output is below 16384 (128x128)
```
force_builders=Docs,linux,ocllinux,windows,ocl,macosx,oclmacosx,linuxNoOpt
```

pooling ocl kernel optimization

---

modules/videoio/src/cap_msmf.cpp

build fails with MSVS 2010/2012 without additional flags

videoio(MSMF): avoid using of C++11 code

---

modules/imgcodecs/src/grfmt_sunras.cpp

`src_pitch` may be large than data `step`
resolves #11827

imgcodecs(sunras): avoid buffer overrun

---

modules/python/src2/cv2.cpp

The result of PyUnicode_AsUTF8() is now of type const char * rather of 
char *.
See
https://docs.python.org/3/whatsnew/3.7.html
https://bugs.python.org/issue28769

Python 3.7 compatability

---

modules/videoio/src/videoio_registry.cpp

Current implementation of VFW is not able to properly work with some cameras (black / grey frames are provided).
related #11810

videoio(VFW): lower priority (after DSHOW)

---

modules/core/include/opencv2/core/hal/intrin_sse.hpp

> intrin_sse.hpp:299:74: warning: extra ‘;’

core(hal): eliminate build warnings

---

modules/highgui/src/window_gtk.cpp

<cut>
Related warnings:
> /build/precommit_custom_linux/3.4/opencv/modules/highgui/src/window_gtk.cpp:497:28: warning: cast between incompatible function types from 'void (*)(CvImageWidgetClass*)' {aka 'void (*)(_CvImageWidgetClass*)'} to 'GClassInitFunc' {aka 'void (*)(void*, void*)'} [-Wcast-function-type]
/build/precommit_custom_linux/3.4/opencv/modules/highgui/src/window_gtk.cpp:499:31: warning: cast between incompatible function types from 'void (*)(CvImageWidget*)' {aka 'void (*)(_CvImageWidget*)'} to 'GInstanceInitFunc' {aka 'void (*)(_GTypeInstance*, void*)'} [-Wcast-function-type]
/build/precommit_custom_linux/3.4/opencv/modules/highgui/src/window_gtk.cpp:646:71: warning: cast between incompatible function types from 'void* (*)()' to 'GThreadFunc' {aka 'void* (*)(void*)'} …

fix function signatures, drop invalid casts

---

modules/cudaimgproc/src/hough_circles.cpp
modules/cudastereo/src/stereocsbp.cpp

use cv::AutoBuffer::data() to get data pointer
related #11719 
```
```

cuda: fix build

---

modules/core/src/opengl.cpp

resolves #11910
we have to use `buffer.data()` now, not the `operator _T*()`

core: fix autobuffer usage in opengl.cpp

---

modules/objdetect/src/qrcode.cpp

resolves #11905
return early from `QRCode::localization()` if one of the steps had no output

objdetect: validate input in qrcode

---

modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_googlenet.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_precomp.hpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

resolves #11926
`CV_ENUM` is just a legacy support for C API "defines" and anonymous enums.

dnn(test): drop CV_ENUM for DNNBackend / DNNTarget

---

modules/core/include/opencv2/core/mat.hpp

Related #11930 
Warn the user that `Mat::eye` and `Mat::ones` do not propagate with multi-channels type.

Add a note in the doc about Mat::ones and Mat::eye with multi-channels type

---

modules/dnn/src/opencl/conv_layer_spatial.cl

add zero padding if read position is bigger than input width
This patch fixes https://github.com/opencv/opencv/issues/11857
```
force_builders=Docs,linux,ocllinux,windows,ocl,macosx,oclmacosx,linuxNoOpt
```

Fix gemmlike convolution input reading

---

modules/dnn/src/layers/shuffle_channel_layer.cpp

call setParamsFrom, so name & type get properly copied from the importer params

dnn: preserve name, type strings for ShuffleChannelLayer

---

modules/core/include/opencv2/core/operations.hpp
modules/core/test/test_math.cpp

resolves #11888
Fixed compilation for `Matx::solve()` function with non-square matrixes

Fixed Matx::solve function for non-square matrixes

---

modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp

Temporary object lifetime must be greater than pointer usage.

DNN(OCL): fix wrong usage of stalled .getMat() pointers

---

modules/dnn/src/layers/prior_box_layer.cpp
modules/dnn/src/opencl/prior_box.cl
modules/dnn/test/test_layers.cpp

Enables Test_Caffe_layers.PriorBox_squares test for OpenCL targets (see https://github.com/opencv/opencv/issues/11866)

Clip kernel for OpenCL PriorBox layer

---

modules/core/include/opencv2/core/operations.hpp
modules/core/test/test_math.cpp

resolves #11950
Fix for unreachable code warnings in Matx::solve() and Matx::inv()

Fixed unreachable code warnings for Matx::solve()

---

modules/core/include/opencv2/core.hpp
modules/core/src/lda.cpp

removing it had to be postponed until 4.0 (3.x ABI compliance)

core: remove unused dataAsRow flag from LDA

---

modules/imgproc/perf/perf_warp.cpp
modules/imgproc/src/imgwarp.cpp

`DECOMP_SVD` -> `DECOMP_LU`
`getPerspectiveTransform()` requires to solve 8x8 linear system.
Performance is improved from 27.6 ms to 2.6 ms (1000 calls, i7-6700)
resolves #11944
```
```

imgproc(getPerspectiveTransform): change solve() 'method' parameter

---

modules/dnn/src/ocl4dnn/src/math_functions.cpp
modules/dnn/test/test_halide_layers.cpp

Fixes OpenCL test cases (see https://github.com/opencv/opencv/issues/11866)
```
test_opencl=ON
```

Fix fully-connected layer in case of number of rows less than 4

---

cmake/OpenCVDetectCUDA.cmake

CMake 3.9.0+ is required.
OpenCV has own patched version of FindCUDA. It was necessary 5 years ago, but current implementation from CMake works well too.
Validated with Ubuntu 16.04 + CUDA SDK 8.0 + cmake 3.9.0 (official distributed binaries).
```
```

cmake: allow to use external FindCUDA from modern CMake

---

modules/core/include/opencv2/core/operations.hpp
modules/core/test/test_math.cpp

- 'if' logic is moved into templates.
- removed unnecessary cv::Mat objects creation.
- fixed inv() test (invA * A == eye)
- added more Matx tests to cover all defined template specializations
[Current coverage of operations.hpp](http://pullrequest.opencv.org/buildbot/export/opencv_releases/3_4_coverage-lin64-debug/20180712-213645_88/coverage_html/opencv/modules/core/include/opencv2/core/operations.hpp.gcov.html).
```
```

core: eliminate 'if' logic from Matx::inv()/solve()

---

cmake/OpenCVDetectInferenceEngine.cmake

These CMake options are enough:
- `-DWITH_INF_ENGINE=ON`
- `-DIE_PLUGINS_PATH=lib/ubuntu_16.04/intel64`
- `-DENABLE_CXX11=ON` (OpenCV 3.4 only)
```
```

cmake: update DL IE detection to align with OpenVINO 2018 R2

---

modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/src/layers/softmax_layer.cpp
modules/dnn/test/test_tf_importer.cpp

* Enables TensorFlow networks tests for different backends and targets
* Fixes bugs in OpenCL implementations of SoftMax and DetectionOutput layers
resolves https://github.com/opencv/opencv/issues/11961
```
```

Fix bugs in OpenCL SoftMax and DetectionOutput layers

---

modules/core/include/opencv2/core/matx.hpp
modules/core/test/test_operations.cpp

core: use "explicit" for Matx() ctor

---

modules/core/include/opencv2/core/cvdef.h
modules/core/include/opencv2/core/mat.hpp
modules/core/perf/perf_mat.cpp

`[[nodiscard]]` is defined in C++17.
There is fallback alias for modern GCC / Clang compilers.
Merge after #11989.
<cut/>
[Validated](http://pullrequest.opencv.org/buildbot/builders/precommit_macosx/builds/16098).
```
/build/precommit_macosx/3.4/opencv/modules/calib3d/src/calibinit.cpp:518:9: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
img.clone();
```
```
```

core: CV_NODISCARD macro with semantic of [[nodiscard]] attr

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/misc/java/test/DnnTensorFlowTest.java
modules/dnn/src/caffe/caffe_importer.cpp
modules/dnn/src/darknet/darknet_importer.cpp
modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/darknet/darknet_io.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_darknet_importer.cpp

I added new constructor for DarknetImporter to load from std::istream.
Current constructor gets to two pathnames which are raw strings. Without std::filesystem of C++17, some pathname has problem for cross-platform development. This changes makes abstractly to load files.
<cut/>
```c++
std::ifstream cfg("path/to/cfg");
std::ifstream model("path/to/model");
Net net = readNetFromDarknet(cfg, model);
```
And more, by this changes we will be able to include resources into binary, like followings.
```c++
std::istringstream cfg("some configuration text");
std::ifstream model("path/to/model");
Net net = readNetFromDarknet(cfg, model);
```
```
```

Reading Darknet from cv::FileStorage

---

modules/ts/include/opencv2/ts/ts_ext.hpp
modules/ts/include/opencv2/ts/ts_perf.hpp

Example (reuse 'Transform' test case):
```
PERF_TEST(Transform, getPerspectiveTransform_1000) { ... }
PERF_TEST(Transform, getPerspectiveTransform_QR_1000) { ... }
```
```
```

ts: fix PERF_TEST() macro to allow test_case name reusing

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/src/op_inf_engine.hpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_misc.cpp

Add `scalefactor` and `mean` values to `setInput`. Add output blob data type to `blobFromImage(s)`. This way we can pass UINT8 input blob to VPU and normalize it by ScaleShift layer on device's side.
Model                      | FP32 inputs, usb3.0 | FP32 inputs, usb2.0 | UINT8 inputs, usb3.0 | UINT8 inputs, usb2.0 | x-factor (fp32/u8, usb2.0)
---|---|---|---|---|---
AlexNet                     |   82.497 |   94.448   | 82.014 |   84.162    | 1.12   
GoogLeNet                   |  105.076 |  116.899  | 104.499 |  106.975    | 1.09   
Inception_v2_SSD_TensorFlow |  338.367 |  373.696  | 337.281 |  356.496    | 1.05   
MobileNet_SSD_Caffe         |   94.407 |  115.654   | 92.994 |   97.792    | 1.18   
MobileNet_SSD_v1_TensorFlow |  116.405 |  151.172  | 115.637 |  133.696    | 1.13 …

uint8 inputs for deep learning networks

---

modules/videoio/src/container_avi.cpp

Added verbose error messages to AVI container
```
```

AVI container: verbose error messages

---

modules/videoio/src/cap_v4l.cpp

the static variables will cause race-condition when operating in
multithread scenarios.
Signed-off-by: Teng Yiliang <ylteng@outlook.com>
remove the static variables "static int width/height" used for parameters setting, add two internal members "CvCaptureCAM_V4L::width_set/height_set" to store the temporary parameters.
The static variables will cause race-condition when open() & setProperty(CV_CAP_PROP_FRAME_WIDTH/CV_CAP_PROP_FRAME_HEIGHT) to multi-cameras simultaneously in mult-threads.
in our usage scenarios, 8 webcamera could be correctly open/config/stream simultaneously using CAP_V4L interface without any lock after such change.
```
```

use struct member width_set/height_set to replace static width/height.

---

cmake/OpenCVCompilerOptimizations.cmake

```
|-- test_cv
|-- 3rdparty
|-- opencv
|-- build
CMakeLists.txt
```
```
mkdir test_cv && cd test_cv
mkdir build
git init
mkdir 3rdparty && cd 3rdparty
git submodule add https://github.com/opencv/opencv.git
mkdir ../build
cmake ..
```
corresponding CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 2.8)
project(test_cv)
add_subdirectory(3rdparty/opencv)
```
cmake copies cv_cpu_helper.h to a parent project:
```
|-- test_cv
|-- 3rdparty
|-- opencv
|-- build
|-- modules
|-- core
|-- include
|-- opencv2
|-- core
cv_cpu_helper.h
CMakeLists.txt
```

Do not copy cv_cpu_helper.h to parent if OpenCV is a submodule

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp
samples/dnn/tf_text_graph_ssd.py

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/492
SSD networks produce base bounding boxes (anchors, priors, proposals) and predict deltas for it's coordinates. For now SSDs from TensorFlow predict values in `ymin, xmin, ymax, xmax` order but PriorBox layer and DetectionOutput layer produce outputs in `xmin, ymin, xmax, ymax` coordinates order. There is `loc_pred_transposed` flag which indicates layout of predictions at `DetectionOutput` layer (to distinguish between Caffe's SSDs and TensorFlow's ones). However this mode doesn't supported in Intel's Inference Engine so all the graphs have three output layers and OpenCV runs a local `DetectionOutput`.
https://github.com/opencv/opencv/blob/51074b9743a36996af60bb5f8dbcddb71efe73b2/modules/dnn/src/layers/detection_output_la …

Run entire SSDs from TensorFlow using Intel's Inference Engine

---

modules/python/src2/cv2.cpp
modules/python/test/test_videoio.py
modules/videoio/include/opencv2/videoio.hpp
modules/videoio/include/opencv2/videoio/registry.hpp
modules/videoio/misc/python/pyopencv_videoio.hpp
modules/videoio/src/videoio_registry.cpp
modules/videoio/test/test_precomp.hpp
modules/videoio/test/test_video_io.cpp

into `cv::videoio_registry` namespace
[Documentation link](http://pullrequest.opencv.org/buildbot/export/pr/12020/docs/de/db1/group__videoio__registry.html)

videoio: add routines to query information about backends API

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/layers/proposal_layer.cpp
modules/dnn/src/ocl4dnn/src/ocl4dnn_pool.cpp
modules/dnn/src/opencl/ocl4dnn_pooling.cl
modules/dnn/src/torch/torch_importer.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_torch_importer.cpp
samples/dnn/object_detection.py

* Enable Faster-RCNN and RFCN object detection networks (from Caffe) with Inference Engine backend on CPU. There are fallbacks to default implementation at `DetectionOutput` and `Slice` layers.
input size: 320x240
| Model | OpenCV, CPU | OpenCV, GPU (fp32) | with IE, CPU | with IE, GPU (fp32) |
|----|----|----|---|----|
| VGG16 based | ~1.5s | 848ms | 357ms | |
| ZF | 600ms | 320ms | 177ms | 1.5s |
| ResNet-50 RFCN | 95ms | 134ms | 57ms | 115ms |
CPU: Intel&reg; Core&trade; i7-6700K CPU @ 4.00GHz x 8
GPU: Intel&reg; HD Graphics 530 (Skylake GT2)
* Enable Torch layers tests with Intel's Inference Engine backend.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/496
``` …
```

Faster-RCNN anf RFCN models on CPU using Intel's Inference Engine

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

resolves #12024
This pullrequest adds a simple check for the input index of the Mul node in the Maximum node to solve the issue.

TF import : Allow a different input order for Mul+Maximum (ReLU)

---

modules/dnn/include/opencv2/dnn/shape_utils.hpp
modules/dnn/src/dnn.cpp

For debug purposes.
Runtime flags:
- `OPENCV_DNN_CHECK_NAN_INF` - enable checks for each layer (slowdowns execution)
- `OPENCV_DNN_CHECK_NAN_INF_DUMP` - dump used matrixes
- `OPENCV_DNN_CHECK_NAN_INF_RAISE_ERROR` - raise CV_Assert() on problem detection
Supported:
- OpenCV backend (CPU / OpenCL)
- FP32 and FP16 (OpenCL only)

dnn: check layer output for NaN/Inf

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp

maybe related to #12086, #12085, #12084 discovered by #12056
resolves #12086
resolves #12085 
resolves #12084

core:avx2 fix unaligned store for v_store_interleave v_uint32x8-3ch

---

modules/core/src/ocl.cpp

to avoid silent crashes of OpenCL worker threads.

core(ocl): don't expose exceptions from OpenCL callback

---

modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/test/test_backends.cpp

* Fix Myriad tests for SSDs from TensorFlow.
* Enables any-size test for OpenCV's face detection network on Myriad
```
```

Fix DetectionOutput layer on Myriad

---

modules/core/src/umatrix.cpp

- check result from CV_XADD() directly
- decrease urefcount after unmap() call only

core(ocl): do not split refcount operations / compare

---

cmake/OpenCVModule.cmake

Variables `OPENCV_TEST_${the_module}_DEPS` and `OPENCV_PERF_${the_module}_DEPS` have been filled but not used.
```
```

Restored tests dependencies processing

---

3rdparty/openvx/hal/openvx_hal.cpp
3rdparty/openvx/hal/openvx_hal.hpp
modules/imgproc/include/opencv2/imgproc/hal/hal.hpp
modules/imgproc/src/hal_replacement.hpp
modules/imgproc/src/imgwarp.cpp

Fixes typo in function name hal::warpPerspective.

---

cmake/OpenCVDownload.cmake
samples/CMakeLists.txt
samples/dnn/CMakeLists.txt
samples/dnn/face_detector/download_weights.py
samples/dnn/face_detector/weights.meta4

* write download scripts for failed download attempts, minor changes in download logs
* fixed installation of samples data (was "<samples>/data/data")
* do not download face_detector models, instead created script which allows users to download models described in Metalink file
* Run cmake in clean build directory - cmake complains it can not download several files
* Run `bash <build>/download_with_wget.sh` script (or with_curl) - all files will be downloaded to the download cache
* Run `cmake .` in the build directory - all downloaded files will be found by cmake
* Go to directory samples/dnn/face_detector
* Run command `python download_weights.py`
Alternative way:
* Install one of [tools supporting Metalink format](https://en.wikipedia.org/wiki/Metalink)
* Run this tool and pass …

cmake download workaround, samples data installation

---

modules/stitching/include/opencv2/stitching/detail/matchers.hpp
modules/stitching/src/matchers.cpp
samples/cpp/stitching_detailed.cpp

Allow the use of SIFT FeaturesFinder for the `stitching_detailed` example.

feat(stitching): Add Sift support for the FeaturesFinder

---

cmake/OpenCVDetectCUDA.cmake

resolves #11354
Allows compiling CUDA OpenCV with a clang compiler (which is a valid scenario supported by CUDA).
Allows compiling CUDA OpenCV with a clang compiler but using gcc for the cuda compiler (CUDA_HOST_COMPILER=/usr/bin/gcc). This is also an extremely common scenario as the latest versions of gcc and clang are not supported by Clang, so you often need to specify an older (usually gcc) compiler. Arch-based distros install gcc-5 with cuda.
Note: CUDA still throws warnings about -Wmissing-prototypes and -Wstrict-prototypes when compiling CUDA with gcc but OpenCV with clang. This is because they share CXX flags and there is no checks done to see what the cuda compiler is. Crucially, it compiles
```
```

Support WITH_CUDA with clang compiler.

---

modules/videoio/src/cap_v4l.cpp

resolves #12107 
There was YV12 format, but no YU12 - this PR adds it.
Ported patch from #12107

videoio: added YUV420 format (UV order) support to v4l capture

---

modules/dnn/src/opencl/conv_layer_spatial.cl

Check should be always before memory access attempt.
```
```
<cut>
Pre-check via "if" is very slow (total performance drop ~2-5%).
Using `clamp()` / `min()` to fix reading indexes.

dnn(ocl): avoid memory access violation

---

modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/src/convert.cpp

Fix for SSE2 intrinsics problem in the part of saturation arithmetic processing during 32s->16u packed conversion - for big negative values less than -INT_MAX+32767 the sign of the numbers is lost due to overflow that leads to incorrect saturation to MAX value, instead of zero (e.g. convert32s8u(-2147465847) == 255).
CV_ENABLED_INTRINSICS settings shall be set to ON to reproduce the issue - it is not reproducible with disabled intrinsics.

Fix in SSE2 optimizations of types conversion routines (32s->16u)

---

modules/dnn/perf/perf_net.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/src/layers/scale_layer.cpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/layers/softmax_layer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp
samples/dnn/tf_text_graph_common.py
samples/dnn/tf_text_graph_faster_rcnn.py
samples/dnn/tf_text_graph_ssd.py

* resolves https://github.com/opencv/opencv/issues/11983
median time for a single 800x600 image forward pass:
| Model | OpenCV on CPU | OpenCV on GPU, fp32 | with IE on CPU |
| Inception_v2_Faster_RCNN (TensorFlow) **before PR** | 286.62ms | 333.81ms | |
| Inception_v2_Faster_RCNN (TensorFlow) **with PR** | 287.17ms | 335.21ms | 203.22ms |
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/498
```
```

Faster-RCNN from TensorFlow on CPU with Intel's Inference Engine backend

---

modules/core/include/opencv2/core/hal/intrin.hpp

resolves #12146
All vx_call() must be wrapped into own simd128/simd256/simd512 namespace
```
namespace CV__SIMD_NAMESPACE {
... vx_call declaration is here ...
}
```

core(intrin): avoid symbols duplication from SIMD128/256 cases

---

modules/videoio/src/cap_mjpeg_decoder.cpp

resolves #12164
check for `m_mjpeg_frames.end()` before iterating

videoio: check iterator in mjpeg_encoder.cpp

---

modules/core/src/utils/filesystem.cpp

- use '3.4.x' cache name for current maintenance series (there are no serious changes between them)
- message is shown only once during creation of new cache directory
- use `OPENCV_CACHE_SHOW_CLEANUP_MESSAGE=0` to hide this warning
<cut/>
Example:
```
[ WARN:0] Creating new OpenCV cache directory: /home/alalek/.cache/opencv/3.4.x-dev
[ WARN:0] There are several neighbor directories, probably created by old OpenCV versions.
[ WARN:0] Feel free to cleanup these unused directories:
[ WARN:0]   - 3.3.1-dev
[ WARN:0]   - 3.4.2
[ WARN:0]   - 3.4.2-dev
[ WARN:0]   - 4.0.0-pre
[ WARN:0] Note: This message is showed only once.
```

core: dump neighbour cache directories (from old OpenCV versions)

---

modules/photo/src/contrast_preserve.hpp

resolves: #12167
use a new Mat header for the resize() result.

photo: avoid resizing a const Mat in decolor()

---

samples/gpu/CMakeLists.txt

via find_package(OpenCV)
related #11534
Should fix [this build](http://pullrequest.opencv.org/buildbot/builders/2_4_winpack-test-win32-vc14/builds/10077)
[Validated](http://pullrequest.opencv.org/buildbot/builders/2_4_winpack-test-win32-vc14/builds/10079).

(2.4) samples(gpu): fix build (invalid access to cvconfig.h from sample)

---

apps/interactive-calibration/calibController.cpp

resolves #12202
only copy the 2nd part if `worstElemIndex < (int)numberOfFrames-1`

apps: fix interactive calibration

---

modules/dnn/misc/quantize_face_detector.py
modules/dnn/src/layers/normalize_bbox_layer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp
samples/dnn/face_detector/opencv_face_detector.pbtxt

Enabled OpenCL and Myriad targets for a quantized face detection network in TensorFlow format.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/507
Efficiency comparison:
| Backend, target | Caffe model | TensorFlow model | x-factor |
| DNN_BACKEND_INFERENCE_ENGINE, DNN_TARGET_CPU         | 7.134 |  7.163   |  1.00   |
| DNN_BACKEND_INFERENCE_ENGINE, DNN_TARGET_MYRIAD      | 94.330 | 95.294  |  0.99   |
| DNN_BACKEND_INFERENCE_ENGINE, DNN_TARGET_OPENCL      | 13.729 | 13.759  |  1.00   |
| DNN_BACKEND_INFERENCE_ENGINE, DNN_TARGET_OPENCL_FP16 | 10.642 | 10.855  |  0.98   |
| DNN_BACKEND_OPENCV, DNN_TARGET_CPU                   | 13.748 | 13.371  |  1.03   |
| DNN_BACKEND_OPENCV, DNN_TARGET_OPENCL                | 13.659 | 13.417  |  1.02   |
| …

Quantized face detection network using Intel's Inference Engine backend

---

modules/core/include/opencv2/core/cuda.hpp
modules/core/misc/python/pyopencv_core.hpp
modules/cudabgsegm/CMakeLists.txt
modules/cudafeatures2d/CMakeLists.txt
modules/cudafilters/CMakeLists.txt
modules/cudafilters/include/opencv2/cudafilters.hpp
modules/cudaimgproc/CMakeLists.txt
modules/cudaimgproc/include/opencv2/cudaimgproc.hpp
modules/cudalegacy/src/cuda/NCVBroxOpticalFlow.cu
modules/cudalegacy/test/NCVTest.hpp
modules/cudalegacy/test/NCVTestSourceProvider.hpp
modules/cudaobjdetect/CMakeLists.txt
modules/cudaoptflow/CMakeLists.txt
modules/cudastereo/CMakeLists.txt
modules/cudawarping/CMakeLists.txt
modules/python/bindings/CMakeLists.txt
modules/python/src2/gen2.py
modules/python/src2/hdr_parser.py
modules/python/test/test_cuda.py

resolves #4524
- Wraps GpuMat in a clean way, in compare to UMat. Perhaps UMat wrapper needs to be rewritten following this PR.
- Provide the Python binding generator with automatic fail-over for CUDA functionalities (Similar to UMat and OpenCL). An additional effort to unify the naming shall lead to a great CUDA/OpenCL/CPU fail-over system.
- Exposes some CUDA functionalities to the Python binder
- Provides unit tests for some basic CUDA-based pythonic functionalities
- Minor cleanup of the binder generation code, to match the current coding style
Well, Python is getting more and more famous, and deserves more attention now.
Now that several Python libraries are already CUDA-enabled, especially in the field of vision and learning, it is really a necessity for OpenCV to catch up. This PR …

Support Python binding for CUDA functionalities

---

modules/core/CMakeLists.txt

Builds with opencv_world enabled did not find some headers in _cuda_ and _opencl_ subdirectories.

Fixed core headers installation in world builds

---

modules/imgcodecs/src/grfmt_pfm.cpp

resolves  #12239
This pullrequest changes the encoding of non-float32-images when encoded to `pfm` format.
Formerly, anything other than float32 was converted to uint8 in order to encode it into the `pfm`-format, which is counter-intuitive and drops a lot of data unnecessarily.
With this fix, all three- or single-channel image types are converted to the corresponsing float32-type directly.

fixed 64-float pfm auto conversion

---

modules/core/perf/perf_arithm.cpp

Keep the same type for passed `Scalar` values.
There is no sense to pass values like 3506.3 for 8U tests.
<cut/>
1920x1080 CV_8UC1 results:
|Name of Test|ms|
|---|:-:|
|absdiff::BinaryOpTest::(1920x1080, 8UC1)|0.144|
|absdiffScalarDouble::BinaryOpTest::(1920x1080, 8UC1)|0.730|
|absdiffScalarSameType::BinaryOpTest::(1920x1080, 8UC1)|0.111|
|add::BinaryOpTest::(1920x1080, 8UC1)|0.150|
|addScalarDouble::BinaryOpTest::(1920x1080, 8UC1)|0.680|
|addScalarSameType::BinaryOpTest::(1920x1080, 8UC1)|0.111|
|divide::BinaryOpTest::(1920x1080, 8UC1)|0.994|
|max::BinaryOpTest::(1920x1080, 8UC1)|0.120|
|maxScalarDouble::BinaryOpTest::(1920x1080, 8UC1)|0.119|
|maxScalarSameType::BinaryOpTest::(1920x1080, 8UC1)|0.117|
|min::BinaryOpTest::(1920x1080, 8UC1)|0.152|
|minScalarDouble::BinaryOpTest::(1920x1080, …

core(perf): fix addScalar test

---

modules/ml/include/opencv2/ml.hpp
modules/ml/src/data.cpp
modules/ml/test/test_mltests2.cpp

It is designed for 1D vectors only.
resolves #12236
replaces #12237 
```
```

ml: don't use "getSubVector()" with 2D matrix

---

modules/imgcodecs/include/opencv2/imgcodecs/ios.h
modules/imgcodecs/src/ios_conversions.mm

This adds the export macros to the iOS UIImage conversion functions. Without the macro, the functions are not available when building OpenCV as a dynamic framework.
(This is a resubmission of a previous PR #12245 so that it can properly go to the 3.4 branch instead of master)

Add export macro for ios conversion functions

---

modules/core/include/opencv2/core/base.hpp
modules/core/include/opencv2/core/cvdef.h
modules/core/src/matmul.cpp
modules/dnn/include/opencv2/dnn/shape_utils.hpp
modules/dnn/src/caffe/caffe_importer.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/crop_and_resize_layer.cpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/src/layers/padding_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/layers/prior_box_layer.cpp
modules/dnn/src/layers/reshape_layer.cpp
modules/dnn/src/layers/resize_layer.cpp
modules/dnn/src/layers/scale_layer.cpp
modules/dnn/src/nms.cpp
modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/src/torch/torch_importer.cpp
modules/dnn/test/test_layers.cpp
modules/highgui/src/window_w32.cpp
samples/dnn/classification.cpp
samples/dnn/custom_layers.hpp
samples/dnn/segmentation.cpp
samples/dnn/text_detection.cpp

**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1722
Multi-argument CV_Assert() is accessible via CV_Assert_N() (with malformed messages).
Or use `OPENCV_FORCE_MULTIARG_ASSERT_CHECK` definition (before any of OpenCV headers) to force previous behavior.
Fix: avoid expanding of assertion inner macro
Sample code:
`CV_Assert(type == CV_8UC3);`
Message before:
"type == (((0) & ((1 << 3) - 1)) + (((3)-1) << 3))"
Message after:
"type == CV_8UC3"
<cut/>
There are many other cases which are much [worse](https://github.com/opencv/opencv/issues/12012#issue-342551071).
related #9293
```
#docker_image:Custom=halide:16.04
#buildworker:Custom=linux-1
```

core: repair CV_Assert() messages

---

modules/core/include/opencv2/core/hal/intrin.hpp
modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/test/test_intrin_utils.hpp

Intrinsics must be effective, so don't declare FP16 type/operations if there is no native support.
- CV_FP16: supports load/store into/from float32
- CV_SIMD_FP16: declares FP16 types and native FP16 operations
resolves #12027
```
force_builders=armv7,armv8,custom
```

core(intrin): restrict FP16 operations

---

modules/videoio/src/cap_v4l.cpp

Removes an unwanted while loop in cap_v4l.cpp
The while loop would run only once making it useless and leading
to confusion.
So, remove the unwanted while loop and just keep an infinite for
loop.
Note: Change better seen with ignoring whitespace changes.

cap-v4l: remove unwanted loop in V4L2 mainloop

---

modules/dnn/src/layers/normalize_bbox_layer.cpp

VS 2015 compilation failed: 
```
normalize_bbox_layer.cpp(279): error C2398: Element '1': conversion from 'const int' to 'unsigned __int64' requires a narrowing conversion
```

Fixed windows build with InferenceEngine

---

modules/shape/CMakeLists.txt
modules/shape/src/aff_trans.cpp
modules/shape/src/precomp.hpp
modules/video/CMakeLists.txt
modules/video/include/opencv2/video/tracking.hpp
modules/video/include/opencv2/video/tracking_c.h
modules/video/src/compat_video.cpp
modules/video/src/lkpyramid.cpp
modules/video/test/test_estimaterigid.cpp

**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1724
Proposal to remove duplicate RANSAC code in video module in OpenCV 4.
In ideal world, we would just remove `estimateRigidTransform` as the RANSAC estimators are implemented in calib3d. To support transition I have kept at least the most used overload as deprecated.
Follow up of https://github.com/opencv/opencv/pull/10569#issuecomment-400312371 
Related #11594 #10631

video: remove duplicate RANSAC code

---

modules/cudaarithm/src/cuda/math.cu

Closes #12281 - a bug in cuda::pow with negative base values

---

modules/core/misc/java/src/java/core+MatOfRotatedRect.java
modules/core/misc/java/test/RotatedRectTest.java

related: #12226 , #11800
add a MatOfRotatedRect class (and a small test) to the java wrappers.
this is needed for the dnn wrappers, (EAST and YOLOv3 models).

java: add a MatOfRotatedRect class

---

CMakeLists.txt

resolves #12294
GPhoto support should be improved:
- make it C++98 compliant (currently it partially uses C++11)
- fix support for PTP Android devices (it creates VideoCapture instance, but can't handle anything if device doesn't provide camera control)
- CMake detection should be fixed (#12294)

cmake: WITH_GPHOTO2=OFF by default

---

modules/core/misc/java/src/java/core+MatOfRotatedRect.java
modules/core/misc/java/test/RotatedRectTest.java

my bad (sorry for the extra work).
but it must be float, not double, to be binary compatible to the c++ object.
related #12287

java: change MatOfRotatedRect to CV_32FC5

---

modules/videoio/src/cap_xine.cpp

resolves #12304
Some `CV_Assert`s changed to `CV_Assert_N`s according to https://github.com/opencv/opencv/issues/12304

`CV_Assert`s changed

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/python/src2/cv2.cpp

related: #12270
* add a pyopencvVecConverter for RotatedRect, so `vector<RotatedRect>` can be passed as an argument
* wrap the NMSBoxes overload with RotatedRect into python/java. we have to use an alias (NMSBoxesRotated) here, because at the "wrapper level", both functions have the same signature.

python: add support for NMSBoxes(RotatedRect)

---

platforms/android/build_sdk.py
platforms/android/ndk-17.config.py

GCC toolchain is deprecated and emits verbose messages.
Switched to Clang.

android: NDK17 support

---

modules/dnn/src/layers/prior_box_layer.cpp

- The size of second channel should be size[2] of output tensor,
- The Scalar should be {variance[0], variance[0], variance[0], variance[0]}
for _variance.size() == 1 case.
Signed-off-by: Wu Zhiwen <zhiwen.wu@intel.com>
```
```

dnn: fix variance setting bug for PriorBoxLayer

---

modules/ts/src/ts.cpp

Option `test_data_check` can be used to verify that no test cases have been skipped due to missing test data.
Example run without downloaded DL models:
```.sh
$ ./bin/opencv_test_dnn
...
[  PASSED  ] 1703 tests.
```
Same but with the new option enabled:
```.sh
$ ./bin/opencv_test_dnn  --test_require_data=true
...
[  PASSED  ] 1590 tests.                                                                                                  
[  FAILED  ] 113 tests, listed below: 
...
113 FAILED TESTS
```

Added option to fail on missing testdata

---

modules/dnn/CMakeLists.txt
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp
samples/dnn/tf_text_graph_faster_rcnn.py
samples/dnn/tf_text_graph_ssd.py

* Do not exclude preprocessing nodes such `Sub` and `Mul` from object detection networks from TensorFlow.
* Enable Intel's Inference Engine performance tests
* More fusion for OpenCL targets:
| Test name | 3.4 | PR | x-factor |
| opencv_face_detector (DNN_BACKEND_OPENCV, DNN_TARGET_OPENCL)                  |  24.801ms  |  22.848ms   |   1.09|   
| opencv_face_detector (DNN_BACKEND_OPENCV, DNN_TARGET_OPENCL_FP16)             |  29.691ms  |  26.732ms   |   1.11|
| DenseNet_121 (DNN_BACKEND_OPENCV, DNN_TARGET_OPENCL)                          |  67.347ms  |  48.065ms   |   1.40|   
| DenseNet_121 (DNN_BACKEND_OPENCV, DNN_TARGET_OPENCL_FP16)                     |  86.088ms  |  58.142ms   |   1.48|   
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/509
``` …
```

Include preprocessing nodes to object detection TensorFlow networks

---

modules/core/src/count_non_zero.cpp

Replace custom SSE2 and NEON countNonZero implementatons with uiniversal intrinsics
TODO:
```
force_builders=Custom,armv8
```

countNonZero function reworked to use wide universal intrinsics

---

modules/imgcodecs/src/grfmt_webp.cpp
modules/imgcodecs/src/grfmt_webp.hpp
modules/imgcodecs/src/loadsave.cpp
modules/imgcodecs/test/test_webp.cpp

- don't reallocate passed 'img' (test is fixed - must use `IMREAD_UNCHANGED` / `IMREAD_ANYCOLOR`)
- avoid memory DDOS
- avoid reading of whole file during header processing
- avoid data access after allocated buffer during header processing (missing checks)
- use [WebPFree()](https://github.com/webmproject/libwebp/commit/822f113ebbe8810a1de0f11062faaf7edb0556e3) to free allocated buffers
- drop unused & undefined `.close()` method
- added checks for channels >= 5 in encoder
```
```

imgcodecs(webp): multiple fixes

---

modules/ml/src/knearest.cpp
modules/ml/test/test_emknearestkmeans.cpp

resolves #12347
move code for adjusting `K` to `BruteForceImpl::findNearest` and add a similar condition for the `KDtree`.

ml: fix adjusting K in KNearest

---

modules/js/src/embindgen.py
modules/video/CMakeLists.txt
modules/video/src/lkpyramid.cpp
platforms/js/build_js.py

resolves #12359
- `estimateRigidTransform()` is excluded from JS bindings
related #12248
```
**WIP**
```

build: fix js build (make video->calib3d dependency optional)

---

modules/imgproc/src/resize.cpp

Bit-exact resize reworked to use wide intrinsics
```
```

Bit-exact resize reworked to use wide intrinsics

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/imgproc/src/smooth.cpp

Bit-exact GaussianBlur reworked to use wide intrinsics
TODO:
**Note**: IPP should be disabled during these tests. 1 thread results are preferable (`--perf_threads=1`).
Dispatching should be disabled too: `-DCPU_DISPATCH=`
```
```

Bit-exact GaussianBlur reworked to use wide intrinsics

---

modules/dnn/src/layers/crop_layer.cpp
modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/test/test_caffe_importer.cpp

Enable OCV/OCL_fp16 tests for Faster-RCNN networks from Caffe
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/513
```
```

Replace Slice layer to Crop in Faster-RCNN networks from Caffe

---

modules/imgcodecs/src/grfmt_webp.cpp
modules/imgcodecs/src/utils.hpp

related #12353
```
force_builders=win32
```

imgcodecs(webp): use safe cast to size_t on Win32

---

modules/calib3d/src/stereosgbm.cpp

to allocate memory >2Gb
resolves #12368

calib3d: use `Mat::reserveBuffer()` instead of `.create()`

---

modules/videoio/src/cap_msmf.cpp

resolves #12301 
Fix two refcounting problems in the MSMF video capture backend:
- the smart pointer in `SourceReaderCB` held a reference to the `IMFSourceReader`, but apparently `IMFSourceReader` also holds several references to the callback interface, resulting in a dependency cycle
- initializing the refcount to 1 in `SourceReaderCB`'s ctor prevented the object from being deleted, resulting in two leaked instances

Fix https://github.com/opencv/opencv/issues/12301

---

modules/imgproc/src/resize.cpp

resolves #12370
Fixed bit-exact resize wide intrinsics implementation for 16U
```
**WIP**
```

Fixed bit-exact resize wide intrinsics implementation for 16U

---

modules/java/generator/gen_java.py
modules/python/src2/gen2.py
modules/python/src2/hdr_parser.py

With #12288, binding fails to cast named enums properly, and the C++11 enums are not recognized.
This PR fixes such issues, promoting a smooth transition to C++11 with proper enum interface (rather than just `int`s).
- Supports parsing `enum class` and `enum struct` with the correct scope
- Improves enum and consts hierarchical parsing
- Support enum arguments in Java and Python binders
<cut/>
```
```

Binding-generator improvements

---

modules/dnn/test/test_common.hpp

[Failed build](http://pullrequest.opencv.org/buildbot/builders/3_4_openvino-skl-lin64/builds/57).
[Validated](http://pullrequest.opencv.org/buildbot/builders/3_4_openvino-skl-lin64/builds/58).
related #12142

dnn: fix tests build with disabled OpenCL

---

modules/core/CMakeLists.txt
modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/mat.inl.hpp
modules/core/src/matrix_wrap.cpp
modules/core/test/test_mat.cpp
modules/cudafeatures2d/test/test_features2d.cpp

- support passing of `std::vector<KeyPoint>` via InputArray
related #9457
```
```

core: wrap custom types via _RawArray (raw() call)

---

modules/videoio/src/cap_v4l.cpp

Currently the private control enumeration will be stopped when QUERYCTRL
returns -EINVAL only. It is possible however that other errors occur.
One particular case is when the v4l2 device doesn't support any controls
and doesn't implement the QUERYCTRL ioctl. In that case the v4l2
framework returns -ENOTTY. In that case the current control enumeration
will go in an endless loop.
To fix this change the control enumeration stop condition. If any errors
occur, end the control enumeration.
Signed-off-by: Todor Tomov <todor.tomov@linaro.org>

cap_v4l: Fix private control enumeration end condition

---

modules/core/include/opencv2/core/mat.inl.hpp
modules/core/src/arithm.cpp
modules/core/src/convert.cpp
modules/core/src/convert_scale.cpp
modules/core/src/copy.cpp
modules/core/src/count_non_zero.cpp
modules/core/src/lut.cpp
modules/core/src/mathfuncs.cpp
modules/core/src/matmul.cpp
modules/core/src/matrix_wrap.cpp
modules/core/src/mean.cpp
modules/core/src/minmax.cpp
modules/core/src/norm.cpp
modules/core/src/persistence_json.cpp
modules/core/src/sum.cpp
modules/cudaarithm/src/arithm.cpp
modules/cudaimgproc/src/canny.cpp
modules/imgcodecs/src/grfmt_jpeg2000.cpp
modules/imgcodecs/src/grfmt_png.cpp
modules/imgcodecs/src/grfmt_pxm.cpp
modules/imgcodecs/src/grfmt_sunras.cpp
modules/imgproc/src/accum.cpp
modules/imgproc/src/linefit.cpp

Commits:
- 09837928d934d104b3f327ce42122b7b8f35fff3
- 10fb88d02791b33d83a3756c62e21aa1c5a1e68d
Excluded changes with std::atomic (C++98 requirement)
related #12357 #12391

(3.4) backport fixes for static analyzer warnings

---

modules/ts/include/opencv2/ts/ts_gtest.h

OpenCV tests no longer compiles with vc12.
This fix enables it to compile again.

Workaround for GTest v1.8.1 + Visual Studio 2013 (vc12)

---

modules/cudaimgproc/src/canny.cpp
modules/videoio/src/cap_openni2.cpp

C++98 is used in OpenCV 3.x.
```
```

build: don't use nullptr without C++11 guard

---

modules/core/src/batch_distance.cpp
modules/core/src/kmeans.cpp

On my computer with gcc 6.3, hal::normL2Sqr_ with AVX2 is much faster than the unrolled _AccTp normL2Sqr(const _Tp* a, const _Tp* b, int n) and the naive loop.
I am not sure if importing hal in base.hpp follows the design. If there's a better way, please let me know.

Replace naive normL2Sqr with hal::normL2Sqr_ for better performance

---

modules/python/src2/cv2.cpp

resolves #12427 
```
pw_compilers=gcc-4.9, gcc-5, gcc-6, clang-4, clang-5, clang-6
```

python:ppc64 Add missing support for PyLongObject

---

modules/js/CMakeLists.txt
modules/js/src/embindgen.py

Although Emscripten currently utilized Python2 and Clang for Windows, there is no harm to maintain highly compatible code with all platforms
- Resolves #12436
- Cleanup some deprecated Python code
- Handle unnamed enums
- Support MSVC
```
```

opencv_js: Support Python3 and MSVC

---

modules/imgproc/src/demosaicing.cpp

`bayer_XX2rgba` was returning a [NxMx3] array. I guess it was falling back on `bayer_xx2rgb` (no `a`)
I added the appropriate lines to tell it the depth of each image.
Let me know if you need anything else.
```
```

Select the correct depth for bayer2rgb and bayer2rgba

---

cmake/OpenCVDetectPython.cmake

I am not sure if the issue I went through is reproducible, but this change makes things more straightforward.
Basically I was experimenting with Emscripten on Windows, which affected my environment varibles heavily, and as a result `PYTHON2INTERP_FOUND` became set, while `PYTHON2_EXECUTABLE` is empty, thus broke building all python-based modules!
Anyway, what matters to us is that `PYTHON*_EXECUTABLE` is set, not `PYTHON*INTERP_FOUND`
- Improve detection of Python executable by checking for `PYTHON*_EXECUTABLE` rather than for `PYTHON*INTERP_FOUND`

CMAKE: Improve python detection

---

modules/core/src/mean.cpp
modules/core/test/test_arithm.cpp

Fixed meanStdDev() implementation for the case input matrix has more than 4 channels

Fixed meanStdDev() for multi-channel input matrixes

---

cmake/OpenCVFindProtobuf.cmake

Typo I believe. No such property as `INTERFACE_INCLUDE_SYSTEM_DIRECTORIES` in cmake

Fix include paths when building with external protobuf

---

modules/python/src2/cv2.cpp
modules/python/src2/gen2.py

resolves #12468
related #12427
There is some mess with `pyopencv_to()`/`pyopencv_from()`: multiple templated overloads.
C++ doesn't allow partial specialization for functions (only types are allowed), so this:
```
template<typename T>
PyObject* pyopencv_from(const cv::Ptr<T>& p)
```
declares a new function overload and introduce mess.
Introduced `struct PyOpenCV_Converter`:
- allowed SFINAE checks
- allowed partial specialization
```
```

python: fix "unsigned int" / "size_t" overloading conflict

---

modules/dnn/src/layers/pooling_layer.cpp

- remove raw SSE2 implementation
- Unfortunately, neither test_dnn nor perf_dnn covers this part
- Adding new new test case for these part seems really complicated task, so I'll just throw the PR

dnn: remove raw SSE2 implementation

---

modules/calib3d/src/dls.cpp
modules/core/include/opencv2/core/private.hpp
modules/core/src/cuda_stream.cpp
modules/core/src/lapack.cpp
modules/core/src/opengl.cpp
modules/features2d/src/matchers.cpp
modules/python/src2/cv2.cpp

- Suppress some meaningless warnings that originate from external libraries
- Fix a warning specific for MSVC2013, in which warning code 5033 does not exists yet

MSVC: Slience external/meaningless warnings

---

modules/dnn/misc/tensorflow/attr_value.pb.cc
modules/dnn/misc/tensorflow/attr_value.pb.h
modules/dnn/misc/tensorflow/function.pb.cc
modules/dnn/misc/tensorflow/function.pb.h
modules/dnn/misc/tensorflow/graph.pb.cc
modules/dnn/misc/tensorflow/graph.pb.h
modules/dnn/misc/tensorflow/op_def.pb.cc
modules/dnn/misc/tensorflow/op_def.pb.h
modules/dnn/misc/tensorflow/tensor.pb.cc
modules/dnn/misc/tensorflow/tensor.pb.h
modules/dnn/misc/tensorflow/tensor_shape.pb.cc
modules/dnn/misc/tensorflow/tensor_shape.pb.h
modules/dnn/misc/tensorflow/types.pb.cc
modules/dnn/misc/tensorflow/types.pb.h
modules/dnn/misc/tensorflow/versions.pb.cc
modules/dnn/misc/tensorflow/versions.pb.h
modules/dnn/src/tensorflow/attr_value.proto
modules/dnn/src/tensorflow/function.proto
modules/dnn/src/tensorflow/graph.proto
modules/dnn/src/tensorflow/op_def.proto
modules/dnn/src/tensorflow/tensor.proto
modules/dnn/src/tensorflow/tensor_shape.proto
modules/dnn/src/tensorflow/tf_io.hpp
modules/dnn/src/tensorflow/types.proto
modules/dnn/src/tensorflow/versions.proto

Preventing conflicts when linking both `opencv-dnn` and `tensorflow`. Same stuff as for Caffe
related #10139
```
```

Rename tensorflow namespace

---

modules/imgproc/src/demosaicing.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/519
Relates to #12465 
I had a typo in my tests which meant that I wasn't testing these cases.
Without this, when converting to bayer2rgba, the provided bayer pattern was ignored and assumed to be `rggb`.
related #8178

Fix BayerXX2RGBA when blue is on the first line.

---

CMakeLists.txt
cmake/OpenCVFindVA_INTEL.cmake
modules/core/include/opencv2/core/va_intel.hpp

MediaSDK is not actually needed to build VA-API/OpenCL interoperability feature. Detected `VA_INTEL_MSDK_INCLUDE_DIR` is not used.

Removed unnecessary build-time MediaSDK detection

---

cmake/OpenCVUtils.cmake

When cross compiling with clang, the internal C++ headers are not found
when adding sysroot to -isystem, that is redundant anyway because it
will look for headers insider --sysroot path with same quality as it
would do with -isystem otherwise
Signed-off-by: Khem Raj <raj.khem@gmail.com>
```
FAILED: 3rdparty/openexr/CMakeFiles/IlmImf.dir/Iex/IexBaseExc.cpp.o
....
In file included from
TOPDIR/build/tmp/work/cortexa7t2hf-neon-vfpv4-bec-linux-musleabi/opencv/3.4.3+gitAUTOINC+b38c50b3d0_1f6d6f0626_bdb7bb85f3_34e4206aef_fccf7cd6a4-r0/git/3rdparty/openexr/Iex/IexBaseExc.cpp:43:
In file included from
TOPDIR/build/tmp/work/cortexa7t2hf-neon-vfpv4-bec-linux-musleabi/opencv/3.4.3+gitAUTOINC+b38c50b3d0_1f6d6f0626_bdb7bb85f3_34e4206aef_fccf7cd6a4-r0/git/3rdparty/openexr/Iex/IexBaseExc.h:48:
In file …
```

Check for clang before using -isystem

---

modules/imgproc/src/resize.cpp

Fixed bit-exact resize SIMD implementation for AVX2 baseline
```
force_builders=Custom,linux,macosx,windows,docs,iOS,ARMv8
```

Fixed bit-exact resize SIMD implementation for AVX2 baseline

---

modules/core/src/mean.cpp

meanStdDev() implementation updated to use wide universal intrinsics
```
force_builders=Custom,linux,macosx,windows,docs,iOS,ARMv8
```

meanStdDev() implementation updated to use wide universal intrinsics

---

doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown
doc/py_tutorials/py_gui/py_trackbar/py_trackbar.markdown

For some mysterious (for me) reason, two lines of the code appears in my browser (Chrome) in the same line.
I've added an "enter" (just pressed enter), but don't know if it's the best solution.
```
```

Minor changes in docs (Python Tutorials)

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp
samples/android/mobilenet-objdetect/src/org/opencv/samples/opencv_mobilenet/MainActivity.java

Replace default value of `crop` argument from true to false.
Replace default value of `swapRB` argument from true to false.
With this PR `blobFromImage` and `blobFromImages` just create a 4D blob from an image by default:
```python
blob = img.transpose(2, 0, 1).reshape(1, img.shape[2], img.shape[0], img.shape[1])
```
Impacted applications:
* By default, Caffe framework works with BGR images ([source](https://github.com/BVLC/caffe/wiki/Image-Format:-BGR-not-RGB)) so `blobFromImage` without explicit `swapRB` flag for images from `cv::imread` now matches Caffe's models inputs. On the other hand, TensorFlow models work mostly with RGB images so we need to specify `swapRB=true` now.
* Without `crop=false` for object detection samples, `blobFromImage` cropped an input image keeping aspect …

Change default value of crop argument of blobFromImage

---

modules/core/src/copy.cpp
modules/core/src/matrix_wrap.cpp
modules/core/src/umatrix.cpp

related: #12561, #12268
My previous patch at #12268 was incomplete.
> Is just dst.copyTo(_dst); (without if) not enough?
> It seems it also works with copyTo(). Judging by the function code, I do not know how it can work though...
In fact it was working initially, but I got deceived by an already compiled test results (built, but forgot to install?), and thought the modifications worked as well, but it turned out it did not 😞 
```
```

Fix a bug in meanShiftSegmentation

---

samples/dnn/tf_text_graph_common.py
samples/dnn/tf_text_graph_faster_rcnn.py
samples/dnn/tf_text_graph_mask_rcnn.py
samples/dnn/tf_text_graph_ssd.py

resolves https://github.com/opencv/opencv/issues/12442
related http://answers.opencv.org/question/199588/attributeerror-dnn-object-has-no-attribute-writetextgraph/?comment=199598#post-id-199598
Use TensorFlow to create object detection text graphs in case of outdated OpenCV imported in corresponding scripts (with no writeTextGraph).

Import tensorflow to create text graphs if import cv is failed

---

modules/core/include/opencv2/core/hal/interface.h
modules/core/include/opencv2/core/types_c.h
modules/core/src/datastructs.cpp
modules/core/src/persistence.cpp
modules/core/src/persistence.hpp
modules/core/src/persistence_c.cpp
modules/core/src/persistence_types.cpp
modules/cudalegacy/src/graphcuts.cpp
modules/features2d/misc/java/test/FlannBasedDescriptorMatcherTest.java
modules/features2d/src/matchers.cpp
modules/flann/include/opencv2/flann/miniflann.hpp
modules/flann/src/miniflann.cpp
modules/ts/src/ts_perf.cpp

avoid OpenCV crashes due size change `CV_ELEM_SIZE(CV_USRTYPE1)`: 8 -> 2
relates #12463

core: drop usage of CV_USRTYPE1 in OpenCV

---

modules/calib3d/src/calibration.cpp

Before this fix, the code would fail if only standard deviations of
extrinsic parameters are requested. While standard deviations matrix
should be computed if any set of standard deviations is requested. A
variable is added to represent this case.
It fixes a bug when only stddev of extrinsic parameters are requested.
To reproduce this bug, try to call `calibrateCamera` with
`stdDeviationsIntrinsics` set to `noArray()`, while
`stdDeviationsExtrinsics` set to a vector of `double`. After camera
calibration, check the elements of `stdDeviationsExtrinsics`.

Fix failure to request stddev of non-intrinsics

---

CMakeLists.txt
cmake/OpenCVGenPkgconfig.cmake
cmake/OpenCVUtils.cmake
platforms/ios/build_framework.py
samples/cpp/example_cmake/CMakeLists.txt

Improve support for side-by-side installations (multiple major versions).
Improve conformance with Linux/GNU installation layout.
Details:
- includes have one extra level: `/usr/include/opencv4/` (no changes in applications are required if CMake is used).
- CMake config is moved into "lib". It is incorrect to place it in "share" directory due direct paths to binaries.
- changed paths for "doc", "licenses", "java"
- use "opencv4" by default (except "lib" - no "opencv" in path)
- pkg-config file is renamed to `opencv4.pc`
- use lower-case "opencv" in paths
All paths are still configurable.
```
**WIP**
test_modules=core
build_contrib:iOS=ON
```

cmake: update install paths (Linux)

---

modules/js/CMakeLists.txt
modules/js/src/make_umd.py

- Improves Emscripten <s>and other windows-specific dependencies</s> detection
- Provides meaningful message in case of compile issues
By inspecting CMake vars in the builders, we can notice the following:
```
EMSCRIPTEN_INCLUDE_DIR=/opt/emsdk-portable/emscripten/1.37.21/system/include
```
```
```

Improves JS dependencies detection and status indication

---

modules/js/src/embindgen.py
modules/js/src/templates.py

Enums support in JS module was not complete! If an enum is utilized in a constructor or a const, it would fail such as in [this build](http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/17414/)..
This PR fixes the issue
- Support enum types in constructors
- Cast enum consts to their numeric values
```
```

JS: Improve enums support

---

samples/python/_run_winpack_demo_python27.cmd

- accepts script parameter (allows drag & drop from 'explorer')
- use script dir instead of current dir (can launch samples from 'samples/dnn')
- added 'pause' to show error messages (about missing numpy) instead of instant closing

samples: update winpack python samples launcher

---

samples/python/_run_winpack_demo_python27.cmd

- accepts script parameter (allows drag & drop from 'explorer')
- use script dir instead of current dir (can launch samples from 'samples/dnn')
- added 'pause' to show error messages (about missing numpy) instead of instant closing
backport #12612

(3.4) samples: update winpack python samples launcher

---

modules/core/src/opengl.cpp

- Eliminates some annoying warnings
```
docker_image:Custom=qt:16.04
```

OpenGL: avoid losing precision in double-to-float conversion

---

modules/dnn/CMakeLists.txt
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/tensorflow/tf_graph_simplifier.cpp

* resolves https://github.com/opencv/opencv/issues/12542
* remove `-Werror=non-virtual-dtor` suppression introduced in https://github.com/opencv/opencv/pull/10608 (related: http://answers.opencv.org/question/199796/opencv-343-compiling-with-mingw-64-810-and-cmake-for-eclipse/)
```
```

Fix #12542

---

modules/core/include/opencv2/core/ocl.hpp
modules/core/src/ocl.cpp
modules/core/test/ocl/test_gemm.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/blank_layer.cpp
modules/dnn/src/layers/concat_layer.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/crop_layer.cpp
modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/src/layers/flatten_layer.cpp
modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/layers/lrn_layer.cpp
modules/dnn/src/layers/normalize_bbox_layer.cpp
modules/dnn/src/layers/padding_layer.cpp
modules/dnn/src/layers/permute_layer.cpp
modules/dnn/src/layers/prior_box_layer.cpp
modules/dnn/src/layers/region_layer.cpp
modules/dnn/src/layers/reorg_layer.cpp
modules/dnn/src/layers/reshape_layer.cpp
modules/dnn/src/layers/shuffle_channel_layer.cpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/layers/softmax_layer.cpp
modules/dnn/src/layers/split_layer.cpp
modules/dnn/src/ocl4dnn/src/ocl4dnn_lrn.cpp
modules/dnn/src/opencl/prior_box.cl
modules/dnn/test/test_onnx_importer.cpp
modules/python/test/test_dnn.py

remove `OCL_PERFORMANCE_CHECK(ocl::Device::getDefault().isIntel())` from deep learning layers.
Is there a way to test this PR on non Intel GPUs?
```
```

Remove isIntel check from deep learning layers

---

modules/js/CMakeLists.txt
platforms/js/build_js.py

- avoid unnecessary 2 messages for other build configurations
```
-- ${EMSCRIPTEN_INCLUDE_DIR}/emscripten/bind.h` was not detected
-- Module js disabled because the following dependencies are not found: Emscripten
```
```
force_builders=Docs,Custom
```

build: cleanup js scripts

---

modules/core/include/opencv2/core/private.hpp
modules/core/src/ocl.cpp
modules/core/src/system.cpp

* fixed warning about variable redefinition when both IPP and instrumentation are enabled
* fixed segfault when no `funName` provided for `NodeData` struct
* compilation fixed when both OCL and instrumentation are enabled

Fixes for instrumentation of IPP and OCL

---

modules/core/include/opencv2/core/utility.hpp
modules/core/src/system.cpp

C++11 `<mutex>` is not available when compiling with  /clr under Visual Studio, thus opencv cannot be easily included.
It is fixed by making a CEEMutex wrapper class, around an opaque implementation using std::mutex internally
resolves #11912

hide use of std::mutex from /clr compilation under Visual Studio

---

modules/cudaarithm/include/opencv2/cudaarithm.hpp
modules/cudaarithm/perf/perf_element_operations.cpp
modules/cudaarithm/src/cuda/polar_cart.cu
modules/cudaarithm/test/test_element_operations.cpp

Merge with opencv/opencv_extra#522
related: #12561, #12268
Fix for `cuda::polarToCart` functionality
- Support double precision
- test double precision and tune tolerance
All tests are performed using
```
opencv_perf_cudaarithm --gtest_filter=*PolarToCart* --perf_min_samples=10000 --perf_force_samples=10000 
```
|       | Type  | mean | median | min  |    stddev   | total time | --gtest_param_filter     |
|-------|-------|------|--------|------|-------------|------------|--------------------------|
| Before| float | 0.20 |  0.19  | 0.18 | 0.01 (5.3%) |  2054 ms   | (1920x1080, true)        |
|       | double| N/A  |  N/A   |  N/A |  N/A        |   N/A      |  N/A                     |
| After | float | 0.19 |  0.19  | 0.18 | 0.01 (4.1%) |  1994 ms   | (1920x1080, 32FC1, true) |
|       | …

Support double precision in cuda::polarToCart() + fix broken tests

---

platforms/ios/build_framework.py

The regex was only parsing for a single digit in the major version, causing Xcode 10 to be treated as version "1". Other parts of the script only turn on bitcode generation if the Xcode version is > 7.

Fix Xcode version parsing error (affects bitcode generation)

---

doc/tutorials/imgproc/pyramids/pyramids.markdown

Fixing typo in image pyramids tutorial

Fix typo "wit" -> "with"

---

modules/cudaimgproc/test/test_color.cpp
modules/cudev/include/opencv2/cudev/functional/detail/color_cvt.hpp

* follow the implementation of Luv2RGBfloat in imgproc/src/color_lab.cpp
* related #12561
* since the implementation of CPU side changed in #9226 , the ```opencv_test_cudev``` was failing
* the difference was 30+ when the eps was 2.
* still, it rarely happens, but when converting the Luv to RGB colorspace, there is a gap of gradation, and the error was happening around this gap.
* expanding eps was one choice (as commented in #12561 ) but I managed to port the implementation of imgproc to cudev.
* once this modification is approved, I'll open a PR for opencv_contrib, too.
```
```

cudev: fix test failure of cudev

---

modules/ts/misc/run_suite.py

Utilize the currently running Python executable, especially if the version matches the Python module being tested

TS: Utilize the currently running Python executable

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp

resolves #10824 #12696
document, that the codecs internal methods are used to convert grayscale images 
(so results differ from cvtColor).
```
buildworker:Linux x64 Debug=linux-2
```

document imread grayscale behaviour

---

modules/calib3d/src/chessboard.cpp
modules/calib3d/test/test_chesscorners.cpp
modules/core/include/opencv2/core/check.hpp
modules/core/src/check.cpp

- avoid updating of input image during equalizeHist() call
- avoid for() with double variable (use 'int' instead)
- more CV_Check*() macros
- use Mat_<T>, Matx
- static for local variables
<cut/>
```
buildworker:Linux x64 Debug=linux-2
```

calib3d: findChessboardCornersSB() minor updates

---

3rdparty/protobuf/src/google/protobuf/stubs/atomicops_internals_generic_gcc.h

Resolves #12684 
This commit fixes an issue while trying to compile on s390x architecture.
This is simply a backport of a fixe already applied in official protobuf code:
- https://github.com/protocolbuffers/protobuf/pull/3955
This commit was used to compile openCV on s390x for openSUSE:
- https://build.opensuse.org/package/show/home:ldevulder:branches:devel:openQA/opencv
- https://build.opensuse.org/public/build/home:ldevulder:branches:devel:openQA/SLE_15/s390x/opencv/_log
```
buildworker:Linux x64 Debug=linux-2
```

3rdparty/protobuf: fix compilation issue on s390

---

modules/videoio/src/cap_ffmpeg_impl.hpp

resolves #9023 
It fixes a typo in the frame rate calculation in the ffmpeg wrapper making some frame rates off. Examples: 
* 59.9 stays the same
* 59.94 is rounded to 59.9
* 59.2 is rounded to 59
* 59.15 is rounded to 59

Fix frame rate rounding in ffmpeg wrapper (#9023)

---

modules/cudaarithm/include/opencv2/cudaarithm.hpp

resolves #12015
Fix documentation of `cv::cuda::compare` to specify the type returned.

Fix documentation of cv::cuda::compare

---

modules/dnn/src/opencl/conv_layer_spatial.cl

- avoid memory access violation during "prefetch" stage
No performance regressions:
- on i5-6600 (Fedora 28, Intel OpenCL NEO 18.30.11148)
- on i7-6700K (Fedora 28, Intel OpenCL NEO 18.33.11309)

dnn(ocl4dnn): drop weights_buf

---

modules/core/src/ocl.cpp

For debug purposes.
Usage example:
- `OPENCV_OPENCL_BUILD_EXTRA_OPTIONS="-cl-opt-disable"`
- `OPENCV_OPENCL_BUILD_EXTRA_OPTIONS="-D OPENCV_DEBUG_HEADERS=1 -I<path_to_debug_headers>"`

ocl: OPENCV_OPENCL_BUILD_EXTRA_OPTIONS parameter

---

modules/core/include/opencv2/core/utils/configuration.private.hpp
modules/core/src/system.cpp

Adds support for configuration parameters with list of paths. New function `cv::utils::getConfigurationParameterPaths` will return `vector<string>` with paths recorded in corresponding environment variable. Paths should be separated by `;` on Windows and `:` on other platforms (similar to `PATH`).

Added support for multi-path configuration parameter (env)

---

modules/videoio/src/cap_ffmpeg_impl.hpp

The `codec_tag` is only available when opening a file from disk. If `AVStream` is a network stream then `fourcc` must be obtained using `codec_id`. I have tested the following scenarios:
1) Open a `.mp4` file and verify that `codec_tag` is returned (old behavior)
2) Open a `rtsp` stream and verify that `codec_fourcc` is returned (Tested with a MJPEG, H264 and H265 stream)
```
docker_image:Custom=ffmpeg-master
```

Obtain fourcc when `AVStream` is network stream

---

cmake/OpenCVCompilerOptions.cmake

Avoids passing -Wall, which will enable literally every warning in
Clang. Avoids passing -ffunction-sections etc to clang-cl, which each
generate warnings.
A user reported a compiler crash when building opencv with clang-cl:
https://bugs.llvm.org/show_bug.cgi?id=39007
While reproducing it, I ran into these issues.

Fix CMake for clang-cl

---

modules/calib3d/src/calibration.cpp

resolves #12012 
related #12334 
I've added a check for CALIB_USE_EXTRINSIC_GUESS such that an error is raised if this flag is set in stereoCalibrate. This commit is created to fix issue #12012.

Add check for CALIB_USE_EXTRINSIC_GUESS in stereoCalibrate

---

modules/dnn/src/opencl/conv_layer_spatial.cl

- to avoid multiple conditional calls via sub_group() functions
<cut/>
```
#define ACTIVATION_RELU_FUNCTION(x, c) ((Dtype)(x) > 0 ? (Dtype)(x) : ((Dtype)(x) * (negative_slope)))
...
#define ACTIVATION_FUNCTION(_dst_, _offset_, _data_, _channel_) do { \
(_dst_)[(_offset_)] = ACTIVATION_RELU_FUNCTION(eltwise_data[(_offset_)] + (_data_), _channel_); \
} while(0)
...
#define SUBGROUP_GET_BIAS(k, i) intel_sub_group_shuffle(bias[k], i)
...
ACTIVATION_FUNCTION(dst, out_offset + ( 0 + i ) * out_pitch_y, blockC00[i] + SUBGROUP_GET_BIAS(0, i), group_x * TILE_N + i);
```

dnn(ocl4dnn): calculate activation expression once

---

modules/cudastereo/src/cuda/stereobp.cu
modules/cudastereo/src/stereobp.cpp

* if the src has odd number of height, access error happens
* check both dst and src range
Before
```
Device count: 1
Device 0: "GeForce GTX 1060"
CUDA Driver Version / Runtime Version          10.0 / 10.0
CUDA Capability Major/Minor version number:    6.1
Total amount of global memory:                 6144 MBytes (6442450944 bytes)
GPU Clock Speed:                               1.57 GHz
Max Texture Dimension Size (x,y,z)             1D=(131072), 2D=(131072,65536), 3D=(16384,16384,16384)
Max Layered Texture Size (dim) x layers        1D=(32768) x 2048, 2D=(32768,32768) x 2048
Total amount of constant memory:               65536 bytes
Total amount of shared memory per block:       49152 bytes
Total number of registers available per block: 65536
Warp size: …
```

cudastereo: fix test failure of StereoBeliefPropagation

---

cmake/OpenCVFindProtobuf.cmake

Adds `IMPORTED` for the `protobuf::libprotobuf` alias target as it otherwise produces an error during `install`:
`CMake Error: install(EXPORT "OpenCVModules" ...) includes target "opencv_dnn" which requires target "libprotobuf" that is not in the export set.`
cmake version: 3.10.2

Fix install with external protobuf

---

modules/core/include/opencv2/core/ocl.hpp

`ocl::KernelArg::Local()` now is incorrect: it doesn't provide local mem size, as a result a kernel fails to run.
This PR fixes this by introducing this missing argument and making possible to pass local mem args to kernels w/o using `KernelArg` constructor.

ocl::KernelArg::Local(): added size argument

---

modules/core/include/opencv2/core/hal/intrin.hpp

_tzcnt_u32() is not exported by clang-cl intrin.h so check for
clang-cl and enable an alterate for _tzcnt_u32()
Some discussions:
http://lists.llvm.org/pipermail/cfe-dev/2016-October/051329.html
https://bugs.llvm.org/show_bug.cgi?id=30506
TEST=Build opencv with clang-cl (disabled WEBP and DirectX due to other failures)
Change the reference to _tzcnt_u32() which is not available by default on clang-cl (unlike MSVC). 
```
```

Fix clang-cl _tzcnt_u32 intrinsic

---

modules/ts/src/cuda_test.cpp

When two installed CUDA-enabled devices have the same name, it is impossible to differentiate them..
As a matter of fact, it turned out that some failing tests reported in #12561 only occurs with a specific device, and without such information, debugging is very hard..
- Prints out the device ID if it is greater than zero
```
```

TS/CUDA: Show device ID in case of multiple devices

---

samples/_winpack_build_sample.cmd

relates #12636
Support configurations without full MSVS installations - where [BuildTools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017) is available only.

samples: add search for MSVS 2017 BuildTools

---

modules/cudaimgproc/test/test_color.cpp

The test of ```cudaimgproc``` fails.  Related to #12561
This PR will fix the test failure
<cut/>
```
[----------]
[ GPU INFO ]    Run on OS Windows x64.
[----------]
*** CUDA Device Query (Runtime API) version (CUDART static linking) ***
Device count: 1
Device 0: "GeForce GTX 1060"
CUDA Driver Version / Runtime Version          10.0 / 10.0
CUDA Capability Major/Minor version number:    6.1
Total amount of global memory:                 6144 MBytes (6442450944 bytes)
GPU Clock Speed:                               1.57 GHz
Max Texture Dimension Size (x,y,z)             1D=(131072), 2D=(131072,65536), 3D=(16384,16384,16384)
Max Layered Texture Size (dim) x layers        1D=(32768) x 2048, 2D=(32768,32768) x 2048
Total amount of constant memory:               65536 bytes
Total amount of …
```

cudaimgproc: fix test failure of cudaimgproc convert color of bgr2lab series

---

modules/core/src/parallel.cpp

Similar to 'OMP_DYNAMIC=TRUE'.
OpenMP is very sensitive to background jobs.
Switch to old behavior:
- set `OPENCV_FOR_OPENMP_DYNAMIC_DISABLE=1`
- or call `omp_set_dynamic(0)` from user code.
<cut/>
---
[Before](http://pullrequest.opencv.org/buildbot/builders/3_4_etc-qt-openmp-lin64/builds/24):
```
[----------] 2 tests from Core_KMeans
[ RUN      ] Core_KMeans.singular
[       OK ] Core_KMeans.singular (559692 ms)
[ RUN      ] Core_KMeans.compactness
command timed out: 600 seconds without output
```
[After](http://pullrequest.opencv.org/buildbot/builders/3_4_etc-qt-openmp-lin64/builds/25):
```
[----------] 2 tests from Core_KMeans
[ RUN      ] Core_KMeans.singular
[       OK ] Core_KMeans.singular (8336 ms)
[ RUN      ] Core_KMeans.compactness
[       OK ] Core_KMeans.compactness (22233 …
```

core: call omp_set_dynamic() for better CPU usage

---

samples/_winpack_build_sample.cmd

MSVS is shipped with CMake compoment (enabled by default in BuildTools configuration).
Don't require separate CMake installation.
<cut/>
---
<details>
```
================================================================================
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
=================================================================================
cmake --version
cmake version 3.11.18040201-MSVC_2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
CMake is detected
```
</details>

samples: prefer CMake from MSVS

---

modules/core/include/opencv2/core/persistence.hpp
modules/core/src/persistence_cpp.cpp
samples/dnn/classification.cpp
samples/dnn/classification.py
samples/dnn/common.hpp
samples/dnn/common.py
samples/dnn/models.yml
samples/dnn/object_detection.cpp
samples/dnn/object_detection.py
samples/dnn/segmentation.cpp
samples/dnn/segmentation.py
samples/dnn/tf_text_graph_common.py

**WIP**
related: https://github.com/opencv/opencv/pull/12354, https://github.com/opencv/opencv/pull/12186
* Add a YAML file with deep learning networks aliases to autofill preprocessing parameters for OpenCV samples.
Before:
```
python object_detection.py --model opencv_face_detector.caffemodel --config opencv_face_detector.prototxt --mean 104 177 123 --width 300 --height 300
```
now:
```
python object_detection.py opencv_fd
```
Proposed approach just puts appropriate default values to specified arguments. User can override it manually and modify another arguments as well:
```
python object_detection.py opencv_fd --width 320 --height 240 --input /path/to/image
```
* A help message contains filled parameters and shows possible aliases:
```
$ python ../samples/dnn/object_detection.py …
```

Add a file with preprocessing parameters for deep learning samples

---

modules/core/src/matrix.cpp

core: re-throw allocation exception if there is no fallback

---

modules/calib3d/src/fisheye.cpp
modules/calib3d/src/stereobm.cpp
modules/dnn/perf/perf_convolution.cpp
modules/imgproc/src/drawing.cpp
modules/imgproc/src/imgwarp.cpp
modules/imgproc/src/lsd.cpp
modules/imgproc/src/pyramids.cpp
modules/imgproc/test/ocl/test_pyramids.cpp
modules/imgproc/test/ocl/test_warp.cpp
modules/imgproc/test/test_imgwarp_strict.cpp
modules/objdetect/src/cascadedetect.cpp
modules/objdetect/src/detection_based_tracker.cpp
modules/objdetect/src/haar.cpp
samples/cpp/select3dobj.cpp
samples/tapi/dense_optical_flow.cpp

relates #12811 
changes area() emptiness checks to use empty()
cases:
.area() == 0 to empty()
.area() != 0 to !empty()
.area() > 0 to  !empty()
_src.size().area() > 0 to !_src.empty() //no need to create size here
if( r.area() ) to if( !r.empty() )

change area() emptiness checks to empty()

---

modules/core/include/opencv2/core/hal/intrin.hpp
modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_forward.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_sse_em.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/core/include/opencv2/core/vsx_utils.hpp
modules/core/src/mean.cpp
modules/core/test/test_arithm.cpp
modules/core/test/test_intrin_utils.hpp
modules/imgproc/CMakeLists.txt
modules/imgproc/perf/perf_accumulate.cpp
modules/imgproc/src/accum.simd.hpp
modules/imgproc/src/smooth.cpp
modules/video/src/lkpyramid.cpp

This patch paves the way for #12064
Merge with opencv_contrib: opencv/opencv_contrib#1771
```
force_builders=Custom,armv7,armv8,linux
CPU_BASELINE:Linux x64=AVX2
pw_compilers=gcc-4.9, gcc-5, gcc-6, clang-4, clang-5, clang-6
pw_with_opencv_contrib=branch:changeUnvMultiply16
```

 core:unv Change behaviour of 16-bit multiply operator

---

modules/core/include/opencv2/core/utils/trace.hpp
modules/core/src/mathfuncs.cpp
modules/core/src/mathfuncs_core.simd.hpp
modules/js/CMakeLists.txt
platforms/js/build_js.py

- support emscipten 1.38.12 ([wasm is ON by default](https://github.com/kripken/emscripten/blame/dc5c6841ae36cf59748de21b152176e9fdd0c2d2/src/settings.js#L735), need to disable explicitly)
- verbose build messages
- use builtin Math functions
```
```

js: update build js

---

modules/dnn/src/caffe/caffe_importer.cpp
modules/dnn/test/test_caffe_importer.cpp

We have been using OpenCV dnn module to run some of our caffe models (OpenCV version 3.4.1). After upgrading to 3.4.2 we noticed problems caused by #11461 
Our network reuses parameters from some of it's layers as described in our `deploy.prototxt` file (see the layer name in the lines highlighted by `HERE`):
```
layer {
name: "conv1"  type: "Convolution"  bottom: "input_0"  top: "conv1_0"  <--- HERE
param { name: "conv1_w"    lr_mult: 1    decay_mult: 1  }
param { name: "conv1_b"   lr_mult: 2    decay_mult: 0  }
convolution_param {    num_output: 48    kernel_size: 11    stride: 4
weight_filler {      type: "gaussian"      std: 0.01    }
bias_filler {      type: "constant"      value: 0    }
}
}
...
layer {
name: "conv1"  type: "Convolution"  bottom: "input_2"  top: "conv1_2"   <--- HERE …
```

Fix dnn caffe importer extract blobs from reused layers

---

modules/objdetect/src/qrcode.cpp
modules/objdetect/test/test_qrcode.cpp

- also drop unnecessary matrix initialization
resolves #12819

objdetect: validate QRdecode inputs

---

modules/videoio/src/cap_v4l.cpp

videoio: return -1 is incorrect for function with 'bool' result

---

modules/core/src/copy.cpp
modules/core/test/test_ds.cpp
modules/imgproc/src/canny.cpp
modules/imgproc/src/deriv.cpp
modules/imgproc/src/morph.cpp
modules/imgproc/src/resize.cpp
modules/imgproc/src/smooth.cpp

Exceptions caught by value incur needless cost in C++, most of them can
be caught by const-reference, especially as nearly none are actually
used. This could allow compiler generate a slightly more efficient code.

Catch exceptions by const-reference

---

apps/traincascade/old_ml.hpp
modules/features2d/src/kaze/KAZEConfig.h

Relevant guards can be found in
https://github.com/opencv/opencv/blob/ef5579dc8667e5eb5e149acc4af898421eed99da/modules/features2d/src/kaze/AKAZEConfig.h#L8
and
https://github.com/opencv/opencv/blob/ef5579dc8667e5eb5e149acc4af898421eed99da/modules/ml/include/opencv2/ml.hpp#L44

Fix clashing include guards

---

modules/flann/include/opencv2/flann.hpp

Resolves #12847
Added documentation for Distance functor in flann module. However, I am not sure if the "Detailed Description" section of `GenericIndex` is the most appropriate place for it. I would like some feedback in this regard.

flann: Add documentation for Distance functor

---

modules/dnn/src/caffe/caffe_importer.cpp

Resolves #12315
Recognize `ConvolutionDepthwise` as `Convolution` within Caffe parser.

Recognize ConvolutionDepthwise as Convolution

---

samples/dnn/common.hpp

resolves #12918
use `const char*` pointers for the getenv() results, so they can be checked for NULL

dnn/samples: handle not set env vars gracefully

---

modules/core/include/opencv2/core/base.hpp

`CV_ErrorNoReturn` should not be used in OpenCV
relates #12744
relates #12787

core: fix merge from 3.4

---

modules/core/include/opencv2/core/base.hpp
modules/core/include/opencv2/core/cvdef.h

core: move compiler defines from base.hpp into cvdef.h

---

doc/py_tutorials/py_calib3d/py_depthmap/py_depthmap.markdown

Pull Request is an update for depth map tutorial, for opencv python. Now in the tutorial we have answer for:
What are the StereoBM parameters and basically what is the meaning of using those?
Reference to understand added. Reference is from Ros wiki and clearly describes what are the parameters. It was hard to find when a programmer is new to stereo depth and disparity map. It is better to understand, tutorial can give the basics for parameters now.

Update depth map for python-opencv

---

modules/python/common.cmake

- https://python.readthedocs.io/en/stable/whatsnew/3.4.html
- The `sysconfig` key `SO` is deprecated, it has been replaced by `EXT_SUFFIX`
Message from CMake step (with Python 3.7):
```
DeprecationWarning: SO is deprecated, use EXT_SUFFIX
```
```
```

python: eliminate DeprecationWarning: SO -> EXT_SUFFIX

---

doc/tutorials/calib3d/camera_calibration/camera_calibration.markdown
doc/tutorials/calib3d/table_of_content_calib3d.markdown
modules/calib3d/doc/calib3d.bib
modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/include/opencv2/calib3d/calib3d_c.h
modules/calib3d/src/calibration.cpp
modules/calib3d/test/test_cameracalibration.cpp
modules/calib3d/test/test_cameracalibration_badarg.cpp
samples/cpp/calibration.cpp
samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp
samples/cpp/tutorial_code/calib3d/camera_calibration/in_VID5.xml

**Merge with extra**: opencv/opencv_extra#528
Checkerboard patterns on paper using off-the-shelf printers are the most
convenient calibration targets. And these printed patterns stuck on
roughly planar surfaces are the mostly used calibration structure world
wide. But in most cases printed patterns are inaccurate and the sticking
surfaces are not perfectly planar.
For example, the square size of the above chessboard is set to 15mm
in the PDF file. The printed paper was pasted to a glass panel which was
not so perfect planar structure. We measured the distances between
combinations of p1, p2, p3 and p4 with a vernier caliper of 0.02mm
resolution (The uncertainties of the measurements are probably larger
than 0.1mm I think). The result are compared to hypothesis values. The
maximum error is …

More accurate pinhole camera calibration with imperfect planar target

---

modules/core/src/mean.cpp

6x1000 CV_32C1 valgring report with `OPENCV_IPP=SSE42`:
```
Intel(R) IPP version: ippIP SSE4.2 (y8) 2019.0.0 Gold (-) Jul 24 2018
...
==12590== Invalid read of size 16
==12590==    at 0x9AF2368: icv_y8_ownSumSq_32f_C1R_M7_Al (in lib/libopencv_core.so.3.4.3)
==12590==  Address 0x24edf180 is 0 bytes after a block of size 32,000 alloc'd
==12590==    at 0x4C30E38: memalign (vg_replace_malloc.c:857)
==12590==    by 0x4C30F40: posix_memalign (vg_replace_malloc.c:1020)
```
relates #12877

core(ipp): disable SSE4.2 meanStdDev() optimization for CV_32F

---

modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests.hpp
modules/gapi/src/api/kernels_imgproc.cpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp

Renamed cv::gapi::sobel(...) kernel to cv::gapi::Sobel(...) to match with OpenCV naming rules

Renamed Sobel operator GAPI kernel to match with OpenCV naming rules

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp

`_mm256_zeroupper` is replaced by `_mm256_zeroall`
This should fix an incorrect behavior of `vx_cleanup` on AVX+ baselines on some compilers (for example GCC 7.3.0, Ubuntu 18.04).
`_mm256_zeroupper` unpredictably spoils local variables even when there's no other intrinsics used in the code.
`_mm256_zeroall` doesn't cause such errors at the same time having similar purpose and performance.

AVX v256_cleanup() fixed

---

modules/calib3d/src/calibration.cpp

This is a fix to the signature of static function
collectCalibrationData() and clean-up for #12772. Since fallback scheme
in calibration method selection is not used anymore. As an input
parameter, iFixedPoint should be passed by value according to the OpenCV
coding style guide.
Only the signature of the specific internal utility function is changed. No implementation logic is modified.

Fix signature of static function collectCalibrationData() in modules/calib3d/src/calibration.cpp

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/solvepnp.cpp
samples/cpp/tutorial_code/features2D/Homography/decompose_homography.cpp
samples/cpp/tutorial_code/features2D/Homography/homography_from_camera_displacement.cpp
samples/cpp/tutorial_code/features2D/Homography/panorama_stitching_rotating_camera.cpp
samples/cpp/tutorial_code/features2D/Homography/perspective_correction.cpp
samples/cpp/tutorial_code/features2D/Homography/pose_from_homography.cpp

Similar to `aruco::drawAxis`, it allows displaying the object frame from a pose estimation method.
Note that since `undistortPoints` has been moved into the calib3d module, `#include <opencv2/imgproc.hpp>` can be removed in `pose_from_homography.cpp` in master.

Add drawFrameAxes function

---

modules/gapi/include/opencv2/gapi/fluid/gfluidbuffer.hpp
modules/gapi/include/opencv2/gapi/gcompiled.hpp
modules/gapi/src/api/gcomputation.cpp
modules/gapi/src/backends/cpu/gcpubackend.hpp
modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/src/backends/fluid/gfluidbackend.hpp
modules/gapi/src/backends/fluid/gfluidbuffer.cpp
modules/gapi/src/backends/fluid/gfluidbuffer_priv.hpp
modules/gapi/src/compiler/gcompiled.cpp
modules/gapi/src/compiler/gcompiled_priv.hpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/src/compiler/gislandmodel.hpp
modules/gapi/src/compiler/passes/meta.cpp
modules/gapi/src/compiler/passes/passes.hpp
modules/gapi/src/executor/gexecutor.cpp
modules/gapi/src/executor/gexecutor.hpp
modules/gapi/test/gapi_fluid_test.cpp
modules/gapi/test/internal/gapi_int_recompilation_test.cpp

This new method allows to compile a G-API graph one and then adjust it
to new input size(s). The support is determined by the underlying backends
capabilities - if a `GCompiled` object has been produced with backends
supporting `reshape()`, adjustments are made; an exception is thrown
otherwise.
Currently only Fluid backend supports reshape capability, and CPU (OpenCV)
backend throws. OpenCV backend reshaping will be added later.

G-API: Introduce new `reshape()` API

---

modules/python/src2/gen2.py

This PR closes the input file containing the list of source files during the python wrapper generation.
At the moment this generates this warning:
`modules/python/bindings/..//src2/gen2.py:1181: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/dev/trunk/MMSTP/Sources/misc/OpenCV/build/modules/python_bindings_generator/headers.txt' mode='r' encoding='UTF-8'>`
This PR closes the input file containing the list of source files during the python wrapper generation and thus fixes the warning listed above.

Python wrapper generator: Fix closing input file

---

modules/highgui/src/window_cocoa.mm

the patch fixes the recently updated implementation (#12697); sometimes only the window titlebar was shown, without the window content.

fixed imshow on mac

---

cmake/OpenCVCompilerOptions.cmake

[Linux Debug (Ubuntu 14.04) build](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL_noICV_noSSE-lin64-debug/builds/197).

cmake: eliminate GCC4.x warnings

---

modules/imgcodecs/src/grfmt_tiff.cpp
modules/imgcodecs/test/test_tiff.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/538
I recently updated my local OpenCV version to 3.4.3 and found out that
I could not read my TIFF images related to my project. After debugging I
found out that there has been some static analysis fixes made
that accidentally have broken reading those black-and-white TIFF images.
Commit hash in which reading of mentioned TIFF images has been broken:
cbb1e867e5141412c62ff534def7f117e28e04e8
Basically the fix is to revert back to the same functionality that has been there before.
When black-and-white images are read bpp (bitspersample) is 1.
Without the case 1: this TiffDecoder::readHeader() function always return false.
PR fixes reading thresholded (black-and-white) TIFF images.
```
opencv_extra=3.4
```

Fix reading of black-and-white (thresholded) TIFF images

---

modules/core/misc/java/gen_dict.json
modules/java/generator/src/cpp/converters.cpp
modules/java/generator/src/cpp/converters.h

add rudimentary support for MatOfRotatedRect, so `Dnn.NMSBoxesRotated()` can be used with the east text detection.

java: add support for MatOfRotatedRect

---

modules/imgproc/src/templmatch.cpp

Avoid rounding errors when using CV_8U image in matchTemplate.
The result of TM_CCOEFF_NORMED is 0/0 when all pixels have the same value in matched area. However, "wndSum2 - wndMean2 == 0" may become "wndSum2 - wndMean2 > 0" because of rounding errors. If "fabs(num) < t" is true at the same time, we may get a unexpected value. Therefore, I give a proper threshold for the denominator.
**Here is my test code:**
Mat aim = imread("../images/aim2.png", IMREAD_GRAYSCALE);
Mat templ = imread("../images/templ0.png", IMREAD_GRAYSCALE);
Mat result;
matchTemplate(aim, templ, result, TemplateMatchModes::TM_CCOEFF_NORMED);
double minVal = 0.0f;
double maxVal = 0.0f;
Point minLoc;
Point maxLoc;
minMaxLoc(result, &minVal, &maxVal, &minLoc, &maxLoc);
cout << maxLoc << endl;
A wrong result comes with the …

fix matchTemplate for imgproc module

---

modules/highgui/src/window_w32.cpp

resolves #13049
relates #11714
avoid calling GetMessage()  (which will make it stall), if we have an "inifinite" timeout, but don't have a valid window handle any more

highgui: fix broken waitKey() condition in window_w32

---

modules/highgui/include/opencv2/highgui.hpp

since it is using std::string in opencv4,  NULL is no more a valid option
```
**WIP**
```

docs: remove NULL strings from highgui.hpp

---

modules/highgui/src/window_w32.cpp

Building OpenCV with MinGW-w64
resolves #13016 
Replaced the use *strcpy_s* and *strcat_s*, which are available only on MSVC, in file *window_w32.cpp* with *strcpy* and *strcat* usage. This was wrapped in a conditional compilation and take effect only when built with MinGW.

Replaced strcpy_s, strcat_s for MinGW builds.

---

modules/calib3d/src/circlesgrid.cpp
modules/calib3d/src/circlesgrid.hpp
modules/calib3d/test/test_chesscorners.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/542
During the cluster-based detection of circle grids, the detected circle
pattern has to be mapped to 3D-points. When doing this the width (i.e.
more circles) and height (i.e. less circles) of the pattern need to
be identified in image coordinates.
Until now this was done by assuming that the shorter side in image
coordinates (length in pixels) corresponds to the height in 3D.
This assumption does not hold if we look at the pattern from
a perspective where the projection of the width is shorter
than the projection of the height. This in turn lead to misdetections in
although the circle pattern was clearly visible.
Instead count how many circles have been detected along two edges of the
projected quadrangle and use the one …

CircleGridClusterFinder: map circle pattern width and height correctly

---

modules/gapi/CMakeLists.txt
modules/gapi/cmake/standalone.cmake

Added Standalone.cmake to simplify standalone build. (Standalone.cmake should be included into user CMakeLists.txt to add fluid target to the project)

G-API: Added Standalone.cmake

---

CMakeLists.txt

backport #12896
Enabled by default in OpenCV 3.4 (but it is not reliable - limited set of configurations is supported)
```
buildworker:iOS=macosx-1
```

cmake: OPENCV_GENERATE_PKGCONFIG

---

modules/videoio/src/cap_dshow.cpp

This PR adds support for Y16 cameras (and some others) using the DirectShow library on Windows. In the process it also fixes a bug where changing the FOURCC property has no effect. This code is based on a modified patch from e-Con systems, published here with their permission (see [here](https://www.e-consystems.com/blog/camera/accessing-see3cam-custom-format-with-opencv/)).
Given the discussion here: https://github.com/opencv/opencv/pull/7196 I've tried to keep the same behavior:
- Cameras still open in RGB24 mode by default
- If the user selects Y16 via `CAP_PROP_FOURCC`, DirectShow retrieves a 16-bit image, but it is implicitly converted to a grey RGB image and returned. I bit-shift the image for the conversion.
- If the user sets `CV_CAP_PROP_CONVERT_RGB` to `false`, and the camera is …

Add support for changing fourcc and support mono formats (e.g. Y8, Y16) in DirectShow

---

samples/python/digits_video.py

issue [from answers.opencv.org](http://answers.opencv.org/question/202597/wrong-predictions-from-opencv-sample-digitspy/)
(the [test](https://github.com/opencv/opencv/blob/master/modules/python/test/test_digits.py#L89) has it correct)

samples: fix digits_video.py

---

modules/dnn/src/dnn.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/test/test_tf_importer.cpp
samples/dnn/tf_text_graph_faster_rcnn.py

resolves https://github.com/opencv/opencv/issues/13050
resolves https://github.com/opencv/opencv/issues/12996
Fixed OpenCL optimization for eltwise and convolution layers fusion. Number of fused layers across all the tests before PR: 136. Number of fusions with this PR: 142 (+6).
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/545
No efficiency regressions observed:
(median time for a single input forward pass)
CPU: Intel&reg; Core&trade; i7-6700K CPU @ 4.00GHz x 8
GPU: Intel&reg; HD Graphics 530 (Skylake GT2)
Test name | 3.4 branch | With a PR | x-factor
----|----|----|----
AlexNet::OCV/OCL                                 | 18.537 |   18.890    | 0.98   |
AlexNet::OCV/OCL_FP16                            | 12.725 |   12.706    | 1.00   |
DenseNet_121::OCV/OCL …

Update text graphs generator for Faster-RCNN networks from TensorFlow

---

modules/core/src/sum.cpp
modules/core/src/umatrix.cpp

Workaround to avoid OpenCL runtime crashing due large amount of kernel events.
relates #13087
<cut />
One of possible Linux crash point:
https://github.com/intel/compute-runtime/blob/18.33.11309/runtime/os_interface/linux/drm_buffer_object.cpp#L167
```
```

OCL: core: run "reduce" kernels in synchronous mode

---

modules/core/include/opencv2/core/persistence.hpp
modules/core/test/test_io.cpp

resolves #11934
resolves #8148
Adds direct read and write support for the Matx class to FileStorage. Internally calls the read and write functions for the Mat class, so output format is identical and can be used interchangeably with Mat data types (so there will be no change to previous FileStorage output). If the read is empty, the default Matx (all zeros) is returned (similar to Vec), otherwise the data is passed to the Matx constructor. This may then throw an exception if the format or size are not correct.

Support for Matx read/write by FileStorage

---

modules/core/include/opencv2/core/cvdef.h
modules/core/include/opencv2/core/mat.hpp
modules/features2d/include/opencv2/features2d.hpp

Resolves Pedantic warning of the kind: `extra ‘;’ [-Wpedantic]` (no open issue about it that I am aware of)
When enabled all warnings, it appears quite often a Pedantic warning of this kind:
```
/usr/local/include/opencv4/opencv2/features2d.hpp:1202:32: warning: extra ‘;’ [-Wpedantic]
CV_ENUM_FLAGS(DrawMatchesFlags);
```
And analogously for every time `CV_ENUM_FLAGS` is used. This is quite annoying, so I have fixed it.
Thanks!

Fixed pendantic warning

---

doc/tutorials/core/how_to_scan_images/how_to_scan_images.markdown

- cv::at => cv::Mat::at()
- removed unnecessary `@ref`
[Build messages](http://pullrequest.opencv.org/buildbot/builders/master_docs-lin64/builds/10630/steps/make%20doxygen/logs/warnings%20%283%29).

docs: fix links

---

modules/features2d/src/feature2d.cpp
modules/python/test/test_stitching.py
modules/stitching/include/opencv2/stitching.hpp
modules/stitching/include/opencv2/stitching/detail/matchers.hpp
modules/stitching/misc/python/pyopencv_stitching.hpp
modules/stitching/perf/opencl/perf_stitch.cpp
modules/stitching/perf/perf_estimators.cpp
modules/stitching/perf/perf_matchers.cpp
modules/stitching/perf/perf_precomp.hpp
modules/stitching/perf/perf_stich.cpp
modules/stitching/src/matchers.cpp
modules/stitching/src/precomp.hpp
modules/stitching/src/stitcher.cpp
modules/stitching/test/test_matchers.cpp
modules/stitching/test/test_precomp.hpp
samples/cpp/stitching.cpp
samples/cpp/stitching_detailed.cpp
samples/python/stitching.py

I have received a very little feedback on evolution proposal #11039. I have decided to come with some code, to start the discussion. Here are some minimal changes in the stitching module, that I think should go to OpenCV 4.0. Large parts of the evolution proposal are not implemented and I'm awaiting further feedback.
```
force_builders=linux,Linux OpenCL,windows,macosx,docs,Custom,Win64 OpenCL
**WIP**
```

[evolution] Stitching for OpenCV 4.0

---

modules/core/src/persistence_cpp.cpp
modules/core/test/test_io.cpp

To align 3.4 with https://github.com/opencv/opencv/pull/13123 considering https://github.com/opencv/opencv/pull/12641/files#r221050674

Add a test for FileNode::keys()

---

modules/video/src/dis_flow.cpp
modules/video/src/variational_refinement.cpp

resolves opencv/opencv_contrib#1894
|Name of Test|before|after|before vs after (x-factor)|
|perf::DenseOpticalFlow_DIS::("PRESET_FAST", 640x480)|14.602|13.442|1.09|
|perf::DenseOpticalFlow_DIS::("PRESET_FAST", 1280x720)|40.623|36.206|1.12|
|perf::DenseOpticalFlow_DIS::("PRESET_FAST", 1920x1080)|86.579|77.698|1.11|
|perf::DenseOpticalFlow_DIS::("PRESET_MEDIUM", 640x480)|53.288|41.514|1.28|
|perf::DenseOpticalFlow_DIS::("PRESET_MEDIUM", 1280x720)|177.925|137.496|1.29|
|perf::DenseOpticalFlow_DIS::("PRESET_MEDIUM", 1920x1080)|436.096|332.447|1.31|
|perf::DenseOpticalFlow_DIS::("PRESET_ULTRAFAST", 640x480)|7.564|6.485|1.17|
|perf::DenseOpticalFlow_DIS::("PRESET_ULTRAFAST", 1280x720)|23.024|19.151|1.20|
|perf::DenseOpticalFlow_DIS::("PRESET_ULTRAFAST", …

Fix missing intrin.hpp header in dis_flow.cpp

---

CMakeLists.txt

avoid using of `ENABLE_NEON` / `ENABLE_VFPV3` flags
resolves #13114

cmake: fix Android features detection

---

modules/videoio/src/cap_v4l.cpp

relates #12893
/cc @aleksey-nikolaev @paroj

videoio(v4l): turn off normalization of V4L properties

---

doc/py_tutorials/py_imgproc/py_transforms/py_fourier_transform/py_fourier_transform.markdown

for integer division and filter symmetry.
resolves #13139 
Changes the second snippet of example code lines 2, 3, and 6.
- Changes the calculation of `crow` and `ccol` to use integer division since they're used as indices for slicing.
- Changes the slicing on line 3 to have symmetry.
- Change call from `np.abs()` to `np.real()` as a symmetric filter from the previous change will cause a real value to be calculated in the inverse transform.
```
```

doc(tutorial_py_fourier_transform): Correct errors in tutorial

---

modules/dnn/src/dnn.cpp

resolves https://github.com/opencv/opencv/issues/13159
The bug is introduced in https://github.com/opencv/opencv/pull/13065
```
```

Fix a bug with OpenVINO backend

---

modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/elementwise_layers.cpp

[See also](https://github.com/opencv/opencv/pull/13115#issuecomment-438047854).
Fix intrinsics code.
Add `"layers_common.hpp"` header otherwise `#if CV_SIMD128`is not detected on my computer. 
Remove what should be an useless include.

Fix batch_norm_layer intrinsics code

---

modules/imgproc/src/morph.cpp
modules/imgproc/test/ocl/test_filters.cpp

'ksize' is not updated with 'kernel'
resolves #13105
```
```

imgproc(ocl): fix morph generic filter checks

---

modules/dnn/src/vkcom/src/op_pool.cpp

Fix a bug with Vulkan's max pooling considering optimization from https://github.com/opencv/opencv/pull/13065
```
test_module=dnn
tests_filter=*
**WIP**
```

Fix Vulkan's max pooling in case of no output indices

---

samples/python/letter_recog.py

The load() function returns a new object, and as such does not use the one it is called on. This commit updates the uses of model.load in this program so it will work as intended and not throw an error.
Fixed use of model.load instances in letter_recog.py

Fixed use of model.load instances in letter_recog.py

---

samples/python/video.py

Workaround to handle drive letter in parameters values
Failed case:
```
synth:bg=D:\test\opencv\sources\samples\python/../..\samples/data/lena.jpg:noise=0.05
```

samples(python): fix video parameters

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/551
This tiny patch adds support for parsing ONNX files containing "ConvTranspose" layer. The existing Deconvolution implementation is capable of handling those, only the mapping was missing.
```
opencv_extra=add_transposedConv_onnx
```

DNN: Add support for ConvTranspose when parsing ONNX

---

modules/highgui/src/window_QT.cpp

broken in 11eafca3e2a4cbc62f1309d25db0ea3ed9a6ea8e

highgui: Qt - restore convertscale semantics

---

modules/core/src/batch_distance.cpp
modules/features2d/test/test_matchers_algorithmic.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/543
resolves #11855 
```
```

resolve #11855

---

modules/core/src/copy.cpp

resolves #13180
since none of the implemented branches can handle more than 2 dimensions,
move the dims() check from the CV_OCL_RUN up, so it gets checked for all of them

core: move dims() check to the top in copyMakeBorder()

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/imgproc/src/bilateral_filter.cpp

Updated bilateralFilter handling of NaN values to improve accuracy for CV_32F matrices
Unrolled bilateralFilter neighbor processing loop
```
```

NaN handling for bilateralFilter

---

modules/features2d/src/draw.cpp

resolves #13219
Change the random colour generation, such that the alpha channel is set to 255, instead of 0.

Resolve #13219: Make randomly generated colours opaque.

---

modules/core/src/parallel.cpp

introduced by commit 4e629000095779ae8f544ddd4de77633680a3db9
resolves #13207
Through fixed, but I have no idea about the different behavior between running in main thread and a separate thread due to I don't familiar with OpenMP.

fix numThreadsMax for OpenMP

---

modules/highgui/src/window_w32.cpp

related: #13216 (it's only a partial fix)
similar to #13184
also remove the unused `origin` variable in cvShowImage (the origin is constant [here](https://github.com/opencv/opencv/pull/13184))

highgui: restore convertscale semantics in window_w32.cpp

---

modules/core/src/utils/filesystem.cpp

On FreeBSD I was getting the following error. It appears some preprocessor directives were missing.
```
/root/opencv_bram/modules/core/src/utils/filesystem.cpp:125:17: error: variable has incomplete type 'struct stat'
struct stat stat_buf;
```

Fixed build on FreeBSD

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp

documentation about the newly supported PFM file formats (cv::imread and cv::imwrite)

updated documentation for imread and imwrite (added pfm image format)

---

modules/core/include/opencv2/core/types_c.h

Fix a missing part of a check for the cvUplImage() function. If compiling in c, the compiler could tried to use the c++ constructer and return an error.

Fix missing check part (defined(__cplusplus)) in header types_c.h

---

modules/gapi/cmake/init.cmake

`BUILD_opencv_gapi=OFF` is not enough.
CMake option: `WITH_ADE=OFF`.
resolves #12856

cmake: allow to disable ADE build

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_backends.cpp

* Fix updated Emotion_ferplus model in ONNX format
* Reduce inputs for OpenPose tests in 8 times to speedup tests.
```
```

Fix ONNX's emotion_ferplus model.

---

modules/androidcamera/src/camera_activity.cpp

resolves #11699 Missing std header
This Pull Request add `<functional>` header to fix #11699, which is a compile error when we build androidcamera module on 2.4 branch.
```
buildworker:Linux x64 Debug=linux-1
```

androidcamera: add a missing header.

---

modules/dnn/src/vkcom/src/common.hpp
modules/dnn/src/vkcom/src/context.cpp
modules/dnn/src/vkcom/src/op_base.cpp

Use a global dedicated mutex to make sure initialize once and
protect command buffer pool and queue.
Signed-off-by: Wu Zhiwen <zhiwen.wu@intel.com>
```
```

dnn/Vulkan: make thread safe

---

3rdparty/carotene/hal/CMakeLists.txt

resolves #13238 
`ENABLE_NEON` is deprecated now, but it was used in Carotene library build to detect NEON.

Fixed NEON detection in Carotene build

---

modules/core/include/opencv2/core/persistence.hpp
modules/core/src/persistence.cpp

Fixed problem with symbol compatibility between GCC 5-6 and Clang.
`FileNode::operator string() const `  is generated differently and causes link-time errors.
https://www.gnu.org/software/gcc/gcc-7/porting_to.html - "Mangling change for conversion operators"

Made FileNode::operator string inline

---

modules/core/include/opencv2/core/hal/intrin_cpp.hpp

```
/opencv/modules/core/include/opencv2/core/hal/intrin_cpp.hpp:691:1: 
warning: this 'for' clause does not guard... [-Wmisleading-indentation]                                                    
for (int i = 0; i < n; i++)                                                      
^~~                                                                    
/opencv/modules/core/include/opencv2/core/hal/intrin_cpp.hpp:693:5: 
note: ...this statement, but the latter is misleadingly indented as if it is 
guarded by the 'for'            
return c;                                                   
^~~~~~ 
```

Fixed misleading indentation warning in intrin_cpp.hpp

---

platforms/ios/build_framework.py

This Pull Request changes the `ios/build_framework.py` script to allow specifying architectures to be used to build OpenCV for iPhoneSimulator platform, via `--iphonesimulator_archs` flag.
Its default value is the same as was hardcoded before, so this change is backwards-compatible with any existing setup.

Add ability to specify iPhoneSimulator build ARCHS

---

modules/highgui/src/precomp.hpp
modules/highgui/src/window_QT.cpp
modules/highgui/src/window_cocoa.mm
modules/highgui/src/window_gtk.cpp
modules/highgui/src/window_w32.cpp
modules/highgui/test/test_gui.cpp

resolves #13216
related #13184
* adds a single function similar to removed one to rescale pixel values and swap B and R channels before showing image in the window
* rewrote highgui test to cover different image types passed to `imshow`

Restored function to rescale pixel values before imshow

---

modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/sse_utils.hpp

This PR fixes compilation errors under Ubuntu 16.04 and gcc 5.4.0 which does not accept `const int` as intrinsic immediates. Related to #10136.

Fix for gcc 5.4.0 compilation errors

---

modules/highgui/test/test_gui.cpp

resolves #13344
Restored longer delay in highgui test to fix the test on slower platforms (valgrind, debug, high load).
4 sec -> 18 sec

Restored 500ms delay in highgui test

---

modules/core/src/va_intel.cpp

resolves #12662
`CV_Check` macro expansion for unsupported types (unsigned int, int)

Fixed compilation with VA-interop on 32-bit platforms

---

modules/imgproc/include/opencv2/imgproc.hpp

This PR fixes a small error in LineIterator example code in documentation.

Fix error in LineIterator example code in doc

---

modules/features2d/include/opencv2/features2d.hpp
modules/features2d/src/brisk.cpp
modules/features2d/test/test_brisk.cpp

Allows setting threshold and octaves parameters after creating a brisk object. These parameters do not affect the initial pattern initialization and can be changed later without re-initialization.
I added these locally to avoid re-running the full initialization (which takes quite a long time) when changing parameters. Maybe this is useful to the rest of the community.
resolves #11527
Adds get/set functions for BRISK parameters.
```
force_builders=linux
```

 Get/Set functions for BRISK parameters, issue #11527

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/cap_librealsense.cpp
modules/videoio/src/cap_librealsense.hpp

This pullrequest will fix bug and add support get properties of VideoCapture_LibRealsense.
* Fix to apply settings by passing <code>rs2::config</code> to <code>rs2::pipeline::start()</code>.
* Add support some basic properties to <code>cv::VideoCapture::get()</code>.
```cpp
cv::VideoCapture capture( cv::VideoCaptureAPIs::CAP_INTELPERC );
if( !capture.isOpened() ){
return -1;
}
// Image
capture.get( cv::CAP_INTELPERC_IMAGE_GENERATOR + cv::CAP_PROP_FRAME_WIDTH );
capture.get( cv::CAP_INTELPERC_IMAGE_GENERATOR + cv::CAP_PROP_FRAME_HEIGHT );
capture.get( cv::CAP_INTELPERC_IMAGE_GENERATOR + cv::CAP_PROP_FPS );
// Depth
capture.get( cv::CAP_INTELPERC_DEPTH_GENERATOR + cv::CAP_PROP_FRAME_WIDTH );
capture.get( cv::CAP_INTELPERC_DEPTH_GENERATOR + cv::CAP_PROP_FRAME_HEIGHT );
capture.get( …
```

Fix VideoCapture_LibRealsense

---

cmake/OpenCVCompilerOptimizations.cmake

Required flags are not added (for example via USE_NEON / ENABLE_NEON).
resolves #13374
```
test_modules=none
buildworker:Linux x64=linux-4
buildworker:Linux x64 Debug=linux-4
ci_branch=3.4
```

cmake: fix compiler flags (CPU_BASELINE_REQUIRED=xxx + CPU_BASELINE=DETECT)

---

modules/stitching/perf/perf_matchers.cpp

<cut/>
Error message:
```
[ RUN      ] match_bestOf2Nearest.bestOf2Nearest/1, where GetParam() = "orb"
Expected: 
[-277.7071733171182;
5.55526061248414;
1]
Actual:
[-278.7399608679396;
5.604726888851799;
1]
/build/precommit_custom_linux/opencv/modules/ts/src/ts_perf.cpp:570: Failure
Failed
Difference (=1.0327875508214106) between argument1 "dist" and expected value is greater than 1
params    =       "orb"
termination reason:  reached maximum number of iterations
bytesIn   =      32000
bytesOut  =          0
samples   =          1
outliers  =          0
frequency = 1000000000
min       =   10131296 = 10.13ms
median    =   10131296 = 10.13ms
gmean     =   10131296 = 10.13ms
gstddev   = 0.00000000 = 0.00ms for 97% dispersion interval
mean      =   10131296 = 10.13ms
stddev    =          0 = …
```

stitching(perf): increase threshold of transform vector

---

modules/js/src/embindgen.py
modules/js/test/test_photo.js
modules/js/test/tests.html
modules/photo/CMakeLists.txt
platforms/js/build_js.py

resolves #13299 
1. Enable the build flag in build_js.py.
2. Append js into WRAP list of photo’s CMakefiles.txt
3. Add photo module's API into JS API whitelist (embindgen.py)
TODO:
```
**WIP**
force_builders=Docs,Custom
```

Enable Javascript bindings for photo module.

---

modules/features2d/include/opencv2/features2d.hpp

python: don't use 'cv2.' in documentation

---

platforms/ios/build_framework.py
platforms/osx/build_framework.py

This Pull Request changes `build_framework.py` script in `platforms/ios` and `osx` to allow specifying that `OpenCV.framework` should be built with nonfree modules enabled, via `--enable_nonfree` boolean flag. It's false by default, thus preserves backwards compatibility.
Resolves #13417.

Add ability to build iOS and macOS frameworks with nonfree modules

---

modules/videoio/src/cap_msmf.cpp

On windows 7, MinCore_Downlevel does not work correctly. However, the only API used was QISearch, which can be found in Shlwapi.
resolves #12010
This is a fix that should be backported to 3.4 as well. Should that be a separate PR, or done after merging?

Remove MinCore_Downlevel, replace with Shlwapi

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

* Compute shapes of intermediate blobs in ONNX importer
* Perform constant operations from ONNX graphs during import.
* Shape: returns a shape of input blob
* Gather: slicing specific dimension
* Concat over constants
resolves https://github.com/opencv/opencv/issues/12869
resolves https://github.com/opencv/opencv/issues/13303
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/558

Operate with shapes in ONNX models

---

modules/imgproc/src/color_rgb.cpp
modules/imgproc/src/opencl/color_rgb.cl

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/560
* All conversions in `color_rgb.cpp` rewritten to wide universal intrinsics
* Platform-specific code removed
* `mRGBA2RGBA`: saturation added
master branch has different RGB2Gray coefficients so there will be separate PR
<cut/>
<details>
<summary>Baseline AVX2</summary>
|Name of Test|rgb initial avx2|rgb wide avx2|rgb wide avx2 vs rgb initial avx2 (x-factor)|
|cvtColor8u::Size_CvtMode::(127x61, COLOR_BGR2BGR555)|0.011|0.004|3.09|
|cvtColor8u::Size_CvtMode::(127x61, COLOR_BGR2BGR565)|0.011|0.003|3.19|
|cvtColor8u::Size_CvtMode::(127x61, COLOR_BGR2GRAY)|0.006|0.004|1.55|
|cvtColor8u::Size_CvtMode::(127x61, COLOR_BGR5552BGR)|0.007|0.003|2.20|
|cvtColor8u::Size_CvtMode::(127x61, …

RGB to/from Gray rewritten to wide intrinsics

---

modules/videoio/src/cap_images.cpp

broken in 11eafca3e2a4cbc62f1309d25db0ea3ed9a6ea8e
relates #13060

videoio: fix CAP_IMAGES

---

modules/stitching/perf/perf_stich.cpp
modules/stitching/src/exposure_compensate.cpp

**Please read issue #13399 first**
First commit adds a performance test. It showcases a panorama-type stitching, using BlocksGainCompensator with different block size. As the block size get smaller, computation time explodes, fast.
The second commit resolves the first part of issue #13399, ignoring blocks that do not overlap with any other.
The third commit leverage Eigen if available to resolve the equation system in a more optimized fashion.
Performance test results: "master" is self-explanatory, "optimized" uses the second commit, "eigen_llt" uses the second and the third.
```
Name of Test              master   optimized  eigen   optimized    eigen   
llt        vs        llt    
master       vs    
(x-factor)   master  
(x-factor) …
```

Optimize exposure compensation

---

modules/core/include/opencv2/core/hal/intrin_vsx.hpp

resolves #13442
````
pw_compilers=gcc-4.9, gcc-5, gcc-6, gcc-7, clang-4, clang-5, clang-6, power9_gcc-4.9, power9_gcc-5, power9_gcc-6, power9_gcc-7, power9_clang-4, power9_clang-6
pw_cmake_definitions=WITH_EIGEN:OFF
````

core:vsx fix build failure on GCC<=6

---

modules/imgproc/src/deriv.cpp

Resolves #13375
This pullrequest replaces hard coded delta value (0) in `cv::Sobel` and `cv::Scharr` functions to `delta`.

Fix Scharr and Sobel functions

---

modules/core/src/ocl.cpp

used by OpenCV
relates #13414 #13108

core(ocl): add parameter to limit device max workgroup size

---

cmake/OpenCVDetectCUDA.cmake

resolves #13465
Fixed the fact the Turing option wasn't added to `_gerenations` in `cmake/OpenCVDetectCUDA.cmake`.

Added Turing to the _generations list.

---

modules/features2d/misc/java/test/Features2dTest.java
modules/java/generator/gen_java.py
modules/python/src2/hdr_parser.py
samples/java/tutorial_code/features2D/feature_flann_matcher/SURFFLANNMatchingDemo.java
samples/java/tutorial_code/features2D/feature_homography/SURFFLANNMatchingHomographyDemo.java

resolves https://github.com/opencv/opencv/issues/12963
docs: https://pullrequest.opencv.org/buildbot/export/pr/13471/docs/javadoc/index.html
Current output for Features2d.java:
```java
// C++: enum DrawMatchesFlags
public static final int
DrawMatchesFlags_DEFAULT = 0,
DrawMatchesFlags_DRAW_OVER_OUTIMG = 1,
DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS = 2,
DrawMatchesFlags_DRAW_RICH_KEYPOINTS = 4;
...
//
// C++:  void cv::drawKeypoints(Mat image, vector_KeyPoint keypoints, Mat& outImage, Scalar color = Scalar::all(-1), DrawMatchesFlags flags = DrawMatchesFlags::DEFAULT)
//
//javadoc: drawKeypoints(image, keypoints, outImage, color, flags)
public static void drawKeypoints(Mat image, MatOfKeyPoint keypoints, Mat outImage, Scalar color, int flags)
{
Mat keypoints_mat = keypoints; …
```

Try to fix "enum struct" wrapping for Java

---

modules/gapi/src/backends/ocl/goclbackend.cpp

Fixes issues with multiple nodes subgraphs for OCL/GPU GAPI backend

GAPI OCL backend internal UMat size fix

---

modules/videoio/src/cap_v4l.cpp

videoio: v4l: Fix new frame size applying in v4l.
1. Fix variable name in `if` expression in CvCaptureCAM_V4L::icvSetFrameSize

videoio: Fix new frame size applying in v4l.

---

cmake/OpenCVDetectApacheAnt.cmake
modules/java/jar/CMakeLists.txt
modules/java/jar/build.xml.in

resolves #13434
Usage:
```
cmake -DOPENCV_JAVA_SOURCE_VERSION=1.5 -DOPENCV_JAVA_TARGET_VERSION=1.8 ...
cmake --build . --target opencv_java_jar
```

cmake(java): add OPENCV_JAVA_SOURCE_VERSION / OPENCV_JAVA_TARGET_VERSION

---

modules/dnn/src/dnn.cpp

dnn: add Vulkan device check for BackendRegistry

---

modules/stitching/src/matchers.cpp

This pullrequest fixes the initial values bug of `pairwise_matches[xxx].confidence` in `FeaturesMatcher::operator ()` of `modules/stitching/src/matcher.cpp` when `Stitcher::stitch()` is called multiple times for different input images and there are images that fail to compute a validate Homography matrix.

fix initial values bug for `pairwise_matches[xxx].confidence`

---

modules/highgui/src/window_w32.cpp

When looking closely, there's a gray "gutter" around the displayed image. Since it's just 1 pixel wide, it never showed up on the bottom and right borders between image and window chrome.
That gutter is now visible properly. Perhaps it would make sense to remove it entirely (set to zero in `icvCalcWindowRect`). Previously that _would_ have cut off the last row and column of an image.
There has been no issue for this and it fixes no bugs (to my knowledge). This is purely cosmetic.

Off-by-ones in windows/GDI window calculations

---

modules/highgui/src/window_w32.cpp

resolves #4990
in `HighGUIProc` case `WM_MOUSEMOVE` as well as in `MainWindowProc` case `WM_MOUSEWHEEL`, window coordinates are turned into image coordinates. Unfortunately, the size of the image is stored nowhere explicitly and generally. It is determined by querying (`icvGetBitmapData`) the GDI bitmap object associated with the window. In the standard GDI case, that's the original image.
In the OpenGL case, that is instead the whole window (including chrome). The _actual_ image is only stored in `window->glDrawData`, which is a pointer to `cv::ogl::Texture2D` and to be used by the drawing callback to OpenGL.
I've added code to determine image size according to situation.

fix for #4990: correct calculation of image coordinates from window coordinates

---

modules/videoio/cmake/detect_ffmpeg.cmake

resolves #13533
Find each FFmpeg library manually using results provided by pkg-config
[build](https://pullrequest.opencv.org/buildbot/builders/master_etc-ffmpeg-master-lin64/builds/101) :heavy_check_mark:

Fixed standalone FFmpeg search with pkg-config

---

modules/stitching/include/opencv2/stitching/detail/exposure_compensate.hpp
modules/stitching/perf/perf_stich.cpp
modules/stitching/src/exposure_compensate.cpp

Adds ChannelsCompensator and BlocksChannelsCompensator. The idea is to compensator each channel independantly. This is necessary if the images we want to stitch together do not have the same white balance.
For instance, I used three images of the "boatN.jpg" samples from opencv_extra, and modified the white balance of each of those. I then compared the result using the 4 compensators.
[Base images](https://ibb.co/y53HG7s)
1st one is original.
2nd one is colder.
3rd one is warmer.
[Stitching result](https://ibb.co/yVXzNfH)
1st one is `GainCompensator`
2nd one is `BlocksGainCompensator`
3rd one is `ChannelsCompensator`
4th one is `BlocksChannelsCompensator`
Commits e03ce35, 6ae003e and 833212e are quite simple.
5eb7d8a  brings some deep changes in the `BlocksGainCompensator`. To avoid code …

Channels exposure compensators

---

modules/stitching/include/opencv2/stitching/detail/exposure_compensate.hpp
modules/stitching/src/exposure_compensate.cpp

Fix issue #13563.
Uninitialized conditional branching was due to the `updateGain` attribute that was not initialized in the constructor of the class declaring it.
I fixed the behavior by initializing the attibute, and removed all `setUpdateGain(true)` that were called in various locations as they are not needed anymore.
EDIT: I could not rename the `updateGain` attribute to keep source compatibility as this attribute is only protected

Fixed uninitialized value 

---

modules/core/src/merge.cpp
modules/core/test/test_mat.cpp

The merge of the array of 3channel mat gives the wrong result on a particular input.<br/>
When an array of mat entering as input type If each Mat is not a single channel, but array of three or four ```Mat```'s of the three channels is input, the ```ipp_merge()``` call will result in an incorrect merge.<br/>
```ipp_merge ()``` seems to have been implemented assuming that the ```Mat``` channels are all 1 channel.
Therefore, we must move the ```ipp_merge()``` call below the ```if (! Allch1)``` branch to work properly.
```cpp
Mat src1(2, 2, CV_8UC3, Scalar::all(1));
Mat src2(2, 2, CV_8UC3, Scalar::all(2));
Mat src3(2, 2, CV_8UC3, Scalar::all(3));
Mat src_arr[] = { src1, src2, src3 };
Mat dst;
merge(src_arr, 3, dst);
cout << dst << endl;
```

Fix a bug in cv :: merge when array of 3-channel mat is input

---

modules/stitching/include/opencv2/stitching/detail/exposure_compensate.hpp
modules/stitching/src/exposure_compensate.cpp

Currently, the BlocksCompensators compute exposure gains for each block, then filter them twice by applying a separable filter (I have been able to find this number as "good value" in the literature as well).
This PR adds the ability to change the number of times the filter is applied. I mostly use this to disable the filtering operation, but there would be no point in limiting that option to a boolean.

Stitcher: Setter/getter for number of gain filtering iterations

---

modules/core/include/opencv2/core/cvdef.h

resolves #13552 
CV_XADD will not use `__c11_atomic_fetch_add` (clang exclusive) if `__INTEL_COMPILER` is defined.

Fix improper defining of CV_XADD when using Intel C++ on Mac

---

modules/stitching/src/exposure_compensate.cpp

If non-overlapping images are fed to `GainCompensator`, an assertion fail occurs.
This PR makes sure that when non-overlapping images are fed to `GainCompensator`, the calculated gains are all 1, and no error occurs.
NOTE: This may solve #13582

Do not compute gains when no images overlap

---

modules/stitching/include/opencv2/stitching/detail/exposure_compensate.hpp
samples/cpp/stitching_detailed.cpp

- Added getter and setter for block size of `BlocksCompensator`
- Added options 'channels' and 'channels_blocks' for exposure compensator methods.
- Added options for AKAZE features.
- Added options for selecting the block size of a 'gain_blocks' and 'channels_blocks' methods.
- Added options for selecting the number of image feed for exposure compensators.
- Added options for selecting the number of gain filtering iterations for 'gain_blocks' and 'channels_blocks' methods.
- Default features fallback from SURF to ORB if SURF is not available.
- Added a few logs for more details about times.

Improve stitching detailed

---

modules/dnn/src/layers/convolution_layer.cpp

Add a error message for convolutional layer in case of wrong input channels (most frequent is BGRA instead of BGR).
```python
net = cv.dnn.readNet('opencv_face_detector.caffemodel', 'opencv_face_detector.prototxt')
inp = np.random.standard_normal([1, 4, 300, 300]).astype(np.float32)
net.setInput(inp)
out = net.forward()
```
```
File "run.py", line 8, in <module>
out = net.forward()
cv2.error: OpenCV(3.4.5-dev) /path/to/opencv/modules/dnn/src/layers/convolution_layer.cpp:263: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 4 in function 'getMemoryShapes'
```

Add a text message for Convolution layer's input channels check

---

modules/dnn/src/torch/THGeneral.cpp

malloc.h should not be needed anymore, see #6270

dnn: remove malloc.h include

---

modules/gapi/src/api/gcall.cpp
modules/gapi/src/compiler/gmodelbuilder.cpp

This pullrequest fixes GCall issue due to wrong usage in unrollExpr in case of multi-threaded environment. FIXME added to address the need to improve current code to ensure no such problem occurs in future.

GAPI: fix GCall misuse in unrollExpr

---

modules/cudaoptflow/src/farneback.cpp
modules/cudaoptflow/test/test_optflow.cpp
modules/video/src/optflowgf.cpp

- Before this PR, following tests failed on some platform.
CUDA_OptFlow/FarnebackOpticalFlow.Accuracy/19
CUDA_OptFlow/FarnebackOpticalFlow.Accuracy/23
- The algorithm now recognizes the OPTFLOW_USE_INITIAL_FLOW flag.
Previously, when the flag was set, it did not use the flow data
passed as input, instead used some garbage data in memory.
- More strict test limit.
- Related #12895 
```
```

Fix Farneback Optical Flow Algorithm

---

samples/dnn/models.yml

it is used in [the tutorial](https://docs.opencv.org/4.0.0/d5/de7/tutorial_dnn_googlenet.html), and the mean/size/model, etc. information should be easy to find, and used with the "zoo" option.

dnn/samples: add googlenet to model zoo

---

3rdparty/openvx/hal/openvx_hal.cpp
3rdparty/openvx/include/ivx.hpp
modules/imgproc/src/median_blur.cpp

resolves #13588
resolves #13634
* remove usage of CV_USRTYPE1 (ivx.hpp)
* resolve a namespace issue (median_blur.cpp)
* fix the  MAGIC_SCALE constant for windows compilers (including mingw) (openvx_hal.cpp)

fix openvx wrappers

---

samples/dnn/tf_text_graph_faster_rcnn.py

resolves https://github.com/opencv/opencv/issues/13237

Faster-RCNN from TensorFlow with dilated convolutions

---

modules/core/test/test_eigen.cpp

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/2_4-win32-vc14/builds/10685) message:
```
Difference between original eigen vectors matrix and result: 0.0102803
Maximum allowed difference: 0.01
```
```
```

core(test): relax eigen eps value: 0.01 -> 0.02

---

modules/cudaimgproc/src/cuda/clahe.cu
modules/cudev/include/opencv2/cudev/block/scan.hpp
modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp
modules/cudev/include/opencv2/cudev/warp/scan.hpp
modules/cudev/include/opencv2/cudev/warp/shuffle.hpp
modules/cudev/test/test_scan.cu

For warp shuffle functions introduced from CUDA 9, giving full mask may cause the program to hang on some devices. This PR tries to fix this for `__shfl_up_sync` function. Without this PR, following tests hang with RTX 2080 Ti.
```
./bin/opencv_test_cudev --gtest_filter=*Integral*
./bin/opencv_test_cudaarithm --gtest_filter=*Integral*
./bin/opencv_test_cudaimgproc --gtest_filter=*CLAHE*
```
Resolves #13014 
```
```

__shfl_up_sync with mask for CUDA >= 9

---

modules/gapi/include/opencv2/gapi/gmat.hpp
modules/gapi/src/api/gmat.cpp
modules/gapi/test/gapi_desc_tests.cpp

This pullrequest adds descr_of function taking a vector of Mat objects

GAPI: Add version of descr_of function taking vector of Mat

---

modules/videoio/src/cap_avfoundation_mac.mm
modules/videoio/test/test_video_io.cpp

Fixed test failures on Mac:
* AVFoundation writer supports only "mov", "mp4"/"m4v" and "3gp" formats with H264 and MJPG codecs - enabled these combinations to synthetic read_write test
* big_buck_bunny.mjpg.avi returned FPS=0, thus frame position calculations were wrong - added proper handling
* unsupported formats were not handled correctly in some cases: `setupReadingAt` returned true even if AssetReader returned false

AVFoundation on Mac: fixed frame count and unsupported format handling (3.4)

---

doc/tutorials/introduction/linux_install/linux_install.markdown

Should help avoid future issues about pkg-config (#13154, #13245) without changing the code, simply adding to the documentation.
Adds another item to the optional build parameters that explains flags needs to generate the ``pkg-config`` .pc file during build and installation.

Add note about building for pkg-config

---

modules/videoio/src/cap_avfoundation_mac.mm
modules/videoio/test/test_video_io.cpp

Ported #13685 from 3.4 manually due to conflicts in test_video_io.cpp

AVFoundation on Mac: fixed frame count and unsupported format handling (master)

---

modules/dnn/src/dnn.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/test/test_layers.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/571
In https://github.com/opencv/opencv/pull/13387 were introduced tests that check Intel's Inference Engine Myriad plugin crash for FP32 networks (because only FP16 are supported). However we use don't unload plugin and subsequent tests could work slower or even produce incorrect results.
Proposed to replace these tests to correct ones adding valid FP16 models.
<cut/>
Current:
```
$ ./bin/opencv_test_dnn --gtest_filter=Layer_Test_Convolution_DLDT*
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from Layer_Test_Convolution_DLDT
[ RUN      ] Layer_Test_Convolution_DLDT.Accuracy/0, where GetParam() = CPU
[       OK ] Layer_Test_Convolution_DLDT.Accuracy/0 (25 …
```

Remove ASSERT_ANY_THROW tests for Myriad plugin

---

modules/core/include/opencv2/core/cvdef.h
modules/imgproc/src/pyramids.cpp
modules/imgproc/test/test_filter.cpp

resolves #12961 
Force ARM implementation to use an unaligned int pointer.

PyrDown: Fix bug #12961

---

modules/js/src/core_bindings.cpp

This is an update to PR #13701 to base it on 3.4 -- we recompiled and retested build with 3.4 
Text below taken from original PR (which will be closed):
This PR is necessary for opencv.js to implement the C to JS bindings for Emscripten needed for advanced pattern matching.
In the docs:
https://docs.opencv.org/3.4.5/db/d39/classcv_1_1DescriptorMatcher.html#a378f35c9b1a5dfa4022839a45cdf0e89
`knnMatch` needs input `matches` of `type std::vector< std::vector< DMatch > > &`
`match` needs input `matches` of `type std::vector< DMatch > &`
We have tested the matching functions with the code below and it worked as expected (new constructor cv.DMatchVectorVector):
```
var orb = new cv.ORB();
var kp1 = new cv.KeyPointVector();
var des1 = new cv.Mat();
orb.detectAndCompute(patternImg, new cv.Mat(), …
```

Added DMatch bindings

---

modules/ml/src/svm.cpp
modules/ml/test/test_svmtrainauto.cpp

resolves #13621
_tl;dr sigmoid kernel is now as it should be, removed a restriction on coef0 that I understand to be incorrect_
Normally the sigmoid kernel used in SVM is:
K(x, y) = tanh(gamma * <x, y> + coef0)
But OpenCV had implemented the negative of this:
K(x, y) = -tanh(gamma * <x, y> + coef0)
[The OpenCV documentation](https://docs.opencv.org/3.4/d1/d2d/classcv_1_1ml_1_1SVM.html#aad7f1aaccced3c33bb256640910a0e56) says that it should be the former.
I've fixed this and added a test to give some coverage.  I chose a simple dataset that seemed well suited to the sigmoid kernel, and saw that someone else had used successfully:
When trying to replicate the gamma and coef0 values used in this example, I found that coef0 was restricted to be 0 or positive, but that isn't a necessary or …

SVM sigmoid kernel fix (issue #13621)

---

modules/dnn/src/layers/convolution_layer.cpp

Move convolution weights cloning to fusion phase to reduce top memory consumption.
| Model | w/o PR | with PR |
|---|---|---|
| AlexNet | 398 MB | 398 MB (x1.00) |
| ResNet-50 | 222 MB | 222 MB (x1.00) |
| SqueezeNet v1.1 | 35 MB | 30.5 MB (x0.86) |
| MobileNet-SSD (Caffe) | 73 MB | 50.3 MB (x0.68) |
| MobileNet-SSD v1 (TensorFlow) | 83.3 MB | 58.8 MB (x0.70) |
Sample (use `/usr/bin/time --verbose`)
```cpp
#include <opencv2/opencv.hpp>
using namespace cv;
using namespace cv::dnn;
std::string keys =
"{ model     | |  }"
"{ proto     | |  }"
"{ size     | |  }";
int main(int argc, char** argv) {
CommandLineParser parser(argc, argv, keys);
const std::string model = parser.get<String>("model");
const std::string proto = parser.get<String>("proto");
const int size = parser.get<int>("size"); …
```

Clone convolution layer weights only for fusion

---

samples/dnn/tf_text_graph_common.py

resolves https://github.com/opencv/opencv/issues/13725
This fix aligns TensorFlow's and OpenCV's paths for text graphs creation:
https://github.com/opencv/opencv/blob/631b246881f04021dfcdb2f6be03c6c108f82163/modules/dnn/src/tensorflow/tf_importer.cpp#L1963-L1969

Align TensorFlow and OpenCV paths to create a text graph

---

modules/core/src/ocl.cpp

add messages to avoid silent kernel destruction
Related: "mvn_fuse4" kernel in dnn test "Test_Torch_nets.FastNeuralStyle_accuracy/0"
<cut/>
<details>
Trace output without patch (`CV_OPENCL_TRACE_CHECK=1` `CV_OPENCL_SHOW_RUN_KERNELS=1`):
```
OpenCV(OpenCL:0): clBuildProgram(binary: dnn/mvn)
OpenCV(OpenCL:0): result = clGetProgramBuildInfo(handle, devices[0], CL_PROGRAM_BUILD_STATUS, sizeof(build_status), &build_status, &retsz)
OpenCV(OpenCL:0): clCreateKernel('mean_fuse4')
OpenCV(OpenCL:0): clSetKernelArg('mean_fuse4', arg_index=0, cl_mem=0000013AAFBD4BB0)
OpenCV(OpenCL:0): clSetKernelArg('mean_fuse4', arg_index=1, size=4, value=0000001D90F6D094)
OpenCV(OpenCL:0): clSetKernelArg('mean_fuse4', arg_index=2, size=4, value=0000001D90F6D048)
OpenCV(OpenCL:0): clSetKernelArg('mean_fuse4', …
```

ocl: support empty "ptr only" UMat in Kernel::set()

---

modules/core/include/opencv2/core/persistence.hpp
modules/core/src/persistence.cpp
modules/core/test/test_ptr.cpp
modules/gapi/include/opencv2/gapi/gcompoundkernel.hpp
modules/stitching/src/camera.cpp
modules/video/src/optical_flow_io.cpp

Merge with opencv/opencv_contrib#1980
* `warning: declaration shadows a static data member of 'cv::FileStorage' [-Wshadow]`
* `warning: local variable xxxxx will be copied despite being returned by name [-Wreturn-std-move]`
* `warning: explicitly assigning value of variable of type 'Ptr<opencv_test::(anonymous namespace)::anonymous namespace)::Reporter>' to itself [-Wself-assign-overloaded]`
```
```

Fixed warnings produced by clang-9.0.0

---

modules/video/src/optflowgf.cpp

Rework modules/video/src/optflowgf.cpp to use the universal intrinsics and remove the CV_SSE2 code in it.

Optical Flow rework to use wide universal intrinsics

---

modules/dnn/src/layers/mvn_layer.cpp
modules/dnn/src/opencl/mvn.cl

instead of `get_local_size(0)` and dynamic local memory allocation
```
```

dnn(ocl): use compile-time LOCAL_SIZE parameter

---

modules/imgproc/src/morph.cpp

resolves #13755
Fixed out of bound reading issue in erode() and dilate()
[Validation build](http://pullrequest.opencv.org/buildbot/builders/3_4_valgrind-lin64-debug/builds/56).

Fixed out of bound reading issue in erode() and dilate()

---

modules/core/include/opencv2/core/cuda_types.hpp
modules/cudaimgproc/perf/perf_histogram.cpp
modules/cudaimgproc/src/cuda/clahe.cu
modules/cudaimgproc/src/histogram.cpp
modules/cudaimgproc/test/test_histogram.cpp
modules/imgproc/perf/perf_histogram.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/573
Due to size limit of shared memory, histogram is built on
the global memory for CV_16UC1 case.
The amount of memory needed for building histogram is:
65536 * 4byte = 256KB
and shared memory limit is 48KB typically.
Added test cases for CV_16UC1 and various clip limits.
Added perf tests for CV_16UC1 on both CPU and CUDA code.
There was also a bug in CV_8UC1 case when redistributing
"residual" clipped pixels. Adding the test case where clip
limit is 5.0 exposes this bug.
Related : https://github.com/opencv/opencv_contrib/issues/1958
Performance test on 2080 Ti and CUDA 10 :
|   Type   | Image Size | Clip Limit |  CPU | CUDA |
|:--------:|:----------:|:----------:|:----:|:----:|
| CV_8UC1  | 1280x720   |          0 | 0.72 …

Add CV_16UC1 support for cuda::CLAHE

---

modules/gapi/include/opencv2/gapi/gproto.hpp

This pullrequest adds GOut() function overloading for tuple of parameter pack

GAPI: Add GOut overloading for tuple of parameter pack

---

modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_imgproc_perf_tests_fluid.cpp
modules/gapi/src/api/kernels_imgproc.cpp
modules/gapi/src/backends/cpu/gcpuimgproc.cpp
modules/gapi/src/backends/fluid/gfluidimgproc.cpp
modules/gapi/test/common/gapi_imgproc_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp
modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp
modules/gapi/test/cpu/gapi_imgproc_tests_fluid.cpp

This pullrequest adds overloading of Sobel kernel which returns both x- and y- derivatives.
```
```

WIP: GAPI: Add Sobel kernel which returns both dx and dy

---

modules/video/src/camshift.cpp

Issue #9152
In the example of the post #9152 the calculated value of the variable "rotate_c" are negative. It can not be, because the formula by which it was calculated is the sum of squares. 
In the counterexample, the variable is negative and very close to zero (due to inaccurate calculations), i think,  reasonable to add to avoid such cases theshold.

fixed incorrect formulas in the algorithm camshift

---

samples/dnn/tf_text_graph_mask_rcnn.py

resolves https://github.com/opencv/opencv/issues/13071
Enables the following model:
* [mask_rcnn_resnet50_atrous_coco_2018_01_28](http://download.tensorflow.org/models/object_detection/mask_rcnn_resnet50_atrous_coco_2018_01_28.tar.gz)
* [mask_rcnn_resnet101_atrous_coco_2018_01_28](http://download.tensorflow.org/models/object_detection/mask_rcnn_resnet101_atrous_coco_2018_01_28.tar.gz)
Please note that similar to https://github.com/opencv/opencv/issues/13237 you need to modify a `pipeline.config` file:
replace
```
height_stride: 8
width_stride: 8
```
to
```
height_stride: 16
width_stride: 16
```
resnet-50:
resnet-101:

Enable Mask-RCNN models with dilated convolutions from TensorFlow

---

modules/imgproc/perf/perf_cvt_color.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/574
Added performance tests for missing types (for the conversions that support them).
They are needed for performance optimization purposes only so they are disabled to speed up passing all tests.
```
```

Perf tests for cvtColor for 16U and 32f added

---

doc/tutorials/videoio/video-input-psnr-ssim/video_input_psnr_ssim.markdown

This pull request fixes small typo in "Video Input with OpenCV and similarity measurement" tutorial.
The tutorial says that for acquire the frame need to use `cv::VideoCapture::read` but the code example uses wrong member function `cv::VideoCapture::open`.

Fix typo in the tutorial

---

modules/calib3d/src/calibration.cpp

objectPoints and imagePoints are not checked whether they're empty and
cause checkVector() to fail, thus result in a wrong error message.
Fixes: https://github.com/opencv/opencv/issues/6002

calib3d: Fix calibrateCamera() misleading error.

---

modules/gapi/perf/common/gapi_imgproc_perf_tests_inl.hpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp

resolves #13787  
This pullrequest removes initialization of additional outputs for graph due to valgrind warnings

GAPI: Fixes an issue with valgrind and sobelxy

---

modules/cudalegacy/src/cuda/NCVHaarObjectDetection.cu
modules/cudalegacy/src/cuda/NPP_staging.cu
modules/cudev/include/opencv2/cudev/warp/scan.hpp

resolves #13761
Without this PR, following tests hang on 2080 Ti (and possibly on other Volta and Turing cards).
```
opencv_test_cudalegacy --gtest_filter=*NPPST.Integral*
opencv_test_cudalegacy --gtest_filter=*NPPST.SquaredIntegral*
opencv_test_cudalegacy --gtest_filter=*NPPST.RectStdDev*
opencv_test_cudalegacy --gtest_filter=*NPPST.Integral*
opencv_test_cudalegacy --gtest_filter=*NPPST.VectorOperations*
opencv_test_cudalegacy --gtest_filter=*NCV.HaarCascadeApplication*
```
The hanging behavior of the last test case (`NCV.HaarCascadeApplication`) is identical issue to #13761, which this PR resolves.
Using "safe" version of block scan function (in `cudev` module) added by #13658 fixes these hanging issues.
Verified on following test environments:
```
CUDA 10.0 on 2080 Ti
CUDA 9.2 on 1080 …
```

cudalegacy: Use safe block scan function

---

modules/dnn/perf/perf_net.cpp
modules/dnn/src/layers/lrn_layer.cpp
modules/dnn/src/layers/normalize_bbox_layer.cpp
modules/dnn/src/layers/resize_layer.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

The following test now use IE backend:    
Normalize layer
* Test_Torch_layers.net_normalize
* Test_Torch_nets.OpenFace_accuracy
Resize layer
* Test_Darknet_nets.YOLOv3
* Test_Darknet_layers.upsample
* Test_Torch_layers.upsampling_nearest  
LRN layer
* Test_Caffe_layers.LRN
<cut/>
Processor: Intel® Core™ i5-6500 CPU @ 3.20GHz × 4
Graphics: Intel® HD Graphics 530 (Skylake GT2)  
| Name of Test                            | Time before changes (ms) | Time after changes (ms) |  x-factor after vs before |
|-----------------------------------------|--------------------------|-------------------------|---------------------------|
| OpenFace::DNNTestNetwork::DLIE/CPU      | 18.298                   | 17.791                  | 0.97                      |
|  OpenFace::DNNTestNetwork::DLIE/OCL     | …

Runing tests on IE backend 

---

samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/CsvReader.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/CsvReader.h
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/CsvWriter.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/CsvWriter.h
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/Mesh.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/Mesh.h
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/Model.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/Model.h
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/ModelRegistration.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/ModelRegistration.h
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/PnPProblem.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/PnPProblem.h
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/RobustMatcher.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/RobustMatcher.h
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/Utils.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/Utils.h
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/main_detection.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/main_registration.cpp

- Lots of auto formatting code changes.
- Fix parsing of arguments:
https://github.com/opencv/opencv/blob/54a1bbe1c42ceeb3bd0875e7c95ffcc0d883f1e4/samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/main_detection.cpp#L105-L112
- Add keypoints matching visualization (only after training a new model file)
- Add possibility to use another type of keypoints (not only ORB)
---
It is not possible to get the same detection results with the provided image and video than in the tutorial video.
Beware of the Kalman filter formulation used (constant acceleration on Euler angles). Here what looks like a better [formulation](https://github.com/chili-epfl/chilitags/pull/75).
---
Some video results (unfortunately, YouTube applied too much compression):
Training pose:
```
cv::Mat rvec = …
```

Add keypoints matching visualization for real-time pose estimation tutorial

---

modules/cudastereo/src/cuda/stereobm.cu

- Fix hanging issue on 2080 Ti
- Fix racing issue
---------
The following test hangs on RTX 2080 Ti.
```
./bin/opencv_test_cudastereo --gtest_filter=*StereoBM*
```
The following test reports race condition.
```
cuda-memcheck --tool racecheck ./bin/opencv_test_cudastereo --gtest_filter=*StereoBM*
```
This PR fixes above issues.
---------
```
```

cuda::StereoBM - Fix hanging and racing issue

---

modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/drawing.cpp

cv::LineIterator can be used without being attached to any cv::Mat, it only needs the size and type of data. An alternative constructor has been defined for that.
In that case, a LineIterator can no more be dereferenced with the * operator, but pos() still returns valid pixel positions.
It can be useful when LineIterator is just used to compute positions of pixels on a line, without requiring to build a Mat just for that.
Use case : with a dataset that would represent a huge image, pixel positions can be pre-computed before querying the dataset API.

LineIterator witout a Mat

---

modules/flann/include/opencv2/flann/dist.h

All `<arm_neon.h>` includes in `core/cv_cpu_dispatch.h` are protected by an
`ifndef __CUDACC__` to prevent attempting to use neon intrinsics when
compiling cuda kernels (.cu) -- this prevents hard errors such as
```error: identifier "__builtin_neon_qi" is undefined```
Add this same protection to flann/dist.h to fix compilation involving
flann.hpp.
Only protection around the inline neon code in flann/dist.h's Hamming distance function.
<cut/>
```
```

Fix Flann compilation under nvcc + NEON

---

modules/gapi/include/opencv2/gapi/fluid/gfluidbuffer.hpp
modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp
modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/src/backends/fluid/gfluidbackend.hpp
modules/gapi/src/backends/fluid/gfluidbuffer.cpp
modules/gapi/src/backends/fluid/gfluidbuffer_priv.hpp
modules/gapi/test/gapi_fluid_resize_test.cpp
modules/gapi/test/gapi_fluid_test.cpp
modules/gapi/test/gapi_fluid_test_kernels.cpp

* Added NV12toRGB to FluidKernel::Kind enum to inform the engine of the special scheduling mechanic of the kernel (kernel consumes 2 lines from the first input, 1 line from the second, and produces 2 lines)
* Added appropriate NV12toRGBFluidAgent - the scheduler entity to support new kind of scheduling and line dependencies, added input port parameter to schedule related methods of FluidAgent (firstWindow, linesReadAndNextWindow)
* Extended FluidUnit structure to have a vector of line consumptions to support different line consumption requirements on different input ports
* Extended roi inference process to be aware of new kind of in/out roi dependency
* Added test kernel and tests
```
```

G-API Fluid nv12 support

---

modules/core/include/opencv2/core/hal/intrin.hpp
modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/imgproc/src/resize.cpp

Reworked bit-exact linear resize using new wide LUT intrinsics and add support for CV_8UC3
```
buildworker:Custom=linux-1,linux-2
```

Resize reworked using wide universal intrinsics

---

modules/imgproc/perf/perf_integral.cpp
modules/imgproc/src/sumpixels.avx512_skx.cpp
modules/imgproc/src/sumpixels.cpp
modules/imgproc/test/test_filter.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/578
Implementing AVX512 support using universal intrinsics for the cv::integral method when operating on 2, 3 and 4 channel and the result is CV_64F.
Will be following up with single channels support next week.   
<cut/>
From opencv_perf_imgproc results of various size Mats:
|Name of Test|no avx512|avx512|avx512 vs no avx512 (x-factor)|
|integral::Size_MatType_OutMatDepth::(127x61, 8UC2, CV_64F)|0.024|0.007|3.23|
|integral::Size_MatType_OutMatDepth::(127x61, 8UC3, CV_64F)|0.035|0.009|3.97|
|integral::Size_MatType_OutMatDepth::(127x61, 8UC4, CV_64F)|0.046|0.009|4.92|
|integral::Size_MatType_OutMatDepth::(128x128, 8UC2, CV_64F)|0.049|0.015|3.39|
|integral::Size_MatType_OutMatDepth::(128x128, 8UC3, …

Implementing AVX512 Support for 2 and 4 channel mats for CV_64F format

---

doc/py_tutorials/py_gui/py_video_display/py_video_display.markdown

Check return value in python tutorial

---

modules/video/include/opencv2/video/tracking.hpp
modules/video/src/ecc.cpp
modules/video/test/test_ecc.cpp

resolves #12432
The issue tracked in https://github.com/opencv/opencv/issues/12432 is resolved with the changes here, by adding a new function called computeECC as suggested by the issue author, and, by adding another optional argument to findTransformECC to control the size of the Gaussian filter (set to default of 5, to maintain backward compatibility; set to 1 to do no filtering, like the issue author would like). Tests and documentation strings are included as well. 
This is my first pull request, and so pardon my tardiness.

New computeECC function, and updated findTransformECC function to make gaussian filtering optional

---

modules/dnn/src/layers/lrn_layer.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/test/test_halide_layers.cpp

Inference Engine backend doesn't support LRN with bias and Myriad plugin doesn't support normalization across channels. Enabled test for all the configurations.
```
build_parallel_tests:Custom=1
```

Add extra limitations for LRN from Inference Engine backend

---

modules/cudev/include/opencv2/cudev/block/scan.hpp
modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp
modules/cudev/include/opencv2/cudev/warp/scan.hpp
modules/cudev/include/opencv2/cudev/warp/shuffle.hpp

- Use `shfl_down`, instead of `__shfl_down`, on `scan.hpp`
```
modules/cudev/include/opencv2/cudev/warp/scan.hpp
modules/cudev/include/opencv2/cudev/warp/shuffle.hpp
```
This fix is applied to make the code conform to the structure of `cudev` module. `__shfl_down` should be directly called at `shuffle.hpp` and other files in `cudev` module should call `shfl_down`, which is a wrapper for `__shfl_down`.
- Remove race conditions
```
modules/cudev/include/opencv2/cudev/block/scan.hpp
modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp
```
This fix is applied to pass the following `cuda-memcheck --tool racecheck` tests:
```
cuda-memcheck --tool racecheck opencv_test_cudev
cuda-memcheck --tool racecheck opencv_test_cudaarithm --gtest_filter=*Integral*
```
``` …
```

cudev - Rework some code

---

platforms/ios/cmake/Toolchains/common-ios-toolchain.cmake
platforms/ios/cmake/Toolchains/xcodebuild_wrapper.in

which breaks `check_type_size()` macro.
resolves #13856

cmake: workaround iOS try_compile(COPY_FILE) bug

---

modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java

Bug fix of `Interrupted while setCameraPreviewSize` and `width and height must be > 0` which is related to `JavaCamera2View`
`org.opencv.android.JavaCamera2View` crashes on certain phones such as Samsung Galaxy S7 and Alcatel A5A. (On contrary, `JavaCameraView` works fine.) It is because `CameraBridgeViewBase.CAMERA_ID_BACK` and `CameraBridgeViewBase.CAMERA_ID_FRONT` do not match correct values. This patch introduces two new `final int` variables to correctly detect cameras.
```
java.lang.RuntimeException: Interrupted while setCameraPreviewSize.
at org.opencv.android.JavaCamera2View.connectCamera(JavaCamera2View.java:333)
at org.opencv.android.CameraBridgeViewBase.onEnterStartedState(CameraBridgeViewBase.java:360)
at org.opencv.android.CameraBridgeViewBase.processEnterState(CameraBridgeVie …
```

Making JavaCamera2View be consistent with JavaCameraView

---

samples/dnn/tf_text_graph_common.py

```
Tensorflow version: 1.12.0
OpenCV version: 3.4.3
```
Fix the bug in creating tensorflow model's pbtxt file. 
The type of tensor.tensor_content should be `bytes` not `str` 
```
node.attr['value'].tensor.tensor_content = ""
--> 
node.attr['value'].tensor.tensor_content = bytes('', 'utf-8')
```

fix tf_text_graph_common tensor_content type bug

---

modules/core/perf/perf_io_base64.cpp

- can be enable separately, if needed
- not stable (due storage I/O processing)
```
```

core: disable I/O perf test

---

modules/core/include/opencv2/core/mat.hpp
modules/core/test/test_mat.cpp

resolves #13926
replace erroneous `+` with `*`  in mat.hpp

Core fix mat matx mult

---

modules/core/src/persistence_json.cpp
modules/stitching/include/opencv2/stitching.hpp
modules/stitching/src/stitcher.cpp

This pull request makes minor revisions to syntax in the core and stitching modules to improve support for Visual C++ 2013.
I am testing with a configuration similar to the following:
```
CALL C:\TBB\bin\tbbvars.bat ia32 vs2013
cmake -DCMAKE_BUILD_TYPE=RELEASE ^
-DWITH_OPENGL=ON ^
-DWITH_TBB=ON ^
-DOPENCV_SKIP_PYTHON_LOADER=ON ^
-DPYTHON2_LIBRARY=C:/Python27/libs/python27.lib ^
-DPYTHON2_INCLUDE_DIR=C:/Python27/include ^
-DWITH_ADE=OFF ^
-DWITH_QUIRC=OFF ^
-G "Visual Studio 12 2013" ^
Z:/SDKs/OpenCV/fork
```

core, stitching: revise syntax to support Visual C++ 2013

---

modules/cudev/include/opencv2/cudev/warp/shuffle.hpp

This fix is required to build `3.4` branch and `master` branch using CUDA 10.1.
Reference: https://github.com/opencv/opencv/issues/13952#issuecomment-469017932
Resolves #13941 
```
```

CUDA 10.1 Build Issue Fix

---

modules/core/include/opencv2/core/cuda/detail/color_detail.hpp

This fix is required to build `master` branch on Windows.
References:
https://github.com/opencv/opencv/issues/13491#issuecomment-469036165
https://github.com/opencv/opencv/issues/13952#issuecomment-469017932
Resolves #13491 
```
```

Windows Build Issue Fix

---

modules/gapi/include/opencv2/gapi/imgproc.hpp

This pullrequest removes incorrect asserts in NV12 to RGB/BGR color conversion kernels and add a little documentation on other asserts

G-API: Remove incorrect assert in NV12 to RGB/BGR kernels

---

modules/calib3d/src/calibration.cpp

resolves #13908
fix the regression of cv::calibrateCamera describe in Issue#13908 by allocating the matrix _Jo only when it seems requested

Fix Issue_13908

---

cmake/OpenCVModule.cmake
modules/videoio/CMakeLists.txt
modules/videoio/cmake/plugin.cmake

- support comma-separated list in VIDEOIO_PLUGIN_LIST
- opencv tests/samples depend on plugins virtual target

cmake: +opencv_videoio_plugins virtual target

---

doc/tutorials/introduction/documenting_opencv/documentation_tutorial.markdown

resolves #13457
Must have that flag. Otherwise following "doxygen overview" tutorial won't work.

Need -DBUILD_DOCS CMake flag to build docs

---

modules/imgproc/src/resize.cpp

resolves #13950
Fixed out of bound reading in LINEAR_EXACT resize for 8UC3
[Validation build](http://pullrequest.opencv.org/buildbot/builders/3_4_valgrind-lin64-debug/builds/61)

Fixed out of bound reading in LINEAR_EXACT resize for 8UC3

---

modules/videoio/src/cap_gstreamer.cpp

According to the gstreamer docs [1], the GstMessage pointer returned by
gst_bus_pop() is nullable, meaning NULL is a valid return value.
Previously, gst_is_missing_plugin_message would throw an assert when its
message object parameter would fail the GST_IS_MESSAGE macro check,
crashing the entire process (unless running in a try-catch block of course).
Instead of relying on valid messages, check if the message object itself is
valid before passing it to other gstreamer functions.
[1] https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstBus.html#gst-bus-pop
Signed-off-by: Christopher N. Hesse <raymanfx@gmail.com>

videoio: gst: Fix gst assertion on null msg

---

modules/core/src/matrix_wrap.cpp
modules/core/test/test_misc.cpp

resolves #13772
Related commit: https://github.com/opencv/opencv/commit/dd45fe13d190e91961e44fe9809d13a6e357f6bb

core: fix condition in OutputArray::create(allowTransposed=True)

---

modules/gapi/CMakeLists.txt
modules/gapi/cmake/standalone.cmake

This pullrequest modifies standalone G-API cmake for proper testing standalone build
If the project uses MSVC some warnings occurs:
1) _CRT_SECURE_NO_DEPRECATE suppress a warning about "unsafe" function for which Microsoft has "safe" version. In our situation that function calls correctly.
2) Also if we export G-API (which has some non-exportable STL containers) on Windows we need to suppress 4251 warning (as there is no another robust solution).
```
```

G-API: Modifies standalone G-API cmake for testing it properly

---

modules/java/generator/android/java/org/opencv/android/BaseLoaderCallback.java

Shortens the hard coded log tag of BaseLoaderCallback.java by a few characters to prevent this specific android lint error.
> BaseLoaderCallback.java:31: Error: The logging tag can be at most 23 characters, was 31 (OpenCVLoader/BaseLoaderCallback) [LongLogTag]
> Log.e(TAG, "Package installation failed!");

fix android lint error in BaseLoaderCallback (LongLogTag)

---

modules/core/misc/java/src/java/core+Mat.java
modules/core/misc/java/test/MatTest.java
modules/java/generator/src/cpp/Mat.cpp
modules/java/test/android_test/src/org/opencv/test/OpenCVTestCase.java
modules/java/test/pure_test/src/org/opencv/test/OpenCVTestCase.java

resolves #13955
In particular it exposes methods for handling Mat with more than 2 dimensions.
* add constructors taking an array of dimension sizes
* add constructor taking an existing Mat and an array of Ranges
* add override of the create method taking an array of dimension sizes
* add overrides of the ones and zeros methods taking an array of dimension sizes
* add override of the submat method taking an array of ranges
* add overrides of put and get taking arrays of indices
* add wrapper for copySize method
* fix crash in the JNI wrapper of the reshape(int cn, int[] newshape) method

Expose more C++ functionality in the Java wrapper of the Mat class

---

modules/dnn/misc/java/src/cpp/dnn_converters.cpp
modules/java/android_sdk/android_gradle_lib/build.gradle
platforms/android/build_sdk.py

* add build flag "--debug"
* when flag is set then
* set CMake build type to Debug
* set CMake build flag BUILD_WITH_DEBUG_INFO to ON
* invokes ninja with target "install" instead of "install/strip"
* suppresses stripping of debug information in the SDK gradle build
* fixes a bug in the DNN Java wrapper (missing LOG_TAG define)

Add Android SDK debug build flag

---

modules/videoio/src/cap_v4l.cpp

resolves https://github.com/opencv/opencv/issues/13697
Fixes a bug where CAP_V4L would segfault after releasing a capture device. The error seemed to be caused by a frame not being released properly when CONVERT_RGB is disabled. Possibly it was marked as allocated when it wasn't, and then the segfault occurs when the destructor gets called.
I've tested switching between modes (before releasing the camera) and it works without any errors.

fix segfault when CONVERT_RGB is disabled with V4L backend

---

modules/imgcodecs/test/test_tiff.cpp

Fixes a bug in which the big endian data in the `tiff_sample_data` array was never being tested.  This could be observed by e.g. changing the 9th byte in the big endian data from `0xde` to something that should fail the test, e.g. `0xdd`, and the test would still pass even though it should fail.

Fix bug in test_tiff.cpp

---

cmake/OpenCVCompilerOptions.cmake
cmake/OpenCVUtils.cmake
cmake/checks/runtime/cpu_vsx_aligned.cpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp

resolves #13211
- check sanity of vsx aligned ld/st
- force universal intrinsics v_load_aligned/v_store_aligned
to failback to unaligned ld/st if cmake runtime vsx aligned test fail
````
pw_compilers=gcc-4.9, gcc-5, gcc-6, gcc-8, clang-4, clang-5, clang-6, power9_gcc-7, power9_gcc-8, power9_clang-4, power9_clang-6
pw_cmake_definitions=WITH_EIGEN:OFF
````

core:vsx working around gcc aligned memory access bug

---

modules/videoio/src/cap_dc1394_v2.cpp

Function `dc1394_deinterlace_stereo_frames_fixed` have been fixed in latest libdc1394 versions.

Removed obsolete functions from cap_dc1394_v2.cpp

---

modules/ml/src/ann_mlp.cpp

resolves #13946 
Changed the epsilon assigning condition. Initially, epsilon was taking FLOAT_MIN value in case of only COUNT condition, however according to the relevant issue, epsilon checking shouldn't happen.

Changed eps checking condition

---

modules/dnn/src/layers/region_layer.cpp

Dnn module support darknet yolo networks, but when the net input dim size not equal,it will produce wrong detection results .
Just Fix the region layer's output anchor size normalization error.

fix the region layer's output anchor size  normalization error

---

3rdparty/libtiff/tif_config.h.cmake.in

Keep `_FILE_OFFSET_BITS` undefined in Android builds.
relates #13808 
<cut/>
Error message:
```
In file included from /opt/android/android-ndk-r16b/sysroot/usr/include/fcntl.h:32:0,
from /home/alalek/projects/opencv/dev/3rdparty/libtiff/tiffiop.h:34,
from /home/alalek/projects/opencv/dev/3rdparty/libtiff/tif_aux.c:30:
/opt/android/android-ndk-r16b/sysroot/usr/include/sys/cdefs.h:217:75: error: operator '&&' has no right operand
#if !defined(__LP64__) && defined(_FILE_OFFSET_BITS) && _FILE_OFFSET_BITS == 64
^
```

3rdparty: fix libtiff build

---

CMakeLists.txt

resolves #14055 
Changed CMAKE_SYSTEM_NAME matching condition as given in the issue.

changes cmake_system_name matching condition

---

modules/core/test/test_eigen.cpp

relates #14089
Failed builds:
- [AVX2](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64-avx2/builds/397)
- [ARMv8](http://pullrequest.opencv.org/buildbot/builders/precommit_armv8/builds/11443)
```
force_builders=Linux AVX2,ARMv8
```

core: fix Core_EigenNonSymmetric.convergence test

---

modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/test/gapi_fluid_test.cpp

Allow nodes produced after some operation to be "unused": not being an output and not being used as inputs to other operations
<cut/>
Fluid test is added to cover new behavior. Below is the graph example built by the test:

[G-API] Allow unused nodes in Fluid backend

---

modules/flann/include/opencv2/flann/kmeans_index.h

When running with >1 OpenCV thread, KMeans index generation was
non-deterministic. Issue is resolved by protecting each radius variable
with a mutex.
resolves #9179
relates #3458

flann/kmeans: Fix non-determinism of KMeans index

---

samples/android/15-puzzle/AndroidManifest.xml
samples/android/15-puzzle/gradle/AndroidManifest.xml
samples/android/camera-calibration/AndroidManifest.xml
samples/android/camera-calibration/gradle/AndroidManifest.xml
samples/android/face-detection/AndroidManifest.xml
samples/android/face-detection/gradle/AndroidManifest.xml
samples/android/image-manipulations/AndroidManifest.xml
samples/android/image-manipulations/gradle/AndroidManifest.xml
samples/android/tutorial-2-mixedprocessing/AndroidManifest.xml
samples/android/tutorial-2-mixedprocessing/gradle/AndroidManifest.xml
samples/android/tutorial-3-cameracontrol/AndroidManifest.xml
samples/android/tutorial-3-cameracontrol/gradle/AndroidManifest.xml
samples/android/tutorial-4-opencl/AndroidManifest.xml
samples/android/tutorial-4-opencl/gradle/AndroidManifest.xml

Many of the Android samples rely on an _options menu_ (see image below) to work properly. On newer devices & Android versions (or at least on my phone), the menu was permanently hidden by the fullscreen theme and there seemed to be no way for the user to make it visible. Consequently, most of the examples were dysfunctional.
<cut/>
This PR simply removes the Android theme `Theme.NoTitleBar.Fullscreen` in the samples that use the options menu, which seems to fix the issue.
_Figure: Options menu visible on top of the image (Android 8.0.0 on Google Pixel 2)_
I tested this by building OpenCV from source (on Debian Stretch) and installing the samples using `adb` as
```
export ANDROID_HOME=~/Android/Sdk
export ANDROID_NDK=~/Android/Sdk/ndk-bundle
export ANDROID_SDK=~/Android/Sdk
cd …
```

Remove fullscreen android:theme from samples where it breaks the menu

---

modules/calib3d/include/opencv2/calib3d.hpp

Fix #11754 by removing the dead link to `calibration_artificial.cpp` in calib3d.hpp [here](https://github.com/opencv/opencv/blob/6501cb93a43fe560a7fb7272b4575aa562653e92/modules/calib3d/include/opencv2/calib3d.hpp#L181)

Remove dead link in calib3d.hpp

---

cmake/checks/runtime/cpu_vsx_aligned.cpp

relates #14040, #13211 
This patch fix compilation fail on aligned/ld/st run-time test when c++11 enabled or when build opencv4 current master and that case unnecessary fallback to unaligned ld/st intrinsics, however its my bad after all :(
<cut/>
compilation errors from CMakeError file
```bash
Run Build Command:"/usr/bin/make" "cmTC_b1fdd/fast"
/usr/bin/make -f CMakeFiles/cmTC_b1fdd.dir/build.make CMakeFiles/cmTC_b1fdd.dir/build
make[1]: Entering directory '/worker/buildbot/Power9_Linux_gcc-6__opencv/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_b1fdd.dir/cpu_vsx_aligned.cpp.o
/usr/bin/g++-6    -O3 -DNDEBUG -fPIE   -mcpu=power8 -mcpu=power9 -mtune=power9 -std=c++11 -o CMakeFiles/cmTC_b1fdd.dir/cpu_vsx_aligned.cpp.o -c …
```

cmake:vsx Fix compilation fail on aligned runtime test

---

modules/core/include/opencv2/core/cvdef.h

keep it empty to avoid failures of these declarations:
```
static CV_CONSTEXPR const int var = ...;
```

core: fix fallback CV_CONSTEXPR definition

---

modules/imgproc/src/sumpixels.avx512_skx.cpp
modules/imgproc/src/sumpixels.cpp

Implementing AVX512 Support for 1 channel mats for CV_64F format
Also made some small changes to ensure const correctness
<cut/>
|Name of Test|no avx512|avx512|avx512 vs no avx512 (x-factor)|
|integral::Size_MatType_OutMatDepth::(127x61, 8UC1, CV_64F)|0.012|0.007|1.56|
|integral::Size_MatType_OutMatDepth::(128x128, 8UC1, CV_64F)|0.025|0.014|1.77|
|integral::Size_MatType_OutMatDepth::(640x480, 8UC1, CV_64F)|0.474|0.257|1.85|
|integral::Size_MatType_OutMatDepth::(1280x720, 8UC1, CV_64F)|1.437|0.772|1.86|
|integral::Size_MatType_OutMatDepth::(1920x1080, 8UC1, CV_64F)|3.247|1.772|1.83|
|integral::Size_MatType_OutMatDepth::(3840x2160, 8UC1, CV_64F)|12.942|7.441|1.74|
|integral_sqsum::Size_MatType_OutMatDepth::(127x61, 8UC1, CV_64F)|0.013|0.012|1.08| …

Implementing AVX512 Support for 1 channel mats for CV_64F format

---

modules/dnn/src/layers/lrn_layer.cpp
modules/dnn/test/test_halide_layers.cpp

Remove some limitations introduced in https://github.com/opencv/opencv/pull/13887.
Test `Layer_Test_Halide/LRN.Accuracy` is failed due a bug in Myriad plugin so we can skip it rather disabling an entire layer.

Extend LRN layer support with IE backend

---

modules/core/include/opencv2/core/cvdef.h

related #10589
@mwoehlke-kitware , does this patch fix your issue?
__Note:__ merge to _master_ is not needed, `std::array` is always enabled on this branch.

Fixed cvdef.h for MSVC C users

---

modules/core/include/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp
modules/core/src/opencl/runtime/generator/template/opencl_core.hpp.in
modules/core/src/opencl/runtime/opencl_core.cpp
samples/opencl/opencl-opencv-interop.cpp

<cut/>
Warnings (Xcode 10.1, OSX 10.14 Mojave):
> opencv/samples/opencl/opencl-opencv-interop.cpp:72:15: warning: 'clGetPlatformInfo' is deprecated: first deprecated in macOS 10.14 - (Define CL_SILENCE_DEPRECATION to hide this warning) [-Wdeprecated-declarations]
```
```

OCL: define CL_SILENCE_DEPRECATION on MacOSX

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/582
This is relevant to cases where the net is loaded from an ONNX model
containing ConvTranspose layers, which may include the output_shape
attribute.
c.f. https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvTranspose
```
```

Make use of explicit output shape for the de-convolution layer.

---

modules/gapi/test/common/gapi_imgproc_tests_inl.hpp

resolves #14072 
This pullrequest fixes a valgrind issue in NV12 tests
[Validation build](http://pullrequest.opencv.org/buildbot/builders/master_valgrind-lin64-debug/builds/10153).

G-API: Fix valgrind issue in NV12 test

---

modules/dnn/src/op_inf_engine.cpp
modules/dnn/src/op_inf_engine.hpp

relates #13884
<cut/>
```
docker_image:Custom=ubuntu-openvino-2018r3:16.04
docker_image:Linux AVX2=ubuntu-openvino-2018r4:16.04
```

dnn: fix support drop for IE<2018R3

---

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

resolves https://github.com/opencv/opencv/issues/14149
* This PR adds fusion of SoftMax subgraph from TensorFlow's slim library.
* Apply `sortByExecutionOrder` graph nodes sort function by default
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/586

Fix Mobilenet v2 from TensorFlow slim

---

modules/core/CMakeLists.txt

replaces #14173
[Validated](http://pullrequest.opencv.org/buildbot/builders/precommit_custom_linux/builds/1955/steps/cmake/logs/stdio).
```
#build_contrib:Custom=OFF
```

cmake: emit error if CUDA is enabled without opencv_contrib

---

doc/tutorials/dnn/dnn_googlenet/dnn_googlenet.markdown

resolves #14148 
This updates the 'classification_classes_ILSVRC2012.txt' link in the documentation to not return a 404

Fixed #14148 Broken Documentation Link

---

modules/dnn/CMakeLists.txt
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/include/opencv2/dnn/utils/inference_engine.hpp
modules/dnn/perf/perf_net.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/src/op_inf_engine.hpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_common.cpp
modules/dnn/test/test_common.hpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_ie_models.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

```
**WIP**
#tests_filter:Linux AVX2=*:-Test_Caffe_layers.Conv_Elu/1
```

Fix precision in tests for MyriadX

---

modules/videoio/src/cap_avfoundation_mac.mm
modules/videoio/src/cap_gstreamer.cpp
modules/videoio/src/cap_mfx_writer.cpp
modules/videoio/test/test_dynamic.cpp
modules/videoio/test/test_mfx.cpp
modules/videoio/test/test_video_io.cpp

We expect no throw behavior for incorrect VideoWriter parameters, added test to check this.
Changes in GStreamer backend:
* replaced `abort()` calls with error handling
Changes in AVFoundation VideoWriter backend:
* added support to UTF-8 filenames (not tested)
* removed fallback to mp4/h264 codec in case when extension or FourCC are not supported (supported extensions: `mov, qt, mp4, m4v`, supported FourCC codes: `JPEG, MJPEG, jpeg, mjpeg, H264, avc1`)
* added basic error handling and cleanup
Changes in MediaSDK backend:
* added soft `fps` check and modified
```
docker_image:Linux AVX2=ubuntu:18.04
```

videoio: added bad parameters handling to VideoWriter

---

3rdparty/zlib/inflate.c
3rdparty/zlib/patches/20190330-ununitialized-use-state-check.diff

To unblock future checks by fuzzer with memory sanitizer.

3rdparty(zlib): prevent uninitialized use of state->check

---

modules/dnn/CMakeLists.txt

resolves #14195 
````
pw_compilers=clang-4, clang-5, clang-6, gcc-4.9, power9_gcc-5, power9_gcc-6, power9_gcc-7
````

dnn:perf add missing definition __OPENCV_TEST to fix pch

---

modules/core/src/system.cpp

OpenBSD build fix

---

modules/dnn/CMakeLists.txt
modules/dnn/perf/perf_common.cpp
modules/dnn/test/test_common.impl.hpp

- don't share .cpp files (PCH support is broken)
- test_common.cpp contents moved to test_common.impl.hpp which included by:
* test_common.cpp from accuracy tests
* perf_common.cpp from perf tests
resolves #14195
relates #14196
[Validation build](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL_noICV_noSSE-lin64-debug/builds/343).

cmake: fix build of dnn tests with shared common code

---

modules/core/CMakeLists.txt

resolves #14205
```
build_world:Custom=ON
build_contrib:Custom=ON
```

cmake: fix CUDA world build

---

modules/imgcodecs/src/bitstrm.cpp

Seeking outside of the current block doesn't update actual data, so getByte()/etc will get wrong data from stalled buffer.

imgcodecs: fix RBaseStream::setPos() outside of current block

---

3rdparty/zlib/inflate.c
3rdparty/zlib/patches/20190330-ununitialized-use-state-check.diff

(3.4) 3rdparty(zlib): prevent uninitialized use of state->check

---

modules/core/src/lda.cpp

- exceptions from constructor will not cause destructor calls
fixes [weekly valgrind build](http://pullrequest.opencv.org/buildbot/builders/3_4_valgrind-lin64-debug/builds/68)
relates #14102 #14103
[Validation build](http://pullrequest.opencv.org/buildbot/builders/3_4_valgrind-lin64-debug/builds/69)

core(lda): don't perform calculations in constructor

---

modules/imgcodecs/src/grfmt_tiff.cpp

(3.4) imgcodecs(tiff): avoid leak of helper struct on malformed inputs

---

cmake/OpenCVModule.cmake
cmake/OpenCVPCHSupport.cmake

relates #14217
To avoid mess in "world" builds.
They are here for more than 9 years. Currently it is not needed (relative includes works well with modern compilers).
GCC-based precompiled headers issue has been fixed.
<cut/>
```
```

(3.4) cmake: don't add tests dirs as include directories

---

modules/dnn/src/layers/convolution_layer.cpp

SqueezeNet which has a number of 1x1 convolutions is 5% faster.
model name | before PR | with PR | x-factor |
---|---|---|---
AlexNet                           | 14.234 |  14.220    | 1.00   |
DenseNet_121                      | 36.797 |  36.205    | 1.02   |
EAST_text_detection               | 68.035 |  67.741    | 1.00   |
ENet                              | 42.840 |  43.617    | 0.98   |
FastNeuralStyle_eccv16            | 115.886 | 115.539   | 1.00   |
GoogLeNet                         | 14.781 |  14.803    | 1.00   |
Inception_5h                      | 16.138 |  16.230    | 0.99   |
Inception_v2_Faster_RCNN          | 281.913 | 281.062   | 1.00   |
Inception_v2_SSD_TensorFlow       | 43.484 |  42.729    | 1.02   |
MobileNet_SSD_Caffe               | 19.403 |  19.465    | 1.00   | …

Enable 1x1 convolution optimization

---

cmake/OpenCVModule.cmake
cmake/OpenCVPCHSupport.cmake
modules/gapi/perf/common/gapi_core_perf_tests.cpp
modules/gapi/perf/common/gapi_imgproc_perf_tests.cpp
modules/gapi/perf/internal/gapi_compiler_perf_tests.cpp
modules/gapi/test/common/gapi_compoundkernel_tests.cpp
modules/gapi/test/common/gapi_core_tests.cpp
modules/gapi/test/common/gapi_imgproc_tests.cpp
modules/gapi/test/common/gapi_operators_tests.cpp
modules/gapi/test/cpu/gapi_operators_tests_fluid.cpp
modules/gapi/test/internal/gapi_int_backend_tests.cpp
modules/gapi/test/internal/gapi_int_executor_tests.cpp
modules/gapi/test/internal/gapi_int_garg_test.cpp
modules/gapi/test/internal/gapi_int_gmetaarg_test.cpp
modules/gapi/test/internal/gapi_int_gmodel_builder_test.cpp
modules/gapi/test/internal/gapi_int_island_fusion_tests.cpp
modules/gapi/test/internal/gapi_int_island_tests.cpp
modules/gapi/test/internal/gapi_int_recompilation_test.cpp
modules/gapi/test/internal/gapi_int_resolve_kernel_test.cpp
modules/gapi/test/internal/gapi_int_vectorref_test.cpp
modules/gapi/test/internal/gapi_transactions_test.cpp
modules/gapi/test/own/gapi_types_tests.cpp
modules/gapi/test/own/mat_tests.cpp
modules/gapi/test/own/scalar_tests.cpp
modules/gapi/test/util/any_tests.cpp
modules/gapi/test/util/optional_tests.cpp
modules/gapi/test/util/variant_tests.cpp

Force using of relative includes to avoid mess in world builds.
```
```

build: fix world G-API tests

---

modules/gapi/include/opencv2/gapi/util/variant.hpp

resolves #14143 
<cut/>
```
buildworker:Custom=linux-1,linux-2
```

GAPI: fix build with Intel Compiler 2019

---

modules/dnn/src/op_inf_engine.cpp
modules/dnn/test/test_ie_models.cpp

resolves #14246
Mac support for Op Inference Engine. 
Added a condition to check for mac os and add corresponding libraries.

Master mac openvino support

---

doc/py_tutorials/py_imgproc/py_thresholding/py_thresholding.markdown

Improves the tutorial from the documentation's Python Tutorials > Image Processing > Thresholding
* fix grammar issues 
* fix small incorrections (e.g. "threshold value is the mean of neighbourhood area" where it is actually the mean minus C)
In the areas that I changed, I switched to a one sentence per line scheme.
**WIP**

Improve python image processing thresholding tutorial

---

modules/imgcodecs/src/grfmt_tiff.cpp
modules/imgcodecs/src/grfmt_tiff.hpp
modules/imgcodecs/src/utils.cpp
modules/imgcodecs/src/utils.hpp
modules/imgcodecs/test/test_tiff.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/588
- more checks
- drop separate branches for 32FC1 handling
- added for 32F/64F non-compressed
- added tests for 32FC3 (RAW + hdr SGILOG compression)
- added test 64FC1
- dump tiff errors on stderr
- cvSize->Size (align with master branch)
[Coverage build](http://pullrequest.opencv.org/buildbot/export/opencv_releases/3_4_coverage-lin64-debug/20190404-113749_347/coverage_html/opencv/modules/imgcodecs/src/index.html).

imgcodecs(tiff): sanitize tiff decoder

---

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/src/tensorflow/tf_graph_simplifier.hpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

resolves https://github.com/opencv/opencv/issues/14224
resolves https://github.com/opencv/opencv/issues/14073
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/589
<cut/>
```
**WIP**
```

Remove Switch and Merge nodes from TensorFlow networks

---

modules/videoio/src/cap_avfoundation_mac.mm

resolves #14258
resolves #12763
Added authorization status check and authorization request to AVFoundation camera backend for OSX Mojave (10.14+).
**Note**: to be backported to 3.4 with part of #14156 
force_builders_only=Mac,iOS

Added authorization request to AVFoundation camera backend (OSX 10.14+)

---

modules/core/include/opencv2/core/version.hpp

OpenCV 3.4.6
relates #14038
<cut/>
<details>
[opencv_world346.dll (vc14)](https://www.virustotal.com/gui/file/c811a1e64a8e4c6933cb4d57bb6464617c27b00d812700cfc82c32424b7a84ea/detection)
[opencv_world346d.dll (vc14)](https://www.virustotal.com/gui/file/ac4605bcaa0375aa2f1d971397b9bd708c98b9f42c8650e38f8b84f046d3abd9/detection) (1 detection, [considered false positive](https://stackoverflow.com/questions/54052224/virustotal-trapmine-suspicious-low-ml-score) - 2019-04-07)
[opencv_world346.dll (vc15)](https://www.virustotal.com/gui/file/30143f5f0dc9cdd046a5f4db7b503998b5fd67b6f5dc41f82ee58ac90a59bdd7/detection)
[opencv_world346d.dll (vc15)](https://www.virustotal.com/gui/file/2802b417e018cb204488368175c0673b07816d32e778e16830efe7e589693d47/detection) …

OpenCV release (3.4.6)

---

modules/videoio/src/cap_ffmpeg_impl.hpp

They are not part of the C++ standard, and MSVC will error out:
```
error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
```
<cut/>
See [godbolt example](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,lang:c%2B%2B,source:'%23include+%3Cstring%3E%0A%0Aint+main()+%7B%0A++++std::string%7B%22hello%22%7D%3B%0A++++(std::string)%7B%22hello%22%7D%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:51.836498185407095,l:'4',m:99.99999999999999,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:vcpp_v19_20_x64,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),lang:c%2B%2B,libs:!(),options:'',source:1),l:'5',n:'0',o:'x64+msvc+v19.20+(Editor+%231,+Comp …

Do not use compound literals (fix MSVC C4576)

---

modules/videoio/src/cap_avfoundation_mac.mm

related #14267
Compile-time check has been replaced with runtime check.
**cc** @jeroen
```
force_builders_only=Mac,iOS
```

AVFoundation: Use runtime check for camera authorization

---

modules/dnn/src/dnn.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/layers/flatten_layer.cpp
modules/dnn/src/layers/padding_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/592
<cut/>
```
```

Enable some tests for Inference Engine 2019R1

---

modules/dnn/src/tensorflow/tf_importer.cpp

Get number of channels from an initialized blob.
resolves https://github.com/opencv/opencv/issues/14236

Fix a bug in FusedBatchNorm (TensorFlow) layer importer

---

modules/core/include/opencv2/core/private.hpp
modules/core/include/opencv2/core/utils/allocator_stats.hpp
modules/core/include/opencv2/core/utils/allocator_stats.impl.hpp
modules/core/src/alloc.cpp
modules/core/src/ocl.cpp
modules/core/src/system.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp
modules/ts/include/opencv2/ts.hpp
modules/ts/include/opencv2/ts/ts_ext.hpp
modules/ts/include/opencv2/ts/ts_perf.hpp
modules/ts/misc/testlog_parser.py
modules/ts/src/precomp.hpp
modules/ts/src/ts.cpp
modules/ts/src/ts_perf.cpp
modules/ts/src/ts_tags.cpp
modules/ts/src/ts_tags.hpp
platforms/scripts/valgrind.supp

`--gtest_filter` is not enough for flexible tests filtering on multiple platforms in multiple configurations: 32-bit / debug / valgrind / coverage / etc.
resolves #12710
related #12502 #11523
Patch includes:
- added functionality to collect memory usage of OpenCL sybsystem
- memory usage of `fastMalloc()` (disabled by default):
* It is not accurate sometimes - external memory profiler is required.
- specify common `CV_TEST_TAG_` macros
- added `applyTestTag()` function
- write memory usage / enabled tags into Google Tests output file (.xml)
TODO:
```
force_builders=linux32,win32
buildworker:Linux x64 Debug=linux-1
```

ts: support test tags

---

apps/traincascade/cascadeclassifier.cpp

Add flushing to printing number of processed positive/negative samples so that when running opencv_traincascade, the user is informed of updates quicker.
Without this change I got updates one per half of hour.

Add flushing to printing number of processed positive/negative samples so that user is informed of updates quicker

---

modules/dnn/src/op_inf_engine.cpp

There is no `<vpu/vpu_plugin_config.hpp>` in the https://github.com/opencv/dldt

Fix dnn with IE from GitHub

---

cmake/templates/OpenCVConfig.cmake.in

resolves #14323 
Resolve symlinks when setting `OpenCV_CONFIG_PATH`.

Fix OpenCVConfig.cmake for Arch Linux.

---

samples/dnn/README.md

Remove dnn samples arguments from README page. Some of them are outdated.
related: http://answers.opencv.org/question/211466/faster-rcnn-no-results/

Remove preprocessing parameters from README

---

cmake/OpenCVDetectTBB.cmake

Adds `IMPORTED` for the `TBB::tbb` alias target as otherwise cmake produces the following error:
```
CMake Error: install(EXPORT "OpenCVModules" ...) includes target "opencv_core" which requires target "tbb" that is not in the export set.
```
This problem occurs with the defaults used by homebrew on macOS, which compiles both static and shared versions of TBB and OpenCV. The problem should also occur on other platforms when `-DBUILD_SHARED_LIBS=OFF` is set and an external TBB library is used. However, I don't have the setup to verify this in practice.
A similar fix is implemented in #12741 for another module.
```
Xbuild_tbb=ON
Xwith_tbb=ON
Xbuild_shared=OFF
```

Fix compile error with external TBB and -DBUILD_SHARED_LIBS=OFF

---

cmake/OpenCVPCHSupport.cmake

process defines from INTERFACE targets
relates https://github.com/opencv/opencv/pull/14277#discussion_r274877920

cmake: fix PCH generation

---

modules/java/test/pure_test/build.xml
modules/ts/misc/run_utils.py

tests: workaround for DYLD_LIBRARY_PATH on Apple MacOSX

---

cmake/OpenCVUtils.cmake

- compiler's vars are no available in global scope of OpenCVUtils.cmake (`project(CXX)` is called after including of this file)
- added include guard into `OpenCVUtils.cmake`
- added support for `MODULE_LIBRARY`
<cut/>
CMake 3.7.0 (3.14.1 is file) emits this message for opencv_java:
```
CMake Error:
Error evaluating generator expression:
$<IF:$<BOOL:$<TARGET_PROPERTY:opencv_java,COMPILE_PDB_NAME_DEBUG>>,$<TARGET_PROPERTY:opencv_java,COMPILE_PDB_NAME_DEBUG>,$<TARGET_PROPERTY:opencv_java,COMPILE_PDB_NAME>>
Expression did not evaluate to a known generator expression
CMake Error:
Error evaluating generator expression:
$<IF:$<BOOL:$<TARGET_PROPERTY:opencv_java,COMPILE_PDB_NAME_RELEASE>>,$<TARGET_PROPERTY:opencv_java,COMPILE_PDB_NAME_RELEASE>,$<TARGET_PROPERTY:opencv_java,COMPILE_PDB_NAME>> …
```

cmake: fix PDB processing

---

modules/core/include/opencv2/core/utils/logger.defines.hpp
modules/core/include/opencv2/core/utils/logger.hpp
modules/core/include/opencv2/core/utils/logtag.hpp
modules/core/src/logger.cpp
modules/core/src/utils/logtagconfig.hpp
modules/core/src/utils/logtagconfigparser.cpp
modules/core/src/utils/logtagconfigparser.hpp
modules/core/src/utils/logtagmanager.cpp
modules/core/src/utils/logtagmanager.hpp
modules/core/test/test_logtagconfigparser.cpp
modules/core/test/test_logtagmanager.cpp

```
```
Logging revamp for OpenCV 4.1.x, [OE-11](https://github.com/opencv/opencv/wiki/OE-11.-Logging), issue #11003
This PR replaces #13642 because the old PR was not salvageable.
Please keep all high-level or design-level discussions to the issue thread #11003 to keep the dialogue in one place.
Rebase and squash will happen, therefore keep in mind *code review comments might be lost*. Please put *persistent* comments (specific to the code changes in this PR and which are not high-level design issues) in this PR.
**Do not merge yet** - the PR contains numerous behavior changes that still need to be ironed out for backward compatibility. Also missing "meaningful" performance tests.
- **The logging output format is changed; this is an observable library behavior …

OE-11 Logging revamp (#11003) for 4.2.x (draft (logging_20190220))

---

modules/core/src/directx.cpp

relates #13972
fix usage of clGetPlatformIDs in initializeContextFromD3D11Device

FIX: getting platformIDs in initializeContextFromD3D11Device

---

modules/core/include/opencv2/core/utils/logtag.hpp
modules/core/src/logger.cpp
modules/core/src/utils/logtagconfigparser.cpp
modules/core/src/utils/logtagmanager.cpp
modules/core/src/utils/logtagmanager.hpp
modules/core/test/test_logtagmanager.cpp

Some compilers has lack of proper support for that
[Failed nightly build](http://pullrequest.opencv.org/buildbot/builders/master_winpack-build-win64-vc14/builds/10797/steps/compile%20debug/logs/stdio).
[Validation build](http://pullrequest.opencv.org/buildbot/builders/master_winpack_controller/builds/10801) :+1:

build: reduce usage of constexpr

---

cmake/OpenCVPCHSupport.cmake

fixes build with VTK
relates #14313
[Failed nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL_noICV_noSSE-lin64-debug/builds/364).
[Validation build](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL_noICV_noSSE-lin64-debug/builds/365) :+1:

cmake: guard macro definitions in PCH scripts

---

modules/ts/src/ts.cpp

similar to '--test_require_data' parameter
Will be enabled on CI by default to catch issues like this: https://github.com/opencv/opencv/pull/14368#issuecomment-485341446
<cut/>
It [works](http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/20236/steps/test_dnn/logs/stdio) =(

 ts: +ENV{OPENCV_TEST_REQUIRE_DATA}

---

samples/cpp/detect_mser.cpp

Corrected spelling of "synthetic" and added grammatical clarification for keys to press to change view or use mouse.
<cut/>
Fix 1 (line 41):
`syntehtic` to `synthetic`
-spelling correction
Fix 2 (line 43):
`2, 8, 4, 6, +,- or 5 keys` to `2, 8, 4, 6, +, -, or 5 keys`
-grammatical clarification

Grammatical errors for help() in detect_mser.cpp

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/misc/java/test/Calib3dTest.java

Fixes: https://github.com/opencv/opencv/issues/14169

calib3d: add find4QuadCornerSubpix java wrapper

---

modules/core/include/opencv2/core/hal/intrin_vsx.hpp

```BASH
List failed tests (first 10):
hal_intrin128.uint16x8_BASELINE :
SIMD128: void opencv_test::hal::intrin128::cpu_baseline::test_hal_intrin_uint16()
/worker/buildbot/Power9_Linux_gcc-6__opencv/opencv/modules/core/test/test_intrin_utils.hpp:778: Failure
Expected equality of these values:
(unsigned)(R::nlanes*R::nlanes/4)
Which is: 16
v_reduce_sad(a, b)
Which is: 10
````
````
pw_compilers=gcc-4.9, gcc-5, power9_gcc-6, power9_gcc-7
````

core:vsx fix sum of v_reduce_sad

---

modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/test/test_caffe_importer.cpp

resolves https://github.com/opencv/opencv/issues/14404
<cut/>
```
test_module:Mac OpenCL=dnn,python2,python3,java
```

Fix batching in DetectionOutput layer for IE backend

---

modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/test/gapi_fluid_resize_test.cpp
modules/gapi/test/gapi_fluid_test_kernels.cpp
modules/gapi/test/gapi_fluid_test_kernels.hpp

* Fixed incorrect first iteration window setting for fluid FilterAgent: previously it was unconditionally set to Filter's lpi value which lead to incorrect work on small images/rois
```
```

G-API fluid fix small rois

---

modules/videoio/src/cap_v4l.cpp

Related #13969
Resolves #14439
Build with enabled V4L2 failed on CentOS 6.10 (docker image `condaforge/linux-anvil-comp7`):
```
../modules/videoio/src/cap_v4l.cpp: In function 'int cv::capPropertyToV4L2(int)':
../modules/videoio/src/cap_v4l.cpp:1614:16: error: 'V4L2_CID_ROTATE' was not declared in this scope
return V4L2_CID_ROTATE;
^~~~~~~~~~~~~~~
../modules/videoio/src/cap_v4l.cpp:1614:16: note: suggested alternative: 'V4L2_CID_BASE'
return V4L2_CID_ROTATE;
^~~~~~~~~~~~~~~
V4L2_CID_BASE
../modules/videoio/src/cap_v4l.cpp:1616:16: error: 'V4L2_CID_IRIS_ABSOLUTE' was not declared in this scope
return V4L2_CID_IRIS_ABSOLUTE;
^~~~~~~~~~~~~~~~~~~~~~
../modules/videoio/src/cap_v4l.cpp:1616:16: note: suggested alternative: 'V4L2_CID_FOCUS_ABSOLUTE'
return V4L2_CID_IRIS_ABSOLUTE; …
```

Support very old V4L

---

modules/ts/src/ts.cpp

relates #12783
Messages like these:
```
[ INFO:0] Memory_usage (OpenCV): 0 (base=0  current=0)
[ INFO:0] Memory_usage (OpenCL): 0 (base=0  current=0)
```

ts: silence zero memory usage messages

---

modules/imgproc/src/hough.cpp

resolves #14432
relates #10232

imgproc: fix RemoveOverlaps() with empty input vector

---

modules/dnn/src/layers/lrn_layer.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_common.hpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp

Observed regression as `DNNTestNetwork.Inception_5h` test with LRN layer. Add more checks to be ensured that all the layers from networks are supported by IE backend
Also remove skips in case of missed test data.
<cut/>
```
test_module:Mac …
```

Check if Inference Engine networks are fully supported by backend

---

doc/opencv.bib
modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/levmarq.cpp
modules/calib3d/src/precomp.hpp
modules/calib3d/src/solvepnp.cpp
modules/calib3d/test/test_solvepnp_ransac.cpp

related #14181 
This is a draft to see how adding a separate function to refine a pose after `solvePnP` would look:
- `solvePnPRefineLM` the classical Levenberg-Marquardt iterative minimization process
- `solvePnPRefineVVS` minimize the projection error using a virtual visual servoing scheme
---
`LMSolver` should be compared to the C implementation code for the Levenberg-Marquardt:
https://github.com/opencv/opencv/blob/7b8ce63730430edeaf26790020dbe23b6a8ddf81/modules/calib3d/src/calibration.cpp#L1221-L1248
Also, I have added the possibility to set the epsilon in the LM implementation.

Add solvePnPRefineLM and solvePnPRefineVVS

---

modules/video/perf/opencl/perf_dis_optflow.cpp
modules/video/src/dis_flow.cpp
modules/video/src/opencl/dis_flow.cl

resolves #14372
Added reduction implementation via OpenCL shared memory (compatible with OpenCL 1.2).
TODO:
<cut/>
```
```

video(DISOpticalFlow): use OpenCL shared mem

---

modules/dnn/src/op_inf_engine.cpp
modules/dnn/test/test_misc.cpp

resolves https://github.com/opencv/opencv/issues/14483
relates #13694
<cut/>
```
test_module:Mac OpenCL=dnn,python2,python3,java
```

Fix uint8 input data for Async mode of dnn

---

cmake/OpenCVCompilerDefenses.cmake

Adds hardening support for clang and Apple clang builds.
**Note:** linker in XCode does not support `-z` option

Added support for clang build hardening

---

cmake/OpenCVCompilerOptimizations.cmake

- fix misused `CPU_DISPATCH`, `CPU_DISPATCH_FINAL` should be used for filtering
Usage:
```
cmake -DCPU_DISPATCH=ALL ...
```
Main purpose of ALL value is enable testing of all available CPU configurations (even if they are not in default list).
<cut/>
<details>
<summary>Result:</summary>
```
--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3
--       requested:                 SSE3
--     Dispatched code generation:  SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CNL AVX512_CEL AVX512_ICL
--       requested:                 SSE SSE2 SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CNL AVX512_CEL AVX512_ICL
--       SSSE3 (1 files):           + …
```

cmake: support CPU_DISPATCH=ALL

---

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/src/tensorflow/tf_graph_simplifier.hpp
modules/dnn/src/tensorflow/tf_importer.cpp

Reduce a bit memory consumption of TensorFlow models (`cv::readNet`)
<cut/>
| model | Before PR (readNet mem consumption) | With PR | model file size |
| ssd_inception_v2_coco_2017_11_17 | 183MB | 162MB | 98MB |
| ssd_mobilenet_v1_coco_2017_11_17 | 79MB | 73MB | 28MB |
| faster_rcnn_inception_v2_coco_2018_01_28 | 127MB | 116MB | 55MB |
| EAST text detection | 147MB | 139MB | 93MB |
| Inception | 110.9MB | 110.8MB | 52MB |
Still a bit unclear why the numbers are two times larger than the sizes of binary models.

Remove extra weights cloning from TensorFlow importer

---

modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java

resolves #14477
relates #10081
Some of `uv_mat1` or `uv_mat2` is malformed (creates view outside of allocated buffer).
Select correct Mat for future processing.
```
```

android: fix JavaCamera2View UV plane handling

---

modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/src/layers/proposal_layer.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp

Do not recreate output blob in DetectionOutput layer but fill it by zeros.
resolves https://github.com/opencv/opencv/issues/14530

Fixed DetectionOutput output blob shape

---

modules/calib3d/src/levmarq.cpp

```
>>>     CID 1444972:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "epsf" is not initialized in this constructor nor in any functions that it calls.
83         LMSolverImpl() : maxIters(100) { init(); }
```

calib3d: fix uninitialized fields in ctors

---

modules/core/include/opencv2/core/cvstd.inl.hpp

`cv::String` is `std::string` in OpenCV 4.x

core: drop 'operator << (ostream, String)' overload

---

modules/imgproc/src/geometry.cpp
modules/imgproc/test/test_intersectconvexconvex.cpp

Added checks for all of vertices from each contour instead of checking
only for the first vertex.
Fixes: https://github.com/opencv/opencv/issues/14367

imgproc: fixed intersectConvexConvex

---

modules/core/include/opencv2/core/base.hpp

Fix typo in [`NormTypes`](https://docs.opencv.org/4.1.0/d2/de8/group__core__array.html#gad12cefbcb5291cf958a85b4b67b6149f) documentation: 
should be `NORM_RELATIVE | NORM_L2SQR` for the last one.

Fix typo in NormTypes documentation

---

modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/test/gapi_fluid_resize_test.cpp

* Added an adjustment for roi produced by NV12toRGB to always be even

G-API Fixed fluid roi inference to always produce even sizes for nv12

---

modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra:** opencv/opencv_extra#602
<cut/>
```
force_builders=Linux AVX2,Custom,Mac OpenCL
docker_image:Linux AVX2=ubuntu-openvino-2019r1:16.04
```

Support BatchNorm3D layer on IE backend

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/onnx/onnx_importer.cpp

This change allows ONNX model blob already loaded in-memory to be passed to the ONNX importer from which to initialize the cv::dnn::Net instance.  It accomplishes this by wrapping the in-memory buffer with std::streambuf interface which std::istream requires in order to read data from it.  Hopefully this functionality would be generally useful.
I'm open to renaming the top-level function to something more appropriate if the name I've given is not consistent with any sort of naming convention.
Thanks,
Kohei

Add support for loading ONNX model from in-memory buffer.

---

doc/opencv.bib
modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/ap3p.cpp
modules/calib3d/src/ap3p.h
modules/calib3d/src/ippe.cpp
modules/calib3d/src/ippe.hpp
modules/calib3d/src/p3p.cpp
modules/calib3d/src/p3p.h
modules/calib3d/src/solvepnp.cpp
modules/calib3d/test/test_solvepnp_ransac.cpp

**Merge with opencv_extra**: https://github.com/opencv/opencv_extra/pull/606
@tobycollins This is the (draft) pull request following tobycollins/IPPE#4
Main differences with the original IPPE code:
- camera parameters and distortion coefficients are not used since we pass already points in normalized camera frame
- add some code to be compatible with `CV_32F`/`CV_64F` input types
- cosmetic changes, use `CV_Assert`, ...
---
Main changes:
- add `SOLVEPNP_IPPE` for planar pose estimation
- add `SOLVEPNP_IPPE_SQUARE` for tag pose estimation (`z=0`, frame is centered)
- add `solvePnPGeneric` that returns all the solutions and optionally the reprojection error
- rewrite tests and add new tests
``` …
```

Add IPPE method for planar pose estimation in solvePnP

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
samples/dnn/tf_text_graph_faster_rcnn.py

resolves https://github.com/opencv/opencv/issues/13720
Add support of [faster_rcnn_nas_coco_2018_01_28](http://download.tensorflow.org/models/object_detection/faster_rcnn_nas_coco_2018_01_28.tar.gz) from TensorFlow.
Known problems:
* Object detection classes are shifted for Faster R-CNN networks (need to fix a sample or list of classes?)
* Faster R-CNN from TensorFlow don't work on random input (need to test on images with no detections). Reason - the first DetectionOutput may have less detections than allocated memory. Possible solution - fill the rest of output blob by zeros. (fixed by https://github.com/opencv/opencv/pull/14552)
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/604
``` …
```

StridedSlice from TensorFlow

---

modules/gapi/include/opencv2/gapi/gcomputation.hpp
modules/gapi/src/api/gcomputation.cpp
modules/gapi/test/gapi_gcomputation_tests.cpp

Consider the following case:
```
TEST(GComputationTest, VectorAsOutputApply)
{
cv::GMat in;
cv::GMat out[3];
std::tie(out[0], out[1], out[2]) = cv::gapi::split3(in);
cv::Mat in_mat(3, 3, CV_8UC3);
cv::randu(in_mat, cv::Scalar::all(0), cv::Scalar::all(255));
std::vector<cv::Mat> out_mats(3);
std::vector<cv::Mat> ref_mats(3);
cv::split(in_mat, ref_mats);
cv::GComputation({in}, {out[0], out[1], out[2]}).apply({in_mat}, out_mats);
EXPECT_EQ(cv::Size(3, 3), out_mats[0].size());
for (const auto& it : ade::util::zip(ref_mats, out_mats))
{
const auto& ref_mat = std::get<0>(it);
const auto& out_mat = std::get<1>(it);
EXPECT_EQ(0, cv::countNonZero(ref_mat != out_mat));
}
}
```
This will work fine if the output matrices are preallocated
```
for (auto& out_mat : out_mats)
{ …
```

G-API: GComputation doesn't work with output vector<cv::Mat>

---

modules/videoio/doc/videoio_overview.markdown
modules/videoio/include/opencv2/videoio/registry.hpp

resolves #14508
Removed mention of `cvconfig.h`, added instruction on building videoio plugins.

Docs: updated videoio module overview

---

modules/core/misc/java/src/java/core+CvType.java
modules/core/misc/java/test/CvTypeTest.java

resolves #14211
- Adds CvType.CV_16F
- Deprecate `CV_USRTYPE1`, since it has the same value as `CV_16F`
- typeToString() is changed to return `CV_16F` instead of `CV_USRTYPE1`

java: add CvType.CV_16F

---

modules/core/misc/java/src/java/core+CvType.java
modules/core/misc/java/src/java/core+Mat.java
modules/imgproc/misc/java/src/java/imgproc+Moments.java
modules/java/generator/android/java/org/opencv/android/Utils.java
modules/java/generator/src/java/org/opencv/utils/Converters.java

In java, `java.lang` package is implicitly imported, so there is no need to fully qualify the classes, e.g. it would be redundant to say `java.lang.String`.

java: remove redundant declaration of java.lang package

---

modules/videoio/src/cap_images.cpp
modules/videoio/src/precomp.hpp

resolves #14617
- allowed pattern format is `%0?[1-9]?[du]`
- don't use buffers on stack
- multiple '%' patterns are not allowed
- `%%` is not allowed

imgcodecs(CAP_IMAGES): fix handling of input pattern

---

modules/calib3d/misc/java/gen_dict.json
modules/calib3d/misc/java/test/Calib3dTest.java

The values of CALIB_FIX_K1, CALIB_FIX_K2, CALIB_FIX_K3, and CALIB_FIX_K4 reset by gen_dict.json are incorrect. Correct values are output by removing unnecessary missing_consts blocks.
https://github.com/opencv/opencv/blob/master/modules/calib3d/include/opencv2/calib3d.hpp#L262-L265
https://github.com/opencv/opencv/blob/master/modules/calib3d/misc/java/gen_dict.json#L5-L19

java: fix java missing_consts

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/test/test_intrin_utils.hpp

Fixed v_signmask implementation for AVX2, updated universal intrinsics tests.

Fixed v_signmask implementation for AVX2

---

modules/imgcodecs/src/grfmt_tiff.cpp

Only some TIFF-orientations were handled properly for  8-bit-images, 16/32-bit were completely broken. This fixes it.
Attached is an example-program (main.cpp) and sample images with multiple depths (8, 16, 32-float)  and all 8 orientations.
[tif-orient-fix.tar.gz](https://github.com/opencv/opencv/files/3212170/tif-orient-fix.tar.gz)

handle all orientations properly

---

modules/java/test/pure_test/build.xml
modules/ts/misc/run.py
modules/ts/misc/run_suite.py

Usage example:
- `run.py -a -t java --package=calib3d`

java(test): test package filtering

---

CMakeLists.txt
cmake/OpenCVDetectTBB.cmake

resolves #12415
* fixed IE detection status printing on OSX (use `IMPORTED_LOCATION_<CFG>` properties)
* Debug build with TBB (from system package) - made debug library optional
<cut/>
```
Inference Engine:            YES (2019010000 / 1.6.0)
libs:            _lib_rel-NOTFOUND / _lib_dbg-NOTFOUND
```
```
Inference Engine:            YES (2019010000 / 1.6.0)
libs:            <ieroot>/lib/intel64/libinference_engine.dylib / <ieroot>/lib/intel64/libinference_engined.dylib
```
``` …
```

Fix TBB debug and IE status information

---

modules/js/src/core_bindings.cpp
modules/js/src/embindgen.py
modules/js/test/test_imgproc.js

previously floodFill() is white-list without any implementation.
floodFill() is now fully functional in JS.
Fixes: https://github.com/opencv/opencv/issues/14525
```
```

js: added floodFill function to JS binding

---

modules/calib3d/misc/java/test/Calib3dTest.java
modules/core/misc/java/test/MatTest.java
modules/core/misc/java/test/RotatedRectTest.java
modules/imgcodecs/misc/java/test/ImgcodecsTest.java
modules/java/test/android_test/src/org/opencv/test/OpenCVTestCase.java
modules/java/test/android_test/src/org/opencv/test/OpenCVTestRunner.java
modules/java/test/android_test/src/org/opencv/test/android/UtilsTest.java
modules/java/test/pure_test/src/org/opencv/test/OpenCVTestCase.java
modules/objdetect/misc/java/test/CascadeClassifierTest.java

This is the first part of JUnit tests update, as they are with JUnit 3 syntax, while JUnit 4 syntax can be used. Another option is to migrate to JUnit 5, but that needs Java 8.
**Proposed change:**
To use specific assertions (e.g. `assertFalse`, `assertNotNull`, `assertEquals`) instead of `assertTrue` with condition. This leads to a little better readability.

java: test: use assertNotNull and assertFalse

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/perf/perf_pnp.cpp
modules/calib3d/src/calibration.cpp
modules/calib3d/src/solvepnp.cpp
modules/calib3d/test/test_cameracalibration.cpp
modules/calib3d/test/test_solvepnp_ransac.cpp
modules/calib3d/test/test_undistort.cpp
modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/undistort.cpp

**Merge with opencv_extra**: https://github.com/opencv/opencv_extra/pull/609
resolves #14423 
Try to uniform input shape for:
- `solvePnPRansac`
- `solvePnP`
- `undistortPoints`
- `projectPoints`

Fix solvePnPRansac and Nx3 1-channel input when N=5

---

modules/videoio/src/cap_dshow.cpp

* Missing getter for CV_CAP_PROP_CONVERT_RGB, CAP_PROP_CHANNEL
Refactoring:
* moved `pControl->Stop()` before deleting any resources.
* used switch case for `CV_CAP_PROP_SETTINGS` instead of `if`
```
```

VideoCapture Direct Show. Added getter for CV_CAP_PROP_CONVERT_RGB, CAP_PROP_CHANNEL properties.

---

modules/imgproc/src/color_hsv.simd.hpp
modules/imgproc/src/color_lab.cpp

resolves #14629 
Fixed out of bounds read for cases when number of channels is the same between conversions.
In these cases a block size can be arbitrary i.e. not a multiplier of a number of channels.
```
```

Fixed out of bounds read for RGB2HLS_b and RGB2Luv_b

---

modules/video/src/dis_flow.cpp
modules/video/src/opencl/dis_flow.cl
modules/video/src/variational_refinement.cpp
modules/video/test/ocl/test_dis.cpp

There is still a lot of CPU code (`calcUV()`) in OpenCL path.
<cut/>
<details>
<summary>Performance i5-6600 (2019-05-04)</summary>
OpenCL changes:
|Name of Test|OpenCL base|OpenCL patch|x-factor|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_FAST", 640x480)|4.925|4.351|1.13|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_FAST", 1280x720)|11.652|10.717|1.09|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_FAST", 1920x1080)|23.907|22.218|1.08|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_MEDIUM", 640x480)|15.054|14.218|1.06|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_MEDIUM", 1280x720)|48.519|47.960|1.01|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_MEDIUM", 1920x1080)|119.827|119.602|1.00|
|perf::OCL_DenseOpticalFlow_DIS::("PRESET_ULTRAFAST", 640x480)|2.391|2.020|1.18| …

video(DISOpticalFlow): update OpenCL implementation

---

modules/core/misc/java/src/java/core+KeyPoint.java
modules/core/misc/java/src/java/core+Mat.java
modules/java/generator/gen_java.py

The generated code should not have redundant `return;` statements, and whenever possible, directly return the created object.
Also, this change excludes all imports in `java.lang.` package.

java: generated code inline return

---

3rdparty/libpng/patches/20190528-fix-leak-png_handle_exif.diff
3rdparty/libpng/pngrutil.c

https://github.com/glennrp/libpng/commit/a142b7a543d16d271b8aba3ef7ca4aa9a368f55d

3rdparty(libpng): fix leak in png_handle_eXIf

---

3rdparty/libpng/patches/20190528-fix-leak-png_handle_exif.diff
3rdparty/libpng/pngrutil.c

(3.4) 3rdparty(libpng): fix leak in png_handle_eXIf

---

modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_common.hpp
modules/dnn/test/test_common.impl.hpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_tf_importer.cpp

- reading via `std::istreambuf_iterator<char>` is slow (especially in debug mode)
- raise errors from helper function

dnn(test): replace file content reading

---

modules/core/CMakeLists.txt
modules/core/include/opencv2/core/hal/intrin.hpp
modules/core/include/opencv2/core/hal/intrin_avx512.hpp
modules/core/include/opencv2/core/hal/intrin_forward.hpp
modules/core/test/test_intrin.cpp
modules/core/test/test_intrin512.simd.hpp
modules/core/test/test_intrin_utils.hpp
modules/imgproc/src/contours.cpp
modules/imgproc/src/resize.cpp
modules/imgproc/src/sumpixels.cpp

relates #13891
Implementation of 512-bit wide universal intrinsics for AVX512
https://github.com/opencv/opencv/wiki/OE-29.-Adding-AVX512-Support
<cut/>
TODO:
```
force_builders=docs,linux,Custom
#build_image:Custom Mac=
CPU_BASELINE:Custom Mac=AVX512_SKX
```

AVX512 wide universal intrinsics

---

3rdparty/libjpeg/README
3rdparty/libjpeg/change.log
3rdparty/libjpeg/jcinit.c
3rdparty/libjpeg/jcmaster.c
3rdparty/libjpeg/jctrans.c
3rdparty/libjpeg/jdatadst.c
3rdparty/libjpeg/jdcolor.c
3rdparty/libjpeg/jdct.h
3rdparty/libjpeg/jdhuff.c
3rdparty/libjpeg/jdmainct.c
3rdparty/libjpeg/jdmaster.c
3rdparty/libjpeg/jdmerge.c
3rdparty/libjpeg/jfdctflt.c
3rdparty/libjpeg/jfdctfst.c
3rdparty/libjpeg/jidctflt.c
3rdparty/libjpeg/jidctfst.c
3rdparty/libjpeg/jidctint.c
3rdparty/libjpeg/jinclude.h
3rdparty/libjpeg/jpegint.h
3rdparty/libjpeg/jpeglib.h
3rdparty/libjpeg/jversion.h

https://www.ijg.org/
relates #10274
**Note**: libjpeg-turbo is used by default. libjpeg is deprecated (use for compatibility reasons only)

3rdparty: update libjpeg 9c

---

modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp
modules/gapi/test/cpu/gapi_core_tests_fluid.cpp
modules/gapi/test/gpu/gapi_core_tests_gpu.cpp

This pullrequest adds new parameters alpha and beta in tests on ConvertTo kernel

G-API: Add parameters alpha and beta in tests on ConvertTo kernel

---

modules/calib3d/src/calibration.cpp
modules/calib3d/test/test_cameracalibration.cpp

... to fix https://github.com/opencv/opencv/issues/11131 but preserve the good parts to keep https://github.com/opencv/opencv/issues/10791 fixed
resolves #11131
It reverts the wrong maths of b085158d5999fdced91094405f8753e9275092f6. That commit solved the issue #10791 by
1. calculating the rectification rotation in a new way, and
2. calculating the new focal length in a new way.
Please note that only the second change is needed to resolve the issue #10791, while the first change is actually wrong maths that can give arbitrary rotation around the Z axis. In other words, the rectified image can be rotated 180 degrees because of this, even though the rotation error is usually very small in the most typical stereo setup.
So, as the first change is both unnecessary and wrong, I reverted it. …

Revert the bad parts of b085158d5999fdced91094405f8753e9275092f6

---

samples/python/tutorial_code/core/mat_mask_operations/mat_mask_operations.py

because t = (time.time() - t) will return seconds,  dividing by 1000 to obtain seconds will be incorrect.
resolves #14711 
removes unnecessary divide by 1000
```
```

Remove divide by 1000

---

modules/core/src/system.cpp

[QNX](http://blackberry.qnx.com/en/products/neutrino-rtos/index) is a POSIX-compliant real-time embedded operating system. In general OpenCV's core builds correctly with the QNX cross-compiler. However, there is a small conflict with the `gettimeofday` function.
The QNX implementation of the C standard library does not define the `timezone` struct, and the `tv` field of `gettimeofday` is not used. Documentation is available here: http://www.qnx.com/developers/docs/6.5.0/index.jsp?topic=%2Fcom.qnx.doc.neutrino_lib_ref%2Fg%2Fgettimeofday.html
Therefore, to maintain build compatibility with QNX we can define variable `tz` as an int rather than a `timezone`, which does not affect anything downstream because `tz` is unused but does fix the compile error.

Fix build issue on QNX platform

---

CMakeLists.txt
doc/CMakeLists.txt
modules/calib3d/include/opencv2/calib3d.hpp
modules/core/include/opencv2/core.hpp
modules/cudaarithm/include/opencv2/cudaarithm.hpp
modules/features2d/include/opencv2/features2d.hpp
modules/java/generator/gen_java.py
modules/java/generator/templates/java_class.prolog
modules/java/generator/templates/java_class_inherited.prolog
modules/java/generator/templates/java_module.prolog
modules/java/jar/build.xml.in
modules/ml/include/opencv2/ml.hpp
modules/python/src2/hdr_parser.py
modules/videoio/include/opencv2/videoio.hpp

**Merge with opencv_contrib**: https://github.com/opencv/opencv_contrib/pull/2131
Related to #4286
Adds javadoc to generated code. However, there are some current limitations:
- `@code` is copied as is.  I guess it needs to be decided if `@code{.java}` should exist in `.cpp` or in `gen_dict.json`, to be discussed in a new issue.
- Many doxygen commands are not properly handled, they should be fixed, in future PRs.
- `@param` is assumed to span a single line, not on multiple lines
- Embedded `images` are not handled
- Tests of the javadoc to be added (optionally, can we invoke `gen_java.py` with test code?)
To implement in this PR:
```
opencv_contrib=param
```

java: generated code to have javadoc

---

cmake/checks/cpu_avx512skx.cpp

Some versions of GCC have problems with AVX-512 intrinsics in `-O0` mode (`CMAKE_BUILD_TYPE=Debug`), e.g. [bug 79932](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79932). And some corner cases, e.g. [bug 80353](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80353). Reproduced in GCC 5 and 6, no problems in 7.4.
Added more things to auto-detection program to avoid compiler errors in mentioned configurations. I think we can remove `operator <<` and `operator >>` overloads from universal intrinsics in future.
cc @terfendail

AVX 512 detection: workaround for older GCC with -O0

---

modules/calib3d/src/stereobm.cpp
modules/calib3d/src/stereosgbm.cpp
modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/features2d/src/fast.cpp
modules/features2d/src/fast_score.cpp
modules/imgproc/src/canny.cpp
modules/imgproc/src/corner.cpp
modules/imgproc/src/imgwarp.cpp
modules/imgproc/src/moments.cpp
modules/video/src/lkpyramid.cpp

- use compile-time checks instead (`#if CV_SIMD128`)
- runtime checks are useless

core(intrin): drop hasSIMD128 checks

---

modules/core/src/convert.dispatch.cpp
modules/core/src/convert.simd.hpp
modules/core/src/convert_scale.simd.hpp

Message from UBSAN:
<cut/>
> modules/core/src/convert.dispatch.cpp:213:9: runtime error: call to function cv::opt_AVX2::cvtScale32f(float const*, unsigned long, unsigned char const*, unsigned long, float*, unsigned long, cv::Size_<int>, double*) through pointer to incorrect function type 'void (*)(const unsigned char *, unsigned long, const unsigned char *, unsigned long, unsigned char *, unsigned long, cv::Size_<int>, void *)'
modules/core/src/convert_scale.simd.hpp:272: note: cv::opt_AVX2::cvtScale32f(float const*, unsigned long, unsigned char const*, unsigned long, float*, unsigned long, cv::Size_<int>, double*) defined here
```
```

core: avoid function type cast, make happy UBSAN

---

cmake/OpenCVCompilerOptimizations.cmake
modules/core/include/opencv2/core/hal/intrin_avx512.hpp
modules/imgproc/src/sumpixels.avx512_skx.cpp

Fix for MSVS2019 build warnings
<cut/>
```
force_builders=Custom Win,Custom
buildworker:Custom Win=windows-1
```

Fix for MSVS2019 build warnings

---

modules/videoio/cmake/plugin.cmake

cmake always installs `MODULE` targets to `LIBRARY DESTINATION` which is `lib` on Windows and is not used for _videoio_ plugins search.

Fixed plugin installation location on Windows

---

modules/java/generator/src/cpp/common.h

In JDK1.8 this is already done, I copied the definition for JDK1.7

make -fvisibility=hidden work with java 1.7

---

modules/videoio/cmake/detect_msdk.cmake

* in some distributions MediaSDK headers are located in `include/mfx` directory
* prefer libva shipped with MediaSDK, use system otherwise
**Note:** probably can be ported to 3.4 branch

Improved MediaSDK detection mechanism

---

modules/core/include/opencv2/core/hal/intrin_avx512.hpp

Rename parameters in AVX512 implementation of v_load/store_interleave
relates #14162
<cut/>
```
```

Rename parameters in AVX512 implementation of v_load/store_interleave

---

modules/dnn/src/layers/mvn_layer.cpp
modules/dnn/src/opencl/mvn.cl
modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/test/test_tf_importer.cpp

resolves https://github.com/opencv/opencv/issues/14683
Make MVN layer similar to Keras and Intel's Inference Engine (but now different to Caffe for big epsilon values).
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/617
```
```

Fix #14683

---

CMakeLists.txt

cmake: typo in hook name

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp
modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp
modules/gapi/include/opencv2/gapi/gcommon.hpp
modules/gapi/include/opencv2/gapi/gcompoundkernel.hpp
modules/gapi/include/opencv2/gapi/gkernel.hpp
modules/gapi/include/opencv2/gapi/gtransform.hpp
modules/gapi/include/opencv2/gapi/ocl/goclkernel.hpp
modules/gapi/include/opencv2/gapi/util/util.hpp
modules/gapi/src/api/gkernel.cpp
modules/gapi/src/compiler/passes/kernels.cpp
modules/gapi/test/gapi_transform_tests.cpp

Description:
In utils.h were created 2 classes to separate kernels from transformations via "tag" in kernel package;
GAPI_TRANSFORM is implemented in a way similar to G_TYPED_KERNEL
```
```

G-API Introduce GAPI_TRANSFORM initial interface

---

samples/dnn/js_face_recognition.html

Fix #14734 
Add `utilt.loadOpenCv()` at the beginning of `main()`, and set the original `main()` as its onloadCallback function.
Now the face recognition sample can load both opencv.js(asm.js) and opencv.js(WASM).
```
force_builders=Docs,Custom
```

opencv.js: fix the loading issue of opencv.js(WASM) in face recognition

---

modules/core/include/opencv2/core/cvstd.hpp
modules/videoio/src/cap_gstreamer.cpp
modules/videoio/src/precomp.hpp
modules/videoio/test/test_ffmpeg.cpp
modules/videoio/test/test_gstreamer.cpp
modules/videoio/test/test_video_io.cpp
platforms/scripts/valgrind.supp
platforms/scripts/valgrind_3rdparty.supp

- exception-safe smart pointers, fixed many memory leaks
- fixed errors handling
- fixed strings handling
- fixed file existence check
- fixed toFraction() implementation
- add 'drop=true' for v4l2 input
- avoid overriding custom pipelines sink's 'max-buffers' value
- updated valgrind supression rules
- added support for GStreamer native leaks tracking (via gst_deinit() call)
- repaired capturing through GStreamer0.10 (fixed CV_8UC1)
<cut/>
```
#build_image:Custom=gstreamer0.10:16.04
```

videoio: update GStreamer code

---

modules/core/include/opencv2/core/hal/intrin_avx512.hpp
modules/imgproc/src/sumpixels.avx512_skx.cpp

from [MSVS2017](http://pullrequest.opencv.org/buildbot/builders/3_4-win64-vc15/builds/29) and GCC8 -O1 mode
<cut/>
```
from modules/dnn/layers/layers_common.avx512_skx.cpp:2:
modules/core/include/opencv2/core/hal/intrin_avx512.hpp: In function ‘void cv::hal_AVX512_SKX::v_lut_deinterleave(const float*, const cv::hal_AVX512_SKX::v_int32x16&, cv::hal_AVX512_SKX::v_float32x16&, cv::hal_AVX512_SKX::v_float32x16&)’:
modules/core/include/opencv2/core/hal/intrin_avx512.hpp:1602:49: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
y.val = _mm512_i32gather_ps(idxvec.val, tab + 1, 4);
^
modules/core/include/opencv2/core/hal/intrin_avx512.hpp: In function ‘void cv::hal_AVX512_SKX::v_lut_deinterleave(const double*, const cv::hal_AVX512_SKX::v_int32x16&, …
```

core: eliminate AVX512 build warnings

---

modules/calib3d/CMakeLists.txt
modules/js/src/embindgen.py
modules/js/test/test_calib3d.js
modules/js/test/tests.html
modules/js/test/tests.js
platforms/js/build_js.py

resolves #14293
This adds javascript bindings for the calib3d module, along with tests.
Currently I have only added the `findHomography` function, but will add the rest of the module soon.
<cut/>
```
```

Add javascript bindings for calib3d module.

---

modules/core/include/opencv2/core/cvstd_wrapper.hpp

This pull request restores MSVC 2013 support to the core module.

core: revise syntax to support Visual C++ 2013

---

modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_common.hpp
modules/dnn/test/test_common.impl.hpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_googlenet.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_main.cpp
modules/dnn/test/test_misc.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp
modules/ts/include/opencv2/ts.hpp
modules/ts/src/ts_tags.cpp

For easy enabling of skipped tests without touching of test code.
<cut/>
Example:
```
./bin/opencv_test_dnn --test_tag_enable=dnn_skip_ie_myriadx --test_tag=dnn_skip_ie_myriadx
./bin/opencv_test_dnn --test_tag_enable=dnn_skip_ie_myriadx
./bin/opencv_test_dnn --test_tag_force=dnn_skip_ie_myriadx
```
Output examples:
```
[ SKIPSTAT ] 449 tests via tags
[ SKIPSTAT ] TAG='mem_6gb' skip 14 tests
[ SKIPSTAT ] TAG='verylong' skip 7 tests
[ SKIPSTAT ] TAG='dnn_skip_ie_myriadx' skip 131 tests
[ SKIPSTAT ] TAG='dnn_skip_ocl_fp16' skip 21 tests
[ SKIPSTAT ] TAG='dnn_skip_ie_2019r1' skip 0 tests (150 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_ie' skip 250 tests
[ SKIPSTAT ] TAG='dnn_skip_ie_ocl' skip 10 tests
[ SKIPSTAT ] TAG='dnn_skip_ie_ocl_fp16' skip 16 tests
[ SKIPSTAT ] 370 tests via …
```

dnn(test): replace SkipTestException with tags

---

modules/videoio/src/cap_mfx_common.cpp

On systems where the Intel GPU is not the primary device the obsolete flag MFX_IMPL_AUTO may cause a capture device created with the CAP_INTEL_MFX flag to use the software and not the hardware video decoder.
I can reproduce on a laptop with both an Nvidia and Intel GPU. Before the change the result of [this](https://github.com/opencv/opencv/blob/987061d800609ba8e4cff893fb6502bc6a4750c4/modules/videoio/src/cap_mfx_common.cpp#L26) was
`impl == MFX_IMPL_SOFTWARE`
after the change 
`impl == MFX_IMPL_VIA_D3D11 & MFX_IMPL_HARDWARE2`
Even if this does not effect every multiple device/monitor setup the obsolete flag should probably still be updated

Update obsolete flag in Intel video decoder.

---

modules/core/include/opencv2/core/hal/intrin_neon.hpp

core(intrin): v_load_low() workaround for aarch64+clang

---

modules/flann/include/opencv2/flann.hpp
modules/flann/include/opencv2/flann/dist.h

1. Keep a local copy of `features` matrix in `flann::GenericIndex` constructor. This fixes #4376 and #12606
2. Suppress some warnings in MSVC regarding implicit type conversions

Keep a local copy of `features` from `flann::GenericIndex ` constructor

---

modules/dnn/src/op_inf_engine.cpp

resolves https://github.com/opencv/opencv/issues/14852 (Linux, Mac only)
```
```

Limit number of threads in CPU plugin of IE by OpenCV's getNumThreads

---

modules/core/include/opencv2/core/private.hpp

This minor fix creates unique name for each scope-limited instrumentation variable.
This fixes compilation for cases when multiple region instrumentations enabled like in [dis_flow.cpp](https://github.com/opencv/opencv/blob/master/modules/video/src/dis_flow.cpp#L1095).

Fixed multi instrumentations

---

modules/dnn/src/op_inf_engine.cpp
modules/dnn/src/op_inf_engine.hpp

resolves #14912
Fixed compilation names conflict cv::Ptr in opencv/dnn and ICNNNetwork::Ptr in dldt.
Was added cv:: namespace to the Ptr
<cut/>
```
```

Fixed names conflict with dldt

---

modules/gapi/include/opencv2/gapi/gcompiled_async.hpp
modules/gapi/include/opencv2/gapi/gcomputation_async.hpp
modules/gapi/test/gapi_async_test.cpp

- added two template test cases (for calback and future usage model),  emphasising life time of output arguments compared to call to `async`  functions
```
```

Async API for GAPI : output arguments lifetime tests

---

cmake/OpenCVDetectCXXCompiler.cmake

It is perfectly possible to compile ARM binaries on Aarch64. Generalize
the code to no only swap X86 with X86_64, but also ARM and AARCH64.
Signed-off-by: Stefan Brüns <stefan.bruens@rwth-aachen.de>

Fix detection of 32bit ARM builds on Aarch64

---

modules/core/include/opencv2/core/matx.hpp

Due to the explicitly declared copy constructor Vec<T, n>::Vec(Vec <T,n>&)
GCC 9 warns if there is no assignment operator, as having one typically
requires the other (rule-of-three, constructor/desctructor/assginment).
As the values are just a plain array the default assignment operator does
the right thing. Tell the compiler explicitly to default it.
resolves #14933

Explicitly default operator= for Vec<T, n>

---

modules/imgproc/src/filter.dispatch.cpp
modules/imgproc/src/filterengine.hpp
modules/imgproc/src/templmatch.cpp

The first commit cleans up the crossCorr call from dftFilter2D.
The second commit does the actual removal.

Crosscorr cleanup

---

modules/calib3d/src/stereobm.cpp
modules/calib3d/src/stereosgbm.cpp
modules/core/include/opencv2/core/hal/intrin.hpp
modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_avx512.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/features2d/src/fast.cpp
modules/imgproc/src/canny.cpp
modules/imgproc/src/contours.cpp
modules/imgproc/src/hough.cpp

Avoid using v_signmask universal intrinsic and mark it as deprecated
```
force_builders=Custom,Linux AVX2,ARMv7,ARMv8,Linux32,Win32
```

Avoid using v_signmask universal intrinsic and mark it as deprecated

---

samples/python/tutorial_code/ImgTrans/LaPlace/laplace_demo.py

According to this [stackoverflow question/answer](https://stackoverflow.com/questions/43903243/opencv-laplacian-different-results-in-python-and-c/56664626#56664626), we need to add the flag `ksize=` to get the same result between C++, Java and Python.
This will fix the snippet code associted with the following tutorial file:
`/opencv/doc/tutorials/imgproc/imgtrans/laplace_operator/laplace_operator.markdown`

Fix Python code to get the same result between the Cpp, Java and Python.

---

modules/calib3d/src/ptsetreg.cpp

does not resolve any issue - just cleans up the code
getSubset function code contains a lot of nonsense like:
iters < maxAttempt in inner loop
if( i == modelPoints && !cb ... in inner loop
and needs some cleanup :)

Parmen ransac point set registrator get subset disaster cleanup

---

modules/gapi/src/compiler/passes/meta.cpp

const lvalue reference to object since in the given expression a new object is returned from a function. 
Original code is a valid behavior since this is the case for extended lifetime of the temporary object  (const lvalue reference of the same type is bound to that temporary).
Anyway, the code is doubtful and requires the developer to check for the return type and provide some rationale to ensure the code is correct. Taking this into account, it's easier to replace reference with an object.
---
References: [Temporary Object Lifetime](https://en.cppreference.com/w/cpp/language/lifetime) - look at the exceptions from the rules

G-API: Use object instead of reference in extended lifetime case

---

modules/imgproc/src/connectedcomponents.cpp
modules/imgproc/test/test_connectedcomponents.cpp

resolves #14955
Increase the size of chunksSizeAndLabelsSize to make sure further access is not out of bounds.
Add an assert to check that the new size is correct and a test that used to make the assert fail.

Fix connected components ParallelGrana buffer overflow

---

modules/features2d/src/blobdetector.cpp

resolves #12244
This PR addresses a small bug in the implementation of insertion sort inside the blob detector, as found in issue #12244.
Here is a dumbed down version of the bug and its solution that you can run on e.g. [cpp.sh](cpp.sh) (using doubles instead of circles but the idea is the same). The fix is simple really, the implementation of insertion sort is comparing the wrong variable in the while loop.
```
#include <string>
#include <vector>
#include <algorithm>
std::vector<double> broken_insert_sort(std::vector<double> centers, double new_num) {
centers.push_back(new_num);
size_t k = centers.size() - 1;
while( k > 0 && centers[k] < centers[k-1]) // Wrong comparison here
{
centers[k] = centers[k-1];
k--;
}
centers[k] = new_num;
return centers;
} …
```

Fix blob detector insertion sort (issue #12244)

---

modules/dnn/test/test_caffe_importer.cpp
modules/ts/src/ts.cpp

Flag is enabled on CI
relates #14847

ts: runtime check for misused 'optional' test data files

---

modules/videoio/src/cap_gstreamer.cpp

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_opt-avx2_noICV-skl-lin64-clang/builds/264)
```
```

videoio: eliminate build warnings (clang)

---

modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java
modules/java/generator/android/java/org/opencv/android/CameraBridgeViewBase.java

from CameraBridgeViewBase (common base with JavaCameraView)
Both interfaces (JavaCameraView/JavaCamera2View) using the same method and the same approach.
If user want to tune calculation then it should override "View" class and override this method (`calculateCameraFrameSize()`)
resolves #14915

android: JavaCamera2View use calculateCameraFrameSize() method

---

modules/imgcodecs/src/loadsave.cpp

OpenCV upstream stuff may reinterpret vector as column.
Fixes Python `imdecode()` interface.
resolves #14978

imgcodecs: force reshaping of imdecode() input into a single row

---

modules/videoio/src/cap_v4l.cpp

This PR adds support for 10-bit grey format for the V4L2 interface.
This is useful for some MIPI cameras that only support that pixel format.
The conversion is implemented in a similar way as the 16b grey conversion - so the output image is using just 8b and everything is divided by 4.0 to drop the two least significant bits.

V4L2: Add V4L2_PIX_FMT_Y10 (10 bit grey) support

---

modules/stitching/src/seam_finders.cpp

resolves #14646
- corrects the error message in the SeamFinder::createDefault()

Fix error message on invalid seam finder parameter #14646

---

modules/core/include/opencv2/core/cvdef.h

Checking CV_CXX11 is not enough for MSVC <=1800 as the compiler is not fully c++11 compliant. This will fix compilation error using VS13, where `noexcept` is not supported.
After change:  
if CV_CXX11 is defined and the compiler is NOT MSVC1800 and below, `CV_NOEXCEPT` is defined as `noexcept`, else `no-op`

Support compiliation for <=VS13

---

modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp
modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/src/backends/fluid/gfluidbackend.hpp
modules/gapi/test/gapi_fluid_parallel_rois_test.cpp
modules/gapi/test/gapi_fluid_test_kernels.cpp

- serial loop other user specified ROIs(Tiles)
```
```

G-API: Fluid Internal Parallelism

---

modules/gapi/include/opencv2/gapi/own/exports.hpp

fixes G-API symbol export specifier in case of G-API standalone mode
Originally, if someone decides to use G-API standalone and link G-API static library to a user's dynamic one: the symbols from our static lib are exported and placed into the symbol table of the user's dynamic library.
```
```

G-API: fix export specifier in standalone build

---

modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp
modules/gapi/test/cpu/gapi_core_tests_fluid.cpp
modules/gapi/test/gpu/gapi_core_tests_gpu.cpp

adds tests for output allocation for all backends

G-API: Add output allocation tests for backends

---

modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/src/backends/fluid/gfluidbackend.hpp

avoid generation of copy ctors with unique_ptr members
resolves #15065
```
force_builders=ARMv7,Custom Win
```

gapi: fix build with unique_ptr

---

modules/core/test/test_io.cpp

port into master #15050
relates #14977 
Part of tests are disabled due missing base64 encoders (+json base64 decoder).
<cut/>
```
```

core(persistence): base64 tests

---

modules/calib3d/include/opencv2/calib3d.hpp

This pull request fixes a small formatting issue in the doxygen for cv::findChessboardCornersSB().

calib3d: fix format in findChessboardCornersSB doxygen

---

modules/cudalegacy/src/calib3d.cpp

fix #15079
* use SOLVE_EPNP for the initial guess
```
```

cudalegacy: fix test failure of SolvePnPRansac

---

modules/js/src/embindgen.py
modules/js/test/test_features2d.js

resolves https://github.com/opencv/opencv/issues/13641
This is mostly a workaround for the issue.
```
buildworker:Docs=linux-1
```

Fix drawKeypoints and drawMatches for JS
