modules/objdetect/src/qrcode.cpp
fix kmeans clusterization and improvement of quality
Along with this algorithm there are related data in opencv_extra:
PR link: [https://github.com/opencv/opencv_extra/pull/490](https://github.com/opencv/opencv_extra/pull/490)
=> Objdetect: update detect QRCode algorithm

3rdparty/ittnotify/src/ittnotify/ittnotify_config.h, 3rdparty/openexr/CMakeLists.txt, 3rdparty/protobuf/CMakeLists.txt, apps/createsamples/utility.cpp, modules/calib3d/src/calibration.cpp, modules/calib3d/test/test_cameracalibration_badarg.cpp, modules/core/src/array.cpp, modules/imgproc/src/contours.cpp, modules/imgproc/src/drawing.cpp, modules/imgproc/src/floodfill.cpp, modules/imgproc/test/test_moments.cpp, modules/objdetect/src/haar.cpp
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1692
```
```
=> build: eliminate GCC8 warnings

modules/core/include/opencv2/core/cvdef.h, modules/core/include/opencv2/core/types.hpp
resolves #11999
resolves #11979
=> build: fix build error on Visual Studio 2013 and earlier

modules/core/include/opencv2/core/base.hpp
More assertions will be added to reduce number of unsertain issues.
```
```
=> Enable debug assertions for static analysis builds

modules/core/test/test_rand.cpp
=> core(test): remove verbose messages

modules/core/include/opencv2/core/base.hpp
#12006 backported to 3.4 branch
=> Enable debug assertions for static analysis builds (port to 3.4)

modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp
Several virtual functions have been updated.
```
```
=> dnn, IE backend: updated to match new interface

samples/cpp/detect_mser.cpp
Hi! Found a small issue in detect_mser.cpp example, with 2 arrays missing one element (see 
#01ad0f0). I did also do some formatting and safety improvements.
=> Mser sample improvments

modules/core/include/opencv2/core/types.hpp, modules/core/include/opencv2/core/types_c.h, modules/core/src/array.cpp, modules/core/src/persistence_types.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/imgproc/src/filter.cpp, modules/imgproc/src/undistort.cpp, modules/videoio/src/cap_mjpeg_encoder.cpp
* check for TermCriteria
* SparseMat dimension limit was wrong in some cases
* uninitialized fields in DNN layer
* unchecked value in MJPEG writer
```
```
=> Fixed several issues found by static analysis tools

modules/dnn/CMakeLists.txt, modules/dnn/src/op_inf_engine.cpp, modules/dnn/test/test_ie_models.cpp, modules/ts/include/opencv2/ts.hpp, modules/ts/src/ts.cpp
Test Intel's OpenVINO models using OpenCV interface.
```
```
=> Tests Intel's OpenVINO models

modules/objdetect/test/test_qrcode.cpp
improve error checks
resolves #12045
=> objdetect(qr): update test code

apps/createsamples/utility.cpp, modules/calib3d/src/circlesgrid.cpp, modules/calib3d/src/dls.cpp, modules/calib3d/test/test_chesscorners.cpp, modules/core/src/persistence_json.cpp, modules/core/test/test_mat.cpp, modules/core/test/test_rand.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/src/layers/recurrent_layers.cpp, modules/features2d/src/brisk.cpp, modules/features2d/src/kaze/KAZEFeatures.cpp, modules/imgcodecs/src/exif.cpp, modules/imgcodecs/src/grfmt_bmp.cpp, modules/imgcodecs/src/grfmt_pam.cpp, modules/imgcodecs/src/grfmt_tiff.cpp, modules/imgproc/src/contours.cpp, modules/imgproc/src/drawing.cpp, modules/imgproc/src/filter.avx2.cpp, modules/imgproc/src/floodfill.cpp, modules/imgproc/src/histogram.cpp, modules/imgproc/src/hough.cpp, modules/imgproc/src/min_enclosing_triangle.cpp, modules/ml/src/ann_mlp.cpp, modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/src/container_avi.cpp
* variables assigned but not used (useless assignment)
* division by 0
**Note:** regenerated test data for KAZE in opencv/opencv_extra#494
```
```
=> More issues found by static analysis

modules/dnn/test/test_halide_layers.cpp
but execute tested functions in Layer_Test_Halide/Convolution.Accuracy
```
```
=> dnn(test): skip checks only for unstable tests

modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp
* Several new pure methods have been added to the base class
=> Fixed build with the latest IE version

modules/imgproc/include/opencv2/imgproc.hpp
=> fix a typo.

modules/core/include/opencv2/core/hal/intrin.hpp, modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/test/test_intrin.avx2.cpp, modules/core/test/test_intrin.cpp, modules/core/test/test_intrin.simd.hpp, modules/core/test/test_intrin_utils.hpp
Expand hal_intrin tests to support SIMD256
````
pw_compilers=gcc-4.9, gcc-5, gcc-6
````
=> core:test Expand hal_intrin tests to support SIMD256

modules/core/src/arithm.cpp, modules/core/src/copy.cpp, modules/core/src/mean.cpp, modules/core/src/rand.cpp, modules/core/test/test_arithm.cpp, modules/core/test/test_concatenation.cpp, modules/core/test/test_rand.cpp
Some checks has been transformed to assertions and will throw an exception when empty inputs are passed to a function.
=> Added strict checks for empty inputs to some core functions

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/perf/perf_warp.cpp, modules/imgproc/src/imgwarp.cpp
drop compatibility workaround via runtime parameter
=> imgproc(getPerspectiveTransform): add solveMethod parameter

apps/interactive-calibration/rotationConverters.cpp, cmake/FindCUDA.cmake, cmake/OpenCVPCHSupport.cmake, cmake/templates/OpenCVConfig.cmake.in, doc/js_tutorials/js_imgproc/js_grabcut/js_grabcut.markdown, doc/js_tutorials/js_setup/js_usage/js_usage.markdown, doc/py_tutorials/py_imgproc/py_grabcut/py_grabcut.markdown, doc/tutorials/calib3d/real_time_pose/real_time_pose.markdown, doc/tutorials/introduction/windows_install/windows_install.markdown, modules/calib3d/test/test_chesscorners.cpp, modules/calib3d/test/test_chesscorners_timing.cpp, modules/core/include/opencv2/core/types_c.h, modules/core/src/datastructs.cpp, modules/core/src/persistence_c.cpp, modules/cudafilters/src/cuda/median_filter.cu, modules/cudaimgproc/src/mssegmentation.cpp, modules/cudawarping/test/test_warp_affine.cpp, modules/cudawarping/test/test_warp_perspective.cpp, modules/cudev/test/test_warp.cu, modules/features2d/doc/read_file_nondiff32.pl, modules/features2d/doc/read_file_score32.pl, modules/ml/src/svm.cpp, modules/objdetect/src/hog.cpp, modules/ts/include/opencv2/ts/ts_gtest.h, samples/cpp/train_HOG.cpp, samples/cpp/tutorial_code/ml/introduction_to_pca/introduction_to_pca.cpp, samples/cpp/warpPerspective_demo.cpp, samples/dnn/custom_layers.hpp, samples/winrt/OcvImageProcessing/OcvImageProcessing/Common/StandardStyles.xaml
Found via `codespell -q 3 -I ../opencv-whitelist.txt --skip="./3rdparty"`
```
force_builder=Custom
```
=> Misc. typos

modules/core/src/merge.cpp
=> core(merge): fix SIMD loop head processing

modules/imgproc/include/opencv2/imgproc.hpp
resolves #12132
clarify input format for cornerSubPix in docs
=> imgproc: update cornerSubPix documentation

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/mvn_layer.cpp, modules/dnn/test/test_tf_importer.cpp
enables `Test_TensorFlow_layers.mvn_batch_norm` tests mentioned in https://github.com/opencv/opencv/issues/11866
```
```
=> MVN layer using Intel's Inference Engine backend

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp, samples/dnn/tf_text_graph_ssd.py
resolves #12114
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/501
This PR changes generation script adding new command line arguments. However we can easier extract them from a [config file](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync.config).
```
```
=> MobileNet-SSD v1 from TensorFlow with shared convolution weights

modules/objdetect/src/qrcode.cpp
1. Update binarization
In the test data there were changes: PR link: [https://github.com/opencv/opencv_extra/pull/504](https://github.com/opencv/opencv_extra/pull/504)
2. Corrected seg. faults to this new compute points after convex hull
3. Refactor code
=> Objdetect: QRCode detector: Update binarization

modules/core/src/merge.cpp, modules/core/src/split.cpp, modules/core/test/test_mat.cpp
Builds with failed tests:
- [Core_Merge.hang_12171](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/16867)
- [Core_Split.hang_12171](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/16871)
- [Core_Split.crash_12171](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/16872)
=> core(test): extra tests/fixes for merge/split

modules/photo/src/contrast_preserve.hpp
resolves #12165 
resolves #12167 
resolves #12170 
* Pass by value in Decolor::grad_system
* Pass by value in Decolor::weak_order
* Keep image aspect ratio in resize called in grad_system and weak_order
* Bug correction in loop inside Decolor::gradvector
=> - Decolor corrections

modules/imgproc/src/color_rgb.cpp
=> imgproc(cvtColor): temporary disable IPP for 8U GRAY2BGR mode

modules/gpu/include/opencv2/gpu/gpu.hpp, modules/gpu/perf/perf_video.cpp, modules/gpu/src/pyrlk.cpp, samples/gpu/CMakeLists.txt
=> (2.4) gpu(sparse_multi): fix definition without TBB

modules/imgproc/src/color.cpp, modules/imgproc/src/color.hpp
Do not try to process empty inputs.
resolves #12163
=> imgproc(cvtColor): slightly improve error messages

modules/core/include/opencv2/core/cvstd.inl.hpp, modules/dnn/include/opencv2/dnn/shape_utils.hpp
remove from DNN module headers
=> core: cv::Range() ostream write operator

modules/dnn/src/layers/reshape_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/12066
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/502
```
```
=> Enable reshape-as-shape layer from TensorFlow

samples/python/asift.py
a typo in the comment of the asift.py
related #12190
=> Fix a Typo in the comment of asift.py

modules/calib3d/include/opencv2/calib3d.hpp
=> doc: fix typo

modules/imgproc/src/intersection.cpp, modules/imgproc/test/test_intersection.cpp
resolves #12221
Precision of calculation for intersection of RotatedRect.
```
```
=> Increase precision for intersection calculation of RotatedRect

modules/photo/src/seamless_cloning.cpp, modules/photo/src/seamless_cloning.hpp, modules/photo/src/seamless_cloning_impl.cpp
resolves #12053
additionally trying to clean up the code
=> Update seamless cloning

modules/cudafeatures2d/include/opencv2/cudafeatures2d.hpp, modules/cudafeatures2d/src/fast.cpp, modules/cudafeatures2d/src/orb.cpp
=> Avoid multi-inheritance in the cuda::features2d classes

modules/imgproc/include/opencv2/imgproc.hpp
=> fix an error in the formula for cv::cornerSubPix

modules/cudaimgproc/include/opencv2/cudaimgproc.hpp, modules/cudaimgproc/src/mssegmentation.cpp
=> Fixes bug in `cuda::meanShiftSegmentation`

modules/core/include/opencv2/core/base.hpp, modules/core/include/opencv2/core/cvdef.h
=> build: fix build with defined CV_STATIC_ANALYSIS

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/prior_box_layer.cpp
with enabled Inference Engine
related #12219
```
```
=> dnn(build): fix CV_Assert() usage

modules/core/include/opencv2/core.hpp, modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/misc/java/test/ImgprocTest.java, samples/android/camera-calibration/src/org/opencv/samples/cameracalibration/CameraCalibrator.java, samples/android/camera-calibration/src/org/opencv/samples/cameracalibration/OnCameraFrameRender.java, samples/android/mobilenet-objdetect/src/org/opencv/samples/opencv_mobilenet/MainActivity.java, samples/java/tutorial_code/Histograms_Matching/back_projection/CalcBackProjectDemo1.java, samples/java/tutorial_code/ImgProc/Smoothing/Smoothing.java, samples/java/tutorial_code/ShapeDescriptors/find_contours/FindContoursDemo.java, samples/java/tutorial_code/TrackingMotion/corner_subpixels/CornerSubPixDemo.java, samples/java/tutorial_code/TrackingMotion/generic_corner_detector/CornerDetectorDemo.java, samples/java/tutorial_code/TrackingMotion/good_features_to_track/GoodFeaturesToTrackDemo.java, samples/java/tutorial_code/ml/introduction_to_pca/IntroductionToPCADemo.java, samples/java/tutorial_code/ml/introduction_to_svm/IntroductionToSVMDemo.java, samples/java/tutorial_code/ml/non_linear_svms/NonLinearSVMsDemo.java
=> Move enums

modules/viz/src/widget.cpp
=> viz: call "mapper->Update()" before and after SetInputData()

modules/dnn/src/layers/crop_and_resize_layer.cpp, modules/dnn/src/layers/detection_output_layer.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/test/test_tf_importer.cpp, samples/dnn/mask_rcnn.py, samples/dnn/tf_text_graph_common.py, samples/dnn/tf_text_graph_mask_rcnn.py, samples/dnn/tf_text_graph_ssd.py
resolves https://github.com/opencv/opencv/issues/11412
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/510
=> Support Mask-RCNN from TensorFlow

modules/imgproc/misc/java/gen_dict.json, modules/imgproc/misc/java/test/ImgprocTest.java, modules/photo/misc/java/test/PhotoTest.java, modules/video/misc/java/test/BackgroundSubtractorMOGTest.java
=> related moved enums

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/lrn_layer.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_ie_models.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
```
force_builders=Custom,ocllinux
#docker_image:Linux OpenCL=ubuntu-openvino:16.04
```
=> Enable more deep learning tests using Intel's Inference Engine backend

modules/ts/src/ts.cpp
=> ts: don't pass NULL for std::string() constructor

cmake/OpenCVDetectInferenceEngine.cmake, doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, platforms/android/build_sdk.py, platforms/android/service/engine/AndroidManifest.xml, platforms/android/service/engine/src/org/opencv/engine/OpenCVEngineService.java, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
<cut/>
<details>
[opencv_world343.dll (vc14)](https://www.virustotal.com/#/file/962f8355f9f76f7ab75a25b496da095a65222982b3c3dcee0132b079bb681dbd/detection)
[opencv_world343.dll (vc15)](https://www.virustotal.com/#/file/0abb50c9a205f9bf3bc91eb8e90706883320825c3cd412975a5941286466040e/detection)
[opencv_ffmpeg343_64.dll](https://www.virustotal.com/#/file/508afc300cf29defdd03428a9000276fee7a006fd378184bbcf952a69e916961/detection)
[opencv_ffmpeg343.dll](https://www.virustotal.com/#/file/c21b3563eeb499eac1eea02e7b21d7899f1a0084caa0b11309ea807f185f923b/detection)
</details>
=> OpenCV version++ (3.4.3)

modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_ie_models.cpp
=> Fix lifetime of networks which are loaded from Model Optimizer IRs

doc/tutorials/introduction/windows_install/windows_install.markdown
Fixes  #12252
Adds small documentation clarifying BUILD_opencv_world
=> Adds a small note describing BUILD_opencv_world

modules/dnn/misc/java/test/DnnListRegressionTest.java, modules/java/generator/src/cpp/opencv_java.hpp
resolves #12324
correct the LIST_GET macro in opencv_java.hpp and add a dnn java test
=> java: fix LIST_GET macro

modules/imgproc/src/distransform.cpp
=> Fix typo in distanceTransform

samples/dnn/object_detection.py
resolves #12349
I fixed sample/dnn/object_detection.py to work with Python3.
=> Fixed that object_detection.py does not work in python3.

modules/imgcodecs/src/loadsave.cpp
=> imgcodecs: add null pointer check

modules/imgproc/misc/java/test/Subdiv2DTest.java, modules/imgproc/src/subdivision2d.cpp, modules/imgproc/test/test_subdivision2d.cpp
=> Fix bug in Subdiv2D::getTriangleList

README.md
Saves a redirect from HTTP -> HTTPS each.
[ci skip]
```
```
=> Use secure URLs in README

modules/core/include/opencv2/core/mat.inl.hpp, modules/core/src/arithm.cpp, modules/core/src/convert.cpp, modules/core/src/convert_scale.cpp, modules/core/src/copy.cpp, modules/core/src/count_non_zero.cpp, modules/core/src/lut.cpp, modules/core/src/mathfuncs.cpp, modules/core/src/matmul.cpp, modules/core/src/mean.cpp, modules/core/src/minmax.cpp, modules/core/src/norm.cpp, modules/core/src/parallel_impl.cpp, modules/core/src/sum.cpp, modules/cudaimgproc/src/canny.cpp, modules/imgproc/src/accum.cpp
some static analyzer warings.
```
```
=> fix some static analyzer warnings

modules/dnn/src/layers/flatten_layer.cpp
Signed-off-by: Wu Zhiwen <zhiwen.wu@intel.com>
=> dnn: Remove a duplicated code snippet for flatten layer

modules/imgproc/src/segmentation.cpp
Avoid manual address arithmetic
resolves #12365
=> imgproc(segmentation): don't increase mask NULL pointer

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_graph_simplifier.hpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_common.hpp, modules/dnn/test/test_tf_importer.cpp, samples/dnn/object_detection.py, samples/dnn/tf_text_graph_common.py, samples/dnn/tf_text_graph_faster_rcnn.py, samples/dnn/tf_text_graph_mask_rcnn.py, samples/dnn/tf_text_graph_ssd.py
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/506
faster-rcnn (https://github.com/opencv/opencv/issues/11848, https://github.com/opencv/opencv/issues/12033).
```
```
=> Import SSDs from TensorFlow by training config

modules/imgproc/src/distransform.cpp, modules/imgproc/test/test_distancetransform.cpp
=> Fix bug in distanceTransform

modules/imgproc/src/contours.cpp
=> imgproc: small code refactoring (findContours -> l_cinfo)

modules/core/src/rand.cpp
=> Solves issue 12392

modules/ts/include/opencv2/ts/ts_gtest.h, modules/ts/src/ts_gtest.cpp
https://github.com/google/googletest/releases/tag/release-1.8.1
```
build_contrib:iOS=ON
```
=> ts: update Google Test 1.8.1

modules/core/src/matrix_wrap.cpp, modules/core/src/parallel_impl.cpp, modules/core/src/persistence_json.cpp, modules/cudaarithm/src/arithm.cpp, modules/imgcodecs/src/grfmt_jpeg2000.cpp, modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/src/grfmt_pxm.cpp, modules/imgcodecs/src/grfmt_sunras.cpp, modules/imgproc/src/linefit.cpp
```
force_builders=linux,windows,mac,docs
```
=> fix some errors found by static analyzer.

modules/imgproc/src/smooth.cpp
Do not block OpenCL / HAL / IPP calls.
=> imgproc(GaussianBlur): restore processing order

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/include/opencv2/dnn/dict.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/include/opencv2/dnn/dnn.inl.hpp, modules/dnn/include/opencv2/dnn/layer.details.hpp, modules/dnn/include/opencv2/dnn/layer.hpp, modules/dnn/include/opencv2/dnn/shape_utils.hpp, modules/dnn/include/opencv2/dnn/version.hpp, modules/dnn/src/caffe/caffe_importer.cpp, modules/dnn/src/caffe/caffe_shrinker.cpp, modules/dnn/src/darknet/darknet_importer.cpp, modules/dnn/src/dnn.cpp, modules/dnn/src/init.cpp, modules/dnn/src/nms.cpp, modules/dnn/src/precomp.hpp, modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_graph_simplifier.hpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/src/torch/torch_importer.cpp, modules/dnn/test/test_precomp.hpp
=> dnn: update "guard" inline namespace

modules/dnn/src/dnn.cpp
resolves https://github.com/opencv/opencv/issues/12407
=> Fix #12407

modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_precomp.hpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
Starts from OpenVINO R3 Myriad plugin can process batch size != 1.
```
force_builders=Custom,ocllinux
```
=> Enable Myriad tests with batch size > 1

modules/imgproc/src/subdivision2d.cpp
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1747
resolves https://github.com/opencv/opencv_contrib/issues/1746
related #12348
=> imgproc: fix Subdiv2D::getTriangleList()

modules/core/src/matrix_sparse.cpp
=> core: add validation for the potential null pointer

cmake/OpenCVCompilerOptions.cmake, modules/calib3d/perf/perf_pnp.cpp, modules/calib3d/test/test_affine3.cpp, modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/core/perf/opencl/perf_arithm.cpp, modules/core/perf/perf_split.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_torch_importer.cpp, modules/photo/test/test_hdr.cpp
merge together with https://github.com/opencv/opencv_contrib/pull/1751
```
```
=> trying to fix the custom AVX2 builder test failures (false alarms)

modules/imgproc/src/grabcut.cpp
```
CPU_BASELINE:Win32=AVX2
```
=> imgproc: grabcut numeric stability

modules/cudalegacy/src/fgd.cpp
[Failed build](http://pullrequest.opencv.org/buildbot/builders/3_4_cuda-lin64/builds/147).
related #11630
```
```
=> cuda: fix build (legacy C-API usage)

modules/video/perf/perf_optflowpyrlk.cpp
=> video(perf): drop unreliable sanity check

modules/core/include/opencv2/core/bindings_utils.hpp, modules/core/src/bindings_utils.cpp, modules/python/test/test_misc.py, modules/python/test/tests_common.py
=> bindings: add debug helpers for args conversions

modules/core/include/opencv2/core/cvdef.h, modules/core/include/opencv2/core/cvstd_wrapper.hpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp
Optional: opencv/opencv_contrib#1766
- Add CV_CONSTEXPR macro
- Utilize CV_NOEXCEPT and CV_CONSTEXPR
- Add Ptr<> operators for logical comparsion
=> Support MSVC 2013

modules/core/include/opencv2/core/cuda/detail/transform_detail.hpp, modules/cudev/include/opencv2/cudev/grid/detail/transform.hpp
=> fix uninitialized read errors reported by CUDA-INITCHECK

modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qrcode.cpp, samples/cpp/live_detect_qrcode.cpp
1. Optimization function - searchVerticalLines (new name searchHorizontalLines)
2. Added sample - live_detect_qrcode.cpp in sample/cpp
3. Сhanged the heuristics of fixing the points of labels
=> Objdetect: QRCode detector: Optimization search lines and added sample

modules/highgui/src/window.cpp
resolves #12492
related #11630
```
docker_image:Custom=qt:16.04
```
=> highgui: fix QT build

apps/traincascade/old_ml.hpp, apps/traincascade/old_ml_tree.cpp, modules/core/include/opencv2/core/core_c.h, modules/core/include/opencv2/core/cvstd_wrapper.hpp, modules/core/include/opencv2/core/persistence.hpp, modules/core/src/array.cpp, modules/core/test/test_ptr.cpp, modules/objdetect/include/opencv2/objdetect.hpp, modules/objdetect/src/cascadedetect.cpp, modules/photo/src/inpaint.cpp, modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap.cpp
resolves #12489 ([validated](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14-static/builds/10572))
resolves #12490 (validated, check "Custom" precommit build)
related #12467
```
```
=> core: change cv::Ptr DefaultDeleter

modules/core/src/sum.cpp
sum() implementation updated to use wide universal intrinsics
```
force_builders=Custom,linux,macosx,windows,docs,iOS,ARMv8
**WIP**
```
=> sum() implementation updated to use wide universal intrinsics

modules/dnn/test/test_common.hpp, modules/dnn/test/test_ie_models.cpp
```
force_builders=Custom,linux,Linux OpenCL,docs
```
=> dnn(test): run DL IE tests on Intel OpenCL devices only

modules/ts/misc/testlog_parser.py
testlog_parser updated to handle output of latest GTest as well
=> GTest result parser update

modules/dnn/src/torch/torch_importer.cpp
=> Replace CV_USRTYPE1 for int64 to CV_32SC2 in Torch importer

modules/python/test/test_dnn.py, modules/python/test/tests_common.py
* blobFromImage test
* OpenCV's face detection network with different backends
```
```
=> Add python tests for dnn module

modules/imgproc/include/opencv2/imgproc.hpp
related #11108 
```
**WIP**
```
=> Doc: Fix document about HoughLines

3rdparty/ffmpeg/ffmpeg.cmake, modules/ts/include/opencv2/ts/ts_ext.hpp, modules/videoio/test/test_ffmpeg.cpp
**Merge with**: https://github.com/opencv/opencv_3rdparty/pull/33
- ffmpeg 4.0.2
- openh264 1.8.0
```
buildworker:Win64=windows-1
buildworker:Win32=windows-1
```
=> ffmpeg: update 4.0 (master)

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/test/test_ie_models.cpp
```
force_builders=Custom,ocllinux
#doesn't work: build_parallel_tests=1
#test_modules=dnn
```
=> Enable Myriad device for OpenVINO models test

modules/ts/misc/run_android.py, modules/ts/misc/run_long.py, modules/ts/misc/run_suite.py
- DNN: avoid very large models
- build filter per module
- fixed longTestFilter
[Validation build](http://pullrequest.opencv.org/buildbot/builders/3_4_valgrind-lin64-debug/builds/24)
=> ts: update valrind test filter

modules/core/include/opencv2/core/version.hpp
=> release: OpenCV 4.0.0-alpha (version++)

modules/dnn/test/test_common.hpp
=> dnn(test): test at least CPU code path

modules/core/src/opengl.cpp
=> fix a bug in OpenGL

modules/js/src/core_bindings.cpp, modules/js/src/embindgen.py, modules/js/src/templates.py
=> JS: Support enum properties

modules/cudev/include/opencv2/cudev/util/saturate_cast.hpp
=> cudev: fix CvFp16Test failure

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/chessboard.cpp
findChessboardCornersSB: speed up using parallel_for and add support for flags
```
force_builders=linux,windows,macosx,docs
```
=> findChessboardCornersSB: speed improvements

apps/interactive-calibration/calibController.cpp, apps/interactive-calibration/frameProcessor.cpp, modules/core/include/opencv2/core/operations.hpp, modules/core/src/channels.cpp, modules/core/src/lda.cpp, modules/core/src/matrix_operations.cpp, modules/core/src/ocl.cpp, modules/core/test/test_io.cpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/permute_layer.cpp, modules/dnn/src/torch/THDiskFile.cpp, modules/imgproc/src/featureselect.cpp, modules/imgproc/src/histogram.cpp, modules/objdetect/src/hog.cpp, modules/photo/src/fast_nlmeans_denoising_opencl.hpp, modules/videoio/src/container_avi.cpp, samples/dnn/segmentation.cpp
Merge with opencv/opencv_contrib#1784
Ported #12150 by @paroj 
```
```
=> printf format warnings wnabled

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp, samples/dnn/object_detection.cpp, samples/dnn/object_detection.py
possibly related https://github.com/opencv/opencv/issues/12441
=> add Net::getUnconnectedOutLayersNames method

modules/calib3d/src/chessboard.cpp, modules/calib3d/src/chessboard.hpp, modules/calib3d/test/test_chesscorners.cpp
=> M_PI changed to CV_PI

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap.cpp, modules/videoio/src/cap_avfoundation.mm, modules/videoio/src/cap_avfoundation_mac.mm, modules/videoio/src/cap_dc1394.cpp, modules/videoio/src/cap_dc1394_v2.cpp, modules/videoio/src/cap_ffmpeg.cpp, modules/videoio/src/cap_gphoto2.cpp, modules/videoio/src/cap_gstreamer.cpp, modules/videoio/src/cap_images.cpp, modules/videoio/src/cap_libv4l.cpp, modules/videoio/src/cap_mfx_writer.hpp, modules/videoio/src/cap_mjpeg_decoder.cpp, modules/videoio/src/cap_mjpeg_encoder.cpp, modules/videoio/src/cap_msmf.cpp, modules/videoio/src/cap_qt.cpp, modules/videoio/src/cap_qtkit.mm, modules/videoio/src/cap_unicap.cpp, modules/videoio/src/cap_v4l.cpp, modules/videoio/src/cap_vfw.cpp, modules/videoio/src/cap_winrt_capture.hpp, modules/videoio/src/cap_ximea.cpp, modules/videoio/src/precomp.hpp, modules/videoio/test/test_camera.cpp
=> videoio: added '.getBackendName()' method

modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp, modules/dnn/test/test_halide_layers.cpp
=> dnn: ocl4dnn verification test

modules/flann/include/opencv2/flann/kmeans_index.h
- fix synchronization bug (perhaps related to #9179)
relates #3458
=> flann: drop useless mutex

modules/core/misc/python/pyopencv_core.hpp, modules/core/misc/python/pyopencv_umat.hpp, modules/features2d/misc/python/pyopencv_features2d.hpp, modules/objdetect/misc/python/pyopencv_objdetect.hpp, modules/python/src2/cv2.cpp, modules/python/src2/gen2.py, modules/stitching/misc/python/pyopencv_stitching.hpp, modules/videoio/misc/python/pyopencv_videoio.hpp
Merge with opencv/opencv_contrib#1796
Improve the bindings automation
- Automatically generate the enum bindings
=> Generate enum bindings automatically

doc/CMakeLists.txt
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1792
=> docs: DOXYGEN_BLACKLIST CMake variable for modules exclusion

modules/features2d/CMakeLists.txt, modules/features2d/include/opencv2/features2d.hpp, modules/js/src/embindgen.py, platforms/js/build_js.py
resolves https://github.com/opencv/opencv/issues/11300
```
```
=> JavaScript bindings for features2d module

modules/java/generator/android/java/org/opencv/android/FpsMeter.java
fixed typo in FpsMeter.java
'mFramesCouner' -> 'mFramesCounter'
=> fix typo in FpsMeter.java

modules/ts/misc/report.py, modules/ts/misc/summary.py, modules/ts/misc/table_formatter.py, modules/ts/misc/testlog_parser.py
Fix for the test suite reporting tools to work with Python 2.7
=> TS: fix Python v2/v3 compatibility

modules/core/src/lapack.cpp
SSE2 code in invert() replaced with universal intrinsics
=> SSE2 code in invert() replaced with universal intrinsics

modules/imgproc/src/sumpixels.cpp
integral() implementation updated to utilize wide universal intrinsics
```
force_builders=Linux AVX2,Linux32
```
=> integral() implementation updated to utilize wide universal intrinsics

modules/cudafilters/src/cuda/median_filter.cu
* avoid race condition
* resolves #12721 
resolves #12505
resolves #11622
```
```
=> cudafilters: fix test failure of cudafilters Median_Accuracy

samples/gpu/video_reader.cpp
Change iteration to iterate separately when the video is decode on a GPU to account for different number of frames
resolves #12692 
```
force_builders=linux,docs,Custom
```
=> Fixes #12692: Update samples/gpu/videoreader.cpp

3rdparty/ffmpeg/ffmpeg-download.ps1.in, 3rdparty/ffmpeg/ffmpeg.cmake
=> Correct licenses install location for ffmpeg-download script

modules/js/src/core_bindings.cpp
resolves https://github.com/opencv/opencv/issues/12706
```
```
=> Fix JavaScript bindings for features2d module

modules/dnn/src/layers/permute_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/523
```
```
=> Add Shufflenet support in ONNX

modules/imgproc/include/opencv2/imgproc.hpp
Resolves #11492.
Added documentation for function `cvtColorTwoPlane`. 
Request for review.
=> Added documentation for cvtColorTwoPlane

modules/cudabgsegm/test/test_bgsegm.cpp
=> CUDA/BgSegm: fix the threshold of MOG2.Update test

samples/CMakeLists.example.in, samples/_winpack_build_sample.cmd
=> samples: add winpack "drap & drop" build script

modules/videoio/src/cap_dc1394_v2.cpp
=> videoio: drop rectification code for VIDERE cameras

cmake/OpenCVModule.cmake, cmake/templates/dllmain.cpp.in, modules/core/src/ocl.cpp, modules/core/src/precomp.hpp
to detect process termination after ExitProcess() call
resolves #12750
relates #1972 #1490
```
```
=> cmake: add DllMain() into each OpenCV DLL

modules/imgproc/src/pyramids.cpp
````
pw_compilers=gcc-4.9, gcc-5, gcc-6, clang-4, clang-5, clang-6
```
=> imgproc: Enable VSX on pyrDown & pyrUp

modules/imgproc/src/resize.cpp
=> resolves #11283

modules/highgui/src/window_cocoa.mm
This PR should speed up window drawing on retina Macs.  On my computer, displaying 1000 1080p images went from taking 130 seconds to 40, which still isn't great but is a lot better than before.
It also changes the default size of windows (and size of autosize windows) to the size of the image in pixels (instead of points), meaning that windows will default to 1/2 the size that they previously did on retina macs.
=> Faster Cocoa Window Drawing

modules/core/src/copy.cpp, modules/core/src/lapack.cpp, modules/core/src/mathfuncs.cpp, modules/core/src/matmul.cpp
Replaced core module calls to universal intrinsics to wide version
=> Replaced core module calls to universal intrinsics to wide version

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp
=> Fix Pooling and Convolution layers from Intel's Inference Engine

modules/video/src/lkpyramid.cpp, modules/video/src/opencl/pyrlk.cl
* remove race condition
* upload _prevPts to OpenCL device explicitly before calling "sparse"
resolves #12828
=> video: fix test failure of PyrLKOpticalFlow.Mat

modules/core/include/opencv2/core/opencl/ocl_defs.hpp, modules/core/src/ocl.cpp
=> OCL: bailout from unsupported types

modules/core/include/opencv2/core/optim.hpp, modules/core/src/lpsolver.cpp, modules/core/test/test_lpsolver.cpp
=> core: update solveLP() interface

modules/core/include/opencv2/core/version.hpp
<cut/>
<details>
[opencv_world400.dll (vc14)](https://www.virustotal.com/#/file/3e0f512f552c7da8c09c34eac48742fe41a410b6957dc50d22a81374d7cc6c82/detection)
[opencv_world400d.dll (vc14)](https://www.virustotal.com/#/file/a78357285461698f06bc87168f44cdd31a764bf49b6472ea2c67613ef285e708/detection)
[opencv_world400.dll (vc15)](https://www.virustotal.com/#/file/86305c8e617c1f0668fade32190d541c692212a832b04f4048973f292ba5ede8/detection)
[opencv_world400d.dll (vc15)](https://www.virustotal.com/#/file/35a6cf9f81ee549fcdbd88595cdbcff4776bd82767a2f56658b8c3e6898e7283/detection)
</details>
=> release: OpenCV 4.0.0-beta (version++)

modules/videoio/src/cap_ffmpeg_impl.hpp
This pullrequest changes code so that unused empty block is removed
=> Remove unused empty block

modules/dnn/src/op_inf_engine.cpp
=> Implement getBatchSize for Intel's Inference Engine networks

modules/flann/include/opencv2/flann.hpp
Added documentation for the flann::GenericIndex::radiusSearch function with vector signature.
=> Add documentation for radiusSearch

modules/dnn/test/test_torch_importer.cpp
resolves https://github.com/opencv/opencv/issues/12691
=> Fix ENet test

modules/imgproc/src/geometry.cpp
=> rewrote the line segment intersection function to make the static analyzer happy

modules/core/include/opencv2/core/hal/intrin_vsx.hpp
should resolves #12830 after merge it with master
````
pw_compilers=gcc-4.9, gcc-5, gcc-6, clang-4, clang-5, clang-6
````
=> core:vsx change behavior of v_round to rounding to nearest even

modules/features2d/src/orb.cpp
=> ORB: compute default norm by wta_k

modules/objdetect/CMakeLists.txt
=> cmake: fix objdetect QR decoder link_libraries

modules/objdetect/perf/perf_qrcode_pipeline.cpp, modules/objdetect/test/test_qrcode.cpp
With opencv_extra PR [https://github.com/opencv/opencv_extra/pull/533](https://github.com/opencv/opencv_extra/pull/533)
=> Objdetect: QRCode pipeline: Added perf tests

modules/calib3d/src/calibration.cpp, modules/calib3d/src/chessboard.cpp, modules/core/include/opencv2/core/base.hpp, modules/core/include/opencv2/core/cvdef.h, modules/dnn/src/layers/pooling_layer.cpp, modules/imgcodecs/src/grfmt_pfm.cpp, modules/imgproc/src/contours.cpp, modules/objdetect/src/hog.cpp
Minor issues with uninitialized class members and possible division by zero.
```
```
=> Fixed several issues found by static analysis

CMakeLists.txt, modules/highgui/src/window.cpp
=> Fixed a few comments related to macOS support

modules/objdetect/src/qrcode.cpp
PR to test qrcode algorithms on the new test data.
With opencv_expra PR: [https://github.com/opencv/opencv_extra/pull/537](https://github.com/opencv/opencv_extra/pull/537)
=> Fix dataset: russian.jpg

modules/core/misc/java/src/java/core+Mat.java, modules/core/misc/java/test/MatTest.java, modules/java/generator/src/cpp/Mat.cpp
resolves https://github.com/opencv/opencv/issues/12821
=> Multidimensional Mat reshape in Java

modules/viz/include/opencv2/viz/viz3d.hpp, modules/viz/include/opencv2/viz/widgets.hpp, modules/viz/src/clouds.cpp, modules/viz/src/shapes.cpp, modules/viz/src/viz3d.cpp, modules/viz/src/vizimpl.cpp, modules/viz/src/vizimpl.hpp, modules/viz/src/widget.cpp
resolves #11675
resolves #10831
I don't use viz so I don't know if these changes are ok or not.
=> Make some methods in viz const

modules/python/test/test_copytomask.py
=> Add python test for copyto with mask

modules/imgcodecs/src/grfmt_webp.cpp, modules/imgcodecs/test/test_png.cpp, modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/demosaicing.cpp, modules/imgproc/test/test_color.cpp, modules/imgproc/test/test_cvtyuv.cpp, modules/imgproc/test/test_goodfeaturetotrack.cpp
https://github.com/opencv/opencv/pull/12884
preview : http://pullrequest.opencv.org/buildbot/export/pr/12971/docs/d7/dbd/group__imgproc.html
=> Upd imgproc hpp

modules/calib3d/test/test_cameracalibration.cpp
resolves https://github.com/opencv/opencv/issues/12970
=> Fix #12970

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Padding layer support from ONNX
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/539
=> Add ONNX's padding import

doc/Doxyfile.in, modules/core/doc/intro.markdown, modules/core/include/opencv2/core/base.hpp, modules/core/include/opencv2/core/utility.hpp
=> docs: intro formatting update, minor cleanup

modules/core/include/opencv2/core.hpp
solves #13035 
```
**WIP**
```
=> typo in kmeans doc

modules/core/src/ocl.cpp
resolves https://github.com/opencv/opencv/issues/12824 for GPUs with `cl_khr_fp16` features.
=> Fix #12824

modules/java/generator/src/java/org/opencv/utils/Converters.java, modules/java/test/android_test/src/org/opencv/test/OpenCVTestCase.java, modules/java/test/common_test/src/org/opencv/test/utils/ConvertersTest.java, modules/java/test/pure_test/src/org/opencv/test/OpenCVTestCase.java
=> java: add converters, tests for MatOfRotatedRect

3rdparty/ffmpeg/ffmpeg.cmake, modules/videoio/src/cap_ffmpeg_impl.hpp
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/35
~Merge after #13033~
ffmpeg 3.4.2 -> 3.4.5
```
```
=> (3.4) ffmpeg: update wrapper

modules/dnn/src/dnn.cpp
=> Fix integer overflow when accumulating timing values

3rdparty/ffmpeg/ffmpeg.cmake
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/36
ffmpeg 4.0.2 -> 4.1
=> ffmpeg: update wrapper (4.1 - master)

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap.cpp
=> videoio: backport "VideoCapture(int index, int apiPreference)" interface

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/drawing.cpp
=> update drawing functions

modules/objdetect/include/opencv2/objdetect.hpp, modules/objdetect/perf/perf_qrcode_pipeline.cpp, modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qrcode.cpp, samples/cpp/live_detect_qrcode.cpp
=> refined QRCodeDetector API for OpenCV 4.0

modules/core/src/arithm.cpp, modules/core/src/convert.cpp, modules/core/src/convert_scale.cpp, modules/core/src/copy.cpp, modules/core/src/precomp.hpp, modules/core/test/test_mat.cpp
=> core: fix processing of vector-rows

modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp, modules/gapi/test/common/gapi_core_tests_inl.hpp, modules/gapi/test/common/gapi_tests_common.hpp, modules/gapi/test/gapi_scalar_tests.cpp, modules/gapi/test/internal/gapi_int_recompilation_test.cpp
Fix for https://github.com/opencv/opencv/issues/12911
=> G-API: Fixed unitialized mat in LUT test

modules/objdetect/include/opencv2/objdetect.hpp, modules/objdetect/perf/perf_qrcode_pipeline.cpp, modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qrcode.cpp, samples/cpp/live_detect_qrcode.cpp
=> (3.4) refined QRCodeDetector API for OpenCV 4.0

modules/core/src/arithm.cpp, modules/core/src/convert.cpp, modules/core/src/convert_scale.cpp, modules/core/src/copy.cpp, modules/core/src/mathfuncs.cpp, modules/core/src/matrix.cpp, modules/core/src/precomp.hpp
resolves #13101
relates #13080
```
```
=> core: rework getContinuousSize() for vector-col/row support

modules/core/test/test_arithm.cpp
to verify SIMD code path
resolves #12826
=> core(test): extend divideByZero test

CMakeLists.txt
Disable pkg-config file generation by default.
=> cmake: OPENCV_GENERATE_PKGCONFIG

modules/core/include/opencv2/core/persistence.hpp, modules/core/src/persistence.cpp, modules/core/test/test_io.cpp
From https://github.com/opencv/opencv/pull/12641 considering https://github.com/opencv/opencv/pull/12641/files#r221050674
=> Add FileNode::keys() missed during refactoring

modules/stitching/test/test_matchers.cpp
relates #13121
```
#build_contrib=OFF
#tests_filter=ParallelFeaturesFinder.IsSameWithSerial
```
=> stitching(test): workaround ParallelFeaturesFinder.IsSameWithSerial

modules/gapi/cmake/DownloadADE.cmake
Should help with #12831 
resolves #12831
=> Update ADE to version 0.1.1d

modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp, modules/gapi/perf/cpu/gapi_imgproc_perf_tests_fluid.cpp, modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp, modules/gapi/perf/gpu/gapi_imgproc_perf_tests_gpu.cpp, modules/gapi/test/common/gapi_core_tests_inl.hpp, modules/gapi/test/common/gapi_tests_common.hpp, modules/gapi/test/cpu/gapi_core_tests_cpu.cpp, modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp, modules/gapi/test/cpu/gapi_imgproc_tests_fluid.cpp, modules/gapi/test/cpu/gapi_operators_tests_cpu.cpp, modules/gapi/test/cpu/gapi_operators_tests_fluid.cpp, modules/gapi/test/gpu/gapi_core_tests_gpu.cpp, modules/gapi/test/gpu/gapi_imgproc_tests_gpu.cpp, modules/gapi/test/gpu/gapi_operators_tests_gpu.cpp
=> G-API: update tests checks

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/include/opencv2/videoio/videoio_c.h, modules/videoio/src/cap_avfoundation_mac.mm, modules/videoio/src/cap_msmf.cpp
=> videoio: drop VideoCaptureModes enum in favour of fourcc

cmake/OpenCVDetectInferenceEngine.cmake, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/blank_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/crop_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_ie_models.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
=> Extra hyperparameters for Intel's Inference Engine layers

3rdparty/carotene/src/colorconvert.cpp
- update parameter in carotene
- resolves #13182
=> carotene: fix test failure of ColorCvtRGB2Gray

modules/gapi/include/opencv2/gapi.hpp, modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp, modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp, modules/gapi/include/opencv2/gapi/garray.hpp, modules/gapi/include/opencv2/gapi/gcommon.hpp, modules/gapi/include/opencv2/gapi/gcompiled.hpp, modules/gapi/include/opencv2/gapi/gcomputation.hpp, modules/gapi/include/opencv2/gapi/gkernel.hpp, modules/gapi/include/opencv2/gapi/gmat.hpp, modules/gapi/include/opencv2/gapi/gpu/ggpukernel.hpp, modules/gapi/include/opencv2/gapi/gscalar.hpp, modules/gapi/samples/api_ref_snippets.cpp
This PR brings some documentation to public G-API headers, in particular:
* GComputation
* GCompiled
* GKernelPackage
* GCompileArgs
Also, a number of new documentation sections added to the main reference to organize G-API docs better.
=> G-API: Doxygen class reference

modules/core/src/utils/filesystem.cpp, platforms/scripts/valgrind.supp
Valgrind [build](http://pullrequest.opencv.org/buildbot/builders/3_4_valgrind-lin64-debug/builds/36).
Validation [build](http://pullrequest.opencv.org/buildbot/builders/3_4_valgrind-lin64-debug/builds/37).
=> core: fix issues from valgrind builder

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, platforms/android/build_sdk.py, platforms/android/service/engine/AndroidManifest.xml, platforms/android/service/engine/src/org/opencv/engine/OpenCVEngineService.java, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
<cut/>
<details>
[opencv_world344.dll (vc14)](https://www.virustotal.com/#/file/aaec07565cee9ec0de19b806fbef97d605e8d43b1d80b26d6196c4fb780e5545/detection)
[opencv_world344d.dll (vc14)](https://www.virustotal.com/#/file/547eeb3b0b65e6ceafeafe8c4dbcbabb306719aa3866255c59efded5f9454166/detection)
[opencv_world344.dll (vc15)](https://www.virustotal.com/#/file/72e89f21e5279bc930c6fea9269e6e4645b6841cffbea31262389efa68625f83/detection)
[opencv_world344d.dll (vc15)](https://www.virustotal.com/#/file/8e32dc45cf172d04d2a5030ebe9ed5f3608d09f61bfb97a5b3138a13febcc7fb/detection)
[opencv_ffmpeg344_64.dll](https://www.virustotal.com/#/file/e6acb89dfe6f3af13afaa3ff46ca4e3e1846d868d398e0fd662da2affd515d61/detection) …
=> OpenCV version++ (3.4.4)

modules/core/include/opencv2/core/version.hpp
=> release: OpenCV 4.0.0 (version++)

samples/dnn/tf_text_graph_mask_rcnn.py
related https://github.com/opencv/opencv/issues/13050
Changes similar to ones from https://github.com/opencv/opencv/pull/13065 (Faster-RCNN networks generator).
=> Update Mask-RCNN networks generator

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/perf/perf_net.cpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/test/test_common.hpp, modules/dnn/test/test_ie_models.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_misc.cpp
merge after https://github.com/opencv/opencv/pull/12913
```
```
=> Initial support of FPGA target from Intel's OpenVINO toolkit

modules/dnn/src/layers/blank_layer.cpp
=> dnn: fix format

modules/core/include/opencv2/core/types.hpp, modules/core/test/test_operations.cpp
resolves #12108
fixed operator- and operator -= for Rect
=> core: fixed operator- for Rect

cmake/OpenCVModule.cmake
=> cmake: don't generate dllmain for cudev module

modules/highgui/src/precomp.hpp, modules/highgui/src/window.cpp, modules/highgui/src/window_w32.cpp
=> highgui: add missing API cvGetPropVisible_W32

cmake/OpenCVModule.cmake, modules/imgcodecs/CMakeLists.txt, modules/videoio/CMakeLists.txt, samples/cpp/tutorial_code/compatibility/compatibility_test.cpp
=>  cmake: install "legacy/constants_c.h" compatibility headers

3rdparty/carotene/hal/CMakeLists.txt
Ported #13278 from _master_ (although the original issue is not reproduced on this branch)
=> Fixed NEON detection in Carotene build (port from master)

modules/imgproc/perf/perf_contours.cpp, modules/imgproc/src/contours.cpp
Updated findContours to use wide universal intrinsics
```
```
=> Updated findContours to use wide universal intrinsics

modules/imgproc/src/median_blur.cpp
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL_noICV_noSSE-win64-vc14-debug/builds/218)
=> build: eliminate warnings

modules/imgproc/perf/perf_contours.cpp
Added anonymous namespace to perf_contours
Related to #13242
=> Added anonymous namespace to perf_contours

modules/gapi/src/backends/fluid/gfluidimgproc.cpp, modules/gapi/src/backends/fluid/gfluidimgproc_func.dispatch.cpp, modules/gapi/src/backends/fluid/gfluidimgproc_func.hpp, modules/gapi/src/backends/fluid/gfluidimgproc_func.simd.hpp
Additional 20-30% speed-up on top of my previous PR #13315
=> GAPI (fluid): Erode/Dilate optimization, part 2

modules/objdetect/src/qrcode.cpp
=> QRcode seg. faults

modules/imgproc/src/grabcut.cpp
resolves #13297
relates #11984
=> imgproc: local "CV_Assert(totalSampleCount > 0)" check

modules/gapi/include/opencv2/gapi/gpu/ggpukernel.hpp, modules/gapi/include/opencv2/gapi/ocl/core.hpp, modules/gapi/include/opencv2/gapi/ocl/imgproc.hpp
removes gpu mention from ocl backend
=> G-API gpu backend renaming patch 

modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/include/opencv2/core/hal/intrin_vsx.hpp, modules/core/perf/perf_norm.cpp, modules/core/src/norm.cpp, modules/ts/include/opencv2/ts.hpp
norm implementation updated to use wide universal intrinsics
```
```
=> hal::norm update

modules/imgproc/test/test_resize_bitexact.cpp
- use "random" area on input image
- avoid duplicate cases
=> imgproc(test): fix resize bitexact test

modules/core/src/utils/filesystem.cpp
=> core: add getcwd() stub

modules/video/src/dis_flow.cpp, modules/video/src/variational_refinement.cpp
Fixed static analyzer warnings in DISOpticalFlow
=> Fixed static analyzer warnings in DISOpticalFlow

modules/core/src/arithm.cpp
Updated inRange, addWeighted and comparison implementations with wide un.intrinsics
```
```
=> Updated inRange, addWeighted and comparison implementations with wide un.intrinsics

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/perf/perf_net.cpp, modules/dnn/src/dnn.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_common.hpp, modules/dnn/test/test_googlenet.cpp, modules/dnn/test/test_ie_models.cpp, modules/dnn/test/test_misc.cpp
adds basic registry for DNN backends and targets
```
```
=> DNN backends registry

modules/dnn/src/dnn.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_common.hpp
relates #13332
```
docker_image:Linux AVX2=ubuntu-openvino:16.04
```
=> dnn: fixup available backends/targets

modules/stitching/perf/perf_matchers.cpp
=> stitching(perf): update test threshold

modules/dnn/src/op_inf_engine.cpp
=> Exclude Input layer from list of outputs for IE networks

modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/13384
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/556
```
```
=> Element-wise subtraction from TensorFlow

cmake/OpenCVVersion.cmake
moved to CMakeFiles (no conflicts are expected)
=> cmake: hide 'junk' dir from the root of build directory

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/loadsave.cpp
=> try to solve #13381

modules/dnn/src/vkcom/include/op_pool.hpp, modules/dnn/src/vkcom/src/context.cpp, modules/dnn/src/vkcom/src/context.hpp, modules/dnn/src/vkcom/src/op_base.cpp
=> dnn: fix vulkan backend builds with Clang

modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_torch_importer.cpp
=> Minor fixes in IE backend tests

modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/include/opencv2/core/hal/intrin_vsx.hpp, modules/imgproc/perf/perf_histogram.cpp, modules/imgproc/src/histogram.cpp
compareHist reworked to use wide universal intrinsics
=> compareHist updated with wide intrinsics

modules/gapi/include/opencv2/gapi/util/compiler_hints.hpp, modules/gapi/src/backends/fluid/gfluidcore.cpp, modules/gapi/src/backends/fluid/gfluidutils.hpp, modules/gapi/src/compiler/gcompiler.cpp, modules/gapi/src/compiler/gmodel.cpp, modules/gapi/src/compiler/gmodel.hpp
* Moved "resolve_kernels" and "check_islands_content" passes to separate "kernels" stage in compiler
* Removed unused opaque from cv::gimpl::Op
=> G-API: Added "kernels" pass stage to compiler

modules/highgui/src/cap_dc1394_v2.cpp
=> (2.4) videoio(dc1394): use lazy initialization on demand

modules/videoio/src/cap_dc1394_v2.cpp
=> videoio(dc1394): use lazy initialization on demand

modules/stitching/src/exposure_compensate.cpp
=> stitching: fix l_gains data type from Eigen solver (float / double)

modules/stitching/include/opencv2/stitching.hpp, modules/stitching/src/stitcher.cpp
Add methods to select the interpolation mode used when warping images in the stitcher
=> Stitching: added functions to set warp interpolation mode

modules/core/include/opencv2/core/eigen.hpp, modules/core/test/test_mat.cpp
=> core: fix eigen2cv() - don't change fixed type of 'dst'

modules/imgproc/src/median_blur.cpp, modules/imgproc/test/test_filter.cpp
resolves #13409
Fixed medianBlur implementation for hi-resolution images
=> Fixed medianBlur implementation for hi-resolution images

modules/core/misc/python/pyopencv_rotationwarper.hpp, modules/python/src2/cv2.cpp, modules/stitching/misc/python/pyopencv_stitching.hpp
fix after https://github.com/opencv/opencv/pull/13267
=> Fix python bindings without stitching module

cmake/OpenCVDetectInferenceEngine.cmake, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp
https://software.intel.com/en-us/openvino-toolkit
https://software.intel.com/en-us/articles/OpenVINO-RelNotes
backported #13293
<cut/>
```
tests_filter=*
```
=> dnn: add OpenVINO 2018R5 defines

modules/videoio/src/cap_v4l.cpp
=> videoio(v4l2): fix build due missing V4L2_CID_ISO_SENSITIVITY

modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/imgproc/src/filter.cpp
Reworked separable filter to use wide universal intrinsics
TODO:
```
```
=> Reworked separable filter to use wide universal intrinsics

modules/objdetect/src/qrcode.cpp
=> objdetect(qrcode): don't process small/non-regular images

modules/dnn/src/layers/mvn_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_ie_models.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
=> Fix dnn tests with Inference Engine R5

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, platforms/android/build_sdk.py, platforms/android/service/engine/AndroidManifest.xml, platforms/android/service/engine/src/org/opencv/engine/OpenCVEngineService.java, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
<cut/>
<details>
[opencv_world345.dll (vc14)](https://www.virustotal.com/#/file/34332bd528ccf4f5788dd0b90fbb315ee9f616966687eb09d83d8876a1698ff1/detection)
[opencv_world345d.dll (vc14)](https://www.virustotal.com/#/file/923361d83dc3922822731c2c54766608c9f804526c1e07c800545eea26e1751d/detection)
[opencv_world345.dll (vc15)](https://www.virustotal.com/#/file/c1ba032b632b4c97eb9d06059ed54798bfe1d976c3d9ed626e59b8543847f23d/detection)
[opencv_world345d.dll (vc15)](https://www.virustotal.com/#/file/504b8d0f5ba4324f8b0cf7bf85fe9cb4f66a06afcc6fac299572987407c5db4f/detection)
[opencv_ffmpeg345_64.dll](https://www.virustotal.com/#/file/e6acb89dfe6f3af13afaa3ff46ca4e3e1846d868d398e0fd662da2affd515d61/detection) …
=> OpenCV version++ (3.4.5)

modules/imgproc/src/filter.cpp
Commit: 124011c3219b4be6b90aec4538b4560711deb3d2
PR: https://github.com/opencv/opencv/pull/13392
Sobel filter with 16S/16U datatype is broken.
relates #13506
=> imgproc: revert "Speedup filter2d by loop unrolling"

modules/js/src/core_bindings.cpp, modules/js/src/embindgen.py
=>  js: allow building with aruco 

samples/dnn/edge_detection.py
resolves https://github.com/opencv/opencv/issues/13576
=> Fix edge_detection.py sample for Python 3

3rdparty/carotene/src/resize.cpp
=> fix implicit fallthrough warning.

modules/core/misc/java/src/java/core+RotatedRect.java
Fix a very small typo in core+RotatedRect.java in Java binding. See commit.
=> Fix typo in core+RotatedRect.java

modules/calib3d/src/homography_decomp.cpp, modules/calib3d/test/test_homography_decomp.cpp
=> Fix the bug in case determinant of rotation matrix is -1

samples/dnn/tf_text_graph_common.py, samples/dnn/tf_text_graph_faster_rcnn.py, samples/dnn/tf_text_graph_mask_rcnn.py, samples/dnn/tf_text_graph_ssd.py
Enable SSD models from [TensorFlow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) with FPN proposals.
Tested models:
* [ssd_mobilenet_v1_fpn_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz)
* [ssd_resnet_50_fpn_coco](http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz)
resolves https://github.com/opencv/opencv/issues/12835
=> SSD with FPN proposals from TensorFlow

doc/py_tutorials/py_feature2d/py_matcher/py_matcher.markdown
resolves https://github.com/opencv/opencv/issues/13615
=> fixed tutorial code of py_matcher

modules/core/include/opencv2/core/cvdef.h, modules/imgproc/src/fixedpoint.inl.hpp
=> Added CV_ALWAYS_INLINE macro

modules/imgproc/src/filter.cpp, modules/imgproc/src/morph.cpp
Morphology reworked to use wide universal intrinsics
TODO:
=> Morphology reworked to use wide universal intrinsics

modules/calib3d/src/circlesgrid.cpp, modules/calib3d/src/quadsubpix.cpp, modules/calib3d/test/test_cameracalibration.cpp, modules/calib3d/test/test_cameracalibration_artificial.cpp, modules/calib3d/test/test_chessboardgenerator.cpp, modules/calib3d/test/test_solvepnp_ransac.cpp, modules/features2d/src/blobdetector.cpp, modules/objdetect/src/qrcode.cpp
=> Code clean up

modules/imgproc/src/thresh.cpp
threshold() reworked to use wide universal intrinsics
=> threshold() reworked to use wide universal intrinsics

modules/gapi/src/api/gcall_priv.hpp
This pullrequest documents internal GCall behavior
=> GAPI: document GCall's recursive behavior

modules/imgproc/perf/perf_contours.cpp, modules/imgproc/src/shapedescr.cpp
boundingRect() reworked to use wide universal intrinsics
```
```
=> boundingRect() reworked to use wide universal intrinsics

modules/flann/include/opencv2/flann/kdtree_index.h, modules/flann/include/opencv2/flann/lsh_index.h, modules/flann/include/opencv2/flann/random.h
std::rand() has no thread-safe guarantee.
backport commit: 147f3ebf0add6e281b5fc0a4d0c2826502ce88cd (#8294)
=> (2.4) flann: use OpenCV theRNG()

modules/imgproc/src/color_yuv.cpp, modules/imgproc/test/test_color.cpp
relates #13649
Debug build is fine only (without SIMD optimizations)
```
```
=> imgproc(test): RGB2YUV regression test

modules/imgproc/src/color_yuv.cpp
port of PR #13649
See the original PR description
```
```
=> YUV/YCrCb conversions rewritten to wide intrinsics (port to master)

modules/gapi/src/backends/fluid/gfluidbackend.cpp
This patch fixes the issue when FluidData.internal flag incorrectly set to true for nodes which are slot nodes in terms of the IslandModel (nodes which connect different islands).
In the picture below Data1 is read by Sobel3x3 which requires 1-pixel border. Data1 is a slot node and its data will be full-image allocated by GExecutor. But without proposed fix FluidData.internal flag will be set to true for Data1 and later passes will assume what its data will be allocated as internal fluid ring buffer with border maintained and preallocated by fluid backend. In the end it will lead to a segfault as border will not be added to Data1 and Sobel3x3 will try to read border pixels.
```
+--fluid_isl0----------------------+    +--nonfluid_isl0--+
| Op -> Data1 -> Sobel3x3 -> Data2 | -> |   .... …
```
=> G-API Fixed fluid heterogeneity support

modules/dnn/src/dnn.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_layers.cpp
```
tests_filter=*
build_parallel_tests=1
```
**WIP**
=> DNN: Object detection sample: Fix bug with other size

modules/dnn/src/dnn.cpp, modules/dnn/test/test_misc.cpp
resolves https://github.com/opencv/opencv/issues/13575
=> Fix a dnn bug with retrieving all the output blobs

modules/imgproc/src/median_blur.cpp
=> imgproc: medianBlur code cleanup

modules/imgproc/perf/perf_blur.cpp, modules/imgproc/src/blend.cpp
blendLinear() reworked to use wide universal intrinsics
```
```
=> blendLinear() reworked to use wide universal intrinsics

modules/imgproc/src/spatialgradient.cpp
spatialGradient() reworked to use wide universal intrinsics
```
```
=> spatialGradient() reworked to use wide universal intrinsics

modules/dnn/src/layers/blank_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp
This PR fixes tests with Intel's Inference Engine from the future :alien: 
```
```
=> Fix IE tests

modules/imgproc/src/color_yuv.cpp
All 4:2:0 and 4:2:2 conversions from/to YUV in `color_yuv.cpp` rewritten to wide universal intrinsics
<cut/>
Summary, performance boost (times) compared to original time
|Baseline|RGB to YUV42x|YUV42x to RGB, small|YUV42x to RGB, big|
|AVX2|2-3|8-10|13-18|
|AVX512SKX|2.5-3.5|9-11|11-18|
|SSE2|1|4-6|5.5-9.5|
|SSE4.1|2.5-3.5|9-10|11-18|
Geometric mean (ms):
<details>
<summary>Baseline AVX2</summary>
|Name of Test|yuv initial avx2|yuv wide 42x avx2|yuv wide 42x avx2 vs yuv initial avx2 (x-factor)|
|CvtColor::OCL_CvtColorFixture::(640x480, (COLOR_RGB2YUV_IYUV, 3, 1))|0.458|0.177|2.60|
|CvtColor::OCL_CvtColorFixture::(640x480, (COLOR_YUV2RGB_IYUV, 1, 3))|1.779|0.103|17.25|
|CvtColor::OCL_CvtColorFixture::(640x480, (COLOR_YUV2RGB_NV12, 1, …
=> YUV42x color conversions rewritten to wide intrinsics

samples/dnn/object_detection.cpp, samples/dnn/object_detection.py
Fixed work net:
* [https://github.com/opencv/open_model_zoo/tree/2018/intel_models/person-detection-retail-0002](https://github.com/opencv/open_model_zoo/tree/2018/intel_models/person-detection-retail-0002) 
* [https://github.com/opencv/open_model_zoo/tree/2018/intel_models/face-person-detection-retail-0002](https://github.com/opencv/open_model_zoo/tree/2018/intel_models/face-person-detection-retail-0002)
on object detection sample
=> DNN: Object detect sample: Update functionality

modules/dnn/src/op_inf_engine.cpp, modules/dnn/test/test_layers.cpp
resolves https://github.com/opencv/opencv/issues/13715
resolves https://github.com/opencv/opencv/issues/13569
```
#test_modules=dnn
```
=> Add a mutex for shared Inference Engine plugins

modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/test/test_backends.cpp
Issue: [https://github.com/opencv/opencv/issues/13724](https://github.com/opencv/opencv/issues/13724)
=> DNN: IE Backend: Not work with other width-height

modules/core/src/ocl.cpp
resolves #13741
```
CXXFLAGS:Linux x64 Debug=-DCV_LOG_STRIP_LEVEL=10
```
=> core(ocl): fix log messages

modules/python/package/cv2/__init__.py
=> python: sys.path[0] is reserved for the main script

modules/core/src/ocl.cpp
=> (3.4) core(ocl): fix log messages

apps/traincascade/old_ml.hpp, doc/pattern_tools/gen_pattern.py, doc/py_tutorials/py_feature2d/py_brief/py_brief.markdown, modules/calib3d/src/rho.cpp, modules/core/include/opencv2/core/cvstd.hpp, modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/src/bindings_utils.cpp, modules/core/src/precomp.hpp, modules/core/src/utils/datafile.cpp, modules/dnn/src/onnx/opencv-onnx.proto, modules/ml/include/opencv2/ml.hpp, modules/ml/src/svm.cpp, modules/videoio/src/cap_dshow.cpp
=> (3.4) spelling fixes

modules/dnn/src/caffe/caffe_importer.cpp
related: https://stackoverflow.com/questions/54536676/how-to-fix-error-215-pbblob-raw-data-type-caffefloat16-in-function
=> Read raw floats data from Caffe models

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_halide_layers.cpp
This PR fixes changes in Inference Engine backend which will come from the future :ghost:
```
docker_image:Custom=ubuntu-openvino-2018r4:16.04
```
=> Fix Intel's Inference Engine backend

modules/gapi/include/opencv2/gapi/imgproc.hpp, modules/gapi/src/api/kernels_imgproc.cpp, modules/gapi/src/backends/cpu/gcpuimgproc.cpp, modules/gapi/test/common/gapi_imgproc_tests.hpp, modules/gapi/test/common/gapi_imgproc_tests_inl.hpp, modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp
This pullrequest adds a new kernel for nv12 to rgb color conversion
=> G-API: Introduces NV12 to RGB and BGR color conversion

modules/photo/include/opencv2/photo.hpp, modules/photo/src/tonemap.cpp
=> Solves bug 13853

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/blank_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/src/layers/scale_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_halide_layers.cpp
=> Fix Inference Engine backend

modules/dnn/src/layers/detection_output_layer.cpp
=> Replace default confidence threshold for dnn detectors

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/579
resolves https://github.com/opencv/opencv/issues/13479 considering changes from https://github.com/opencv/opencv/pull/13730
```
```
=> Grouped deconvolution from ONNX

samples/dnn/tf_text_graph_ssd.py
resolves https://github.com/opencv/opencv/issues/13895
=> Fix TensorFlow SSDs with non-square inputs

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/580
=> Import Upsample and Unsqueeze from ONNX

modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/include/opencv2/core/hal/intrin_vsx.hpp, modules/imgproc/src/pyramids.cpp
Horizontal line processing for pyrDown() reworked using wide universal intrinsics.
=> Horizontal line processing for pyrDown() reworked using wide universal intrinsics

modules/core/include/opencv2/core/vsx_utils.hpp
resolves #13934
````
pw_compilers=gcc-4.9, gcc-5, gcc-6, power9_gcc-6, power9_gcc-7
````
=> core:vsx Fix narrowing warning on vector splats

modules/ml/src/svm.cpp
=> ml: handle sigmoid NaN result (should be Inf)

platforms/android/build_sdk.py
* look for NDK in "ndk-bundle" directory under the SDK directory if location not specified
* look for cmake and ninja in "cmake" directory under the SDK directory if not found in the path
* disable use of ccache if not found in the path
=> Android build improvements

modules/videoio/src/cap_v4l.cpp
=> videoio(v4l): fix build due missing defines

modules/core/misc/python/pyopencv_umat.hpp, modules/core/misc/python/shadow_umat.hpp, modules/java/generator/gen_java.py, modules/python/bindings/CMakeLists.txt, modules/python/src2/cv2.cpp, modules/python/src2/gen2.py, modules/python/src2/hdr_parser.py, modules/stitching/misc/python/pyopencv_stitching.hpp, modules/videoio/misc/python/pyopencv_videoio.hpp
- better handling of enum arguments
- less merge conflicts
```
```
=> bindings: backport generator from OpenCV 4.x

platforms/android/build_sdk.py
=> (3.4) android: backport build_sdk.py

modules/core/src/cuda_host_mem.cpp, modules/core/src/opengl.cpp, modules/highgui/src/window_QT.cpp
Validated:
- [1](http://pullrequest.opencv.org/buildbot/builders/3_4_cuda-lin64/builds/319)
- [2](http://pullrequest.opencv.org/buildbot/builders/3_4_etc-qt-openmp-lin64/builds/165)
=> build: fix warnings

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_torch_importer.cpp
=> DNN: Optimization: Fuse Deconvolution -> BatchNorm

modules/core/include/opencv2/core/cvstd_wrapper.hpp
=> CUDA 10.1 Build Issue Fix on Master Branch

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/grfmt_jpeg2000.cpp
I believe the title says it all.
Since this is my first PR to the OpenCV repository, I might have missed some required changes.
Therefore, your guidance is very appreciated!
Best,
Gregor
=> Add JPEG2000 compression flag.

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/grfmt_tiff.cpp
=> issue-13921: Support setting compression setting for writing tiff images

modules/core/include/opencv2/core/hal/intrin_neon.hpp
=> core(intrin): NEON v_load_expand_q() support unaligned addr

doc/tutorials/calib3d/camera_calibration_pattern/camera_calibration_pattern.markdown, doc/tutorials/calib3d/table_of_content_calib3d.markdown
=> Tutorial create pattern grid for calibration using gen_pattern.py

modules/cudaarithm/src/core.cpp, modules/cudaarithm/src/cuda/lut.cu, modules/cudaarithm/src/lut.cpp, modules/cudaarithm/src/lut.hpp
https://github.com/opencv/opencv/issues/13952#issuecomment-470260632
```
```
=> Extract Ptr-related code from lut.cu to new lut.cpp

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/drawing.cpp
reverts #13843 (see comments for details)
Separate implementation is in progress here: #13869
=> imgproc: revert #13843

doc/js_tutorials/js_assets/utils.js, modules/js/src/embindgen.py
resolves https://github.com/opencv/opencv/issues/14020
Added changes from
https://github.com/opencv/opencv/pull/12361
https://github.com/opencv/opencv/pull/12601
https://github.com/opencv/opencv/pull/12622
```
```
=> Add onRuntimeInitialized for opencv.js (WASM)

modules/photo/include/opencv2/photo.hpp
documentation improvement
https://pullrequest.opencv.org/buildbot/export/pr/13655/docs/d1/d0d/group__photo.html
```
force_builders=Linux x64,docs
```
=> Update documentation -photo.hpp-

samples/python/stitching_detailed.py
add `if __name__ == '__main__'`: in stitching_detailed.py
=> Issue 14047

doc/tutorials/imgproc/anisotropic_image_segmentation/anisotropic_image_segmentation.markdown, doc/tutorials/imgproc/motion_deblur_filter/motion_deblur_filter.markdown, doc/tutorials/imgproc/out_of_focus_deblur_filter/out_of_focus_deblur_filter.markdown, doc/tutorials/imgproc/periodic_noise_removing_filter/periodic_noise_removing_filter.markdown
Adding the previous and next tutorial links to the scripts where they were missing for the Image Processing tutorials.
=> adding missing quick navigation to ImageProc module

modules/core/src/lda.cpp, modules/core/test/test_eigen.cpp
=> core: add iterations limit check in eigenNonSymmetric()

modules/core/src/utils/filesystem.cpp
=> core: cache dir version update

modules/core/include/opencv2/core/hal/intrin_vsx.hpp
* optimize v_lut_deinterleave
* optimize v_interleave_/pairs/quads/triplets
* optimize v_lut, use vec_extract instead of aligned store
````
pw_compilers=clang-4, clang-5, clang-6, gcc-4.9,power9_ gcc-5, power9_gcc-6, power9_gcc-7
````
=> core:vsx Several improvements(3)

modules/core/src/matmul.simd.hpp
transform() implementation updated to utilize wide universal intrinsics
=> transform() implementation updated to utilize wide universal intrinsics

platforms/android/build-tests/test_cmake_build.py, platforms/android/build_sdk.py
enables Video I/O backend via Media NDK
relates #14005
=> android: build package with API 21

cmake/OpenCVDetectInferenceEngine.cmake
<cut/>
```
#docker_image:Linux AVX2=ubuntu-openvino-2018r4:16.04
#test_opencl:Linux AVX2=OFF
#buildworker:Linux AVX2=linux-1
#build_parallel_tests:Linux AVX2=1
#test_bigdata:Linux AVX2=1
#test_module:Linux AVX2=dnn,python2,python3,java
#tests_filter:Linux AVX2=*:-Test_Caffe_layers.Conv_Elu/1
```
=> cmake: support OpenVINO env variable: INTEL_OPENVINO_DIR

samples/python/dis_opt_flow.py, samples/python/stitching.py, samples/python/stitching_detailed.py
relates #14108
resolves #14047
=> samples: fix python samples compatibility with demo.py

CMakeLists.txt
resolves #14139
<cut/>
```
```
=> cmake: set CMP0068 => NEW

modules/core/src/lda.cpp
- fix resource allocation management
- reduce variables scope
- fix complex_div
- fix comments, constants
- simplify add/sub operations
- ~~use mul by *inv_value* instead of multiple div operations~~ (regressions)
<cut/>
Decomposed commits: https://github.com/alalek/opencv/commits/core_refactor_eigenvalues_detailed
```
```
=> core: refactor EigenvalueDecomposition (hqr2)

modules/dnn/test/test_ie_models.cpp
=> Reduce number of tested models from OpenVINO

modules/dnn/test/test_ie_models.cpp
Fix after https://github.com/opencv/opencv/pull/14212 for IE test build for version after 2018R5.
=> Fix build with IE > 2018R5

modules/dnn/src/tensorflow/tf_importer.cpp
tensorflow tf.add_n op has supported by opencv already.Just add a judgement code.
=> Add support for   tf.add_n operation

modules/imgcodecs/src/grfmt_bmp.cpp
=> (3.4) imgcodecs(bmp): limit size of processed images

modules/imgcodecs/src/grfmt_sunras.cpp
=> (3.4) imgcodecs(sunras): avoid undefined shift

modules/dnn/src/dnn.cpp
variable `i` is only used int for loops, move it in.
=> Postpone variable definitions

cmake/OpenCVDetectInferenceEngine.cmake, modules/dnn/perf/perf_net.cpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_ie_models.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp
<cut/>
```
docker_image:Linux AVX2=ubuntu-openvino-2019r1:16.04
```
=> dnn: OpenVINO 2019R1

modules/imgcodecs/src/grfmt_tiff.cpp
=> imgcodecs(tiff): check TIFF tile size

modules/calib3d/src/ptsetreg.cpp, modules/calib3d/test/test_affine2d_estimator.cpp, modules/calib3d/test/test_affine_partial2d_estimator.cpp
resolves #14259
Thanks @llschloesser for the test case!
=> calib3d: don't change input data in estimateAffine2D/estimateAffinePartial2D()

modules/core/include/opencv2/core/version.hpp
relates #14037
<cut/>
<details>
[opencv_world410.dll (vc14)](https://www.virustotal.com/gui/file/3eeb6f0befda496d6f037b997aefde145641440fe5cddbba9237a6ae29d52d7c/detection)
[opencv_world410d.dll (vc14)](https://www.virustotal.com/gui/file-analysis/OGUxNjJmODdjZjhkN2YwYTYwYzczNDlkYzNkYTMwODI6MTU1NDcxMDU1Nw==/detection) (1 detection, [considered false positive](https://stackoverflow.com/questions/54052224/virustotal-trapmine-suspicious-low-ml-score) - 2019-04-07)
[opencv_world410.dll (vc15)](https://www.virustotal.com/gui/file/65234854502e8b2e50ba65893e95191da2c0771a0284c3047ed0e2de5e253c23/detection) (1 detection, [considered false positive](https://stackoverflow.com/questions/54052224/virustotal-trapmine-suspicious-low-ml-score) - 2019-04-07) …
=> release: OpenCV 4.1.0

modules/highgui/src/window_cocoa.mm, modules/videoio/src/cap_avfoundation_mac.mm
resolves #14291
<cut/>
```
CXXFLAGS_EXTRA:Mac OpenCL=--std=c++11
```
=> macosx: fix C++11 build

cmake/OpenCVDetectDirectX.cmake, cmake/OpenCVDetectOpenCL.cmake
resolves #14286
relates #13972
=> cmake: fix WITH_OPENCL_D3D11_NV check

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp
=> Deep networks visualization

doc/py_tutorials/py_imgproc/py_histograms/py_histogram_backprojection/py_histogram_backprojection.markdown
=> fix just a typo of the word 'word'

modules/ts/src/ts.cpp
=> ts: flush stdout/stderr before test launch

modules/calib3d/CMakeLists.txt, modules/calib3d/src/calibinit.cpp, modules/calib3d/src/circlesgrid.cpp, modules/features2d/CMakeLists.txt, modules/features2d/src/blobdetector.cpp
=> build: avoid highgui dependency

modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/src/op_inf_engine.hpp
=> Fix Inference Engine extensions on Mac

modules/ml/include/opencv2/ml.hpp, modules/ml/misc/python/test/test_knearest.py, modules/ml/src/knearest.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/597
Add Ptr KNearest::load and python binding
relates #14137
```
test_modules=python2,python3
```
=> Add Ptr KNearest::load and python binding

modules/dnn/src/layers/flatten_layer.cpp, modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/13839
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/595
=> Fix TensorFlow's Squeeze and a new fusion for SoftMax from slim backend

doc/py_tutorials/py_ml/py_svm/py_svm_opencv/py_svm_opencv.markdown
Fixes a broken link for Histogram and Orient Gradients.
=> Update py_svm_opencv.markdown: Fixes a broken link and a typo.

modules/imgcodecs/src/grfmt_tiff.cpp
=> imgcodecs(tiff): update tile size checks

modules/imgcodecs/src/grfmt_tiff.cpp
=> (3.4) imgcodecs(tiff): update tile size checks

modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp
Cleared up deprecated intrinsics for FP16
=> Cleared up deprecated intrinsics for FP16

modules/dnn/src/onnx/onnx_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/599
Extra resolves https://github.com/opencv/opencv/issues/13894
=> Const reshape for ONNX

samples/cpp/digits.cpp
Currently, only a Python implementation of the SVM and KNearest digit recognition sample exists. This pull request adds a C++ implementation.
=> samples: Add C++ implementation of digits.py

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra:** opencv/opencv_extra#601
=> Fix ONNX importer deconvolution

modules/gapi/include/opencv2/gapi/gmat.hpp, modules/gapi/include/opencv2/gapi/gproto.hpp, modules/gapi/include/opencv2/gapi/gtype_traits.hpp, modules/gapi/src/api/gbackend.cpp, modules/gapi/src/api/gmat.cpp, modules/gapi/src/api/gproto.cpp, modules/gapi/src/backends/common/gbackend.hpp, modules/gapi/src/backends/cpu/gcpubackend.cpp, modules/gapi/src/backends/ocl/goclbackend.cpp, modules/gapi/src/compiler/gcompiled.cpp, modules/gapi/src/executor/gexecutor.cpp, modules/gapi/test/gapi_desc_tests.cpp, modules/gapi/test/gapi_planar_test.cpp, modules/gapi/test/internal/gapi_int_gmetaarg_test.cpp
* Added `planar` flag to `GMatDesc`, `asPlanar()` and `asInterleaved()` combinators, integrated into framework, added tests
=> G-API planar GMatDesc

modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/test/test_intrin_utils.hpp
Fixed v_reduce_sad intrinsics implementation and added tests
=> Fixed v_reduce_sad intrinsics implementation and added tests

modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java
resolves #13526
Changed the way Images are converted into rgba Mats so that JavaCamera2View also shows correct colors when the Image contains I420 or YV12 data.
Converting Images to Mats now checks the properties of the Image Planes to choose the correct conversion method. Two main case can be discerned: 
1. The pixel stride of the chroma channels equals 2. This means the Image data is in NV21 format. This case was already supported and the code for the conversion was reused.
2. The pixel stride of the chroma channels equals 1. This means the chroma channels of the image are not interleaved. This case was not supported yet and caused the the colors of the image to be displayed incorrectly (the image was mostly green/purple as seen below). This was fixed by checking the pixel stride of the …
=> Fix for JavaCamera2View not displaying colors correctly on some devices

modules/calib3d/src/fundam.cpp
=> Fix for Homogenous precision #14242

modules/dnn/misc/python/test/test_dnn.py
resolves https://github.com/opencv/opencv/issues/14435
**WIP**
```
test_modules:Custom=dnn,java,python2,python3
test_bigdata:Custom=ON
```
=> Add an assertion for Async request status

modules/gapi/CMakeLists.txt, modules/gapi/include/opencv2/gapi/gcompiled_async.hpp, modules/gapi/include/opencv2/gapi/gcomputation_async.hpp, modules/gapi/src/executor/gasync.cpp, modules/gapi/test/gapi_async_test.cpp
- naive implementation as a starting point
- Adds a naive implementation of Asynchronous API for GAPI module
=> Async API for GAPI

modules/ts/src/ts_perf.cpp
properly handle "check" mode with:
"--perf_min_samples=1 --perf_force_samples=1"
=> ts: fix perf calibation

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/dnn.cpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/layers_common.cpp, modules/dnn/src/layers/layers_common.hpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/594
<cut/>
```
test_module:Mac OpenCL=dnn,python2,python3,java
```
=> Support Convolution3D layer on IE backend

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/13494
resolves https://github.com/opencv/opencv/issues/11183
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/603
=> Refactored TensorFlow subgraphs fusion

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp, modules/gapi/include/opencv2/gapi/gcall.hpp, modules/gapi/include/opencv2/gapi/gkernel.hpp, modules/gapi/include/opencv2/gapi/gmat.hpp, modules/gapi/include/opencv2/gapi/gproto.hpp, modules/gapi/include/opencv2/gapi/gtype_traits.hpp, modules/gapi/src/api/gcall.cpp, modules/gapi/src/api/gproto.cpp, modules/gapi/src/compiler/gcompiler.cpp, modules/gapi/test/gapi_planar_test.cpp, modules/gapi/test/internal/gapi_int_garg_test.cpp
* Added GMatP type
* Changed planar tests to operate on GMatP
=> G-API GMatP

modules/dnn/src/op_inf_engine.cpp
<cut/>
```
docker_image:Linux AVX2=ubuntu-openvino-2019r1:16.04
```
=> build: avoid MSVC ICE

modules/ml/doc/ml_intro.markdown
fix a typo in ml_intro.md, tress -> trees
=> fix a typo in md file

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/layers_common.cpp, modules/dnn/src/layers/layers_common.hpp, modules/dnn/src/layers/pooling_layer.cpp
resolves https://github.com/opencv/opencv/issues/14464
=> Fix #14464

modules/videoio/src/cap_avfoundation_mac.mm, modules/videoio/src/cap_mfx_writer.cpp, modules/videoio/test/test_mfx.cpp, modules/videoio/test/test_video_io.cpp
Related #14156
Related #14267
Related #14278
Backported some improvements made in AVFoundation and MediaSDK backends on _master_ branch.
=> Backported AVFoundation fixes from master branch

samples/dnn/tf_text_graph_ssd.py
about https://answers.opencv.org/question/212607/readnet-fails
=> extends regex matching for conv group of layers

modules/dnn/src/dnn.cpp, samples/dnn/object_detection.cpp, samples/dnn/object_detection.py
resolves https://github.com/opencv/opencv/issues/13667
Camera with 60fps @ 1280x720 is used (Logitech C922 PRO)
| Target | `--async=0` | `--async=1` | `--async=2` | `--async=3` | `--async=4` |
|------|-----|-----|-----|----|---|
| NCS, USB 3.0 | 11.6 | 9.9 | 11.9 | 11.9 | 11.9 |
| NCS2, USB 3.0 | 26.43 | 19.9 | 39.5 | **53.2** | 48.6 |
CPU: Intel® Core™ i7-6700K CPU @ 4.00GHz × 8
NCS: Intel® Movidius™ Neural Compute Stick
NCS2: Intel® Neural Compute Stick 2
* All the numbers are frames per second which are processed by network (FPS):
```
$ python object_detection.py opencv_fd --target 3
```
```
build_parallel_tests:Custom=1 …
```
=> Async mode for dnn's object detection sample

modules/calib3d/src/stereobm.cpp, modules/core/src/system.cpp
Small typo fixes in modules/calib3d/src/stereobm.cpp and modules/core/src/system.cpp
=> Small typo fixes

modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/include/opencv2/core/hal/intrin_vsx.hpp, modules/core/src/stat.simd.hpp, modules/core/test/test_intrin_utils.hpp
Reworked v_popcount implementation to provide number of bits in a single lane
TODO:
```
```
=> Reworked v_popcount implementation

doc/py_tutorials/py_ml/py_knn/py_knn_opencv/py_knn_opencv.markdown
helps in resolving issue #5673
this pull request just removes unnecessary importing to matplotlib in knn tutorials
=> remove unnecessary imports in knn tutorials

modules/calib3d/include/opencv2/calib3d.hpp
=> calib3d(docs): examples paragraph is related to findHomography()

modules/imgproc/src/color_lab.cpp, modules/imgproc/test/test_color.cpp
* All color conversions from `color_lab.cpp` rewritten to wide universal intrinsics
* Platform-specific code removed
* Minor fix to tests logging
<cut/>
* `wide 84 big` is final revision's performance
* `wide 78` is [intermediate revision of April 18th](https://github.com/opencv/opencv/pull/14106/commits/b3c16d22b0d4a1f5d6b956461bbcd35aec15269b)
<details>
<summary>Baseline AVX512 SKX</summary>
|Name of Test|lab initial avx512|lab wide 78 avx512|lab wide 84 big avx512|lab wide 78 avx512 vs lab initial avx512 (x-factor)|lab wide 84 big avx512 vs lab initial avx512 (x-factor)|
|---|:-:|:-:|:-:|:-:|:-:|
|cvtColor8u::Size_CvtMode::(1920x1080, COLOR_BGR2Lab)|10.338|7.932|7.875|1.30|1.31|
|cvtColor8u::Size_CvtMode::(1920x1080, COLOR_BGR2Luv)|14.173|13.979|14.918|1.01|0.95| …
=> Lab, Luv and XYZ conversions rewritten to wide intrinsics

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/608
Fix wrong indentation as well while at it
```
opencv_extra=onnx-log-softmax
force_builders=Linux x64,docs
```
=> Fix LogSoftmax for ONNX

cmake/OpenCVFindLAPACK.cmake
MSVC does not support `float _Complex` type, instead it provides `_Fcomplex` and `_Dcomplex`. This patch fixes compilation with OpenBLAS. Previously we only used MKL on Windows.
```
```
=> LAPACK: add support for complex numbers for MSVC

modules/imgproc/src/color.simd_helpers.hpp, modules/imgproc/src/color_hsv.simd.hpp
- All conversions from `color_hsv.simd.hpp` rewritten to wide universal intrinsics
- Platform-specific code removed
TODOs:
<cut/>
On sizes 640x480 and 1920x1080:
* RGB2HSV_b: up to 7x
* The rest: 1x to 1.5x
<details>
<summary>Baseline AVX512 SKX</summary>
|Name of Test|hsv initial avx512skx|hsv wide 49 avx512skx|hsv wide 49 avx512skx vs hsv initial avx512skx (x-factor)|
|cvtColor8u::Size_CvtMode::(127x61, COLOR_BGR2HLS)|0.026|0.020|1.26|
|cvtColor8u::Size_CvtMode::(127x61, COLOR_BGR2HLS_FULL)|0.025|0.020|1.24|
|cvtColor8u::Size_CvtMode::(127x61, COLOR_BGR2HSV)|0.054|0.020|2.69|
|cvtColor8u::Size_CvtMode::(127x61, COLOR_BGR2HSV_FULL)|0.055|0.020|2.72|
|cvtColor8u::Size_CvtMode::(127x61, COLOR_HLS2BGR)|0.026|0.030|0.87|
|cvtColor8u::Size_CvtMode::(127x61, …
=> HSV and HLS color conversions rewritten to wide intrinsics

modules/videoio/src/backend_plugin.cpp, modules/videoio/src/cap_v4l.cpp
Build fix for OpenBSD systems out of 3rdparty part.
=> OpenBSD build fix

modules/video/src/dis_flow.cpp, modules/video/test/test_OF_accuracy.cpp
=> video:fixed DISOpticalFlow segfault from small img

modules/dnn/perf/perf_net.cpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/test/test_backends.cpp
test | base (ms) | PR (ms) | x-factor
---|---|---|---
FastNeuralStyle_eccv16::DLIE/CPU      |146.392 | 142.619  |  1.03   |
FastNeuralStyle_eccv16::DLIE/MYRIAD   |560.456 | 340.125  |  **1.65**   |
FastNeuralStyle_eccv16::DLIE/OCL      |116.203 | 100.790  |  **1.15**   |
FastNeuralStyle_eccv16::DLIE/OCL_FP16| 82.708 |  67.763  |   **1.22**   |
CPU: Intel® Core™ i7-6700K CPU @ 4.00GHz × 8
GPU: Intel® HD Graphics 530 (Skylake GT2)
VPU: Intel® Neural Compute Stick 2
```
```
=> Enable Slice layer on Inference Engine backend

modules/dnn/include/opencv2/dnn/all_layers.hpp
=> dead link in doc

modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp
```
force_builders=Linux x64 Debug
```
=> dnn(test): update test tags for Debug build

modules/androidcamera/src/camera_activity.cpp
=> make it compatible with clang

modules/gapi/include/opencv2/gapi/own/exports.hpp
- [Warning](http://pullrequest.opencv.org/buildbot/builders/master_noOCL-mac-static/builds/10818)
- [Validated](http://pullrequest.opencv.org/buildbot/builders/master_noOCL-mac-static/builds/10819) :+1:
=> gapi: fix visibility conflict in OpenCV builds

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/test/test_tf_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/613
<cut/>
```
```
=> Fix Identity Switch from Keras

modules/core/include/opencv2/core/hal/intrin_avx.hpp, modules/core/test/test_intrin_utils.hpp
Fix for AVX2 version of v_reduce_min intrinsic
=> Fix for AVX2 version of v_reduce_min intrinsic

modules/videoio/src/backend_plugin.cpp
=> FreeBSD build fix

modules/dnn/perf/perf_net.cpp, modules/dnn/src/layers/blank_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_torch_importer.cpp
=> Enable more deconvolution layer configurations with IE backend

3rdparty/libpng/CHANGES, 3rdparty/libpng/LICENSE, 3rdparty/libpng/README, 3rdparty/libpng/arm/palette_neon_intrinsics.c, 3rdparty/libpng/png.c, 3rdparty/libpng/png.h, 3rdparty/libpng/pngconf.h, 3rdparty/libpng/pnglibconf.h, 3rdparty/libpng/pngpriv.h, 3rdparty/libpng/pngread.c, 3rdparty/libpng/pngrtran.c, 3rdparty/libpng/pngrutil.c, 3rdparty/libpng/pngstruct.h, 3rdparty/libpng/pngwrite.c
http://www.libpng.org/pub/png/libpng.html
https://github.com/glennrp/libpng/releases
relates #13807
```
docker_image:Custom=fedora:29
```
=> 3rdparty: update libpng 1.6.37

3rdparty/libjpeg-turbo/CMakeLists.txt, 3rdparty/libjpeg-turbo/src/jcicc.c, 3rdparty/libjpeg-turbo/src/jdicc.c
=> 3rdparty: fix missing files from libjpeg-turbo 2.0.2

3rdparty/protobuf/README.md, 3rdparty/protobuf/src/google/protobuf/stubs/io_win32.cc
https://github.com/protocolbuffers/protobuf/compare/v3.5.1..v3.5.2
=> 3rdparty: apply protobuf v3.5.1..v3.5.2 patch

modules/imgproc/src/imgwarp.cpp
https://github.com/opencv/opencv/issues/14265
=> Fix alignment issue on ARMv7

modules/dnn/src/caffe/caffe_importer.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/test/test_caffe_importer.cpp
**Merge with extra:** opencv/opencv_extra#614
```
docker_image:Custom=ubuntu-openvino-2019r1.1:16.04
```
=> Add Axpy layer

modules/imgcodecs/src/grfmt_pam.cpp
=> (3.4) imgcodecs: sanitize PAM decoding

modules/calib3d/src/fundam.cpp, modules/calib3d/src/ippe.hpp, modules/calib3d/test/test_cameracalibration_artificial.cpp, modules/core/include/opencv2/core/core_c.h, modules/core/include/opencv2/core/operations.hpp, modules/core/include/opencv2/core/optim.hpp, modules/core/src/datastructs.cpp, modules/core/src/mathfuncs_core.simd.hpp, modules/imgcodecs/src/exif.cpp, modules/imgcodecs/src/rgbe.cpp, modules/ts/src/ts_gtest.cpp, modules/video/src/ecc.cpp, modules/video/src/lkpyramid.cpp, samples/cpp/videocapture_openni.cpp
=> Fix some typos

samples/python/tutorial_code/imgProc/BasicGeometricDrawing/basic_geometric_drawing.py
resolves #14732
Fixes drawing errors by casting positional arguments to int
=> cast positional arguments to int

modules/features2d/misc/java/gen_dict.json, modules/features2d/misc/java/test/SIMPLEBLOBFeatureDetectorTest.java
- Remove SimpleBlobDetector class from class_ignore_list.
- Add SIMPLEBLOBFeatureDetectorTest.
=>  java: fix java SimpleBlobDetector

modules/photo/src/inpaint.cpp, modules/photo/test/test_inpaint.cpp
resolves #14722
Fixes bad indices tests and adds test to check that a simple inpaint is working as expected.
```
```
=> Bug fix 14722

modules/java/jar/CMakeLists.txt, modules/java/jar/build.xml.in, platforms/android/build_sdk.py
=> android: fix javadoc

samples/python/tutorial_code/imgProc/morph_lines_detection/morph_lines_detection.py
resolves #14751
Changed horizontal_size and verticalsize to integer division
=> Changed to integer division

samples/cpp/videocapture_gstreamer_pipeline.cpp
=> samples: skip findFile() in encoding mode

modules/core/include/opencv2/core/cvdef.h, modules/python/common.cmake, modules/python/src2/cv2.cpp
relates #8198
<cut/>
```
build_shared:Custom Mac=OFF
build_examples:Custom Mac=OFF
```
=> core: fix visibility handling

modules/objdetect/misc/java/test/QRCodeDetectorTest.java, modules/objdetect/misc/python/test/test_qrcode_detect.py, modules/objdetect/src/qrcode.cpp
Issue: [https://github.com/opencv/opencv/issues/14709](https://github.com/opencv/opencv/issues/14709)
=> Objdetect: QRCode detector - Mat assertion, added binding tests

modules/java/generator/gen_java.py
=> java: wrap StringIO() to support unicode strings

modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra:** opencv/opencv_extra#615
Related discussion: #14672 
```
docker_image:Custom=ubuntu-openvino-2019r1.0:16.04
```
=> Support Slice layer in ONNX importer

modules/imgcodecs/test/test_exr.impl.hpp, modules/imgcodecs/test/test_grfmt.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/618
relates #14725
=> imgcodecs(test): add OpenEXR I/O test

modules/imgcodecs/src/utils.cpp
The auto vectorizer misses some opportunities on the BGR2Gray functions.  Rewriting so that compiler does a better job - 2x speed up on Power8/9, 5% on x64.
=> Rewrite code in BGR2Gray functions so that auto vectorizer does a better job.

modules/dnn/misc/python/pyopencv_dnn.hpp, modules/flann/misc/python/pyopencv_flann.hpp, modules/python/bindings/CMakeLists.txt, modules/python/common.cmake, modules/python/python3/CMakeLists.txt, modules/python/src2/cv2.cpp, modules/python/src2/gen2.py, modules/python/src2/pycompat.hpp
Supersedes #14428 and  #14120
cmake option "PYTHON3_LIMITED_API" will enable limited API
=> Added cmake switch to enable limited python API (stage 3)

modules/dnn/misc/python/pyopencv_dnn.hpp, modules/flann/misc/python/pyopencv_flann.hpp, modules/python/bindings/CMakeLists.txt, modules/python/common.cmake, modules/python/python3/CMakeLists.txt, modules/python/src2/cv2.cpp, modules/python/src2/gen2.py, modules/python/src2/pycompat.hpp
=> Limited API support for Python3

modules/gapi/include/opencv2/gapi/core.hpp
Fix for https://github.com/opencv/opencv/issues/13713
=> G-API: Removed LUT3D API entry

modules/core/src/logger.cpp, modules/core/src/utils/logtagconfigparser.cpp, modules/core/src/utils/logtagconfigparser.hpp, modules/core/src/utils/logtagmanager.cpp
=> core: repair default log level

modules/imgcodecs/src/grfmt_tiff.cpp
=> (3.4) imgcodecs(tiff): add more checks

modules/core/src/convert.dispatch.cpp, modules/core/src/convert.simd.hpp, modules/core/src/convert_scale.simd.hpp
=> (3.4) core: avoid function type cast, make happy UBSAN

3rdparty/ffmpeg/ffmpeg.cmake
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/43
=> ffmpeg: update 3.4.6

modules/videoio/src/cap_images.cpp, platforms/scripts/valgrind.supp
resolves #14488
resolves #14765
=> valgrind: fix issues

platforms/scripts/valgrind.supp
[Weekly build](http://pullrequest.opencv.org/buildbot/builders/3_4_valgrind-lin64-debug/builds/87).
=> valgrind: suppress OpenEXR ThreadPool

modules/python/package/cv2/__init__.py
#resolves #14761
Change import statement. Otherwise it can not find the target.
=> Solve the import issue in Python2.

modules/gapi/cmake/standalone.cmake, modules/gapi/include/opencv2/gapi/gasync_context.hpp, modules/gapi/include/opencv2/gapi/gcompiled_async.hpp, modules/gapi/include/opencv2/gapi/gcomputation_async.hpp, modules/gapi/include/opencv2/gapi/own/cvdefs.hpp, modules/gapi/src/executor/gasync.cpp, modules/gapi/test/gapi_async_test.cpp
=> Cancelation support fo Async GAPI

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, platforms/android/build_sdk.py, platforms/android/service/engine/AndroidManifest.xml, platforms/android/service/engine/src/org/opencv/engine/OpenCVEngineService.java, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
=> pre: OpenCV 3.4.7 (version++)

modules/ts/misc/run_long.py, modules/videoio/src/cap_gstreamer.cpp, modules/videoio/test/test_gstreamer.cpp, modules/videoio/test/test_video_io.cpp, platforms/scripts/valgrind.supp, platforms/scripts/valgrind_3rdparty.supp
port #14834 into 4.x branch
<cut/>
```
#build_image:Custom=gstreamer0.10:16.04
```
=> videoio(gstreamer): port changes from #14834

modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/621
```
```
=> Support Eltwise3D on OCV backend 

samples/dnn/js_face_recognition.html
hotfix for https://github.com/opencv/opencv/pull/14737
Juat load utils.js as other samples do. Otherwise there is a error message 
```
GET https://docs.opencv.org/master/d5/d86/opencv.js net::ERR_ABORTED 404 (Not Found)
```
=> Fix face recognition sample for JS

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/version.hpp, modules/python/package/setup.py, modules/videoio/doc/videoio_overview.markdown, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
=> pre: OpenCV 4.1.1 (version++)

modules/dnn/perf/perf_caffe.cpp, modules/dnn/perf/perf_net.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_googlenet.cpp, modules/dnn/test/test_misc.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp, modules/objdetect/test/test_qrcode.cpp, modules/ts/src/ts.cpp
misused optional mode
<cut/>
```
```
=> dnn(test): fix usage of findDataFile()

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/622
dnn tensorflow support mirrorpad
```
```
=> dnn tensorflow support mirrorpad

modules/gapi/include/opencv2/gapi/render.hpp, modules/gapi/src/api/render.cpp, modules/gapi/test/gapi_render_test.cpp
=> G-API: Implement line and circle draw operations

samples/dnn/js_face_recognition.html
One more attempt to fix JS sample: https://github.com/opencv/opencv/pull/14864
=> Fix face recognition JS sample

modules/js/src/embindgen.py, modules/js/test/test_imgproc.js
Fixes: https://github.com/opencv/opencv/issues/14690
```
force_builders=Docs,Custom
```
=> js: added fillPoly() and fillConvexPoly()

samples/_winpack_build_sample.cmd
=> samples: support MSVS 2019 compiler (winpack)

modules/dnn/src/caffe/caffe_io.cpp
- ReadProtoFromTextFile
- ReadProtoFromTextBuffer
closes #14714
=> dnn: both protobuf readers have similar behavior

samples/dnn/js_face_recognition.html
Sorry for inconvenience. Now it should works.
```
```
=> Remove extra ")"

modules/core/src/kmeans.cpp, modules/imgproc/src/grabcut.cpp
=> imgproc: fix kmeans() call from grabCut()

modules/dnn/src/op_inf_engine.cpp
<cut/>
```
force_builders_only=linux,docs,Custom,Custom Win,Custom Mac
```
=> dnn: configure plugin path for InferenceEngine

modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/opencl/activations.cl, modules/dnn/test/test_halide_layers.cpp
https://github.com/BVLC/caffe/blame/1.0/src/caffe/layers/bnll_layer.cpp#L17
https://github.com/opencv/opencv/pull/14827#discussion_r296468934
Done:
=>  dnn: fix BNLL layer implementation

modules/dnn/src/op_inf_engine.hpp
=> dnn: adjust compilation options

modules/gapi/test/common/gapi_operators_tests.hpp, modules/gapi/test/common/gapi_operators_tests_inl.hpp, modules/gapi/test/cpu/gapi_operators_tests_cpu.cpp, modules/gapi/test/cpu/gapi_operators_tests_fluid.cpp, modules/gapi/test/gpu/gapi_operators_tests_gpu.cpp
updates operators tests according to new accuracy test model
=> G-API: Align operators tests to new test model

modules/gapi/test/common/gapi_imgproc_tests.hpp, modules/gapi/test/common/gapi_imgproc_tests_inl.hpp, modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp, modules/gapi/test/cpu/gapi_imgproc_tests_fluid.cpp, modules/gapi/test/gpu/gapi_imgproc_tests_gpu.cpp
updates imgproc accuracy tests according to new test model
=> G-API: Align imgproc tests to new model

samples/dnn/js_face_recognition.html
=> Final fix for JS sample of dnn

modules/dnn/src/layers/convolution_layer.cpp
=> dnn: fix build with Vulkan

modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp
=> Enable some tests for Inference Engine backend

cmake/templates/OpenCVConfig.cmake.in
=> cmake: normalize include directories in OpenCVConfig.cmake

modules/dnn/src/layers/max_unpooling_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
```
```
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/623
=> tensorflow support maxpoolgrad(MaxUnPool2d)

modules/calib3d/test/test_undistort.cpp, modules/imgproc/src/undistort.avx2.cpp
resolves #14467
Fixed initUndistortRectifyMap AVX2 implementation
=> Fixed initUndistortRectifyMap AVX2 implementation

modules/imgproc/test/ocl/test_color.cpp
=> fix test failure of OCL_ImgProc/CvtColor8u.mRGBA2RGBA

doc/py_tutorials/py_setup/py_setup_in_ubuntu/py_setup_in_ubuntu.markdown
=> Fix python setup in ubuntu dependencies

modules/videoio/src/backend_plugin.cpp
Fixed VideoWriter creation with empty filename for dynamic videoio backends
=> Fixed video writer filename check for plugins

modules/dnn/perf/perf_convolution3d.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp
Related: #13933 
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/630
```
#force_builders=Custom,Custom Win,Custom Mac
```
=> Support Conv3D on OCV backend

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/layers_common.cpp, modules/dnn/src/layers/layers_common.hpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra:** opencv/opencv_extra#632
```
```
=> Support Deconvolution3D on IE backend

modules/imgproc/src/filter.simd.hpp
resolves #14281
may cause crashes on ARM platform
```
```
=> imgproc: fix unaligned memory access

modules/imgproc/src/smooth.simd.hpp, modules/imgproc/test/test_smooth_bitexact.cpp
resolves #15015
Fix value evaluation overflow in bit-exact GaussianBlur
=> Fix value evaluation overflow in bit-exact GaussianBlur

CMakeLists.txt
=> cmake: disable WITH_NVCUVID by default due build failures

modules/imgproc/src/thresh.cpp
Reduce store gathering pressures - speeds thresholds by up to 20%.
=> Reduce store gathering pressures - speeds thresholds by up to 20%

modules/dnn/test/test_onnx_importer.cpp
Validated: https://ocv-power.imavr.com/#/builders/1/builds/3502
(broken build [example](https://ocv-power.imavr.com/#/builders/1/builds/3486))
=> dnn(test): fix required data

modules/gapi/test/cpu/gapi_core_tests_cpu.cpp, modules/gapi/test/cpu/gapi_core_tests_fluid.cpp, modules/gapi/test/gpu/gapi_core_tests_gpu.cpp
=> Fixed issue happened during merge

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
**Merge with extra:** opencv/opencv_extra#637
Related: #15056 
```
```
=> Fix TF Split layer

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp, modules/dnn/test/test_misc.cpp
=> Fix dumpToFile

modules/core/include/opencv2/core/persistence.hpp, modules/core/src/persistence.cpp, modules/core/src/persistence.hpp, modules/core/src/persistence_base64.cpp, modules/core/src/persistence_cpp.cpp, modules/core/src/persistence_json.cpp, modules/core/src/persistence_xml.cpp, modules/core/src/persistence_yml.cpp, modules/core/test/test_io.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/636
relates #14977
Align with OpenCV 4.x rewritten implementation.
Rework tests.
```
```
=> core(persistence): struct storage layout without alignment gaps

modules/videoio/src/cap_gstreamer.cpp, modules/videoio/test/test_video_io.cpp
resolves #15088
```
#build_image:Custom=gstreamer0.10:16.04
```
=> videoio(gstreamer): more .get() checks

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/layers_common.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp
Related: #14812 
**Merge with extra:** opencv/opencv_extra#634
```
```
=> Support ONNX "ReduceMean" Layer

modules/gapi/include/opencv2/gapi/garray.hpp, modules/gapi/include/opencv2/gapi/gtransform.hpp, modules/gapi/test/gapi_transform_tests.cpp
This pullrequest changes internal functions signatures and changes some tests
=> G-API: GAPI_TRANSFORM internal functionality rework

modules/core/src/persistence_json.cpp, modules/core/src/persistence_xml.cpp, modules/core/src/persistence_yml.cpp
resolves #15127
relates #13011
=> core(persistence): added null ptr checks

modules/js/src/embindgen.py
=> js: whitelist some more functions (calib3d , aruco)

modules/objdetect/src/cascadedetect.cpp, modules/objdetect/src/cascadedetect.hpp
resolves #15124
resolves #15125
=> objdetect: validate feature rectangle on reading

modules/dnn/test/test_caffe_importer.cpp, samples/dnn/face_detector/deploy_lowres.prototxt, samples/dnn/js_face_recognition.html
resolves https://github.com/opencv/opencv/issues/15106 after PR https://github.com/opencv/opencv/pull/10216
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/644
<cut/>
before:
with changes:
=> Fix false positives of face detection network for large faces

modules/core/include/opencv2/core/version.hpp
OpenCV 3.4.7
relates #14855
<cut/>
<details>
[opencv_world347.dll (vc14)](https://www.virustotal.com/gui/file/e425825339cd18d47d71370349c691f209b8878fec63d57b7a3f3acb94c4902c/detection)
[opencv_world347d.dll (vc14)](https://www.virustotal.com/gui/file/35f5c9c1b1a4d8bec4e58f395f8534f1017ce9d911f20cddce200281984e4015/detection)
[opencv_world347.dll (vc15)](https://www.virustotal.com/gui/file/5cc8b44a3ecf669e3d588c4e62ddd4ae51d239a012a546b72604966ba13ef43b/detection)
[opencv_world347d.dll (vc15)](https://www.virustotal.com/gui/file/e8193e3e522bd067efcc0378ba3148c73e2e888c875f0ff6654414802ba4b7f4/detection)
[opencv_ffmpeg347_64.dll](https://www.virustotal.com/gui/file/81a7f978895d6b03aa80d2359dc44825084f88c9b1ea44813e0242aa9ee6e1b9/detection) …
=> OpenCV version++ (3.4.7)

modules/dnn/misc/face_detector_accuracy.py, modules/dnn/misc/quantize_face_detector.py, modules/dnn/src/layers/detection_output_layer.cpp, samples/dnn/face_detector/deploy.prototxt, samples/dnn/face_detector/opencv_face_detector.pbtxt, samples/dnn/face_detector/test.prototxt, samples/dnn/face_detector/train.prototxt
try to solve issue #14841 
@dkurt
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/650
```
```
=> Add clip to deploy.prototxt

modules/core/src/matrix_operations.cpp, modules/core/src/mean.dispatch.cpp, modules/core/src/minmax.cpp, modules/core/src/sum.dispatch.cpp, modules/imgproc/src/box_filter.dispatch.cpp, modules/imgproc/src/corner.cpp, modules/imgproc/src/deriv.cpp, modules/imgproc/src/filter.dispatch.cpp, modules/imgproc/src/median_blur.dispatch.cpp, modules/imgproc/src/morph.dispatch.cpp, modules/imgproc/src/smooth.dispatch.cpp
resolves #15177
related #13085
Restore changes from PR #13085
=> Restored reduced IPP calls

modules/core/src/persistence.cpp
Fixes: https://github.com/opencv/opencv/issues/15187
=> core: fixed error message to avoid confusion

3rdparty/carotene/hal/tegra_hal.hpp
=> carotene: fix fall through warning

cmake/OpenCVModule.cmake, doc/js_tutorials/js_setup/js_setup/js_setup.markdown, modules/core/src/utils/datafile.cpp, modules/flann/include/opencv2/flann/dist.h, modules/highgui/src/roiSelector.cpp, modules/videoio/src/cap_ffmpeg.cpp, modules/videoio/src/cap_winrt/CaptureFrameGrabber.cpp
Backport PRs:
#15098
#15172
#15207
#15221
=> (3.4) backport PRs

modules/videoio/test/test_video_io.cpp
=> videoio(test): skip unstable MSMF tests (2)

modules/js/src/embindgen.py, modules/js/test/test_imgproc.js
=> in OpenCV.js added 'rotate' function and test sample

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/blank_layer.cpp, modules/dnn/src/layers/concat_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/layers/scale_layer.cpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/layers/softmax_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_ie_models.cpp, modules/dnn/test/test_misc.cpp
=> Support new IE API

modules/videoio/src/cap_ffmpeg_impl.hpp
resolves #8834
please refer [8834's issue comment](https://github.com/opencv/opencv/issues/8834#issuecomment-501975197)
```
```
=> try to fix VideoCapture different time stamp(issue 8834)

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/misc/python/test/test_dnn.py, modules/dnn/src/model.cpp
=> Add preprocessing wraps for separate parameters

modules/gapi/include/opencv2/gapi/infer.hpp
=> gapi: fix build with MSVS2017/2019

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/caffe/caffe_importer.cpp, modules/dnn/src/dnn.cpp, modules/dnn/src/model.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_ie_models.cpp
```
buildworker:Custom Win=windows-1
```
=> Determine input shapes

modules/gapi/CMakeLists.txt, modules/gapi/src/compiler/gmodel_priv.hpp, modules/gapi/src/compiler/passes/pattern_matching.cpp, modules/gapi/src/compiler/passes/pattern_matching.hpp, modules/gapi/test/common/gapi_core_tests_inl.hpp, modules/gapi/test/internal/gapi_int_pattern_matching_test.cpp
```
force_builders=Linux32,Win32,Custom Win
```
=> Graph pattern matching

modules/dnn/perf/perf_net.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
Merge after https://github.com/opencv/opencv/pull/15184
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/658
```
```
=> Enable some tests for 2019R2

modules/gapi/test/gapi_transform_tests.cpp
This pullrequest adds more tests on GAPI_TRANSFORM macro
=> G-API: Extend test suite on GAPI_TRANSFORM macro

modules/gapi/test/internal/gapi_int_pattern_matching_test.cpp
=>  Added one more Preproc use case test for graph pattern matching

modules/js/src/embindgen.py, modules/js/test/test_photo.js, platforms/js/build_js.py
In embindgen.py "photo" category added "inpaint" function.
```
```
=> in embindgen.py added inpaint function

modules/gapi/test/gapi_transform_tests.cpp
This pullrequest simplifies GAPI_TRANSFORM testing in some cases
=> Simplify tests on GAPI_TRANSFORM

samples/python/camshift.py
Fix #15148 
Replaced outdated link with the working link.
=> Fixed Typo Closes #15148

doc/py_tutorials/py_core/py_optimization/py_optimization.markdown
=> Fix a typo in python doc

doc/py_tutorials/py_feature2d/py_matcher/py_matcher.markdown
=> fix typo and reference

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/15296
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/661
=> Fix #15296

doc/tutorials/stitching/stitcher/stitcher.markdown
resolves  #15344
added proper link to the stiching.cpp file
=> fix broken code link

modules/core/src/persistence.cpp
Fix a typo. s/last_occurence/last_occurrence/
=> Fix a typo. s/last_occurence/last_occurrence/

CMakeLists.txt, cmake/OpenCVDetectCXXCompiler.cmake, cmake/OpenCVUtils.cmake, cmake/checks/atomic_check.cpp
=> cmake: add libatomic check

modules/imgproc/src/corner.avx.cpp, modules/ts/include/opencv2/ts/ts_gtest.h
=> build: fix build with ICC

modules/objdetect/src/hog.cpp
=> objdetect: add input check in HOG detector

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/15141
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/667
```
```
=> Fix #15141

modules/core/include/opencv2/core/hal/intrin_avx.hpp
Fix for AVX2 implementation of v_check_any(), v_check_all() intrinsics
=> Fix for AVX2 implementation of v_check_any(), v_check_all() intrinsics

modules/core/test/test_intrin_utils.hpp
Extend tests for v_check_any and v_check_all intrinsics to test #15400
=> Extend tests for v_check_any and v_check_all intrinsics

modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/test/test_halide_layers.cpp
=> Fix IE FullyConnected layer

modules/features2d/src/fast.cpp
Change fast corner flags in HAL version from char array to single int
=> Change fast corner flags in HAL version from char array to single int

modules/ts/src/ts.cpp
=> ts: fix callback function signature

modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp, modules/gapi/src/api/gbackend.cpp, modules/gapi/src/backends/fluid/gfluidbackend.cpp, modules/gapi/src/backends/fluid/gfluidbackend.hpp, modules/gapi/test/gapi_fluid_test.cpp, modules/gapi/test/gapi_fluid_test_kernels.cpp, modules/gapi/test/gapi_fluid_test_kernels.hpp
This pullrequest adds support for GArray as an input type in fluid
=> G-API: Support GArray as an input type in fluid

modules/gapi/src/backends/fluid/gfluidbackend.cpp
Simplified code a bit to make static analysis tool able to understand it
@dmatveev @alalek  please take a look
=> GAPI: make static analysis happy in Fluid Internal Parallelism

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, platforms/android/build_sdk.py, platforms/android/service/engine/AndroidManifest.xml, platforms/android/service/engine/src/org/opencv/engine/OpenCVEngineService.java, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
=> pre: OpenCV 3.4.8 (version++)

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/version.hpp, modules/python/package/setup.py, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
=> pre: OpenCV 4.1.2 (version++)

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/const_layer.cpp, modules/dnn/src/layers/crop_and_resize_layer.cpp, modules/dnn/src/layers/detection_output_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/15023
resolves https://github.com/opencv/opencv/issues/15325
```
```
=> Wrap OpenCV layers as custom CPU layers with IE backend

modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp, modules/gapi/src/backends/fluid/gfluidbackend.cpp
as a follow -up for #15091 
@dmatveev please take a look
```
```
=> Fluid Internal Parallelism:

3rdparty/ffmpeg/ffmpeg.cmake
=> ffmpeg/3.4: update FFmpeg wrapper

3rdparty/ffmpeg/ffmpeg.cmake
ffmpeg: 4.1.3 -> 4.2.1
libvpx: 1.8.0 -> 1.8.1
```
```
=> ffmpeg/4.x: update FFmpeg plugin

modules/dnn/src/dnn.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/15472
```
```
=> Fix OpenVINO 2019R1 compilation

modules/calib3d/test/test_undistort.cpp, modules/imgproc/src/undistort.simd.hpp
resolves #15286
Fixed universal intrinsic undistort() implementation
=> Fixed universal intrinsic undistort() implementation

modules/calib3d/perf/perf_stereosgbm.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/670
Added performance test for StereoBM algorithm
=> Added performance test for StereoBM algorithm

modules/video/src/dis_flow.cpp
resolves #15481
Fixed out of bound reading in DIS optical flow evaluation implementation
=> Fixed out of bound reading in DIS optical flow evaluation implementation

samples/dnn/object_detection.cpp, samples/dnn/object_detection.py
Fix out of [0, 1] object detection predictions. See https://github.com/opencv/opencv/pull/15515
=> Fix dnn object detection sample

3rdparty/libpng/patches/20190910-msa-patch.diff, 3rdparty/libwebp/patches/20190910-msa-asm-patch.diff
relates #15422
Excluded by mistake from PR patch set.
=> 3rdparty patch files for PR #15422

modules/imgcodecs/src/grfmt_tiff.cpp, modules/imgcodecs/src/loadsave.cpp
=> imgcodecs: add check image.empty() in imwrite()/imencode()

modules/ml/src/ann_mlp.cpp, modules/ml/src/boost.cpp, modules/ml/src/em.cpp, modules/ml/src/inner_functions.cpp, modules/ml/src/knearest.cpp, modules/ml/src/lr.cpp, modules/ml/src/nbayes.cpp, modules/ml/src/rtrees.cpp, modules/ml/src/svm.cpp, modules/ml/src/svmsgd.cpp, modules/ml/src/tree.cpp, modules/ml/test/test_lr.cpp, modules/ml/test/test_mltests2.cpp
=> ml: add checks of empty train data

platforms/ios/build_framework.py
Currently it is possible to disable full modules in an iOS build, but not possible to disable features (WITH_* variables in cmake).
With this change it is possible to do that.
=> Add option to disable features in iOS build.

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/convolution_layer.cpp
=> Fix computation of internal shapes in Deconvolution layer

modules/imgproc/src/pyramids.cpp
resolves #15562
Fixed OOB reading in pyrDown
=> Fixed OOB reading in pyrDown

modules/core/src/ocl.cpp
to control CL_MEM_USE_HOST_PTR usage
work around for #6293 #15574
=> core(OpenCL): add flag OPENCV_OPENCL_ENABLE_MEM_USE_HOST_PTR

modules/imgproc/src/pyramids.cpp
UBSAN violation expression: `tab = tabR - x;`
=> imgproc: fix indexing issue in pyramids

modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qrcode.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/672
=> QR-Code detection: accuracy improvement

modules/js/src/embindgen.py, modules/js/test/test_calib3d.js, modules/js/test/test_imgproc.js
* js
* cv.stimateAffine2D and cv.warpPolar
* test
* I verified it doesn't add relevant increase on the build size
```
```
=> js - cv.estimateAffine2D, cv.warpPolar

modules/gapi/CMakeLists.txt, modules/gapi/include/opencv2/gapi/render.hpp, modules/gapi/src/api/render.cpp, modules/gapi/src/api/render_ocv.cpp, modules/gapi/src/api/render_ocv.hpp, modules/gapi/src/api/render_priv.hpp, modules/gapi/test/common/gapi_render_tests.hpp, modules/gapi/test/common/gapi_render_tests_inl.hpp, modules/gapi/test/cpu/gapi_render_tests_cpu.cpp
=> G-API: Add new render primitives

modules/core/src/matmul.dispatch.cpp
=> core: workaround transform() inplace calls

cmake/OpenCVFindIPPIW.cmake
=> cmake: add check for IPP IW license files

modules/objdetect/src/qrcode.cpp
=> QR-Code detection: accuracy improvement (fixed)

modules/imgproc/misc/java/test/ImgprocTest.java, modules/imgproc/src/linefit.cpp, modules/imgproc/test/test_convhull.cpp
- update optimal solutions on each iteration
resolves #15083
resolves #4903
=> imgproc: fix fitLine() implementation

modules/dnn/misc/python/test/test_dnn.py, modules/dnn/test/test_model.cpp
Avoid failures of [these tests](https://ocv-power.imavr.com/#/builders/1/builds/4826).
=> dnn(test): fix optional test data

modules/dnn/misc/python/test/test_dnn.py
=> dnn(pytest): backport changes from master, update test setUp()

modules/imgproc/src/histogram.cpp, modules/imgproc/test/test_histograms.cpp
=> imgproc: accurate histogram value thresholding

modules/gapi/test/util/any_tests.cpp
Added tests:
- get_ref_to_val_from_any
- update_val_via_ref
=> Add a few more tests on `any`

modules/gapi/test/common/gapi_tests_common.hpp
=> G-API: Fix valgrind issue in draw::render

modules/core/include/opencv2/core/version.hpp
relates #15436
<cut/>
<details>
[opencv_world412.dll (vc14)](https://www.virustotal.com/gui/file/5f344deca071a1d2695f4a5b7781fc1a905afe6e65c4702cf5fe02dd057923a7/detection)
[opencv_world412d.dll (vc14)](https://www.virustotal.com/gui/file/837098e5024497b03137dfae6f91935bd190692106d3f9b22d1a9a54925fc565/detection)
[opencv_world412.dll (vc15)](https://www.virustotal.com/gui/file/e6fe1b5d8ce9d2968f279e11161f56423094d47e2fba7a1f247ea9b33a9b98a4/detection)
[opencv_world412d.dll (vc15)](https://www.virustotal.com/gui/file/08d057e71867f0d558cc024fe13eb6e61d38df17614cf3cb21a59a4c8a00b4b7/detection)
[opencv_videoio_ffmpeg412_64.dll](https://www.virustotal.com/gui/file/da64038314295b631c3ede7cb4055c96faa88cd15aa7a054a2faf5c685fe90ea/detection) …
=> release: OpenCV 4.1.2

modules/core/src/parallel.cpp
This ensures uniform behavior on any C++11 compliant compiler and silences clang's Thread Sanitizer concerns that above block might not be thread safe.
=> Use atomic operations to modify flagNestedParallelFor

modules/core/src/alloc.cpp
resolves #15691
- before main() launch
relates #15544
=> core(alloc): force initialization of memalign flag

modules/imgproc/include/opencv2/imgproc.hpp
=> document CC_STAT_MAX in ConnectedComponentsTypes

cmake/platforms/OpenCV-WindowsPhone.cmake, cmake/platforms/OpenCV-WindowsStore.cmake
=> cmake: fix UWP scripts path

modules/python/test/test_misc.py, samples/dnn/fast_neural_style.py, samples/dnn/mobilenet_ssd_accuracy.py, samples/dnn/text_detection.py, samples/dnn/tf_text_graph_common.py, samples/dnn/tf_text_graph_ssd.py, samples/python/browse.py, samples/python/calibrate.py, samples/python/camera_calibration_show_extrinsics.py, samples/python/color_histogram.py, samples/python/edge.py, samples/python/facedetect.py, samples/python/fitline.py, samples/python/houghcircles.py, samples/python/houghlines.py, samples/python/kmeans.py, samples/python/lappyr.py, samples/python/opt_flow.py, samples/python/peopledetect.py, samples/python/stereo_match.py, samples/python/turing.py, samples/python/tutorial_code/core/mat_operations/mat_operations.py, samples/python/tutorial_code/imgProc/changing_contrast_brightness_image/changing_contrast_brightness_image.py, samples/python/tutorial_code/ml/introduction_to_pca/introduction_to_pca.py, samples/python/video_threaded.py, samples/python/video_v4l2.py
Pylint 1.8.3 result (Ubuntu 18.04):
```
TOTAL : 157
PASSED: 131
ERRORS: 26
```
=> Fix Pylint warnings

modules/core/include/opencv2/core/hal/intrin_wasm.hpp
relates #15371
```
buildworker:Docs=linux-1
```
=> JS(SIMD): support Emscripten 1.38.48-upstream

modules/core/include/opencv2/core/hal/intrin_wasm.hpp
relates #15662 #15371
```
buildworker:Docs=linux-1
```
=> JS(SIMD): v_reverse implementation

modules/calib3d/src/stereobm.cpp
StereoBM algorithm updated to use wide universal intrinsics
=> StereoBM implementation WUI update

modules/core/include/opencv2/core/hal/intrin_msa.hpp
resolves #15705
```
force_builders=docs,Custom
```
=> core(SIMD): v_reverse() for MSA backend

cmake/OpenCVFindMKL.cmake
=> OpenCVFindMKL: Fix a typo

modules/imgproc/include/opencv2/imgproc.hpp, samples/cpp/intersectExample.cpp
I expanded the documentation for `intersectConvexConvex` and added a sample program illustrating its use.
```
force_builders_only=Linux x64,Docs
```
=> Add documentation and example program for intersectConvexConvex

doc/py_tutorials/py_gui/py_table_of_contents_gui.markdown, doc/py_tutorials/py_gui/py_video_display/py_video_display.markdown
Grammar errors in the python tutorials gui section, specifically the table of contents and the video page.
=> grammar corrections for python gui docs

modules/highgui/src/precomp.hpp
incorrect imshow behaviors
resolves #15745
=> fix incorrect imshow behavior

modules/gapi/include/opencv2/gapi/gasync_context.hpp, modules/gapi/include/opencv2/gapi/gcompiled_async.hpp, modules/gapi/include/opencv2/gapi/gcomputation_async.hpp, samples/dnn/object_detection.cpp
(here  #14346 #14492 is the object of documentation )
@dmatveev, @dbudniko  please take a look
=> G-API: Doxygen documentatation for Async API

modules/dnn/src/dnn.cpp, modules/dnn/test/test_darknet_importer.cpp
resolves https://github.com/opencv/opencv/issues/15750
```
```
=> Fix custom IE layers in case of no MKLDNN plugin

modules/imgproc/src/demosaicing.cpp
Convert demosaic functions to HAL (2.6x faster for VSX).
Added bayerRGBA to vectorized functions (missing from x86) - plus added alpha to parameter list.
Leaving NEON code in since it has much better instructions for interleaving data - plus added HAL bayerRGB_EA for NEON.
```
force_builders=linux,docs,Custom,Linux AVX2,ARMv7
```
=> Convert demosaic functions to HAL (2.6x faster for VSX)

modules/core/src/trace.cpp
`OPENCV_TRACE_ITT_ENABLE=true` by default.
=> core(trace): add ITT control parameter

modules/calib3d/src/fisheye.cpp
=> Fixed typo in assertion

modules/gapi/include/opencv2/gapi/own/mat.hpp
=> add own::Mat empty implementation

modules/gapi/CMakeLists.txt
=> GAPI: fix opencv_world build

modules/core/misc/java/src/java/core+Mat.java, modules/core/misc/java/test/MatTest.java, modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java, modules/java/generator/src/cpp/Mat.cpp
resolves #14915
TODO:
Android build package for testing is [here](http://pullrequest.opencv.org/buildbot/builders/precommit_pack_android/builds/11136).
```
force_builders_only=Android pack
```
=> android: use .getRowStride() in JavaCamera2View

modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp, modules/gapi/src/backends/fluid/gfluidbackend.cpp, modules/gapi/src/backends/fluid/gfluidbackend.hpp, modules/gapi/src/backends/fluid/gfluidimgproc.cpp
=> GAPI Fluid: Dynamic window size

modules/calib3d/src/stereosgbm.cpp
resolves #15206
StereoSGBM algorithm updated to use wide universal intrinsics
```
disable_ipp=ON
```
=> StereoSGBM algorithm updated to use wide universal intrinsics

samples/cpp/stereo_match.cpp
Signed-off-by: Connor James Smith <cjs.connor.smith@gmail.com>
- OpenCV => opencv-4.1.2-dev
- Operating System / Platform => Windows 10/ x86_64
- Compiler => mingw64 ver 8.1.0
resolves #15779
Since the original issue didn't have the information, I was able to confirm the bug existed on my setup. I tested the proposed fix with the stock sample images.
=> Changes disparity image to float representation

doc/tutorials/core/basic_linear_transform/basic_linear_transform.markdown, doc/tutorials/core/how_to_scan_images/how_to_scan_images.markdown, doc/tutorials/core/mat-mask-operations/mat_mask_operations.markdown, doc/tutorials/core/mat_the_basic_image_container/mat_the_basic_image_container.markdown, modules/core/include/opencv2/core/saturate.hpp
* Fix some mistakes;
* Some grammar corrections.
=> Fix wording in some tutorials

modules/python/test/test_cuda.py, samples/python/dis_opt_flow.py, samples/python/stitching.py, samples/python/stitching_detailed.py
relates https://github.com/opencv/opencv/pull/15718
```
```
=> pylint: eliminate warnings

modules/python/src2/gen2.py
resolves #15833
fix format string in gen2.py
=> python: fix type error msg

modules/cudaoptflow/src/pyrlk.cpp
resolves https://github.com/opencv/opencv_contrib/issues/2323
This PR corrects a typo as can be seen.
PS - No PR referred the above issue and no one has made any PR related to it since the issue was created. Please close this if any other person is working on it.
=> Removed a minor typo

modules/core/src/persistence_json.cpp, modules/core/src/persistence_xml.cpp
resolves #15857
relates #13011
=> core(persistence): add more checks for implementation limitations

modules/core/test/test_io.cpp
- added removal of temporary file
backport #15842 #15851 (test)
=> core(test): add test for YAML parse multiple documents

doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown, doc/py_tutorials/py_core/py_image_arithmetics/py_image_arithmetics.markdown, doc/py_tutorials/py_core/py_optimization/py_optimization.markdown
- Basic Operations on Images
- Arithmetic Operations on Images
- Performance Measurement and Improvement Techniques
=> Grammar fixes for python core operations docs

cmake/OpenCVCompilerOptions.cmake
resolves #15886
```
build_shared:Custom Win=OFF
```
=> cmake: set _WIN32_WINNT for Windows 7 API

modules/imgproc/src/distransform.cpp
=> imgproc(IPP): disable ippiDistanceTransform_3x3_8u32f_C1R

3rdparty/protobuf/CMakeLists.txt, cmake/OpenCVUtils.cmake, modules/calib3d/src/solvepnp.cpp, modules/calib3d/src/upnp.cpp, modules/calib3d/src/upnp.h, modules/core/include/opencv2/core/persistence.hpp, modules/core/src/persistence_cpp.cpp, modules/highgui/src/window_gtk.cpp, modules/imgproc/src/fixedpoint.inl.hpp
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/2347
```
build_image:Custom=fedora:31
```
=> build: GCC9 compilation

modules/imgproc/src/demosaicing.cpp
Convert demosiacing with variable number of gradients to HAL - 5.5x faster
```
disable_ipp=ON
```
=> Convert demosiacing with variable number of gradients to HAL

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp, modules/gapi/samples/face_beautification.cpp, modules/gapi/src/backends/ie/giebackend.cpp, modules/gapi/src/backends/ie/giebackend.hpp
- A new G-API sample that processes real-time face beautification pipeline is added. This is a Face Beautification algorithm implemented via G-API.
The sample shows the usage of G-API applying to a real CV problem. The G-API features used in the sample:
- Networks inference INSIDE G-API (used two IE models: face detector (face-detection-adas-0001) and facial landmarks detector (facial-landmarks-35-adas-0002))
- Custom CPU (OpenCV) kernels implementation
- Brand new Streaming-API to process a videostream source INSIDE G-API
- FIXME added in 'gcpukernel.hpp'
``` …
```
=> Introducing the sample of Face Beautification algorithm implemented via Graph-API

modules/js/test/test_features2d.js
relates #15855
Fixes [nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_javascript-emscripten-lin64/builds/570).
```
```
=> js(test): update features2d test

modules/dnn/src/op_inf_engine.cpp
=> dnn: update InferenceEngine extension handling

modules/core/include/opencv2/core/hal/intrin.hpp, modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/test/test_intrin.cpp, modules/core/test/test_intrin_emulator.cpp
```
build_image:Custom=fedora:31
```
=> core(test): extending tests with SIMD C++ emulation code (intrin_cpp.hpp)

modules/core/include/opencv2/core/hal/intrin_msa.hpp
Fixes [nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_mips-msa-lin64/builds/56).
```
```
=> core: fix MSA build

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, doc/tutorials/introduction/documenting_opencv/documentation_tutorial.markdown, doc/tutorials/introduction/windows_install/windows_install.markdown
Update broken links to Doxygen website.
`force_builders_only=Docs`
=> Update links to Doxygen website

modules/dnn/src/tensorflow/tf_importer.cpp, samples/dnn/tf_text_graph_ssd.py
resolves https://github.com/opencv/opencv/issues/15863
might also resolve https://github.com/opencv/opencv/issues/15979
=> FusedBatchNormV3 from TensorFlow

doc/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.markdown, doc/py_tutorials/py_imgproc/py_filtering/py_filtering.markdown, doc/py_tutorials/py_imgproc/py_geometric_transformations/py_geometric_transformations.markdown, doc/py_tutorials/py_imgproc/py_thresholding/py_thresholding.markdown
Note: I capitalized "Gaussian" in multiple instances because this term refers to a person's name. I am open to reversing this, however. Here is a discussion about a similar issue: https://english.stackexchange.com/questions/4481/should-the-word-boolean-be-capitalized
=> grammar corrections

doc/js_tutorials/js_gui/js_trackbar/js_trackbar.markdown, doc/py_tutorials/py_gui/py_trackbar/py_trackbar.markdown, doc/py_tutorials/py_ml/py_knn/py_knn_opencv/py_knn_opencv.markdown, doc/tutorials/imgproc/random_generator_and_text/random_generator_and_text.markdown, modules/core/include/opencv2/core/hal/msa_macros.h, modules/imgproc/test/test_watershed.cpp
=> (3.4) Fix some typos (backport #15995)

modules/gapi/include/opencv2/gapi/infer/ie.hpp, modules/gapi/src/backends/ie/giebackend.cpp, samples/cpp/tutorial_code/gapi/age_gender_emotion_recognition/age_gender_emotion_recognition.cpp, samples/cpp/tutorial_code/gapi/security_barrier_camera/security_barrier_camera.cpp
This samples are simplified versions of their "Open Model Zoo" counterparts.
Also added CPU extensions library to IE plugins (now detectors can work safely with "CPU" target).
Tested with OpenVINO R3 2019.
<cut/>
```
```
=> G-API: Introduced Security Barrier & Interactive Face Detection samples

cmake/templates/opencv_abi.xml.in, modules/core/include/opencv2/core/hal/intrin.hpp, modules/core/include/opencv2/core/hal/simd_utils.impl.hpp, modules/core/test/test_intrin_utils.hpp
relates #15541
```
disable_ipp=ON
```
=> core(simd): v_setall template

modules/ml/src/svm.cpp
=> ml: fix check in SVM::trainAuto

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/opencl/activations.cl, modules/dnn/test/test_halide_layers.cpp
Port https://github.com/opencv/opencv/pull/15808 to 3.4 branch
```
```
=> Port Swish and Mish layers

modules/core/src/system.cpp
resolves #16041
- required to unregister callbacks from system
=> core(tls): unblock TlsAbstraction destructor call

modules/dnn/src/caffe/caffe_importer.cpp, modules/dnn/src/dnn.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_ie_models.cpp
backport for https://github.com/opencv/opencv/pull/15203
```
```
=> Determine input shapes in dnn

modules/calib3d/misc/java/test/Calib3dTest.java, modules/calib3d/misc/python/test/test_solvepnp.py, modules/calib3d/src/solvepnp.cpp, modules/core/src/norm.cpp
=>  calib3d: use normalized input in solvePnPGeneric()

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/python/package/setup.py, platforms/android/build_sdk.py, platforms/android/service/engine/AndroidManifest.xml, platforms/android/service/engine/src/org/opencv/engine/OpenCVEngineService.java, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
~2 weeks left to release
previous PR with version bump: #15435
=> pre: OpenCV 3.4.9 (version++)

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/python/package/setup.py, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
previous PR with version bump: #15436
=> pre: OpenCV 4.2.0 (version++)

modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/src/layers/slice_layer.cpp
=> Support nGraph Slice v1 op

cmake/OpenCVUtils.cmake, modules/gapi/CMakeLists.txt
=> G-API: update CMakeLists.txt, fix TBB dependency handling

modules/imgproc/src/thresh.cpp, modules/imgproc/test/test_thresh.cpp
=> imgproc(IPP): wrong result from threshold(THRESH_TOZERO)

modules/dnn/src/layers/detection_output_layer.cpp
=> Remove Dummy layer (nGraph)

modules/dnn/src/op_inf_engine.cpp
resolves https://github.com/opencv/opencv/issues/16060
```
```
=> Fix FPGA dnn target with HETERO plugin of IE backend

modules/dnn/src/layers/convolution_layer.cpp
=> Modify nGraph's ConvolutionBackpropData and GroupConvolution

modules/imgproc/src/histogram.cpp, modules/imgproc/test/test_histograms.cpp
Added:
* checks for empty and invalid images array
* checks for invalid ranges array
* test
=> imgproc: add parameter checks in calcHist and calcBackProj

modules/imgproc/include/opencv2/imgproc.hpp
Resubmission of https://github.com/opencv/opencv/pull/16119
=> imgproc: fix Voronoi typo

modules/gapi/include/opencv2/gapi/render/render.hpp
=> G-API: Add default initialization for primtitives

modules/core/include/opencv2/core/cvdef.h
=> core: add "namespace cv" in CV_StaticAssert fallback implementation

modules/core/include/opencv2/core/cvdef.h
=> core: provide safe implementations of CV_XADD() only

modules/gapi/src/api/render_ocv.cpp, modules/gapi/test/common/gapi_render_tests.cpp, modules/gapi/test/render/gapi_render_tests_ocv.cpp
=> G-API: Mosaic handle corner cases

doc/py_tutorials/py_gui/py_trackbar/py_trackbar.markdown
=> fix wrong method name

doc/py_tutorials/py_feature2d/py_brief/py_brief.markdown
resolves #14093
the py_brief.markdown file and adds a description of the STAR feature detector
=> (doc): added info about STAR

modules/dnn/test/test_model.cpp
=> dnn(test): fix Test_Model.Keypoints* tests

modules/calib3d/src/calibration.cpp
=> calib3d: clarify error messages in collectCalibrationData()

modules/dnn/src/cuda/math.hpp, modules/dnn/src/cuda/roi_pooling.cu, modules/dnn/src/cuda4dnn/kernels/roi_pooling.hpp, modules/dnn/src/cuda4dnn/primitives/roi_pooling.hpp, modules/dnn/src/layers/pooling_layer.cpp
- adds ROI pooling layer to the CUDA backend
<cut/>
```
```
=> add ROI pooling layer to the CUDA backend

modules/imgproc/src/resize.cpp
relates #15257 #16189
Fix for CV_8UC2 linear resize vectorization
=> Fix for CV_8UC2 linear resize vectorization

modules/cudabgsegm/src/cuda/mog2.cu, modules/cudabgsegm/src/cuda/mog2.hpp, modules/cudabgsegm/src/mog2.cpp
resolves #5296
These modifications allow a cv::cuda::BackgroundSubtractorMOG2 instance to be unaffected by another created with different parameters.
```
```
=> cuda_mog2_issue_5296

modules/imgproc/src/resize.cpp, modules/imgproc/test/test_imgwarp.cpp
resolves #16192
relates #16193 #16189
```
```
=> imgproc: fix resize LANCZOS4 coefficients generation

modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java
=> android(camera2): apply .disconnectCamera() patch from issue 13574

doc/tutorials/introduction/macOS_install/macOS_install.markdown, doc/tutorials/introduction/macos_install/macos_install.markdown, doc/tutorials/introduction/table_of_content_introduction.markdown
resolves #13822
a macOS installation guide based on the current linux installation guide.
=> Mac os install

modules/core/include/opencv2/core/version.hpp
OpenCV 3.4.9
relates #16071
<cut/>
<details>
[opencv_world349.dll (vc14)](https://www.virustotal.com/gui/file/154ab640fcdd34a18933139ecab562ee5d652a03ed4b725adb2b33a4dd8f9c0f/detection)
[opencv_world349d.dll (vc14)](https://www.virustotal.com/gui/file/f9b5cb4cc0711501e88bd3625a23e582b86ea67bd58be57e64a25dab0cc878d0/detection)
[opencv_world349.dll (vc15)](https://www.virustotal.com/gui/file/bc2e4c49b1ef435fd55917663252b9ae8d43916e9c9af2f0373c60002b8c3f30/detection)
[opencv_world349d.dll (vc15)](https://www.virustotal.com/gui/file/bc66cdd0df1dd1804dd76864b2395df47a359f23dd913b3a3437ab1ce9d44406/detection)
[opencv_ffmpeg349_64.dll](https://www.virustotal.com/gui/file/9b2ff69ed1a4988a93eea3296e93c755d729254ebee85716bd6cf270d6376b58/detection) …
=> release: OpenCV 3.4.9

doc/py_tutorials/py_feature2d/py_features_harris/py_features_harris.markdown
=> grammar and readability improvements

modules/java/android_sdk/android_lib/.settings/org.eclipse.jdt.core.prefs, modules/java/test/android_test/.settings/org.eclipse.jdt.core.prefs, samples/android/15-puzzle/.settings/org.eclipse.jdt.core.prefs, samples/android/camera-calibration/.settings/org.eclipse.jdt.core.prefs, samples/android/color-blob-detection/.settings/org.eclipse.jdt.core.prefs, samples/android/face-detection/.settings/org.eclipse.jdt.core.prefs, samples/android/image-manipulations/.settings/org.eclipse.jdt.core.prefs, samples/android/tutorial-1-camerapreview/.settings/org.eclipse.jdt.core.prefs, samples/android/tutorial-2-mixedprocessing/.settings/org.eclipse.jdt.core.prefs, samples/android/tutorial-3-cameracontrol/.settings/org.eclipse.jdt.core.prefs, samples/android/tutorial-4-opencl/.settings/org.eclipse.jdt.core.prefs
It simply removes from old Eclipse project the settings, which are obsolete in Android Studio
=> Android remove Eclipse relicts

cmake/OpenCVUtils.cmake, samples/opencl/opencl-opencv-interop.cpp
<cut/>
```
build_image:Custom=fedora:31
```
=> build: eliminate build warnings

modules/dnn/src/tensorflow/tf_importer.cpp, samples/dnn/tf_text_graph_ssd.py
resolves https://github.com/opencv/opencv/issues/15817
=> AddV2 from TensorFlow

modules/calib3d/src/calibration.cpp, modules/core/include/opencv2/core/check.hpp, modules/core/src/check.cpp, modules/core/test/test_misc.cpp
relates #16242
partially backported: #12668
=> core(check): add Size_<int>

modules/core/src/ovx.cpp
=> Fixed compilation on windows with openvx

modules/objdetect/misc/python/test/test_qrcode_detect.py
When dealing with PATH, it is not recommended to use the plus operator (+). So, I used os.path.join().
=> Changed plus operator to os.path.join()

modules/core/include/opencv2/core/hal/intrin.hpp, modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/src/arithm.cpp, modules/core/src/arithm.simd.hpp, modules/core/src/lapack.cpp, modules/core/src/mathfuncs_core.simd.hpp, modules/core/test/test_intrin_emulator.cpp, modules/core/test/test_intrin_utils.hpp, modules/features2d/src/fast_score.cpp, modules/imgproc/src/corner.avx.cpp
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/2403
Usage:
```
cmake -DOPENCV_EXTRA_FLAGS="-DCV_FORCE_SIMD128_CPP=1" ...
```
<cut/>
```
#test_timeout:Linux x64 Debug=1200
#test_maxtime:Linux x64 Debug=14400
```
=> core: fix simd emulator code

doc/tutorials/video/meanshift/meanshift.markdown, doc/tutorials/video/optical_flow/optical_flow.markdown, doc/tutorials/video/table_of_content_video.markdown, samples/java/tutorial_code/video/meanshift/CamshiftDemo.java, samples/java/tutorial_code/video/meanshift/MeanshiftDemo.java, samples/java/tutorial_code/video/optical_flow/OpticalFlowDemo.java, samples/java/tutorial_code/video/optical_flow/OpticalFlowDenseDemo.java
The java version of the tutorial of [Meanshift](https://docs.opencv.org/master/d7/d00/tutorial_meanshift.html) and [Optical Flow](https://docs.opencv.org/master/d4/dee/tutorial_optical_flow.html) was not present . This Pull Request is to add the java versions of the tutorials
=> Added java code for meanshift and optical_flow

samples/python/digits.py, samples/python/digits_video.py
=> ml/python: fix digits samples(3.4)

modules/dnn/src/layers/normalize_bbox_layer.cpp
=> Enable acrossSpatial normalizeL2 on Myriad

modules/photo/src/seamless_cloning_impl.cpp
resolves #16168
cvtColor function to the computeGradient functions to make it more efficient.
=> Compute gradient x

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
=> Fix uninitialized value
