opencv/opencv

modules/java/generator/android/java/org/opencv/android/CameraActivity.java
modules/java/generator/android/java/org/opencv/android/CameraBridgeViewBase.java
samples/android/15-puzzle/src/org/opencv/samples/puzzle15/Puzzle15Activity.java
samples/android/camera-calibration/src/org/opencv/samples/cameracalibration/CameraCalibrationActivity.java
samples/android/color-blob-detection/src/org/opencv/samples/colorblobdetect/ColorBlobDetectionActivity.java
samples/android/face-detection/src/org/opencv/samples/facedetect/FdActivity.java
samples/android/image-manipulations/src/org/opencv/samples/imagemanipulations/ImageManipulationsActivity.java
samples/android/tutorial-1-camerapreview/src/org/opencv/samples/tutorial1/Tutorial1Activity.java
samples/android/tutorial-2-mixedprocessing/src/org/opencv/samples/tutorial2/Tutorial2Activity.java
samples/android/tutorial-3-cameracontrol/src/org/opencv/samples/tutorial3/Tutorial3Activity.java

* Add `CameraActivity` class to request Camera permission when required
* Update Android samples to derive from this class instead of `Activity`
* Make additional changes to samples that enable/disable menu options based on camera capabilities such that the menu option processing only occurs after the camera permissions have been granted and the camera has started
Tested on
* Lollipop (permission request dialog not required)
* Pie (permission request dialog required)

Add CameraActivity utility class to automate Camera permission handling on Android

---

modules/core/src/matmul.simd.hpp

Unroll multiply and add instructions (absorb latencies) into separate accumulators in dotProd_32f - 35% faster.

Unroll multiply and add instructions in dotProd_32f

---

modules/core/include/opencv2/core/version.hpp

relates #14861
<cut/>
<details>
[opencv_world411.dll (vc14)](https://www.virustotal.com/gui/file/9407bea21800a271e0e2d8029dcd4c9ede754f9ddea6d22bdfbae5c53d9b299c/detection) (1 detection, [considered false positive](https://stackoverflow.com/questions/54052224/virustotal-trapmine-suspicious-low-ml-score) - 2019-07-26)
[opencv_world411d.dll (vc14)](https://www.virustotal.com/gui/file/9a5bf11687a6d704f7cfa6ac4fac3b80bc18d9b5a178afb3bc4a3a6f865796ce/detection) (1 detection, [considered false positive](https://stackoverflow.com/questions/54052224/virustotal-trapmine-suspicious-low-ml-score) - 2019-07-26)
[opencv_world411.dll (vc15)](https://www.virustotal.com/gui/file/27b406d9d2c1985375f698c564382bd64f23ffa42e58d0974320acdbf8ddfd45/detection) …

release: OpenCV 4.1.1

---

modules/core/misc/java/src/java/core+Mat.java

see #12520 or #10802
resolve some confusion from toString(), where Mat's with more than 2 dims (e.g.: dnn blobs) would show up like `[-1*-1*CV_32F` in the output.
expected outcome:
```
Mat m = new Mat(20,22,CvType.CV_32F);
[java] Mat [ 20*22*CV_32FC1, ....]
```
```
int siz[] = {1,2,3,4,5};
Mat m = new Mat(siz,CvType.CV_32F);
[java] Mat [ 1*2*3*4*5*CV_32FC1, ....]
```

java: fix Mat.toString() for higher dimensions

---

modules/dnn/test/test_onnx_importer.cpp

-528MB of tests data
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/652
VGG16_bn from ONNX is the same as VGG16 but with extra batch normalizations:
<details><summary>VGG16_bn</summary>
```
Conv
dilation : 1, 1
group : 1
kernel_size : 3, 3
pad : 1, 1, 1, 1
stride : 1, 1
BatchNormalization
epsilon : 1e-05
momentum : 0.9
spatial : 0
Relu
Conv
dilation : 1, 1
group : 1
kernel_size : 3, 3
pad : 1, 1, 1, 1
stride : 1, 1
BatchNormalization
epsilon : 1e-05
momentum : 0.9
spatial : 0
Relu
MaxPool
kernel_size : 2, 2
pad : 0, 0, 0, 0
stride : 2, 2
Conv
dilation : 1, 1
group : 1
kernel_size : 3, 3
pad : 1, 1, 1, 1
stride : 1, 1
BatchNormalization
epsilon : 1e-05
momentum : 0.9
spatial : 0
Relu
Conv
dilation : 1, 1
group : 1
kernel_size : 3, 3
pad : 1, 1, 1, 1
stride : 1, 1 …
```

Remove VGG16 from ONNX test because there is VGG16_bn

---

modules/dnn/misc/caffe/opencv-caffe.pb.cc
modules/dnn/misc/caffe/opencv-caffe.pb.h
modules/dnn/src/caffe/opencv-caffe.proto
modules/dnn/src/layers/prior_box_layer.cpp
modules/dnn/test/test_layers.cpp

Related: #14921 
**Merge with extra:** opencv/opencv_extra#649
```
```

Support for several min and max sizes in PriorBox layer

---

modules/imgproc/perf/perf_cvt_color.cpp
modules/imgproc/src/demosaicing.cpp

Fixed calculation of Bs for non-green pixels.
resolves #15011
In file modules\imgproc\src\demosaicing.cpp, the Bs values for non-green cells were being calculated incorrectly in the NW and SE gradients. I fixed the math in both the SSE2 accelerated and non-accelerated code blocks.

Bayer VNG Demosaicing Fix #2

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves https://github.com/opencv/opencv/issues/15120
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/651
```
```

Add support for slice from ONNX with multiple outputs

---

modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/test/gapi_fluid_test.cpp

- Adds sanity checks for GFluidOutputRois
- Tests that invalid ROIs provided result in an exception throw

G-API: verify y offset and height of Fluid output ROIs

---

CMakeLists.txt

resolves #15157
resolves #14868
Precompiled headers support is very limited and does not give notable compilation speedup on UNIX platforms. Curren PCH generation mechanism does not support targets-based dependencies cmake approach.

PCH: disable by default on all platforms except MSVC

---

modules/highgui/src/roiSelector.cpp

Fix issue with cv::selectROI rectangle rendering.
Old (wrong) behavior: When dragging from any other corner than top-left, the ROI rectangle is not visible.
New (this PR, fixed) behavior: ROI Rectangle is visible when dragging from any corner. The rectangle doesn't get outside of image bounds.
Fixed and tested for both `fromCenter = true` and `fromCenter = false`

Fix cv::selectROI rectangle rendering issue

---

modules/videoio/src/cap_v4l.cpp

Added macro definition missing in older V4L2 headers.

Fix for building with older V4L2

---

cmake/templates/dllmain.cpp.in
modules/core/src/glob.cpp
modules/core/src/utils/datafile.cpp
platforms/wince/arm-wince-headless-overrides.cmake
platforms/wince/readme.md

This PR adds support to build OpenCV as a shared libraries by
* Adding UNICODE support for getModuleFileName and GetFileAttributesEx methods
* Adding OLDNAMES.lib to properly map zlib open/close/write calls to Windows _ prefixed names
* Add proper DllMain entry as this differs on WINCE and cannot be overridden
* Update README for building shared libraries on WINCE

Support building shared libraries on WINCE

---

modules/dnn/perf/perf_net.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_tf_importer.cpp
samples/dnn/tf_text_graph_ssd.py

enable some tests for IE 2019R2 after https://github.com/opencv/opencv/pull/15139
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/647
There are three tests failed (perhaps, will fix in a separate PR):
```
[  FAILED  ] Test_TensorFlow_nets.EAST_text_detection/3, where GetParam() = DLIE/OCL_FP16
[  FAILED  ] Layer_Test_Halide/ReLU.Accuracy/13, where GetParam() = (-0.1, DLIE/MYRIAD)
[  FAILED  ] Layer_Test_Halide/Eltwise.Accuracy/38, where GetParam() = ([1, 4, 5], "sum", 1, false, DLIE/OCL)
[  FAILED  ] Layer_Test_Halide/Eltwise.Accuracy/146, where GetParam() = ([2, 8, 6], "sum", 1, false, DLIE/OCL)
```
```
build_image:Custom …
```

Modify SSD from TensorFlow graph generation script to enable MyriadX

---

cmake/OpenCVModule.cmake
modules/core/src/utils/datafile.cpp
modules/videoio/src/cap_winrt/CaptureFrameGrabber.cpp

resolves #14388 
This PR contains some fixes to enable building OpenCV for UWP, these are issues that we came across while trying to package OpenCV for **vcpkg** (https://github.com/microsoft/vcpkg/pull/5169).
* Fixes build for UWP by guarding calls to invalid code.
* Fixes build for `videoio` module in UWP.
* Only remove the `/APPCONTAINER` linker flag when building tests in order to produce correct DLLs in UWP.

Fix build for UWP

---

doc/js_tutorials/js_setup/js_setup/js_setup.markdown

It's easier and often more reliable to use docker containers for emscripten builds like this so this PR adds a little section detailing this

OpenCv.js docker container build instructions

---

modules/imgcodecs/src/exif.cpp
modules/imgcodecs/src/exif.hpp

ExifReader::getNumDirEntry use the fixed offset value, which may parse error number of DirEntry in some cases.
Following is structure of TIFF header. We should get the offset through "Offset to first IFD" item.

fix exif bug

---

modules/core/include/opencv2/core/hal/intrin_vsx.hpp

Use the quadword bit permutation instruction to creatively move
the sign bits to create the mask. Note that permute values above 127
will result in 0 in the respective bit position.
This results in a 5-15% speedup in the houghlines imgproc benchmarks.
Otherwise, no change is observed.

hal: vsx: further optimize v_signmask

---

modules/videoio/src/cap_ffmpeg_impl.hpp

I ran into a problem where ffmpeg would not recognise the video format of a .dav file produced by a security camera. Forcing ffmpeg to just assume h264 worked for me, but I had no way of specifying this using OpenCV.
This small patch allows you to specify input format using the OPENCV_FFMPEG_CAPTURE_OPTIONS environment variable, adding the key input_format. I figured it might be useful for others too, hence the PR.

allow forcing the input format for ffmpeg backend with env var

---

modules/videoio/src/cap_v4l.cpp

This PR removes a print which was impossible to hide. My use case is it's also printed in the Python bindings, and as brute-forcing the camera ids is the only reliable way to enumerate all cameras, it's annoying and noisy to print each time.
The return value covers whether the device exists. This might be better hidden behind a debug flag, but I couldn't work out how to do that nicely.

Remove unavoidable print of CV error

---

modules/videoio/test/test_video_io.cpp

videoio(test): skip unstable MSMF tests (3)

---

modules/objdetect/src/hog.cpp

Convert HOG from SSE SIMD to HAL - 35-45% faster on Power (VSX).
```
force_builders=ARMv8,Custom
```

Convert HOG from SSE SIMD to HAL - 35-45% faster on Power (VSX)

---

modules/core/src/system.cpp

This fixes a cv::exception being thrown when trying to use OpenCV and WINCE on ARMv7 Thumb2.

WINCE 8.0 requires ARMv7 Thumb2 and thus have NEON instructions

---

modules/gapi/cmake/DownloadADE.cmake

<cut/>
```
#build_gapi_standalone:Linux32=ade-0.1.1f
#build_gapi_standalone:Win32=ade-0.1.1f
force_builders=ARMv7,ARMv8,Custom Win
```

Bump to new ADE release 0.1.1f

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/own/saturate.hpp
modules/gapi/src/backends/fluid/gfluidcore.cpp

resolves #15163: C++11 definition issue by @neheb
Replace C++ style calls like `std::sin(x)` with plain C style like `sinf(x)` or `sin(x)` depending on type of `x`, is it `float` or `double`.

GAPI: use plain-C interface to math functions, sin/cos, etc.

---

modules/gapi/include/opencv2/gapi/garg.hpp
modules/gapi/include/opencv2/gapi/gtype_traits.hpp
modules/gapi/test/internal/gapi_int_garg_test.cpp

- fixes compatibility issue between G-API and wingdi.h header on Windows systems
- renames `cv::detail::ArgKind::OPAQUE` value to `GOPAQUE` to fix the conflict
---
__Issue__:
Compilation error occurs in G-API code if user includes both wingdi.h and gtype_traits.hpp. The latter is included in garg.hpp, gkernel.hpp, gtransform.hpp ("API" headers).
I imagine that the issue occurs when the order of includes is the following:
```cpp
#include "wingdi.h"  // defines OPAQUE value
#include "gtype_traits.hpp"  // uses ArgKind::OPAQUE
```
In that case opaque error description (hence the joke) is shown:
```bash
include/opencv2/gapi/gtype_traits.hpp(29): error: expected an identifier
OPAQUE,       // Unknown, generic, opaque-to-GAPI data type - STATIC
^
include/opencv2/gapi/gtype_traits.hpp(44): …
```

G-API: fix compatibility with wingdi.h header on Windows systems

---

modules/core/test/test_ptr.cpp

<cut/>
```
opencv_contrib=cmake_tesseract_cxx11_check
```

build: eliminate warnings with Xcode 10.3

---

modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/src/compiler/gmodel.cpp
modules/gapi/src/compiler/gmodel.hpp
modules/gapi/test/gapi_fluid_test.cpp

- Fixes usage model of `Journal` in Fluid backend: clear existing `Journal` entries on graph reshape
- Adds (experimental) test to verify that memory usage stays the same

G-API: Fix Journal usage in Fluid backend

---

modules/core/include/opencv2/core/fast_math.hpp
modules/core/perf/perf_cvround.cpp
modules/core/test/test_math.cpp

Optimize fast_math.hpp primitives for P8+ and GCC based systems.
Leverage compiler builtins to implement most rounding primitives. This should allow the compiler to choose more efficient instructions for the target architecture. PPC has dedicated rounding instructions. Hopefully this also carries over to other architectures too.
Notably, __builtin_lrint{,f} functions just call out to libm. Instead, include an inline solution similar to ARM.
This reduces the testing time by 200-300 seconds on POWER9.
```
```

fast_math.hpp performance improvements

---

3rdparty/libjasper/jas_stream.c
3rdparty/libjasper/jasper/jas_config.h

uClibc-ng for some reason does not provide a definition when some
deprecated APIs are disabled. Value taken from the musl libc.

jas_stream: Add definition for L_tmpnam if missing

---

modules/core/src/ocl.cpp

Detected by clang trunk:
```
opencv/modules/core/src/ocl.cpp:4337:37: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling]
CV_OCL_CHECK_RESULT(retval, cv::format("clCreateBuffer(capacity=%lld) => %p", (long long int)entry.capacity_, (void*)entry.clBuffer_).c_str());
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
opencv/modules/core/src/ocl.cpp:193:42: note: expanded from macro 'CV_OCL_CHECK_RESULT'
if (0) { const char* msg_ = (msg); CV_UNUSED(msg_); /* ensure const char* type (cv::String without c_str()) */ } \
```
because `cv::format` yields a temporary `std::string`, and thus `msg_` points to a destroyed buffer.

modules/core/src/ocl.cpp: Fix dangling pointer

---

modules/core/include/opencv2/core/mat.inl.hpp

resolves #15343
Additionally two move constructors of Mat_<T> are changed to properly move.
<cut/>
```
```

Fix #15343: stack overflow when converting two Mat_<> of different types.

---

modules/core/include/opencv2/core/fast_math.hpp

- extend using of builtin functions
- fixed PPC64LE build: `error: 'scalar_test_data_class' was not declared in this scope` (GCC5/GCC6, GCC7+ is required)
```
#build_image:Custom=powerpc64le
```

core: update fastmath.hpp

---

modules/core/src/stat.simd.hpp

core: fix stat SIMD code

---

3rdparty/libpng/CMakeLists.txt

The deprecated flag ENABLE_VSX should not be used to enable this
feature. Instead, use the baseline cpu feature set to determine.

libpng: update check for VSX enablement

---

platforms/ios/build_framework.py
platforms/osx/build_framework.py

Add command line option `--debug` to both the macOS and iOS build scripts to enable building OpenCV on these platforms with debug info.
Additionally add executable privilege to the macOS build script
```
```

Add debug build option to macOS and iOS build scripts

---

CMakeLists.txt
cmake/OpenCVDetectInferenceEngine.cmake

Adopted detection of Inference Engine targets for case when Inference Engine has more than 1 public library
<cut/>
```
```

Adopted detection of Inference Engine

---

modules/core/include/opencv2/core/mat.inl.hpp

resolves #15379
relates #15365
```
```

core: handle empty Mat in Mat_ assignment operators

---

modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests.hpp
modules/gapi/test/common/gapi_operators_tests.hpp

extends documentation on how to use new accuracy tests model (in *.hpp files with test fixtures declaration)

Document usage of accuracy tests model

---

modules/core/include/opencv2/core/hal/intrin_vsx.hpp

Intrinsics should be using the macros OPENCV_HAL_IMPL_VSX_REDUCE_OP_16 instead the incorrect OPENCV_HAL_IMPL_VSX_REDUCE_OP_8.

Fix macro bug with v_reduce_min and v_reduce_max for chars in VSX

---

modules/video/src/lkpyramid.cpp

Convert lkpyramid from SSE SIMD to HAL - 90% faster on Power (VSX).  Didn't convert NEON since it looks different from the SSE2.

Convert lkpyramid from SSE SIMD to HAL - 90% faster on Power (VSX).

---

modules/core/include/opencv2/core/vsx_utils.hpp

resolves #15411
This disambiguates vec_popcnt for the [v_uint64x2](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_vsx.hpp#L155) and [v_int64x2](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_vsx.hpp#L173) structs in their respective v_popcount overloads ([v_uint64x2](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_vsx.hpp#L840), [v_int64x2](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_vsx.hpp#L842)) by reusing existing macros to provide an overload for `vec_udword2`.
```
```
Extra PowerPC CI: …

Disambiguate vecpopcnt for (u)dword2.

---

modules/core/include/opencv2/core/fast_math.hpp

resolves #15413 
This alters inline assembly to use an instruction mnemonic commonly supported by both gcc and clang. This does not alter functionality, only enables the file to be compiled. See explanation in #15413 for references to the ISA manual.
```
```
Extra PowerPC CI: https://ocv-power.imavr.com/#/opencv_pullrequests

Use commonly supported instruction mnemonic.

---

modules/core/src/norm.cpp
modules/core/src/stat.simd.hpp

Unroll normL2Sqr_, float normL1_ and int normL1_to hide latencies - 30% improvement on VSX.
Vectorize normHamming - 5.6x improvement on VSX ans SSE and 8x speedup for AVX.

Improve vectorization in the 'norm' functions

---

modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/core/src/matmul.simd.hpp

This uses a few features specific to PPC to run 4 multiplication
chains in parallel using the expanding multiply instructions.
This results in ~2.5x speedup in the dot perf tests.

core: vectorize dotProd_32s for VSX

---

modules/imgproc/src/median_blur.dispatch.cpp

The https://github.com/opencv/opencv/commit/5b17a60dde5cb7706bc3b7f6caeb2dcb46850259 removed tegra optimization for OpenCV 4.x. But, I found that tegra optimization remains in master branch. So, I removed this code.

removed tegra optimization

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/infer/ie.hpp
modules/gapi/include/opencv2/gapi/infer/ie/util.hpp
modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/backends/ie/util.hpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

- HAVE_INF_ENGINE flag check in headers "infer/ie.hpp" and "infer/ie/util.hpp" is deleted
- headers in "infer/" and "infer/ie/" folders are included into gapi_ext_hdrs;
+ because of that a few #includes are required in the headers
OpenCV public API should not have features-based conditional compilation in general (because these internal flags are not available in user apps). Instead of using such condoitions, user should add checks into their app.
Also the headers for G-API inference should be put into gapi_ext_hdrs CMake varaible

WIP: G-API: Internal IE flag check in public headers issue

---

modules/gapi/test/own/mat_tests.cpp

gapi(test): fix 32S->8U type in OwnMatConversion.WithND

---

cmake/OpenCVPCHSupport.cmake

resolves #14939
Do not use the chmod command in WIN32

fix 'chmod' is not recognized as an internal or external command in Windows

---

modules/calib3d/src/calibration.cpp

resolves #14469 
relates #13910
Always allocate _Jo matrix in cvCalibrateCamera2Internal() when releaseObject flag is true. This prevents an attempt to multiply an empty _Jo (causing an exception) when the calcJ flag is true during solver iterations.

Fix exception using calibrateCameraRO with iFixedPoint > 0

---

modules/imgproc/perf/perf_integral.cpp

resolves #15439
This PR is changing modules/imgproc/perf/perf_integral.cpp if you look at sumpixels.cpp there are several possible combinations of matrix sizes for the integral function. The performance tests do not cover all possibilities even with some of them being optimised with HAL instructions so it's impossible to analyse improvements made for those combinations.

Adding all possible data type interactions to the perf tests since some use SIMD acceleration and others do not.

---

modules/core/src/opencl/fft.cl

- error: variables in the local address space can only be declared in the outermost scope of a kernel function
[Build logs](http://pullrequest.opencv.org/buildbot/builders/3_4-win64-vc16/builds/94/steps/test_core-opencl/logs/stdio)

core(OpenCL): fix fft kernel compilation

---

modules/highgui/include/opencv2/highgui.hpp
modules/highgui/src/precomp.hpp
modules/highgui/src/window.cpp
modules/highgui/src/window_cocoa.mm
modules/highgui/src/window_w32.cpp

This change adds the ability for the cv created normal window to be TOPMOST, in situations where it is needed for the Window to be above all of the others.
To make a normal window TOPMOST, call cvSetWindowProperty with property WND_PROP_TOPMOST and a non-zero property value. Passing in 0 for the prop_value will make the window TOP.

Added mechanism to set/toggle NORMAL window to TOPMOST window.

---

modules/ts/misc/run_long.py

[Test failure](http://pullrequest.opencv.org/buildbot/builders/master_valgrind-lin64-debug/builds/10189)

gapi(test): disable memory consumption check in valgrind runs

---

modules/ts/src/ts_func.cpp

GCC8
Message:
```
In function 'cv::Mat cvtest::calcLaplaceKernel2D(int)':
cc1plus: warning: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' forming offset [25, 32] is out of the bounds [0, 24] of object 'scharr' with type 'const int [6]' [-Warray-bounds]
/build/precommit_custom_linux/3.4/opencv/modules/ts/src/ts_func.cpp:2706:26: note: 'scharr' declared here
static const int scharr[] = { 3, 10, 3, -1, 0, 1 };
```
<cut/>
```
```

ts: eliminate -Warray-bounds warning

---

modules/gapi/CMakeLists.txt

added `project` command for stand-alone build
```
```
@dmatveev please take a look

G-API: fixing CMake warning for standalone build

---

modules/core/include/opencv2/core/vsx_utils.hpp

Add redirections for for vec_mul{e,o} prior to GCC8 to support older compilers.
resolves #15506
```
```

Fix issue #15506

---

cmake/OpenCVDownload.cmake

resolves #13573
Adds two paramters to customize cmake download process for unstable and slow networks:
* `OPENCV_DOWNLOAD_TRIES_LIST` - list of items representing download tries:
* `OPENCV_DOWNLOAD_PARAMS` - raw parameter string to be used in cmake's `file(DOWNLOAD ...)` call
* added directory creation to fallback `download_with_*.sh` scripts
<cut/>
Examples:
bash:
```.sh
cmake \
-DOPENCV_DOWNLOAD_TRIES_LIST=1\;2\;3\;4\;5 \
-DOPENCV_DOWNLOAD_PARAMS=INACTIVITY_TIMEOUT\;30\;TIMEOUT\;180\;SHOW_PROGRESS \
../opencv
```
cmd:
```.bat
cmake ^
-DOPENCV_DOWNLOAD_TRIES_LIST=a;b;c ^
-DOPENCV_DOWNLOAD_PARAMS=INACTIVITY_TIMEOUT;30;TIMEOUT;180;SHOW_PROGRESS ^
../opencv
```
Edit: renamed to `OPENCV_DOWNLOAD_TRIES` => `OPENCV_DOWNLOAD_TRIES_LIST`, marked both variables as advanced.
``` …
```

cmake: download tries, customizable download parameters

---

doc/js_tutorials/js_setup/js_setup/js_setup.markdown

* js
* documentation only 
* adds a warning on building with docker section related to https://github.com/opencv/opencv/issues/14691
* adds instructions to build the docs with docker

js setup docker build warning and docs instructions

---

modules/highgui/src/window.cpp

related #14872 
On OSX `HAVE_COCOA` is always ON but `window_cocoa.mm` will be compiled only if Qt is disabled. More details in related PR.
This is a quick fix: we made property handler follow same scheme as CMake script. More complete fix would include reworking of CMake scripts together with code refactoring.

Fixed OSX build with Qt

---

modules/videoio/src/cap_avfoundation_mac.mm

related #14267
related #14278
Authorization request being sent does can not result in message because of application exit (e.g. _example_cpp_videocapture_camera_). Thus added main run loop spin with small delay to make sure UI performs request.
Added an environment configuration parameter (`OPENCV_AVFOUNDATION_SKIP_AUTH`) to skip authorization request in OpenCV. Authorization check is still performed.
Backported runtime OSX check from _master_ branch. It should've been done in #14500, but slipped away for some reason.
cc @jeroen
```
```

AVFoundation: fix camera authorization request

---

doc/py_tutorials/py_gui/py_image_display/py_image_display.markdown

This pull request improves the grammar on the "Getting Started with Images" page under "Gui Features in OpenCV" in the python tutorials.

Grammer fixes on python image display tutorial

---

modules/dnn/src/model.cpp
modules/dnn/test/test_model.cpp

Fix missed detections in case of predicted values in relative coordinates but out of [0, 1] range (will fix samples in a separate PR).
```
```

Fix DetectionModel in case of out of [0, 1] range detection prediction

---

CMakeLists.txt
doc/tutorials/introduction/building_tegra_cuda/building_tegra_cuda.markdown

Removes old `BUILD_opencv_java` option and updates documentation to the actual `BUILD_JAVA` option.

Remove old build java option

---

cmake/checks/atomic_check.cpp

resolves #15278
<cut/>
```
```

cmake: use 'long long' for atomic check

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp

Extended v_check_any/v_check_all universal intrinsics to support 64-bit integer
```
#buildworker:Custom=linux-1,linux-2,linux-4
#docker_image:Custom=powerpc64le
```

Extended v_check_any/v_check_all to 64-bit integer

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp
modules/gapi/test/cpu/gapi_core_tests_fluid.cpp
modules/gapi/test/gpu/gapi_core_tests_gpu.cpp

This pullrequest moves maxval to threshold tests parameter and fixes documentation

G-API: Move maxval to threshold tests parameter

---

doc/js_tutorials/js_setup/js_setup/js_setup.markdown
modules/core/include/opencv2/core/cv_cpu_dispatch.h
modules/core/include/opencv2/core/hal/intrin.hpp
modules/core/include/opencv2/core/hal/intrin_wasm.hpp
modules/core/src/mathfuncs_core.simd.hpp
modules/core/src/parallel.cpp
modules/js/CMakeLists.txt
modules/js/perf/README.md
modules/js/perf/base.js
modules/js/perf/package.json
modules/js/perf/perf_helpfunc.js
modules/js/perf/perf_imgproc/perf_cvtcolor.html
modules/js/perf/perf_imgproc/perf_cvtcolor.js
modules/js/perf/perf_imgproc/perf_resize.html
modules/js/perf/perf_imgproc/perf_resize.js
modules/js/perf/perf_imgproc/perf_threshold.html
modules/js/perf/perf_imgproc/perf_threshold.js
modules/js/src/core_bindings.cpp
modules/js/src/make_umd.py
platforms/js/build_js.py

* Proposal: [Improve the performance of JavaScript version of OpenCV (OpenCV.js)](https://docs.google.com/document/d/1Nx3MDFnM47kumdyyUzju2xn3loiZnf0HsmhmCzAJfKo/edit?usp=sharing)
* [Project Report](https://gist.github.com/Wenzhao-Xiang/8636e239c20e0eda839833f9d363828e)
* Mentor: Ningxin Hu @huningxin , Vitaly Tuzov @terfendail 
* Student: Wenzhao Xiang @Wenzhao-Xiang 
* Create the base of OpenCV.js performance test:
This perf test is based on [benchmark.js](https://benchmarkjs.com). And we first add `cvtColor`, `Resize`, `Threshold` into it. We support both browser and Node.js version of it for test.
* Optimize the OpenCV.js performance by WASM threads:
This optimization is based on Web Worker API and SharedArrayBuffer, so it can be only used in browser. We expose two new API …

[GSoC 2019] Improve the performance of JavaScript version of OpenCV (OpenCV.js)

---

modules/dnn/src/layers/recurrent_layers.cpp
modules/dnn/test/test_layers.cpp

This can be used to produce a bidirectional LSTM by having two operating in parallel on the same input, but operating in different directions.
This PR lets cv::dnn::LSTMLayer interpret a new boolean parameter in the LayerParams called "reverse".  If it is true, the LSTM operates in the reverse direction to normal.

dnn: Allow LSTM layer to operate in reverse direction

---

modules/core/src/persistence.cpp

- avoid data copying after buffer block shrink
- resize current block in case of single FileNode

core(persistence): fix reserveNodeSpace() implementation

---

modules/calib3d/src/chessboard.cpp
modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/imgwarp.cpp

 imgproc: use Matx23d as result type of getRotationMatrix2D() call

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_model.cpp

Fix autodetection of input size for dnn networks

---

modules/dnn/misc/python/test/test_dnn.py
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_misc.cpp

do not fail nightly builds (they are run under heavy system load, and some extra time is required for first compilation of network)
<cut/>
```
```

dnn: increase async test timeout

---

modules/dnn/test/test_halide_layers.cpp

Related tests:
<cut/>
```
[ RUN      ] Layer_Test_Halide/Eltwise.Accuracy/30, where GetParam() = ([1, 4, 5], "sum", 1, false, DLIE/CPU)
[       OK ] Layer_Test_Halide/Eltwise.Accuracy/30 (17 ms)
[ RUN      ] Layer_Test_Halide/Eltwise.Accuracy/31, where GetParam() = ([1, 4, 5], "sum", 1, false, DLIE/OCL)
/build/3_4_openvino-opencl-skl-lin64/opencv/modules/dnn/test/test_common.impl.hpp:63: Failure
Expected: (normL1) <= (l1), actual: 0.546033 vs 1e-05
/build/3_4_openvino-opencl-skl-lin64/opencv/modules/dnn/test/test_common.impl.hpp:66: Failure
Expected: (normInf) <= (lInf), actual: 0.986967 vs 0.0001
[  FAILED  ] Layer_Test_Halide/Eltwise.Accuracy/31, where GetParam() = ([1, 4, 5], "sum", 1, false, DLIE/OCL) (140 ms)
[ RUN      ] Layer_Test_Halide/Eltwise.Accuracy/32, where GetParam() = ([1, …
```

dnn: skip "sum" tests on IE/OpenCL target

---

modules/gapi/src/compiler/passes/perform_substitution.cpp

- updates substitution logic: when "detaching" pattern out nodes, correct resource management is performed
- resolves #15603
Originally, doing edge erasure was done in unsafe manner: in a for-loop, we iterated over a container that got changed in the body of that for-loop:
```cpp
for (auto e : graphDataNode->inEdges()) {
graph.erase(e);  // this procedure modifies graphDataNode->inEdges()
}
```

G-API: fix UB/crash in pattern substitution routine

---

doc/tutorials/introduction/linux_install/linux_install.markdown

Add one bulletpoint into the Linux tutorial so it's clearer how to utilize the generated pkg-config info.
As the user might be confused about why `pkg-config --cflags --libs opencv` (<- not opencv4) fails, and issues like https://github.com/opencv/opencv/issues/13154 can suggest that support for pkg-config has been dropped.

Add note about pkg-config usage in tutorial

---

modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_torch_importer.cpp

<cut/>
```
force_builders=Custom,Custom Win,Custom Mac,Linux AVX2
build_image:Linux AVX2=ubuntu-openvino-2019r3.0:16.04
test_filter:Linux AVX2=*
**WIP**
```

Enable ENet with Inference Engine backend on CPU

---

modules/gapi/test/common/gapi_imgproc_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp
modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp
modules/gapi/test/cpu/gapi_imgproc_tests_fluid.cpp
modules/gapi/test/gpu/gapi_imgproc_tests_gpu.cpp

- Size parameter is changed from int to cv::Size type to allow rectangle kernels
- Kernel creation code is adopted for different kernel sizes to not create only white images on the output

OpenCV G-API Filter2D test improvement

---

modules/core/include/opencv2/core/private.cuda.hpp

Fix compiler warnings for latest cuda npp which defines this itself as:
```
#define NPP_VER_MAJOR 10
#define NPP_VER_MINOR 2
#define NPP_VER_PATCH 0
#define NPP_VER_BUILD 243
#define NPP_VERSION (NPP_VER_MAJOR * 1000 +     \
NPP_VER_MINOR *  100 +     \
NPP_VER_PATCH)
```
```
opencv_contrib=
```

Build with cuda 10.1 and NPP 10.2.0.243

---

modules/cudalegacy/src/cuda/NCVBroxOpticalFlow.cu

Messages:
```
opencv/modules/cudalegacy/src/cuda/NCVBroxOpticalFlow.cu(1124): warning: variable "p_threads" was declared but never referenced
opencv/modules/cudalegacy/src/cuda/NCVBroxOpticalFlow.cu(958): warning: variable "dThreads" was declared but never referenced
```
```
```

build: eliminate CUDA warnings

---

cmake/checks/cpu_avx2.cpp

- _mm256_bslli_epi128() works in [GCC 4.9.3+](https://gcc.godbolt.org/z/LIZG-L) only
- Android NDK r10 doesn't support this instruction
relates #15510
fixes [nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_pack-android/builds/530).
```
force_builders=Android pack,Linux AVX2
```

build: update AVX2 check

---

modules/core/src/opengl.cpp

There might be multiple ways of getting OpenCV compile on Tegra (NVIDIA Jetson) platform, but mainly they modify CUDA(8,9,10...) source code, this one fixes it for all installations. 
( https://devtalk.nvidia.com/default/topic/1007290/jetson-tx2/building-opencv-with-opengl-support-/post/5141945/#5141945 et al.).
This way is exactly the same as the one proposed but the code change happens in OpenCV.
```
opencv_contrib=
```

Cuda + OpenGL on ARM

---

modules/core/include/opencv2/core/version.hpp

OpenCV 3.4.8
relates #15435
<cut/>
<details>
[opencv_world348.dll (vc14)](https://www.virustotal.com/gui/file/2872146a745b1f24050030d940511448998ee8a90702f03fa56e55dcff93d7bf/detection)
[opencv_world348d.dll (vc14)](https://www.virustotal.com/gui/file/2872146a745b1f24050030d940511448998ee8a90702f03fa56e55dcff93d7bf/detection)
[opencv_world348.dll (vc15)](https://www.virustotal.com/gui/file/2872146a745b1f24050030d940511448998ee8a90702f03fa56e55dcff93d7bf/detection)
[opencv_world348d.dll (vc15)](https://www.virustotal.com/gui/file/2872146a745b1f24050030d940511448998ee8a90702f03fa56e55dcff93d7bf/detection)
[opencv_ffmpeg348_64.dll](https://www.virustotal.com/gui/file/2872146a745b1f24050030d940511448998ee8a90702f03fa56e55dcff93d7bf/detection) …

OpenCV release (3.4.8)

---

modules/gapi/test/infer/gapi_infer_ie_test.cpp

`InputInfo::getDims()` is deprecated, used `getTensorDesc().getDims()` instead.
<cut/>
```
```

Deprecated IE API in G-API test

---

modules/imgproc/src/accum.simd.hpp

Currently whenever a mask is used at the accumulate function opencv reverts to the generic non-vectorized implementation. This PR adds masking support for uchar and ushort's implementation. Performance improvement for ppc64le are up to 89%.

Adding support for vectorized masking for uchar/ushort.

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_avx512.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/core/test/test_intrin_utils.hpp

New v_reverse HAL intrinsic for reversing the ordering of a vector.
<cut/>
```
disable_ipp=ON
```

New v_reverse HAL intrinsic for reversing the ordering of a vector

---

modules/core/src/mathfuncs.cpp

Because reads and writes to volatile bool are not guaranteed to be atomic.

Use std::atomic in getExpTab32f and getLogTab32f

---

modules/gapi/include/opencv2/gapi/gkernel.hpp

- Unnecessary extra semicolon after member function definition has been removed from the G_ID_HELPER_BODY macro definition because that has been raising warnings.
```
struct G_ID_HELPER_CLASS(Class)                                            \
{                                                                   \
-           static constexpr const char * id() {return Id;};                \
+           static constexpr const char * id() {return Id;}                 \
};     
```

G-API: G_ID_HELPER_BODY macro semicolon issue 

---

modules/gapi/src/backends/fluid/gfluidimgproc_func.simd.hpp

resolves #15690
Initialization code is executed without any dispatching guards for supported CPU instruction sets.

G-API: avoid dynamic initialization in dispatched files

---

modules/core/src/copy.cpp
modules/core/test/test_mat.cpp
modules/ts/src/ts_tags.cpp

workaround #12943
- IPP/SSE4.2 works well

core(IPP): skip huge input in flip()

---

modules/viz/src/precomp.hpp

VTK_MAJOR_VERSION not found unless header is included
Adds include of vtkVersionMacros.h in precomp.hpp

COMP: Enabling build with recent VTK version

---

modules/java/jar/CMakeLists.txt
modules/java/jar/build.xml.in

Error message:
> The code being documented uses modules but the packages defined in $URL are in the unnamed module.
```
build_image:Docs=docs:18.04
buildworker:Docs=linux-1
```

javadoc: fix generation with OpenJDK 11

---

modules/core/src/count_non_zero.simd.hpp

Improves performance a bit. 2.2x on P9 and 2 - 3x on coffee lake
x86-64.
Update countNonZero64f to use SIMD as available on the target platform.
<cut/>
```
disable_ipp=ON
```

core: vectorize countNonZero64f

---

samples/cpp/stitching_detailed.cpp

The usage function states that the default for match_conf is
0.65 if the default SURF feature finder is used, and 0.3 for
orbs. Indeed, if --feature orbs is used, match_conf is set
to 0.3f. This is a NOP, because the real default is also set
to 0.3f. Change it to 0.65f when SURF is in play.

stitching_detailed: use correct match_conf default

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_layers.cpp

resolves https://github.com/opencv/opencv/issues/15724
This PR enables Eltwise layer (sum, prod, max) with input tensors with different number of channels.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/679
<cut/>
```
Median (ms)
Name of Test                          3.4     pr        pr    
vs    
3.4    
(x-factor)
AlexNet::DNNTestNetwork::OCV/CPU                           14.343  14.430     0.99   
DenseNet_121::DNNTestNetwork::OCV/CPU                      37.195  37.235     1.00   
EAST_text_detection::DNNTestNetwork::OCV/CPU               67.625  67.560     1.00   
ENet::DNNTestNetwork::OCV/CPU                              44.997  45.185     1.00   
FastNeuralStyle_eccv16::DNNTestNetwork::OCV/CPU            115.694 116.573    0.99 …
```

Enable Eltwise layer with different numbers of inputs channels

---

modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/test/test_intrin_utils.hpp

Casting v_int64x2 or v_uint64x2 to v_float64x2 and comparing does NOT work in all cases.  Rewrite using epi64 instructions - faster too.
Here is an example that does NOT work
v_int64x2 a = v_setall_s64(-1);
v_int64x2 b = v_setall_s64(-1);
if (v_reinterpret_as_f64(a) == v_reinterpret_as_f64(b))
// Always fails because reinterpreting it as a f64 produces a NaN.  NaN is never equal to any other number, not even itself.
<cut/>
```
disable_ipp=ON
```

Fixing bug with comparison of v_int64x2 or v_uint64x2

---

modules/gapi/include/opencv2/gapi/ocl/goclkernel.hpp
modules/gapi/src/executor/gstreamingexecutor.cpp

- gcc 4.8.4 (ARMv7)
resolves #15758
```
```

G-API: fix ARMv7 build

---

modules/gapi/src/compiler/gmodel.cpp
modules/gapi/src/compiler/gmodel.hpp

* Returned `mkDataNode()` overload as a part of exported API for external backend development (was removed in https://github.com/opencv/opencv/pull/15216)
```
```

G-API: Returned GModel::mkDataNode() overload for external backends

---

samples/cpp/tutorial_code/Histograms_Matching/compareHist_Demo.cpp

I think it would help to change all 3 of the the input file arguments to be "positional" for consistency with the other tutorials. This also simplifies the command line input to run this tutorial by reducing typing, and helpfully prints the "usage" info if any of the 3 required inputs are missing.
I'm new to OpenCV and working through the tutorials. I kept getting runtime errors with this one until I realized that the arguments weren't positional, and I was missing the "--input1", "--input2, "--input3" flags preceding the filenames. All of the previous tutorials had required filenames as positional arguments and didn't require this.
The original code would require each input to be specified like this:
```./compareHist_Demo --input1 filename1 --input2 filename2 --input3 filename3```
But …

Tutorial - Make required input args positional.

---

modules/gapi/include/opencv2/gapi/gkernel.hpp

…ilation
```
force_builders_only=Docs,linux
```

G-API: Fix for "using cv makes G_TYPED_KERNEL fail"

---

modules/calib3d/src/stereobm.cpp

resolves #15744
Fixed StereoBM uniqueness check
```
disable_ipp=ON
```

Fixed StereoBM uniqueness check

---

modules/objdetect/src/hog.cpp

Use circular lut history buffer in computeGradient of HOG.
Reduce lut reads by 2/3 and is 33-52% faster.

Use circular lut history buffer in computeGradient of HOG

---

modules/core/include/opencv2/core/private.hpp
modules/core/include/opencv2/core/utility.hpp
modules/core/include/opencv2/core/utils/instrumentation.hpp
modules/core/include/opencv2/core/utils/tls.hpp
modules/core/include/opencv2/core/utils/trace.private.hpp
modules/core/src/ocl.cpp
modules/core/src/ovx.cpp
modules/core/src/precomp.hpp
modules/core/src/rand.cpp
modules/core/src/system.cpp
modules/core/src/umatrix.cpp
modules/core/test/test_utils.cpp
modules/core/test/test_utils_tls.impl.hpp
modules/imgproc/src/histogram.cpp

**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/2316
resolves #9745
- move TLS & instrumentation code out of core/utility.hpp
- TLSData lost .gather() method (to dispose thread data on thread termination)
- use TLSDataAggregator for reliable collecting of thread data
- prefer using of .detachData() instead of .gather() method
<cut/>
TODO:

core(TLS): implement releasing of ThreadData with thread termination

---

modules/calib3d/include/opencv2/calib3d.hpp

The documentation page StereoBinaryBM and StereoBinarySGBM says that it returns a disparity that is scaled multiplied by 16. This scaling must be undone before calling reprojectImageTo3D, otherwise the results are wrong. The function reprojectImageTo3D() could do this scaling internally, maybe, but at least the documentation must explain that this has to be done.
relates #15779

Doc bugfix

---

modules/imgproc/src/pyramids.cpp
modules/video/src/lkpyramid.cpp
modules/video/src/lkpyramid.hpp

Parallellizes execution of cv::pyrDown and calcSharrDeriv. Both are used extensively in buildOpticalFlowPyramid and changes are aimed to speedup this function.

Parallelize pyrDown & calcSharrDeriv

---

modules/ts/misc/testlog_parser.py

If tests are run through GTest option `--gtest_also_run_disabled_tests`
Launched tests have `status="run"` in GTest
Skipped disabled tests have `status="notrun"` in GTest

TS: do not block reporting of launched "DISABLED_" tests

---

modules/core/src/copy.cpp

Vectorize flipHoriz and flipVert functions.
flipVert - 2x faster on VSX and 1.5x on x86
flipHoriz - up to 40x+faster on VSX and x86.
Also improved for NEON.
```
disable_ipp=ON
```

Vectorize flipHoriz and flipVert functions.

---

modules/calib3d/include/opencv2/calib3d.hpp

The function stereoRectify() takes as input a coordinate transform between two cameras. It is ambiguous how it goes. I clarified that it goes from the second camera to the first.

Clarify stereoRectify() doc

---

modules/viz/include/opencv2/viz/types.hpp

resolves https://github.com/opencv/opencv_contrib/issues/2321
Fix wrong definition of viz::Color::navy().
All the other colors look good.
Reorder the colors definition in chromatic order (because it triggers my OCD)

Fix wrong definition of viz::Color::navy()

---

modules/calib3d/include/opencv2/calib3d.hpp

I made a mistake in my previous pull request. For the function stereoRectify(), R and T are transforms from the first camera to the second, rather than the other way around. To ensure that there is no mistake, I propose developers do a simple check using the stereo_match included executable. It goes as follows:
- Create a left image and a right image, say 100 x 100 pixels each, with the right image shifted 10 pixels to the right. 
- Create an intrinsics file, say with intrinsics matrix 80 0 50; 0 80 50;  0 0 1 and zero distortion (f=80, cx = cy = 50)
- Create an extrinsics file, which is the transform from first to second camera, with identity rotation, translation of -10 0 0, 
- Invoke the shipped stereo_match executable. This will call the stereoRectify() function whose documentation we …

Correct stereoRectify documentation

---

modules/core/src/persistence_yml.cpp
modules/core/test/test_io.cpp

resolves #14130
This pullrequest changes `core/persistence_yml.cpp` to fix incorrect YAML parse behavior. Current 4.x fails to read multiple documents from single file.

Fix YAML parse

---

modules/imgproc/src/moments.cpp

Convert moments in tile algorithms to HAL (1.3x faster for VSX).
```
force_builders=ARMv7,ARMv8,Custom
#build_image:Custom=javascript-simd
```

Convert moments in tile algorithms to HAL (1.3x faster for VSX).

---

modules/core/src/persistence.cpp
modules/core/test/test_io.cpp

resolves #14130
resolves https://github.com/opencv/opencv_contrib/issues/2331
relates #15842
Corresponding code on "3.4" branch is [here](https://github.com/opencv/opencv/blame/3.4.8/modules/core/src/persistence_c.cpp#L662).
```
```

core(persistence): fix processing of multiple YAML documents

---

modules/core/src/ocl.cpp

It's not an error if some OpenCL platform has no devices. This makes
OpenCL device detection work correctly in the following scenario:
<cut/>
```
$ OPENCV_OPENCL_DEVICE=:GPU: ./opencv_test_dnn
OpenCV version: 4.1.2-dev
OpenCV VCS version: 4.1.2-80-g467748ee98-dirty
Build type: Debug
Compiler: /usr/bin/g++  (ver 7.4.0)
Parallel framework: pthreads
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
Intel(R) IPP version: ippIP AVX2 (l9) 2019.0.0 Gold (-) Jul 24 2018
OpenCL Platforms:
AMD Accelerated Parallel Processing
Portable Computing Language
CPU: pthread-AMD Ryzen 7 2700X Eight-Core Processor (OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-znver1)
NVIDIA CUDA
dGPU: GeForce GTX 1080 (OpenCL 1.2 CUDA)
Current OpenCL device:
Type = dGPU
Name = GeForce GTX 1080 …
```

Fix OpenCL device detection when some OpenCL platform has no devices

---

modules/core/include/opencv2/core/opencl/opencl_info.hpp

Simplify OpenCL info dumping code:
* Reduce code nesting
* Drop redundant .c_str() calls
Just a cleanup. Makes line lengths more reasonable.

Simplify OpenCL info dumping code

---

modules/gapi/CMakeLists.txt

`include/opencv2/gapi/render` directory was missing from install set.
**cc** @TolyaTalamanov @dbudniko @dmatveev

Install: added missing gapi headers

---

modules/js/src/helpers.js

expose FS in Module.FS so users can use the filesystem. This gives more flexibility and enable C/C++ APIs  that reference files. Also needed for supporting node.js and load images directly from local filesystem. (i'm working on supporting node.js too)
relates #15425

opencv.js : expose FS

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_misc.cpp

merge changes proposed by @Dimitri1 at https://github.com/opencv/opencv/pull/15064 with test
<cut/>
```
```

Fix dnn::getLayerInputs

---

modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

Related: #15251 
**Merge with extra:** opencv/opencv_extra#683
```
```

Supported ONNX Squeeze, ReduceL2 and Eltwise::DIV

---

modules/core/CMakeLists.txt

`BUILD_ITT=OFF` in case of using ITT from [VTune](https://software.intel.com/en-us/vtune/choose-download).
Example of CMake options (Linux x86-64):
<cut/>
```
cmake -DBUILD_ITT=OFF -DHAVE_ITT=ON \
-DITT_INCLUDE_DIRS=${VTUNE_AMPLIFIER_2019_DIR}/include \
-DITT_LIBRARIES=${VTUNE_AMPLIFIER_2019_DIR}/lib64/libittnotify.a ...
```

cmake: fix ITT define condition

---

modules/videoio/src/cap_gstreamer.cpp

Replaced [g_filename_to_uri](https://developer.gnome.org/glib/stable/glib-URI-Functions.html#g-filename-to-uri) call with [gst_filename_to_uri](https://gstreamer.freedesktop.org/documentation/gstreamer/gsturihandler.html?gi-language=c#gst_filename_to_uri) which handles relative paths correctly.
Test scenario:
```.py
cap = cv2.VideoCapture('test.mp4', cv2.CAP_GSTREAMER) # did not work - fixed
cap = cv2.VideoCapture('/home/user/test.mp4', cv2.CAP_GSTREAMER) # worked
```

videoio: Fixed relative paths handling in GStreamer backend

---

doc/tutorials/introduction/windows_install/windows_install.markdown

resolves #15872
Fix an error during Windows installation caused by trying to create the already existing Build directory. Also excluding intermediate steps for Install directory creation.
opencv/doc/tutorials/introduction/windows_install/windows_install.markdown

Fix Windows installation script error

---

modules/core/include/opencv2/core/opencl/opencl_info.hpp

This pullrequest refactors parts of opencl information dumping: 
- Remove code duplication
- Clarify functionality of ternary operator
- Use cv's String instead of char * for strings
- Remove unused code
```
```

Refactor opencl_info

---

platforms/osx/build_framework.py

resolves #15899
Adds `disable` parameter to the MacOS build to bring it into line with the iOS build and fix build failure
```
```

Fix MacOS build

---

modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp
modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/test/gapi_fluid_test_kernels.cpp

As only difference of I420 compared to NV12 is separate planes for U and V channels (instead of interleaved ones for NV12), changes are relatively small 
What is done:
- extended cv::gimpl::GFluidExecutable::initBufferRois to handle both ports of I420 to RGB conversion
- renaming from  from NV12 to 4:2:0 to express more generic behaviour 
@rgarnov @dmatveev  please take a look

G-API (Fluid) core support for I420

---

modules/gapi/src/backends/fluid/gfluidimgproc.cpp
modules/gapi/src/backends/fluid/gfluidimgproc_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidimgproc_func.hpp
modules/gapi/src/backends/fluid/gfluidimgproc_func.simd.hpp

GAPI Fluid: SIMD optimization for sep filters of 5x5 kernel size (gaussBlur)

---

modules/dnn/src/onnx/onnx_importer.cpp

**Merge with extra:** opencv/opencv_extra#687
relates #15811
<cut/>
```
```

Fix bug in ONNX ReduceL2

---

.gitignore
doc/js_tutorials/js_setup/js_setup/js_setup.markdown
modules/js/test/package.json
modules/js/test/run_puppeteer.js
modules/js/test/tests.html

* js - tests and docs only
* adds support to run js tests with puppeteer (headless chrome - with a single command)
* didn't modify the tests at all, just infer from output page
* small section about running the tests
* important since executing tests with node didn't seem to be working (at least for me node 12)....
* if somebody thumbs up I could fix that too.
```
```

Js test puppeteer

---

modules/features2d/misc/java/test/BruteForceDescriptorMatcherTest.java
modules/features2d/misc/java/test/BruteForceL1DescriptorMatcherTest.java
modules/features2d/misc/java/test/BruteForceSL2DescriptorMatcherTest.java
modules/features2d/misc/java/test/FlannBasedDescriptorMatcherTest.java
modules/features2d/misc/java/test/ORBDescriptorExtractorTest.java
modules/imgproc/src/filter.dispatch.cpp
modules/imgproc/src/fixedpoint.inl.hpp
modules/imgproc/src/smooth.dispatch.cpp
modules/imgproc/test/test_filter.cpp
modules/imgproc/test/test_smooth_bitexact.cpp
modules/objdetect/misc/python/test/test_facedetect.py
modules/ts/include/opencv2/ts.hpp
modules/ts/src/ts.cpp

**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/2342
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/685
resolves #9863
- avoid kernels with bad approximation
- GaussiabBlur - apply error-diffusion approximation for kernel (8-bit fraction)
<cut/>
TODO:

imgproc: fix bit-exact GaussianBlur() / sepFilter2D()

---

modules/gapi/include/opencv2/gapi/own/mat.hpp
modules/gapi/test/own/mat_tests.cpp

* In standard (non multi dimensional) case `dims` in `own::Mat` are empty, so in current implementation `own::Mat::empty()` will always return `false` in non-md case

Fixed own::Mat::empty() for non-md case

---

modules/dnn/misc/python/pyopencv_dnn.hpp
modules/flann/misc/python/pyopencv_flann.hpp
modules/ml/misc/python/pyopencv_ml.hpp
modules/python/src2/cv2.cpp
modules/python/src2/gen2.py
modules/python/src2/pycompat.hpp
modules/videoio/misc/python/pyopencv_videoio.hpp

**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/2353
Using just "name" is not enough, especially in case of `UMat` and "output" parameter.
relates #15895

python: force using of ArgInfo

---

modules/python/src2/cv2.cpp

`OPENCV_PYTHON_DEBUG=1` environment variable to help debugging of Python bindings issues.
Note: some warnings are invalid due "overloading" processing.
relates #15895

python: emit bindings conversion failures

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_avx512.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_msa.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp
modules/core/include/opencv2/core/hal/intrin_sse_em.hpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/core/include/opencv2/core/hal/intrin_wasm.hpp
modules/core/test/test_intrin_utils.hpp
modules/imgproc/src/sumpixels.cpp

This pullrequest is adding support for the get function described in intrin_cpp.hpp line 322 for VSX and adapting the integral HAL implementations to use it. The way the integral functions are accessing a single element from the vector register require 3 instructions on VSX 2 of which are inside the loop. This new implementation requires only a single instruction.
```
force_builders=Linux AVX2,armv7,armv8,Custom,Win32,Linux32
build_image:Custom Win=msvs2017
#buildworker:Custom=linux-3
#build_image:Custom=ubuntu:18.04
#CPU_BASELINE:Custom=AVX512_SKX
#disable_ipp=ON
#buildworker:Custom=linux-1
#build_image:Custom=mips64el
#build_image:Custom=javascript-simd
```

Improving VSX performance of integral function

---

modules/python/src2/cv2.cpp

Linux, release, GCC 8 + contrib:
- `.o` file size: 15Mb => 11Mb
- compilation time: 82 => 62 sec (`-ftime-report`)
- memory usage (GGC): 3.1Gb => 2.4Gb (`-ftime-report`)

python: reduce code size of cv2.cpp

---

modules/dnn/src/op_inf_engine.cpp

- do not require extensions library
<cut/>
```
```

dnn: fix registration of custom OpenCVLayer

---

modules/core/src/logger.cpp
modules/core/src/system.cpp

Add iostream initializer in function writeLogMessage, fixed issue #14906 completely.

Fix android armv7 c++_static init crash

---

modules/core/src/kmeans.cpp
modules/core/test/test_math.cpp

reported here: https://github.com/opencv/opencv_contrib/issues/2351

core(kmeans): bailout if can't select cluster center

---

modules/videoio/src/cap_v4l.cpp

According to the [paragraph](https://linuxtv.org/downloads/v4l-dvb-apis-new/uapi/v4l/open.html#multiple-opens) about multiple opens of the video device, filehandle becomes the owner of the device only after buffers allocations. Simple call to `open` does not affect theirs state, so it falls down to capture initialization, which will stuck on palette setup.
resolves #15782 
Add finite number of attempts in `tryIoctl` functions (10 by default). 
First function that tries to change state of the camera is `VIDIOC_S_FMT` and it fails with `errno EBUSY`.

Fix infinite loop when trying to change state of the busy camera

---

doc/tutorials/introduction/ios_install/ios_install.markdown
doc/tutorials/introduction/table_of_content_introduction.markdown

resolves #15175
Adds additional information to iOS build instructions:
- Removes instructions to create a link to `/Applications/Xcode.app/Contents/Developer` in the root directory.
- Adds instructions to install Xcode command line tools.
- Notes that opencv_contrib modules are not currently included in the iOS Pack downloadable from the [OpenCV Releases](https://opencv.org/releases/) page so manual compilation is required to use those modules under iOS.
- Shows how to include opencv_contrib modules.
- Shows how to exclude specific modules.
- Shows how to specify which architectures to include in the framework.

Add information to iOS build instructions:

---

modules/videoio/src/cap_v4l.cpp
modules/videoio/src/precomp.hpp

- DEBUG logging compilation is enabled for all videoio backends
- eliminate output through perror(), stderr

videoio(v4l2): use logging, update handling of EBUSY, device closing

---

modules/stitching/include/opencv2/stitching/detail/warpers.hpp

resolves #15824 
Renames `R` parameter to `H` in WarpAffine members' documentation to match implementation.

Rename parameter R to H in AffineWarper member declarations

---

modules/ts/include/opencv2/ts.hpp
modules/ts/include/opencv2/ts/ts_ext.hpp
modules/ts/include/opencv2/ts/ts_perf.hpp
modules/ts/src/ts.cpp
modules/ts/src/ts_perf.cpp
modules/ts/src/ts_tags.cpp
modules/ts/src/ts_tags.hpp

- apply tag 'skip_other'
- apply tag 'skip_bigdata' (legacy tests, new tests should use test tags with memory limits)

ts: count skipped tests via SkipTestException

---

modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp

Replace 
c.apply();
With
cc = c.compile();
cc();
In g-api performance tests.
Change gapi_core_perf_tests.cpp

Fix incorrect use of std::move() in g-api perf tests

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/test/test_misc.py

Added tests for Python bindings generated for functions with elemental types as input arguments
Should be treated as a part of tests for [15915](https://github.com/opencv/opencv/pull/15915)
Bad cases, those are resolved by [15915](https://github.com/opencv/opencv/pull/15915) are added as skipped tests and should be enabled in the following PR.

Tests for argument conversion of Python bindings generator

---

modules/calib3d/include/opencv2/calib3d.hpp

resolves #13523
Fixes a typo in the calib3d.hpp file. ( (Scheimpfug condition) to ([Scheimpflug principle](https://en.wikipedia.org/wiki/Scheimpflug_principle))

Fixes typo in calib3d.hpp

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/cuda/activations.cu
modules/dnn/src/cuda4dnn/kernels/activations.hpp
modules/dnn/src/cuda4dnn/primitives/activation.hpp
modules/dnn/src/init.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/opencl/activations.cl
modules/dnn/test/test_halide_layers.cpp

I have added the Swish and Mish activation functions. This resolves https://github.com/opencv/opencv/issues/15693
###This Pull request changes
[Feature addition] New activation functions Swish and Mish.
```
```

Added Swish and Mish activations

---

modules/gapi/CMakeLists.txt
modules/gapi/cmake/init.cmake
modules/gapi/include/opencv2/gapi/render/render.hpp
modules/gapi/src/api/ft_render.cpp
modules/gapi/src/api/ft_render.hpp
modules/gapi/src/api/ft_render_priv.hpp
modules/gapi/src/api/render.cpp
modules/gapi/src/api/render_ocv.cpp
modules/gapi/src/api/render_ocv.hpp
modules/gapi/src/backends/render/grenderocv.cpp
modules/gapi/src/backends/render/grenderocv.hpp
modules/gapi/src/backends/render/grenderocvbackend.cpp
modules/gapi/src/backends/render/grenderocvbackend.hpp
modules/gapi/test/common/gapi_render_tests.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/render/ftp_render_test.cpp
modules/gapi/test/render/gapi_render_tests_ocv.cpp

<cut/>
Enable FreeType via cmake
``` cmake -DWITH_FREETYPE=ON```
`wip::draw::FText` was added in this update.
`wip::draw::Ftext` is primitive that provide ability to render some text via FreeType library. 
Unlike `wip::draw::Text`it is able to render Unicode strings so you should use `std::wstring` instead `std::string`
Since the `freetype`requires a path to the font, it to each primitive is unnecessary, instead the user must pass the `wip::draw::freetype_font`to the graph compilation arguments which contains the path to the font for all `wip::draw::Ftext` primitives. 
For freetype managing was created a  class`FTPTextRender`.  
* getTextSize - Compute size of bounding box for text
* putText - Put text to image
`FTPTextRender` use `pimpl` to hide `freetype` dependency in header because …

G-API: Implement cv::gapi::wip::draw::FText

---

modules/dnn/test/test_misc.cpp

Fix test skip statistics:
<cut/>
```
[ RUN      ] setInput.normalization/18, where GetParam() = (0.00784314, [50, 50, 50], 0, VKCOM/VULKAN)
[     SKIP ] dnn_skip_vulkan
...
[ SKIPSTAT ] TAG='skip_other' skip 20 tests
```
```
build_image:Custom=ubuntu-vulkan:16.04
test_modules:Custom=dnn,java,python3
```

dnn(test): fix Vulkan skip test tag

---

modules/dnn/src/cuda/math.hpp

Fixes two serious typos in `expm1` and `log1p` implementation for `__half` and `__half2` in the CUDA backend.

fix expm1 and log1p for __half/__half2

---

modules/core/misc/java/src/cpp/core_manual.hpp
modules/features2d/misc/java/src/cpp/features2d_manual.hpp
modules/python/src2/hdr_parser.py

resolves #16056
relates #12972
Bindings parser skip code blocks guarded by:
- `#if 0`
- `#ifdef __OPENCV_BUILD` with the same behavior as `#if 0`
- no `#else`/`#elif` support
- basic support for nested `#if` directives

bindings: basic support for #if preprocessor directives

---

modules/dnn/perf/perf_net.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/src/op_inf_engine.hpp
modules/dnn/test/test_tf_importer.cpp

<cut/>
```
```
```
Median (ms)
Name of Test           3.4     pr       pr    
vs    
3.4    
(x-factor)
ENet::DNNTestNetwork::DLIE/CPU 20.269 18.252    1.11   
ENet::DNNTestNetwork::OCV/CPU  44.035 44.212    1.00  
```

Enable MaxPooling with indices in Inference Engine

---

modules/core/include/opencv2/core/types_c.h
samples/cpp/image.cpp
samples/cpp/tutorial_code/core/interoperability_with_OpenCV_1/interoperability_with_OpenCV_1.cpp
samples/cpp/tutorial_code/core/mat_operations/mat_operations.cpp

**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/2373
resolves #15990
relates #11630
- C API objects will lose their default initializers through constructors

core: disable invalid constructors in C API by default

---

modules/calib3d/src/calibration.cpp
modules/calib3d/test/test_cameracalibration.cpp

resolves #15953
reverting PRs: #6836 #6972 #6955
issue #6336 is considered as invalid
- (1/4) Revert "Correct image borders and principal point computation in cv::stereoRectify": 93ff1fb2f21a552c258fc2e9f7973f7d5b159cfc.
- (2/4) Revert "fix calib3d changes in 6836 plus some others": fa42a1cfc2b0fce1d807f18f0ea26ba1e5753b80.
- (3/4) Revert "fix compiler warning": b3d55489d3f1bd2eab0c1e3ad56d8f17d4f447e9.
- (4/4) Revert "add test for 6836": d06b8c4ea9d30be7f60196cdf3c9a65f64370fa4.

calib3d: revert stereoRectify() changes from PRs: 6836, 6972, 6955

---

modules/gapi/include/opencv2/gapi/gkernel.hpp
modules/gapi/test/gapi_kernel_tests.cpp

- Now user doesn't need to do `combine(x, combine(y, combine(z, zz)))` but
just `combine(x, y, z, zz)`

G-API: Added an arbitrary-argument version of cv::gapi::combine

---

modules/dnn/src/dnn.cpp

backports https://github.com/opencv/opencv/pull/15611 (for https://github.com/opencv/opencv/pull/16068)
```
```

Backport fix for autodetection of input shapes

---

modules/dnn/src/cuda/eltwise_ops.cu
modules/dnn/src/cuda4dnn/kernels/eltwise_ops.hpp
modules/dnn/src/cuda4dnn/primitives/eltwise.hpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/test/test_onnx_importer.cpp

- resolves #15894 
<cut/>
```
```

add Eltwise::DIV support in CUDA backend

---

modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/imgproc/perf/perf_resize.cpp
modules/imgproc/src/resize.cpp

Fix a typo in the unrolling of HResizeLinear when k > 1.
Next, add a VSX optimization for the 8u -> 32s operation. This provides a 1.4x speedup for P9 and 1.1X for P8 baselines.
```
disable_ipp=ON
```

HResizeLinear reduce duplicate work and add partial VSX optimization ... and vectorize more copyMask variants

---

modules/videoio/src/backend_plugin.cpp

Should fix messages like these:
> [ERROR:0] global C:\build\precommit_windows64\opencv\modules\videoio\src\backend_plugin.cpp (215) cv::impl::PluginBackend::PluginBackend
> Video I/O: wrong OpenCV version used by plugin 'FFmpeg OpenCV Video I/O plugin': 4.1, OpenCV version is '4.2.0-pre'
relates #16078 #15950

videoio(plugins): relax version check for FFmpeg wrapper on Windows

---

modules/dnn/src/cuda/fill.cu
modules/dnn/src/cuda/resize.cu

- optimize resize kernels (bilinear and nn) to process multiple channels each iteration
Bilinear resize kernel was compute-heavy. To ease the compute load, the calculations involving spatial dimensions at a location (x, y) can be reused by multiple channels.
Inception v2 MaskRCNN performs bilinear resize on a tensor of 204800 channels. The resize takes around 7.5ms. With this PR, it takes just 3.5ms. That's 2.15x improvement.
<cut/>
```
```

cuda4dnn(resize): process multiple channels each iteration

---

modules/dnn/src/cuda/region.cu
modules/dnn/src/cuda4dnn/kernels/region.hpp
modules/dnn/src/cuda4dnn/primitives/region.hpp

- optimizations to region kernels based on profiling results
- optimizations mainly YOLOv3's region pathway
The CUDA part of the region layer took nearly 700us for single image inference on GTX 1050. It now takes around 270us. That's over 2.6x improvement.
The YOLOv2 path is poorly optimized but it's better than before. It can be optimized further if required (I don't think anybody uses YOLOv2 anyway).
<cut/>
**Benchmark:**
- This PR + PR16092
- GTX 1050 and 7700HQ
Warmup runs: 3
Benchmark runs: 100
Model      | CUDA backend | Darknet
------------ | ------------------- | -----------
YOLOv3  | **54.154ms**    | 57.384ms
Benchmark code: https://gist.github.com/YashasSamaga/26eb2eb16be2cc749e3394d300a7585e
DISCLAIMER: I am not very comfortable editing darknet code but I hope it's correct. …

cuda4dnn(region): optimize kernels

---

modules/core/src/parallel_impl.cpp
modules/core/src/system.cpp

resolves #16072
- don't override current application thread names
- set name for own threads only

core(trace/ITT): avoid calling __itt_thread_set_name() by default

---

modules/imgproc/src/approx.cpp
modules/imgproc/test/test_approxpoly.cpp

for epsilon value of Douglas-Peucker algorithm.
resolves #16053

Add eps error checking for approxPolyDP to allow sensible values only

---

modules/dnn/src/cuda/crop_and_resize.cu
modules/dnn/src/cuda4dnn/kernels/crop_and_resize.hpp
modules/dnn/src/cuda4dnn/kernels/resize.hpp
modules/dnn/src/cuda4dnn/primitives/crop_and_resize.hpp
modules/dnn/src/layers/crop_and_resize_layer.cpp

- add `CropAndResize` support for CUDA backend
**Timings (on GTX 1050):**
Model                                  | Before       | Now
---------------------------------- | ------------- | --------------------
Inception v2 Faster RCNN  | 124ms       | **75ms**
Inception v2 Mask RCNN   | 224ms        | **121ms**
ResNet50  Faster RCNN    | 232ms       | **122ms**
^ more information can be found [here](https://github.com/opencv/opencv/pull/16069#issuecomment-562213204)
<cut/>
```
```

add CropAndResize layer for CUDA backend

---

modules/dnn/src/layers/convolution_layer.cpp

Keep origin weights unchanged.
```
```

Fix weights fusion for Convolution and Deconvolution layers in nGraph

---

cmake/OpenCVPCHSupport.cmake

-c is required to avoid linking (and the associated missing "main" message)

Fix pch generation when linker flags used with GCC

---

modules/gapi/test/cpu/gapi_core_tests_cpu.cpp
modules/gapi/test/gpu/gapi_core_tests_gpu.cpp

NaN result is not properly checked anyway

G-API(test): exclude 32F from bitwise_not case

---

modules/gapi/src/backends/fluid/gfluidbuffer.cpp

relates #16081
resolves #16133
Error message:
<cut/>
```
../opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp: In function 'std::unique_ptr<cv::gapi::fluid::BufferStorage> cv::gapi::fluid::{anonymous}::createStorage(int, int, int, int, cv::gapi::fluid::BorderOpt)':
../opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:350:16: error: cannot bind 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithBorder>' lvalue to 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithBorder>&&'
return storage;
^
In file included from /usr/include/c++/4.8.2/memory:81:0,
from ../opencv/modules/core/include/opencv2/core/cvstd_wrapper.hpp:11,
from ../opencv/modules/core/include/opencv2/core/cvstd.hpp:81,
from ../opencv/modules/core/include/opencv2/core/base.hpp:58,
from …
```

G-API: fix build with GCC 4.8

---

modules/dnn/CMakeLists.txt
modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_layers.cpp
modules/ts/src/ts_func.cpp

relates #15739
> The eltwise layer code in OCV backend assumes that the number of channels are same in all inputs.
Details: https://github.com/opencv/opencv/pull/16063/files#r353899705
<cut/>
```
```

dnn(eltwise): fix handling of different number of channels

---

modules/imgproc/src/resize.cpp

resolves #16137
The fourth value read via v_load_q is essentially ignored,
but can cause trouble if it happens to cross page boundaries.
The final few iterations may attempt to read the most extreme
elements of S, which will read 1B beyond the array in most
alignment cases. Run theses in the scalar code to avoid the
above condition.
Likewise, cleanup the iteration increment statements to make
it more obvious they do channel count (3) elements per pass.

imgproc: Prevent 1B overrun of 8C3 SIMD optimization

---

modules/calib3d/test/test_undistort_badarg.cpp
modules/core/include/opencv2/core/mat.hpp
modules/core/src/matrix_expressions.cpp
modules/core/test/test_operations.cpp

don't check properly.
More checks and tests coming soon.
resolves #15760

Add checks for empty operands in Matrix expressions that

---

modules/gapi/src/executor/gstreamingexecutor.cpp

Fix standalone-gapi: build has been failing while building gstreamerexecutor.cpp
<cut/>
```
```

Fix standalone-gapi

---

modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/test/test_halide_layers.cpp

resolves #15893
This PR adds Halide support for DNN::Eltwise::DIV
<cut/>
```
docker_image:Custom=halide:16.04
test_filter:Custom=*Halide*
#build_image:Custom Win=msvs2017
#build_image:Custom Win=msvs2019
```

Eltwise::DIV support in Halide backend

---

modules/dnn/src/cuda/bias_activation.cu
modules/dnn/src/cuda4dnn/kernels/bias_activation.hpp
modules/dnn/src/cuda4dnn/kernels/bias_activations.hpp
modules/dnn/src/cuda4dnn/primitives/convolution.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/convolution_layer.cpp

- fuses ReLU, ReLU6, Power, TanH, Sigmoid, Swish, Mish with convolutions
<cut/>
**Profiling results:**
- `biasN_relu_inplace` takes as much time as `biasN` => ReLU that follows conv with bias is fully FREE
- `biasN_clipped_relu`  takes as much time as `biasN` => ReLU6 that follows conv with bias is fully FREE
- haven't profiled others
**Issues:**
- investigate this fusion failure:
```
[FORWARD] Convolution
[FORWARD] Identity
[FORWARD] Sigmoid
```
Identity is NOP (it's not even copying) but it's blocking the fusion.
In general, shouldn't `Flatten`, `Blank`, `Reshape`, etc. be marked as skipped if there is no copying involved? It's never skipped even though it does absolutely nothing most of the times.
``` …
```

cuda4dnn: fuse activations with convolutions

---

modules/gapi/test/common/gapi_tests_common.hpp

resolves #14961
<cut/>
```
CPU_BASELINE:Custom=SSE4_2
CPU_DISPATCH:Custom=
```

gapi(test): avoid using of unstable random floating-point input

---

modules/dnn/src/cuda4dnn/csl/cudnn/convolution.hpp

- enables tensor cores for convolutions in fp16 mode
<cut/>
**Device:** RTX 2080 Ti
Model                      | FP32                    | FP16 (without tensor cores)  | FP16 (with tensor cores)
-------------------------- | ----------------------- | ---------------------------- | ------------------------
ResNet50                   | 2.74ms                  | 4.79ms                       | 2.36ms
YOLOv3*                    | 9.53ms                  | 10.56ms                      | 6.49ms
FNS Stary Night            | 4.80ms                  | 26.42ms                      | 3.04ms
EAST Text Detection        | 4.00ms                  | 5.67ms                       | 3.05ms
Inception v2 Faster RCNN   | 20.70ms                 | 28.61ms                      | 25.68m
Inception v2 Mask RCNN     | …

cuda4dnn(conv): enable tensor cores for fp16

---

modules/imgcodecs/src/rgbe.cpp

modern readers that expect RADIANCE will read it
the rgbe.cpp HDR image format codec to output RADIANCE as the program type in header. This is the commonly expected value for this file format.

Change program type in hdr format files to modern value: RADIANCE so

---

modules/imgproc/src/shapedescr.cpp
modules/imgproc/test/test_convhull.cpp

Resolves #16051.
Issue #16051 shows a case where findCircle3pts returns NaN for the
center coordinates and radius due to dividing by a determinant of 0. In
this case, the points are colinear, so the longest distance between any
2 points is the diameter of the minimum enclosing circle.

Handle det == 0 in findCircle3pts.

---

modules/calib3d/src/ptsetreg.cpp
modules/calib3d/test/test_affine3d_estimator.cpp

resolves #16007 
Colinearity test is now correctly performed on all 3 coordinates rather than just on x and y

Fix #16007 - colinearity computed using all 3 coordinates

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/dnn.cpp
modules/dnn/test/test_misc.cpp

resolves #15578
Added implementations to load IR models from buffer
<cut/>
```
```

Load IR model from buffer

---

3rdparty/tbb/CMakeLists.txt

https://github.com/intel/tbb/releases/tag/v2020.0
relates #14926
<cut/>
```
#with_tbb=ON
#build_tbb=ON
```

3rdparty: TBB version 2019u8 => 2020.0

---

modules/calib3d/test/test_undistort.cpp
modules/gapi/test/gpu/gapi_imgproc_tests_gpu.cpp

Some test case names were duplicated.
**Note**: this PR is not applicable to 3.4

Avoid duplicated test cases

---

modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_common.impl.hpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_model.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

- fix and enable tests for `DNN_TARGET_CUDA_FP16`
**Pending:**
- investigate FasterRCNN failures
- investigate deconvolution failures
Merge after #16045 
<cut/>
```
force_builders=Custom,linux,docs
```

fix and enable tests for `DNN_TARGET_CUDA_FP16`

---

modules/core/src/arithm.cpp
modules/core/test/test_arithm.cpp

If the depth value of the input array of `cv::compare` is `CV_16F` , an access violation occurs and the program crashes. When depth is `CV_16F` (=7), `getCmpFunc` becomes 0.
https://github.com/opencv/opencv/blob/master/modules/core/src/arithm.cpp#L1237
https://github.com/opencv/opencv/blob/master/modules/core/src/arithm.cpp#L1063
I added an assertion for CV_16F depth.

core: Fix cv::compare crash if src.depth() == CV_16F

---

modules/core/include/opencv2/core/version.hpp

relates #16078
<cut/>
<details>
[opencv_world420.dll (vc14)](https://www.virustotal.com/gui/file/1fe571c8faf3fc1c55bd91bcfa854eb25acec36e8dc6ff7f39ee35b8da3a8800/detection)
[opencv_world420d.dll (vc14)](https://www.virustotal.com/gui/file/3457fe06413f21b69ef3ee0c61e988e784f3cd25febbd5c56e255cece388394a/detection) 
[opencv_world420.dll (vc15)](https://www.virustotal.com/gui/file/ebf0e8976d76623addfd3f902ede9b9caf627b1f35018bc9a3002f2fe1c8e217/detection)
[opencv_world420d.dll (vc15)](https://www.virustotal.com/gui/file/76837bc159fa286f0f619165871ae9ebf8a397d036633763e6305b19004528c0/detection)
detections from `Trapmine: *.ml.score`, [considered false positive](https://stackoverflow.com/questions/54052224/virustotal-trapmine-suspicious-low-ml-score) …

release: OpenCV 4.2.0

---

modules/dnn/src/cuda/fill_copy.cu
modules/dnn/src/cuda/max_unpooling.cu
modules/dnn/src/cuda/normalize.cu
modules/dnn/src/cuda/permute.cu
modules/dnn/src/cuda4dnn/kernels/fill_copy.hpp
modules/dnn/src/cuda4dnn/kernels/permute.hpp
modules/dnn/src/cuda4dnn/primitives/concat.hpp
modules/dnn/src/cuda4dnn/primitives/padding.hpp

- upgrades the reduction logic to:
- eliminate singleton axes
- merge adjacent axes which do not change relative order
- do raw copy if the rank is reduced to one or if the order does not mandate permutation
It adds a new very efficient (on par with raw memory copy) transpose kernel which can be used when the reduction logic leads to rank two tensors.
In almost all cases, the permutation operation reduces to a transpose. Transpose is several times faster than permute kernel.
<cut/>
```
```

cuda4dnn(permute): improve reduction logic and add transpose kernel

---

modules/calib3d/src/calibration.cpp

When calling the `Rodrigues` function with a `4x4` (or any wrong size) matrix, the function does nothing and lets the destination matrix unitialized. This leads to this kind of confusion / issue: [SO issue](https://stackoverflow.com/questions/58969553)
---
Which strategy should be adopted to deal with bad arguments (maybe related #8300)?
Here the shape of the input source matrix is wrong, so it makes sense in my opinion to throw an error.
Otherwise, at least a debug mesage or trace log should be somehow recorded.
---
Also, unfortunately [people](https://stackoverflow.com/a/59398256) are still looking at, refering to the 2.4 documentation.

Add size check for Rodrigues() function 

---

modules/dnn/src/cuda4dnn/csl/cudnn/activation.hpp
modules/dnn/src/cuda4dnn/csl/cudnn/convolution.hpp
modules/dnn/src/cuda4dnn/csl/tensor_ops.hpp
modules/dnn/src/cuda4dnn/primitives/convolution.hpp

cuDNN supports conv + bias + relu fusion in some configurations. This PR enables this cuDNN optimized path whenever possible.
**Device:** GTX 1050
Model                               | without this patch | with this patch
--------------------------------- | ----------------------- | -------------------
Inception v2 MaskRCNN (1024x1024) | 187.6ms               | **180.3ms**

cuda4dnn(conv): use cudnn for conv + bias + relu fusion

---

modules/ml/src/rtrees.cpp

Currently the random number generator for training `cv::ml::RTrees` is seeded with a hardcoded value, which ensures that every forest trained with the same data yields identical results.
This PR adds a method for modifying the training seed per instance in order to allow training new or
additional solutions if desired.
Ultimately, this enables parallelized training / evaluation via forest subdivision. I.e. use `N` threads with `M` trees each instead of training a single `N*M` wide forest.
There are other benefits to this as well, like determining the variance of a model for a given set of hyperparameters.
**Update:** PR modified to make use of global `theRNG()` for `RTrees` training, making random forests random by default. Previous deterministic behavior is achieved by calling …

Allow controlling the random number generator for RTrees training

---

modules/dnn/src/cuda/grid_stride_range.hpp
modules/dnn/src/cuda4dnn/csl/cudnn/cudnn.hpp

- simplifies code to make older versions of MSVC happy
resolves #16260 
<cut/>
```
```

cuda4dnn(build): simplify code to help MSVC 19.10 and lower

---

samples/cpp/tutorial_code/gapi/face_beautification/face_beautification.cpp

resolves #16274
Corrected calls to std::vector.insert to use `end()` for the target iterator instead of `cend()`.
Ran all build and tests.

Fix vector insert

---

.gitignore
modules/java/android_sdk/android_gradle_lib/AndroidManifest.xml
modules/java/android_sdk/android_gradle_lib/build.gradle
modules/java/android_sdk/android_lib/AndroidManifest.xml
modules/java/android_sdk/build.gradle.in
modules/java/generator/android/java/org/opencv/android/OpenCVLoader.java

Currently you set Android version info in `AndroidManifest.xml` , but this is an old relict from Eclipse time. The Gradle way is to have this info in `build.gradle`
Btw, how you provide the Android release is very confusing at least to me. I was not able to test my pull request properly. To be honest, I would like a out-of-the-box running Android project within this repo and no `build.gradle.in` files and so on. Then we could much easier contribute to the Android part.

Android move version info to Gradle style

---

modules/dnn/src/cuda/fp_conversion.cu
modules/dnn/src/cuda4dnn/kernels/fp_conversion.hpp
modules/dnn/src/op_cuda.hpp

- performs fp conversions on GPU
- eliminates the costly intermediate host memory allocation required for every transfer involving fp16 data
<cut/>
```
Test Size = number of 32-bit floats
Test Size: 100
CPU Conversion H2D Time: 0.0088ms
GPU Conversion H2D Time: 0.0148ms
CPU Conversion D2H Time: 0.0077ms
GPU Conversion D2H Time: 0.0098ms
Test Size: 1000
CPU Conversion H2D Time: 0.0068ms
GPU Conversion H2D Time: 0.0147ms
CPU Conversion D2H Time: 0.0078ms
GPU Conversion D2H Time: 0.0098ms
Test Size: 10000
CPU Conversion H2D Time: 0.0125ms
GPU Conversion H2D Time: 0.0187ms
CPU Conversion D2H Time: 0.0140ms
GPU Conversion D2H Time: 0.0123ms
Test Size: 100000
CPU Conversion H2D Time: 0.0622ms
GPU Conversion H2D Time: 0.0496ms
CPU Conversion D2H Time: 0.0780ms
GPU Conversion D2H Time: 0.0423ms …
```

cuda4dnn: improve host-device transfer performance

---

modules/imgcodecs/src/utils.cpp

resolves #16215
- some of `icvCvt_BGR*` functions have R with B channels
swapped what leads to the wrong conversion
- renames misleading `rgb` variable name to `bgr`
- swap back the conversion coefficients, `cB` should be the first
- internal reference - nvbugs/2797421
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

Fix swapped channels in BGR* conversion utility function

---

CMakeLists.txt

When building OpenCV as a sub-project using cmake's add_subdirectory()
the OpenCV's build options would be overwritten to its default
state. With cmake 3.13+ the CMP0077 policy, option() honors previous
definitions via set().

Enable cmake CMP0077 policy

---

modules/videoio/src/backend_plugin.cpp

dl functions are provided by all glibc-based systems (GNU/Linux, but
also GNU/Hurd, GNU/kFreeBSD)

Fix build on non-Linux glibc-based systems

---

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/src/tensorflow/tf_importer.cpp

resolves https://github.com/opencv/opencv/issues/14634
There is no Const nodes in the text graphs because of weights so this patch applies sorting of TensorFlow graphs considering it.
```
```

Sort text TensorFlow graphs

---

modules/dnn/src/dnn.cpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/layers/concat_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_ie_models.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

* Skip some tests
* Lightweight detection of IE targets by @mshabunin 
* Added Concat layer with paddings (OpenFace)
* Fixed FP32 to FP16 conversion for weights
<cut/>
```
```

Update Myriad test of nGraph

---

modules/dnn/src/graph_simplifier.cpp
modules/dnn/src/graph_simplifier.hpp
modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/src/onnx/onnx_graph_simplifier.hpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves https://github.com/opencv/opencv/issues/15244
Share graphs simplification logic from TensorFlow importer to ONNX importer.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/694
```
```

ONNX graphs simplifier

---

modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/op_inf_engine.cpp

```cpp
ie.AddExtension(extension, "CPU");
```
is wrapped to try-catch so we need to do the same for
```cpp
ie.AddExtension(std::make_shared<InfEngineExtension>(), "CPU");
```
```
```

Wrap custom OpenCV layers to try-catch

---

modules/java/generator/android/java/org/opencv/android/OpenCVLoader.java.in

partially reverts #16222
Javadoc doesn't know about Gradle and its scripts.
Should fix nightly builds: http://pullrequest.opencv.org/buildbot/builders/master_pack-android

android: fix javadoc

---

modules/dnn/src/cuda/math.hpp

relates #16218
Fix: rsqrt(float) was improperly put in the ifdef for half

Fix: rsqrt(float) was improperly put in the ifdef for half

---

modules/dnn/src/cuda/shortcut.cu
modules/dnn/src/cuda4dnn/kernels/shortcut.hpp
modules/dnn/src/cuda4dnn/primitives/shortcut.hpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_layers.cpp

- adds layer described in #15724 to the CUDA backend
**Timings (on GTX 1050):**
Model                     | Darknet     | OpenCV CUDA
------------------------ | ------------- | --------------------
YOLOv3 Tiny PRN  | 6.727ms   | **5.94ms**
**Pending:**
- enable FP16 tests (disabled by PR16010)
**References:**
#15724 
#15739 
<cut/>
```
```

support eltwise sum with different number of input channels in CUDA backend

---

3rdparty/carotene/CMakeLists.txt
3rdparty/carotene/hal/CMakeLists.txt

gcc 10+ has renamed this option, therefore check for gcc version before
deciding which name to use for opt parameter

carotene: Replace ipcp-unit-growth with ipa-cp-unit-growth on gcc >= 10

---

modules/dnn/src/cuda/shortcut.cu

relates #16218
<cut/>
@YashasSamaga your latest commit added a new kernel on __half that wasn't ifdefed
```
docker_image:Custom=ubuntu-cuda-cc52:18.04
```

FIX: disable dnn cuda input_shortcut on _half for CC<5.3

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/misc/java/gen_dict.json
modules/dnn/misc/java/src/cpp/dnn_converters.cpp
modules/dnn/misc/java/src/cpp/dnn_converters.hpp
modules/dnn/misc/java/test/DnnTensorFlowTest.java
modules/dnn/misc/python/pyopencv_dnn.hpp
modules/dnn/misc/python/test/test_dnn.py

as requested by @dkurt here: https://github.com/opencv/opencv/pull/16184#issuecomment-569006520
<cut/>
```
```

add a wrapper for getAvailableTargets

---

modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/include/opencv2/core/hal/intrin_neon.hpp
modules/core/src/minmax.cpp
modules/core/test/test_intrin_utils.hpp

Vectorize minMaxIdx functions.
minMaxIdx_8u & minMaxIdx_8s - 11.1x improvement on VSX and 8.6x speedup on x86.
minMaxIdx_16u & minMaxIdx_16s - 8.3x improvement on VSX and 7.5x speedup on x86.
minMaxIdx_32s - 5.1x improvement on VSX and 4.2x speedup on x86.
minMaxIdx_32f - 4.1x improvement on VSX and 3.2x speedup on x86.
minMaxIdx_64f - 1.6x improvement on VSX and 1.5x speedup on x86.
<cut/>
```
force_builders=Custom,ARMv7
#buildworker:Custom=linux-1
#build_image:Custom=mips64el
#build_image:Custom=javascript-simd
disable_ipp=ON
```

Vectorize minMaxIdx functions

---

samples/android/15-puzzle/src/org/opencv/samples/puzzle15/Puzzle15Activity.java
samples/android/camera-calibration/src/org/opencv/samples/cameracalibration/CalibrationResult.java
samples/android/camera-calibration/src/org/opencv/samples/cameracalibration/CameraCalibrator.java

It fixes lint errors and warnings in Android samples.
Because library uses functions which requires camera permission, it makes more sense to move permissions to library instead of apply it to each sample separat

Fix lint issues in Android samples

---

modules/ts/src/ts.cpp

Avoid some hits (dnn models are downloaded under `opencv_extra` source tree)

ts: move message about misused 'optional' under the configuration parameter

---

modules/core/include/opencv2/core/hal/intrin_msa.hpp

fixes nightly builds: http://pullrequest.opencv.org/buildbot/builders/3_4_mips-msa-lin64/builds/113
relates #15488
Naive implementation. Performance is not tested.
/cc @mipsopen-fwu
<cut/>
```
```

core(SIMD): fix MSA build - add v_reduce_min/max for u8/s8

---

modules/videoio/src/precomp.hpp

resolves #15020
- "master" branch only
- GCC issue (Clang is fine)

build: workaround for FORTIFY_SOURCE=2 builds on Alpine

---

cmake/OpenCVCompilerOptions.cmake
cmake/OpenCVUtils.cmake

resolves #7001
<cut/>
Before:
```
$ ldd -u -r ./lib/libopencv_core.so
Unused direct dependencies:
/lib64/librt.so.1
$ ldd -u -r ./bin/opencv_test_core
Unused direct dependencies:
/home/alalek/projects/opencv/build/opencv/lib/libopencv_highgui.so.3.4
/lib64/libdl.so.2
/lib64/librt.so.1
/home/alalek/projects/opencv/build/opencv/lib/libopencv_videoio.so.3.4
/home/alalek/projects/opencv/build/opencv/lib/libopencv_imgcodecs.so.3.4
```
After:
```
$ ldd -u -r ./lib/libopencv_core.so
$ ldd -u -r ./bin/opencv_test_core
Unused direct dependencies:
/home/alalek/projects/opencv/build/opencv/lib/libopencv_highgui.so.3.4
/home/alalek/projects/opencv/build/opencv/lib/libopencv_imgcodecs.so.3.4
```
---
```
```

cmake: apply '-Wl,--as-needed' linker option

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/test/test_darknet_importer.cpp

**Merge with extra**:  https://github.com/opencv/opencv_extra/pull/698
This PR modifies the parsing of 'padding' for convolutional layers in darknet importer.
resolves #16259
```
opencv_extra=3.4modified
```

Convolutional padding parsing modified

---

modules/dnn/test/test_darknet_importer.cpp

relates #16358
<cut/>
Message:
```
[ RUN      ] Test_Darknet_layers.convolutional/1, where GetParam() = DLIE/MYRIAD
/build/precommit_custom_linux/3.4/opencv/modules/dnn/test/test_common.impl.hpp:66: Failure
Expected: (normL1) <= (l1), actual: 0.00510965 vs 0.004
Google Test trace:
/build/precommit_custom_linux/3.4/opencv/modules/dnn/test/test_darknet_importer.cpp:102: convolutional
/build/precommit_custom_linux/3.4/opencv/modules/dnn/test/test_common.impl.hpp:66: Failure
Expected: (normL1) <= (l1), actual: 0.00510965 vs 0.004
Google Test trace:
/build/precommit_custom_linux/3.4/opencv/modules/dnn/test/test_darknet_importer.cpp:122: batch size 2
/build/precommit_custom_linux/3.4/opencv/modules/dnn/test/test_darknet_importer.cpp:102: convolutional …
```

dnn(test): adjust test tolerance for MYRIAD

---

platforms/android/build_sdk.py

build_sdk.py, which compiles OpenCV-SDK for Android.
Added an option/parameter for build only selected modules (for Android), like a whitelist.
Care should be take to include modules which are required to others (this is not checked).
==============
call sample:
==============
python2 ../platforms/android/build_sdk.py \
--modules_list core,imgcodecs,improc \
~/projects/opencv/build \
~/projects/opencv

feat(android): add parameter for choose modules for android

---

modules/gapi/src/compiler/gstreaming.cpp

This PR fixes linkage of G-API library to some target in standalone mode.
The solution is pretty simple, yet maybe not so trim. Alternatively, we can move definitions and usage of functions from `gstreaming.cpp` under `#if !defined` in other files.
```
```

G-API: Fix linkage in standalone mode

---

modules/dnn/src/op_inf_engine.cpp

dnn: prevent unloading of InferenceEngine plugins

---

samples/dnn/object_detection.py

```
File "object_detection.py", line 234
if args.async:
^
SyntaxError: invalid syntax
```
https://github.com/opencv/opencv/issues/15403#issuecomment-526911163

samples(dnn): avoid 'async' keyword (Python 3.7+)

---

samples/cpp/text_skewness_correction.cpp
samples/python/text_skewness_correction.py

Given an image containing a rotated block of text at an unknown angle  in an image, it corrects the text skew by </br>
1. Detecting the block of text in the image .</br>
2. Computing the angle of the rotated text </br>
3. Rotating the image to correct for the skew. 
Before</br>
After</br>

added tutorial for text skewness correction

---

modules/videoio/src/cap_ffmpeg_impl.hpp
modules/videoio/test/test_ffmpeg.cpp

**Add the possibility to skip frames** in VideoCapture by using the existing `OPENCV_FFMPEG_CAPTURE_OPTIONS` environment variable and the `AVCodecContext::skip_frame` method.
**AVDiscard options are :** 
AVDISCARD_NONE : discard nothing
AVDISCARD_DEFAULT : discard useless packets like 0 size packets in avi
AVDISCARD_NONREF : discard all non reference
AVDISCARD_BIDIR : discard all bidirectional frames
AVDISCARD_NONKEY : discard all frames except keyframes
AVDISCARD_ALL : discard all
For example, if you want VideoCapture to capture only keyframes, you can set the env var :
`OPENCV_FFMPEG_CAPTURE_OPTIONS=avdiscard;nonkey`

Videocapture skip frames

---

modules/gapi/test/common/gapi_core_tests_inl.hpp

GAPI(test): update test tolerance for DIV operation on ARM

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/layers/layers_common.cpp
modules/dnn/src/layers/layers_common.hpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp
samples/dnn/human_parsing.py

**Merge with extra:** opencv/opencv_extra#695
```
```
**Example:**
Input  / Output

Add human parsing demo

---

cmake/OpenCVGenABI.cmake

To regenerate ABI/API snapshot of OpenCV 4.2.0 without G-API module
relates #16118

cmake: support OPENCV_ABI_SKIP_MODULES_LIST

---

cmake/checks/cpu_vsx_asm.cpp
modules/core/include/opencv2/core/hal/intrin_vsx.hpp
modules/core/include/opencv2/core/vsx_utils.hpp

resolves #16448
````
pw_compilers=gcc-4.9, gcc-5, gcc-6, power9_gcc-5, power9_gcc-6, power9_gcc-7, power9_gcc-8
````

core:vsx fix inline asm constraints

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/cap_aravis.cpp

If an aravis camera is set up to be software triggered, a trigger needs to be explicitly sent using `arv_camera_software_trigger`, otherwise the camera will not grab any frames.
`modules/videoio/src/cap_aravis.cpp` to support aravis cameras that are set up to be software triggered. Without this change, only hardware-triggered cameras (i.e. cameras receiving a clock/TTL signal to one of their input lines) can grab frames.
```
```

Support software triggering aravis cameras

---

modules/core/include/opencv2/core/vsx_utils.hpp

resovles #16455
workaround for the unexpected results of `vec_vbpermq` in gcc4.9
````
pw_compilers=gcc-4.9
````

core:vsx workaround for the unexpected results of `vec_vbpermq`

---

modules/imgproc/src/connectedcomponents.cpp
modules/imgproc/test/test_connectedcomponents.cpp

resolves #16410
Here is what is happening. In order to do the parallelization, the image is split in stripes and labelling is done on each stripe. In order for stripes to be independent, each stripe starting at height `y` and with width `w` gets a startLabel defined as:
`startLabel = (y+1)/2 * (w+1)/2 + 1`
The formula comes from the fact that for an image of height `h` and width `w`,  an upper bound of the number of labels is: `(h+1)/2 * (w+1)/2 + 1`
The startLabels are too close to each other in some cases and create labels overlapping. Here is why:
let's say a stripe starts in `y0` and finishes in `y1`, we can write
`y0 = 2*y + 1` and `y1 = 2*y + 1 + h`
The maximum number of labels is `(h+1)/2 * (w+1)/2 + 1`
The number of labels for the stripe is: 
`( (2*y+1+h+1)/2 * (w+1)/2 + 1  ) - ( …

Fix bug 16410 and add test

---

modules/dnn/src/cuda/roi_pooling.cu
modules/dnn/src/cuda4dnn/kernels/roi_pooling.hpp
modules/dnn/test/test_layers.cpp

- computes pooling window in full precision (as half precision leads to dramatically inaccurate ROIs)
- processes multiple channels every iteration (4.8x performance improvement on GTX 1050)
<cut/>
```
#docker_image:Custom=ubuntu-cuda-cc52:18.04
```

cuda4dnn(ROIPooling): improve FP16 accuracy and optimize

---

modules/core/include/opencv2/core/cvdef.h

`<limits.h>` -> `<limits>` in C++ mode, just like with the other headers in the rest of the file.
See e.g. [StackOverflow](https://stackoverflow.com/questions/36831465/what-difference-does-it-make-when-i-include-limits-or-limits-h-in-my-c-cod) for the reasons, the most important one being that limits.h does not respect namespaces, which can make problems for downstream consumers of `cvdef.h`.
<cut/>
```
```

cvdef.h: Don't use C's limits.h under C++

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/cap.cpp

Changes:
- Added `explicit` to `VideoCapture` constructors with 2
arguments, 1 of them has default value
- Applied library code style
- Introduced 2 debug macros to improve readability of the code

VideoIO classes refactoring

---

modules/calib3d/include/opencv2/calib3d.hpp

 This is a correction of the previously missleading documentation and a warning related to a common calibration failure described in issue #15992

---

modules/core/include/opencv2/core/types.hpp

resolves #16336
The `main.cpp` will occur the compilation warnings. The reason is at the [modules/core/include/opencv2/core/types.hpp#L1218](https://github.com/opencv/opencv/blob/7fa7fa02264eb2faed638947a5673839da386743/modules/core/include/opencv2/core/types.hpp#L1218)
<cut/>
Assume a file calls `main.cpp` as below
```
#include <opencv2/core/types.hpp>
int main(void) {
return 0;
}
```
If the developer enables the `g++` flags `-Wall -Wdouble-promotion` in the compilation, `g++` will output the following warning messages and generate a ELF file.
```
warning: implicit conversion from ‘float’ to ‘double’ to match other operand of binary expression [-Wdouble-promotion]
1218 |     return (double)x*pt.x + (double)y*pt.y;
|            ~~~~~~~~~^~~~~
warning: implicit conversion from ‘float’ to …
```

Fixed Compilation warnings | Issue #16336

---

cmake/OpenCVUtils.cmake

resolves #16458 
In issue #16458 someone used gcc 10 to build OpenCV and found some warnings were not ignored. Adjusting OpenCVUtils.cmake as per @alalek  's suggestion.

Issue 16458

---

modules/gapi/include/opencv2/gapi/gkernel.hpp
modules/gapi/include/opencv2/gapi/infer.hpp

continues #15840
Unifies macro `G_TYPED_KERNEL` and `G_TYPED_KERNEL_M` (by re-using mechanism introduced in Inference API).
Now can always use `G_TYPED_KERNEL` for any of G-API Kernel at the API level.
TODOs:
```
```

G-API: unify G_TYPED_KERNEL and G_TYPED_KERNEL_M

---

modules/imgproc/src/resize.cpp

resolves #16501
relates #15257
drop optimization for channels>4:
- zero test [coverage](http://pullrequest.opencv.org/buildbot/export/opencv_releases/3_4_coverage-lin64-debug/20200204-015011_648/coverage_html/opencv/modules/imgproc/src/resize.cpp.gcov.html)
- not a part of usual pipelines (out of optimization scope)

imgproc(resize): avoid OOB access

---

modules/imgcodecs/src/loadsave.cpp

resolves #15155
imwrite_ now describes permission denied error when a user does not have write permission in directory.
<cut/>
Example:
```python
import cv2
img = 255*np.ones((100,100),dtype=np.uint8)
#writing in permissible directory
ret = cv2.imwrite('myImage.png',img)
print('imwrite returned: ',ret)
#writing in non permissible directory
ret = cv2.imwrite('/myImage.png',img)
print('imwrite returned: ',ret)
```
Code Output:
```
imwrite returned:  True
[ WARN:0] imwrite_('/myImage.png'): can't open file for writing: permission denied
imwrite returned:  False
```

fixes #15155

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp

resolves #15786
Made documentation for this flag more complete by noting that it tells `imread()` to ignore the image's EXIF orientation. If anyone has suggestions about how to phrase this better, I will be glad to update this PR.

improved documentation for IMREAD_UNCHANGED flag

---

modules/gapi/include/opencv2/gapi/gkernel.hpp

is a follow-up on  #16496:
- Deprecates `G_TYPED_KERNEL_M` in the documentation
- Removes `G_TYPED_KERNEL_M_HELPER*` - these are not needed anymore since `_M` and non-`_M` versions are unified
<cut/>
``` …
```

G-API: deprecate G_TYPED_KERNEL_M and clean up redundant code

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp

resolves #15786
Added `IMREAD_UNCHANGED` to the list of flags that ignores EXIF orientation in the `imread()` documentation. Tested: built with cmake and generated documentation with doxygen.

improved documentation for imread()

---

modules/calib3d/src/stereobm.cpp
modules/core/include/opencv2/core/utils/buffer_area.private.hpp
modules/core/src/buffer_area.cpp
modules/core/test/test_utils.cpp

Introduces `cv::util::BufferArea` class automating creation of structured memory areas for local memory buffers.
<cut>
There are two modes: _safe_ and _unsafe_. In safe mode each allocation is performed immediately, in unsafe mode (default) single large buffer will be allocated during the call to commit and all pointers will be set to appropriate locations inside this buffer. Safe mode can be forced at runtime by constructor parameter for one specific object or using an environment variable for all objects (`OPENCV_BUFFER_AREA_ALWAYS_SAFE`). Safe mode will also be forced for sanitizer-enabled builds.
Single buffer split into several smaller ones is used in several algorithms to reduce memory allocations for better performance. However this approach does not allow to catch OOB access using …

Local memory pool experiment

---

modules/core/include/opencv2/core/cvdef.h
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/src/copy.cpp
modules/dnn/src/onnx/onnx_importer.cpp

Should be used to guard unsafe type casts of pointers.
Some platforms requires that.
relates #16373 #16152 #16139 #14281 #12961

core: CV_STRONG_ALIGNMENT macro

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra**: [opencv/opencv_extra#704](https://github.com/opencv/opencv_extra/pull/704)
resolves #16337
Setting of end Mat values using tensor_content of "cropping2d/strided_slice/stack_1" from pbtxt file. 
`opencv_extra=opencv_extratf`
```
```

TF importer: Corrected end tensor_content parsing for StridedSlice layer.

---

cmake/OpenCVFindLibsPerf.cmake

resolves #16326
Just a workaround. Appropriate fix requires rebuild of IPPICV binaries.
```
```

cmake: hide IPPICV symbols using --exclude-libs

---

modules/videoio/src/cap_msmf.cpp
modules/videoio/test/test_video_io.cpp

resolves #12822
* removed unused functions and tables
* refactored class `MediaType`, removed unused fields, renamed others, added several methods for convenience, added operator<< for debugging
* extracted format enumeration and choosing logic to separate class `FormatStorage`
* extracted device enumeration to class `DeviceList`
* extracted methods to be used in property access methods
* issue have been fixed by selecting native format first (the one returned by device) and requested format after that (format that we will use)
* added early break to videoio frame reading tests in case of failure

MSMF: refactored format handling and property access

---

modules/cudacodec/src/cuvid_video_source.hpp
modules/cudacodec/src/frame_queue.hpp
modules/cudacodec/src/precomp.hpp
modules/cudacodec/src/video_decoder.hpp
modules/cudacodec/src/video_parser.hpp

Fix: cudacodec building problem with CUDA 10

---

modules/dnn/src/dnn.cpp

- don't require `.setInput()` before `.dump()`
- dump networks before and after `.setUpNet()` through parameter
- coding style changes in `.dump()` (tab => `\t`, indentation, "const").
<cut/>
```
```

DNN: update network dump

---

modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/hough.cpp
modules/imgproc/test/test_houghcircles.cpp

relates #16187 (on one image the eye is not detected with param2=0.9, need to lower it down to 0.85). Overall, the quality is much better than the existing HOUGH_GRADIENT method.
Usage:
```
Mat smoothed;
GaussianBlur(grayscale_image, smoothed, Size(7, 7), 1.5, 1.5);
HoughModes method = HOUGH_GRADIENT_ALT;
double dp = 1.5;
double minDist = 10;
double cannyThreshold = 300;
double minCos2 = 0.9; // 0.85 for one of the eye images
int minRadius = 7;
int maxRadius = 500;
std::vector<Vec3f> circles;
HoughCircles(smoothed, circles, method, dp, minDist,
cannyThreshold, minCos2, minRadius, maxRadius);
```
this code detects circles on most of the images that I have (~100 images; the proper regression test will be added later). When it does not, try to narrow down the radius search range `[minRadius, …

improved version of HoughCircles (HOUGH_GRADIENT_ALT method)

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/701
resolves #16370 
This Pull Request aims to fix ONNXImporter. Currently, there are few bugs in processing of various `layer_type` from `.onnx` files. The referenced issue reports a bug in `Split` layer. Though I have observed that there are more bugs. I have listed them below as tasks. I will update them every commit.
``` …
```

Fixed ONNXImporter

---

modules/imgproc/src/resize.cpp
modules/imgproc/test/test_imgwarp.cpp

reverts #16497
Avoid OOB buffer access.
```
[ RUN      ] Resize.nearest_regression_15075
==13146== Invalid write of size 4
==13146==    at 0x4DC1994: cv::resizeNNInvoker::operator()(cv::Range const&) const (resize.cpp:1049)
==13146==    by 0x6AD674C: parallel_for_impl(cv::Range const&, cv::ParallelLoopBody const&, double) (parallel.cpp:498)
==13146==    by 0x6AD6600: cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double) (parallel.cpp:471)
==13146==    by 0x4DC1D5C: cv::resizeNN(cv::Mat const&, cv::Mat&, double, double) (resize.cpp:1105)
```

imgproc: revert resize changes from PR 16497

---

modules/calib3d/src/fundam.cpp

resolves #10643
- [ x ] I agree to contribute to the project under OpenCV (BSD) License.
- [ x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ x ] The PR is proposed to proper branch
- [ x ] There is reference to original bug report and related work
- [ x ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ x ] The feature is well documented and sample code can be built with the project CMake
Attempting to fix the bug issued in #10643, I just copied (modified a few lines) from the normalization part of 8p …

Apply normalization to 7p algorithm.

---

modules/dnn/src/caffe/caffe_importer.cpp

resolves https://github.com/opencv/opencv_contrib/issues/2426
relates #15203
subset of #16616
<cut/>
```
```

dnn(caffe): fix net.input_dim handling in Caffe importer

---

modules/dnn/src/dnn.cpp
modules/dnn/src/op_cuda.hpp

- optimizes out concat layer by forcing the layers providing input to the concat to directly write to the corresponding section of concat's output
<cut/>
```
```

cuda4dnn(concat): write outputs from previous layers directly into concat's output

---

modules/dnn/src/dnn.cpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/layers/crop_and_resize_layer.cpp
modules/dnn/src/layers/scale_layer.cpp
modules/dnn/test/test_tf_importer.cpp

resolves https://github.com/opencv/opencv/issues/14509
* Enable Mask R-CNN tests
* For nGraph API model is fully convertible to IE backend
```
```

Enable Mask R-CNN with Inference Engine.

---

modules/core/src/copy.cpp
modules/core/src/ocl.cpp
modules/core/src/opencl/flip.cl
modules/imgproc/src/pyramids.cpp
modules/imgproc/test/test_histograms.cpp

* failures in ocl_pyrUp
* failures in ocl_flip when processing CV_16UC3 or CV_16SC3 data
* some basic UMat tests; `Mat => UMat => Mat` chain did not work properly on Discrete video cards.
* One of histogram badarg tests tried to access the 2nd element of 1-element input array. Most of the time it worked fine, because the function reported the expected error because of some other bad arg, but sometimes it crashed on histogram allocation when the size was valid but huge.
```
force_builders=Custom Mac,Custom
```

fixed several problems when running tests on Mac

---

modules/core/include/opencv2/core/hal/intrin_avx512.hpp

related #15510
Wrong intrinsics were used in AVX-512 without DQ fallback implementation.
```
disable_ipp=ON
```

intrin: fixed int64->double conversion for AVX-512

---

modules/imgproc/misc/java/test/ImgprocTest.java
modules/imgproc/src/convhull.cpp
modules/imgproc/test/test_convhull.cpp

Fixes issue #14521.
Partially fixes the issue #4539.
1. if possible, the convex hull indices are "rotated" to form a monotonous sequence, decreasing or increasing.
2. added the check to convexityDefects to check that the indices are monotonous; if not, an exception is thrown
3. added the test from #4539 discussion with a workaround (to eliminate the contour self-intersection). With this workaround everything works well.

fixed the ordering of contour convex hull points

---

modules/core/include/opencv2/core/matx.hpp
modules/core/test/test_operations.cpp

Add the following operations for `Matx`:
<cut/>
```
{
Matx31d P1(1, 2, 3);
P1 /= 2;
std::cout << "P1: " << P1.t() << std::endl;
}
{
Matx31d P1(1, 2, 3);
P1 /= 2.0f;
std::cout << "P1: " << P1.t() << std::endl;
}
{
Matx31d P1(1, 2, 3);
P1 /= 2.0;
std::cout << "P1: " << P1.t() << std::endl;
}
{
Matx31d P1(1, 2, 3);
P1 = P1 / 2;
std::cout << "P1: " << P1.t() << std::endl;
}
{
Matx31d P1(1, 2, 3);
P1 = P1 / 2.0f;
std::cout << "P1: " << P1.t() << std::endl;
}
{
Matx31d P1(1, 2, 3);
P1 = P1 / 2.0;
std::cout << "P1: " << P1.t() << std::endl;
}
{
Matx31d P1(1, 2, 3);
std::cout << "P1: " << (P1 / 2).t() << std::endl;
}
{
Matx31d P1(1, 2, 3);
std::cout << "P1: " << (P1 / 2.0f).t() << std::endl;
}
{
Matx31d P1(1, 2, 3);
std::cout << "P1: " << (P1 / 2.0).t() << std::endl;
}
```
Output:
```
P1: [0.5, …
```

Add division operators for Matx.

---

modules/dnn/src/model.cpp
modules/dnn/test/test_model.cpp

resolves #16204 , if merged with https://github.com/opencv/opencv_extra/pull/692
insert (-1,-1) keypoints in case of low probability, instead of skipping them.

dnn: small fix in pose estimation model

---

modules/core/include/opencv2/core/check.hpp
modules/core/src/check.cpp
modules/core/src/matrix_wrap.cpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/include/opencv2/dnn/shape_utils.hpp
modules/dnn/src/caffe/caffe_importer.cpp
modules/dnn/src/dnn.cpp
modules/dnn/test/test_misc.cpp

resolves #16618
- ~~importer(caffe): fix `net.input_dim` handling~~ (moved to #16617)
- importers: avoid using of `setInput()` => `setInputShape()`
- setInput(): shape limitation check (partial)
<cut/>
```
```

dnn: fix processing of input shapes

---

doc/tutorials/videoio/video-input-psnr-ssim/video_input_psnr_ssim.markdown
samples/cpp/tutorial_code/videoio/video-input-psnr-ssim/video-input-psnr-ssim.cpp
samples/python/tutorial_code/videoio/video-input-psnr-ssim.py

This PR adds the python version of [this](https://docs.opencv.org/master/d5/dc4/tutorial_video_input_psnr_ssim.html) tutorial.

add  python version of video-input-psnr-ssim

---

modules/dnn/src/cuda4dnn/primitives/inner_product.hpp

Resolves a problem mentioned in https://github.com/opencv/opencv/issues/16568#issuecomment-589473657
```
```

cuda4dnn(InnerProduct): fix blob rank check assertion

---

modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

Skip some tests which fails on Win32 32-bit configuration.
[Nightly build with failures](http://pullrequest.opencv.org/buildbot/builders/3_4-win32-vc14/builds/660).
<cut/>
```
build_image:Custom Win=msvs2015-win32
```

dnn(test): configure filtering for 32-bit systems

---

modules/dnn/src/op_cuda.hpp

cuda4dnn: resize tensors on reuse if the allocated memory isn't sufficient for reuse

---

modules/dnn/src/darknet/darknet_io.cpp

Merge with extra: [opencv/opencv_extra#714](https://github.com/opencv/opencv_extra/pull/714)
resolves #16623  
`opencv_extra=cvdarknet`
Parsing for `[cost]` layer in darknet_io. Modifications are made to treat `[cost] `layer as `identity` layer.

Darknet_io: Parsing for cost layer added

---

cmake/OpenCVPackaging.cmake
include/opencv2/opencv.hpp
modules/core/include/opencv2/core/persistence.hpp

ABI dump for 4.2.0 should be updated too.

build: exclude opencv_contrib modules

---

modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/test/common/gapi_compoundkernel_tests.cpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/common/gapi_operators_tests_inl.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/gapi_basic_hetero_tests.cpp
modules/gapi/test/gapi_fluid_parallel_rois_test.cpp
modules/gapi/test/gapi_fluid_resize_test.cpp
modules/gapi/test/gapi_fluid_roi_test.cpp
modules/gapi/test/gapi_fluid_test.cpp
modules/gapi/test/gapi_gcomputation_tests.cpp
modules/gapi/test/gapi_opaque_tests.cpp
modules/gapi/test/gapi_planar_test.cpp
modules/gapi/test/gapi_sample_pipelines.cpp
modules/gapi/test/gapi_scalar_tests.cpp
modules/gapi/test/gapi_smoke_test.cpp
modules/gapi/test/gapi_typed_tests.cpp
modules/gapi/test/internal/gapi_int_executor_tests.cpp
modules/gapi/test/internal/gapi_int_recompilation_test.cpp
modules/gapi/test/own/mat_tests.cpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp
modules/gapi/test/test_precomp.hpp

Misused `countNonZero()` (banned for future use)
**Review the latest commit only.**
opencv_test_gapi: 646 FAILED TESTS
opencv_perf_gapi: 96 FAILED TESTS
Message example:
```
[ RUN      ] GCompoundKernel.MergeWithSplit
C++ exception with description "OpenCV(4.2.0-dev) /build/precommit_opencl_linux/opencv/modules/core/src/count_non_zero.dispatch.cpp:124: error: (-215:Assertion failed) cn == 1 in function 'countNonZero'
[  FAILED  ] GCompoundKernel.MergeWithSplit (0 ms)
```
relates #16656

G-API: fix test checks due MatExpr::type() bug

---

modules/dnn/src/dnn.cpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/ie_ngraph.hpp
modules/dnn/src/layers/const_layer.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

wrap OpenCV layers which are not supported by Inference Engine backend to nGraph ops. It will let us to remove old API completely.
```
```

Custom layers with nGraph

---

modules/gapi/samples/privacy_masking_camera.cpp

resolves #16680
Compiling solution locally fixes warning. Solution is untested.

Fix annoying compiler warning issue-16680

---

modules/dnn/test/test_model.cpp

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master_openvino-skl-lin64/builds/583)
<cut/>
Message with NCS - Myriad2:
```
[ RUN      ] Test_Model.Keypoints_face/3, where GetParam() = NGRAPH/MYRIAD
/build/master_openvino-skl-lin64/opencv/modules/dnn/test/test_common.impl.hpp:70: Failure
Expected: (normL1) <= (l1), actual: 0.000332259 vs 0.0001
/build/master_openvino-skl-lin64/opencv/modules/dnn/test/test_common.impl.hpp:73: Failure
Expected: (normInf) <= (lInf), actual: 0.00166094 vs 0.0001
[  FAILED  ] Test_Model.Keypoints_face/3, where GetParam() = NGRAPH/MYRIAD (133 ms)
```
NCS 2 - MyriadX:
```
[ RUN      ] Test_Model.Keypoints_face/3, where GetParam() = NGRAPH/MYRIAD
/build/precommit_custom_linux/opencv/modules/dnn/test/test_common.impl.hpp:70: Failure
Expected: …
```

dnn(test): adjust check tolerance in Keypoints_face

---

modules/dnn/test/test_tf_importer.cpp

A test added in #16595 fails on CUDA_FP16 target. This PR disables that test.
One detection has a very high error of 0.25 in the score which prevents this test from being enabled.
```
[ RUN      ] Test_TensorFlow_nets.Mask_RCNN/1, where GetParam() = CUDA/CUDA_FP16
Unmatched prediction: class 0 score 0.997070 box [0.067256 x 0.266426 from (0.188563, 0.364286)]
/home/yashas/Desktop/gsoc/opencv/modules/dnn/test/test_common.impl.hpp:130: Failure
Value of: matched
Actual: false
Expected: true
Unmatched prediction: class 2 score 0.986328 box [0.154388 x 0.198076 from (0.654859, 0.455821)]
/home/yashas/Desktop/gsoc/opencv/modules/dnn/test/test_common.im …
```

cuda4dnn(tests): disable MaskRCNN test for DNN_TARGET_CUDA_FP16

---

modules/highgui/src/window_QT.cpp
modules/highgui/src/window_QT.h
modules/highgui/src/window_QT.qrc

Adds "copy to clipboard" button to `imshow` window if opencv was built with Qt.
Tested on Windows 10, MACOS 10.14.6, Xubuntu 18.04.2, Qt 5.11.xx.
```
```

add Copy to clipboard functional to imshow wnd with Qt

---

modules/imgproc/src/sumpixels.simd.hpp

Vectorize calculating integral for line for single and multiple channels - up to 2.75x faster.
<cut/>
```
disable_ipp=ON
```

Vectorize calculating integral for line for single and multiple channels

---

modules/videoio/src/cap_v4l.cpp

V4L2: Add V4L2_PIX_FMT_Y12 (12 bit grey) support

---

cmake/OpenCVCompilerOptions.cmake
modules/core/include/opencv2/core/mat.inl.hpp

Recent versions of `clang` emit warnings for deprecated `enum` + `other_enum` expressions ([Compiler Explorer Example](https://godbolt.org/z/KDQL6c)). 
`mat.inl.hpp` relies quite extensively on those expressions for joining flags, which shows when using OpenCV with the latest Emscripten release for example.
As a least-intrusive option, I added a local `clang diagnostic ignored` pragma for this warning type.
```
```

Ignore clang warnings for deprecated enum+enum operations in mat.inl.hpp

---

samples/cpp/3calibration.cpp
samples/cpp/calibration.cpp
samples/cpp/camshiftdemo.cpp
samples/cpp/contours2.cpp
samples/cpp/convexhull.cpp
samples/cpp/cout_mat.cpp
samples/cpp/delaunay2.cpp
samples/cpp/detect_blob.cpp
samples/cpp/detect_mser.cpp
samples/cpp/digits.cpp
samples/cpp/distrans.cpp
samples/cpp/drawing.cpp
samples/cpp/edge.cpp
samples/cpp/facedetect.cpp
samples/cpp/facial_features.cpp
samples/cpp/fback.cpp
samples/cpp/ffilldemo.cpp
samples/cpp/fitellipse.cpp
samples/cpp/grabcut.cpp
samples/cpp/image_alignment.cpp
samples/cpp/laplace.cpp
samples/cpp/letter_recog.cpp
samples/cpp/matchmethod_orb_akaze_brisk.cpp
samples/cpp/morphology2.cpp
samples/cpp/segment_objects.cpp
samples/cpp/select3dobj.cpp
samples/cpp/stereo_calib.cpp
samples/cpp/stereo_match.cpp
samples/cpp/stitching_detailed.cpp
samples/cpp/tree_engine.cpp

In some sample files, when display usage, it will use the cpp files' name as binary executable files' name.  However, it should be actual file name. So I use the `argv[0]`  instead of cpp files' name.
<cut/>
For example,  sample files code as follows.
```C++
static void help()
{
printf("\nThis sample demonstrates Canny edge detection\n"
"Call:\n"
"    /.edge [image_name -- Default is fruits.jpg]\n\n");
}
```
Now, I update it to:
```C++
static void help(char** argv)
{
printf("\nThis sample demonstrates Canny edge detection\n"
"Call:\n"
"    %s [image_name -- Default is fruits.jpg]\n\n", argv[0]);
}
```
```
force_builders=docs,linux,windows,mac
```

Using argv[0] represent binary executable files' name in help() function in sample codes instead of cpp files' name.

---

modules/dnn/test/test_onnx_importer.cpp

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_openvino-skl-lin64/builds/596).
<cut/>
```
```

Skipped ResizeUnfused test on Builder API

---

modules/gapi/test/gapi_opaque_tests.cpp

This fixes Static Analyses issues in G-API tests. 
` MyCustomType::num` member is not initialized by default, because: 
- it is  built-in type
- it has no (c++11 style) default member initializer 
- class `MyCustomType` has no user-defined default constructor 
So KW is right here , and some  kind of initialization should be added
@dmatveev  please review 
@smirnov-alexey , FYI

KW: G-API tests - fixes for uninitialized variables

---

modules/videoio/src/cap_msmf.cpp

resolves #16711
Default resolution for camera is set to `640x480`, if camera supports only greater resolutions, the detection process fails to select them because starting value of `0x0` is considered closer to `640x480` than to e.g. `1920x960`.

MSMF: fixed issue with camera format selection

---

modules/dnn/src/graph_simplifier.cpp
modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves #16707 
**Merge with extra**: [opencv/opencv_extra#719](https://github.com/opencv/opencv_extra/pull/719)
`opencv_extra=cvonnx`
1. Gather-Cast subgraph fusion
2. Mul-Cast subgraph fusion
Different Pytorch versions create different subgraphs, according to what I have observed till now, the difference is only because of presence or absence of cast layer after Gather and Mul layer. The idea is to fuse Gather-Cast and Mul-Cast . Hence presence or absence of Cast layer wouldn't make any affect on loading of model.
Below attached, three different subgraphs obtained using same code but different pytorch versions. Producer of Fast style transfer models is Pytorch 1.1, which is middle subgraph in attached image . PR …

ONNX: Add support for Style trasfer models, ONNX model zoo

---

modules/python/src2/hdr_parser.py
modules/python/test/test_umat.py

The hard-coded string value "Mat" was used in the two format strings for vector_mat and vector_mat_template, preventing UMat arguments to functions that have these types from working correctly. as noted in #12231.
resolves #12231

Use argument value for 'mat' in call to format for vector_mat and vector_mat_template

---

modules/core/include/opencv2/core/utils/logger.hpp
modules/core/src/logger.cpp
modules/core/test/test_utils.cpp

Added macros:
- `CV_LOG_ONCE_xxx(tag, ...message)`
- `CV_LOG_IF_xxx(tag, logging_condition, ...message)`

core(logger): add CV_LOG_ONCE_xxx() CV_LOG_IF_xxx() macros

---

modules/gapi/src/api/render.cpp

Integer parameters to Drawing primitives require definitions from `imgproc.hpp` which is not included by default.
`#include <opencv2/imgproc.hpp>` already exists in `render.hpp`
Removed `#include <opencv2/imgproc.hpp>`  from `render.cpp`

G-API: Include <imgproc.hpp> to <render.hpp>

---

modules/gapi/include/opencv2/gapi/own/mat.hpp
modules/gapi/test/own/mat_tests.cpp

Method `create(...)` throw exception in this case now.
cv::Mat checks the dimensions in `setSize(...)`. If the dimension is less then 0, it throws exception. own::Mat checks `size.height` and `size.width` in `create(...)` and throws exception if dimension is less then 0.
Added test for this case.

G-API: Fix. own::Mat successfully creates a {-1, -1} mat.

---

modules/core/include/opencv2/core/cuda.hpp
modules/core/include/opencv2/core/cuda.inl.hpp
modules/core/src/cuda_stream.cpp
modules/python/test/test_cuda.py

This is a proposal for adding `CV_WRAP` compatible `cudaPtr()` getter methods to `GpuMat` and `Stream`, required for enabling interoperability between **OpenCV** and other CUDA supporting python libraries like **Numba**, **CuPy**, **PyTorch**, etc.
<cut/>
Here is an example for sharing a `GpuMat` with **CuPy**:
```python
import cupy as cp
data_gpu_cv = cv.cuda_GpuMat()
data_gpu_cv.upload(np.eye(64, dtype=np.float32))
data_gpu_cp = cp.asarray(CudaArrayInterface(data_gpu_cv))
data_gpu_cp *= 42.0
assert np.allclose(data_gpu_cp.get(), np.eye(64) * 42.0)
```
In this example `CudaArrayInterface` is a (incomplete) adapter class that implements the [cuda array interface](https://numba.pydata.org/numba-doc/dev/cuda/cuda_array_interface.html) used by other frameworks:
```python …
```

Allow access to CUDA pointers for interoperability with other libraries

---

modules/core/src/ocl.cpp

Fix for an issue encountered while testing opencv master with a WIP backend of [pocl](http://www.portablecl.org/):
clGetSupportedImageFormats returns CL_INVALID_VALUE if called with
num_entries set to 0 and a non-NULL image_formats pointer. The old code will do this if no formats for a given type are available.

core(ocl): Don't query image formats when none exist

---

modules/core/include/opencv2/core/cvstd.inl.hpp

ToT libc++ (LLVM) no longer includes `<sstream>`
as part of `<complex>` which breaks building opencv.
Include `<sstream>` header explcitly to fix this.
<cut/>

Fix building with ToT libc++

---

modules/imgcodecs/src/grfmt_jpeg.cpp

Standard huffman tables are handled by modern libjpeg-turbo:
https://github.com/libjpeg-turbo/libjpeg-turbo/commit/a113506d175d03ae0e40965c3d3d21a5d561e119
Test image is available here (~500Kb): https://github.com/image-rs/jpeg-decoder/issues/76

imgcodecs(jpeg): drop unnecessary code

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/test/test_darknet_importer.cpp

resolves #15987
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/711
- adds support for grouped convolutions
- adds new activations
- sigmoid
- swish
- adds support for scale channels
<cut/>
**Prediction using OpenCV CPU backend:**
**Darknet Reference:**
```
tvmonitor: 44%
dog: 78%
cat: 27%
bicycle: 58%
truck: 89%
car: 33%
```
<cut/>
```
```

dnn(darknet-importer): add grouped convolutions, sigmoid, swish, scale_channels

---

modules/gapi/include/opencv2/gapi/gproto.hpp
modules/gapi/src/api/gproto.cpp
modules/gapi/src/compiler/gcompiled.cpp
modules/gapi/test/own/mat_tests.cpp

cv::GMat in;
cv::GMat a, b, c, d;
std::tie(a, b, c, d) = cv::gapi::split4(in);
cv::GMat out = cv::gapi::merge3(a, b, c);   
// Zero-height in_mat
cv::Mat in_mat(cv::Size(8, 0), CV_8UC4);
cv::Mat out_mat(cv::Size(8, 8), CV_8UC3);
cv::GComputation comp(cv::GIn(in), cv::GOut(out));
comp.apply(cv::gin(in_mat), cv::gout(out_mat),
cv::compile_args(cv::gapi::core::fluid::kernels()));
It crashed in `physIdx(int logIdx)` from gfluidbuffer_priv.h ( Fluid backend ), because we use `(logIdx - m_roi.y) % m_data.rows`, when m_data.rows == 0 ( Segmentation fault ).
Added GAPI_Assert for this case.

G-API: Zero-height mat is cause of crash

---

modules/dnn/CMakeLists.txt
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/op_inf_engine.cpp

<cut/>
```
Xtest_modules:Custom=dnn,python2,python3,java
```

DNN(IE): switch to nGraph backend by default

---

3rdparty/ffmpeg/ffmpeg.cmake

ffmpeg/3.4: update FFmpeg wrapper

---

modules/core/src/parallel.cpp
modules/ts/src/ts.cpp

relates #16457
- cache value, evaluate once
- better support for MINGW
- anything in 'cv' namespace
- test: dump number of active threads

core: update CPUs detection

---

modules/gapi/src/backends/fluid/gfluidimgproc.cpp

"Unsafe" `memcpy` were replaced with "safe" :) `std::copy_n` to make static analysis  happy

GAPI - KW fixes - - replace "unsafe" memcpy with "safe" :) std::copy_n to make KW happy

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/fundam.cpp

Lets the user choose the maximum number of iterations the robust
estimator runs for, similary to findHomography. This can significantly
improve performance (at a computational cost).
I've benchmarked different RANSAC variants for a paper I've been working on. It's also part of an open challenge on local features and robust matchers: you can find a lot more information [on the website](https://vision.uvic.ca/image-matching-challenge/). OpenCV performs quite poorly compared with other methods, and the main reason is that it caps the maximum number of iterations to 1000, which is a very conservative value. This parameter is exposed by APIs (e.g. homography estimation) but not others.
To show why this matters, I ran some experiments on the validation set for the benchmark, with 2000 SIFT …

Expose maxIters in findFundamentalMat

---

cmake/OpenCVModule.cmake

Goal is tuning of build process for OpenCV accuracy tests:
- speedup through applying `-O1` instead of regular `-O3`/`-O2`
- add extra debug symbols
- or smaller size (`-Os`)
- emulate user's `-ffast-math`
- etc
<cut/>
Results (i5-6600, PCH and ccache are OFF, "-O1" override, GCC 9):
- opencv_test_core: 1:47.16 => 1:13.43
- opencv_test_gapi: 1:24.94 => 1.01:04

cmake: allow extra compile options for tests

---

3rdparty/ffmpeg/ffmpeg.cmake

- ffmpeg 4.2.2
- libvpx 1.8.1 -> 1.8.2
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/53
relates #15950

ffmpeg/4.x: update FFmpeg plugin

---

modules/calib3d/src/chessboard.cpp

implements suggestion from #16781 to avoid triggering out of range.

fix: estimateChessboardSharpness triggers out of range test

---

modules/gapi/src/executor/gstreamingexecutor.cpp

Bitwise operations (&=) on booleans were replaced with correct logical one ( && ) to make KW happy

GAPI - KW fixes - replaced bitwise &= on bools, with explicit &&

---

modules/gapi/include/opencv2/gapi/own/mat.hpp
modules/gapi/test/own/mat_tests.cpp

This patch adds promoting for one of the arguments to bigger type to avoid multiplication overflow in own::Mat::total() and according tests

GAPI - KW fixes - avoid overflow in own::Mat::total() and according tests

---

modules/gapi/test/own/mat_tests.cpp

These are leftovers from #16796 

GAPI - KW fixes:  avoid overflow in own::Mat::total() and according tests, part 2

---

modules/python/CMakeLists.txt

Warning from [Winpack builder](http://pullrequest.opencv.org/buildbot/builders/3_4_winpack-build-win64-vc14/builds/701).

cmake: fix missing project() warning in Python standalone builds

---

apps/version/opencv_version.cpp

Dump number of configured threads.
relates #16268
Usage example:
```
$ ./bin/opencv_version --threads
$ OPENCV_FOR_THREADS_NUM=3 ./bin/opencv_version --threads
```

opencv_version: dump threads information

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp
samples/dnn/tf_text_graph_ssd.py

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/725
Add support for MobileNetV3  SSD from TensorFlow Object Detection API: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#mobile-models
Follow a guide to run the model: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API
**NOTE**: considering discussion https://github.com/tensorflow/models/issues/7727, only updated models work correctly: https://github.com/tensorflow/models/pull/8057
**NOTE**: comparing to other SSD networks, these models expect normalized inputs (`[-1, 1]` input range):
```python
net = cv.dnn_DetectionModel('frozen_inference_graph.pb', 'graph.pbtxt')
net.setInputSize(320, 320)
net.setInputScale(1.0 / 127.5) …
```

Support for MobileNetV3-SSD from TensorFlow

---

modules/core/include/opencv2/core/hal/intrin_vsx.hpp

releated to #15494
There's no need to use `vec_perm()` instead of `vec_splat()`,
since instruction `vperm` is quite heavy compared to `vsplt[b,h,w]`.
````
````

core:vsx reimplement `v_broadcast_element()`

---

modules/objdetect/test/test_qrcode.cpp

Two _objdetect_ tests were failing in build configurations without QUIRC (`WITH_QUIRC=OFF`) due to invalid input image being used.

objdetect: fix QRCode tests with disabled QUIRC

---

modules/videoio/misc/plugin_ffmpeg/Dockerfile-ffmpeg
modules/videoio/misc/plugin_ffmpeg/Dockerfile-ubuntu
modules/videoio/misc/plugin_gstreamer/Dockerfile

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
results in smaller image size.

Some debian package manager tweaks

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/src/api/kernels_core.cpp
modules/gapi/src/backends/cpu/gcpucore.cpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp

G-API: Implement WarpAffine

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/misc/python/test/test_dnn.py

the float variant seems to be always shadowed by the int version as
Rect2d is implicitly convertible to Rect

dnn: expose only float variant of NMSBoxes for bindings 

---

modules/dnn/src/cuda4dnn/csl/memory.hpp
modules/dnn/src/op_cuda.hpp

The host memory is page-locked to improve host-device memory transfer performance. #16648 
fixed a bug where the device memory is resized if the previously allocated memory isn't sufficient. However, it did not re-register the corresponding host memory.
Original report: https://github.com/opencv/opencv/issues/16568#issuecomment-590202635
```
```

[WIP] cuda4dnn: release and relock page-locked memory when tensor is resized

---

modules/core/include/opencv2/core/mat.inl.hpp
modules/core/test/test_mat.cpp

core: fix .begin()/.end() of empty Mat

---

doc/js_tutorials/js_gui/js_image_display/js_image_display.markdown
doc/py_tutorials/py_calib3d/py_calibration/py_calibration.markdown
doc/py_tutorials/py_gui/py_image_display/py_image_display.markdown
doc/py_tutorials/py_imgproc/py_contours/py_contours_more_functions/py_contours_more_functions.markdown
doc/py_tutorials/py_imgproc/py_histograms/py_histogram_begins/py_histogram_begins.markdown
doc/tutorials/ml/introduction_to_svm/introduction_to_svm.markdown
doc/tutorials/videoio/video-input-psnr-ssim/video_input_psnr_ssim.markdown
modules/cudaoptflow/include/opencv2/cudaoptflow.hpp
modules/videoio/include/opencv2/videoio.hpp

`@sa` forces links auto-creation on each word.
Pages with problems:
- https://docs.opencv.org/4.2.0/dc/dbb/tutorial_py_calibration.html
- https://docs.opencv.org/4.2.0/d5/dc4/tutorial_video_input_psnr_ssim.html

doc: fix misused "see also" doxygen command

---

cmake/OpenCVDetectPython.cmake

Minor issue that's applicable on 3.4. Found it on Fedora 31 where Python is 3.7.6.
If you feel it's not spelt to your liking it can be changed to something else since we're here.

fix: minor typo in CMakeCVDetectPython

---

modules/gapi/cmake/DownloadADE.cmake

Enabling Android build back for ADE and G-API
resolves #16780
<cut/>
```
```

Try to enable G-API build on Android

---

modules/dnn/src/cuda4dnn/primitives/scale_shift.hpp
modules/dnn/src/layers/scale_layer.cpp
modules/dnn/test/test_darknet_importer.cpp

**Changes:**
- fixes segmentation fault (issue #16866, https://github.com/opencv/opencv/issues/16420#issuecomment-599478461)
- add support for bias in untrainable mode for CUDA backend (introduced in OCV backend in #16738)
- allow batches in untrainable mode in the CUDA  backend (#16630)
<cut/>
```
Xforce_builders=Custom
Xbuildworker:Custom=linux-4 …
```

cuda4dnn(ScaleShift): fix segfaults, support bias in untrainable mode, allow batches in untrainable mode

---

apps/CMakeLists.txt

Usage:
- `cmake -DOPENCV_INSTALL_APPS_LIST=opencv_version ...`
To replace `INSTALL_CREATE_DISTRIB` behavior restrictions (it doesn't install debug binaries).

cmake(apps): support OPENCV_INSTALL_APPS_LIST

---

modules/calib3d/src/quadsubpix.cpp

Following warning has been reproduced with latest version of Visual Studio 2019 16.5.0:
```
opencv\modules\core\include\opencv2\core\types.hpp(1302): warning C4756: overflow in constant arithmetic
```
```
```

calib3d: fixed VS2019 warning C4756

---

modules/gapi/include/opencv2/gapi/util/variant.hpp
modules/gapi/test/util/variant_tests.cpp

This patch fixes compilation during (perfectly valid) assignment of [lvalue reference](https://en.cppreference.com/w/cpp/language/reference) to a `variant`. 
The error is something like this : 
> error: static assertion failed: Type not found
static_assert(std::is_same<Target, First>::value, "Type not found");
Root cause of the problem is that during argument type deduction for `emplate<class T> varaiant::operator=(T&&)`  and lvalue ref argument  `T` is matched as a ref (e.g. `int&`). Then it is look up in the total types list of the variant (which fails) : 
>required from ‘constexpr const size_t cv::util::type_list_index<__int&__, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::value’
``` …
```

G-API utils - fix compilation error in variant::operator=

---

modules/dnn/src/cuda4dnn/csl/cudnn/cudnn.hpp
modules/dnn/src/cuda4dnn/primitives/convolution.hpp
modules/dnn/src/dnn.cpp

**Changes:**
1. The CUDA backend uses dynamic cast for fusing convolutions with activations in `setActivation`. Hence, the string-based layer type check in `fuseLayers` is redundant.
2. Fallback to natively fused convolution if cudnn fused convolution throws `CUDNN_STATUS_NOT_SUPPORTED` (reproducer: Resnet34_kinetics)
- this issue has been there for quite some time but was masked by fusion failures because of #16877 
```
```

cuda4dnn(conv): fix CUDNN_STATUS_NOT_SUPPORTED, remove redundant fusion checks

---

modules/calib3d/src/dls.cpp

Check pointers before dereferencing.

calib3d: check input values in dls (KW)

---

modules/core/src/parallel.cpp

fix
> 
error: use of undeclared identifier '_SC_NPROCESSORS_ONLN'
>

fix freebsd build

---

modules/core/src/parallel.cpp
modules/dnn/CMakeLists.txt

backport #16915
```
Xbuild_image:Linux OpenCL=ubuntu:20.04
Xbuildworker:Linux OpenCL=linux-2
build_image:Linux AVX2=ubuntu:20.04
```

(3.4) eliminate build warnings

---

modules/imgproc/src/resize.cpp
modules/imgproc/test/test_imgwarp.cpp

resolves #15075
relates #16497
- ~~drop unused `pix_size4`~~ (separate PR with cleanup)

imgproc(resize): fix resizeNNInvoker handling of generic pixel size

---

modules/core/src/matrix_expressions.cpp

relates #16739
relates #16538
relates #16597

core: emit warning ONCE on ambiguous MatExpr processing

---

modules/core/perf/opencl/perf_matop.cpp
modules/core/src/ocl.cpp

- control using of `clEnqueueMapBuffer` or `clEnqueueReadBuffer[Rect]` APIs
- added benchmarks with OpenCL buffer access use cases
Runtime options:
- bool: `OPENCV_OPENCL_BUFFER_FORCE_MAPPING=1`
- bool: `OPENCV_OPENCL_BUFFER_FORCE_COPYING=1`
<cut/>
```
```

core(OCL): options to control buffer access flags

---

modules/core/include/opencv2/core/version.hpp

OpenCV 3.4.10
relates #16770
<cut/>
<details>
[opencv_world3410.dll (vc14)](https://www.virustotal.com/gui/file/d220bc5c12bc7b4058cb787bb213470707883169f905676aa167873904989d42/detection)
[opencv_world3410d.dll (vc14)](https://www.virustotal.com/gui/file/12853e01f95464aa91028f0546cd9329212a718330cca73c91d7724960553e7b/detection)
[opencv_world3410.dll (vc15)](https://www.virustotal.com/gui/file/b925e1955af1718ed1ae10d1f3f1db57e5ab8c4865729e4748d0ba721edca687/detection)
[opencv_world3410d.dll (vc15)](https://www.virustotal.com/gui/file/6a50675deabb1a687630bf5c515a53eaf6415d5eaa49cd400be03da8f54276f4/detection)
[opencv_ffmpeg3410_64.dll](https://www.virustotal.com/gui/file/02546b95e59bf99b2a6dd409b644498224e3b625f2028e278b00d98cfb73001a/detection) …

release: OpenCV 3.4.10

---

modules/core/include/opencv2/core/version.hpp

relates #16771
<cut/>
<details>
[opencv_world430.dll (vc14)](https://www.virustotal.com/gui/file/b88dfc5fae838927362b24037d85aaa07cd3d64d7dcde97a108c0bda1f0e1553/detection)
[opencv_world430d.dll (vc14)](https://www.virustotal.com/gui/file/649ccdbb5aaffeb210efba5b9bfef0b63bc41807bf5408d32a78f739d4239f78/detection) 
[opencv_world430.dll (vc15)](https://www.virustotal.com/gui/file/db70a0e572acea07b9a3385a2b177afb4e27b30520440217c63aa886bf38897e/detection)
[opencv_world430d.dll (vc15)](https://www.virustotal.com/gui/file/f8895f461b134117c0501b0da602ab0c620735279b180b27a217bd0e9e709258/detection)
detections from `Trapmine: *.ml.score`, [considered false positive](https://stackoverflow.com/questions/54052224/virustotal-trapmine-suspicious-low-ml-score) …

release: OpenCV 4.3.0

---

doc/Doxyfile.in

The PREDEFINED setting for  had a space between the define name and the equal sign and this is not allowed, it results in the warning:
```
error: Illegal PREDEFINED format '=', no define name specified
```
according to the documentation explicitly states that no space is allowed:
> The PREDEFINED tag can be used to specify one or more macro names that are defined before the preprocessor is started (similar to the -D option of e.g. gcc). The argument of the tag is a list of macros of the form: name or name=definition (no spaces). If the definition and the "=" are omitted, "=1" is assumed. To prevent a macro definition from being undefined via #undef or recursively expanded use the := operator instead of the = operator.
See details at …

Incorrect PREDEFINED setting.

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp
modules/gapi/include/opencv2/gapi/gkernel.hpp
modules/gapi/include/opencv2/gapi/gmat.hpp
modules/gapi/include/opencv2/gapi/gproto.hpp
modules/gapi/include/opencv2/gapi/gtype_traits.hpp
modules/gapi/src/api/gproto.cpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/test/gapi_frame_tests.cpp
modules/gapi/test/internal/gapi_int_garg_test.cpp

* Added a GFrame class to introduce an api entity for image buffer with some auxiliary information
```
```

Added GFrame class

---

modules/core/include/opencv2/core/utility.hpp

It's possible either by accident or design to init a Mat with no rows. In such a case instead of a CV assertion you end up with a divide by zero seg fault when trying to forEach.
```
#include <opencv2/core.hpp>
int main() {
cv::Mat test(cv::Size(0,1), CV_8UC1);
test.forEach<uint8_t>([](const auto& pixel, const int pos[]) {
});
}
```
`Process finished with exit code 136 (interrupted by signal 8: SIGFPE)`

Fixed divide by zero segfault in forEach

---

modules/gapi/include/opencv2/gapi/util/variant.hpp
modules/gapi/test/util/variant_tests.cpp

This patch fixes usage of [Universal (Forwarding ) reference](https://en.cppreference.com/w/cpp/language/reference) in the converting constructor and assignment operator of `variant`.
<cut/>
In c++,  function template argument such  as `T&&`  is not always a _rvalue  reference_. If `T` is function template parameter, then `T&&` is a universal reference , which can be bound to both _rvalue  reference_ and _lvalue  reference_  . I.e. in the following declaration  `t` is the universal reference: 
```c++
template <typename T> 
voif f(T&& t);
```
So, in order to have a template function with templated parameter accepting only _rvalue references_, some extra effort is needed . One possible way is to add an extra overload which is a better match for _lvalue references_ .  For `variant` …

G-API utils - make variant converting constructor and assignment operator properly forward it's argument

---

modules/gapi/src/executor/gexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/test/gapi_opaque_tests.cpp

Added GOpaque support to GStreamingExecutor

---

modules/gapi/src/compiler/gislandmodel.cpp

- remove unreachable code in `GIsland::producer()`
Static analysis complains that code after  `GAPI_Assert` is unreachable (is it's either `throw`s exception / issue division by zero / call `abort`)
```
```

GAPI - KW fixes - removes unreachable code GIsland::producer()

---

modules/dnn/src/dnn.cpp
modules/dnn/src/init.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/torch/torch_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves https://github.com/opencv/opencv/issues/16877
* Remove `toLoweCase` for types when construct dnn layers
* Register `SoftMax` for compatibility (there are number of tests which showed `"SoftMax"` type name). Origin type is `Softmax`
I'd like to recommend to merge after the release.
/cc @YashasSamaga 
<cut/>
```
```

Case sensitive dnn layers types

---

modules/imgproc/src/thresh.cpp
modules/imgproc/test/test_thresh.cpp

Add getThreshVal_Otsu_16u, which is almost a literal copy of getThreshVal_Otsu_8u, except that it does not have an ipp acceleration and have 2<sup>16</sup> instead of 2<sup>8</sup> buckets.
16bit Otsu thresholding is useful for IR-images.

Enable Otsu thresholding for CV_16UC1 images

---

doc/pattern_tools/gen_pattern.py

Finish one TODO in gen_pattern.py. Switch the parser to `argparse` without changing command line interfaces.
This is a reworked version of my previous PR #16968 , which is closed by myself. Many thanks to @alalek and @asmorkalov . Thank you for your great suggestions!

 Switch to argparse in gen_pattern.py from parsing manually - reworked

---

modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra:** opencv/opencv_extra#732  
**relates:** #14853, #14813
_TODO:_
```
```

Supported Fully Connected layer with two inputs

---

modules/gapi/include/opencv2/gapi/fluid/gfluidbuffer.hpp
modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp
modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/src/backends/fluid/gfluidbackend.hpp
modules/gapi/src/backends/fluid/gfluidbuffer.cpp
modules/gapi/src/backends/fluid/gfluidbuffer_priv.hpp
modules/gapi/test/gapi_kernel_tests.cpp

* Changed shared_ptr to unique_ptr for pimpl implementation in fluid::Buffer and fluid::View
```
```

G-API: unique_ptr for Priv in fluid

---

modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_imgproc_perf_tests_cpu.cpp
modules/gapi/src/api/kernels_imgproc.cpp
modules/gapi/src/backends/cpu/gcpuimgproc.cpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp

- there are performance and accuracy tests
- additional comparison functions and fixtures implemented
_Patch to opencv_extra has the same branch name._
```
Xbuild_image:Custom=ubuntu-openvino-2019r2.0:16.04 …
```

G-API: cv::gapi::goodFeaturesToTrack() implementation

---

modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp

resolves #16998
warnings:
```
opencv\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(39): 
warning C4715: 'cv::`anonymous namespace'::colorspaceName': not all control paths return a value
opencv\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(217,89): 
warning C4244: 'return': conversion from 'const InT' to 'OutT', possible loss of data 
opencv\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(561,31): 
warning C4805: '|=': unsafe mix of type 'bool' and type 'const OPJ_UINT16' in operation
opencv\modules\imgcodecs\src\grfmt_jpeg2000_openjpeg.cpp(626,35): 
warning C4244: 'initializing': conversion from 'OPJ_UINT32' to 'uint8_t', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\xutility(3606,22): 
warning C4244: …
```

OpenJPEG: fixed compilation and warnings with VS

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/ptsetreg.cpp
modules/calib3d/test/test_translation3d_estimator.cpp

I've done my best to follow the PR guidelines, but this is my first PR to OpenCV, so I anticipate some back and forth; I'm grateful for your time.
Currently the RANSAC filter in calib3D/ptsetreg.cpp only permits full affine transformations. I have an application (and others may as well) that requires limiting the transform to translation only.
The new function follows the API and implementation structure for estimateAffine3D exactly, only the implementations of runKernel, computeError, and checkSubset are modified (and are considerably simpler) for the new class - users can call estimateTranslation3D as a drop in replacement for estimateAffine3D whenever it is appropriate.
I've built successfully on my system and implemented tests. estimateTranslation3D will be strictly faster than …

added estimateTranslation3D to calib3d/ptsetreg

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/739
<details>
<summary> Example network </summary>
<cut/>
```
node {
name: "input"
op: "Placeholder"
attr {
key: "dtype"
value {
type: DT_FLOAT
}
}
attr {
key: "shape"
value {
shape {
dim {
size: 1
}
dim {
size: 2
}
dim {
size: 3
}
dim {
size: 4
}
}
}
}
}
node {
name: "conv2d/Conv2D_dummy_paddings"
op: "Const"
attr {
key: "dtype"
value {
type: DT_INT32
}
}
attr {
key: "value"
value {
tensor {
dtype: DT_INT32
tensor_shape {
dim {
size: 4
}
dim {
size: 2
}
}
tensor_content: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
}
}
}
}
node {
name: "conv2d/bias"
op: "Const"
attr {
key: "dtype"
value {
type: DT_FLOAT
}
}
attr {
key: "value"
value { …
```

Support FusedResizeAndPadConv2D from TensorFlow

---

modules/gapi/include/opencv2/gapi/own/assert.hpp

- added `[[noreturn]]` to standalone version of  `GAPI_Assert` implementaion 
relates #16952
@dmatveev @rgarnov please take a look
<cut/>
```
```

GAPI: Fix [-Wreturn-type] warning on standalone mac build

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/cpu/video.hpp
modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/include/opencv2/gapi/video.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests.hpp
modules/gapi/perf/common/gapi_video_perf_tests.cpp
modules/gapi/perf/common/gapi_video_perf_tests.hpp
modules/gapi/perf/common/gapi_video_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_imgproc_perf_tests_cpu.cpp
modules/gapi/perf/cpu/gapi_video_perf_tests_cpu.cpp
modules/gapi/perf/perf_precomp.hpp
modules/gapi/src/api/kernels_video.cpp
modules/gapi/src/backends/cpu/gcpuvideo.cpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/common/gapi_video_tests.cpp
modules/gapi/test/common/gapi_video_tests.hpp
modules/gapi/test/common/gapi_video_tests_common.hpp
modules/gapi/test/common/gapi_video_tests_inl.hpp
modules/gapi/test/cpu/gapi_video_tests_cpu.cpp
modules/gapi/test/test_precomp.hpp

- two implementations with different input (GMat's or GArray<GMat>'s) to support features to build / not to build optical flow pyramids inside the kernel
- opencv_gapi is linked with opencv_video now
- there are performance and accuracy tests (implemented actively using cv::video perf test for optFlowPyrLK)
``` …
```

G-API: gapi::calcOpticalFlowPyrLK() Implementation

---

modules/highgui/src/window_winrt.cpp

Fix #16974
```
build_image:Custom Win=msvs2019-ws-x64
```

highgui: Fix error at #include <window_winrt_bridge.hpp>

---

3rdparty/openexr/IlmImf/ImfAttribute.cpp

std::binary_function was deprecated with C++11 and removed in C++17. It provided just two typedefs which in this case were unused.

Remove std::binary_function as it's deprecated in C++11

---

modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/mat.inl.hpp
modules/core/src/matrix_expressions.cpp
modules/core/test/test_mat.cpp

Rework `MatExpr` implementation in `InputArray`:
- avoid multiple expression evaluations
- avoid issues with reduced support of `InputArray::EXPR`
<cut/>
TODO:
```
```

core(MatExpr): drop from InputArray

---

modules/cudaimgproc/test/test_color.cpp

resolves #17037 
relates #12561
Though this PR fixes rounding error of `CV_32F`, I can see one test failure case when I tried long stress test using `gtest_repeat=-1`
The failed test is `CUDA_ImgProc/CvtColor.Luv2BGRA/7`
```
/home/ubuntu/opencv-fork/modules/cudaimgproc/test/test_color.cpp:2017: Failure
The max difference between matrices "dst_gold" and "dst" is 9 at (91, 48), which exceeds "depth == 0 ? 2 : 1e-4", where "dst_gold" at (91, 48) evaluates to (0, 2, 0, 255), "dst" at (91, 48) evaluates to (0, 2, 9, 255), "depth == 0 ? 2 : 1e-4" evaluates to 2
[  FAILED  ] CUDA_ImgProc/CvtColor.Luv2BGRA/7, where GetParam() = (NVIDIA Tegra X1, 113x113, CV_8U, sub matrix) (10 ms)
```
The difference is 9, and I don't think this is suitable to loosen the `eps`.
Something similar to #11315 for CUDA …

CUDA: Fix cuda imgproc failure

---

modules/dnn/src/layers/permute_layer.cpp
modules/dnn/src/onnx/onnx_graph_simplifier.hpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/740
resolves #16971 
```
opencv_extra=padfusion
```
SubgraphFusion for 
```
```

ONNX : ReflecitonPad2d and ZeroPad2d Subgraph fusion added

---

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/744
Let's merge after https://github.com/opencv/opencv/pull/16985
To export model to ONNX, see https://github.com/amdegroot/ssd.pytorch/pull/462
```
python3 export_to_onnx.py --model ssd300_mAP_77.43_v2.pth
```
```python
net = cv.dnn.readNet('ssd.onnx')
img = cv.imread('example.jpg')
rows, cols = img.shape[0:2]
inp = cv.dnn.blobFromImage(img, 1.0, (300, 300), mean=(123, 117, 104), swapRB=True)
net.setInput(inp)
out = net.forward()
for detection in out[0,0,:,:]:
score = float(detection[2])
if score > 0.7:
xmin, ymin, xmax, ymax = [int(v) for v in detection[3:] * [cols, rows, cols, rows]]
cv.rectangle(img, (xmin, ymin), (xmax, ymax), (23, 230, 210), thickness=2)
cv.imshow('Object …
```

Enable ONNX SSD from https://github.com/amdegroot/ssd.pytorch

---

modules/photo/test/test_denoising.cuda.cpp

resolves #17024 
This test failure only happens in master branch, but test fix now based on 3.4 branch (regular procedure)

photo: fix test failure on Jetson Nano/TX1/TX2

---

modules/dnn/CMakeLists.txt
modules/dnn/src/op_inf_engine.hpp

Allow to build without NN Builder API, but with IE + ngraph
<cut/>
```
```

Fixed compilation when NN builder is not built

---

modules/dnn/src/layers/pooling_layer.cpp

Fix potential bug in deprecated API for the internal changes in IE
<cut/>
```
```

Align DLIE and nGraph average pooling layers

---

modules/gapi/include/opencv2/gapi/util/variant.hpp
modules/gapi/test/util/variant_tests.cpp

adding one more [missing function](https://en.cppreference.com/w/cpp/utility/variant/get_if) to local version of `std::variant`
```
```

GAPI: utils - variant::get_if

---

modules/python/src2/hdr_parser.py
modules/videoio/misc/java/test/VideoCaptureTest.java

`explicit` keyword is removed from the function declaration string.
Resolves:  #16988.
```
```

Header parser `explicit` constructors support

---

platforms/winpack_dldt/2020.2/20200413-dldt-disable-unused-targets.patch
platforms/winpack_dldt/2020.2/20200413-dldt-fix-binaries-location.patch
platforms/winpack_dldt/2020.2/20200413-dldt-pdb.patch
platforms/winpack_dldt/2020.2/20200415-ngraph-disable-unused-options.patch
platforms/winpack_dldt/2020.2/patch.config.py
platforms/winpack_dldt/2020.2/sysroot.config.py
platforms/winpack_dldt/build_package.py

https://github.com/opencv/dldt/releases/tag/2020.2
relates #16847
<cut/>
```
Xbuild_image:Custom Win=winpack-dldt-2020.2
```

Build OpenCV winpack with DLDT 2020.2

---

modules/cudabgsegm/test/test_bgsegm.cpp

CUDA: fix test failure on Jetson TX2

---

modules/objdetect/src/qrcode.cpp

I'm quite sure that this is a typo

objdetect: fix wrong condition check

---

modules/viz/include/opencv2/viz/widgets.hpp

`WCube` constructor reorders `min_point`, `max_point` parameters when necessary. I added this info to the description.

Added to description of WCube constructor

---

modules/objdetect/test/test_cascadeandhog.cpp

objdetect: avoid test failure on Arm platform

---

cmake/OpenCVFindIPP.cmake
cmake/OpenCVFindIPPIW.cmake

Resolves #16537
Only IPP/IPPIW binaries distributed with OpenCV should be copied to `<INSTALL>/lib/opencv4/3rdparty`.
Checked samples build with following configurations (Ubuntu 18):
```
cmake -GNinja -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=install $OPT ../opencv
```
where OPT is:
1. `<empty>` - default, use IPPICV and IPPIW from OpenCV
2. `-DIPPROOT=/opt/intel/compilers_and_libraries_2020.0.166/linux/ipp` - use standalone IPP, use IPPIW from OpenCV
3. `-DIPPROOT=/opt/intel/compilers_and_libraries_2020.0.166/linux/ipp -DBUILD_IPP_IW=OFF` - use standalone IPP and IPPIW

Do not copy standalone IPP libraries to install for static builds

---

samples/python/tutorial_code/ShapeDescriptors/point_polygon_test/pointPolygonTest_demo.py

resolves #17070
fixed a `TypeError` caused by incorrect use of `tuple()`.  As mentioned by @qingshihuangdi, python expects `tuple([255,255,255])` rather than `tuple(255,255,255)`.

Point Polygon Test Demo : resolved tuple error

---

modules/dnn/src/dnn.cpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/ie_ngraph.hpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/src/op_inf_engine.hpp
modules/dnn/test/test_misc.cpp

Support flexible inputs for OpenVINO IR models. We can work with non-default IR input resolutions but not with flexible inputs which may change between runs.
<cut/>
```
```

Flexible inputs for OpenVINO IR models

---

modules/videoio/src/cap_msmf.cpp

- warning C4800: 'int': forcing value to bool 'true' or 'false'

videoio(MSMF): fix build warning

---

modules/dnn/src/layers/region_layer.cpp
modules/dnn/test/test_darknet_importer.cpp

Support for RegionYolo nGraph op since **OpenVINO 2020.2**
<cut/>
```
```
**CPU:** Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz  
|                 | Fallback, ms | nGraph implementation, ms |
|-----------------|--------------|---------------------------|
| Yolov3 CPU      | 334          | 329                       |
| Yolov3 OCL      | 277          | 254                       |
| Yolov3 …

Support nGraph Region

---

modules/objdetect/perf/perf_qrcode_pipeline.cpp
modules/objdetect/src/qrcode.cpp
modules/objdetect/test/test_qrcode.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/746
Fixed bug with skip some localization points. Due to this bug some QR-Codes couldn't be found and also the method detectMulti() could return a different number of found QR-codes 

QRDetectMulti : different return value bug fix

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/743
resolves #17001 
```
opencv_extra=onnximporter
```
Parsing for `Upsample` node obtained from fusion of Unfused Resized Subgraph by adding setting of layer parameters.
``` …
```

ONNX: modifications in onnx_importer for upsample node fused from unfused Resize subgraph

---

doc/tutorials/ml/non_linear_svms/non_linear_svms.markdown
modules/calib3d/include/opencv2/calib3d.hpp
modules/imgproc/include/opencv2/imgproc.hpp
modules/video/include/opencv2/video/tracking.hpp

Resolves #16987 
Here are new outputs:
1. https://docs.opencv.org/4.3.0/d0/dcc/tutorial_non_linear_svms.html: backslash
2. https://docs.opencv.org/4.3.0/d4/d86/group__imgproc__filter.html: remaining texttt command
3. https://docs.opencv.org/4.3.0/d4/d86/group__imgproc__filter.html: remaining texttt command
4.  https://docs.opencv.org/4.3.0/d4/d86/group__imgproc__filter.html: different size underneath sum symbol
5.  https://docs.opencv.org/4.3.0/d9/d0c/group__calib3d.html: probably missing some \cdot around the E
8.  https://docs.opencv.org/4.3.0/dc/d6b/group__video__track.html: twice warpMatrix
Formulas 6 and 7 are fixed in #17120

Fixed "strange" formulas in the documentation for 3.4 branch

---

modules/gapi/include/opencv2/gapi/imgproc.hpp

Resolves #16987 
Here are new outputs:
6. https://docs.opencv.org/4.3.0/da/dc5/group__gapi__filters.html: remaining texttt command
7.  https://docs.opencv.org/4.3.0/da/dc5/group__gapi__filters.html: different size underneath sum symbol
1, 2, 3, 4, 5, 8 are fixed in #17123 #17123

Fixed "strange" formulas in the documentation for master branch

---

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/734
resolves #16876
```
opencv_extra=fasterrcnn
```
Support to resnet_backbone by adding 
1. **fusion of Unfused Frozen BatchNorm.**
2. **fusion of unfused Upsample with two inputs.**
Unfused Version of batchnorm. Latest version of pytorch ( 1.4 )
Below for are node properties of Reshape nodes
Below attached Fused version of Batchnorm to show comparison between unfused and fused batchnorm.
Initializers inputs of Reshape of above unfused subgraph acts same as Initializer inputs of Fused batchnorm.
**Initializers** are not considered as nodes.
One more example of **Initializer** is …

ONNX: Add support for Resnet_backbone (Torchvision)

---

modules/videoio/CMakeLists.txt
modules/videoio/cmake/plugin.cmake
modules/videoio/src/backend_plugin.cpp

- added suffix to debug versions of videoio plug-ins
- trying to load plug-ins with `d` suffix in debug builds
Note: FFmpeg plug-in does not work because it does not have debug version, but the file can be renamed or forced via environment and then it will work (more or less)
Validated debug builds:
- [Win64](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/24118)
- [Win32](http://pullrequest.opencv.org/buildbot/builders/precommit_windows32/builds/12399)
<cut/>
```
build_debug:Custom Win=ON
test_modules:Custom Win=videoio
Xbuild_debug:Win64 OpenCL=ON
Xtest_modules:Win64 OpenCL=videoio
build_debug:Win32=ON
test_modules:Win32=videoio
**WIP**
```

videoio: load debug versions of plug-ins in debug builds

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/own/convert.hpp
modules/gapi/src/backends/ie/giebackend.cpp

relates #16995
<cut/>
```
Xforce_builders=Custom
build_image:Custom=plaidml2
test_filter:Custom=*ML* 
Xbuild_image:Custom=ubuntu-openvino-2020.1.0:16.04
Xtest_modules:Custom=gapi
```

GAPI: fix build, update IE handling, add OPENCV_GAPI_INF_ENGINE

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp
modules/gapi/include/opencv2/gapi/video.hpp
modules/gapi/perf/common/gapi_video_perf_tests.hpp
modules/gapi/perf/common/gapi_video_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_video_perf_tests_cpu.cpp
modules/gapi/src/api/kernels_video.cpp
modules/gapi/src/backends/cpu/gcpuvideo.cpp
modules/gapi/test/common/gapi_video_tests.hpp
modules/gapi/test/common/gapi_video_tests_common.hpp
modules/gapi/test/common/gapi_video_tests_inl.hpp
modules/gapi/test/cpu/gapi_video_tests_cpu.cpp

- kernel added to a cv::gapi::video namespace
- tests to check a kernels (based on cv::video tests for cv::buildOpticalFlowPyramid())
- tests for a combined G-API-pipeline (buildOpticalFlowPyramid() -> calcOpticalFlowPyrLK())
- tests for internal purposes added
- custom function for comparison in tests implemented
```
Xforce_builders=Custom,Custom Win,Custom Mac …
```

G-API: gapi::buildOpticalFlowPyramid() Implementation

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_ie_models.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp

OpenVINO 2020.2
<cut/>
Disabled tests related to Maxpooling layer handling.
Left issues (will be fixed separately):
```
[ RUN      ] DNNTestOpenVINO.models/10, where GetParam() = (DLIE/MYRIAD, "person-detection-retail-0013")
C++ exception with description "OpenCV(3.4.10-dev) /build/precommit_custom_linux/3.4/opencv/modules/dnn/src/op_inf_engine.cpp:881: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = MYRIAD): Unexpected CNNNetwork format: it was converted to deprecated format prior plugin's call in function 'initPlugin'
[  FAILED  ] DNNTestOpenVINO.models/10, where GetParam() = (DLIE/MYRIAD, "person-detection-retail-0013") (4914 ms)
```
```
**WIP** …
```

dnn(test): skip failed NGRAPH/MYRIAD tests

---

modules/dnn/src/cuda4dnn/primitives/slice.hpp

resolves #17116 
details: https://github.com/opencv/opencv/issues/17116#issuecomment-618828526
<cut/>
```
```

cuda4dnn(Slice): handle case where no slicing is required

---

3rdparty/protobuf/src/google/protobuf/text_format.cc
3rdparty/protobuf/src/google/protobuf/text_format.h
modules/dnn/src/caffe/caffe_io.cpp

resolves #17138
relates #11129
- backport AllowUnknownField(), SetRecursionLimit() from protobuf 3.8.0
- limit recursion in SkipField*() calls too
<cut/>
```
```

dnn(protobuf): backport AllowUnknownField(), SetRecursionLimit()

---

cmake/OpenCVFindProtobuf.cmake
modules/dnn/CMakeLists.txt

<cut/>
```
Xbuild_image:Custom=ubuntu:18.04
Xbuildworker:Custom=linux-3
```

cmake: fix protobuf handling

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/backend.hpp
modules/videoio/src/backend_plugin.cpp
modules/videoio/src/backend_static.cpp
modules/videoio/src/cap.cpp
modules/videoio/src/cap_avfoundation.mm
modules/videoio/src/cap_avfoundation_mac.mm
modules/videoio/src/cap_ffmpeg.cpp
modules/videoio/src/cap_gstreamer.cpp
modules/videoio/src/cap_images.cpp
modules/videoio/src/cap_interface.hpp
modules/videoio/src/cap_mfx_writer.cpp
modules/videoio/src/cap_mjpeg_encoder.cpp
modules/videoio/src/cap_msmf.cpp

- Added additional constructor and `open` method for `VideoWriter`
those accept a vector of parameters
- Moved the actual implementation of the `VideoWriter::open` to the general method
which accepts a vector of parameters
- Propagate parsed parameters map up to actual video backend construction
```
```

feature: Extend VideoWriter to accept vector of parameters

---

modules/objdetect/src/hog.cpp
modules/objdetect/src/opencl/objdetect_hog.cl

resolves #17172 
The minimum necessary fix is to add more `barrier(CLK_LOCAL_MEM_FENCE)` between the access to `smem`
Still, following the #11409, I think it's reasonable to remove `-D CPU` part and `-D WAVE_SIZE` part
I'm open for discussion on this point.

OpenCL: fix test failure on ODROID-N2

---

modules/dnn/test/test_onnx_importer.cpp

relates #16629
<cut/>
Message:
```
[ RUN      ] Test_ONNX_nets.Alexnet/0, where GetParam() = OCV/CPU
unknown file: error: C++ exception with description "OpenCV(3.4.10-dev) C:\build\precommit_windows32\3.4\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 150994944 bytes in function 'cv::OutOfMemoryError'
[  FAILED  ] Test_ONNX_nets.Alexnet/0, where GetParam() = OCV/CPU (1538 ms)
...
[ RUN      ] Test_ONNX_nets.CaffeNet/0, where GetParam() = OCV/CPU
unknown file: error: C++ exception with description "OpenCV(3.4.10-dev) C:\build\precommit_windows32\3.4\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 150994944 bytes in function 'cv::OutOfMemoryError'
[ …
```

dnn(test): update skip tests on Win32 configuration

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/layers/region_layer.cpp
modules/dnn/test/test_darknet_importer.cpp

**Merge with extra:** opencv/opencv_extra#753
resolves: #17148 
```
```
**Performance tests**
**CPU:** Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
| Net               | Backend                      | branch 3.4 | branch yolov4 | …

Support Yolov4

---

modules/calib3d/test/test_fisheye.cpp

Restored test disabled during 3.0-alpha preparation.

---

samples/dnn/text_detection.cpp

Trained model taked from here: https://github.com/meijieru/crnn.pytorch
How to convert from pb to onnx
Using classes from here: https://github.com/meijieru/crnn.pytorch/blob/master/models/crnn.py
```python
import torch
import models.crnn as crnn
model = CRNN(32, 1, 37, 256)
model.load_state_dict(torch.load('crnn.pth'))
dummy_input = torch.randn(1, 1, 32, 100)
torch.onnx.export(model, dummy_input, "crnn.onnx", verbose=True)
```

Add text recognition to examples_dnn_text_decoder

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/test/cpu/gapi_core_tests_fluid.cpp

Fix fluid resize operating with zero output size

---

modules/dnn/src/cuda/crop_and_resize.cu
modules/dnn/src/cuda/functors.hpp
modules/dnn/src/cuda/math.hpp
modules/dnn/src/cuda/memory.hpp
modules/dnn/src/cuda/permute.cu
modules/dnn/src/cuda/region.cu
modules/dnn/src/cuda/resize.cu
modules/dnn/src/cuda/roi_pooling.cu
modules/dnn/src/cuda/vector_traits.hpp
modules/dnn/src/layers/convolution_layer.cpp

**Mish (+ swish and sigmoid):**
This activation is used in YOLOv4. Surprisingly, the mish kernels are compute-bound instead of being bandwidth-bound. The first convolution in YOLOv4 takes less time than the fused bias mish activation step. 
Mish is a composition of several functions: tanh(log(1 + exp(x))). Hence, it is very likely that there is a very good approximation or simplification to the mish function (clearly the log isn't necessary since tanh is a composition over e^x). This PR introduces a fast numerically stable implementation of the mish activation.
Details of the approximation can be found [here](https://cs.stackexchange.com/a/125052/66162).
Operation                                              | without this PR | with this PR …

cuda4dnn: optimizations for swish, mish, sigmoid, region, resize based ops, transpose, identity-conv fusion

---

modules/dnn/src/cuda/region.cu
modules/dnn/src/cuda4dnn/kernels/region.hpp
modules/dnn/src/cuda4dnn/primitives/region.hpp
modules/dnn/src/layers/region_layer.cpp

#17148 for CUDA backend
OCV CPU vs CUDA FP32
```
Relative Error >> Total: 0.00654598, Average: 7.11095e-08, Max: 2.4893e-05
```
GTX 1050 Mobile with 608 x 608 input
Model      | Inference FPS | Inference FPS (with #16900) | Inference + NMS FPS  | 
------------ | ------------------- | --------------------------------------- | ------------------------------ |
YOLOv3  | 10.42              | 10.91                                       |
YOLOv4  | 10.31              | 10.56                                       | 9.71
Code: https://gist.github.com/YashasSamaga/2b98b7ebd62b9719f81941bccabd2e52
```
NOTE: NMS not included.
YOLO v4
OCV CPU >> init: 1120.1ms, inference: 855.422ms
CUDA FP32 >> init: 624.283ms, inference: 96.9914ms
YOLO v3
OCV CPU >> init: 709.338ms, inference: 610.165ms
CUDA FP32 >> …
```

cuda4dnn(region): add scale_x_y parameter for YOLOv4

---

modules/dnn/src/layers/slice_layer.cpp

#17222 introduced `finalSliceRanges` as a replacement for `sliceRanges`. When #17231 was merged into master, the `sliceRanges` was not changed to `finalSliceRanges` in `initCUDA`. This tipped off assertions in the SliceOp primitive.
<cut/>
```
```

cuda4dnn(Slice): fix regression from 3.4 port

---

doc/tutorials/calib3d/table_of_content_calib3d.markdown
doc/tutorials/core/table_of_content_core.markdown
doc/tutorials/dnn/table_of_content_dnn.markdown
doc/tutorials/features2d/table_of_content_features2d.markdown
doc/tutorials/gpu/table_of_content_gpu.markdown
doc/tutorials/imgcodecs/table_of_content_highgui.markdown
doc/tutorials/ios/table_of_content_ios.markdown
doc/tutorials/stitching/table_of_content_stitching.markdown
doc/tutorials/videoio/table_of_content_videoio.markdown
doc/tutorials/viz/table_of_content_viz.markdown

Per the discussion on #17223, this pull request covers similar additions of languages fields to the tutorials tables of content for several modules. Note that there are still many tutorials which do not specify compatibility or an author (ex: latter two of the [videoio module tutorials](https://docs.opencv.org/master/df/d2c/tutorial_table_of_content_videoio.html)) but it would be very difficult for me to reliably provide that information. 

Update tutorials tables of content for several modules

---

modules/calib3d/misc/java/test/Calib3dTest.java
modules/calib3d/test/test_fisheye.cpp

Reproducer for https://github.com/opencv/opencv/issues/17171

Added C++ and Java regression test for estimateNewCameraMatrixForUndistortRectify

---

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra:** opencv/opencv_extra#755
```
```

Added ONNX BatchNorm subgraph

---

modules/core/src/matrix_expressions.cpp

relates #16948
Test case: `fisheyeTest.jacobians`

core(MatExpr): fix warning in case of e.s == (0, 0, 0, 0)

---

modules/videoio/src/cap_mfx_common.cpp
modules/videoio/src/cap_mfx_common.hpp
modules/videoio/src/cap_mfx_reader.cpp
modules/videoio/src/cap_mfx_writer.cpp

Added environment variables to control MFX videoio backend:
- `OPENCV_VIDEOIO_MFX_IMPL` - preferred implementation, number, see mfxIMPL documentation
- `OPENCV_VIDEOIO_MFX_POOL_TIMEOUT` - surface pool wait timeout, seconds, default value is 1
- `OPENCV_VIDEOIO_MFX_EXTRA_SURFACE_NUM` - extra surfaces in surface pool, number, default value is 0
- `OPENCV_VIDEOIO_MFX_BITRATE_DIVISOR` - bitrate calculation divisor, number, default value is 500, `bitrate = pixel_num * fps/ divisor`
- `OPENCV_VIDEOIO_MFX_WRITER_TIMEOUT` - encoder timeout, seconds, default value is 1

CAP_MFX: surface pool with timeout, more parameters

---

modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/scale_layer.cpp
modules/dnn/test/test_onnx_importer.cpp

Fixed bug with ngraph::op::v1::Multiply 

---

modules/gapi/include/opencv2/gapi/gmat.hpp
modules/gapi/include/opencv2/gapi/opencv_includes.hpp
modules/gapi/include/opencv2/gapi/own/cvdefs.hpp
modules/gapi/include/opencv2/gapi/own/mat.hpp
modules/gapi/src/api/gmat.cpp
modules/gapi/src/api/gscalar.cpp

- moved "standalone" aliases of cv types to `opencv_includes.hpp` to
keep responsibility principle aplied
- introduced correct aliasing for `descr_of(Mat)` function for
standalone case
```
force_builders=ARMv7,Custom,Custom Win,Custom Mac
```
Patch to …

G-API: "deownification" corrections

---

modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/test/test_layers.cpp

Fix BatchNorm reinitialization after fusion

---

modules/java/generator/src/java/org/opencv/utils/Converters.java

Using addAll is preferred for performance reason (implementation of addAll uses System. arraycopy())
See https://dev.to/sendilkumarn/9-tips-to-increase-your-java-performance-1l4d

Prefer addAll instead of iteration for performance

---

modules/imgcodecs/CMakeLists.txt
modules/videoio/src/cap_avfoundation.mm
modules/videoio/src/cap_ios_abstract_camera.mm

This PR resolves a few compilation issues when targeting Mac Catalyst by using the `TARGET_OS_MACCATALYST` conditional around iOS APIs that are unavailable on the Mac platform.
Additionally, the removal of linkage to the AssetsLibrary framework was because that library is unavailable on Mac Catalyst. It appears that the iOS specific code in OpenCV doesn't include or link against that framework, and seems to work fine without it. Perhaps it was left over from older / removed code?
Although this PR doesn't fully resolve the related issue #17291, it's a step in the right direction.
```
```

Compilation fixes for Mac Catalyst

---

modules/dnn/test/test_common.impl.hpp
modules/dnn/test/test_darknet_importer.cpp

<cut/>
```
#build_image:Custom=ubuntu-openvino-2019r3.0:16.04
test_filter:Custom=*YOLO*
```

Increase test threshold for YOLOv3 on OCL FP16

---

modules/features2d/test/test_matchers_algorithmic.cpp

In the current master branch, building features2d and its test without flann causes build failure and the error log is below:
```
$ mkdir build && cd build && cmake -DBUILD_LIST="ts,features2d" .. && make -j8
...
--   OpenCV modules:
--     To be built:                 core features2d highgui imgcodecs imgproc ts videoio
--     Disabled:                    world
--     Disabled by dependency:      calib3d dnn flann gapi java_bindings_generator ml objdetect photo python_bindings_generator python_tests stitching video
--     Unavailable:                 java js python2 python3
--     Applications:                tests perf_tests apps
...
/home/yosshi999_for_entry/opencv/modules/features2d/test/test_matchers_algorithmic.cpp: In member function ‘virtual void …
```

ignore a features2d's test dependent on flann when flann module is absent

---

modules/gapi/include/opencv2/gapi/gopaque.hpp
modules/gapi/include/opencv2/gapi/util/type_traits.hpp
modules/gapi/include/opencv2/gapi/util/variant.hpp
modules/gapi/test/util/variant_tests.cpp

Reworked `variant::operator(T&&)` and `varaint::variant(T&&)` to be more
concise and signature accurate with C++17 [specification](https://en.cppreference.com/w/cpp/utility/variant)
<cut/>
```
test_modules:Custom Win=gapi,dnn,python2,python3,java
```
Patch to opencv_extra has the same …

GAPI: utils - variant converting ctor and assignment op. reworked

---

doc/tutorials/introduction/documenting_opencv/documentation_tutorial.markdown

Fixes #17337. This adds a note clarifying that pylint should be installed for the `make check_pylint` command to work.

Add note on Pylint install for make check_pylint

---

doc/tutorials/introduction/macos_install/macos_install.markdown

This adds a note mentioning CMake can be installed simply with brew on macOS.

Add note on CMake installation with Homebrew

---

modules/videoio/src/cap_avfoundation.mm
modules/videoio/src/cap_ios_abstract_camera.mm

relates #17304
Messages:
> /Volumes/build-storage/build/precommit_ios/opencv/modules/videoio/src/cap_avfoundation.mm:395:55: warning: 'TARGET_OS_MACCATALYST' is not defined, evaluates to 0 [-Wundef]
/Volumes/build-storage/build/precommit_ios/opencv/modules/videoio/src/cap_ios_abstract_camera.mm:302:6: warning: 'TARGET_OS_MACCATALYST' is not defined, evaluates to 0 [-Wundef]
```
```

build: fix warnings about TARGET_OS_MACCATALYST

---

modules/dnn/src/layers/convolution_layer.cpp

model from https://github.com/opencv/opencv/issues/17259
```
(base) model_1: 56.99ms
(base) model_2: 170.85ms
(ftz) model_1: 49.18ms
(ftz) model_2: 49.33ms
```
```python
import time
net = cv.dnn.readNet('model_1.prototxt', 'model_1.caffemodel')
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
inp = np.random.standard_normal([1, 3, 112, 112]).astype(np.float32)
net.setInput(inp)
net.forward()
speeds = []
for i in range(10):
start = time.time()
net.forward()
speeds.append((time.time() - start) * 1000)
print(np.median(speeds))
net = cv.dnn.readNet('model_1.prototxt', 'model_2.caffemodel')
net.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
inp = np.random.standard_normal([1, 3, 112, 112]).astype(np.float32)
net.setInput(inp)
net.forward()
speeds = [] …
```

Flush to zero Convolution denormal weights

---

modules/dnn/src/cuda4dnn/csl/cublas.hpp
modules/dnn/src/cuda4dnn/csl/cudnn/cudnn.hpp
modules/dnn/src/cuda4dnn/csl/stream.hpp

Layers that require cuDNN or cuBLAS capabilities have handles as member object. A useless handle is created when they are default constructed. They are going to be replaced by the actual handle later. Handle creation is costly. Hence, all the temporary handles waste resources.
Each `cv::dnn::Net` object now creates exactly one stream, one cuDNN handle and one cuBLAS handle. 
This PR makes default constructed handle objects not create any handle. A special constructor must be used to create a handle.
Model                      | init time (master) | init time (with this PR)
-------------------------- | ---------------------- | -----------------------------
ResNet 50               | 260ms                 | 170ms                        
Enet Cityscapes      | 170ms                 | 30ms …

cuda4dnn: do not create temporary unused handles

---

modules/core/include/opencv2/core/eigen.hpp
modules/core/test/test_mat.cpp

This PR addresses issue https://github.com/opencv/opencv/issues/17237. The primary contributions are two conversion functions (cv2eigen and eigen2cv) for the Eigen::Tensor module along with unit tests.

Add eigen tensor conversions

---

modules/gapi/include/opencv2/gapi/imgproc.hpp

Fix documentation for cv::gapi::blur

---

modules/gapi/include/opencv2/gapi/fluid/gfluidbuffer.hpp
modules/gapi/src/backends/fluid/gfluidbuffer_priv.hpp

Fixed some uninitialized members in `Fluid` structures to make static analysis happy.
```
test_modules:Custom Win=gapi,dnn,python2,python3,java
```

GAPI: fix uninitialized variables in Fluid

---

samples/dnn/object_detection.cpp
samples/dnn/object_detection.py

resolves: opencv/opencv#17246, opencv/opencv#17111
<details>
<summary>Hypothesis: NMS over multiple output layers is not needed (i.e. YOLOv3, YOLOv4)</summary>
**Hypothesis**: NMS over multiple output layers is not needed (i.e. YOLOv3, YOLOv4)
**Resuls**: NMS is required
Output without NMS in sample - 10 detections. Some of detections have an IoU approximately equal 1.
Output with NMS in sample - 7 detections.
</details>

Fixed NMSBoxes bug

---

modules/dnn/src/layers/convolution_layer.cpp

relates #17295
Failed [builds](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL-lin32/builds/754).
```
force_builders=Linux32
```

dnn: *_DENORMALS_ZERO_MODE is defined for SSE3

---

modules/imgcodecs/src/grfmt_tiff.cpp
modules/imgcodecs/test/test_tiff.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/758
For the tiff file which has 1 bpp, it will fail after calling CV_TIFF_CHECK_CALL. But TIFFGetField for bpp failed will not influence the final image decoding result. I have attached a tiff file for this case.(https://drive.google.com/file/d/1NurdgX8QF_7Nig-k6n_BFDY52_pY8Yob/view?usp=sharing)
Too many CHECK will result regression.
<cut/>
```
opencv_extra=master
```

fix bug for CHECK bpp issue

---

modules/core/src/system.cpp

Previous code does not work for values like 100000MB.
The overflow itself is in line `return v * 1024 * 1024;`.

Fix integer overflow in parseOption().

---

cmake/templates/opencv-XXX.pc.in

The legacy `includedir` was removed in 4.0 (https://github.com/opencv/opencv/pull/12477) but it was not removed from the `.pc` file.
The non-existing path causes issues when trying to link against OpenCV using pkg-config in CMake.

pkg-config: Drop broken include path

---

modules/dnn/src/dnn.cpp
modules/dnn/src/dnn_common.hpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/ie_ngraph.hpp
modules/dnn/src/precomp.hpp

dnn: update network dump code, include ngraph serialization

---

modules/videoio/src/cap_msmf.cpp

resolves #17400
Skip audio streams when looking for best format match.

videoio/MSMF: fixed audio stream handling

---

modules/imgproc/src/drawing.cpp
modules/imgproc/test/test_drawing.cpp

fixes https://github.com/opencv/opencv/issues/16875. The corresponding test is added.

fixed fillPoly, the overloaded variant with InputArrayOfArrays parameter

---

modules/dnn/perf/perf_net.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp
samples/dnn/tf_text_graph_common.py
samples/dnn/tf_text_graph_efficientdet.py

Model from https://github.com/google/automl/
| DNN_BACKEND_OPENCV | DNN_BACKEND_INFERENCE_ENGINE |
|---|---|
|241.67ms | 88.53ms |
CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/763
1. Download repository and checkout from https://github.com/google/automl/tree/master/efficientdet#2-pretrained-efficientdet-checkpoints
2. Run
```
python3 model_inspect.py --runmode=saved_model --model_name=efficientdet-d0  --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir
```
3. Optimize
```python
import tensorflow as tf
from tensorflow.python.tools import optimize_for_inference_lib
from tensorflow.tools.graph_transforms import TransformGraph
pb_file = 'savedmodeldir/efficientdet-d0_frozen.pb'
graph_def = tf.compat.v1.GraphDef()
try: …
```

EfficientDet text graph generator

---

doc/tutorials/imgproc/table_of_content_imgproc.markdown
doc/tutorials/imgproc/table_of_contents_contours.markdown

First step of #17245. 
This simply groups together contours related articles into their own section under Image Processing tutorials for an easier to follow structure.

Create separate section and table of contents for contours articles 

---

modules/features2d/misc/java/test/BruteForceDescriptorMatcherTest.java
modules/features2d/misc/java/test/FlannBasedDescriptorMatcherTest.java
modules/java/generator/gen_java.py

Issue: https://github.com/opencv/opencv/issues/11268
Affected classes in 3.4:
- BOWKMeansTrainer
- FlannBasedMatcher
- BFMatcher

Generate proper constructor for classes with smart pointer

---

modules/objdetect/src/cascadedetect_convert.cpp

- [ y] I agree to contribute to the project under OpenCV (BSD) License.
- [y ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [n ] There is reference to original bug report and related work - no bug report was opened. it's a straightforward fix.
- [n ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
Patch to opencv_extra has the same branch name. - simple fix for cascade conversions
- [n ] The feature is well documented and sample code can be built with the project CMake - simple fix

Fixed cascadedetect convert from old cascade to new

---

doc/tutorials/core/file_input_output_with_xml_yml/file_input_output_with_xml_yml.markdown
modules/core/include/opencv2/core/persistence.hpp
modules/core/src/persistence_cpp.cpp
modules/core/src/persistence_xml.cpp
modules/python/test/test_filestorage_io.py
samples/python/tutorial_code/core/file_input_output/file_input_output.py

1. fixed Python part of the tutorial about using OpenCV XML-YAML-JSON I/O functionality from C++ and Python.
2. added startWriteStruct() and endWriteStruct() methods to FileStorage
3. modifed FileStorage::write() methods to make them work well inside sequences, not only mappings.
it seems that in master branch just the tutorial should be fixed and CV_WRAP should be added to already existing startWriteStruct() and endWriteStruct() declarations in FileStorage class. Then everything works out of the box. But I can check it as soon as the patch gets merged into master and submit another master-specific patch, if needed.

fixed #17044

---

modules/imgproc/misc/java/test/ImgprocTest.java
modules/imgproc/src/shapedescr.cpp
modules/imgproc/test/test_fitellipse.cpp

... or close-to-singular cases.
Seems to resolve https://github.com/opencv/opencv/issues/10270

improved fitEllipse and fitEllipseDirect accuracy in singular cases

---

modules/core/include/opencv2/core/eigen.hpp

- fixes #17366
- [fixes](http://pullrequest.opencv.org/buildbot/builders/3_4_noICV-lin64-clang/builds/595) `warning: 'const' qualifier on reference type 'cv::InputArray' (aka 'const cv::_InputArray &') has no effect`
- [fixes](https://ocv-power.imavr.com/#/builders/9/builds/8727) requirement of C++11: `error: 'array' in namespace 'std' does not name a template type`
relates #17320
```
```

core: fix builds with eigen helper header

---

modules/dnn/src/dnn.cpp

relates #17393
Support output names like "3488.0" (layer 3488, port 0).
<cut/>
```
test_filter:Custom=*DNNTestOpenVINO*
test_filter:Custom Win=*DNNTestOpenVINO*
```

dnn(IE): fix layers extraction

---

modules/videoio/src/cap_ffmpeg_impl.hpp

decoder should be properly flushed after that.
resolves #17257
Windows wrapper will be updated later (~2 weeks).

videoio(ffmpeg): fix handling of AVERROR_EOF

---

modules/calib3d/include/opencv2/calib3d.hpp

Add instructions for how to use findEssentialMat() when camera matrices are different

---

modules/dnn/src/onnx/onnx_importer.cpp
samples/dnn/virtual_try_on.py

resolves: opencv/opencv#17463
```
```

Fixed virtual Try-On sample

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/include/opencv2/videoio/videoio_c.h

This fixes a broken link in the documentation (no functionality change) to the mp4ra website within the fourcc section.

- Fixing broken URL to mp4ra website

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp
modules/gapi/include/opencv2/gapi/gcompiled.hpp
modules/gapi/src/backends/cpu/gcpubackend.cpp
modules/gapi/src/backends/cpu/gcpubackend.hpp
modules/gapi/src/backends/cpu/gcpukernel.cpp
modules/gapi/src/backends/ocl/goclbackend.cpp
modules/gapi/src/backends/ocl/goclbackend.hpp
modules/gapi/src/backends/render/grenderocvbackend.cpp
modules/gapi/src/compiler/gcompiled.cpp
modules/gapi/src/compiler/gcompiled_priv.hpp
modules/gapi/src/executor/gexecutor.cpp
modules/gapi/src/executor/gexecutor.hpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/test/cpu/gapi_ocv_stateful_kernel_test_utils.hpp
modules/gapi/test/cpu/gapi_ocv_stateful_kernel_tests.cpp

Enable stateful kernels in G-API OCV Backend

---

platforms/android/build_sdk.py

This Pull Request
- fixes the build issue reported in #14668
- improves the checking of default locations for Android NDK by looking for an "NDK (Side by side)" installation
- improves the checking of default locations for Android make by taking the most recent version in the event of multiple versions being present
- outputs a hint at the end of the build about the environment variable ANDROID_NDK_HOME (required to build the samples) if it is not set
<cut/>
```
```

Add handling for Android "NDK (Side by side)"

---

modules/gapi/test/streaming/gapi_streaming_tests.cpp

Relates to https://github.com/opencv/opencv/issues/17470

Skip some GAPI tests if VideoCapture is not capable to playback video

---

samples/python/stitching_detailed.py

Fixes the help for `--features`, previously listed all possible values as default value.
Also adds the default value to the help for two other arguments

Fix '--help' of stitching_detailed.py sample

---

modules/videoio/cmake/plugin_standalone.cmake

Fix embedding of version information through .rc [extra file](https://github.com/opencv/opencv_3rdparty/blame/ffmpeg/master/ffmpeg/build_videoio_plugin.sh#L35).

videoio: fix plugins build

---

modules/dnn/src/cuda4dnn/primitives/resize.hpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Set thresholds for FP16 target:**
- YOLOv4 test
- EfficientDet test
**Disabled tests:**
- tf2_prelu (assertion fails; related issue #17263)
- MatMul (not supported)
**Fixed tests:**
- Resize layer with two inputs where the second input gives the shape (introduced in FlowNet PR)
All tests pass now!
```
```

cuda4dnn(resize, tests): allow two-input resize, fix test thresholds 

---

modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/op_inf_engine.hpp

Starting from 2020.2 this method is deprecated. See https://github.com/openvinotoolkit/openvino/blob/2020/inference-engine/include/ie_iextension.h
<cut/>
```
```

Removed error lisneter usage

---

cmake/OpenCVDetectCUDA.cmake
cmake/templates/cvconfig.h.in
modules/cudacodec/src/cuvid_video_source.hpp
modules/cudacodec/src/frame_queue.hpp
modules/cudacodec/src/precomp.hpp
modules/cudacodec/src/video_decoder.hpp
modules/cudacodec/src/video_parser.hpp

* detect header automatically and not based on version number
- CUDA 11 RC comes 
- with nvcuvid library (libnvcuvid.so)
- without the header file
- So building ends up with "header not found"
- Twisting more `ifdef`is chaos, so check before building.
```
```

CUDA: fix corner case of libnvcuvid

---

modules/dnn/src/cuda/functors.hpp

- faster and more accurate mish implementation
- the thresholds were set incorrectly in the #17200 (not wrong but less accurate)
\#                | Time (float)    | Time (float4)  | L2 norm*        | SM SOL (float) | SM SOL (float4)
---------------- | ----------------- | ------------------ | ----------------- | -------------------- | ---------------------
ReLU           | 1.47ms          | 1.39ms          | N/A                | 21.31%            | 14.04%
Mish (old)    | 1.51ms          | 1.39ms           | 0.00012458  | 40.27%             | 28.77%
Mish (new)  | 1.49ms          | 1.39ms           | 2.4583e-05   | 38.5%               | 23.5% 
\* L2 norm of the error vector for 16 million+ activations uniformly sampled from `[-50, 50]`
Code: …

cuda4dnn(mish): improve accuracy and performance

---

modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/op_inf_engine.cpp

Backport #17554
<cut/>
```
```

(3.4) Removed plugin dispatcher (backport 17554)

---

platforms/android/build_sdk.py

The `build_sdk.py` script in `platforms/android` has a `--no_samples_build` flag, which is supposed to disable building the sample projects. However, this only sets the `BUILD_ANDROID_EXAMPLES` CMake variable, and leaves the `INSTALL_ANDROID_EXAMPLES` CMake variable to `ON`. If you take a look at the [samples CMakeLists](https://github.com/opencv/opencv/blob/977e5afbacb7b6ecb91efe071629b636bd6fa807/samples/CMakeLists.txt#L41-L43), you will see that it's actually checking for either of this variables being true. Therefore, even with this flag set, it will still build the samples!
This pull request fixes that by changing both CMake variables. This does not affect the 3.4 branch (since this flag does not exist in 3.4) so it's based on master.
See details at …

platforms/android: fix --no_samples_build flag not working

---

modules/core/include/opencv2/core/cuda/common.hpp
modules/cudaimgproc/src/cuda/canny.cu
modules/cudaimgproc/test/test_canny.cpp
modules/cudaoptflow/src/cuda/tvl1flow.cu
modules/cudaoptflow/test/test_optflow.cpp

Fixes #16013
We are going to use texture object, rather than texture reference.
It allows us to run the algorithm asynchronously.
This is similar to what's been done in #11483
<cut/>
```
```

cuda optflow TVL1 : run safely in async mode

---

platforms/android/build_sdk.py

resolves #17572 Build for Android failed: "can't concat str to bytes"
on Windows 10 64bit with python 3.6.6

fixing #17572

---

modules/imgproc/src/color_yuv.simd.hpp

The symbol "scr1" is already defined in the mingw-w64 runtime package in "mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32\include\dlgs.h" (included through "windows.h" for example).
=> renaming of variables to avoid this conflict: `scr1 => v_scr1`
resolves #17546

imgproc(color_yuv.simd): Fix the build using MinGW

---

modules/cudaimgproc/src/cuda/canny.cu

relates #17556 
* After #17556 , the build on Jetson TX1 and TX2 fails
* enable_if_t and is_base_of is c++14 feature
* override is c++11 feature
```
opencv/modules/cudaimgproc/src/cuda/canny.cu(110): warning: "override" and "final" are C++11 features
opencv/modules/cudaimgproc/src/cuda/canny.cu(131): error: namespace "std" has no member "enable_if_t"
```

CUDA: fix build error on Jetson TX1 and TX2

---

modules/cudaoptflow/src/cuda/tvl1flow.cu

Relates #17581
* I missed one more `enable_if_t` in `cudaoptflow` 
* This will let Jetson TX1 and TX2 let build
* `enable_if_t` is a c++14 feature
```
```

fix build on Jetson TX1 and TX2

---

doc/opencv.bib

Linkfix, the [current link](https://arxiv.org/pdf/1808.01752) goes to a random unrelated paper.

docs: linkfix in bibliography

---

modules/dnn/src/darknet/darknet_io.cpp

resolve: #17415
```
test_filter:Custom=*YOLO*
```

Disabling default NMS in yolo layer

---

modules/videoio/cmake/detect_ximea.cmake

The location of the XIMEA library is not the same in all versions of this software.
The search path is updated to take into account the different locations identified.

videoio(ximea): fix the detection of the XIMEA library

---

modules/dnn/src/ie_ngraph.cpp

Tested with the changes from https://github.com/openvinotoolkit/openvino/pull/963
<cut/>
```
#build_image:Custom=ubuntu-openvino-2020.2.0:16.04 - OK
```
/cc @ilya-lavrenov

Remove deprecated Inference Engine CPU extensions

---

modules/dnn/src/ie_ngraph.cpp

ports https://github.com/opencv/opencv/pull/17622
<cut/>
```
test_filter:Custom=*OpenVINO*
```

(master) Remove deprecated Inference Engine CPU extensions

---

modules/dnn/test/test_ie_models.cpp

backport #17616
<cut/>
```
test_filter:Custom=*OpenVINO*
```

(3.4) Conditional compilation for network reader

---

modules/dnn/src/layers/elementwise_layers.cpp

Use approximation for Mish layer introduced by @YashasSamaga in https://github.com/opencv/opencv/pull/17200 for CPU  backend.
| | 3.4 | PR |
|---|---|---|
|YOLOv4 @ 416x416 | 475.93ms | 246.38ms (x1.93)
Also tried the following nGraph implementation:
```cpp
float two = 2.f, thresh = 20.f;
auto two_node = std::make_shared<ngraph::op::Constant>(ngraph::element::f32, ngraph::Shape{1}, &two);
auto thresh_node = std::make_shared<ngraph::op::Constant>(ngraph::element::f32, ngraph::Shape{1}, &thresh);
auto x = std::make_shared<ngraph::op::v1::Minimum>(node, thresh_node);
auto exp_node = std::make_shared<ngraph::op::v0::Exp>(x);
auto add = std::make_shared<ngraph::op::v1::Add>(exp_node, two_node);
auto mul = std::make_shared<ngraph::op::v1::Multiply>(add, exp_node);
auto add2 = …
```

Optimize Mish for CPU backend

---

modules/dnn/src/cuda/functors.hpp

The FP32 mish is well optimized. It's sufficiently optimized that converting the FP16 input to FP32 and applying the FP32 mish activation is faster than the FP16 direct mish computation (what is currently on master).
<cut/>
\#                            | master                    | (this PR)             | tkDNN (with TensorRT)
------------------------- |  ------------------------ | --------------------- | --------------------------------
YOLOv4 608 x 608 | 9.75ms                      | 9.50ms            | 9.01ms
</cut>
<details>
<summary>raw performance stats (master)</summary>
```
YOLO v4
[CUDA FP32]
init >> 438.666ms
inference >> min = 17.583ms, max = 21.566ms, mean = 18.0522ms, stddev = 0.898828ms
[CUDA FP16]
init >> 422.158ms
inference >> min = 9.704ms, max = 9.862ms, mean = …
```

cuda4dnn(mish): use fp32 mish for fp16 mish (faster and more accurate)

---

modules/gapi/src/backends/plaidml/gplaidmlcore.cpp
modules/gapi/test/gapi_plaidml_pipelines.cpp

`cv::gapi::core::plaidml::kernels()` has got implementation only under `HAVE_PLAIDML` macro while API available without this macro, so in case using this function without `HAVE_PLAIDML` it will cause linking error
```
build_image:Custom=plaidml2
test_filter:Custom=*ML*
```

G-API: Add default implementation for plaidml::kernels

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp
modules/gapi/include/opencv2/gapi/gcommon.hpp
modules/gapi/include/opencv2/gapi/gcompiled.hpp
modules/gapi/src/backends/common/gbackend.hpp
modules/gapi/src/backends/cpu/gcpubackend.cpp
modules/gapi/src/backends/cpu/gcpubackend.hpp
modules/gapi/src/backends/cpu/gcpukernel.cpp
modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/src/backends/ocl/goclbackend.cpp
modules/gapi/src/backends/ocl/goclbackend.hpp
modules/gapi/src/backends/plaidml/gplaidmlbackend.cpp
modules/gapi/src/backends/render/grenderocvbackend.cpp
modules/gapi/src/compiler/gcompiled.cpp
modules/gapi/src/compiler/gcompiled_priv.hpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/src/executor/gexecutor.cpp
modules/gapi/src/executor/gexecutor.hpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.hpp
modules/gapi/test/cpu/gapi_ocv_stateful_kernel_tests.cpp
modules/gapi/test/gapi_compile_args_tests.cpp

<cut/>
```
**WIP**
build_image:Linux AVX2=ubuntu-clang:18.04 …
```

Enable state initialization params via compile_args

---

modules/flann/include/opencv2/flann/kdtree_single_index.h

Instead of using the current dimension for which we just got a big span,
we were computing Min and Max for the previous dimension stored in cutfeat
(and using 0 instead of the dimension indice for the very first dimension
with "span > (1-eps)max_span")
relates #17607
<cut/>

Fix: error in the dimension used for computeMinMax

---

modules/dnn/src/dnn.cpp
modules/dnn/src/op_inf_engine.hpp

backport #17658
<cut/>
```
```

(3.4) Conditional compilation for IR v7 support

---

cmake/OpenCVDetectCUDA.cmake

relates #17526 
resolves #17598

CUDA: fix native detection on Jetson

---

modules/core/include/opencv2/core/cvdef.h

Detailed discussion: https://stackoverflow.com/questions/48213572/c-macro-to-test-availability-of-func-function-pretty-function-e

Increased portability of CV_Func

---

modules/imgcodecs/src/ios_conversions.mm

UIImageToMat() fail to convert indexed color image now.
This is because CGBitmapContextCreate() in UIImageToMat() don't support indexed color spaces.
I added if block for indexed color spaces.
CGBitmapContextCreate
https://developer.apple.com/documentation/coregraphics/1455939-cgbitmapcontextcreate?language=objc
- [○] I agree to contribute to the project under OpenCV (BSD) License.
- [○] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [○] The PR is proposed to proper branch
- [○] The feature is well documented and sample code can be built with the project CMake

support indexed color images on iOS

---

modules/gapi/CMakeLists.txt

resolves #17677
[Failed nightly builds](http://pullrequest.opencv.org/buildbot/builders/master_winpack-build-win64-vc15/builds/907).
```
build_world:Custom Win=ON
```

cmake(gapi): fix opencv_world build for winpack

---

modules/gapi/src/backends/common/serialization.cpp

min max fix for G-API standalone build

---

cmake/OpenCVDetectCUDA.cmake

Introduced in https://github.com/opencv/opencv/pull/17499
<cut/>
```
buildworker:Custom=linux-2,linux-4
```

Restored compatibility with CMake older than 3.7.

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/test/test_darknet_importer.cpp

Merge with extra: opencv/opencv_extra#770
relates #17666
<cut/>
```
force_builders=Linux32,Win32,Custom,Custom Win,Custom Mac
test_filter:Custom=*YOLO*:*VINO*:*ENet*:*route*
test_filter:Custom Win=*YOLO*:*VINO*:*ENet*:*route*
```

Supported yolov4-tiny

---

modules/calib3d/src/fisheye.cpp
modules/calib3d/test/test_fisheye.cpp

Fisheye undistorting points is unstable in configurations with larger distortion coefficients. Lets assume a standard situation of undistorting  images and redistorting it with new fisheye distortion coefficients.
<cut/>
The following test image from Cityscapes datasets is used
The following settings show that the current implementation is instable for larger distortion coefficients.
Distortion Parameters 1: [3.0, 0.0, 0.0, 0.0]
Distortion Parameters 2: [9.0, 0.0, 0.0, 0.0]
The current implementation shows a lot of noise outside the actual image. To fix this, the optimization can be improved by checking the convergence and returning an invalid point otherwise.
Results of improvement A:
Distortion Parameters 1: [3.0, 0.0, 0.0, 0.0]
Distortion Parameters 2: [9.0, 0.0, 0.0, 0.0]
As visible, …

fix instable fisheye undistortPoints

---

cmake/OpenCVFindOpenBLAS.cmake

When provide environment variable `OpenBLAS_HOME`, `OpenCVFindOpenBLAS.cmake` forgets to look in `${OpenBLAS_HOME}/include/openblas` for include files.

forget to look in sub folder of include/openblas

---

modules/dnn/src/cuda/concat.cu
modules/dnn/src/cuda/slice.cu
modules/dnn/src/cuda4dnn/primitives/slice.hpp
modules/dnn/src/dnn.cpp

- reduces slice to copy if possible (like in YOLOv4 Tiny)
- reduces concat to copy if possible
- enables more concat fusions
slice from yolov4 tiny         | master            | this PR
--------- | ------------------ | ----------
slice1  | 46us                | 31us
slice2  | 25us                | 17us
slice3  | 19us                | 9us
I think it's possible to fuse slice just like concat but it seems to be a more complex than concat fusion.
<cut/>
```
```

cuda4dnn(slice, concat): reduce slice and concat to copy, more concat fusions

---

modules/imgcodecs/test/test_read_write.cpp

imgcodecs: fix test build with disabled JPEG and PNG libs

---

modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/layers/prior_box_layer.cpp
modules/dnn/src/layers/proposal_layer.cpp
modules/dnn/src/layers/reorg_layer.cpp
modules/dnn/src/layers/resize_layer.cpp

backport #17756
<cut/>
```
```

(3.4) Fixed header paths for some nGraph ops

---

modules/dnn/CMakeLists.txt
modules/dnn/src/cuda4dnn/csl/cudnn/convolution.hpp
modules/dnn/src/cuda4dnn/csl/cudnn/transpose_convolution.hpp

There are five tests failing on GTX 1050 which are not fixable (no convolution algorithm found). These might be limited to 6.1 devices or devices that don't support good FP16 performance.
```
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] Test_ONNX_layers.Convolution3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_ONNX_layers.PoolConv3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_ONNX_nets.Resnet34_kinetics/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.Convolution3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.concat_3d/1, where GetParam() = CUDA/CUDA_FP16
```
Related #17496
fixes #17747 
**Pending:**
- test on CUDA11
<cut/>
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull- …

cuda4dnn(build): add basic support for cuDNN 8

---

CMakeLists.txt
cmake/OpenCVDetectCUDA.cmake
modules/core/include/opencv2/core/cuda_types.hpp

<cut/>
- Fixes error message:
> cuda_types.hpp(109): error C3861: 'data': identifier not found
```
Xforce_builders_only=Custom,Custom Win
build_image:Custom=ubuntu-cuda11:18.04
Xbuild_image:Custom Win=cuda10
```

(3.4) CUDA: fix build

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp
samples/cpp/tutorial_code/snippets/imgcodecs_imwrite.cpp

**Update documentation of imwrite()**
see [documentation preview](https://pullrequest.opencv.org/buildbot/export/pr/17728/docs/d4/da8/group__imgcodecs.html#gabbc7ef1aa2edfaa87772f1202d67e0ce)

Update documentation of imwrite()

---

modules/dnn/src/dnn.cpp

- clamps concat axis before use (otherwise valid fusions where axis is negative won't happen)
-  generalizes the axis requirement from channels to any axis as long as all channels preceding the concat axis are singleton
I haven't fixed the comments. Not sure how to rewrite them.
For the list of models you find [here](https://gist.github.com/YashasSamaga/48bdb167303e10f4d07b754888ddbdcf/edit):
number of concat fusions before: 60
number of concat fusions after: 72
List of fusions before and after: https://gist.github.com/YashasSamaga/94449832c25f2993cfc8ffc0a8bdf618

dnn: allow concat fusion for non-channel axis

---

cmake/OpenCVDetectCUDA.cmake
cmake/templates/cvconfig.h.in
modules/core/include/opencv2/core/private.cuda.hpp

Previously added ccbin option into `CUDA_NVCC_FLAGS` breaks other CUDA scripts (which expect `CUDA_HOST_COMPILER` only).
- revert ccbin PRs: #17526 #17671
- preventive fix for arch "11.0" (`CUDA_ARCH_BIN_OR_PTX_10` bug)
- new var: `OPENCV_CUDA_DETECTION_NVCC_FLAGS`
- new var: `OPENCV_CMAKE_CUDA_DEBUG`
resolves #17704
<cut/>
```
force_builders_only=Custom,Custom Win
xbuild_image:Custom=ubuntu-cuda:18.04
build_image:Custom=ubuntu-cuda11:18.04
Xbuild_image:Custom Win=cuda10
```

cmake(cuda): repair ccbin, re-implement execute_process() cache

---

cmake/OpenCVDetectCUDA.cmake
cmake/templates/cvconfig.h.in
modules/core/include/opencv2/core/private.cuda.hpp

backport #17745 and others
- excluded CUDNN
- changed C++11 condition
<cut/>
```
force_builders_only=Custom,Custom Win
build_image:Custom=ubuntu-cuda11:18.04
Xbuild_image:Custom Win=cuda10
```

(3.4) cmake: backport CUDA scripts

---

modules/imgproc/perf/opencl/perf_filters.cpp
modules/imgproc/src/filter.dispatch.cpp
modules/imgproc/src/filter.hpp
modules/imgproc/src/opencl/filterSepCol.cl
modules/imgproc/src/opencl/filterSepRow.cl
modules/imgproc/src/opencl/filterSep_singlePass.cl
modules/imgproc/src/smooth.dispatch.cpp
modules/imgproc/test/ocl/test_sepfilter2d.cpp
modules/stitching/src/exposure_compensate.cpp

resolves #16214
relates #2635
relates #15855
- do not truncate/round kernel values
TODO:
<cut/>
```
buildworker:Linux OpenCL=linux-2
```

OCL: imgproc: align GaussianBlur/sepFilter2D OpenCL with CPU version

---

modules/dnn/src/cuda4dnn/csl/event.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/op_cuda.hpp

Some models like YOLOv3, YOLOv4, Mask RCNN, etc. have multiple output blobs. Currently, the output blobs are transferred one after another after the inference is completed. This PR allows output blobs that are computed early during inference to be copied to CPU buffers while rest of inference is still happening on the GPU.
YOLOv4 has three output blobs and they take approximately 0.5ms, 0.3ms and 0.03ms to be copied to the CPU. This PR begins transferring the 0.5ms blob as soon as possible simultaneously as GPU is doing rest of the inference.
<cut/>
Profiling shows that the transfer of 0.5ms and 0.3ms blob is now completely hidden. The PINK indicates D2H memory operation.
Gains are big for YOLOv4 as the importer somehow sets up the network to compute 0.5ms blob first, 0.3ms blob next and …

cuda4dnn: overlap D2H output blobs transfer with inference

---

modules/features2d/src/sift.simd.hpp

<details>
<summary>Test cases</summary>
<pre>
feature2d_detect.
detect/57  # GetParam() = (SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")
detect/58  # GetParam() = (SIFT_DEFAULT, "stitching/a3.png")
detect/59  # GetParam() = (SIFT_DEFAULT, "stitching/s2.jpg")
feature2d_extract.
extract/18  # GetParam() = (SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")
extract/19  # GetParam() = (SIFT_DEFAULT, "stitching/a3.png")
extract/20  # GetParam() = (SIFT_DEFAULT, "stitching/s2.jpg")
feature2d_detectAndExtract.
detectAndExtract/18  # GetParam() = (SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")
detectAndExtract/19  # GetParam() = (SIFT_DEFAULT, "stitching/a3.png")
detectAndExtract/20  # …

use universal SIMD intrinsics for SIFT

---

modules/flann/include/opencv2/flann/hierarchical_clustering_index.h

Before, when maxCheck was reached in the first descent of a tree, time was still wasted parsing
the next trees till their best leaves whose points were not used at all.

Fix trees parsing behavior in hierarchical_clustering_index:

---

modules/dnn/src/cuda/activation_eltwise.cu
modules/dnn/src/cuda/activations.cu
modules/dnn/src/cuda/bias_activation.cu
modules/dnn/src/cuda/bias_activation_eltwise.cu
modules/dnn/src/cuda/bias_eltwise_activation.cu
modules/dnn/src/cuda/eltwise_activation.cu
modules/dnn/src/cuda/eltwise_ops.cu
modules/dnn/src/cuda/functors.hpp
modules/dnn/src/cuda/scale_shift.cu
modules/dnn/src/cuda4dnn/csl/cudnn/convolution.hpp
modules/dnn/src/cuda4dnn/csl/span.hpp
modules/dnn/src/cuda4dnn/csl/tensor_ops.hpp
modules/dnn/src/cuda4dnn/kernels/activation_eltwise.hpp
modules/dnn/src/cuda4dnn/kernels/activations.hpp
modules/dnn/src/cuda4dnn/kernels/bias_activation.hpp
modules/dnn/src/cuda4dnn/kernels/bias_activation_eltwise.hpp
modules/dnn/src/cuda4dnn/kernels/bias_eltwise_activation.hpp
modules/dnn/src/cuda4dnn/kernels/eltwise_activation.hpp
modules/dnn/src/cuda4dnn/primitives/convolution.hpp
modules/dnn/src/cuda4dnn/primitives/eltwise.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/convolution_layer.cpp

- use `device::size_type` and `device::index_type` in `Span`
- refactor functors
- each functor has a `Params` member type (replacement for varidiac templates)
- fuses eltwise with convolution for three topologies (shown below)
- cuDNN fused convolution when actiation is ReLU and is applied after the eltwise operation
<cut/>
**activation(conv + eltwise)**
Examples: ResNet, ...
```
--------------               ---------------
| Bias Layer |               | Convolution |
--------------               ---------------
|                             |
|       ----------------      |
--------| Eltwise Sum  |-------
----------------
|
----------------
|  Activation  |                 
----------------
|
```
**eltwise + activation(conv)**
Examples: YOLOv3, YOLOv4, ....
```
-------------- …
```

cuda4dnn(conv): fuse eltwise with convolutions

---

modules/features2d/src/matchers.cpp
modules/features2d/test/test_matchers_algorithmic.cpp

resolves #17771
Applied patch from the issue + minor refactoring and formatting
<cut/>
```
```

Fixed checkMasks in DescriptorMatcher with train descs in UMats

---

modules/dnn/src/dnn.cpp

fixes #17796 
There were some CUDA backend specific changes in `dnn.cpp` which weren't done in #17752. This caused tests to fail on master.
All tests pass with this PR.
Sorry for the delay.
<cut/>
```
```

cuda4dnn(concat): fix concat fusion to work with arbitary axis

---

modules/features2d/src/blobdetector.cpp

double area = moms.m00;
is same as
double area = contourArea(contours[contourIdx]);
Not to mention
"moms" already calculated here,"contourArea" should not apply

Use"moms"replace "contourArea"

---

modules/features2d/src/sift.simd.hpp

clearer to understand the boundary of internal buffers
- [+] I agree to contribute to the project under OpenCV (BSD) License.
- [+] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [+] The PR is proposed to proper branch
- [+] There is reference to original bug report and related work
- [+] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [+] The feature is well documented and sample code can be built with the project CMake

use bufferarea for allocating buffer in SIFT

---

modules/videoio/src/cap_v4l.cpp

I am working with a triggered camera that uses v4l2 in Linux.  Because it is a triggered camera, a "select timeout" is very likely.  In the function `CvCaptureCAM_V4L::grabFrame`, there is an initialization process that is conditionally dependent on the variable `FirstCapture` being `True`.   If the first call to `read_frame_v4l2` returns `False`, the `FirstCapture` variable is never set to `True`.  This will cause a re-initialization on the next iteration along with impassible failure.  The following output is generated using OPENCV_LOG_LEVEL=DEBUG:
```none
[DEBUG:1] VIDEOIO(V4L2:/dev/video2): tryIoctl(3, VIDIOC_QBUF(3227014671), failIfBusy=1) …
```

3.4 Allow first capture to return false

---

modules/dnn/src/op_inf_engine.cpp

relates #14881
Try to re-enable this flag on Windows (was disabled for 2019R1).
<cut/>
```
Xbuild_image:Custom Win=openvino-2019r3.0
```

dnn(IE): enable KEY_CPU_THREADS_NUM for Windows

---

modules/gapi/include/opencv2/gapi/own/mat.hpp

Made arguments unnamed for explicitly-defaulted constructors and assign operators to avoid compiler warnings
```
```

GAPI: fix warnings in own::Mat default generated constructors/assign op

---

modules/dnn/CMakeLists.txt
modules/dnn/src/cuda4dnn/init.hpp
modules/dnn/src/dnn.cpp

- throws errors if the user marks `OPENCV_DNN_CUDA` but cuDNN, cuBLAS or CUDA dependencies haven't been resolved
- check if device supports fp16 before using `DNN_TARGET_CUDA_FP16`
- check if device is compatible before use (device cc applicable from the list in `CUDA_ARCH_BIN` or `CUDA_ARCH_PTX` )
- check if a valid device is selected before init
- reduce the chances of future bugs by setting streams in `initCUDABackend` (see #17359) 
- check CUDART version with the version used in build
- check cuDNN version with the version used in build
- ensure that cuDNN's CUDART version matches with the CUDART version being used
<cut/>
``` …
```

cuda4dnn: catch common build mistakes early and better diagnostics

---

modules/gapi/src/logger.hpp

This patch add missing `GAPI_LOG_DEBUG`  facility.
<cut/>
```
```

GAPI: GAPI_LOG_DEBUG facility

---

modules/dnn/test/test_model.cpp

<cut/>
```
Xbuild_image:Custom Win=openvino-2019r3.0
Xtest_filter:Custom=*lice*:*plit*:*Test_Model*
Xtest_filter:Custom Win=*lice*:*plit*:*Test_Model*
```

dnn(test): adjust tests for OpenVINO 2020.4 (4.x branch)

---

modules/core/include/opencv2/core/version.hpp

OpenCV 3.4.11
relates #17501
<cut/>
<details>
[opencv_world3411.dll (vc14)](https://www.virustotal.com/gui/file/b74a7cf8d3d4adbc749cb45b3e270ad10937ff4dc02f206aa7c31df180ea91cf/detection)
[opencv_world3411d.dll (vc14)](https://www.virustotal.com/gui/file/35df2c2a211528f9966e2feaf88f25862e746389413300c0d697e8516db27d5c/detection)
[opencv_world3411.dll (vc15)](https://www.virustotal.com/gui/file/781138599cae9e9abc1dd353518635a6df40c440d4048f233e2380fe7011fda8/detection)
[opencv_world3411d.dll (vc15)](https://www.virustotal.com/gui/file/e6aeb211c7a542a003197135aca789fa1a42681907b6e328d20eabe2732fe5e9/detection)
[opencv_ffmpeg3411_64.dll](https://www.virustotal.com/gui/file/431947a3feb6e67f0a9d1bcc9480a0fcde16c02fc355e8be0fee186c93cc23a2/detection) …

release: OpenCV 3.4.11

---

modules/core/include/opencv2/core/persistence.hpp
modules/core/src/persistence.cpp
modules/core/test/test_io.cpp

- do not store user-controlled "FileStorage" pointer
- store FileStorage::Impl pointer instead
resolves #17876
```
force_builders=win32
```

core(persistence): fix "use after free" bug

---

modules/dnn/src/ie_ngraph.cpp

Replaced copy_with_new_args to clone_with_new_inputs

---

modules/cudaarithm/src/core.cpp
modules/cudaarithm/test/test_core.cpp

Resolves #17840 
https://github.com/opencv/opencv/pull/17863#issuecomment-661536808
~~`cv::cuda::GpuMat::create` does not allocate a new GpuMat if required size and type equals existing size and type.~~
https://github.com/opencv/opencv/blob/bf8136eaa68d8f17edba929622ddba05f95c89d8/modules/core/src/cuda/gpu_mat.cu#L160-L161
~~This PR implements `cv::cuda::detachOutput` to allocate a new GpuMat in such cases. Unfortunately, `_dst` is const so assignment is not possible. Instead, this implementation clones `src`.~~

cuda::flip - Use in-place npp function for inplace arguments

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/cap_ffmpeg.cpp
modules/videoio/src/cap_ffmpeg_api.hpp
modules/videoio/src/cap_ffmpeg_impl.hpp
modules/videoio/test/test_ffmpeg.cpp

Relates to #15499
Duplicates commit of https://github.com/opencv/opencv/pull/17452
```
```

FFmpeg cap consider rotation metadata 3.4

---

modules/cudaarithm/test/test_element_operations.cpp

let test pass on Jetson

---

modules/gapi/test/common/gapi_video_tests_common.hpp

- fix numeric overflow due to incorrect type casting:
The result of expression `nPointsX*nPointsY` generated 4-byte type while casting to a bigger size of 8-byte
- remove unnecessary default constructor
``` …
```

GAPI: KW fix - video_tests

---

modules/gapi/include/opencv2/gapi/gtyped.hpp
modules/gapi/test/gapi_typed_tests.cpp

1) `GArray<GMat>` ProtoParam's type in `gtyped.hpp` is now `std::vector<cv::Mat>`
It is needed for typed version of `GComputation`,  `GComputationT` in case a graph's input/output node is `GArray<GMat>`
2) Tests for using GArray<GMat> with GComputation added
3) Added the possibility to pass compile_args to GComputationT::apply() fro convenient usage in tests
``` …
```

GAPI: Overload for `GArray<GMat>` ProtoParam

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/five-point.cpp
modules/calib3d/test/test_cameracalibration.cpp

updated variant of #17551 by @tompollok with a little smoke test for the new function.
<cut/>

findEssentialMatrix: 2 camera matrices

---

modules/calib3d/src/calibration_handeye.cpp
modules/calib3d/test/test_calibration_hand_eye.cpp

the documentation [suggests using PnP](https://docs.opencv.org/trunk/d9/d0c/group__calib3d.html#gaebfc1c9f7434196a374c382abf43439b) for the camera pose, but solvePnP returns a Rodrigues vector and there are no checks warning you about this..

calib3d: calibrateHandEye - allow using Rodrigues vectors for rotation

---

modules/imgcodecs/src/grfmt_jpeg2000.cpp

libjasper has recently changed `jas_matrix_get` from a macro to an inline function (389951d07 @ https://github.com/jasper-software/jasper), causing the build to fail with `error: lvalue required as unary ‘&’ operand`.
This likely also affects the Opencv 3 and 2 branches; I can create a PR for these, too, if desired.

Fix build of grfmt_jpeg2000.cpp

---

3rdparty/carotene/CMakeLists.txt
3rdparty/carotene/hal/CMakeLists.txt
3rdparty/carotene/hal/dummy.cpp
3rdparty/carotene/src/dummy.cpp

When building with XCode for ARM, carotene and tegra_hal static libraries will be deleted. Probably caused by issue: https://gitlab.kitware.com/cmake/cmake/-/issues/17457
From cmake docs:
>Some native build systems may not like targets that have only object files, so consider adding at least one real source file

Fix Carotene compilation with XCode

---

modules/dnn/src/cuda/bbox_utils.hpp
modules/dnn/src/cuda/block_stride_range.hpp
modules/dnn/src/cuda/detection_output.cu
modules/dnn/src/cuda/fill_copy.cu
modules/dnn/src/cuda/functors.hpp
modules/dnn/src/cuda/grid_nms.cu
modules/dnn/src/cuda/grid_stride_range.hpp
modules/dnn/src/cuda/index_helpers.hpp
modules/dnn/src/cuda/math.hpp
modules/dnn/src/cuda4dnn/csl/tensor.hpp
modules/dnn/src/cuda4dnn/kernels/detection_output.hpp
modules/dnn/src/cuda4dnn/kernels/grid_nms.hpp
modules/dnn/src/cuda4dnn/primitives/detection_output.hpp
modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/test/test_model.cpp
modules/dnn/test/test_tf_importer.cpp

Many object detection models can now fully run on the GPU without requiring CPU fallback.
**Approximation in findTopK:**
The confidence values are in the range `[0.0, 1.0]`. The findTopK kernel creates N bins (2048 in this PR). The bins are all stored in the shared memory on the GPU and hence no additional global memory workspace is required. Each block (workgroup) processes one class. The bins are indexed by `(confidence - conf_threshold) *BINS`. The sorting has a precision of 1/N (~`0.0005`). All errors in sorting are off by at most 1/N.
Choosing N is a tradeoff between performance and accuracy. Larger N gives more accurate sorting but is slower.
<cut/>
**Why does ResNet50 Faster RCNN test have low test thresholds?**:
The test fails sometimes. The atomic operations used in approximate …

cuda4dnn(DetectionOutput): add fast approximate DetectionOutputOp

---

modules/dnn/src/cuda4dnn/primitives/convolution.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/convolution_layer.cpp

Eltwise layer can create two types of operators: `ShortcutOp` and `EltwiseOp`. There is a dynamic cast to `EltwiseOpBase` to retrieve configuration to check fusion compatibility. No check is made to see if the cast was successful (required since some `EltwiseLayer` use `cuda4dnn::ShortcutOp` which is not derived from `EltwiseOpBase`).
fixes #17934 
fixes #17946 for master
fixes cuda part of #17964 

cuda4dnn(Eltwise, Power): fix eltwise fusion, enable more eltwise fusion, fix power fusion

---

cmake/OpenCVDetectCUDA.cmake

resolves #16649
* update minimum requirement of CUDA to 8.0
* remove deprecated version checks
Still, this PR is open for discussion.
Supporting different CUDA based on branch is one solution.
Updating CUDA 8.0 is also another point to discuss.
It's still possible to build for old CC, by specifying `CUDA_ARCH_BIN` manually at cmake stage
<cut/>
```
```

CUDA: drop support of old CC

---

doc/opencv.bib
modules/features2d/include/opencv2/features2d.hpp
modules/features2d/src/affine_feature.cpp
modules/features2d/test/test_affine_feature.cpp
samples/cpp/asift.cpp

ASIFT in C++.
The reason of the redundant test script is that it is for a future testdata generated by Python implementation (asift.py). Filestorage in python's opencv is supporting only cv::Mat. So this test uses cv::Mat for storing/reading generated data.
I referred:
- Python implementation in https://github.com/opencv/opencv/blob/3.4/samples/python/asift.py
- C++ implementation in https://github.com/kukuruza/Erie
Actually my implementation is different from Erie, but I used some idea from that.
I have no idea how to specify its contribution so please give me some advice.
This PR is related to Issue #4399 .
Test data is in https://github.com/opencv/opencv_extra/pull/775
I compared the extraction time for the 1st image (aero1.jpg) described in asift.py.
For C++ backend, I measured the …

Implement ASIFT in C++

---

modules/dnn/include/opencv2/dnn/all_layers.hpp

Adds a comment written in the source code for bool getMemoryShapes into the DetectionOutputLayer class documentation, as requested in this issue:
resolves #14645
```
```

Adding comment from source code to DetectionOutputLayer class documentation

---

modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

relates: #17647
**merge with extra:** opencv/opencv_extra#777
<cut/>
```
```

Supported convolution with non-const weights

---

modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/layers/permute_layer.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_misc.cpp

resolves https://github.com/openvinotoolkit/openvino/issues/1503
resolves https://github.com/opencv/opencv/issues/17954
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/779
```
#build_image:Custom=ubuntu-openvino-2020.1.0:16.04
```

Replace nGraph's i64 to i32 for size_t

---

modules/imgproc/include/opencv2/imgproc.hpp
samples/cpp/warpPerspective_demo.cpp

updates warpPerspective_demo.cpp

Update doc and sample

---

modules/videoio/src/cap_aravis.cpp

Hi,
Module videoio fails to compile on recent master if WITH_ARAVIS is set. GCC 9.3.0 reports the following errors:
`opencv/modules/videoio/src/cap_aravis.cpp:505:14: error: ‘CAP_PROP_ARAVIS_AUTOTRIGGER’ was not declared in this scope; did you mean ‘cv::CAP_PROP_ARAVIS_AUTOTRIGGER’?`
`opencv/modules/videoio/src/cap_aravis.cpp:594:14: error: ‘CAP_PROP_ARAVIS_AUTOTRIGGER’ was not declared in this scope; did you mean ‘cv::CAP_PROP_ARAVIS_AUTOTRIGGER’?`
The proposed patch fixes the code accordingly.

videoio: fix compilation with Aravis enabled

---

modules/stitching/include/opencv2/stitching.hpp
modules/stitching/misc/python/test/test_stitching.py

Related to https://github.com/opencv/opencv/issues/17956, enable calling composePanorama with both function signatures in Python, and add tests to verify both implementations can run with the test images.
- *[x] I agree to contribute to the project under OpenCV (BSD) License.
- *[x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- *[x] The PR is proposed to proper branch
- *[x] There is reference to original bug report and related work

Add Python binding for composePanorama

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/test/test_darknet_importer.cpp

Addressing the issue described in https://github.com/opencv/opencv/issues/17778 to enable using both leaky ReLU and ReLU. This PR should be merged in conjunction with https://github.com/opencv/opencv_extra/pull/784, which adds the test data for the new activation function.
- *[x] I agree to contribute to the project under OpenCV (BSD) License.
- *[x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- *[x] The PR is proposed to proper branch
- *[x] There is reference to original bug report and related work
- *[x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable …

Add ReLU Activation to DarkNet Importer

---

modules/dnn/src/ie_ngraph.cpp

backports https://github.com/opencv/opencv/pull/17888 + https://github.com/opencv/opencv/pull/17894
```
```

Dnn backport ngraph

---

modules/core/src/cuda/gpu_mat.cu
modules/cudaarithm/test/test_gpumat.cpp

Resolves #13092
If given in-place arguments to `GpuMat::convertTo`, `*this` and `dst` refers to the same newly allocated GpuMat after these two lines:
```
_dst.create(size(), rtype);
GpuMat dst = _dst.getGpuMat();
```
<cut/>
In consequence, `*this` refers to a different GpuMat from which `src` refers to.
Before this PR, in the following line:
```
funcs[sdepth][ddepth](reshape(1), dst.reshape(1), stream);
```
the first argument derives from `*this` which refers to the same data as `dst`.
So it should be fixed as the following line to make the first argument derive from `src`:
```
funcs[sdepth][ddepth](src.reshape(1), dst.reshape(1), stream);
^^^^
```
Patch to opencv_extra has the same branch …

cuda::GpuMat::convertTo - fix for in-place arguments

---

modules/core/misc/objc/common/Converters.h

Partial fix for #18049
- fix incorrect return type in the declaration of `Mat_to_vector_Point2d` (Objective-C version)

Fix Objective-C declaration of Mat_to_vector_Point2d

---

modules/dnn/src/cuda/detection_output.cu
modules/dnn/test/test_onnx_importer.cpp

1. There was ill-formed code in #17301 which should have resulted in compile-time errors. clang and gcc 9+ diagnose it correctly. MSVC and gcc 8 and below don't.
2. Disables variable weights convolution test as it is not supported.
fixes #18030 
<cut/>
```
```

cuda4dnn(DetectionOutput, tests): fix compile-time errors, disable unsupported tests

---

modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_tf_importer.cpp

relates: #14312
merge with extra: opencv/opencv_extra#787
<cut/>
```
```

Supported ReduceSum op

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_layers.cpp

fixes #17946 for 3.4
<cut/>
```
test_filter:Custom=*TestLayerFusion*
test_filter:Custom Win=*TestLayerFusion*
```

dnn: add exhaustive fusion tests, enable more eltwise fusions

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

relates: #18076
merge with extra: opencv/opencv_extra#788
<cut/>
```
```

Fix MatMul and Add axes

---

modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves: #16235
merge with extra: opencv/opencv_extra#792
<cut/>
```
```

Added ReduceSum to ONNX importer

---

modules/core/src/ocl.cpp

in case of `OPENCV_OPENCL_DEVICE=disabled`
<cut/>
Error message:
```
RUN      ] Image2D.turnOffOpenCL
Exception message: OpenCV(3.4.11-dev) /home/alalek/projects/opencv/dev/modules/core/src/ocl.cpp:6466: error: (-220:Unknown error code -220) OpenCL error CL_INVALID_CONTEXT (-34) during call: clGetSupportedImageFormats(CL_MEM_OBJECT_IMAGE2D, NULL) in function 'isFormatSupported'
/home/alalek/projects/opencv/dev/modules/core/test/ocl/test_image2d.cpp:78: Failure
Expected: isFormatSupported = cv::ocl::Image2D::isFormatSupported(0, 1, true) doesn't throw an exception.
Actual: it throws.
CV_8UC1 is not supported for OpenCL images. Test skipped.
[  FAILED  ] Image2D.turnOffOpenCL (0 ms)
```

core(OpenCL): fix ocl::Image2d::isFormatSupported()

---

modules/core/src/copy.cpp

improve Mat::operator=(Scalar)
- Mat::zeros() is faster than Mat::ones(). 
- The reason is that Mat::zeros() use memset(), but Mat::ones() use memcpy() for every row.
- As a result, Mat::ones() need more memory access than Mat::zeros().
-  I modified Mat::operator=(Scalar) that use memset() on possible case. ( 8U, 8S, and 8UC3 same scalar element etc...)
- 50% performance enhancement

improve Mat::operator=(Scalar)

---

modules/highgui/src/window_gtk.cpp

- allow Users to handle such case
- exception will be thrown instead
Useful for docker containers or other environments without configured DISPLAY.
GTK doc reference:
- https://developer.gnome.org/gtk3/stable/gtk3-General.html#gtk-init
- https://developer.gnome.org/gtkglext/stable/gtkglext-gtkglinit.html
<cut/>
-----
Before:
- `terminate()` called with message "Gtk-WARNING **: 09:37:26.975: cannot open display:"
After:
- throws C++ exception from imshow() and subsequent calls.

highgui: don't terminate if we can't initialize GTK backend

---

modules/features2d/include/opencv2/features2d.hpp
modules/features2d/src/sift.dispatch.cpp
modules/features2d/src/sift.simd.hpp
modules/features2d/test/test_sift.cpp

I added an option so that SIFT can return 8-bit descriptors instead of 32-bit floating-point descriptors.
(David Lowe in his paper uses 8-bit descriptors)
These 8-bit descriptors must be equal to 32-bit floating-point ones because the current implementation applies `saturate_cast<uchar>` to the descriptors. (The test `Features2d_SIFT.descriptor_type` ensures this.)
- [+] I agree to contribute to the project under OpenCV (BSD) License.
- [+] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [+] The PR is proposed to proper branch
- [+] There is reference to original bug report and related work
- [+] There is …

8-bit SIFT descriptors

---

modules/videoio/src/cap_ffmpeg_impl.hpp

resolves #16634
I faced the same issue.
ODROID-N2+ comes with Ubuntu 20.04.
I agree that the straight way to solve the issue is to install newer `ffmpeg` using `apt`
Still, I don't see a reason a to keep a keywords which should be covered by macro.

videoio: fix build error on odroid-n2-plus

---

.github/workflows/arm64-build-checks.yml

This patch adds github action workflow to enable the arm64 build checks.
Related: https://github.com/opencv/opencv/issues/17951

Add arm64-build-checks github action

---

modules/features2d/src/brisk.cpp

-Reorder loops in BRISK to reduce unnecessary values being recomputed
-Utilize lookup tables and a trigonometry identity to reduce the number of calls to sine/cosine
This PR addresses the ideas described in https://github.com/opencv/opencv/issues/13390. It's worth noting that this implementation is heavily based off the fork (https://github.com/okriof/opencv/tree/master/modules/features2d/src) from the OP of https://github.com/opencv/opencv/issues/13390 - I just omitted the sine/cosine approximation aspect.
Specs:
OS: Linux (Ubuntu 18.04)
Build type: Debug
Compiler: /usr/bin/c++  (ver 7.5.0)
Parallel framework: pthreads (nthreads=8)
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
```
cat /proc/cpuinfo  | grep 'name'| uniq
model name	: Intel(R) Core(TM) i7-7700HQ …
```

Improve BRISK Initialization

---

modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp

These changes
1. add performance tests for a list of Fluid Core kernels:
- GAdd
- GSub
- GCmpScalar
- bitwise operations with GMats
- GAbsDiff
- GAbsDiffC
- GAddWeighted
- GSplit3
- GConvertTo
- GResize
2. propose perfomance tests for other kernels (which are not checked/implemented for Fluid yet)
``` …
```

[G-API]: Fluid Core kernels performance tests

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves: #18179
merge with extra: opencv/opencv_extra#801
<cut/>
```
```

Supported ONNX Pow op

---

modules/videoio/src/cap_ffmpeg_impl.hpp

Back-port of fixes for libavcodec version checks found during #18146 .
```
```

Back-port for FFMPEG versions guard fix for AV_CODEC_FLAG_GLOBAL_HEADER and AVDISCARD_NONINTRA

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/calibration_handeye.cpp
modules/calib3d/test/test_calibration_hand_eye.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/800
Specific fix for 3.4 branch since I don't want to have ugly code to test for C++11 features in master just because 3.4 branch is tied to obsolete < C++11 version.

[3.4]  Fix cubic root computation in calibrateHandEye

---

doc/mymath.js
doc/mymath.sty
modules/calib3d/include/opencv2/calib3d.hpp

Fix #17828
- use everywhere `camera intrinsic matrix` instead of just `camera matrix` as in [A Flexible New Technique for Camera Calibration, Zhengyou Zhang](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr98-71.pdf)
- add `\cameramatrix`, `\distcoeffs`, `\distcoeffsfisheye` to avoid copy/paste errors, e.g. [here](https://github.com/opencv/opencv/blob/3547ac4b49a4f237f1546ccea5bdc2fbe4326d5f/modules/calib3d/include/opencv2/calib3d.hpp#L …

Use camera intrinsic matrix everywhere in the doc

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra:** opencv/opencv_extra#793
resolves #17516
resolves #17531
Also resolves untracked problem with constant input for Gemm layers
```
opencv_extra=testdata_for_17516_17531
```

Fix ONNX loading in issues opencv#17516, opencv#17531

---

modules/cudaimgproc/src/cuda/hist.cu
modules/cudaimgproc/src/histogram.cpp
modules/cudaimgproc/test/test_histogram.cpp
modules/cudaoptflow/src/cuda/tvl1flow.cu

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/797
This PR aims to make the `cuda::equalizeHist` bit-exact to the CPU counterpart.
resolves #18035 
resolves #10330
<cut/>
When building a lookup table from a histogram, the CPU implementation does this:
(from https://github.com/opencv/opencv/pull/226#issue-3382738)
```
C = count(Y == min(Y))
lut[i] = 255 * (count(Y <= i) - C) / (width * height - C)
```
However, what the CUDA implementation did was this:
```
lut[i] = 255 * count(Y <= i - 1) / (width * height)
```
This PR implements a CUDA kernel to make the CUDA implementation bit-exact.
For tests, now we can change this:
```
EXPECT_MAT_NEAR(dst_gold, dst, 3.0);
```
to this:
```
EXPECT_MAT_NEAR(dst_gold, dst, 0.0);
^^^
```
The performance of new CUDA implementation is …

bit-exact cuda::equalizeHist

---

modules/videoio/cmake/detect_ffmpeg.cmake

Checked build with specified FFmpeg version - it works.

videoio: reduce min libavcodec version

---

modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp
modules/imgcodecs/test/test_read_write.cpp

Default parameters of OpenJPEG encoder produce lossless encoding (or visual lossless) which leads to heavy encoded files.
This patch helps to reduce output file size if user doesn't explicitly specify compression ratio.
| Test            |  Size Before   | Size After       | PSNR Before | PSNR After |
| --------------- | ------------------ | ------------------ | ------------------ | --------------- |
|  BGR          | 585751 bytes | 230283 bytes | 361.202          | 36.3795      |
|  Grayscale  | 193798 bytes | 76691 bytes   | 361.202          | 36.6272       |

Change default parameters of OpenJPEG encoder to produce lossy result

---

doc/tutorials/imgproc/anisotropic_image_segmentation/anisotropic_image_segmentation.markdown
samples/cpp/tutorial_code/ImgProc/anisotropic_image_segmentation/anisotropic_image_segmentation.cpp
samples/python/tutorial_code/imgProc/anisotropic_image_segmentation/anisotropic_image_segmentation.py

I found a typo in the tutorial "Anisotropic image segmentation by a gradient structure tensor" from the Image Processing module.
A factor 1/2 is missing in the computation of the eigenvalues of the structure tensor. The correct formula is the eq. 4 of this paper:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.104.8552&rep=rep1&type=pdf
This pull request changes the text of the tutorial and the code of the python/cpp samples by inserting the 0.5 x factor.

fix missing 0.5 factor in anisotropic segmentation tutorial

---

modules/gapi/include/opencv2/gapi/operators.hpp
modules/gapi/src/api/operators.cpp
modules/gapi/test/common/gapi_operators_tests_inl.hpp

**These changes**:
- relocate overloaded operators for `cv::GMat` and `cv::GScalar` to `cv::` 
namespace
- add a test to check the compilation of operators' usage.
**Explanation**:
Overloads of math (and other) operators for `cv::GMat` and `cv::GScalar` contained in `operators.hpp` are located in a global namespace, which causes conflicts in a particular case: when an operator is called in a non-global namespace and there is another overload of this operator in this namespace - it **hides** our overload situated in the global namespace.
**Example**:
```
#include <opencv2/gapi.hpp>
namespace for_test
{
class A {};
int operator|(A, int);
int operator|(A, int) { return 1; }
cv::GComputationT<cv::GMat(cv::GMat, cv::GMat)> cmp([&](cv::GMat in1, cv::GMat in2)
{
return in1 | in2;
});
} // …
```

[G-API]: Relocation of operators' overloads

---

modules/dnn/src/layers/permute_layer.cpp
modules/dnn/test/test_layers.cpp

UMat allocation in CUDA targets causes unused CUDA devices (as OpenCL devices) to be initialized by these unexpected allocations in OpenCV 4. This PR stops these unwanted allocations from taking place if they are not required.
resolves #17852 
``` …
```

dnn(permute): do not allocate UMat in non-OpenCL targets

---

modules/ml/src/kdtree.cpp
modules/ml/src/knearest.cpp
modules/ml/test/test_knearest.cpp

Several issues about the implementation of the KDTree for kNN have been brought up over the years:
- https://github.com/opencv/opencv/issues/17927
- https://github.com/opencv/opencv/issues/11877
- https://github.com/opencv/opencv/issues/8917
I believe this PR should address the issues described:
- Add an additional clause in the median split algorithm to ensure no infinite loop in the case of identical values
- Ensure the computations for the nearest neighbor are correctly returned
- Enable original tests with some updates to reflect the implementation of the KD Tree
- Add a new test based on issues to verify
- *[x] I agree to contribute to the project under OpenCV (BSD) License.
- *[x] To …

Fix KD Tree kNN Implementation

---

modules/videoio/src/cap_ffmpeg_impl.hpp

relates #17489
`cv::Mat` is not available in FFmpeg Windows wrapper for 3.4 branch.

videoio: repair build of FFmpeg Windows wrapper

---

modules/ml/include/opencv2/ml.hpp
modules/ml/src/rtrees.cpp
modules/ml/test/test_rtrees.cpp

Per https://github.com/opencv/opencv/issues/11142, this PR adds logic to account for sample weights when computing the oobError during training in rtrees.
Open questions:
- Should `oobError` be moved outside the loop to ensure it's computed for the forest, rather than being reset per tree? That would also require changing the termination condition (maybe using a local error accumulator which as added to `oobError`).
- Should we be averaging over `n_oob`?
This also addresses https://github.com/opencv/opencv/issues/4431, as it makes OOB error accessible.
- *[x] I agree to contribute to the project under Apache 2 License.
- *[x] To the best of my knowledge, the proposed patch is not based on a …

Account for sample weights in calculating OOB Error

---

modules/calib3d/misc/objc/test/Calib3dTest.swift
modules/core/misc/objc/common/ByteVectorExt.swift
modules/core/misc/objc/gen_dict.json
modules/core/misc/objc/test/CoreTest.swift
modules/dnn/misc/objc/gen_dict.json
modules/imgcodecs/misc/objc/test/ImgcodecsTest.swift
modules/imgproc/misc/objc/gen_dict.json
modules/imgproc/misc/objc/test/ImgprocTest.swift
modules/imgproc/misc/objc/test/Subdiv2DTest.swift
modules/objc/generator/gen_objc.py
modules/objc/test/test/OpenCVTestCase.swift
samples/swift/ios/ColorBlobDetection/ColorBlobDetection/ColorBlobDetector.swift
samples/swift/ios/FaceDetection/FaceDetection/ViewController.swift

This PR solves #18269
This PR:
- for each module generate a {module-name}Ext.swift file
- for any functions in the module that have in/out array parameters generate a Swift extension takes Swift native array types which calls down to the relevant Objective-C function
- for any functions that take `ByteVector`, `IntVector`, `FloatVector`, `DoubleVector` generate a Swift extension that instead takes `[Int8]`, `[Int32]`, `[Float]`, `[Double]`
- fix issue in Dnn.Net module with function name clash
- suppress wrapper generation of unneeded `MorphShapes_c`, `SmoothMethod_c` enums which were causing build errors on Swift face detection sample
- update tests and samples to use the new Swift extension functions whenever possible

Swift native in/out array handling

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

merge with extra: opencv/opencv_extra#805
<cut/>
```
```

Support global reduce ops

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/gcomputation.hpp
modules/gapi/include/opencv2/gapi/gscalar.hpp
modules/gapi/misc/python/test/test_gapi_core.py

Basically this PR proves that opencv `python gen` supports overloads
* Wrapped `cv::gapi::mean` operation
* Wrapped `GScalar`
* Wrapped corresponding overloads for `GComputation()` and `apply`
```
```

[G-API] Wrap cv::gapi::mean kernel into python

---

doc/js_tutorials/js_imgproc/js_grabcut/js_grabcut.markdown

Typo fix: CV.rabCutClasses to CV.grabCutClasses

---

modules/dnn/src/onnx/onnx_importer.cpp

This PR restores original commit by @shubhamcodez and fixes https://github.com/opencv/opencv/issues/17187
<cut/>
```
```

Restore changes from PR #17629

---

modules/gapi/include/opencv2/gapi/gkernel.hpp

resolves #17952
This PR fixes issue described in #17952.

Fix implicitly-deleted default constructor

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

With Pytorch ver. 1.6 (or newer) onnx importer with Opset 11 stores **scales** parameter as float32.
relates: https://github.com/opencv/opencv/issues/18253 and https://github.com/opencv/opencv/issues/18300
merge with extra: opencv/opencv_extra#806
<cut/>
```
opencv_extra=testdata_for_resize_opset11 …
```

Fix loading of ONNX models with Resize operation with Opset 11 for newer versions of Pytorch

---

modules/gapi/include/opencv2/gapi/rmat.hpp
modules/gapi/test/rmat/rmat_tests.cpp
modules/gapi/test/rmat/rmat_view_tests.cpp

* This PR brings RMat and MatView classes, their basic implementation and tests for them
* RMat integration into the framework is to come
``` …
```

Basic RMat implementation

---

modules/cudaarithm/src/core.cpp
modules/cudaarithm/test/test_core.cpp

resolves #18347 
<cut/>
```
```

cudaarithm: use only even number for inplace flip

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

merge with extra: opencv/opencv_extra#808
resolves: #18350 
<cut/>
```
```

Fixed bug in ONNX Mul op

---

modules/gapi/include/opencv2/gapi/garray.hpp
modules/gapi/src/api/garray.cpp
modules/gapi/src/api/gorigin.cpp
modules/gapi/src/api/gproto.cpp
modules/gapi/src/compiler/gobjref.hpp
modules/gapi/src/executor/gexecutor.cpp
modules/gapi/test/gapi_array_tests.cpp

Added support initialization for GArray. CONST_VALUE used for this.
You can create an empty or filled std::vector and put or move it into a GArray.
Example:
```
std::vector<cv::Mat> vec; // or vec = {some values}
cv::GComputation pp([&]() {
cv::GMat in;
cv::GArray<cv::GMat> garr(vec); // or garr(std::move(vec))
return cv::GComputation(custom::SomeOp::on(in, garr));
});
```
Possible:
- `cv::GArray<cv::GMat> garr(vec)`;
- `cv::GArray<cv::GMat> garr(rval)`;
- `cv::GArray<cv::GMat> garr({some values})`.
Impossible:
- `cv::GArray<cv::GMat> garr = vec; // explicit`;
- `cv::GArray<cv::GMat> garr = std::vector<cv::Mat>(some size); // explicit`;
- `cv::GArray<cv::GMat> garr = std::vector<cv::Mat>()`. …

[G-API]: Add GArray initialization support

---

modules/dnn/src/opencl/prior_box.cl

relates #18283 
OpenCL FP16 inference on Arm Mali is not supported, as claimed on #18283 
There are 2 points, one is `isIntel()` call and another is kernel build failure 
```
OpenCL program build log: dnn/prior_box
Status -11: CL_BUILD_PROGRAM_FAILURE
-DDtype=half -DDtype4=half4 -Dconvert_T=convert_half4
<source>:67:9: error: call to 'clamp' is ambiguous
vstore4(clamp(vec, 0.0f, 1.0f), index, dst);
^~~~~
```
This PR is to fix the 2nd point.
The error comes that clamp is accepting 
`half4, float, float` as a parameter, when it's supposed to accept either `half4, half, half` or `float4, float, float`
This PR will explicitly cast the latter 2 parameters, and let the kernel to be built.
I confirmed on RK3399, by also disabling [here](https://github.com/opencv/opencv/blob/e668cff5731b4f1005889f …

OpenCL: add explicit cast for half

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/gcomputation.hpp
modules/gapi/misc/python/test/test_gapi_sample_pipelines.py
modules/python/src2/cv2.cpp
modules/python/test/test_copytomask.py

Impossible to wrap function which return `std::tuple<>`, so this patch introduce `pyopencv_from` for `std::tuple<Ts...>`
```
```

[G-API] Support std::tuple for return type

---

modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp

Tiling and scaling modes are not supported by underlying code.
relates #16494
See also:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25779
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25823

imgcodecs(openjpeg): add checks for input

---

modules/gapi/test/cpu/gapi_core_tests_fluid.cpp
modules/gapi/test/gpu/gapi_core_tests_gpu.cpp

Bug: [18373](https://github.com/opencv/opencv/issues/18373)

Disabled failed test instantiations

---

modules/calib3d/src/ippe.cpp

This change fixes the argument checking assertions at the beginning of IPPE::PoseSolver::solveGeneric. 
- Changed number of point comparison to compare number of image points and number of object points.
- Fixed typo in second CV_CheckType message
- Fixed type checking for _objectPoints

Fixed assertions on IPPE solver for SolvePnP

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/gcommon.hpp
modules/gapi/include/opencv2/gapi/gframe.hpp
modules/gapi/include/opencv2/gapi/gmat.hpp
modules/gapi/include/opencv2/gapi/gtype_traits.hpp
modules/gapi/src/api/gframe.cpp
modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/test/gapi_frame_tests.cpp

- The underlying host type is still cv::Mat, a new cv::MediaFrame
type is to be added as a separate PR.
```
```

G-API: Make GFrame a new (distinct) G-type, not an alias to GMat

---

modules/dnn/src/opencl/ocl4dnn_lrn.cl

relates #18283 #18360 
Platform: Firefly RK3399 (Arm Mali-T860 OpenCL 1.2)
Compiler: GCC 5.4.0
OpenCV: Recent 3.4 ( 3e3787ecb6b1823944a9be8e65a71a3c02a4260f )
When running `opencv_test_dnn` with `OPENCV_DNN_OPENCL_ALLOW_ALL_DEVICES=1`, one kernel fails building.
```
[----------] 192 tests from Layer_Test_Halide/LRN
(snip)
[ RUN      ] Layer_Test_Halide/LRN.Accuracy/1, where GetParam() = ([6, 5, 8], 3, [0.9, 1, 1.1], false, "ACROSS_CHANNELS", OCV/OCL_FP16)
OpenCL program build log: dnn/ocl4dnn_lrn
Status -11: CL_BUILD_PROGRAM_FAILURE
-D Dtype=half
<source>:38:79: error: call to 'native_powr' is ambiguous
out_off[(head - post_pad) * step] = in_off[(head - post_pad) * step] * (Dtype)native_powr((Dtype)scale_val, (Dtype)negative_beta);
^~~~~~~~~~~
note: candidate function
note: candidate …
```

OpenCL: fix cast for native_powr when half

---

modules/videoio/test/test_mfx.cpp
modules/videoio/test/test_precomp.hpp

Names instead of numbers help with filtering.
```
videoio/videoio_mfx.
read_write_raw/640x480x1xmpeg2  # GetParam() = (640x480, 1, 0x5609b5c36567 pointing to ".mpeg2")
read_write_raw/640x480x1x264  # GetParam() = (640x480, 1, 0x5609b5c3656e pointing to ".264")
read_write_raw/640x480x1x265  # GetParam() = (640x480, 1, 0x5609b5c36573 pointing to ".265")
...
read_write_raw/1920x1080x100x265  # GetParam() = (1920x1080, 100, 0x5609b5c36573 pointing to ".265")
```

videoio: naming MFX tests

---

modules/gapi/test/cpu/gapi_ocv_stateful_kernel_tests.cpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

gapi: fix building wihout video module, fix infer test

---

modules/gapi/cmake/standalone.cmake

[G-API] Fix Windows standalone build 

---

modules/cudaarithm/src/core.cpp
modules/cudaarithm/test/test_core.cpp

relates #18347 
- I followed the comments
<cut/>
```
```

CUDA: brush up by following the comments

---

modules/videoio/cmake/plugin.cmake
modules/videoio/src/precomp.hpp

Build environment: Ubuntu 20.04 with installed Eigen and enable videoio plugins (`VIDEOIO_PLUGIN_LIST=all`).
Avoid including of `private.hpp` through removal of `__OPENCV_BUILD` definition.
<cut/>
```
In file included from /build/precommit_opencl_linux/next/opencv/modules/videoio/src/precomp.hpp:55,
from /build/precommit_opencl_linux/next/opencv/modules/videoio/src/cap_ffmpeg.cpp:42:
/build/precommit_opencl_linux/next/opencv/modules/core/include/opencv2/core/private.hpp:70:12: fatal error: Eigen/Core: No such file or directory
70 | #  include <Eigen/Core>
|            ^~~~~~~~~~~~
compilation terminated.
```

videoio: fix plugins build with enabled Eigen

---

modules/dnn/test/test_torch_importer.cpp

relates #18360 ( https://github.com/opencv/opencv/pull/18360#issuecomment-694845115 )
This PR will loosen the EPS a bit and let the test pass on Firefly RK3399 (Mali T860)

dnn: loosen threshold for Mali

---

modules/core/include/opencv2/core/check.hpp
modules/dnn/src/onnx/onnx_importer.cpp

Compile-time check to avoid crashes.
`CheckContext` content should not be initialized in runtime (stored in "Data" section).

core: force check for string literals are used in the message

---

modules/ml/misc/python/test/test_goodfeatures.py

relates #6285
Error:
```
File "modules/ml/misc/python/test/test_goodfeatures.py", line 14, in test_goodFeaturesToTrack
original = arr.copy(True)
TypeError: order must be str, not bool
```
<cut/>
```
```

ml: fix python test

---

platforms/ios/build_framework.py

relates #7358 #18381
There is no reason to disable `opencv_world` in general. This special module includes subset of OpenCV modules. For example, it should be able to build with `opencv_core` only.
Looks like disabling `opencv_world` was wrong from the beginning (by #7358 and following fixes).
P.S. Use `--without world` to disable `opencv_world` again
/cc @komakai @sjang42 @nevir

ios: don't force BUILD_opencv_world=OFF in case of excluded modules

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi.hpp
modules/gapi/include/opencv2/gapi/gframe.hpp
modules/gapi/include/opencv2/gapi/media.hpp
modules/gapi/src/api/media.cpp
modules/gapi/test/gapi_frame_tests.cpp

This PR brings a new data structure `cv::MediaFrame`, which is a host-type for a graph-based `GFrame`. The idea of `cv::MediaFrame` is to handle various media formats (also tied to an external memory) under the same uniform hood.
There's only a `cv::MediaFrame` class itself + tests in this PR, no integration with the runtime part of G-API done yet (to be pushed and merged separately). 
Documentation is by now internal, but will be published as Doxygen with the upcoming PRs.
``` …
```

G-API: Introduce cv::MediaFrame, a host type for cv::GFrame

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/ocl/goclkernel.hpp
modules/gapi/perf/common/gapi_core_perf_tests.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_cpu.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp
modules/gapi/src/api/kernels_core.cpp
modules/gapi/src/backends/cpu/gcpucore.cpp
modules/gapi/src/backends/ocl/goclcore.cpp
modules/gapi/src/backends/ocl/goclkernel.cpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp
modules/gapi/test/gapi_opaque_tests.cpp
modules/gapi/test/gpu/gapi_core_tests_gpu.cpp

**These changes:**
- add API and documentation for a new `countNonZero()` standard G-API kernel
- implement this kernel via OCV and OCL Backend
- provide appropriate tests (performance and accuracy)
- for the obvious reason, `countNonZero` macro is disabled for these tests
- fix the `GOpaque` functionality for OCL Backend (SEPARATE COMMIT)
- fix some documentation link problems
``` …
```

[G-API]: countNonZero() Standard Kernel Implementation

---

modules/dnn/src/darknet/darknet_io.cpp

#18017 enable using both leaky ReLU and ReLU in darknet, but it also exits a bug https://github.com/opencv/opencv/pull/18017#issuecomment-699038433

fix issue in PR #18017

---

modules/calib3d/src/fundam.cpp
modules/calib3d/test/test_homography.cpp

Fixes #18254 
- Added a check for minimum points to calculate Homography
```
```

calib3d: check for minimum corresponding points to calculate homography

---

modules/imgproc/src/subdivision2d.cpp

Condition 'filterPoints' is always true, no role in if conditions.

imgproc: bool is always True

---

modules/imgproc/src/gcgraph.hpp

relates #18454
3.4 branch: imgproc module
master branch: calib3d module (moved code)

calib3d/imgproc: add GCGraph::maxFlow() missing empty checks

---

modules/core/src/matrix.cpp

This PR fixes an issue in the `setSize()` method of `cv::Mat`. According to the documentation (for example https://docs.opencv.org/4.4.0/d3/d63/classcv_1_1Mat.html#a5fafc033e089143062fd31015b5d0f40) the parameter `const size_t* steps` is an `Array of ndims-1 steps in case of a multi-dimensional array (the last step is always set to the element size)`. This is reflected in the implementation, where the `m.step.p[i]` is always set to `esz` for the last dimension:
https://github.com/opencv/opencv/blob/1913482cf5d257d7da292bb2c15f22d0588d34dc/modules/core/src/matrix.cpp#L245
However a few lines above, there is a check if `_steps[i]` is a multiple of `esz1`. This statement **does** access the `i`th element of `_steps` for the last dimension. This …

Fix out-of-bounds access in setSize() from cv::Mat() constructor

---

modules/python/test/test_copytomask.py

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master_etc-centos-lin64/builds/35/steps/test_python2/logs/stdio):
```
AttributeError: 'module' object has no attribute 'full'
```
<cut/>
```
```

python: replace numpy.full() to support numpy<1.13

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp
modules/gapi/include/opencv2/gapi/garg.hpp
modules/gapi/include/opencv2/gapi/gframe.hpp
modules/gapi/include/opencv2/gapi/gkernel.hpp
modules/gapi/include/opencv2/gapi/gmetaarg.hpp
modules/gapi/include/opencv2/gapi/gtype_traits.hpp
modules/gapi/include/opencv2/gapi/media.hpp
modules/gapi/src/api/gbackend.cpp
modules/gapi/src/api/gframe.cpp
modules/gapi/src/api/gproto.cpp
modules/gapi/src/api/media.cpp
modules/gapi/src/backends/common/gbackend.hpp
modules/gapi/src/backends/common/serialization.cpp
modules/gapi/src/backends/common/serialization.hpp
modules/gapi/src/backends/cpu/gcpubackend.cpp
modules/gapi/src/compiler/gcompiled.cpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/src/compiler/passes/dump_dot.cpp
modules/gapi/test/gapi_frame_tests.cpp

For your early review.
A more detailed description TBD.
Need to rebase on the latest `master` to merge with changes from @smirnov-alexey 
``` …
```

G-API: Integrated cv::MediaFrame as I/O type + CPU backend

---

modules/dnn/src/dnn.cpp

(3.4) Removed get_output_as_single_output_node method (backport 18031)

---

modules/core/src/logger.cpp
platforms/scripts/valgrind.supp

- keep logger available until the program termination
fixes #18152

core(logger): avoid destruction of GlobalLoggingInitStruct object

---

modules/dnn/src/ie_ngraph.cpp

backport #17993
<cut/>
```
Xbuild_image:Custom=ubuntu-openvino-2020.4.0:16.04
Xbuild_image:Custom Win=openvino-2020.4.0
```

(3.4) [IE][VPU]: Refactor vpu configs (backport 17993)

---

modules/videoio/src/cap_dc1394_v2.cpp

[Compiler warning message](http://pullrequest.opencv.org/buildbot/builders/3_4_coverage-lin64-debug/builds/886/steps/compile%20debug/logs/warnings%20%281%29).

videoio(dc1394_v2): ensure variable initialization

---

modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/test/test_gapi_core.py

This code failed: `Failed convert array to cv::Mat` 
```
in_mat = np.array([1,2,3])
cv.gin(in_mat)
```
But this code works fine:
```
in_mat = np.array([1,2,3]).astype(np.uint8)
cv.gin(in_mat)
```
While parsing was used incorrect `ArgInfo` it was marked as outputarg == `true` instead of `false` 
https://github.com/opencv/opencv/blob/master/modules/gapi/misc/python/pyopencv_gapi.hpp#L144
Replace `ArgInfo{"mat", true}` -> `ArgInfo{"mat", false}`
``` …
```

[G-API] Numpy array with int64 failed in cv.gin

---

doc/tutorials/introduction/config_reference/config_reference.markdown

Resolves #18537
<cut/>
```
build_contrib:Docs=OFF
```

Doc: fixed warnings when CUDA modules are missing

---

modules/gapi/include/opencv2/gapi/gcall.hpp
modules/gapi/include/opencv2/gapi/infer.hpp
modules/gapi/include/opencv2/gapi/infer/ie.hpp
modules/gapi/src/api/gcall.cpp
modules/gapi/src/api/gcall_priv.hpp
modules/gapi/src/api/ginfer.cpp
modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/compiler/gmodel.cpp
modules/gapi/src/compiler/gmodel.hpp
modules/gapi/src/compiler/gmodelbuilder.cpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

```
Xbuild_image:Custom=ubuntu-openvino-2020.4.0:16.04
Xbuild_image:Custom Mac=openvino-2020.4.0
build_image:Linux …
```

[G-API] Introduce generic version for cv::gapi::infer

---

modules/core/include/opencv2/core/version.hpp

OpenCV 3.4.12
relates #18282
<cut/>
<details>
[opencv_world3412.dll (vc14)](https://www.virustotal.com/gui/file/b92d1901d363ca5eb2ec887b7363c3d444107deba4c2229d70d3c739abfc4923/detection)
[opencv_world3412d.dll (vc14)](https://www.virustotal.com/gui/file/cfda706e01e43151029b22802f08ea776a24744af25691b32e9b5140772da350/detection)
[opencv_world3412.dll (vc15)](https://www.virustotal.com/gui/file/994f6b832c2d9fdb53e28f9bdf0fb57428e787da237d7a844588d7323e0fb78d/detection)
[opencv_world3412d.dll (vc15)](https://www.virustotal.com/gui/file/01bb89bd9a71790afeac9f6996d23a77fa38d19cd4d2251c4e3de0fc2958be0c/detection)
[opencv_ffmpeg3412_64.dll](https://www.virustotal.com/gui/file/2abd4c09ef76e913bde03929d8a0c31b5515772f682551acb43a2914d4bd42d0/detection) …

release: OpenCV 3.4.12

---

modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/src/compiler/passes/exec.cpp

Fix warning in clang version 10.0.0-4ubuntu1
```
warning: loop variable 'nh' of type 'const ade::Handle<ade::Node>' creates a copy from type 'const ade::Handle<ade::Node>' [-Wrange-loop-construct]
```
<cut/>
```
```

Fix warnings: "-Wrange-loop-construct" in gapi

---

cmake/templates/opencv_abi.xml.in
modules/imgcodecs/CMakeLists.txt
modules/imgcodecs/include/opencv2/imgcodecs.hpp
modules/imgcodecs/include/opencv2/imgcodecs/macosx.h
modules/imgcodecs/misc/objc/macosx/Mat+Converters.h
modules/imgcodecs/misc/objc/macosx/Mat+Converters.mm
modules/imgcodecs/src/apple_conversions.h
modules/imgcodecs/src/apple_conversions.mm
modules/imgcodecs/src/macosx_conversions.mm
modules/objc/generator/gen_objc.py

This PR solves https://github.com/opencv/opencv/issues/18546.
It consists
- Extract CoreGraphics conversion logics from ios_conversions.mm to apple_conversions.h, apple_conversions.mm (MatToCGImage(), CGImageToMat())
- Simplify ios_conversions.mm
- Add macosx_conversions.mm for macOS/AppKit (MatToNSImage(), NSImageToMat())
- Add Mat+Conversions.h and Mat+Conversions.mm for macOS/AppKit
<cut/>
**Usage example in Swift:**
**※ Don't forget to set the `-all_load` flag to "Other Linker Flags" in "Build Settings" when using!** https://github.com/opencv/opencv/issues/17532
```
// CGImage to Mat
let sourceMat = Mat(cgImage: cgImage, alphaExist: true)
// NSImage to Mat
let sourceMat = Mat(nsImage: nsImage, alphaExist: true)
// Something to process
let grayMat = Mat()
Imgproc.cvtColor(src: …
```

Mat conversions for macOS/AppKit

---

modules/core/misc/objc/common/Mat.h
modules/core/misc/objc/common/Mat.mm

Added because there was no method to get Mat data directly in Objective-C or Swift.
Usage example in Swift:
```
let mat = Mat.zeros(Size(width: 256, height: 256), type: CvType.CV_8UC4)
let dataPointer = mat.dataPointer() // <- UnsafeMutablePointer<UInt8>
let data = Data(bytes: dataPointer, count: bytesPerPixel * pixels)
```
```
buildworker:iOS=macosx-1
```

Add Mat data pointer bridging method for Objective-C/Swift

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/imgproc/include/opencv2/imgproc.hpp

Same as #18582 but for master branch, because `modules/gapi/include/opencv2/gapi/core.hpp` doesn't exist in 3.4

Doc: INTER_LINEAR_EXACT unsupported in remap

---

modules/core/include/opencv2/core/cvdef.h

resolves #18597
relates #17567

core: fix __clang_major__ typo regression

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/solvepnp.cpp

resolves #18595
This PR is to fix issue [#18595 ](https://github.com/opencv/opencv/issues/18595).
The solution was to adopt a similar approach to the one taken for struct CirclesGridFinderParameters under the same file calib3d.hpp
It was verified that the modified binding exposes the data fields under struct UsacParams

Fix: UsacParams Python bindings (Issue#18595)

---

modules/python/src2/hdr_parser.py

This pull request fixes https://github.com/opencv/opencv/issues/18553 by making the Python bindings generator create a declaration for 'imshow' that works with GpuMat inputs under Python.

[FIX #18553] Enable imshow to take GpuMat inputs in Python

---

modules/stitching/include/opencv2/stitching/detail/warpers.hpp
modules/stitching/include/opencv2/stitching/detail/warpers_inl.hpp
modules/stitching/include/opencv2/stitching/warpers.hpp
modules/stitching/src/warpers.cpp
modules/stitching/test/test_reprojection.cpp

resolves #18608 
Since warpPoint method is not used in stiching_detailed sample, I did not create a separate sample, but I'd say it's self-explanatory

stiching: add warpPointBackward to warpers

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/gstreaming.hpp
modules/gapi/include/opencv2/gapi/infer/parsers.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/samples/text_detection.cpp
modules/gapi/src/api/kernels_core.cpp
modules/gapi/src/backends/cpu/gcpucore.cpp
modules/gapi/test/common/gapi_core_tests_inl.hpp

This sample models the Text Detection demo from OMZ:
https://github.com/openvinotoolkit/open_model_zoo/tree/2020.4/demos/text_detection_demo
Also: renamed cv::gapi::size() to cv::gapi::streaming::size()
``` …
```

G-API: Introduced a Text Detection sample

---

modules/stitching/include/opencv2/stitching/detail/exposure_compensate.hpp
modules/stitching/src/exposure_compensate.cpp
modules/stitching/test/test_exposure_compensate.cpp
modules/stitching/test/test_precomp.hpp

This PR adds the necessary code to add a similarity mask to the exposure compensator of the stitching pipeline.
You can configure a `similarity_threshold` which defines a threshold on the relative error between the pixels of two images. If the error is above the threshold, it is ignored when calculating the exposure compensation. This allows the removal of ghosting artifacts due to exposure compensation when part of the images are different (for instance a moving car which would only be present on a single picture)
Note that by default the behavior is unchanged.
<cut/>
The top 2 images are the source images. The bottom left one used a block, per channel exposure compensation. The bottom right used the same, with a similarity threshold of 0.1.
Despite the seam finder and blender doing …

support similarity masks

---

modules/cudaarithm/src/lut.cpp
modules/stitching/src/blenders.cpp

Fixes two errors when building with the options WITH_CUDA=ON and BUILD_CUDA_STUBS=ON on a machine without CUDA.
In the cudaarithm module, make sure cuda_runtime.h only gets included when CUDA is installed.
In the stitching module, don't assume that cuda is present just because cudaarithm and cudawarping are present (as is the case when building with the above options).
Fixes opencv/opencv_contrib#2724
<cut/>
```
```

Fix errors when building with cuda stubs

---

modules/objc/generator/gen_objc.py
modules/objc/generator/templates/cmakelists.template

This PR addresses #18489
- when building with CMake 3.19 or greater and Xcode 12 or greater generate **swiftinterface** files
- improvements to the autogenerated Xcode project for Xcode New Build system
- add support for standard module properties **VersionNumber** and **VersionString**
- when build with older versions of CMake and/or Xcode continue to build as before (without generating **swiftinterface** files)
```
```

Add support for Swift version independence

---

modules/js/src/make_umd.py

resolves #18632
Fixes TypeError mentioned in #18632.
<cut/>
```
build_image:Custom=javascript-simd:1.39.16
```

Fix TypeError when building for WebAssembly with Python 3

---

modules/core/include/opencv2/core/mat.inl.hpp
modules/core/src/matrix.cpp
modules/core/src/matrix_sparse.cpp
modules/core/src/umatrix.cpp

- change preserves backward binary compatibility
- move out large / complex functions from .hpp files
- slightly reduce compilation time / binaries size of OpenCV / User applications
<cut/>
<details>
<summary>Binaries size change</summary>
Configuration: GCC 9.3.1, Release -O2, WITH_IPP=OFF, WITH_VIZ=OFF
- lib/*.so size change (17 files w/o ts.a):
| before | after | diff bytes | diff % |
| ---:| ---:| ---:| ---:|
| 27 270 216 | 24 670 896 | 2 599 320 | 9.5% |
- opencv_interactive-calibration
| before | after | diff bytes | diff % |
| ---:| ---:| ---:| ---:|
| 166 384 | 141864 | 24520 | 14.7% |
- opencv_test_core (GoogleTest templates are huge)
| before | after | diff bytes | diff % |
| ---:| ---:| ---:| ---:|
| 16 665 136 | 16 391 896 | 273 240 | 1.6% |

core: move inline code from mat.inl.hpp

---

modules/stitching/include/opencv2/stitching/detail/motion_estimators.hpp
modules/stitching/src/motion_estimators.cpp
modules/stitching/test/test_precomp.hpp
modules/stitching/test/test_wave_correction.cpp

This PR adds a new wave correction kind: `WAVE_CORRECT_AUTO`. It will detect the direction (vertical or horizontal) in which the panorama spans, and use that direction for the wave correction algorithm. This enables the usage of wave correction in a generic way.
<cut/>

stitching: add WAVE_CORRECT_AUTO

---

modules/gapi/src/api/gmat.cpp
modules/gapi/src/backends/common/gbackend.hpp
modules/gapi/src/backends/common/serialization.cpp

- Changed descr_of(RMat) to use canDescribeHelper to correctly handle planar case
- Added export of createMat
- Added setting of Storage::INPUT and Storage::OUTPUT in deserialization routine of GComputation
``` …
```

[G-API] Minor s11n and RMat improvements:
