modules/dnn/src/dnn.cpp
modules/dnn/src/op_inf_engine.cpp

Different way to reset Myriad device

---

samples/python/stitching_detailed.py

Improve the overall readability and maintainability of the Python example stitching script.
Specifically:
* PEP8 fixes
* Removed unused variables
* Start splitting main function into easier to understand functions.
* Use dictionaries for option parsing rather than `if`, this also allows easily showing all available options in the help output.
* Update help text (copied from C++ example)
* Added the AKAZ and BRISK feature finders as options.

Make stitching script more pythonic

---

modules/java/android_sdk/build.gradle.in

It finish https://github.com/opencv/opencv/pull/16222 
This file was forgotten

finish Android version info to Gradle style

---

modules/dnn/src/layers/mvn_layer.cpp

Extend MVN layer support through nGraph

---

samples/android/15-puzzle/src/org/opencv/samples/puzzle15/Puzzle15Activity.java
samples/android/camera-calibration/src/org/opencv/samples/cameracalibration/CalibrationResult.java
samples/android/camera-calibration/src/org/opencv/samples/cameracalibration/CameraCalibrator.java

(3.4) fix lint errors and warnings ins Android samples

---

modules/dnn/src/onnx/onnx_importer.cpp

dnn(onnx): handle unaligned access in ONNX importer

---

modules/imgcodecs/src/loadsave.cpp
modules/imgcodecs/test/test_precomp.hpp
modules/imgcodecs/test/test_read_write.cpp

1. Added flag handler for imdecode which was the issue
2. Take care of color resize cases
3. Port changes to imread as well.
resolves #16203
```
```

Added resize flag handlers for imread and imdecode | Issue #16203

---

modules/dnn/src/layers/lrn_layer.cpp

Support nGraph LRN with SPATIAL_NRM

---

modules/imgproc/src/resize.cpp

I wasn't impressed with my workaround for the OOB fix. Let's fix it with little or no regressing of performance.
This fixes #16137 with little or no performance impact. I have
also added a debug check as a sanity check.

Improve resize 8u3

---

modules/calib3d/misc/python/test/test_solvepnp.py
modules/calib3d/src/solvepnp.cpp

Added default type instead of `reprojectionError.type()`
Refers #16049

Added type check for solvePnPGeneric | Issue: #16049

---

modules/core/src/matmul.simd.hpp

Reduce LLC loads, stores and multiplies by 2x on MulTransposed - 8% faster

Reduce LLC loads, stores and multiplies on MulTransposed - 8% faster

---

modules/dnn/src/layers/softmax_layer.cpp

Extend nGraph Softmax layer (support logsoftmax)

---

modules/dnn/src/layers/convolution_layer.cpp

Extend nGraph Deconvolution layer support

---

modules/core/src/parallel_impl.cpp

https://github.com/opencv/opencv/issues/11274#issuecomment-491596774

core(build): fix i386 compilation

---

cmake/OpenCVGenABI.cmake

(3.4) cmake: support OPENCV_ABI_SKIP_MODULES_LIST

---

modules/objdetect/include/opencv2/objdetect.hpp
modules/objdetect/src/qrcode.cpp

objdetect(QR): don't introduce deprecated API, compatibility code

---

modules/highgui/src/window_QT.cpp

Fix compilation errors on GLES platforms

---

modules/videoio/src/cap_avfoundation.mm

resolves #6450
I changed a logic of cv::VideoCapture().
Because cv::VideoCapture::get returns wrong value and cv::VideoCapture cannot set value.
Transplanting cv::VideoCapture()'s logic of macOS, this problem can be fixed.
```
```

Fix issue #6450

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/imgproc/include/opencv2/imgproc.hpp

resolves #13602
resolves #9392

added note about BORDER_WRAP in separable filters; fixed SGBMStereo description

---

.github/PULL_REQUEST_TEMPLATE.md

The PR adds checklist to pull request description template.
<cut>
```
```

Added PR readiness checklist

---

modules/objdetect/src/qrcode.cpp
modules/objdetect/test/test_qrcode.cpp

solved problem with incorrect processing of transformation points in method QRCodeDetector::decodeMulti()
relates #15338

fixed issue with Mat reshape in decodeMulti()

---

modules/imgproc/src/drawing.cpp
modules/imgproc/test/test_drawing.cpp

fixed antialiased line rendering to process image border correctly

---

modules/dnn/src/layers/resize_layer.cpp
modules/dnn/test/test_layers.cpp

resolves https://github.com/opencv/opencv/issues/13462
```
```

Fix dnn::ResizeLayer to manage varying input shapes

---

modules/videoio/include/opencv2/videoio.hpp

Improved GStreamer documentation

---

modules/gapi/src/api/render_ocv.cpp

G-API: Fix ocv render text slowdown

---

modules/dnn/src/ie_ngraph.hpp

```
test_timeout:Custom Win=1200
test_maxtime:Custom Win=14400
```

dnn: eliminate MSVC warnings from ngraph.hpp

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/test/test_darknet_importer.cpp

**Merge with extra**: [opencv/opencv_extra#700](https://github.com/opencv/opencv_extra/pull/700)
resolves #16437
1. Added parsing for Connected layer and Dropout.
2. Modifies padding parsing for Maxpool layer. 
`opencv_extra=opnecvc_extra`

Added parsing for Connected and Dropout. Modified maxpool padding

---

cmake/templates/OpenCVConfig.cmake.in
samples/CMakeLists.example.in
samples/CMakeLists.txt
samples/android/face-detection/jni/CMakeLists.txt
samples/android/tutorial-2-mixedprocessing/jni/CMakeLists.txt
samples/android/tutorial-4-opencl/jni/CMakeLists.txt
samples/cpp/example_cmake/CMakeLists.txt

resolves #13000
resolves #11428
```
```

cmake: enable C++11 implicitly

---

cmake/OpenCVDetectInferenceEngine.cmake

If IE API is implemented in multiple libraries, it solves the issues with that in robust way.

CMAKE: more robust custom IE libraries support

---

cmake/OpenCVDetectInferenceEngine.cmake

(3.4) CMAKE: more robust custom IE libraries support

---

samples/CMakeLists.txt

CMakeLists.txt includes samples_utils.cmake, so the later should be
installed as well to make samples build successfully
- [*] I agree to contribute to the project under OpenCV (BSD) License.
- [*] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [*] The PR is proposed to proper branch

Install all CMake files required to build samples

---

modules/core/include/opencv2/core/utility.hpp
modules/python/src2/cv2.cpp

core: export getCPUFeaturesLine to bindings

---

modules/core/src/persistence_json.cpp
modules/core/test/test_io.cpp

Fixes partially https://github.com/opencv/opencv/issues/14977

Implemented BASE64 support in cv::FileStorage parser for JSON

---

modules/objdetect/src/qrcode.cpp

There was mistake in use new() function without delete() function. I fixed it using vector<int> instead dynamic array

fix wrong memory allocation

---

README.md

3.4 docs for 3.4 branch

---

modules/core/src/persistence.cpp
modules/core/src/persistence_json.cpp
modules/core/test/test_io.cpp

trying to fix handling file storages with extremely long lines

---

cmake/OpenCVDetectInferenceEngine.cmake
modules/dnn/src/op_inf_engine.hpp

dnn: align with OpenVINO 2020.1

---

modules/dnn/src/layers/elementwise_layers.cpp

resolves https://github.com/opencv/opencv/issues/14566

Restore PowerFunctor state

---

modules/highgui/src/window_cocoa.mm
samples/cpp/watershed.cpp

resolves #16343.
Thanks to @cwreynolds and @saskatchewancatch for the help!

fixed cv::moveWindow() on mac

---

modules/dnn/src/layers/resize_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp
samples/dnn/human_parsing.py
samples/dnn/virtual_try_on.py

**Merge with extra:**  opencv/opencv_extra#703
```
```
[CP-VTON paper](https://arxiv.org/pdf/1807.07688.pdf)
**Example**
Person / Target cloth / Output

Add CP-VTON sample

---

modules/dnn/test/test_ie_models.cpp

<cut/>
```
test_filter:Custom=*.models*
```

dnn(test): test DLDT IRv10 model, drop old models

---

samples/python/drawing.py
samples/python/laplace.py

There are some files in samples/cpp whose python samples are not available. So, this PR is just adding "laplace.py" python code for laplace.cpp .
Added drawing.py to samples/python as it's code is not present

Adding python codes to samples/python

---

samples/python/grabcut.py

- [ x] I agree to contribute to the project under OpenCV (BSD) License.
- [ x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ x] The PR is proposed to proper branch
- [ x] There is reference to original bug report and related work
- [ x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable

Minor update in grabcut.py

---

3rdparty/openexr/Imath/ImathQuat.h

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4-win64-vc16/builds/276).
```
```

Fix compilation with MSVS2019

---

modules/dnn/test/test_onnx_importer.cpp

dnn(test): configure filtering for 32-bit systems (part 2)

---

modules/core/src/matrix_expressions.cpp
modules/core/test/test_mat.cpp
modules/dnn/test/test_misc.cpp

core(MatExpr): fix .type() bug

---

modules/core/src/parallel.cpp

Fixed getCPUCount to account for cgroups.
Added common code to parse CPU files into a generic function for android and Linux
Tested on Linux VMs, docker images, Kubernetes pods.
resolves #16268
resolves #16183

Fixed getCPUCount | Issue #16268

---

modules/calib3d/src/rho.cpp
modules/calib3d/src/stereosgbm.cpp
modules/core/include/opencv2/core/utils/buffer_area.private.hpp
modules/core/src/buffer_area.cpp
modules/core/test/test_utils.cpp
modules/features2d/src/fast.cpp

Use BufferArea in StereoSGBM, RHO and FAST

---

modules/core/src/parallel.cpp

core: fix build getNumberOfCPUs for JavaScript

---

modules/dnn/src/ie_ngraph.cpp

Track Hetero execution for nGraph networks using ngraph::Function

---

modules/gapi/test/common/gapi_core_tests_inl.hpp

resolves #16679
relates #16657
```
force_builders_only=Custom Mac
```

G-API(test): fix check

---

modules/imgcodecs/src/exif.hpp

bug fix to Inconsistent comment for EXIF issue id #15706

---

modules/core/src/matrix_expressions.cpp
modules/core/test/test_mat.cpp

core: fix MatExpr::size() for gemm()

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra:** opencv/opencv_extra#718
resolves: #16718 
resolves: https://github.com/opencv/opencv/issues/16660
```
```

Supported Div op for constants

---

modules/imgproc/perf/perf_integral.cpp
modules/imgproc/src/sumpixels.simd.hpp

resolves #16708
```
disable_ipp=ON
```

imgproc(integral): avoid OOB access

---

.github/ISSUE_TEMPLATE.md

Added checklist and recommendations to issue template

---

modules/dnn/src/layers/scale_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves https://github.com/opencv/opencv/issues/16476
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/722
<cut/>
```
```

Broadcasting from ONNX

---

modules/core/src/minmax.cpp
modules/core/src/norm.cpp

- extra assertion checks
- "specialize" generic norm implementation through simple loop

core: fix coverity issues

---

modules/core/src/minmax.cpp
modules/core/src/norm.cpp
modules/core/src/sum.dispatch.cpp
modules/core/test/ocl/test_arithm.cpp
modules/ts/src/ts_func.cpp

core: FP16 norm() test

---

doc/tutorials/dnn/dnn_android/dnn_android.markdown
doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/python/package/setup.py
platforms/android/build_sdk.py
platforms/android/service/readme.txt
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

- Android Manager internal version is not increased (stuck on 3.49)
previous PR with version bump: #16071

pre: OpenCV 3.4.10 (version++)

---

doc/tutorials/dnn/dnn_android/dnn_android.markdown
doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/python/package/setup.py
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #16078

pre: OpenCV 4.3.0 (version++)

---

modules/dnn/src/layers/scale_layer.cpp

relates #16753 #16738
<cut/>
```
```

dnn: fix merge mistake in scale_layer.cpp

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**relates:** #16728
**Merge with extra:** opencv/opencv_extra#727
```
```

Supported Flatten for constant nodes

---

modules/dnn/src/dnn.cpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/op_inf_engine.cpp
modules/dnn/src/op_inf_engine.hpp

- HETERO plugin doesn't switch well between devices
<cut/>
```
```

dnn(ie): separate IECore for different devices

---

cmake/OpenCVDetectCXXCompiler.cmake
modules/core/CMakeLists.txt
modules/core/include/opencv2/core/utils/allocator_stats.impl.hpp

core: adjust type of allocator_stats counter, allow to disable

---

samples/cpp/intelligent_scissors.cpp

Intelligent scissors

---

modules/core/src/parallel.cpp

fixes #16777 Fairly obvious change.

Fixes issue 16777.

---

modules/dnn/misc/python/pyopencv_dnn.hpp

resolves https://github.com/opencv/opencv/issues/16811

Fix memory leak in Python custom dnn layers

---

modules/calib3d/src/chessboard.cpp
modules/core/src/persistence.cpp
modules/features2d/src/kaze/AKAZEFeatures.cpp
modules/objdetect/src/qrcode.cpp

Note: I'll backport to 3.4. manually

Fixs several problems found by static analysis

---

modules/features2d/src/kaze/AKAZEFeatures.cpp
modules/objdetect/src/qrcode.cpp

Backport 3.4: Fix several problems found by static analysis

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra:** opencv/opencv_extra#717
**relates:** #16654
<cut/>
```
```

Support Slice layer with multiple inputs

---

modules/stitching/src/stitcher.cpp

nonfree code is disabled by default.

stitching: don't use nonfree by default

---

.gitignore

See https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019 and https://docs.microsoft.com/en-us/cpp/build/cmakesettings-reference?view=vs-2019

Ignore Visual Studio cmake configuration file

---

samples/cpp/intelligent_scissors.cpp

Add link to article for sample "Intelligent scissors":
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.138.3811&rep=rep1&type=pdf

Add link to article for sample "Intelligent scissors"

---

modules/imgproc/src/bilateral_filter.dispatch.cpp
modules/imgproc/src/box_filter.dispatch.cpp
modules/imgproc/src/deriv.cpp
modules/imgproc/src/filter.dispatch.cpp
modules/imgproc/src/median_blur.dispatch.cpp
modules/imgproc/src/morph.dispatch.cpp
modules/imgproc/src/smooth.dispatch.cpp
modules/imgproc/test/test_filter.cpp
modules/objdetect/src/qrcode.cpp
modules/ts/include/opencv2/ts/ts_ext.hpp

resolves #16857
Throws exception on empty input - see #8300
opencv_contrib tests are good :+1:

imgproc: add src.empty() checks in filter operations

---

3rdparty/libwebp/src/dec/frame_dec.c
3rdparty/libwebp/src/dec/idec_dec.c
3rdparty/libwebp/src/dec/vp8i_dec.h
3rdparty/libwebp/src/dec/vp8l_dec.c
3rdparty/libwebp/src/dec/vp8li_dec.h
3rdparty/libwebp/src/demux/demux.c
3rdparty/libwebp/src/dsp/dec_neon.c
3rdparty/libwebp/src/dsp/dsp.h
3rdparty/libwebp/src/dsp/lossless.c
3rdparty/libwebp/src/dsp/lossless_common.h
3rdparty/libwebp/src/dsp/lossless_enc_sse2.c
3rdparty/libwebp/src/dsp/lossless_sse2.c
3rdparty/libwebp/src/dsp/msa_macro.h
3rdparty/libwebp/src/dsp/upsampling_msa.c
3rdparty/libwebp/src/dsp/upsampling_neon.c
3rdparty/libwebp/src/enc/histogram_enc.c
3rdparty/libwebp/src/enc/picture_csp_enc.c
3rdparty/libwebp/src/enc/vp8i_enc.h
3rdparty/libwebp/src/mux/muxi.h
3rdparty/libwebp/src/mux/muxread.c
3rdparty/libwebp/src/utils/color_cache_utils.h
3rdparty/libwebp/src/utils/thread_utils.c
3rdparty/libwebp/src/utils/utils.c
3rdparty/libwebp/src/webp/decode.h
3rdparty/libwebp/src/webp/encode.h
3rdparty/libwebp/src/webp/mux.h
3rdparty/libwebp/src/webp/mux_types.h
3rdparty/libwebp/src/webp/types.h

- https://github.com/webmproject/libwebp/releases/tag/v1.1.0

3rdparty: update libwebp 1.0.3 => 1.1.0

---

3rdparty/tbb/CMakeLists.txt

- https://github.com/oneapi-src/oneTBB/releases/tag/v2020.1
relates #16195

3rdparty: update TBB 2020.0 => 2020.1

---

modules/core/src/persistence.cpp
modules/core/test/test_io.cpp

core(persistence): fix resource leaks - force closing files

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/src/api/kernels_core.cpp
modules/gapi/src/backends/cpu/gcpucore.cpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp

G-API: Implement WarpPerspective

---

modules/core/src/persistence.cpp
modules/core/src/persistence_c.cpp
modules/core/test/test_io.cpp

resolves #16823
backported tests #16895

(3.4) core(persistence): fix resource leaks - force closing files

---

modules/calib3d/include/opencv2/calib3d.hpp

This PR closes #16292 calib3d(docs): misleading/ wrong documentation for RT
This PR introduces fixes to the documentation of the calib3d module. In addition to improving the documentation, I did minor spelling, grammar, and style guide (line length mostly) work BUT restricted these to those function's documentation that I needed to touch for this PR. 
```
force_builders_only=Docs,linux
```

Closes 16292: calib3d(docs): misleading/ wrong documentation for RT

---

cmake/OpenCVModule.cmake
platforms/winpack_dldt/.gitattributes
platforms/winpack_dldt/2020.1/20200313-dldt-disable-unused-targets.patch
platforms/winpack_dldt/2020.1/20200313-dldt-fix-binaries-location.patch
platforms/winpack_dldt/2020.1/20200313-ngraph-disable-tests-examples.patch
platforms/winpack_dldt/2020.1/20200318-dldt-pdb.patch
platforms/winpack_dldt/2020.1/20200319-dldt-fix-msvs2019-v16.5.0.patch
platforms/winpack_dldt/2020.1/patch.config.py
platforms/winpack_dldt/2020.1/sysroot.config.py
platforms/winpack_dldt/build_package.py
platforms/winpack_dldt/cmake-opencv-checks/POST_FINALIZE.cmake
platforms/winpack_dldt/package-tests/test_dnn_backends.py

Build package with OpenCV and [DLDT](https://github.com/opencv/dldt).
Details are below...<cut/>
Build prerequisites:
- Python 3.5+
- CMake
- Git Bash
- MSVS 2019 ([buildtools](https://aka.ms/buildtools) is enough)
Launch prerequisites:
- package itself requires MSVS 2019 redistibutables: [vc_redist.x64.exe](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
- AVX2 CPU
Build steps:
- create build directory (~10 Gb is required)
- from build directory run `python <opencv_src>/platforms/winpack_dldt/build_package.py`
- check `package` directory
- sanity test:
```
.\package\opencv\build\setup_vars_opencv3.cmd python .\package\opencv\src\opencv\platforms\winpack_dldt\package-tests\test_dnn_backends.py
```
Notes:
- TBB parallel backend is used (from IE) …

Build opencv winpack dldt

---

modules/gapi/src/backends/fluid/gfluidimgproc_func.simd.hpp

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master_etc-simd-emulator-lin64/builds/10).
```
test_module:Custom=gapi
```

G-API(SIMD): initialize accumulator values

---

modules/calib3d/include/opencv2/calib3d.hpp

(3.4) calib3d updates documentation

---

modules/imgproc/src/resize.avx2.cpp
modules/imgproc/src/resize.cpp
modules/imgproc/src/resize.hpp
modules/imgproc/src/resize.sse4_1.cpp

imgproc(resize): drop unused 'pix_size4'

---

modules/videoio/src/cap_msmf.cpp

videoio: fixed conversion in MSMF backend

---

modules/stitching/src/seam_finders.cpp

stitching: fix range check in DpSeamFinder::computeCosts

---

modules/videoio/src/cap_msmf.cpp

videoio: fixed MSMF writer fps handling

---

modules/gapi/src/backends/fluid/gfluidbackend.hpp
modules/gapi/src/compiler/gislandmodel.cpp
modules/gapi/src/compiler/gislandmodel.hpp
modules/gapi/src/executor/gexecutor.cpp
modules/gapi/src/executor/gexecutor.hpp

- Port GExecutor to this new interface
```
```

Introduce a new abstraction layer over island input/output data

---

modules/imgproc/test/ocl/test_houghlines.cpp

OpenCL: let the test pass on Mali G52 (ODROID-N2)

---

modules/dnn/src/dnn.cpp

Fix ENet test with OpenVINO 2020.2

---

modules/imgproc/src/opencl/hough_lines.cl

OpenCL: fix OpenCL spec violation

---

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/test/test_tf_importer.cpp

resolves https://github.com/opencv/opencv/issues/16879
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/738
<cut/>
```
```

Import TF2.0 network from Keras

---

modules/gapi/src/compiler/gislandmodel.hpp

Added export to GIslandExecutable class

---

modules/dnn/src/onnx/onnx_importer.cpp

Fix Elu import from ONNX

---

doc/faq.markdown

FAQ page migrated to Github Wiki: https://github.com/opencv/opencv/wiki/FAQ

Migrated FAQ page to Github Wiki.

---

cmake/OpenCVExtraTargets.cmake
cmake/templates/cmake_uninstall.cmake.in

Details: https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake
closes #16896

cmake: update generation of 'uninstall' target

---

modules/gapi/include/opencv2/gapi/garray.hpp
modules/gapi/include/opencv2/gapi/gopaque.hpp
modules/gapi/src/api/gproto.cpp
modules/gapi/src/api/gproto_priv.hpp
modules/gapi/src/compiler/gislandmodel.cpp
modules/gapi/src/compiler/gislandmodel.hpp
modules/gapi/src/executor/gexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/test/internal/gapi_int_proto_tests.cpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp

Async islands

---

platforms/winpack_dldt/2020.2/20200413-dldt-disable-unused-targets.patch
platforms/winpack_dldt/2020.2/20200413-dldt-fix-binaries-location.patch
platforms/winpack_dldt/2020.2/20200413-dldt-pdb.patch
platforms/winpack_dldt/2020.2/20200415-ngraph-disable-unused-options.patch
platforms/winpack_dldt/2020.2/patch.config.py
platforms/winpack_dldt/2020.2/sysroot.config.py
platforms/winpack_dldt/build_package.py

(3.4) Build OpenCV winpack with DLDT 2020.2

---

doc/py_tutorials/py_ml/py_svm/py_svm_basics/py_svm_basics.markdown

Fix python tutorial document miss

---

modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/layers/blank_layer.cpp
modules/dnn/src/layers/concat_layer.cpp

Remove NodeVector for nGraph

---

cmake/OpenCVDetectInferenceEngine.cmake
modules/dnn/src/op_inf_engine.hpp

dnn: align with OpenVINO 2020.2

---

modules/core/include/opencv2/core/utility.hpp
samples/cpp/tutorial_code/snippets/core_various.cpp

- New `TickMeter` methods: `getFPS`, `getAvgTimeSec` and `getAvgTimeMilli`
- Extracted code snippets from documentation
- Minor formatting fixes

TickMeter: added FPS and AvgTime, improved docs, reformatted

---

modules/core/include/opencv2/core/mat.hpp
modules/core/src/matrix_expressions.cpp
modules/core/src/matrix_wrap.cpp

core: drop EXPR handing code in InputArray

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_ie_models.cpp

Avoid calling `CNNNetworkNGraphImpl::convertToCNNNetworkImpl()` during loading of IRv10.
<cut/>
Scope: tests `DNNTestOpenVINO.models`
Message of failing on MYRIAD with IRv10:
```
[ RUN      ] DNNTestOpenVINO.models/22, where GetParam() = (NGRAPH/MYRIAD, "person-detection-retail-0013")
Exception message: OpenCV(3.4.10-dev) /build/precommit_custom_linux/3.4/opencv/modules/dnn/src/ie_ngraph.cpp:612: error: (-2:Unspecified error)
Failed to initialize Inference Engine backend (device = MYRIAD):
Unexpected CNNNetwork format: it was converted to deprecated format prior plugin's call
in function 'initPlugin'
...
```
```
Xbuild_image:Custom=ubuntu-openvino-2020.1.0:16.04 …
```

dnn(IE): avoid conversion to legacy CNNNetworkImpl

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_sse.hpp

core(SIMD): suppress coverity UNINIT_CTOR on SIMD vectors

---

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/751
```
```

PReLU from Tensorflow

---

modules/cudaoptflow/src/cuda/pyrlk.cu
modules/video/src/lkpyramid.cpp
modules/video/src/lkpyramid.hpp

Resolves issue [#17175](https://github.com/opencv/opencv/issues/17175)

fix Scharr nomination

---

modules/dnn/src/layers/slice_layer.cpp
modules/dnn/test/test_layers.cpp

dnn: Slice with variable input shapes

---

doc/py_tutorials/py_setup/py_intro/py_intro.markdown

Update NumPy links

---

doc/tutorials/introduction/documenting_opencv/documentation_tutorial.markdown

The previous link yielded "SORRY This page does not exist yet."

Update Supported formula commands - MathJax link

---

doc/tutorials/imgproc/table_of_content_imgproc.markdown

This adds the Languages field for the "Random generator and text with OpenCV" tutorial and updates the Languages field for the "Anisotropic image segmentation by a gradient structure tensor" tutorial.
On a related note: I have not been able to locate an equivalent for the C++ RNG class in Python, but I believe this functionality can be achieved with NumPy (among other options). If I have missed the equivalent or if NumPy is an acceptable alternative, I would very much like to try expanding the "Random generator and text with OpenCV" tutorial to include Python. Thank you!

Update table of content for imgproc module tutorials to reflect languages used

---

modules/videoio/src/cap_dshow.cpp

- [. ] I agree to contribute to the project under OpenCV (BSD) License.
- [ .] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ .] The PR is proposed to proper branch
- [ .] There is reference to original bug report and related work
- [ .] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ .] The feature is well documented and sample code can be built with the project CMake
This solved issue #17207

(3.4) Fix MINGW DShow compilation

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

Merge with extra: opencv/opencv_extra#748
resolves: #15822
```
```

 Added NDHWC Concat support for TensorFlow

---

doc/tutorials/introduction/windows_visual_studio_image_watch/windows_visual_studio_image_watch.markdown

Updated the Windows Visual Studio Image Watch tutorial to include download links to the latest versions for the latest Visual Studio versions.

Update Image Watch Tutorial

---

doc/js_tutorials/js_setup/js_setup/js_setup.markdown
doc/js_tutorials/js_setup/js_usage/js_usage.markdown

Included instructions on getting the prebuilt `opencv.js` script in the releases and online documentations in the tutorial. Could help those people who simple want to start using the script. Resolves #17094 .

Easier access to opencv.js in tutorial

---

README.md

Adding Official OpenCV course link

---

samples/dnn/tf_text_graph_ssd.py

Determine SSD input shape

---

doc/js_tutorials/js_setup/js_nodejs/js_nodejs.markdown

resolves #17279
Update documentation to solve #17279. Simple documentation bug. This is my first PR to this repository. Please be gentle!
<cut/>
```
```

Fix #17279 Documentation Error

---

modules/features2d/test/ocl/test_feature2d.cpp

features2d: fix test failure on Mali T760 and Mali T628

---

modules/dnn/src/layers/resize_layer.cpp
modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/757/
<cut/>
```
```

TensorFlow downscale bilinear resize

---

modules/calib3d/src/stereobm.cpp
modules/calib3d/test/test_stereomatching.cpp

1. Fixes Possible code error in stereobm.cpp in calib3d module
2. Added UT for BufferBM usage in StereoBM
resolves #17201

Fixed indexing in prefilter

---

samples/_winpack_build_sample.cmd

Important single character fix

---

samples/opencl/opencl-opencv-interop.cpp

samples: fix OpenCL events leaks

---

doc/py_tutorials/py_ml/py_knn/py_knn_opencv/py_knn_opencv.markdown
doc/py_tutorials/py_ml/py_knn/py_knn_understanding/py_knn_understanding.markdown

This pull request covers a number of revisions and small additions to the kNN tutorials for OpenCV-Python. I would be very happy to do the same for the other Python ML tutorials!
Please note that I am not sure why some sentences were split across multiple lines. While it does not seem to reflect on Github, this can be seen by viewing the *original unaltered* files (and other ML tutorials) in VSCode and Vim.

Revise and expand kNN Python tutorials

---

3rdparty/quirc/include/quirc_internal.h
3rdparty/quirc/src/decode.c
3rdparty/quirc/src/quirc.c
3rdparty/quirc/src/version_db.c

Update [quirc library](https://github.com/dlbeer/quirc) to v1.1 version
```
```

Objdetect: QR decoder: Update 3rd party

---

modules/imgproc/include/opencv2/imgproc.hpp

Fix documentation for cv::blur

---

modules/dnn/src/layers/convolution_layer.cpp

backport #17374 
```
force_builders=Linux32
```

(3.4) dnn: *_DENORMALS_ZERO_MODE is defined for SSE3

---

modules/dnn/src/layers/normalize_bbox_layer.cpp

Switch ngraph::op::v1::Multiply to v0

---

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra:** opencv/opencv_extra#761
resolves: opencv/opencv#17243
```
```

Add ClipByValue subgraph

---

samples/dnn/mask_rcnn.py
samples/dnn/segmentation.py

Fix segmentation py

---

modules/dnn/src/dnn.cpp

Bug introduced in #16161
The concat fusion logic creates new wrappers. I forgot to set the streams of the newly created wrappers after fusion. This makes the wrappers use the default stream for copying.
#17349 dropped support for default streams and added assertions to catch the accidental use of default streams.
The new assertions are triggered when blobs of concat layer are being transferred from host to device or vice versa. Unfortunately, this situation does not happen in any test case. Hence, the bug wasn't caught.
This PR removes the need to set streams manually (very error-prone and easy to forget) and instead does it automatically in `wrap`. Ideally, it is best if this was done inside `wrapMat` but it's a static function and doesn't have access to `impl`. The `setStream` code has …

cuda4dnn(concat): fix stream not being set for concat wrappers after fusion 

---

doc/mymath.sty

Fix for https://github.com/opencv/opencv/issues/16989

Command name typo fix for formulas in documentation.

---

modules/dnn/perf/perf_net.cpp
modules/dnn/test/test_darknet_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/762
relates #17148
<cut/>
```
force_builders=Linux32,Win32,Custom,Custom Win,Custom Mac
```

dnn(test): add YOLOv4 tests

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/layers/region_layer.cpp
modules/dnn/src/model.cpp

related: opencv/opencv#17332
```
```

Fixed NMSBoxes bug in DetectionModel

---

modules/dnn/src/darknet/darknet_io.cpp

chk divide 0 in darknet

---

modules/js/test/tests.html

Fix Test Case: in latest version, window.cv is a promise instance that makes most test case failed.

---

modules/dnn/test/test_tf_importer.cpp

dnn(test): file 'dnn/efficientdet-d0.pb' is optional

---

samples/dnn/human_parsing.cpp

should this go into 3.4 or master ?

dnn: add a human parsing cpp sample

---

modules/core/src/count_non_zero.dispatch.cpp
modules/core/test/test_countnonzero.cpp

related #17453
<cut/>
```
Xdisable_ipp=ON
```

Added countNonZero test for big arrays

---

platforms/winpack_dldt/2020.3.0/20200413-dldt-disable-unused-targets.patch
platforms/winpack_dldt/2020.3.0/20200413-dldt-fix-binaries-location.patch
platforms/winpack_dldt/2020.3.0/20200413-dldt-pdb.patch
platforms/winpack_dldt/2020.3.0/20200604-dldt-disable-multidevice.patch
platforms/winpack_dldt/2020.3.0/patch.config.py
platforms/winpack_dldt/2020.3.0/sysroot.config.py
platforms/winpack_dldt/build_package.py

https://github.com/openvinotoolkit/openvino/releases/tag/2020.3.0
relates #16847 #17056
Preview packages:
- [3.4 branch](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_custom_windows/20200604-105156--1090/)
- [master branch](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_custom_windows/20200604-100214--1089/)
```
```

Build OpenCV winpack with DLDT 2020.3.0

---

cmake/OpenCVDetectVTK.cmake

**Merge with contrib**: opencv/opencv_contrib#2549
~Note: the code builds but does not work, additional investigation required~

Added VTK 9 support

---

doc/tutorials/dnn/dnn_android/dnn_android.markdown
doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/python/package/setup.py
platforms/android/build_sdk.py
platforms/android/service/readme.txt
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #16770

pre: OpenCV 3.4.11 (version++)

---

doc/tutorials/dnn/dnn_android/dnn_android.markdown
doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/version.hpp
modules/python/package/setup.py
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #16771

pre: OpenCV 4.4.0 (version++)

---

3rdparty/ffmpeg/ffmpeg.cmake

ffmpeg/4.4: update FFmpeg plugin

---

modules/dnn/src/dnn.cpp
modules/objdetect/src/qrcode.cpp

Note: I decided to refactor problematic method in qrcode.cpp to make it more readable.
```
```

Fix minor issues found by static analysis

---

modules/core/src/precomp.hpp

add Memory barriers

---

modules/core/include/opencv2/core/eigen.hpp

Add documentation about usage of cv2eigen functions in eigen.hpp

---

doc/tutorials/introduction/macos_install/macos_install.markdown

Closes #17340
- [ ✓ ] I agree to contribute to the project under OpenCV (BSD) License.
- [ ✓ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ✓ ] The PR is proposed to proper branch
- [ ✓ ] There is reference to original bug report and related work
- [ ✓ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ ✓ ] The feature is well documented and sample code can be built with the project CMake

Added information to OpenCV documentation [MacOS]

---

cmake/OpenCVFindMKL.cmake

I use the MKL package provided by nuget. Please check this link(https://software.intel.com/en-us/articles/installing-intel-performance-libraries-using-nuget) for related information.
MKL 2020.1.216

improve the mkl search procedure

---

cmake/OpenCVDetectInferenceEngine.cmake
modules/dnn/src/dnn.cpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/op_inf_engine.hpp

Align with https://github.com/opencv/opencv/releases/tag/4.3.0-openvino-2020.3.0
<cut/>
```
```

DNN: use OpenVINO 2020.3 defines

---

modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/op_inf_engine.cpp

Removed plugin dispatcher

---

modules/core/misc/objc/common/CVObjcUtil.h
modules/core/misc/objc/common/Mat.h
modules/core/misc/objc/common/Mat.mm
modules/imgproc/misc/objc/test/ImgprocTest.swift
modules/objc/generator/gen_objc.py
platforms/ios/build_framework.py

resolves #17547
<cut/>
This pull request;
- reworks native pointer handling to use cv::Ptr instead of raw pointer
- reworks Objective-C wrapper creation to ensure wrappers of the correct Objective-C object are created
- fixes testFitEllipse (broken by a different commit)
- fixes a small bug in the iOS build script
```
buildworker:iOS=macosx-1
```

Rework native pointer handling for Objective-C/Swift binding

---

modules/dnn/src/layers/region_layer.cpp

```
test_filter:Custom=*YOLO*
```

Changed StridedSlice to VariadicSplit in Region layer

---

cmake/OpenCVDetectCUDA.cmake

respect CUDA_HOST_COMPILER when detecting CUDA arch

---

cmake/OpenCVDetectCUDA.cmake

resolves #17598 
relates #17526 
<cut/>
```
```

CUDA: Fix cuda fail safe path

---

modules/core/src/logger.cpp

- for using of logging functions from global destructors
relates #13909

core(logger): complete initialization of logger structures

---

modules/dnn/test/test_ie_models.cpp

<cut/>
```
test_filter:Custom=*OpenVINO*
```

Conditional compilation for network reader

---

modules/dnn/src/dnn.cpp
modules/dnn/src/op_inf_engine.hpp

Conditional compilation for IR v7 support

---

modules/flann/include/opencv2/flann/kdtree_single_index.h

Optim: test that could be done once has been extracted from the loop

---

modules/flann/include/opencv2/flann/dist.h
modules/flann/include/opencv2/flann/kmeans_index.h
modules/flann/include/opencv2/flann/lsh_index.h
modules/flann/include/opencv2/flann/lsh_table.h
modules/flann/include/opencv2/flann/result_set.h

Pev  fixes and clean

---

modules/flann/include/opencv2/flann/hierarchical_clustering_index.h

Remove duplicate line

---

modules/imgproc/include/opencv2/imgproc.hpp

Clarify component statistics documentation

---

modules/flann/src/miniflann.cpp

<cut/>
test_module_force=flann

Fix arguments list in loadindex for histogram intersection

---

cmake/OpenCVCompilerOptions.cmake

cmake: fix ENABLE_PROFILING

---

modules/flann/include/opencv2/flann/autotuned_index.h
modules/flann/include/opencv2/flann/flann_base.hpp
modules/flann/include/opencv2/flann/hierarchical_clustering_index.h
modules/flann/include/opencv2/flann/index_testing.h
modules/flann/include/opencv2/flann/kdtree_index.h
modules/flann/include/opencv2/flann/kdtree_single_index.h
modules/flann/include/opencv2/flann/kmeans_index.h
modules/flann/include/opencv2/flann/lsh_index.h
modules/flann/include/opencv2/flann/lsh_table.h
modules/flann/include/opencv2/flann/nn_index.h
modules/flann/include/opencv2/flann/simplex_downhill.h

<cut/>
test_module_force=flann

Clean: replace C style asserts by CV_Assert and CV_DbgAssert

---

modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/layers/prior_box_layer.cpp
modules/dnn/src/layers/proposal_layer.cpp
modules/dnn/src/layers/reorg_layer.cpp
modules/dnn/src/layers/resize_layer.cpp

Fixed header paths for some nGraph ops

---

modules/dnn/perf/perf_net.cpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/test/test_common.impl.hpp
modules/dnn/test/test_darknet_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/771
relates #17666 
<cut/>
```
test_filter:Custom=*DarkNet*:*YOLO*
test_filter:Custom Win=*DarkNet*:*YOLO*
```

dnn(test): add YOLOv4-tiny tests

---

platforms/winpack_dldt/2020.4/20200413-dldt-pdb.patch
platforms/winpack_dldt/2020.4/20200604-dldt-disable-multidevice.patch
platforms/winpack_dldt/2020.4/20200701-dldt-disable-unused-targets.patch
platforms/winpack_dldt/2020.4/patch.config.py
platforms/winpack_dldt/2020.4/sysroot.config.py
platforms/winpack_dldt/build_package.py

https://github.com/openvinotoolkit/openvino/tree/releases/2020/4 (not released yet)
relates #16847 #17056 #17466
Required build options:
```
opencv/platforms/winpack_dldt/build_package.py --dldt_src_branch=releases/2020/4 --dldt_src_commit=relea
ses/2020/4 --dldt_release=2020040000
```
<cut/>
Preview packages:
- [3.4 branch](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_custom_windows/20200707-190643--1191/)
- [master branch](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_custom_windows/20200706-150535--1182/)
<cut/>
```
build_image:Custom Win=winpack-dldt-2020.4
```

Build OpenCV winpack with DLDT 2020.4.0

---

modules/core/src/trace.cpp

core: use lazy on-demand initialization for param_traceEnable

---

modules/features2d/src/sift.simd.hpp

features2d: v_fma => v_mulladd for integers

---

modules/core/misc/objc/common/CVObjcUtil.h
modules/core/misc/objc/common/DMatch.mm
modules/core/misc/objc/common/KeyPoint.mm
modules/core/misc/objc/common/Point2d.mm
modules/core/misc/objc/common/Point2f.mm
modules/core/misc/objc/common/Point3d.mm
modules/core/misc/objc/common/Point3f.mm
modules/core/misc/objc/common/Rect2d.mm
modules/core/misc/objc/common/Rect2f.mm
modules/core/misc/objc/common/RotatedRect.mm
modules/core/misc/objc/common/Scalar.mm
modules/core/misc/objc/common/Size2d.mm
modules/core/misc/objc/common/Size2f.mm
modules/core/misc/objc/common/TermCriteria.mm
modules/objc/doc/README.md
modules/objc/generator/gen_objc.py
platforms/ios/build_framework.py

This PR
- fixes #17817
- improves the documentation to show the relationship between classes and modules (partially addresses comment from @vpisarev on PR #17165 )
- adds favicon to documentation bundle
<cut/>

Documentation fixes/improvements

---

modules/dnn/src/graph_simplifier.cpp
modules/dnn/src/tensorflow/tf_graph_simplifier.cpp

Move TensorFlow specific names management for graphs fusion.

Fix TensorFlow->ONNX imports

---

modules/dnn/perf/perf_layer.cpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/opencl/slice.cl
modules/dnn/test/test_layers.cpp

resolves #17762
relates #17743
TODO:
<cut/>
```
**WIP**
Xbuild_image:Custom=ubuntu:18.04
Xbuildworker:Custom=linux-5
Xtest_opencl:Custom=ON
Xbuild_image:Custom Win=openvino-2019r3.0
Xtest_modules:Custom=dnn,python2,python3,java
test_filter:Custom=*lice*:*plit*
test_filter:Custom Win=*lice*:*plit*
```

dnn: fix OpenCL implementation of Slice layer

---

modules/imgproc/src/color_yuv.dispatch.cpp
modules/imgproc/test/test_color.cpp

imgproc: add missing check into cvtColorTwoPlane()

---

modules/gapi/include/opencv2/gapi/infer.hpp

resolves  #17869 
<cut/>
```
Xbuild_image:Custom Win=msvs2017
```

G-API: Try to fix infer2 problem with VS2017

---

modules/core/include/opencv2/core/version.hpp

relates #17506
<cut/>
<details>
[opencv_world440.dll (vc14)](https://www.virustotal.com/gui/file/de5df2551ae10bd22a16c268cf7de9e7b39200182f80a355133957e1492ec1b9/detection)
[opencv_world440d.dll (vc14)](https://www.virustotal.com/gui/file/09be72dd5c5ab949b45becc76469f9e2d79a8c59a8c9e3a8f51d66b96c554589/detection) 
[opencv_world440.dll (vc15)](https://www.virustotal.com/gui/file/6e5a73e453fcd932d6fcf3f2668b396df330e109c8158708d549b403bb5707bf/detection)
[opencv_world440d.dll (vc15)](https://www.virustotal.com/gui/file/76ddbf749041321989e0255099169f7b484f1f1b59a268421427b05a6d098352/detection)
[opencv_ffmpeg440_64.dll](https://www.virustotal.com/gui/file/2a8a9358868d414fe37d708234340c67cbebd779ab44cdb24d33a196dd206136/detection) …

release: OpenCV 4.4.0

---

modules/dnn/src/ie_ngraph.cpp

These changes are needed for https://github.com/openvinotoolkit/openvino/pull/1324
<cut/>
```
```

Fixed removing is_parameter, is_constant, is_output

---

modules/dnn/src/ie_ngraph.cpp

Reverts opencv/opencv#17872
This PR is broke the current OpenVINO master.

Revert "Fixed removing is_parameter, is_constant, is_output"

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

relates: #17647 
**merge with extra:** opencv/opencv_extra#774
<cut/>
```
```

Support Gather for variable inputs

---

doc/opencv.bib
modules/imgproc/include/opencv2/imgproc.hpp

Added reference to Original Wu's articte about SAUF algorithm

---

modules/dnn/src/layers/elementwise_layers.cpp

update mish functor

---

modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/opencl/slice.cl

relates #17764
- make slice kernel VTune friendly
- prefer to spawn more work groups
- cache kernel execution information
<cut/>
```
```

DNN: OpenCL/slice update

---

modules/dnn/src/cuda/mvn.cu
modules/dnn/src/cuda4dnn/kernels/mvn.hpp
modules/dnn/src/cuda4dnn/primitives/mvn.hpp
modules/dnn/src/layers/mvn_layer.cpp

```
Xbuild_image:Custom=ubuntu-cuda11:18.04
```

cuda4dnn(MVNOp): add MVNOp

---

modules/flann/include/opencv2/flann/hierarchical_clustering_index.h

Cleaner code for hierarchical_clustering

---

modules/flann/include/opencv2/flann.hpp
modules/flann/include/opencv2/flann/kmeans_index.h

Pev  multiple kmeans trees

---

modules/core/include/opencv2/core.hpp

Fixes https://github.com/opencv/opencv/issues/18000

Document PatchNANs input type (issue #18000)

---

modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/layers_common.simd.hpp

(3.4) added depth-wise convolution (backport 17858)

---

modules/dnn/src/onnx/onnx_importer.cpp

relates: #17921
<cut/>
```
```

Fix ONNX Gather op

---

modules/videoio/src/cap_ffmpeg_impl.hpp

In order to support encoding AV1 videos we need to use the new ffmpeg encoding API. This PR enables encoding videos using  the [rav1e](https://github.com/xiph/rav1e) encoder. 
Relates #11389 
/cc @alalek 
```
force_builders=linux,windows,mac,docs
```

Add support for using new ffmpeg encoding API when writing a video 

---

modules/flann/include/opencv2/flann.hpp
modules/flann/include/opencv2/flann/kmeans_index.h

Merge the two KMeansIndexParams ctor on master

---

modules/core/misc/objc/common/Mat.h
modules/objc/generator/gen_objc.py
modules/objc/generator/templates/cmakelists.template
platforms/ios/build_docs.py
platforms/ios/build_framework.py
platforms/osx/build_docs.py
platforms/osx/build_framework.py

This PR resolves #18058
- builds combined Swift/Objective-C documentation
- adds sample code to `Mat` class documentation
- adds documentation for `Mat(rows:cols:type:)` constructor
- adds build flags `--run_test` and `--build_docs`
- adds links in the documentation from parent modules and manually written member classes (e.g. from `Core` to `Mat`)

Obj-C/Swift docs improvements

---

modules/flann/include/opencv2/flann/kmeans_index.h

Refactoring to prepare for other vector types while mutualizing methods

---

modules/dnn/src/ie_ngraph.cpp

related PR in openvino
https://github.com/openvinotoolkit/openvino/pull/1334
**MUST BE** merged after merging related PR's

[IE][VPU]: Refactor vpu configs

---

doc/opencv.bib
modules/imgproc/include/opencv2/imgproc.hpp

As requested in this ticket https://github.com/opencv/opencv/issues/17451, I added reference in documentation.

Added reference to paper to CornerSubPix function.

---

samples/cpp/stereo_match.cpp

* add the HH4 mode
* option to display disparity with a color map
* display current settings in the title bar
* don't close app when wanting to take screenshots

Update the stereo sample:

---

modules/calib3d/src/usac/degeneracy.cpp
modules/calib3d/src/usac/ransac_solvers.cpp
samples/cpp/essential_mat_reconstr.cpp

[GSoC, New RANSAC] Fix warnings

---

modules/flann/include/opencv2/flann.hpp
modules/flann/include/opencv2/flann/defines.h
modules/flann/include/opencv2/flann/dist.h

DNA mode: add the distance computations

---

doc/pattern_tools/gen_pattern.py

Fixed centering issue with make_cicle_pattern and make_acircle_pattern()

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/solvepnp.cpp

This is 5 years too late in my opinion.
See #5065 and https://github.com/opencv/opencv/pull/6864#issuecomment-473450679

Add broken implementation note for DLS and UPnP

---

samples/dnn/siamrpnpp.py

Proposal : https://summerofcode.withgoogle.com/projects/#4979746967912448
Mentors : Liubov Batanina @l-bat, Stefano Fabri @bhack, Ilya Elizarov @ieliz
Student : Jin Yeob Chung @jinyup100
-  Export of the torch implementation of the SiamRPN++ visual tracker to ONNX
- Please refer to (https://gist.github.com/jinyup100/7aa748686c5e234ed6780154141b4685) or _Code to 
generate ONNX models_ at the bottom of this PR description
-  Addition of siamrpnpp.py in the opencv/samples/dnn repository  
- SiamRPN++ visual tracker can be performed on a sample video input
- Parsers include:
- --input_video  _path to sample video input_
- --target_net _path to target branch of the visual tracker_
- --search_net  _path to search branch of the visual tracker_
- --rpn_head _path to head of the visual tracker_
- …

[GSoC] Add siamrpnpp.py

---

modules/dnn/src/layers/scale_layer.cpp
modules/dnn/test/test_layers.cpp
samples/dnn/optical_flow.py

merge with extra: opencv/opencv_extra#780
</cut>
```
opencv_extra=data_aug_with_different_size
```

Flownet2 with anysize

---

samples/dnn/models.yml

ADD yolov4 in models.yml

---

modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/perf/perf_resize.cpp
modules/imgproc/src/fixedpoint.inl.hpp
modules/imgproc/src/resize.cpp
modules/imgproc/test/test_imgwarp.cpp
modules/imgproc/test/test_resize_bitexact.cpp

Bit-exact Nearest Neighbor Resizing

---

modules/flann/include/opencv2/flann/kmeans_index.h
modules/flann/src/miniflann.cpp

Pev  handle dna vectors

---

modules/dnn/src/onnx/onnx_importer.cpp

resolves: #18209
<cut/>
```
```

Support Reshape with zero dim

---

modules/calib3d/src/calibinit.cpp
modules/calib3d/src/calibration.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp
modules/flann/include/opencv2/flann/result_set.h
modules/flann/include/opencv2/flann/timer.h
modules/highgui/src/window_w32.cpp
modules/objdetect/src/cascadedetect_convert.cpp

(3.4) backport: checks and fixes from static code analyzers results

---

modules/calib3d/src/usac.hpp
modules/dnn/src/dnn.cpp

checks and fixes from static code analyzers results (2)

---

doc/tutorials/dnn/dnn_android/dnn_android.markdown
doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/python/package/setup.py
platforms/android/build_sdk.py
platforms/android/service/readme.txt
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #17501

pre: OpenCV 3.4.12 (version++)

---

.github/ISSUE_TEMPLATE.md

Fix typo in the issue template that was fixed in opencv_contrib: https://github.com/opencv/opencv_contrib/pull/2461#discussion_r392132312.

ISSUE_TEMPLATE: fix typo

---

modules/videoio/src/backend_plugin.cpp

Haiku is POSIX compatible
- [x ] I agree to contribute to the project under Apache 2 License.
- [x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ x] The PR is proposed to proper branch
- [x ] The feature is well documented and sample code can be built with the project CMake

Haiku: build fix

---

doc/tutorials/dnn/dnn_android/dnn_android.markdown
doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/version.hpp
modules/python/package/setup.py
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #17506

pre: OpenCV 4.5.0 (version++)

---

3rdparty/ffmpeg/ffmpeg.cmake

ffmpeg/4.x: update FFmpeg wrapper

---

modules/imgcodecs/src/loadsave.cpp

imgcodecs: lazy on-demand codecs initialization

---

modules/imgproc/src/connectedcomponents.cpp
modules/imgproc/test/test_connectedcomponents.cpp

Fix signed integer overflow in connected components

---

doc/py_tutorials/py_imgproc/py_contours/py_contour_properties/py_contour_properties.markdown

Note: I created a second PR because I couldn't change the source branch in the previous PR.
This explanation was created to avoid confusion, but it seems like the author was confused :D

Fix np row,column to cv y,x [3.4 branch]

---

modules/gapi/include/opencv2/gapi/gcomputation.hpp
modules/gapi/include/opencv2/gapi/gproto.hpp
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/shadow_gapi.hpp
modules/gapi/misc/python/test/test_gapi_core.py
modules/python/src2/cv2.cpp

[G-API] Wrap GIn & GOut

---

modules/core/src/matrix_wrap.cpp

core: emit more clear messages in OutputArray::create()

---

doc/tutorials/calib3d/camera_calibration/camera_calibration.markdown

typo error

---

modules/dnn/src/cuda4dnn/init.hpp

Make sure there is a cuda device before getting it

---

modules/dnn/test/test_ie_models.cpp

* Extracted similar code to a function
* Check result of `map::find`
<cut/>
```
```

dnn: fix some tests

---

modules/core/src/directx.cpp
modules/core/src/ocl.cpp
modules/core/src/opengl.cpp
modules/core/src/va_intel.cpp

OCL: fix PlatformInfo usage

---

modules/objc/generator/CMakeLists.txt
modules/objc/test/cmakelists.template
platforms/ios/build_framework.py
samples/swift/ios/ColorBlobDetection/ColorBlobDetectionDynamic.xcodeproj/project.pbxproj
samples/swift/ios/ColorBlobDetection/ColorBlobDetectionDynamic.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
samples/swift/ios/FaceDetection/FaceDetectionDynamic.xcodeproj/project.pbxproj
samples/swift/ios/FaceDetection/FaceDetectionDynamic.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

This PR fixes #18381 and #18405
- fix cmake file to handle case when we are not building **opencv_world**
- modify **install_name** to not hard code library path
- update tests and samples to work with the change to **install_name**
<cut/>
```
```

iOS build fixes

---

modules/gapi/include/opencv2/gapi/gcommon.hpp
modules/gapi/include/opencv2/gapi/gopaque.hpp
modules/gapi/src/backends/common/serialization.cpp
modules/gapi/src/backends/common/serialization.hpp
modules/gapi/test/gapi_array_tests.cpp
modules/gapi/test/gapi_opaque_tests.cpp
modules/gapi/test/s11n/gapi_s11n_tests.cpp
modules/gapi/test/s11n/gapi_sample_pipelines_s11n.cpp

[G-API] Add support for more types serialization

---

modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp
modules/dnn/src/opencl/conv_layer_spatial.cl
modules/dnn/test/test_layers.cpp

resolves #17953
resolves #18433
relates #9847
Thanks @YashasSamaga and @tomoaki0705 for reporting this problem!

dnn(opencl): fix convolution kernel w/o bias with activation

---

modules/dnn/src/layers/resize_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp

Emit more information from DNN ONNX importer.

dnn: improve debugging of ONNX parsing errors

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/gcomputation.hpp
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/shadow_gapi.hpp
modules/gapi/misc/python/test/test_gapi_core.py
modules/gapi/misc/python/test/test_gapi_sample_pipelines.py
modules/gapi/src/api/gcomputation.cpp
modules/gapi/test/gapi_gcomputation_tests.cpp
modules/python/src2/cv2.cpp

[G-API] wrap gin

---

modules/core/src/opencl/runtime/opencl_core.cpp
platforms/android/build_sdk.py

Android OpenCL support

---

modules/gapi/include/opencv2/gapi/gcomputation.hpp
modules/gapi/include/opencv2/gapi/s11n.hpp
modules/gapi/src/api/gcomputation.cpp
modules/gapi/src/api/gcomputation_priv.hpp
modules/gapi/src/api/s11n.cpp
modules/gapi/src/backends/common/serialization.cpp
modules/gapi/src/backends/common/serialization.hpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/test/s11n/gapi_s11n_tests.cpp

[G-API] Export a part of serialization interface

---

modules/calib3d/src/fundam.cpp
modules/calib3d/src/ptsetreg.cpp
modules/calib3d/src/solvepnp.cpp
modules/calib3d/src/usac/local_optimization.cpp

Related: https://github.com/opencv/opencv/pull/17683 https://github.com/opencv/opencv/pull/18482
Fixes #18454

change flags and bugfix graph in new RANSAC. 

---

doc/tutorials/videoio/intelperc.markdown

I am a global innovator intel and I will humbly help update the integration with the camera realsense. I have almost all models (from the perceptual to the d435).

Modified for Intel Realsense webcam

---

modules/core/src/parallel.cpp

Simple patch to check if OpenBSD is defined.

Add an OpenBSD check

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_misc.cpp

dnn: check for empty Net in .forward()

---

modules/core/include/opencv2/core/eigen.hpp

resolves #18472
relates #17320
- define OPENCV_DISABLE_EIGEN_TENSOR_SUPPORT

core: allow to disable including of unsupported/Eigen/CXX11/Tensor

---

modules/core/test/test_mat.cpp

core(test): regression test for 18473

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/java/generator/gen_java.py

java: fix javadoc generation

---

doc/stylesheet.css

doxygen: backport style changes

---

modules/core/include/opencv2/core/version.hpp

relates #18278
This PR is opened for CI configuration for OpenCV 5.x branch.
<cut/>
```
```

next: OpenCV 5.0-pre

---

modules/dnn/perf/perf_net.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_torch_importer.cpp

<cut/>
```
Xbuild_image:Custom=ubuntu-openvino-2020.4.0:16.04
Xbuild_image:Custom Win=openvino-2020.4.0
Xbuild_image:Custom Mac=openvino-2020.4.0
```

dnn(test): update tests for OpenVINO 2021.1

---

platforms/winpack_dldt/2020.4/20201005-dldt-fix-cldnn-compilation.patch
platforms/winpack_dldt/2020.4/patch.config.py
platforms/winpack_dldt/2021.1/20200413-dldt-pdb.patch
platforms/winpack_dldt/2021.1/20200604-dldt-disable-multidevice.patch
platforms/winpack_dldt/2021.1/20201005-dldt-disable-unused-targets.patch
platforms/winpack_dldt/2021.1/patch.config.py
platforms/winpack_dldt/2021.1/sysroot.config.py
platforms/winpack_dldt/build_package.py

https://github.com/openvinotoolkit/openvino/releases/tag/2021.1
relates #16847 #17056 #17466 #17759
Preview packages:
- [3.4 branch](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_custom_windows/20201007-204007--1495/)
- [master branch](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_custom_windows/20201007-162014--1492/)
<cut/>
```
```

Build OpenCV winpack with DLDT 2021.1.0

---

modules/dnn/test/test_layers.cpp

dnn(test): enable tests from issue 17953

---

modules/dnn/src/dnn.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/test/test_common.impl.hpp
modules/dnn/test/test_layers.cpp

dnn(opencl): bypass unsupported fusion cases

---

cmake/OpenCVDetectCUDA.cmake

cmake: fix typo in CUDA_GENERATION=Auto cache

---

modules/dnn/test/test_model.cpp

<cut/>
```
Xbuild_image:Custom=ubuntu-openvino-2020.4.0:16.04
Xbuild_image:Custom Win=openvino-2020.4.0
Xbuild_image:Custom Mac=openvino-2020.4.0
test_modules:Custom Mac=dnn,gapi,python2,python3,java
```

dnn(test): update tests for OpenVINO 2021.1 (OpenCV 4.x)

---

modules/core/include/opencv2/core/version.hpp

relates #18288
<cut/>
<details>
[opencv_world450.dll (vc14)](https://www.virustotal.com/gui/file/96fdca3c5549adde7c6a7f20384e82c960768a29a191dd001ebafda9fcdf8881/detection)
[opencv_world450d.dll (vc14)](https://www.virustotal.com/gui/file/264a6b121c45a060e8dc432c1cd6c05e7f468ae711be2296b1e0e980d8fd0724/detection) 
[opencv_world450.dll (vc15)](https://www.virustotal.com/gui/file/47c4bfd64eb1740af837af6e937ff68df07e4ad1670f66d71534ddb0a3438fb0/detection)
[opencv_world450d.dll (vc15)](https://www.virustotal.com/gui/file/08aeae0f13d5b07a5ee83f527b0b710f2789de9041b7c5aa36ebf711a319d7f8/detection)
[opencv_ffmpeg450_64.dll](https://www.virustotal.com/gui/file/e5b3be3fa9d73ff07b3b78bb97bab21b8628315a2d8efcdbce36179a11333a4d/detection)
</details>

release: OpenCV 4.5.0

---

platforms/winpack_dldt/build_package.py

build: winpack_dldt with videoio plugins

---

3rdparty/protobuf/CMakeLists.txt

cmake(protobuf): ensure using of own headers

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp

imwrite: multi-image overload for bindings

---

modules/objc/generator/gen_objc.py

Fixes issue with Objective-C binding discovered while fixing #18598 
- when generating properties with enum type - add casts between the C++ enum and the Objective-C enum type
- prevent the same header being included multiple times
- minor code tidy-up

Fix Objective-C/Swift binding's handling of properties with enum type 

---

modules/core/include/opencv2/core/directx.hpp
modules/core/src/directx.cpp
modules/core/src/directx.hpp
modules/core/src/ocl.cpp

Add support for DirectX-OpenCL interop thread-local initialization.
<cut/>
```
force_builders=Linux x64,Linux OpenCL,Win64 OpenCL,Docs
```

Add support thread-local directx (OpenCL interop) initialization

---

modules/gapi/include/opencv2/gapi/media.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp

G-API KW fixes (WW43 2020)

---

modules/videoio/src/cap_avfoundation.mm
modules/videoio/src/cap_avfoundation_mac.mm

add HEVC(H.265) codec to iOS,Mac VideoWriter

---

samples/dnn/siamrpnpp.py

fixes #18613

---

modules/imgproc/include/opencv2/imgproc.hpp

Typo in docstring of distanceTransform

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/rmat.hpp
modules/gapi/include/opencv2/gapi/s11n.hpp
modules/gapi/src/api/s11n.cpp
modules/gapi/src/backends/common/serialization.cpp
modules/gapi/src/backends/common/serialization.hpp
modules/gapi/test/s11n/gapi_s11n_tests.cpp

[G-API]: Introduce RMat serialization API

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp

[G-API] Fix namespace for OCVCallHelper

---

modules/objdetect/include/opencv2/objdetect.hpp
modules/objdetect/src/qrcode.cpp
modules/objdetect/test/test_qrcode.cpp

These changes add detection and decoding of curved QR-codes

Detection and decoding of curved QR-codes

---

modules/objdetect/src/qrcode.cpp

resolves #18669
These changes fix bug in decoding of curved QR-codes
```
build_debug:Custom Win=ON
```

Curved QR-code decoding (fix)

---

modules/gapi/include/opencv2/gapi/infer/ie.hpp
modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

Expand ie::Params to support config

---

modules/gapi/src/executor/gstreamingexecutor.cpp

Set queue size = 1 to Copy island right after the desync.
In this case, Copy won't read more data from a "last_written"
container than required, while feeding the desynchronized path.
Sometimes Copy don't get fused into an island and behaves
on its own -- in this case, it reads more data in advance
so the slow (desync) part actually processes some data in-sync
(more than actually required)
``` …
```

G-API: Desync -- fix the queue saturation problem

---

modules/gapi/src/backends/ie/giebackend/giewrapper.cpp

```
Xtest_modules:Custom=gapi
```

Fixed Inputs/OutputsDataMap conversion

---

doc/CMakeLists.txt

- ~~add samples/data~~ (need to resolve conflicts first)
- add opencv_contrib/modules
<cut/>
```
Xforce_builders=docs
Xopencv_contrib=pr2743
```

doxygen: adjust IMAGE_PATH

---

modules/calib3d/src/usac/ransac_solvers.cpp
modules/core/src/dxt.cpp
modules/gapi/include/opencv2/gapi/render/render_types.hpp
modules/objdetect/src/qrcode.cpp

Fix issues found by static analysis

---

modules/calib3d/src/usac.hpp

calib3d: uninitialzed fields in usac

---

modules/videoio/src/cap_gstreamer.cpp

A running GMainLoop processes many events on the GLib/GStreamer world. While some things may work without it, many others won't. Examples of these are signals, timers and many other source events. The problem becomes more concerning by the fact that some GStreamer elements rely on signals to work. This PR allows the user to specify an OpenCV option to start a main loop, if needed. Since the loop blocks, this is done in a separate thread.
I've documented the example that motivated to push this [in this wiki](https://developer.ridgerun.com/wiki/index.php?title=RidgeRun_OpenCV_Fork#GStreamer_Main_Loop).

Allow a GMainLoop when capturing using GStreamer

---

modules/java/generator/gen_java.py

- the same generated code from Python2/3
- avoid randomized output due to unpredictable dict/set order
<cut/>
```
```

Java: robust code generation

---

samples/cpp/stitching.cpp

resolves #18807
<cut/>
- [+] I agree to contribute to the project under Apache 2 License.
- [+] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [+] The PR is proposed to proper branch
- [+] There is reference to original bug report and related work
- [+] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [+] The feature is well documented and sample code can be built with the project CMake

Changed sample code,  fixes #18807

---

modules/java/generator/gen_java.py

- support multi-level namespaces
- support inner classes (Params)
- reduce scope of 'using namespace' in JNI C++ code
```
opencv_contrib=text_drop_ambiguous_api
```

java: 'namespace_' class prefix, support inner classes

---

modules/objc/generator/gen_objc.py

- the same generated code from Python2/3
- avoid randomized output due to unpredictable dict/set order
relates #18798
/cc @komakai 
<cut/>
```
force_builders_only=docs,ios,Custom Mac
Xbuild_image:Custom Mac=osx_framework
build_contrib:Custom Mac=OFF
```

objc: robust code generation

---

modules/objc/generator/gen_objc.py

```
force_builders_only=docs,ios,Custom Mac
Xbuild_image:Custom Mac=osx_framework
build_contrib:Custom Mac=OFF
```

objc(test): repair binary resource files

---

modules/gapi/test/s11n/gapi_s11n_tests.cpp

Added ND GMatDesc serialization test

---

modules/objc/generator/gen_objc.py

objc: skip unsupported inner namespaces

---

modules/java/generator/gen_java.py

relates #18801
relates https://github.com/opencv/opencv_contrib/pull/2737

java: workaround handling of base class

---

modules/python/src2/gen2.py

resolves https://github.com/opencv/opencv_contrib/issues/2750
/cc @LaurentBerger

python: emit "string" => "std::string"

---

modules/dnn/src/graph_simplifier.cpp
modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/test/test_onnx_importer.cpp

relates: #16783
**merge with extra:** opencv/opencv_extra#804
Necessary changes for further work on supporting RCNN-like models from **torchvision**.
<cut/>
```
opencv_extra=multi_output_gather
```

Fix loading issue for Faster RCNN model from #16783

---

modules/core/include/opencv2/core/cv_cpu_dispatch.h
modules/core/include/opencv2/core/cvdef.h
modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/src/convert.simd.hpp
modules/core/test/test_intrin.cpp
modules/core/test/test_intrin_utils.hpp

resolves #18779
<cut/>
```
disable_ipp=ON
```

core: fix F16C compilation check

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/python/package/setup.py
platforms/android/build_sdk.py
platforms/android/service/readme.txt
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #18282
**WIP**

pre: OpenCV 3.4.13 (version++)

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/python/package/setup.py
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #18288

pre: OpenCV 4.5.1 (version++)

---

modules/core/include/opencv2/core.hpp
modules/highgui/include/opencv2/highgui.hpp
modules/imgcodecs/include/opencv2/imgcodecs.hpp

documentation improvement
ready to review
```
```

Documentation Improvement

---

modules/dnn/src/model.cpp
modules/dnn/test/test_model.cpp

Fixed Test_Model.DetectionOutput

---

modules/calib3d/include/opencv2/calib3d.hpp

Fixes #18837
[Demo page](http://pullrequest.opencv.org/buildbot/export/pr/18849/docs/d9/d0c/group__calib3d.html#ga59b0d57f46f8677fb5904294a23d404a) for this patch.
<cut/>

Minimum change to address issue #18837

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

my previous PR  #18708 closed itself!
resolves #18695
merge with extra https://github.com/opencv/opencv_extra/pull/816
<cut/>
```
opencv_extra=patch-1
Xforce_builders=Custom,Custom Win,Custom Mac
```

Fixing dnn Resize layer for variable input size

---

modules/calib3d/doc/calib3d.bib
modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/solvepnp.cpp
modules/calib3d/src/sqpnp.cpp
modules/calib3d/src/sqpnp.hpp
modules/calib3d/test/test_solvepnp_ransac.cpp

Added algorithm from "A Consistently Fast and Globally Optimal Solution to the Perspective-n-Point Problem" by G. Terzakis and M.Lourakis to SolvePnP. Based in part on the implementation from [terzakig/sqpnp](https://github.com/terzakig/sqpnp).
The [paper from ECCV2020](http://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123460460.pdf) argues that the method used produces state-of-the-art results without requiring a co-planar arrangement of points. Integration with the SolvePnP unit test suggests this claim is accurate.
The primary changes introduced by this pull request are:
- Addition of SQPnP algorithm
- Documentation corresponding to algorithm
- Integration with existing SolvePnP unit tests
System:
Windows 10 64-bit
Visual Studio 2019

Added SQPnP algorithm to SolvePnP

---

doc/tutorials/core/how_to_use_OpenCV_parallel_for_/how_to_use_OpenCV_parallel_for_.markdown

Fix typo in docs

---

modules/dnn/test/test_onnx_importer.cpp

dnn(test): skip unstable GatherMultiOutput OCL_FP16 test

---

platforms/apple/build_xcframework.py

Right now, if you build an xcframework and the destination xcframework path already exists, xcodebuild will throw an error complaining about this. This happens very late in the whole process, which is troublesome. This PR resolves this issue by deleting the xcframework if it already exists prior to building.

Delete xcframework if it already exists before building a new one

---

doc/tutorials/videoio/orbbec-astra/orbbec_astra.markdown
samples/cpp/tutorial_code/videoio/orbbec_astra/orbbec_astra.cpp

* Implemented frames pairing procedure in the code sample.
* Improved explanations in the tutorial.

Improve tutorial on using Orbbec Astra cameras

---

modules/core/src/system.cpp
modules/ts/src/ts.cpp

core(IPP): workaround getIppTopFeatures() value mismatch

---

modules/core/include/opencv2/core/mat.hpp

No any implementation.
resolves #18879

core(UMat): drop unavailable methods

---

modules/calib3d/include/opencv2/calib3d.hpp

Fixed minor typo "poins" in documentation page

---

modules/dnn/src/dnn.cpp

dnn: add another color to Net::Impl::dump()

---

platforms/apple/build_xcframework.py
platforms/js/opencv_js.config.py

Fixes https://github.com/opencv/opencv/issues/19017
relates #18940
```
```

Updated modules white list for JS after calib3d reorg

---

modules/gapi/include/opencv2/gapi/infer.hpp
modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/backends/ie/util.hpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

[G-API] Support GFrame for infer

---

modules/dnn/test/test_model.cpp

relates #17570
Error messages:
<cut/>
<details>
<summary>MYRIAD</summary>
```
[ RUN      ] Test_Model.TextDetectionByEAST/1, where GetParam() = NGRAPH/MYRIAD
/build/precommit_custom_linux/opencv/modules/dnn/test/test_model.cpp:258: Failure
The difference between box.center.x and gtBox.center.x is 4.37310791015625, which exceeds EPS_PIXELS, where
box.center.x evaluates to 661.923095703125,
gtBox.center.x evaluates to 657.54998779296875, and
EPS_PIXELS evaluates to 3.
/build/precommit_custom_linux/opencv/modules/dnn/test/test_model.cpp:260: Failure
The difference between box.size.width and gtBox.size.width is 18.09197998046875, which exceeds EPS_PIXELS, where
box.size.width evaluates to 298.74801635742188,
gtBox.size.width evaluates to 316.83999633789062, and
EPS_PIXELS evaluates to 3.
[ …
```

dnn(test): adjust EAST test tolerance

---

modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/test/test_backends.cpp

Failed [nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_halide-skl-lin64/builds/766).
relates #18862
```
build_image:Custom=halide:16.04
```

dnn: fix build with Halide, skip tests with crashes

---

modules/features2d/test/test_nearestneighbors.cpp
modules/flann/include/opencv2/flann/miniflann.hpp
modules/flann/src/miniflann.cpp

resolves #17553
Fix is targeted to the "master" (4.x) branch due to limitation of ABI support.
Fix for 3.4 would be larger (probably won't fix).

flann: avoid dangling pointers on lost features data

---

modules/features2d/src/orb.cpp
modules/features2d/test/test_orb.cpp

resolves #16197
relates #10690
- height must be handled too

features2d: fix ORB::setFirstScale() handling

---

modules/core/src/convert.dispatch.cpp
modules/core/src/opencl/halfconvert.cl
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp
modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp
modules/dnn/src/opencl/conv_spatial_helper.cl

relates #18465
/cc @tomoaki0705

DNN(OpenCL): avoid mess FP16/FP32 in convolution layer

---

modules/core/src/ocl.cpp
modules/dnn/src/ocl4dnn/src/math_functions.cpp
modules/dnn/src/opencl/gemm_buffer.cl
modules/dnn/test/test_onnx_importer.cpp

- dst is not initialized, may include NaN values
- 0*NaN produces NaN
fixes #18937
relates #11397

DNN(OpenCL): fix GEMM kernels with beta=0

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/streaming/format.hpp

```
test_modules:Custom=gapi,python2
```

Included format in core.hpp

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/gcommon.hpp
modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/include/opencv2/gapi/infer/parsers.hpp

G-API: Fix various Doxygen isses for the 4.5.1 release

---

modules/imgproc/src/clahe.cpp
modules/imgproc/src/imgwarp.cpp
modules/imgproc/src/pyramids.cpp

Move big objects (>20k) from stack to heap.

---

cmake/OpenCVDetectInferenceEngine.cmake
modules/dnn/perf/perf_net.cpp
modules/dnn/src/op_inf_engine.hpp
modules/dnn/test/test_darknet_importer.cpp

dnn: use OpenVINO 2021.2 defines

---

modules/gapi/test/common/gapi_core_tests_inl.hpp

Fixes: https://github.com/opencv/opencv/issues/19117

arm64 fix: Replaced float value strong equal checks with check with tolerance

---

modules/imgproc/src/color.hpp

Added YUV conversion fix

---

platforms/winpack_dldt/2021.2/20200413-dldt-pdb.patch
platforms/winpack_dldt/2021.2/20200604-dldt-disable-multidevice.patch
platforms/winpack_dldt/2021.2/20201217-dldt-disable-unused-targets.patch
platforms/winpack_dldt/2021.2/20201218-dldt-vs-version.patch
platforms/winpack_dldt/2021.2/build.config.py
platforms/winpack_dldt/2021.2/patch.config.py
platforms/winpack_dldt/2021.2/sysroot.config.py
platforms/winpack_dldt/build_package.py

https://github.com/openvinotoolkit/openvino/releases/tag/2021.2
relates #16847 #17056 #17466 #17759 #18534
Preview packages:
- [3.4 branch](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_custom_windows/20201218-075109--1773/)
- [master branch](http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_custom_windows/20201218-065939--1772/)
<cut/>
```
```

Build OpenCV winpack with DLDT 2021.2.0

---

doc/js_tutorials/js_setup/js_setup/js_setup.markdown
modules/js/generator/embindgen.py
platforms/js/opencv_js.config.py

(3.4) JavaScript: backport PR #18985

---

modules/core/include/opencv2/core/vsx_utils.hpp

Fix comment typos.

---

modules/flann/include/opencv2/flann/all_indices.h
modules/flann/include/opencv2/flann/autotuned_index.h
modules/flann/include/opencv2/flann/composite_index.h
modules/flann/include/opencv2/flann/flann_base.hpp
modules/flann/include/opencv2/flann/general.h
modules/flann/include/opencv2/flann/hierarchical_clustering_index.h
modules/flann/include/opencv2/flann/index_testing.h
modules/flann/include/opencv2/flann/kdtree_index.h
modules/flann/include/opencv2/flann/kdtree_single_index.h
modules/flann/include/opencv2/flann/kmeans_index.h
modules/flann/include/opencv2/flann/linear_index.h
modules/flann/include/opencv2/flann/lsh_index.h
modules/flann/include/opencv2/flann/matrix.h
modules/flann/include/opencv2/flann/nn_index.h
modules/flann/include/opencv2/flann/params.h
modules/flann/include/opencv2/flann/random.h
modules/flann/include/opencv2/flann/saving.h
modules/flann/src/precomp.hpp

Replace FLANNException by CV_Error.

---

modules/imgproc/src/intersection.cpp
modules/imgproc/test/test_intersection.cpp

imgproc: add rotatedRectangleIntersection empty input handling

---

modules/core/include/opencv2/core/mat.hpp

docs(core): fix process_video_frame() code snippet

---

doc/tutorials/introduction/config_reference/config_reference.markdown

relates #18195
- [Old page](https://docs.opencv.org/4.5.1/db/d05/tutorial_config_reference.html)

docs(build config): fix table cells

---

modules/videoio/src/backend_plugin.cpp
modules/videoio/src/cap_ffmpeg.cpp
modules/videoio/src/cap_gstreamer.cpp
modules/videoio/src/cap_mfx_plugin.cpp
modules/videoio/src/cap_msmf.cpp
modules/videoio/src/cap_ueye.cpp
modules/videoio/src/plugin_api.hpp

Revised support for plugin API versioning.
**RFC**
/cc @mshabunin @asmorkalov @joshdoe
Thanks for looking at these and providing feedback.
<cut/>
To be merged after the current release.

videoio: plugins API versioning

---

modules/core/test/test_opencl.cpp

OpenCL: parametrize OpenCLExecutionContext tests

---

modules/dnn/src/tensorflow/tf_importer.cpp

dnn: improve debugging of TensorFlow parsing errors

---

README.md

update forum link

---

doc/js_tutorials/js_setup/js_usage/js_usage.markdown

docs(tutorial_js_usage): fix imshow usage

---

modules/core/include/opencv2/core/hal/intrin_wasm.hpp

<cut/>
```
force_builders=linux,docs,Custom
```

Inlined WASM fallback intrinsics to avoid using of V_TypeTraits

---

samples/python/tutorial_code/video/background_subtraction/bg_sub.py

https://github.com/opencv/opencv/issues/19299

docs: hotfix: call isOpened() in python bg sub tutorial

---

samples/dnn/person_reid.cpp
samples/dnn/person_reid.py

Hi, this is a sample of person ReIDentification. 
This sample uses one of the state-of-the-art ReID models built by Tencent YoutuLab. 
Currently there are a python script and a Cpp script with the same features, both supportting extracting ReID feature with youtu baseline ReID model. 
<cut/>
This sample takes two sets of images as input, namely the query set and gallery set. 
This sample first load the onnx model of youtu ReID baseline and then extract the ReID feature of all images in the query and gallery set. 
For each query image, the gallery images are ranked based on its consine similarity with the query image. 
Finally the ranking list is visualized in an output folder. 
Following is the example of the visualization results. The first image of each row is the query, and the rest is …

All person ReIDentification samples.

---

modules/gapi/src/executor/gasync.cpp

relates #19020 (problem is reduced, but it is not fixed)
relates #14346

gapi(async): use lazy-initialization of async_service singleton

---

modules/highgui/src/window_w32.cpp

fix typo of the word storage

---

.github/ISSUE_TEMPLATE.md
doc/py_tutorials/py_setup/py_intro/py_intro.markdown
doc/tutorials/introduction/android_binary_package/O4A_SDK.markdown
doc/tutorials/introduction/android_binary_package/android_dev_intro.markdown
doc/tutorials/introduction/android_binary_package/dev_with_OCV_on_Android.markdown
doc/tutorials/introduction/windows_install/windows_install.markdown
modules/videoio/src/cap_libv4l.cpp
modules/videoio/src/cap_v4l.cpp
samples/cpp/stereo_calib.cpp

Updated links to forum.opencv.org

---

.github/ISSUE_TEMPLATE.md
doc/py_tutorials/py_setup/py_intro/py_intro.markdown
doc/tutorials/introduction/android_binary_package/O4A_SDK.markdown
doc/tutorials/introduction/android_binary_package/android_dev_intro.markdown
doc/tutorials/introduction/android_binary_package/dev_with_OCV_on_Android.markdown
doc/tutorials/introduction/windows_install/windows_install.markdown
modules/videoio/src/cap_v4l.cpp
samples/cpp/stereo_calib.cpp

Ported #19352 to _master_ branch.

Updated more links to forum.opencv.org (master)

---

modules/videoio/test/test_video_io.cpp

Related work: https://github.com/opencv/opencv/pull/18377

VideoCapture test to ensure that cv::VideoCapture does not share output buffers

---

doc/js_tutorials/js_setup/js_setup/js_setup.markdown

JavaScript(documentation): fix path

---

samples/dnn/dasiamrpn_tracker.cpp

Hi,  This is DaSiamRPN tracker with C++ version. The model used in this example is the same as [PR18033](https://github.com/opencv/opencv/pull/18033).
```
Xforce_builders_only=docs,linux,win64
```

Add DaSiamRPN tracker sample of c++ version

---

doc/tutorials/app/orbbec_astra.markdown
samples/cpp/tutorial_code/videoio/orbbec_astra/orbbec_astra.cpp

Small corrections to Orbbec Astra cameras tutorial

---

modules/cudalegacy/test/test_calib3d.cpp

fix peaky test failure

---

modules/core/src/ocl.cpp

- reuse g_isOpenCLAvailable variable instead
relates #19133
relates #10180

core(OpenCL): update isOpenCLActivated()

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves: #19359
merge with extra opencv/opencv_extra#837
<cut/>
```
```

Fixed bug with constant Div

---

modules/dnn/src/tensorflow/tf_importer.cpp

resolves: #18479
<cut/>
```
```

Added shared weights for MatMul

---

modules/python/test/test.py

fix python test runner wildcard handling

---

modules/core/include/opencv2/core/utils/tls.hpp
modules/python/src2/cv2.cpp

resolves #19426
/cc @xiedeacc
Validation: `cmake -DENABLE_IMPL_COLLECTION=ON -DENABLE_INSTRUMENTATION=ON ...`, target `opencv_python3`

build: fix cv2.cpp compilation

---

modules/core/include/opencv2/core/hal/intrin_wasm.hpp

relates #19216
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4_javascript-simd-emscripten-lin64/builds/449).
```
buildworker:Custom=linux-6
build_image:Custom=javascript-simd
```

JavaScript: fix SIMD build

---

modules/imgproc/doc/colors.markdown

Resolves https://github.com/opencv/opencv/issues/19406

Fix error in documentation for RGB->HSV convertion

---

modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/include/opencv2/imgproc/bindings.hpp
modules/imgproc/misc/objc/gen_dict.json
modules/python/test/test_houghlines.py

Return accumulator value in HoughLines algorithm

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

resolves #18247
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/844
```
opencv_extra=tf-leakyrelu
```

DNN: Add LeakyReLU to TensorFlow Importer

---

modules/highgui/include/opencv2/highgui.hpp
modules/highgui/src/window.cpp
modules/highgui/src/window_QT.cpp
modules/highgui/src/window_cocoa.mm
modules/highgui/src/window_gtk.cpp
modules/highgui/src/window_w32.cpp
modules/highgui/src/window_winrt.cpp

first code proposal for #19410
```
force_builders=Win32,Custom
```

pollKey implementation for w32 backend of highgui

---

doc/js_tutorials/js_imgproc/js_intelligent_scissors/js_intelligent_scissors.markdown

relates #19194
Merge after https://github.com/openvinotoolkit/cvat/pull/2689
[Page](http://pullrequest.opencv.org/buildbot/export/pr/19422/docs/d9/df5/tutorial_js_intelligent_scissors.html)
<cut/>
```
linter_checks=check_pylint
```

js(tutorial): add note about CVAT integration

---

modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/normalize_bbox_layer.cpp
modules/dnn/src/layers/scale_layer.cpp

Switched to v1 Multiply

---

samples/cpp/tutorial_code/ImgTrans/imageSegmentation.cpp
samples/python/tutorial_code/ImgTrans/distance_transformation/imageSegmentation.py

Update imageSegmentation.cpp, imageSegmentation.py

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/misc/python/test/test_dnn.py

fix #19346
fix #19481
original opinion by @mikr. thanks! https://github.com/opencv/opencv/issues/19346#issue-788394632

[dnn] fix high level api for python

---

cmake/OpenCVDetectTBB.cmake

hotfix #19456
Message:
```
c++: error: __TBB_NO_IMPLICIT_LINKAGE=1: No such file or directory
```

cmake: use INTERFACE_COMPILE_DEFINITIONS

---

modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/backends/ie/giebackend.hpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

[G-API] Implement async infer

---

cmake/android/android_gradle_projects.cmake
platforms/android/gradle-wrapper/gradle/wrapper/gradle-wrapper.properties.in
platforms/android/ndk-22.config.py

Fix Android NDK 22 build error

---

modules/gapi/include/opencv2/gapi/render/render.hpp
modules/gapi/src/api/render.cpp
modules/gapi/src/backends/render/grenderocv.cpp
modules/gapi/test/common/gapi_render_tests.hpp
modules/gapi/test/render/gapi_render_tests_ocv.cpp

- [x ] I agree to contribute to the project under Apache 2 License.
- [x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x ] The PR is proposed to proper branch
``` …
```

Render Frame NV12 on CPU

---

doc/tutorials/imgproc/pyramids/pyramids.markdown

docs(tutorial_pyramids): Fix typo under "Perform downsampling" subsection

---

samples/dnn/tf_text_graph_common.py

Corrected SSD text graph generation for Identity nodes

---

modules/cudafilters/src/cuda/median_filter.cu

Follow up of #12721
There are still some race condition in [median_filter.cu](https://github.com/opencv/opencv/blob/fa8684b5c8267f1c0c89f6279b9b0ff87500480c/modules/cudafilters/src/cuda/median_filter.cu#L130-L137
)
https://github.com/opencv/opencv/blob/fa8684b5c8267f1c0c89f6279b9b0ff87500480c/modules/cudafilters/src/cuda/median_filter.cu#L130-L137
Though I inserted `__syncthreads()` between the lines, the operation `+=` does both read and write.
This causes a race condition
```
```

cudafilters: remove danger race condition

---

modules/core/include/opencv2/core/utils/plugin_loader.private.hpp

plugins: use RTLD_NOW instead of RTLD_LAZY

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/cuda/activations.cu
modules/dnn/src/cuda/functors.hpp
modules/dnn/src/cuda4dnn/kernels/activations.hpp
modules/dnn/src/cuda4dnn/primitives/activation.hpp
modules/dnn/src/init.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/opencl/activations.cl
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_onnx_importer.cpp

Based on Caffe's [Exponential Layer](https://caffe.berkeleyvision.org/tutorial/layers/exp.html).
resolves: #19475 #18088 
merge with extra: opencv/opencv_extra#853
<cut/>
```
build_image:Custom Win=openvino-msvs2019-2021.2.0
Xbuildworker:Custom=linux-4,linux-6 …
```

DNN : Add Exp layer

---

samples/python/houghcircles.py
samples/python/tutorial_code/Histograms_Matching/back_projection/calcBackProject_Demo1.py
samples/python/tutorial_code/Histograms_Matching/back_projection/calcBackProject_Demo2.py
samples/python/tutorial_code/Histograms_Matching/histogram_calculation/calcHist_Demo.py
samples/python/tutorial_code/TrackingMotion/corner_subpixels/cornerSubPix_Demo.py
samples/python/tutorial_code/TrackingMotion/good_features_to_track/goodFeaturesToTrack_Demo.py
samples/python/tutorial_code/ml/introduction_to_svm/introduction_to_svm.py
samples/python/tutorial_code/ml/non_linear_svms/non_linear_svms.py
samples/python/tutorial_code/ml/py_svm_opencv/hogsvm.py
samples/python/tutorial_code/video/optical_flow/optical_flow.py
samples/python/tutorial_code/videoio/video-input-psnr-ssim.py

Update python samples

---

modules/dnn/src/layers/proposal_layer.cpp

resolves #19600
relates #19536

dnn: fix build (nullptr issue)

---

modules/core/include/opencv2/core/cvdef.h
modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/mat.inl.hpp
modules/core/src/matrix_wrap.cpp
modules/core/test/test_mat.cpp

resolves #18897
relates #8535
relates #17046

core(InputArray): replace STD_ARRAY to MATX

---

modules/core/misc/java/test/MatTest.java
modules/java/generator/src/cpp/Mat.cpp
modules/java/test/android_test/src/org/opencv/test/OpenCVTestCase.java
modules/java/test/pure_test/src/org/opencv/test/OpenCVTestCase.java

Fix bug in put/get of non-continuous Mat

---

modules/calib3d/src/sqpnp.hpp
modules/dnn/src/layers/pooling_layer.cpp
modules/videoio/src/cap_msmf.cpp

Fixed several issues found by static analysis (backported)

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/init.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/opencl/activations.cl
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/858
backport #19545
partial backport #19620

(3.4) Added exp layer (backport 19545)

---

modules/videoio/src/cap_ffmpeg_impl.hpp

Warnings example: [no-fix](http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/28577) / [partial fix](http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/28580)
<cut/>
```
build_image:Custom Win=ffmpeg-plugin
buildworker:Custom Win=windows-2
test_modules:Custom Win=videoio,python3,java
Xbuild_image:Win64=ffmpeg-plugin-msvs2015
Xbuildworker:Win64=windows-2
Xtest_opencl:Win64=ON
buildworker:Win64 OpenCL=windows-1
```

(3.4) videoio: ffmpeg fixes

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/python/package/setup.py
platforms/android/build_sdk.py
platforms/android/service/readme.txt
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #18824

pre: OpenCV 3.4.14 (version++)

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/version.hpp
modules/python/package/setup.py
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #18825

pre: OpenCV 4.5.2 (version++)

---

modules/dnn/src/ie_ngraph.cpp

Determine layout

---

modules/calib3d/src/calibinit.cpp
modules/calib3d/src/checkchessboard.cpp
modules/calib3d/src/circlesgrid.cpp
modules/core/src/system.cpp
modules/imgproc/src/subdivision2d.cpp

Local objects optimization in calibration init

---

samples/dnn/virtual_try_on.py

Removed unused variables found by pylint

---

doc/tutorials/app/video_write.markdown
modules/videoio/doc/videoio_overview.markdown
modules/videoio/include/opencv2/videoio.hpp
modules/videoio/include/opencv2/videoio/doc/hwaccel.doc.hpp
samples/cpp/videocapture_gstreamer_pipeline.cpp

videoio(doc): add 'videoio_hwaccel' group

---

modules/stitching/include/opencv2/stitching.hpp
modules/stitching/src/stitcher.cpp
modules/stitching/test/test_stitcher.cpp

resolves https://github.com/opencv/opencv/issues/18459

get and set cameras on stitcher

---

modules/gapi/include/opencv2/gapi/media.hpp
modules/gapi/src/api/media.cpp
modules/gapi/src/backends/ie/giebackend.cpp

``` 
// disabled due high memory usage: test_opencl:Custom=ON …
```

Upstream fixes from release

---

modules/dnn/src/layers/mvn_layer.cpp
modules/dnn/src/layers/resize_layer.cpp

Added ngraph::op::v4::Interpolation

---

modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/mat.inl.hpp
modules/core/src/matrix.cpp
modules/core/src/umatrix.cpp

(3.4) noexcept def construct Mat, UMat, Mat_, MatSize, MatStep

---

doc/js_tutorials/js_setup/js_setup/js_setup.markdown
modules/js/CMakeLists.txt
modules/js/generator/embindgen.py
modules/js/test/test_objdetect.js
platforms/js/build_js.py
platforms/js/opencv_js.config.py

This PR adds javascript support for the class QRCodeDetector.
Tests for the proposed functions are derived from the equivalent python tests.
Because sample images are needed for running the tests, the build of the tests
requires now the opencv_extra repository.
(Alternatively i could copy some test images into the tutorial folder and use
them in the tests)
Due to emscripten limitations the functions _decodeMulti_ and
_detectAndDecodeMulti_ are excluded.
As far as i know it is not possible to use a function parameter (string array)
to return the decoded content of the QR codes.
``` …
```

Add QRCodeDetector to JavaScript Build

---

doc/js_tutorials/js_setup/js_setup/js_setup.markdown
modules/calib3d/src/solvepnp.cpp
modules/calib3d/src/stereobm.cpp
modules/calib3d/src/stereosgbm.cpp
modules/calib3d/test/test_solvepnp_ransac.cpp
modules/core/include/opencv2/core/fast_math.hpp
modules/core/include/opencv2/core/vsx_utils.hpp
modules/core/src/system.cpp
modules/core/test/ocl/test_opencl.cpp
modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/src/layers/mvn_layer.cpp
modules/dnn/src/layers/resize_layer.cpp
modules/dnn/src/nms.inl.hpp
modules/js/generator/embindgen.py
modules/js/test/test_objdetect.js
platforms/js/build_js.py
platforms/js/opencv_js.config.py
samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp
samples/dnn/virtual_try_on.py

#19253 from mightbxg:bugfix_PnPRansac
#19284 from Ziachnix:feature/js-qr-code-detector
#19613 from WeiChungChang:NMS_refine
#19675 from asmorkalov:as/pylint_warnings
#19685 from danbey:setting_stereoBMImpl_in_init_list
~~#19687 from alalek:videoio_docs_fixes_3.4~~
#19690 from hedgepigdaniel:fix/calibration_fisheye
#19692 from seiko2plus:issue_19647
#19703 from danbey:setting_StereoSGBMParams_in_init_list
#19715 from seiko2plus:issue_19698
#19716 from l-bat:lb/fix_resize
#19717 from danbey:bad_value_param_should_be_passed_by_reference
~~#19718 from alalek:backport_19683~~
#19720 from alalek:ocl_test_skip_spir_amd
Previous "Merge 3.4": #19686
<cut/>
<details>
```
#buildworker:Custom=linux-1,linux-2,linux-4,linux-6 …
```

(4.x) Merge 3.4

---

modules/features2d/include/opencv2/features2d.hpp
modules/features2d/src/mser.cpp

features2d(MSER): chi_table.h notes

---

modules/core/CMakeLists.txt
modules/core/src/parallel/parallel.cpp
modules/core/src/parallel/registry_parallel.impl.hpp

resolves #19733
relates #19470
```
```

core(parallel): fix plugins handling if no filesystem available

---

cmake/OpenCVDetectInferenceEngine.cmake
modules/dnn/src/op_inf_engine.hpp
modules/dnn/test/test_common.hpp
modules/dnn/test/test_common.impl.hpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

relates #19146
<cut/>
```
#YOLO*:*VINO*:*Infer*:*Layer*:*layer*
```

dnn: use OpenVINO 2021.3 defines

---

modules/gapi/include/opencv2/gapi/infer.hpp
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/python_bridge.hpp
modules/gapi/misc/python/shadow_gapi.hpp
modules/gapi/misc/python/test/test_gapi_core.py
modules/gapi/misc/python/test/test_gapi_infer.py

[G-API] Python ROI generic inference

---

modules/gapi/test/streaming/gapi_streaming_tests.cpp

Fixes https://github.com/opencv/opencv/issues/19800
* Moved std::functions from test parameters to function tables as valgrind complains on google tests trying to print std::functions
<cut/>
``` …
```

G-API: Fixed valgrind warnings in accessors tests

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/include/opencv2/gapi/python/python.hpp
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/test/test_gapi_sample_pipelines.py
modules/gapi/misc/python/test/test_gapi_streaming.py
modules/gapi/src/backends/python/gpythonbackend.cpp
modules/python/src2/cv2.cpp

[G-API] Python backend

---

doc/Doxyfile.in
modules/core/include/opencv2/core/hal/intrin.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/src/matrix_transform.cpp
modules/core/test/test_intrin_utils.hpp
modules/dnn/src/layers/convolution_layer.cpp

```
force_builders=Linux AVX2,linux,docs,Custom
```

Updated UI documentation to address WUI

---

modules/gapi/include/opencv2/gapi/garray.hpp
modules/gapi/include/opencv2/gapi/gmat.hpp
modules/gapi/include/opencv2/gapi/gopaque.hpp
modules/gapi/include/opencv2/gapi/gscalar.hpp
modules/gapi/include/opencv2/gapi/own/exports.hpp
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/python_bridge.hpp
modules/gapi/misc/python/shadow_gapi.hpp
modules/gapi/misc/python/test/test_gapi_sample_pipelines.py
modules/gapi/src/backends/python/gpythonbackend.cpp
modules/python/src2/cv2.cpp
modules/python/src2/hdr_parser.py

[G-API] Introduce custom python operator API

---

modules/videoio/src/cap_avfoundation.mm
modules/videoio/src/cap_avfoundation_mac.mm

videoio(avfoundation): add getCaptureDomain()

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/cpu/stereo.hpp
modules/gapi/include/opencv2/gapi/stereo.hpp
modules/gapi/src/api/kernels_stereo.cpp
modules/gapi/src/backends/cpu/gcpustereo.cpp
modules/gapi/test/common/gapi_stereo_tests.cpp
modules/gapi/test/common/gapi_stereo_tests.hpp
modules/gapi/test/common/gapi_stereo_tests_inl.hpp
modules/gapi/test/cpu/gapi_stereo_tests_cpu.cpp

G-API Stereo operation and tests

---

modules/python/src2/cv2.cpp
modules/python/src2/gen2.py
modules/python/src2/hdr_parser.py
modules/python/src2/pycompat.hpp

No semantic changes on 3.4 / master branches.
Required to properly support this PR: https://github.com/opencv/opencv_contrib/pull/2882

python: fix CV_WRAP_AS handling

---

modules/core/src/arithm.cpp
modules/core/test/test_operations.cpp

core(arithm_op): workaround problem with scalars handling

---

modules/videoio/src/cap_mjpeg_encoder.cpp

videoio(mjpeg): disable parallel encoder

---

modules/python/src2/cv2.cpp
modules/python/src2/gen2.py

python: exception-free pyopencv_to() wrapper

---

modules/js/generator/CMakeLists.txt
modules/js/perf/base.js
modules/js/perf/perf_helpfunc.js
modules/js/perf/perf_imgproc/perf_blur.js
modules/js/perf/perf_imgproc/perf_cvtcolor.js
modules/js/perf/perf_imgproc/perf_dilate.js
modules/js/perf/perf_imgproc/perf_erode.js
modules/js/perf/perf_imgproc/perf_filter2D.js
modules/js/perf/perf_imgproc/perf_gaussianBlur.js
modules/js/perf/perf_imgproc/perf_medianBlur.js
modules/js/perf/perf_imgproc/perf_pyrDown.js
modules/js/perf/perf_imgproc/perf_remap.js
modules/js/perf/perf_imgproc/perf_resize.js
modules/js/perf/perf_imgproc/perf_scharr.js
modules/js/perf/perf_imgproc/perf_sobel.js
modules/js/perf/perf_imgproc/perf_threshold.js
modules/js/perf/perf_imgproc/perf_warpAffine.js
modules/js/perf/perf_imgproc/perf_warpPerspective.js

resolves #19754
This is a Pull Request for the Issue 19754
For the perf tests in OpenCV.js, the scripts can not run successfully on Node.js. In this PR, I modify the scripts in perf tests so that the functions imported from other modules can run successfully in perf tests.
<cut/>
```
```

Solves #19754

---

modules/gapi/cmake/DownloadADE.cmake

cmake: fix ADE dependency handling

---

modules/core/include/opencv2/core/hal/intrin.hpp

backport changes from #19821
relates #18952

core: backward compatibility for vx_store/vx_store_aligned calls

---

modules/js/perf/base.js
modules/js/perf/perf_helpfunc.js
modules/js/perf/perf_imgproc/perf_blur.js
modules/js/perf/perf_imgproc/perf_cvtcolor.js
modules/js/perf/perf_imgproc/perf_dilate.js
modules/js/perf/perf_imgproc/perf_erode.js
modules/js/perf/perf_imgproc/perf_filter2D.js
modules/js/perf/perf_imgproc/perf_gaussianBlur.js
modules/js/perf/perf_imgproc/perf_medianBlur.js
modules/js/perf/perf_imgproc/perf_pyrDown.js
modules/js/perf/perf_imgproc/perf_remap.js
modules/js/perf/perf_imgproc/perf_resize.js
modules/js/perf/perf_imgproc/perf_scharr.js
modules/js/perf/perf_imgproc/perf_sobel.js
modules/js/perf/perf_imgproc/perf_threshold.js
modules/js/perf/perf_imgproc/perf_warpAffine.js
modules/js/perf/perf_imgproc/perf_warpPerspective.js

- to run with Node.js
backport #19771
relates #19754
```
```

(3.4) fix the perf tests of OpenCV.js

---

modules/videoio/src/cap_dshow.cpp

videoio(dshow): add NULL ptr check

---

modules/cudaarithm/src/core.cpp

resolves https://github.com/opencv/opencv_contrib/issues/2895
```
```

cuda: fix inplace condition in cv::cuda::flip

---

modules/imgproc/src/imgwarp.cpp

delete unused variable

---

doc/tutorials/introduction/linux_install/linux_install.markdown

Small changes in the warning text of the installation process :)

Update text in linux_install.markdown

---

modules/ml/src/boost.cpp
modules/ml/src/tree.cpp

relates #19884 #3032 #3537
```
test_modules_force=text
```

ML: fix legacy import in DTreesImpl

---

modules/ml/src/rtrees.cpp
modules/ml/src/tree.cpp

ML: update checks

---

modules/calib3d/src/usac/ransac_solvers.cpp

calib3d: fix masks for usac

---

modules/imgproc/test/test_houghcircles.cpp
samples/cpp/calibration.cpp
samples/cpp/digits_svm.cpp
samples/cpp/select3dobj.cpp
samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp
samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/main_detection.cpp
samples/tapi/ufacedetect.cpp

Resolves: https://github.com/opencv/opencv/issues/19941.

Add namespace specifier for format()

---

modules/gapi/include/opencv2/gapi/infer/ie.hpp
modules/gapi/samples/face_detection.cpp

G-API MTCNN sample

---

doc/Doxyfile.in

doxygen: fix quotes in add_toggle macro

---

samples/python/stitching_detailed.py

There are two issues with the code in the tutorial:
1. Vertical wave correction isn't supported but proposed as parameter to the user
2. Changing the confidence threshold isn't supported but proposed as parameter to the user
Both are because of static implementations instead of using the user defined parameters.
Please see the commit descriptions for details.
This Pull request solves both Issues.

Stitching Detailed Tutorial Improvements

---

cmake/OpenCVDownload.cmake

Fix typo: 'DOWNLAOD' to 'DOWNLOAD'

---

modules/dnn/src/ie_ngraph.cpp

resolves #18723
relates https://github.com/openvinotoolkit/openvino/pull/2871
<cut/>
```
```

DNN(IE): implicit usage of IE::GPU OpenCL kernels cache

---

CMakeLists.txt

no system libs required for linking in QNX

Enable QNX build

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp

Document imwrite depth fallback

---

samples/dnn/dnn_model_runner/dnn_conversion/paddlepaddle/README.md
samples/dnn/dnn_model_runner/dnn_conversion/requirements.txt

Update `requirements.txt` and `README.md` for PaddlePaddle model conversion case.

Update requirements and README for PaddlePaddle sample

---

modules/gapi/samples/face_detection.cpp

G-API MTCNN demo hotfix to align overall pipeline accuracy with the reference Python code output.

---

modules/calib3d/src/solvepnp.cpp
modules/calib3d/src/usac/ransac_solvers.cpp
modules/calib3d/test/test_usac.cpp

#20008
Bugfix https://github.com/opencv/opencv/issues/20008

fix inliers in solvePnPRansac

---

modules/world/CMakeLists.txt

One of two PRs to fix #19386
The second one is https://github.com/opencv/opencv_contrib/pull/2951

vtk 9.0 autoinit fix

---

CMakeLists.txt

The option as been moved away from python-related options.

[build] Move `OPENCV_DISABLE_FILESYSTEM_SUPPORT`. [NFC]

---

modules/highgui/src/window_QT.cpp
modules/highgui/src/window_winrt_bridge.cpp

highgui: fix trackbar value pointer handling

---

modules/objdetect/src/hog.cpp
modules/objdetect/test/opencl/test_hogdetector.cpp

Fixes https://github.com/opencv/opencv/issues/20131

Accurate HOG initialization with and without SVM

---

modules/gapi/samples/face_detection_mtcnn.cpp

Remove custom transpose kernel from MTCNN sample

---

doc/tutorials/introduction/config_reference/config_reference.markdown
doc/tutorials/introduction/general_install/general_install.markdown

* Added standalone plugin build description to the general installation tutorial.
* Updated some options in the config reference tutorial

docs/tutorials: improve plugin sections

---

modules/highgui/src/window_gtk.cpp

Fixing https://github.com/opencv/opencv/issues/20141

Round fix in OnMouse

---

modules/videoio/src/cap_dshow.cpp

videoio(dshow) fix memory leak

---

samples/wp8/OcvImageManipulation/PhoneXamlDirect3DApp1/PhoneXamlDirect3DApp1/App.xaml.cs
samples/wp8/OcvRotatingCube/PhoneXamlDirect3DApp1/PhoneXamlDirect3DApp1/App.xaml.cs
samples/wp8/OpenCVXaml/OpenCVXaml/App.xaml.cs

wp8 samples typos (3.4)

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/python/package/setup.py
platforms/android/build_sdk.py
platforms/android/service/readme.txt
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #19656

pre: OpenCV 3.4.15 (version++)

---

modules/highgui/src/window_gtk.cpp

(4.x) highgui(GTK): fix NULL ptr checks

---

modules/highgui/src/window_gtk.cpp

(3.4) highgui(GTK): fix NULL ptr checks

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/version.hpp
modules/python/package/setup.py
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #19657

pre: OpenCV 4.5.3 (version++)

---

modules/core/misc/objc/common/MatExt.swift
modules/core/misc/objc/test/MatTest.swift

In response to comment here
https://github.com/opencv/opencv/pull/17165#issuecomment-708878645
I created a function like "at" for the Swift binding.
---
<cut/>
```
force_builders=docs,ios,Custom Mac
buildworker:Custom Mac=macosx-1
```

Swift at function

---

CMakeLists.txt
cmake/android/android_gradle_projects.cmake
modules/core/misc/java/src/java/core+Mat.java
modules/core/misc/java/src/java/core+MatAt.kt
modules/core/misc/java/test/MatTest.java
modules/java/android_sdk/android_gradle_lib/build.gradle
modules/java/android_sdk/build.gradle.in
modules/java/generator/gen_java.py
modules/java/test/pure_test/src/org/opencv/test/OpenCVTestCase.java
platforms/android/build_sdk.py
platforms/android/ndk-22.config.py
samples/android/build.gradle.in

A function like "at" for Java/Kotlin (partner to #20220 )
Includes some Kotlin extensions (Android only) to allow you do cool things like:
```
val (b, g, r) = lena.at<UByte>(10, 10).v3c
```
Also includes ability to disable Kotlin extensions for anyone that doesn't want them
<cut/>
```
```

Java at function

---

modules/gapi/samples/face_detection_mtcnn.cpp

Hot fix negative MTCNN PNet ROI coordinates

---

modules/core/include/opencv2/core/types_c.h

core: fix nSize initialization in cvIplImage()

---

modules/python/package/cv2/__init__.py

/cc @TolyaTalamanov 
see also #13779

python(loader): add workaround to detect and patch sys.path[0]

---

modules/dnn/src/tensorflow/tf_importer.cpp

Split up layer dispatch of Tensorflow importer into map of functions

---

modules/highgui/src/window.cpp

Fixes https://github.com/opencv/opencv/issues/20090

Reorder defined checks in pollKey according to cmake file

---

modules/calib3d/test/test_undistort.cpp

Added new unit test for cv::initInverseRectificationMap()
Replaces unit test from #20165 and completes the updating of cv::initInverseRectificationMap() started in #20247

Added new unit test for cv::initInverseRectificationMap()

---

modules/core/include/opencv2/core/utils/filesystem.private.hpp

As per comment https://github.com/opencv/opencv/pull/20010#commitcomment-51027021

Reenable filesystem for ios builds

---

apps/model-diagnostics/model_diagnostics.cpp
modules/dnn/src/tensorflow/tf_importer.cpp

TF importer diagnostic mode

---

modules/core/src/persistence.cpp
modules/core/test/test_io.cpp

resolves #20279
relates #13011
relates #12570
relates #12463

core(persistence): fix types format handling, fix 16F support

---

modules/core/src/persistence.cpp

(3.4) core(persistence): fix types format handling

---

cmake/OpenCVDetectInferenceEngine.cmake
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/op_inf_engine.hpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_ie_models.cpp
modules/dnn/test/test_torch_importer.cpp

https://github.com/openvinotoolkit/openvino/releases/tag/2021.4
previous update #19770
```
YOLO*:*VINO*:*Infer*:*Layer*:*layer*
```

dnn: use OpenVINO 2021.4 defines

---

samples/python/camera_calibration_show_extrinsics.py
samples/python/gaussian_mix.py
samples/python/hist.py
samples/python/lk_homography.py
samples/python/lk_track.py
samples/python/video_v4l2.py

This PR fixes errors on Windows in some samples on 3.4 branch
backport #20326

Fix samples 3.4

---

modules/gapi/include/opencv2/gapi/streaming/format.hpp
modules/gapi/misc/python/samples/gaze_estimation.py

Gaze Estimation sample based on GAPI Python api.
``` …
```

G-API: Python. Gaze Estimation sample.

---

samples/python/gaussian_mix.py
samples/python/hist.py
samples/python/morphology.py

This PR fixes errors in some samples

Fix samples

---

modules/dnn/misc/java/gen_dict.json
modules/java/generator/gen_java.py

(3.4) Java: force using of 'Ptr<>' for OpenCV classes

---

modules/highgui/src/window.cpp
modules/highgui/src/window_w32.cpp

- imshow uses WINDOW_AUTOSIZE
- fix missing Save dialog
- Ctrl+S / Ctrl+C don't trigger waitKey() anymore
resolves #20352
relates #20281

highgui: fix win32 backend behavior

---

modules/core/include/opencv2/core/version.hpp

OpenCV 4.5.3
relates #20242
<cut/>
<details>
[opencv_world453.dll (vc14)](https://www.virustotal.com/gui/file/53e1151a7f3da7d05ad720010e24ea1594cd5d599572cebd7fc83cf99de72f3e/detection)
[opencv_world453d.dll (vc14)](https://www.virustotal.com/gui/file/94866e70c00b316a4dbaae27b0a9f7b360c733707e34f3b99b77be1d940f5283/detection) 
[opencv_world453.dll (vc15)](https://www.virustotal.com/gui/file/2e558a3b435b484514157bf1482b5c8b9d42db5496dcc8c9384883c8c28a585f/detection)
[opencv_world453d.dll (vc15)](https://www.virustotal.com/gui/file/605b51cb436223d20fae468fbcaa49b7ce60876e6f9b6383833b52b5c03e8dad/detection)
[opencv_videoio_ffmpeg453_64.dll](https://www.virustotal.com/gui/file/cd4a87e499db76de896084d04df4a55a1715cc7e361036c31ababc57c38ab140/detection …

release: OpenCV 4.5.3

---

modules/gapi/test/infer/gapi_infer_onnx_test.cpp

```
test_filter:Custom=*ONNX*
```

G-API: ONNX. Skip tests.

---

modules/features2d/include/opencv2/features2d.hpp
modules/features2d/src/agast.cpp
modules/features2d/src/fast.cpp

Reduce overloads for FAST and AGAST

---

platforms/winpack_dldt/build_package.py

build(winpack_dldt): avoid stale sysroot contents

---

CMakeLists.txt
modules/core/src/parallel.cpp
modules/core/src/system.cpp

Fixes #20395.
```
force_builders=linux,docs,Android armeabi-v7a
```

Improves support for Unix non-Linux systems, including QNX

---

modules/core/src/persistence.cpp
modules/core/src/persistence.hpp
modules/core/src/persistence_base64_encoding.cpp
modules/core/src/persistence_base64_encoding.hpp
modules/core/src/persistence_impl.hpp
modules/core/src/persistence_json.cpp
modules/core/src/persistence_xml.cpp
modules/core/src/persistence_yml.cpp
modules/core/test/test_io.cpp
modules/python/test/test_filestorage_io.py

issue #14977
Test data is at https://github.com/opencv/opencv_extra/pull/877
```
opencv_extra=base64_encoding
force_builders=Custom,ARMv7
```

port base64 encoding from 3.4

---

doc/tutorials/core/mat_the_basic_image_container/mat_the_basic_image_container.markdown

- [N/A] There is reference to original bug report and related work
- [N/A ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [N/A] The feature is well documented and sample code can be built with the project CMake

minor grammar edits

---

modules/js/src/make_umd.py

Related to https://github.com/opencv/opencv/issues/20064#issue-886535505
```
```

Bugfix on import script with web worker.

---

modules/gapi/samples/face_detection_mtcnn.cpp

Single transpose MTCNN version

---

modules/core/include/opencv2/core/parallel/backend/parallel_for.tbb.hpp

Fix typo in comment, OpenMP => TBB

---

modules/dnn/src/dnn_common.hpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp

Related: https://github.com/opencv/opencv/pull/20453

Reimplement onnx refactor for master

---

3rdparty/readme.txt
platforms/winrt/readme.txt

resolves #20495
Details:
Fixed the links:
-> Broken/Missing Links
-> Some links expired

Fix Broken Link

---

modules/gapi/misc/python/samples/gaze_estimation.py

Applying comments from https://github.com/opencv/opencv/pull/20144
``` …
```

G-API: Python. Gaze Estimation sample. Update.

---

modules/dnn/src/layers/detection_output_layer.cpp

GetPriorBBoxes() assumes the input blob has shape (1, 2, num_priors * 4, 1) with the second channel being prior-box variances. But when `_varianceEncodedInTarget` is true, the input has shape (1, 1, num_prioirs * 4, 1), as checked by the following assertion
https://github.com/opencv/opencv/blob/424eaba4c5db94524e416c95dba38c8d09071afe/modules/dnn/src/layers/detection_output_layer.cpp#L239
Another reference in the [reshape](https://github.com/opencv/opencv_extra/blob/3c7cf7a13255a0917a13aeb801b322ff9d3d898f/testdata/dnn/faster_rcnn_vgg16.prototxt#L486) for the input of Detection output layer in faster-rcnn-vgg16.

DNN : fix bug in extracting prior-box variances in detection output layer

---

doc/tutorials/dnn/dnn_text_spotting/dnn_text_spotting.markdown
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/math_utils.hpp
modules/dnn/src/model.cpp
modules/dnn/test/test_model.cpp

The algorithm is based on Hannun's paper First-Pass Large Vocabulary
Continuous Speech Recognition using Bi-Directional Recurrent DNNs.

Implement ctc prefix beam search decode for TextRecognitionModel.

---

samples/cpp/kalman.cpp
samples/python/kalman.py

Fixes #20091  
- updated view
- fixed dims in Python sample
- added statePost use

Update kalman sample

---

modules/python/common.cmake

cmake: handle empty CVPY_SUFFIX

---

modules/videoio/src/cap_ueye.cpp

Added exposure and gain props, maximized pixel clk

---

modules/highgui/src/window_w32.cpp

resolves #20592
relates #20281

highgui(win32): avoid using of stalled iterator

---

modules/dnn/src/opencl/conv_spatial_helper.cl

resolves #20615
/cc @diablodale

dnn(OpenCL): avoid out of buffer access in copyWeightsSwizzled

---

doc/py_tutorials/py_feature2d/py_fast/py_fast.markdown

Hi, OpenCV Team
This PR fix python document, does not affect code.
https://github.com/opencv/opencv/pull/5471

docs: fix image path for py_fast doc

---

modules/imgcodecs/src/loadsave.cpp

Documentation was desynchronized in commit 11eafca3e2a4cbc62f1309d25db0ea3ed9a6ea8e
- [skip] There is reference to original bug report and related work
only esthetic doc change
- [skip] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
only esthetic doc change
- [skip] The feature is well documented and sample code can be built with the project CMake
only esthetic doc change

Sync imread_ docuemtation with the implemetation.

---

modules/core/src/ocl.cpp

This fixes opencv/opencv#20613 and is compatible with existing behavior of platforms, device types, and device indices. It fixes the case of multiple platforms when those platforms have common substrings. See issue for details.
There should be no change in *already working* existing behavior of 3.4 and 4.x master when using APIs that allow specification of OpenCL "configuration" or setting the envvar `OPENCV_OPENCL_DEVICE`. If it worked before, it should continue working in the same way. It it previously failed and could only use the workaround I describe in the issue...now the PR's code will work using the expected manner + the workaround.
Code approach:
* copy 4.x selectOpenCLDevice() back to 3.4 -- it is compatible and easily used
* filter platforms rather than trying only first …

fix opencv/opencv#20613 -- selectOpenCLDevice

---

modules/core/src/intel_gpu_gemm.inl.hpp
modules/core/src/opencl/intel_gemm.cl

relates #20670
<cut/>
```
buildworker:Linux OpenCL=linux-4
```

core(OpenCL): buffer bounds in intelblas_gemm_buffer_NT

---

modules/dnn/src/cuda4dnn/primitives/padding.hpp

The existing assertion asserts that the effective ranks (after removing leading singleton axes) of the input tensor and output tensor are equal. This assertion fails in two tests:
```
[  FAILED  ] Test_ONNX_layers.CalculatePads/0, where GetParam() = CUDA/CUDA
[  FAILED  ] Test_ONNX_layers.CalculatePads/1, where GetParam() = CUDA/CUDA_FP16
```
The effective rank of the input may be smaller than the effective rank of the output but the converse is never true. For example,
```
input: [1, 1, 1, 3]; effective rank = 1
output: [1, 1, 3, 3]; effective rank = 2
```
There is padding for axis 2 which is a singleton axis in the input tensor.
The correct assertion is to check that the input effective rank is less than or equal to the output effective rank. This PR fixes the assertion and the tests …

cuda4dnn(padding): fix assertion to allow input effective rank to be lower than output effective rank

---

3rdparty/carotene/hal/tegra_hal.hpp
3rdparty/openvx/hal/openvx_hal.cpp
3rdparty/openvx/hal/openvx_hal.hpp
modules/imgproc/include/opencv2/imgproc/hal/hal.hpp
modules/imgproc/src/color_yuv.dispatch.cpp
modules/imgproc/src/color_yuv.simd.hpp
modules/imgproc/src/hal_replacement.hpp
modules/imgproc/test/test_color.cpp

fixes https://github.com/opencv/opencv/issues/17036

different paddings in cvtColorTwoPlane() for biplane YUV420

---

modules/gapi/src/executor/gexecutor.cpp
modules/gapi/test/internal/gapi_int_executor_tests.cpp

G-API: Handle reshape for generic case in GExecutor

---

modules/photo/src/inpaint.cpp

This submission is used to improve the performance of the inpaint algorithm for 3 channels images(RGB or BGR).
Reason:
The original algorithm implementation did not consider the cache hits and repeated calculation
The loop of channels is outside the core loop, so the performance is not very good.
Moving the channel loop inside the core loop can significantly improve cache hits and reduce the redundant calculation, thereby improving performance.
Performance:
360P, about >= 30% improvement
iphone8P: 5.52ms -> 3.75ms
iphone6s: 14.04ms -> 9.15ms

This submission is used to improve the performance of the inpaint algorithm for 3 channels images(RGB or BGR)

---

doc/pattern_tools/gen_pattern.py
doc/tutorials/calib3d/camera_calibration_pattern/camera_calibration_pattern.markdown
modules/calib3d/include/opencv2/calib3d.hpp

Generate radon checkerboard for `findChessboardCornersSB` and update docs
resolves #20364

generate radon checkerboard

---

modules/python/src2/hdr_parser.py

Verbose output for errors found by header parser.

---

modules/video/perf/opencl/perf_bgfg_knn.cpp
modules/video/perf/opencl/perf_bgfg_mog2.cpp
modules/video/perf/perf_bgfg_knn.cpp
modules/video/perf/perf_bgfg_mog2.cpp

Clean up test data

---

modules/video/perf/opencl/perf_bgfg_knn.cpp
modules/video/perf/opencl/perf_bgfg_mog2.cpp
modules/video/perf/perf_bgfg_knn.cpp
modules/video/perf/perf_bgfg_mog2.cpp

(4.x) Clean up test data

---

modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

G-API: Fix bugs with dangling frames

---

modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp
modules/dnn/src/opencl/conv_layer_spatial.cl

similar to #20774
<cut/>
```
force_builders=Custom,Linux AVX2,Linux OpenCL,Custom Win
```

dnn(OpenCL): fix conv DWCONV workgroup

---

modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/lsd.cpp
modules/imgproc/test/test_lsd.cpp
samples/cpp/lsd_lines.cpp

resolves https://github.com/opencv/opencv_contrib/issues/2524
```
```

Restore LineSegmentDetector

---

modules/dnn/src/int8layers/convolution_layer.cpp

resolves #20799 
```
[ RUN      ] Test_Int8_layers.Convolution2D/0, where GetParam() = OCV/CPU
--28388-- REDIR: 0x7798eb0 (libc.so.6:posix_memalign) redirected to 0x4c33f60 (posix_memalign)
[ INFO:0] global /home/jebastin/opencv_build/opencv/modules/dnn/src/tensorflow/tf_importer.cpp (2759) populateNet DNN/TF: parsing model (N/A version info). Number of nodes = 6
[ INFO:0] global /home/jebastin/opencv_build/opencv/modules/dnn/src/tensorflow/tf_importer.cpp (2759) populateNet DNN/TF: parsing model (N/A version info). Number of nodes = 3
[ INFO:0] global /home/jebastin/opencv_build/opencv/modules/dnn/src/tensorflow/tf_importer.cpp (2759) populateNet DNN/TF: parsing model (N/A version info). Number of nodes = 10
[ INFO:0] global /home/jebastin/opencv_build/opencv/modules/dnn/src/tensorflow/tf …
```

dnn : fix illegal memory access in int8 convolution

---

modules/gapi/include/opencv2/gapi/own/types.hpp

remove redundant semicolons

---

modules/core/src/parallel_impl.cpp

core(parallel): suppress TSAN warning

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/python/package/setup.py
platforms/android/build_sdk.py
platforms/android/service/readme.txt
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #20236

pre: OpenCV 3.4.16 (version++)

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/version.hpp
modules/python/package/setup.py
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #20242

pre: OpenCV 4.5.4 (version++)

---

modules/features2d/src/blobdetector.cpp
modules/features2d/test/test_blobdetector.cpp

fixes #20649
reverts #19859
relates #6667

features2d: repair SimpleBlobDetector

---

modules/imgcodecs/misc/objc/ios/Mat+QuickLook.mm
modules/imgcodecs/misc/objc/macosx/Mat+QuickLook.mm

Fix for https://github.com/opencv/opencv/issues/20816
```
```

Fix build on older Xcode versions

---

modules/core/src/matrix.cpp
modules/python/src2/cv2.cpp
modules/python/test/test_misc.py

resolves #20968
relates #20558

python: properly handle step for multichannel case

---

modules/objdetect/test/test_qrcode.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/933
This PR adds test case for fix #20882 in QR detection algorithm

Add test case for QR detection fix

---

modules/highgui/src/window_w32.cpp

resolves #21002
relates #20281

highgui(win32): fix trackbar setRange

---

apps/opencv_stitching_tool/README.md
apps/opencv_stitching_tool/opencv_stitching/.gitignore
apps/opencv_stitching_tool/opencv_stitching/blender.py
apps/opencv_stitching_tool/opencv_stitching/camera_adjuster.py
apps/opencv_stitching_tool/opencv_stitching/camera_estimator.py
apps/opencv_stitching_tool/opencv_stitching/camera_wave_corrector.py
apps/opencv_stitching_tool/opencv_stitching/exposure_error_compensator.py
apps/opencv_stitching_tool/opencv_stitching/feature_detector.py
apps/opencv_stitching_tool/opencv_stitching/feature_matcher.py
apps/opencv_stitching_tool/opencv_stitching/image_handler.py
apps/opencv_stitching_tool/opencv_stitching/megapix_downscaler.py
apps/opencv_stitching_tool/opencv_stitching/megapix_scaler.py
apps/opencv_stitching_tool/opencv_stitching/panorama_estimation.py
apps/opencv_stitching_tool/opencv_stitching/seam_finder.py
apps/opencv_stitching_tool/opencv_stitching/stitcher.py
apps/opencv_stitching_tool/opencv_stitching/stitching_error.py
apps/opencv_stitching_tool/opencv_stitching/subsetter.py
apps/opencv_stitching_tool/opencv_stitching/test/.gitignore
apps/opencv_stitching_tool/opencv_stitching/test/SAMPLE_IMAGES_TO_DOWNLOAD.txt
apps/opencv_stitching_tool/opencv_stitching/test/stitching_detailed.py
apps/opencv_stitching_tool/opencv_stitching/test/test_composition.py
apps/opencv_stitching_tool/opencv_stitching/test/test_matcher.py
apps/opencv_stitching_tool/opencv_stitching/test/test_megapix_scaler.py
apps/opencv_stitching_tool/opencv_stitching/test/test_performance.py
apps/opencv_stitching_tool/opencv_stitching/test/test_registration.py
apps/opencv_stitching_tool/opencv_stitching/test/test_stitcher.py
apps/opencv_stitching_tool/opencv_stitching/timelapser.py
apps/opencv_stitching_tool/opencv_stitching/warper.py
apps/opencv_stitching_tool/opencv_stitching_tool.py

Sqaushed the work proposed in https://github.com/opencv/opencv/pull/20758

Created Stitching Tool based on stitching_detailed.py

---

modules/core/src/system.cpp

1. Code uses PPC_FEATURE_HAS_VSX, but it's not checked similarly to PPC_FEATURE2_ARCH_3_00 and PPC_FEATURE2_ARCH_3_00 for availability. FreeBSD has those macros in machine/cpu.h, but I went with the way chosen for PPC_FEATURE2_ARCH_3_00 and PPC_FEATURE2_ARCH_3_00. Other than that, FreeBSD also has sys/auxv.h and that's where elf_aux_info() is defined.
2. getauxval() is actually Linux-only, but code checked for __unix__. It won't work on all UNIX, so change it back to __linux__. Add another code variant strictly for FreeBSD.
3. Update comment. This commit adds code for FreeBSD, but recently there appeared support for powerpc64 in OpenBSD.
``` …
```

Add support for runtime CPU feature check on POWER on FreeBSD.

---

modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/hough.cpp
modules/imgproc/test/test_houghlines.cpp

Fix seg fault houghlinespointset

---

modules/videoio/doc/videoio_overview.markdown

doc(videoio): fix apiPreference note, replace DSHOW(deprecated)->MSMF

---

modules/js/test/package.json

- avoid broken dependency: https://github.com/Automattic/cli-table/issues/152
resolves #21076
```
```

JavaScript(test): pin cli-table dependency

---

modules/js/src/core_bindings.cpp
modules/js/test/package.json
modules/js/test/test_video.js
platforms/js/opencv_js.config.py

To verify that Tracker wrapper works.
Blocked by #21045
```
```

JavaScript: add TrackerMIL

---

modules/dnn/src/cuda/grid_nms.cu
modules/dnn/src/cuda/grid_stride_range.hpp
modules/dnn/src/tensorflow/tf_importer.cpp

I made small corrections to improve overall readablity

Improved overall readblity of the code

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_misc.cpp

resolves failures of [nightly builds](http://pullrequest.opencv.org/buildbot/builders/3_4_openvino-opencl-win64/builds/640).
<cut/>
```
Xbuildworker:Win64 OpenCL=windows-3
Xbuild_image:Win64 OpenCL=msvs2019 …
```

dnn: fix U8 input support in FP16 networks

---

modules/objdetect/src/qrcode_encoder.cpp

Resolves https://github.com/opencv/opencv/issues/21098
This PR fixes access to uninitialized memory and illegal access to array and removes unused variables
Validation:

QR encoder: fix memory and unused variables issues

---

modules/dnn/src/onnx/onnx_graph_simplifier.cpp

Fix for https://github.com/opencv/opencv/issues/21078, tests are coming to 4.x with https://github.com/opencv/opencv/pull/21088
SoftMax: https://github.com/onnx/onnx/blob/master/docs/Operators.md#softmax
LogSoftMax: https://github.com/onnx/onnx/blob/master/docs/Operators.md#logsoftmax

Add Log/Softmax simplification

---

modules/highgui/src/window_cocoa.mm

resolves #21014
<cut/>
```
force_builders=Mac,iOS
```

resolve #21014 by limiting number of ticks

---

doc/py_tutorials/py_feature2d/py_feature_homography/py_feature_homography.markdown

https://github.com/opencv/opencv/issues/21187 
fix gray image does not have three dimensions 
```
```

fix issue 21187: markdown file: gray image does not have three dimensions

---

modules/gapi/doc/10-hld-overview.md
modules/gapi/include/opencv2/gapi/own/cvdefs.hpp

- Some files were modified in openvino repo to fix issues, so to actualize versions those changes should be applied here as well.
- Actualized defines with current `interface.h`
``` …
```

[G-API] Bring updates from openvino version of standalone files

---

doc/py_tutorials/py_feature2d/py_feature_homography/py_feature_homography.markdown
samples/python/tutorial_code/video/optical_flow/optical_flow.py
samples/python/tutorial_code/video/optical_flow/optical_flow_dense.py

fix the iusse: https://github.com/opencv/opencv/issues/21223
* Added a conditional sentence to judge whether ret is true
* Modify the problem of using the `next` keyword as a variable
* some python code style: add space

fix cvtColor-error

---

modules/core/include/opencv2/core/types.hpp
modules/core/test/test_misc.cpp

Fow now, it is possible to define valid rectangle for which some
functions overflow (e.g. br(), ares() ...).
This patch fixes the intersection operator so that it works with
any rectangle.

Solve Rect overflow issues.

---

cmake/OpenCVFindLibsGUI.cmake
modules/highgui/CMakeLists.txt
modules/highgui/src/window_QT.cpp
modules/highgui/src/window_QT.h

- [ x] I agree to contribute to the project under Apache 2 License.
- [ x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x ] The PR is proposed to proper branch
- [ x] There is reference to original bug report and related work
- [ x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
```
```

Qt opengl build fix

---

doc/js_tutorials/js_video/js_lucas_kanade/js_lucas_kanade.markdown
doc/tutorials/video/optical_flow/optical_flow.markdown

I was reading the original paper and your docs and found a small spelling mistake in the docs. I thought it was nice to give the creator proper credit so changed his name in your docs. The original paper on the Gunnar Färneback algorithm can be found online ([here](https://www.diva-portal.org/smash/get/diva2:273847/FULLTEXT01.pdf)'s a link) where he spells his own name as Gunnar, not Gunner. I checked the openCV repositories for uses of his name, and in some places it was spelled right. Where not I changed it.

Update Optical Flow algorithm name from Gunner to Gunnar as that's the name he published his paper with

---

modules/calib3d/src/usac.hpp
modules/calib3d/src/usac/dls_solver.cpp
modules/calib3d/src/usac/pnp_solver.cpp
modules/calib3d/src/usac/ransac_solvers.cpp
modules/calib3d/src/usac/utils.cpp
modules/calib3d/test/test_usac.cpp

fixes #21105
relates #17683
<cut/>

Fix intrinsics processing in case USAC parameters

---

modules/core/test/test_arithm.cpp

Fix issues in reduceArgMax test found by coverity

---

modules/videoio/src/cap_msmf.cpp
modules/videoio/test/test_camera.cpp

(3.4) videoio(MSMF): add queue for async ReadSample()

---

modules/3d/src/rgbd/odometry_frame_impl.cpp

Odometry warnings fix

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/objdetect/src/qrcode_encoder.cpp

(3.4) Fixed several issues found by static analysis

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/python/package/setup.py
platforms/android/build_sdk.py
platforms/android/service/readme.txt
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #20806

pre: OpenCV 3.4.17 (version++)

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/version.hpp
modules/python/package/setup.py
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #20788

pre: OpenCV 4.5.5 (version++)

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra: https://github.com/opencv/opencv_extra/pull/947**
related: https://github.com/opencv/opencv/pull/21203
```
opencv_extra=div_fix
```

fix const/x in Div

---

modules/dnn/test/test_onnx_importer.cpp

<cut/>
```
test_filter:Custom=*DynamicAxes*
```

dnn(test): decompose 'DynamicAxes' test

---

modules/dnn/src/dnn.cpp
modules/dnn/src/dnn_common.hpp
modules/dnn/src/onnx/onnx_graph_simplifier.hpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/precomp.hpp
modules/dnn/src/tensorflow/tf_graph_simplifier.hpp

relates #19347 (debug helper for the issue)
relates #18145 (incomplete dynamic shapes support)
<cut/>
```
test_bigdata:Custom …
```

dnn: improve logging, catch import errors

---

modules/highgui/src/window_gtk.cpp

resolves #21289
Manual validation:
broken since #20149

highgui(gtk): repair scroll events

---

doc/tutorials/introduction/windows_install/windows_install.markdown

Fix: Grammatical mistake

---

samples/dnn/speech_recognition.py

```
build_image:Custom Win=msvs2019-opengl
```

AudioIO: add OpenCV audio reading to dnn speech recognition sample

---

modules/core/include/opencv2/core/version.hpp

release: OpenCV 3.4.17

---

doc/opencv.bib
modules/3d/doc/3d.bib
modules/3d/doc/solvePnP.markdown
modules/3d/include/opencv2/3d.hpp

see https://github.com/opencv/opencv/pull/21320

[Backport 5.x] Main PnP pose computation doc page

---

modules/core/include/opencv2/core/mat.hpp

Remove unnecessary use of ref-capture in code example.

---

modules/calib3d/src/dls.cpp
modules/calib3d/src/dls.h
modules/calib3d/src/solvepnp.cpp

Use c++ namespaces explicitly

---

modules/imgcodecs/src/grfmt_tiff.cpp

```
force_builders=linux,win64,mac,docs
```

tiff need check TIFFTAG_SAMPLEFORMAT, should not always use unsigned.

---

modules/core/src/matrix.cpp

We only use that value as uint64_t below anyway.

Fix a potential UBSAN error.

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/gapi/src/api/media.cpp

* dnn/onnx_importer: values read from file have to be checked before use
* gapi: return in void function

Fixed some issues found by static analysis

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp

Update documentation of imreadmulti()

---

samples/python/tracker.py

relates #20036 #18838
- fix broken ROI re-initialization by SPACE key
- create tracker instance once
- add `cv.samples.findFileOrKeep` for searching of video files
- drop unused backend/target parameters

samples(python): update tracker.py

---

modules/core/src/persistence.cpp
modules/core/src/persistence_impl.hpp
modules/core/test/test_io.cpp

resolves #21448
caused by #13011

core(persistence): avoid NULL pointer dereference

---

modules/dnn/include/opencv2/dnn/layer.hpp
modules/dnn/src/debug_utils.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/dnn_common.hpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp

Related: https://github.com/opencv/opencv/pull/21343

Add domain support to model diagnostic tool

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Update PULL_REQUEST_TEMPLATE.md and ISSUE_TEMPLATE.md

---

modules/imgcodecs/src/grfmt_tiff.cpp
modules/imgcodecs/test/test_tiff.cpp

**Merge with extra: https://github.com/opencv/opencv_extra/pull/952**
resolves #18717

Reading BigTiff images

---

modules/core/include/opencv2/core/utils/fp_control.private.hpp
modules/core/include/opencv2/core/utils/fp_control_utils.hpp
modules/core/src/parallel.cpp
modules/core/src/system.cpp
modules/core/test/test_misc.cpp

relates #21046
- support x86 SSE FTZ+DAZ flags
Info: https://en.wikipedia.org/wiki/Subnormal_number
```
build_image:Custom=openmp:16.04
```

core: FP denormals support

---

modules/dnn/src/onnx/onnx_importer.cpp

https://github.com/onnx/onnx/blob/main/docs/IR.md#optional-inputs-and-outputs

Fix optional outputs support

---

modules/dnn/src/caffe/caffe_importer.cpp
modules/dnn/src/darknet/darknet_importer.cpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/src/torch/torch_importer.cpp

reworks #17295 continues #21506
resolves #21046

dnn: apply hint to ignore denormals processing

---

modules/core/src/va_intel.cpp

Per intel docs for libva, when vaDeriveImage fails vaCreateImage +
vaPutImage should be tried. This is important as mesa with AMD HW
will always fail because the image is interlaced, but the HW
capability still exists
Fixes https://github.com/opencv/opencv/issues/21536
- [ x ] I agree to contribute to the project under Apache 2 License.
- [ x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ x ] The PR is proposed to the proper branch
- [ x ] There is a reference to the original bug report and related work
- [ x ] The feature is well documented and sample …

Fallback to vaCreateImage + vaPutImage when vaDeriveImage fails

---

modules/3d/include/opencv2/3d/odometry.hpp
modules/3d/misc/python/test/test_odometry.py
modules/3d/src/rgbd/odometry.cpp
modules/3d/src/rgbd/odometry_frame_impl.cpp
modules/3d/src/rgbd/odometry_functions.cpp
modules/3d/src/rgbd/odometry_functions.hpp
modules/3d/src/rgbd/odometry_settings_impl.cpp
modules/3d/test/test_odometry.cpp
samples/python/odometry.py

Odometry python support

---

modules/gapi/samples/pipeline_modeling_tool/dummy_source.hpp
modules/gapi/samples/pipeline_modeling_tool/pipeline_builder.hpp
modules/gapi/samples/pipeline_modeling_tool/utils.hpp
modules/gapi/src/backends/ie/giebackend.cpp

[G-API] Pipeline modeling tool - Fix generating FP16 Mat

---

modules/gapi/samples/pipeline_modeling_tool.cpp
modules/gapi/samples/pipeline_modeling_tool/pipeline.hpp
modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/logger.hpp

[G-API] Handle errors in IEBackend & modeling tool

---

modules/core/include/opencv2/core/vsx_utils.hpp

core(vsx): update vec_absd() workaround condition

---

modules/imgproc/src/histogram.cpp
modules/imgproc/test/test_histograms.cpp

Linked issue: https://github.com/opencv/opencv/issues/21595

Issue 21595 fix 3.4 branch

---

modules/3d/include/opencv2/3d/ptcloud.hpp
modules/3d/src/ptcloud/ptcloud_utils.cpp
modules/3d/src/ptcloud/ptcloud_utils.hpp
modules/3d/src/ptcloud/ptcloud_wrapper.hpp
modules/3d/src/ptcloud/sac_segmentation.cpp
modules/3d/src/ptcloud/sac_segmentation.hpp
modules/3d/src/ptcloud/sampling.cpp
modules/3d/test/test_sac_segmentation.cpp
modules/3d/test/test_sampling.cpp

1. Added description of SACSegmentation#segment for models_coefficients parameter.
2. Added copyright of 3D point cloud sampling and USAC-based segmentation algorithm.

Added 3D point cloud code comments and copyright

---

modules/core/include/opencv2/core/base.hpp

- [ + ] I agree to contribute to the project under Apache 2 License.
- [ + ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ + ] The PR is proposed to the proper branch

Fix -Winvalid-noreturn under clang-cl

---

modules/3d/src/rgbd/hash_tsdf_functions.cpp

Fixes AVX+ compilation broken by #21189
```
force_builders=Linux AVX2,Custom,Custom Win
buildworker:Custom=linux-3,linux-5
```

Fix HashTSDF compilation

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/gapi/misc/python/package/gapi/__init__.py
modules/python/src2/cv2.cpp
modules/python/src2/gen2.py
modules/python/src2/pycompat.hpp
modules/python/test/test_misc.py

Port to 4.x: submodule or a class scope for exported classes #21488

---

samples/dnn/speech_recognition.cpp

AudioIO: add dnn speech recognition sample on C++

---

modules/core/include/opencv2/core.hpp
modules/core/perf/perf_arithm.cpp
modules/core/src/matrix_transform.cpp
modules/core/test/test_arithm.cpp

Add n-dimensional transpose to core

---

modules/dnn/src/layers/recurrent_layers.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge after** https://github.com/opencv/opencv/pull/21542
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/959

Fix LSTM support in ONNX

---

modules/java/generator/android/java/org/opencv/android/CameraBridgeViewBase.java

Update CameraBridgeViewBase error message - Change "you device does" to "your device does"

Update CameraBridgeViewBase error message

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/cuda/concat.cu
modules/dnn/src/cuda/kernel_dispatcher.hpp
modules/dnn/src/cuda/permute.cu
modules/dnn/src/cuda/slice.cu
modules/dnn/src/cuda4dnn/csl/memory.hpp
modules/dnn/src/cuda4dnn/csl/pointer.hpp
modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/model.cpp
modules/dnn/src/tengine4dnn/src/tengine_graph_convolution.cpp
modules/dnn/test/test_ie_models.cpp
samples/dnn/speech_recognition.cpp
samples/dnn/speech_recognition.py

Fixes source comments and documentation related to dnn code.

dnn: fix various dnn related typos

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp
modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/backends/oak/goakbackend.cpp
modules/gapi/src/backends/streaming/gstreamingbackend.cpp
modules/gapi/src/compiler/gislandmodel.cpp
modules/gapi/src/compiler/gislandmodel.hpp
modules/gapi/src/executor/gexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.hpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp

[G-API] Handle exceptions in streaming executor

---

modules/dnn/src/cuda4dnn/csl/cudnn/cudnn.hpp
modules/dnn/src/cuda4dnn/csl/cudnn/recurrent.hpp
modules/dnn/src/cuda4dnn/csl/tensor_ops.hpp
modules/dnn/src/cuda4dnn/primitives/recurrent_cells.hpp
modules/dnn/src/layers/recurrent_layers.cpp
modules/dnn/src/onnx/onnx_importer.cpp

Add CUDA backend for LSTM layer
```
build_image:Custom=ubuntu-cuda-cc52:18.04
```

Add CUDA backend for LSTM layer

---

modules/core/include/opencv2/core/hal/intrin_msa.hpp
modules/core/include/opencv2/core/hal/msa_macros.h

resolves #19432
<cut/>
```
```

Fix MSA sum overflow issue (#19432)

---

modules/videoio/test/test_ffmpeg.cpp
modules/videoio/test/test_precomp.hpp
modules/videoio/test/test_video_io.cpp

add test (DISABLED_open_from_web)

---

modules/3d/src/rgbd/odometry_functions.cpp
modules/3d/test/test_odometry.cpp

Odometry prepareFrame fix

---

modules/videoio/src/cap_ffmpeg_impl.hpp

backport #21819
Resolves this valgrind report (caused by incomplete error handling bailout code in open()):
<cut/>
```
==1086648== 20,910 bytes in 1 blocks are possibly lost in loss record 342 of 423
==1086648==    at 0x4849803: memalign (vg_replace_malloc.c:1516)
==1086648==    by 0x484991F: posix_memalign (vg_replace_malloc.c:1688)
==1086648==    by 0x53AB37E: av_malloc (mem.c:86)
==1086648==    by 0x4DEC3EB: ff_mpeg_er_init (mpeg_er.c:115)
==1086648==    by 0x497B48D: ff_mpv_common_init (mpegvideo.c:974)
==1086648==    by 0x497C753: ff_mpv_encode_init (mpegvideo_enc.c:949)
==1086648==    by 0x49797BF: encode_init (mpeg4videoenc.c:1280)
==1086648==    by 0x4B9EC52: avcodec_open2 (avcodec.c:351)
==1086648==    by 0x49FB47E: CvVideoWriter_FFMPEG::open(char const*, int, double, int, int, …
```

(3.4) videoio(ffmpeg): avoid memory leaks

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp

Fixes https://github.com/opencv/opencv/issues/21857

Document defaults for JPEG settings.

---

modules/dnn/src/cuda/activations.cu
modules/dnn/src/cuda/functors.hpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/opencl/activations.cl
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_misc.cpp
modules/dnn/test/test_model.cpp
modules/dnn/test/test_onnx_conformance.cpp
modules/dnn/test/test_onnx_conformance_layer_filter__cuda_denylist.inl.hpp
modules/dnn/test/test_onnx_importer.cpp

Related https://github.com/opencv/opencv/pull/21831

Fix CUDA compilation issues and adjust thresholds.

---

samples/gdb/mat_pretty_printer.py

Mat pretty printer: fix submatrix indexation

---

cmake/mirrors/custom.cmake
cmake/mirrors/gitcode.cmake

Support mirrors for TIM-VX and others 3rdparty components in opencv_contrib

---

.github/workflows/PR-5.x-U20.yaml

This PR adds a workflow for GitHub Actions to build and test OpenCV on `ubuntu-18.04` for `5.x` branch

Added workflow for Github Actions to build and test OpenCV on Linux for 5.x

---

.github/workflows/PR-3.4-W10.yaml

This PR adds a workflow for GitHub Actions to build and test OpenCV on Windows10 for 3.4 branch

Added workflow for Github Actions to build and test OpenCV on Windows for 3.4 branch

---

modules/highgui/src/window_gtk.cpp

Try to solve I21853 mouse wheel problem with GTK3

---

modules/core/include/opencv2/core/cuda.hpp
modules/python/test/test_cuda.py

Wrap gpuMat::release to Python

---

.github/workflows/PR-4.x-W10.yaml

This PR adds a workflow for GitHub Actions to build and test OpenCV on Windows10 for 4.x branch

Added workflow for Github Actions to build and test OpenCV on Windows for 4.x branch

---

.github/workflows/PR-4.x-W10.yaml

This PR cleans a list of turned off tests for 4.x branch (it's different for each branch).

GTest filtered list for 4.x

---

modules/imgproc/include/opencv2/imgproc.hpp

Some Doxygen links were missing/broken. The commit should easily apply to 4.x as well.

Minor documentation fixes for geometric image transformations

---

.github/workflows/PR-3.4-ARM64.yaml

Black list of tests can be found [here](https://github.com/opencv-cn-ci-bot/opencv-cn-pipelines/blob/master/precommit/ubuntu-20.04-arm64.groovy).

Workflow to build and test on ARM64 for 3.4 branch

---

3rdparty/openvx/README.md
doc/js_tutorials/js_imgproc/js_morphological_ops/js_morphological_ops.markdown
doc/js_tutorials/js_setup/js_nodejs/js_nodejs.markdown
doc/py_tutorials/py_feature2d/py_feature_homography/py_feature_homography.markdown
doc/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.markdown
doc/tutorials/imgproc/morph_lines_detection/morph_lines_detection.md

Fix some typos in doc.

---

modules/core/include/opencv2/core/mat.hpp
modules/cudafilters/include/opencv2/cudafilters.hpp
modules/cudafilters/src/cuda/median_filter.cu
modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/onnx/opencv-onnx.proto
modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/opencl/medianFilter.cl
modules/imgproc/test/test_convhull.cpp
modules/ml/src/lr.cpp
modules/videoio/src/cap_gstreamer.cpp
modules/videoio/src/cap_intelperc.cpp
modules/videoio/src/cap_intelperc.hpp
modules/videoio/src/cap_libv4l.cpp
modules/videoio/test/test_video_io.cpp

Fix some typos in modules/.

---

.github/workflows/PR-3.4-W10.yaml

Move from https to ssh for Windows in Github Actions

---

modules/calib3d/src/sqpnp.cpp
modules/calib3d/src/sqpnp.hpp

This PR mirrors to OpenCV changes made recently to the official [SQPnP implementation](https://github.com/terzakig/sqpnp)
```
```

Fixes and optimizations for the SQPnP solver

---

.github/workflows/PR-3.4-W10.yaml

Move environment variables on a host side (GHA Windows)

---

.github/workflows/PR-4.x-ARM64.yaml

Black list of tests can be found [here](https://github.com/opencv-cn-ci-bot/opencv-cn-pipelines/blob/master/precommit/ubuntu-20.04-arm64.groovy)

Workflow to build and test on ARM64 for 4.x branch

---

.github/workflows/PR-3.4-ARM64.yaml
.github/workflows/PR-3.4-U20.yaml
.github/workflows/PR-3.4-W10.yaml

This PR adds extended DNN testing on Linux, adapts ARM64 build with self-hosted runner to use ccache and git cache, and changes docker images.

Extended DNN testing in GHA

---

.github/workflows/PR-3.4-W10.yaml

GHA: fix git merge (part 2)

---

modules/gapi/include/opencv2/gapi/streaming/cap.hpp
modules/gapi/misc/python/samples/gaze_estimation.py

-> There's no issue about this change.
->This PR only exposes the api to python.

Add make_capture_src for video stream to Python

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra:** https://github.com/opencv/opencv_extra/pull/968
Fixes #21698

Add prefixes to layer names and layer output names

---

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra:** https://github.com/opencv/opencv_extra/pull/974
Fixes #21947

Fix vector access in TF::sortByExecutionOrder

---

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown
modules/core/include/opencv2/core/version.hpp
modules/dnn/include/opencv2/dnn/version.hpp
modules/python/package/setup.py
platforms/maven/opencv-it/pom.xml
platforms/maven/opencv/pom.xml
platforms/maven/pom.xml

previous PR with version bump: #21281

pre: OpenCV 4.6.0 (version++)

---

modules/flann/include/opencv2/flann.hpp
modules/flann/include/opencv2/flann/dist.h

I assume 4.x is the right branch because it is the repo's current default. Please advise if not so!

typo: Minkowsky is actually Minkowski

---

modules/objdetect/src/qrcode_encoder.cpp
modules/objdetect/test/test_qrcode_encode.cpp

objdetect: qrcode_encoder: fix to missing timing pattern

---

modules/core/src/precomp.hpp
modules/imgproc/src/color_hsv.simd.hpp
modules/imgproc/src/precomp.hpp

successor of #21948 and #22050

imgproc: use singleton in color_hsv.simd.hpp

---

modules/core/include/opencv2/core/version.hpp

release: OpenCV 3.4.18

---

modules/highgui/src/window_cocoa.mm

In Mac highgui now shows trackbars in creation order. Solves issue #5056

---

modules/core/include/opencv2/core/version.hpp

release: OpenCV 4.6.0
