opencv/opencv

modules/core/include/opencv2/core/mat.inl.hpp
modules/core/src/matrix.cpp
modules/core/src/umatrix.cpp

relates #18640
opencv_contrib=fix_uninitialized_var

core: move inline code from mat.inl.hpp (OpenCV 4.x additions)

---

modules/videoio/cmake/init.cmake

Fix configure error using cmake 3.18.*:
```
INTERFACE_LINK_LIBRARIES: optimized;F:/vcpkg/installed/x64-windows/lib/avcodec.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avcodec.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avdevice.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avdevice.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avfilter.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avfilter.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avformat.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avformat.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avresample.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avresample.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avutil.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avutil.lib;optimized;F:/vcpkg/insta …
```

Fix cmake configure error

---

modules/core/src/dxt.cpp

This is useful for non power-of-two sizes when WITH_IPP is not an option.
This shows consistent improvement on openCV benchmarks, and we measure
even larger improvements on our internal workloads.
For example, for 320x480, `32FC*`, we can see a ~5% improvement, as
`320=2^6*5` and `480=2^5*3*5`, so the improved radix3 version is used.
`64FC*` is flat as expected, as we do not specialize the functors for `double`
in this change.
```
dft::Size_MatType_FlagsType_NzeroRows::(320x480, 32FC1, 0, false)                                1.239  1.153     1.07
dft::Size_MatType_FlagsType_NzeroRows::(320x480, 32FC1, 0, true)                                 0.991  0.926     1.07
dft::Size_MatType_FlagsType_NzeroRows::(320x480, 32FC1, DFT_COMPLEX_OUTPUT, false)               1.367  1.281     1.07 …
```

Optimize opencv dft by vectorizing radix2 and radix3.

---

modules/gapi/include/opencv2/gapi/gcommon.hpp
modules/gapi/include/opencv2/gapi/s11n.hpp
modules/gapi/include/opencv2/gapi/s11n/base.hpp
modules/gapi/src/backends/common/serialization.cpp
modules/gapi/test/s11n/gapi_s11n_tests.cpp

```
Xtest_modules:Custom=gapi
```

Not serialize compile arguments which have no S11N<T> template specialization

---

CMakeLists.txt
cmake/FindONNX.cmake
modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/infer/onnx.hpp
modules/gapi/samples/infer_ie_onnx_hybrid.cpp
modules/gapi/samples/infer_ssd_onnx.cpp
modules/gapi/src/backends/onnx/gonnxbackend.cpp
modules/gapi/src/backends/onnx/gonnxbackend.hpp
modules/gapi/src/compiler/passes/kernels.cpp
modules/gapi/test/infer/gapi_infer_onnx_test.cpp

- Basic operations are implemented (Infer, -ROI, -List, -List2);
- Implemented automatic preprocessing for ONNX models;
- Test suite is extended with `OPENCV_GAPI_ONNX_MODEL_PATH` env for test data
(test data is an ONNX Model Zoo repo snapshot);
- Fixed kernel lookup logic in core G-API:
- Lookup NN kernels not in the default package, but in the associated
backend's aux package. Now two NN backends can work in the same graph.
- Added Infer SSD demo and a combined ONNX/IE demo;
<cut/>
Build & install the ONNX RT (currently tested with v1.5.1):
```bash
$ git clone --recursive https://github.com/microsoft/onnxruntime.git
$ cd onnxruntime
$ git checkout v1.5.1
$ git submodule update --init
$ ./build.sh --config Release --build_shared_lib --parallel \
$     --cmake_extra_defines …
```

G-API: Introduce ONNX backend for Inference

---

modules/features2d/src/keypoint.cpp

Implementation (and usage in context of std::partition) of KeypointResponseGreaterThanThreshold does actually compare a keypoint with given threshold by greatness OR equality.

Change naming of keypoints comparator

---

modules/videoio/src/cap_mfx_reader.cpp
modules/videoio/src/cap_mfx_reader.hpp
modules/videoio/test/test_mfx.cpp

<cut/>
```
test_modules:Custom Win=dnn,python2,python3,java,videoio
```

videoio: added frameSize to MFX capture

---

cmake/OpenCVFindLibsPerf.cmake

**Merge with opencv_contrib**: https://github.com/opencv/opencv_contrib/pull/2732
Compatibility with Ceres 2.0.0 CMake scripts
Related CMake message:
> Failed to find Ceres - Found Eigen dependency, but the version of Eigen found () does not exactly match the version of Eigen Ceres was compiled with (3.3.7).
```
opencv_contrib=
```

cmake: prefer using Eigen configuration files

---

modules/gapi/cmake/standalone.cmake

Fixed undefined rmat and media symbols in standalone

---

modules/dnn/src/layers/prior_box_layer.cpp

The change is needed due to removing default opset namespace for Unsqueeze
in the scope of this refactoring activity: https://github.com/openvinotoolkit/openvino/pull/2767
Signed-off-by: Roman Kazantsev <roman.kazantsev@intel.com>
```
```

Use explicit opset of Unsqueeze from nGraph

---

modules/dnn/src/layers/prior_box_layer.cpp

backport #18741
<cut/>
```
```

(3.4) Use explicit opset of Unsqueeze from nGraph (backport #18741)

---

cmake/OpenCVFindOpenBLAS.cmake

Fix typo coming from the original Caffe file: https://github.com/BVLC/caffe/blob/9b891540183ddc834a02b2bd81b31afae71b2153/cmake/Modules/FindOpenBLAS.cmake#L25
Has been fixed in PyTorch: https://github.com/pytorch/pytorch/commit/63df9ffd0bd13f46600046e53ad9610ddbe752df
---
- N/A There is reference to original bug report and related work

Fix typo in OpenCVFindOpenBLAS.cmake file

---

cmake/OpenCVDetectInferenceEngine.cmake
modules/dnn/src/op_inf_engine.hpp

Maintain default flow of this page: https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend
<cut/>
```
```

dnn: use OpenVINO 2021.1 defines

---

modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/src/api/kernels_imgproc.cpp
modules/gapi/src/backends/cpu/gcpuimgproc.cpp
modules/gapi/test/common/gapi_imgproc_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp

These changes:
- Add morphologyEx() standard kernel
- provide API and documentation (without separate 3x3 version)
- support OCV backend
- provide accuracy tests: check only different operations, not kernels/borders
```
Xbuild_image:Custom …
```

[G-API]: morphologyEx() Standard Kernel Implementation

---

doc/tutorials/video/background_subtraction/background_subtraction.markdown
doc/tutorials/videoio/video-input-psnr-ssim/video_input_psnr_ssim.markdown
doc/tutorials/videoio/video-write/video_write.markdown

Code snippets need a section marked with `###` above to render properly.

Fix code snippets inclusion into video tutorials

---

modules/python/src2/hdr_parser.py

bindings: "inline namespace"

---

samples/python/stitching_detailed.py

A small bugfix, closes #18650.
<cut/>

Use in-place sort in stiching example

---

modules/gapi/src/backends/cpu/gnnparsers.cpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/common/gapi_parsers_tests_common.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp

Added support of 1x1x1xN input for parseYolo

---

modules/dnn/perf/perf_convolution.cpp
modules/dnn/perf/perf_convolution1d.cpp
modules/dnn/perf/perf_convolution3d.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/layers_common.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp

resolves https://github.com/opencv/opencv/issues/18205
**merge with extra:** https://github.com/opencv/opencv_extra/pull/813
<cut/>
```
opencv_extra=test_conv1d
Xbuildworker:Custom=linux-3
Xbuild_image:Custom=ubuntu:18.04
XCPU_BASELINE:Custom=AVX512_SKX
Xdisable_ipp:Custom=ON
```

Add support for Conv1D on OpenCV backend

---

samples/cpp/CMakeLists.txt

Intrudeced in commit 397ba2d9aafb5312e777ce2f886d7b568109e931:
add OpenCV sample for digit and text recongnition, and provide multiple OCR models.
https://github.com/opencv/opencv/commit/397ba2d9aafb5312e777ce2f886d7b568109e931
Signed-off-by: Jose Quaresma <quaresma.jose@gmail.com>

samples: cmake: digits needs opencv_dnn module to build

---

modules/core/misc/objc/gen_dict.json

- arg types may be passed as `string` instead of `std::string`
/cc @komakai

objc: fix std::string handling

---

doc/tutorials/videoio/video-input-psnr-ssim/video_input_psnr_ssim.markdown

Affected doc: tutorial_video_input_psnr_ssim

Small typo-fix

---

modules/objc/CMakeLists.txt
modules/objc/generator/CMakeLists.txt
modules/objc/generator/gen_objc.py
modules/objc/generator/templates/cmakelists.template
platforms/ios/build_framework.py
platforms/osx/build_framework.py

Allow to run generator for Obj-C source code in non-Apple build environments (necessary for validation of changes in generated code in case of headers parser refactoring)
Align with `gen_opencv_java_source` / `gen_opencv_python_source` targets.
```
force_builders_only=docs,ios,Custom Mac
Xbuild_image:Custom Mac=osx_framework
```

cmake: update objc generator scripts

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/cap_openni2.cpp

This pull request includes minor modifications to the OpenNI module of VideoCapture to handle Orbbec Astra cameras properly.  Only depth sensor reading is supported. The color sensor is accessible as a regular UVC camera.

videoio: Support Orbbec Astra 3D cameras using OpenNI2 API

---

modules/gapi/include/opencv2/gapi/rmat.hpp
modules/gapi/src/api/rmat.cpp
modules/gapi/src/backends/common/gbackend.hpp
modules/gapi/test/rmat/rmat_test_common.hpp
modules/gapi/test/rmat/rmat_view_tests.cpp
modules/gapi/test/s11n/gapi_s11n_tests.cpp

* Added missing multidimensional steps (strides) for RMat::View
``` …
```

[G-API] ND RMat Views

---

modules/gapi/src/backends/onnx/gonnxbackend.cpp
modules/gapi/test/infer/gapi_infer_onnx_test.cpp

- Changed assert for CV_32F case. Added test.
<cut/>
New tests:
- InferTensor;
- InferDynamicInputTensor;
- Infer(Gray)Image;
- InferMultiNodes.
Refactored tests:
- Infer;
- InferROI;
- InferROIList;
- Infer2ROIList.
Tests contain unsupported(OCV bb) models:
- tinyyolov2-8.onnx from https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2
```
test_filter:Custom=*ONNX*
```

G-API: ONNX. Support tensor input for CNN with dynamic input 

---

modules/dnn/src/onnx/onnx_graph_simplifier.cpp

relates: #18785
<cut/>
```
```

[ONNX] Added handler for int32 tensors

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/garg.hpp
modules/gapi/include/opencv2/gapi/gopaque.hpp
modules/gapi/include/opencv2/gapi/streaming/cap.hpp
modules/gapi/include/opencv2/gapi/streaming/meta.hpp
modules/gapi/src/api/gbackend.cpp
modules/gapi/src/api/grunarg.cpp
modules/gapi/src/backends/common/gbackend.hpp
modules/gapi/src/backends/common/gmetabackend.cpp
modules/gapi/src/backends/common/gmetabackend.hpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/src/compiler/gislandmodel.cpp
modules/gapi/src/compiler/gislandmodel.hpp
modules/gapi/src/executor/gexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/test/gapi_graph_meta_tests.cpp

This PR brings support of generic in-graph metadata in the G-API.
The metadata comes into graph with its input arguments and propagates through the graph then.
The main idea behind this metadata today is to tag every object with extra streaming-related info (e.g., a frame number and a timestamp) to allow app-side data synchronization when `streaming::desync()` feature is used (see tests).
* `cv::GRunArg` is not an alias over `variant<>` anymore, now it is a distinct type;
* `cv::GRunArg` is extended with a metadata dictionary;
* `cv::GCaptureSource` is extended to put the meta information to the captured frames;
* Introduced a generic `streaming::meta<T>(obj, str)` operation which accesses a metadata field `str` of object `obj` and of the given type `T`; its return value is `GOpaque<T>` …

G-API: Introduce runtime in-graph metadata

---

modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/src/api/kernels_imgproc.cpp
modules/gapi/src/backends/cpu/gcpuimgproc.cpp
modules/gapi/test/common/gapi_imgproc_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp

These changes:
- Add `fitLine()` standard kernel
- provide API and documentation:
- to support all the original OpenCV functionality, provide two different API (for 2D and 3D points) with several overloads for both (for input `cv::GMat`, `cv::GArray<Point{2,3}i>`, `cv::GArray<Point{2,3}f>`, `cv::GArray<Point{2,3}d>`)
- support OCV backend
- provide accuracy tests
- comparison function for `cv::Vec<T, n>` provided
``` …
```

[G-API]: fitLine() Standard Kernel Implementation

---

apps/interactive-calibration/parametersController.cpp

Fix typo 'Applicatioin'

---

modules/dnn/test/test_onnx_importer.cpp

@alalek Test_ONNX_layers.Conv1d_variable_weight_bias/1 fails every time, I think it is better to disable it on this device
<cut/>
```
opencv_extra=named_params_onnx
```

Disable Conv1d test on NGRAPH/MYRIAD

---

modules/dnn/test/test_onnx_importer.cpp

dnn(test): skip gather_multi_output test on Myriad

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves #18626
merge with extra opencv/opencv_extra#818
<cut/>
```
```

[ONNX] Added Reduce ops for batch and channel

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/layers/reshape_layer.cpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves https://github.com/opencv/opencv/issues/17914 and https://github.com/opencv/opencv/issues/18072
**merge with extra:** opencv/opencv_extra#798
**Current limitations for fix**: **Expand**,  **Shape** and **ConstantFill** layers are not supported, since their parameters use constBlobs, which are not accessible during allocation of layers memory
There is a problem with loading ONNX networks with input shapes denoted by some string parameter (e.g. "width", "height"). It seems that OpenCV parser replaces these parameters to zeroes by default.
One of the examples is MaskRCNN in #17914  . I believe that converting from PyTorch to ONNX with "dynamic_axes" will produce the same issues.
```
Xopencv_extra=named_params_onnx …
```

Fix problems with loading ONNX networks with parametrized inputs

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/include/opencv2/dnn/version.hpp
modules/dnn/src/model.cpp
modules/dnn/test/test_caffe_importer.cpp

relates #14780
- proxy selected Net methods only (don't derive from Net directly)
- default Model ctor is protected
This refactoring is conservative enough and it doesn't introduce changes in existed code from:
- C++ tests
- C++ samples
- Python bindings tests (no Java tests, BTW)
---
Required for integration of #17570

dnn: fix High-Level public API (cv::dnn::Model class)

---

modules/gapi/test/cpu/gapi_ocv_stateful_kernel_tests.cpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp

Tests failed for standalone centOs build.
<cut/>
Case:
```
try {
setSource(make_src(dataPath))
} catch(...) {
skipTest("Warning!")
}
```
Magic centos commands:
```
```

G-API: Adding a skip for failed streaming tests

---

doc/tutorials/imgproc/erosion_dilatation/erosion_dilatation.markdown
samples/cpp/tutorial_code/ImgProc/Morphology_1.cpp
samples/java/tutorial_code/ImgProc/erosion_dilatation/MorphologyDemo1.java
samples/python/tutorial_code/imgProc/erosion_dilatation/morphology_1.py

[Demo page](http://pullrequest.opencv.org/buildbot/export/pr/17839/docs/db/df6/tutorial_erosion_dilatation.html)
The tutorial for erosion and dilation lack on explanation for java and python. With this PR I want to improve the tutorial by modifying and expanding the information provided. 
This PR addresses the following:
Feedback and opinions about the changes are appreciated. 
<cut/>
Patch to opencv_extra has the same branch name.~ ((not applicable)
```
force_builders=docs
```

Update tutorial for erosion / dilation

---

doc/py_tutorials/py_calib3d/py_epipolar_geometry/py_epipolar_geometry.markdown

Fixes #18847
Code validated. Result matches anticipated.
<cut/>
Rectified Image Pair:
Image Pair:

Fixed issue with Epipolar Geometry Tutorial

---

modules/imgcodecs/CMakeLists.txt
modules/imgcodecs/include/opencv2/imgcodecs/ios.h
modules/imgcodecs/include/opencv2/imgcodecs/macosx.h
modules/imgcodecs/misc/objc/ios/Mat+Converters.h
modules/imgcodecs/misc/objc/ios/Mat+Converters.mm
modules/imgcodecs/misc/objc/macosx/Mat+Converters.h
modules/imgcodecs/src/apple_conversions.h

#18547 introduces `CGImage`<->`Mat` conversion for MacOS platforms. This PR enables the same capabilities for iOS platforms. C++ users can now use `MatToCGImage` and `CGImageToMat` in `ios.h`, and Objc users can now do the equivalent conversions in `Mat+Converters.h`.
I also took the liberty of adding `CF_RETURNS_RETAINED` annotations to methods that return `CGImageRef`, so that the Swift compiler knows to `CFRelease()` when the reference count goes to 0. This is technically a breaking change, as the prior implementation required users to explicitly use `takeRetainedValue()` to properly reference count; however, I think the expectation is that such objects are reference counted by default, so I would categorize the prior behavior as a bug and my changes as a bugfix.
<cut/>
See details at …

Expose CGImage <-> Mat conversion for iOS platforms

---

cmake/FindONNX.cmake

The path to the ORT installation directory was set incorrectly with `DORT_INSTALL_DIR=`. It is a fix for this problem.
test_filter:Custom=*ONNX*

G-API: ONNX. Added small fix for cmake

---

modules/core/include/opencv2/core/persistence.hpp
modules/core/test/test_io.cpp

- Add instructions on how to write unnamed objects with Python-API for writing to sequences.
- Add more information on the typeName-parameter.
- Provide test for using `FileStorage.write()` to write to sequence.
Follow-up to closed PR https://github.com/opencv/opencv/pull/18761

Small improvements to persistence-API doc

---

modules/calib3d/src/sqpnp.cpp

calib3d: eliminate 'register' build warning

---

modules/dnn/src/onnx/onnx_importer.cpp

resolves #18898
The onnx_importer.cpp was causing a Segmentation Fault without an error message when converting newer models like MobileNetV2 that had been converted from PyTorch torchvision using torch.onnx. This occurred with the recent update to OpenCV 4.5.0. The culprit was chased down to an indexing issue in the conversion of the ReduceMean layer. You can see the one line change I made in the code comparison of this commit. My understanding was that the intention was to delete the last two dimensions of the tensor which corresponded to the feature size in order to create the correct size tensor for output by changing the last two dimensions. If that is not the expected behavior, then this code will not fix the issue. However, we did verify that this code will fix the issue if that is …

Fix for index error for Reduce Mean

---

modules/core/src/copy.cpp

The code
```
if (flip_mode < 0)
{
if (size.width == 1)
flip_mode = 0;
if (size.height == 1)
flip_mode = 1;
}
```
above will always override that condition.
<cut/>

Remove unnecessary condition (will never reach)

---

cmake/OpenCVFindLibsPerf.cmake

relates #18699
Failed [nightly CentOS build](http://pullrequest.opencv.org/buildbot/builders/3_4_etc-centos-lin64/builds/41).
Caused by old CMake 2.8.12
```
```

cmake: update condition for find_package(Eigen3 CONFIG)

---

modules/objc/generator/gen_objc.py

Reproducer for this problem:
```
CV_WRAP std::vector< std::vector<Point> > detectTextContours(InputArray frame) const;
```
relates #17570
<cut/>
```
```

objc: fix handling of std::vector<std::vector<T>> return type

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/layers/pooling_layer.cpp
modules/dnn/src/ocl4dnn/src/ocl4dnn_pool.cpp
modules/dnn/test/test_onnx_importer.cpp

Resolves: https://github.com/opencv/opencv/issues/18643
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/820
<cut/>
```
opencv_extra=test_pool1d
```

Support for Pool1d layer for OpenCV and OpenCL targets

---

modules/gapi/test/gapi_graph_meta_tests.cpp

It is a continuation of this: https://github.com/opencv/opencv/pull/18819
Fixes: https://github.com/opencv/opencv/issues/17470
```
```

G-API: Adding skip for GraphMeta tests

---

modules/core/src/ocl.cpp

fix https://github.com/opencv/opencv/issues/18906
add two test cases
I ran `opencv_test_cored.exe --gtest_filter=OCL*` and all passed successfully including the two new test cases
```
[==========] 6837 tests from 60 test cases ran. (267680 ms total)
[  PASSED  ] 6837 tests.
```

fix missing addref() in ocl::Context::create(str)

---

doc/py_tutorials/py_calib3d/py_calibration/py_calibration.markdown

`xrange()` was abandoned and doesn't exist in Python 3. `range()` works as intended

doc: Fix example code using deprecated `xrange` in py_tutorials

---

modules/core/src/matrix_wrap.cpp
modules/core/test/test_mat.cpp

Add checks that prevents indexing an array by negative values (issues were discovered by static code analysis with coverity).

core(matrix): Negative values checks

---

modules/gapi/test/common/gapi_parsers_tests_common.hpp
modules/gapi/test/rmat/rmat_tests.cpp
modules/gapi/test/test_precomp.hpp

Compilation warning (clang):
```
modules/gapi/test/common/gapi_parsers_tests_common.hpp:214:59: warning:
implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-const-int-float-conversion]
it.confidence = static_cast<float>(std::rand()) / RAND_MAX;
~ ^~~~~~~~
/usr/include/stdlib.h:86:18: note: expanded from macro 'RAND_MAX'
#define RAND_MAX        2147483647
^~~~~~~~~~
```

G-API: eliminate std::rand() and RAND_MAX from tests

---

modules/dnn/src/dnn.cpp
modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_model.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

All tests pass on GTX 1080 Ti (cuDNN 7.6.5) and RTX 2080 Ti (cuDNN 7.6.5).
Some tests fail due to non-availability of convolution algorithms on GTX 1050 (cuDNN 8.0.5). These cannot be fixed as it's a cuDNN issue.
```
[  FAILED  ] 9 tests, listed below:
[  FAILED  ] Test_ONNX_layers.Convolution3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_ONNX_layers.Convolution3D_bias/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_ONNX_layers.PoolConv3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_ONNX_nets.Resnet34_kinetics/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.Convolution3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.concat_3d/1, where GetParam() = CUDA/CUDA_FP16
```
```
C++ exception with …
```

cuda4dnn: enable fusion tests, update thresholds, fix eltwise fusion regression

---

modules/gapi/test/cpu/gapi_ocv_stateful_kernel_test_utils.hpp
modules/gapi/test/gapi_array_tests.cpp
modules/gapi/test/gapi_opaque_tests.cpp

G-API(test): avoid anonymous namespace types as template parameters

---

modules/gapi/src/executor/gstreamingexecutor.cpp

* There are two `handleNewStream()` calls performed in `GStreamingExecutor::setSource()`, removed one of them (https://github.com/opencv/opencv/blob/master/modules/gapi/src/executor/gstreamingexecutor.cpp#L1258 remains)
```
```

Removed redundant call of handleNewStream in streaming executor

---

modules/gapi/include/opencv2/gapi/garray.hpp
modules/gapi/include/opencv2/gapi/gcommon.hpp
modules/gapi/include/opencv2/gapi/gkernel.hpp
modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/include/opencv2/gapi/opencv_includes.hpp
modules/gapi/include/opencv2/gapi/own/types.hpp
modules/gapi/include/opencv2/gapi/s11n.hpp
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/shadow_gapi.hpp
modules/gapi/misc/python/test/test_gapi_core.py
modules/gapi/misc/python/test/test_gapi_imgproc.py
modules/gapi/misc/python/test/test_gapi_sample_pipelines.py
modules/gapi/misc/python/test/test_gapi_streaming.py
modules/gapi/src/api/gcomputation.cpp
modules/gapi/src/backends/common/serialization.cpp
modules/gapi/src/compiler/gcompiled_priv.hpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/src/compiler/gstreaming.cpp
modules/gapi/src/compiler/gstreaming_priv.hpp
modules/gapi/test/own/gapi_types_tests.cpp

* Added struct `GTypeInfo` which stores `GShape` & `GKind`.
* Implemented function `collectInfo` which collect `GTypeInfo` from input/output node handles in the `ade::Graph`, such kind of information are needed to:
* Properly allocate outputs ( Python `GComputation.apply()` doesn't take output args, so need to allocate their inside)
* Properly extract inputs ( Need to know how to represent values coming from python. Example: If we have tuple contains 4 values and can be represented as `cv::Scalar` or `cv::Rect`) 
* Added `CV_POINT2F` to `GKind` to handle `GArray<cv::Point2f>`
* Wrapped `GGoodFeatures` operation
* Wrapped `GArray<cv::Point2f>` as …

[G-API] Wrap GArray

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/gmat.hpp
modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/src/api/gmat.cpp
modules/gapi/src/api/kernels_core.cpp
modules/gapi/src/backends/cpu/gcpucore.cpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp

These changes:
- Add `kmeans()` standard kernel
-  provide API and documentation - 4 overloads:
- standard `GMat` - for any dimensionality
- `GMat` without bestLabels initialization for convenience
- `GArray<Point2f>` - for 2D
- `GArray<Point3f>` - for 3D
- support OCV backend
- Accuracy tests:
- for every input - 2 tests
1) without initializing. In this case, no comparison with cv::kmeans is done as kmeans uses random auto-initialization
2) with initialization
- in both cases, only 1 attempt is done as after first attempt kmeans initializes bestLabels randomly
```
build_gapi_standalone:Linux …
```

[G-API]: kmeans() Standard Kernel Implementation

---

modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/include/opencv2/gapi/video.hpp
modules/gapi/src/api/kernels_video.cpp
modules/gapi/src/backends/cpu/gcpuvideo.cpp
modules/gapi/test/common/gapi_video_tests.hpp
modules/gapi/test/common/gapi_video_tests_common.hpp
modules/gapi/test/common/gapi_video_tests_inl.hpp
modules/gapi/test/cpu/gapi_video_tests_cpu.cpp

New BackgroundSubtractor kernel represents 2 types of operation such as:
- Background Subtractor MOG2 (default);
- Background Subtractor KNN
<cut/>
Published for review on 27th of October. 
@dmatveev , @OrestChura , please take a look.
```
force_builders_only=linux,docs,Custom
Xforce_builders=Custom,Custom Win,Custom Mac,Linux32,Win32 …
```

GAPI: New BackgroundSubtractor stateful kernel

---

platforms/apple/build_xcframework.py

- make happy old Python linters
<cut/>
Error message ( `/usr/bin/flake8 (ver: 2.5.4)` ):
```
./platforms/apple/build_xcframework.py:13:113: E901 SyntaxError: invalid syntax
assert sys.version_info >= (3, 6), f"Python 3.6 or later is required! Current version is {sys.version_info}"
^
1
1       E901 SyntaxError: invalid syntax
```
relates #18826
/cc @colejd
<cut/>
```
```

apple/build_xcframework.py: python syntax

---

modules/python/package/cv2/__init__.py

resolves #18502
- multiprocessing need to start from bootstrap code
- loading may fail due to missing os.add_dll_directory() calls

python: restore sys.path in bootstrap()

---

modules/videoio/src/cap_mjpeg_decoder.cpp
modules/videoio/test/test_video_io.cpp

Relates to: https://github.com/opencv/opencv/pull/18966
<cut/>
```
```

Added test for VideoCapture CAP_PROP_FRAME_MSEC option

---

modules/gapi/test/executor/gtbbexecutor_internal_tests.cpp

The test has race condition, which is addressed by the patch. 
The race is next: 
1. Master thread is calling `execute` (effectively blocked, waiting for callback to be called)
2. "Async" thread picks up the callback 
3. Call the callback
4. Then sets the variables in test
5. After call back is called, master thread is unblocked and may check the variables (set in point 4 by the "async" thread) earlier then they actually changed 
Changes:
- callback should be called as the last step (after flag variables are
set), as it effectively unblock the master thread
fixes #18974

TBB executor for GAPI: fix race consition in Async test

---

modules/dnn/src/layers/pooling_layer.cpp

My previous PR https://github.com/opencv/opencv/pull/18862/ was merged to ```master``` branch and this created problems with enabled ```HAVE_VULKAN``` option, which is not present in ```3.4``` branch
```
build_image:Custom=ubuntu-vulkan:16.04
```

Fix build when HAVE_VULKAN is ON

---

platforms/ios/run_tests.py

Splitting this out into a standalone PR, based on the initial work here: https://github.com/opencv/opencv/pull/18925
Xcode 12 no longer supports building to deployment targets earlier than 9.0, which triggers a warning, and possible failure when treating warnings as errors.

Increase testing IPHONEOS_DEPLOYMENT_TARGET to 9.0

---

modules/gapi/src/executor/gasync.cpp

GAPI: reuse copy_through_move_t in the gasync.cpp file
opencv#17851 introduced separate header for `copy_through_move_t`. This PR removes it's local duplicate in gasync.cpp to reuse one from the header
<cut/>
```
```

GAPI: Reuse move through copy

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/model.cpp
modules/dnn/test/test_model.cpp

In the detect function in modules/dnn/include/opencv2/dnn/dnn.hpp, whose implementation can be found at modules/dnn/src/model.cpp, the Non Max Suppression (NMS) is applied only for objects of the same label. Thus, a flag
was added with the purpose to allow developers to choose if they want to keep the default implementation or wether they would like NMS to be applied to all the boxes, regardless of label.
The flag is called nmsDifferentLabels, and is given a default value of false, which applies the current default implementation, thus allowing existing projects to update opencv without disruption
resolves #18832 
The following image is from the MSCOCO dataset and the predictions were generated using YoloV4 trained on the MSCOCO dataset (weights here: …

Add option for NMS for boxes with different labels

---

modules/gapi/include/opencv2/gapi/infer.hpp
modules/gapi/src/api/ginfer.cpp

- explicitly declared default constructor
- made initilizer_list  constructor to accept the list by copy
   -- as it is  more canonical (and as copying the initializer_list does
not force copy of the list items)
   -- current version anyway does not do what it is intended to
(fixes #17385)

GAPI: fix C++17 compilation errors in GNetPackage 

---

modules/core/include/opencv2/core/cv_cpu_dispatch.h
modules/core/include/opencv2/core/hal/intrin.hpp
modules/core/include/opencv2/core/hal/intrin_rvv.hpp
platforms/linux/riscv64-gcc.toolchain.cmake

This PR From GSoC Project "Optimize OpenCV for RISC-V"
The main objective of the project is adding implementation of OpenCV wide universal intrinsics for RISC-V vector in OpenCV Hardware Acceleration Layer (HAL).
This PR is now working in progress.
Following two previous PRs mainly provided the toolchain files for cross-compiling OpenCV with target riscv64 on Linux platform. The first PR is with Clang and the second is with riscv-gnu-toolchain.
https://github.com/opencv/opencv/pull/17922
https://github.com/opencv/opencv/pull/18227
Added toolchain file for target `riscv64-clang`.
Added toolchain file for target `riscv64-gcc`.
Added universal intrinsics implementation with RISC-V vector extension.
Added some native intrinsics in C++ that are unsupported by compiler temporarily.
Universal …

Universal intrinsics implementation with RISC-V vector extension

---

platforms/linux/riscv64-clang.toolchain.cmake

In the upstream LLVM, the current convention uses `-march=rv64gcv0p9 -menable-experimental-extensions` as an option for clang to enable the latest 0.9 version RISC-V vector extension.

Modified rvv option for clang to match LLVM upstream

---

modules/objc/generator/gen_objc.py

Splitting this out into a standalone PR, based on the initial work here: https://github.com/opencv/opencv/pull/18925
This patch prevents a symbol conflict between types `Point`/`Rect`/`Size` and those provided by `Darwin`:
```
/Users/chrisbal/Documents/opencv/.build/x86_64-apple-macosx/debug/opencv2.framework/Modules/opencv2.swiftmodule/x86_64-apple-macos.swiftinterface:676:81: error: ambiguous type name 'Rect' in module 'opencv2'
public func detectMultiScale(img: opencv2.Mat, foundLocations: inout [opencv2.Rect], foundWeights: inout [Swift.Double], hitThreshold: Swift.Double)
~~~~~~~ ^
opencv2.Rect:1:12: note: found candidate with type 'Rect'
open class Rect : NSObject {
^
Darwin.Rect:1:15: note: found candidate with type 'Rect'
public struct Rect {
```
I provided backwards compatibility …

Fix Darwin collision of Point/Rect/Size types

---

modules/core/src/norm.cpp

The most of target machine use one type cpu unit resource
to execute some one type of instruction, e.g.
all vx_load API use load/store cpu unit,
and v_muladd API use mul/mula cpu unit, we interleave
vx_load and v_muladd to improve performance on most targets like
RISCV or ARM.
- [Y] I agree to contribute to the project under Apache 2 License.
- [Y] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [Y] The PR is proposed to proper branch
- [N] There is reference to original bug report and related work
- [N] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
Patch to …

norm.cpp(normL2Sqr_): improve performance of pipeline

---

modules/core/src/count_non_zero.dispatch.cpp

resolves #17453
relates #17455
Reproduced even on Linux with `OPENCV_IPP=sse42`
(MacOSX and Win32 platforms doesn't have AVX2 IPP optimizations)
/cc @eplankin

core(IPP): disable SSE4.2 code path in countNonZero()

---

modules/core/include/opencv2/core/quaternion.hpp
modules/core/include/opencv2/core/quaternion.inl.hpp
modules/core/test/test_quaternion.cpp

I found that many papers directly write a number plus a quaternion. 
It has to write like this
```
double number = 2.0;
Quatd q{1, 2, 3, 4};
Quatd ans = Quatd(number,0,0,0) + q;
```
which is too much trouble for users. So adding this operations may be friendly and convenience

Add adding and subtraction operations between a number and a quaternion;

---

modules/videoio/src/cap_msmf.cpp
modules/videoio/test/test_camera.cpp
modules/videoio/test/test_video_io.cpp

When using `cv::VideoCapture` by index on Windows with MS Media Foundation (`cv::CAP_MSMF`), the field `cv::CAP_PROP_POS_MSEC` always returns 0.
This PR makes an unused timestamp parameter from the `IMFSourceReaderCallback::OnReadSample(...)` interface available through `cv::VideoCapture::get(cv::CAP_PROP_POS_MSEC)`.

Add live timestamps to MSMF Video API

---

.github/workflows/arm64-build-checks.yml

relates #17989
This is just an example, no need to run it always.
- https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
- https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#manual-events

github(actions): manual trigger for arm64-build-checks.yml

---

cmake/OpenCVModule.cmake
modules/python/bindings/CMakeLists.txt

Currently only `python_bindings_generator` is properly handled.
Other cases (java, obj, +added js) may not work.
In case of #18965 (js) we have this order:
```
OPENCV_MODULES_BUILD=opencv_core;opencv_imgproc;opencv_js_bindings_generator;opencv_python_tests;opencv_video;opencv_dnn;opencv_features2d;opencv_calib3d;opencv_objdetect;opencv_js
```
(dnn module is not processed before `opencv_js_bindings_generator` - this is necessary to fill `*_opencv_dnn_HEADERS` variable)
<cut/>
```
force_builders_only=linux
#,Custom,Custom Mac
```

cmake: fix processing order of <wrapper>_bindings_generator

---

modules/calib3d/test/test_cornerssubpix.cpp
modules/calib3d/test/test_fisheye.cpp
modules/imgproc/test/test_drawing.cpp
modules/ts/include/opencv2/ts/ts_ext.hpp
modules/ts/src/ts.cpp

OpenCV tests should not write any test results by default.
However sometimes it is useful to collect extra information for problem investigation (test failure).
- on devices/configurations without properly configured debugger
- on devices where compilation is not available (cross-compilation case) to modify test code or replace `#if 0`
Available options:
- `--test_debug` / `--test_debug=N`
- `OPENCV_TEST_DEBUG` environment variable
- variable `cvtest::debugLevel`
---
**Note**: Use debug mode for "debugging" single test case only. There is no requirement for unique filenames (`result.png` / `test.png` is a common practice).
**Note**: Use `imshow()` for debug levels >= 10 (to avoid test crashes due to lack of UI backend).

ts: cvtest::debugLevel / --test_debug=<N> option

---

samples/dnn/scene_text_detection.cpp

- GCC 4.8.5 doesn't support regex
resolves #19016
relates #17570
```
test_modules:Custom=none
```

samples: replace regex

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/backend_plugin.cpp
modules/videoio/src/cap_ffmpeg.cpp
modules/videoio/src/cap_gstreamer.cpp
modules/videoio/src/cap_interface.hpp
modules/videoio/src/cap_mfx_plugin.cpp
modules/videoio/src/cap_msmf.cpp
modules/videoio/src/cap_ueye.cpp
modules/videoio/src/plugin_api.hpp
modules/videoio/test/test_gstreamer.cpp

See #14035 for a companion PR to add CV_16UC1/GRAY16_LE capture support. I'm new to test writing, but added one that seems to make sense. I'm not clear if all PRs are still supposed to be based off 3.4, but I ran into roadblocks trying to build 3.4 at all, master just worked so easily.
<cut/>
```
test_modules:Custom=videoio,python2,python3,java
```

Add CV_16UC1/GRAY16_LE support to GStreamer backend for VideoWriter

---

modules/dnn/include/opencv2/dnn/dnn.inl.hpp
modules/gapi/include/opencv2/gapi/util/optional.hpp

**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/2775
- GCC 4.8.5 / CentOS 7
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master_etc-centos-lin64/builds/44)
<cut/>
```
/build/master_etc-centos-lin64/opencv/modules/core/include/opencv2/core/utility.hpp:1004:9: warning: 'paramCoeff.cv::dnn::dnn4_v20201117::DictValue::<anonymous>.cv::dnn::dnn4_v20201117::DictValue::<anonymous union>::pi' may be used uninitialized in this function [-Wmaybe-uninitialized]
/build/master_etc-centos-lin64/opencv/modules/core/include/opencv2/core/utility.hpp:1004:9: warning: 'param.cv::dnn::dnn4_v20201117::DictValue::<anonymous>.cv::dnn::dnn4_v20201117::DictValue::<anonymous union>::pi' may be used uninitialized in this function [-Wmaybe-uninitialized] …
```

build warnings

---

cmake/OpenCVUtils.cmake

`ocv_cmake_dump_vars()` macro scans all available CMake variables.
Lets avoid that in trace mode because this generates huge logs.
Usage: `cmake . --trace-expand -DCMAKE_TRACE_MODE=1`
Log size reduction: 837275957 => 44462513 (837 Mib => 44 Mib)
<cut/>
```
$ cmake . --trace-expand >/tmp/trace.log 2>&1
$ ll /tmp/trace.log
-rw-rw-r-- 1 alalek alalek 837275957 Dec  5 13:32 /tmp/trace.log
$ cmake . --trace-expand -DCMAKE_TRACE_MODE=1 >/tmp/trace.log 2>&1
$ ll /tmp/trace.log
-rw-rw-r-- 1 alalek alalek 44462513 Dec  5 13:32 /tmp/trace.log
```

cmake: avoid excessive output from cmake --trace/--trace-expand

---

modules/core/CMakeLists.txt
modules/core/include/opencv2/core/utils/allocator_stats.impl.hpp

- don't use OPENCV_ALLOCATOR_STATS_COUNTER_TYPE definition in non C++11 builds
- don't use with MinGW: #16990 and duplicates
relates #16786

core: update handling of allocator stats type

---

modules/videoio/src/cap_gstreamer.cpp
modules/videoio/test/test_video_io.cpp

- CAP_PROP_POS_MSEC is not reliable
resolves #19025
<cut/>
```
buildworker:Custom=linux-1,linux-2
test_modules:Custom=videoio,python2,python3,java
```

videoio(test): skip GStreamer in 'frame_timestamp' tests

---

modules/core/perf/perf_allocation.cpp
modules/core/src/alloc.cpp

Fixes program startup unsafe thread behavior of the core memory allocator `fastMalloc()` and
deallocator `fastFree()` from issue https://github.com/opencv/opencv/issues/19004 and adds performance test case.
Summary: The code works as expected on below tested platforms. I do not see any
consistent performance gains or losses.
🚨Please note: this PR is *only* for OpenCV 4 and newer. This fix *requires*
a C++11 compliant compiler. Do not apply this exact code to the 3.x codebase since
that code might be compiled on an older C++98 compiler. Only C++11 or newer
promises thread-safe initialization of static local variables
https://en.cppreference.com/w/cpp/language/storage_duration#Static_local_variables.
Such a variable is low cost, will only initialize once, handles exceptions, and
threads …

add thread-safe startup of fastMalloc and fastFree

---

modules/gapi/perf/common/gapi_video_perf_tests_inl.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/common/gapi_video_tests_common.hpp
modules/gapi/test/common/gapi_video_tests_inl.hpp

These changes move G-API output to the first place of arguments in comparison functions in some tests to make them consistent and eliminate warnings from coverity tool.
@alalek 's [comment reference](https://github.com/opencv/opencv/pull/18857#discussion_r537888168).
With the changes in indicated `kmean`'s tests, I'm taking courage to edit older but similar places in code I introduced some time ago.
``` …
```

[G-API]: Fix coverity warnings

---

modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java

resolves #16861
To unblock development of derived classes.
Any sample is out of scope for now.

android: use protected fields in JavaCamera2View

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/include/opencv2/gapi/video.hpp

These changes remove: 
- multiple return
- multiple notes
relates #18963
<cut/>
```
```

[G-API] Multiple return/note fix

---

modules/core/include/opencv2/core/ocl.hpp

Fix opencv/opencv#18888 by clarifying doc for two APIs of `OpenCLExecutionContext`

clarify opencl execution context doc

---

modules/dnn/src/layers/resize_layer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/825
Fixes #18721: TF resize bilinear upsampling layer shift
Added ``half_pixel_centers`` parameter to cover ``align_corners=False, half_pixel_centers=True`` case for TF  [resize_bilinear](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/image/resize_bilinear).
<cut/>
``` …
```

Added TF resize_bilinear behaviour alignment

---

modules/core/include/opencv2/core/hal/intrin_wasm.hpp

resolves #18097
/cc @vrabaud @huningxin @lionkunonly
<cut/>
```
force_builders=linux,docs,Custom
```

JS(WASM): use fallback on missing intrinsics in Emscripten 2.0.0+

---

modules/dnn/src/caffe/opencv-caffe.proto

Allow to load `opencv_face_detector` model with external protobuf.
Builtin protobuf has patch with support for "custom" properties.
Validation instructions:
- `cmake -DBUILD_PROTOBUF=OFF -DPROTOBUF_UPDATE_FILES=ON ...`
- `./bin/opencv_test_dnn --gtest_filter=*opencv_face*`
**Note**: .pb.cc / .pb.h files are not updated (not necessary and this update is large enough)
relates #18702

dnn(caffe): add DetectionOutputParameter.clip to .proto file

---

modules/videoio/src/cap_gstreamer.cpp

Disabled synchronization with video stream rate for file/URI input in GStreamer VideoCapture backend. By default video decoding is performed with same rate as file FPS and manual pipeline configuration was required to avoid it.
related(?): #5766
Note: did not test it with cameras (v4l2://) and network streams (rstp://, http://, etc.).

videoio: turn off synchronized sink in GStreamer

---

platforms/apple/build_xcframework.py

This PR fixes a bug found by @vade [here](https://github.com/opencv/opencv/pull/18826#issuecomment-742748803). It was introduced in 69e1167882a8145bfcc2ba3a89fcdc23ee8b7913. This PR fixes that bug.
I also found another issue that prevents the use of absolute paths when assembling the xcframework, so I've also included a fix for that.
```
force_builders_only=docs,ios,Custom Mac
```

Fix path resolution bugs for XCFramework builds

---

modules/imgproc/src/smooth.simd.hpp

env:
Parallel framework: pthreads (nthreads=8)
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
<cut/>
Measured performance of `GaussianBlur(src, dst, Size(7,7), 0, 0, btype)`.
Conventional perftests (3x3 and 5x5) are not improved because these are already optimized in 698b2bf.
| name | image size, type, btype | mean (usec) in 3.4 | mean (usec) in this PR |
gaussianBlur7x7/0| 	(640x480, 16UC1, BORDER_REPLICATE) | 358 |100
gaussianBlur7x7/1 |	(640x480, 16UC1, BORDER_CONSTANT)| 351|97
gaussianBlur7x7/2 |	(640x480, 16UC1, BORDER_REFLECT) 	| 605|100
gaussianBlur7x7/3 |	(640x480, 16UC1, BORDER_REFLECT101)| 694|100
gaussianBlur7x7/4 |	(1280x720, 16UC1, BORDER_REPLICATE) |2081|343
gaussianBlur7x7/5 |	(1280x720, 16UC1, BORDER_CONSTANT)| 1219|489 …

support SIMD for larger symmetric Bit-exact 16U gaussian blur

---

CMakeLists.txt
platforms/ios/build_framework.py
platforms/osx/build_framework.py

This PR addresses #19014 
- remove obsolete check for Cmake version 3.0 or greater when using Xcode 4.3 or greater
- add .py script check for Cmake version 3.19 or greater when build for iOS with Xcode 12.2 or greater
- add .py script check for Cmake version 3.17 or greater when build for macOS or build for iOS with Xcode 12.1 or lower

Check for CMake 3.19 if Xcode version is 12.2 or higher

---

modules/dnn/src/layers/resize_layer.cpp
modules/dnn/test/test_tf_importer.cpp

Relates to OpenCV issue #18721
Merge with extra: opencv/opencv_extra#830
Added support of TF nearest neighbour resize cases: ``align_corners=False, half_pixel_centers=True``,  ``align_corners=True, half_pixel_centers=False``.
```
```

Added TF nearest neighbour resize behaviour alignment

---

platforms/android/gradle-wrapper/gradle/wrapper/gradle-wrapper.properties

resolves #19047
Upgrade to the latest Gradle 6.7.1 failed with build errors:
<cut/>
```
Failed to notify project evaluation listener.
'org.gradle.api.file.RegularFileProperty org.gradle.api.file.ProjectLayout.fileProperty(org.gradle.api.provider.Provider)'
java.lang.NoSuchMethodError: 'org.gradle.api.file.RegularFileProperty org.gradle.api.file.ProjectLayout.fileProperty(org.gradle.api.provider.Provider)
```

android: use gradle 5.6.4

---

3rdparty/protobuf/CMakeLists.txt

resolves #17282
Adds into OpenCVModules.cmake:
```
set_target_properties(libprotobuf PROPERTIES
INTERFACE_LINK_LIBRARIES "-landroid;-llog"
)
```

android: add -llog for libprotobuf

---

CMakeLists.txt

- NEON / ANDROID_ARM_NEON are toolchain-specific flags
- they are usually not defined for native builds
- let work CPU_BASELINE=DETECT properly
resolves #18244
**WIP**

(3.4) cmake: don't define ENABLE_NEON flags in non-cross-compiling mode

---

CMakeLists.txt

- NEON / ANDROID_ARM_NEON are toolchain-specific flags
- they are usually not defined for native builds
- let work CPU_BASELINE=DETECT properly
resolves #18244
relates #19054
**WIP**

(4.x) cmake: don't define ENABLE_NEON flags in non-cross-compiling mode

---

modules/flann/include/opencv2/flann/miniflann.hpp

- due to lifetime restrictions on passed 'features' parameter and its dangling pointers
- dangling pointer issue is fixed for OpenCV 4.5.1+
Added a note for C++ coders about limitations (but it is not in scope of Doxygen documentation).
Consider using `FlannBasedMatcher` instead.
relates #17553
fix for 4.5.1+: #19045
related commit: https://github.com/opencv/opencv/commit/562914e33bea921a0a235fbf2b6bba6830644e16 (Jul 13, 2011)

(3.4) flann: drop wrapping of Index class

---

cmake/OpenCVFindMKL.cmake

- allow to specify `MKL_LIBRARIES` through command-line (to support custom cases)
- added `MKL_USE_SINGLE_DYNAMIC_LIBRARY=ON` mode
resolves #17870

cmake: update MKL library searching

---

modules/gapi/test/streaming/gapi_streaming_tests.cpp

Relates to: [#19009](https://github.com/opencv/opencv/pull/19009)
```
Xbuild_image:Custom=ubuntu-openvino-2021.1.0:20.04 …
```

[G-API]: Fix new streaming tests for CI

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/calibinit.cpp
modules/calib3d/src/circlesgrid.cpp
modules/calib3d/test/test_chesscorners.cpp

- detect case with infinite loop and raise NoConv exception
- handle such exception
- add support for case with missing `blobDetector` (image contains Point2f array of candidates)
- add regression test
- undone rectification for "failed" detections too
- drop redirectError() usage
resolves #18713
related commit: https://github.com/opencv/opencv/commit/f8e9f65ea84eab534456e22ebafb44860e05bc10 (Feb 7, 2011)

calib3d: fix findCirclesGrid hang

---

doc/js_tutorials/js_setup/js_usage/js_usage.markdown

While going thru the opencv.js tutorial, I've noticed a typo.

Fix a typo s/VERISON/VERSION/ in opencv.js tutorial

---

modules/gapi/perf/common/gapi_imgproc_perf_tests.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_imgproc_perf_tests_cpu.cpp
modules/gapi/test/common/gapi_imgproc_tests.hpp

Performance tests for 5 new color conversion kernels:
- BGR2RGB
- BGR2I420
- RGB2I420
- I4202BGR
- I4202RGB
``` …
```

[G-API]: Performance tests for color conversion kernels

---

modules/videoio/test/test_main.cpp

- configure through `OPENCV_TEST_VIDEOIO_BACKEND_REQUIRE_FFMPEG` environment variable

videoio(test): add FFmpeg backend check

---

modules/gapi/include/opencv2/gapi/streaming/format.hpp
modules/gapi/src/backends/common/gbackend.hpp
modules/gapi/src/backends/streaming/gstreamingbackend.cpp
modules/gapi/src/backends/streaming/gstreamingbackend.hpp
modules/gapi/src/backends/streaming/gstreamingkernel.hpp

[G-API] GStreamingBackend hotfix

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/test/test_fisheye.cpp

Added '@ref' to enumerations to enable doxygen checks in Camera Calibration and 3D Reconstruction documentation.
Replaces #18872
<cut/>
**Notes**:
* Did not check enumerations with '#'. 
* Could not add `@ref` to enumerations in `@code` blocks.
**Observations** (not addressed)
* stereoCalibrate(...) and fisheye::stereoCalibrate(...) has random '?' in description? [See here](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga91018d80e2a93ade37539f01e6f07de5) and [here](https://docs.opencv.org/3.4/db/d58/group__calib3d__fisheye.html#gadbb3a6ca6429528ef302c784df47949b)
_CALIB_FIX_INTRINSIC Fix cameraMatrix? and distCoeffs? so that only R, T, E, and F matrices are estimated._
* fisheye::stereoCalibrate() has no enumeration option CALIB_ZERO_DISPARITY. [See …

Added '@ref' to 3.4 Camera Calibration and 3D Reconstruction documentation

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/include/opencv2/gapi/streaming/format.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp
modules/gapi/src/api/kernels_core.cpp
modules/gapi/src/api/kernels_streaming.cpp
modules/gapi/src/backends/cpu/gcpucore.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/ocl/goclcore.cpp
modules/gapi/src/backends/streaming/gstreamingbackend.cpp
modules/gapi/src/backends/streaming/gstreamingbackend.hpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/src/compiler/gislandmodel.cpp
modules/gapi/src/executor/gexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/test/cpu/gapi_core_tests_fluid.cpp
modules/gapi/test/gpu/gapi_core_tests_gpu.cpp
modules/gapi/test/internal/gapi_int_island_fusion_tests.cpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp

* Added generic copy kernel
* Moved RMat wrapping on the inputs to StreamInput to eliminate a difference between GIslandExecutable::run() overloads (the streaming one didn't have computation inputs wrapped)
```
test_modules:Custom=gapi,python2
```

Generic copy kernel

---

modules/core/include/opencv2/core/ocl.hpp
modules/core/src/ocl.cpp
modules/core/src/opengl.cpp

- to avoid crash with old OpenCL runtimes
resolves #5209

core(opencl): add version check before clCreateFromGLTexture() call

---

modules/core/test/test_misc.cpp
modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/tensorflow/tf_importer.cpp

The character literal overload is more efficient. More info at:
http://clang.llvm.org/extra/clang-tidy/checks/performance-faster-string-find.html

Optimize calls to std::string::find() and friends for a single char.

---

doc/tutorials/introduction/windows_install/windows_install.markdown

Ref: https://forum.opencv.org/t/install-error-for-visual-studio-2019-cmake-error-could-not-create-named-generator-visual-studio-16-2019-win64/144
relates #9514
/cc @LaurentBerger 
```
```

doc(windows): update how to handle MSVS 2019

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/src2/cv2.cpp
modules/python/test/test_misc.py

If provided `PyObject` can't be converted to string `TypeError` is  reported instead of `SytemError` without any message.
Partially resolves #18835. but doesn't resolve problem with overload selection in general.

fix: conversion to string in python bindings

---

modules/calib3d/include/opencv2/calib3d.hpp

docs(calib3d): avoid reference on legacy C API constants

---

modules/photo/test/test_hdr.cpp

Fixes: https://github.com/opencv/opencv/issues/19124

Increased Photo_CalibrateDebevec.regression test tolerance to pass on arm64 with gcc 9.3.

---

modules/js/generator/embindgen.py

- avoid randomized output due to unpredictable dict/set order
```
```

JavaScript: robust code generation

---

cmake/templates/opencv_abi.xml.in

- this API is experimental for now (under active development)

ABI: exclude quaternion header from ABI/API check

---

modules/core/src/matmul.simd.hpp

Performance uplift (x-factor) ranges from 2.20 to 2.50, on the following perf tests of the core module:
1. `Mat_Transform::Size_MatType`
2. `Transform::OCL_TransformFixture`
The associated issue is #19163.
- [ X ] I agree to contribute to the project under Apache 2 License.
- [ X ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ X ] The PR is proposed to proper branch
- [ X ] There is reference to original bug report and related work

[cv::transform] Enable CV_SIMD for the 16U case on AArch64.

---

doc/Doxyfile.in

Doxygen 1.8.20 warning:
```
warning: Tag 'TCL_SUBST' at line 70 of file 'opencv/doc/Doxyfile' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
```

doxygen: drop deprecated TCL_SUBST

---

modules/js/generator/embindgen.py

- class_info.props is a 'list'
relates #19161
Error message:
```
TypeError: '<' not supported between instances of 'ClassProp' and 'ClassProp'
```
<cut/>
```
force_builders=docs,Custom
```

JavaScript(build): fix generator with Python3

---

modules/core/include/opencv2/core/version.hpp

OpenCV 3.4.13
relates #18824
<cut/>
<details>
[opencv_world3413.dll (vc14)](https://www.virustotal.com/gui/file/6c5578b9774d1c659db300091b4a8e159535a878df6861e81d2fcdfa8b8dc0af/detection)
[opencv_world3413d.dll (vc14)](https://www.virustotal.com/gui/file/ec470aba9a856908c9336955bad526d2b8f02d8db43aaa9689b6f79101f75b02/detection)
[opencv_world3413.dll (vc15)](https://www.virustotal.com/gui/file/195c972e39e4df9901405d5edfbe4a5826f642d4c64afbe14aca4e10e73af588/detection)
[opencv_world3413d.dll (vc15)](https://www.virustotal.com/gui/file/0a03d40e96f6435154e3d45dbeca823f6af68641cef6ccb95d688193dd42b0c1/detection)
[opencv_ffmpeg3413_64.dll](https://www.virustotal.com/gui/file/2abd4c09ef76e913bde03929d8a0c31b5515772f682551acb43a2914d4bd42d0/detection) …

release: OpenCV 3.4.13

---

modules/gapi/src/executor/gexecutor.cpp

GFrame as internal node in GExecutor

---

modules/core/include/opencv2/core/version.hpp

OpenCV 4.5.1
relates #18825
<cut/>
<details>
[opencv_world451.dll (vc14)](https://www.virustotal.com/gui/file/6349298e6c189b72c230cf28cc2b289bed73877739888a0c427a8a6e0105c2b1/detection)
[opencv_world451d.dll (vc14)](https://www.virustotal.com/gui/file/44cd5dcf7f4dfdb598c954a647a81bc05713d4bab091d35b54b1e660bb24926b/detection) 
[opencv_world451.dll (vc15)](https://www.virustotal.com/gui/file/3003615e050fe164d5d740de7019d69858436fbcd6cb1e6eed668b640f8757e0/detection)
[opencv_world451d.dll (vc15)](https://www.virustotal.com/gui/file/1297d89e05513cad66f2cba8719b95b6613554ba38507da5940e85c2d4bafc46/detection)
[opencv_ffmpeg451_64.dll](https://www.virustotal.com/gui/file/e5b3be3fa9d73ff07b3b78bb97bab21b8628315a2d8efcdbce36179a11333a4d/detection) …

release: OpenCV 4.5.1

---

modules/core/src/ocl.cpp

Fixes https://github.com/opencv/opencv/issues/19132
* Remove errant assignment in `getOpenCLAllocator_()`
* Rename variable in the 4 places from g_isOpenCVActivated to g_isOpenCLActivated
Tests are successful. Here is output of `opencv_test_cored.exe`. The 4 test fails are unrelated.
```
[ SKIPSTAT ] 34 tests skipped
[ SKIPSTAT ] TAG='mem_6gb' skip 1 tests
[ SKIPSTAT ] TAG='skip_bigdata' skip 1 tests
[ SKIPSTAT ] TAG='skip_other' skip 32 tests
[==========] 11608 tests from 245 test cases ran. (417470 ms total)
[  PASSED  ] 11604 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] Core_InputOutput.filestorage_base64_basic_read_XML
[  FAILED  ] Core_InputOutput.filestorage_base64_basic_read_YAML
[  FAILED  ] …
```

remove g_isOpenCVActivated errant assign and clarify variable

---

modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp
modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.hpp
modules/imgcodecs/src/loadsave.cpp
modules/imgcodecs/test/test_grfmt.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/833
Fixes #19083
<cut/>
```
```

OpenJPEG: decoder for J2K codestreams

---

modules/js/src/make_umd.py

resolves #19198
```
force_builders=docs,Custom
```

JavaScript: fix Python 3 support in make_umd.py

---

platforms/js/build_js.py

- don't switch between Python versions in the middle of the build
relates #19207
<cut/>
```
force_builders=linux,docs,Custom
```

JavaScript(build): reuse Python executable used to run main script

---

modules/gapi/test/infer/gapi_infer_ie_test.cpp

Reopen of https://github.com/opencv/opencv/pull/18913
These changes:
- Replace plugin config parameters with the working ones
- Refactor for consistency
``` …
```

[G-API]: IE tests pluginConfig fix & refactoring

---

modules/gapi/src/backends/onnx/gonnxbackend.cpp
modules/gapi/test/infer/gapi_infer_onnx_test.cpp

```
force_builders=Custom, Custom Win, Custom Mac
build_image:Custom Win=ubuntu-onnx:20.04
build_image:Custom Mac=ubuntu-onnx:20.04
```

G-API: Support GFrame for ONNX infer 

---

modules/gapi/cmake/standalone.cmake
modules/gapi/src/backends/streaming/gstreamingbackend.cpp
modules/gapi/src/backends/streaming/gstreamingbackend.hpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/src/executor/gstreamingexecutor.cpp

[G-API] Fix streaming kernels in standalone 

---

modules/core/include/opencv2/core/version.hpp
modules/imgcodecs/src/loadsave.cpp

Hi, OpenCV Team
This PR tries to fix https://github.com/opencv/opencv/issues/12818 on branch 3.4.
Though labled as `won't fix` in existing issues, there are still some programs using `cvSaveImage( )`. I just happen to migrate a project with many OpenCV C API calls to C++ API calls, comparing two implementations results, and encounter opencv 3.4 latest version (3.4.13)'s `cvSaveImage( )` still crash on Windows platform. Thus I would like to share my solution.
Apart from this PR's fix method, people could also write a simple function as alternative to the bug `cvSaveImage`:
```c++
void mySaveImage(const char* filename, IplImage* dst)
{
cv::Mat img = cv::cvarrToMat(dst);
cv::imwrite(filename, img);
}
```

Fix cvSaveImage( ) function bug

---

modules/calib3d/include/opencv2/calib3d.hpp

Added '@ref' to enumerations to enable doxygen checks in Camera Calibration and 3D Reconstruction documentation.
Fixed miscellaneous references in master which were missed by #19089. 

Updated Calib3d documentation to fix missing @ref in master

---

modules/imgproc/misc/objc/test/ImgprocTest.swift

relates #19068
<cut/>
Failed test messages:
> Test Case '-[OpenCVTestTests.ImgprocTest testMinAreaRect]' started.
/Volumes/build-storage/build/precommit_custom_mac/build/osx/build/build-x86_64-macosx/modules/objc_bindings_generator/osx/test/test/ImgprocTest.swift:1131: error: -[OpenCVTestTests.ImgprocTest testMinAreaRect] : XCTAssertEqual failed: ("Size2f {2.000000,5.000000}") is not equal to ("Size2f {5.000000,2.000000}")
/Volumes/build-storage/build/precommit_custom_mac/build/osx/build/build-x86_64-macosx/modules/objc_bindings_generator/osx/test/test/ImgprocTest.swift:1132: error: -[OpenCVTestTests.ImgprocTest testMinAreaRect] : XCTAssertEqual failed: ("-90.0") is not equal to ("0.0")
---
```
buildworker:Custom …
```

Swift(test): fix minAreaRect test

---

modules/gapi/perf/common/gapi_imgproc_perf_tests.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_imgproc_perf_tests_cpu.cpp
modules/gapi/test/common/gapi_imgproc_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp

Performance tests for `morphologyEx` operation added
```
```

[G-API]: Performance tests for morphologyEx

---

doc/tutorials/imgproc/imgtrans/hough_lines/hough_lines.markdown

There was a typo in referencing the argument `minLineLength` in the tutorial for `HoughLinesP`.

Fix typo in hough_lines tutorial

---

modules/gapi/test/test_precomp.hpp

Add missing `#include <thread>` in modules/gapi/test/test_precomp.hpp
Fix #19244

Fix building opencv using gcc 11.x #19244

---

doc/py_tutorials/py_feature2d/py_sift_intro/py_sift_intro.markdown

This is a minor fix to the python SIFT example in the documentation. It removes a couple of sentences related to the patent and the part that points to the contrib repo since those those no longer seem applicable.

Remove blurb about patent in python SIFT example

---

modules/imgproc/include/opencv2/imgproc.hpp

Solution to documentation [issue #18836](https://github.com/opencv/opencv/issues/18836)
Clarify what FULL on enum means.  H (hue) reduced on conversion to 0..180 (360/2) range by default for 8 bit images.  FULL modifier expands H range to 0..255 for 8 bit images.

Doc issue fix 18836 FULL

---

modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/backends/onnx/gonnxbackend.cpp
modules/gapi/test/infer/gapi_infer_onnx_test.cpp

ORT API infer is `Run` method:
```
auto outputs = this_session.Run(Ort::RunOptions{nullptr},
in_run_names.data(),
&in_tensors.front(),
input_names.size(),
out_names.data(),
out_names.size());
```
We should call `Run()` with order of input layers' names. We can put names in different order. If we want to use const input than we call constInput(name, cv::Mat):
```
auto net = cv::gapi::onnx::Params<YoloNet>{model_path}
.constInput("image_shape", ins[1])
```
After that name will be added in order of input names and input tensor for Mat's data is created:
```
input_names.emplace_back(c_in_pair.first);
in_tensors.emplace_back(createTensor(this_memory_info,
in_tensor_info[idx],
c_in_pair.second.first));
```
And we call Run with new input names and appropriate tensors, where names: …

G-API: ONNX. Const input

---

modules/gapi/perf/common/gapi_imgproc_perf_tests.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_imgproc_perf_tests_cpu.cpp
modules/gapi/test/common/gapi_imgproc_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests_common.hpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp

- Performance tests for `boundingRect` operation added
- Accuracy test bodies merged/refactored using initialization functions which have been added recently
- new file created to share similar code between acc. and perf. tests
```
xbuild_image:Custom …
```

[G-API]: Performance tests for boundingRect

---

modules/gapi/CMakeLists.txt
modules/gapi/src/backends/common/gcompoundkernel.cpp
modules/gapi/src/backends/common/serialization.cpp
modules/gapi/src/backends/cpu/gcpubackend.cpp
modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/src/backends/ocl/goclbackend.cpp
modules/gapi/src/compiler/gcompiler.cpp
modules/gapi/src/compiler/gmodelbuilder.cpp
modules/gapi/src/compiler/passes/kernels.cpp
modules/gapi/src/compiler/passes/meta.cpp
modules/gapi/test/gapi_gcomputation_tests.cpp
modules/gapi/test/internal/gapi_int_gmodel_builder_test.cpp

Clang complains that the code in question binds a temporary value (returned by `indexed`) to a (`const`) reference.  While technically assigning a temporary value to `const` reference is OK (as it extends a lifetime of the temporary to lifetime of the reference), let\s please the compiler :)   
resolves #18928
<cut/>
```
buildworker:iOS=macosx-1 …
```

GAPI: fix Clang warning for dangling references in for loop variable

---

modules/ts/misc/summary.py
modules/ts/misc/table_formatter.py

This PR is related to issue #19267 .

[ts][summary.py] Extend `-o` to support tabs separated output.

---

modules/videoio/src/cap_mfx_plugin.cpp
modules/videoio/src/videoio_registry.cpp

Fixes: https://github.com/opencv/opencv/pull/19027#issuecomment-760060435

videoio: fix API/ABI_VERSION macros before plugin_api.hpp

---

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves #19327
merge with extra opencv/opencv_extra#835
<cut/>
```
```

Added Mish ONNX subgraph

---

modules/gapi/src/compiler/passes/kernels.cpp

- use lazy on-demand initialization
continues #19326

gapi: avoid global static initializers

---

modules/videoio/src/backend_plugin.cpp
modules/videoio/src/backend_plugin_legacy.impl.hpp
modules/videoio/src/cap_ffmpeg.cpp
modules/videoio/src/cap_gstreamer.cpp
modules/videoio/src/plugin_api.hpp
modules/videoio/src/plugin_capture_api.hpp
modules/videoio/src/plugin_writer_api.hpp

relates #19027
- separate APIs versioning
- module keeps support of both versions
<cut/>
---
Review the last commit only. Others are technical commits to keep git history properly:
- [backend_plugin_legacy.impl.hpp](https://github.com/alalek/opencv/blame/videoio_plugins_api_split_capture_write/modules/videoio/src/backend_plugin_legacy.impl.hpp)
- [plugin_writer_api.hpp](https://github.com/alalek/opencv/blame/videoio_plugins_api_split_capture_write/modules/videoio/src/plugin_writer_api.hpp)
- [plugin_capture_api.hpp](https://github.com/alalek/opencv/blame/videoio_plugins_api_split_capture_write/modules/videoio/src/plugin_capture_api.hpp)
```
Xbuild_image:Custom=ubuntu:20.04 …
```

videoio(plugins): split capture and writer APIs

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/src2/cv2.cpp
modules/python/src2/gen2.py
modules/python/test/test_misc.py

Python doesn't support function overloads, but OpenCV is C++ library and massively utilize them. If user has wrong input for overloaded function he/she receives only the latest conversion error message and sometimes it is not clear what is going on.
If every argument parsing function reports good diagnostic message why the argument can't be parsed, user will have sufficient information to fix the problem - overload resolution exception contains information about each conversion error.
Resolves #16432, #15465
Example error message output:
```
OpenCV(3.4.13-dev) :-1: error: (-5:Bad argument) in function 'testOverloadResolution'
> Overload resolution failed:
>  - Argument 'value' is required to be an integer
>  - function takes exactly 4 arguments (3 given)
```
See details at …

Raise overload resolution exception in Python bindings if overload resolution fails

---

doc/py_tutorials/py_imgproc/py_pyramids/py_pyramids.markdown
doc/py_tutorials/py_imgproc/py_thresholding/py_thresholding.markdown
doc/py_tutorials/py_imgproc/py_transforms/py_fourier_transform/py_fourier_transform.markdown
doc/py_tutorials/py_photo/py_non_local_means/py_non_local_means.markdown

update `xrange()` to `range()`, as Python 2 has been deprecate, more info:
1.  Python 2 has been no longer supported officially since January 1, 2020.  Check  https://www.python.org/doc/sunset-python-2
2.  xrange() was renamed to range() in Python 3. Check  https://stackoverflow.com/questions/17192158/nameerror-global-name-xrange-is-not-defined-in-python-3/17192181#17192181

 update xrange() to range(), as Python 2 has been deprecate

---

modules/stitching/src/exposure_compensate.cpp

Closes #19184 
```
[ RUN      ] ExposureCompensate.SimilarityThreshold
/opencv/modules/stitching/test/test_exposure_compensate.cpp:69: Failure
Expected: (psnr_similarity_mask) > (300), actual: 38.0114 vs 300
[  FAILED  ] ExposureCompensate.SimilarityThreshold (56824 ms)
```
```
[ RUN      ] ExposureCompensate.SimilarityThreshold
[       OK ] ExposureCompensate.SimilarityThreshold (115807 ms)
```

stitching: workaround the ExposureCompensate.SimilarityThreshold failure

---

modules/gapi/src/backends/ie/giebackend.cpp

relates #19050 #18928
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master_openvino-mac/builds/626).
```
```

GAPI: fix build warning

---

modules/core/src/ocl.cpp

Keep Image instance alive while it is used in Kernel's argument.
resolves #19134
relates #2621
replaces #19135
<cut/>
```
```

core(OpenCL): fix lifetime handling of Image kernel args

---

modules/highgui/src/window_w32.cpp

Patch for issue #19308. Removes the mandatory 1-pixel gap between picture area and window.

highgui: remove gutter in window_w32

---

modules/cudalegacy/src/calib3d.cpp

This `image_normalized` is created as a single column vector.
https://github.com/opencv/opencv/blob/bbad38b2c51c78e71d3364814e58b1e6e887705a/modules/imgproc/src/undistort.dispatch.cpp#L476
This part should scan in `(i, 0)` and not `(0, i)`
<cut/>
```
```

cudalegacy: fix wrong index

---

modules/gapi/perf/common/gapi_imgproc_perf_tests.hpp
modules/gapi/perf/common/gapi_imgproc_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_imgproc_perf_tests_cpu.cpp
modules/gapi/test/common/gapi_imgproc_tests.hpp
modules/gapi/test/common/gapi_imgproc_tests_common.hpp
modules/gapi/test/common/gapi_imgproc_tests_inl.hpp
modules/gapi/test/cpu/gapi_imgproc_tests_cpu.cpp

- Performance tests for `fitLine` and `findContours` operations added
- new file created to share similar code between acc. and perf. tests
- Accuracy test bodies refactored
``` …
```

[G-API]: Performance tests for fitLine and findContours

---

modules/dnn/misc/python/test/test_dnn.py
modules/python/src2/cv2.cpp
modules/python/test/test_misc.py

Minimal hotfix for test_overload_resolution() tests.
relates #14780
---
Tests with Rect conversions should be added in a separate PR (to 3.4 branch). Probably after #19344 to avoid conflicts

Python: handle errors in Rect conversions

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/src2/cv2.cpp
modules/python/test/test_misc.py

This PR introduces common way on how fixed size sequence can be converted to OpenCV type e.g. `tuple/list/np.array` to `cv::Rect`.
Each field of the OpenCV `struct`s are packed to lightweight reference wrappers array, so only homogeneous sequence can be parsed, so `TermCriteria` is parsed separately.
This patch disables the conversion from Python complex to `cv::Point`, because in my opinion it is error prone and doesn't take into account conversion from floating point values to integers as others do.
<cut/>
```
```

Common fixed size Python sequence conversion to OpenCV types

---

samples/dnn/tf_text_graph_ssd.py

Corrected SSD text graph generation in accordance with preprocessing block order 

---

modules/videoio/src/backend_plugin.cpp
modules/videoio/src/cap.cpp
modules/videoio/src/cap_ffmpeg.cpp
modules/videoio/src/cap_ffmpeg_impl.hpp
modules/videoio/src/cap_ffmpeg_legacy_api.hpp
modules/videoio/src/cap_interface.hpp
modules/videoio/src/plugin_capture_api.hpp
modules/videoio/test/test_ffmpeg.cpp

relates #19394
relates #16766
Validation:
- `--gtest_filter=*ffmpeg*with_property*`
- with/without `cmake ... -DVIDEOIO_PLUGIN_LIST=all`
Note: FFmpeg Windows wrapper is not updated.
<cut/>
```
force_builders=Linux32,Win32,Custom
```

videoio(plugins): support VideoCaptureParameters, CAPTURE_API_VERSION=1

---

modules/videoio/src/cap_dshow.cpp
modules/videoio/src/cap_dshow.hpp
modules/videoio/test/test_camera.cpp

Related issue : https://github.com/opencv/opencv/issues/19367
The PR fixed it the case to set FOURCC/FPS/CHANNEL & CONVERT_RGB in any order.
Every time `stopDevice` is called, `setConvertRgb` should be called again with correct value.
For example settings `FPS` after CONVERT_RGB:
https://github.com/opencv/opencv/blob/ea41f89b40392fc0c5bdfe0f0c43c4820c4b2eac/modules/videoio/src/cap_dshow.cpp#L3455-L3467
Same for `CHANNEL`
https://github.com/opencv/opencv/blob/ea41f89b40392fc0c5bdfe0f0c43c4820c4b2eac/modules/videoio/src/cap_dshow.cpp#L3447-L3453
And when settings `FOURCC`/`WIDTH`/`HEIGHT`
https://github.com/opencv/opencv/blob/ea41f89b40392fc0c5bdfe0f0c43c4820c4b2eac/modules/videoio/src/cap_dshow.cpp#L3494-L3500
<cut/>
I'm using Boson camera from FLIR. I'm interested in Y16 format video. I'm …

VideoCapture/DSHOW : Allow to set CAP_PROP_CONVERT_RGB before FOURCC/FPS/CHANNEL/WIDTH/HEIGHT.

---

samples/python/hist.py

Instead of being a copy of line 76, line 79 instead correctly indicates that it will show a histogram for a gray image in curve mode, as given by the code block at line 103 referencing image "gray" instead of image "im".

[Minor PR] Change Keymap wording for gray image in curve mode

---

modules/gapi/include/opencv2/gapi/infer/onnx.hpp
modules/gapi/src/backends/onnx/gonnxbackend.cpp
modules/gapi/test/infer/gapi_infer_onnx_test.cpp

We can call infer with images (not tensors) for networks like this:
https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/faster-rcnn#input-to-model
Fix for build on Windows (ort::Session on Windows expects wchar_t* instead char*).
```
test_filter:Custom=*ONNX*
```

G-API: ONNX. Support for networks with three dimensional input.

---

modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/pooling_layer.cpp

relates: https://github.com/opencv/opencv/pull/18862 https://github.com/opencv/opencv/pull/18783
Necessary changes for enabling Conv1D and Pool1D for CUDA in ```master``` branch.
<cut/>
```
Xbuild_image:Custom=ubuntu-openvino-2021.1.0:20.04
Xtest_modules:Custom=dnn,python2,python3,java
```

Preparations for enabling 1D support for Conv and Pool operations on CUDA

---

modules/stitching/test/test_matchers.cpp

Guard non-free usage in stitching as contrib can be built without it

---

cmake/OpenCVDetectTBB.cmake

continues #19384
Workarounds TBB problem on Windows:
```
LINK : fatal error LNK1104: cannot open file 'tbb12.lib'
```
Caused by [this oneTBB code](https://github.com/oneapi-src/oneTBB/blame/2dba2072869a189b9fdab3ffa431d3ea49059a19/include/oneapi/tbb/detail/_config.h#L334).
Usage steps:
```
call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
cmake -G "Visual Studio 16 2019" -A x64 ../opencv -DCMAKE_BUILD_TYPE=Release -DWITH_TBB=ON
```
Validated:
- CMake:
```
-- Found TBB (env): C:/Program Files (x86)/Intel/oneAPI/tbb/latest/lib/intel64/vc_mt/tbb.lib
...
--   Parallel framework:            TBB (ver 2021.1 interface 12010)
```
- and test output:
```
Parallel framework: tbb (nthreads=8)
```
---
P.S. oneMKL with oneTBB requires dirty workaround to enable build on Windows (not in scope of …

cmake: workaround oneTBB build issues with MSVC

---

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/test/test_onnx_importer.cpp

resolves: #18876
merge with extra opencv/opencv_extra#842
<cut/>
```
```

Added ONNX NormalizeL2 subgraph

---

modules/core/include/opencv2/core/cuda.hpp
modules/core/src/cuda_stream.cpp
modules/core/test/test_cuda.cpp
modules/python/test/test_cuda.py

adds feature described in issue opencv/opencv#19285
includes code, test, and doc.
TLDR: adds a constructor for cuda::Stream which accepts a raw cudaStream_t and assumes ownership of it including destroying the raw CUDA stream in the Stream's destructor.
<cut/>
```
```

add cuda::Stream constructor with cuda stream flags

---

modules/highgui/include/opencv2/highgui.hpp
modules/highgui/src/precomp.hpp
modules/highgui/src/window.cpp
modules/highgui/src/window_w32.cpp

combined with the proposed zero-delay `pollKey` alternative to waitKey (separate pull request), disabling VSYNC can *drastically* speed up display of images. I can get close to 1000 fps for a trivial example (see below), whereas with VSYNC it's nailed to 60 fps (for my screen) and with mandatory `Sleep()` in `waitKey` it's throttled to a jittery 100 FPS depending on OS scheduler.
~~I hope I based this on the right branch. it's not a bug fix.~~ I think I managed to retarget this to the master branch.
I took the implementation of the TOPMOST property as a template and tried to emulate the code structure.
please let me know if I can improve or if this isn't the right way to get such code introduced.
<cut/>
```python
#!/usr/bin/env python3
import time …
```

highgui: expose VSYNC window property for OpenGL on W32

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/src2/cv2.cpp
modules/python/test/test_misc.py

they might be thrown from third-party code (notably Ogre in the ovis
module).
While Linux is kind enough to print them, they cause instant termination
on Windows.
Arguably, they do not origin from OpenCV itself, but still this helps
understanding what went wrong when calling an OpenCV function.
@andy-held 
- n/a There is reference to original bug report and related work
- n/a There is accuracy test, performance test and test data in opencv_extra repository, if applicable
```
```

python: also catch general c++ exceptions

---

modules/dnn/include/opencv2/dnn/shape_utils.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/layers/concat_layer.cpp
modules/dnn/src/layers/flatten_layer.cpp
modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/layers/normalize_bbox_layer.cpp
modules/dnn/src/layers/reshape_layer.cpp
modules/dnn/src/layers/scale_layer.cpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/layers/softmax_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp

DNN's `clamp()` implementation is misleading (wrong name is selected).
The real `clamp` meaning is here: https://en.cppreference.com/w/cpp/algorithm/clamp
relates: https://github.com/opencv/opencv_contrib/pull/1156
<cut/>
```
build_image:Custom=halide:16.04
```

DNN: rename clamp() => normalize_axis()

---

cmake/OpenCVDetectTBB.cmake

relates #19447
- https://gitlab.kitware.com/cmake/cmake/-/issues/19434 (requires CMake 3.16+)
To support Ubuntu 16.04 (CMake 3.5.x) / 18.04 (CMake 3.10.x).
Ubuntu 20.04 has CMake 3.16.3.
Error message:
```
target_compile_definitions called with non-compilable target type
```
<cut/>
-------
```
build_image:Custom Win=oneapi_tbb-2021.1.1
```

cmake(TBB): fix target_compile_definitions() with "UNKNOWN" target

---

cmake/OpenCVFindLAPACK.cmake
cmake/OpenCVFindMKL.cmake

continues #19384 #19447
Workarounds oneMKL with oneTBB problem from oneAPI on Windows.
```
LINK : fatal error LNK1104: cannot open file 'tbb12.lib'
```
Usage steps:
```
call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
cmake -G "Visual Studio 16 2019" -A x64 ../opencv -DCMAKE_BUILD_TYPE=Release -DWITH_TBB=ON -DMKL_WITH_TBB=ON
```
<cut/>
```
build_image:Custom Win=oneapi_mkl_with_tbb-2021.1.1
```

cmake: workaround oneAPI problem with -DMKL_WITH_TBB=ON

---

modules/core/include/opencv2/core/cuda.hpp
modules/core/include/opencv2/core/cuda.inl.hpp
modules/core/src/cuda/gpu_mat_nd.cu
modules/core/src/cuda_gpu_mat_nd.cpp

For the first step to resolving #15897 and #16433, this PR tries to implement a minimal set of functions and entities that a `GpuMatND` class should have.
This PR includes:
* Constructor with internally managed memory with reference counting
* Constructor with external memory
* Default destructor, default copy, and move operations
* `clone()` for deep copying, with the resulting array being always continuous
* N-dim submatrix extraction (shallow copy)
* Uploading from and downloading to `Mat`
* Converting operator to `GpuMat`
<cut/>
Tests are in https://github.com/opencv/opencv_contrib/pull/2805
The following leak check was performed with the test.
```
cuda-memcheck --leak-check full opencv_test_cudev.exe --gtest_filter=*GpuMatND*
```
I hope this PR could be accepted as a minimal …

Minimal implementation of GpuMatND

---

modules/objdetect/src/qrcode.cpp
modules/objdetect/test/test_qrcode.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/845
fix #19363
<cut/>

QRCodeDetector::decodeMulti() fixed invalid usage fixedType()

---

modules/core/include/opencv2/core/cuda.hpp

relates #19259
Probably relates: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59526
<cut/>
Failed ARMv7 builder (GCC 4.8.x)
```
/build/precommit_armv7/opencv/modules/core/include/opencv2/core/cuda.hpp:456:15: error: function 'cv::cuda::GpuMatND& cv::cuda::GpuMatND::operator=(cv::cuda::GpuMatND&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'cv::cuda::GpuMatND& cv::cuda::GpuMatND::operator=(cv::cuda::GpuMatND&&)'
GpuMatND& operator=(GpuMatND&&) noexcept = default;
^
```
Failed CentOS 7:
```
/build/precommit_custom_linux/opencv/modules/core/include/opencv2/core/cuda.hpp:456:15: error: function 'cv::cuda::GpuMatND& cv::cuda::GpuMatND::operator=(cv::cuda::GpuMatND&&)' defaulted on its first declaration with an …
```

core(cuda.hpp): fix GpuMatND compilation with GCC < 5

---

modules/highgui/src/window.cpp
modules/highgui/src/window_QT.cpp
modules/highgui/src/window_cocoa.mm
modules/highgui/src/window_gtk.cpp
modules/highgui/src/window_winrt.cpp

relates #19411
Fix missing `pollKey()` definition in case of no-GUI builds
[ARMv7 builder](http://pullrequest.opencv.org/buildbot/builders/precommit_armv7/builds/12983):
```
ImportError: /home/build/work/master/build/lib/cv2.so: undefined symbol: _ZN2cv7pollKeyEv
```

highgui(pollKey): properly handle no-GUI case

---

modules/imgcodecs/src/apple_conversions.h
modules/imgcodecs/src/macosx_conversions.mm

This fixes compilation errors with certain versions of OSX where one would obtain errors like:
```
In file included from ../modules/imgcodecs/src/apple_conversions.mm:5:
In file included from ../modules/imgcodecs/src/apple_conversions.h:8:
In file included from ../modules/core/include/opencv2/core.hpp:3304:
../modules/core/include/opencv2/core/utility.hpp:53:4: warning: Detected Apple 'check' macro definition, it can cause build conflicts. Please, include this header before any Apple headers. [-W#warnings]
^
../modules/core/include/opencv2/core/utility.hpp:905:5: warning: declaration does not declare anything [-Wmissing-declarations]
bool check() const;
^~~~~~~~~~~~~~~~~~
3 warnings and 3 errors generated.
```
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a- …

CHange import order to avoid apple check error

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/test/cpu/gapi_core_tests_fluid.cpp

SIMD optimization for AbsDiffC kernel via univ intrinsics.
<cut/>
@rgarnov, @OrestChura please take a look.
Full performance report from latest revision:
[AbsDiffC_full_perf_report.xlsx](https://github.com/opencv/opencv/files/5854937/AbsDiffC_full_perf_report.xlsx)
```
force_builders=Linux AVX2,Custom,ARMv7
disable_ipp:Custom=ON
Xbuildworker:Custom=linux-1,linux-2,linux-4
Xbuild_image:Custom=powerpc64le
```

GAPI: SIMD optimization for AbsDiffC kernel

---

modules/stitching/perf/opencl/perf_stitch.cpp
modules/stitching/perf/perf_estimators.cpp
modules/stitching/perf/perf_matchers.cpp
modules/stitching/perf/perf_precomp.hpp
modules/stitching/perf/perf_stich.cpp

Not not test stitiching with SURF, if NONFREE is disabled

---

modules/core/src/parallel_impl.cpp

This fixes #19463
<cut/>
```
force_builders=linux,docs,mac,ARMv7,Custom
```

Disable thread sanitization check when CV_USE_GLOBAL_WORKERS_COND_VAR is not set.

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/src/api/kernels_core.cpp
modules/gapi/src/backends/cpu/gcpucore.cpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp

``` 
// disabled due high memory usage: test_opencl:Custom=ON …
```

Add Media Frame size function and corresponding tests

---

modules/imgcodecs/src/exif.cpp
modules/imgcodecs/src/exif.hpp
modules/imgcodecs/src/grfmt_base.cpp
modules/imgcodecs/src/grfmt_base.hpp
modules/imgcodecs/src/grfmt_jpeg.cpp
modules/imgcodecs/src/grfmt_jpeg.hpp
modules/imgcodecs/src/grfmt_png.cpp
modules/imgcodecs/src/loadsave.cpp
modules/imgcodecs/test/test_png.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/843
Added Exif parsing for PNG files to support Exif orientation tag.  Moved decoder specific Exif parsing to JPEG and PNG decoders, respectively. Issue 16579
resolves #16579
- [X ] I agree to contribute to the project under Apache 2 License.
- [X ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [X ] The PR is proposed to proper branch
- [X ] There is reference to original bug report and related work
- [X ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
Patch to opencv_extra has the same branch …

Added Exif parsing for PNG Issue 16579

---

platforms/js/build_js.py

This PR resolves issue #19493 . 
```
force_builder=Custom
```

Pass custom config file path as absolute

---

modules/core/include/opencv2/core/hal/intrin_neon.hpp

On Armv8 in AArch64 execution mode, we can skip the sequence
```
v<op>_<ty>(vget_high_<ty>(x), vget_high_<ty>(y))
```
in favour of
```
v<op>_high_<ty>(x, y)
```
This has better changes for recent compilers to use less data movement
operations and better register allocation. See for example:
https://godbolt.org/z/bPq7vd
<cut/>
- [ X ] I agree to contribute to the project under Apache 2 License.
- [ X ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ X ] The PR is proposed to proper branch
```
force_builders=linux,docs,ARMv8,ARMv7
```

[hal][neon] Optimize the v_dotprod_fast intrinsics for aarch64.

---

modules/imgcodecs/CMakeLists.txt

Previous link dependency: imgcodecs --> zlib --> libpng
this can generate imgcodecs shared lib, until Visual Studio integrated
with vcpkg, which will additionally specify LIBPATH, pointing to vcpkg
installed zlib (if any), which links the wrong zlib.
Fixed link dependency: imgcodecs --> libpng --> zlib
in this fixed case, symbols in zlib referenced in libpng will be found
in the build-from-source static zlib, instead of the vcpkg one.
related discussion:
- https://github.com/microsoft/vcpkg/issues/16165
- https://github.com/opencv/opencv/issues/17051
- https://github.com/opencv/opencv/issues/10576
MSVC linking order reference pages:
- https://docs.microsoft.com/en-us/cpp/build/reference/link-input-files?view=msvc-160
for link order
- …

fix link order: put zlib after png/tiff/openexr

---

modules/dnn/src/layers/proposal_layer.cpp

As the source code, **since width and height do NOT depend on variable within the inner loop**, it is better to move them to the first loop and we can save several redundant executions.
- [v] I agree to contribute to the project under Apache 2 License.
- [v] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [v] The PR is proposed to proper branch

Refine the execution order of for loop

---

modules/core/src/rand.cpp

This PR fix 3.4 branch's core module failure build on android arm64, by determine and including `arm_neon.h` header file.

fix core module android arm64 build

---

modules/cudaoptflow/src/brox.cpp
modules/cudaoptflow/src/farneback.cpp
modules/cudaoptflow/src/pyrlk.cpp
modules/cudaoptflow/src/tvl1flow.cpp
modules/video/src/lkpyramid.cpp
modules/video/src/optflowgf.cpp
modules/video/src/tvl1flow.cpp

fixes https://github.com/opencv/opencv/issues/17960

getDefaultName() isn't overloaded in SparseOpticalFlow

---

3rdparty/carotene/src/resize.cpp

If statement has the same expression on both sides so this can be reduce
Signed-off-by: Dan Ben Yosef <danbey@gmail.com>

Reduce if statement as it has the same expression on both sides of '&&'

---

modules/gapi/include/opencv2/gapi/util/optional.hpp

```
Xbuild_image:Custom=ubuntu-openvino-2021.1.0:20.04
Xtest_modules:Custom=gapi …
```

G-API: Fix optional move constructor

---

modules/imgcodecs/CMakeLists.txt
modules/imgcodecs/test/test_png.cpp

imgcodecs(test): don't include png.h

---

modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

* In case empty roi list for `InferROIList` & `Infer2` data will be got from `StreamingOutput` but not post back, due the list is empty, it cause hanging.
* Since the async request and collecting data for the next frame work asynchronously, there is a data race on `StreamingOutput` object, because callback can call `StreamingOutput::post` method while the `StreamingOutput::get` is working. 
``` …
```

[G-API] Async infer request hotfix

---

modules/gapi/test/gapi_fluid_test.cpp

Based on recent discussion in a related bug report (#19434), let's change the statistic used to measure the "memory consumption" 
```
```

[G-API] Change memory measurement statistic in Fluid tests

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/test/test_darknet_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/847
This PR resolves the issue  #19393  and the test data is added in opencv_extra through PR[ #opencv/opencv_extra/pull/847](https://github.com/opencv/opencv_extra/pull/847)
<cut/>
```
opencv_extra=tanh_darlnet_testdata …
```

TanH darknet and test

---

samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp

This pull request will prevent error in function cvConvertScale() due to empty undistorted image matrix

Handle error in camera calibration tutorial

---

samples/va_intel/display.cpp.inc

The code worked with assumption that PCI devices sorted by name match DRI devices order, i.e. device with ID 0000:00:02 should be represented by `card0/renderD128` and device 0000:01:00 by `card1/renderD129`. But in reality this is wrong:
```
$ ls -l /dev/dri/by-path/
lrwxrwxrwx. 1 root root  8 Feb 18 16:30 pci-0000:00:02.0-card -> ../card1
lrwxrwxrwx. 1 root root 13 Feb 18 16:30 pci-0000:00:02.0-render -> ../renderD129
lrwxrwxrwx. 1 root root  8 Feb 18 16:30 pci-0000:01:00.0-card -> ../card0
lrwxrwxrwx. 1 root root 13 Feb 18 16:30 pci-0000:01:00.0-render -> ../renderD128
```
Instead we probe `drm` endpoint as it seem to contain correct DRI device names:
```
$ ls  /sys/bus/pci/devices/0000\:01\:00.0/drm
card0  controlD64  renderD128
$ ls  /sys/bus/pci/devices/0000\:00\:02.0/drm
card1 …
```

VA sample: device autodetection changed

---

modules/core/include/opencv2/core.hpp
modules/core/include/opencv2/core/cvdef.h
modules/core/include/opencv2/core/simd_intrinsics.hpp
modules/core/src/hal_internal.cpp
modules/core/src/hal_internal.hpp
modules/core/src/intel_gpu_gemm.inl.hpp
modules/core/src/matrix_c.cpp
modules/core/src/matrix_iterator.cpp
modules/core/src/matrix_operations.cpp
modules/core/src/matrix_sparse.cpp
modules/core/src/matrix_wrap.cpp

Compatibility impact: Low
approved at technical meeting.

core: include version.hpp in cvdef.h, fix precomp.hpp usage

---

modules/core/include/opencv2/core/ocl.hpp
modules/core/src/ocl.cpp
modules/core/src/ocl_disabled.impl.hpp

fixes https://github.com/opencv/opencv/issues/19571
This is only for OpenCV 4.x. It requires C++11 or newer.
- follows iso c++ guideline C.44
- enables default compiler-created constructors to also be noexcept

add noexcept to default constructors of cv::ocl

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp
modules/imgcodecs/src/grfmt_exr.cpp
modules/imgcodecs/test/test_exr.impl.hpp

OpenEXR comression options

---

modules/core/include/opencv2/core/ocl.hpp
modules/core/src/ocl.cpp
modules/core/src/ocl_disabled.impl.hpp

backport #19572
- handled KernelArg, Image2D

(3.4) add noexcept to default constructors of cv::ocl

---

modules/imgcodecs/test/test_exr.impl.hpp

build warning (windows 32-bit)

---

modules/video/src/lkpyramid.cpp

If prevPts size is (N, 1) (which is a default layout for converting `vector<Point2f>` to `UMat`) the `prevPts.cols == 1` and optical flow will be calculated for the first point only.
Getting `prevPts.total()` as in line 1048 is the correct way to get points count.

Minor fix in OCL implementation of calcOpticalFlowPyrLK

---

modules/core/include/opencv2/core/ocl.hpp
modules/core/src/ocl.cpp
modules/core/src/ocl_disabled.impl.hpp
modules/core/test/ocl/test_opencl.cpp

fix https://github.com/opencv/opencv/issues/19573
- enables inline construct and assigns with r-values
- enables compiler-created default move construct/assigns
- includes test cases
- This is only for opencv 4.x branch -- move semantics are only available in c++11 or newer

add move construct/assigns to cv::ocl main classes

---

modules/core/include/opencv2/core/parallel/parallel_backend.hpp
modules/core/misc/plugins/parallel_openmp/CMakeLists.txt
modules/core/src/parallel/plugin_parallel_wrapper.impl.hpp

hotfix #19470
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master-contrib_docs-lin64/builds/11472).
```
```

core(parallel): fix JS build, fix OpenMP version dump

---

modules/dnn/src/layers/detection_output_layer.cpp

**According to experiment, for sorting std::vector, when the target to be sorted is less than 12.5% of the whole vector, apply partial_sort instead of sort benefits at most x8 speedup.**
Typically within detection out layer, the output is far less than the proposals after NMS; for example, for faster RCNN model coming from TensorFlow, there are 90 (# of classes) * 100 proposals but outputs 100 outcomes only. Sometimes even after NMS, the proposals is still far largen than the number to keep. Ex, for maskRCNN, we keep top 100 but proposal after NMS is 1292, so the ratio is 100/1292 ~ 8% and partial sort is faster x 2 times than sort. In the case if we keep top 10 only, the ratio is 10/1292 < 1% so partial sort benefits more.
As the result, in this case, apply partial sort makes it faster …

apply partial sort to save computations

---

modules/dnn/src/layers/proposal_layer.cpp

In ProposalLayerImpl layer, there is a fake image. For now, we actually allocate memory for it.
```
// We've chosen the smallest data type because we need just a shape from it.
fakeImageBlob.create(shape(1, 1, imInfo.at<float>(0), imInfo.at<float>(1)), CV_8UC1);
```
For example, if the input image has [N, C, H, W] = [1, 3, 1024, 1024], it will create a memory space of 1024*1024 = 1MB.
**For edge devices, allocate 1MB unnecessary memory indeed consumes too much system resource.**
Also notice that fakeImageBlob is a class member variable so its life scope is the same as dnn net.
However, this fake mat is used at:
- prior box layer and
- detection out layer.
In both of the layers, we don't access the content but merely request the shape info.
Instead, in the PR, we make fakeImageBlob as …

save allocation of memory for fake image

---

modules/dnn/src/layers/detection_output_layer.cpp

Move map resize to the beginning of loop to avoid unnecessary check within inner loop.
**Google benchmark test:**
Vgg16 Faster RCNN model, detection output layer is used by
1. proposal output; where we have 1 location class and 9 * 14 * 14 = 1764 prediction per class.
2. Output layer: where we have 21 location classes and 100 prediction per class.
According to test on VGG16 faster RCNN, there are speedup of:
65.38% (17000ns  / 10279 ns)
45.22% (30308 / 20870 ns)
<cut/>
the benchmark program is at the link and compiled by:
https://drive.google.com/file/d/1sBzXPuCLEekjoWh85k4ZUKlgqQrJcXsU/view?usp=sharing
```
g++ test.cpp -std=c++14 -O3 -I<benchmark>/benchmark/include -L<benchmark>/build/src -lbenchmark -lpthread -o 
benchmark
```
```
Run on (12 X 4600 MHz CPU s)
CPU Caches:
L1 Data 32 KiB …
```

improve map allocation check

---

cmake/OpenCVPluginStandalone.cmake

cmake(plugins): build without opencv_*.so on OSX

---

modules/videoio/src/cap_gstreamer.cpp
modules/videoio/test/test_gstreamer.cpp

Use `GstVideoInfo` to handle strides properly (not available in GStreamer 0.10).
```
force_builders_only=Linux AVX2,Custom,docs
Xbuild_image:Custom=gstreamer:16.04
```

videoio(gstreamer): rework retrieveFrame() to handle strides

---

cmake/OpenCVPluginStandalone.cmake

On Windows default plugin name would be just `${OPENCV_PLUGIN_NAME}` without suffix and plugin won't load.

plugins: add suffix to default OUTPUT_NAME

---

modules/gapi/perf/common/gapi_core_perf_tests.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_cpu.cpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_common.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/common/gapi_imgproc_tests_common.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp

- Performance tests for kmeans operation added
- New file created to share common parts between accuracy and performance tests for core kernels
- Accuracy test bodies refactored
- Some test typos corrected
``` …
```

[G-API]: Performance tests for kmeans

---

modules/imgproc/src/imgwarp.cpp
modules/imgproc/test/test_imgwarp.cpp

imgproc(warpAffine): avoid buffer indexes overflow in SIMD code

---

modules/imgproc/include/opencv2/imgproc.hpp

relative to https://forum.opencv.org/t/why-cv-blendlinear-from-imgproc-is-missing-in-python/1851

python binding blendLinear

---

modules/core/src/copy.cpp

**Problem**: addition of unsigned offset to 0x000007ff0362 overflowed to 0x000007fefac0
In `third_party/opencv/modules/core/src/copy.cpp ` the function `copyMakeConstBorder_8u` receives the step of a cv::Mat, namely `dststep` of type `size_t`. When offsetting the destination matrix pointer to start copying data, `memcpy(dst + (i - top) * dststep, constBuf, dstroi.width)` the result of `(i - top)` could be negative, then, when applying the arithmetic operator * because of [arithmetic operator conversion](https://en.cppreference.com/w/cpp/language/operator_arithmetic) the int is converted to size_t, resulting pointer overflow.

Fix UB in CopyMakeConstBoder_8u

---

modules/videoio/src/cap_ffmpeg_impl.hpp

related #19460
Compilation fix for older FFmpeg versions (< 2.0.0, >9 years old)

videoio: av_frame_unref compilation fix

---

modules/videoio/src/cap_ffmpeg_hw.hpp
modules/videoio/src/cap_ffmpeg_impl.hpp

relates #19460
thanks to @mikhail-nikolskiy
<cut/>
```
build_image:Custom Win=ffmpeg-plugin
buildworker:Custom Win=windows-2
test_modules:Custom Win=videoio,python3,java
Xtest_modules=videoio,python3,java
buildworker:Win64 OpenCL=windows-1
build_image:Win64=ffmpeg-plugin-msvs2015
buildworker:Win64=windows-2
test_opencl:Win64=ON
```

videoio(ffmpeg): fix VIDEO_ACCELERATION_ANY handling

---

3rdparty/ffmpeg/ffmpeg.cmake

**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/61
- FFmpeg 3.4.8
previous update: #18284

ffmpeg/3.4: update FFmpeg wrapper 2021.03

---

modules/gapi/src/backends/ie/giebackend.cpp
modules/videoio/src/cap_msmf.cpp

<cut/>
```
test_modules:Custom=gapi,python3,java
test_modules:Custom Win=gapi,python3,java
test_modules:Custom Mac=gapi,python3,java
```

Fix static analyzer issues

---

3rdparty/ffmpeg/ffmpeg.cmake
modules/videoio/test/test_video_io.cpp

**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/62
- FFmpeg 4.3.2
previous update: #18290

ffmpeg/4.x: update FFmpeg wrapper 2021.03

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/fisheye.cpp
modules/calib3d/test/test_fisheye.cpp

Resolves #13450
Replaces abandoned PR #18306 and adds test

Added CALIB_FIX_FOCAL_LENGTH to fisheye calibration

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/core/src/bindings_utils.cpp
modules/python/test/test_fs_cache_dir.py

Replaces https://github.com/opencv/opencv/pull/18931 and adds more test for imgcodecs interop.

getCacheDirectory binding for Python

---

modules/objdetect/src/qrcode.cpp

This PR will fix some cases of false positive detection of QR codes and prevent segmentation fault in `decodeCurved()` due to these cases
resolves [#19626](https://github.com/opencv/opencv/issues/19626)

QR code: fix false positive detection

---

modules/imgcodecs/src/grfmt_exr.cpp
modules/imgcodecs/src/grfmt_exr.hpp
modules/imgcodecs/test/test_exr.impl.hpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/859
EXR alpha support for 4 channel reading and writing.  Issue https://github.com/opencv/opencv/issues/16115.  
Replaced magic numbers (3 and 4) with const variables where possible to enhance readability and mantainability.
<cut/>

EXR alpha support for 4 channel reading and writing

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/test/test_darknet_importer.cpp

Spatial Attention Module in YOLOv4.  
From https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-different-layers
resolves : #18988 
merge with extra : opencv/opencv_extra#861
<cut/>
```
```

dnn : Added Spatial Attention Module in Darknet Importer

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

Merge with extra: opencv/opencv_extra#857
Fixes #19489: [tf.keras.layers.Reshape](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Reshape) layer interpreted incorrectly by readNetFromTensorflow() in dnn.
```
```

Aligned TF Reshape layer behaviour

---

modules/core/include/opencv2/core/hal/intrin_cpp.hpp

Intrinsics reference implementation updated to address wide universal intrinsics as well
<cut/>
```
force_builders_only=Custom,Linux x64,docs
```

Updated cpp reference implementations for a few intrinsics

---

modules/calib3d/src/stereobm.cpp

To improve preformence it is better to init the params (StereoBMImpl) in the
initialization list.

Init params (StereoBMParams) in StereoBMImpl constructor initialization list

---

samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp

The camera_calibration sample has a bug where when using fisheye and with a video as the source, the corrected image is almost entirely empty except for the 1-4 pixels closest to the origin. This is because `fisheye::undistortImage` uses an identity as the output camera matrix by default, and therefore maps all points very close to (0,0).
This fix is to use `fisheye::estimateNewCameraMatrixForUndistortRectify` to create the output camera matrix, in the same manner that it is used when images are used as the calibration source.
Also, there are two added guards around calibration flags for `calibrateCameraRO` that are not applicable to `fisheye::calibrate`.
relates #7040
<cut/>
Patch to …

fix camera_calibration sample for fisheye

---

modules/gapi/include/opencv2/gapi/infer/ie.hpp
modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

Reshape changes shape for CNN input dims.
To use input reshape, you should call function `cfgInputReshape` for `Params`:
1. `.cfgInputReshape( { {layer1_name, shape1}, {layer3_name, shape3} } )` - for some layers;
2. `.cfgInputReshape(layer1_name, shape1)` - for single layer;
3. `.cfgInputReshape( { layer1_name, layer3_name } )` - for reshaping by input image.
`layer..._name` - name of input layer, which should to be reshaped.
`shape...` - vector of dimensions, which reshape will use (1,3,300,300 for example).
Behavior:
- `input_reshape_table` from IEUnit contains pairs layer's name --- dimensions for reshape;
- Unfortunately, now current CNN input layers dimensions are not checked, but if provided incorrect dimensions in 1st and 2nd cases of `cfgInputReshape` then IE throw error message; …

[G-API]: Adding reshape for CNN input.

---

modules/gapi/perf/common/gapi_video_perf_tests.hpp
modules/gapi/perf/common/gapi_video_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_video_perf_tests_cpu.cpp
modules/gapi/test/common/gapi_video_tests_common.hpp
modules/gapi/test/common/gapi_video_tests_inl.hpp
modules/gapi/test/cpu/gapi_video_tests_cpu.cpp

- Performance tests for BackgroundSubtractor stateful operation added
- Accuracy test misprint fixed
``` …
```

[G-API]: Performance tests for BackgroundSubtractor

---

modules/dnn/src/layers/detection_output_layer.cpp
modules/dnn/src/nms.inl.hpp

To boost NMS performance, we apply early termination here at this PR.
Notice that **current detection out layer will be used internally by proposal layer.**
In this case, finally, proposal will, ex output top 100 proposals among all candidates.
Typically, **the # of candidates is about more than several thousands**.
Currently flow seriously down-grades performance **by applying NMS for all candidates**.
**However, as we know, to output top K NMS output, we should check if we have picked enough candidates and terminate once we have collected what we need.**
As the table below, to output top K = 100 candidates, we just need to check less than one thousand bboxes
But for current flow, we check all.
pic | # of candidate calculated before | # of candidate calculated after
-- | -- | --
1 | 6000 …

boost NMS performance

---

modules/dnn/src/cuda4dnn/init.hpp
modules/dnn/src/dnn.cpp

The `checkVersions()` that was introduced in #17788 was partially useless since a version mismatch (that could create problems) would throw an exception before `checkVersions()`.
The FP16 and device compatibility checks have been removed from `BackendRegistry`. `BackendRegistry` creates a static local object. Hence, subsequent calls to get targets with device id changed can return the wrong set of targets. These checks are instead done in `initCUDA` now. The target will switch to FP32 if FP16 is not supported.
```
build_image:Custom=ubuntu-cuda-cc52:18.04
```

cuda4dnn: fix version check diagnostic

---

modules/calib3d/src/stereosgbm.cpp

To improve performance it is better to init the params (StereoSGBMParams) in the
initialization list.

Init params (StereoSGBMParams) in StereoSGBMImpl constructor init list

---

modules/calib3d/src/solvepnp.cpp
modules/calib3d/test/test_solvepnp_ransac.cpp

resolves #17799 
relates #14447
When `solvePnPRansac` is called, it will do RANSAC and then call `solvePnPGeneric`, in which `cvFindExtrinsicCameraParams2` will be called. Sometimes the point-pairs after RANSAC are less than 6, but the DLT algorithm used in `cvFindExtrinsicCameraParams2` (SOLVEPNP_ITERATIVE) needs at least 6 points, in this case the function will throw an error. See [solvePnPGeneric](https://github.com/mightbxg/opencv/blob/master/modules/calib3d/src/solvepnp.cpp#L875), [cvFindExtrinsicCameraParams2](https://github.com/mightbxg/opencv/blob/master/modules/calib3d/src/calibration.cpp#L1173).
The proper logic for `solvePnPGeneric` should be returning `false` (0 or -1) instead of throwing an error to the executable, so I added try-block, just like …

Unexpected exception in solvePnPRansac caused by input points

---

modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/mat.inl.hpp
modules/core/src/matrix.cpp
modules/core/src/umatrix.cpp

Resolves issue https://github.com/opencv/opencv/issues/19682

add noexcept to default constructor for: Mat, UMat, Mat_, MatSize, MatStep

---

modules/core/src/system.cpp

closes #19698
```
disable_ipp=ON
```

core:ppc64 fix detecting CPU features when optimization is off

---

modules/core/src/system.cpp

It is best to pass bad_value_ param by reference to avoid copy.

Avoiding copy by passing param by reference

---

modules/core/test/ocl/test_opencl.cpp

Details: https://community.amd.com/t5/opencl/spir-support-in-new-drivers-lost/td-p/170165
<cut/>
```
Current OpenCL device: 
Type = dGPU
Name = Baffin
...
Device extensions:
...
cl_khr_spir
[ RUN      ] OpenCL.support_SPIR_programs
Program SPIR size: 1700 bytes
OpenCL program build log: /simple_spir
Status -11: CL_BUILD_PROGRAM_FAILURE
Error: HSAIL doesn't support OpenCL extension spir.
An invalid binary was detected.
Error: BRIG code generation failed.
/build/3_4_noICV-skx-lin64/opencv/modules/core/test/ocl/test_opencl.cpp:123: Failure
Value of: program.ptr() != NULL
Actual: false
Expected: true
[  FAILED  ] OpenCL.support_SPIR_programs (0 ms)
```
---
```
force_builders=Custom,Linux OpenCL
build_image:Linux …
```

core(ocl): skip SPIR test on AMD devices if problem detected

---

modules/ts/misc/run_long.py

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master_valgrind-lin64-debug/builds/10287).

valgrind: filter out hardware-accelerated videoio tests

---

modules/gapi/src/backends/ie/giebackend.cpp

[G-API] Fix blocking desc usage

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/js/generator/CMakeLists.txt
platforms/js/opencv_js.config.py

Enums are not properly supported by bindings generators, so added a dedicated calls with "int" values.
```
```

JavaScript: support setLogLevel() / getLogLevel() calls

---

modules/dnn/include/opencv2/dnn/shape_utils.hpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra**: opencv/opencv_extra#849
**Fixes** #17364: inappropriate OpenCV processing of specific tensor summation case in [LaneNet](https://github.com/MaybeShewill-CV/lanenet-lane-detection) BiseNetv2 front end.
Added [tf.math.add](https://www.tensorflow.org/api_docs/python/tf/math/add) and OCV [`eltwise_layer` ](https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/eltwise_layer.cpp)behaviour alignment.
The initial problem problem is incorrect processing of the case, when, for example, there are two tensors: `a` (shape: [1,1,1,n] ) and `b`  (shape: [1,<some_val_1>,<some_val_2>,n]  ). [ `tf.math.add`](https://www.tensorflow.org/api_docs/python/tf/math/add) returns the result `c` (shape: [1,<some_val_1>,<some_val_2>,n] ), whereas OpenCV compares `1` vs ` …

Added TF add behaviour alignment

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

Merge with extra: opencv/opencv_extra#865
Fixes [#18214](https://github.com/opencv/opencv/issues/18214#issuecomment-683894976): 
* issue 1:  aligned OCV and [TF multiplication](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Multiply?hl=ru) layer behaviour for the following case: inputs **a** (shape: [1,1,1, C] ) and **b** (shape: [1, H, W, C] ), OCV **a** mul **b** returns [1,1,1, C], whereas TF mul - [1, H, W, C].
* issue 2: MobileNetV3 reshape problem (before Conv layer): ``number of input channels should be multiple of 72 but got 1 in getMemoryShapes()``
```
build_image:Custom …
```

Corrected DNN elementwise multiplication

---

modules/gapi/include/opencv2/gapi/streaming/format.hpp
modules/gapi/src/api/kernels_streaming.cpp
modules/gapi/src/backends/common/gbackend.hpp
modules/gapi/src/backends/streaming/gstreamingbackend.cpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp

``` 
// disabled due high memory usage: test_opencl:Custom=ON …
```

[G-API] Added Y, UV accessors for cv::MediaFrame

---

samples/python/stitching_detailed.py

resolves #19761
<cut/>
This is a Pull Request for the Issue [19761](https://github.com/opencv/opencv/issues/19761)
In OpenCV 4.5.1 
```
cv.xfeatures2d_SURF.create
```
will not create an AttributeError, even if the function is excluded (no nonfree option)
In Line 305 (now 306) however, if `surf ` is passed to the parameter `features`
`finder = FEATURES_FIND_CHOICES[args.features]()` 
aka
`
cv.xfeatures2d_SURF.create()`
will raise an 
`error: OpenCV(4.5.1) ..\opencv_contrib\modules\xfeatures2d\src\surf.cpp:1029: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; …

Solve Issue 19761

---

modules/gapi/include/opencv2/gapi/streaming/sync.hpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.hpp
modules/gapi/test/streaming/gapi_streaming_sync_tests.cpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp

This PR brings `cv::gapi::streaming::sync_policy` enum which allows to control input streaming sources synchronization when passed as compile arg. Currently possible values are `dont_sync` and `drop`. If `dont_sync` or nothing is passed, framework will behave as previously. If `drop` is passed, framework will run the whole graph only on inputs which timestamps are equal, dropping all inappropriate frames. Need to note that const (non-video) sources are not taken into account when comparing timestamps since their output is always the same.
For each input our streaming executor creates an `Emitter` which is responsible for pulling data from the source. There is 1:1 correspondence between emitters and GComputation inputs. For const sources `ConstEmitter`-s are created, for video sources - …

G-API: Basic frame drop functionality

---

modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_torch_importer.cpp

Introduce relaxed accuracy thresholds for CL target in some dnn tests.

---

modules/core/src/directx.cpp
modules/core/src/opencl/cvtclr_dx.cl
modules/core/src/va_intel.cpp

(had to close [PR](https://github.com/opencv/opencv/pull/19776/) into master and open this PR into 3.4)
1. Run OpenCL kernels on 4x less work items as each item computes 4 pixels
2. Use float4 vector arithmetic in NV12->BGR kernel
If applied together with [PR19755](https://github.com/opencv/opencv/pull/19755), performance of the following command 
```
example_tapi_video_acceleration -accel=any -opencl=true -i=input.mp4 -o=null
```
increases on my iGPU from ~550fps to ~850fps (H264 1080p input video).

Performance optimization in DirectX and VAAPI interop

---

modules/gapi/test/streaming/gapi_streaming_sync_tests.cpp

G-API(build): eliminate Win32 build warning

---

modules/gapi/src/backends/plaidml/gplaidmlbackend.cpp

[G-API] Support RMat for PlaidML backend

---

modules/gapi/perf/common/gapi_video_perf_tests.hpp
modules/gapi/perf/common/gapi_video_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_video_perf_tests_cpu.cpp
modules/gapi/src/backends/cpu/gcpuvideo.cpp
modules/gapi/test/common/gapi_video_tests_common.hpp
modules/gapi/test/common/gapi_video_tests_inl.hpp

- Performance tests for KalmanFilter stateful operation added
- Accuracy test misprint fixed and a little refactoring applied
- A bug with changing KalmanParams due to non-copy assignment in KalmanFilter::setup() fixed
``` …
```

[G-API]: Performance tests for KalmanFilter

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: opencv/opencv_extra#854
**Fixes** #18920: added ``steps`` parameter support for Slice layer
```
```

Added Steps support in DNN Slice layer

---

modules/dnn/src/ocl4dnn/src/math_functions.cpp

fixup #19114
Fixes error message:
```
[ RUN      ] Test_ONNX_layers.GatherMultiOutput/0, where GetParam() = OCV/OCL
[ERROR:0] OpenCL kernel can't be reused in async mode: gemm_buffer_copy_image_no_transpose_float
[       OK ] Test_ONNX_layers.GatherMultiOutput/0 (1 ms)
```

dnn(OpenCL): fix gemm kernel scheduling

---

modules/core/include/opencv2/core/hal/intrin_neon.hpp

Similar to https://github.com/opencv/opencv/pull/19486 we can fuse the two intrinsics
```c++
vmovl_##suffix(vget_high_##suffix());
```
into the equivalent single intrinsic
```c++
vmovl_high_##suffix();
```
for AArch64.
On gcc 10.2 and before, the compiler emits fewer instructions (see https://godbolt.org/z/x9GcY5evj).
```
force_builders=linux,docs,ARMv8,ARMv7
```

[hal][neon] Optimise v_expand for AArch64

---

modules/imgproc/test/ocl/test_imgproc.cpp

The MinEigenVal path through the corner.cl kernel makes use of native_sqrt,
a math builtin function which has implementation defined accuracy.
Partially addresses issue #9821

Relax accuracy requirement on OpenCL MinEigenVal corner kernel test.

---

modules/gapi/samples/semantic_segmentation.cpp
modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

- This PR should solve problem with semantic-segmentation-adas-0001 network.
- Added support for int32 input and output;
- Added sample for semantic-segmentation-adas-0001.
``` …
```

G-API: IE. Adding support for INT32 type.

---

modules/dnn/src/cuda/math.hpp
modules/dnn/src/cuda/resize.cu
modules/dnn/src/cuda4dnn/kernels/resize.hpp
modules/dnn/src/cuda4dnn/primitives/resize.hpp
modules/dnn/src/layers/resize_layer.cpp

- Ports the features added in the following PRs to the CUDA backend:
#19071
#18996 
- adds `opencv_linear` support from #16472
- Resolves #18721 for CUDA backend.
The resize layer of the CUDA backend now supports everything that OCV CPU backend supports.
```
```

cuda4dnn(resize): add alignCorners and halfPixelCenters params to NN and bilinear resize

---

modules/gapi/test/streaming/gapi_streaming_tests.cpp

G-API: Fixed Y access in BGR accessor test, added more instantiations

---

modules/gapi/src/backends/common/gbackend.hpp
modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/backends/onnx/gonnxbackend.cpp
modules/gapi/test/infer/gapi_infer_onnx_test.cpp

ONNX's RCNN contains output (labels) with [INT64 type](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/faster-rcnn).
INT64 type isn't supported for cv::Mat. Conversion to INT32 is used for this output.
``` …
```

 G-API: ONNX. Adding INT64-32 conversion for output.

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

Merge with extra: opencv/opencv_extra#868
Fixes #19512: added TF sum ``reduction_indices=-1`` case support
```
```

Added reduce sum by channel support

---

modules/gapi/include/opencv2/gapi/infer/onnx.hpp
modules/gapi/src/backends/onnx/gonnxbackend.cpp
modules/gapi/test/infer/gapi_infer_onnx_test.cpp

Unnecessary network outputs can be omitted. For example: FRCNN has output with `INT_64` data type, which unsupported for OCV. Name of this output is "6381". We can "disable" this output. It works for dynamic output case only when we should remap onnx outputs to g-api out.
You can set layer names which you will use in remapping. You should call overload of cfgPostProc function for this.
```
.cfgOutputLayers({"gapi_out1", "gapi_out2"})
.cfgPostProc({cv::GMatDesc{CV_32F, {1,20}}, cv::GMatDesc{CV_32F, {5}}},
remapRcnnPorts,
{"6383", "6379"}
);
```
There are two layers with names "6383" and "6379" will be used for remapping. Data will be remapped from "6383", "6379" to "gapi_out1", "gapi_out2" with remapRcnnPorts function logic (Unfortunately we can't set out_meta for network with dynamic …

G-API: ONNX. Disable unnecessary outputs

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp

Fixes conversion of the kernel's input for `GArray<GArray<U>> -> vector<vector<U>>` case
``` …
```

[G-API]: Fix kernel's input conversion bug

---

modules/core/src/mathfuncs_core.dispatch.cpp
modules/core/test/test_arithm.cpp

resolves #19506
Looks like the problem relates to `ippsMagnitude_32f` only. ippsMagnitude_64f works fine.
<cut/>
/cc @eplankin
```
```

core(IPP): disable some ippsMagnitude_32f calls

---

modules/gapi/include/opencv2/gapi/gopaque.hpp

Problem is caused by undetermined order of used headers (will be fixed separatelly).
Failed builds due to this problem:
- http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/31078 and others (mostly on linux-5)
- http://pullrequest.opencv.org/buildbot/builders/precommit_linux64_no_opt/builds/28377 and others
```
buildworker:Linux x64=linux-5
```

build: workaround sporadic failures of python binding compilation

---

cmake/OpenCVModule.cmake

- cmake uses filesystem's order which may vary
- unpredictable headers order may cause build failures (primary bindings)
relates #19818
```
buildworker:Linux x64=linux-5
buildworker:Linux x64 Debug=linux-5
```

cmake: fix order of headers

---

cmake/OpenCVFindIPP.cmake
cmake/OpenCVModule.cmake
doc/Doxyfile.in
modules/core/include/opencv2/core/hal/intrin.hpp
modules/core/include/opencv2/core/hal/intrin_cpp.hpp
modules/core/src/arithm.cpp
modules/core/src/mathfuncs_core.dispatch.cpp
modules/core/src/matrix_transform.cpp
modules/core/test/test_arithm.cpp
modules/core/test/test_intrin_utils.hpp
modules/core/test/test_operations.cpp
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/imgproc/test/ocl/test_imgproc.cpp
modules/python/src2/cv2.cpp
modules/python/src2/gen2.py
modules/python/src2/hdr_parser.py
modules/python/src2/pycompat.hpp
modules/videoio/src/cap_avfoundation.mm
modules/videoio/src/cap_avfoundation_mac.mm
modules/videoio/src/cap_mjpeg_encoder.cpp

#18952 from terfendail:wui_doc
#19681 from eplankin:link_problem
#19793 from aarongreig:aaron/imgproc/relaxCornerEigenValTest
#19798 from LupusSanctus:am/reduce_sum_ch
#19808 from alalek:3.4_python_fix_wrap_as
#19809 from alalek:issue_19513
#19811 from alalek:issue_19599
#19812 from alalek:workaround_19634
#19813 from alalek:issue_19506
#19814 from alalek:pyopencv_to_safe
#19819 from alalek:cmake_fix_headers_order
Previous "Merge 3.4": #19796
<cut/>
<details>
```
#buildworker:Custom=linux-1,linux-2,linux-4,linux-6
#build_image:Custom=powerpc64le …
```

(4.x) Merge 3.4

---

modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/test/test_gapi_sample_pipelines.py
modules/python/src2/cv2.cpp
modules/python/src2/gen2.py

- extra methods through `PYOPENCV_EXTRA_METHODS_<NS_UPPER>` macros
- extra constants through `PYOPENCV_EXTRA_CONSTANTS_<NS_UPPER>` macros
- rename cv.gapi_wip_op => cv.gapi.wip.op
- rename cv.gapi_wip_kernels => cv.gapi.wip.kernels
- Validation: `help(cv.gapi.wip)`
Requested here:
- https://github.com/opencv/opencv/pull/19351#discussion_r603290166
- https://github.com/opencv/opencv/pull/19804#discussion_r604036516
<cut/>
```
Help on module cv2.gapi.wip in cv2.gapi:
NAME
cv2.gapi.wip
FUNCTIONS
kernels(...)
kernels(...) -> GKernelPackage
make_capture_src(...)
make_capture_src(path) -> retval
.   * @brief OpenCV's VideoCapture-based streaming source.
.    *
.    * This class implements IStreamSource interface.
.    * Its constructor takes the same parameters as cv::VideoCapture does.
.    * …
```

Python: allow to customize Python namespaces

---

modules/python/bindings/CMakeLists.txt

- with changes backport from 4.x (#19319)
relates #19819

cmake: fix files order in Python bindings

---

modules/videoio/src/cap_avfoundation.mm
modules/videoio/src/cap_avfoundation_mac.mm

backport changes from #19821
relates #19809

videoio(build): eliminate inconsistent 'override' warnings

---

apps/model-diagnostics/model_diagnostics.cpp

relates #19693
<cut/>
Compiler message (Ubuntu 20.04):
> /build/master_openvino-skl-lin64/opencv/apps/model-diagnostics/model_diagnostics.cpp:57:34: warning: cast between incompatible function types from 'void (*)(const cv::Exception&)' to 'cv::ErrorCallback' {aka 'int (*)(int, const char*, const char*, const char*, int, void*)'} [-Wcast-function-type]
```
57 |     redirectError((ErrorCallback)diagnosticsErrorCallback, NULL);
|                                  ^~~~~~~~~~~~~~~~~~~~~~~~
```
```
```

apps(model_diagnostics): fix invalid callback

---

modules/gapi/include/opencv2/gapi/garray.hpp
modules/gapi/test/gapi_array_tests.cpp

If GArray<GArray<U>> wasn't an input or an output of a graph, assertion would fail.
Added test to check the fix works
``` …
```

[G-API] Fix bug of GArray<GArray> passing through a graph

---

doc/tutorials/dnn/dnn_pytorch_tf_segmentation/pytorch_sem_segm_model_conversion_tutorial.md
doc/tutorials/dnn/dnn_pytorch_tf_segmentation/tf_sem_segm_model_conversion_tutorial.md
doc/tutorials/dnn/table_of_content_dnn.markdown
samples/python/tutorial_code/dnn/dnn_conversion/common/test/voc_segm_test.py
samples/python/tutorial_code/dnn/dnn_conversion/pytorch/segmentation/py_to_py_fcn_resnet50.py

GSoC project: "Write a tutorial about training a network in TF or PyTorch and then running it in OpenCV"
**Part 1.** [Classification case](https://github.com/opencv/opencv/pull/17604)
**Part 2.** Segmentation case:
* TensorFlow DNN (FCN example) => DNN conversion => OpenCV [Net](https://docs.opencv.org/4.3.0/db/d30/classcv_1_1dnn_1_1Net.html) object
* PyTorch DNN (FCN example) => DNN conversion => OpenCV [Net](https://docs.opencv.org/4.3.0/db/d30/classcv_1_1dnn_1_1Net.html) object
* Evaluation
<cut/>

[GSoC] Added TF and PyTorch segmentation conversion cases

---

modules/core/include/opencv2/core/version.hpp

OpenCV 3.4.14
relates #19656
<cut/>
<details>
[opencv_world3414.dll (vc14)](https://www.virustotal.com/gui/file/b87ee686227781321fcd99294499c84e8cf4091edcc8672eda17d9528aa11706/detection)
[opencv_world3414d.dll (vc14)](https://www.virustotal.com/gui/file/2c78cbb32d8d6b1604a908128235b962065b789bf89d231510a04d720cdc9497/detection)
[opencv_world3414.dll (vc15)](https://www.virustotal.com/gui/file/b0637e5738b272351a78b126f8e57f5b32846bad92cded6abb6fccc6db3ff491/detection)
[opencv_world3414d.dll (vc15)](https://www.virustotal.com/gui/file/58b8d4a99409f51e80e7026df88fec366ba085317a762e224b0fa3c5133b6447/detection)
[opencv_ffmpeg3414_64.dll](https://www.virustotal.com/gui/file/3f61eaff916f22b95a444ccde7d30c75423b1b8bfbbdb6b6f3e987fafed9d77e/detection) …

release: OpenCV 3.4.14

---

modules/gapi/test/gapi_async_test.cpp

relates #19678
unlock code compilation, but tests will fail with error message

gapi(test): avoid compilation failure with GCC11

---

modules/core/include/opencv2/core/version.hpp

OpenCV 4.5.2
relates #19657
<cut/>
<details>
[opencv_world451.dll (vc14)](https://www.virustotal.com/gui/file/f72879b346bebdf89daea53674a9bebc7f40806b6d76ec6fb71bfb6be4493ce3/detection)
[opencv_world451d.dll (vc14)](https://www.virustotal.com/gui/file/162588e825258c56e7df72e65de4a52404030ce12c761d566372b98ea4020b72/detection) 
[opencv_world451.dll (vc15)](https://www.virustotal.com/gui/file/420fb5da01508fa860b8b525afad68b47e1f29e87c83b7ed0acf834c2ed25d09/detection)
[opencv_world451d.dll (vc15)](https://www.virustotal.com/gui/file/35850a521dfce4eae91d21f9e9c09ed9b11b7e3b99a8cb11f4a9954026a02cda/detection)
[opencv_ffmpeg451_64.dll](https://www.virustotal.com/gui/file/8f373e1ab44860c125e93471e916a08180c0921c12b485d62f1158ec0026cc9c/detection) …

release: OpenCV 4.5.2

---

modules/gapi/test/streaming/gapi_streaming_tests.cpp

Problem: TestTwoVideosDifferentLength has incorrect skip for setSource().
relates #19844
<cut/>
```
```

G-API: Adding a skip for failed streaming test

---

modules/calib3d/src/fundam.cpp

This commit passes the parameter maxIters that represent
the maximum number of iterations, that can be passed to findFundamentalMat
to the method LMeDS.
This parameter were added to the function findFundamentalMat and
were passed just for the RANSAC method, but should be passed to
both methods to be consistent.
Related work: https://github.com/opencv/opencv/pull/16498

Add maxIters parameter to LMeDS method in findFundamentalMat

---

modules/core/perf/opencl/perf_arithm.cpp
modules/imgproc/perf/opencl/perf_imgproc.cpp
modules/imgproc/test/ocl/test_imgproc.cpp

Also bring perf_imgproc CornerMinEigenVal accuracy requirements in line with
the test_imgproc accuracy requirements on that test and fix indentation on
the latter.
Partially addresses issue #9821

Relax accuracy requirements in the OpenCL sqrt perf arithmetic test.

---

modules/videoio/src/cap_android_camera.cpp

Follow up to #19597 to address https://github.com/opencv/opencv/pull/19597#discussion_r601683120
Adds support for setting the color conversion with the CV_CAP_PROP_FOURCC property
Removes support for CAP_PROP_CONVERT_RGB property
Sample at https://github.com/komakai/NdkCamtest updated to use the FOURCC property
Based on feedback from @xhj14012 add logging to warn that setting exposure/ISO property has no effect unless AutoExposure is off
```
android_pack_config=ndk-18-api-level-24.config.py
```

Fix Android NDK camera's color format conversions

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/five-point.cpp

Lets the user choose the maximum number of iterations the robust
estimator runs for, similary to findFundamentalMat
and findHomography functions.
Original issue: https://github.com/opencv/opencv/issues/19845
Related work: https://github.com/opencv/opencv/pull/16498

Expose maxIters in findEssentialMat

---

modules/highgui/src/window.cpp

this fixes issue #19870
`HAVE_QT` and `HAVE_WIN32UI` can both be true at the same time
if `HAVE_QT`, `window_w32.cpp` is not included in the build, see `CMakeLists.txt`
code for `HAVE_WIN32UI` must be inactive if `HAVE_QT`
empty cases added to implement this

fix for #19870

---

modules/ml/src/boost.cpp
modules/ml/src/rtrees.cpp
modules/ml/test/test_rtrees.cpp

Addresses https://github.com/opencv/opencv/issues/12974, although that issue incorrectly mentions the saving/loading of the model, which is not relevant. The source of the issue is no validation when calling the `predict` method, which we have in other models i.e;
- https://github.com/opencv/opencv/blob/master/modules/ml/src/svm.cpp#L2013
- https://github.com/opencv/opencv/blob/master/modules/ml/src/knearest.cpp#L370
- https://github.com/opencv/opencv/blob/master/modules/ml/src/nbayes.cpp#L314

Fix bug with predictions in RTrees/Boost

---

modules/features2d/include/opencv2/features2d.hpp

Related to https://github.com/opencv/opencv/issues/12976, removes virtual inheritance from Features2D, as it no longer appears to be necessary (there is no longer a diamond inheritance structure).

Remove virtual inheritance from Feature2D

---

doc/tools/html_functions.py

resolves #19896
<strike>omit generating a return value for `None` in the docs</strike>
[edit] generate a more pythonic `func() -> ret` signature

docs:fix python retvals

---

modules/core/src/precomp.hpp
modules/core/src/system.cpp

core: avoid process cleanup deadlock if TlsStorage is not used

---

cmake/OpenCVModule.cmake

related #19819
There can exist modules without headers causing configuration issue:
```
CMake Error at /opencv/cmake/OpenCVModule.cmake:883 (list):
list sub-command SORT requires list to be present.
```

Fix header sorting for modules without headers

---

modules/python/package/cv2/__init__.py

Currently, the LOADER_DIR is set to os.path.dirname(os.path.abspath(__file__)). This does not point to the true library path if the cv2 folder is symlinked into the Python package directory such that importing cv2 under Python fails. The proposed change only resolves symbolic links correctly by calling os.path.realpath(__file__) first and does not change anything if __file__ contains no symbolic link.
- [] The PR is proposed to proper branch

Update __init__.py to support symbolic links

---

modules/photo/src/contrast_preserve.hpp

fix a build warning:
```
C:\Slave\workspace\precommit\windows10\opencv\modules\photo\src\contrast_preserve.hpp(289): warning C4244: '=': conversion from 'double' to '_Tp', possible loss of data
with
[
_Tp=float
]
C:\Slave\workspace\precommit\windows10\opencv\modules\photo\src\contrast_preserve.hpp(361): warning C4244: '=': conversion from 'double' to '_Tp', possible loss of data
with
[
_Tp=float
]
```
(from https://build.opencv.org.cn/job/precommit/job/windows10/1633/console)

photo: Update contrast_preserve.hpp

---

modules/dnn/src/layers/crop_and_resize_layer.cpp

The fix complements [#17998](https://github.com/opencv/opencv/pull/17998)
```
```

Explicit usage of int64_t in CropAndResizeLayer (IE backend)

---

modules/imgproc/src/contours.cpp
modules/imgproc/test/test_contours.cpp

This pull requests slightly modifies the behaviour of findContours() when the `mode` flag is set to `RETR_TREE`, in order to avoid a subtle bug.
In the uncommon case that the same border pixel belongs to two different contours marked with the same index, it is important to be able to tell which of the two contours is the "last one encountered", in order to reliably find a father for the next contour met during the scan. This pull request address that specific case.
```
```

Fix #4363 - wrong hierarchy (RETR_TREE) in findContours

---

CMakeLists.txt

[OpenCV's minimum CMake version is 3.5.1](https://github.com/opencv/opencv/blob/68d15fc62edad980f1ffa15ee478438335f39cc3/cmake/OpenCVMinDepVersions.cmake#L1-L3), so these checks are unneeded.

Remove extraneous CMake version checks, minimum required version is 3.5.1

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp
modules/imgcodecs/src/loadsave.cpp
modules/imgcodecs/test/test_tiff.cpp

The current implementation of `imreadmulti` reads all images from the multipage file, sometimes this is not the required functionality, for example due to memory contraints, or really just wanting to target a specific subrange of the multipage file. This PR allows any subsequence to be read . 

Add reading of specific images from multipage tiff

---

modules/videoio/include/opencv2/videoio/registry.hpp
modules/videoio/src/backend.hpp
modules/videoio/src/backend_plugin.cpp
modules/videoio/src/backend_static.cpp
modules/videoio/src/videoio_registry.cpp
modules/videoio/test/test_plugins.cpp

to properly disable unsupported test cases / configurations in PR #19755 (plugins support for UMat will be added later in a separate PR)

videoio(plugin): add query API for plugins

---

modules/core/include/opencv2/core/cvdef.h

https://github.com/opencv/opencv/pull/16125

Fix missing return type for unsafe CV_XADD function

---

cmake/OpenCVFindOpenEXR.cmake
modules/imgcodecs/src/grfmt_exr.cpp

Try to find OpenEXR 3.0 using the upstream cmake config, and fallback to the previous algorithm if not found
- [x ] I agree to contribute to the project under Apache 2 License.
- [x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x ] The PR is proposed to proper branch

Support building with OpenEXR 3.x

---

modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

Infer kernels in `IE` backend works asynchronously and implemented via `RequestPool` which has a set of `InferRequest`'s and concurrent bounded queue to track free requests.
Before run the task `RequestPool` pop first free request and if there are no free requests it blocks. (*)     
When execution is finished (all frames are processed or at least started processing) need to wait for all requests are free.
There is some trick: try to pop all requests from queue, if specific request is busy it blocks until it's free. When it finishes guarantee all requests are free, **but the queue of free requests is empty**.
```cpp
cv::GArray<cv::Rect> rr; …
```

G-API: Fix infer hanging

---

modules/videoio/cmake/detect_msdk.cmake
modules/videoio/src/cap_mfx_common.hpp

* https://github.com/oneapi-src/oneVPL
* https://oneapi-src.github.io/oneAPI-spec/elements/oneVPL/source/VPL_intel_media_sdk.html
* uses legacy MediaSDK interface
Things to do on the next step:
* don't use `mfxvideo++.h`
* init using `MFXLoad()`
Tested with open-source version on Windows and oneAPI 2021.2 on Windows and Linux.
<cut/>
```
```

Initial oneVPL support

---

samples/cpp/squares.cpp

Fix samples/cpp/squares.cpp:
```
$ ../build/opencv_squares pic1.png 
A program using pyramid scaling, Canny, contours and contour simplification
to find squares in a list of images (pic1-6.png)
Returns sequence of squares detected on the image.
Call:
./../build/opencv_squares [file_name (optional)]
Using OpenCV version 4.5.2-dev
[ WARN:0] global /home/alexander/git/opencv/modules/core/src/utils/samples.cpp (59) findFile cv::samples::findFile('0') => ''
terminate called after throwing an instance of 'cv::Exception'
what():  OpenCV(4.5.2-dev) /home/alexander/git/opencv/modules/core/src/utils/samples.cpp:62: error: (-2:Unspecified error) OpenCV samples: Can't find required data file: 0 in function 'findFile'
Aborted (core dumped)
```
It tries to find file "0" and fails.
See details at …

Fix squares sample failure when a single file passed

---

modules/imgcodecs/include/opencv2/imgcodecs.hpp
modules/imgcodecs/src/grfmt_exr.cpp

Issue https://github.com/opencv/opencv/issues/19925
OpenEXR 1.7.1 provided with CentOS 7 does not support `DWAA_COMPRESSION` and `DWAB_COMPRESSION` compression options.

Fix OpenCV build with OpenEXR before 2.2.0

---

modules/video/src/ecc.cpp
modules/video/test/test_ecc.cpp

Addresses https://github.com/opencv/opencv/issues/14657. The problem in the original issue was they were using unsigned int values. This causes problems in the ECC computation, as subtracting the mean will result in certain being 0 instead of negative, and this impacts the dot product / norm.
I know this isn't pretty - the alternative solution is just raise an exception if a matrix of type `CV_8U` or `CV_16U` is supplied.

Fix unsigned int bug in computeECC

---

modules/stitching/src/matchers.cpp

Address edge case described here: https://github.com/opencv/opencv/issues/5240 if `range_width_` is 1, then the the inner loop will never execute. 

Fix Edge Case in Matcher Loop

---

modules/calib3d/include/opencv2/calib3d.hpp

- Added missing documentation for the CALIB_FIX_FOCAL_LENGTH flag
- Removed erroneous information about the number of distortion coefficients
returned
- Added some missing @ref tags

calib3d: Update documentation of calibrateCamera

---

modules/python/src2/gen2.py
modules/python/test/test_cuda.py

this corrects bug #16592 where a Stream is created at
each GpuMat::load(arr,stream) call
a correct solution would have been to add a default to GpuMat::load
but due to circular dependence between Stream and GpuMat, this is not possible
<cut/>
<details>
```
```
</details>

Stream default to Stream::Null() when no default in function prototype

---

samples/dnn/openpose.py

samples/dnn: better errormsg  in openpose.py

---

modules/flann/include/opencv2/flann/any.h

There are a handful of static initializers in our binary which originate from the opencv library. All of them are attributed to the `policy` private static member of the templated `SinglePolicy` class:
[opencv2/flann/any.h#L176](https://github.com/jstaahl/opencv/blob/3.4/modules/flann/include/opencv2/flann/any.h#L176).
These can be avoided by using the Meyer singleton pattern for the `get_policy()` function.
issue report: https://github.com/opencv/opencv/issues/20051

Remove static initializers

---

modules/gapi/src/backends/ie/giebackend.cpp

Disable auto fusing in ie backend

---

samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp

There was a typo in the tutorial code on camera calibration.
The original author probably meant to say 'undistorted', but the corresponding variable was named 'undistorsed'.
This PR fixes this typo issue.
---

Fix typo in calib3d tutorial code

---

modules/objdetect/misc/java/test/QRCodeDetectorTest.java

Possible fix for failing test
https://build.opencv.org.cn/job/precommit/job/ubuntu-20.04-arm64/1868/
Assuming that `QRCodeDetector.detectAndDecodeMulti` does not guarantee the QR Codes are returned in any specific order then this I think this fix is reasonable

Fix for failing QRCodeDetectorTest.testDetectAndDecodeMulti test

---

modules/gapi/src/backends/ie/giebackend.cpp

[G-API] IE backend convert fp32 to fp16

---

modules/core/misc/objc/common/Point2i.h
modules/core/misc/objc/common/Rect2i.h
modules/core/misc/objc/common/Size2i.h
modules/core/misc/objc/common/Typealiases.swift
modules/core/misc/objc/gen_dict.json
platforms/ios/build_framework.py
platforms/osx/build_framework.py

This PR hopefully addresses a few issues that have been giving trouble when building the Swift wrapper for iOS/macOS
- add a build flag `disable-swift` flag to suppress building Swift extensions
- when the `disable-swift` is set - still generate Swift extensions and put them in SwiftSources output folder such they can be added manually to a project if needed
- change to use `typealias` instead of `NS_SWIFT_NAME` to handle Point2i → Point, Rect2i → Rect, Size2i → Size type mappings (thanks to @chrisballinger for this)
Issue that may be fixed or partially fixed by this PR: #19645 #19992 #19254
```
force_builders=docs,ios,Custom Mac
buildworker:Custom Mac=macosx-1
```

Fixes for Swift troubles

---

modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/phasecorr.cpp
modules/imgproc/test/test_pc.cpp

Make the function divSpectrums public.  A unit test to verify the function for supported input types and flags is added.
This feature is requested in https://github.com/opencv/opencv/issues/19767.

Make div spectrums public

---

doc/opencv.bib

---
**Warning: issue is still present with this PR. Maybe someone will found the solution**
---
See:
- [How to use the month field in BibTeX?](https://www.bibtex.com/f/month-field/)
- [Bibtex day and Month Problem](https://tex.stackexchange.com/questions/345321/bibtex-day-and-month-problem)
Unfortunately, there are still some issues (year is still not rendered for the two entries).
- In current master, [e.g. 1](https://docs.opencv.org/master/d0/de3/citelist.html#CITEREF_Tsai89), [e.g. 2](https://docs.opencv.org/master/d0/de3/citelist.html#CITEREF_Park94):
- **With this PR, issue is still present on my computer**
- Removing the `month` or the …

Use correct BibTeX syntax for month field

---

modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/mat.inl.hpp
modules/core/test/test_mat.cpp

This is important to be more standard compliant with C++ and an ever increasing number of people using standard algorithms for better code readability- and maintainability.
The functions are copy pasted from their counterparts (even though they should probably call the counterparts but this gave me some trouble).
They return iterators using std::reverse_iterators
Follow up of an open feature request:
https://github.com/opencv/opencv/issues/4641
Edit: Additionally there should be a test implemented for it. This still has to be done.
```
force_builders=linux,docs,Custom,Win64 …
```

Adding functions rbegin() and rend() functions to matrix class.

---

samples/python/stitching_detailed.py

Seam finder in stitching_detailed.py does not update the masks and output panorama looks blurry because of that. The blurryness problem was mentioned in issue [#14413](https://github.com/opencv/opencv/issues/14413) and seam finder update problem was mention in issue [#15520](https://github.com/opencv/opencv/issues/15520).
To fix the updating problem, DP and Voronoi seam finder result needs to be assigned to a variable. In addition, graph cut seam finder should be removed from the script as it returns None.

Fix seam finder in stitching_detailed.py

---

modules/gapi/include/opencv2/gapi/gcommon.hpp
modules/gapi/include/opencv2/gapi/gstreaming.hpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp

Support queue capacity as graph compilation argument

---

modules/imgproc/src/smooth.simd.hpp
modules/imgproc/test/test_smooth_bitexact.cpp

See issue #20121
The SIMD code in [smooth.simd.hpp](https://github.com/opencv/opencv/blob/5f4e55bc68db4a105fcafa465c19c047d35a2e0e/modules/imgproc/src/smooth.simd.hpp#L1240) adds two pixel values before multiplying by weights, which leads to data overflow:
```cpp
v_mul_expand(vx_load(src + j * cn) + vx_load(src + (n - 1 - j)*cn), vx_setall_u16((uint16_t) *((uint32_t*)(m + j))), v_add0, v_add1);
```
Both 3.4 and master branches are affected.
Test case is also added in this PR.
relates #18983
<cut/>

Fix data overflow problem in GaussianBlur

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/perf/common/gapi_core_perf_tests.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_cpu.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp
modules/gapi/src/api/kernels_core.cpp
modules/gapi/src/backends/cpu/gcpucore.cpp
modules/gapi/src/backends/ocl/goclcore.cpp
modules/gapi/test/common/gapi_core_tests.hpp
modules/gapi/test/common/gapi_core_tests_inl.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/cpu/gapi_core_tests_cpu.cpp
modules/gapi/test/gpu/gapi_core_tests_gpu.cpp

Add `transpose` operation to gapi which is similar with opencv `transpose` https://docs.opencv.org/master/d2/de8/group__core__array.html#ga46630ed6c0ea6254a35f447289bd7404
Add Unit/Perf test
``` …
```

G-API: Add transpose operation

---

doc/py_tutorials/py_feature2d/py_features_harris/py_features_harris.markdown
doc/py_tutorials/py_feature2d/py_shi_tomasi/py_shi_tomasi.markdown
doc/py_tutorials/py_feature2d/py_sift_intro/py_sift_intro.markdown

This PR fixes LaTeX script in [the document](https://docs.opencv.org/3.4/db/d27/tutorial_py_table_of_contents_feature2d.html).
For example, we can use `\det, \operatorname{trace}` instead of `det, trace`.
The screenshot is from [Harris Corner Detection](https://docs.opencv.org/3.4/dc/d0d/tutorial_py_features_harris.html).

Fix LaTeX (MathJax) script in the docs

---

modules/videoio/test/test_video_io.cpp

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14/builds/11543).
Problem is observed on windows-1 buildworker only. windows-2 works for now.
<cut/>
Perhaps this Windows update triggers observed regressions (`Microsoft.VP9VideoExtensions`):
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
<Provider Name="Microsoft-Windows-WindowsUpdateClient" Guid="{945a8954-c147-4acd-923f-40c45405a658}" />
...
<TimeCreated SystemTime="2021-05-26T17:32:44.4278236Z" />
...
</System>
<EventData>
<Data Name="updateTitle">9N4D0MSMP0PT-Microsoft.VP9VideoExtensions</Data>
<Data Name="updateGuid">{11b61434-d23c-4592-9867-d389484d8467}</Data>
<Data Name="updateRevisionNumber">1</Data>
</EventData>
</Event>
```
```
buildworker:Win64=windows-1 …
```

videoio(test): bailout from VP9 tests if first frame can't be read

---

modules/core/src/ocl.cpp
modules/core/test/ocl/test_opencl.cpp

fixup #19334 (reported by @rasmus25: https://github.com/opencv/opencv/pull/19334#issuecomment-849090553)

core(OpenCL): avoid limit of Image kernel args

---

modules/imgproc/src/color_lab.cpp

A Neon specific implementation of RGB2Lab increases single threaded performance by ~25%, here's the numbers run on aws c6gd.4xlarge with gcc 9.3 (numbers are similar using gcc 10)
| Test set   | Test number |    After/before ratio | Speedup with 1/million bounds [%] |
|------------|-------------|----------|-----------------------------------|
| cvtColor8u |           8 |  0.76835 |                        23.2 ± 0.2 |
| cvtColor8u |          34 |  0.76204 |                        23.8 ± 0.2 |
| cvtColor8u |          67 |  0.76667 |                        23.3 ± 0.2 |
| cvtColor8u |          69 |  0.76773 |                        23.2 ± 0.2 |
| cvtColor8u |          71 |  0.76231 |                        23.8 ± 0.2 |
| cvtColor8u |          73 |  0.76184 |                        23.8 ± 0.2 …

Add Neon optimised RGB2Lab conversion

---

modules/imgproc/src/phasecorr.cpp

resolves #20100
Add some std::sqrt() to magSpectrum().
[#20100](https://github.com/opencv/opencv/issues/20100)
```
```

Add missing sqrt to magSpectrum().

---

modules/features2d/include/opencv2/features2d.hpp
modules/features2d/src/mser.cpp
modules/features2d/test/test_mser.cpp
modules/python/test/test_mser.py

Note: copy of https://github.com/opencv/opencv/pull/20022, but applied to `next` instead of `3.4`, as this results in an API change.
Addresses issue described here https://github.com/opencv/opencv/issues/5630. In MSER, `min_diversity` was used for color images but not for grayscale. There was a check to verify variance was positive, which I replaced with checking to verify the variance is greater than `minDiversity`. I also expose setter/getter for `minDiversity`.
Note:
- Had to explicitly set `minDiversity` to 0 (to replicate the original logic) in `history_update_regression`, `cases`, and `test_mser.py` unit tests, as `min_diversity` defaults to 0.2.
Patch to opencv_extra has the same …

Handle minDiversity in Grayscale MSER

---

modules/photo/src/merge.cpp
modules/photo/test/test_hdr.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/873
Addresses https://github.com/opencv/opencv/issues/18180. The issue seemed to be with numerical stability when `w_sum` matrix contained zeroes. Should be merged in conjunction with https://github.com/opencv/opencv_extra/pull/873, which contains test data taken from original issue.

Fix Robertson Calibration NaN Bug

---

modules/core/include/opencv2/core/cv_cpu_dispatch.h
platforms/linux/riscv64-071-gcc.toolchain.cmake

Thanks to @damonyu1989 for bringing us a parallel implementations based on RVV 0.7.1 with pr #19778. However, there is a minor bug that causes conflicts with the existing toolchain.
In [cv_cpu_dispatch.h](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/cv_cpu_dispatch.h#L145), 
```
#if defined(__riscv) && defined(__riscv_vector)
#endif
```
`CV_RVV071` will be defined when `__riscv`, `__riscv_vector` are defined, which are compiler preset macros. This will cause conflicts because any compiler that supports RVV will generate these two macros, not specific to RVV 0.7.1. This means that when you try to compile OpenCV using the toolchain base on the latest RVV draft of the standard, you will incorrectly define the macro `CV_RVV071` and try to reference a header …

Fix RVV toolchain conflicts.

---

modules/gapi/include/opencv2/gapi/infer.hpp
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/shadow_gapi.hpp
modules/gapi/samples/face_detection_mtcnn.cpp

Removed `networks` from shadow_gapi. Added wrapper for networks and `operator +=` for GNetPackage.
``` …
```

G-API: Python. Wrapper for networks.

---

modules/ts/misc/table_formatter.py

ts: migrate from cgi.escape to html.escape in .py file

---

modules/java/test/pure_test/build.xml
modules/ts/misc/run.py
modules/ts/misc/run_suite.py

Replacement: https://github.com/opencv/opencv/pull/20037

Analog of gtest_filter for java tests

---

modules/imgcodecs/src/grfmt_exr.cpp

Hi, some applications can produce float32 depth maps in OpenEXR format and they can use Z channel instead of Y channel (but only Y is supported in OpenCV). And this is quite natural because Z channel is a "Distance of the front of a sample from the viewer" - see [OpenEXR documentation](https://www.openexr.com/documentation/TechnicalIntroduction.pdf).
Currently if you will try to read such float32 .exr image with single Z channel via ```imread(path, cv::IMREAD_UNCHANGED)``` - empty image will be returned.
The proposed fix will try to find Z channel only if no Y channel is found (i.e. this fix is backwards compatible).

EXR reading: support Z channel if no Y channel

---

modules/videoio/src/cap_dshow.cpp

setSizeAndSubtype didn't reset VD->pAmMediaType to the original value when SetFormat fails even though the value is used in multiple places afterwards.

videoio(dshow) fix incompatible media type left set on video device

---

modules/core/include/opencv2/core/mat.hpp
modules/core/perf/opencl/perf_usage_flags.cpp
modules/core/src/ocl.cpp
modules/core/src/umatrix.cpp
modules/core/test/test_opencl.cpp

fixes opencv/opencv#19807
* Request code review of these changes before merge.
* I do not recommend merging this until after code review, then I try this on the 3.x branch, and then I make any needed changes. ***I have not done any coding or testing of this on the 3.x legacy branch.*** I request code review of this approach before I do anything in 3.x
* Clarified doxygen comments on some fields of `cv::UMat`
* Please consider my notes and caveats at https://github.com/opencv/opencv/issues/19807#issuecomment-810645975
I have been using this in my own code for one month with opencl on/off and with two GPUs (intel and nvidia).
Passes all core unit tests when applied to the 4.5.2 branch.
No known issues.
```
[ SKIPSTAT ] 36 tests skipped
[ …
```

UMat usageFlags fixes opencv/opencv#19807

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/perf/perf_undistort.cpp
modules/calib3d/src/undistort.dispatch.cpp
modules/calib3d/test/test_undistort.cpp
modules/ts/include/opencv2/ts.hpp
modules/ts/src/ts_func.cpp

This pull request adds a function to Calib3D to support inverse rectification in procam systems. Essentially, it provides the inverse of initUndistortRectifyMap() such that projectors are properly handled in stereo-rectified projector-camera pairs.
**Why is this function needed?** Inverse rectification has been incorrectly applied in many works, including mishandling of distortion coefficients. Hopefully this proposed function will help curb this trend. 
_Once successfully merged, a duplicate function can be added for fisheye calibration._
- [NA] There is reference to original bug report and related work
- [?] There is accuracy test, performance test and test data in opencv_extra repository, if applicable

Added initInverseRectificationMap()

---

modules/gapi/include/opencv2/gapi/infer.hpp
modules/gapi/include/opencv2/gapi/infer/ie.hpp

https://pullrequest.opencv.org/buildbot/export/pr/20169/docs/
``` …
```

[G-API] Generic type documentation

---

modules/3d/include/opencv2/3d.hpp
modules/3d/src/octree.cpp
modules/3d/src/octree.hpp
modules/3d/test/test_octree.cpp

Hi, recently we want to contribute an `octree` class to the `next` branch. We read some implementations in open source projects, such as Open3D, PCL, Octomap. They all contain octrees, but their implementation is different.
In the current PR, we have only implemented some very basic functions. 
Before improving it, we have the following doubts:
- Which functions of the octree in the `next` branch should be implemented? 
- What is the role of the `octree` in the `3d` module in the future?
Looking forward to your opinion, thank you.

Add Octree to 3D module in next branch - in progress

---

modules/calib3d/include/opencv2/calib3d.hpp

Fixed missing hyperlink references throughout calib3d documentation. 
- [NA] There is reference to original bug report and related work
- [NA] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [NA] The feature is well documented and sample code can be built with the project CMake

Calib3d update hyperlinks

---

modules/dnn/src/cuda4dnn/csl/cublas.hpp
modules/dnn/src/cuda4dnn/csl/tensor.hpp
modules/dnn/src/cuda4dnn/csl/tensor_ops.hpp
modules/dnn/src/cuda4dnn/primitives/matmul.hpp
modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/test/test_onnx_importer.cpp

Adds a new MatMulOp which performs strided batched GEMM (or regular GEMM when effective tensor ranks are two or below) on runtime blobs.
resolves #19929 
```
build_image:Custom=ubuntu-cuda-cc52:18.04
```

cuda4dnn(MatMul): add MatMulOp

---

modules/video/src/tracking/tracker_dasiamrpn.cpp

This PR fixes the incorrect structure of best score ID and prevents out of range indexing and incorrect access to `cv::Mat`

Tracking API: fix incorrect structure

---

3rdparty/ffmpeg/ffmpeg.cmake
modules/videoio/test/test_video_io.cpp

**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/65
- FFmpeg 4.4
- libvpx 1.10.0
previous update: #19666
```
```

ffmpeg/4.x: update FFmpeg wrapper 2021.06

---

modules/gapi/include/opencv2/gapi/infer/ie.hpp
modules/gapi/include/opencv2/gapi/infer/onnx.hpp

Documentation for cfg_functions of Params.
Docs:  http://pullrequest.opencv.org/buildbot/export/pr/20112/docs/
``` …
```

G-API: Documentation for Params (IE and ONNX).

---

modules/core/src/norm.cpp
modules/core/test/test_arithm.cpp

There can be an int overflow.
cv::norm( InputArray _src, int normType, InputArray _mask ) is fine,
not cv::norm( InputArray _src1, InputArray _src2, int normType, InputArray _mask ).
The fix and bug were both introduced in 34530da
```
```

Fix potential NaN in cv::norm.

---

modules/gapi/include/opencv2/gapi/infer/parsers.hpp
modules/gapi/src/backends/cpu/gcpucore.cpp
modules/gapi/src/backends/cpu/gnnparsers.cpp
modules/gapi/src/backends/cpu/gnnparsers.hpp

Added specialization for ParseSSD functions with different return values. Unfortunately needs call `cv::gapi::parseSSD<GArray<Rect>>` for second version of ParseSSD. But all samples use first version of ParseSSD with tuple in return value. 
Returned overloads, removed defaults from second function variant.
``` …
```

G-API: Removing ParseSSD overload.

---

modules/highgui/src/window_gtk.cpp

Fixing https://github.com/opencv/opencv/issues/20073.
According to https://developer.gnome.org/gtk3/stable/checklist-modifiers.html: "With `gtk_accelerator_get_default_mod_mask()` you can test for modifier keys reliably; this way your key event handlers will work correctly even if `NumLock` or `CapsLock` are activated. "

Apply modifier mask to the state of modifier keys

---

modules/features2d/include/opencv2/features2d.hpp
modules/features2d/src/draw.cpp

This commit adds the feature of selecting the thickness
of the matches drawn by the drawMatches function.
In larger images, the default thickness of 1 pixel creates images
that are hard to visualize.
resolves https://github.com/opencv/opencv/issues/20095

Add Thickness parameter in drawMatches function

---

modules/dnn/src/layers/batch_norm_layer.cpp

resolves : #20280
related discussion on a similar issue https://github.com/opencv/opencv/pull/20228#discussion_r648196526
<cut/>
```
```

dnn : Fix NaNs during BatchNorm reinitialization

---

modules/features2d/src/sift.simd.hpp

Reduce branch density by collapsing compares.
Performance improvements from 1.03 to 1.53 with existing tests
<cut/>
```
% ./modules/ts/misc/summary.py -u us -m median ./build-{3.4,improv-sift}/*.xml | grep SIFT
(x-factor)
detect::OCL_feature2d::(SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png") 50256.333 48789.417 1.03
detect::OCL_feature2d::(SIFT_DEFAULT, "stitching/a3.png") 64591.083 52250.542 1.24
detect::OCL_feature2d::(SIFT_DEFAULT, "stitching/s2.jpg") 132094.667 99417.667 1.33
detect::feature2d::(SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png") 77521.167 60114.083 1.29
detect::feature2d::(SIFT_DEFAULT, "stitching/a3.png") 70179.083 55914.917 1.26
detect::feature2d::(SIFT_DEFAULT, "stitching/s2.jpg") 137359.208 …
```

Improve SIFT for arm64/Apple silicon

---

modules/core/include/opencv2/core/mat.hpp
modules/core/src/matrix_operations.cpp
modules/core/src/umatrix.cpp
modules/core/test/ocl/test_matrix_expr.cpp

updates the `UMat` static factories to accept a `UMatUsageFlags` param
- aligns the static factories (zeros, ones, eye, diag) with the `UMat` constructors
- defaults to `USAGE_DEFAULT` making these changes backwards compatible
- adds test case
- only tested on 4.x branch. *Do not apply to legacy 3.x* because this PR is useless without the 4.x-only https://github.com/opencv/opencv/pull/20027

add usageFlags to UMat static factories

---

modules/calib3d/src/chessboard.cpp

There are several operator= overloads and some compilers can be confused.
This is not present in 3.4. I cannot get my compiler options but here is the error I get:
error: use of overloaded operator '=' is ambiguous (with operand types 'cv::Mat' and 'int')
meta = 0;
~ ^ ~
./include/opencv2/core/mat.hpp:1070:10: note: candidate function
Mat& operator = (const Mat& m);
^
./include/opencv2/core/mat.hpp:1257:10: note: candidate function
Mat& operator = (const Scalar& s);
^
./include/opencv2/core/mat.hpp:2099:10: note: candidate function
Mat& operator = (Mat&& m);

Do not use = 0 for a cv::Mat.

---

modules/core/src/system.cpp

The call to `setData` may throw an exception without `CV_THREAD_SANITIZER`.
This fix is to avoid the memory leak on `pData` when exception is thrown.

fix memory leak when exception is thrown

---

modules/core/misc/java/src/java/core+MatAt.kt
modules/core/misc/objc/common/Mat.mm
modules/core/misc/objc/common/MatExt.swift
modules/core/misc/objc/test/MatTest.swift

On Java there are no signed type so the Java binding just handles CV_8U as CV_8S and CV_16U as CV_16S
The Objective-C/Swift binding mostly just followed the Java binding as much as possible so the original implementation also does not have good handling for CV_8U and CV_16U.
This PR:
- adds Mat.put/Mat.get functions for Swift/Kotlin using the relevant unsigned types (UInt8/Uint16/UByte/UShort)
- updates other functions to use the new Mat.put/Mat.get functions
- fixes a bug in the Objective-C [Mat put:(int)row col:(int)col data:(NSArray<NSNumber*>*)data] implementation
- adds tests for the new unsigned put/get functions on Swift
```
force_builders=docs,ios,Custom Mac …
```

Improvements/fixes for unsigned type handling in Swift/Kotlin

---

samples/cpp/tutorial_code/Histograms_Matching/MatchTemplate_Demo.cpp
samples/cpp/tutorial_code/Histograms_Matching/calcBackProject_Demo1.cpp
samples/cpp/tutorial_code/Histograms_Matching/calcHist_Demo.cpp

`float* histRange = { range };` doesn't make much sense. `histRange` is
an array of array(s), so it should have a type of ptr to ptr. Strangely
some domos are correct as well as the example for the function
https://docs.opencv.org/master/d6/dc7/group__imgproc__hist.html#ga4b2b5fd75503ff9e6844cc4dcdaed35d

Fix an arg for calcHist() in demos

---

modules/videoio/src/cap_msmf.cpp

resolves #17687
Fix issue #17687 using @ercarpio suggestion to set MF_READWRITE_ENABLE_HARDWARE_TRANSFORMS  to false. 
Without this fix, some webcams take a few minutes to startup using MSMF on Windows, whereas it should be instantaneous.
My webcam was having this delay issue and it solved for me as well. From my experiments there were no drawbacks so far.
Would appreciate more testing on this with broader range of webcams as I don't have many to test by myself.
Kindly request @mshabunin for review, as he asked this pull request.
<cut/>

fix #17687 MSMF slow webcam startup

---

modules/core/include/opencv2/core/opencl/opencl_info.hpp
modules/core/src/ocl.cpp
modules/ts/src/ocl_perf.cpp
modules/ts/src/ts_perf.cpp

This pull request is refactored from #20288, to remove incomplete/problematic changes to GEMM.
Now, the changes include the following:
* Support cl_image conversion for CL_HALF_FLOAT (float16)
* Support cl_image conversion for additional channel orders:
CL_A, CL_INTENSITY, CL_LUMINANCE, CL_RG, CL_RA
* Comment on why cl_image conversion is unsupported for CL_RGB
* Predict optimal vector width for float16
* ocl::kernelToStr: support float16
* ocl::Device::halfFPConfig: drop artificial requirement for OpenCL
version >= 1.2. Even OpenCL 1.0 supports the underlying config
property, CL_DEVICE_HALF_FP_CONFIG.
* dumpOpenCLInformation: provide info on OpenCL half-float support
and preferred half-float vector width
* randu: support default range [-1.0, 1.0] for float16
``` …
```

[refactored] OpenCL: core support for more formats, including float16

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: opencv/opencv_extra#879
resolves : #20273 #20332
Similar to patch for tensorflow importer #13359
<cut/>
```
YOLO*:*VINO*:*Infer*:*Layer*:*layer*
```

dnn : modified onnx importer to concat const input blobs

---

modules/gapi/include/opencv2/gapi/gstreaming.hpp
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/shadow_gapi.hpp
modules/gapi/misc/python/test/test_gapi_streaming.py
modules/gapi/src/compiler/gstreaming.cpp
modules/gapi/src/compiler/gstreaming_priv.hpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.hpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp

Wrapping desync operation for Python.
Questionable place of m_desync flag.
``` …
```

G-API: Python. Desync.

---

modules/gapi/src/backends/ie/giebackend/giewrapper.cpp

Deprecated in OpenVINO 2021.4
Resolves warnings from here: http://pullrequest.opencv.org/buildbot/builders/precommit_custom_linux/builds/6221
relates #20325
<cut/>
```
test_modules:Custom=dnn,python2,python3,java,gapi
test_modules:Custom Win=dnn,python2,python3,java,gapi
test_modules:Custom Mac=dnn,python2,python3,java,gapi
YOLO*:*VINO*:*Infer*:*Layer*:*layer*
```

G-API(IE): replace deprecated calls

---

modules/dnn/misc/java/gen_dict.json
modules/java/generator/gen_java.py
modules/video/misc/java/test/TrackerCreateTest.java

resolves #19915
Conflict base/derived classes:
<cut/>
```
ClassificationModel <= Model
DetectionModel <= Model
KeypointsModel <= Model
SegmentationModel <= Model
TextDetectionModel <= Model
TextRecognitionModel <= Model
BOWKMeansTrainer <= BOWTrainer
TrackerDaSiamRPN <= Tracker
TrackerGOTURN <= Tracker
TrackerMIL <= Tracker
```

Java: force using of 'Ptr<>' for OpenCV classes

---

modules/dnn/src/layers/normalize_bbox_layer.cpp

[`using v0::NormalizeL2`](https://github.com/openvinotoolkit/openvino/blob/5cee8bbf29797f4544b343e803de957e9f041f92/ngraph/core/include/ngraph/op/normalize_l2.hpp#L60) is going to be removed from the ngraph op namespace so the external usages need to be updated.
```
YOLO*:*VINO*:*Infer*:*Layer*:*layer* …
```

Use explicit version of ngraph NormalizeL2

---

cmake/OpenCVDetectInferenceEngine.cmake

backport #20026 + CMake fixes
```
force_builders_only=Custom,Custom Win,Custom Mac
build_image:Custom Win=openvino-2021.4.0-autovers
```

cmake(IE): extract INF_ENGINE_RELEASE from InferenceEngine package

---

cmake/OpenCVCompilerOptions.cmake

resolves #20285
`platforms/js/build_js.py --threads` uses `-pthread`.
```
```

cmake: exclude -pthread from Emscripten default build

---

modules/core/include/opencv2/core/version.hpp

OpenCV 3.4.15
relates #20236
<cut/>
<details>
[opencv_world3415.dll (vc14)](https://www.virustotal.com/gui/file/7f92e88814465cffda4c7b3ae79a3deeabd3a594c5da48226649ea0228071a05/detection)
[opencv_world3415d.dll (vc14)](https://www.virustotal.com/gui/file/fb74c7209dd0797e670cf52ed2868ec0cc8abada9c818963b8d7327095c54c7e/detection)
[opencv_world3415.dll (vc15)](https://www.virustotal.com/gui/file/3efb02b69038309da6adc09ed9b4688c966cf88871d433a49687c3840aba9343/detection)
[opencv_world3415d.dll (vc15)](https://www.virustotal.com/gui/file/7820efdf7a466ef3ab077302ffe5f5dc79520cf432d505d3b692ff79ac59a3fb/detection)
[opencv_ffmpeg3415_64.dll](https://www.virustotal.com/gui/file/3f61eaff916f22b95a444ccde7d30c75423b1b8bfbbdb6b6f3e987fafed9d77e/detection) …

release: OpenCV 3.4.15

---

modules/videoio/src/container_avi.cpp

In https://github.com/opencv/opencv/pull/10145 refactoring VideoInputStream was misplaced inside #pragma pack block resulting in broken std::string alignment = crashes on 32bit arm.
To reproduce we must hit cap_mjpeg_decoder.cpp:
```
cv::VideoCapture icap;
icap.open("anyfile.mp4");
```
crash in VideoInputStream::m_fname std::string ctor.
Existing videoio tests should catch this crash, but none of the arm32 builders run videoio tests.
I don't have an opencv test setup for arm32, is there any way to enable and run videoio tests on the CI?

fix videoio/src/container_avi.cpp VideoInputStream alignment crashes on 32bit arm (android)

---

modules/highgui/src/window_QT.cpp

In Qt backend of `imshow()`, the image shown in the window can be zoomed and dragged with the mouse. And the function `DefaultViewPort::controlImagePosition()` aims to keep the image border out of the visible window area. However, this function doesn't work properly when the image is zoomed (the translation distance should be scaled by current zooming factor), which makes it hard to check the pixel value near image borders, see the gif below:
This PR resolves the problem:
```
buildworker:Custom=linux-1,linux-2,linux-4,linux-6
```

Fix image position control in window_QT

---

samples/dnn/colorization.cpp
samples/dnn/colorization.py

[development here](https://github.com/richzhang/colorization) has moved from caffe to pytorch,
the old implementation/data was moved to a `caffe` branch, invalidating our previous download links

dnn: update links for the colorization samples

---

modules/dnn/src/onnx/onnx_importer.cpp

- Fixed bug while loading onnx model in debug. Blob is 4d and you are trying to access it with at() which is 2d. This error does not occur in Release because CV_DbgAssert only asserts under debug. For more info please check lines  937-950 of \opencv\modules\core\include\opencv2\core\mat.inl.hpp.

Fix bug while loading onnx model in debug

---

modules/gapi/src/backends/common/serialization.cpp
modules/gapi/src/backends/common/serialization.hpp
modules/gapi/test/s11n/gapi_sample_pipelines_s11n.cpp

Currently GScalar may be value-initialized, in this case its value is bound within the graph as a ConstValue:
```
struct ConstValue
{
static const char *name() { return "ConstValue"; }
GRunArg arg;
};
```
Put this information into the serialized graph, and test that it deserialize properly (as part of a real graph).
 
The following use cases must be implemented
```
auto p = cv::gapi::serialize(cv::GComputation(GIn(a), GOut(cv::gapi::addC(a,10))));
...
auto p = cv::gapi::serialize(cv::GComputation(GIn(a), GOut(a+10)))
...
auto p = cv::gapi::serialize(cv::GComputation(a, a+10));
...
// then
auto c = cv::gapi::deserialize<cv::GComputation>(p);
// and then
c.apply(cv::gin(in_mat /*, 10 */), cv::gout(out_mat));   // without `10` in runargs, `in_mat` only
```
 
See details at …

GAPI: Implement ConstValue serialize/deserialize

---

cmake/checks/cpu_rvv.cpp
modules/core/include/opencv2/core/hal/intrin_rvv.hpp
platforms/linux/riscv64-gcc.toolchain.cmake

This patch updates the RISC-V vector implementation of Wide Universal Intrinsics to **RVV 0.10**, making it consistent with the latest riscv-gnu-toolchain (https://github.com/riscv/riscv-gnu-toolchain/tree/rvv-intrinsic, Commit ID: _28271f03bb538d926ad2889dc8ad1b0cb1b3b45c_). At present, this version can achieve the same status as the previous version, that is, it has passed all HAL tests. And 11485 passed, 21 failed in core tests.
The details are as follows:
- Update toolchain file _riscv64-gcc.toolchain.cmake_ to match the latest compilation options.
- Update CPU check file _cpu_rvv.cpp_.
- Update _intrin_rvv.hpp_. Update all RVV native intrinsic interfaces to RVV 0.10.
- Build riscv-gnu-toolchain and QEMU simulator
```
git clone git@github.com:riscv/riscv-gnu-toolchain.git -b …
```

Update RISC-V back-end to RVV 0.10

---

modules/gapi/samples/face_detection_mtcnn.cpp

MTCNN 1st pnet simplification to ensure single graph input

---

modules/python/src2/cv2.cpp

resolves #20408
this pr tries to avoid the `Using 'value' pointer is unsafe and deprecated.` warning in the python bindings.
use a nullptr in createTrackbar(), and set the value later

python: fix trackbar warning

---

modules/dnn/src/dnn.cpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/ie_ngraph.hpp
modules/dnn/test/test_ie_models.cpp

Issue #20380
replaces #17393
backport #18393
<cut/>
```
force_builders_only=Custom,Custom Win,Custom Mac
test_filter:Custom=*OpenVINO*:*onv*
test_filter:Custom Win=*OpenVINO*:*onv*
```

dnn: workaround handling of InferenceEngine output layout

---

samples/cpp/grabcut.cpp

Hey all, I was playing around with the Grabcut example (https://docs.opencv.org/3.4/d8/d83/tutorial_py_grabcut.html) and was annoyed that the background is completely black, instead of showing the original image in a transparant way. 
I updated the code to make it transparant. I also made the application a bit more interactive, so you don't have to press 'n' any time you add some foreground or background, but it automatically runs at least one cycle. 
Image of the result: 
Let me know if you have any feedback :)

Updated grabcut example to show the background in a transparant way

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra** : opencv/opencv_extra#881
relates #19316 #19499 #19696 #19957
Using tools like tf2onnx and keras2onnx, to convert tensorflow networks to onnx format, fuses zero-padding layer with convolution layer but does not check if the padding is symmetric when importing such converted networks.
``` …
```

dnn : Fix convolution asymmetric padding bug in onnx importer

---

modules/dnn/src/dnn.cpp
modules/dnn/src/dnn_common.hpp
modules/dnn/src/layers/not_implemented_layer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

This PR adds `DummyLayer` and replaces all failed to initialize layers with it. This solves the issue of memory corruption in `getLayerShapes()` because `DummyLayer` just throws an exception in every function. 
Test data is at https://github.com/opencv/opencv_extra/pull/882
`opencv_extra=tf_diag_dummy`

Fix TFImporter diagnostic mode segfault

---

samples/python/stitching_detailed.py

In some cases the user wants to specify the `compose_megapix ` parameter if the resulting image size should be limited.
This causes `"compose_scale"` to be different than 1
without rounding the composed image sizes (variable "sz") which are calculated by `full_img_sizes[i][0] * compose_scale` they will be odly fractions of a pixel (e.g. (**5300.965, 3772.897**)) and therefore cause a "TypeError: integer argument expected, got float" in line
456        roi = warper.warpRoi(sz, K, cameras[i].R)

fix TypeError when specifying compose_megapix in stitching_detailed python sample

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

Related: https://github.com/opencv/opencv/pull/20394
Tests: https://github.com/opencv/opencv_extra/pull/884
`opencv_extra=tf_importer_asym_pads`
```
force_builders_only=Custom,Custom Win,Custom Mac
test_filter:Custom=*OpenVINO*:*onv*:*ayer* …
```

Implement asymmetric padding for conv2d, max_pool and conv2d_backprop_input

---

modules/core/include/opencv2/core/hal/intrin_rvv.hpp

Fixed comparison operations and some packing operations.
All of the failures in core module for RISC-V with RVV.
See #20278 for previous state
Currently, all the core tests have passed:
```
[ SKIPSTAT ] 14 tests skipped
[ SKIPSTAT ] TAG='mem_6gb' skip 1 tests
[ SKIPSTAT ] TAG='skip_other' skip 13 tests
[==========] 11542 tests from 249 test cases ran. (3737861 ms total)
[  PASSED  ] 11542 tests.
```

bug fixes for universal intrinsics of RISC-V back-end

---

modules/dnn/src/layers/recurrent_layers.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_onnx_importer.cpp

Added support for the non-zero inputs of hidden state and cell state for LSTM layer as requested in [issue #19278](https://github.com/opencv/opencv/issues/19278) (part 1). ONNX and TF importers are supported.
Test data here: https://github.com/opencv/opencv_extra/pull/886
`opencv_extra=lstm_inside`
I was unable to add the tests for TensorFlow 2 because of the known issue: https://github.com/tensorflow/tensorflow/issues/47554

Support non-zero hidden state for LSTM

---

modules/dnn/src/dnn_common.hpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp

I encountered strange behavior of model diagnostic tool when I was registering a custom layer: the tool indicated that the layer was probably missing, when we can know for sure; this change will enable easier debug and cleaner implementation of model diagnostics.

Split layer dispatch into functions in ONNXImporter

---

doc/py_tutorials/py_imgproc/py_contours/py_contour_features/py_contour_features.markdown

In line 94,  closing brackets are added which were missing .

Closing brackets missing

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/src2/gen2.py
modules/python/test/test_misc.py

This PR allows to call functions with slightly modified keyword arguments if original argument name is reserved by Python.
Moreover it fixes stub file syntax for both positional and keyword arguments.
Resolves #16142
Resolves https://github.com/opencv/opencv_contrib/issues/2370

fix: convert arguments names that are keywords reserved by Python

---

modules/gapi/samples/face_detection_mtcnn.cpp

Remove explicit PNet resizes from MTCNN graph

---

doc/tutorials/objdetect/traincascade.markdown

To fix for #20301 
Createsamples and traincascade have been disabled since OpenCV 4.0. These apps can be used from opencv 3.4. This added as the note to documentation.

fix traincascade documentation

---

cmake/OpenCVDetectVTK.cmake

Find_package sets VTK_DIR to VTK_DIR-NOTFOUND if we didn't find VTK 9, which leads us to not being able to find VTK 8.2 in custom directory as described in #20314.

Fix find_package cache pollution

---

modules/dnn/misc/python/test/test_dnn.py

Add test for workaround mentioned at issue https://github.com/opencv/opencv/issues/18880

Add Python's test for LSTM layer

---

modules/highgui/cmake/init.cmake
modules/videoio/cmake/init.cmake
platforms/linux/gnu.toolchain.cmake
platforms/linux/riscv.toolchain.cmake

- unexpected pkg-config module (we should not use host binary)
- bump cmake_minimum_required to 3.5 in toolchain files

CMake: fix cross-compilation problems

---

modules/python/src2/hdr_parser.py

The header parser checks if the function take `Mat` or `vector<Mat>` to generate `UMat`/`GpuMat` declarations. These variant is generated by mapping `InputArray`, `InputOutputArray`, etc. to `mat` = `"Mat"`, `"UMat"`, or `"GpuMat"`. 
If the argument type is explicitly `Mat`, the parser still try to generate alternative declarations, but no mapping will be performed and the declaration is duplicated. Take `imreadmulti()` for instance:
```c++
static PyObject* pyopencv_cv_imreadmulti(PyObject* , PyObject* args, PyObject* kw)
{
using namespace cv;
pyPrepareArgumentConversionErrorsStorage(2);
{
PyObject* pyobj_filename = NULL;
String filename;
PyObject* pyobj_mats = NULL;
vector_Mat mats;
PyObject* pyobj_flags = NULL;
int flags=IMREAD_ANYCOLOR;
bool retval;
const char* keywords[] = { …
```

Avoid adding false UMat/GpuMat declaration

---

doc/js_tutorials/js_imgproc/js_contours/js_contour_features/js_contour_features.markdown
doc/js_tutorials/js_imgproc/js_contours/js_contour_properties/js_contour_properties.markdown
doc/js_tutorials/js_imgproc/js_contours/js_contours_begin/js_contours_begin.markdown
doc/js_tutorials/js_imgproc/js_contours/js_contours_hierarchy/js_contours_hierarchy.markdown
doc/js_tutorials/js_imgproc/js_contours/js_contours_more_functions/js_contours_more_functions.markdown
doc/py_tutorials/py_imgproc/py_contours/py_contour_features/py_contour_features.markdown
doc/py_tutorials/py_imgproc/py_contours/py_contour_properties/py_contour_properties.markdown
doc/py_tutorials/py_imgproc/py_contours/py_contours_begin/py_contours_begin.markdown
doc/py_tutorials/py_imgproc/py_contours/py_contours_hierarchy/py_contours_hierarchy.markdown
doc/py_tutorials/py_imgproc/py_contours/py_contours_more_functions/py_contours_more_functions.markdown

Add links in [python](https://docs.opencv.org/4.5.2/d3/d05/tutorial_py_table_of_contents_contours.html) and [js](https://docs.opencv.org/4.5.2/d0/d43/tutorial_js_table_of_contents_contours.html) contours tutorial.

add links in python and js contours tutorial

---

modules/core/include/opencv2/core/hal/intrin_rvv.hpp

The solution fixes set of failed tests on resize, HoughTransform, GausssianBlur and others.

Fixed memory access issue in v_rshr_pack_store intrinsic on RISC-V RVV

---

modules/gapi/samples/semantic_segmentation.cpp

Some semantic segmentation networks such as unet-camvid-0001 from OMZ produce multi-plane output (1 x num_classesx H x W). In that case need to perform argmax operation for every pixel through channel plane in order to convert output to 1 x 1 x H x W representation where every pixel is class id.
``` …
```

[G-API] Support postprocessing for not argmaxed outputs

---

modules/gapi/include/opencv2/gapi/infer/bindings_ie.hpp
modules/gapi/src/backends/ie/bindings_ie.cpp

[G-API] Expand PyParams to support constInput

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/init.cpp
modules/dnn/src/layers/recurrent_layers.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_onnx_importer.cpp

Added support for GRU layer as requested in issue  [issue #19278](https://github.com/opencv/opencv/issues/19278) (part 2). Only ONNX importer is supported.
Test data here: https://github.com/opencv/opencv_extra/pull/888
`opencv_extra=gru_layer`
```
```

Add initialization and inference for GRU layer

---

modules/imgcodecs/misc/objc/ios/Mat+Converters.h
modules/imgcodecs/misc/objc/ios/Mat+Converters.mm
modules/imgcodecs/misc/objc/ios/Mat+QuickLook.h
modules/imgcodecs/misc/objc/ios/Mat+QuickLook.mm
modules/imgcodecs/misc/objc/macosx/Mat+QuickLook.h
modules/imgcodecs/misc/objc/macosx/Mat+QuickLook.mm

Sometime you want to see quickly the contents of a Mat object. This PR takes advantage of the Xcode Quicklook function to give a debug view of a Mat object as follows:
* if the Mat has 2 dimensions and type CV_8U and 1 channel - show Xcode Quicklook as grayscale image
* if the Mat has 2 dimensions and type CV_8U and 3 or 4 channel - show Xcode Quicklook as color image
* if the Mat has 2 dimensions and 1 channel and number of rows and  number of columns is less than 10 - display Xcode Quicklook as LaTeX style matrix
* if the Mat has 2 dimensions and 1 channel and type other than CV_8U - show Xcode Quicklook as a heat map

Add Quicklook for Mat on iOS and macOS

---

modules/imgproc/include/opencv2/imgproc.hpp

To fix for #20385 
In Python, hierarchy is nested inside a top level array. This should be added to the documentation.
This [OpenCV tutorial](https://docs.opencv.org/3.4/d9/d8b/tutorial_py_contours_hierarchy.html) use this feature.

add note about hierarchy in python version

---

modules/dnn/CMakeLists.txt
modules/dnn/src/layers/convolution_layer.cpp
modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/layers/layers_common.simd.hpp

PR for GSoC'21 project on Optimize OpenCV DNN for RISC-V.
This PR is going to add the functions implemented by RVV intrinsics (0.10) in [layers_common.simd.hpp](https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/layers_common.simd.hpp), which has 4 functions as below. 
In this PR, we assume that vlen=128, which means if RVV Vector Registers are 256-bit or more longer, then the current implementation will use only a part of them. We will make the implementation adjustable to different vector sizes by other PR(s).
| Functions         | Implement && Build | Vectorize tails (No Scala)                             | Max used of vReg (v0-v31) | 
| ----------------- | ------------------ | ------------------------------------------------------ | ------------------------- |
| …

Optimization of DNN using native RISC-V vector intrinsics.

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

Resolves attempt №2 of https://github.com/opencv/opencv/issues/19696. Tests: https://github.com/opencv/opencv_extra/pull/893.
`
opencv_extra=efficientnet_fix_34
`

Add Max layer to TF

---

modules/core/include/opencv2/core/ocl.hpp

resolves #20518
I've documented the behavior of the following functions, which take ownership of one reference of the raw OpenCL arguments passed in:
- `ocl::OpenCLExecutionContext::create`
- `ocl::Device::fromHandle`
I did not change the documentation for the following functions, which do not take ownership of their arguments:
- `ocl::Context::fromHandle`

docs(core/ocl): clarify ownership of arguments passed into OpenCL related functions

---

modules/ml/misc/java/test/MLTest.java

I think "loaded" should be tested instead of "saved".

java: fix MLTest.java

---

modules/videoio/src/cap_android_camera.cpp

continues #20509
The code was crashing on buffer.insert() line#330 on Android 11 Emulator with Camera2 NDK. This is tested with a C++ Test Application.
It looks like the U & V indexes are reversed and the YUVPlaner check condition is having an assignment operator than `==`.
This fix satisfies the YUV buffer memory layout expectation as in https://en.wikipedia.org/wiki/YUV#/media/File:Yuv420.svg

Fix YUV indexes + YUV Planner detection condition

---

modules/imgproc/include/opencv2/imgproc.hpp

Fixes #19569 
Added minor note to [documentation](https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html#ga47a974309e9102f5f08231edc7e7529d).

add note about Python's dsize to doc

---

modules/dnn/src/layers/recurrent_layers.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

Add support for activations for LSTM layer.
Related to issue: https://github.com/opencv/opencv/issues/18390
There are 3 models, mentioned in the issue. Two of them were produced by keras2onnx, another one - by CNTK (from onnxruntime). Unfortunately, LSTM doesn't support dynamic shapes, so I cannot test those two models. 
Test data should be downloaded: https://github.com/opencv/opencv_extra/pull/891
`opencv_extra=lstm_activations`

Support activations (Sigmoid, Tanh) for LSTM

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/cap_ffmpeg_impl.hpp

A little feature that was merged recently to 3.4
port of #20541

VideoCapture add open/read timeout params to FFMPEG backend

---

modules/flann/include/opencv2/flann/heap.h
modules/flann/include/opencv2/flann/hierarchical_clustering_index.h
modules/flann/include/opencv2/flann/kdtree_index.h
modules/flann/include/opencv2/flann/kmeans_index.h

FLANN allocates huge amounts of memory with every call to `findNeighbors` due to its private heap allocations. This affects memory throughput and overall speed of user applications, especially the ones that frequently query for neighbors. After all, although `malloc` does cache on its own, it also does a lot of smart things besides that, which costs some time penalty. To solve the problem, this PR introduces a static, thread-safe, and bounded memory pool for heap allocations. It have been tested thoroughly for very long hours, under extensive parallelization, and with strict leakage profiling. **The tests showed more than 70x memory throughput gain**. For roughly the same amount of calls, the memory footprint of `findNeighbors` using master branch was around 18.2 GB/sec, which got reduced …

Improves FLANN's heap allocations by a memory pool

---

modules/videoio/src/cap_gstreamer.cpp
modules/videoio/test/test_gstreamer.cpp

This patch adds 16-bit grayscale support to GStreamerCapture and updates the test with 16-bit support and a 16-bit test case.
```
```

videoio/gstreamer: Add support for GRAY16_LE.

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/init.cpp
modules/dnn/src/layers/cumsum_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

Support importing ONNX CumSum layer for CPU.  This patch addresses #20110.
ONNX CumSum specs:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#CumSum
Test data:
https://github.com/opencv/opencv_extra/pull/890 

Support cumsum layer for onnx

---

modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/backends/ie/giebackend/giewrapper.cpp
modules/gapi/src/backends/ie/giebackend/giewrapper.hpp

[G-API] Prohibit setPrecision & preprocessing for importedNetworks

---

modules/dnn/src/caffe/caffe_io.cpp

The two argument versions has been deprecated, cf
https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.coded_stream
```
force_builders=lunux,docs
```

Use the one argument version of SetTotalBytesLimit.

---

modules/gapi/src/executor/gexecutor.cpp

[G-API] Validate RMat adapter in executor

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

Test data is at https://github.com/opencv/opencv_extra/pull/895
`opencv_extra=onnx_split_sum_fix`

fix Split partial sum

---

modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp

resolves #20585
```
top = UMat::zeros(4, sz, (use_half_) ? CV_16SC1 : CV_32FC1);
```
doesn't work as expected.

dnn(OpenCL): fix top initialization in verifyResult

---

modules/gapi/include/opencv2/gapi/gcomputation.hpp
modules/gapi/include/opencv2/gapi/gstreaming.hpp
modules/gapi/misc/python/package/gapi/__init__.py
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/shadow_gapi.hpp
modules/gapi/misc/python/test/test_gapi_streaming.py

The goal of this PR is to support all different overloads for `compileStreaming` method in python, such as:
* compileStreaming(cv::GMetaArgs, cv::GCompileArgs = { })
* compileStreaming(cv::ExtractMetaCallback, cv::GCompileArgs = { })
* compileStreaming(cv::GCompileArgs = { })
To wrap these methods need to add `GAPI_WRAP` macros before every signature. The generated code will try every overloads in order from top to bottom as declared in c++ file and if overload isn't suitable (`pyopencv_to` for params return false) try the next one. So the problem was that `pyopencv_to(cv::ExtractMetaCallback)` always return `true` which means  that the …

[G-API] Extend compileStreaming to support different overloads

---

modules/gapi/src/executor/gexecutor.cpp

[G-API] Fix GExecutor WriteBackExec

---

modules/imgproc/src/hough.cpp
modules/python/test/test_houghcircles.py

Fixes #19238
Relates #16561
cvMat with different dimensions were copied to OutputArray _circles.
HOUGH_GRADIENT :
```
Mat(1, numCircles, cv::traits::Type<CircleType>::value, &circles[0]).copyTo(_circles);
```
vs
HOUGH_GRADIENT_ALT :
```
std::vector<Vec3f> cwow(ncircles);
Mat(cwow).copyTo(_circles);
```
This has been fixed and a test has been added.

Fix hough circles alt dimensions

---

modules/dnn/src/caffe/caffe_importer.cpp

This is to make code work with arenas (ReleaseCleared is incompatible).
The cleaning of the memory is also simpler.
ReleaseCleared not working with arenas is described here:
https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.repeated_field#RepeatedPtrField.ReleaseCleared.details
Arenas are described here:
https://developers.google.com/protocol-buffers/docs/reference/arenas
- [ x To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV

Do not use deprecated ReleaseCleared in protobuf library.

---

modules/java/test/common_test/src/org/opencv/test/utils/ConvertersTest.java

- 'new Byte' => 'Byte.valueOf'
Message looks like this:
```
[javac] C:\build\precommit_opencl\build\java_test\src\org\opencv\test\utils\ConvertersTest.java:31: warning: [removal] Byte(byte) in Byte has been deprecated and marked for removal
[javac]         truth.add(new Byte(value1));
```

java(test): avoid deprecation warning

---

modules/core/src/ocl.cpp

- NULL is used for allocation of workgroup local variables

core(ocl): handle NULL in dumpValue() debug call

---

cmake/OpenCVCompilerOptions.cmake
modules/core/include/opencv2/core/cvdef.h
modules/core/include/opencv2/core/mat.hpp
modules/core/include/opencv2/core/matx.hpp

fix opencv/opencv#20544 with nodiscard for msvc/gcc and applying it to the most common static factories in the api.
PR is set on branch 3.4. Should be able to apply also on 4.x with some minor work.
<cut/>
⚠ 4.x might have additional static factories which need this improved `CV_NODISCARD_STD`.
I need to know if you will do the additonal work in the up-merge.
Or if I need to do the work with a 4.x specific commit after you up-merge.
Please tell me. 😀
```
```

fix opencv/opencv#20544 nodiscard for msvc/gcc

---

modules/3d/include/opencv2/3d/detail/submap.hpp

Related to [PR3002 opencv/opencv_contirb](https://github.com/opencv/opencv_contrib/pull/3002).
The purpose is to add an edge-adding function of [Loop Closure Detection detection](https://github.com/opencv/opencv_contrib/pull/3002), which is called when a loop was detected.

Update submap.cpp for loop closure detection in 3d

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/core/src/bindings_utils.cpp
modules/python/src2/cv2.cpp
modules/python/test/test_legacy.py
modules/python/test/test_misc.py

Resolves #18412, resolves #14636 
`PyObject*` to `std::vector<T>` conversion logic:
- If user passed Numpy Array
- If array is planar and T is a primitive type (doesn't require constructor call) that matches with the element type of array, then
copy element one by one with the respect of the step between array  elements. If compiler is lucky (or brave enough) copy loop can be  vectorized.
For classes that require constructor calls this path is not  possible, because we can't begin an object lifetime without hacks.
- Otherwise fall-back to general case
- Otherwise - execute the general case:
If PyObject* corresponds to Sequence protocol - iterate over the  sequence elements and invoke the appropriate `pyopencv_to` function.
`std::vector<T>` to `PyObject*` conversion logic:
- If …

feat: update conversion logic for `std::vector<T>` in Python bindings

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

Fixes ONNX model from https://github.com/opencv/opencv/issues/20540 and https://github.com/opencv/opencv/issues/19499. Tests: https://github.com/opencv/opencv_extra/pull/897.
`opencv_extra=onnx_scale_fix`

Fix hasDynamicShapes for batch_size and axis selection in Scale layer

---

modules/python/src2/cv2.cpp

If allocation fails it should raise the following error in Python
```
MemoryError: Can't allocate NumPy array for vector with dtype=5 and shape=(10)
```

fix: NumPy array allocation error message in vector conversion

---

modules/dnn/src/layers/resize_layer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra:** https://github.com/opencv/opencv_extra/pull/905
Fixes https://github.com/opencv/opencv/issues/17726
relates #11050 (code branch has [zero coverage](http://pullrequest.opencv.org/buildbot/export/opencv_releases/3_4_coverage-lin64-debug/20210902-021141_1204/coverage_html/opencv/modules/dnn/src/layers/resize_layer.cpp.gcov.html))
The results of nets start diverging after(including) 'decoder/concat' `Concat` layer. I tracked it down to dnn.cpp:2962, where the optimization of this layer is applied: it disables 'decoder/concat' layer and changes the output mats of input layers of type `ResizeBilinear` to point to different parts of the one big matrix. The problem is in 'decoder/ResizeBilinear_1': it effectively does nothing since its input is already has 64x64 WxH, and so …

Fix resize+concat optimization

---

modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp
modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp
modules/dnn/src/opencl/conv_layer_spatial.cl

resolves #18361
relates #11959
- drop CreateSubBuffer
- fix FUSED_CONV_ELTWISE mode
Test case: `Test_ONNX_nets.Shufflenet/0`
```
```

dnn(OpenCL): fix buffer offsets in IDLF kernel

---

modules/core/include/opencv2/core/ocl.hpp
modules/core/src/ocl.cpp
modules/dnn/src/layers/batch_norm_layer.cpp
modules/dnn/src/layers/mvn_layer.cpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/ocl4dnn/src/math_functions.cpp
modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp
modules/dnn/src/ocl4dnn/src/ocl4dnn_softmax.cpp
modules/dnn/src/opencl/gemm_image.cl

- if kernel code doesn't support that
relates #20615
```
test_filter:Custom Win=*:-Test_Caffe_nets.FasterRCNN_vgg16/1
```

dnn(OpenCL): fix automatic globalsize adjusting

---

modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/902
Add Normalize subgraph, support for starts<0 and axis<0 in `Slice`, `Mul` broadcasting in the middle and fix `Expand`'s unsqueeze, fixing the latest attempt in https://github.com/opencv/opencv/issues/20428 and no-op `Expand` in https://github.com/opencv/opencv/issues/20643.
`opencv_extra=split_slice_shenanigans`

Add Normalize subgraph, fix Slice, Mul and Expand

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/cap_ffmpeg_impl.hpp

I added CAP_PROP_STREAM_OPEN_TIME to the capture properties enumeration and support for it in the `getProperty()` method of the FFmpeg VideoCapture object.
Motivation - RTSP (RTP) stream timestamps are relative to start of stream, which is undesirable when trying to correlate the stream to external data streams. 
Testing - I'm happy to add a test case, but as the return value of `cap.get(cv2::CAP_PROP_STREAM_OPEN_TIME)` is nondeterministic, I'm unsure if it needs one/how to do it. I tested locally (with an IP camera and an RTSP stream) and it works. Please advise if more extensive testing/sample code is needed.

Add CAP_PROP_STREAM_OPEN_TIME

---

modules/features2d/include/opencv2/features2d.hpp
modules/python/src2/hdr_parser.py

2nd pass of fixes opencv/opencv#20544
Originally intended to include any needed changes for 4.x branch. During which, found these opportunities.
Should work on 3.x and 4.x
`CV_NODISCARD_STD` was not put on the related pure virtual. By official c++ spec, a [[nodiscard]] attribute on a virtual is not inherited, therefore it is useless and unneeded on the pure virtual. It is only put on the two implementations.

add nodiscard to features2d clone funcs (2nd review for nodiscard)

---

modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra:** https://github.com/opencv/opencv_extra/pull/907
Fixes https://github.com/opencv/opencv/issues/20643.
```opencv_extra=prelu_slope```

Fix PReLU negative slope access pattern

---

modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp
modules/dnn/src/opencl/conv_layer_spatial.cl

- dropped usage of CreateSubBuffer() - buffers lifetime management issue
- fixed elementwise offset
- avoid out of bounds read access
relates #20651 #20583 (CreateSubBuffer())
<cut/>
Tasks:
```
test_filter:Custom Win=*:-Test_Caffe_nets.FasterRCNN_vgg16/1
```

dnn(OpenCL): fix out of bound access in GEMM-like kernels

---

modules/core/src/intel_gpu_gemm.inl.hpp
modules/core/src/matmul.dispatch.cpp
modules/core/test/ocl/test_gemm.cpp

relates #8104
OpenCL kernels should not read memory outside of buffers (even if result is masked/zeroed after that).
<cut/>
```
force_builders=Custom,Linux AVX2,Linux OpenCL,Custom Win
```

core(OpenCL): fix intel_gpu_gemm kernel requirements

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

`parseBiasAdd` in tf_importer.cpp can only load Const from Second place, and the default input layer is the first one.
But the following Tensorflow code will produce Const in the First Place. At this point, the input layer is the **Second one**.
```py
inp = tf.placeholder(tf.float32, [1, 2, 3, 4], 'input')
sub = 3.0 - inp
```
The test data could be found at [PR of opencv_extra](https://github.com/opencv/opencv_extra/pull/909).

DNN: BiasAdd tf_importer.cpp could load Const from First Place

---

modules/imgproc/src/min_enclosing_triangle.cpp

Fixes #17585
Function `createConvexHull` just cast `cv::Mat` to `vector<cv::Point2f>` by `convertTo()` and call `ConvexHull`.
There is problem: `convertTo()` can't cast `cv::Mat(n, 2, CV_32FC1)` to `vector<cv::Point2f>`. But `ConvexHull` can take `cv::Mat(n, 2, CV_32FC1)`.
To fix problem can delete `createConvexHull` (this is "private" function and calls once).

deleted dublicated "private" createConvexHull and convertTo

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/layers/region_layer.cpp
modules/dnn/test/test_darknet_importer.cpp

**Merge with extra:** https://github.com/opencv/opencv_extra/pull/906
This PR adds test for https://github.com/opencv/opencv/pull/19877 by @erikguo, which implements new_coords for YOLOv4x-mish in CPU mode, fixing https://github.com/opencv/opencv/issues/18975. 
The golds were obtained from OpenCV itself after I compared resulting boxes and probabilities of classes after NMS from Darknet and OpenCV. Boxes' coordinates in range [0-1] differ in 5th decimal place,  probabilities(0-1) in 4th.
`opencv_extra=yolov4x-mish`

Add support for YOLOv4x-mish

---

modules/gapi/CMakeLists.txt
modules/gapi/src/streaming/onevpl/accelerators/accel_policy_interface.hpp
modules/gapi/src/streaming/onevpl/accelerators/surface/cpu_frame_adapter.cpp
modules/gapi/src/streaming/onevpl/accelerators/surface/cpu_frame_adapter.hpp
modules/gapi/src/streaming/onevpl/accelerators/surface/surface.cpp
modules/gapi/src/streaming/onevpl/accelerators/surface/surface.hpp
modules/gapi/test/streaming/gapi_streaming_vpl_core_test.cpp

this PR is the single one in series of https://github.com/opencv/opencv/pull/20469
Introduce VPL Surface & CPU MediaFrame Adapter
``` …
```

G-API: oneVPL (simplification) added surface & frame adapter

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra** : opencv/opencv_extra#912
relates #20660 
'axes' for unsqueeze node changed from attribute to input in opset version 13
[11](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Unsqueeze-11), [13](https://github.com/onnx/onnx/blob/master/docs/Operators.md#unsqueeze)

dnn : fix for unsqueeze opset version 13 in onnx_importer

---

modules/core/src/system.cpp

It fixes https://github.com/opencv/opencv/issues/20685

Detect FP16 on FreeBSD aarch64

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/cuda/eltwise_ops.cu
modules/dnn/src/cuda/functors.hpp
modules/dnn/src/cuda4dnn/kernels/eltwise_ops.hpp
modules/dnn/src/cuda4dnn/primitives/eltwise.hpp
modules/dnn/src/layers/eltwise_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra:** https://github.com/opencv/opencv_extra/pull/908
Related: https://github.com/opencv/opencv/issues/20438
<cut/>
```
opencv_extra=min
```

Add Min layer to CPU, OpenCL, Halide, Inference Engine, NGraph and CUDA

---

samples/dnn/text_detection.py

This pull request will fix text detection sample.
cv.line() accepts only input int type point. Therefor, it is need cast to int type.
This is an error to be fixed by this pull request.
```
File "text_detection.py", line 239, in <module>
main()
File "text_detection.py", line 227, in main
cv.line(frame, p1, p2, (0, 255, 0), 1)
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
```

fix cast in text detection sample

---

modules/gapi/include/opencv2/gapi/gstreaming.hpp
modules/gapi/include/opencv2/gapi/streaming/desync.hpp
modules/gapi/src/api/kernels_streaming.cpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp

G-API: Added desync RMats and MediaFrames support

---

modules/calib3d/include/opencv2/calib3d.hpp
modules/calib3d/src/five-point.cpp
modules/calib3d/test/test_cameracalibration.cpp

Finish PR from #17981, which creates a new api for computing pose from different cameras.
The original author and commit is preserved.  I got the go-ahead from a maintainer to finish the original PR:  https://github.com/opencv/opencv/pull/17981#issuecomment-905237498
```
```

Recover pose from different cameras (version 2)

---

modules/imgproc/src/filter.simd.hpp

Improve the performance of RowFilter in imgproc for u8 to f32 data.
```
disable_ipp=ON
```

Add RowVec_8u32f

---

doc/py_tutorials/py_bindings/py_bindings_basics/py_bindings_basics.markdown
modules/core/misc/python/package/mat_wrapper/__init__.py
modules/python/src2/cv2.cpp
modules/python/test/test_mat.py
modules/python/test/tests_common.py

resolves #19091
~~**On hold, merge after**: #20611~~
Usage:
```
cv.call(cv.Mat(data3D))
cv.call(data3D)  # passes as 2D array with the last dimension wrapped into channels (current behavior for images)
```
C++-written cv.Mat is not reliable with Python limited API and numpy 1.20+ (not stable ABI guarantee).
Package loader is required (OPENCV_SKIP_PYTHON_LOADER must be OFF).
No plans to backport to "3.4" maintenance branch.
No plans to support Python 2.7.
<cut/>
TODO:

python: cv.Mat wrapper over numpy.ndarray

---

modules/core/misc/objc/common/Rect2d.mm
modules/core/misc/objc/common/Rect2f.mm
modules/core/misc/objc/test/RectTest.swift

Fix a bug in iOS/macOS implementation of Rect2f(Point2f, Point2f) and Rect2d(Point2d, Point2d) initializers causing loss of precision due to erroneous casts to `int`

Fix bug in initializers Rect2f(Point2f,Point2f) and Rect2d(Point2d,Point2d)

---

modules/imgproc/src/hough.cpp

This PR fix the bug in HoughLinesSDIV reported in #20751.
Above is a test picture and test code.The results before and after modifying the code are shown in the figure below.
I also test more pictures and more parameters.The code works just fine.

fix the bug of HoughlinesSDIV

---

modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp
modules/dnn/src/opencl/conv_layer_spatial.cl

Avoid inefficient automatic scheduling of 3D task layout with LWS=1x1x256
Also there is no efficient selection of 3D LWS (GWS must be divisible to LVS).
Finally, task is reworked to process as 1D array.
relates #20655
<cut/>
```
force_builders=Custom,Linux AVX2,Linux OpenCL,Custom Win
```

dnn(OpenCL): fix conv BASIC workgroup

---

modules/cudafilters/test/test_filters.cpp
modules/imgproc/src/smooth.simd.hpp
modules/imgproc/test/test_smooth_bitexact.cpp

resolve #20792
resolve #20666
* sharp Gaussian kernel causes over flow and ends up in blank image

imgproc: suppress GaussianBlur to generate empty images

---

modules/java/android_sdk/build.gradle.in

The example in the build.gradle file of the Android OpenCV SDK about the CMAKE setup uses a hard-coded OpenCV version. Therefore, the example does not match the actual SDK version. This is fixed by using CMAKE to automatically insert the actual version number.

Automatically set the correct OpenCV version in build.gradle

---

modules/videoio/src/cap_gstreamer.cpp

I noticed this while reading the code, and it seems wrong to me. From the [documentation](https://gstreamer.freedesktop.org/documentation/gstreamer/gst.html?gi-language=c#gst_init_check), `gst_init_check` "will return FALSE if GStreamer could not be initialized for some reason".
I do not understand why the current code ever works, because in my test project (with gstreamer 1.16.2), `err` is never `NULL` after a call to `gst_init_check(NULL, NULL, &err);`. But I could imagine that it is different with other versions of gstreamer.
I haven't tested my patch at all, but it seemed important enough to open a discussion, and a PR seemed like a good way. Feel free to close if I am missing something :innocent:.
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pul …

Fix gst_initializer

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

The `ExpandDims` layer was implemented by "Reshape layer."
The following code will generate the `ExpandDims` layer:
```py
expand_dim = tf.expand_dims(input, -1)
expand_dim = tf.expand_dims(input, 2)
```
Related test data could be found at [PR in opencv_extra](https://github.com/opencv/opencv_extra/pull/911).
There are still some unresolved issues here:
- 1. ~~**Currently, this code can only handle when the dimension input layer dimension is 4.**, since the different Datalayout between OpenCV and Tensorflow.~~(Solved.)
- 2. Since the implementation uses the `dstNet.getLayerShapes()` function. This implementation can not handle [this model](https://drive.google.com/drive/folders/1-y9zh3fiwARdAXjL41X-2vNwtr9Phjqi?usp=sharing). 
See details at …

Add ExpandDims layer of tf_importer.cpp

---

modules/dnn/src/cuda/eltwise_ops.cu
modules/dnn/src/cuda/kernel_dispatcher.hpp
modules/dnn/src/cuda4dnn/kernels/eltwise_ops.hpp
modules/dnn/src/dnn.cpp

EltwiseOp requires all the input tensors to have the same shape. This PR generalizes it to support eltwise operations on any set of compatible tensors as input.
resolves #20778
The following tests were failing:
```
[  FAILED  ] Test_TensorFlow_layers.eltwise_add_vec/0, where GetParam() = CUDA/CUDA
[  FAILED  ] Test_TensorFlow_layers.eltwise_add_vec/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.eltwise_mul_vec/0, where GetParam() = CUDA/CUDA
[  FAILED  ] Test_TensorFlow_layers.eltwise_mul_vec/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.channel_broadcast/0, where GetParam() = CUDA/CUDA
[  FAILED  ] Test_TensorFlow_layers.channel_broadcast/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_nets.EfficientDet/0, where …
```

cuda4dnn(eltwise): tensor broadcasting

---

modules/gapi/test/common/gapi_tests_helpers.hpp

G-API: Add more parameters to render fixture

---

3rdparty/ffmpeg/ffmpeg.cmake

**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/67
- FFmpeg 3.4.8 (no changes)
previous update: #19665

ffmpeg/3.4: update FFmpeg wrapper 2021.10

---

3rdparty/ffmpeg/ffmpeg.cmake

**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/68
- FFmpeg 4.4 (no changes)
previous update: #20244

ffmpeg/4.x: update FFmpeg wrapper 2021.10

---

modules/core/misc/java/src/java/core+Mat.java
modules/core/misc/java/src/java/core+MatMatMul.kt
modules/core/misc/java/test/MatTest.java
modules/core/misc/objc/common/Mat.h
modules/core/misc/objc/common/Mat.mm
modules/core/misc/objc/common/MatExt.swift
modules/core/misc/objc/test/MatTest.swift
modules/java/generator/src/cpp/Mat.cpp

Android and iOS wrapper both have element-wise multiplication operations (https://en.wikipedia.org/wiki/Hadamard_product_(matrices)) for `Mat`  but lack matrix multiplication operations (https://en.wikipedia.org/wiki/Matrix_multiplication).
This PR adds matrix multiplication for `Mat` in Android and iOS wrappers.
It also adds operator overloading for the `*` operator in Swift and Kotlin
```
```

Add matrix multiplication to Mat for iOS/Android

---

modules/core/src/system.cpp

core(TLS): force TlsAbstraction initialization before main()

---

modules/dnn/misc/python/test/test_dnn.py

resolves #20534
relates #20480
Reusing `dnn:Net` after target switching is buggy (TBD).
<cut/>
```
```

dnn(pytest/test_input_3d): reload model between switching targets

---

modules/highgui/include/opencv2/highgui/highgui_c.h
modules/highgui/src/window.cpp

return type is C++ template
relates #10412
```
build_image:Custom Win=oneapi-2021.4.0-clang
```

(3.4) highgui: drop invalid cvGetWindowImageRect

---

modules/highgui/include/opencv2/highgui/highgui_c.h
modules/highgui/src/window.cpp

C function can't return C++ object.
relates #10412
relates #20980

(4.x) highgui: drop invalid cvGetWindowImageRect

---

modules/videoio/src/cap_dshow.cpp

```
build_image:Custom Win=oneapi-2021.4.0-clang
Xbuild_image:Custom Win=oneapi-2021.4.0
Xbuild_image:Custom Win=oneapi-2021.4.0-icc
Xbuild_image:Custom Win=msvs2019-ninja
build_image:Custom=oneapi-2021.4.0
```

videoio(dshow): eliminate build warnings from MSVC-Clang

---

modules/objdetect/src/qrcode.cpp

Fixed issue #20880, QRDetect::searchHorizontalLines() boundary condition will skip the matched qrcode near the end

---

modules/dnn/CMakeLists.txt

dnn(cmake): don't hijack OpenCL options with Tengine

---

modules/dnn/test/test_model.cpp

- 32-bit configuration may fail due to memory fragmentation
Message looks like this:
```
[ RUN      ] Test_Model.Segmentation/0, where GetParam() = OCV/CPU
unknown file: error: C++ exception with description "bad allocation" thrown in the test body.
[  FAILED  ] Test_Model.Segmentation/0, where GetParam() = OCV/CPU (949 ms)
```

dnn(test): skip tests with high memory usage

---

modules/core/include/opencv2/core/hal/intrin_avx.hpp
modules/core/include/opencv2/core/hal/intrin_avx512.hpp

In practice, processors offering AVX2/AVX512 also FMA, that is why it got unnoticed.
```
force_builders=linux,docs,Linux AVX2,Custom
disable_ipp=ON
```

Only use fma functions when CV_FMA3 is set.

---

samples/cpp/falsecolor.cpp

There are two values that provoke unintended behaviour when running the sample code _falsecolor.cpp_.
First instance is trying to set the tracker position to -1 and that throws and out of bounds exception.
The second instance sets the maximum tracker position to 1 which only allows the two colormaps to be applied the first and the last.
There is an issue that could be closed after this PR is merged. (#21002)

BUGFIX in sample falsecolor.cpp | Fix trackbar position settings

---

modules/videoio/src/cap_android_mediandk.cpp

Fix: #21021
NDK API AMediaCodec_getOutputBuffer() returns MediaCodecBuffer::data()
which is actually ABuffer::data(). The returned buffer address is already
adjusted by offset.
More info:
ABuffer::base() returns base address without offset
ABuffer::data() returns base + offset
Change-Id: I2936339ce4fa9acf657a5a7d92adc1275d7b28a1
```
android_pack_config=ndk-18-api-level-21.config.py
```

videoio: drop unnecessary offset for accessing video output buffer

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/932
Fixed bug in #20896：When parsing a pooling layer in dnn/tensorflow. If keep_dims is false, the  additional "nhwc" layer and "squeeze" layer will be lost. Because the final "squeeze" layer name is not the original layer name. 
Solution: 
Change the final output layer's name to the orignal **pooling** layer's name.
```
opencv_extra=tf_pooling
```

fix bug: wrong output dimension when "keep_dims" is false in pooling layer.

---

doc/pattern_tools/gen_pattern.py

Fixes #21026
This PR  is going to fix args parse in `gen_pattern.py`:
- set default value for `markers`
- added condition:`p_type == "radon_checkerboard"  and "markers" in args`
After the fix, [all the tutorial examples](https://docs.opencv.org/4.x/da/d0d/tutorial_camera_calibration_pattern.html) work.

fix markers parse in doc/pattern_tools/gen_pattern.py

---

modules/dnn/src/opencl/ocl4dnn_lrn.cl
modules/dnn/test/test_caffe_importer.cpp

- FP16 intermediate computation is not accurate and may provide NaN values
resolves #21004
<cut/>
Validated on Ice Lake CPU (i5-1035G1) with test filter (3.4.16): `--gtest_filter=*:-*vgg16/1:*RCNN_zf/1:*Mask_RCNN/1`
---
i7-6700K failed tests (both Linux/Windows):
```
[ RUN      ] Reproducibility_AlexNet.Accuracy/1, where GetParam() = (false, OCL_FP16)
/build/precommit_opencl_linux/3.4/opencv/modules/dnn/test/test_common.impl.hpp:69: Failure
Expected: (normInf) <= (lInf), actual: 0.00360501 vs 0.003
|ref| = 0.64178860187530518
[  FAILED  ] Reproducibility_AlexNet.Accuracy/1, where GetParam() = (false, OCL_FP16) (299 ms)
...
[ RUN      ] Reproducibility_AlexNet.Accuracy/4, where GetParam() = (true, OCL_FP16)
/build/precommit_opencl_linux/3.4/opencv/modules/dnn/test/test_common.impl.hpp:69: …
```

dnn(ocl4dnn): fix LRN layer accuracy problems

---

modules/videoio/src/cap_ffmpeg_impl.hpp

Fix the following build failure with gcc 4.8:
```
In file included from /home/buildroot/autobuild/instance-3/output-1/build/opencv4-4.5.4/modules/videoio/src/cap_ffmpeg_impl.hpp:100:0,
from /home/buildroot/autobuild/instance-3/output-1/build/opencv4-4.5.4/modules/videoio/src/cap_ffmpeg.cpp:50:
/home/buildroot/autobuild/instance-3/output-1/build/opencv4-4.5.4/modules/videoio/src/cap_ffmpeg_hw.hpp: In constructor 'HWAccelIterator::HWAccelIterator(cv::VideoAccelerationType, bool, AVDictionary*)':
/home/buildroot/autobuild/instance-3/output-1/build/opencv4-4.5.4/modules/videoio/src/cap_ffmpeg_hw.hpp:939:23: error: use of deleted function 'std::basic_istringstream<char>& std::basic_istringstream<char>::operator=(const std::basic_istringstream<char>&)'
s_stream_ = …
```

modules/videoio/src/cap_ffmpeg_impl.hpp: fix build with gcc 4.8

---

modules/gapi/include/opencv2/gapi/util/any.hpp

`#warning` directive is not supported in MSVC and will cause a C1021 error.
Therefore a compile error occurs when using G-API in a project where RTTI is disabled.

Use `#pragma message` instead of `#warning` for non-GCC compilers

---

modules/gapi/src/backends/ie/giebackend.cpp
modules/gapi/src/backends/ie/giebackend/giewrapper.cpp
modules/gapi/src/backends/ie/giebackend/giewrapper.hpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp

1. **Outputs map are filled only for `LoadNetwork` case.**
These maps: https://github.com/opencv/opencv/blob/master/modules/gapi/src/backends/ie/giebackend.cpp#L221-L222 are filled only in case LoadNetwork: https://github.com/opencv/opencv/blob/master/modules/gapi/src/backends/ie/giebackend.cpp#L241-L242, but are used by both of them:
https://github.com/opencv/opencv/blob/master/modules/gapi/src/backends/ie/giebackend.cpp#L953
2. **`cv::gapi::ie::Params::pluginConfig(IEConfig)` set config globally to `IE::Core`, but should be set locally within `ExecutableNetwork`:** https://github.com/opencv/opencv/blob/master/modules/gapi/src/backends/ie/giebac …

[G-API] Fix bugs in GIEBackend

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/perf/common/gapi_core_perf_tests.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_cpu.cpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

SIMD for Divide kernel.
<cut/>
[FluidDivSIMD.xlsx](https://github.com/opencv/opencv/files/7520026/FluidDivSIMD.xlsx)
``` …
```

GAPI Fluid: SIMD Div kernel.

---

modules/gapi/perf/common/gapi_video_perf_tests_inl.hpp
modules/gapi/test/common/gapi_tests_common.hpp
modules/gapi/test/common/gapi_video_tests_inl.hpp
modules/gapi/test/cpu/gapi_ocv_stateful_kernel_tests.cpp
modules/gapi/test/gapi_graph_meta_tests.cpp
modules/gapi/test/infer/gapi_infer_ie_test.cpp
modules/gapi/test/infer/gapi_infer_onnx_test.cpp
modules/gapi/test/streaming/gapi_streaming_tests.cpp
modules/gapi/test/test_main.cpp

This PR sets the second parameter of FindDataFile to false for tests of G-API. This handles the problem with failed tests which aren't skipped.
Also removing `initTestDataPath()` logic.
``` …
```

G-API: Removing G-API test code that is a reflection of ts module

---

modules/gapi/perf/common/gapi_core_perf_tests.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_cpu.cpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

SIMD optimization for Fluid Multiply kernel.
<cut/>
[FluidMulSIMD.xlsx](https://github.com/opencv/opencv/files/7504274/FluidMulSIMD.xlsx)
``` …
```

GAPI Fluid: SIMD Multiply kernel.

---

modules/core/include/opencv2/core/cvstd_wrapper.hpp

resolves #17261
Avoid problem which comes from invalid external 'check' macro definition.
Hopefully it is internal identifier and it is not a part of our public API.

core: avoid using of 'check' identifier

---

modules/imgcodecs/src/loadsave.cpp
modules/photo/src/seamless_cloning.cpp

resolves #20167  
Add a warning message using CV_LOG_WARNING() to imread().
Add a src check using CV_Assert() to seamlessClone().
These changes would help using imread() and seamlessClone(). Change in imread would especially help to new users when they can make mistakes with path.
Signed-off-by: nickjackolson <metedurlu@gmail.com>
<cut/>
System Info:
- Linux pop-os 5.13.0-7614-generic 14  x86_64 x86_64 x86_64 GNU/Linux
- cmake version 3.16.3
- g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- [ + ] I agree to contribute to the project under Apache 2 License.
- [ + ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ + ] The PR is proposed to proper branch
- [ + ] There is reference to original bug report and …

Friendlier error messages when image path does not exist: Add warning message to imread()

---

modules/imgproc/src/color_hsv.simd.hpp

In case of very small negative h (e.g. -1e-40), with the current implementation,
you will go through the first condition and end up with h = 6.f, and will miss
the second condition.

Fix H clamping for very small negative values.

---

modules/core/src/logger.cpp
modules/core/src/precomp.hpp
modules/core/src/system.cpp
modules/core/src/trace.cpp

Examples:
- `[ INFO:0] Initialize OpenCL runtime...` (previous default, available with `OPENCV_LOG_TIMESTAMP=0`)
- `[ INFO:0@0.004] Initialize OpenCL runtime...` (new default)
- `[ INFO:0@3709606] Initialize OpenCL runtime...` (with `OPENCV_LOG_TIMESTAMP_NS=1`)

core(logger): dump timestamp information with message

---

samples/dnn/tf_text_graph_ssd.py

Avoid `SyntaxWarning` on Python >= 3.8
```
>>> "convolutional" == "convolutional"
True
>>> "convolutional" is "convolutional"
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
True
```
Related to #21121

Use ==/!= to compare constant literals (str, bytes, int, float, tuple)

---

CMakeLists.txt

Typo discovered by #21121 which uses https://pypi.org/project/codespell/

CMakeLists.txt: Fix typo discovered by codespell

---

modules/gapi/include/opencv2/gapi/cpu/gcpukernel.hpp
modules/gapi/samples/gaze_estimation.cpp
modules/gapi/samples/infer_ie_onnx_hybrid.cpp
modules/gapi/samples/infer_single_roi.cpp
modules/gapi/samples/infer_ssd_onnx.cpp
modules/gapi/samples/onevpl_infer_single_roi.cpp
modules/gapi/samples/privacy_masking_camera.cpp
modules/gapi/samples/semantic_segmentation.cpp

Cleaning G-API samples.
Removed ParseSSD custom kernels. cv::gapi::parseSSD instead.
Added graph operations for semantic segmentation instead operations in a kernel.
``` …
```

G-API: Cleaning samples

---

modules/gapi/include/opencv2/gapi/garray.hpp
modules/gapi/include/opencv2/gapi/gopaque.hpp
modules/gapi/include/opencv2/gapi/own/cvdefs.hpp
modules/gapi/include/opencv2/gapi/own/saturate.hpp
modules/gapi/src/backends/common/serialization.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/executor/gstreamingexecutor.cpp
modules/gapi/src/executor/gstreamingexecutor.hpp

- `cv::detail::OpaqueKind m_kind` field of `VectorRef` and `OpaqueRef` is now set to `CV_UNKNOWN` by default
- added overload for `saturate()` function calls with the same input and output type
- solved followed Win warnings about Fluid ConvertTo kernel with the same issue
- sanitized resize value in `ByteMemoryInStream::operator>> (std::string& str)`: `std::string::resize()` method expects `std::size_t` when used to get `uint32_t` instead
- handled exception throws from ~GStreamingExecutor() by try-catch block (will address this issue further in the future)
```
build_gapi_standalone:Linux …
```

[G-API] Fixed Coverity issues

---

modules/gapi/src/api/rmat.cpp
modules/gapi/src/backends/common/gbackend.hpp
modules/gapi/test/rmat/rmat_view_tests.cpp

- fixed issue due to auto-changing `mat.dims` to `2` in `cv::Mat` constructors even if source Mat's `dims == 1`
- added test
- fixed for standalone too (needed changes in `asView()` logic)
``` …
```

[G-API] Fix issue of getting 1D Mat out of RMat::View

---

modules/ts/misc/chart.py
modules/ts/misc/report.py
modules/ts/misc/summary.py

Python syntax errors discovered by #21121
Closes #21122
```
futurize -f libfuturize.fixes.fix_print_with_import -w \
./modules/ts/misc/report.py \
./modules/ts/misc/summary.py \
./modules/ts/misc/chart.py
```

Use print() function in both Python 2 and Python 3

---

doc/js_tutorials/js_assets/js_camshift.html
doc/js_tutorials/js_assets/js_meanshift.html
modules/highgui/CMakeLists.txt
modules/js/generator/embindgen.py
modules/ts/misc/run.py
platforms/winpack_dldt/build_package.py
samples/dnn/dasiamrpn_tracker.py
samples/dnn/siamrpnpp.py
samples/python/tutorial_code/video/meanshift/camshift.py
samples/python/tutorial_code/video/meanshift/meanshift.py

Like #21128 
Typos discovered by #21121 which uses https://pypi.org/project/codespell/
```
codespell --count --ignore-words-list=activ,hist,halfs,ist,lod,msdos,numer \
--skip="./3rdparty/*,*.bib,*.c,*.cc,*.cl,*.clj,*.cmake,*.cpp,*.cu,*.h,*.hpp,*.java,*.json,*.markdown,*.proto,*.svg,*.txt,*.xml"
```

Fix typos discovered by codespell

---

modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_common.hpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

backport of #21126
<cut/>
```
Xbuildworker:Win64 OpenCL=windows-3
Xbuild_image:Win64 OpenCL=msvs2019
Xbuildworker:Custom Win=windows-3
Xtest_opencl:Custom Win=ON
```

(3.4) dnn(test): update InferenceEngine tests

---

modules/gapi/test/infer/gapi_infer_ie_test.cpp

relates #20925
```
build_image:Custom Win=openvino-2021.4.2-vc14
```

gapi: fix build with MSVS2015 (with IE)

---

modules/dnn/test/test_model.cpp
modules/dnn/test/test_tf_importer.cpp

4.x changes
<cut/>
```
Xbuildworker:Win64 OpenCL=windows-3
Xbuildworker:Custom Win=windows-3
Xtest_opencl:Custom Win=ON
```

dnn(test): update InferenceEngine tests

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/perf/common/gapi_core_perf_tests.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_cpu.cpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

SIMD for GAPI Fluid AddC kernel.
<cut/>
[FluidAddCSIMD.xlsx](https://github.com/opencv/opencv/files/7601676/FluidAddCSIMD.xlsx)
``` …
```

GAPI Fluid: SIMD for AddC kernel.

---

modules/dnn/perf/perf_recurrent.cpp
modules/dnn/src/layers/fully_connected_layer.cpp
modules/dnn/src/layers/layers_common.simd.hpp
modules/dnn/src/layers/recurrent_layers.cpp

This uses the AVX-optimised fastGEMM1T for matrix multiplications where available, instead of the standard cv::gemm.
fastGEMM1T is already used by the fully-connected layer.  This PR involves two minor modifications to allow use with the LSTM layer:
- Use unaligned access.  I don't believe this involves any performance hit in on modern CPUs (Nehalem and Bulldozer onwards) in the case where the address is actually aligned.
- Allow for weight matrices where the number of columns is not a multiple of 8.
I have not enabled AVX-512 or RVV as I don't have access to such CPUs to test on.  If there are no problems with this PR I'll send a separate PR which deals with ARM NEON.
<cut/>
Performance comparison (vs built-in gemm, i.e. build without a BLAS):
```
Median (ms)
Name of Test …
```

dnn: LSTM optimisation

---

modules/dnn/src/layers/lrn_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp

A few fixes for https://github.com/opencv/opencv/issues/21078, tests are coming to 4.x with https://github.com/opencv/opencv/pull/21088
Clip default min and max: https://github.com/onnx/onnx/blob/master/docs/Operators.md#clip
LeakyReLU default alpha: https://github.com/onnx/onnx/blob/master/docs/Operators.md#leakyrelu
LRN default alpha: https://github.com/onnx/onnx/blob/master/docs/Operators.md#lrn
Split default axis: https://github.com/onnx/onnx/blob/master/docs/Operators.md#split

fix Clip, LeakyReLU, LRN, Split defaults

---

modules/imgproc/src/color_lab.cpp
modules/imgproc/test/test_color.cpp

For LL=49, uu=205, vv=23, we end up with x=7373056 and y=458
which overflows y*x.

Fix integer overflow in cv::Luv2RGBinteger::process.

---

3rdparty/protobuf/CMakeLists.txt
modules/dnn/CMakeLists.txt

relates #20998
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc15/builds/897)
```
```

build: eliminate C4309 warning from protobuf files with MSVS2017

---

modules/gapi/perf/common/gapi_core_perf_tests.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_cpu.cpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

SIMD for GAPI Fluid SubC kernel.
<cut/>
[FluidSubCSIMD.xlsx](https://github.com/opencv/opencv/files/7626017/FluidSubCSIMD.xlsx)
``` …
```

GAPI Fluid: SIMD for SubC kernel.

---

modules/dnn/src/onnx/onnx_importer.cpp

A few fixes for https://github.com/opencv/opencv/issues/21078, tests are coming to 4.x with https://github.com/opencv/opencv/pull/21088
Transpose: https://github.com/onnx/onnx/blob/master/docs/Operators.md#transpose

Add default order to Transpose

---

modules/dnn/src/onnx/onnx_importer.cpp

Fix for https://github.com/opencv/opencv/issues/21078, tests are coming to 4.x with https://github.com/opencv/opencv/pull/21088
Sum: https://github.com/onnx/onnx/blob/master/docs/Operators.md#sum

add Sum of 1 input

---

modules/videoio/src/cap_android_mediandk.cpp

- issue nubmer #21149 report, some android 12 device, allocated bufferSize is too small for the retrieve frame, so change logic for debugging
- when this debugging successful in android studio environment, I will change logic about check bufferSize for the work well in any android environment (any sdk version including 31 - android12)
<cut/>
```
force_builders=Android pack,docs
android_pack_config=ndk-18-api-level-24.config.py
```

Check buffer size when frameWidth * frameHeight bigger than allocated buffer size

---

modules/dnn/test/test_int8_layers.cpp

- zero additional code coverage and up to x3-x8 tests slowdown
- implementation executes OCV/CPU in all cases
- wrong skip conditions
relates #20228

dnn(test): drop non OCV/CPU cases for Int8

---

modules/dnn/test/test_backends.cpp
modules/dnn/test/test_caffe_importer.cpp
modules/dnn/test/test_darknet_importer.cpp
modules/dnn/test/test_halide_layers.cpp
modules/dnn/test/test_layers.cpp
modules/dnn/test/test_misc.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp
modules/dnn/test/test_torch_importer.cpp

backport of #21167
<cut/>
Before:
```
[ SKIPSTAT ] 1106 tests skipped
[ SKIPSTAT ] TAG='mem_6gb' skip 7 tests
[ SKIPSTAT ] TAG='verylong' skip 7 tests
[ SKIPSTAT ] TAG='dnn_skip_ie_myriadx' skip 190 tests
[ SKIPSTAT ] TAG='dnn_skip_ocl' skip 4 tests (1 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_ocl_fp16' skip 32 tests (3 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_ie' skip 0 tests (301 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_ie_ngraph' skip 288 tests (182 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_ie_ocl' skip 19 tests
[ SKIPSTAT ] TAG='dnn_skip_ie_ocl_fp16' skip 67 tests (2 times in extra skip list)
[ SKIPSTAT ] TAG='skip_other' skip 492 tests
[==========] 7706 tests from 78 test cases ran.
```
After:
```
[ SKIPSTAT ] 832 tests skipped
[ SKIPSTAT …
```

(3.4) dnn(test): re-enable tests which works with OpenVINO 2021.4.x

---

modules/dnn/src/onnx/onnx_importer.cpp

Fix for https://github.com/opencv/opencv/issues/21078, tests are coming with https://github.com/opencv/opencv/pull/21088.
AveragePool: https://github.com/onnx/onnx/blob/master/docs/Operators.md#averagepool
MaxPool: https://github.com/onnx/onnx/blob/master/docs/Operators.md#maxpool

fix ceil_mode for Average/MaxPooling

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/opencl/activations.cl

Fix for https://github.com/opencv/opencv/issues/21078, tests are coming to 4.x with https://github.com/opencv/opencv/pull/21088
ELU: https://github.com/onnx/onnx/blob/master/docs/Operators.md#elu

Add alpha parameter to ELU layer

---

modules/videoio/src/cap_android_camera.cpp

In the NV21 and YV12 formats, "V (Cr)" is placed before "U (Cb)".
NV21: YYYYYYYY VUVU
YV12: YYYYYYYY VVUU
https://www.itread01.com/content/1542704886.html
https://developer.android.com/reference/android/graphics/ImageFormat#NV21
https://developer.android.com/reference/android/graphics/ImageFormat#YV12
Test Device : Pixel(NV21), Pixel3a(NV21)
```
android_pack_config=ndk-18-api-level-24.config.py
```

videoio: fix grabFrame() in cap_android_camera.cpp

---

modules/gapi/perf/common/gapi_core_perf_tests.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_cpu.cpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

SIMD for GAPI Fluid MulC kernel.
<cut/>
[FluidMulCSIMD.xlsx](https://github.com/opencv/opencv/files/7642127/FluidMulCSIMD.xlsx)
``` …
```

GAPI Fluid: SIMD for MulC kernel.

---

modules/core/include/opencv2/core/hal/intrin_rvv.hpp
modules/dnn/src/layers/layers_common.simd.hpp
platforms/linux/riscv64-clang.toolchain.cmake

This patch is going to fix and update the RVV cross-compile using clang.
In terms of support for RVV, Clang/LLVM is more active. With the update of spec and Intrinsic, many new functions have been supported by LLVM, but not in GNU yet. Therefore, for RVV related development in OpenCV, I propose to use clang/LLVM as the compiler.
There are a few differences between the GNU tool-chain and LLVM:
1. C-style casting on RVV type is invalid. Clang has checked on it, not in GCC yet.
2. Some intrinsic is renamed.
3. New instruction/intrinsic. E.g. `vpopc`
4. Vector type vxxxmf<n> is implemented.
5. Overloaded intrinsic.
For that, the following file is updated:
- `platforms/linux/riscv64-clang.toolchain.cmake` : the CMake file for RVV cross-compile. Modify RVV version in compile flag(0p9 -> 0p10). …

Update RVV backend for using Clang.

---

modules/videoio/include/opencv2/videoio.hpp
modules/videoio/src/cap_msmf.cpp
modules/videoio/test/test_audio.cpp

I changed the CAP_PROP_AUDIO_SAMPLES_PER_SECOND property from (read-only) to (open, read). Acceptable values are 8.0 kHz, 11.025 kHz, 22.05 kHz, and 44.1 kHz. If the value is not set, the behavior is standard.
@alalek 
```
force_builds=Win32
```

Audio MSMF: added the ability to set sample per second

---

modules/dnn/test/test_onnx_importer.cpp

3.4 part: #21173
<cut/>
Before (2021-12-01):
```
[ SKIPSTAT ] 1338 tests skipped
[ SKIPSTAT ] TAG='mem_6gb' skip 7 tests
[ SKIPSTAT ] TAG='verylong' skip 7 tests
[ SKIPSTAT ] TAG='dnn_skip_ie_myriadx' skip 193 tests
[ SKIPSTAT ] TAG='dnn_skip_ocl' skip 4 tests (1 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_ocl_fp16' skip 36 tests (3 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_ie' skip 0 tests (343 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_ie_ngraph' skip 355 tests (189 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_ie_cpu' skip 1 tests
[ SKIPSTAT ] TAG='dnn_skip_ie_ocl' skip 21 tests
[ SKIPSTAT ] TAG='dnn_skip_ie_ocl_fp16' skip 71 tests (2 times in extra skip list)
[ SKIPSTAT ] TAG='skip_other' skip 643 tests
[==========] 8470 tests from 85 test cases …
```

dnn(test): re-enable tests which works with OpenVINO 2021.4.x

---

modules/stitching/include/opencv2/stitching/detail/matchers.hpp
modules/stitching/misc/python/test/test_stitching.py

As outlined in the feature request in the issue https://github.com/opencv/opencv/issues/21171 : the keypoints field has been made parsable by the bindings.

Added CV_PROP_RW macro to keypoints

---

modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp

Fix for "MulDoublePerfTestGPU" test failures.
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master_opt-avx512_noICV-win64-vc16/builds/52)
<cut/>
``` …
```

GAPI GPU: fix for "MulDoublePerfTestGPU" test failures.

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/init.cpp
modules/dnn/src/layers/arg_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra:** https://github.com/opencv/opencv_extra/pull/941
Note: ArgMax/ArgMin layers should output  int64 tensor per standard, but DNN module uses floats everywhere.
`opencv_extra=argminmax_dnn`
resolves #10286
relates #20733

Add ArgMax and ArgMin layers

---

cmake/OpenCVDetectPython.cmake
modules/python/common.cmake

This PR fixes following issue https://github.com/opencv/opencv/issues/21141.

Replaced distutils module to sysconfig

---

modules/gapi/include/opencv2/gapi/streaming/onevpl/cfg_params.hpp
modules/gapi/samples/onevpl_infer_single_roi.cpp
modules/gapi/src/streaming/onevpl/cfg_params.cpp

Fix for issue 
https://github.com/opencv/opencv/issues/21225
<cut/>
```
force_builders=Linux x64,Docs,Linux32,Win32, Mac
```

G-API: Fix Win32 build: uint64_t ->size_t

---

platforms/ios/build_framework.py

When generating a macos framework using the `build_framework.py` script, if a different name has been chosen for the framework (using the `--framework_name` option), the headers must all be updated to use this new name as well. However, this script will throw an exception if the header file included non-ASCII characters, since the files are opened and saved in ASCII mode. This change ensures that headers are read and written as UTF-8 encoded files instead of ascii.

fix unicode errors for framework headers

---

modules/core/src/ocl.cpp

fixed an error ------Context::p is protected whinin this context

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/940
Batch_matmul means we do matirx multiplication in a batch size.
We noiced that we can implement batch_matmul layer by "InnerProduct" when there is no `const` blob in the input tensors. 
<cut/>

Add BatchMatMul layer support for tf_importer

---

modules/objc/generator/gen_objc.py
platforms/ios/build_framework.py

This PR fixes following issue https://github.com/opencv/opencv/issues/21141 for files in 4.x branch which are not located in 3.4 branch.

Replaced distutils to shutil when copying files in a tree

---

modules/dnn/include/opencv2/dnn/all_layers.hpp
modules/dnn/src/cuda/activations.cu
modules/dnn/src/cuda/functors.hpp
modules/dnn/src/cuda4dnn/kernels/activations.hpp
modules/dnn/src/cuda4dnn/primitives/activation.hpp
modules/dnn/src/layers/elementwise_layers.cpp
modules/dnn/src/opencl/activations.cl

**Merge after https://github.com/opencv/opencv/pull/21160.**
Fix for https://github.com/opencv/opencv/issues/21078, tests are coming to 4.x with https://github.com/opencv/opencv/pull/21088
ELU: https://github.com/onnx/onnx/blob/master/docs/Operators.md#elu
<cut/>
``` …
```

Add alpha parameter to ELU (CUDA)

---

modules/imgproc/src/opencl/resize.cl
modules/imgproc/src/resize.cpp
modules/imgproc/test/ocl/test_warp.cpp

resolves #21198
<cut/>
```
```

imgproc(OpenCL): fix resizeLN, avoid integer overflow

---

modules/gapi/perf/common/gapi_core_perf_tests.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_cpu.cpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

Moved SIMD for GAPI Fluid AbsDiffC kernel to enable dynamic dispatching.
<cut/>
[FluidAbsDiffCSIMDEnableDynamicDispatch.xlsx](https://github.com/opencv/opencv/files/7675258/FluidAbsDiffCSIMDEnableDynamicDispatch.xlsx)
``` …
```

GAPI Fluid: Enable dynamic dispatching for AbsDiffC kernel.

---

doc/tutorials/imgproc/pyramids/pyramids.markdown

This PR change `16` to `256` for the gaussian pyramid tutorial. The tutorial use a 5x5 filter with elements sum up to 256, thus to normalize, the factor to be divided should be 256 instead of 16.
To verify if 256 is correct and 16 is not, I come up with the following test code locally, re-implement the pyramid down, and 256 is verified to be correct, 16 not correct.
```c++
void pyramidDown(const Mat& src, Mat& dst, const Size& _dsz = Size(),
int  borderType = BORDER_DEFAULT
)
{
CV_Assert(borderType != BORDER_CONSTANT);
Size dsz;
if (_dsz.empty()) {
fprintf(stderr, "!! dsz empty()\n");
int src_width = src.size().width;
int src_height = …
```

docs: correct normalize factor in gaussian pyramid tutorial

---

modules/imgproc/src/color_lab.cpp
modules/imgproc/test/test_color.cpp

- no NaN propagation guarantee
details #21111

imgproc: catch NaNs in clip(), use table index debug check

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra:** [opencv/opencv_extra#943](https://github.com/opencv/opencv_extra/pull/943)
The square layer is used to square each element. We noiced that we can implement square layer by "Eltwise"  by connecting the input twice to it.

Add Square layer support for tf_importer

---

modules/imgproc/src/color_lab.cpp
modules/imgproc/test/test_color.cpp

This is a follow-up on #21111 .
BTW, may I suggest to add a v_clamp to HAL that would be NaN safe ? _mm_min_ss does not seem to be according to https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#techs=SSE,SSE2,SSE3,SSSE3,SSE4_1,SSE4_2&text=min_ss&ig_expand=4786

Use NaN-safe clip function.

---

modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/test/test_tf_importer.cpp

**Merge with extra:** opencv/opencv_extra#946
Add tf_argmax and tf_argmin parsing for dnn.
relates #21208.

add argmax and argmin parsing for tensorflow

---

modules/videoio/src/cap_gstreamer.cpp
modules/videoio/test/test_audio.cpp

I added audio support wav and flac formats in Gstreamer backend
</cut>
```
build_image:Linux AVX2=ubuntu:20.04
```

Audio GStreamer: added support .wav .flac audio formats

---

modules/imgproc/src/thresh.cpp
modules/imgproc/test/test_thresh.cpp

Fix of the issue [#16085](https://github.com/opencv/opencv/pull/16085).
The problem appeared in the case when source element is equal to the threshold (float data type). Due to the difference between OpenCV and IPP function implementations we have to compare source element with the floating point value next to the threshold (thresh + eps), not the threshold itself; eps value was updated.
<cut/>
```
```

Fixed threshold(THRESH_TOZERO) at imgproc(IPP)

---

modules/gapi/include/opencv2/gapi/core.hpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

[Performance report](https://github.com/opencv/opencv/files/7717918/SubRC.SIMD.xlsx)
``` …
```

GAPI FLUID: SIMD for SubRC kernel

---

modules/dnn/test/test_misc.cpp
modules/dnn/test/test_onnx_importer.cpp
modules/dnn/test/test_tf_importer.cpp

[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master_vulkan-lin64/builds/895)
```
force_builders_only=Linux AVX2
build_image:Linux AVX2=ubuntu-vulkan:16.04
buildworker:Linux AVX2=linux-4
test_filter:Linux AVX2=*
```

dnn(test): skip failed tests on Vulkan backend

---

3rdparty/ffmpeg/ffmpeg.cmake
modules/videoio/src/cap_ffmpeg_impl.hpp

Merge with 3rdparty: https://github.com/opencv/opencv_3rdparty/pull/70
FFmpeg 3.4.9
previous update: #20808
```
```

ffmpeg/3.4: update FFmpeg wrapper 2021.12

---

3rdparty/ffmpeg/ffmpeg.cmake

Merge with 3rdparty: https://github.com/opencv/opencv_3rdparty/pull/71
FFmpeg 4.4.1
previous update: #20811

ffmpeg/4.x: update FFmpeg wrapper 2021.12

---

modules/highgui/CMakeLists.txt

resolves #21299
relates #21213
/cc @LaurentBerger 
4.x patch is next... Done: #21303
<cut/>
```
build_image:Custom Win=msvs2019-opengl
```

(3.4) highgui: fix Win32 with OPENGL=ON

---

modules/highgui/CMakeLists.txt

resolves #21299
relates #21302
relates #21213
/cc @LaurentBerger 
<cut/>
```
build_image:Custom Win=msvs2019-opengl
```

highgui: fix Win32 with OPENGL=ON

---

modules/dnn/src/dnn.cpp

- this doesn't make sense in case of multiple inputs
relates #18145
<cut/>
``` …
```

dnn: do not try to rebuilt network during setInput()

---

modules/highgui/src/window_gtk.cpp

`flags` doesn't pass CV_EVENT_FLAG_LBUTTON / CV_EVENT_FLAG_MBUTTON / CV_EVENT_FLAG_RBUTTON press modifiers during the mouse movement.
Test example: `samples/python/find_obj.py`
---
broken since #20253
Reference: https://docs.gtk.org/gtk3/func.accelerator_get_default_mod_mask.html
> The modifier mask determines which modifiers are considered significant for **keyboard** accelerators.

highgui(gtk): fix onmouse event flags

---

samples/python/find_obj.py

This PR fixes IndexError that occurs when running asift.py sample and trying to see matching points pairs. The error is caused by incorrect array shape in draw method from find_obj.py.

Fix matching points viewing in asift.py sample

---

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
modules/dnn/src/onnx/onnx_graph_simplifier.hpp
modules/dnn/src/onnx/onnx_importer.cpp

BTW, Peak memory usage (`readNetFromONNX("resnet-34_kinetics.onnx")`, `/usr/bin/time` output):
- before: `822832maxresident`
- after: `548984maxresident`

dnn(onnx): debug dump of inputs/outputs/initializers in importer

---

modules/dnn/src/layers/pooling_layer.cpp

- to avoid out of buffer access
relates #19416 (avoid out of range access)
<cut/>
Before (valgrind):
```
...
[DEBUG:0@5.537] DNN/ONNX: processing node with 1 inputs and 1 outputs: [MaxPool]:(66)
==1070476== Invalid read of size 4
==1070476==    at 0x4AB62B7: cv::dnn::PoolingLayerImpl::getMemoryShapes(std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > const&, int, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&) const (pooling_layer.cpp:1118)
```
After:
```
...
[DEBUG:0@5.778] DNN/ONNX: processing node with 1 inputs and 1 outputs: [MaxPool]:(66) …
```

dnn: add checks in pooling layer implementation

---

doc/opencv.bib
modules/calib3d/doc/calib3d.bib
modules/calib3d/doc/solvePnP.markdown
modules/calib3d/include/opencv2/calib3d.hpp

Use a single PnP pose computation page similar to the Bayer conversion page in order to remove duplicated doc and avoid potential mistakes when updating the doc in the future.

Main PnP pose computation doc page

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/src2/cv2.cpp
modules/python/test/test_misc.py

resolves #20930
/cc @UnaNancyOwen @berak

python: use '((x,y), (w,h), angle)' in std::vector<RotatedRect>

---

modules/gapi/src/backends/fluid/gfluidcore.cpp

Disabling SSE4.1 path in GFluidResize due to Valgrind issues

---

modules/core/include/opencv2/core/dualquaternion.inl.hpp
modules/core/include/opencv2/core/quaternion.inl.hpp

Warning fixes for quaternion headers

---

modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

- re-enable quantized models tests previously disabled in #21340
<cut/>
```
```

dnn(onnx): handle non-default ONNX domains

---

modules/core/include/opencv2/core/version.hpp

OpenCV 4.5.5
relates #21281
<cut/>
<details>
[opencv_world455.dll (vc14)](https://www.virustotal.com/gui/file/95c909d2a741732cccdf64ca21b7fbcbc2ee6e2b4f5434912a61b50e12b96d74)
[opencv_world455d.dll (vc14)](https://www.virustotal.com/gui/file/c9efe3d4a9cdab27761f26ebd29cd6a159f0dbaa6c08c52fc5e51a9f6c13f2a9) 
[opencv_world455.dll (vc15)](https://www.virustotal.com/gui/file/f281767a1ed3b9cf045da9304a66af73fc90c7942b905b98e53f18512be2738e)
[opencv_world455d.dll (vc15)](https://www.virustotal.com/gui/file/cec3940af60c31c696b5af9e22742aff187b2d696df963b7e84874b1fbb9f0e8)
[opencv_videoio_ffmpeg455_64.dll](https://www.virustotal.com/gui/file/865bd4199488cbf8d5d19082292de1556a652b6ad0ec82ac560c673f2ac91e6c)
</details>

release: OpenCV 4.5.5

---

modules/core/src/ocl.cpp

(3.4) core(OpenCL): add option to abort on OpenCL kernel build failure

---

modules/dnn/src/opencl/activations.cl

- (3.4) exceptions are catched by fallback CPU path
- (3.4) OPENCV_OPENCL_ABORT_ON_BUILD_ERROR (disabled by default)
- fixed DNN OpenCL kernels
```
```

core(OpenCL): add option to abort on OpenCL kernel build failure

---

modules/core/include/opencv2/core/mat.hpp

This pull request updates the `UMatUsageFlags` documentation to warn the user that most of these flags are experimental.
Related issue: #20765

Doc warnings about experimental UMatUsageFlags

---

modules/imgproc/src/connectedcomponents.cpp
modules/imgproc/test/test_connectedcomponents.cpp

Fixes bug referenced in issue #21366, regarding CCL algorithms LabelingBolelli4C and LabelingBolelli4CParallel.

Fix #21366

---

platforms/apple/build_xcframework.py

apple/build_xcframework.py: fix incorrect catalyst archs

---

modules/core/src/kmeans.cpp

Related to [this Stack Overflow question](https://stackoverflow.com/questions/70632193/error-message-in-opencv-number-of-clusters-should-be-more-than-number-of-elemen), the assertion _message_ of which greatly surprised me.
Someone please consider if this makes sense. It's so strange that I question my perception. `N` is the number of elements, `K` is the number of clusters.

kmeans: assertion "There can't be more clusters than elements"

---

modules/videoio/src/cap_msmf.cpp

Message is expected during normal code execution.
Warnings are visible by default and may confuse users.
- https://stackoverflow.com/questions/53888878/cv2-warn0-terminating-async-callback-when-attempting-to-take-a-picture
- https://stackoverflow.com/questions/59596748/warn0-global-sourcereadercbsourcereadercb-terminating-async-callback-wa
- https://stackoverflow.com/questions/60007427/cv2-warn0-global-cap-msmf-cpp-674-sourcereadercbsourcereadercb-termina

videoio(MSMF): use info message in SourceReaderCB destructor

---

modules/gapi/include/opencv2/gapi/imgproc.hpp
modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp

Resolves https://github.com/opencv/opencv/issues/19379
``` …
```

GAPI Resize: fix rounding of the scaled size

---

modules/gapi/src/backends/ie/giebackend.cpp

Adapt remote inference to operate with NV12 blobs

---

modules/videoio/cmake/detect_aravis.cmake
modules/videoio/src/cap_aravis.cpp

Confirmed working with Aravis-0.8 and my Pixelink USB 3 Vision protocol camera.
Aravis updated its API to make most function calls take in GObject data to write errors to (in addition to returning error codes); OpenCV doesn't use GObject, so we just don't pass a pointer to a GObject. Additionally, I removed a deprecated function call.

Updated To Modern Version of Aravis USB 3 Vision Protocol Library

---

modules/gapi/src/backends/fluid/gfluidcore_simd_sse41.hpp
modules/gapi/src/backends/fluid/gfluidimgproc.cpp

- Reworking the Resize Linear U8C3 horizontal pass. Previous version handles 16 pixels per loop iteration. New version handles 5 pixels per iteration. 
- Fix for [valgrind issue](https://github.com/opencv/opencv/issues/21097) 
- Enabling SSE41 SIMD Resize  U8C3
<cut/>
[Resize8uc3NewHorizontal.xlsx](https://github.com/opencv/opencv/files/7614258/Resize8uc3NewHorizontal.xlsx)
```
build_image:Custom …
```

GAPI Fluid: Resize Linear U8C3 - reworking horizontal pass.

---

modules/python/src2/pycompat.hpp

Comment from Python documentation:
> Unlike other functions that steal references, `PyModule_AddObject()` only decrements the reference count of value on success.
> This means that its return value must be checked, and calling code must `Py_DECREF()` value manually on error.

fix: handle possible PyModule_AddObject failure

---

modules/gapi/test/infer/gapi_infer_ie_test.cpp

Relates #21134
OpenVINO recommends to use MSVS 2019.  Warnings (4268) are disabled.
```
build_image:Custom Win=openvino-2021.4.2-vc14
```

G-API: Suppress ngraph warnings for MSVS2015 (4268)

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/src2/cv2.cpp
modules/python/test/test_misc.py

- Add special case handling when submodule has the same name as parent
- `PyDict_SetItemString` doesn't steal reference, so reference count  should be explicitly decremented to transfer object life-time ownership
-Submodule initialization errors are propagated to the parent module initialization and `ImportError` is set.
- Add sanity checks for module registration input

Python submodules initialization fixes

---

cmake/OpenCVCompilerOptions.cmake

- avoid missing of necessary library dependencies
relates #21347
relates #21483 (3.4)
```
```

cmake(link): add '-Wl,--no-undefined'

---

modules/dnn/include/opencv2/dnn/dict.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/dnn_common.hpp
modules/dnn/src/layers/recurrent_layers.cpp

Validate:
<cut/>
```
build_image:Custom=halide:16.04
Xbuild_image:Custom=ubuntu-openvino-2019r3.0:16.04
Xbuild_image:Custom=ubuntu-openvino-2021.4.0:20.04
buildworker:Custom=linux-6
Xbuildworker:Custom=linux-5 …
```

(3.4) dnn: fix API - explicit ctors, const methods

---

modules/dnn/include/opencv2/dnn/dict.hpp
modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/misc/objc/gen_dict.json
modules/dnn/src/dnn.cpp
modules/dnn/src/dnn_common.hpp
modules/dnn/src/layers/recurrent_layers.cpp

relates #21429
Validate:
<cut/>
```
Xbuild_image:Custom=ubuntu-vulkan:16.04
Xbuild_image:Custom=halide:16.04
Xbuild_image:Custom=ubuntu-openvino-2019r3.0:16.04 …
```

(4.x) dnn: fix API - explicit ctors, const methods

---

modules/core/src/persistence_base64.cpp

relates #21496
Error message (`-Werror=address`):
```
modules/core/src/persistence_base64.cpp: In function ‘bool base64::base64_valid(const uint8_t*, size_t, size_t)’:
modules/core/src/persistence_base64.cpp:167:31: error: comparing the result of pointer addition ‘(src + ((sizetype)off))’ and NULL [-Werror=address]
167 |     if (src == 0 || src + off == 0)
|                     ~~~~~~~~~~^~~~
```

build: fix GCC12 compilation

---

modules/videoio/cmake/detect_gstreamer.cmake

resolves #21393
Resolves windows build error when building with GStreamer by adding the gst-audio dependency.
```
cap_gstreamer.obj : error LNK2019: unresolved external symbol __imp_gst_audio_info_from_caps referenced in function "public: bool __cdecl cv::GStreamerCapture::grabAudioFrame (void)" (?grabAudioFrame@GStreamerCapture@cv@@QEAA_NXZ)
```
Extends PR opencv#21294 and adds in the solution provided by opencv#21393 for windows.

videoio: added explicit gst-audio dependency for windows

---

modules/core/include/opencv2/core/core_c.h

clang-cl defines both __clang__ and _MSC_VER, yet uses `#pragma GCC` to disable certain diagnostics.
At the time `-Wreturn-type-c-linkage` was reported by clang-cl.
This PR fixes this behavior by reordering defines.
- [ + ] I agree to contribute to the project under Apache 2 License.
- [ + ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ + ] The PR is proposed to the proper branch
- [ - ] There is a reference to the original bug report and related work
- [ - ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- …

Disable -Wreturn-type-c-linkage under clang-cl

---

modules/imgproc/src/drawing.cpp

Left shift of negative values is undefined but works in practice.
A test is useless as there is no MSAN on the build farm.
This is a follow-up on https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40230

Fix undefined behavior in line drawing.

---

modules/core/src/system.cpp

hwcap should actually be long.
I set it initially as long, since I referenced the Linux code, but it looks like it causes issues on FreeBSD, while long works fine. While researching this, I noticed that HWCAP is actually long everywhere, so you might want to switch Linux to long as well.
```
```

Fix VSX detection on FreeBSD

---

modules/gapi/CMakeLists.txt
modules/gapi/include/opencv2/gapi/streaming/gstreamer/gstreamerpipeline.hpp
modules/gapi/include/opencv2/gapi/streaming/gstreamer/gstreamersource.hpp
modules/gapi/misc/python/package/gapi/__init__.py
modules/gapi/misc/python/pyopencv_gapi.hpp
modules/gapi/misc/python/test/test_gapi_streaming.py
modules/gapi/src/streaming/gstreamer/gstreamerpipeline.cpp

```
build_image:Linux AVX2=ubuntu:20.04
force_builders=Custom,Custom Win,Custom Mac,Linux AVX2 …
```

G-API: Wrap GStreamerSource

---

modules/python/src2/cv2.cpp
modules/python/test/test_misc.py

relates #21478
Fix for the module reference counter after discovering the Python interpreter shutdown issue during  #21489.

fix: wrong reference counter after module initialization

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/src2/cv2.cpp
modules/python/test/test_misc.py

- Add special case handling when submodule has the same name as parent
- `PyDict_SetItemString` doesn't steal reference, so reference count  should be explicitly decremented to transfer object life-time  ownership
- Add sanity checks for module registration input
Backport: #21478 

Python submodules initialization fixes backport to 4.x

---

modules/highgui/src/window.cpp

actually calling `imshow` with an empty Mat gives confusing Assertion
`OpenCV(4.5.5-dev) D:\GitHub\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'`

fix for confusing Assertion in imshow 

---

modules/gapi/perf/gpu/gapi_core_perf_tests_gpu.cpp

Fix for https://github.com/opencv/opencv/pull/21474#issuecomment-1023060475
``` …
```

GAPI: Change comparison function for DivC GPU test

---

modules/dnn/src/graph_simplifier.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_importer.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/954
Opset13 has changed resize layer mapping. 
And there may the empty input in the resize node.
Happened when exporting the ONNX model with the 1.9 or later version of pytorch with opset 13, for example the "Resize" in [ AnimeGANv2 model](https://github.com/Kazuhito00/AnimeGANv2-ONNX-Sample/tree/main/model).
More details can be found in the [Test data](https://github.com/opencv/opencv_extra/pull/954).
```
opencv_extra=resize_onnx_opset13
```

Add resize layer compatible with ONNX opset13 version

---

modules/core/src/hal_internal.cpp

Because Fortran is called in Lapack, MSAN does not think the memory
has been written even though it is the case.
MSAN does no support well cross-language memory analysis.

Fix wrong MSAN errors.

---

modules/dnn/include/opencv2/dnn/dnn.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/test/test_onnx_conformance.cpp

continues #21490
TODO:
```
```

(3.4) dnn: support outputs registration under new names

---

modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

[Split4 SIMD .xlsx](https://github.com/opencv/opencv/files/7970580/Split4.SIMD.xlsx)
``` …
```

GAPI FLUID: Enable dynamic dispatching for Split4

---

modules/imgcodecs/src/grfmt_tiff.cpp
modules/imgcodecs/test/test_tiff.cpp

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/955
```
opencv_extra=master
```

TiffEncoder write support more depth type

---

modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

Added SIMD for GAPI Fluid DivC kernel..
<cut/>
[FluidDivCSIMD.xlsx](https://github.com/opencv/opencv/files/7897396/FluidDivCSIMD.xlsx)
``` …
```

GAPI Fluid: SIMD for DivC kernel.

---

modules/core/src/cuda/gpu_mat.cu
modules/ts/include/opencv2/ts/cuda_test.hpp
modules/ts/src/cuda_test.cpp

`GpuMat::dataend()` is incorrectly calculated in [GpuMat::create()](url) meaning that `locateROI(wholeSize,ofs)` currently returns the stride in `wholeSize` instead of the width of the ROI when the `GpuMat` constructor has to allocate device memory internally.
The test case https://github.com/opencv/opencv_contrib/pull/3168 requres a modification to `createMat()` to return `wholeSize` and `ofs`.
This PR will cause cudafilters test cases to fail until https://github.com/opencv/opencv_contrib/pull/3167 is merged.
```
```

Fix calculation of GpuMat::dataend

---

modules/dnn/src/dnn.cpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/ie_ngraph.hpp
modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp

fixup #18031
part of fixes from #21564 
Validate:
<cut/>
```
Xbuild_image:Custom=ubuntu-openvino-2022.1.0.dev20220131:20.04
test_modules:Custom Mac=dnn,gapi,python2,python3,java
```

dnn(ngraph): fixup get_output_as_single_output_node() replacement patch

---

modules/dnn/include/opencv2/dnn/shape_utils.hpp
modules/dnn/src/dnn.cpp
modules/dnn/src/ie_ngraph.cpp
modules/dnn/src/ie_ngraph.hpp
modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp

Failed [nightly builds](http://pullrequest.opencv.org/buildbot/builders/master_openvino-skl-lin64/builds/1276):
```
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] Test_ONNX_layers.Convolution_variable_weight/0, where GetParam() = NGRAPH/CPU
[  FAILED  ] Test_ONNX_layers.Conv1d/0, where GetParam() = NGRAPH/CPU
[  FAILED  ] Test_ONNX_layers.Conv1d_bias/0, where GetParam() = NGRAPH/CPU
[  FAILED  ] Test_ONNX_layers.Conv1d_variable_weight/0, where GetParam() = NGRAPH/CPU
[  FAILED  ] Test_ONNX_layers.PoolConv1d/0, where GetParam() = NGRAPH/CPU
```
Validate:
<cut/>
```
Xbuild_image:Custom=ubuntu-openvino-2022.1.0.dev20220131:20.04
build_image:Custom …
```

dnn: fix outputs handling with OpenVINO backend

---

modules/imgproc/include/opencv2/imgproc.hpp

Trying to improve the documentation for the LineIterator class. In particular, the previous documentation for the constructor was not rendered reasonably by Doxygen.

Update LineIterator documentation

---

modules/imgproc/include/opencv2/imgproc.hpp
modules/imgproc/src/floodfill.cpp
modules/imgproc/test/test_floodfill.cpp

fix cv::floodfill() for calling it with an empty mask

---

modules/core/include/opencv2/core/persistence.hpp

Multiline post-variable doxygen comments [need a terminator](https://www.doxygen.nl/manual/docblocks.html#memberdoc). Without this PR, the previous comments appear as two separate comments in the generated HTML documentation in reverse order.
```
force_builders=docs
```

Fix cv::FileStorage::Mode::Memory doxygen layout

---

modules/videoio/src/cap_ffmpeg_impl.hpp

Apply changes discussed in https://github.com/opencv/opencv/issues/21558
<cut/>
```
build_image:Custom Win=ffmpeg
Xbuild_image:Custom Win=ffmpeg-plugin
buildworker:Custom Win=windows-2
test_modules:Custom Win=videoio
```

Default FFMPEG VideoCapture backend to rtsp_flags=prefer_tcp

---

modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp

Updated skip filters in ONNX conformance tests to include OpenVINO 2022.1.
<cut/>
```
build_image:Custom=ubuntu-openvino-2022.1.0.dev20220131:20.04
test_modules:Custom Mac=dnn,gapi,python2,python3,java
```

Update filters in ONNX tests

---

modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp

backport of #21609
<cut/>
```
build_image:Custom=ubuntu-openvino-2022.1.0.dev20220131:20.04
test_modules:Custom Mac=dnn,gapi,python2,python3,java
```

[backport] Update filters in ONNX tests

---

modules/imgcodecs/src/grfmt_pam.cpp
modules/imgcodecs/src/grfmt_tiff.cpp

(3.4) imgcodecs: add runtime checks to validate input

---

modules/core/src/matrix.cpp

Thread Sanitizer identified an incorrect implementation of double checked locking.  Use std::call_once to ensure the singleton object is created exactly once, and in a thread-safe manner.

Replaced incorrect double checked locking with a static

---

modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp

Workaround for the OpenCV's known issue. The issue is observed for 16S destination type in arithmetical operation.
Linked and resolved issue is "**G-API: Sporadic failures of DivCPerfTestFluid/DivCPerfTest (2022-02-03)**" #21584
<cut/>
``` …
```

GAPI Perf Tests:Workaround for the OpenCV's issue.

---

modules/highgui/src/window_QT.cpp

can be overriden by environment:
QT_AUTO_SCREEN_SCALE_FACTOR=0
fixes #16198

highui: qt - enable hidpi by default

---

modules/gapi/src/backends/fluid/gfluidcore_simd_sse41.hpp

Fix for 32bit build issue in the Resize.
Validate:
<cut/>
```
XCPU_BASELINE:Linux32=SSE4_2
XCPU_BASELINE:Win32=SSE4_2
force_builders=linux,docs,Linux AVX2,Linux32,Win32,Custom,Custom Win,Custom Mac …
```

GAPI Fluid Resize: Fix for 32bit build issue.

---

modules/stitching/src/seam_finders.cpp

std::lower_bound is linear for set
https://en.cppreference.com/w/cpp/algorithm/lower_bound

Fix DpSeamFinder::hasOnlyOneNeighbor

---

modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp

[Merge4 SIMD.xlsx](https://github.com/opencv/opencv/files/8111470/Merge4.SIMD.xlsx)
``` …
```

GAPI FLUID: Enable dynamic dispatching for Merge4 kernel

---

modules/gapi/src/backends/fluid/gfluidimgproc.cpp

Incorrect Mat size, ksize == -1

GAPI Fluid: Fix incorrect kernel matrix size for Scharr

---

platforms/linux/riscv64-clang.toolchain.cmake

With the release of RISC-V Vector spec 1.0 and the release of Clang 14.0, we can use `-march=rv64gcv` as compile flag instead of `-march=rv64gcv0p10` and `-menable-experimental-extensions` is not needed anymore. So this patch is going to update the toolchain file to adapt the newest changing.
Note:
For now, Clang/LLVM toolchain also need GNU-toolchain for binutils(linker) and glibc. and only the very latest release binutils(2.38) will support rvv 1.0, which has not include/update in current [riscv-gnu-toolchain](https://github.com/riscv-collab/riscv-gnu-toolchain), so we have to update it manully by using following commands:
``` bash
cd riscv-gnu-toolchain/riscv-binutils && \
git checkout riscv-binutils-2.38 && \
cd .. && \
make linux
```
I also have a docker file for the new rvv-clang …

 Update Clang toolchain for RVV.

---

modules/dnn/src/darknet/darknet_io.cpp
modules/dnn/src/layers/slice_layer.cpp
modules/dnn/src/onnx/onnx_importer.cpp
modules/dnn/src/tensorflow/tf_importer.cpp
modules/dnn/src/torch/torch_importer.cpp
modules/dnn/test/test_layers.cpp

**Merge with extra:** https://github.com/opencv/opencv_extra/pull/956
```
opencv_extra=split_expand
```

Fix negative starts in Slice and add no-op Expand for consts

---

modules/imgproc/src/colormap.cpp

proposal for #21640
For regular cv::Mat CV_8UC1 src, applying the colormap is simpler than calling the cv::LUT() mechanism.

Optimize cv::applyColorMap() for simple case

---

modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp
modules/gapi/src/backends/fluid/gfluidcore.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp
modules/gapi/src/backends/fluid/gfluidcore_func.hpp
modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp
modules/gapi/test/common/gapi_tests_common.hpp

Add SIMD for GAPI Fluid DivRC kernel.
[FluidDivRCSIMD.xlsx](https://github.com/opencv/opencv/files/8095911/FluidDivRCSIMD.xlsx)
<cut/>
``` …
```

GAPI Fluid: SIMD for DivRC kernel.

---

modules/core/include/opencv2/core/bindings_utils.hpp
modules/python/src2/cv2.cpp
modules/python/src2/gen2.py
modules/python/src2/pycompat.hpp
modules/python/test/test_misc.py

All classes are registered in the scope that corresponds to C++ namespace or exported class.
Example:
`cv::ml::Boost` is exported as `cv.ml.Boost`
`cv::SimpleBlobDetector::Params` is exported as `cv.SimpleBlobDetector.Params`
For backward compatibility all classes are registered in the global module with their mangling name containing scope information. Example:
`cv::ml::Boost` has `cv.ml_Boost` alias to `cv.ml.Boost` type
Closes #14730  
Backport for 4.x is required to handle [GAPI aliases](https://github.com/opencv/opencv/blob/6ae8103022cdb3cd79f417945fd8332c28298b7b/modules/gapi/misc/python/package/gapi/__init__.py#L291) in the right way:
```python
cv.gapi.wip.draw.Rect = cv.gapi_wip_draw_Rect
cv.gapi.wip.draw.Text = cv.gapi_wip_draw_Text
cv.gapi.wip.draw.Circle = …
```

feature: submodule or a class scope for exported classes

---

modules/core/src/directx.cpp

Fix convertFromD3D11Texture2D is not working with NVIDIA GPU

---

samples/python/stitching_detailed.py

- `seam_finder.find()` returns None and overwrites `masks_warped`
- `indices` is only 1-dimensional
- avoid invalid value in sqrt and subsequent runtime warning
- avoid printing help string on each run (use argparse builtin behavior)
- added graphcut seam finder support
Tested on Ubuntu 20.04 with python 3.8.10 and opencv-python-contrib 4.5.5.62

Bug fixes and feature support in stitching_detailed.py

---

modules/gapi/perf/streaming/gapi_streaming_source_perf_tests.cpp
modules/gapi/src/streaming/onevpl/engine/preproc/preproc_engine.cpp
modules/gapi/src/streaming/onevpl/engine/preproc/preproc_engine.hpp
modules/gapi/src/streaming/onevpl/engine/preproc/preproc_session.cpp
modules/gapi/src/streaming/onevpl/engine/preproc/preproc_session.hpp
modules/gapi/src/streaming/onevpl/engine/preproc_engine_interface.hpp
modules/gapi/test/streaming/gapi_streaming_vpp_preproc_test.cpp

Add ROI processing for core part of  VPP preproc which is essential from https://github.com/opencv/opencv/pull/21554
```
force_builders=XCustom,Custom Win,Custom Mac
Xbuild_image:Custom Win=openvino-2021.2.0 …
```

 G-API: Add ROI processing in VPP preproc

---

modules/gapi/src/backends/cpu/gcpubackend.cpp
modules/gapi/src/backends/cpu/gcpubackend.hpp
modules/gapi/src/backends/fluid/gfluidbackend.cpp
modules/gapi/test/cpu/gapi_ocv_stateful_kernel_tests.cpp
modules/gapi/test/internal/gapi_int_executor_tests.cpp

* Added reshape functionality to CPU backend
* Fixed fluid heterogeneous reshape
``` …
```

G-API: Added reshape() functionality to CPU backend

---

modules/videoio/src/cap_ffmpeg_impl.hpp

resolves #21696
```
==54702== 8,040 bytes in 15 blocks are definitely lost in loss record 307 of 310
==54702==    at 0x4849803: memalign (vg_replace_malloc.c:1516)
==54702==    by 0x484991F: posix_memalign (vg_replace_malloc.c:1688)
==54702==    by 0x9A34D44: av_malloc (in /usr/lib64/libavutil.so.56.70.100)
==54702==    by 0x9A3503D: av_mallocz (in /usr/lib64/libavutil.so.56.70.100)
==54702==    by 0x9A2055F: av_frame_alloc (in /usr/lib64/libavutil.so.56.70.100)
==54702==    by 0x48DEADE: CvCapture_FFMPEG::retrieveFrame(int, unsigned char**, int*, int*, int*, int*) (cap_ffmpeg_impl.hpp:1444)
==54702==    by 0x48E360E: cvRetrieveFrame_FFMPEG (cap_ffmpeg_impl.hpp:2957)
==54702==    by 0x48E3A07: cv::(anonymous namespace)::CvCapture_FFMPEG_proxy::retrieveFrame(int, cv::_OutputArray const&) …
```

videoio(ffmpeg): fix memory leak through sw_picture
