modules/dnn/src/ie_ngraph.cpp
=> Changed call of NodeTypeInfo constructor

modules/gapi/CMakeLists.txt, modules/gapi/src/streaming/onevpl/accelerators/surface/base_frame_adapter.cpp, modules/gapi/src/streaming/onevpl/accelerators/surface/base_frame_adapter.hpp, modules/gapi/src/streaming/onevpl/accelerators/surface/cpu_frame_adapter.cpp, modules/gapi/src/streaming/onevpl/accelerators/surface/dx11_frame_adapter.cpp, modules/gapi/src/streaming/onevpl/engine/preproc/preproc_dispatcher.cpp, modules/gapi/src/streaming/onevpl/engine/preproc/preproc_dispatcher.hpp, modules/gapi/src/streaming/onevpl/engine/preproc/preproc_engine.cpp, modules/gapi/src/streaming/onevpl/engine/preproc/vpp_preproc_defines.hpp, modules/gapi/src/streaming/onevpl/engine/preproc_defines.hpp, modules/gapi/test/streaming/gapi_streaming_vpp_preproc_test.cpp
Added VPP preproc Dispatcher/Facade implements the same IPreprocEngine interface and aggregates CPU & GPU preproc engine and switch implementation by actual MediaFrame type. 
```
force_builders=XCustom,Custom Win,Custom Mac
Xbuild_image:Custom Win=openvino-2021.2.0 …
```
=> G-API: Add VPP preproc CPU/GPU dispatcher

modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp, modules/gapi/src/backends/fluid/gfluidcore.cpp, modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp, modules/gapi/src/backends/fluid/gfluidcore_func.hpp, modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp
- Move SIMD of the Add kernel to enable dynamic dispatching.
- Add support of new combination of types.
<cut/>
Performance:
[FluidAddSIMD.xlsx](https://github.com/opencv/opencv/files/8219348/FluidAddSIMD.xlsx)
``` …
```
=> GAPI Fluid: Dynamic dispatching for Add kernel.

modules/core/src/va_wrapper.impl.hpp
After #21538 libopencv_core started to explicitly link with libva. We wanted to keep this dependency optional and load it dynamically at runtime.
Before patch:
```
$ ldd lib/libopencv_core.so
linux-vdso.so.1 (0x00007ffdbf3d9000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd4a6c0b000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd4a69ec000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd4a67e4000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd4a65c7000)
libva.so.2 => /usr/lib/x86_64-linux-gnu/libva.so.2 (0x00007fd4a63a6000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd4a601d000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd4a5c7f000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 …
```
=> Fix libva dynamic loading

modules/gapi/include/opencv2/gapi/imgproc.hpp, modules/gapi/include/opencv2/gapi/own/assert.hpp, modules/gapi/perf/cpu/gapi_imgproc_perf_tests_fluid.cpp, modules/gapi/src/backends/fluid/gfluidimgproc.cpp
Resize F32C1 scalar version.
<cut/>
```
CPU_BASELINE:Custom …
```
=> GAPI Fluid: Resize F32C1 scalar version.

modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp, modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp, modules/gapi/src/backends/fluid/gfluidcore.cpp, modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp, modules/gapi/src/backends/fluid/gfluidcore_func.hpp, modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp
- Dynamic dispatching for Sub was enabled.
- Support of new combinations of type was added.
<cut/>
``` …
```
=> GAPI Fluid: Enable dynamic dispatching for the Sub kernel.

modules/core/src/mathfuncs.cpp, modules/core/test/test_arithm.cpp, modules/ts/include/opencv2/ts/ocl_test.hpp
Resolves #21732
Raise an exception if one of sources is the same as one of destinations since inplace mode works incorrectly (with and without IPP).
```
```
=> cartToPolar/polarToCart: disable inplace mode

modules/core/misc/objc/gen_dict.json, modules/objc/generator/gen_objc.py
Alternative fix for #21725
```
```
=> Objective-C wrapper header fix-ups to avoid clashes with system macros

modules/core/include/opencv2/core/vsx_utils.hpp
LLVM 13.0.0 on FreeBSD 13.1-BETA2 on powerpc64le:
<cut/>
```
/wrkdirs/usr/ports/graphics/opencv/work/opencv-4.5.5/modules/core/include/opencv2/core/vsx_utils.hpp:352:12: warning: 'vec_permi' macro redefined [-Wmacro-redefined]
^
/usr/lib/clang/13.0.0/include/altivec.h:13077:9: note: previous definition is here
#define vec_permi(__a, __b, __c)                                               \
^
/wrkdirs/usr/ports/graphics/opencv/work/opencv-4.5.5/modules/core/include/opencv2/core/vsx_utils.hpp:370:25: error: redefinition of 'vec_promote'
VSX_FINLINE(vec_dword2) vec_promote(long long a, int b)
^
/usr/lib/clang/13.0.0/include/altivec.h:14604:1: note: previous definition is here
vec_promote(signed long long __a, int __b) {
^
/wrkdirs/usr/ports/graphics/opencv/work/opencv-4.5.5/modules/core/inclu …
```
=> Fix build with LLVM 13 on ppc64le

doc/js_tutorials/js_assets/webnn-electron/package.json, doc/js_tutorials/js_setup/js_setup/js_setup.markdown, doc/tutorials/calib3d/usac.markdown, doc/tutorials/core/how_to_use_OpenCV_parallel_for_new/how_to_use_OpenCV_parallel_for_new.markdown, doc/tutorials/dnn/dnn_halide_scheduling/dnn_halide_scheduling.markdown, doc/tutorials/dnn/dnn_text_spotting/dnn_text_spotting.markdown, doc/tutorials/gapi/anisotropic_segmentation/porting_anisotropic_segmentation.markdown, doc/tutorials/gapi/interactive_face_detection/interactive_face_detection.markdown, doc/tutorials/imgproc/shapedescriptors/bounding_rects_circles/bounding_rects_circles.markdown, doc/tutorials/introduction/android_binary_package/dev_with_OCV_on_Android.markdown, doc/tutorials/introduction/linux_gdb_pretty_printer/linux_gdb_pretty_printer.markdown, doc/tutorials/ios/image_manipulation/image_manipulation.markdown
Fix various typos found within tutorial documentation
=> Fix typos in tutorials within `docs/`

modules/gapi/samples/pipeline_modeling_tool.cpp, modules/gapi/samples/pipeline_modeling_tool/pipeline_builder.hpp, modules/gapi/samples/pipeline_modeling_tool/test_pipeline_modeling_tool.py
=> [G-API] Pipeline modeling tool: Skip frames

modules/python/src2/hdr_parser.py
`inline namespace` should be skipped in header parser namespaces list.
Example:
```cpp
namespace cv {
inline namespace inlined {
namespace inner {
// content
} // namespace inner
} // namespace inlined
} // namespace cv
```
Before fix `inner` is registered as `cv..inner`
After fix: `cv.inner`
=> fix: inline namespace handling in header parser

modules/python/src2/gen2.py
resolves https://github.com/opencv/opencv_contrib/issues/3171
We should not have non-initialized(NULL) base types during types registration (dynamic types registration is required by `LIMITED_API`).
Binding test is very tricky for this case, so it is not added (base and derived classes should be defined in different files)
<cut/>
---
Before (`ImgHashBase` is registered too late):
```
CVPY_TYPE(AverageHash, img_hash_AverageHash, Ptr<cv::img_hash::AverageHash>, Ptr, img_hash_ImgHashBase, 0, ".img_hash");
CVPY_TYPE(BlockMeanHash, img_hash_BlockMeanHash, Ptr<cv::img_hash::BlockMeanHash>, Ptr, img_hash_ImgHashBase, 0, ".img_hash");
CVPY_TYPE(ColorMomentHash, img_hash_ColorMomentHash, Ptr<cv::img_hash::ColorMomentHash>, Ptr, img_hash_ImgHashBase, 0, ".img_hash");
CVPY_TYPE(ImgHashBase, …
```
=> python: ensure publishing of subclasses before derived types

modules/gapi/perf/cpu/gapi_core_perf_tests_fluid.cpp, modules/gapi/src/backends/fluid/gfluidcore.cpp, modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp, modules/gapi/src/backends/fluid/gfluidcore_func.hpp, modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp
SIMD for ConvertTo
Performance:
[FluidConvertToSIMD.xlsx](https://github.com/opencv/opencv/files/8349633/FluidConvertToSIMD.xlsx)
<cut/>
``` …
```
=> GAPI Fluid: SIMD for ConvertTo.

modules/core/include/opencv2/core/hal/intrin_rvv.hpp
The goal of this patch is to optimize the existing Universal Intrinsics implementation of RVV.
The initial version of RVV UI is #18228.
The main difference between this patch and the initial version is the design of the data structure: Using a pointer to the RVV Intrinsic Type instead of an array to hold the value. In this way, no more Intrinsic functions such as load & store needed in the struct, which provides opportunities for compilation optimization.
[This](https://godbolt.org/z/4MToxzn7h) is a comparison on assembly level, taking `v_fma` as an example, the implementation of this patch reduces the number of instructions by about 50%.
This patch is tested on QEMU with the core testcases and the dnn testcases, and the results are the same as master.
See details at …
=> Update universal intrinsics of RVV back-end.

modules/dnn/src/layers/reduce_layer.cpp, modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp, modules/dnn/test/test_onnx_importer.cpp
fixup #21601
Error message:
```
ie_ngraph.cpp:359: error: (-215:Assertion failed) !cvLayer->name.empty() in function 'InfEngineNgraphNode'
```
<cut/>
```
force_builders_only=Custom,Custom Win
Xbuild_image:Custom Win=openvino-2022.1.0
```
=> dnn: fix ReduceLayer implementation, update OpenVINO tests

modules/videoio/src/cap_ffmpeg_impl.hpp
resolves #20147
<cut/>
_FFmpeg@n5.0_ (debug)
```.sh
./configure \
--enable-shared --disable-static --enable-pic --enable-gpl --enable-nonfree \
--enable-libxvid --enable-libx264 --enable-swresample \
--prefix=/home/user/ffmpeg/install \
--enable-debug=3 --disable-stripping --extra-cflags="-gstabs+ -Og -g -fno-inline -fno-omit-frame-pointer" --disable-optimizations 
```
TODO:
```
build_shared:Custom=OFF
build_examples:Custom=OFF
build_image:Linux AVX2=ubuntu:20.04
Xbuild_image:Win64=msvs2019
force_builders=Custom,Custom Win,Linux AVX2
Xbuild_image:Custom=ubuntu:20.04
build_image:Custom Win=ffmpeg …
```
=> videoio: initial FFmpeg 5.0 support

modules/imgproc/src/connectedcomponents.cpp
=> Update Connected component labelling bug

modules/stitching/include/opencv2/stitching/detail/matchers.hpp, modules/stitching/misc/python/test/test_stitching.py
In respect to the issue  #21364, the pull request makes **matches** and **inliers_mask** attributes of the **cv2.detail_MatchesInfo** class accessible from python interface. By this way, developers could be able to make  changes on the computed matches.
- [Yes] I agree to contribute to the project under Apache 2 License.
- [Yes] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [Yes] The PR is proposed to the proper branch
- [Yes] There is a reference to the original bug report and related work
=> python binding for matches and inliers_mask attributes of cv2.detail_MatchesInfo class

modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
<cut/>
```
Xbuild_image:Custom Win=openvino-2021.4.2
build_image:Custom Win=openvino-2022.1.0
test_timeout:Custom Win=600
```
=> (3.4) dnn(test): update OpenVINO tests

modules/gapi/src/backends/ie/giebackend.cpp
A warning arisen from https://github.com/opencv/opencv/pull/21688
<cut/>
```
```
=> G-API: Fix warning in giebackend

modules/gapi/src/backends/cpu/gcpubackend.cpp, modules/gapi/src/backends/cpu/gcpubackend.hpp, modules/gapi/src/executor/gexecutor.cpp, modules/gapi/src/executor/gexecutor.hpp, modules/gapi/src/executor/gstreamingexecutor.cpp, modules/gapi/test/cpu/gapi_ocv_stateful_kernel_tests.cpp
=> Fixed handling of new stream, especially for stateful OCV kernels

modules/video/src/bgfg_KNN.cpp, modules/video/src/bgfg_gaussmix2.cpp
The KNN and MOG2 background subtractors extend the `Algorithm` class but don't override the `getDefaultName()` method (which returns `my_object`).
* https://github.com/opencv/opencv/blob/4.5.5/modules/core/src/algorithm.cpp#L80-L84
Add override for the method, avoiding the `.` character in the name because persistence disallows it in key names.
* https://github.com/opencv/opencv/blob/4.5.5/modules/core/src/persistence_json.cpp#L223-L224
* https://github.com/opencv/opencv/blob/4.5.5/modules/core/src/persistence_yml.cpp#L260-L261
```
#include <opencv2/opencv.hpp>
int main(int argc, char* argv[])
{
std::cout << cv::createBackgroundSubtractorKNN()->getDefaultName() << std::endl;
cv::createBackgroundSubtractorKNN()->save("knn.algo");
std::cout << …
```
=> add BackgroundSubtractor(KNN|MOG2).getDefaultName() implementation

modules/imgproc/CMakeLists.txt, modules/imgproc/src/smooth.dispatch.cpp, modules/imgproc/test/test_filter.cpp
Fixed issue [#11303](https://github.com/opencv/opencv/issues/11303).
The problem was the following: in the parallel version of the function in case when kernelSize/2 is bigger than a height of a tile,  out-of-bounds read happens when the second and the one before the last tiles are processed.
Now sequential mode is used in such cases.
=> Fixed out-of-bounds read in parallel version of ippGaussianBlur()

modules/videoio/src/cap_ffmpeg_impl.hpp
Resolves these valgrind reports (caused by incomplete error handling bailout code in `open()`):
<cut/>
```
==940136== 11,040 bytes in 12 blocks are definitely lost in loss record 271 of 273
==940136==    at 0x4849803: memalign (vg_replace_malloc.c:1516)
==940136==    by 0x484991F: posix_memalign (vg_replace_malloc.c:1688)
==940136==    by 0x540583E: av_malloc (mem.c:104)
==940136==    by 0x4E96783: avcodec_alloc_context3 (options.c:143)
==940136==    by 0x4A3498B: icv_configure_video_stream_FFMPEG(AVFormatContext*, AVStream*, AVCodec const*, int, int, int, double, AVPixelFormat, int) (cap_ffmpeg_impl.hpp:2111)
==940136==    by 0x4A374E8: CvVideoWriter_FFMPEG::open(char const*, int, double, int, int, cv::VideoWriterParameters const&) (cap_ffmpeg_impl.hpp:2944)
==940136==    by 0x4A37FE2: …
```
=> (4.x) videoio(ffmpeg): avoid memory leaks

modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_model.cpp, modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp, modules/dnn/test/test_onnx_importer.cpp
relates #21795
<cut/>
```
Xbuild_image:Custom Win=openvino-2021.4.2
build_image:Custom Win=openvino-2022.1.0
buildworker:Custom Win=windows-1
test_timeout:Custom Win=600
```
=> (4.x) dnn(test): update OpenVINO tests

modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_int8_layers.cpp
<cut/>
<details>
```
[ RUN      ] Test_Caffe/opencv_face_detector.issue_15106/0, where GetParam() = ("dnn/opencv_face_detector.caffemodel", CPU)
Unmatched prediction: class 1 score 0.887999 box [0.594293 x 0.685449 from (0.63864, 0.71978)]
Highest IoU: 0
/build/precommit_linux64/4.x/opencv/modules/dnn/test/test_common.impl.hpp:143: Failure
Value of: matched
Actual: false
Expected: true
Unmatched prediction: class 1 score 0.466805 box [0.638403 x 0.776095 from (2.26659, 3.04262)]
Highest IoU: 0
/build/precommit_linux64/4.x/opencv/modules/dnn/test/test_common.impl.hpp:143: Failure
Value of: matched
Actual: false
Expected: true
Unmatched prediction: class 1 score 0.393454 box [0.607265 x 0.774242 from (3.10245, 3.04498)]
Highest IoU: 0 …
```
=> (4.x) dnn(test): update opencv_face_detector checks

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/test/test_tf_importer.cpp
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/970
Fixes https://github.com/opencv/opencv/issues/21852
Another way of fixing this is to draw inspiration from Rust: use custom vector type with bound checks enabled by [default](https://doc.rust-lang.org/std/vec/struct.Vec.html#indexing), providing [methods](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get_unchecked) that don't do bounds-checking.
=> Add assert to address tf simplifier security concerns

modules/core/src/persistence.cpp, modules/core/test/test_io.cpp
Fixes #21851
Relates #16488
As with https://github.com/opencv/opencv/pull/21861, we could adopt Rust's approach and move from pointers to custom vector type with bound checks enabled by [default](https://doc.rust-lang.org/std/vec/struct.Vec.html#indexing), providing [methods](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get_unchecked) that don't do bounds-checking.
=> Add assert to persistance to address security concerns

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/fisheye.cpp
#19138 
Wrap hardcoded termination criteria to `cv::TermCriteria` with default values from code
=> Add termination criteria to cv::fisheye::undistortPoints()

modules/calib3d/perf/perf_undistort.cpp, modules/calib3d/test/test_fisheye.cpp, modules/calib3d/test/test_undistort_points.cpp
Lack of test has allowed error described in [#19138] to be unnoticed.
In addition to random points, four corners and principal center
added to point set
=> Add distort/undistort test for fisheye::undistortPoints()

.github/workflows/PR-3.4-U20.yaml
This PR fixes an issue when the fork repository has another name ([example](https://github.com/opencv/opencv/runs/6064424452?check_suite_focus=true#step:6:11)).
=> Fixed url for a fork

.github/workflows/PR-4.x-U20.yaml, .github/workflows/timvx_backend_tests.yml
This PR fixes an issue when the fork repository has another name ([example](https://github.com/opencv/opencv/runs/6064424452?check_suite_focus=true#step:6:11)).
=> Fixed url for a fork (4.x branch)

.github/workflows/PR-4.x-U20.yaml, .github/workflows/timvx_backend_tests.yml
This PR adds a check for the same branch in opencv_extra fork of PR owner and fix timvx workflow (`khadas-vim3-tests`).
=> opencv_extra fork usage in Github Actions (4.x branch)

modules/imgproc/test/test_imgwarp.cpp
for the #21459 issue.
alternative to #21848 based on https://github.com/opencv/opencv/pull/21848#issuecomment-1101116161 feedback.
=> remove Imgproc_cvWarpAffine.regression test

modules/core/include/opencv2/core/cuda.hpp, modules/python/test/test_cuda.py
https://github.com/opencv/opencv/issues/21894
=> Fix #21894: Wrap constructor to Python to create initialized cuda::BufferPool object

modules/calib3d/test/test_undistort_points.cpp
=> Add use of R and P parameters to cv::undistortPoints test

.github/workflows/PR-3.4-U20.yaml
This PR adds a check for the same branch in opencv_contrib fork of PR owner for 3.4 branch.
=> opencv_contrib fork usage in Github Actions for 3.4 branch

modules/core/src/parallel.cpp
_SC_NPROCESSORS_ONLN is non standard as defined on https://man7.org/linux/man-pages/man3/sysconf.3.html
It seems to only be on glibc, cf https://www.gnu.org/software/libc/manual/html_node/Processor-Resources.html
=> Fix compilation with non glibc.

.github/workflows/PR-3.4-W10.yaml
This PR cleans a list of turned off tests for 3.4 branch (it's different for each branch).
=> GTest filtered list for 3.4 branch

modules/core/include/opencv2/core/mat.hpp
=> Remove an extra "not" in doc

modules/js/test/test_imgproc.js
In test_imgproc.js, the test_filter suite's last test assigns a variable to `size` without declaring it with `let`, polluting the global scope. This PR adds `let` to the statement, so that the variable is scoped to the test block.
Before:
After:
```
force_builder=Custom
```
=> Fix global variable assignment in JS test suite

.github/workflows/PR-3.4-U20.yaml
This PR changes a workflow to use a self-hosted GitHub runner on Linux x86_64 for 3.4 branch with ccache support.
=> Workflow to use a self-hosted Github runner on Linux x86_64 for 3.4 branch

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/undistort.dispatch.cpp, modules/calib3d/test/test_undistort_points.cpp
`cv::undistortPoints()` has unclear interface and additional functionality. New function computes only undistorted image points position
=> Add undistortImagePoints function

modules/imgcodecs/include/opencv2/imgcodecs.hpp
It was previously not clear that the extension should include the period, [and I am not the only person that encountered this problem](https://stackoverflow.com/questions/4254460/opencv-could-not-find-encoder-for-the-specified-extension).
I assume that this is true for all supported extensions, but I haven't checked the source.
=> Small imencode documentation improvement

modules/imgcodecs/src/grfmt_jpeg.cpp
Hello, I encountered [this kind of crash](https://github.com/opencv/opencv/issues/19635) on Windows and I think I've got the solution.
[`3rdparty/libjpeg-turbo/src/jpeglib.h`](https://github.com/opencv/opencv/blob/c8228e5789510ec26378eceb17311dd7bddf0b33/3rdparty/libjpeg-turbo/src/jpeglib.h#L898):
```
* NB: you must set up the error-manager BEFORE calling jpeg_create_xxx.
```
Patch to opencv_extra has the same branch name.~~
=> fix JpegEncoder::write

modules/video/src/kalman.cpp
If there will be measurement before the next predict, `statePost` and `errorCovPost` would be assigned to updated value. So I guess these steps are meant to handle the case when no measurement and KF only do the predict step.
```cpp
statePre.copyTo(statePost);
errorCovPre.copyTo(errorCovPost);
```
=> Fix KalmanFilter comment error

doc/tutorials/imgproc/imgtrans/hough_circle/hough_circle.markdown
On this page: https://docs.opencv.org/4.5.5/d4/d70/tutorial_hough_circle.html, in the _Explanation_ section, the snippets for Python and Java are switched.
This bug exists in the documentation for versions 3.3.1 up to 5.0.0-pre
=> Documentation Fix: Python and Java switched in Explanation

.github/workflows/PR-3.4-W10.yaml
This PR adds a check for the same branch in opencv_contrib fork of PR owner for 3.4 branch on Windows.
=> opencv_contrib branch check on Windows

modules/gapi/test/rmat/rmat_view_tests.cpp
Fixes [Win32 failure](http://pullrequest.opencv.org/buildbot/builders/master-win32-vc16/builds/100001) due to allocation of 1.5Gb.
```
[ RUN      ] Test/RMatViewNDTest.StepFromView/9, where GetParam() = (5, 7)
unknown file: error: C++ exception with description "bad allocation" thrown in the test body.
[  FAILED  ] Test/RMatViewNDTest.StepFromView/9, where GetParam() = (5, 7) (0 ms)
```
Max memory usage is reduced up to 4x.
```
```
=> G-API(test): reduce used amount of memory

modules/3d/src/ptcloud/sampling.cpp
Fix a bug: the output format should be determined by the channel of the `sampled_pts`.
=> Modify randomSampling in point cloud

modules/imgproc/include/opencv2/imgproc/segmentation.hpp, modules/imgproc/src/intelligent_scissors.cpp
(Noting that based on https://github.com/opencv/opencv/wiki/Branches#which-branch-should-i-target-my-pr this pull request here could be for 3.4 instead of 4.x branch. However, it is for 4.x since 3.4 doesn't have the typos.)
=> imgproc: fix two typos (imput, magnutude)

modules/videoio/src/cap_v4l.cpp
Added support for V4L2_PIX_FMT_XBGR32 and V4L2_PIX_FMT_ABGR32 pixel
formats.
<cut/>
```
```
=> Added support for 4B RGB V4L2 pixel formats

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
We have a model in https://github.com/opencv/opencv_zoo/pull/51, which has asymmetric paddings in convolution layers. The model is managed to be quantized, but the current version of opencv does not support asymmetric paddings in quantized int8 convolution layer. So this PR adds the asymmetric padding support for quantized int8 convolution layer in ONNX importer.
Test data: https://github.com/opencv/opencv_extra/pull/973
=> Support asymmetric paddings for QConv in ONNX

modules/3d/doc/3d.bib, modules/3d/include/opencv2/3d/ptcloud.hpp, modules/3d/src/ptcloud/normal_estimation.cpp, modules/3d/src/ptcloud/region_growing_3d.cpp, modules/3d/src/ptcloud/region_growing_3d.hpp, modules/3d/test/test_normal_estimation.cpp, modules/3d/test/test_ptcloud_utils.cpp, modules/3d/test/test_ptcloud_utils.hpp, modules/3d/test/test_sac_segmentation.cpp
This PR is aimed at adding point cloud normal estimation and region growing algorithms.
Since there are many methods of KNN search, and both normal  estimation and region growing use the results of KNN search, I plan to use the following structure:
To summarize the main work of this PR.
1. Added a method called `normalEstimate()` to calculate the normal and curvature of each point in the point cloud.
2. Added a class called `RegionGrowing3D` to configure and implement region growing algorithm for point cloud.
TODO:
=> Add normal estimation and region growing algorithm for point cloud

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/python/package/setup.py, platforms/android/build_sdk.py, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
previous PR with version bump: #21280
=> pre: OpenCV 3.4.18 (version++)

modules/calib3d/perf/perf_undistort.cpp, modules/calib3d/src/fisheye.cpp, modules/calib3d/test/test_fisheye.cpp
Messages:
- MSVS 2015: `modules\calib3d\src\fisheye.cpp(378): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)`
- MSVS 2015+: `warning C4244: 'initializing': conversion from 'const double' to 'int', possible loss of data (compiling source file modules\calib3d\perf\perf_undistort.cpp`
=> (4.x) build warnings

modules/videoio/test/test_audio.cpp, modules/videoio/test/test_video_io.cpp
... due to misconfigured / outdated environment
Merge after #22028
=> windows: skip failed videoio tests

3rdparty/ffmpeg/ffmpeg.cmake
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/72
- FFmpeg 4.4.2
- libvpx 1.11
previous update: #21296
=> ffmpeg/4.x: update FFmpeg wrapper 2022.05

doc/js_tutorials/js_setup/js_usage/js_usage.markdown
The Emscripten library is not guaranteed to be fully loaded during the
script element's onload event. Module.onRuntimeInitialized seems to be
more reliable.
=> Update js_usage.markdown to use onRuntimeInitialized

modules/calib3d/include/opencv2/calib3d.hpp
=> Update fisheye::distortPoints() documentation

modules/calib3d/test/test_cameracalibration.cpp
* Remove transpose for rvec after calibration
* Change compare threshold from 110% to 10% for perViewErrors
* Add transpose to goodRotMatrs load
#19849 
#20810 
=> Fix cameracalibration test

platforms/ios/build_framework.py
I've faced an issue building iOS framework on macOS. This issue happened on different devices with different python versions. It happens only with 3.4 branch.
The output:
```
============================================================
ERROR: cannot use a string pattern on a bytes-like object
============================================================
File "/Users/user/test/opencv/platforms/ios/build_framework.py", line 120, in build
self._build(outdir)
File "/Users/user/test/opencv/platforms/ios/build_framework.py", line 88, in _build
xcode_ver = getXCodeMajor()
File "/Users/user/test/opencv/platforms/ios/build_framework.py", line 45, in getXCodeMajor
m = re.match(r'Xcode\s+(\d+)\..*', ret, flags=re.IGNORECASE)
File …
```
=> Fix Xcode version matching

modules/core/include/opencv2/core/check.hpp, modules/core/include/opencv2/core/utils/plugin_loader.private.hpp, modules/core/src/check.cpp, modules/core/src/ocl.cpp, modules/core/src/utils/plugin_loader.impl.hpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/features2d/include/opencv2/features2d.hpp, modules/features2d/src/matchers.cpp, modules/gapi/include/opencv2/gapi/fluid/gfluidkernel.hpp, modules/gapi/include/opencv2/gapi/own/types.hpp, modules/stitching/include/opencv2/stitching.hpp, modules/stitching/include/opencv2/stitching/detail/motion_estimators.hpp
Removed `const` qualifier on by-value return type.
From [Scott Meyer](https://www.aristeia.com/BookErrata/ec++3e-errata.html):
> Declaring by-value function return values const will prevent their being bound to [rvalue references in C++0x](http://www.artima.com/cppsource/rvalue.html). Because rvalue references are designed to help improve the efficiency of C++ code, it's important to take into account the interaction of const return values and the initialization of rvalue references when specifying function signatures.
=> remove const from functions returning by value

modules/highgui/src/window_QT.cpp
=> highgui: Qt: waitKey() supports Cyrillic/Japanese keyboard layout

modules/objdetect/perf/perf_qrcode_pipeline.cpp, modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qrcode.cpp
=> Fix sampling for version multiplying factor

modules/videoio/src/cap_gstreamer.cpp
Some GStreamer elements may produce buffers with very non
standard strides, offsets and/or even transport each plane
in different, non-contiguous pointers. This non-standard
layout is communicated via GstVideoMeta structures attached
to the buffers. Given this, when a GstVideoMeta is available,
one should parse the layout from it instead of generating
a generic one from the caps.
The GstVideoFrame utility does precisely this: if the buffer
contains a video meta, it uses that to fill the format and
memory layout. If there is no meta available, the layout is
inferred from the caps.
=> Consider video meta on GStreamer video capture

apps/interactive-calibration/calibCommon.hpp, apps/interactive-calibration/calibController.cpp, apps/interactive-calibration/frameProcessor.cpp, apps/interactive-calibration/frameProcessor.hpp, apps/interactive-calibration/main.cpp, apps/interactive-calibration/parametersController.cpp
The option to save all frames that contribute to final calibration result.
Useful for dataset collection and further offline tuning.
=> Save Frames option for interactive calibration tool

apps/visualisation/opencv_visualisation.cpp
Problem: the `model_visualization.avi` with `XVID` codec did (silently) not work whereas `model_visualization.mp4` with `H264` does work.
Proposed solution: make the video codec configurable (defaulting to existing behaviour) and error-log-and-exit if the output video file could not be opened.
(The "happy fish" image does not have the 20x20 size of the "profile face" model but it seems nonetheless suitable for smoke test use.)
```
opencv_build/bin/opencv_visualisation \
--image=opencv/samples/data/HappyFish.jpg \
--model=opencv/data/haarcascades/haarcascade_profileface.xml \
--data=temp_data/ \
--ext=mp4 --fourcc=H264 --fps=42
```
=> apps/opencv_visualisation: configurable video codec

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/980
This PR will fix the issue #22015 
The essence of the issue is that the `Clip layer` is supposed to accept 1-3 inputs, but the implementation here  is based on `ReLU6`, which only supports attributes as parameters.
https://github.com/opencv/opencv/blob/b19683eb41f425ec436193bd90a27f7637b4e8e1/modules/dnn/src/onnx/onnx_importer.cpp#L1935
Solution: When parsing the `Clip layer`, the `min` and `max` obtained from `node_proto.input()`, instead of from `layerParams`, are passed as parameters to the `ReLU6`. This allows the `Clip layer` to support 1-3 inputs.
=> Fix issue 22015, let Clip layer support 1-3 inputs

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/983
backport of #22122
[Related Comment](https://github.com/opencv/opencv/pull/22122#issuecomment-1163025425)
=> bug fixed of GEMM node in ONNX_importer of 3.4 branch

modules/core/doc/intro.markdown
This markdown file corresponds to the first link on the landing page of the OpenCV documentation, e.g., the first link of https://docs.opencv.org/4.6.0/index.html that will take you here: https://docs.opencv.org/4.6.0/d1/dfb/intro.html
=> Fix minor errors in the first documentation page (Introduction)

apps/interactive-calibration/calibCommon.hpp, apps/interactive-calibration/calibPipeline.cpp, apps/interactive-calibration/frameProcessor.cpp, apps/interactive-calibration/frameProcessor.hpp, apps/interactive-calibration/main.cpp, apps/interactive-calibration/parametersController.cpp
Can be useful when the screen is smaller than the image from camera.
=> Add zoom factor to interactive calibration tool

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_ffmpeg_impl.hpp
Adds functionality to read the frame type for an ffmpeg VideoCapture via property syntax. The new property `CAP_PROP_FRAME_TYPE` is readonly. It returns the frame type ascii code of the most recently read frame (i.e. 73 = 'I', 80 = 'P', 66 = 'B' or 63 = '?' if unknown)
closes #21859 
=> Frame type property for ffmpeg video capture

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/int8layers/convolution_layer.cpp, modules/dnn/src/int8layers/fully_connected_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/layers_common.cpp, modules/dnn/src/layers/layers_common.hpp, modules/dnn/src/net.cpp, modules/dnn/src/net_impl.hpp, modules/dnn/src/net_quantization.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_int8_layers.cpp
Hi, the purpose of this PR is to add per-tensor quantization to the model quantization part of opencv dnn. 
[The difference of per-channel quantization and per-tensor quantization](https://www.tensorflow.org/lite/performance/quantization_spec).
The existing quantization method in opencv/dnn is based on **per-channel quantization**, which can achieve better accuracy than **per-tensor quantization**. But for some hardware, per-tensor quantization will be easier to optimize the speed, especially NPU chips.
For example, the [NPU of TIM-VX](https://github.com/VeriSilicon/TIM-VX) backend:
ResNet50 int8 (per-channel) takes **525.298 ms** on Khadas Vim3,
And ResNet50 int8 (per-tensor) takes **20.01 ms** on Khadas Vim3.
Compared with per-channel quantize, the per-tensor quantization has the …
=> Add per_tensor_quantize to int8 quantize

modules/imgproc/include/opencv2/imgproc.hpp
- [not applicable (documentation improvement)] There is a reference to the original bug report and related work
- [not applicable] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
=> Improve documentation of calcHist overload that accepts vectors

modules/dnn/src/layers/fast_convolution/fast_convolution.hpp, modules/dnn/src/layers/fast_convolution/fast_convolution.simd.hpp, modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp
This PR is compatible `fastConv` and `winogradConv` with ARMv7.
The previous #21910 PR only supported AARCH64 or ARMv8. And it has [bugs on ARMv7](https://github.com/opencv/opencv/pull/21910#issuecomment-1172772375)
as @asenyaev reported. 
closes #22188
=> DNN: ARMv7 compatible fastConv

modules/objdetect/test/test_precomp.hpp, modules/objdetect/test/test_qrcode_encode.cpp
`std::random_shuffle` with two arguments is deprecated since C++11 and removed since C++17. This PR adds conditional compilation directives to replace it with the recommended `std::shuffle` (together with manually-constructed RNGs) when C++11 is available in the test files for `objdetect` module.
Resolves #22209.
=> Replace `std::random_shuffle` with `std::shuffle` in tests for `objdetect`

modules/features2d/src/sift.simd.hpp
This PR fixes the warning during the compilation on Linux ARM64:
```
[1013/2494] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/sift.dispatch.cpp.o
In file included from /opencv/modules/features2d/src/sift.dispatch.cpp:76:
/opencv/modules/features2d/src/sift.simd.hpp: In function 'void cv::cpu_baseline::calcSIFTDescriptor(const cv::Mat&, cv::Point2f, float, float, int, int, cv::Mat&, int)':
/opencv/modules/features2d/src/sift.simd.hpp:832:5: warning: iteration 7 invokes undefined behavior [-Waggressive-loop-optimizations]
832 |     for( ; k < len; k++ )
|     ^~~
/opencv/modules/features2d/src/sift.simd.hpp:832:14: note: within this loop
832 |     for( ; k < len; k++ )
|            ~~^~~~~
```
Link to a pipeline: …
=> Pragma to ignore -Waggressive-loop-optimizations on Linux ARM64

modules/dnn/src/layers/scale_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
[Test Data](https://github.com/opencv/opencv_extra/pull/986).
Related https://github.com/opencv/opencv/issues/22195
In this PR, we fix `Scaler Layer` can not handle 1x1 weights correctly.
=> DNN: Bug fix 22195 in 3.4

modules/videoio/src/cap_dshow.cpp
Changing the condition so that `STRSAFE_NO_DEPRECATE` is defined for both gcc and clang when building with a mingw-w64 toolchain.
=> Define `STRSAFE_NO_DEPRECATE` for both clang and gcc mingw-w64

modules/highgui/src/window_cocoa.mm
Python binding is passing NULL as (int*)value.
sliderChanged crash when trying to dereference value
A user reported this issue to me on IRC and opened an issue in opencv-python
https://github.com/opencv/opencv-python/issues/691
I have a solution for the issue but I do not know which OpenCV branch I should target
=> correct an issue of trackbar on macOS

modules/dnn/src/tensorflow/tf_importer.cpp
Fixes #22221.
In this case, the `pack` operator stacks three 4-dimensional tensors into a 5-dimensional tensor. However, the data layout of the output of the `pack` operator is still recognized as 4-dimensional (`DATA_LAYOUT_NHWC`) in tf_importer, which will lead to some problems like #22221 . Changing the data layout to `DATA_LAYOUT_UNKNOWN` fixes the problem.
For testing, I doubt whether we should put the model in opencv_extra since it is ~432MB.
=> Changing data_layout for pack in tf_importer

apps/interactive-calibration/parametersController.cpp
Related: [PR](https://github.com/opencv/opencv/pull/22079)
`has()` always returns true
=> Fix save_frames parameter

doc/tutorials/introduction/config_reference/config_reference.markdown
The [4.6.0 docs](https://docs.opencv.org/4.6.0/db/d05/tutorial_config_reference.html) has a broken layout
The markdown is not interpreted as a table.
The section doesn't exists on 3.4 branch, so fixing on master.
=> doc: fix layout

.github/workflows/PR-3.4.yaml
Renaming in case of ubuntu 20.04 is in use ([dockerfile](https://github.com/opencv-infrastructure/opencv-gha-dockerfile/blob/main/ubuntu-github-actions-arm64--20.04/Dockerfile#L4)).
=> Linux ARM64 rename ubuntu version on 3.4

.github/workflows/PR-4.x.yaml
Renaming in case of ubuntu 20.04 is in use ([dockerfile](https://github.com/opencv-infrastructure/opencv-gha-dockerfile/blob/main/ubuntu-github-actions-arm64--20.04/Dockerfile#L4)).
=> Linux ARM64 rename ubuntu version on 4.x

.github/workflows/PR-5.x.yaml
Renaming in case of ubuntu 20.04 is in use ([dockerfile](https://github.com/opencv-infrastructure/opencv-gha-dockerfile/blob/main/ubuntu-github-actions-arm64--20.04/Dockerfile#L4)).
=> Linux ARM64 rename ubuntu version on 5.x

modules/python/package/cv2/__init__.py
This PR fixes an issue https://github.com/opencv/opencv-python/issues/689 as @impact27 suggested.
Python docs said ([link](https://docs.python.org/3/library/functions.html#locals)): 
> The contents of this dictionary should not be modified; changes may not affect the values of local and free variables used by the interpreter.
`ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions.`
=> Fixed an issue with a recursion of cv2 in python

modules/core/include/opencv2/core/hal/intrin.hpp, modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp, modules/core/test/test_intrin_utils.hpp
Related PR: #22278  
According to the build issues on [Win64](https://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/100064/steps/compile%20release/logs/warnings%20%28210%29) and [Win32](https://pullrequest.opencv.org/buildbot/builders/precommit_windows32/builds/100053/steps/compile%20release/logs/stdio), I have already modify the code. But since I do not have a device with Windows and MVCS 15, please let the build bot compile the code for further verification.
```
force_builders=Win64,win32,Custom Win
```
=> [GSoC] Fix compilation errors and warnings when using MSVC on Windows.

modules/imgproc/src/drawing.cpp
fixup #22153 
/cc @vpisarev @vrabaud 
> C:\build\3_4-win64-vc14\opencv\modules\imgproc\src\drawing.cpp(1491): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\build\3_4-win64-vc14\build\modules\imgproc\opencv_imgproc.vcxproj]
C:\build\3_4-win64-vc14\opencv\modules\imgproc\src\drawing.cpp(1492): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\build\3_4-win64-vc14\build\modules\imgproc\opencv_imgproc.vcxproj]
C:\build\3_4-win64-vc14\opencv\modules\imgproc\src\drawing.cpp(1507): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\build\3_4-win64-vc14\build\modules\imgproc\opencv_imgproc.vcxproj]
C:\build\3_4-win64-vc14\opencv\modules\imgproc\src\drawing.cpp(1508): warning …
=> imgproc: fixup leftovers of int->int64_t conversion

modules/core/src/buffer_area.cpp, modules/core/test/test_utils.cpp
resolves #22291
In some cases original pointers can go out of scope. We didn't really need to zero them.
I decided to leave `DbgAssert` for `ptr`, because it can _theoretically_ help to debug some issues.
=> core: remove unnecessary pointer cleanup in BufferArea

modules/core/misc/objc/common/Mat.mm, modules/core/misc/objc/test/MatTest.swift
Bug fix:
The original implementation of -[Mat initWithSize:type:] and -[Mat initWithSize:type:scalar] contained a bug where the dimensions were swapped round. This PR fixes this.
=> Fix bug in Objective-C/Swift [Mat initWithSize:**] functions

CMakeLists.txt, modules/videoio/CMakeLists.txt, modules/videoio/cmake/detect_obsensor.cmake, modules/videoio/cmake/init.cmake, modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_interface.hpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_interface.hpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.cpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.hpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_v4l2.cpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_v4l2.hpp, modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp, modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.hpp, modules/videoio/src/cap_obsensor_capture.cpp, modules/videoio/src/cap_obsensor_capture.hpp, modules/videoio/src/videoio_registry.cpp, samples/cpp/videocapture_obsensor.cpp
OBSensor is Orbbec's new generation RGB-D camera brand, based on UVC protocol. The purpose is to let OpenCV read RGB and depth data from Orbbec RGB-D Camera via UVC protocol, rather than relying on the 3rdparty library (like OpenNI). This will greatly facilitate users to directly read, use and process the depth camera in OpenCV.
Supported Orbbec Device
* Orbbec Astra+: [detail](https://orbbec3d.com/index/Product/info.html?cate=38&id=9)
* Depth Stream (640x480x30 fps CV_16UC1)
* RGB Stream (640x480x30fps BGR)
* Orbbec Femto: [detail](https://orbbec3d.com/index/Product/info.html?cate=38&id=18)
* Depth Stream (640x480x30 fps CV_16UC1)
* RGB Stream (640x480x30fps BGR)
* Orbbec future device:
* ...
Supported OS: Windows and Linux. (MacOX will be supported in near future.)
Supported HW: x86, …
=> videoio: add support for obsensor (Orbbec RGB-D Camera )

modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.cpp
#22312
`Shlwapi.lib`  have not be linked. 
Normally, it should be linked at `modules\videoio\src\cap_msmf.cpp`
=> fix linkage issue when enable BUILD_opencv_world (#22312)

platforms/android/build_sdk.py, platforms/ios/build_framework.py
This PR enables building dynamically linked opencv libs using python build scripts. Shared object for Android and framework for iOS. 
On Android building SO was already possible before this PR, now it is exposed in build_sdk.py as a command line parameter.
On iOS the option was already available as a command line argument, but was doing nothing for iOS simulator or device build. This PR enables that build providing it with the required dependencies.
=> dynamically linked libs on mobile

modules/videoio/src/cap_obsensor/obsensor_stream_channel_v4l2.cpp
libstdc++ that comes with gcc 4.8 doesn't
define `getline(basic_istream<char>&&, std::string&)`
even if it's part of the c++11 standard.
However we can still use the following:
`getline(basic_istream<char>&, std::string&)`.
=> Fix compilation error on CentOS 7 (gcc 4.8)

modules/core/src/system.cpp
This PR enables the use of `std::chrono::steady_clock` on supported compilers as a source to retrieve the current tick count and clock frequency in a cross-platform way.
Resolves #6902.
=> Use `std::chrono::steady_clock` in `getTickCount`

modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_int8_layers.cpp, modules/dnn/test/test_onnx_importer.cpp
| Time Summary In Debug Linux of DNN test |  |  |  |
| --------------------------------------- | -- | -- | -- |
| Chip                                    | Befor Path Debug Time | With Path Debug Time | Release Time |
| Apple M1 chip                           | 10.5 min | **6.2 min (41% reduction)** | 2 min |
| intel i7-12700K                         | 145 s | **78 s (46% reduction)** | 52 s |
More detailed Linux Debug time of test_dnn summary table can be found at this [sharing sheet](https://docs.google.com/spreadsheets/d/1VKKSTxEmYOWrlrjNVtltd90hii3VVttdsjmNhahITm0/edit?usp=sharing).
=> DNN: add more skip flag for very long test case in test_dnn.

modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.cpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_v4l2.cpp, modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.hpp
This PR fixes a build on Windows using Visual Studio 14 (it works with VS 16 somehow).
Relates to https://github.com/opencv/opencv/pull/22196
Pipelines before changes:
- [VS-16](https://github.com/asenyaev/ci-gha-workflow/runs/7642171973?check_suite_focus=true) :heavy_check_mark: 
- [VS-14](https://github.com/asenyaev/ci-gha-workflow/runs/7642171912?check_suite_focus=true#step:9:1202) :heavy_multiplication_x: 
Pipelines after changes:
- [VS-16](https://github.com/asenyaev/ci-gha-workflow/runs/7648667221?check_suite_focus=true) :heavy_check_mark: 
- [VS-14](https://github.com/asenyaev/ci-gha-workflow/runs/7648667116?check_suite_focus=true) :heavy_check_mark: 
Thanks @rogday for the help!
Patch …
=> Fix in obsensor for VS 14

modules/imgcodecs/src/grfmt_jpeg.cpp, modules/imgcodecs/src/grfmt_png.cpp
Releasing resources should be done in the destructor. The user might call this method more than once.
```cpp
auto res = decoder.readData(mat);
...
res = decoder.readData(mat);
```
This is not efficient but it is possible. In this case, behavior is undefined because of the `close()` call.
=> release png,jpeg resources in destructor

modules/dnn/src/onnx/onnx_graph_simplifier.cpp, modules/dnn/test/test_onnx_importer.cpp
| Test in YoloV4 with M1 chip |  |  |
| --------------------------- | -- | -- |
|                             | Befor Patch optimize | With Patch optimize |
| Time                        | 364 ms | **304 ms (17% faster)**  |
The Mish layer can be generated by two different implementations:
```py
x * (torch.tanh(F.softplus(x)))
x * (torch.tanh(torch.log(torch.exp(x) + 1)))
```
In order to make [YoloV4](https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/yolov4) run faster on OpenCV, Mish's graph fusion optimization is essential.
For now, the original [YoloV4 in ONNX's model_zoo](https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/yolov4) cannot be loaded correctly by OpenCV, because original YoloV4 has very complicated struct and the …
=> DNN: add another two Mish activation to onnx_graph_simplifier

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/int8layers/reduce_layer.cpp, modules/dnn/src/layers/reduce_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Related ReduceSum issue #22195 
Related Dynamic Batch of Reduce Layer issue #22086
In this PR, we supported two input of `ReduceSum layer` and dynamic batch size in `Reduce Layer` of `ONNX_importer.cpp`.
[Regression test](https://github.com/opencv/opencv_extra/pull/987).
The [pervious PR](https://github.com/opencv/opencv/pull/22140) on Dynamic Batch of Reduce Layer has been closed.
=> DNN: Reduce Layer (add dynamic batch and ReduceSum support) 

modules/imgproc/include/opencv2/imgproc.hpp
Resolve https://github.com/opencv/opencv/issues/22242
Replace https://github.com/opencv/opencv/pull/22256
---
Some imgproc functions actually work with `CV_32F / CV_64F` combination:
- `cv::boxFilter` (output depth can be explicitly specified)
- `cv::buildPyramid`
- `cv::Scharr` (output depth can be explicitly specified)
- `cv::sepFilter2D` (output depth can be explicitly specified)
- `cv::Sobel` (output depth can be explicitly specified)
- `cv::sqrBoxFilter` (output depth can be explicitly specified)
=> Fix documentation about depth combinations for imgproc functions

samples/python/stitching_detailed.py
if this is not done, adjusting will fail if there are some low confidence matches which are included by the user by lowering the conf_thresh parameter. 
see https://github.com/lukasalexanderweber/stitching/pull/19
=> Add confidence threshold to camera adjuster

modules/imgcodecs/misc/objc/ios/Mat+QuickLook.mm, modules/imgcodecs/misc/objc/macosx/Mat+QuickLook.mm
Bugfix (Objc Bindings):
For a Mat with 10 or less rows and 10 or less columns and more than one channel - Quicklook fails like this:
This PR fixes the problem by adding a check that the number of channels is 1 before trying to draw a matrix style Quicklook
=> Fix bug in ObjC/Swift Quicklook function

modules/gapi/cmake/DownloadADE.cmake
There was a number of issues fixed in ADE recently, mainly about new compiler support + various build options were added.
Bumping ADE in OpenCV resolves #21109 
=> G-API: Bump ADE to version 0.1.2

modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.hpp
```
This fixes the following error with mingw toolchain:
opencv/modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.hpp:160:10: error: 'condition_variable' in namespace 'std' does not name a type
160 |     std::condition_variable streamStateCv_;
|          ^~~~~~~~~~~~~~~~~~
```
relates #22196
=> videoio: Include missing condition_variable header

modules/videoio/src/cap_ffmpeg_hw.hpp, modules/videoio/src/cap_msmf.cpp
```
This fixes the following error with mingw toolchain:
opencv/modules/videoio/src/cap_msmf.cpp:1020: error: 'wstring_convert' is not a member of 'std'
1020 |                                     std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> conv;
|                                          ^~~~~~~~~~~~~~~
opencv/modules/videoio/src/cap_ffmpeg_hw.hpp:230:26: error: 'wstring_convert' is not a member of 'std'
230 |                     std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> conv;
|                          ^~~~~~~~~~~~~~~
The locale header is required according to C++ standard.
See https://en.cppreference.com/w/cpp/locale/wstring_convert
```
Patch to opencv_extra has the …
=> videoio: Include missing locale header for std::wstring_convert

modules/core/include/opencv2/core/hal/intrin.hpp, modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp, modules/core/test/test_intrin_utils.hpp
This is a patch of my GSoC project that the goal is to make the existing Universal Intrinsic compatible with scalable (variable-length) backends.
In #22179, we have already introduce a new framework of universal intrinsic for RISC-V Vector backend and few implementations and test cases are also added.
In this patch, we are going to add more universal intrinsic implementations for RVV.
Tested with QEMU for RVV backend in various VLEN:
```
qemu-riscv64 -cpu rv64,x-v=true,vlen=128 ./bin/opencv_test_core --gtest_filter="hal*"
qemu-riscv64 -cpu rv64,x-v=true,vlen=512 ./bin/opencv_test_core --gtest_filter="hal*"
```
Also tested for AVX and SSE backend on Linux.
Patch to opencv_extra has the same …
=> [GSoC] Add more universal intrinsic implementations for RVV.

modules/3d/src/levmarq.cpp
Fixes compilation warning caused by #22413 
=> LevMarq log level warning fix

modules/3d/include/opencv2/3d/depth.hpp, modules/3d/src/rgbd/depth_to_3d.cpp, modules/3d/src/rgbd/normal.cpp, modules/3d/test/test_normal.cpp, modules/3d/test/test_odometry.cpp
* Tests for normals changes:
- Random plane generation fixed (maxDepth issue, rendering issue, 32F to 16U transformation issue)
- Different scale issue fixed, checked for all normal computers and all output data types
- Rendered normals test added: calculated normals are compared to pre-rendered ones
- RNG fixed to follow TS's RNG
- Rewritten to parametric GTest
* Tests for plane detector rewritten to parametric GTest
* Several fixes to normal computers:
- no `setMethod`: use `create` static method instead
- depth difference threshold for LINEMOD algorithm has been put into interface
* Fix for `depthTo3d` function for dense case with mask, test added
* `CrossProduct` - a new normal computer implementing the most naive way to calculate normals on a depth image, performing no filtering or …
=> More tests for normals

3rdparty/carotene/CMakeLists.txt, 3rdparty/carotene/src/add_weighted.cpp
This PR suppress warnings in 3rdparty carotene. Examples ([link](https://github.com/opencv/ci-gha-workflow/runs/7948765106?check_suite_focus=true#step:12:474)):
```
[459/1823] Building CXX object 3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/src/add_weighted.cpp.o
/Users/opencv-cn/GHA-OCV-3/_work/ci-gha-workflow/ci-gha-workflow/opencv/3rdparty/carotene/src/add_weighted.cpp:112:28: warning: 'typename' occurs outside of a template [-Wc++11-extensions]
void operator() (const typename VecTraits<s32>::vec128 & v_src0,
^~~~~~~~~
...
[473/1823] Building CXX object 3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/src/div.cpp.o
/Users/opencv-cn/GHA-OCV-3/_work/ci-gha-workflow/ci-gha-workflow/opencv/3rdparty/carotene/src/div.cpp:93:19: warning: unused function …
```
=> Suppress warnings in carotene on macOS ARM64 for 3.4 branch

modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/test/test_ffmpeg.cpp
This PR should fix https://github.com/opencv/opencv/issues/21101 in most cases by returning a valid fourcc from `CvCapture_FFMPEG::getProperty(CAP_PROP_FOURCC)` when `codec_tag==0` and `_opencv_avcodec_get_name(codec_id)` is invalid.  Previously as noted in the issue `getProperty` would have returned 0.
In addition to the description in https://github.com/opencv/opencv/issues/21101, it appears that the value of `video_st->CV_FFMPEG_CODEC_FIELD->codec_tag` depends on the video file itself and not just the codec used.  That is some vp9 video's will have a valid codec_tag and some will have zero.    As a result all of the test cases apart from "../cv/tracking/faceocc2/data/faceocc2.webm" would have worked before this change and are included to verify that the previous functionality still …
=> Fix video codec fourcc #21101

modules/videoio/src/cap_msmf.cpp
There may be more than one streams in some camera device (for example RealSense D405)
some streaming setting may be not regular visualable image.
But, in MSMF backend, by default, regular visualable image is require.
This patch will skip some streaming base on the format.
=> select correct MediaType in MSMF backend.

modules/videoio/src/cap_v4l.cpp
Devices which only support multi-planar capture cannot be processed as
single-planar.
Add multi-planar support to v4l driver.
=> V4L2: Add multi-planar capture support

doc/tutorials/features2d/homography/homography.markdown
An idea I had.
Propose a small exercise to show the different homography transformations operating step-by-step. This should allow the user to learn, exercise the following topics:
- homogeneous transformations,
- rotation interpolation (and maybe SLERP, LERP, ... if using quaternion?),
- homography transformation from camera displacement
---
There is a dedicated YouTube channel for OpenCV tutorials: https://www.youtube.com/user/OpenCVTutorials
Would be great if you could add the following video on this channel:
https://user-images.githubusercontent.com/8229425/174500387-36882645-06ee-4aac-b0e4-3f3111e9d3be.mp4
Title of the video:
> OpenCV homography tutorial - Demo 3: Homography from the camera displacement
And with the following description:
> This video illustrates the following OpenCV …
=>  Update homography tutorial with a small exercise

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/dnn_common.hpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.avx2.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.hpp, modules/dnn/src/layers/fast_convolution/fast_convolution.simd.hpp, modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp, modules/dnn/src/net_impl_fuse.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_int8_layers.cpp, modules/dnn/test/test_torch_importer.cpp
1. Bring and adapt the latest the [Ficus OpConv.fx](https://github.com/vpisarev/ficus/blob/master/lib/NN/OpConv.fx) code.
2. Fused Conv+Add+Activation. (Currently only for Conv2D, in the future FastConv can support Conv1D and Conv3D, we will also support both.)
3. FastConv branch still reuses the `weightsMat`, and remove the `fastWeights`.
4. Optimize the `Winograd_F63`: pack tile 12 and adjust the data pipeline. (About 1 ms speedup on M1 chip, testing model: ResNet50).
TODO List:
- ~~Find out why MobileNetv2 is slow.~~ It is caused by the difference between OpenMP and GCD.
| Model Name | Wthout Patch | With Patch |
|:-------:|:--------:|:------------:|
| ReseNet 50 | 26.8 ms | **24.6 ms** |
| MobileNetv2| 5.43 ms | GCD: 5.5 ms, OpenMP: 4.7 ms |
| Model Name | Without Patch | With Patch | …
=> DNN: Further optimization of Conv2D

modules/gapi/cmake/DownloadADE.cmake
=> G-API: Update ADE to v0.1.2a to fix new Windows warnings

modules/dnn/src/onnx/onnx_graph_simplifier.cpp, modules/dnn/test/test_onnx_importer.cpp
[Related extra data](https://github.com/opencv/opencv_extra/pull/993)
[Download link](https://github.com/zihaomu/zihaomu/files/9393786/mobilenetv2_fp16_v7.tar.gz)
The FP16 model is half the size of the FP32 model, which will be edge device friendly.
Currently, OpenCV `ONNX_importer` cannot load FP16 models correctly and DNN also doesn't have full FP16 backend support.
So, my idea is that in the first step we make OpenCV DNN load FP16 ONNX model as FP32 model, and every layer will be computed as FP32.
Here is a [FP16 text recognition model(CRNN)](https://github.com/opencv/opencv_zoo/pull/79) which was converted by my GSoC student Yiyao @Charles-258, and we found it even has better accuracy performance than the original FP32 model.
And I have tested these FP16 CRNN models in the existing …
=> DNN: load fp16 ONNX model as fp32

modules/objdetect/test/test_qrcode.cpp
Fixes [different behavior](https://github.com/opencv/ci-gha-workflow/runs/7898518988?check_suite_focus=true#step:35:283) (arm vs x86) in `close_1.png`
There is problem in `resize()` with INTER_LINEAR interpolation. There is INTER_LINEAR_EXACT interpolation to fix this. This fix breaks test with close_5.png image.
QR code in close_5.png is big and has alignment pattern, objdetect works bad with these QR codes. Different interpolation flag breaks detection.
=> QR code, change resize interpolation for Arm

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/src/tengine4dnn/include/tengine_graph_convolution.hpp, modules/dnn/src/tengine4dnn/src/tengine_graph_convolution.cpp
In https://github.com/opencv/opencv/pull/21910, fast convolution is introduced with support for asymmetric padding in calculation. So there is no need to keep a separate padding layer for asymmetric padding in convolution layer.
https://github.com/opencv/opencv/blob/d09cc0f30c708ca06ad1a05f5b39f6368d986fad/modules/dnn/test/test_onnx_importer.cpp#L118-L122
OpenVINO, Default CPU (CPU, OCL, Tengine), Vulkan, CUDA, WebNN are registered for this test.
=> Remove asymmetric padding in Conv layer since it is supported in CPU backend

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
[Squeeze node of ONNX](https://github.com/onnx/onnx/blob/main/docs/Operators.md#squeeze) has moved the axes from attribute to input.
[Test Data](https://github.com/opencv/opencv_extra/pull/989)
=> DNN: Add qgemm and squeeze op13 supported on ONNXImporter

modules/dnn/src/layers/fast_convolution/fast_convolution.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.simd.hpp
We have a bug using `v_add` of Universal intrinsics, and in this PR, we replace `v_add` with `+`.
[Related comment](https://github.com/opencv/opencv/pull/22401#issuecomment-1229880932)
=> DNN: replace v_add with plus

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/hough.cpp, modules/imgproc/test/test_houghlines.cpp
This aims to fix the bug that occurs in Hough transform (e.g., HoughLines) when 1) The user-supplied `max_theta` parameter is equal to or barely larger than the true value of theta, 2) The `threshold` parameter is not very small, and 3) `min_theta` and `theta` parameters are chosen such that `cvRound` in the existing code rounds its argument down.
The bug was discovered in https://github.com/opencv/opencv/issues/21983
Here is an ad hoc test that illustrates the modification:
```cpp
#include <iomanip>
#include <opencv2/core.hpp>
int main() {
double min_theta = 0.0;
double max_theta = 1.0;
double delta_thetas[] = {
0.01,
0.0999, 0.1, 0.1001,
0.15,
0.666, 0.667,
0.9,
};
std::cout << std::setprecision(4) << std::fixed;
std::cout << "min_theta=" << min_theta << ", …
```
=> Fix angle discretization in Hough transforms

modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp, modules/core/test/test_intrin_utils.hpp
This is a patch of my GSoC project that the goal is to make the existing Universal Intrinsic compatible with scalable (variable-length) backends.
In #22179 and #22353, we have already introduce a new framework of universal intrinsic and some of intrinsic functions are added.
In this patch, we are going to add the remaining universal intrinsic implementations for RVV. When this patch is integrated, the new RVV backend will be done.
Tested with QEMU for RVV backend in various VLEN:
```
qemu-riscv64 -cpu rv64,x-v=true,vlen=128 ./bin/opencv_test_core --gtest_filter="hal*"
qemu-riscv64 -cpu rv64,x-v=true,vlen=512 ./bin/opencv_test_core --gtest_filter="hal*"
```
Patch to opencv_extra has the same …
=> [GSoC] Add remaining universal intrinsic implementations for RVV.

modules/dnn/src/layers/fast_convolution/fast_convolution.hpp
Fixes #22450
Relates #22401
```
force_builders=Linux32,Win32
```
=> DNN: Try to be compatible with win32

modules/calib/src/calibration.cpp, modules/calib/test/test_cameracalibration.cpp
Fixes #22421
Connected test data PR: [#1003@extra](https://github.com/opencv/opencv_extra/pull/1003)
* Stereo Calibration is fixed for cases when intrinsic camera matrices are provided by user and don't have to be recomputed
* Erroneous variable initialization removed, see [this commit](https://github.com/opencv/opencv/pull/22460/commits/96e2d326185fd1639238c8158ff9daf10d25c712)
* Regression test for the case
* Less address arithmetics, making valgrind happy
* Fix for `CALIB_SAME_FOCAL_LENGTH` flag:
* Volatile variable (i.e. that is changed by the callback) made mask-fixed as it should be
* See [this commit](https://github.com/opencv/opencv/pull/22460/commits/a8b4ffac50b195670fef2c0017a36b38d223ad81)
* Other `stereoCalibrateImpl()` refactoring changes
* Implement SE(3) exponential …
=> Stereo calibration fixed when intrinsic guess is given

modules/gapi/CMakeLists.txt, modules/gapi/src/compiler/gcompiled.cpp, modules/gapi/src/compiler/gcompiled_priv.hpp, modules/gapi/src/compiler/gstreaming.cpp, modules/gapi/src/compiler/gstreaming_priv.hpp, modules/gapi/src/executor/gabstractexecutor.cpp, modules/gapi/src/executor/gabstractexecutor.hpp, modules/gapi/src/executor/gabstractstreamingexecutor.cpp, modules/gapi/src/executor/gabstractstreamingexecutor.hpp, modules/gapi/src/executor/gexecutor.cpp, modules/gapi/src/executor/gexecutor.hpp, modules/gapi/src/executor/gstreamingexecutor.cpp, modules/gapi/src/executor/gstreamingexecutor.hpp
The classes are `GAbstractExecutor` and `GAbstractStreamingExecutor`, respectively.
The idea behind this simple refactoring is to introduce other execution policies (implemented by executors) in the near future.
Note: this PR replaces obsolete #21762 and #21816 -- which now can be closed.
=> G-API: Introduce abstract base classes for GExecutor and GStreamingExecutor

modules/gapi/include/opencv2/gapi/python/python.hpp, modules/gapi/misc/python/pyopencv_gapi.hpp, modules/gapi/misc/python/test/test_gapi_sample_pipelines.py, modules/gapi/misc/python/test/test_gapi_stateful_kernel.py, modules/gapi/src/backends/python/gpythonbackend.cpp
**Please review both interface design and code.** :slightly_smiling_face: 
Stateful kernel in C++ is really useful to many usecases like tracking.
This PR will enable python G-API users to use stateful kernel and expand the usecases in python G-API.
[Here](https://github.com/xiong-jie-y/g_api_examples/tree/main/tracking_example) is the example video and the example code of this feature.
The example kernel is like this.
```python
class State:
def __init__(self, tracker, initial_box):
self.tracker = tracker
self.initial_box = initial_box
@cv.gapi.kernel(Tracker)
class TrackerImpl:
@staticmethod
def setup(input_image_desc, box):
tracker = cv.TrackerKCF_create()
return State(tracker, None)
@staticmethod
def run(image, box, state):
if state.initial_box is None:
state.tracker.init(image, box) …
```
=> Add stateful kernel to python G-API

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/test/test_ffmpeg.cpp
When using `VideoCapture` with the FFMpeg backend to stream from an RTSP source at a low frame rate on a machine with a large number of CPU cores, `VideoCapture::read/grab` can fail due to the interrupt timer exceeding `timeout_after_ms`.  To try and fix this, this PR adds the `CAP_PROP_N_THREADS` which can be set on open to reduce the number of threads in this case.  This is related to https://github.com/opencv/opencv/issues/20002 but I cannot tell if it fixes the issue as I am unable to re-create it on a machine with reading from a file with only 20 CPU cores.
In addition to this `VideoCapture::open` can get stuck and therefore interupted on the call to `err = avformat_find_stream_info(ic, NULL);` when streaming from an RTSP source at a low frame rate regardless of the number of CPU …
=> VideoCapture FFMpeg RTSP low fps fixes

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
Fixes #21290 
opencv_extra: https://github.com/opencv/opencv_extra/pull/1004
Original issue:
https://github.com/opencv/opencv/issues/21290
Found out, why my tf models wasn't supported by latest version of OpenCV. The problem was, that in graph layers with their id's were looking like:
0: input
1: reshape
2: conv
But while building graph in OpenCV it was looking like:
0: input
1: reshape//nhwc
2: reshape
3: reshape/nchw
4: conv
The problem is while getting memory shapes and connecting nodes with each other, the algorithm is connecting them by names, so the chain of layers ids was not: 0 -> 1 -> 2 -> 3 -> 4, but 0 -> 1 -> 2 -> 4.
There's 2 ways of solving this issue:
1. Place the original name as the latest in this permutation chain, which may …
=> changed names of permutations if Reshpe is in NHWC

3rdparty/ffmpeg/ffmpeg.cmake, modules/videoio/test/test_ffmpeg.cpp, modules/videoio/test/test_video_io.cpp
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/73
- FFmpeg 4.4.2
- added AV1 support through aom 3.4.0: https://aomedia.googlesource.com/aom/+/refs/tags/v3.4.0
resolves #11389
previous update: https://github.com/opencv/opencv/pull/22034
```
```
=> ffmpeg/4.x: update FFmpeg wrapper 2022.09

modules/videoio/src/cap_android_mediandk.cpp
Android back-end for VideoCapture from video files improvements:
* after the open the following informations are available: width, height, fps, orientation (if built with API level >= 28), frame count (if built with API level >= 29)
* add support for CAP_PROP_ORIENTATION_AUTO (if built with API level >= 28)
* decode using video height and not the height aligned for the encode (ex: 1080 instead of 1088)
- [ x ] I agree to contribute to the project under Apache 2 License.
- [ x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ x ] The PR is proposed to the proper branch
- [ x ] There is a reference to the …
=> Fix issues: #22214 and #22198

modules/videoio/include/opencv2/videoio.hpp
This pull request removes a reference to a link that appears to be broken. Instead of being useful, it directs the user to some casino site. I guess that the domain owner has changed and this link should be replaced or removed entirely. I don't know what to replace it with, so I suggest removing it for now.
PS: I did not see anything in your contribution guidelines about fixing errors in the docs, so I did this. My apologies if this was the wrong place to notify you.
=> Removes a broken link

modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/test/test_video_io.cpp
resolves #22141
- [ x ] I agree to contribute to the project under Apache 2 License.
- [ x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ x ] The PR is proposed to the proper branch
- [ x ] There is a reference to the original bug report and related work
- [  ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ x ] The feature is well documented and sample code can be built with the project CMake
=> Fixed  time value obtained on some frames at the end of the video #22141

modules/3d/src/levmarq.cpp, modules/calib/src/calibration.cpp
* `initIntrinsicParams2d()`
* `calibrateCameraInternal`
* `stereoCalibrateImpl`
* `collectCalibrationData`
* `calibrateCameraRO`
* `LevMarq::optimize()`: a comment explaining the code
* Less C-style pointer expressions in calibration code
* Less non-owning memory variables
* Calibration refinement callback is a lambda now
* Jacobians are borrowed from pre-allocated buffer, not allocated at each callback call
* Index arithmetics made cleaner
* fix TODOs in code
* get rid of memcpy
=> Calibration internals refactored

modules/videoio/src/cap_android_camera.cpp
Bugfix / Android:
On certain models (for example the OneNote 8T) **grabFrame** fails to obtain frame data even after an **onCaptureComplete** callback has been received. This PR fixes this problem by polling for frame data until we get a frame or we exceed a timeout of 2 second.
=> Poll for frame data if acquisition fails after OnCaptureCompleted

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Fixes #22215 .
Test data: https://github.com/opencv/opencv_extra/pull/998
Link to the model: https://drive.google.com/u/0/uc?id=1rm3mIqjJNu0xPTCjMKnXccspazV1B2zv&export=download
Things have to be done for the support:
```
```
=> Support for YOLOv7 ONNX (not simplified)

modules/dnn/include/opencv2/dnn/shape_utils.hpp, modules/dnn/src/layers/normalize_bbox_layer.cpp
Make GCC 12 happy:
```
In file included from /usr/include/c++/12/x86_64-redhat-linux/bits/c++allocator.h:33,
from /usr/include/c++/12/bits/allocator.h:46,
from /usr/include/c++/12/string:41,
from /home/alalek/projects/opencv/dev/modules/core/include/opencv2/core/cvstd.hpp:56,
from /home/alalek/projects/opencv/dev/modules/core/include/opencv2/core/base.hpp:58,
from /home/alalek/projects/opencv/dev/modules/core/include/opencv2/core.hpp:53,
from /home/alalek/projects/opencv/dev/modules/dnn/src/layers/../precomp.hpp:42,
from /home/alalek/projects/opencv/dev/modules/dnn/src/layers/normalize_bbox_layer.cpp:43:
In member function ‘void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = int]’,
inlined from ‘static void std::allocator_traits<std::allocator<_CharT> …
```
=> dnn: eliminate GCC12 warning in total() call

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/calibration.cpp, modules/calib3d/src/fisheye.cpp, modules/calib3d/test/test_cameracalibration.cpp, modules/calib3d/test/test_fisheye.cpp
Extension of stereoCalibrate function for both, pinhole and fisheye model, to return the translation and rotation vectors between each calibration object and the coordinate system of the first camera of the stereo pair. This feature is helpful to evaluate the individual image pairs used for calibration. This feature is in particular interesting for the fisheye model since its stereoCalibrate function has not provided a parameter to obtain the reprojection errors per stereo image pair. With these per-view transformations available, it is now possible to calculate these reprojection errors. In addition, for the pinhole model, it is also interesting to not only get the per-view rms errors, but also statistics within one view.
For the implementation, the single camera calibration methods were …
=> Stereo Calibration: Return rotation and transformation vectors for each calibration object

modules/core/include/opencv2/core/hal/intrin.hpp, modules/imgproc/src/sumpixels.avx512_skx.hpp
Warnings looks like:
```
In function ‘__m512i _mm512_cvtepi16_epi32(__m256i)’,
inlined from ‘void cv::hal_AVX512_SKX::v_expand(const v_int16x32&, v_int32x16&, v_int32x16&)’ at /home/alalek/projects/opencv/dev/modules/core/include/opencv2/core/hal/intrin_avx512.hpp:2028:1,
inlined from ‘bool cv::hal::opt_AVX512_SKX::{anonymous}::Integral_SIMD<unsigned char, double, double>::operator()(const uchar*, size_t, double*, size_t, double*, size_t, double*, size_t, int, int, int) const’ at /home/alalek/projects/opencv/dev/modules/imgproc/src/sumpixels.simd.hpp:854:29:
/usr/lib/gcc/x86_64-redhat-linux/12/include/avx512fintrin.h:2243:52: warning: ‘__Y’ may be used uninitialized [-Wmaybe-uninitialized]
2243 |   return (__m512i) __builtin_ia32_pmovsxwd512_mask ((__v16hi) __A,
| …
```
=> build: eliminate uninitialized warnings from GCC12

.github/workflows/arm64-build-checks.yml, .github/workflows/lint_python.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

3rdparty/openexr/CMakeLists.txt, cmake/OpenCVCompilerOptions.cmake, modules/core/include/opencv2/core/cuda.hpp, modules/core/include/opencv2/core/cuda.inl.hpp, modules/core/include/opencv2/core/matx.hpp, modules/core/include/opencv2/core/opengl.hpp, modules/core/include/opencv2/core/utils/filesystem.private.hpp, modules/features2d/src/affine_feature.cpp, modules/stitching/include/opencv2/stitching/detail/warpers.hpp
=> Disabled compiling warnings in case of symbols in cmake for 3.4

platforms/linux/riscv64-gcc.toolchain.cmake
from https://github.com/riscv-collab/riscv-gnu-toolchain, default install path is `/opt/riscv` and they recommend add it to the PATH variable.
=> Detect RISC-V compiler from PATH environment variable

modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp, modules/core/test/test_intrin_utils.hpp
The original signmask implementation returned incorrect results in some cases (e.g. new test cases, 242 is returned but 2 is expected).
This is due to [Vector Tail Agnostic](https://github.com/riscv/riscv-v-spec/blob/b6368b3c44d775f8eb01c7ce0ad017db19944aa7/v-spec.adoc#343-vector-tail-agnostic-and-vector-mask-agnostic-vta-and-vma) in RVV, and this patch solves the problem by using "bitwise AND" to mask high bit.
=> Fix v_signmask for RISC-V Vector

modules/imgcodecs/src/grfmt_webp.cpp
Relates to https://github.com/opencv/opencv/issues/22569
=> Report that animated webp is not supported for now

platforms/linux/riscv64-clang.toolchain.cmake, platforms/linux/riscv64-gcc.toolchain.cmake
- uppercase paths should be avoided
- align with defaults from https://github.com/riscv-collab/riscv-gnu-toolchain
relates #18228
/cc @dkurt (#22547)
=> riscv: use /opt/riscv path in toolchain

modules/calib3d/include/opencv2/calib3d.hpp, modules/imgproc/include/opencv2/imgproc.hpp
---
About the `Q` matrix: https://github.com/opencv/opencv/blob/a682f02f595ae90e58fdfaeeeb4c6d99d9aecdd1/modules/calib3d/src/calibration.cpp#L2755-L2762
Add also references to related functions since in my opinion it is preferable to have html links for related functions.
---
To be ported to the `4.x` branch.
I can open a dedicated pull request if it is preferable, just tell me.
=> [3.4] Add information about the disparity-to-depth mapping matrix

modules/gapi/samples/pipeline_modeling_tool.cpp, modules/gapi/samples/pipeline_modeling_tool/utils.hpp
The motivation of this PR is the following:
1. Some NN models might require individual `config`
2. Specifying `config` in `.yml` config file once is more convenient if it isn't supposed to be changed according user scenario.
The logic is following: 
- User can specify configuration parameters for every `Infer` node locally via `.yml` config file. 
- `local` config might be combined with `global` (in case it's specified via `--load_config`) until they have key conflicts.
- In case "key conflict" app reports the problem and crash.
```
```
=> [G-API] Pipeline modeling tool - support local infer node config

3rdparty/libjpeg-turbo/CMakeLists.txt
Use global OpenCV settings for MS Visual Studio run-time libraries to prevent collision:
```
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\build\precommit_windows64\build\modules\imgcodecs\opencv_imgcodecs.vcxproj]
```
The regression was introduced in https://github.com/opencv/opencv/pull/22372
=> Fix multiple sdtlib linkage warning on Windows with MSVS.

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/perf/perf_blur.cpp, modules/imgproc/src/stackblur.cpp, modules/imgproc/test/test_stackblur.cpp
Hi, the basic idea is blurring input images through one-dimension blur in the horizontal and the vertical respectively. StackBlur can blur the image in linear time. In theory, stackblur should run at the same speed as BoxBlur, and stackblur can eliminate the boxed-feeling of Boxblur in a large kernel size, and achieve the same effect as Gaussian blur.
Stack Blur was invented by Mario Klingemann <mario@quasimondo.com>.
Details description can be found at: http://underdestruction.com/2004/02/25/stackblur-2004
HW/SW:
Apple M1 chip / MacOS
The testing image size: [1920 x 2048], Input format: CV_8UC3.
**Test the rule**, run 1000 times to pick the value with the lowest speed.
The source log of the image and some test script can be found [this google …
=> Add StackBlur for imgproc

modules/imgcodecs/src/loadsave.cpp
I have noticed some warnings during the Windows build. That patch fixes that warnings such as unreachable code and unusued variable.
=> fix warnings in ImageCollection

modules/stitching/include/opencv2/stitching/detail/matchers.hpp, modules/stitching/src/matchers.cpp
Replacement for https://github.com/opencv/opencv/pull/19955/
=> Extracted matches_confindece_thresh as stitching matcher parameter.

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml
This pull request enables template chooser with templates for bug report and feature request. See my fork for the effect: https://github.com/fengyuentau/opencv/issues/new/choose. Note these changes only take effect if they are put in the default branch.
Github documentation for configuring issue templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
=> Enable issue template chooser

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/1008
This PR try to fix #22355.
ONNX operator doc: https://github.com/onnx/onnx/blob/main/docs/Operators.md#Slice
TODO:
=> DNN: Let Slice layer support non-sequential and negative axes

modules/gapi/include/opencv2/gapi/infer/ie.hpp, modules/gapi/samples/pipeline_modeling_tool.cpp, modules/gapi/samples/pipeline_modeling_tool/pipeline_builder.hpp, modules/gapi/src/backends/ie/giebackend.cpp, modules/gapi/test/infer/gapi_infer_ie_test.cpp
This `cfgOutputPrecision` handle is partially introduced/discussed there: https://github.com/opencv/opencv/issues/22522
=> G-API: API for configuring model output precision for IE backend

modules/imgcodecs/src/grfmt_tiff.cpp, modules/imgcodecs/test/test_tiff.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1006
fix #22388 
https://github.com/opencv/opencv/issues/22388
=> imgcodecs: tiff: Reduce memory usage to read 16bit image.

modules/gapi/CMakeLists.txt, modules/gapi/include/opencv2/gapi/infer/bindings_onnx.hpp, modules/gapi/include/opencv2/gapi/infer/onnx.hpp, modules/gapi/misc/python/pyopencv_gapi.hpp, modules/gapi/misc/python/shadow_gapi.hpp, modules/gapi/misc/python/test/test_gapi_infer_onnx.py, modules/gapi/src/backends/onnx/bindings_onnx.cpp, modules/gapi/src/backends/onnx/gonnxbackend.cpp
I think that the feature to run modle on onnxruntime is worth exposing to python G-API considering that
* Onnxruntime supports many ML runtimes
* Onnxruntime itself is very easy to install
This PR is the first step to expose onnxruntime features to python and support of execution providers will follow later.
This PR is draft, so let's have a discussion if necessary :slightly_smiling_face: 
-  [x] Adding python unit test for onnx runtime
-  [x] Create the same preprocess as openvino one to be able to accept the input with same shape as openvino. Currently transposing and reshaping is necessary like [this](https://github.com/xiong-jie-y/g_api_examples/blob/main/low_light_enhancement_onnx/enhance_low_light.py#L25-L26) in the user code.
-> I will not implement this because it seems that the …
=> Add python bindings for G-API onnx

modules/gapi/include/opencv2/gapi/infer/ie.hpp, modules/gapi/samples/pipeline_modeling_tool.cpp, modules/gapi/samples/pipeline_modeling_tool/pipeline_builder.hpp, modules/gapi/src/backends/ie/giebackend.cpp, modules/gapi/test/infer/gapi_infer_ie_test.cpp
The implementation is straight forward: replace `IE::InferRequest` to `IInferExecutor` which encapsulates how execution should be started (`Infer()`/`StartAsync`). Every kind of `IInferExecutor` must notify `RequestPool` when execution finishes by using by using callback that was passed while instantiation (see `m_notify()`) it helps `RequestPool` to understand which requests are working and which are idle.
=> G-API: Add synchronous execution for IE backend

modules/imgproc/src/imgwarp.cpp
The old version of IPP warpaffine can't work(can't pass build) which was controlled by flag `IPP_DISABLE_WARPAFFINE`. 
This pull request provides IPPIW warpaffine version controlled by flag `HAVE_IPP_IW `, and check ipp NE flag for the different result issue between OpenCV and IPP. 
Tested 100 images with src size is 1920x1080, data type is CV_8UC3, ROI is the whole image:
[
](url)
code snippet as following:
~~~
const int bordertype = cv::BORDER_CONSTANT;
int interpolation = cv::INTER_LINEAR; 
double angle = 30;                    
vector<cv::Mat> srcData;
for (auto imgpath : sInputFiles)
{
Mat img = cv::imread(imgpath, cv::IMREAD_COLOR);
cv::Size dsize(1920, 1080);
Mat img_resized;
cv::resize(img, img_resized, dsize, 0, 0, cv::INTER_CUBIC);
srcData.push_back(img);
}
vector<cv::Mat> …
=> Add warpAffine IPPIW implementation to replace with old version

cmake/OpenCVCompilerOptimizations.cmake
- PCH may not pass compilation flags properly
to complete #22527
```
force_builders=Win64,Linux Debug
```
=> cmake(opt): force separate targets for dispatched code

modules/calib3d/include/opencv2/calib3d.hpp
Fixes #22563
It was incorrectly stated that Jacobian should be calculated for error function (which is always L2).
In fact it should be calculated for data function.
=> Doc fix for LMSolver

modules/photo/include/opencv2/photo/cuda.hpp, modules/python/test/test_cuda.py
Python bindings were missing from the CUDA photo denoising functions.  The function signatures have been updated and python test added to verify their existence.
Are these supposed to be in the main repository?
=> Add bindings to CUDA photo denoising functions

modules/stitching/include/opencv2/stitching/detail/matchers.hpp, modules/stitching/include/opencv2/stitching/detail/seam_finders.hpp, modules/stitching/misc/python/test/test_stitching.py, modules/stitching/src/matchers.cpp, modules/stitching/test/test_matchers.cpp
This PR fixes two small issues in the header files for the stitching code, fixing two issues in Python and one minor one in the sample C++ code `stitching_detailed.cpp`.
1. changes to `BestOf2NearestRangeMatcher` fixing https://github.com/opencv/opencv/issues/22315
1. operator (called `apply2` in Python) now has `CV_WRAP_AS` and `CV_OUT` to work correctly in Python
2. the base class `FeaturesMatcher` version of this function is marked as `virtual` fixing a bug in `stitching_detailed.cpp` where the `--rangewidth` argument did not do anything, and `BestOf2NearestRangeMatcher`'s version is marked as `CV_OVERRIDE` correspondingly
3. The `GraphCutSeamFinder` masks argument is now correctly marked as `CV_IN_OUT` fixing https://github.com/opencv/opencv/issues/20945
I ran `opencv_test_stitching` …
=> Fix stitching Python bindings (and one stitching_detailed.cpp bug)

modules/objdetect/include/opencv2/objdetect.hpp, modules/objdetect/misc/python/test/test_peopledetect.py
resolves https://github.com/opencv/opencv/issues/22129
=> HOGDescriptor

modules/js/src/helpers.js
On **opencv.js**, `cv.imread` on a canvas element first gets the 2d context by `getContext('2d')`.
This produces the warning on Chrome (and other webkit browsers):
```
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true.
See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
```
The link: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
The correct syntax: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#syntax
The compatibility: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#browser_compatibility
In this PR i added the `willReadFrequently` attribute and checked on Chrome (compatible), …
=> Opencv.js: on imread add willReadFrequently to getContext

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/int8layers/convolution_layer.cpp, modules/dnn/src/int8layers/layers_common.hpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.hpp, modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp, modules/dnn/src/layers/layers_common.cpp, modules/dnn/src/layers/layers_common.hpp, modules/dnn/src/net.cpp, modules/dnn/src/net_impl.cpp, modules/dnn/src/net_impl.hpp, modules/dnn/src/net_quantization.cpp, modules/dnn/test/test_torch_importer.cpp
Two task in the PR:
1. add `enableWinograd` API for Net
2. disable Winograd branch in try quantize func.
Winograd Convolution will effect the accuracy, which may lead to more errors in the calibration process of DNN on-fly-quantize (`net.quantize()`). This PR wants to disable the Winograd branch in convolution computation.
=> DNN: add enableWinograd API for Net

modules/calib3d/include/opencv2/calib3d.hpp
relates #22572 (https://github.com/opencv/opencv/pull/22572#discussion_r990702936)
- avoid `@ref`
- align with 4.x branch (minimize merge conflicts)
<cut/>
---
Extra minor documentation changes example (added `title=`):
```.diff
-<p>The function is based on <a class="el" href="../../d9/d0c/group__calib3d.html#ga1aaacb6224ec7b99d34866f8f9baac83">RQDecomp3x3</a> . </p>
+<p>The function is based on <a class="el" href="../../d9/d0c/group__calib3d.html#ga1aaacb6224ec7b99d34866f8f9baac83" title="Computes an RQ decomposition of 3x3 matrices.">RQDecomp3x3</a> . </p>
```
---
/cc @asmorkalov @catree
=> docs: prefer # for links generation

modules/core/include/opencv2/core/cvdef.h
Dear OpenCV team,
I found a minor typo whilst using OpenCV for my project.
I'm proposing to fix the typo.
Many thanks!
changh95.
---
=> fix typo (portatibility -> portability)

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/1012
This PR try to fix #22625 
ONNX operator doc: https://github.com/onnx/onnx/blob/main/docs/Operators.md#unsqueeze
=> DNN: Make Unsqueeze layer support negative axes

modules/videoio/src/cap_dshow.cpp, samples/python/stitching_detailed.py
Setting CAP_PROP_AUTO_EXPOSURE on VideoCapture with backend DSHOW does not change anything. Now with this implementation the property can be used with value 1 for availability.
https://github.com/opencv/opencv/issues/17019
https://github.com/opencv/opencv/issues/15958
https://github.com/opencv/opencv/issues/14494
https://github.com/opencv/opencv/issues/9738
=> Implemented CV_CAP_PROP_AUTO_EXPOSURE on cap_dshow

modules/dnn/src/layers/fast_convolution/depthwise_convolution.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.avx2.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.hpp, modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_layers.cpp
This PR is proposed for optimizing the winograd futher more. Support the Winograd branch on AVX2 and NEON and Universal intrinsic. 
The original code comes from: https://github.com/vpisarev/ficus/blob/master/lib/NN/OpConv_Winograd.fx.
It should be noted that the existing Winograd only supports NEON. This path not only improves the speed of Winograd on NEON, but also adds the Winograd support of AVX2 and Universal intrinsic.
Test Details: Run the model 1000 times, choose the minimum time.
| Platform| Before | With this Patch | Speedup ratio |
|:-------:|:-------:|:--------:|:------------:|
| Apple M1 ARM | 24.0 ms | 21.7 ms |  9.58 % |
| Intel i7-12700K 12 threads | 25.46 ms  | 21.75 ms | 14.8 % | 
|  | Status | Remarks |
|:-------:|:--------:|:------------:|
| Winograd NEON | …
=> optimize winograd futher more

modules/objdetect/src/qrcode.cpp
There is already a function `adaptiveThreshold` call  in `void QRDecode::init`:
`adaptiveThreshold(original, bin_barcode, 255, ADAPTIVE_THRESH_GAUSSIAN_C, THRESH_BINARY, 83, 2);`
=> QR code, reduce extra adaptiveThreshold()

doc/js_tutorials/js_setup/js_setup/js_setup.markdown
Remove duplicated step in Build OpenCV.js doc: https://docs.opencv.org/4.6.0/d4/da1/tutorial_js_setup.html
=> docs: remove duplicated step in Build .js doc

modules/dnn/src/tensorflow/tf_importer.cpp
This PR try to fix #22597.
Continue the work of #22628 due to branch name is incorrect.
=> DNN-TF: let StridedSlice layer support const input

modules/dnn/src/layers/fast_convolution/depthwise_convolution.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.avx2.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.hpp, modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp
Related issue: [discusstion](https://github.com/opencv/opencv/pull/22593#issuecomment-1284545846).
1. Fix bug in Winograd.
2. Run a dummy Winograd when the device can not support the required CPU Instruction.
---
<cut/>
```
force_builders=Linux x64 Debug,Custom
```
=> DNN: bug fixed in Winograd

samples/android/15-puzzle/gradle/AndroidManifest.xml, samples/android/camera-calibration/gradle/AndroidManifest.xml, samples/android/color-blob-detection/gradle/AndroidManifest.xml, samples/android/face-detection/gradle/AndroidManifest.xml, samples/android/image-manipulations/gradle/AndroidManifest.xml, samples/android/mobilenet-objdetect/gradle/AndroidManifest.xml, samples/android/tutorial-1-camerapreview/gradle/AndroidManifest.xml, samples/android/tutorial-2-mixedprocessing/gradle/AndroidManifest.xml, samples/android/tutorial-3-cameracontrol/gradle/AndroidManifest.xml, samples/android/tutorial-4-opencl/gradle/AndroidManifest.xml
Required for Android 12+ builds.
Error message:
> Manifest merger failed : android:exported needs to be explicitly specified for element <activity#org.opencv.samples.puzzle15.Puzzle15Activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
<cut/>
Note:
- `CRLF => LF` is massively changed in `samples/android/tutorial-4-opencl/gradle/AndroidManifest.xml`
```
force_builders_only=Android armeabi-v7a,Android pack
```
=> android: add android:exported="true"

modules/dnn/test/test_onnx_importer.cpp
It's a part of extended DNN test suite and should not fail without downloaded models.
=> Do not fail tests in Yolo v7 model was not found

modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/test/test_ffmpeg.cpp
=> libav for jetson tk1 does not provide libavutil/display.h

platforms/android/ndk-25.config.py
This PR provides modern Android build configuration.
Usage example with NDK 25b:
<cut/>
```.bash
export ANDROID_NDK="/opt/android/android-sdk.studio/ndk/25.1.8937393"
export ANDROID_SDK="/opt/android/android-sdk.studio"
export ANDROID_SDK_ROOT="/opt/android/android-sdk.studio"
#export ANDROID_NATIVE_API_LEVEL=28
python3 ${OPENCV_SRC_DIR}/platforms/android/build_sdk.py --config ndk-25.config.py --use_android_buildtools
```
Note:
- `--use_android_buildtools` is recommended to use `cmake&ninja` tools from Android SDK instead of system packages (`cmake` package should be pre-installed through [sdkmanager](https://developer.android.com/studio/command-line/sdkmanager)).
- `ANDROID_NATIVE_API_LEVEL` is optional (default=32), use 28 for Android 9 ([versions …
=> android: add configuration for NDK 25 and Android API 32 (12L)

.github/workflows/PR-5.x.yaml
merge together with https://github.com/opencv/ci-gha-workflow/pull/76
=> 5.x: Added ARM64 debug configuration to CI.

modules/3d/include/opencv2/3d/odometry.hpp, modules/3d/include/opencv2/3d/odometry_frame.hpp, modules/3d/src/rgbd/odometry_frame_impl.cpp, modules/3d/src/rgbd/odometry_functions.cpp, modules/3d/src/rgbd/odometry_functions.hpp, modules/3d/src/rgbd/utils.hpp, modules/3d/test/test_odometry.cpp
* Added documentation for `OdometryFrame` and some methods of `Odometry`
* Renamed `getScaledDepth` to `getProcessedDepth` to support further changes (depth bilateral filtering)
=> Docs added for Odometry and OdometryFrame

modules/core/include/opencv2/core/cuda/common.hpp
Fix for https://github.com/opencv/opencv_contrib/issues/3361.
When a cuda runtime/driver function returns an error code which generates an OpenCV exception that code is not cleared so any subsequent calls to `cudaGetLastError();` will return it.  This means any future functions which call `cudaSafeCall(cudaGetLastError())` or similar macros can throw an exception from this error as described in https://github.com/opencv/opencv_contrib/issues/3361.
As OpenCV does not expose a method for clearing this error it seems reasonable that it would be the responsibility of the OpenCV lib to automatically clear it when it throws and exception.  If this is valid fix, it should probably also be applied to the [macro ](https://github.com/opencv/opencv_contrib/blob/c4027ab7f912a3053175477d41b1a62d0078bc5 …
=> Reset cuda runtime error code to cudasuccess on runtime failure.

modules/videoio/src/cap_ffmpeg_impl.hpp
The pertaining issue: https://github.com/opencv/opencv/issues/22701
=> Dump the values of OPENCV_FFMPEG_CAPTURE_OPTIONS and OPENCV_FFMPEG_WRITER_OPTIONS to debug log

modules/highgui/src/precomp.hpp, modules/highgui/src/window.cpp, modules/highgui/src/window_cocoa.mm
naive fix for the #22595 issue.
tested 'not visible' behaviour via `cv::waitKey(12345);` and minimising the window during that wait.
=> add cvGetPropVisible_COCOA

modules/gapi/test/gapi_async_test.cpp
Preventing: gapi_async_test.cpp:448:26: error: ‘sleep_for’ is not a member of ‘std::this_thread’
Fix #22728
=> Included thread in gapi_async_test.cpp

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/stackblur.cpp, modules/imgproc/test/test_stackblur.cpp
Related comments: https://github.com/opencv/opencv/pull/20379#discussion_r1007458906
Purpose of this PR:
1. Remove the C-style implementation
2. Improve API documentation of `stackBlur`.
3. Remove inappropriate optimizations.
4. Remove never used code.
=> improve code style and Doc of stackblur

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/int8layers/quantization_utils.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Merge with extra: [opencv_extra/#1014](https://github.com/opencv/opencv_extra/pull/1014)
For zeropoint and scale can be 1-D tensor, only exists in `Quant`, `Deaunt` and weight of `QLinearConv`. We have supported 1-D tensor case in `QLinearConv`. For `Quant` and `Deaunt`, we can support the constant input case, which is very common situation in per-channel QDQ quantized format. Model examples can be found at PR of extra.
=> DNN: let Quant and Dequant of ONNX_importer support the Constant input.

modules/3d/include/opencv2/3d.hpp, modules/3d/src/octree.cpp, modules/3d/test/test_octree.cpp
This PR is aim at handling cases where the depth setting is too large in 3D module 's octree
**Current Problem**
​	When we build an octree by cloud data, if the `maxDepth` we set is too large, we can not get an octree since a CV_ERROR  was thrown. This is due to precision problems with floating-point number. For example, in `test_octree.cpp`, if we set `maxDepth`=18, this statement will be execute 
`CV_Error(Error::StsBadArg, "The point is out of boundary!");`
**Reason**
​	In the current version, every time the function `insertPointRecurse()` is called to insert a point, it always determines whether the point is in the space first through this statement
`if(!node.isPointInBound(point, node.origin, node.size))`
if true, it will throw a `CV_Error`
​	It decide which subblock the point is in …
=> 3D: Handle cases where the depth of Octree setting is too large

modules/imgproc/src/floodfill.cpp
Remove unnecessary typecasts, which even made `floodFill` fail when processing a large image.
- _not sure, so proposing to the default branch_
=> Fix `floodFill` for very large images

modules/gapi/include/opencv2/gapi/core.hpp, modules/gapi/include/opencv2/gapi/gcommon.hpp, modules/gapi/include/opencv2/gapi/gscalar.hpp, modules/gapi/include/opencv2/gapi/imgproc.hpp, modules/gapi/include/opencv2/gapi/s11n.hpp, modules/gapi/misc/python/package/gapi/__init__.py, modules/gapi/misc/python/pyopencv_gapi.hpp, modules/gapi/misc/python/python_bridge.hpp, modules/gapi/misc/python/test/test_gapi_core.py, modules/gapi/misc/python/test/test_gapi_types.py, modules/gapi/src/backends/common/serialization.cpp
Python bindings are available since a long time, but only a few operations (`operation::on(...)` wrappers) were exposed.
There was a great plan to implement feature in python parser that could automatically detect `G-API` operation (via `GAPI_TYPED_KERNEL` macro or so) and expose it into python, but this functionality is more about giving an opportunity to user to implement python `kernels` for already existing in G-API operations. 
This PR is going to expose just `operation::on` wrappers to python in order to give user everything that is available from c++, because now, for developers who don't build from source and change the code only …
=> G-API Expose all core operations to python

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/grfmt_exr.cpp
extracted from #21324
(cherry picked from commit aa276ece66265dcf07af5f840933377d2106c871)
=> OpenEXR encoder: add capability to set the DWA compression level

modules/highgui/src/window_w32.cpp
Remove unnecessary function resulting in infinite recursion. Since In all four places it was used, we already check the shared pointer, the extra assert that the function provided was redundant, so I removed it, and I added a de-reference to the `window` parameters.
=> Remove infinite recursion in Trackbar handling on Windows

modules/core/include/opencv2/core/check.hpp, modules/core/src/check.cpp, modules/imgcodecs/src/grfmt_webp.cpp
Added support for:
- `CV_Check{EQ,NE}(bool, bool, msg)`  (LT,GE,etc variants doesn't makes sense with `bool` and should not be used)
- `CV_CheckTrue(bool_expr_must_be_true, msg)`
- `CV_CheckFalse(bool_expr_must_be_false, msg)`
Also eliminates related build warning: http://pullrequest.opencv.org/buildbot/builders/precommit_linux32/builds/100058
```
force_builders=Linux32
```
=> core: support CV_Check*() macros with 'bool' parameters

cmake/OpenCVDetectCUDA.cmake
When building with CUDA on windows the following two warnings 
1. `#1394-D: field of class type without a DLL interface used in a class with a DLL interface from windows CUDA builds.`
2. `#1388-D: base class dllexport/dllimport specification differs from that of the derived class.`
are issue thousands of times.  
Aswell as hiding legitimite warnings from the user it causes many to think that there build is broken see below for examples
- https://stackoverflow.com/questions/65767280/error-installing-opencv-using-build-all-field-of-class-type-without-a-dll-inter
- https://answers.opencv.org/questions/scope:all/sort:activity-desc/page:1/query:field%20of%20class%20type%20without%20a%20DLL%20interface/
- https://forums.developer.nvidia.com/t/custom-opencv-cuda-several-warnings-when-building-it/ …
=> Suppress CUDA nvcc generated warnings #1394-D and #1388-D on windows

modules/gapi/include/opencv2/gapi/imgproc.hpp
Python bindings are available since a long time, but only a few operations (`operation::on(...)` wrappers) were exposed.
There was a great plan to implement feature in python parser that could automatically detect `G-API` operation (via `GAPI_TYPED_KERNEL` macro or so) and expose it into python, but this functionality is more about giving an opportunity to user to implement python `kernels` for already existing in G-API operations. 
This PR is going to expose just `operation::on` wrappers to python in order to give user everything that is available from c++, because now, for developers who don't build from source and change the code only …
=> G-API Expose all imgproc operations to python

modules/gapi/test/infer/gapi_infer_ie_test.cpp
* Moved test fixture initialization from constructor to the `InferWithReshape::SetUp` method to avoid crash in case when exception is thrown (e.g. can not find test data).
* Call parent class `SetUp` method in `InferWithReshapeNV12::SetUp`
Example of crash (aarch64/qemu, build with OpenVINO support):
```
[----------] 6 tests from InferWithReshape
[ RUN      ] InferWithReshape.TestInfer
C++ exception with description "OpenCV(4.6.0-dev) /opencv/modules/ts/src/ts.cpp:1064: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml in function 'findData'
" thrown in the test fixture's constructor.
89748 Segmentation fault      (core dumped)
```
=> gapi: fix InferWithReshape test crash when data is not found

doc/js_tutorials/js_imgproc/js_gradients/js_gradients.markdown, doc/py_tutorials/py_imgproc/py_gradients/py_gradients.markdown, modules/video/src/bgfg_gaussmix2.cpp
There is `Gaussian` used in API names and documentations. To keep the same, I change `Gausssian` (3 s) to `Gaussian` (2 s). Correct me if I am wrong.
=> fix typo: Gausssian to Gaussian

modules/highgui/src/window_cocoa.mm
This patch calls `activateIgnoringOtherApps` when creating a Cocoa window, fixing the issue that the window created by `imshow` was spawned behind other instead of in the foreground.
=> Cocoa/highgui: Set `[NSApp activateIgnoringOtherApps]` to spawn window on top

modules/highgui/src/window_cocoa.mm
Fixes https://github.com/opencv/opencv/issues/10647 on macOS in  branch 3.4
=> backport #22737: Cocoa/highgui: Set [NSApp activateIgnoringOtherApps] to spawn window on top

modules/highgui/src/window_w32.cpp
This fixes some of the problems -- when toolbars are created in one go, and some go outside the window bounds (when main client are becomes nothing), they will get sized correctly.
However, with `WINDOW_NORMAL`, some wonkiness still remains and blank buttons tend to appear once in a while (this might be due to the spacers).
Ideally, the trackbars should automatically resize to fit the width of the main window, when said window is resized (either manually when in `NORMAL` mode, or by code). This might however break some existing code that relies on current behaviour to place multiple trackbars on single row. Any opinions?
=> Fix #22767: Ensure that the buttons are spaced to the size of the toolbar window, which is always visible.

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/1015
This PR is a temporary solution to fix #22713.
When 3D or 4D `MatMul` with a const input, it will create a virtual layer to ensure it can be run correctly. Later I will create a new PR to optimize the parsing of `MatMul` so that 3D or 4D operations can also use SIMD and multi-thread acceleration like 2D `MatMul`.
=> DNN: Make MatMul layer support 3D or 4D operation with const input

modules/dnn/perf/perf_layer.cpp, modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/src/op_cuda.cpp
This PR lets `MAX`, `MIN`, `SUM`, `PRODUCT` and `DIV` operators without broadcast support CUDA.
=> DNN: Let part of the operators in nary_eltwise support CUDA

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1021
This PR is try to solve the `MatMul` node problem of https://github.com/opencv/opencv/issues/22859
=> DNN: let MatMul can work when both two inputs are const

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/tile_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Fixes #22789
Merge with https://github.com/opencv/opencv_extra/pull/1017
ONNX doc for Tile:
- Opset 1: 3 inputs (https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Tile-1)
- Opset 6: 2 inputs (https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Tile-6)
- Opset 13: 2 inputs (https://github.com/onnx/onnx/blob/main/docs/Operators.md#Tile)
- Opset 13 is basically the same as Opset 6 for inference.
=> dnn: support ONNX Tile

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap.cpp, modules/videoio/src/cap_avfoundation.mm, modules/videoio/src/cap_avfoundation_mac.mm, modules/videoio/src/cap_ffmpeg.cpp, modules/videoio/src/cap_interface.hpp, modules/videoio/test/test_ffmpeg.cpp, modules/videoio/test/test_orientation.cpp
This is an extension to #15499. I pulled some of the code up, so now it would be somewhat easier to add support for orientation metadata into the other backends as well.
=> Add support for CAP_PROP_ORIENTATION_AUTO to AVFoundation backend

cmake/OpenCVUtils.cmake
```
build_image:Custom=ffmpeg-master
```
=> cmake: ocv_check_modules: ignore -latomic and -lstdc++

modules/dnn/src/ie_ngraph.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
resolves #22640
relates #17622 (3.4) / #17634 (4.x)
TODO:
<cut/>
```
force_builders_only=Custom,Custom Win
Xbuild_image:Custom Win=openvino-2022.1.0
buildworker:Custom Win=windows-1
```
=> dnn(openvino): fix custom layers BlockingDesc

modules/core/src/minmax.cpp
naive change for the #22860 issue (but untested since I don't have OpenCL 1.1 here)
=> ocl_minMaxIdx to call minmaxloc.cl for OpenCL 1.2+ only

modules/dnn/perf/perf_net.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_darknet_importer.cpp
Related issue: https://github.com/opencv/opencv/issues/22825
Before this patch, every convolution 3x3s1 layer keeps twore-packed weight parameter one for general convolution and another for Winograd convolution.
This PR proposes to let the 3x3s1 convolution layer save only one re-packed weight parameter at a time.
```
```
=> DNN: reduce the memory used in convolution layer

modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Merge with test data: [opencv_extra data](https://github.com/opencv/opencv_extra/pull/1022).
=> DNN: gemm support transA and transB, and first input is constance.

modules/core/include/opencv2/core/hal/intrin_rvv.hpp
- v_interleave_quads
- v_pack_triplets
- v_signmask
relates #18228
<cut/>
Resolved test failures:
<details>
```
[ RUN      ] hal_intrin128.uint8x16_BASELINE
SIMD128: void opencv_test::hal::intrin128::cpu_baseline::test_hal_intrin_uint8()
/home/alalek/projects/opencv/dev/modules/core/test/test_intrin_utils.hpp:523: Failure
Expected equality of these values:
resQ[8*i]
Which is: '\x5' (5)
dataA[8*i ]
Which is: '\t' (9)
Google Test trace:
/home/alalek/projects/opencv/dev/modules/core/test/test_intrin_utils.hpp:522: i=1
/home/alalek/projects/opencv/dev/modules/core/test/test_intrin_utils.hpp:524: Failure
Expected equality of these values:
resQ[8*i + 1]
Which is: '\t' (9)
dataA[8*i+4]
Which is: '\r' (13, 0xD)
Google Test trace:
/home/alalek/projects/opencv/dev/modules/core/test/test_intrin_utils …
```
=> risc-v: fix RVV backend on clang with undefined CV_RVV_SCALABLE

3rdparty/libjpeg-turbo/src/simd/CMakeLists.txt
to avoid issues on CI.
relates #22372
=> cmake(3rdparty): drop simd warning in libjpeg-turbo

modules/videoio/test/test_ffmpeg.cpp
relates #22894
Fail messages on Windows:
```
[ RUN      ] videoio_ffmpeg_16bit.basic/0, where GetParam() = ("FFV1", "avi", false, true)
[ INFO:0@44.452] global /build/opencv/modules/videoio/src/cap_interface.hpp (188) warnUnusedParameters VIDEOIO: unused parameter: [5]=2 / 0x0000000000000002
C:\build\precommit_windows64\4.x\opencv\modules\videoio\test\test_ffmpeg.cpp(595): error: Expected equality of these values:
isSupported
Which is: true
writer.isOpened()
Which is: false
[  FAILED  ] videoio_ffmpeg_16bit.basic/0, where GetParam() = ("FFV1", "avi", false, true) (0 ms)
[ RUN      ] videoio_ffmpeg_16bit.basic/1, where GetParam() = ("FFV1", "mkv", false, true)
[ INFO:0@44.453] global /build/opencv/modules/videoio/src/cap_interface.hpp (188) warnUnusedParameters VIDEOIO: unused parameter: …
```
=> videoio(test): test skip due to non-updated FFmpeg wrapper

3rdparty/carotene/hal/tegra_hal.hpp, modules/imgproc/test/test_filter.cpp
Fixes https://github.com/opencv/opencv/issues/22893
=> Integer underflow fix for morphologyEx in Carotene (arm).

modules/videoio/test/test_ffmpeg.cpp, modules/videoio/test/test_video_io.cpp
Nightly build: http://pullrequest.opencv.org/buildbot/builders/master-win64-vc16/builds/100005 (sporadic on i7-11800H)
<cut/>
```
[ RUN      ] videoio/videocapture_acceleration.read/74, where GetParam() = (sample_322x242_15frames.yuv420p.libx264.mp4, FFMPEG, ANY, false)
VideoCapture FFMPEG:D3D11
VideoCapture with acceleration = D3D11  @ FFMPEG     on sample_322x242_15frames.yuv420p.libx264.mp4 with PSNR-original = 20.7884
C:\build\master-win64-vc16\opencv\modules\videoio\test\test_video_io.cpp(789): error: Expected: (min_psnr_original) >= (psnr_threshold), actual: 20.7884 vs 23
[  FAILED  ] videoio/videocapture_acceleration.read/74, where GetParam() = (sample_322x242_15frames.yuv420p.libx264.mp4, FFMPEG, ANY, false) (61 ms)
[ RUN      ] videoio/videocapture_acceleration.read/78, where …
```
=> videoio(test): update PSNR check for H264/265

modules/core/src/logger.cpp
- Strip path from logger, keep file name only.
- Reverted `CV_Error()` changes.
=> core(logger): strip opencv's modules base path

modules/core/include/opencv2/core/bindings_utils.hpp, modules/python/src2/gen2.py, modules/python/test/test_misc.py
Fixes export of class properties having names that are reserved in Python.
Classes exported with `CV_EXPORTS_W_MAP` are not affected, because their properties are string literals in `dict` 
Existing use case: [cv:: TrackerKCF::Params::lambda](https://github.com/opencv/opencv_contrib/blob/a26f71313009c93d105151094436eecd4a0990ed/modules/tracking/include/opencv2/tracking.hpp#L123)
=> fix: add _ suffix to properties having reserved keyword names

modules/python/test/test_misc.py
=> fix: remove function duplicates in test_misc.py

modules/videoio/src/cap_ffmpeg_impl.hpp
```
build_image:Custom=ubuntu:14.04
```
=> Fix missing FFmpeg include needed for av_get_pix_fmt_name

modules/video/include/opencv2/video/tracking.hpp, modules/video/test/test_trackers.cpp, samples/python/tracker.py
Merge this PR with: https://github.com/opencv/opencv_extra/pull/1025.
Update model download link without code change.
NanotrackV2 is faster than NanoTrackV1. At the same time, the accuracy rate is improved.
| Model Version | Speed |  VOT2018 EAO (higher is better) |
|:-------:|:--------:|:------------:|
| NanoTrackV1 | 150 FPS | 0.311 |
| NanoTrackV2 | 200 FPS | 0.352 |
=> Video: update download link for NanoTrack

modules/objdetect/include/opencv2/objdetect.hpp, modules/objdetect/perf/perf_qrcode_pipeline.cpp, modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qrcode.cpp
merge with https://github.com/opencv/opencv_extra/pull/1024
Added detect QR code alignment marker (1 marker for 2-6 versions, 6 markers for 7-40 versions). Alignment marker uses to find the correct position of the fourth corner.
To check the correctness, a benchmark [was launched](https://github.com/opencv/opencv_benchmarks):
[qr.py.txt](https://github.com/opencv/opencv/files/10210080/qr.py.txt)
- +2% total decode (~+5% against detected QR codes)
- +0.4 pixels total accuracy for corner detect
Logging from benchmark:
[METRIC_CORNER_DIST_default.txt](https://github.com/opencv/opencv/files/10190260/METRIC_CORNER_DIST_default.txt)
[METRIC_CORNER_DIST_new.txt](https://github.com/opencv/opencv/files/10221133/METRIC_CORNER_DIST_new.txt)
No decode regression now.
See details at …
=> Use QR code alignment markers

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_gstreamer.cpp, modules/videoio/test/test_gstreamer.cpp
Address https://github.com/opencv/opencv/issues/22868
Used the same defaults as it's done for FFmpeg
```
```
=> Timeouts support for GStreamer backend

modules/dnn/src/cuda4dnn/primitives/matmul.hpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/1018
This PR follows the https://github.com/opencv/opencv/pull/22775
The main purpose of this PR is making `MatMul` support the broadcast that the second input has less dimention than the first one.  And let the operation support SIMD and multi-thread. Beacuse it doesn't support 1D Mat, only support MatMul like 
```
2x3x4 mul 4x5 -> 2x3x5
2x3x4x5 mul 3x5x6 -> 2x3x4x6
```
- **2 const inputs:** create a virtual layer for the first input
- **1 const input with CPU (whether or not using broadcast):** use the SIMD and multi-thread flow which for `InnerProduct`
- **1 const input with CUDA:** broadcast inputs will fallback to CPU. Inputs with the same shape will use the cuda. 
See details at …
=> DNN: make MatMul support 3D or 4D with broadcast

modules/videoio/test/test_ffmpeg.cpp
relates #22248
Avoid reaching of valgrind default limitations:
```
[ RUN      ] videoio_read.threads/6, where GetParam() = (("video/big_buck_bunny.h264", 125, false), 2000, true)
Use --max-threads=INT to specify a larger number of threads
and rerun valgrind
valgrind: the 'impossible' happened:
Max number of threads is too low
```
=> videoio(test): reduce number of test threads

modules/core/src/parallel_impl.cpp
No need to loop as RDTSC is 3/4 times faster than _mm_pause.
=> Even faster CV_PAUSE on SkyLake and above.

modules/core/src/utils/filesystem.cpp
No significant changes are expected with cache management on 4.x release series.
=> core: freeze cache directory prefix - "4.x"

modules/core/include/opencv2/core/cuda/common.hpp
See https://github.com/opencv/opencv_contrib/pull/3378 and https://github.com/opencv/opencv_contrib/issues/3390.  
CUDA texture references have now been completley removed in the latest SDK (CUDA 12.0).
If https://github.com/opencv/opencv_contrib/pull/3378 is merged this code block which is causing builds to fail against CUDA 12.0 (https://github.com/opencv/opencv_contrib/issues/3390) will become redundant.
=> Replace all instances of CUDA texture references with texture objects

modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/test/test_onnx_importer.cpp
- this mode is not supported by #22828
fixup #22828
```
```
=> dnn: disable OpenCL code path in MatMul processing

modules/calib3d/src/five-point.cpp, modules/calib3d/src/usac.hpp, modules/calib3d/src/usac/ransac_solvers.cpp, modules/calib3d/test/test_usac.cpp
Added a default parameter `maxIters` to `findEssentialMat` and replaced the hardcoded value of `1000` in `ransac_solvers.hpp`. Fix for issue #22696
Test to check:
```python
def roll():
kpts0 = np.random.rand(2, 50)
kpts1 = np.random.rand(2, 50)
norm_thresh = .5
conf = .5
a = cv2.findEssentialMat(
kpts0, kpts1, np.eye(3), threshold=norm_thresh, prob=conf, method=cv2.USAC_MAGSAC, maxIters = 1
)
b = cv2.findEssentialMat(
kpts0, kpts1, np.eye(3), threshold=norm_thresh, prob=conf, method=cv2.USAC_MAGSAC, maxIters = 5000
)
return not (np.array_equal(a[0], b[0]) and np.array_equal(a[1], b[1]))
results_sum = sum([roll() for _ in range(10)])
print('Test failed' if results_sum == 0 else 'Test OK')
``` …
=> Fix maxIter parameter in usac findEssentialMat 

platforms/scripts/valgrind_3rdparty.supp
resolves #22991
Issue is not reproducible with newer FFmpeg version, hence suppressing. Tested with system package from Ubuntu 22.04 (probably 4.4.2):
```
--     FFMPEG:                      YES
--       avcodec:                   YES (58.134.100)
--       avformat:                  YES (58.76.100)
--       avutil:                    YES (56.70.100)
--       swscale:                   YES (5.9.100)
--       avresample:                NO
```
Note: suppressing only libavcodec 57
=> valgrind: suppress FFV1 16 bit issue in avcodec-57

modules/photo/src/merge.cpp
We still need images[i] = img because it is used below in buildPyramid.
=> Fix self converTo.

modules/dnn/src/layers/gather_layer.cpp, modules/dnn/test/test_onnx_importer.cpp
- support FP16 data
fixup #21738
Fixes failed tests:
```
[  FAILED  ] Test_ONNX_layers.Gather/1, where GetParam() = OCV/OCL_FP16
[  FAILED  ] Test_ONNX_layers.GatherMulti/1, where GetParam() = OCV/OCL_FP16
[  FAILED  ] Test_ONNX_layers.MatMul_init/1, where GetParam() = OCV/OCL_FP16
```
=> dnn: fix gather layer implementation

modules/calib3d/src/solvepnp.cpp
The current implementation overwrites the result rotation and translation in every iteration. If SOLVEPNP_ITERATIVE was run as a refinement it will start from the incorrect initial transformation thus  degrading the final outcome. 
There is not bug report I am aware of nor any test or documentation that references the existence of this bug
- [✅] I agree to contribute to the project under Apache 2 License.
- [✅] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [✅] The PR is proposed to the proper branch
- [❌] There is a reference to the original bug report and related work
- [❌] There is accuracy test, …
=> Bugfix for solvePnPRansac with SOLVEPNP_ITERATIVE

cmake/OpenCVDetectCUDA.cmake
Fix https://github.com/opencv/opencv/issues/23010.
The ability to disable nvcc warnings wasn't introduced until CUDA 11.2 (https://docs.nvidia.com/cuda/archive/11.2.0/cuda-toolkit-release-notes/index.html)
=> Fix nvcc compile errors when built against CUDA SDK < 11.2

modules/objc/generator/gen_objc.py
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/3398
- prefix with outer class name
resolves #22206
resolves https://github.com/opencv/opencv_contrib/issues/3302
relates #17165
TODO:
<cut/>
```.diff
./modules/objc_bindings_generator/osx/gen/objc/xfeatures2d/BEBLID.h
@@ -18,8 +18,8 @@
// C++: enum BeblidSize (cv.xfeatures2d.BEBLID.BeblidSize)
typedef NS_ENUM(int, BeblidSize) {
-    SIZE_512_BITS = 100,
-    SIZE_256_BITS = 101
+    BEBLID_SIZE_512_BITS = 100,
+    BEBLID_SIZE_256_BITS = 101
};
./modules/objc_bindings_generator/osx/gen/objc/xfeatures2d/TEBLID.h
@@ -18,8 +18,8 @@
// C++: enum TeblidSize (cv.xfeatures2d.TEBLID.TeblidSize)
typedef NS_ENUM(int, TeblidSize) {
-    SIZE_256_BITS = 102,
-    SIZE_512_BITS = 103
+    TEBLID_SIZE_256_BITS = 102,
+ …
```
=> obj-c: de-duplicate values of nested enums

modules/dnn/perf/perf_net.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_int8_layers.cpp
Merge with opencv/opencv_extra#1026
- All tests now use `yolov4-tiny-2022-12` instead of `yolov4-tiny`
- I had to update test reference data, because results were different, I didn't check how previous bounding boxes look like, but updated boxes looks well:
First image:
Second image:
=> dnn: updated YOLOv4-tiny model and tests

modules/core/include/opencv2/core.hpp, modules/core/src/matrix_transform.cpp, modules/core/test/test_arithm.cpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/test/test_onnx_importer.cpp
Fixes https://github.com/opencv/opencv/issues/22794
Merge with https://github.com/opencv/opencv_extra/pull/1023.
Current workaround for negative steps is computing the forward indexing range for slice and flip at axis with negative step:
> x of shape [5, 10], x[5:0:-1, 10:1:-3] <=> np.flip(x[1:5:1, 2:10:3], aixs=(0, 1))
We can also extend `Range` to support backward indexing and steps like Python `list`, which needs more effort to do so I think.
=> dnn: support ONNX Slice with negative steps by adding and using cv::flipND

modules/imgproc/src/color.hpp
Define channels number for Lab, Luv, YCrCb and XYZ conversions. Resolves performance issue #20465
Fixes #20465
=> dstChannels Lab, Luv, YCrCb and XYZ conversion fix

modules/dnn/test/pascal_semsegm_test_fcn.py, modules/python/test/test_misc.py, modules/python/test/tst_scene_render.py
This change replaces references to a number of deprecated NumPy type aliases (np.bool, np.int, np.float, np.complex, np.object, np.str) with their recommended replacement (bool, int, float, complex, object, str).
Those types were deprecated in 1.20 and are removed in 1.24, cf https://github.com/numpy/numpy/pull/22607.
=> Remove references to deprecated NumPy type aliases.

modules/dnn/src/ie_ngraph.cpp, modules/dnn/src/ie_ngraph.hpp, modules/dnn/src/layers/concat_layer.cpp, modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/src/net_openvino.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_ie_models.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_model.cpp
* Use OpenVINO Runtime API (aka Tensor API or API 2.0) which has been introduces in 2022.1
* Remove `InferenceEngine::DataPtr` completely
* Internal dynamism feature works only with a new API. Actual for Faster-* family models and with layers such as NonZero, Top-k and others. This feature may improve performance.
```
```
=> Switch to new OpenVINO API after 2022.1 release

modules/video/include/opencv2/video/tracking.hpp
The download link of Doc lacked a space at the beginning, which prevented Doxygen from parsing it as a link.
Related Link: https://docs.opencv.org/4.x/d8/d69/classcv_1_1TrackerNano.html
Before this patch, the link is parsed as plain text:
With this patch:
=> Doc: Add spaces to make links clickable

3rdparty/ffmpeg/ffmpeg.cmake, modules/videoio/test/test_ffmpeg.cpp, modules/videoio/test/test_video_io.cpp
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/74
- FFmpeg 4.4.3
previous update: https://github.com/opencv/opencv/pull/22498
```
```
=> ffmpeg/4.x: update FFmpeg wrapper 2022.12

cmake/OpenCVDetectCUDA.cmake, modules/world/CMakeLists.txt
=> cmake: VERSION_GREATER_EQUAL is not supported in CMake 3.5.1

modules/core/include/opencv2/core/cuda/common.hpp
Fix build errors reported in https://github.com/opencv/opencv/issues/23034
Confirmed builds with  CUDA 12.0, CuDNN 8.7.0.84, Nvidia Video Codec SDK 12.0 on both
- Windows 11 22H2: Visual Studio 2022 (17.43)
- Ubuntu 20.04 LTS (WSL): g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```
```
=> Fix CUDA 12.0 build errors

modules/calib3d/misc/java/test/Calib3dTest.java, modules/calib3d/src/fisheye.cpp, modules/calib3d/test/test_fisheye.cpp
Backport of #22604 to 3.4
Connected PR in extra: [#1030@extra](https://github.com/opencv/opencv_extra/pull/1030)
=> Backport to 3.4: fix fisheye aspect ratio

platforms/js/opencv_js.config.py
ORB constructor is failing to set the very important protected parameter fastThreshold, so binding this method is necessary.
Related to https://github.com/opencv/opencv/issues/17395#issuecomment-903189183
```
```
=> Add missing ORB.setFastThreshold(int) method

platforms/js/opencv_js.config.py
I was trying to use the emscripten/js binding for the aruco module.
I have found typo in https://github.com/opencv/opencv/pull/23009 about the exported methods.
PS: @asmorkalov As of 4.7.0, it seems I cannot import ArucoDetector from https://docs.opencv.org/4.7.0/opencv.js after migration
=> fix typo: stetDictionary to setDictionary

modules/dnn/src/layers/fast_convolution/fast_convolution.avx2.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.cpp, modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp
The segmentation fault error only happens in AVX only platform, while the `CV_TRY_AVX2` is true and `checkHardwareSupport(CPU_AVX2)` is false. And this inconsistency will cause Winograd branch code to enter the wrong memory block. And in AVX only platform, the Winograd can not be speeded up by AVX or AVX2 which will be slower than the generic Convolution branch. So, in short term, I think disabling Winograd is a better solution.
And for a long-term solution, we should support Winograd at https://github.com/opencv/opencv/blob/4.x/modules/dnn/src/layers/layers_common.simd.hpp. After that, OpenCV can automatically generate AVX or AVX2 code for Winograd based on CPU instruction set. I will try to implement this.
detailed discussion: https://github.com/cocoa-xu/evision/issues/153#issuecomment-1 …
=> DNN: fix possible segmentation fault error in winograd on x86

modules/core/src/system.cpp
Fixes https://github.com/opencv/opencv/issues/23085.
After https://github.com/opencv/opencv/pull/22271 was merged, OpenCV can no longer initialize on M1 macs due to missing the required `NEON_DOTPROD` feature. This patch simply checks if `__ARM_FEATURE_DOTPROD` is enabled (which should be true when compiling for M1 macs), and turns on `CV_CPU_NEON_DOTPROD` if this feature is supported in runtime.
=> Open CV_CPU_NEON_DOTPROD on Apple silicon devices

modules/features2d/src/sift.simd.hpp
relates #22246 #22295
GCC12 still emits this warning on x86 (`cmake ... -DCPU_BASELINE=AVX2 -DCPU_DISPATCH=`)
=> build: eliminate GCC9 warning from sift.simd.hpp

cmake/checks/cpu_rvv.cpp, modules/core/include/opencv2/core/hal/intrin_rvv.hpp
Adjust for GCC about type cast.
<cut/>
```
Xbuild_image:Custom=riscv-gcc
Xbuild_image:Custom=riscv-gcc-rvv
build_image:Custom=riscv-gcc-rvv-128
Xbuild_image:Custom=riscv-clang
Xbuild_image:Custom=riscv-clang-rvv
test_timeout:Custom=1200
```
=> Use reinterpret instead of c-style casting for GCC

modules/dnn/src/layers/fast_convolution/depthwise_convolution.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.cpp, modules/dnn/src/layers/fast_convolution/fast_convolution.hpp, modules/dnn/test/test_onnx_importer.cpp
Merge with test data: https://github.com/opencv/opencv_extra/pull/1034
Fixes: https://github.com/opencv/opencv/issues/23074
In the previous optimization, we fused the `Conv` and `Add` layers. This PR further provides support for `Depth-wise Conv` and `Add` layers fusion.
=> DNN: fused depthwise and add

modules/core/include/opencv2/core/fast_math.hpp, modules/core/test/test_math.cpp
Backport of the fix from #23098 
Sometimes `cvIsInf(double)` assumes NaN as Inf. This PR fixes that and adds some regression tests
=> Backport to 3.4: cvIsInf() fix

modules/ts/include/opencv2/ts/ts_perf.hpp, modules/ts/src/ts_perf.cpp
This may unexpectedly broke performance reports and provide wrong results due to measurement **in runtime**.
- it measures a time between exiting of `startTimer()`, `iter++` and calling of `stopTimer()`. Critical code path is minimized for this flow.
- on properly configured system its value is almost zero: about 10-11 clock ticks (ns, on Linux x86). By comparing to 1'000'000 clock ticks of 1ms sample measurement - it is a nothing.
- other values are not expected (and not observed during the 5+ years). Other values would just break the numbers in the performance report.
- this value is already ignored (forced to 0) for `PERF_STRATEGY_SIMPLE` which is default since [2014](https://github.com/opencv/opencv/blame/4.7.0/modules/ts/src/ts_perf.cpp#L37).
Lets remove this unnecessary step of …
=> perf: drop runtime time adjustment calibration

modules/calib3d/src/precomp.hpp, modules/calib3d/src/usac/local_optimization.cpp, modules/calib3d/test/test_usac.cpp
The bug arises in #22884 when setting a number of points to numbers like 60000 and bigger.
For N samples GraphCut tries to allocate an edge connectivity matrix of size NxN and segfaults on big numbers, see [here](https://github.com/opencv/opencv/blob/9208dcb07c015e1fda44e40bb07b43c700b4bf46/modules/calib3d/src/usac/local_optimization.cpp#L43).
The solution is to use `std::set<int>` instead of `std::vector<bool>`.
Despite theoretically longer read/write time, like O(log N) vs O(1), I've got +30% performance on my machine, probably because of CPU caching.
The bug reproducer is just a `usac_testUsacParams.accuracy` test with bigger `pts_size`.
=> USAC fix: GraphCut fails to allocate big dense matrices

modules/calib3d/src/calibration.cpp
=> Backport to 3.4: fixing how stdDev in calibration is calculated

modules/dnn/src/cuda4dnn/primitives/matmul.hpp
When building with GCC 7.5, I see following warning message.
```
In file included from /opencv-fork/modules/core/include/opencv2/core.hpp:53:0,
from /opencv-fork/modules/dnn/src/layers/../precomp.hpp:49,
from /opencv-fork/modules/dnn/src/layers/fully_connected_layer.cpp:43:
/opencv-fork/modules/dnn/src/layers/../cuda4dnn/primitives/matmul.hpp: In instantiation of ‘void cv::dnn::cuda4dnn::MatMulOp<T>::forward(const std::vector<cv::Ptr<cv::dnn::dnn4_v20221220::BackendWrapper> >&, const std::vector<cv::Ptr<cv::dnn::dnn4_v20221220::BackendWrapper> >&, cv::dnn::cuda4dnn::csl::Workspace&) [with T = float]’:
/opencv-fork/modules/dnn/src/layers/fully_connected_layer.cpp:871:1:   required from here
/opencv-fork/modules/dnn/src/layers/../cuda4dnn/primitives/matmul.hpp:41:43: warning: suggest …
```
=> build: suppress warning

modules/videoio/src/cap_msmf.cpp, modules/videoio/test/test_video_io.cpp
Adding HEVC/H265 FourCC support to MSMF video writer. I have verified it with my own video input stream, and it works well on my workstation.
=> Adding HEVC/H265 FourCC support to MSMF video writer

modules/imgproc/src/distransform.cpp
Related issue: https://github.com/opencv/opencv/issues/23060
=> removed redundant code in `distransform.cpp`

modules/calib/src/fisheye.cpp, modules/calib/test/test_fisheye.cpp
Fixes #23057
Parameter uncertainty fixed + ground truth test data fixed
=> Fisheye calibration: uncertainty fixed

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/perf/perf_layer.cpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/layer_norm.cpp, modules/dnn/src/onnx/onnx_graph_simplifier.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Merge with https://github.com/opencv/opencv_extra/pull/1032
Benchmark:
| Layer | Mean (ms) | Median (ms) | Min (ms) |
| - | - | - | - |
| layer norm expanded | 0.43 | 0.42 | 0.40 |
| layer norm (this pr) | 0.02 | 0.02 | 0.01 |
*: tested with size 1x50x768 on Apple M1.
```
```
=> dnn: add layer normalization for vision transformers

modules/core/src/parallel.cpp
Omit the first check of the double-checked locking pattern in `recordException()` in parallel.cpp when `CV_THREAD_SANITIZER` is defined. This should only slow `recordException()` down when the thread sanitizer is used, and avoids the TSAN data race warning.
`CV_THREAD_SANITIZER` is defined in `cvdef.h` which is included by `core.hpp` which is included by `utility.hpp` which is included by `precomp.hpp` which is included by `parallel.cpp`. If this is too indirect, `#include "cvdef.h"` can be added in `parallel.cpp`.
https://github.com/opencv/opencv/blob/52855a39ad5c3d5ae9b983e6add43163ca474b84/modules/core/src/parallel.cpp#L266-L291
Clang's thread sanitizer found the following when running an internal fuzz target:
```
WARNING: ThreadSanitizer: data race (pid=8714)
Read of size 1 by thread …
```
=> Avoid double-checked locking with TSAN in parallel

modules/calib3d/src/fisheye.cpp, modules/calib3d/test/test_fisheye.cpp
Backport of #23178 to 3.4
This can be automatically ported to 4.x
=> Backport to 3.4 of the fisheye calibration uncertainty fix

modules/imgproc/src/drawing.cpp, modules/imgproc/test/test_drawing.cpp
Fixes #22012
Fixing the bug described in https://github.com/opencv/opencv/issues/22012
The artifacts can occur when corners of a polygon are outside of the image. To be more precise, the outline of the polygon is being drawn using clipped endpoints of an edge, while the borders of the area to be filled are determined using unclipped points of an edge. This can introduce a small offset between the outline and the filled area in polygons which have corner points outside of the image.
The issue is fixed by correcting the edges when lines are clipped.
=> Fix occuring artifacts in fillPoly

modules/dnn/src/layers/fast_convolution/depthwise_convolution.cpp, modules/dnn/test/test_onnx_importer.cpp
Merge this PR with test data: https://github.com/opencv/opencv_extra/pull/1041.
Related issue: https://github.com/opencv/opencv/issues/23151
Related PR: #22905
=> DNN: fixed bug in depthwise conv of stride 2

modules/objdetect/src/qrcode_encoder.cpp, modules/objdetect/test/test_qrcode_encode.cpp
Fixes #22205 and #23105 
While splitting the data to multiple QR codes it constantly cleans the resulting vector(final_qr_codes).
The fix is to just clean the result vector after all work is done with it.
=> Fix encodeStructuredAppend() resulting in only one QR code problem, and false output data fix.

modules/core/include/opencv2/core/hal/intrin_rvv071.hpp
This PR includes two fixes for RISC-V RVV 0.7 intrinsics:
* Use non-saturated add/sub instructions for 32 and 64 bit int
Apparently 32- and 64-bit types differ from 8- and 16-bit, e.g. NEON intrinsics have same pattern (`vqadd` - saturated, `vadd` - wraps on overflow): https://github.com/opencv/opencv/blob/ff8af10cfea719ed4278f1f54ef5466bc726c7a1/modules/core/include/opencv2/core/hal/intrin_neon.hpp#L473-L493 
* `v_check_`  intrinsics use 32-bit element size to avoid 64-bit operations which are not supported by HW
<cut/>
```
Xbuild_image:Custom=riscv-gcc
Xbuild_image:Custom=riscv-gcc-rvv
build_image:Custom=riscv-gcc-rvv-128
Xbuild_image:Custom=riscv-clang
Xbuild_image:Custom=riscv-clang-rvv …
```
=> RISC-V RVV 0.7: v_add/v_sub saturation and avoiding 64-bit VLEN

modules/gapi/cmake/DownloadADE.cmake, modules/ts/include/opencv2/ts.hpp
They jump out of GTest after XCode update to 13.1 on Mac M1.
Merge with https://github.com/opencv/opencv_contrib/pull/3434.
```
build_image:Custom=ubuntu-clang:20.04
buildworker:Custom=linux-1,linux-4
```
=> Supress tones of -Wdeprecated-copy warnings

3rdparty/openjpeg/openjp2/jp2.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47342
The read overflow triggered by reading `src[j]` in
```cpp
for (j = 0; j < max; ++j) {
dst[j] = src[j];
}
```
The max is calculated as `new_comps[pcol].w * new_comps[pcol].h`, however the `src = old_comps[cmp].data;` which may have different `w` and `h` dimensions.
The patch was contributed to the third party library openjpeg https://github.com/uclouvain/openjpeg/pull/1441
Normally I would suggest to update to openjpeg 2.5.1 when released, but there was no release in 4 months and from security point of view I suggest to make the hot fix for now and bump the version when available. The tracking issue was created - https://github.com/opencv/opencv/issues/23066
See details at …
=> Fix Heap-buffer-overflow READ in opj_jp2_apply_pclr

CMakeLists.txt, modules/core/CMakeLists.txt
`OPENCV_CONFIG_FILE_INCLUDE_DIR` is actually a configurable option, but the rules for some of the generated files are not following this. This PR is intending to fix this minor issue.
=> Change generated header file output location

3rdparty/libpng/CMakeLists.txt, modules/calib3d/test/test_cameracalibration.cpp, modules/flann/include/opencv2/flann/index_testing.h, modules/ml/src/kdtree.cpp, modules/ts/include/opencv2/ts.hpp, modules/video/test/test_optflowpyrlk.cpp
Backport of #23203
Backport of https://github.com/opencv/opencv_contrib/pull/3434
Merge with https://github.com/opencv/opencv_contrib/pull/3435
```
buildworker:Custom=linux-1,linux-4
```
=> Warning supression fix for XCode 13.1 and newer. Backport #23203

modules/imgproc/src/lsd.cpp
This is a replacement for https://github.com/opencv/opencv/pull/23052, where I made some mistakes with the branches at the end.
- It fixes the [nfa function](https://github.com/opencv/opencv/blob/a6b178a3d9f5c8df83df01d2bfe3ff53048391ea/modules/imgproc/src/lsd.cpp#L1074) which is missing the first log_gamma call compared with the function in the [binomial_nfa repository](https://github.com/rafael-grompone-von-gioi/binomial_nfa/blob/main/C99/log_binomial_nfa.c#L152).
- It also fixes the logic issue on [rect_nfa function](https://github.com/opencv/opencv/blob/a6b178a3d9f5c8df83df01d2bfe3ff53048391ea/modules/imgproc/src/lsd.cpp#L94), which had a logic issue on the way the pixels inside the rectangle were being checked.
With the changes to the rect_nfa function, now it checks the same pixels …
=> Fix rect_nfa (lsd)

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/cuda4dnn/primitives/matmul.hpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with:** https://github.com/opencv/opencv_extra/pull/1033
This PR tries to make `GEMM` can be supported with `transA` and `transB` in CUDA. It's a follow-up to https://github.com/opencv/opencv/pull/22882
`GEMM` onnx documentation: https://github.com/onnx/onnx/blob/main/docs/Operators.md#Gemm
Because `MatMul` can be seen as a specific case of `GEMM`, I put the `GEMM` into `MatMulOp`. This may make it possible to implement the whole GEMM operation: `αAB+βC` in the future.
```
```
=> DNN: make GEMM can be supported with transA and transB in CUDA

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/onnx/onnx_graph_simplifier.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/src/opencl/activations.cl, modules/dnn/test/test_onnx_importer.cpp
This PR adds the CPU and OCL kernels of GELU and GELU-Approximation layers.
Merge with https://github.com/opencv/opencv_extra/pull/1044
References:
- https://github.com/pytorch/vision/blob/main/torchvision/models/vision_transformer.py
- https://pytorch.org/docs/stable/generated/torch.nn.GELU.html
=> Add GELU layer for vision transformers

modules/core/include/opencv2/core/hal/intrin_sse.hpp
`ptr` may generate a `misaligned-pointer-use` warning with some sanitizers when cast to `int*`.
`memcpy()` it to the aligned `int tmp`.
`summary.py` of `run.py -t core` at 3.4 head and with patch gave this report: [opencv_summary_report.txt](https://github.com/opencv/opencv/files/10393334/opencv_summary_report.txt)
The geometric mean and average of the right-most column is 0.98. The median is 0.99.
I guess this "speed loss" comes from performance testing imprecision.
Thanks to @vrabaud for this fix.
=> Fix misaligned-pointer-use in intrin_sse.hpp

modules/gapi/samples/pipeline_modeling_tool.cpp, modules/gapi/samples/pipeline_modeling_tool/dummy_source.hpp, modules/gapi/samples/pipeline_modeling_tool/pipeline.hpp, modules/gapi/samples/pipeline_modeling_tool/pipeline_builder.hpp, modules/gapi/samples/pipeline_modeling_tool/utils.hpp
* Added `wait_mode` property for `source`. It has two supported options: `busy`/`sleep`. The reason for adding is that `busy` wait approach works more accurate than `sleep`.
* Report latency for every iteration as `double` instead of `int`. 
* Added `warm-up` iteration.
* Changed the format of reported statistics. Use one line representation to make it easier to parse via regex.
=> [G-API] Pipeline modeling tool: Refactor calculating performance statistics

modules/stitching/src/autocalib.cpp
Add missing denominator swap. See pictures below for before/after comparison. The function was used to create both images. Images were created by stitching two other images (I can provide source material for reproduction if needed). No other parameters were changed between two calls other than the proposed fix. Also tested on pinhole camera model.
Before fix:
After fix:
Related commit: https://github.com/opencv/opencv/commit/60e1eda1495ec7bc64b41220e92bcaf23ece05db
=> Fix focal length estimation from homography matrix

modules/features2d/include/opencv2/features2d.hpp, modules/features2d/src/sift.dispatch.cpp, modules/features2d/test/test_descriptors_regression.impl.hpp, modules/features2d/test/test_detectors_invariance.cpp, modules/features2d/test/test_detectors_invariance.impl.hpp, modules/features2d/test/test_invariance_utils.hpp
Fixing https://github.com/opencv/opencv/issues/23123
See also: https://github.com/vicsyl/dog_precision
Even though by detector scale invariance test for SIFT the constrains had to be relaxed for the test to pass, the change improved other test metrics in SIFT detector/descriptor/scale/rotation invariance tests. Even metrics for detector scale invariance test for SIFT are better after the change for different parameters. See my comment at [test_detectors_invariance.cpp](https://github.com/opencv/opencv/pull/23124/files/ceef3c3e79953572b04c769060894d16eebbae5d#diff-85bb8de4fd45cfaf437e085f60aa40a55ee3964a45c082044e3a851989f0937d) for more details. …
=> different interpolation by double image

modules/dnn/src/tflite/tflite_importer.cpp
relates #23161
`axis = 0` => `axis = 4` - invalid index of `remap` array.
=> dnn(tflite): fix wrong axis normalization

modules/videoio/src/cap_obsensor/obsensor_stream_channel_interface.hpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.cpp, modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp, modules/videoio/src/cap_obsensor_capture.cpp
[ About Femto Mega](https://orbbec3d.com/index/Product/info.html?cate=38&id=11)
Be able to open the depth and color stream of the Orbbec Femto Mega Camera
OBSensor：Fix the problem that takes too long to turn off the stream on Windows platform
OS | Compiler | Camera | Result
-- | -- | -- | --
Windows11 | (VS2022)MSVC17.3 | Femto Mega | Pass
Ubuntu22.04 | GCC11.2 | Femto Mega | Pass
=> videoio: add support for Orbbec Femto Mega RGB-D camera

modules/calib3d/src/calibration.cpp, modules/calib3d/test/test_undistort.cpp
Resolves https://github.com/opencv/opencv/issues/23304
Fixes the incorrect pixel grid
Switches type to double to avoid precision loss as all callers use doubles
=> Fix calib3d undistortion grid

modules/imgproc/src/stb_truetype.cpp
The overflow happens for INT_MAX so the code just needs to be moved down.
=> Fix signed integer overflow.

modules/python/src2/gen2.py, modules/python/src2/hdr_parser.py
Some functions can have arguments that marked with both `CV_OUT` and `CV_IN_OUT` modifiers. Example `Feature2D::compute`
```cpp
CV_WRAP virtual void compute( InputArray image,
CV_OUT CV_IN_OUT std::vector<KeyPoint>& keypoints,
OutputArray descriptors );
```
Solution: if argument marked as `CV_IN_OUT keep only '/IO' modifier and remove '/O' one.
fixes #23263
=> fix: remove extra '/O' modifier for '/IO' arguments

modules/core/include/opencv2/core/quaternion.inl.hpp
Fixes #23293
The PR is fixing the issue described in [Issue #23293 ](https://github.com/opencv/opencv/issues/23293)
=> Fixed strict type in slerp and spline; Fixed nlerp usage condition

modules/highgui/src/window_w32.cpp
Remove separator between 2 or more trackbars. This separator has zero thickness and creates bags in toolbar.
=> Remove separator between trackbars.

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/layer.cpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/blank_layer.cpp, modules/dnn/src/layers/concat_layer.cpp, modules/dnn/src/layers/const_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/flatten_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/lrn_layer.cpp, modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/src/layers/padding_layer.cpp, modules/dnn/src/layers/permute_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/layers/reshape_layer.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/layers/softmax_layer.cpp, modules/dnn/src/net_cann.cpp, modules/dnn/src/op_cann.cpp, modules/dnn/src/op_cann.hpp
Related issue: https://github.com/opencv/opencv_zoo/issues/136
Features added:
- Support operators with multiple output: ONNX Split.
- Support Slice without steps.
Bugs fixed:
- Wrong settings in ClipByValue (Relu6).
- Wrong calculation of pads in convolution layer (It is wrong generally but only fixed specifically for CANN for now).
=> dnn CANN backend: fix some bugs and add some features

modules/dnn/test/test_common.hpp, modules/dnn/test/test_onnx_conformance.cpp
Move `global_deny_list` out of `if` condition.
`global_deny_list` was set to that can be parsed correctly, but cannot run on any backend.
It should have nothing to do with `backend`.
For example: some bad case in the `global_deny_list` but not in the `vulkan_deny_list`, the Vulkan CI will fail with these cases.
=> DNN Test ONNX: Fix the logic of the test case

modules/dnn/src/layers/cpu_kernels/conv_winograd_f63.cpp
4 failed tests in open_test_dnn listed below:
* Test_Caffe_layers.Conv_Elu/0, where GetParam() = OCV/CPU
* Test_ONNX_layers.ConvResizePool1d/0, where GetParam() = OCV/CPU
* Test_TensorFlow_layers.tf_reshape_nhwc/0, where GetParam() = OCV/CPU
* Test_Torch_layers.net_inception_block/0, where GetParam() = OCV/CPU
In winofunc_AtXA_8x8_f32 and winofunc_BtXB_8x8_f32 implementation, incorrect input parameters cause tests failure.
Add four new different variables for the last four input parameters of v_transpose4x4 to fix bugs, and update related comments.
=> Fix bugs of test case failure

modules/dnn/src/net_impl_fuse.cpp
Bug #23351
The `Conv_Add` fusion strategy wants to bypass the biasLayerData(Add layer). But the strategy only works when its consumer size is 1.
=> DNN : fix bug in layer fusion

doc/tutorials/app/kinect_openni.markdown, modules/videoio/include/opencv2/videoio.hpp, modules/videoio/include/opencv2/videoio/legacy/constants_c.h, modules/videoio/misc/gen_dict.json, modules/videoio/test/test_video_io.cpp, samples/cpp/videocapture_openni.cpp
Merge with https://github.com/opencv/opencv_contrib/pull/3446
Related issue: https://github.com/opencv/opencv/issues/11810
=> remove flags of obsolete VideoCapture backends

samples/cpp/fitellipse.cpp
1). At least 5 points can fit an ellipse
2). The result of fitEllipse、 fitEllipseAMS、fitEllipseDirect maybe different,I think it's better to draw the different result,rather than "continue".
3). Need to check the size of boxAMS/boxDirect ,not the size of box,after fitEllipseAMS、fitEllipseDirect.
=> Optimize&Fix fitEllipse sample

modules/highgui/include/opencv2/highgui.hpp, modules/highgui/src/roiSelector.cpp
Related Issue : https://github.com/opencv/opencv/issues/23175
I've added a printNotice argument to `selectROI` (and it's overload) and `selectROIs` functions.
I've also updated the function declarations in `highgui.hpp`.
Tested by building locally.
=> added argument to print notice in `roiSelector.cpp`

modules/videoio/include/opencv2/videoio/legacy/constants_c.h, modules/videoio/src/cap_dshow.cpp
- [OK] I agree to contribute to the project under Apache 2 License.
- [OK] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [OK] The PR is proposed to the proper branch
- [OK] There is a reference to the original bug report and related work
https://github.com/opencv/opencv/issues/19621
https://github.com/opencv/opencv/issues/21408
before AWB setting
CAP_PROP_WHITE_BALANCE_BLUE_U: 2000
CAP_PROP_AUTO_WB: -1
after AWB disable setting
CAP_PROP_WHITE_BALANCE_BLUE_U: 2000
CAP_PROP_AUTO_WB: -1
after AWB enable setting
CAP_PROP_WHITE_BALANCE_BLUE_U: 2000
CAP_PROP_AUTO_WB: -1
after Manual WB(and Disable AWB) setting …
=> Support VideoCapture CAP_PROP_AUTO_WB and CV_CAP_PROP_WHITE_BALANCE_BLUE_U for DShow

modules/dnn/src/net_impl.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
Needed for generic applications such as benchmarking pipelines. So OpenCV can tell about the default input shapes specified in the models.
=> Propagate inputs info for ONNX and TFLite models

3rdparty/quirc/include/quirc.h, 3rdparty/quirc/src/decode.c, modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qrcode.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1046
Fixes  #23249, fixes  #23155, fixes #20724
Added quirc_flip() method to horizontally flip the data.
When the decoder fails to ECC the data we flip the image, and try one more time.
=> Added QR_Code data flip support, flip and retry after first ECC failure

doc/js_tutorials/js_assets/js_pose_estimation.html
doc/js_tutorials/js_assets/js_pose_estimation.html
=> Fix error of `POSE_PAIRS` in pose estimation doc

modules/ml/src/data.cpp
When using a sampleIdx Mat to limit the training samples to train on the current code will fail with an assert since it is checking that the index is < the length of the samples to train on instead of the available samples.
=> Fix for using sampleIdx to limit training data

modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/test/test_intrin_utils.hpp
relates #7175
relates #15738
discussion https://github.com/opencv/opencv/pull/23098#discussion_r1118052669
OpenCV SIMD backends:
<cut/>
```
Xforce_builders=Custom
Xbuild_image:Custom=riscv-gcc
Xbuild_image:Custom=riscv-gcc-rvv
Xbuild_image:Custom=riscv-clang
Xbuild_image:Custom=riscv-clang-rvv
test_timeout:Custom=600
```
=> core(simd): 64-bit integer EQ/NE without misused 64F guard

modules/gapi/test/gapi_fluid_resize_test.cpp
The Resize gives calculation deviation on ARM. So the Resize test tolerance should be increased up to 2.
Fix for issue:
https://github.com/opencv/opencv/issues/19122
<cut/>
```
Xforce_builders=Linux AVX2,Linux32,Win32,Custom,Custom Win,Custom Mac …
```
=> Increasing tolerance for Preproc4lpiTest set on ARM

doc/py_tutorials/py_setup/py_setup_in_windows/py_setup_in_windows.markdown
after copying the **cv2.pyd** file to the **site-packages** directory python interpreter shows error
**"ImportError: DLL load failed while importing cv2: The specified module could not be found."** when installing using pre-built binaries as discussed in the #22072 
file **opencv_world.dll** also need to be copied.
=> fix "ImportError: DLL load failed while importing cv2" while installing from pre-built binaries

modules/imgcodecs/include/opencv2/imgcodecs.hpp
This PR is for pre-work for https://github.com/opencv/opencv/issues/23397 .
Reason
--------
The current imwrite() was listing based on the input image (8/16/32/64, unsigned/siged/float). 
For this reason, it is not easy to describe specification changes for each format.
Therefore, I propose listing based on the output file. 
This allows us to change only the Encoder line that modifies the supported input image formats.
=> imgcodecs: update documentation for imwrite() to support images formats.

modules/highgui/src/window_cocoa.mm
Fixes https://github.com/opencv/opencv/issues/21401
Check keydown event characters length before returning the pressed character code
=> check keydown event characters length on macos

platforms/linux/riscv64-071-gcc.toolchain.cmake
* `CMAKE_*_FLAGS` contained excessive compiler flags
* `CMAKE_SYSTEM_PROCESSOR` was missing
* Used `CMAKE_*_FLAGS_INIT` ([cmake 3.7+](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS_INIT.html#variable:CMAKE_%3CLANG%3E_FLAGS_INIT))
Tested with the following configuration:
```
PATH=/opt/riscv64-linux-x86_64-20210618/bin:${PATH} \
cmake \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_TOOLCHAIN_FILE=/opencv/platforms/linux/riscv64-071-gcc.toolchain.cmake \
-DBUILD_SHARED_LIBS=OFF \
/opencv
```
=> RISC-V: fix hardcoded options in RVV 0.7.1 toolchain file

modules/python/src2/cv2.cpp, modules/python/src2/pycompat.hpp
Fixes #23059 
Fix reference counting error in registerNewType so it no longer double-steals sometimes.
Edit: Fixes bug, not just related.
=> Fix reference counting errors in registerNewType

modules/gapi/include/opencv2/gapi/opencv_includes.hpp, modules/gapi/include/opencv2/gapi/own/types.hpp
- Point3f was added to type traits but was missing in the "own" package; fixed.
Note to test the build you'd need to get & build ADE first:
```
$ git clone https://github.com/opencv/ade.git
$ mkdir ade_BUILD
$ cd ade_BUILD
$ cmake ../ade -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release
$ make
$ make install
```
After that:
```
$ mkdir gapi_BUILD
$ cd gapi_BUILD
$ cmake /path/to/opencv/modules/gapi -Dade_DIR=/path/to/ade_BUILD/install/share/ade -DCMAKE_BUILD_TYPE=Release
$ make
```
=> G-API: Fix compilation error in Standalone mode

doc/js_tutorials/js_assets/js_contours_begin_contours.html
In a JS example, arguments `rows` and `cols` in a call to `Mat.zeros` were switched. The correct order is `rows` then `cols`:
https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#a56daa006391a670e9cb0cd08e3168c99
=> Switch `rows` and `cols` in call to Mat.zeros

modules/videoio/src/cap_dshow.cpp
=> Fix OBS Virtual Camera capture.

modules/imgcodecs/src/grfmt_bmp.cpp, modules/imgcodecs/src/grfmt_bmp.hpp, modules/imgcodecs/test/test_grfmt.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1050
For 32 bits per pixel with 3 or 4 channel destination images, apply scale factor and mask to parse BMP files correctly
closes #23445 
=> bmp decoder fix scale factor and IMREAD_COLOR incorrect result

modules/core/include/opencv2/core/utility.hpp
The old documentation implies that the call is only valid for the next parallel region and must be called again if addtional regions should be affected as well.
=> core: improve doc for setNumThreads

modules/core/include/opencv2/core/hal/intrin.hpp, modules/dnn/src/layers/cpu_kernels/convolution.cpp
This patch is going to fix the incomplete compatibility layer by adding more compatibility functions into the HAL compatibility layer.
The HAL compatibility layer was introduced by #22179 when we supported the scalable RVV backend, which mainly includes some new universal intrinsic that have to be introduced in the RVV backend. And then with this HAL compatibility layer, we can use the new universal intrinsic in other non-scalable backends.
However, when the HAL compatibility layer is implemented, I used the compile-time wide universal intrinsic type (e.g. v_float32). It works fine most of the time, but the following special cases have problems: When using a specific narrow universal intrinsic type in a wide SIMD target. 
For example, in #22440, `v_add` for `v_float32x4` is called. It can …
=> Fix HAL compatibility layer

modules/dnn/src/layers/region_layer.cpp
Fix objectness (dstData[index + 4]) is not assigned if new_coords == 1.
=> Fix objectness is not assigned in dnn::region_layer

modules/gapi/src/backends/ie/giebackend.cpp
Since `IE backend` implements "streaming"  [`run(IInput&, IOutput&)`](https://github.com/opencv/opencv/blob/4.x/modules/gapi/src/compiler/gislandmodel.cpp#L387)method it must take care of propagating meta from inputs.
The handling implemented the same way as for the default `GIslandModel::run`: https://github.com/opencv/opencv/blob/4.x/modules/gapi/src/compiler/gislandmodel.cpp#L436-L440
Since `post` is done in `PostOutputs` / `PostOutputsList` callback functions, meta collected and moved to `IECallContext`.
=> [G-API] Handle meta from multiple inputs in IE backend

3rdparty/quirc/src/decode.c
Introduced in https://github.com/opencv/opencv/pull/23275
Buildbot report: https://pullrequest.opencv.org/buildbot/builders/4_x_ARMv7-lin/builds/100067/steps/compile%20release/logs/stdio
=> Fix build regression in Quirc

modules/imgproc/src/geometry.cpp
This PR fix warning in pointPolygonTest, remove unused variables
=> fix warning in pointPolygonTest

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Merge with test case: https://github.com/opencv/opencv_extra/pull/1053.
The attribute of `split` in `Split layer` has been moved from `attribute` to `input`.
Related link: https://github.com/onnx/onnx/blob/main/docs/Operators.md#inputs-1---2-12
The purpose of this PR is to support the `split` with input type.
=> DNN: support the split node of onnx opset >= 13

modules/objdetect/include/opencv2/objdetect/charuco_detector.hpp, modules/objdetect/misc/python/test/test_objdetect_aruco.py, modules/objdetect/src/aruco/charuco_detector.cpp
setcharucoparameters fails in python
This hack works meanwhile:
=> Fix python bindings for setCharucoParameters

modules/dnn/test/test_onnx_importer.cpp
Added tests with various sequence length and batch sizes
Test data: https://github.com/opencv/opencv_extra/pull/1057
=> Added LSTM and GRU tests for various batch and input length sizes

modules/imgproc/src/drawing.cpp
Added explicit cast to unsigned before doing the left shift.
This was caught by UBSan which reported things like:
drawing.cpp:361:22: runtime error: left shift of negative value -26214
drawing.cpp:383:22: runtime error: left shift of negative value -78642
<cut/>
```
build_image:Custom=riscv-gcc-rvv
test_timeout:Custom=600
```
=> Fixed undefined left shifting of negative number

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/misc/python/test/test_dnn.py, modules/dnn/src/dnn_utils.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_misc.cpp
The purpose of this PR:
1. Add new API `blobFromImageParam` to extend `blobFromImage` API. It can support the different datalayout (NCHW or NHWC), and letter_box.
2. ~~`blobFromImage` can output `CV_16F`~~
=> DNN: Add New API blobFromImageParam

modules/dnn/src/layers/cpu_kernels/convolution.cpp, modules/dnn/test/test_onnx_importer.cpp
Address https://github.com/opencv/opencv/issues/23465
Merge with test: https://github.com/opencv/opencv_extra/pull/1058
=> DNN: try to fix the sporadic crashes in perf_dnn

modules/dnn/src/layers/recurrent_layers.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
This PR addresses #21118 [issue](https://github.com/opencv/opencv/issues/21118). The problem is that the ONNX parser is unable to read the hidden state and cell state for single-layer LSTMs. This PR fixes the issue by updating the parser to correctly read hidden and cell states.
=> Fix ONNX parser for single-layer LSTM hidden and cell states

modules/core/src/ocl.cpp
Simple fix to handle OpenCL devices with the vendor name "Intel Inc." the same way as "Intel(R) Corporation" and "Intel"
=> Fix ocl::device::isIntel implementation

modules/dnn/perf/perf_layer.cpp, modules/dnn/src/layers/nary_eltwise_layers.cpp
This PR will fix #23278 
Current implement is a temp impl. I will try to make more eltwise broadcast cases support CUDA. 
The inference time of [model](https://github.com/opencv/opencv/files/10826659/model3.zip) is from **26.7651 ms** to **17.8416 ms**.
**perf_test result**
run this script to generate result
```shell
.\bin\opencv_perf_dnn.exe '--gtest_filter=CUDA/Layer_NaryEltwise.*/*:CUDA/Layer_NaryEltwise/*.*' --gtest_output=xml:../tmp/1th.xml --perf_threads=1
```
use this script to generate summary
```shell
python ../modules/ts/misc/summary.py -m min 1th.xml 0th.xml -o markdown
```
result
|Name of Test|0th|1th|1th vs 0th (x-factor)|
|NHWC_H::CUDA/Layer_NaryEltwise::CUDA/CUDA|39.003 (fallback to cpu)|17.936|2.17|
**Layer by layer data:**
- before being fixed
```shell …
```
=> DNN/CUDA: make 'abcd op 1b11' broadcast eltwise operator support cuda

modules/objdetect/include/opencv2/objdetect/aruco_board.hpp, modules/objdetect/misc/python/test/test_objdetect_aruco.py, modules/objdetect/src/aruco/aruco_board.cpp, modules/objdetect/src/aruco/charuco_detector.cpp, modules/objdetect/test/test_charucodetection.cpp
The problem was in python bindings in `void matchImagePoints(InputArrayOfArrays detectedCorners, InputArray detectedIds, OutputArray objPoints, OutputArray imgPoints)`. 
`detectedCorners` may include aruco marker corners as `vector<vector<Point2f>>` or `vector<Mat>`. Any `Mat` in `vector<Mat>` must have 4 rows for 4 corners for one marker (one marker has 4 corners).
`detectedCorners` may include Charuco corners as `vector<Point2f>` or `Mat`. Python bindings add extra dimension to `detectedCorners` and therefore `vector<Mat>` case is additionally  processed for charuco corners.
Until the PR merge, you can using custom `matchImagePoints()`:
```
def matchImagePoints(charuco_board, charuco_corners, charuco_ids):
objPoints = []
imgPoints = []
for i in range(0, len(charuco_ids)):
index = …
```
=> fix charuco matchImagePoints

modules/dnn/test/test_onnx_importer.cpp
Added test for covering this PR #23475 fixing the issue [#21118](https://github.com/opencv/opencv/issues/21118) where functionality for hidden states as inputs was supported
Test data lives here: #[1062](https://github.com/opencv/opencv_extra/pull/1062)
=> Added test for LSTM without hidden state initialisation

cmake/android/android_gradle_projects.cmake, modules/java/android_sdk/build.gradle.in
Hello,
Android Gradle Plugin version 8.0 is asking for namespace. This is become mandatory and after I update my AGP to 8.0, I got this error 
```
Namespace not specified. Please specify a namespace in the module's build.gradle file like so:
android {
namespace 'com.example.namespace'
}
If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.
```
This change fix this future releases. However I am not sure how opencv wants to user namespace I used "org.opencv" if there is a different namespace please let me know so I can changed that too. Also should I add …
=> AGP 8.0 build.gradle namespace and aidl buildFeature requirement added

modules/gapi/src/backends/onnx/gonnxbackend.cpp, modules/gapi/test/infer/gapi_infer_onnx_test.cpp
- Existing tests pass with the ONNX models mentioned in tests.
- Building instruction is up-to-date: https://github.com/opencv/opencv/wiki/Graph-API#building-with-microsoft-onnx-runtime-support
- Testing instruction was updated with specific models required for tests: https://github.com/opencv/opencv/wiki/Graph-API#building-with-microsoft-onnx-runtime-support
=> Bump supported ONNX RT version to 1.14.1

modules/core/include/opencv2/core/operations.hpp
=> don't ignore documentation for cv::format in doxygen

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn_common.hpp, modules/dnn/src/model.cpp, modules/dnn/test/test_model.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1011
The followings are the purpose of the PR:
1. Let `blobFromImage` support `Scalar` scale to feed the requirement of Standard Deviation value.
2. more stable DB text detection API, the old post-processing will get assert errors when `length == 0.;`. [The related code part](https://github.com/opencv/opencv/blob/4.x/modules/dnn/src/model.cpp#L1461).
3. Output the correct confidence or score instead of always being **1.**.
4. Support PP-OCR-v2 and PP-OCR-v3 DB models. The original inference code can be found [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/infer/predict_det.py#L48-L51).
[Related regression test model](https://github.com/opencv/opencv_extra/pull/1011).
See details at …
=> DNN: More stable DB text detection API

modules/objdetect/include/opencv2/objdetect/aruco_board.hpp, modules/objdetect/src/aruco/aruco_board.cpp, modules/objdetect/test/test_aruco_utils.cpp, modules/objdetect/test/test_aruco_utils.hpp, modules/objdetect/test/test_charucodetection.cpp
Add support for certain ChArUco board patterns as they had been generated with OpenCV contrib version prior 4.6.0.
The pull request adds a `setLegacyParameter(bool)` method to the Charuco class to allow switching to the old board design as described in https://github.com/opencv/opencv/issues/23152.
Default setting for this parameter is `false´ to remain compatible with OpenCV contrib 4.6.0 and OpenCV 4.7.0.
=> ChArUco pre460 pattern support

doc/py_tutorials/py_calib3d/py_depthmap/py_depthmap.markdown
Explain parameter usage as well.
=> (docs) Depthmap py_tutorial: add reference to cv.StereoBM class documentation 

modules/videoio/src/cap.cpp, modules/videoio/src/videoio_registry.cpp, modules/videoio/src/videoio_registry.hpp
Added list of deprecated backends, which not supported by opencv anymore. This needs to give for user more information about chosen backend, when VideoCapture failed trying to use chosen by user  backend. 
=> 4.x deprecated VideoCapture backends

modules/objc/generator/gen_objc.py
Fixes issue blocking #23264
I think at some point I was trying to solve an issue with conflicting class names by appending the module name to the class name. This resulted in problems where the class with the conflicting name was later used as a base class.
Whatever the original problem - I have confirmed that this change has no impact on the current Objective-C wrappers for modules in both **opencv** and **opencv_contrib**
=> Fix Objective-C generator handling of base class names

modules/highgui/src/window_QT.cpp
For dark Qt themes, it is hard to read the pixel color information on the bottom left, like the coordinates or RGB values. This PR proposes a way on how the dynamically sets the font colors based on the system's theme.
Original Example:
With patch:
For Windows, nothing is changed (tested on a windows 11 system), because the font color is #000000 when using the default Qt theme.
=> Fixes pixel info color font for dark Qt themes

modules/dnn/src/cuda/eltwise_ops.cu, modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/test/test_layers.cpp
Merged after https://github.com/opencv/opencv/pull/23557
Fix yolo regression error mentioned in https://github.com/opencv/opencv/commit/e3e1f704a4c59a38747102d586925e05de1729aa#commitcomment-110475963
After fix this bug, the brute force test mentioned in https://github.com/opencv/opencv/issues/23556 will all passed with CUDA. (different shape broadcast will fallback to cpu)
Test is added in PR https://github.com/opencv/opencv/pull/23557
=> DNN/CUDA: Solve the bug of same shape broadcast with CUDA

modules/videoio/src/cap_ffmpeg_impl.hpp
resolves #9455
related #3225
* Use different counters for wrong packets recieved by demuxer and errors from decoder
* Allow modifying these counters via environment variables `OPENCV_FFMPEG_READ_ATTEMPTS`/`OPENCV_FFMPEG_DECODE_ATTEMPTS`
* Added logging when reading breaks at one of error limits
Notes:
* I've been able to reproduce original issue with a video file with 14 total streams (video + audio + subtitles), at some point in the video only packets from the last stream are being sent by the demuxer, thus exceeding our limit. For my specific video total number of packets from wrong stream was about 2700. I've chosen 4096 as default value.
* Default limit of decoding attempts is quite low, because I'm not sure in which cases it can be exceeded (network stream?). I tried to read 8k video …
=> videoio/FFmpeg: increased packet read attempt limit, allow configuring it

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn_common.hpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/cpu_kernels/conv_block.simd.hpp, modules/dnn/src/layers/cpu_kernels/convolution.cpp, modules/dnn/src/layers/cpu_kernels/convolution.hpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/net_impl.cpp, modules/dnn/src/net_impl_backend.cpp, modules/dnn/src/registry.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_common.hpp, modules/dnn/test/test_common.impl.hpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_googlenet.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_model.cpp, modules/dnn/test/test_onnx_conformance.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
This PR proposes to support FP16 backend in Convolution. 
For now, we only support FP16 at ARM aarch64.
In addition to adding fp16, I also added `seperateIm2col` optimization in this patch.
```
Net net = readNet(modelPath);
net.setPreferableTarget(DNN_TARGET_CPU_FP16);
net.setInput(blob);
Mat output = net.forward();
```
| Task | Status | Remarks |
|:-------:|:--------:|:------------:|
| Convolution 2D FP16 | :heavy_check_mark: | Done |
| Winograd FP16 | Because the current modification has reached 2k lines, winograd fp16 will be completed in the next PR. |  |
| Accuracy Test | :heavy_check_mark: | Done |
| Performance Test | :heavy_check_mark: | Done |
| Compiler bug | :heavy_check_mark: | Done |
**Test on M1 chip, 4 threads.**
| Model Name | FP32 (Conv+Wino) | Conv(FP16) + Wino(FP 32) | …
=> DNN: FP16 support on Convolution 2D

modules/dnn/src/layers/recurrent_layers.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
This PR contains necessary changes to support `layout` attribute. This attributes is present in [ONNX](https://github.com/onnx/onnx/blob/main/docs/Operators.md#lstm) and [Torch](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html#lstm) (in touch it is name as `batch_first=True`) libraries. When `layout = 1` input to LSTM layer is expected to have batch dimension first -> `[batch_size, sequence_length, features]` vs `layout = 0` - default `[sequence_length, batch_size, features]`
Test data and data generator for PR located here [#1063](https://github.com/opencv/opencv_extra/pull/1063)
=> LSTM ONNX Layout Attribute Support 

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
- [] There is a reference to the original bug report and related work
=> Add assert to check if layer input size is not empty

modules/imgproc/src/resize.cpp, modules/imgproc/test/test_resize_bitexact.cpp
resolves https://github.com/opencv/opencv/issues/22204
related: https://github.com/opencv/opencv/issues/9096#issuecomment-1551306017
/cc @Yosshi999
=> Fix even input dimensions for INTER_NEAREST_EXACT

modules/videoio/src/cap_ffmpeg_impl.hpp
Remove locks added in https://github.com/opencv/opencv/pull/9006 from `VideoCapure/VideoWriter::open()` when using the FFMpeg backend to fix https://github.com/opencv/opencv/issues/20114.
Locks are removed if `OPENCV_FFMPEG_IS_THREAD_SAFE==true`.
Should I add a test?  If so it would need to be skipped on Windows to avoid build bot failures and it may be confusing when it fails on user's machines?
=> Videoio: FFMpeg remove locks from `VideoCapure/VideoWriter::open()` to fix 20114

doc/tutorials/calib3d/camera_calibration/camera_calibration.markdown, samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp, samples/cpp/tutorial_code/calib3d/camera_calibration/in_VID5.xml
Added opportunity to calibrate camera using ChArUco board pattern in /samples/cpp/tutorial_code/calib3d/camera_calibration/caera_calibration.cpp 
- [] There is a reference to the original bug report and related work
=> add ChArUco board pattern into calib3d/camera_calibration

modules/dnn/src/layers/region_layer.cpp, modules/dnn/test/test_darknet_importer.cpp
resolves https://github.com/opencv/opencv/issues/19781
```
```
=> Fix Region layer with OpenVINO in case of different width/height

modules/dnn/src/layers/cpu_kernels/convolution.cpp
@zihaomu Our CI environment started failing after you merged this [commit](https://github.com/opencv/opencv/commit/5229312ad2a4fbf9a6abfd6490b265c39587e6f7). 
```
/build/build_cuda/3p/opencv/linux-x64/ubuntu22.04/Debug/modules/dnn/src/layers/cpu_kernels/convolution.cpp: In function 'void cv::dnn::packData8(char*&, float*&, int&, int&, int&, const int*, int, int, int)':
/build/build_cuda/3p/opencv/linux-x64/ubuntu22.04/Debug/modules/dnn/src/layers/cpu_kernels/convolution.cpp:448:43: error: 'CONV_NR' was not declared in this scope; did you mean 'CONV_3D'?
448 |                 vx_store(inpbufC_FP32 + k*CONV_NR, vx_load(inptrInC + k1));
|                                           ^~~~~~~
|                                           CONV_3D
```
See details at …
=> Build fix for AVX 256

modules/imgproc/include/opencv2/imgproc.hpp
Resolves #22975
Completed the sentence as per the suggestion given in the issue #22975
=> Fix truncated sentenced in boxPoints documentation #22975

modules/java/generator/gen_java.py
I've met a javadoc generation error on Ubuntu 22:
```
[javadoc] /build-docs/modules/java/jar/opencv/java/org/opencv/calib3d/Calib3d.java:11320: error: element not closed: ul
[javadoc]      * <ul>
[javadoc]        ^
[javadoc] /build-docs/modules/java/jar/opencv/java/org/opencv/calib3d/Calib3d.java:11348: error: unexpected end tag: </li>
[javadoc]      *   </li>
[javadoc]          ^
[javadoc] /build-docs/modules/java/jar/opencv/java/org/opencv/calib3d/Calib3d.java:11349: error: unexpected end tag: </ul>
[javadoc]      * </ul>
[javadoc]        ^
```
Reason: a list of items in the parameter description does not generate good html, `</ul>` and `</li>` elements are added after the following `@param` item. It looks as follows and my version of javadoc (17.0.6) fails:
```
@param first param
<ul> …
```
=> Fix javadoc generation

modules/core/misc/python/pyopencv_core.hpp, modules/python/test/test_misc.py
resolves https://github.com/opencv/opencv/issues/23628
```python
t = cv.CV_MAKETYPE(cv.CV_32F, 4)
```
=> CV_MAKETYPE Python binding

modules/dnn/src/int8layers/softmax_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Resolves https://github.com/opencv/opencv/issues/23636.
Merge with https://github.com/opencv/opencv_extra/pull/1064.
This PR maps the QLinearSoftmax (from com.microsoft domain) to SoftmaxInt8 in dnn along with some speed optimization.
Todo:
=> Support ONNX operator QLinearSoftmax in dnn

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/net_impl_fuse.cpp
Since we have supported the Convolution 1D, 2D, and 3D, we can perform the `Conv_Add` trick for all types of Convolution.
=> DNN: Remove unnecessary flags for convolution 

modules/core/include/opencv2/core/optim.hpp, modules/core/src/lpsolver.cpp, modules/core/test/test_lpsolver.cpp
Partially solves infeasible results issue https://github.com/opencv/opencv/issues/12343
Solution extracted from abandoned PR https://github.com/opencv/opencv/pull/19530
=> Added final constrants check to solveLP to filter out flating-point numeric issues

modules/objc/generator/gen_objc.py, modules/objc/generator/templates/objc_module_body.template, modules/objc/generator/templates/objc_module_header.template
Origin: https://github.com/opencv/opencv/pull/18940
Ported back patch to support module names that start from a digit. The backport is done to reduce conflicts during regular 4.x -> 5.x merge
=> ObjC naming backport from 5.x

modules/core/src/norm.cpp, modules/python/src2/cv2_convert.cpp, modules/python/src2/cv2_numpy.cpp, modules/python/test/test_norm.py
* Also, fixes `cv::norm` with `NORM_INF` and `CV_16F`
resolves https://github.com/opencv/opencv/issues/23687
=> Import and export np.float16 in Python

modules/videoio/src/cap_ffmpeg_impl.hpp
Related PR: https://github.com/opencv/opencv/pull/23669
Issue: https://github.com/opencv/opencv/issues/21006
=> backport to 3.4: Fixed FPS computation on some videos for FFmpeg backend

modules/imgproc/perf/perf_intelligent_scissors.cpp
Adding basic performance test that can be used before and after the #21959 changes etc. as per @asmorkalov's https://github.com/opencv/opencv/pull/21959#issuecomment-1565240926 comment.
=> imgproc: add basic IntelligentScissorsMB performance test

modules/imgproc/src/filter.simd.hpp
Although unsigned overflow is well-defined by the C++ standard, it is often unintentional or confusing and so UBSan has an option to warn about it.
It warned here:
`Addition of unsigned offset to 0x00017fd31b97 overflowed to 0x00017fd30c97`
In my own use of OpenCV at least, this is the only case of unsigned overflow.
I reformunated the pointer arithmetic to either add or subtract based on the sign of y. It's easier to understand this way vs always adding and wrapping around to an address *smaller* than the base address.
=> Reformulated some pointer arithmetic to avoid (unsigned) overflow

modules/dnn/src/onnx/onnx_importer.cpp
Addition of normalize_axis to ONNXImporter::parseSqueeze to prevent a bug when the attribute _axes_ contains negative values. Negative values are part of the ONNX standard: https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Squeeze-11
=> Addition of normalize_axis to ONNXImporter::parseSqueeze

modules/core/include/opencv2/core/bindings_utils.hpp, modules/python/src2/gen2.py, modules/python/src2/hdr_parser.py, modules/python/test/test_misc.py
Reverted named argument handling from #19156.
Ported new solution from #23224
The port is required to harmonize 4.x -> 5.x merges.
=> Re-implement named parameters bindings for Python

modules/imgproc/src/intersection.cpp, modules/imgproc/test/test_intersection.cpp
_rotatedRectangleIntersection() can be (statically) customized to use double instead of float for better accuracy
this is a proposal for experimentation around #23546
for better accuracy, _rotatedRectangleIntersection() could use double. It will still return cv::Point2f list for backward compatibility, but the inner computations are controlled by a typedef
=> better accuracy for _rotatedRectangleIntersection() (proposal for #23546)

3rdparty/openjpeg/CMakeLists.txt
Address: https://github.com/opencv/opencv/issues/23710
Warning introduced in https://github.com/opencv/opencv/pull/23682
Technically, there is function prototype in openjp2/ht_dec.c:1096. It's only place where the function is used. I added warning suppression.
=> Fixed OpenJPEG 2000 compiler warning for some GCC versions (#23710)

modules/objdetect/include/opencv2/objdetect.hpp, modules/objdetect/misc/objc/gen_dict.json, modules/objdetect/perf/perf_qrcode_pipeline.cpp, modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qr_utils.hpp, modules/objdetect/test/test_qrcode.cpp, samples/cpp/qrcode.cpp
Using Aruco to detect finder patterns to search QR codes.
TODO (in next PR):
- add single QR detect (update `detect()` and `detectAndDecode()`)
- need reduce full enumeration of finder patterns
- need add finder pattern info to `decode` step
- need to merge the pipeline of the old and new algorithm
[Current results:](https://docs.google.com/spreadsheets/d/1ufKyR-Zs-IGXwvqPgftssmTlceVjiQX364sbrjr2QU8/edit#gid=1192415584)
+20% total detect, +8% total decode in OpenCV [QR benchmark](https://github.com/opencv/opencv_benchmarks/tree/develop/python_benchmarks/qr_codes) 
78.4% detect, 58.7% decode vs 58.5 detect, 50.5% decode in default
[main.py.txt](https://github.com/opencv/opencv/files/10762369/main.py.txt)
add new info to [google docs](https://docs.google.com/spreadsheets/d/1ufKyR-Zs-IGXwvqPg …
=> Add detect qr with aruco

modules/stitching/src/blenders.cpp
Removed passing try_gpu parameter to FeatherBlender constructor because it only has sharpness parameter and does not support GPU branch,
=> Fix missuse of try_gpu in stitching/FeatherBlender

modules/imgproc/src/color_hsv.simd.hpp
related PR #22520
* `mhls3` is read outside of array `interTmpM` (3 elements), it is not used anywhere
* ~replacing `max_nlanes` with `vlanes` for array size is still in question, I think it should be OK~ It was not OK :smiley:
=>  imgproc/cvtColor: fixed invalid read in BGR2HLS

modules/imgproc/test/test_intelligent_scissors.cpp
Preparation for the #21959 changes as per @asmorkalov's https://github.com/opencv/opencv/pull/21959#issuecomment-1560511500 suggestion.
=> imgproc: add contour values check to IntelligentScissorsMB tests

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
This PR fixes issue mentioned in [#23663](https://github.com/opencv/opencv/issues/23663) 
Merge with https://github.com/opencv/opencv_extra/pull/1067
=> Assertion Fix in Split Layer

modules/imgproc/src/intelligent_scissors.cpp
When reading the code I noticed a `TODO(opt)` comment, this pull request is for that.
https://github.com/opencv/opencv/blob/4.5.5/modules/imgproc/src/intelligent_scissors.cpp#L628
```
float cost = cost_q + local_cost(q, r);  // TODO(opt): compute partially until cost < cost_r
```
* https://github.com/opencv/opencv/pull/21941 and this pull request change the same non-test files. However, the changes themselves don't overlap i.e. there should be no merge conflicts.
* Based on https://github.com/opencv/opencv/wiki/Branches#which-branch-should-i-target-my-pr this pull request here could be for 3.4 instead of 4.x branch. However, it is for 4.x since 3.4 doesn't have the intelligent scissors code.
```
$ export OPENCV_TEST_DATA_PATH=../opencv_extra/testdata
$./bin/opencv_perf_imgproc …
```
=> imgproc: optimise local cost computation in IntelligentScissorsMB::buildMap

modules/dnn/src/layers/cpu_kernels/conv_winograd_f63.cpp, modules/dnn/src/layers/cpu_kernels/convolution.cpp, modules/dnn/src/layers/cpu_kernels/convolution.hpp
Address https://github.com/opencv/opencv/issues/23760
The patch aims to add a runtime check for X86 platform without AVX(2).
=> DNN: fix bug for X86 winograd

modules/stitching/include/opencv2/stitching/detail/motion_estimators.hpp, modules/stitching/src/motion_estimators.cpp
Fixing a typo in file `modules/stitching/include/opencv2/stitching/detail/motion_estimators.hpp` and `motion_estimators.cpp`, since the correct plural of "path" is "paths", not "pathes".
=> fixing typo in stitching parameter names

platforms/ios/cmake/Toolchains/common-ios-toolchain.cmake
=> build(ios): disable workaround for CMake 3.25.1+

cmake/templates/opencv_run_all_tests_unix.sh.in, doc/py_tutorials/py_feature2d/py_fast/py_fast.markdown, modules/calib3d/src/usac/quality.cpp, modules/objdetect/include/opencv2/objdetect/aruco_board.hpp, platforms/scripts/pylintrc
MSVS compiler always gives a warning of `“”`. The `“”` should only be used in Chinese. So, I think we should replace them with `""`.
[warning C4819](https://stackoverflow.com/questions/10501634/warning-c4819-how-to-find-the-character-that-has-to-be-saved-in-unicode)
=> remove unsupported unsupported unicode “”

modules/dnn/misc/python/test/test_dnn.py, modules/python/src2/cv2_convert.cpp
resolves https://github.com/opencv/opencv/issues/23764
I don't think that `scalefactor` as a `Scalar` is a good idea. Is there models with different scales for channels?
=> Change Scalar assignment in Python from single value

modules/gapi/include/opencv2/gapi/infer/ie.hpp, modules/gapi/src/backends/ie/giebackend.cpp, modules/gapi/test/infer/gapi_infer_ie_test.cpp
=> G-API: Expose explicit preprocessing for IE Backend

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
resolves https://github.com/opencv/opencv/issues/23745
merge with extra: https://github.com/opencv/opencv_extra/pull/1070
=> Consider half pixel mode in ONNX resize

modules/python/src2/typing_stubs_generation/ast_utils.py, modules/python/src2/typing_stubs_generation/generation.py, modules/python/src2/typing_stubs_generation/nodes/__init__.py, modules/python/src2/typing_stubs_generation/nodes/node.py, modules/python/src2/typing_stubs_generation/nodes/type_node.py, modules/python/src2/typing_stubs_generator.py
Enum names exist only during type checking.
During runtime they should be denoted as named integral types
This patch fixes circular import issue introduced by #23798.
Before patch `TermCriteria` was defined as follows:
```python
TermCriteria = typing.Tuple[cv2.TermCriteria_Type, int, float]
"""Any type providing sequence protocol is supported"""
```
which works fine during type checking, but introduces runtime failure:
```python
>>> import cv2
...
TermCriteria = tuple[cv2.TermCriteria_Type, int, float]  # Any type providing sequence protocol is supported
^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'cv2' has no attribute 'TermCriteria_Type' (most likely due to a circular import)
```
Generated `__init__.py` after patch will hide `cv2.TermCriteria_Type` enumeration by …
=> fix: typing module enums references

modules/python/src2/typing_stubs_generation/generation.py, modules/python/src2/typing_stubs_generation/nodes/namespace_node.py
- Re-export native submodules of cv2 package level.
- Re-export  manually registered  symbols like cv2.mat_wrapper.Mat
`__init__.pyi` file import section after patch
```python
from cv2 import Error as Error
from cv2 import aruco as aruco
from cv2 import cuda as cuda
from cv2 import detail as detail
from cv2 import dnn as dnn
from cv2 import fisheye as fisheye
from cv2 import flann as flann
from cv2 import gapi as gapi
from cv2 import ipp as ipp
from cv2 import ml as ml
from cv2 import ocl as ocl
from cv2 import ogl as ogl
from cv2 import parallel as parallel
from cv2 import samples as samples
from cv2 import segmentation as segmentation
from cv2 import utils as utils
from cv2 import videoio_registry as videoio_registry
from cv2.mat_wrapper import Mat as Mat
```
Resolves: #23777
See …
=> feat: re-export symbols to cv2 level

modules/python/src2/typing_stubs_generation/generation.py
Solves:
```
Python 3.9.5 (default, Nov 23 2021, 15:27:38) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
File "<stdin>", line 1, in <module>
File "/home/ksenia/Projects/opencv-build-3.9/install/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
bootstrap()
File "/home/ksenia/Projects/opencv-build-3.9/install/lib/python3.9/site-packages/cv2/__init__.py", line 175, in bootstrap
if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
File "/home/ksenia/Projects/opencv-build-3.9/install/lib/python3.9/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
py_module = importlib.import_module(module_name)
File "/usr/lib/python3.9/importlib/__init__.py", line …
```
=> Force mat_wrapper import to satisfy dependencies for MatLike alias

modules/imgproc/src/distransform.cpp, modules/imgproc/test/test_distancetransform.cpp
This attempts to fix the following bug which was caused by storing squares of large integers into 32-bit floating point variables:
https://github.com/opencv/opencv/issues/22732
=> Fix distransform to work with large images

modules/python/src2/typing_stubs_generation/generation.py, modules/python/src2/typing_stubs_generation/nodes/type_node.py
Correct fix for #23821
Apart adding `import cv2.mat_wrapper` adds `import cv2.gapi.wip.draw` import to `cv2/typing/__init__.py`
`cv2/typing/__init__.py` imports after fix:
```python
import cv2
import cv2.dnn
import cv2.gapi.wip.draw
import cv2.mat_wrapper
import numpy
import typing
```
=> fix: AST nodes required usage imports

modules/python/src2/typing_stubs_generation/generation.py, modules/python/src2/typing_stubs_generation/nodes/type_node.py, modules/python/src2/typing_stubs_generation/predefined_types.py
This patch introduces conditional alias definition.
- Fixes compatibility with NumPy versions < 1.20 and Python < 3.9
- Updates enums handling to utilise introduced `ConditionalAliasTypeNode `
Generated `cv2/typing/__init__.py` content after patch:
```python
import cv2.mat_wrapper
import numpy
import sys
import typing
if numpy.lib.NumpyVersion(numpy.__version__) > "1.20.0" and sys.version_info >= (3, 9):
NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
else:
NumPyArrayGeneric = numpy.ndarray
if numpy.lib.NumpyVersion(numpy.__version__) > "1.20.0" and sys.version_info >= (3, 9):
NumPyArrayFloat32 = numpy.ndarray[typing.Any, numpy.dtype[numpy.float32]]
else:
NumPyArrayFloat32 = numpy.ndarray
if numpy.lib.NumpyVersion(numpy.__version__) > "1.20.0" and …
```
=> fix: conditionally define generic NumPy NDArray alias

modules/core/include/opencv2/core/mat.hpp
Address https://github.com/opencv/opencv/issues/21125
OpenCV does not provide any example that uses multi-dimensional reshape for now to reference.
=> Document parameters of multi-dimentional reshape

modules/python/src2/typing_stubs_generation/api_refinement.py, modules/python/src2/typing_stubs_generation/ast_utils.py, modules/python/src2/typing_stubs_generation/generation.py, modules/python/src2/typing_stubs_generation/nodes/function_node.py, modules/python/src2/typing_stubs_generator.py
These patch introduce a customisation point to manually refine autogenerated stubs to fulfil conventions that are not expressed in C++ API.
Example: functions accepting "empty" arguments in their C++ API accepts `None` in Python (`cv::resize` accepts empty `cv::Size` as `dsize`).
- Mark `resize` `dsize` and `calcHist` `mask` arguments as optional regardless of their C++ API optionality
Before patch
```python
@typing.overload
def resize(src: cv2.typing.MatLike, dsize: cv2.typing.Size, dst: cv2.typing.MatLike | None = ..., fx: float = ..., fy: float = ..., interpolation: int = ...) -> cv2.typing.MatLike: ...
@typing.overload
def resize(src: UMat, dsize: cv2.typing.Size, dst: UMat | None = ..., fx: float = ..., fy: float = ..., interpolation: int = ...) -> UMat: ...
@typing.overload
def …
```
=> feat: manual refinement for Python API definition

doc/tutorials/app/orbbec_astra.markdown
Resolves the documentation issue from https://github.com/opencv/opencv/issues/23579.
Orbbec is moving to support UVC directly so they do not provide the old `install.sh` for OpenNI SDK >= 2.3.0.86. Also in their new release of OpenNI SDK, paths of include headers and libraries are changed. Changing our cmake script for this change does not make sense since we cannot make this kind of change everytime they update. So just added a subsection providing `install.sh` for users as a workaround on our side.
@Lecrapouille You may also take a look at this pull request.
=> fix broken links and outdated information for documentation of Orbbec camera

3rdparty/ffmpeg/ffmpeg.cmake
- FFmpeg version: 3.4.13
- OpenH264 version 1.8.0
- libvpx version 1.13.0
Previous update for 3.4: https://github.com/opencv/opencv/pull/21295
```
```
=> FFmpeg/3.4: update FFmpeg wrapper 2023.6

modules/gapi/CMakeLists.txt
Need to register external dependency if dnn module is not used:
```
-DWITH_OPENVINO=ON -DBUILD_opencv_dnn=OFF -DBUILD_SHARED_LIBS=OFF
```
Similar to https://github.com/opencv/opencv/blame/1db1422fbdc1a03d1523b50ad9b05d72cbd39616/modules/dnn/CMakeLists.txt#L241
=> G-API: fix static build with OpenVINO

modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/test/test_ffmpeg.cpp
Address #22876 by adding a `CAP_PROP_CODEC_FOURCC` to the `VideoCapture` FFmpeg backend.
Merge with https://github.com/opencv/opencv_contrib/pull/3488
=> `VideoCapture`: change `CAP_PROP_FOURCC` to fix #22876

modules/gapi/include/opencv2/gapi/gkernel.hpp, modules/gapi/include/opencv2/gapi/infer.hpp, modules/gapi/include/opencv2/gapi/streaming/desync.hpp, modules/gapi/include/opencv2/gapi/streaming/meta.hpp, modules/gapi/misc/python/python_bridge.hpp, modules/gapi/misc/python/test/test_gapi_sample_pipelines.py, modules/gapi/src/backends/ov/govbackend.cpp, modules/gapi/src/compiler/gmodelbuilder.cpp, modules/gapi/test/internal/gapi_int_gmodel_builder_test.cpp
The PR is going to fix several problems:
1. Major: `GKernel` doesn't hold `kind` for its outputs. Since `GModelBuilder` traverse graph from outputs to inputs once it reaches any output of the operation it will use its `kind` to create  `Data` meta for all operation outputs. Since it essential for `python` to know `GTypeInfo` (which is `shape` and `kind`) it will be confused.
Consider this operation:
```
@cv.gapi.op('custom.square_mean', in_types=[cv.GArray.Int], out_types=[cv.GOpaque.Float, cv.GArray.Int])
class GSquareMean:
@staticmethod
def outMeta(desc):
return cv.empty_gopaque_desc(), cv.empty_array_desc()
```
Even though `GOpaque` is `Float`, corresponding metadata might have `Int` kind because it might be taken from `cv.GArray.Int`
so it will be a problem if one of the outputs of …
=> G-API: Fix incorrect OpaqueKind for Kernel outputs

modules/objdetect/include/opencv2/objdetect/charuco_detector.hpp, modules/objdetect/misc/python/test/test_objdetect_aruco.py, modules/objdetect/src/aruco/charuco_detector.cpp
`detectDiamonds` cannot be called from python, reproducer:
```
detector = cv.aruco.CharucoDetector(
cv.aruco.CharucoBoard(
(3, 3), 200.0, 100.0,
cv.aruco.getPredefinedDictionary(cv.aruco.DICT_4X4_250)
)
)
image = np.zeros((640, 480, 1), dtype=np.uint8)
res = detector.detectDiamonds(image)
print(res)
```
The error in `detectDiamonds` API fixed by replacing `InputOutputArrayOfArrays markerIds` with `InputOutputArray markerIds`.
=> Fix detect diamonds api

3rdparty/ffmpeg/ffmpeg.cmake, modules/videoio/test/test_ffmpeg.cpp
Related PR in 3rdparty: https://github.com/opencv/opencv_3rdparty/pull/77
Previous FFmpeg Update: https://github.com/opencv/opencv/pull/23035
Software versions:
- FFmpeg version n4.4.4
- OpenH264 version 1.8.0
- libVPX version 1.13.0
- libAOM version 3.6.1
```
```
=> FFmpeg/4.x: update FFmpeg wrapper 2023.6

modules/core/src/parallel.cpp
Single-case tested with success on Windows 11 with MinGW-w64 Standalone GCC v13.1.0 while building OpenCV 4.7.0
Brought from #23849 
=> Add `pthread.h` Inclusion if `HAVE_PTHREADS_PF` is defined

modules/objdetect/src/aruco/charuco_detector.cpp, modules/objdetect/test/test_charucodetection.cpp
Added charuco board checking to avoid detection of incorrect board.
Fixes #23517
=> add charuco board check

modules/calib3d/src/usac/degeneracy.cpp, modules/calib3d/src/usac/dls_solver.cpp, modules/calib3d/src/usac/essential_solver.cpp, modules/calib3d/src/usac/estimator.cpp, modules/calib3d/src/usac/fundamental_solver.cpp, modules/calib3d/src/usac/homography_solver.cpp, modules/calib3d/src/usac/pnp_solver.cpp
Fix for https://github.com/opencv/opencv/pull/23078
=> Get rid of unsafe raw pointers to Mat object in USAC

samples/python/calibrate.py
- Fixed width and height swap in board size
- Fixed defaults in command line hint
- Fixed board visualization for Charuco case
- Used matchImagePoints method to handle partially detected Charuco boards
Replaces: https://github.com/opencv/opencv/pull/23757, https://github.com/opencv/opencv/pull/23840
=> Reworked calibrate.py

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation.yml
=> Update PRs & Issue templates to exclude 3.4 from active development

modules/core/src/mean.simd.hpp
We introduced scalable RVV as a new Universal Intrinsic backend last summer and also introduced some changing of the Universal Intrinsic API: #22179. In order to make the current SIMD vectorized loops availableto the scalable backend, we need to rewrite the code already written by Universal Intrinsic.
Since there are ~400 SIMD code blocks in ~50 files written by Universal Intinsic., thousands of lines of code need to be rewritten, which will be a huge work if done manually. Then I am developing a (semi-)automated rewriter/refactor based on clang-tidy, that can convert the convert existing code to the new API. The rewriter can already handle about 80% of the cases, and some corner cases are still under development. The link to the rewriter: https://github.com/hanliutong/rewriter
This patch …
=> Rewrite SIMD code by using new Universal Intrinsic API : an example.

modules/core/include/opencv2/core/cuda.hpp
It gives error when building projects with -Wpedantic -Werror
error: extra ‘;’ [-Werror=pedantic]
Issue #23916
=> removed trailing semicolon after function

modules/stitching/include/opencv2/stitching/detail/matchers.hpp, modules/stitching/src/matchers.cpp
Fixes #22632
Simply search & replaced all instances of `confindece`
- [N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
=> Fix typo `confindece`

cmake/OpenCVCompilerOptions.cmake
Relates to https://github.com/opencv/opencv_contrib/issues/3150
`-fast-math` option includes -ffinite-math-only option. Compiler expects that floats/doubles could not be NaN/Inf and does optimization accordingly. In particular __builtin_isnan and related built-in returns invalid result or optimized out by compiler.
Related discussion in GCC issue tracker: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84949
Stackoverflow question: https://stackoverflow.com/questions/69463347/why-does-gcc-ffast-math-disable-the-correct-result-of-isnan-and-isinf
=> Disable finite-math-only option with ENABLE_FAST_MATH=1 case to handle NaN and Inf checks correctly

modules/python/src2/typing_stubs_generation/api_refinement.py, modules/python/src2/typing_stubs_generation/nodes/__init__.py
May close #23925 . I am not sure this actually works because I can't figure out how to generate python bindings myself. But it looks right based on available API.
=> Add missing properties to error class

modules/videoio/src/cap_v4l.cpp, modules/videoio/test/test_precomp.hpp, modules/videoio/test/test_v4l2.cpp
This PR will support future improvement in #18498
* create 1 virtual device of type CAP (0x1) at /dev/video10
```
sudo modprobe vivid ndevs=1 node_types=0x1 vid_cap_nr=10`
```
* make sure user have read/write access (e.g. via group 'video')
```
$ ls -l /dev/video10
crw-rw----+ 1 root video ... /dev/video10
```
* set environment variable:
```
export OPENCV_TEST_V4L2_VIVID_DEVICE=/dev/video10
```
* run v4l2 tests:
```
opencv_test_videoio --gtest_filter=*videoio_v4l2*
```
Reference: https://www.kernel.org/doc/html/v4.8/media/v4l-drivers/vivid.html
* minor logging improvements in cap_v4l.cpp
* not all formats are tested for now, excluded more complex JPEG and Bayer formats
* picture contents is not tested
=> videoio: test for V4L using virtual device

modules/python/src2/typing_stubs_generation/generation.py
Every function has at least 1 overload (the **main** one), so before the fix `check_overload_presence` always produced `True`
As a coincide, removes unnecessary `import typing` in several modules stubs e.g. `cv2/gapi/core/cpu/__init__.pyi`
=> fix: typing stubs overload presence check

modules/python/src2/typing_stubs_generation/api_refinement.py, modules/python/src2/typing_stubs_generation/generation.py
Adds missing typing stubs:
- Matrix depths: `CV_8U`, `CV_8S` and etc.
- Matrix type constants: `CV_8UC1`, `CV_32FC3` and etc.
- Matrix type factory functions: `CV_*(channels) -> int` and `CV_MAKETYPE`
Resolves: #23910
Added content of `__init__.pyi`:
``` python
CV_8U: int
CV_8UC1: int
CV_8UC2: int
CV_8UC3: int
CV_8UC4: int
CV_8S: int
CV_8SC1: int
CV_8SC2: int
CV_8SC3: int
CV_8SC4: int
CV_16U: int
CV_16UC1: int
CV_16UC2: int
CV_16UC3: int
CV_16UC4: int
CV_16S: int
CV_16SC1: int
CV_16SC2: int
CV_16SC3: int
CV_16SC4: int
CV_32S: int
CV_32SC1: int
CV_32SC2: int
CV_32SC3: int
CV_32SC4: int
CV_32F: int
CV_32FC1: int
CV_32FC2: int
CV_32FC3: int
CV_32FC4: int
CV_64F: int
CV_64FC1: int
CV_64FC2: int
CV_64FC3: int
CV_64FC4: int
CV_16F: int
CV_16FC1: int
CV_16FC2: int
CV_16FC3: int
CV_16FC4: int
def …
```
=> feat: add matrix type stubs generation

modules/imgcodecs/src/grfmt_avif.cpp
A common decoder cannot be shared with checkSignature which is used like a static function (on a static ist of decoders).
=> Fix checkSignature not thread safe for AVIF.

modules/core/misc/python/package/mat_wrapper/__init__.py
Closes #23780 by specifying `ndarray`'s generic types. The use of `TYPE_CHECKING` and a type alias allows this to keep compatibility with all Python versions.
=> Fix partially unknown Mat

modules/python/src2/cv2_convert.cpp, modules/python/src2/cv2_util.hpp, modules/python/test/test_misc.py
Output string representation of NumPy array type if it is not convertible to OpenCV Mat type
Example output from the test:
```
cv2.error: OpenCV(4.8.0-dev) :-1: error: (-5:Bad argument) in function 'dumpInputArray'
> Overload resolution failed:
>  - argument data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'argument'
```
Resolves: #23106
=> feat: update NumPy type to Mat type fail message

cmake/OpenCVUtils.cmake
fixup #23842
Error message on `-DWITH_OPENVINO=ON -DBUILD_SHARED_LIBS=OFF`:
```
CMake Error: install(EXPORT "OpenCVModules" ...) includes target "ocv.3rdparty.openvino" more than once in the export set.
CMake Error in CMakeLists.txt:
given target "ocv.3rdparty.openvino" more than once.
```
=> cmake: don't export external target twice

modules/videoio/test/test_v4l2.cpp
related #23944
Added FOURCC codes missing on older systems.
=> videoio: fix v4l2 test on older platforms (centos)

modules/python/src2/typing_stubs_generation/generation.py
Addresses the same issue as #23809 , but also handles nested modules case
e.g. adds the following section to `cv2/gapi/__init__.pyi`:
```python
from cv2.gapi import core as core
from cv2.gapi import ie as ie
from cv2.gapi import imgproc as imgproc
from cv2.gapi import oak as oak
from cv2.gapi import onnx as onnx
from cv2.gapi import ov as ov
from cv2.gapi import own as own
from cv2.gapi import render as render
from cv2.gapi import streaming as streaming
from cv2.gapi import video as video
from cv2.gapi import wip as wip
```
- [] There is a reference to the original bug report and related work …
=> fix: recursively re-export nested submodules in typing stubs

modules/python/src2/cv2_util.hpp, modules/python/test/test_misc.py
Fix for BuildBot. 
Regression introduced in https://github.com/opencv/opencv/pull/23958
=> Fixed tests execution with Python 2.7

modules/core/misc/python/package/mat_wrapper/__init__.py, modules/python/src2/typing_stubs_generation/nodes/type_node.py
Fixes an issue in #23838 that re-introduced #23780 for `NumPyArrayGeneric`, `NumPyArrayFloat32`, `NumPyArrayFloat64` and all their aliases/subtypes/unions. As well as supporting generic static hints in python 3.8.
Read https://github.com/opencv/opencv/pull/23927#discussion_r1256326835 for the full explanation.
=> Prefer using `TYPE_CHECKING` condition in `cv2.typing` module

modules/core/src/matrix_transform.cpp, modules/imgproc/src/demosaicing.cpp
We experienced Segmentation Fault errors in _core_ `Flip` and _imgproc_ `Bayer` tests. Debugging has shown that issues are caused by an unaligned memory access in RVV code. This PR fixes them.
Below are quick performance comparison:
<details>
<summary>x86_64 performance results</summary>
**Core i5-11600**
|Name of Test|before|after|(x-factor)|
|Flip::OCL_FlipFixture::(640x480, 8UC1, FLIP_BOTH)|0.008|0.009|0.99|
|Flip::OCL_FlipFixture::(640x480, 8UC1, FLIP_COLS)|0.009|0.009|1.00|
|Flip::OCL_FlipFixture::(640x480, 8UC1, FLIP_ROWS)|0.008|0.008|1.05|
|Flip::OCL_FlipFixture::(640x480, 32FC1, FLIP_BOTH)|0.033|0.033|1.00|
|Flip::OCL_FlipFixture::(640x480, 32FC1, FLIP_COLS)|0.035|0.035|1.00|
|Flip::OCL_FlipFixture::(640x480, 32FC1, FLIP_ROWS)|0.035|0.035|1.00| …
=> RISC-V: fix unaligned loads and stores

modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp, modules/core/test/test_intrin_utils.hpp
I'm currently rewrite more code to the scalable Universal Intrinsic and I found that the Universal Intrinsic function `v_popcount` is missing for 64-bits integer in scalable RVV backend. This patch adds the missing implementation
BTW, according to the [documentation](https://github.com/opencv/opencv/blob/6af4a029417b0ed6e393610b5d7d99a13eb06219/modules/core/include/opencv2/core/hal/intrin_cpp.hpp#L820C1-L834C2) below , `v_popcount`  is designed for all integer type, but the unit test for 64-bit integer type is missing. I also enable the test in this patch.
```cpp
/** @brief Count the 1 bits in the vector lanes and return result as corresponding unsigned type
Scheme:
@code
{A1 A2 A3 ...} => {popcount(A1), popcount(A2), popcount(A3), ...}
@endcode
For all integer types. */
template<typename …
```
=> Add missing ”v_popcount“ for RVV and enable tests.

modules/imgproc/test/test_houghlines.cpp
C++20 made it invalid to use simple-template-ids for constructors and destructors: https://eel.is/c++draft/diff.cpp17.class#2 GCC 11 and later throw an error on this, with the unhelpful message `expected unqualified-id before ')' token`. This PR fixes the problem.
=> test_houghlines: Fix C++20 compatibility

modules/python/src2/typing_stubs_generation/api_refinement.py, modules/python/src2/typing_stubs_generation/generation.py, modules/python/src2/typing_stubs_generation/nodes/constant_node.py
This patch adds typing stubs generation for `__all__` and `__version__` constants.
Introduced `__all__` is intentionally empty for all generated modules stubs. 
Type hints won't work for star imports
resolves #23950
=> Python typing magic constants

modules/python/src2/gen2.py
This patch fixes usage of `cuda::Stream` in function arguments.
Affected modules: `cudacodec`: 
[`using namespace cuda`](https://github.com/opencv/opencv_contrib/blob/9dfe233020f669f17021dfc456fe77531e776b74/modules/cudacodec/include/opencv2/cudacodec.hpp#L62)  in public `cudacodec.hpp` header can be removed after merge of the patch.
=> feat: add cuda_Stream and cuda_GpuMat to simple types mapping

modules/dnn/test/test_torch_importer.cpp
Resolves https://github.com/opencv/opencv/issues/23947
Issue 1:
```
[ RUN      ] Test_Torch_nets.FastNeuralStyle_accuracy/0, where GetParam() = CUDA/CUDA
/home/ci/opencv/modules/dnn/test/test_common.impl.hpp:79: Failure
Expected: (normInf) <= (lInf), actual: 1.10242 vs 1.1
|ref| = 255
[  FAILED  ] Test_Torch_nets.FastNeuralStyle_accuracy/0, where GetParam() = CUDA/CUDA (188 ms)
```
Issue 2:
```
[ RUN      ] Test_Torch_nets.FastNeuralStyle_accuracy/1, where GetParam() = CUDA/CUDA_FP16
/home/ci/opencv/modules/dnn/test/test_common.impl.hpp:79: Failure
Expected: (normInf) <= (lInf), actual: 25.654 vs 25
|ref| = 255
[  FAILED  ] Test_Torch_nets.FastNeuralStyle_accuracy/1, where GetParam() = CUDA/CUDA_FP16 (1900 ms)
```
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#makin …
=> Increase eps for Test_Torch_nets.FastNeuralStyle_accuracy to prevent sporadic test failres with CUDA.

modules/core/src/channels.cpp
Details here: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58006
runtime error: call to function (unknown) through pointer to incorrect function type 'void (*)(const unsigned char **, const int *, unsigned char **, const int *, int, int)'
=> Fix undefined behavior with wrong function pointers called.

modules/core/include/opencv2/core/fast_math.hpp
There is no reason to enable this only on windows. We've measured a 7x improvement in speed for `cvRound` using the intrinsic.
- [ X] I agree to contribute to the project under Apache 2 License.
- [ X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ X] The PR is proposed to the proper branch
- [ X] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ X] The feature is well documented and sample code can be built with the project CMake
=> Use intrinsics for `cvRound` on x86_64 `__GNUC__` (clang/gcc linux) too.

modules/dnn/src/layers/cpu_kernels/conv_block.simd.hpp
=> fix compilation error on Windows ARM, use vaddq_f32 instead of +=

modules/core/include/opencv2/core/mat.inl.hpp, modules/imgproc/include/opencv2/imgproc/imgproc_c.h, modules/videoio/include/opencv2/videoio.hpp
Replacement for https://github.com/opencv/opencv/pull/23974.
Suppressed the warning as it's done for GCC and Clang.
The PR touches header files only. OpenCV does not fully support C++20 for now.
=> Disable waring C5054 in VS2022 c++20

modules/python/src2/gen2.py
This patch enables passing GpuMat as an in/out argument in several functions.
Part of work for opencv/opencv_contrib#3534
=> feat: add cuda_GpuMat to big types

modules/imgproc/src/drawing.cpp, modules/imgproc/test/test_drawing.cpp
For an empty radius, &v[0] would be accessed (though the called functions would not use it due to v.size() being 0). Also add checks for emptyness and fix the first element checks, in case we get INT_MAX to compare to.
=> Fix harmless ASAN error.

modules/python/src2/typing_stubs_generation/api_refinement.py, modules/python/src2/typing_stubs_generation/nodes/__init__.py
Manually add typing stubs for functions defined in `cv2_highgui.hpp`:
- `createTrackbar`
```python
def createTrackbar(trackbarName: str,
windowName: str,
value: int,
count: int,
onChange: Callable[[int], None]) -> None: ...
```
- `createButton`
```python
def createButton(buttonName: str,
onChange: Callable[[tuple[int] | tuple[int, Any]], None],
userData: Any | None = ...,
buttonType: int = ...,
initialButtonState: int = ...) -> None: ...
```
- `setMouseCallback`
```python
def setMouseCallback(
windowName: str,
onMouse: Callback[[int, int, int, int, Any | None], None],
param: Any | None = ...
) -> None: ...
```
closes opencv/opencv-python#875
=> feat: add highgui functions to typing stubs

3rdparty/openjpeg/openjp2/ht_dec.c
This PR fixes the issue: #24006 
=> [Build] popcnt is not supported on windows ARM

modules/python/src2/typing_stubs_generation/api_refinement.py
`redirectError` is defined in `cv2_util.cpp` and manually exported in `cv2.cpp`
Python interface for `redirectError`:
```python
def redirectError(
onError: Callable[[int, str, str, str, int], None] | None
) -> None: ...
```
=> feat: add typing stub for redirectError

modules/python/src2/typing_stubs_generation/api_refinement.py, modules/python/src2/typing_stubs_generation/ast_utils.py, modules/python/src2/typing_stubs_generation/generation.py, modules/python/src2/typing_stubs_generation/nodes/__init__.py, modules/python/src2/typing_stubs_generation/nodes/class_node.py, modules/python/src2/typing_stubs_generation/nodes/constant_node.py, modules/python/src2/typing_stubs_generation/nodes/enumeration_node.py, modules/python/src2/typing_stubs_generation/nodes/function_node.py, modules/python/src2/typing_stubs_generation/nodes/namespace_node.py, modules/python/src2/typing_stubs_generation/nodes/node.py, modules/python/src2/typing_stubs_generation/nodes/type_node.py
This patch introduces typings generation for `dnn_registerLayer`/`dnn_unregisterLayer` manually defined in [`cv2/modules/dnn/misc/python/pyopencv_dnn.hpp`](https://github.com/opencv/opencv/blob/4.x/modules/dnn/misc/python/pyopencv_dnn.hpp)
Updates:
- Add `LayerProtocol` to `cv2/dnn/__init__.pyi`:
```python
class LayerProtocol(Protocol):
def __init__(
self, params: dict[str, DictValue],
blobs: typing.Sequence[cv2.typing.MatLike]
) -> None: ...
def getMemoryShapes(
self, inputs: typing.Sequence[typing.Sequence[int]]
) -> typing.Sequence[typing.Sequence[int]]: ...
def forward(
self, inputs: typing.Sequence[cv2.typing.MatLike]
) -> typing.Sequence[cv2.typing.MatLike]: ...
```
- Add `dnn_registerLayer` function to `cv2/__init__.pyi`:
```python
def dnn_registerLayer(layerTypeName: str, …
```
=> Python typing refinement for dnn_registerLayer/dnn_unregisterLayer functions

3rdparty/libtiff/tif_dirread.c
Hi! We've been fuzzing opencv with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) security predicates and we found numeric truncation error in `tif_dirread.c:4386`.
In function `TIFFReadDirectoryCheckOrder` on line 4386 variable `m` has type `uint16`, structure `TIFFDirEntry` has field `uint16 tdir_tag`. But on the right side of operator there is an integer type value (due to the integer promotion), so the numeric truncation may occur. Our tool has found input when `o->tdir_tag` is equal to 65535 (uint16_max), so then value `o->tdir_tag+1` truncates to zero in variable `m`. Then `m` is used in if operator on line 4380, and it is obvious, that `o->tdir_tag<m` can't be true after truncation and the break from the cycle will not occur even with not ascending order of tags. So we …
=> Numeric truncation at `tif_dirread.c:4386`

modules/calib3d/src/calibration.cpp, modules/calib3d/test/test_cameracalibration.cpp
This should have been fixed with https://github.com/opencv/opencv/issues/23304
=> Fix stereoRectify image boundaries.

modules/videoio/src/cap_v4l.cpp, modules/videoio/test/test_precomp.hpp, modules/videoio/test/test_v4l2.cpp
MSVC warrning:
```
622>C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\algorithm(2650,24): warning C4244: '=': conversion from 'int' to 'char', possible loss of data [C:\build\precommit-contrib_windows64\build\modules\videoio\opencv_test_videoio.vcxproj]
```
ARMv7 Linux build issue:
```
/build/4_x_ARMv7-lin/opencv/modules/videoio/src/cap_v4l.cpp: In member function 'bool cv::CvCaptureCAM_V4L::autosetup_capture_mode_v4l2()':
/build/4_x_ARMv7-lin/opencv/modules/videoio/src/cap_v4l.cpp:276:62: error: 'v4l2_fourcc_be' was not declared in this scope
#define V4L2_PIX_FMT_Y16_BE v4l2_fourcc_be('Y', '1', '6', ' ')
^
```
```
```
=> Fixed warnings in videoio module

modules/gapi/include/opencv2/gapi/infer/bindings_onnx.hpp, modules/gapi/include/opencv2/gapi/infer/onnx.hpp, modules/gapi/misc/python/pyopencv_gapi.hpp, modules/gapi/src/backends/onnx/bindings_onnx.cpp, modules/gapi/src/backends/onnx/gonnxbackend.cpp
=> G-API: Support CUDA & TensoRT Execution Providers for ONNXRT Backend

modules/dnn/src/ie_ngraph.cpp, modules/dnn/src/ie_ngraph.hpp, modules/dnn/src/net_openvino.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_ie_models.cpp, modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
=> Remove legacy nGraph logic

modules/stereo/src/stereo_geom.cpp, modules/stereo/test/test_geometry.cpp
Review and merge after https://github.com/opencv/opencv/pull/24084
Address #24035 in 5.x
Manual port of https://github.com/opencv/opencv/pull/24035
=> Port stereoRectify grid fix #24035

modules/dnn/src/cuda4dnn/primitives/normalize_bbox.hpp, modules/dnn/src/cuda4dnn/primitives/region.hpp
https://github.com/opencv/opencv/pull/23948 appears to have gone stale and it has been over a month since CUDA 12.2 was introduced. This PR is to check if the two simple changes proposed there pass on the CI and if so prompt @jiapei100 to amend the PR or 🤞 one of the maintainers to fix it for them.
@asmorkalov @mshabunin @VadimLevin 
=> `cuda`: fix for compatibility with CUDA Toolkit >= 12.2.0

modules/dnn/src/onnx/onnx_importer.cpp
=> Invalid memory access fix for ONNX split layer parser #24076

modules/core/include/opencv2/core/hal/intrin.hpp
Nightly build issue: https://pullrequest.opencv.org/buildbot/builders/5_x-win32-vc14/builds/100205
The issue introduced in: https://github.com/opencv/opencv/pull/23865
=> Fix v_pack_store alignment issue on Windows 32-bit.

modules/core/include/opencv2/core/cuda.hpp, modules/python/test/test_cuda.py
Fixes https://github.com/opencv/opencv/issues/24038 and added non exhaustive python tests to verify functionality.
@VadimLevin
=> `cuda`: Fix `GpuMat::copyTo` and `GpuMat::converTo` python bindings

samples/python/tst_scene_render.py
Fix bug of python sample code (samples/python/tst_scene_render.py) when backGr or fgr is None (#24114)
1) pass shape tuple to np.zeros arguments instead of integers
2) change np.int to int
- [o] I agree to contribute to the project under Apache 2 License.
- [o] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [o] The PR is proposed to the proper branch
- [o] There is a reference to the original bug report and related work
- [o] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [o] The feature is well documented …
=> fix python sample code (tst_scene_render) 

modules/videoio/src/cap_msmf.cpp
=> Fixed bug when MSMF webcamera doesn't start when build with VIDEOIO_PLUGIN_ALL

modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp, modules/core/src/arithm.cpp, modules/core/src/arithm.simd.hpp, modules/core/src/convert.hpp, modules/core/src/convert.simd.hpp, modules/core/src/convert_scale.simd.hpp, modules/core/src/copy.cpp, modules/core/src/count_non_zero.simd.hpp, modules/core/src/lapack.cpp, modules/core/src/mathfuncs.cpp, modules/core/src/matmul.simd.hpp, modules/core/src/matrix_transform.cpp, modules/core/src/merge.simd.hpp, modules/core/src/norm.cpp, modules/core/src/split.simd.hpp, modules/core/src/stat.simd.hpp, modules/core/src/sum.simd.hpp
The goal of this PR is to match and modify all SIMD code blocks guarded by `CV_SIMD` macro in the `opencv/modules/core` folder and rewrite them by using the new Universal Intrinsic API.
The patch is almost auto-generated by using the [rewriter](https://github.com/hanliutong/rewriter), related PR #23885.
Most of the files have been rewritten, but I marked this PR as draft because, the `CV_SIMD` macro also exists in the following files, and the reasons why they are not rewrited are:
1. ~~code design for fixed-size SIMD (v_int16x8, v_float32x4, etc.), need to manually rewrite.~~ Rewrited
- ./modules/core/src/stat.simd.hpp
- ./modules/core/src/matrix_transform.cpp
- ./modules/core/src/matmul.simd.hpp
2. Vector types are wrapped in other class/struct, that are not supported by the compiler in …
=> Rewrite Universal Intrinsic code by using new API: Core module.

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/test/test_ffmpeg.cpp
As discussed in https://github.com/opencv/opencv_contrib/pull/3488#issuecomment-1598436515 decoder initialization when `VideoCapture` is only used for demuxing  (`CAP_PROP_FORMAT== -1`, `rawMode == true`) is unecessary.  Additionally if video sources can be parsed but not decoded, `VideoCapture` returns an error on decoder initialization preventing it from being used for demuxing.
=> `VideoCapture`: remove decoder initialization when demuxing

modules/core/include/opencv2/core/utils/filesystem.private.hpp, modules/core/src/utils/filesystem.cpp
It has the usual Unix filesystem operations.
- [N/A] There is a reference to the original bug report and related work
- [N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [N/A] The feature is well documented and sample code can be built with the project CMake
=> Fix GNU/Hurd build

modules/videoio/src/cap_gstreamer.cpp
related #24133, #23056, #23937
Steps to reproduce:
* build OpenCV with GStreamer backend as plugin (`-DVIDEOIO_PLUGIN_LIST=gstreamer`)
* open camera by index using GStreamer backend (`VideoCapture cap(0, CAP_GSTREAMER)`)
Result: failure, capture is not opened, when using GStreamer backend as built-in camera can be opened
This was happening due to bug in plugin wrapper.
=> videoio: fix camera opening with GStreamer plugin

modules/imgproc/src/imgwarp.cpp
fix the return-type compile error in `ipp_warpAffine`
When building OpenCV on Windows with MSVC, if we set cmake option `WITH_IPP` ON and `BUILD_IPP_IW` OFF, then we have macro `HAVE_IPP` / `HAVE_IPP_ICV` but no `HAVE_IPP_IW` / `HAVE_IPP_IW_LL` in `cvconfig.h`, thus the function [ipp_warpAffine](https://github.com/opencv/opencv/blob/27d718b2232ac82f3acc97395b979328d9c03cd8/modules/imgproc/src/imgwarp.cpp#L2622C1-L2685C1) will have an empty body (no return), but its signature returns `bool`.
Just add `return false` and apply `CV_UNUSED` to all its arguments, like what other `ipp_*` functions do.
The compile error on my PC is:
``` …
```
=> fix the return-type error in `ipp_warpAffine`

modules/dnn/src/net_impl_fuse.cpp
Fix issue: https://github.com/opencv/opencv/issues/24041
relates #22401
Handling when the `operation` of the `Elemtwise layer` is missing.
`nextData->params.get<String>("operation")` will fail when the `operation` is missing. This patch adds default value for such case.
=> DNN: fix the issue in layer_fuse

modules/videoio/src/cap_dshow.cpp
Streamlabs Desktop has the same issue in #19746. This fixes it using  #23460  method.
=> Adding support for Streamlabs Desktop Virtual Webcam

modules/gapi/cmake/DownloadADE.cmake
This update resolves all warnings produced by recent LLVM/Clang when compiling OpenCV.
=> gapi: update ADE library to 0.1.2b

modules/dnn/perf/perf_layer.cpp
resolves broken perf test: https://pullrequest.opencv.org/buildbot/builders/precommit_custom_linux/builds/100322
=> Remove explitit transB attribute from MatMul perf test

modules/core/test/test_misc.cpp, modules/python/test/tests_common.py, modules/ts/include/opencv2/ts/ts_ext.hpp, modules/ts/src/ts_tags.cpp
In case of `SkipTestException` throws in the fixture's constructor, test should be skipped. Reproducer added to `core` module tests.
related: https://github.com/opencv/opencv/pull/24157
```
force_builders=Win64 OpenCL
```
=> Skip test on SkipTestException at fixture's constructor

modules/dnn/src/layers/cpu_kernels/convolution.hpp
If building with -mcpu=native or any other setting which implies the current CPU has FP16 but with intrinsics disabled, we mistakenly try to use it even though convolution.hpp conditionally defines it correctly based on whether we should *use it*. convolution.cpp on the other hand was mismatched and trying to use it if the CPU supported it, even if not enabled in the build system.
Make the guards match.
Bug: https://bugs.gentoo.org/913031
=> Fix compilation on arm64 with FP16 when disabled

3rdparty/readme.txt, modules/imgcodecs/src/grfmt_tiff.cpp
libtiff homepage is moved to http://www.simplesystems.org/libtiff/ around 2004.
See https://en.wikipedia.org/wiki/LibTIFF
However, some files include old URLs, they should be update. 
This fix contains only changing source code comment, not chaning any behavious.
=> imgcodecs: fix libtiff URL in opencv source code

modules/gapi/CMakeLists.txt, modules/gapi/include/opencv2/gapi/gtype_traits.hpp, modules/gapi/include/opencv2/gapi/streaming/queue_source.hpp, modules/gapi/include/opencv2/gapi/streaming/source.hpp, modules/gapi/src/compiler/gislandmodel.hpp, modules/gapi/src/executor/gstreamingexecutor.cpp, modules/gapi/src/streaming/queue_source.cpp, modules/gapi/test/streaming/gapi_streaming_queue_source_tests.cpp
- Added a new IStreamSource class: in fact, a wrapper over a concurrent queue;
- Added minimal example on how it can be used;
- Extended IStreamSource with optional "halt" interface to break the blocking calls in the emitter threads when required to stop.
- Introduced a QueueInput class which allows to pass the whole graph's input vector at once. In fact it is a thin wrapper atop of individual Queue Sources.
There is a hidden trap found with our type system as described in https://github.com/orgs/g-api-org/discussions/2
While it works even in this form, it should be addressed somewhere in the 5.0 timeframe.
=> G-API: Introduce a Queue Source

modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/test/test_intrin_utils.hpp
fix https://github.com/opencv/opencv/issues/24213
=> core: arm64: v_round() works with round to nearest, ties to even.

modules/gapi/src/api/gbackend.cpp
=> removing unreachable codes in `gbackend`

modules/dnn/test/test_caffe_importer.cpp
This PR is used to finish https://github.com/opencv/opencv/issues/24016 and https://github.com/opencv/opencv/issues/24017
When enable the `FAST MATH` option, the accuracy will drop a little, but the results are still acceptable. So I change the threshold that make test can pass on Ubuntu. The results visualization are below.
**FasterRCNN_vgg16**
| Real | Excepted|
|-|-|
|![real vgg](https://github.com/opencv/opencv/assets/49567307/c15cc69b-4a96-42a9-a113-e64669512b41)|![excepted vgg](https://github.com/opencv/opencv/assets/49567307/0461445e-27c5-452e-aa25-14aecd81160e)|
**detail**
  | real score | expected score | score diff | IoU
-- | -- | -- | -- | --
CAR | 0.997029 | 0.997022 | 7E-06 | 0.970774
DOG | 0.993107 | 0.993028 | 7.9E-05 | 0.976928
BICYCLE | 0.9484 | 0.949398 | 0.000998 | …
=> Increase the test threshold of FastRCNN_vgg166 and FastRCNN_zf when FAST_MATH enable

modules/imgproc/src/geometry.cpp, modules/objdetect/src/qrcode.cpp
Not significant, but we can reduce number of multiplications while compute two lines intersection. Both methods are used heavily in their modules.
=> Minor optimization of two lines intersection

modules/videoio/src/cap_mjpeg_encoder.cpp
resolves #19634
resolves #24171
Enabled parallel processing, that was temporary disabled in #19812 because of the issue #19634
=> Fixed bug with the last 4 bytes in MJPEG encoder

modules/objdetect/misc/python/test/test_objdetect_aruco.py, modules/objdetect/src/aruco/aruco_detector.cpp
Fixes #24127
To refine corners of ArUco markers we need to call matchImagePoints() from base class Board. The method matchImagePoints() implemented in Pimpl and we need to create temp Board object.
=> fix refineDetectedMarkers

modules/core/test/test_misc.cpp, modules/python/test/tests_common.py, modules/ts/include/opencv2/ts/ts_ext.hpp, modules/ts/src/ts_tags.cpp
Reverts https://github.com/opencv/opencv/pull/24186
Current test skipping issue:
```
./bin/opencv_test_dnn --gtest_filter=Test_Caffe_layers*
...
[       OK ] Test_Caffe_layers.DeConvolution/3 (3 ms)
[ RUN      ] Test_Caffe_layers.InnerProduct/0, where GetParam() = NGRAPH/CPU
[       OK ] Test_Caffe_layers.InnerProduct/0 (8 ms)
[ RUN      ] Test_Caffe_layers.InnerProduct/1, where GetParam() = OCV/OCL
[       OK ] Test_Caffe_layers.InnerProduct/1 (4 ms)
[ RUN      ] Test_Caffe_layers.InnerProduct/2, where GetParam() = OCV/OCL_FP16
[     SKIP ] Test with tag 'dnn_skip_ocl_fp16' is skipped ('dnn_skip_ocl_fp16' is in skip list)
[       OK ] Test_Caffe_layers.InnerProduct/2 (0 ms)
[ RUN      ] Test_Caffe_layers.InnerProduct/3, where GetParam() = OCV/CPU
[     SKIP ] 
[       OK ] …
```
=> Revert PR 24186 as it forces skipping tests

modules/dnn/src/ie_ngraph.cpp, modules/dnn/src/ie_ngraph.hpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/blank_layer.cpp, modules/dnn/src/layers/concat_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/crop_and_resize_layer.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/flatten_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/lrn_layer.cpp, modules/dnn/src/layers/max_unpooling_layer.cpp, modules/dnn/src/layers/mvn_layer.cpp, modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/layers/proposal_layer.cpp, modules/dnn/src/layers/region_layer.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/src/layers/scale_layer.cpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/layers/softmax_layer.cpp, modules/dnn/src/net_openvino.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_tflite_importer.cpp
resolves https://github.com/opencv/opencv/issues/24102
* Use `ngraph::Output<ngraph::Node>>` insead of `std::shared_ptr<ngraph::Node>` as a backend wrapper. It lets access to multi-output nodes: https://github.com/opencv/opencv/blob/588ddf1b181aa7243144b27d65fc7690fb89e344/modules/dnn/src/net_openvino.cpp#L501-L504
* All layers can be customizable with OpenVINO >= 2022.1. nGraph reference code used for default layer implementation does not required CPU plugin also (might be tested by commenting CPU plugin at `/opt/intel/openvino/runtime/lib/intel64/plugins.xml`).
* Correct inference if only intermediate blobs requested.
``` …
```
=> Use ngraph::Output in OpenVINO backend wrapper

modules/dnn/src/dnn_utils.cpp, modules/dnn/test/test_misc.cpp
We would like to improve the recently introduced function `blobFromImagesWithParams` with respect to three minor issues that we noticed:
- Currently, `mean` and `scalefactor` are recreated for every image, even though they should be reused. Maybe the compiler is smart enough to optimize this, still we think the variable should be created / swapped before the main loop.
- Next, we would like to improve the function's robustness with respect to inconsistent arguments, i.e. if a single-channel image is passed but `swapRB` is true, as explained below.
- Finally, we made some minor modifications to follow the coding guidelines (`if - else if - else` instead of nested else).
Function wise, there are two improvements from this:
1. Currently, if the user passes a single-channel image in …
=> Fix bug at blobFromImagesWithParams

modules/videoio/src/cap_v4l.cpp
example to reproduce the problem
```cpp
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/videoio.hpp>
using namespace cv;
using namespace std;
void help_func(VideoCapture& cap) {
int height      = cap.get(cv::CAP_PROP_FRAME_HEIGHT);
int width       = cap.get(cv::CAP_PROP_FRAME_WIDTH);
int pixel_type  = cap.get(cv::CAP_PROP_FORMAT);
int channels    = CV_MAT_CN(pixel_type);
int pixel_bytes = CV_ELEM_SIZE(pixel_type);
bool to_bgr     = static_cast<bool>(cap.get(cv::CAP_PROP_CONVERT_RGB));
std::cout << "backend: " << cap.getBackendName() << std::endl;
std::cout << std::hex << "fourcc: " << static_cast<int>(cap.get(cv::CAP_PROP_FOURCC)) << std::endl;
std::cout << std::boolalpha << "to_bgr: " << to_bgr << std::endl; …
```
=> Fixed the channels when capturing yuv422 with v4l2 backend

modules/objdetect/src/aruco/aruco_dictionary.cpp, modules/objdetect/test/test_boarddetection.cpp
Fixes https://github.com/opencv/opencv/issues/24222
Now, if the size of base Dictionary is higher than markers, only the first markers in base Dictionary are taken and no new marker is added.
=> fix extendDictionary

modules/core/src/merge.dispatch.cpp
=> Check that cv::merge input matrices are not empty

CMakeLists.txt, modules/dnn/CMakeLists.txt, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn_params.cpp
Until some recent changes were made, OpenCV selected the default DNN backend either as `DNN_BACKEND_INFERENCE_ENGINE`, if available, or `DNN_BACKEND_OPENCV`, otherwise. Recently, this was removed because OpenCV supports multiple plugins/backends, as discussed in #24085.
This patch has two aims: First, fix the documentation since there is no extended default backend logic anymore. Next, it introduces a CMake variable `OPENCV_DNN_BACKEND_DEFAULT` that can be used to define a user-specific default backend. If this is not set, it defaults to `DNN_BACKEND_OPENCV`. Still, compiling with OpenVINO/Inference Engine support allows to default to it by adding the CMake argument `-D "OPENCV_DNN_BACKEND_DEFAULT=DNN_BACKEND_INFERENCE_ENGINE"`. Selecting a different default backend is similarly possible, …
=> Added CMake configuration OPENCV_DNN_BACKEND_DEFAULT

modules/objdetect/misc/python/test/test_objdetect_aruco.py, modules/objdetect/src/aruco/aruco_detector.cpp, modules/objdetect/src/aruco/charuco_detector.cpp, modules/objdetect/test/test_charucodetection.cpp
- drawDetectedMarkers(), drawDetectedCornersCharuco(), drawDetectedDiamonds() uses only `Point2f` (`CV_32FC2`) for detected corners. But this corners are casted to `int` later in the code.
- drawDetectedMarkers(), drawDetectedDiamonds() has a requirement on CV_32FC2 for corners. This requirement is lost in drawDetectedCornersCharuco().
Strict input data requirements have been removed. Added only the requirement to have 2 channels. The input corners are then casted to CV_32SC2.
added tests
=> fix type cast in drawDetectedMarkers, drawDetectedCornersCharuco, drawDetectedDiamonds

modules/core/src/hal_internal.cpp
Fixes a bunch of the following errors:
```
error: use of undeclared identifier '__msan_unpoison'
CV_ANNOTATE_MEMORY_IS_INITIALIZED(w, sizeof(fptype) * std::min(m, n));
```
=> Add missing sanitizer interface include

modules/dnn/src/tensorflow/tf_importer.cpp
Added default dimension value to tensorflow ArgMax and ArgMin layers.
Added exception when accessing layer's input with out of range index.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48452
=> Added default dimension value to tensorflow ArgMax and ArgMin layers

cmake/OpenCVDetectCUDA.cmake
Currently when `CUDA_ARCH_BIN` isn't specified CMake attempts to build .cu files for the all architechtures it knows about, generating a list of architectures supported by the current CUDA Toolkit (see https://github.com/opencv/opencv/pull/17432).  The idea being that if a user doesn't specify the arch then to be on the safe side it should generate for all architechtures for maximum compatibility.  Additionally if a user just wants to specify a PTX architechture they have to pass `CUDA_ARCH_BIN=` (incurring the overhead of calling `ocv_filter_available_architecture` on all know architectures) in addition to `CUDA_ARCH_PTX=<TAERGET ARCH>` to CMake  to avoid generating binary code for all supported architectures as well.  
This PR proposes that:
1. When `CUDA_ARCH_BIN` and  `CUDA_ARCH_PTX` …
=> `cuda`: update default PTX behaviour when `CUDA_ARCH_BIN` is unset

modules/core/src/copy.cpp, modules/core/src/matrix.cpp, modules/core/test/test_mat.cpp, modules/core/test/test_operations.cpp
This is due to the undefined: negative int multiplied by size_t pointer increment.
To test, compile with:
```
mkdir build
cd build
cmake ../ -DCMAKE_C_FLAGS_INIT="-fsanitize=undefined" -DCMAKE_CXX_FLAGS_INIT="-fsanitize=undefined" -DCMAKE_C_COMPILER="/usr/bin/clang" -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_SHARED_LINKER_FLAGS="-fsanitize=undefined -lubsan"
```
And run:
```
make -j opencv_test_core && ./bin/opencv_test_core --gtest_filter=*UndefinedBehavior*
```
=> Fix undefined behavior arithmetic in copyMakeBorder and adjustROI.

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
Fixed removePhaseSwitches algorithm in tf_graph_simplifier.
The algorithm finds some specific nodes that should be removed. These nodes have input nodes which probably become useless. So there is a BFS-like algorithm that removes all these nodes. It has numConsumers map that keeps the current number of outputs for each node. The algorithm decreases some numComsumers values after each node deleting, but there is a mistake in this operation.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56435
=> Fixed removePhaseSwitches in tf_graph_simplifier

modules/core/include/opencv2/core/hal/intrin_wasm.hpp, modules/js/src/core_bindings.cpp
Issue 1: emcc no longer provides implicit defines for the emscripten version, instead there's a separate header that provide them
Issue 2: disabling the objdetect module breaks the js build
Other than these small issues, OpenCV seems to work pretty well with the latest emscripten 👌. Not sure that the maintainers would like to do something with that information, like upgrade or something.
```
```
=> build fixes for emscripten 3.1.45

modules/core/include/opencv2/core/hal/intrin.hpp, modules/core/include/opencv2/core/hal/intrin_rvv_compat_overloaded.hpp, modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp, modules/imgproc/src/bilateral_filter.simd.hpp, modules/imgproc/src/color_lab.cpp, modules/imgproc/src/color_yuv.simd.hpp, modules/imgproc/src/filter.simd.hpp, modules/imgproc/src/hough.cpp, modules/imgproc/src/stackblur.cpp, modules/imgproc/src/thresh.cpp
The goal of this series of PRs is to modify the SIMD code blocks guarded by CV_SIMD macro in the opencv/modules/imgproc folder: rewrite them by using the new Universal Intrinsic API.
This is the second part of the modification to the Imgproc module ( Part 1: #24058 ), And I tested this patch on RVV (QEMU) and AVX devices, `opencv_test_imgproc` is passed.
The patch is partially auto-generated by using the [rewriter](https://github.com/hanliutong/rewriter).
=> Rewrite Universal Intrinsic code by using new API: ImgProc module Part 2

modules/imgproc/src/box_filter.simd.hpp, modules/imgproc/src/morph.simd.hpp, modules/imgproc/src/shapedescr.cpp
Related PR: #24058, #24132. The goal of this series of PRs is to modify the SIMD code blocks in the opencv/modules/imgproc folder by using the new Universal Intrinsic API.
The modification of this PR mainly focuses on the code that uses the `CV_SIMD_WIDTH` macro. This macro is sometimes used for loop tail processing, such as `box_filter.simd.hpp` and `morph.simd.hpp`.
```cpp
#if CV_SIMD
int i = 0;
for (i < n - v_uint16::nlanes; i += v_uint16::nlanes) {
// some universal intrinsic code
// e.g. v_uint16...
}
#if CV_SIMD_WIDTH > 16
for (i < n - v_uint16x8::nlanes; i += v_uint16x8::nlanes) {
// handle loop tail by 128 bit SIMD
// e.g. v_uint16x8
}
#endif //CV_SIMD_WIDTH 
#endif// CV_SIMD
```
The main contradiction is that the variable-length Universal Intrinsic backend cannot use 128bit …
=> Rewrite Universal Intrinsic code: ImgProc (CV_SIMD_WIDTH related Part)

modules/video/include/opencv2/video/tracking.hpp, modules/video/src/tracking/tracker_vit.cpp, modules/video/test/test_trackers.cpp, samples/dnn/vit_tracker.cpp, samples/python/tracker.py
Vit tracker(vision transformer tracker) is a much better model for real-time object tracking. Vit tracker can achieve speeds exceeding nanotrack by 20% in single-threaded mode with ARM chip, and the advantage becomes even more pronounced in multi-threaded mode. In addition, on the dataset, vit tracker demonstrates better performance compared to nanotrack. Moreover, vit trackerprovides confidence values during the tracking process, which can be used to determine if the tracking is currently lost.
opencv_zoo: https://github.com/opencv/opencv_zoo/pull/194
opencv_extra: [https://github.com/opencv/opencv_extra/pull/1088](https://github.com/opencv/opencv_extra/pull/1088)
NOTE: The speed below is tested by **onnxruntime** because opencv has poor support for the transformer architecture for now. …
=> vittrack(gsoc realtime object tracking model)

modules/dnn/src/torch/THDiskFile.cpp
In the previous code, there was a memory leak issue where the previously allocated memory was not freed upon a failed realloc operation. This commit addresses the problem by releasing the old memory before setting the pointer to NULL in case of a realloc failure. This ensures that memory is properly managed and avoids potential memory leaks.
=> Fix memory leak and handle realloc failure

modules/objdetect/include/opencv2/objdetect/aruco_board.hpp, modules/objdetect/src/aruco/aruco_board.cpp, modules/objdetect/src/aruco/charuco_detector.cpp, modules/objdetect/test/test_charucodetection.cpp
Fixes #23905
checkBoard() is an internal function that checks that the found board has the correct structure
1. fixed a bug with checking extraneous markers:
```
if (find(boardIds.begin(), boardIds.end(), idMaker) == boardIds.end())
continue;
```
2. fixed an indexing bug:
```
const int nearestMarkerId1 = boardIds[nearestMarkerIdx[chId][0]];
const int nearestMarkerId2 = boardIds[nearestMarkerIdx[chId][1]];
```
3. updated docs for getNearestMarkerIdx()/getNearestMarkerCorners()
4. added `checkBoardStructure` flag, this flag allows you to return the old behavior or use your custom board structure check.
=> fix charuco checkBoard

modules/calib3d/src/stereobm.cpp, modules/calib3d/src/stereosgbm.cpp, modules/video/src/tracking/tracker_vit.cpp, modules/video/test/test_trackers.cpp
Related: https://github.com/opencv/opencv/pull/24201
Warnings: https://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/102818/steps/compile%20release/logs/warnings%20%2816%29
=> Warnings fix on Windows.

modules/core/test/test_misc.cpp, modules/ts/include/opencv2/ts/ts_ext.hpp
same as https://github.com/opencv/opencv/pull/24250 but for `SetUp` method
=> Skip test cases in case of SkipTestException in SetUp

modules/3d/src/pointcloud/utils.hpp, modules/3d/src/ptcloud/sampling.cpp, modules/3d/src/rgbd/tsdf_functions.hpp, modules/3d/src/usac/estimator.cpp, modules/core/include/opencv2/core/hal/intrin.hpp, modules/core/src/convert.hpp
Tested with Clang 16 and GCC 13 (RISC-V RVV scalable variant). Also on x86_64 (default Ubuntu 22.04 GCC).
```
build_image:Custom=riscv-clang-rvv
Xbuild_image:Custom=riscv-gcc-rvv-07
test_timeout:Custom=600
```
=> RISC-V: fix compilation in RVV scalable mode

modules/calib3d/src/stereobm.cpp, modules/calib3d/src/stereosgbm.cpp, modules/features2d/src/sift.simd.hpp
The goal of this series of PRs is to modify the SIMD code blocks guarded by CV_SIMD macro: rewrite them by using the new Universal Intrinsic API.
This is the modification to the features2d module and calib3d module.
Test with clang 16 and QEMU v7.0.0. `AP3P.ctheta1p_nan_23607` failed beacuse of a small calculation error. But this patch does not touch the relevant code, and this error always reproduce on QEMU, regardless of whether the patch is applied or not. I think we can ignore it
```
[ RUN      ] AP3P.ctheta1p_nan_23607
/home/hanliutong/project/opencv/modules/calib3d/test/test_solvepnp_ransac.cpp:2319: Failure
Expected: (cvtest::norm(res.colRange(0, 2), expected, NORM_INF)) <= (3e-16), actual: 3.33067e-16 vs 3e-16
[  FAILED  ] AP3P.ctheta1p_nan_23607 (26 ms)
...
[==========] 148 tests …
```
=> Rewrite Universal Intrinsic code: features2d and calib3d module.

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/expand_layer.cpp, modules/dnn/src/onnx/onnx_graph_simplifier.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Resolves https://github.com/opencv/opencv/issues/24300
Resolves https://github.com/opencv/opencv/issues/24308
Merge with https://github.com/opencv/opencv_extra/pull/1098.
**Motivation:**
Current implementation of ONNX Expand is very limited and hard to maintain. It can go very unefficient, e.g. input of shape [1, 5, 1] and shape of value [1, 5, 256], it leads to 256 x [1, 5, 1] constant nodes along with a concat node. See down below for more details .
https://github.com/opencv/opencv/blob/b870ad46bf1a9bb5f4310db1e09a20f4265b823f/modules/dnn/src/onnx/onnx_importer.cpp#L2485-L2494
Since now we have `cv::broadcast` already, it is time to do a refactor on expand.
Checklist:
Patch to opencv_extra …
=> dnn: expand refactor with cv::broadcast for onnx models

modules/core/src/parallel_impl.cpp
**Problem description：**
When the number of cores is large, OpenCV’s thread library may reduce performance when processing parallel jobs.
**The reason for this problem:**
When the number of cores (the thread pool initialized the threads, whose number is as same as the number of cores) is large, the main thread will spend too much time on waking up unnecessary threads.
When a parallel job needs to be executed, the main thread will wake up all threads in sequence, and then wait for the signal for the  job completion after waking up all threads. When the number of threads is larger than the parallel number of a job slices, there will be a situation where the main thread wakes up the threads in sequence and the awakened threads have completed the job, but the main thread is still waking up …
=> optimization for parallelization when large core number

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Resolves https://github.com/opencv/opencv/issues/24319
Merge with https://github.com/opencv/opencv_extra/pull/1101
The model in the issue above has several Gather operators which have shared constant `indices` (same name, same category `Constant`, same type, same value). The following piece of code in onnx importer adds an attribute `real_ndims` if `indices` is not a layer
https://github.com/opencv/opencv/blob/7b399c4248fd6a399f2f5a731864448883fdd364/modules/dnn/src/onnx/onnx_importer.cpp#L2506-L2531
, but the following code converts the constant `indices` into a `Const` layer:
https://github.com/opencv/opencv/blob/7b399c4248fd6a399f2f5a731864448883fdd364/modules/dnn/src/onnx/onnx_importer.cpp#L2533-L2551
, which makes problems for later Gather operators who have shared `indices`. For …
=> dnn onnx: fix not-found constant indices for Gather if shared

modules/dnn/perf/perf_net.cpp, modules/dnn/src/ie_ngraph.cpp, modules/dnn/src/ie_ngraph.hpp, modules/dnn/src/int8layers/batch_norm_layer.cpp, modules/dnn/src/int8layers/convolution_layer.cpp, modules/dnn/src/int8layers/elementwise_layers.cpp, modules/dnn/src/int8layers/eltwise_layer.cpp, modules/dnn/src/int8layers/fully_connected_layer.cpp, modules/dnn/src/int8layers/pooling_layer.cpp, modules/dnn/src/int8layers/quantization_utils.cpp, modules/dnn/src/int8layers/scale_layer.cpp, modules/dnn/src/int8layers/softmax_layer.cpp, modules/dnn/src/layers/const_layer.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/softmax_layer.cpp, modules/dnn/src/net_impl.cpp, modules/dnn/src/net_impl_backend.cpp, modules/dnn/src/net_openvino.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_int8_layers.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
TODO:
Performace results for object detection model `coco_efficientdet_lite0_v1_1.0_quant_2021_09_06.tflite`:
| backend | performance (median time) |
|---|---|
| OpenCV | 77.42ms |
| OpenVINO 2023.0 | 10.90ms |
CPU: `11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz`
Serialized model per-layer stats (note that Convolution should use `*_I8` primitives if they are quantized correctly): https://gist.github.com/dkurt/7772bbf1907035441bb5454f19f0feef
---
``` …
```
=> OpenVINO backend for INT8 models

modules/dnn/src/layers/einsum_layer.cpp
Fixes: https://github.com/opencv/opencv/issues/24311
=> Fixed OpenCL FP16 fallback in Einsum layer

modules/core/misc/java/test/CoreTest.java, modules/java/test/pure_test/build.xml
Fixes CI behaviour. Issue example: https://github.com/opencv/opencv/pull/24323
Temporaty disabled Java test because of https://github.com/opencv/opencv/issues/24348.
=> Fail Java test suite, execution, if one of test failed.

doc/pattern_tools/gen_pattern.py, modules/objdetect/src/aruco/aruco_board.cpp
throw a warning message if the separators in the aruco/charuco boards are too small (less than 0.7 pin of ArUco marker):
```
boardSize = (5, 5)
dict = cv.aruco.getPredefinedDictionary(cv.aruco.DICT_4X4_50)
charucoBoard = cv.aruco.CharucoBoard(boardSize, 100., 85., dict)
arucoBoard = cv.aruco.GridBoard(boardSize, 100., 10., dict)
```
```
[ WARN:0@0.010] global aruco_board.cpp:555 cv::aruco::CharucoBoard::CharucoBoard marker separation:7.5 is less than 0.7 pin of ArUco marker:9.91667, too small separators can degrade the quality of detection, increase squareLength or decrease markerLength
[ WARN:0@0.010] global aruco_board.cpp:258 cv::aruco::GridBoard::GridBoard marker separation:10 is less than 0.7 pin of ArUco marker:11.6667, too small separators can degrade the quality …
```
=> add aruco board separation check

modules/core/test/test_io.cpp, modules/core/test/test_mat.cpp, modules/imgcodecs/test/test_tiff.cpp
Several tests were writing files in the current work directory and did not clean up after test. Moved all temporary files to the `/tmp` dir and added a cleanup code.
=> Fix tests writing to current work dir

cmake/OpenCVDetectPython.cmake
so we don't use numpy.distutils to get includes dirs of python-numpy
=> `numpy.distutils` is removed in numpy 1.26 on Python 3.12.

modules/objdetect/src/aruco/charuco_detector.cpp
Address https://github.com/opencv/opencv/commit/60ae97314236c5c6d96d15a052a6dc2a1fdc3846#r127863372
=> Removed invalid reference usage in charuco detector

modules/python/src2/typing_stubs_generation/generation.py, modules/python/src2/typing_stubs_generation/nodes/type_node.py
Import Python `typing` module as `_typing` to avoid name clashes.
resolves opencv/opencv-python#901
resolves #24352
Changes:
```python
import typing as _typing
from cv2 import typing as typing
@_typing.overload
def solveLP(Func: UMat, Constr: UMat, z: UMat | None = ...) -> tuple[int, UMat]: ...
```
Test file content:
```python
import typing
import cv2
import cv2.typing
if typing.TYPE_CHECKING:
reveal_type(cv2.typing.MatLike)
reveal_type(cv2.imdecode)
reveal_type(cv2.cuda.unregisterPageLocked)
```
Command: `mypy test.py`
Output:
```shell
test.py:6: note: Revealed type is "typing._SpecialForm"
test.py:7: note: Revealed type is "Overload(def (buf: Union[cv2.mat_wrapper.Mat, numpy.ndarray[Any, numpy.dtype[numpy.generic]]], flags: builtins.int) -> Union[cv2.mat_wrapper.Mat, numpy.ndarray[Any, …
```
=> feat: re-export cv2.typing module as typing

modules/dnn/perf/perf_net.cpp
**Merged With https://github.com/opencv/opencv_extra/pull/1095**
This PR aims to extend the performance tests. 
- **YOLOv5** for object detection
- **YOLOv8** for object detection
- **EfficientNet** for classification
Models from OpenCV Zoo:
- **YOLOX** for object detection
- **YuNet** for face detection
- **SFace** for face recognization
- **MPPalm** for palm detection
- **MPHand** for hand landmark
- **MPPose** for pose estimation
- **ViTTrack** for object tracking
- **PPOCRv3** for text detection
- **CRNN** for text recognization
- **PPHumanSeg** for human segmentation
If other models should be added, **please leave some comments**. Thanks!
Build opencv with script:
```shell
-DBUILD_opencv_python2=OFF
-DBUILD_opencv_python3=OFF
-DBUILD_opencv_gapi=OFF
-DINSTALL_PYTHON_EXAMPLES=OFF …
```
=> Extend performance test models

modules/gapi/cmake/DownloadADE.cmake
New patch release is available: https://github.com/opencv/ade/releases/tag/v0.1.2c
=> 3rdparty: update ade version

modules/imgproc/src/stb_truetype.cpp, modules/imgproc/src/stb_truetype.hpp
fix https://github.com/opencv/opencv/issues/24121
Move stb_truetype functions() into the cv namespace. This avoids name collisions with other applications and libraries that use stb_truetype.
```
kmtr@ubuntu:~/work/build5-main$ nm lib/libopencv_imgproc.so | c++filt | grep "stbtt_" | head -10
000000000025b180 t cv::stbtt_GetWeight(cv::stbtt_fontinfo const*)
0000000000259d40 t cv::stbtt_Rasterize(cv::stbtt__bitmap*, float, cv::stbtt_vertex*, int, float, float, float, float, int, int, int, void*)
000000000025b080 t cv::stbtt_CreateFont(unsigned char const*, unsigned int, int)
0000000000258a30 t cv::stbtt_GetGlyphBox(cv::stbtt_fontinfo const*, int, int*, int*, int*, int*)
000000000025b120 t cv::stbtt_GetInstance(cv::stbtt_fontinfo const*, cv::stbtt_axisinfo*, int)
000000000025b0f0 t …
```
=> imgproc: move stb_truetype functions into cv namespace

modules/calib3d/src/undistort.simd.hpp, modules/core/include/opencv2/core/hal/intrin.hpp, modules/core/src/arithm.simd.hpp, modules/core/src/has_non_zero.simd.hpp, modules/core/src/lapack.cpp, modules/core/src/matmul.simd.hpp, modules/core/src/mean.simd.hpp, modules/dnn/src/int8layers/convolution_layer.cpp, modules/dnn/src/int8layers/fully_connected_layer.cpp, modules/imgproc/src/accum.simd.hpp, modules/imgproc/src/color_hsv.simd.hpp, modules/imgproc/src/median_blur.simd.hpp
The goal of this series of PRs is to modify the SIMD code blocks guarded by CV_SIMD macro: rewrite them by using the new Universal Intrinsic API.
The series of PRs is listed below:
#23885 First patch, an example
#23980 Core module
#24058 ImgProc module, part 1
#24132 ImgProc module, part 2
#24166 ImgProc module, part 3
#24301 Features2d and calib3d module
#24324 Gapi module
This patch (hopefully) is the last one in the series. 
This patch mainly involves 3 parts
1. Add some modifications related to float (CV_SIMD_64F)
2. Use `#if (CV_SIMD || CV_SIMD_SCALABLE)` instead of `#if CV_SIMD || CV_SIMD_SCALABLE`, 
then we can get the `CV_SIMD` module that is not enabled for `CV_SIMD_SCALABLE` by looking for `if CV_SIMD`
3. Summary of `CV_SIMD` blocks that remains unmodified: Updated comments
- …
=> Rewrite Universal Intrinsic code: float related part

modules/core/src/hal_replacement.hpp, modules/core/src/matrix_transform.cpp
Hello,
This change proposes the addition of HAL hooks for cv::flip() and cv::rotate() functions from OpenCV core module.
Flip and rotation are functions commonly available from 2D hardware accelerators. This is convenient provision to enable custom optimized implementation of image flip/rotation on systems embedding such accelerator.
Thank you
=> Add HAL implementation hooks to cv::flip() and cv::rotate() functions from core module 

modules/core/include/opencv2/core/hal/intrin_rvv_011_compat.hpp, modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
Fixes compilation with Clang 17 (tested) and GCC trunk (not tested).
Default rounding mode is chosen to be "round to nearest up". Only two intrinsics are actually used in OpenCV code: `vnclip` and `vnclipu`. Others were added for completeness. 
```
Xbuild_image:Custom=riscv-gcc
build_image:Custom=riscv-clang-rvv
Xbuild_image:Custom=riscv-gcc-rvv-07
test_timeout:Custom=600
```
=> RISC-V: added v0.12 intrinsics compatibility header

modules/objdetect/include/opencv2/objdetect/aruco_detector.hpp, modules/objdetect/src/aruco/aruco_detector.cpp
Fixes #24113
cornerRefinementMethod=CORNER_REFINE_SUBPIX  does not work correctly with markers that are too close to each other.
Now `cornerRefinementWinSize` is recalculated for each marker as:
`cornerRefinementWinSize = min(cornerRefinementWinSize, averageArucoPinSize*relativeCornerRefinmentWinSize)
`
relativeCornerRefinmentWinSize=0.3 by default and could be changed
Also the method has been tested by the [benchmark](https://github.com/opencv/opencv_benchmarks/pull/7), 289 aruco boards like this were tested:
command line to generate and run (also need set cornerRefinementMethod: 1 and cornerRefinementWinSize: 10 in aruco_params.yml):
```
objdetect_benchmark.py --marker_length_rate=0.1 --board_x=6 -p=res --rel_center_y=0.53 --rel_center_x=0.56 --synthetic_object=aruco
```
tested with …
=> add dynamic window in aruco cornerRefinement

modules/highgui/src/window_QT.cpp
Fix the issue of missing imshow icons when linking OpenCV as a static library(https://github.com/opencv/opencv-python/issues/585)
=> Fix imshow icons missing when linking the static opencv library

modules/gapi/src/backends/fluid/gfluidcore.cpp, modules/gapi/src/backends/fluid/gfluidcore_func.dispatch.cpp, modules/gapi/src/backends/fluid/gfluidcore_func.hpp, modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp, modules/gapi/src/backends/fluid/gfluidimgproc_func.simd.hpp
The goal of this series of PRs is to modify the SIMD code blocks guarded by CV_SIMD macro: rewrite them by using the new Universal Intrinsic API.
This is the modification to the gapi module, especially the fluid part.
All modifications to the gapi module have been completed, but this PR is marked as draft because many use cases failed in the test, and I am looking for the reason.
<details>
<summary>FAILED  76 tests on RVV QEMU, listed below:</summary>
```
[  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/2, where GetParam() = (8UC3, 1280x720, SAME_TYPE, 0x4e534a, DIV, true, 1, false)
[  FAILED  ] MathOpTestFluid/MathOpTest.MatricesAccuracyTest/3, where GetParam() = (8UC3, 1280x720, SAME_TYPE, 0x4e534a, DIV, true, 1, true)
[  FAILED  ] …
```
=> Rewrite Universal Intrinsic code: gapi module (fluid part).

modules/dnn/test/test_backends.cpp
In case of OpenCL failure the pipeline fails back to CPU and the test compares CPU vs CPU.  Looks like CPU implementation produce slightly different result and it does not fit into threshold:
```
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from DNNTestNetwork
[ RUN      ] DNNTestNetwork.FastNeuralStyle_eccv16/0, where GetParam() = OCV/OCL
[ WARN:0@0.812] global ocl4dnn_conv_spatial.cpp:1923 loadTunedConfig OpenCV(ocl4dnn): consider to specify kernel configuration cache directory through OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"! …
```
=> Tuned threshold for FastNeuralStyle_eccv16 test

modules/dnn/src/layers/const_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Resolves https://github.com/opencv/opencv/issues/24385
Merge with https://github.com/opencv/opencv_extra/pull/1107
Relates https://github.com/opencv/opencv/pull/24092#discussion_r1353964405
=> dnn: fix inconsistent input dtype for nary eltwise layers

modules/videoio/test/test_camera.cpp
Test for https://github.com/opencv/opencv/pull/24180
=> Added test with V4L CAP_PROP_CONVERT_RGB=false.

modules/imgproc/perf/perf_resize.cpp
Fixes https://github.com/opencv/opencv/issues/24408
Sanity data update: https://github.com/opencv/opencv_extra/pull/1108/
Use downscale to ensure inter-area resize.
=> Ensure interarea algorithm usage in resize perfomance test

modules/dnn/src/layers/cumsum_layer.cpp, modules/dnn/test/test_onnx_importer.cpp
When exclusive is false:
dst[i] = dst[i-1] + src[i]
When exclusive is true:
dst[i] = dst[i-1] + src[i-1]
So CumSum layer can be inplace only when exclusive flag is false.
=> Fixed CumSum layer inplace flag

cmake/OpenCVFindProtobuf.cmake, modules/dnn/CMakeLists.txt, modules/dnn/src/caffe/caffe_io.cpp, modules/dnn/test/test_layers.cpp
fix https://github.com/opencv/opencv/issues/24369
related https://github.com/opencv/opencv/issues/23791
1. This patch supports external protobuf v22 and later, it required abseil-cpp and c++17.
Even if the built-in protobuf is upgraded to v22 or later, 
the dependency on abseil-cpp and the requirement for C++17 will continue.
2. Some test for caffe required patched protobuf, so this patch disable them.
This patch is tested by following libraries.
-  Protobuf:                    /usr/local/lib/libprotobuf.so (4.24.4)
-  abseil-cpp:                YES (20230125)
=> supporting protobuf v22 and later(with abseil-cpp/C++17)

cmake/OpenCVDetectCUDA.cmake
CUDA source files are compiled single threaded. The option `--threads` was introduced in NVCC 11.2. The option specifies the number of threads to be used for compilation (see [NVIDIA NVCC Documentation](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#threads-number-t)).
With CMake 3.12 the environment variable `CMAKE_BUILD_PARALLEL_LEVEL` was introduced (see [CMake Documentation](https://cmake.org/cmake/help/latest/envvar/CMAKE_BUILD_PARALLEL_LEVEL.html)). This variable is used to set the NVCC `--threads` option.
=> Enable multicore CUDA compilation

modules/imgproc/src/resize.cpp
This provides a 10 to 20% speed-up.
Related perf test fix: https://github.com/opencv/opencv/pull/24417
This is a split of https://github.com/opencv/opencv/pull/23525 that will be updated to only deal with column merging.
=> Speed up line merging in INTER_AREA

modules/objdetect/src/barcode.cpp
This pointer is called unconditionally in BarcodeImpl::initDecode assuming the size of the image is outside the specified bounds.  This seems to not cause problems on optimized builds, I assume because the optimizer sees through the processImageScale call to see that it can be reduced to a resize call.  Leaving it as is relies on undefined behavior.
This was the least invasive change I could make, however, it might be worthwhile to pull up the logic for a resize so that a SuperScale does not need to be allocated, which seems to be the most common case.
=> Unconditionally create SuperScale in BarcodeDetector to avoid null deref

cmake/OpenCVFindTIMVX.cmake, modules/dnn/CMakeLists.txt
=> dnn: fix HAVE_TIMVX macro definition in dnn test

modules/imgcodecs/src/grfmt_avif.cpp
The API will soon be made no_discard.
=> Check the return value of avifDecoderSetIOMemory.

doc/py_tutorials/py_imgproc/py_transforms/py_fourier_transform/py_fourier_transform.markdown
Truediv (floating point division) operators on line 149 of [the tutorial](https://github.com/opencv/opencv/blob/4.x/doc/py_tutorials/py_imgproc/py_transforms/py_fourier_transform/py_fourier_transform.markdown) produce floating point result:
``` python
crow,ccol = rows/2 , cols/2
```
Hence, indexing operation on line 153:
``` python
mask[crow-30:crow+30, ccol-30:ccol+30] = 1
```
Fails with an error:
``` python
TypeError: slice indices must be integers or None or have an __index__ method
```
This PR fixes the error by replacing the operators with floordiv (integer division) ones.
=> tutorial_py_fourier_transform wrong division operator fix

modules/dnn/src/layers/einsum_layer.cpp, modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp, modules/dnn/test/test_onnx_importer.cpp
This PR added addresses issues not covered in #24037. Namely these are: 
Test case for this patch is in this PR [#1106](https://github.com/opencv/opencv_extra/pull/1106) in opencv extra
Added: 
Features to add: 
=> Ellipses supported added for Einsum Layer

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_ffmpeg.cpp, modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/test/test_ffmpeg.cpp
Allow raw encoded video streams (e.g. h264[5]) to be encapsulated by `cv::VideoWriter` to video containers (e.g. mp4/mkv).
Operates in a similar way to https://github.com/opencv/opencv/pull/15290 where encapsulation is enabled by setting the `VideoWriterProperties::VIDEOWRITER_PROP_RAW_VIDEO` flag when constructing `cv::VideoWriter` e.g.
```
VideoWriter container(fileNameOut, api, fourcc, fps, { width, height }, { VideoWriterProperties::VIDEOWRITER_PROP_RAW_VIDEO, 1 });
```
and each raw encoded frame is passed as single row of a `CV_8U` `cv::Mat`.
The main reason for this PR is to allow `cudacodec::VideoWriter` to output its encoded streams to a suitable container, see https://github.com/opencv/opencv_contrib/pull/3569.
See details at …
=> videoio: Add raw encoded video stream encapsulation to `cv::VideoWriter` with `CAP_FFMPEG`

modules/core/test/test_mat.cpp, modules/dnn/src/layers/layers_common.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/gapi/src/compiler/passes/exec.cpp, modules/gapi/src/streaming/onevpl/file_data_provider.hpp, modules/stitching/src/camera.cpp, modules/video/src/optical_flow_io.cpp
For ubuntu 23.10, supress GCC13 warnings.
OpenCV version: 4.x
Operating System / Platform: Ubuntu 23.10
Compiler & compiler version: GCC 13.2.0
=> fix: supress GCC13 warnings

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/layers/cpu_kernels/fast_norm.cpp, modules/dnn/src/layers/cpu_kernels/fast_norm.hpp, modules/dnn/src/layers/layer_norm.cpp, modules/dnn/src/layers/mvn_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_torch_importer.cpp
Relates https://github.com/opencv/opencv/pull/24378#issuecomment-1756906570
TODO:
=> dnn: add shared fastNorm kernel for mvn, instance norm and layer norm

modules/python/src2/gen2.py
Fixes https://github.com/opencv/opencv/issues/23133
Python bindings signatures are added to Doxygen documentation with `pyopencv_signatures.json`. The file is generated by python bindings generator. The constructors are there, but namespace is handled incorrectly, e.g.:
```
"cv::aruco::Dictionary::cv::aruco::Dictionary::Dictionary": [
{
"name": "cv.aruco.Dictionary",
"arg": "",
"ret": "<aruco_Dictionary object>"
},
{
"name": "cv.aruco.Dictionary",
"arg": "bytesList, _markerSize[, maxcorr]",
"ret": "<aruco_Dictionary object>"
}
],
```
=> Fixed Python signatures in Doxygen documentation.

modules/core/include/opencv2/core.hpp, modules/core/perf/perf_arithm.cpp, modules/core/src/mathfuncs.cpp
backport from #23098
connected PR in extra: [#1118@extra](https://github.com/opencv/opencv_extra/pull/1118)
* new SIMD code for `patchNaNs()`
* CPU perf test
<details>
<summary>Performance comparison</summary>
|Name of Test|noopt|sse2|avx2|sse2 vs noopt (x-factor)|avx2 vs noopt (x-factor)|
|---|:-:|:-:|:-:|:-:|:-:|
|PatchNaNs::OCL_PatchNaNsFixture::(640x480, 32FC1)|0.019|0.017|0.018|1.11|1.07|
|PatchNaNs::OCL_PatchNaNsFixture::(640x480, 32FC4)|0.037|0.037|0.033|1.00|1.10|
|PatchNaNs::OCL_PatchNaNsFixture::(1280x720, 32FC1)|0.032|0.032|0.033|0.99|0.98|
|PatchNaNs::OCL_PatchNaNsFixture::(1280x720, 32FC4)|0.072|0.072|0.070|1.00|1.03|
|PatchNaNs::OCL_PatchNaNsFixture::(1920x1080, 32FC1)|0.051|0.051|0.050|1.00|1.01|
|PatchNaNs::OCL_PatchNaNsFixture::(1920x1080, …
=> Backport to 4.x: patchNaNs() SIMD acceleration

modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
I found that some of the functions in RVV Universal intrinsic call vsetvlmax instructions directly, that may create redundant vsetvl instructions. This patch optimizes those functions by using local variables. (`vsetvlmax` -> `VTraits<_Tpvec>::vlanes`)
The performance evaluation is [core.zip](https://github.com/opencv/opencv/files/13246313/core.zip)
=> Optimize the Implementation of RVV Universal Intrinsic.

modules/dnn/perf/perf_layer.cpp, modules/dnn/src/layers/cpu_kernels/softmax.cpp, modules/dnn/src/layers/cpu_kernels/softmax.hpp, modules/dnn/src/layers/region_layer.cpp, modules/dnn/src/layers/softmax_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp
This PR improves softmax from [ficus nn](https://github.com/vpisarev/ficus/tree/master/lib/NN).
Performance Test result (use min value and Muti-threads):
**macOS M2**
|Name of Test|before|after|after vs before (x-factor)|
|{ 16, 50, 50 }, 0|0.047|0.048|0.98|
|{ 16, 50, 50 }, 1|0.052|0.075|0.69|
|{ 16, 50, 50 }, 2|0.367|0.045|**8.19**|
|{ 16, 197, 197 }, 0|0.700|0.256|2.73|
|{ 16, 197, 197 }, 1|0.602|0.368|1.64|
|{ 16, 197, 197 }, 2|5.706|0.230|**24.81**|
|{ 16, 1024, 1024 }, 0|17.143|18.464|0.93|
|{ 16, 1024, 1024 }, 1|16.001|30.027|0.53|
|{ 16, 1024, 1024 }, 2|162.174|3.120|**51.99**|
**Ubuntu [Intel Core i7-12700K](https://www.intel.com/content/www/us/en/products/sku/134594/intel-core-i712700k-processor-25m-cache-up-to-5-00-ghz/specifications.html)**: 8 …
=> Improve and refactor softmax layer

modules/core/include/opencv2/core/fast_math.hpp
=> Get the SSE2 condition match the emmintrin.h inclusion condition.

modules/features2d/include/opencv2/features2d.hpp, modules/features2d/misc/java/test/BOWImgDescriptorExtractorTest.java
Fixes https://github.com/opencv/opencv/issues/24094
Feature2D is synonym for DescriptorExtractor in C++.
=> Added Java bindings for BOWImgDescriptorExtractor constructor

modules/videoio/src/cap_gstreamer.cpp, modules/videoio/test/test_audio.cpp, modules/videoio/test/test_gstreamer.cpp, modules/videoio/test/test_video_io.cpp
- Fix broken seeking in audio/video playback
- Fix broken audio playback
- Fix unreliable seeking
- Estimate frame count if it is not available directly
- Return -1 for frame count and fps if it is not available. 
- Return 0 for fps if the video has variable frame rate
- Enable and fix tests
- [-] There is a reference to the original bug report and related work => Reproducible test provided
- [-] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
1. Download two test videos:
```bash
wget https://github.com/ietf-wg-cellar/matroska-test-files/raw/master/test_files/test1.mkv
wget …
```
=> Fix gstreamer backend with manual pipelines

modules/videoio/test/test_gstreamer.cpp
Issue: https://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/103335/steps/compile%20release/logs/warnings%20%282%29
Related PR: https://github.com/opencv/opencv/pull/24243
=> Fixed build warning introduced in #24243

doc/pattern_tools/test_charuco_board.py, modules/objdetect/include/opencv2/objdetect/aruco_detector.hpp, modules/objdetect/src/aruco/aruco_detector.cpp, modules/objdetect/src/aruco/charuco_detector.cpp, modules/objdetect/test/test_arucodetection.cpp, modules/objdetect/test/test_charucodetection.cpp
Fixes [#24220](https://github.com/opencv/opencv/issues/24220)
Merge with https://github.com/opencv/opencv_extra/pull/1117
Prepared new filtering algorithm for ArUco. This algorithm fixes:
- multiple detection of a single marker;
- incorrect work with nested contours (issue [#24220](https://github.com/opencv/opencv/issues/24220));
- detection charuco with big markers (big relative to the board cell)
Also:
- This PR increases the marker grouping area by setting default minMarkerDistanceRate = 0.125 vs minMarkerDistanceRate = 0.05 earlier (all old values should work correctly)
- This PR allows you to save multiple contours from the same group, the number of saved contours depends on minGroupDistance.
- This PR disables the ability to detect nested markers (only the innermost markers will be …
=> Fix contour filtering in ArUco

modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/test/test_ffmpeg.cpp
FPS reports per-file FPS and video stream FPS depending on FFmpeg version. The PR use per-stream FPS first.
Fixes https://github.com/opencv/opencv-python/issues/899
Relates to https://github.com/opencv/opencv/pull/23692 and https://github.com/opencv/opencv/issues/21006
=> Use video stream fps first in FFmpeg backend for VideoCapture

modules/js/generator/embindgen.py, modules/js/src/core_bindings.cpp, platforms/js/build_js.py, platforms/js/opencv_js.config.py
ret_type = re.sub('(^|[^\w])' + key + '($|[^\w])', type_dict[key], ret_type)
When compiling JavaScript, this code converts vector<std:: string>to vector std:: string
Details: https://laolaolulu.github.io/posts/emscripten-opencv/#opencvjs%E7%BC%96%E8%AF%91getunconnectedoutlayersnames%E8%BF%87%E7%A8%8B%E4%B8%AD%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86
```
```
=> Dnn_ Net_ A bug occurred when compiling getUnconnectedOutLayersNames into JavaScript

modules/dnn/test/test_onnx_importer.cpp
CUDA kernels for InstanceNormalization are added in https://github.com/opencv/opencv/pull/24378.
=> dnn onnx test: remove cuda backend filter for instance norm test

modules/objdetect/src/qrcode.cpp
Remove filter fix in ArUco-based qr code detector after PR Fix contour filtering in ArUco #24479
there are no changes in accuracy in the [benchmark](https://github.com/opencv/opencv_benchmarks/tree/develop/python_benchmarks/qr_codes)
=> remove filter fix in aruco qr code detector

modules/imgproc/src/distransform.cpp
* Do not use IPP for huge Mat (reproduced with https://github.com/opencv/opencv/issues/23895#issuecomment-1708132367 on `DIST_MASK_5`)
I have observed two types of errors on the reproducer from the issue:
1. When `temp` is not allocated:
```
Thread 1 "app" received signal SIGSEGV, Segmentation fault.
0x00007ffff65dc755 in icv_l9_ownDistanceTransform_5x5_8u32f_C1R_21B_g9e9 () from /home/dkurtaev/opencv_install/bin/../lib/libopencv_imgproc.so.408
(gdb) bt
#0  0x00007ffff65dc755 in icv_l9_ownDistanceTransform_5x5_8u32f_C1R_21B_g9e9 () from /home/dkurtaev/opencv_install/bin/../lib/libopencv_imgproc.so.408
#1  0x00007ffff659e8df in icv_l9_ippiDistanceTransform_5x5_8u32f_C1R () from /home/dkurtaev/opencv_install/bin/../lib/libopencv_imgproc.so.408
#2  0x00007ffff5c390f0 in cv::distanceTransform …
```
=> Handle huge images in IPP distanceTransform

modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/gemm_layer.cpp, modules/dnn/src/layers/instance_norm_layer.cpp, modules/dnn/src/layers/layer_norm.cpp
Resolves https://github.com/opencv/opencv/issues/24154
Resolves https://github.com/opencv/ci-gha-workflow/pull/120#issuecomment-1805226774
New CANN operator added in this PR:
=> dnn cann backend: add hardswish, layernorm and instasnce norm for cann and bug fix

CMakeLists.txt, cmake/OpenCVDetectDirectML.cmake, cmake/checks/directml.cpp, modules/gapi/CMakeLists.txt, modules/gapi/include/opencv2/gapi/infer/onnx.hpp, modules/gapi/src/backends/onnx/dml_ep.cpp
Extend `cv::gapi::onnx::ep::DirectML` to accept `adapter name` as `ctor` parameter in order to select execution device by `name`.
E.g:
```
pp.cfgAddExecutionProvider(cv::gapi::onnx::ep::DirectML("Intel Graphics"));
```
=> G-API: Advanced device selection for ONNX DirectML Execution Provider

modules/dnn/perf/perf_einsum.cpp, modules/dnn/src/layers/einsum_layer.cpp
**Notation:**
- WX: windows10_x64
- MX: macos_x64
- MA: macos_arm64
- UX: ubuntu_x64
- UA: ubuntu_arm64
All data in ms (milliseconds).
Gemm is backend for matrix multiplication
---
Benchmarks: (arrow indicates increase in inference speed compared to [einsum with gemm](https://github.com/opencv/opencv/pull/24445))
| Equation                | Inputs Mat Dims                    | UX (ms)  | UA (ms) | MX (ms) | MA (ms) | WX (ms) |
|-------------------------|------------------------------------|----------|---------|---------|---------|---------|
| "ij, jk -> ik"          | [2, 3], [3,2]                      | 0.04 ± 0.00 | -       | -       | -       | -       |
| "ij, jk -> ik"          | [20, 30], [30,20]                  | 0.07 ± 0.00 | -       | -       | -       | -       |
| "ij, jk -> …
=> Fast gemm for einsum

modules/videoio/src/cap_openni2.cpp
Homogenize cv::VideoCapture behaviour, as it should not throw exceptions for unsupported properties.
Replaces https://github.com/opencv/opencv/pull/24549
=> Print warning, but not throw exceptions in cv::VideoCapture for OpenNI2

modules/dnn/src/cuda/mvn.cu, modules/dnn/src/cuda4dnn/kernels/mvn.hpp, modules/dnn/src/cuda4dnn/primitives/layer_norm.hpp, modules/dnn/src/layers/layer_norm.cpp, modules/dnn/src/opencl/mvn.cl, modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
Merge after https://github.com/opencv/opencv/pull/24544.
Todo:
```
```
=> dnn: add openvino, opencl and cuda backends for layer normalization layer

modules/core/include/opencv2/core.hpp, modules/core/src/check.cpp, modules/core/src/count_non_zero.dispatch.cpp, modules/core/src/count_non_zero.simd.hpp, modules/core/src/has_non_zero.simd.hpp, modules/core/src/lut.cpp, modules/core/src/minmax.cpp, modules/core/test/test_arithm.cpp, modules/ts/include/opencv2/ts/ts_perf.hpp
`cv::LUI()`, `cv::minMaxLoc()`, `cv::minMaxIdx()`, `cv::countNonZero()`, `cv::findNonZero()` and `cv::hasNonZero()` uses depth-based function table. However, it is too short for `CV_16BF`, `CV_Bool`, `CV_64U`, `CV_64S` and `CV_32U` and it may occur out-boundary-access. This patch fix it. And If necessary, when someone extends these functions to support, please relax this test.
=> Fix verify unsupported new mat depth for nonzero/minmax/lut

modules/cudastereo/src/cuda/stereobm.cu
Changed the height parameter in the cudaMemset2D function call to use minSSD_buf.rows instead of disp.rows. This ensures the correct buffer height is used for memory initialization.
its a minor change so if you think you need 4th and 5th point let me know.
=> cudaMemset2D fix: Correct buffer height parameter

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn_utils.cpp, modules/dnn/test/test_misc.cpp
This PR add functionality for specifying value in padding.
It is required in many preprocessing pipelines in DNNs such as Yolox object detection model
=> Add support for custom padding in DNN preprocessing

modules/imgproc/src/color_lab.cpp
There is a race condition between when the static bool is initialized (which is thread safe) and its value check. This PR changes the static bool to a static lambda call to make it thread safe. The static_cast<void> in the end is to prevent unused variables warnings.
=> Fix race condition in color_lab.cpp initLabTabs().

samples/android/tutorial-2-mixedprocessing/src/org/opencv/samples/tutorial2/Tutorial2Activity.java
Regression was introduced in https://github.com/opencv/opencv/pull/24575
=> Fixed regression in Android Tutorial2 initialization.

platforms/android/build_sdk.py
Tries to fix build errors like this:
```
2023-11-27T14:14:56.4627503Z FAILURE: Build failed with an exception.
2023-11-27T14:14:56.4627530Z 
2023-11-27T14:14:56.4627946Z * What went wrong:
2023-11-27T14:14:56.4629021Z Execution failed for task ':tutorial-1-camerapreview:lintVitalAnalyzeRelease'.
2023-11-27T14:14:56.4630451Z > Could not resolve all files for configuration ':tutorial-1-camerapreview:releaseCompileClasspath'.
2023-11-27T14:14:56.4636192Z    > Failed to transform out.aar (project :opencv) to match attributes {artifactType=android-lint-exploded-aar, com.android.build.api.attributes.AgpVersionAttr=7.3.1, com.android.build.api.attributes.BuildTypeAttr=release, com.android.build.gradle.internal.attributes.VariantAttr=release, org.gradle.usage=java-api, …
```
=> Serialize Android samples build in SDK script to prevent raise between gradle instances

modules/gapi/include/opencv2/gapi/infer/ov.hpp, modules/gapi/src/backends/ov/govbackend.cpp, modules/gapi/src/backends/ov/govbackend.hpp
Introduced `cv::gapi::wip::ov::benchmark_mode{}` compile argument which if enabled force `OpenVINO` backend to run only inference without populating input and copying back output tensors. 
This mode is only relevant for measuring the performance of pure inference without data transfers. Similar approach is using on OpenVINO side in `benchmark_app`: https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/benchmark_app/benchmark_app.hpp#L134-L139
=> G-API: Implement inference only mode for OV backend

modules/gapi/src/backends/ie/giebackend.cpp
=> G-API: Soften the argument check in infer2

modules/calib3d/src/calibinit.cpp
=> Fix bug in ChessBoardDetector::findQuadNeighbors

modules/videoio/src/container_avi.cpp
`Bitstream::open` did not check, if file was opened correctly.
=> Report correct open status from Bitstream

modules/core/src/arithm.simd.hpp
I do not have more info on the platform as it is internal.
Without this fix, the error is:
```
core/src/arithm.simd.hpp:868:1: error: too few arguments provided to function-like macro invocation
868 | DEFINE_SIMD_ALL(cmp)
| ^
./third_party/OpenCV/public/modules/./core/src/arithm.simd.hpp:93:5: note: expanded from macro 'DEFINE_SIMD_ALL'
93 |     DEFINE_SIMD_NSAT(fun, __VA_ARGS__)
|     ^
./third_party/OpenCV/public/modules/./core/src/arithm.simd.hpp:89:5: note: expanded from macro 'DEFINE_SIMD_NSAT'
89 |     DEFINE_SIMD_F64(fun, __VA_ARGS__)
|     ^
./third_party/OpenCV/public/modules/./core/src/arithm.simd.hpp:77:9: note: expanded from macro 'DEFINE_SIMD_F64'
77 |         DEFINE_NOSIMD(__CV_CAT(fun, 64f), double, __VA_ARGS__)
|         ^ …
```
=> Fix compilation on some 32-bit windows

modules/calib3d/src/calibration.cpp
This should have been fixed in https://github.com/opencv/opencv/pull/24035
=> Fix stereoRectify image boundaries again.

modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java
Fixes https://github.com/opencv/opencv/issues/15369
Use app may implement inherited class and set `CameraCaptureSession.StateCallback` with any camera options. `allocateSesstionStateCallback` should be overridden for this.
=> Refactor JavaCamera2View to add option to override Camera2 session request options

3rdparty/carotene/src/div.cpp, 3rdparty/openexr/IlmImf/ImfConvert.cpp, 3rdparty/openjpeg/openjp2/j2k.c, 3rdparty/openjpeg/openjp2/tcd.c
I had a chance to build OpenCV with clang 10.
I found 5 lines of warnings and I think it's worth to prevent it.
```
/opencv/3rdparty/carotene/src/div.cpp:160:19: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wi[0/1875]int-float-conversion]
(scale * std::numeric_limits<T>::max()) <  1.0f &&
~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opencv/3rdparty/carotene/src/div.cpp:453:5: note: in instantiation of function template specialization 'carotene_o4t::(anonymous namespace)::div<int>' requested here
div<s32>(size, src0Base, src0Stride, src1Base, src1Stride, dstBase, dstStride, scale, cpolicy);
^
/opencv/3rdparty/carotene/src/div.cpp:161:19: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 …
```
=> build: fix warning in Clang 10

modules/gapi/CMakeLists.txt, modules/gapi/include/opencv2/gapi/cpu/ot.hpp, modules/gapi/include/opencv2/gapi/ot.hpp, modules/gapi/src/3rdparty/vasot/LICENSE.txt, modules/gapi/src/3rdparty/vasot/include/vas/common.hpp, modules/gapi/src/3rdparty/vasot/include/vas/ot.hpp, modules/gapi/src/3rdparty/vasot/src/common/exception.hpp, modules/gapi/src/3rdparty/vasot/src/common/prof.hpp, modules/gapi/src/3rdparty/vasot/src/components/ot/kalman_filter/kalman_filter_no_opencv.cpp, modules/gapi/src/3rdparty/vasot/src/components/ot/kalman_filter/kalman_filter_no_opencv.hpp, modules/gapi/src/3rdparty/vasot/src/components/ot/mtt/hungarian_wrap.cpp, modules/gapi/src/3rdparty/vasot/src/components/ot/mtt/hungarian_wrap.hpp, modules/gapi/src/3rdparty/vasot/src/components/ot/mtt/objects_associator.cpp, modules/gapi/src/3rdparty/vasot/src/components/ot/mtt/objects_associator.hpp, modules/gapi/src/3rdparty/vasot/src/components/ot/mtt/rgb_histogram.cpp, modules/gapi/src/3rdparty/vasot/src/components/ot/mtt/rgb_histogram.hpp, modules/gapi/src/3rdparty/vasot/src/components/ot/object_tracker.cpp, modules/gapi/src/3rdparty/vasot/src/components/ot/prof_def.hpp, modules/gapi/src/3rdparty/vasot/src/components/ot/short_term_imageless_tracker.cpp, modules/gapi/src/3rdparty/vasot/src/components/ot/short_term_imageless_tracker.hpp, modules/gapi/src/3rdparty/vasot/src/components/ot/tracker.cpp, modules/gapi/src/3rdparty/vasot/src/components/ot/tracker.hpp, modules/gapi/src/3rdparty/vasot/src/components/ot/tracklet.cpp, modules/gapi/src/3rdparty/vasot/src/components/ot/tracklet.hpp, modules/gapi/src/3rdparty/vasot/src/components/ot/zero_term_imageless_tracker.cpp, modules/gapi/src/3rdparty/vasot/src/components/ot/zero_term_imageless_tracker.hpp, modules/gapi/src/api/kernels_ot.cpp, modules/gapi/src/backends/cpu/gcpuot.cpp, modules/gapi/test/cpu/gapi_ot_tests_cpu.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1123
! **There is known flaw in the code: usage of `KalmanFilterNoOpencv` class. This should be reworked to use OpenCV version or just refactored.** !
! **Link to the original implementation is:** ttps://github.com/dlstreamer/dlstreamer/tree/master/src/monolithic/gst/elements/gvatrack/vas
=> Ported VAS OT into OpenCV G-API

3rdparty/openjpeg/openjp2/ht_dec.c
Use NEON instructions for ARM64 (implementation based on https://github.com/microsoft/STL/pull/2127, which is Apache licensed).
Godbolt output here: https://godbolt.org/z/q7GPTqT14
=> ht_dec.c: Improve MSVC arm64 popcount performance

modules/videoio/src/cap_ios_photo_camera.mm
- [ x] I agree to contribute to the project under Apache 2 License.
- [x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ x] The PR is proposed to the proper branch
=> The AVVideoCodecJPEG symbol was deprecated in iOS 11.0. We may want to use AVVideoCodecTypeJPEG instead

CMakeLists.txt, modules/java/android_sdk/CMakeLists.txt, modules/java/generator/android-24/java/org/opencv/android/NativeCameraView.java, modules/java/generator/gen_java.py, modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_android_camera.cpp
The PR fixes minor issues in cv::VideoCapture implementation for Android and adds experimental NativeCameraView to test it with samples. The NativeCameraView may be tested by `samples/android/tutorial-1-camerapreview/res/layout/tutorial1_surface_view.xml` modification. Not recommended for production usage. Requires API level 24+ and `WITH_ANDROID_NATIVE_CAMERA` cmake option enabled.
=> Added experimental NativeCameraView class for Android 24+.

modules/dnn/test/test_onnx_importer.cpp
This PR adds test for YOLOv6 model (which was absent before)
The onnx weights for the test are located in this PR [ #1126](https://github.com/opencv/opencv_extra/pull/1126)
```
build_image:Custom=ubuntu:22.04
```
=> Add test for YoloX Yolo v6 and Yolo v8

doc/tutorials/introduction/crosscompilation/arm_crosscompile_with_cmake.markdown, doc/tutorials/introduction/crosscompilation/crosscompile_with_multiarch.markdown, doc/tutorials/introduction/table_of_content_introduction.markdown
Add cross compile tutorial for ubuntu/debian.
( I'm sorry to my poor English. )
Fix https://github.com/opencv/opencv/issues/24628
=> doc: add crosscompile_with_multiarch

modules/java/android_sdk/android_gradle_lib/build.gradle
Gradle namespace is missing in one of configurations.
=> fix build.gradle

modules/dnn/src/layers/cpu_kernels/convolution.cpp, modules/dnn/src/layers/cpu_kernels/convolution.hpp
Fixes the following warning on  armv8:
```
warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
```
Buildbot: https://pullrequest.opencv.org/buildbot/builders/4_x_ARMv8-lin
=> Fixed armv8 compilation warnings

3rdparty/readme.txt
The current one cannot be reached. I replaced it with the one I found in official Github repository https://github.com/randy408/libspng
=> Fix homepage of libspng

modules/gapi/src/backends/ov/govbackend.cpp, modules/gapi/test/infer/gapi_infer_ov_tests.cpp
=> G-API: Get input model layout from the IR if possible in OV 2.0 backend

modules/dnn/src/caffe/caffe_importer.cpp, modules/dnn/src/darknet/darknet_io.cpp, modules/dnn/src/layers/softmax_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/src/torch/torch_importer.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_onnx_conformance_layer_filter_opencv_all_denylist.inl.hpp
Try to solve problem: https://github.com/opencv/opencv/pull/24476#discussion_r1404821158
**ONNX**
`opset <= 11` use 1
`else` use -1
**TensorFlow**
`TF version = 2.x` use -1
`else` use 1
**Darknet, Caffe, Torch**
use 1 by definition
=> Make default axis of softmax in onnx "-1" without opset option

cmake/FindONNX.cmake
Looks the `install` directory layout has been changed for `v1.16.3`
=> Fix path to ONNX Runtime include folder

3rdparty/libspng/CMakeLists.txt, 3rdparty/libspng/LICENSE, 3rdparty/libspng/spng.c, 3rdparty/libspng/spng.h
Include three fixes:
https://github.com/randy408/libspng/commit/e68ba5df571726bf001d9ea150980463ea395a75 https://github.com/randy408/libspng/commit/6c7c8ce3729bb866eec9e94e426c3221abf402b0 https://github.com/randy408/libspng/commit/c9451cab664794dc909c4580dd1e6e013f3db512
and three chores:
https://github.com/randy408/libspng/commit/d86a11d3ab8f37e7772d52490d3b086d0e0f9bc7 https://github.com/randy408/libspng/commit/bab9f94a1186f8fda234b4e1cb65e1b9a77049cc https://github.com/randy408/libspng/commit/fb768002d4288590083a476af628e51c3f1d47cd
I have reviewed CMakeLists.txt and I think disabling unused-variable warning is not needed.
=> Update 3rdparty libspng to 0.7.4

modules/calib3d/src/calibinit.cpp
It seems the port in https://github.com/opencv/opencv/pull/11703 lost the initialization.
The only breaking tests I have are unfortunately internal and complex.
=> Empty vectors before filling them in ChessBoardDetector::processQuads

3rdparty/zlib/ChangeLog, 3rdparty/zlib/README, 3rdparty/zlib/adler32.c, 3rdparty/zlib/compress.c, 3rdparty/zlib/crc32.c, 3rdparty/zlib/deflate.c, 3rdparty/zlib/deflate.h, 3rdparty/zlib/gzclose.c, 3rdparty/zlib/gzguts.h, 3rdparty/zlib/gzlib.c, 3rdparty/zlib/gzread.c, 3rdparty/zlib/gzwrite.c, 3rdparty/zlib/infback.c, 3rdparty/zlib/inffast.c, 3rdparty/zlib/inffast.h, 3rdparty/zlib/inflate.c, 3rdparty/zlib/inftrees.c, 3rdparty/zlib/inftrees.h, 3rdparty/zlib/trees.c, 3rdparty/zlib/uncompr.c, 3rdparty/zlib/zconf.h, 3rdparty/zlib/zlib.h, 3rdparty/zlib/zutil.c, 3rdparty/zlib/zutil.h
The opencv zlib patch is still not merged. So I applied it to zlib-1.3. Since zlib-1.3 didn't modify CMakeLists.txt, opencv's zlib CMakeLists.txt doesn't need to be modified.
=> Update 3rdparty zlib to 1.3

modules/calib3d/src/calibinit.cpp
We already have `quad_count` decrease in https://github.com/opencv/opencv/blob/4.x/modules/calib3d/src/calibinit.cpp#L1271 . So, we have double decrease each loop iteration and it isn't correct
=> Fix bug in ChessBoardDetector::cleanFoundConnectedQuads

modules/calib3d/src/calibinit.cpp
This is more correct to divide sum by number of terms, which at array ends is less than window size
=> Improve icvSmoothHistogram256

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/perf/perf_gemm.cpp, modules/dnn/src/cuda4dnn/csl/cublas.hpp, modules/dnn/src/cuda4dnn/csl/tensor_ops.hpp, modules/dnn/src/cuda4dnn/primitives/matmul_broadcast.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/cpu_kernels/fast_gemm.cpp, modules/dnn/src/layers/cpu_kernels/fast_gemm.hpp, modules/dnn/src/layers/cpu_kernels/fast_gemm_kernels.default.hpp, modules/dnn/src/layers/cpu_kernels/fast_gemm_kernels.simd.hpp, modules/dnn/src/layers/gemm_layer.cpp, modules/dnn/src/layers/matmul_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp
Done:
Tests are done on M1. All data is in milliseconds (ms).
| Configuration | MatMul (Prepacked) | MatMul | InnerProduct |
| - | - | - | - |
| A=[12, 197, 197], B=[12, 197, 64], trans_a=0, trans_b=0 | **0.39** | 0.41 | 1.33 |
| A=[12, 197, 64], B=[12, 64, 197], trans_a=0, trans_b=0  | **0.42** | 0.42 | 1.17 |
| A=[12, 50, 64], B=[12, 64, 50], trans_a=0, trans_b=0    | **0.13** | 0.15 | 0.33 |
| A=[12, 50, 50], B=[12, 50, 64], trans_a=0, trans_b=0    | **0.11** | 0.13 | 0.22 |
| A=[16, 197, 197], B=[16, 197, 64], trans_a=0, trans_b=0 | **0.46** | 0.54 | 1.46 |
| A=[16, 197, 64], B=[16, 64, 197], trans_a=0, trans_b=0  | **0.46** | 0.95 | 1.74 |
| A=[16, 50, 64], B=[16, 64, 50], trans_a=0, trans_b=0    | **0.18** | 0.32 | 0.43 |
| A=[16, 50, 50], B=[16, 50, 64], trans_a=0, trans_b=0    | …
=> dnn: refactor ONNX MatMul with fastGemm

modules/gapi/include/opencv2/gapi/cpu/ot.hpp, modules/gapi/include/opencv2/gapi/ot.hpp, modules/gapi/misc/python/package/gapi/__init__.py, modules/gapi/misc/python/pyopencv_gapi.hpp, modules/gapi/misc/python/python_bridge.hpp, modules/gapi/misc/python/shadow_gapi.hpp, modules/gapi/misc/python/test/test_gapi_ot.py, modules/gapi/misc/python/test/test_gapi_types.py, modules/gapi/src/api/kernels_ot.cpp, modules/gapi/src/backends/cpu/gcpuot.cpp, modules/gapi/test/cpu/gapi_ot_tests_cpu.cpp, modules/python/src2/cv2_convert.hpp, modules/python/src2/pycompat.hpp
=> Enable GAPI VASOT in Python

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/calibinit.cpp, modules/calib3d/src/checkchessboard.cpp, modules/calib3d/test/test_chesscorners.cpp
What I did was get you to pull out of findChessboardCorners cornres the whole part that "checks" and sorts the corners of the checkerboard if present.
The main reason for this is that findChessboardCorners is often very slow to find the corners and this depends in that the size the contrast etc of the checkerboards can be very different from each other and writing a function that works on all kinds of images is complicated. 
So I find it very useful to have the ability to write your own code to process the image and then have a function that controls or orders the corners.
=> Check Checkerboard Corners

modules/core/src/arithm.cpp, modules/core/src/opencl/inrange.cl, modules/imgproc/src/color.hpp, modules/imgproc/src/color_hsv.dispatch.cpp, modules/imgproc/src/color_lab.cpp, modules/imgproc/src/color_rgb.dispatch.cpp, modules/imgproc/src/color_yuv.dispatch.cpp, modules/imgproc/src/deriv.cpp, modules/imgproc/src/imgwarp.cpp, modules/imgproc/src/opencl/color_hsv.cl, modules/imgproc/src/opencl/color_lab.cl, modules/imgproc/src/opencl/color_rgb.cl, modules/imgproc/src/opencl/color_yuv.cl, modules/imgproc/src/opencl/laplacian5.cl, modules/imgproc/src/opencl/pyr_down.cl, modules/imgproc/src/opencl/pyr_up.cl, modules/imgproc/src/opencl/remap.cl, modules/imgproc/src/opencl/resize.cl, modules/imgproc/src/opencl/warp_affine.cl, modules/imgproc/src/opencl/warp_perspective.cl, modules/imgproc/src/pyramids.cpp, modules/imgproc/src/resize.cpp
resolves #24435
Do not use macro definitions with lower case letters - only several kernels have been updated (_imgproc_ and _core_).
Tested core and imgproc on AArch64 RK3588 (Mali GPU) and x86_64 (Intel GPU).
=> OCL: fix incompatibility with Mali ruintime

modules/dnn/test/test_onnx_importer.cpp
resolves #24735
relates #24476
```
force_builders=Linux OpenCL,Linux AVX2,Win64 OpenCL
```
=> dnn(test): tune FP16 test tolerance

modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp
- OpenCL kernel code doesn't support that
resolves #24734
```
force_builders=Linux OpenCL,Linux AVX2,Win64 OpenCL
```
OpenCL builders would fail until tests are fixed (related to other issues).
=> dnn(ocl): don't try KERNEL_TYPE_GEMM_LIKE with kernel_w > 16

modules/dnn/src/opencl/conv_layer_spatial.cl, modules/imgproc/src/opencl/filter2DSmall.cl, modules/imgproc/src/opencl/filterSmall.cl
Avoid verbose OpenCL compilation messages like:
relates #24734
```
[ RUN      ] DNNTestNetwork.AlexNet/0, where GetParam() = OCV/OCL
...
OpenCL program build log: dnn/conv_layer_spatial
Status 0: CL_SUCCESS
-D TYPE=1 -D Dtype=float -D Dtype2=float2 -D Dtype4=float4 -D Dtype8=float8 -D Dtype16=float16 -D as_Dtype=as_float -D as_Dtype2=as_float2 -D as_Dtype4=as_float4 -D as_Dtype8=as_float8 -D KERNEL_WIDTH=11 -D KERNEL_HEIGHT=11 -D STRIDE_X=4 -D STRIDE_Y=4 -D DILATION_X=1 -D DILATION_Y=1 -D INPUT_PAD_W=0 -D INPUT_PAD_H=0 -D INPUT_PAD_RIGHT=0 -D INPUT_PAD_BOTTOM=0 -cl-fast-relaxed-math  -D GEMM_LIKE_CONV_32_1 -D Conv_Interleaved=U_GEMM_LIKE_CONV_k11x11_cn3_g1_s4x4_d1x1_b1_in240x240_p0x0_num1_M96_activ1_eltwise0_FP32_5_1_8_32_SIMD8 -cl-mad-enable -cl-no-subgroup-ifp  -D KERNEL_GEMM_LIKE -D …
```
=> ocl: fix kernels compilation

modules/dnn/src/darknet/darknet_io.cpp, modules/dnn/test/test_darknet_importer.cpp
Request for comments. This is my first PR. 
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1112
resolves https://github.com/opencv/opencv/issues/22747
```
opencv_extra=feat-crop1
```
=> Fixes #22747. Support [crop] configuration for DarkNet

cmake/OpenCVFindLibsGrfmt.cmake, cmake/OpenCVUtils.cmake
Currently cmake scripttry to use regex to parse VER_MAJOR, VER_MINOR, VER_REVISION from ZLIB_VERSION. However, ZLIB_VERSION is "1.3" which means that there is no VER_REVISION.
You ca reproduce using "-DBUILD_ZLIB=ON"
```
--     ZLib:                        zlib (ver 1.3.#define ZLIB_VERSION "1.3")
```
I think it is OK to extract version information from VARNAME.
=> Fix zlib version parse

modules/dnn/src/cuda4dnn/primitives/scale_shift.hpp
caused by https://github.com/opencv/opencv/pull/24384
```
[ RUN      ] Test_Darknet_layers.crop/0, where GetParam() = CUDA/CUDA
C++ exception with description "OpenCV(4.8.0-dev) /home/ci/opencv/modules/dnn/src/layers/../cuda4dnn/primitives/scale_shift.hpp:135: error: (-215:Assertion failed) 0 in function 'operator()'
[  FAILED  ] Test_Darknet_layers.crop/0, where GetParam() = CUDA/CUDA (4 ms)
[ RUN      ] Test_Darknet_layers.crop/1, where GetParam() = CUDA/CUDA_FP16
C++ exception with description "OpenCV(4.8.0-dev) /home/ci/opencv/modules/dnn/src/layers/../cuda4dnn/primitives/scale_shift.hpp:135: error: (-215:Assertion failed) 0 in function 'operator()'
[  FAILED  ] …
```
=> [CUDA] Hotfix Scale with 1 parameter

modules/dnn/test/test_onnx_importer.cpp
Motivation: sporadic test failure like https://github.com/opencv/opencv/actions/runs/7297266682/job/19886377164?pr=24744
```
[ RUN      ] Test_ONNX_nets.ViT_B_32/1, where GetParam() = CUDA/CUDA_FP16
/home/ci/opencv/modules/dnn/test/test_common.impl.hpp:79: Failure
Expected: (normInf) <= (lInf), actual: 0.05369 vs 0.05
ViTB_32  |ref| = 2.8940291404724121
[  FAILED  ] Test_ONNX_nets.ViT_B_32/1, where GetParam() = CUDA/CUDA_FP16 (1352 ms)
```
=> Increate Vit_b test threshold a bit for CUDA FP16.

modules/calib3d/src/calibinit.cpp
Сode doesn't match comment. 
If we want check `1:4` edges ratio and `edge_len` is squared edge length, then we should check
```
ediff > 15*edge_len
```
with constant `15`, not `32`, because
```
ediff > 15*edge_len2 <=> edge_len1 - edge_len2 > 15*edge_len2 <=> edge_len1 > 16*edge_len2 <=> 1:4 edges ratio
```
But for me it's better and simpler to directly check `edge_len1 > 16*edge_len2`
=> Fix mismatch and simplify code in ChessBoardDetector::findQuadNeighbors

CMakeLists.txt, cmake/OpenCVFindLibsGrfmt.cmake, cmake/OpenCVUtils.cmake, cmake/templates/cvconfig.h.in, modules/imgcodecs/src/grfmt_png.cpp
Currently, if `PNG_FOUND`, cmake scripts will check include and parse header while we can use `PNG_VERSION_STRING` conveniently. If `BUILD_PNG`, parse version from `PNG_LIBPNG_VER_STRING` directly is more convenient than parsing major, minor and patch and concatenate them.
The comment of png.h also supports this.
```
/* These should match the first 3 components of PNG_LIBPNG_VER_STRING: */
```
https://github.com/glennrp/libpng/blob/libpng16/png.h#L287
This patch also modifies `ocv_parse_header_version` macro to receive another parameter to make it more general.
The reason why changing `PNG_VERSION` to `PNG_VERSION_STRING` is to be consistent with cmake's FindPNG.
Patch to opencv_extra has the …
=> Refine logic of parsing PNG version

modules/videoio/src/cap_ios_video_camera.mm
- [x ] I agree to contribute to the project under Apache 2 License.
- [ x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ x] The PR is proposed to the proper branch
=> Replace deprecated symbol with AVVideoCodecTypeH264 deprecated since ios11

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Merge with https://github.com/opencv/opencv_extra/pull/1132.
Resolves https://github.com/opencv/opencv/issues/24697
Credits to @LaurentBerger.
---
This is a workaround. I suggest to get input shapes and calculate the output shapes in `getMemoryShapes` so as to keep the best compatibility. It is not always robust getting shapes during the importer stage and we should avoid that as much as possible.
=> dnn onnx: support constaint inputs in einsum importer

cmake/android/android_gradle_projects.cmake, modules/java/android_sdk/build.gradle.in, modules/java/android_sdk/libcxx_helper/CMakeLists.txt, platforms/android/build_aar.sh
- Added JavaDoc package build and publishing
- Added Source package build and publishing
- More metadata for publishing
- Disable native samples build with aar, because prefab is not complete yet
=> Enable Android AAR package build with SDK project itself without Python

3rdparty/ffmpeg/ffmpeg.cmake, modules/videoio/test/test_ffmpeg.cpp
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/80
- FFmpeg 4.4.4
- OpenH264 version 1.8.0
- libVPX version 1.13.1
- libAOM version 3.8.0
previous update: #23846
```
```
=> ffmpeg/4.x: update FFmpeg wrapper 2023.12

cmake/OpenCVDetectCXXCompiler.cmake
Two CMake variable are marked as deprecated and "#TODO next release: remove this". It is introduced in https://github.com/opencv/opencv/pull/11167 which is before the release of 4.0. Since it's deprecated almost six years ago, I think it's OK to remove them.
=> Remove deprecated CMake variable

doc/py_tutorials/py_bindings/py_bindings_basics/py_bindings_basics.markdown
Fixes https://github.com/opencv/opencv/issues/24522
=> Document read-only check in Python bindings

modules/videoio/src/cap_msmf.cpp
Fixes https://github.com/opencv/opencv/issues/24487
Previous trial: https://github.com/opencv/opencv/pull/22347
Documentation: https://learn.microsoft.com/en-us/windows/win32/medfound/video-subtype-guids#luminance-and-depth-formats
=> Reworked camera stream check to exclude non-video formats

modules/imgcodecs/test/test_avif.cpp
close https://github.com/opencv/opencv/issues/24792
(This fix initialize `result` variable only.)
=> imgcodecs: suppress warning at test_avif.cpp

modules/core/include/opencv2/core/cuda/common.hpp
Currently building opencv_core with clang emits the following warnings
> 3 warnings generated.
> [3/109] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/bindings_utils.cpp.o
> In file included from /home/b/repos/opencv/opencv/modules/core/src/bindings_utils.cpp:5:
> In file included from /home/b/repos/opencv/opencv/modules/core/src/precomp.hpp:60:
> In file included from /home/b/repos/opencv/opencv/modules/core/include/opencv2/core/private.cuda.hpp:73:
> /home/b/repos/opencv/opencv/modules/core/include/opencv2/core/cuda/common.hpp:102:87: warning: unused parameter 'tex' [-Wunused-parameter]
>         template<class T> inline void createTextureObjectPitch2D(cudaTextureObject_t* tex, PtrStepSz<T>& img, const cudaTextureDesc& texDesc) {
> …
=> core: fix clang warnings

modules/objdetect/src/aruco/aruco_detector.cpp
Concurrently writing to a `vector<bool>` is not thread-safe.
=> Fix aruco detector thread safety.

modules/videoio/src/cap_gstreamer.cpp
This is just to show which plugin is missing. I had to rebuild opencv with this patch to debug a problem locally, and I think it is generally useful.
=> Better error message for missing gstreamer plugin

modules/dnn/test/test_onnx_importer.cpp
This pull request changes weights of yolov7 model. This was required as the onnx graph of the previous yolov7 outputted detections and **as well as features maps of the model**. Having vector of 4 tensors would make [unification of API for YOLO models](https://github.com/opencv/opencv/pull/24691#discussion_r1435033606) problematic, thus change was required.
Weights are located in this PR [#1134](https://github.com/opencv/opencv_extra/pull/1134)
=> Changed onnx weights of yolov7

cmake/OpenCVCompilerOptions.cmake
```
FAILED: lib/libopencv_core.so.13.0
...
ld: error: undefined symbol: __cxa_atexit
```
Do not try to use --no-undefined on OpenBSD. OpenBSD does not link shared libraries with libc and thus linkage with --no-undefined is expected to fail.
=> Fix building on OpenBSD

cmake/OpenCVFindCANN.cmake
Ascend NPU is a series of AI processors. [hiascend](https://www.hiascend.com/). And Compute Architecture for Neural Network (CANN) is a set of computing architectures that serves NPU and programming.
This commit links the libacl_dvpp_mpi library when building with CANN backend. For implementation, please refer to https://github.com/opencv/opencv_contrib/pull/3608.
- [N/A] There is a reference to the original bug report and related work
=> Link libacl_dvpp_mpi library when building with CANN backend

modules/highgui/src/window_QT.cpp
I was trying to fix highgui's statusbar got cropped.
However, none of my fixes by adjusting heights take any effect, and it reveals a deeper and actual problem.
The `QBoxLayout myGlobalLayout -> addWidget`'s 2nd parameter is `stretch` rather than `alignment`, so the old code does nothing, and the layout does not work.
https://doc.qt.io/qt-6/qboxlayout.html#addWidget
`myStatusBar->setFixedHeight(20);` is a ad-hoc fix becuase when adding the statusbar, the author did not realize that the layout was not working.;
Since the layout is fixed, setting a fixed height is no longer needed (both statusbar & qlabel's default height is reasonably small, roughly text height).
After:
The statusbar text looks perfect now.
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good …
=> fix highgui qt's statusbar text got cropped

modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/test/test_ffmpeg.cpp, modules/videoio/test/test_precomp.hpp
Fix https://github.com/opencv/opencv/issues/24774
=> videoio: fix 24774 incorrect timestamps returned by VideoCapture when CAP_PROP_FORMAT == -1

cmake/OpenCVCompilerOptimizations.cmake
Sorry for submitting multiple PRs.
This is a follow-up of #24642 and #24698 
I just concluded that `if` section of each compiler should correspond where defining the option and calling the `ocv_cpu_aarch64_baseline_merge_feature_options`
=> cmake: brush up the cmake part of merging option

modules/dnn/src/cuda/eltwise_ops.cu, modules/dnn/src/cuda4dnn/csl/tensor.hpp, modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/src/net_impl_fuse.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_layers.cpp
Inspired by https://github.com/opencv/opencv/pull/24786. This PR keeps the fusion of `NaryEltwise` and `Concat` while addressed the data missing problem via supporting broadcasting if a.rank() != b.rank().
Resolves https://github.com/opencv/opencv/issues/23977
Resolves https://github.com/opencv/opencv/issues/24606
Resolves https://github.com/opencv/opencv/issues/24635
Resolves https://github.com/opencv/opencv/issues/24721 
=> dnn (cuda): support broadcasting if a.rank() != b.rank()

platforms/android/aar-template/OpenCV/build.gradle.template, platforms/android/build_java_shared_aar.py, platforms/android/build_static_aar.py
Modified AAR script.
Now the script creates 2 maven repos. The first repo contains sources jar, javadoc jar and AAR without cpp libraries. The second repo contains modified AAR with cpp libraries. The script merges two repos into one.
=> Modified AAR script: added javadoc to Android Maven

modules/dnn/src/layers/einsum_layer.cpp, modules/dnn/test/test_onnx_importer.cpp
This PR extents support of Einsum layer #24037. Now 1d vector operation are supported by einsum layer.  
=> 1d  operation support for einsum layer

modules/dnn/src/layers/cpu_kernels/fast_gemm.cpp, modules/dnn/src/layers/einsum_layer.cpp
This PR replaces iterative batch matrix multiplication which `FastGemmBatch` in Einsum layer. 
=> Replace interactive batched Matrix Multiply. 
