opencv/opencv

doc/js_tutorials/js_setup/js_nodejs/js_nodejs.markdown
=> Missing import

.github/workflows/PR-4.x.yaml
=> Add workflows for macOS ARM64 and macOS x86_64 for branch 4.x

.github/workflows/PR-5.x.yaml
=> Add workflows for macOS ARM64 and macOS x86_64 for branch 5.x

.github/workflows/PR-3.4.yaml
=> Add workflows for macOS ARM64 and macOS x86_64 for branch 3.4

modules/core/src/hal_internal.cpp
=> Fix typo that prevents compilation with sanitizer.

doc/opencv.bib, doc/tutorials/features2d/homography/homography.markdown, modules/calib3d/include/opencv2/calib3d.hpp, samples/cpp/tutorial_code/features2D/Homography/pose_from_homography.cpp
Some refresh of the tutorial, a missing link is replaced with https://web.archive.org/
=> Update homography tutorial

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/grfmt_jpeg.cpp, modules/imgcodecs/test/test_jpeg.cpp, samples/cpp/imgcodecs_jpeg.cpp
fix https://github.com/opencv/opencv/issues/22052
This merge request contains sample and test program.
```
```
=> imgcodecs: jpeg: add IMWRITE_JPEG_SAMPLING_FACTOR parameter

modules/videoio/src/cap_ffmpeg_impl.hpp
resolves #22126
- [ x ] I agree to contribute to the project under Apache 2 License.
- [ x ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ x ] The PR is proposed to the proper branch
- [ x ] There is a reference to the original bug report and related work
- [ x ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ x ] The feature is well documented and sample code can be built with the project CMake
=> VideoCapture segfault fix for #22126

.github/workflows/PR-4.x.yaml
=> Workflow for labeled iOS PRs in 4.x branch

.github/workflows/PR-3.4.yaml
=> Workflow for labeled iOS PRs in 3.4 branch

modules/js/src/core_bindings.cpp
=> Fix missing CharVector for JavaScript bindings

modules/imgproc/src/pyramids.cpp, modules/imgproc/test/test_pyramid.cpp
=> fix the bug in pyrUp

.github/workflows/PR-3.4.yaml
I am using a ultrawide monitor and the names in the status box look good on my side. Please take a look on your side whether the name is too long to fit in the status box.
cc @ShiqiYu , please take a look as well.
=> Rename jobs for better understanding for branch 3.4

.github/workflows/PR-4.x.yaml
I am using a ultrawide monitor and the names in the status box look good on my side. Please take a look on your side whether the name is too long to fit in the status box.
cc @ShiqiYu , please take a look as well.
=> Rename jobs for better understanding for branch 4.x

.github/workflows/PR-5.x.yaml
I am using a ultrawide monitor and the names in the status box look good on my side. Please take a look on your side whether the name is too long to fit in the status box.
cc @ShiqiYu , please take a look as well.
=> Rename jobs for better understanding for branch 5.x

CMakeLists.txt, modules/core/CMakeLists.txt, modules/highgui/CMakeLists.txt, modules/highgui/cmake/detect_wayland.cmake, modules/highgui/cmake/init.cmake, modules/highgui/src/precomp.hpp, modules/highgui/src/window.cpp, modules/highgui/src/window_wayland.cpp, modules/highgui/test/test_gui.cpp
-enable using -DWITH_WAYLAND=ON
-adapted from https://github.com/pfpacket/opencv-wayland
-using stable protocol
-overrides HAVE_QT if HAVE_WAYLAND and WITH_WAYLAND are set
Signed-off-by: Joel Winarske <joel.winarske@gmail.com>
@pfpacket
=> highgui Wayland xdg_shell

3rdparty/carotene/CMakeLists.txt, 3rdparty/carotene/hal/CMakeLists.txt, cmake/OpenCVDetectHalide.cmake, modules/python/CMakeLists.txt, platforms/android/android.toolchain.cmake, platforms/linux/gnu.toolchain.cmake, samples/CMakeLists.txt, samples/cpp/example_cmake/CMakeLists.txt, samples/hal/c_hal/CMakeLists.txt, samples/hal/slow_hal/CMakeLists.txt, samples/openvx/CMakeLists.txt
=> DRY (don't repeat yourself)

.github/workflows/PR-5.x.yaml
=> Android GHA workflow for 5.x branch

.github/workflows/PR-3.4.yaml
=> Android GHA workflow for 3.4 branch

.github/workflows/PR-4.x.yaml
=> Android GHA workflow for 4.x branch

modules/features2d/src/sift.simd.hpp
=> build: add missing GCC condition for pragma

.github/workflows/PR-3.4.yaml
=> Docs workflow in GHA for 3.4

.github/workflows/PR-4.x.yaml
=> Docs workflow in GHA for 4.x

.github/workflows/PR-5.x.yaml
=> Docs workflow in GHA for 5.x

.github/workflows/PR-3.4.yaml
=> Workflow on Ubuntu 14.04 for 3.4 branch

modules/imgproc/include/opencv2/imgproc.hpp
=> Imgproc: Fix doxygen typo

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/five-point.cpp, modules/calib3d/src/sqpnp.hpp
=> Typos: cheirality vs chirality

apps/interactive-calibration/calibCommon.hpp, apps/interactive-calibration/frameProcessor.cpp, apps/interactive-calibration/frameProcessor.hpp, apps/interactive-calibration/main.cpp, apps/interactive-calibration/parametersController.cpp
=> Add symmetric circles board support to interactive calibration app

apps/interactive-calibration/calibCommon.hpp, apps/interactive-calibration/calibPipeline.cpp, apps/interactive-calibration/main.cpp, apps/interactive-calibration/parametersController.cpp
=> Add option to force reopen camera in interactive calibration tool

modules/highgui/CMakeLists.txt, modules/highgui/src/plugin_wrapper.impl.hpp, modules/highgui/src/precomp.hpp, modules/highgui/src/window_w32.cpp
=> make imgcodecs optional for highgui

apps/interactive-calibration/main.cpp, doc/tutorials/calib3d/interactive_calibration/interactive_calibration.markdown
Merge after: https://github.com/opencv/opencv/pull/22146, https://github.com/opencv/opencv/pull/22135, https://github.com/opencv/opencv/pull/22147, https://github.com/opencv/opencv/pull/22079
=> Add new parameters to interactive calibration tool tutorial

doc/py_tutorials/py_calib3d/py_calibration/py_calibration.markdown
issue: #22360 
[N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
[N/A] The feature is well documented and sample code can be built with the project CMake
=> Fix the example in py_calib3d/py_calibration

modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.cpp
=> Fix infinite loop in obsensor

modules/gapi/src/streaming/onevpl/cfg_param_device_selector.cpp, modules/gapi/test/streaming/gapi_streaming_tests.cpp
=> Fix G-API OneVPL compilation

CMakeLists.txt, cmake/OpenCVGenPkgconfig.cmake
=> cmake: Enable pkgconfig support for mingw

modules/3d/src/levmarq.cpp
Log level dropped from `INFO` to `DEBUG` to reduce log size.
Solves #22369
=> LevMarq: log level lowered

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.hpp, modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp, samples/cpp/videocapture_obsensor.cpp
Hi, 
I'm not sure if the whitespace needs to be removed manually.
Only for 4.x branch.
#22196
=> remove whitespace in 4.x

samples/cpp/calibration.cpp
---
Allow passing some rough camera intrinsic parameters as an initial guess allow converging to the correct intrinsic parameters with my data.
With some `2048x2048` calibration images:
- with `CALIB_FIX_K3=1`, reprojection error is `1.2656`
- with `CALIB_FIX_K3=0`, reprojection error is `5.1693`
- with `CALIB_FIX_K3=0` and by using `fx=1400, fy=1400, cx=1024, cy=1024`, reprojection error is `0.39724`
The same images but resized to `1024x1024`:
- with `CALIB_FIX_K3=1`, reprojection error is `0.65225`
- with `CALIB_FIX_K3=0`, reprojection error is `2.31561`
- with `CALIB_FIX_K3=0` and by using `fx=700, fy=700, cx=512, cy=512`, reprojection error …
=> [3.4] Add flag to pass initial guess for camera intrinsics into the calibration exe

modules/imgcodecs/src/grfmt_tiff.cpp, modules/imgcodecs/test/test_tiff.cpp
=> 4-bit_palette_color

modules/gapi/samples/onevpl_infer_single_roi.cpp, modules/gapi/src/streaming/onevpl/accelerators/accel_policy_va_api.cpp, modules/gapi/src/streaming/onevpl/cfg_param_device_selector.cpp
=> G-API: Fix OneVPL linux build

modules/videoio/test/test_ffmpeg.cpp
=> videoio(test): fix build warning

samples/data/dnn/object_detection_classes_yolov4.txt, samples/dnn/models.yml
I don't know if this action is necessary, or the previous PR scale for the brach master.
Thanks.
=> ADD weights yolov4 in models.yml

modules/imgproc/src/hough.cpp
=> Improvement on error handling for HoughCircles

doc/pattern_tools/svgfig.py
The issue was discussed on [opencv forum](https://forum.opencv.org/t/using-example-calibration-target-code/7823/11) and created under https://github.com/opencv/opencv/issues/21708.
=> Save output file to local directory instead of desktop (for windows)

platforms/android/android.toolchain.cmake, samples/cpp/tutorial_code/video/meanshift/camshift.cpp, samples/cpp/tutorial_code/video/meanshift/meanshift.cpp, samples/java/tutorial_code/video/meanshift/CamshiftDemo.java, samples/java/tutorial_code/video/meanshift/MeanshiftDemo.java, samples/winrt/ImageManipulations/MainPage.xaml.cpp
=> Fix some typos in platforms/, samples/, 3rdparty/.

modules/core/src/arithm.cpp, modules/core/src/minmax.cpp, modules/core/test/test_mat.cpp
=> Changes separated from Mat 1D support in core #18594

modules/calib/src/calibration.cpp
In `calibrateCameraRO` and `stereoCalibrate` the last stage is LevMarq-driven fine-tuning.
If fine-tuning fails, then a per view error (which is calculated at every callback call) can be incorrect (since it corresponds to failed parameters) and should be recalculated.
=> Calibration per view error fixed

3rdparty/readme.txt
=> Update 3rdparty readme.txt for spng

modules/core/include/opencv2/core/fast_math.hpp
This patch optimizes the cvCeil and cvFloor functions on
the LoongArch platform.
=> Optimize the cvCeil and cvFloor functions for LoongArch

cmake/OpenCVFindTIMVX.cmake
Signed-off-by: xiang.zhang <xiang.zhang@verisilicon.com>
=> Disable default path while search libtim-vx.so with TIMVX_INSTALL_DIR

3rdparty/readme.txt
- [] There is a reference to the original bug report and related work
=> 3rdparty: Update readme.txt for libjpeg-turbo simd

modules/highgui/src/window_cocoa.mm
naive fix for the #22483 issue.
=> add explicit onChange callback in cocoa cvSetTrackbarPos

modules/videoio/src/cap_android_mediandk.cpp, modules/videoio/src/cap_interface.hpp, modules/videoio/src/videoio_registry.cpp
=> Add H264 / H265 writter support for Android

modules/gapi/src/streaming/onevpl/source_priv.cpp
=> G-API: Replace MFX major version assertion to warning

modules/videoio/src/cap_android_camera.cpp
Fix #22101
Adjust the plane lengths check for Android Camera to consider the case where the frame stride is longer than the frame width.
If the frame stride is longer than the frame width then use a submat to exclude the unwanted data on the right of the image
=> Fix for frame stride wider than frame width for 1080p issue

modules/3d/src/rgbd/normal.cpp, modules/3d/src/rgbd/odometry.cpp, modules/3d/src/rgbd/odometry_functions.cpp, modules/calib/src/calibration.cpp, modules/calib/test/test_cameracalibration.cpp
An attempt to fix broken compilation caused by #22499 
```
```
=> Fix MSVC15 compilation

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/gather_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/1007
Should resolve #20439, resolve #19957
=> add Gather implementation

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_read_write.cpp
I am trying to finalize #17753 pr. To understand the requirements and see what we can do I also take a look at #6574. 
=> [GSoC 2022] Multipage Image Decoder API

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/dnn/dnn_halide_scheduling/dnn_halide_scheduling.markdown, doc/tutorials/dnn/dnn_openvino/dnn_openvino.markdown, doc/tutorials/dnn/table_of_content_dnn.markdown, modules/dnn/include/opencv2/dnn/dnn.hpp
=> OpenCV for OpenVINO documentation

modules/dnn/src/onnx/onnx_importer.cpp
=> DNN: Remove unused code in onnx_importer.cpp

modules/gapi/samples/pipeline_modeling_tool/dummy_source.hpp, modules/gapi/samples/pipeline_modeling_tool/pipeline.hpp, modules/gapi/samples/pipeline_modeling_tool/pipeline_builder.hpp, modules/gapi/samples/pipeline_modeling_tool/utils.hpp
=> [G-API] Pipeline modeling tool - expand performance report

modules/core/src/hal_internal.cpp
=> Move marking memory as initialized earlier.

modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Related test data: [PR at opencv_extra](https://github.com/opencv/opencv_extra/pull/1010).
=> DNN: support GreaterOrEqual and LessOrEqual op in ONNX

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_tiff.cpp
=> support use memory buffer as input to read multi-page image

.github/workflows/PR-5.x.yaml
=> Workflow Ubuntu 20.04 x64 with CUDA support (5.x)

modules/core/include/opencv2/core/types.hpp
=> core: expose rectangle intersection to bindings

cmake/OpenCVPCHSupport.cmake, modules/calib3d/src/usac/dls_solver.cpp, modules/calib3d/src/usac/essential_solver.cpp
=> build(-system) fixes

modules/dnn/src/int8layers/pooling_layer.cpp, modules/dnn/src/onnx/onnx_importer.cpp
Related issues #22509 and #22442.
=> Parsing quantized nodes does not rely on names

.github/workflows/PR-5.x.yaml
=> Trigger on dnn (onnx) label (5.x)

.github/workflows/PR-4.x.yaml
=> Trigger on "category: dnn (onnx)" label

modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
=> Address CUDA-related errors

doc/opencv.bib
---
Fix https://github.com/opencv/opencv/issues/22626 using:
- https://dblp.org/rec/conf/bmvc/AlcantarillaNB13.html?view=bibtex
- http://www.bmva.org/bmvc/2013/Papers/paper0013/index.html
=> Fix AKAZE bib reference

modules/ts/misc/chart.py, modules/ts/misc/color.py, modules/ts/misc/concatlogs.py, modules/ts/misc/perf_tests_timing.py, modules/ts/misc/report.py, modules/ts/misc/run.py, modules/ts/misc/run_android.py, modules/ts/misc/run_long.py, modules/ts/misc/run_suite.py, modules/ts/misc/run_utils.py, modules/ts/misc/summary.py, modules/ts/misc/table_formatter.py, modules/ts/misc/testlog_parser.py, modules/ts/misc/trace_profiler.py
* Added documentation strings for all scripts in `modules/ts/misc`
* Changed executable bit for several scripts (enabled for some, disabled for others)
=> ts: basic documentation for utility scripts

cmake/android/android_gradle_projects.cmake, samples/android/build.gradle.in
Force using of the same CMake & NDK version during the build.
```
force_builders_only=Android armeabi-v7a,Android pack
```
=> android: update build scripts

modules/imgproc/src/smooth.dispatch.cpp
=> imgproc: sigma2=sigma1 in top-level function of GaussianBlur

modules/dnn/src/onnx/onnx_importer.cpp
=> DNN: remove never used code in onnximporter

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp
Backport: Related PR https://github.com/opencv/opencv/pull/22725
=> Fix infinit loop in tf 3.4 branch

3rdparty/zlib/CMakeLists.txt, 3rdparty/zlib/ChangeLog, 3rdparty/zlib/LICENSE, 3rdparty/zlib/README, 3rdparty/zlib/compress.c, 3rdparty/zlib/crc32.c, 3rdparty/zlib/deflate.c, 3rdparty/zlib/deflate.h, 3rdparty/zlib/gzlib.c, 3rdparty/zlib/gzread.c, 3rdparty/zlib/gzwrite.c, 3rdparty/zlib/infback.c, 3rdparty/zlib/inflate.c, 3rdparty/zlib/inftrees.c, 3rdparty/zlib/inftrees.h, 3rdparty/zlib/trees.c, 3rdparty/zlib/uncompr.c, 3rdparty/zlib/zconf.h, 3rdparty/zlib/zlib.h, 3rdparty/zlib/zutil.c, 3rdparty/zlib/zutil.h
resolves #22764
https://github.com/madler/zlib/releases/tag/v1.2.13
- replace README -> LICENSE in install distribution
---
previous update: https://github.com/opencv/opencv/pull/21821
---
```
```
=> 3rdparty: zlib 1.2.12 => 1.2.13

modules/objdetect/src/qrcode.cpp
=> log QR version and corners

modules/highgui/src/window_w32.cpp
Details and consequences are described in the related issue.
=> Fix #22766: Corrected off-by one error causing inconsistent row spacing.

modules/core/src/opengl.cpp
=> Print CL status code on error in opengl interop functions

modules/core/src/opengl.cpp
Fix for https://github.com/opencv/opencv/pull/22855
```
```
=> Fixed OpenGL errors formatting

modules/core/src/opengl.cpp
Address issues found in https://github.com/opencv/opencv/pull/22866
```
```
=> More fixes for OpenCL error reporting

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/nms.cpp, modules/dnn/test/test_nms.cpp
Resolves #22851.
Merge with https://github.com/opencv/opencv_extra/pull/1020.
=> dnn: add batched nms

modules/videoio/src/cap.cpp, modules/videoio/src/cap_interface.hpp
Related #22792
Fixed build with cmake option: `-DVIDEOIO_PLUGIN_LIST=ffmpeg` by moving new function to the header.
```
build_image:Custom=ffmpeg-master
```
=> videoio: fixed FFmpeg plugin build

modules/calib3d/test/test_cameracalibration.cpp, modules/calib3d/test/test_fisheye.cpp, modules/core/include/opencv2/core/types.hpp, modules/core/test/test_intrin_utils.hpp, modules/gapi/include/opencv2/gapi/ocl/goclkernel.hpp, modules/gapi/src/streaming/onevpl/default.cpp, modules/objdetect/src/qrcode.cpp, modules/video/src/tracking/tracker_nano.cpp
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/3389
```
force_builders=Win64,Win64 OpenCL,Win32,Custom Win
```
=> build: fix/eliminate MSVC warnings

modules/videoio/src/cap_avfoundation_mac.mm
=> fix: AVFoundation inconsistent camera indices

modules/core/include/opencv2/core/bindings_utils.hpp, modules/python/src2/cv2_convert.cpp, modules/python/src2/cv2_convert.hpp, modules/python/test/test_misc.py, modules/videoio/include/opencv2/videoio.hpp, modules/videoio/misc/python/pyopencv_videoio.hpp, modules/videoio/src/cap.cpp
Add Python bindings for VideoCapture::waitAny #21826
=> Add waitAny wrapper and bindings

modules/core/src/parallel_impl.cpp
This is fixing https://github.com/opencv/opencv/issues/22852
=> Fix slower CV_PAUSE on SkyLake and above.

modules/videoio/src/cap_obsensor/obsensor_stream_channel_interface.hpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_msmf.cpp, modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp, modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.hpp, modules/videoio/src/cap_obsensor_capture.cpp, modules/videoio/src/cap_obsensor_capture.hpp
| OS | Compiler | Camera | Result |
|-----|-----------|---------|--------|
|Windows11| (VS2022)MSVC17.3|Orbbec Gemini 2|Pass|
|Windows11| (VS2022)MSVC17.3|Orbbec Astra 2|Pass|
|Ubuntu22.04|GCC9.2|Orbbec Gemini 2|Pass|
|Ubuntu22.04|GCC9.2|Orbbec Astra 2|Pass|
=> videoio: add Orbbec Gemini 2 and Astra 2 camera support

modules/core/include/opencv2/core.hpp, modules/core/src/algorithm.cpp, modules/features2d/include/opencv2/features2d.hpp, modules/python/src2/gen2.py
Java and Obj-C/Swift are out-of-scope as `FileStorage` was excluded previously there.
relates #9247
TODO:
```
```
=> python: resolve Ptr<FileStorage> requirement issue

modules/videoio/src/cap_v4l.cpp
=> videoio(v4l): initialize variables

modules/objdetect/include/opencv2/objdetect/aruco_detector.hpp, modules/objdetect/include/opencv2/objdetect/aruco_dictionary.hpp, modules/objdetect/src/aruco/aruco_detector.cpp, modules/objdetect/src/aruco/aruco_dictionary.cpp, modules/objdetect/src/aruco/aruco_utils.hpp
**Merge after contrib**: https://github.com/opencv/opencv_contrib/pull/3397
relates #22368
=> aruco(cleanup): don't use Ptr<FileStorage>

modules/photo/perf/perf_hdr.cpp, modules/photo/src/merge.cpp, modules/photo/test/test_hdr.cpp, modules/python/test/test_umat.py
With this PR the process function for MergeMertens is parallelized. Also performance tests for all HDR methods are added as well as a determinism test for the parallel version of MergeMertens.
Running the photo performance tests locally on my workstation before this PR:
```
[----------] 3 tests from HDR
[ RUN      ] HDR.Mertens
[ PERFSTAT ]    (samples=13   mean=216.34   median=216.96   min=204.84   stddev=6.12 (2.8%))
[       OK ] HDR.Mertens (2949 ms)
[ RUN      ] HDR.Debevec
[ PERFSTAT ]    (samples=13   mean=69.54   median=69.15   min=67.06   stddev=1.77 (2.5%))
[       OK ] HDR.Debevec (1016 ms)
[ RUN      ] HDR.Robertson
[ PERFSTAT ]    (samples=13   mean=50.11   median=50.38   min=47.92   stddev=1.28 (2.6%))
[       OK ] HDR.Robertson (763 ms)
[----------] 3 tests from HDR (4728 ms …
```
=> Parallelize implementation of HDR MergeMertens.

platforms/js/opencv_js.config.py
Bug: https://github.com/opencv/opencv/issues/22989
```
buildworker:Custom=linux-4,linux-1
```
=> Update Javascript bindings for Aruco after migration

doc/tutorials/introduction/windows_install/windows_install.markdown
The folder `http://sourceforge.net/projects/opencvlibrary/files/opencv-win/` is stale and wasn't updated since 2018. The parent folder `http://sourceforge.net/projects/opencvlibrary/files/` has fresh windows install exe files.
=> SourceForge folder update

modules/videoio/src/cap_ffmpeg_impl.hpp
- use `cv::getNumberOfCPUs()` with better implementation of detection of available/online/quota CPUs (ref #16457)
- follow FFmpeg warning and limit to 16 threads (visible through OPENCV_FFMPEG_DEBUG=1 mode)
- `CAP_PROP_N_THREADS` property has higher priority (from #22248)
Validated through:
```
$ OPENCV_FFMPEG_DEBUG=1 OPENCV_FFMPEG_THREADS=40 taskset -c 1-18 ./bin/opencv_test_videoio --gtest_filter=*threads*
```
=> videoio(ffmpeg): limit number of default threads

modules/objdetect/src/qrcode.cpp
Fixes https://github.com/opencv/opencv/issues/22978
Related changes: https://github.com/opencv/opencv/pull/22814
=> Valgrind issues fix in QRCode detector.

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/version.hpp, modules/python/package/setup.py, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
previous PR with version bump: #22027
=> pre: OpenCV 4.7.0 (version++)

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/python/package/setup.py, platforms/android/build_sdk.py, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
previous PR with version bump: #22026
=> pre: OpenCV 3.4.19 (version++)

modules/features2d/src/blobdetector.cpp
https://github.com/opencv/opencv/pull/20367#discussion_r1056690981
=> Fixed blob detector parameters range.

modules/core/include/opencv2/core/version.hpp
=> release: OpenCV 3.4.19

modules/dnn/src/ie_ngraph.cpp
=> dnn(openvino): remove undefined status

modules/dnn/src/layers/fast_convolution/fast_convolution.cpp
Related issue: https://github.com/opencv/opencv/issues/23046
=> DNN: fix invalid memory access

modules/core/include/opencv2/core/version.hpp
Relates: https://github.com/opencv/opencv/pull/22972
=> release: OpenCV 4.7.0

modules/videoio/test/test_audio.cpp
=> videoio(test): skip unstable Media.audio test

doc/opencv.bib, modules/photo/include/opencv2/photo.hpp
=> Fix broken paper link for fastNlMeansDenoising

modules/core/src/hal_internal.cpp
=> Fix compilation with msan

modules/calib3d/test/test_homography.cpp, modules/imgproc/test/test_color.cpp, modules/imgproc/test/test_convhull.cpp, modules/imgproc/test/test_imgwarp.cpp, modules/imgproc/test/test_imgwarp_strict.cpp, modules/ts/src/ts.cpp, modules/video/test/test_estimaterigid.cpp
=> Enable 2-channel arrays in resize tests

modules/ts/src/cuda_test.cpp
merge with contrib https://github.com/opencv/opencv_contrib/pull/3426
=> SURF: make test tolerate to rounding error

modules/3d/perf/perf_tsdf.cpp, modules/3d/src/rgbd/odometry_functions.cpp, modules/3d/src/rgbd/odometry_functions.hpp, modules/3d/src/rgbd/volume_impl.cpp, modules/3d/test/test_odometry.cpp, modules/3d/test/test_tsdf.cpp
```
force_builders=Win64 OpenCL,Win32,Custom Win
```
=> MSVC warnings fixed in 3d module

modules/features2d/src/sift.simd.hpp
=> Fix rootsift

modules/calib/include/opencv2/calib.hpp, modules/calib/src/calibration.cpp, modules/calib/src/fisheye.cpp, modules/calib/test/test_cameracalibration.cpp, modules/calib/test/test_fisheye.cpp
* Port of #22519 to 5.x
* Distortion coefficients were not copied properly, fixed
* Minor coding style chages
=> Stereo calibration perView pose output: port to 5.x

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/src/net_impl_fuse.cpp
Related issue: https://github.com/opencv/opencv/issues/23234.
=> DNN: fuse conv+naryEletwise on CUDA backend.

modules/imgproc/src/color_hsv.simd.hpp, modules/imgproc/test/test_color.cpp
In case of huge (and probably invalid) input, make sure we do not
rely only on the while loops for truncation.
=> Speed up HLS2RGB.

modules/flann/include/opencv2/flann/flann_base.hpp, modules/flann/include/opencv2/flann/saving.h, modules/flann/src/miniflann.cpp
=> Fixed potential memory leak in flann

CMakeLists.txt, cmake/OpenCVModule.cmake
=> Add ENABLE_DELAYLOAD option

samples/opengl/opengl.cpp
=> use findFile in opengl.cpp sample

modules/objdetect/misc/python/test/test_objdetect_aruco.py, modules/objdetect/src/aruco/aruco_board.cpp
=> Fix create aruco Board in Python

modules/videoio/include/opencv2/videoio.hpp
No note in doc about [issue #17687](https://github.com/opencv/opencv/issues/17687) and [PR] (https://github.com/opencv/opencv/pull/20327)
=> Note for MSMF in doc

modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Several fixes for ONNX model from https://huggingface.co/openai/clip-vit-base-patch32
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1049
=> Several fixes for ONNX importer: Expand, Gather

modules/js/src/helpers.js
=> add opencv.js imread function can use OffscreenCanvas

samples/cpp/tutorial_code/Histograms_Matching/MatchTemplate_Demo.cpp, samples/cpp/tutorial_code/Histograms_Matching/calcBackProject_Demo1.cpp, samples/cpp/tutorial_code/Histograms_Matching/compareHist_Demo.cpp, samples/cpp/tutorial_code/ImgProc/anisotropic_image_segmentation/anisotropic_image_segmentation.cpp, samples/cpp/tutorial_code/ImgProc/out_of_focus_deblur_filter/out_of_focus_deblur_filter.cpp, samples/cpp/tutorial_code/ImgProc/periodic_noise_removing_filter/periodic_noise_removing_filter.cpp, samples/cpp/tutorial_code/ImgTrans/generalizedHoughTransform.cpp
Fixes https://github.com/opencv/opencv/issues/23378
=> Fix image loading in tutorials code

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
Fixes https://github.com/opencv/opencv/issues/23295
=> Fix identifying initializers in ONNX graph simplification

modules/objdetect/src/face_detect.cpp, modules/objdetect/test/test_face.cpp
Merge with https://github.com/opencv/opencv_extra/pull/1038
=> upgrade FaceDetectorYN to v2

doc/py_tutorials/py_setup/py_intro/py_intro.markdown
Added fix for sentence in Introduction to OpenCV-Python Tutorials section OpenCV-Python.  
=> Python tutorial intro small grammar update

modules/videoio/src/cap_dshow.cpp
This is a follow-up on #23460. Since OBS uses NV12 internally, it's better to capture in NV12 to avoid unnecessary conversions on the OBS side. This also removes the YUY2 implementation changes in #23460 that were specific to the OBS Virtual Camera.
=> Use NV12 instead of YUY2 for OBS Virtual Camera.

samples/cpp/CMakeLists.txt
=> #21804 Add opencv_gapi as dep to samples/cpp

modules/highgui/include/opencv2/highgui.hpp, modules/highgui/src/window_cocoa.mm
=> add scrollWheel to Cocoa

samples/dnn/models.yml
I don't know if this action is necessary, or the previous PR scale for the brach master.
Thanks.
=> ADD weights  yolov4-tiny in models.yml

samples/python/videocapture_obsensor.py
=> Add python sample of how to use Orbbec camera.

samples/cpp/calibration.cpp
added charuco pattern into calibration.cpp. Added charuco pattern with predefined aruco dictionary and with dictionary from file.
- [х] I agree to contribute to the project under Apache 2 License.
- [х] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [х] The PR is proposed to the proper branch
- [х] There is a reference to the original bug report and related work
- [х] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [х] The feature is well documented and sample code can be built with the project CMake
=> Add charuco pattern into calibration.cpp

.github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml
- N/A There is a reference to the original bug report and related work
=> Fixed a typo in `documentation.yml` and `feature_request.yml`

modules/calib3d/src/fisheye.cpp
=> Fix function name in comment

modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/src/onnx/onnx_graph_simplifier.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_importer.cpp
Merge with test data: https://github.com/opencv/opencv_extra/pull/1054
=> DNN: add ONNX where node support

apps/interactive-calibration/calibCommon.hpp, apps/interactive-calibration/frameProcessor.cpp, apps/interactive-calibration/frameProcessor.hpp, apps/interactive-calibration/main.cpp, apps/interactive-calibration/parametersController.cpp
=> Charuco board into interactive calibration

3rdparty/flatbuffers/README.md, 3rdparty/flatbuffers/include/flatbuffers/array.h, 3rdparty/flatbuffers/include/flatbuffers/base.h, 3rdparty/flatbuffers/include/flatbuffers/buffer.h, 3rdparty/flatbuffers/include/flatbuffers/flatbuffer_builder.h, 3rdparty/flatbuffers/include/flatbuffers/flatbuffers.h, 3rdparty/flatbuffers/include/flatbuffers/stl_emulation.h, 3rdparty/flatbuffers/include/flatbuffers/table.h, 3rdparty/flatbuffers/include/flatbuffers/vector.h, 3rdparty/flatbuffers/include/flatbuffers/vector_downward.h, 3rdparty/flatbuffers/include/flatbuffers/verifier.h, cmake/OpenCVDetectFlatbuffers.cmake, modules/dnn/misc/tflite/schema_generated.h
resolves https://github.com/opencv/opencv/issues/23466
=> Update FlatBuffers source code to 23.5.9

apps/interactive-calibration/frameProcessor.cpp
=> remove unused var

samples/cpp/stereo_calib.cpp
=> added aruco pattern support into stereo_calibration.cpp

modules/core/misc/java/gen_dict.json, modules/core/misc/java/test/CoreTest.java
Issue https://github.com/opencv/opencv/issues/18796
=> Restored Java bindings for CPU features management

modules/features2d/src/affine_feature.cpp, modules/features2d/test/test_affine_feature.cpp
Address https://github.com/opencv/opencv/issues/20865
=> Fixed mask handling in AffineFeature

modules/python/src2/cv2_util.cpp
[https://github.com/opencv/opencv/issues/23633](url)
=> Proposed solution for issue #23633

modules/core/include/opencv2/core/eigen.hpp
Address https://github.com/opencv/opencv/issues/21604
=> Build warning fix on Windows for Eigen wrapper.

platforms/maven/opencv/scripts/properties
Typo present, changing OpenVC to OpenCV.
=> Update properties - typo

.github/workflows/PR-4.x.yaml
Merge after: https://github.com/opencv/ci-gha-workflow/pull/95
=> [CI] : add the ci node of Vulkan

apps/CMakeLists.txt, apps/traincascade/boost.cpp, apps/traincascade/cascadeclassifier.cpp, apps/traincascade/old_ml.hpp, apps/traincascade/old_ml_boost.cpp, apps/traincascade/old_ml_inner_functions.cpp, apps/traincascade/old_ml_precomp.hpp, apps/traincascade/old_ml_tree.cpp
This pull allows to compile traincascade application with OpenCV 4.6. Changes uses new persistence C++ API in place of legacy one.
=> fix: traincascade, use C++ persistence API

modules/dnn/src/layers/cpu_kernels/convolution.cpp
=> DNN: fix potential bug, stride should not be set as 0.

samples/dnn/scene_text_spotting.cpp
=> solve Issue 23685

samples/dnn/text_detection.cpp
=> solve Issue I23683

modules/imgproc/src/templmatch.cpp
@asmorkalov, sorry for reopening. I tried to keep @captain-n3m0's initial commit.
resolves https://github.com/opencv/opencv/issues/23585
=> Update matchTemplate with mask

platforms/ios/build_framework.py
- [X ] I agree to contribute to the project under Apache 2 License.
- [X ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
This pull request fixes bug #23507.
=> updated mac catalyst target to be compatible with latest xCode / macos

modules/gapi/src/backends/ie/giebackend.cpp, modules/gapi/test/infer/gapi_infer_ie_test.cpp
=> WIP: [G-API] IE Backend: Update the condition for applying the resize preprocessing

apps/createsamples/utility.cpp
=> Fixed potential buffer overflow of user file name in create_samples_app

modules/objdetect/include/opencv2/objdetect/aruco_detector.hpp, modules/objdetect/perf/perf_aruco.cpp, modules/objdetect/src/aruco/aruco_detector.cpp, modules/objdetect/test/test_arucodetection.cpp, modules/objdetect/test/test_boarddetection.cpp, modules/objdetect/test/test_charucodetection.cpp
=> fix Java bindings for cornerRefinementMethod binding

modules/gapi/src/backends/ov/govbackend.cpp, modules/gapi/src/backends/ov/govbackend.hpp, modules/gapi/src/backends/ov/util.hpp, modules/gapi/test/infer/gapi_infer_ov_tests.cpp
=> G-API: OpenVINO Backend Hotfix

modules/dnn/src/dnn_utils.cpp
=> checktype in blobFromImages and blobFromImagesWithParams

modules/objdetect/include/opencv2/objdetect.hpp, modules/objdetect/include/opencv2/objdetect/graphical_code_detector.hpp, modules/objdetect/perf/perf_qrcode_pipeline.cpp, modules/objdetect/src/graphical_code_detector.cpp, modules/objdetect/src/graphical_code_detector_impl.hpp, modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qrcode.cpp, samples/cpp/qrcode.cpp
=> Add graphical code detector interface

modules/js/generator/embindgen.py, modules/js/src/core_bindings.cpp, modules/js/test/test_objdetect.js, platforms/js/opencv_js.config.py
Try to address https://github.com/opencv/opencv/issues/23723
```
```
=> Refreshed JavaScript bindings for Aruco related algorithms

modules/dnn/src/layers/cpu_kernels/convolution.cpp
=> fixing typo of a variable name in dnn::runFastConv

modules/js/generator/embindgen.py, platforms/js/opencv_js.config.py
Address: regression https://github.com/opencv/opencv/issues/23737
- Add new base class for QRCodeDetector to JS white-list
- Resolve inheritance relations when all classes are parsed.
- Add branch to handle `std::vector<std::string>` in method parameters.
```
```
=> JS bingings fix after Aruco-based QR code detector integration

modules/js/src/core_bindings.cpp, modules/js/test/test_objdetect.js, platforms/js/opencv_js.config.py
merge after https://github.com/opencv/opencv/pull/23769
=> JS bindings for Aruco-based QR code detector

modules/dnn/src/caffe/caffe_importer.cpp
=> removing unreachable code and fixing a typo

modules/js/generator/embindgen.py, modules/js/src/core_bindings.cpp, modules/js/test/test_objdetect.js, platforms/js/opencv_js.config.py
Merge after https://github.com/opencv/opencv/pull/23666
No JS test for now as model files are required
Also hacked std::string as JS generator omits namespaces by some reason
=> Barcode js bindings

modules/objdetect/test/test_barcode.cpp
* test whole barcode interface (common + specific)
* do not use csv-files
Note: there are minor limitations related to the `set` usage (e.g. algorithm may return multiple identical results and it will not be checked correctly), but this is intended for test simplicity.
=> objdetect: updated barcode test

modules/python/src2/typing_stubs_generation/generation.py
- Export ALL_CAPS versions alongside from normal names for enum constants, since both versions are available in runtime
- Change enum names entries comments to documentary strings
Before patch
```python
RMat_Access_R: int
RMat_Access_W: int
RMat_Access = int  # One of [R, W]
```
After patch
```python
RMat_Access_R: int
RMAT_ACCESS_R: int
RMat_Access_W: int
RMAT_ACCESS_W: int
RMat_Access = int
"""One of [RMat_Access_R, RMAT_ACCESS_R, RMat_Access_W, RMAT_ACCESS_W]"""
```
Resolves: #23776
=> Export enums ALL_CAPS version to typing stub files

modules/objdetect/src/barcode_decoder/common/super_scale.cpp, modules/objdetect/src/barcode_decoder/common/super_scale.hpp
Alternative to https://github.com/opencv/opencv/pull/23818.
Removes duplication from interface part.
=> Fixed barcode to be built without DNN

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/python/package/setup.py, platforms/android/build_sdk.py, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
previous PR with version bump: #22971
=> pre: OpenCV 3.4.20 (version++)

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/version.hpp, modules/python/package/setup.py, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
previous PR with version bump: #22972
=> pre: OpenCV 4.8.0 (version++)

modules/dnn/src/layers/elementwise_layers.cpp
=> dnn: fix overflow in sigmoid layer for 3.4

modules/gapi/src/backends/ov/govbackend.cpp, modules/gapi/src/backends/ov/util.hpp, modules/gapi/test/infer/gapi_infer_ov_tests.cpp
=> G-API: Apply ov::Core lifetime WA for OpenVINO Backend

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
=> dnn: disable warning when loading a fp16 model

modules/core/include/opencv2/core/version.hpp
Related: https://github.com/opencv/opencv/pull/23831
=> Release OpenCV 3.4.20

modules/gapi/src/backends/ov/govbackend.cpp, modules/gapi/src/backends/ov/govbackend.hpp
=> G-API: Fix async inference for OpenVINO backend

modules/core/include/opencv2/core/version.hpp
=> Switch to version 3.4.20-dev

modules/calib3d/src/usac/gamma_values.cpp
=> removing duplicated statement

modules/calib3d/src/usac/degeneracy.cpp, modules/calib3d/src/usac/essential_solver.cpp, modules/calib3d/src/usac/fundamental_solver.cpp, modules/calib3d/src/usac/pnp_solver.cpp, modules/calib3d/src/usac/ransac_solvers.cpp, modules/calib3d/src/usac/sampler.cpp, modules/calib3d/src/usac/termination.cpp, modules/calib3d/src/usac/utils.cpp
just read and correct some typos in `usac`
=> fixing typos in usac

modules/objdetect/test/test_qr_utils.hpp, modules/objdetect/test/test_qrcode.cpp
One variable is unknown while the other one is unused.
=> Fix compilation when HAVE_QUIRC is not set.

modules/videoio/src/cap_images.cpp
=> Add single image support to VideoCapture

modules/videoio/src/cap_images.cpp
resolves #23935
Diff looks slightly complex because I moved out common part (`grabFrame` call) and realigned the code. Actual fix is added `return false` to the `if (!haveImageReader(...))` block. Also unified log messages.
=> videoio: fix CAP_IMAGES with non-numbered file

doc/tutorials/introduction/config_reference/config_reference.markdown, doc/tutorials/introduction/env_reference/env_reference.markdown, doc/tutorials/introduction/table_of_content_introduction.markdown
Collected most environment variables used to a single document.
=> doc: added environment vars reference

doc/opencv.bib, modules/objdetect/include/opencv2/objdetect/aruco_dictionary.hpp
Improves documentation, issue [1939](https://github.com/opencv/opencv_contrib/issues/1939).
=> update ArUco Dictionary documentation

modules/core/include/opencv2/core/fast_math.hpp
=> Fix LoongArch Macro Definition

modules/core/src/ocl.cpp, modules/core/src/system.cpp, modules/dnn/src/layers/max_unpooling_layer.cpp, modules/dnn/src/net_impl.cpp, modules/highgui/src/window_wayland.cpp, modules/imgcodecs/src/grfmt_pxm.cpp, modules/imgcodecs/src/loadsave.cpp
Address: https://github.com/opencv/opencv/issues/23994
=> Use OpenCV logging instead of std::cerr

modules/dnn/src/layers/detection_output_layer.cpp, modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
resolves https://github.com/opencv/opencv/issues/23992
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1076
=> [TFLite] Pack layer and other fixes for SSD from Keras

modules/gapi/include/opencv2/gapi/infer/bindings_onnx.hpp, modules/gapi/include/opencv2/gapi/infer/onnx.hpp, modules/gapi/misc/python/pyopencv_gapi.hpp, modules/gapi/src/backends/onnx/bindings_onnx.cpp, modules/gapi/src/backends/onnx/gonnxbackend.cpp
=> G-API: Support OpenVINO Execution Provider for ONNXRT Backend

modules/imgproc/src/drawing.cpp, modules/imgproc/test/test_drawing.cpp
=> Fixed possible out-of-bound access in circles drawing

modules/flann/include/opencv2/flann/any.h, modules/flann/include/opencv2/flann/general.h, modules/flann/include/opencv2/flann/matrix.h, modules/flann/include/opencv2/flann/params.h, modules/flann/include/opencv2/flann/result_set.h, modules/flann/misc/python/pyopencv_flann.hpp, modules/flann/misc/python/test/test_flann_based_matcher.py
As a side-effect this patch improves reporting errors by FLANN `get_param`.
resolves #21642
=> Fix FLANN python bindings

modules/calib/include/opencv2/calib.hpp, modules/calib/test/test_fisheye.cpp, samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp
=> Unify Pinhole and Fisheye camera models

modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/opencl/activations.cl, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/24051
```
```
=> PReLU with element-wise scales

modules/3d/include/opencv2/3d.hpp, modules/3d/src/five-point.cpp, modules/3d/src/fundam.cpp, modules/3d/src/ptcloud/sac_segmentation.cpp, modules/3d/src/ptsetreg.cpp, modules/3d/src/solvepnp.cpp, modules/3d/src/usac.hpp, modules/3d/src/usac/bundle.cpp, modules/3d/src/usac/degeneracy.cpp, modules/3d/src/usac/dls_solver.cpp, modules/3d/src/usac/essential_solver.cpp, modules/3d/src/usac/estimator.cpp, modules/3d/src/usac/fundamental_solver.cpp, modules/3d/src/usac/gamma_values.cpp, modules/3d/src/usac/homography_solver.cpp, modules/3d/src/usac/local_optimization.cpp, modules/3d/src/usac/plane_solver.cpp, modules/3d/src/usac/pnp_solver.cpp, modules/3d/src/usac/quality.cpp, modules/3d/src/usac/ransac_solvers.cpp, modules/3d/src/usac/sampler.cpp, modules/3d/src/usac/sphere_solver.cpp, modules/3d/src/usac/termination.cpp, modules/3d/src/usac/utils.cpp, modules/3d/test/test_sac_segmentation.cpp, modules/3d/test/test_usac.cpp
Base branch is PR #23979. Merging PR #23078 and PR #23806 to 5.x
=> Merge usac to 5.x

modules/dnn/src/layers/detection_output_layer.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_model.cpp, modules/dnn/test/test_tf_importer.cpp
required for https://github.com/opencv/opencv/pull/23987
```
```
=> DetectionOutput layer on OpenVINO without limitations

.github/workflows/PR-5.x.yaml
related: https://github.com/opencv/opencv_contrib/pull/3543
=> Add CI configuration with Ubuntu 22.04 for 5.x branch.

modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/max_unpooling_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/src/net_openvino.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
* MaxUnpooling with OpenVINO
* Fully connected with transposed inputs/weights with OpenVINO
* Enable backends tests for TFLite (related to https://github.com/opencv/opencv/issues/23992#issuecomment-1640691722)
* Increase existing tests thresholds
```
```
=> TFLite models on different backends (tests and improvements)

modules/videoio/include/opencv2/videoio.hpp
fix https://github.com/opencv/opencv/issues/24081
=> videoio: doc: add odd width or height limitation for FFMPEG

modules/core/src/persistence.cpp
Although acceptable to Intel CPUs, it's still undefined behaviour according to the C++ standard.
It can be replaced with memcpy, which makes the code much simpler, and it generates the same assembly code with gcc and clang with -O2 (verified with godbolt).
=> Fixed invalid cast and unaligned memory access

modules/dnn/misc/python/test/test_dnn.py, modules/dnn/perf/perf_caffe.cpp, modules/dnn/perf/perf_net.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/ocl4dnn/src/math_functions.cpp, modules/dnn/src/opencl/gemm_buffer.cl, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_int8_layers.cpp, modules/dnn/test/test_model.cpp
* resolves https://github.com/opencv/opencv/issues/24111
* Updates required for actual models from https://github.com/opencv/opencv_extra/pull/1080
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1080
```
```
=> OCL_FP16 MatMul with large batch

modules/dnn/src/op_halide.cpp
=> add missing include

modules/gapi/misc/python/test/test_gapi_infer.py, modules/gapi/misc/python/test/test_gapi_infer_ov.py, modules/gapi/test/infer/gapi_infer_ie_test.cpp, modules/gapi/test/infer/gapi_infer_ov_tests.cpp
related: https://github.com/opencv/ci-gha-workflow/pull/109
=> Mark OpenVINO models for G-API tests optional

modules/objdetect/test/test_qrcode_encode.cpp
=> Fix compilation when forcing later C++.

modules/calib3d/src/ap3p.cpp, modules/calib3d/test/test_solvepnp_ransac.cpp
=> Fix crash in ap3p

modules/imgproc/src/distransform.cpp, modules/imgproc/test/test_distancetransform.cpp
resolves https://github.com/opencv/opencv/issues/23895
=> distanceTransform for inputs with large step and height

samples/dnn/js_face_recognition.html
Changed face recognition model in js_face_recognition dnn sample: replaced torch7 model from https://github.com/pyannote/pyannote-data by ONNX model from https://github.com/opencv/opencv_zoo/tree/main/models/face_recognition_sface
=> Replaced torch7 by onnx model in js_face_recognition dnn sample

samples/dnn/fast_neural_style.py
Replaced torch7 model by ONNX model in fast-neural-style dnn sample.
=> Replaced torch7 model by ONNX model in fast-neural-style dnn sample

modules/dnn/src/net_openvino.cpp
resolves https://github.com/opencv/opencv/issues/24249
=> Build with OpenVINO in Debug

CMakeLists.txt, modules/dnn/CMakeLists.txt, modules/dnn/src/dnn_params.cpp
- disable message on default value
relates #24218, #24085
=> cmake: revise OPENCV_DNN_BACKEND_DEFAULT integration

modules/js/test/test_core.js, modules/js/test/test_mat.js, modules/js/test/tests.html, modules/js/test/tests.js, platforms/js/opencv_js.config.py
=> JavaScript: include LUT support

modules/videoio/test/test_camera.cpp
Related to https://github.com/opencv/opencv/pull/24142
=> More strict test for MSMF FOURCC (camera)

modules/dnn/test/test_caffe_importer.cpp
resolves https://github.com/opencv/opencv/issues/24256
ci: https://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/100195
```
```
=> Higher threshold for FasterRCNN_vgg16

modules/calib3d/src/checkchessboard.cpp, modules/objdetect/src/aruco/apriltag/apriltag_quad_thresh.cpp
=> More fixes for iterators-are-pointers case

modules/dnn/perf/perf_gemm.cpp, modules/dnn/src/layers/gemm_layer.cpp
CI validation:
Checklist:
```
Xbuild_image:Custom=ubuntu-openvino-2022.1.0:20.04
```
=> Update OpenVINO init of new GEMM layer

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/python/package/setup.py, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
Previous version bump: https://github.com/opencv/opencv/pull/23833
=> Version update to 4.8.1.

.github/workflows/PR-4.x.yaml
Pipeline: https://github.com/opencv/ci-gha-workflow/pull/109
Dockerfile: https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/19
=> Added CI with OpenVINO for DNN and G-API.

samples/dnn/README.md
**PR Summary**
PR updated the location of the `samples/dnn/download_models.py` file.
=> fix: update location to `samples/dnn/download_models.py`

modules/dnn/src/layers/cpu_kernels/fast_gemm.cpp, modules/dnn/src/layers/cpu_kernels/fast_gemm_kernels.default.hpp, modules/dnn/src/layers/cpu_kernels/fast_gemm_kernels.simd.hpp, modules/dnn/src/layers/gemm_layer.cpp, modules/dnn/test/test_onnx_importer.cpp
Resolves https://github.com/opencv/opencv/issues/24312
Resolves https://github.com/opencv/opencv/pull/23897#pullrequestreview-1639273804
```
force_builders=Linux OpenCL,Win64 OpenCL,Custom
modules_filter:Custom=none
disable_ipp:Custom=ON
```
=> dnn: hotfixes for fast gemm

modules/gapi/cmake/DownloadADE.cmake
Previous update: https://github.com/opencv/opencv/pull/24337
=> Updated libade to 0.1.2d

modules/dnn/src/layers/gather_elements_layer.cpp
Resolves https://github.com/opencv/opencv/pull/24092#discussion_r1364875338
=> dnn: fp16 support for gather elements

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn_read.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_misc.cpp
=> Native ONNX to Inference Engine backend

modules/imgcodecs/src/grfmt_avif.cpp
=> Make sure AVIF decoder is destroyed in case of failure

.github/workflows/PR-5.x.yaml
=> Enable RISC-V CI configuration for 5.x

modules/video/src/tracking/tracker_vit.cpp
=> video tracking (dnn): set backend and target for TrackerVit

modules/dnn/test/test_graph_simplifier.cpp, modules/dnn/test/test_layer_fusion.cpp
=> dnn (onnx): add subgraph fusion tests

doc/opencv.bib, doc/tutorials/calib3d/interactive_calibration/interactive_calibration.markdown, doc/tutorials/calib3d/table_of_content_calib3d.markdown, doc/tutorials/calib3d/usac.markdown
=> Reformat USAC tutorial

modules/dnn/src/graph_simplifier.cpp, modules/dnn/src/graph_simplifier.hpp, modules/dnn/src/onnx/onnx_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/test/test_onnx_importer.cpp
related: https://github.com/opencv/opencv/pull/24463#issuecomment-1783033931
=> Commutative rules for DNN subgraphs fusion

modules/core/include/opencv2/core/hal/intrin_rvv.hpp, modules/core/include/opencv2/core/hal/intrin_rvv071.hpp, modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
=> Exclude RVV UI internals from Doxygen documentation.

modules/3d/test/test_normal.cpp
Platform: RISC-V board LicheePi4A
Version: 5.x
Configuration: static build, OpenCL OFF, Release/Debug
Apparently calling `inv()` expression during static initialization might cause segmentation fault. Use lazy-initialized singletone instead.
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000000dd6c0 in cv::MatExpr::operator cv::Mat (this=0x3fffffef58) at /work/opencv/modules/core/include/opencv2/core/mat.inl.hpp:3183
3183	    op->assign(*this, m);
(gdb) bt
#0  0x00000000000dd6c0 in cv::MatExpr::operator cv::Mat (this=0x3fffffef58) at /work/opencv/modules/core/include/opencv2/core/mat.inl.hpp:3183
#1  0x000000000012510a in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /work/opencv/modules/3d/test/test_normal.cpp:19
#2  0x000000000012d4e6 …
```
=> 3d: fix static init in test

doc/LICENSE_CHANGE_NOTICE.txt, doc/js_tutorials/js_setup/js_setup/js_setup.markdown, doc/py_tutorials/py_gui/py_video_display/py_video_display.markdown, doc/tutorials/core/univ_intrin/univ_intrin.markdown, doc/tutorials/imgproc/out_of_focus_deblur_filter/out_of_focus_deblur_filter.markdown, doc/tutorials/introduction/building_tegra_cuda/building_tegra_cuda.markdown, doc/tutorials/introduction/java_eclipse/java_eclipse.markdown, doc/tutorials/introduction/linux_install/linux_install.markdown, doc/tutorials/introduction/macos_install/macos_install.markdown, doc/tutorials/introduction/transition_guide/transition_guide.markdown, modules/videoio/include/opencv2/videoio.hpp, modules/videoio/include/opencv2/videoio/legacy/constants_c.h
=> Fix some of the broken urls in docs

modules/dnn/src/layers/cpu_kernels/softmax.cpp
Related: https://github.com/opencv/opencv/pull/24466
=> Enable softmax layer vectorization on RISC-V RVV

doc/py_tutorials/py_ml/py_knn/py_knn_understanding/py_knn_understanding.markdown, doc/py_tutorials/py_ml/py_svm/py_svm_basics/py_svm_basics.markdown
=> updated additional resources links

modules/highgui/src/window_QT.cpp
Fixes #13657  and fixes #20215 
I test it on macOS and QT 6.6.0
- [X ] There is a reference to the original bug report and related work
=> fix tab arrow issue

modules/3d/src/usac.hpp, modules/3d/src/usac/essential_solver.cpp, modules/3d/src/usac/quality.cpp, modules/3d/src/usac/ransac_solvers.cpp
Port of solution for:
- https://github.com/opencv/opencv/issues/24482
- https://github.com/opencv/opencv/issues/24281
Original PR: https://github.com/opencv/opencv/pull/24499
=> Port of Replace double atomic in USAC

modules/calib3d/src/calibinit.cpp
=> Fix typos in calibinit.cpp

modules/imgproc/src/cornersubpix.cpp, modules/imgproc/test/test_cornersubpix.cpp
=> Fix out of image corners in cv::cornerSubPix

modules/dnn/test/test_onnx_importer.cpp
- [ X] I agree to contribute to the project under Apache 2 License.
- [ X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ X] The PR is proposed to the proper branch
- [ X] There is a reference to the original bug report and related work
- [ X] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [ X] The feature is well documented and sample code can be built with the project CMake
=> Add yolov5n to tests

modules/dnn/src/graph_simplifier.cpp, modules/dnn/src/graph_simplifier.hpp, modules/dnn/src/onnx/onnx_graph_simplifier.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_graph_simplifier.cpp
resolves https://github.com/opencv/opencv/issues/24568
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1125
TODO:
=> Fix graph fusion with commutative ops

modules/core/include/opencv2/core/matx.hpp
=> Fix comment typo in matx.hpp

modules/calib3d/test/test_chesscorners_timing.cpp
=> Fix time measurement in test Calib3d_ChessboardDetector.timing

cmake/android/android_gradle_projects.cmake, platforms/android/aar-template/build.gradle, platforms/android/aar-template/gradle/wrapper/gradle-wrapper.properties, platforms/android/build-tests/test_gradle_aar.sh, platforms/android/build_java_shared_aar.py, platforms/android/build_static_aar.py, samples/android/15-puzzle/build.gradle.in, samples/android/camera-calibration/build.gradle.in, samples/android/color-blob-detection/build.gradle.in, samples/android/face-detection/build.gradle.in, samples/android/face-detection/jni/CMakeLists.txt, samples/android/image-manipulations/build.gradle.in, samples/android/mobilenet-objdetect/build.gradle.in, samples/android/tutorial-1-camerapreview/build.gradle.in, samples/android/tutorial-2-mixedprocessing/build.gradle.in, samples/android/tutorial-2-mixedprocessing/jni/CMakeLists.txt, samples/android/tutorial-3-cameracontrol/build.gradle.in
Related changes in CI pipelines: https://github.com/opencv/ci-gha-workflow/pull/121
=> Android AAR package build and test with CI

modules/calib3d/src/calibinit.cpp
=> Fix typo in ChessBoardDetector::generateQuads

README.md
Added campaign info to top of README, as well as Additional Resources such as our social profiles, cool stuff submission form, and volunteer form.
=> Update README.md - Add campaign and additional resources

modules/calib3d/include/opencv2/calib3d.hpp
=> doc: typo fix

modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java, modules/java/generator/android/java/org/opencv/android/FpsMeter.java
=> Report resolution together with FPS in JavaCamera2View

README.md
=> OpenCV.AI notification.

modules/dnn/src/onnx/onnx_graph_simplifier.cpp
Resolves https://github.com/opencv/opencv/issues/24609
=> dnn onnx graph simplifier: handle optional inputs of Slice

modules/dnn/src/cuda/eltwise_ops.cu, modules/dnn/src/cuda/functors.hpp, modules/dnn/src/cuda4dnn/kernels/eltwise_ops.hpp, modules/dnn/src/cuda4dnn/primitives/eltwise.hpp, modules/dnn/src/layers/nary_eltwise_layers.cpp
Related https://github.com/opencv/opencv/issues/24606#issuecomment-1837390257
=> dnn cuda: support Sub

modules/java/generator/android/java/org/opencv/android/StaticHelper.java
Fixes https://github.com/opencv/opencv/issues/8100
=> Removed info lib handling in OpenCV initialization on Android

modules/videoio/src/cap_ffmpeg_impl.hpp
=> Added warning, if FFmpeg pipeline was interrupted by timeout

modules/objdetect/src/face_detect.cpp
=> Get code to compile without DNN

modules/dnn/src/onnx/onnx_graph_simplifier.cpp, modules/dnn/src/onnx/onnx_importer.cpp
resolves https://github.com/opencv/opencv/issues/24671
related discussion: https://github.com/opencv/opencv/pull/24655#discussion_r1416744142
TODO:
<details>
<summary>patch</summary>
```patch
--- a/modules/dnn/src/onnx/onnx_graph_simplifier.cpp
+++ b/modules/dnn/src/onnx/onnx_graph_simplifier.cpp
@@ -313,18 +313,30 @@ class AttentionSubGraph : public Subgraph {
att_add = addNodeToMatch("Add", addNodeToMatch(""), att_matmul);
// v_path
-        slice_v = addNodeToMatch("Slice", att_add, addNodeToMatch(""), addNodeToMatch(""));
+        slice_v = addNodeToMatch("Slice", {att_add,
+                                             addNodeToMatch(""),
+                                             addNodeToMatch(""),
+                                             addNodeToMatch(""),
+ …
```
=> Replace Slice optional inputs removal to adjustment

doc/tutorials/introduction/crosscompilation/crosscompile_with_multiarch.markdown
Close https://github.com/opencv/opencv/issues/24695
=> doc: use python3-minimal instead of python3-dev

doc/tutorials/introduction/android_binary_package/android_dev_intro.markdown, doc/tutorials/introduction/android_binary_package/dev_with_OCV_on_Android.markdown
This PR updates Android tutorials parts related to Windows
=> Android Tutorial for Windows Updated

3rdparty/readme.txt
Close https://github.com/opencv/opencv/issues/24705
=> 3rdparty: update libtiff URLs

CMakeLists.txt, modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_obsensor/obsensor_stream_channel_interface.hpp, modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp, modules/videoio/src/cap_obsensor_capture.cpp, samples/cpp/videocapture_obsensor.cpp
=> add support Orbbec Gemini2 and Gemini2 XL camera

modules/imgcodecs/src/grfmt_spng.cpp
=> SPNG integration warning fixes on Windows

doc/tutorials/introduction/android_binary_package/android_dnn_intro.markdown, doc/tutorials/introduction/android_binary_package/android_ocl_intro.markdown, samples/android/tutorial-4-opencl/build.gradle.in, samples/android/tutorial-4-opencl/jni/CLprocessor.cpp, samples/android/tutorial-4-opencl/jni/CMakeLists.txt, samples/android/tutorial-4-opencl/src/org/opencv/samples/tutorial4/MyGLSurfaceView.java, samples/android/tutorial-4-opencl/src/org/opencv/samples/tutorial4/NativePart.java
Update android opencl sample and tutorial
=> Update android opencl sample

cmake/OpenCVGenConfig.cmake
Follow up on https://github.com/opencv/opencv/pull/24723
=> Do not install removed toolchain file for Android.

modules/imgproc/src/contours.cpp
=> Fix typos in imgproc/src/contours.cpp

modules/dnn/test/test_backends.cpp, modules/dnn/test/test_onnx_importer.cpp, modules/dnn/test/test_tf_importer.cpp
Regular builds: http://pullrequest.opencv.org/buildbot/builders/4_x-win32-vc14/builds/100354
```
force_builders=Linux32,Win32
```
=> dnn(test): skip tests on 32-bit Windows

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/version.hpp, modules/python/package/setup.py, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
previous PR with version bump: #23833
=> pre: OpenCV 4.9.0 (version++)

modules/calib3d/include/opencv2/calib3d.hpp
FIxes https://github.com/opencv/opencv/issues/24067
=> Added exception warning to calibrateCamera description.

modules/core/include/opencv2/core/bindings_utils.hpp
Drop test entities from page: https://docs.opencv.org/4.8.0/de/d78/bindings__utils_8hpp.html
=> docs: exclude bindings utils

modules/core/include/opencv2/core/version.hpp
Related https://github.com/opencv/opencv/pull/24766
=> Release 4.9.0.

modules/core/include/opencv2/core/quaternion.inl.hpp
=> Correct invalid error directive

modules/core/src/system.cpp
=> Fix building on OpenBSD X86

modules/objdetect/src/aruco/aruco_detector.cpp
=> Make aruco detector deterministic.

samples/android/15-puzzle/build.gradle.in, samples/android/camera-calibration/build.gradle.in, samples/android/color-blob-detection/build.gradle.in, samples/android/face-detection/build.gradle.in, samples/android/image-manipulations/build.gradle.in, samples/android/mobilenet-objdetect/build.gradle.in, samples/android/qr-detection/build.gradle.in, samples/android/tutorial-1-camerapreview/build.gradle.in, samples/android/tutorial-2-mixedprocessing/build.gradle.in, samples/android/tutorial-3-cameracontrol/build.gradle.in, samples/android/tutorial-4-opencl/build.gradle.in, samples/android/video-recorder/build.gradle.in
=> Fixed typo in Android build scripts.

modules/java/generator/android/java/org/opencv/android/JavaCameraView.java, samples/android/face-detection/gradle/AndroidManifest.xml, samples/android/face-detection/src/org/opencv/samples/facedetect/FaceDetectActivity.java, samples/android/tutorial-1-camerapreview/gradle/AndroidManifest.xml
Added automatic image rotation for JavaCameraView to support any screen orientation.
Added any screen orientation support for tutorial-1-camerapreview and face-detection android samples. 
Fixes: https://github.com/opencv/opencv/issues/9269, https://github.com/opencv/opencv/issues/4963, https://github.com/opencv/opencv/issues/8866, https://github.com/opencv/opencv/issues/5058, https://github.com/opencv/opencv/issues/4704, 
=> Added any screen orientation support for JavaCameraView

README.md
=> Update README.md - remove IndieGoGo, add Support OpenCV page

cmake/android/android_gradle_projects.cmake, doc/tutorials/introduction/android_binary_package/dev_with_OCV_on_Android.markdown, modules/java/CMakeLists.txt, modules/java/android_sdk/android_gradle_lib/build.gradle, modules/java/android_sdk/build.gradle.in, modules/java/generator/gen_java.py, platforms/android/aar-template/OpenCV/build.gradle.template, samples/android/15-puzzle/build.gradle.in, samples/android/camera-calibration/build.gradle.in, samples/android/color-blob-detection/build.gradle.in, samples/android/face-detection/build.gradle.in, samples/android/image-manipulations/build.gradle.in, samples/android/mobilenet-objdetect/build.gradle.in, samples/android/qr-detection/build.gradle.in, samples/android/tutorial-1-camerapreview/build.gradle.in, samples/android/tutorial-2-mixedprocessing/build.gradle.in, samples/android/tutorial-3-cameracontrol/build.gradle.in, samples/android/tutorial-4-opencl/build.gradle.in, samples/android/video-recorder/build.gradle.in
=> Removed Android AIDL from build scrips and tutorials as it's not need since 4.9.0

modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_inner_product.cpp
Preliminary of OpenCL backend revise.
```
```
=> dnn (opencl): integrate bias handling in the inner product opencl kernel

modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java, modules/java/generator/android-24/java/org/opencv/android/NativeCameraView.java, modules/java/generator/android/java/org/opencv/android/CameraBridgeViewBase.java, modules/java/generator/android/java/org/opencv/android/JavaCameraView.java
Added automatic image rotation to JavaCamera2View and NativeCameraView so the video preview was matched with screen orientation.
Fixed double preview initialization bug in JavaCamera2View.
Added proper cameraID parsing to NativeCameraView similar to JavaCameraView
=> Added screen rotation support to JavaCamera2View amd NativeCameraView. Fixed JavaCamera2View initialization.

modules/imgproc/include/opencv2/imgproc.hpp
Because it is a little difficult to tell the difference in the number of channels.
=> Update applyColorMap document

modules/imgcodecs/src/grfmt_jpeg.cpp
libjpeg-turbo has optimized built-in support for encoding/decoding from/to BGR and BGRA [[1]](https://github.com/libjpeg-turbo/libjpeg-turbo/commit/f25c071eb745268452206bb633561b770c4d62ea).
This PR integrates this optimized support when available. As a result both encoding and decoding from/to BGR are faster by ~2% and the same for BGRA is faster by ~3%, measured on a Mac M1 (ARM64) with a 512x512 image. Grayscale performance is unchanged.
```
TEST(Imgcodecs_Jpeg, encode_benchmark)
{
cvtest::TS& ts = *cvtest::TS::ptr();
string input = string(ts.get_data_path()) + "../cv/shared/lena.png";
cv::Mat img = cv::imread(input);
ASSERT_FALSE(img.empty());
// uncomment to test BGRA branch
// cv::cvtColor(img, img, cv::COLOR_BGR2BGRA);
int bestTimeUs = -1;
for (int i = 0; i < 1000; ++i) { …
```
=> jpeg: use libjpeg-turbo built-in color conversions

modules/core/include/opencv2/core/base.hpp
Resolved issue no https://github.com/opencv/opencv/issues/22177
=> Resolved issue number #22177

modules/core/include/opencv2/core/hal/intrin_lsx.hpp, modules/dnn/src/layers/cpu_kernels/fast_gemm_kernels.simd.hpp
See https://github.com/fengyuentau/opencv/actions/runs/7665377694/job/20891162958#step:14:16
Warnings needs to be handled before we add the loongson server to our CI.
=> Handle warnings in loongson-related code

platforms/android/build_static_aar.py
Needed for https://github.com/opencv/ci-gha-workflow/pull/135
=> Fix AAR build with static OpenCV libraries for Android.

doc/tutorials/dnn/dnn_yolo/dnn_yolo.markdown, samples/dnn/yolo_detector.cpp
This PR introduces documentation for the usage of yolo detection model family in open CV. This is not to be merge before #24691, as the sample will need to be changed. 
=> Documentation for Yolo usage in Opencv

.github/workflows/PR-4.x.yaml
Related PR in CI: https://github.com/opencv/ci-gha-workflow/pull/138
=> Added job to test with real hardware

platforms/android/build-tests/test_gradle.sh, platforms/android/build-tests/test_gradle_aar.sh, platforms/android/build_aar.sh, platforms/android/build_java_shared_aar.py, platforms/android/build_static_aar.py
=> Added offline option for Android builds

modules/dnn/src/layers/nary_eltwise_layers.cpp
Resolves https://github.com/opencv/opencv/issues/24954
```
```
=> dnn (opencl): fix incorrect steps and elemsize when dtype changes

.github/workflows/PR-4.x.yaml, cmake/android/android_gradle_projects.cmake, modules/java/android_sdk/CMakeLists.txt
Merge with https://github.com/opencv/ci-gha-workflow/pull/144
=> Allow multiple flags with OPENCV_GRADLE_VERBOSE_OPTIONS

modules/gapi/src/backends/ov/govbackend.cpp, modules/gapi/test/infer/gapi_infer_ov_tests.cpp
=> Fixed support of mean/scale preprocessing in OV backend for non-real types

doc/tutorials/3d/point_cloud/point_cloud.markdown, modules/3d/include/opencv2/3d.hpp, modules/3d/src/pointcloud/io_ply.cpp, modules/3d/src/pointcloud/io_ply.hpp, modules/3d/src/pointcloud/load_point_cloud.cpp, modules/3d/test/test_pointcloud.cpp, samples/python/point_cloud.py
**Warning:** The PR changes exising API.
Fixes #24960
Connected PR: [#1145@extra](https://github.com/opencv/opencv_extra/pull/1145)
* Adds faces loading from and saving to PLY files
* Fixes incorrect PLY loading (see issue)
* Adds per-vertex color loading / saving
=> PLY mesh support

modules/python/src2/typing_stubs_generation/predefined_types.py
=> Fix typo in size

3rdparty/tbb/CMakeLists.txt
=> Suppress TBB compilation warnings visible during Android SDK build

modules/objdetect/include/opencv2/objdetect/aruco_detector.hpp
=> Typo fix in Aruco documentation

modules/objdetect/src/aruco/aruco_detector.cpp, modules/objdetect/src/aruco/aruco_utils.cpp, modules/objdetect/src/aruco/aruco_utils.hpp
Minor fix, two unnecessary Mat copies have been deleted.
=> fix unnecessary copying in ArucoDetector

apps/python-calibration-generator/calibration_generator.py, apps/python-calibration-generator/utils.py
=> Multiview calibration generator improvements

cmake/android/android_gradle_projects.cmake, modules/java/test/android_test/CMakeLists.txt, modules/java/test/android_test/build.gradle.in, modules/java/test/android_test/src/org/opencv/test/android/KotlinTest.kt, modules/java/test/android_test/tests_module/build.gradle.in, platforms/android/ndk-25.config.py
Added Kotlin test, changed Kotlin version for OpenCV
=> Added Kotlin test, changed Kotlin version for OpenCV

3rdparty/libjasper/jas_stream.c, 3rdparty/libjasper/jpc_bs.h, modules/videoio/src/cap_android_camera.cpp
=> Fixed typo.

modules/calib/include/opencv2/calib.hpp, modules/calib/src/calibration.cpp, modules/calib/test/test_cameracalibration.cpp, modules/calib/test/test_fisheye.cpp
=> RegisterCameras function for heterogenious cameras pair

modules/dnn/src/layers/einsum_layer.cpp
Fixes https://github.com/opencv/opencv/issues/25077
=> Fix issue #25077

samples/dnn/models.yml
Below is evidence of the test:
=> Added and tested yolov8x model

samples/python/multiview_calibration.py
=> Ground truth check and Charuco support in multiview_calibration.py

3rdparty/tbb/CMakeLists.txt, cmake/checks/cpu_fp16.cpp, modules/3d/src/calibration_base.cpp, modules/3d/test/test_decompose_projection.cpp, modules/dnn/src/layers/attention_layer.cpp, modules/dnn/src/layers/einsum_layer.cpp, modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/perf/perf_warp.cpp, modules/imgproc/src/imgwarp.cpp, modules/imgproc/src/opencl/remap.cl, modules/imgproc/test/ocl/test_warp.cpp, modules/imgproc/test/test_imgwarp.cpp, modules/objdetect/src/face_detect.cpp, samples/dnn/models.yml
No changes in contrib and extra
#24621 from chacha21:remap_relative
#25050 from akretz:fix_issue_24330
#25069 from asmorkalov:as/disable_win_arm64_fp16
#25076 from fengyuentau:improve_attention
#25091 from Dhanwanth1803:scoreThresh
#25095 from cabelo:yolov8x
#25100 from LaurentBerger:I25077
#25111 from asmorkalov:as/tbb_license_fix
Previous "Merge 4.x": #25105
=> 5.x merge 4.x

modules/dnn/src/net.cpp
=> Update net_impl.cpp and net.cpp to fix the first part of #25112

README.md
=> A small rectification space mistake in README.md

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/calib3d_c_api.h
=> calib3d: doc: remove C API link (For 4.x)

modules/highgui/src/window.cpp, modules/highgui/src/window_QT.cpp, modules/highgui/src/window_gtk.cpp, modules/highgui/src/window_w32.cpp, modules/highgui/src/window_wayland.cpp
Relates to https://github.com/opencv/opencv/pull/22754
Continues # https://github.com/opencv/opencv/pull/25149
=> Backport some highgui changes from #22754

modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp, modules/core/test/test_intrin_utils.hpp
=> Updated RVV intrinsics and test to remove initializer_list

modules/dnn/src/layers/cumsum_layer.cpp
Added int support to CumSum layer
=> Added int support to CumSum layer

samples/dnn/models.yml
Below is evidence of the test:
=> Added and tested yolov8s and yolov8n model

modules/videoio/src/cap_v4l.cpp
Pretty much as the title; needed it to use a crappy webcam with OpenCV
=> Added support for V4L2_PIX_FMT_SGRBG8 pixel format to V4L2 backend

modules/imgcodecs/src/exif.cpp, modules/imgcodecs/src/exif.hpp, modules/imgcodecs/src/grfmt_pfm.cpp
=> Fix 6 typos

modules/video/src/tracking/tracker_vit.cpp
Fix a bug about vittrack post-process.
=> fix a bug about vittrack post-process

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_png.cpp, modules/python/test/test_imread.py, modules/python/test/test_pathlike.py
Hello everyone,
I created this new version of the imread function and I think it can be very useful in several cases.
It is actually passed to it object on which you want to upload the image.
The advantages can be different like in case one needs to open several large images all the same in sequence.
one can use the same pointer and the system would not allocate memory each time
=> add imread

modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
resolves https://github.com/opencv/opencv/issues/25272, https://github.com/opencv/opencv/issues/24965
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1160
=> TFLite new layers

modules/core/src/dxt.cpp
=> Fixed HAL invocation for DCT.

3rdparty/orbbecsdk/orbbecsdk.cmake
Resolves https://github.com/opencv/opencv/issues/25298
fix download file hash value mismatch issue
=> fix download file hash value mismatch issue

modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
resolves https://github.com/opencv/opencv/issues/25310
=> Ownership check in TFLite importer

modules/dnn/test/test_layers_1d.cpp
This PR introduces `0D` test for `expand` layer 
=> Expand 0D layer test

doc/doxygen-awesome.css
resolves https://github.com/opencv/opencv/issues/24573
preview: https://pullrequest.opencv.org/buildbot/export/pr/25339/docs/d2/de8/group__core__array.html#gad12cefbcb5291cf958a85b4b67b6149f
=> Update doc CSS to fit MathJAX formula in table

doc/tutorials/introduction/env_reference/env_reference.markdown
=> typo in env_reference.markdown

modules/core/include/opencv2/core.hpp
=> core: doc: add note for countNonZero, hasNonZero and findNonZero

modules/core/src/hal_replacement.hpp, modules/core/src/matrix_transform.cpp
Fixes https://github.com/opencv/opencv/issues/25338
=> HAL interface for transpose2d.

modules/dnn/test/test_layers_1d.cpp
This PR introduces test for `Slice` layer to test its functionality for 1D arrays
=> Slice Layer 1D test

doc/js_tutorials/js_gui/js_image_display/js_image_display.markdown
=> Fixing code example on js image display documentation

.github/workflows/PR-4.x.yaml
Related PR to CI pipelines: https://github.com/opencv/ci-gha-workflow/pull/155
=> Added experimental build for Windows ARM64 to CI.

modules/core/misc/objc/common/Mat.h, modules/core/misc/objc/common/Mat.mm, modules/imgcodecs/src/ios_conversions.mm, modules/videoio/src/cap_avfoundation.mm
=> fix build of dynamic framework for visionos

modules/imgproc/src/bilateral_filter.dispatch.cpp, modules/imgproc/src/hal_replacement.hpp
Fixes: https://github.com/opencv/opencv/issues/25344
=> HAL interface for bilaterialFilter

modules/photo/src/inpaint.cpp, modules/photo/test/test_inpaint.cpp
=> Correct inpainting floating point values with Telea's algorithm

samples/cpp/drawing.cpp
#25006 
The updated samples allows user to draw randome shapes by using hot keys
=> Improving the drawing cpp sample to draw shapes based on user input

modules/photo/src/inpaint.cpp, modules/photo/test/test_inpaint.cpp
=> Handle top and left border masked pixels correctly in inpaint method

modules/dnn/test/test_onnx_conformance_layer_filter_opencv_all_denylist.inl.hpp
Comment out all passing tests in `test_onnx_conformance_layer_filter_opencv_all_denylist.inl.hpp` file. 
=> Conformance test denylist reduce

samples/opengl/opengl_testdata_generator.cpp
=> Fix build for Windows: bad var names in testdata generator

platforms/js/opencv_js.config.py
=> Added FaceDetectorYN to OpenCV JS API

cmake/OpenCVFindIPP.cmake
=> fix for IPP 2021.10 with OneAPI 2024

modules/highgui/include/opencv2/highgui.hpp, modules/highgui/src/backend.hpp, modules/highgui/src/window.cpp, modules/highgui/src/window_gtk.cpp, modules/highgui/src/window_w32.cpp, modules/highgui/test/test_gui.cpp
issue https://github.com/opencv/opencv/issues/25329
=> Add cv::currentUIFramework

modules/gapi/test/infer/gapi_infer_ie_test.cpp
similar workaround as https://github.com/opencv/opencv/pull/25294
resolves https://github.com/opencv/opencv/issues/25320
=> Skip InferList.TestStreamingInfer

.github/workflows/PR-5.x.yaml, modules/3d/src/rgbd/color_tsdf_functions.cpp, modules/3d/src/rgbd/tsdf_functions.cpp
=> CI pipeline with Windows 10 ARM64 for 5.x

modules/imgcodecs/src/grfmt_jpeg.cpp
=> imgcodecs: jpeg: refactoring for JpegEncoder

modules/imgproc/include/opencv2/imgproc/detail/legacy.hpp, modules/imgproc/src/emd.cpp, modules/imgproc/src/emd_new.cpp, modules/imgproc/src/precomp.hpp, modules/imgproc/test/test_emd.cpp, modules/imgproc/test/test_precomp.hpp
- added more tests for EMD
- refactored to remove CvArr
- used BufferArea for memory allocations
- renamed functions and variables and formatted the code
- kept legacy functions intact in separate header
=> imgproc: refactor EMD to reduce C-API usage

modules/imgproc/src/hal_replacement.hpp, modules/imgproc/src/moments.cpp
Address: https://github.com/opencv/opencv/issues/25489
=> Added moments interface to HAL.

modules/core/perf/perf_math.cpp
=> Perf tests for SVD and solve() created

modules/core/src/hal_replacement.hpp, modules/core/src/norm.cpp
=> HAL for Hamming norm added

modules/highgui/src/window_wayland.cpp
=> highgui: wayland: reduce cpu usage for cv::waitKey()

modules/imgproc/src/moments.cpp
Introduced in https://github.com/opencv/opencv/pull/25490
=> Fix moments integration to OpenCV HAL

modules/dnn/src/layers/cumsum_layer.cpp, modules/dnn/src/layers/expand_layer.cpp, modules/dnn/src/layers/gather_elements_layer.cpp, modules/dnn/src/layers/gather_layer.cpp, modules/dnn/src/layers/scatterND_layer.cpp, modules/dnn/src/layers/scatter_layer.cpp, modules/dnn/src/layers/tile_layer.cpp
=> Added more OpenVINO layers to dnn

modules/core/src/hal_replacement.hpp, modules/core/src/mean.dispatch.cpp
Closes https://github.com/opencv/opencv/issues/25477
=> HAL API for meanStdDev

modules/dnn/misc/face_detector_accuracy.py, modules/dnn/misc/python/test/test_dnn.py, modules/dnn/misc/quantize_face_detector.py, modules/dnn/perf/perf_net.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_misc.cpp, samples/dnn/js_face_recognition.html, samples/dnn/models.yml
Part of https://github.com/opencv/opencv/issues/25314
This PR aims to change the tests related to opencv_face_detector from caffe framework to onnx. Tests in `test_int8_layer.cpp` and `test_caffe_importer.cpp` will be removed in https://github.com/opencv/opencv/pull/25323
```
```
=> Change opencv_face_detector related tests and samples from caffe to onnx 

modules/imgproc/src/emd_new.cpp
Consequence of #25469
`BufferArea` can be used to store objects with sizes which are power of two, because it uses [alignPtr](https://docs.opencv.org/4.x/db/de0/group__core__utils.html#ga7d7b007312be535012cdbd6f45037399) function internally. `Node2D` structure has size of 30 bytes on 32-bit platforms, thus can not be stored in the area. Thus we've moved `data_x` array to a separate `AutoBuffer`.
=> imgproc: fix allocation issue in EMD

modules/dnn/include/opencv2/dnn/dnn.hpp
=> remove dnn::layer::allocate in doc

.github/workflows/PR-4.x.yaml
=> Added Ubuntu 24.04 to regular CI.

modules/dnn/test/test_layers.cpp
Suppress https://github.com/opencv/opencv/issues/23930 in CI for now
=> Skip Test_Caffe_layers.Concat with Vulkan due to sporadic failures

modules/calib3d/src/calibration.cpp, modules/calib3d/src/hal_replacement.hpp
=> HAL for projectPoints() added

3rdparty/openjpeg/openjp2/bio.c, 3rdparty/openjpeg/openjp2/bio.h, 3rdparty/openjpeg/openjp2/dwt.c, 3rdparty/openjpeg/openjp2/ht_dec.c, 3rdparty/openjpeg/openjp2/j2k.c, 3rdparty/openjpeg/openjp2/j2k.h, 3rdparty/openjpeg/openjp2/jp2.c, 3rdparty/openjpeg/openjp2/libopenjp2.pc.cmake.in, 3rdparty/openjpeg/openjp2/openjpeg.c, 3rdparty/openjpeg/openjp2/openjpeg.h, 3rdparty/openjpeg/openjp2/opj_config.h.cmake.in, 3rdparty/openjpeg/openjp2/opj_config_private.h.cmake.in, 3rdparty/openjpeg/openjp2/opj_includes.h, 3rdparty/openjpeg/openjp2/opj_intmath.h, 3rdparty/openjpeg/openjp2/pi.c, 3rdparty/openjpeg/openjp2/t1.c, 3rdparty/openjpeg/openjp2/t1_ht_generate_luts.c, 3rdparty/openjpeg/openjp2/t2.c, 3rdparty/openjpeg/openjp2/tcd.c, 3rdparty/openjpeg/openjp2/tcd.h, 3rdparty/openjpeg/openjp2/tgt.c, 3rdparty/openjpeg/openjp2/thread.c
Closes https://github.com/opencv/opencv/issues/22284
=> OpenJPEG update to 2.5.2.

modules/core/src/arithm.cpp, modules/dnn/src/layers/einsum_layer.cpp, modules/dnn/test/test_layers_1d.cpp
=> Add support for scalar and matrix multiplication in einsum

modules/core/include/opencv2/core.hpp
Related issue: https://github.com/opencv/opencv/issues/25621
=> Replace non-ascii character in comment

modules/core/src/lut.cpp
=> Fixed width and height order in HAL call for LUT

modules/core/perf/opencl/perf_arithm.cpp, modules/core/perf/perf_arithm.cpp, modules/core/test/test_arithm.cpp
=> Tests for cv::rotate() added

modules/core/include/opencv2/core/cuda/detail/reduce.hpp, modules/core/include/opencv2/core/cuda/detail/reduce_key_val.hpp, modules/core/include/opencv2/core/cuda/reduce.hpp
Tries to fix https://github.com/opencv/opencv_contrib/issues/3690 for CUDA 12.4+
Related PR to Contrib: https://github.com/opencv/opencv_contrib/pull/3744 
=> Added branch with variadic version of Trust tuple

modules/gapi/include/opencv2/gapi/infer/onnx.hpp, modules/gapi/src/backends/onnx/gonnxbackend.cpp
=> Port G-API ONNXRT backend into V2 API

modules/core/test/test_mat.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/src/torch/torch_importer.cpp, modules/gapi/src/compiler/passes/exec.cpp, modules/gapi/src/streaming/onevpl/file_data_provider.hpp, modules/ts/include/opencv2/ts/ts_gtest.h
=> Suppress build warnings for GCC14

modules/core/include/opencv2/core/version.hpp
Related: https://github.com/opencv/opencv/pull/25615
=> Release 4.10.0

modules/objdetect/include/opencv2/objdetect/face.hpp
=> Update cv::FaceRecognizerSF class documentation

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/misc/python/pyopencv_dnn.hpp, modules/dnn/misc/python/test/test_dnn.py, modules/python/src2/typing_stubs_generation/predefined_types.py
related: https://github.com/opencv/opencv/issues/25707
=> Wrap dnn addLayer

platforms/android/build_sdk.py
=> Android SDK build script: HWAsan support added

doc/js_tutorials/js_setup/js_setup/js_setup.markdown, modules/js/test/init_cv.js, modules/js/test/test_calib3d.js, modules/js/test/test_core.js, modules/js/test/test_features2d.js, modules/js/test/test_imgproc.js, modules/js/test/test_mat.js, modules/js/test/test_objdetect.js, modules/js/test/test_photo.js, modules/js/test/test_utils.js, modules/js/test/test_video.js, modules/js/test/tests.js, platforms/js/build_js.py
* Firefox tests passed
```
```
=> Fix OpenCV.js tests

doc/pattern_tools/svgfig.py
Update source: https://github.com/jpivarski/svgfig/blob/master/svgfig-1.x/svgfig.py
Fixes https://github.com/opencv/opencv/issues/25769
Fixes https://github.com/opencv/opencv/issues/19795
=> Svgfig library update to version 1.0.1 as it uses BSD-3 license.

modules/video/include/opencv2/video/tracking.hpp, modules/video/src/tracking/tracker_vit.cpp, modules/video/test/test_trackers.cpp, samples/dnn/vit_tracker.cpp
Fixes https://github.com/opencv/opencv/issues/25760
=> video: fix vittrack in the case where crop size grows until out-of-memory when the input is black

modules/core/src/lut.cpp, modules/core/test/test_arithm.cpp
=> Added LUT for FP16 and accuracy test

modules/gapi/include/opencv2/gapi/infer/bindings_onnx.hpp, modules/gapi/include/opencv2/gapi/infer/onnx.hpp, modules/gapi/src/backends/onnx/bindings_onnx.cpp, modules/gapi/src/backends/onnx/gonnxbackend.cpp
=> Extending G-API onnx::Params to pass arbitrary session options

modules/core/src/mean.dispatch.cpp
as it's done for other branches.
=> Fill mean and stdDev tails with zeros for HAL branch in meanStdDev

samples/dnn/download_models.py
=> Drop redundant dependency from download_models.py

modules/core/src/lut.cpp, modules/core/test/test_arithm.cpp
5.x extension for  https://github.com/opencv/opencv/pull/25787
=> Added lut support for all new types in 5.x

3rdparty/clapack/CMakeLists.txt, modules/3d/perf/perf_tsdf.cpp, modules/3d/test/test_tsdf.cpp
Related CI patch: https://github.com/opencv/ci-gha-workflow/pull/175
=> Warnings fix for Ubuntu 24.04.

3rdparty/carotene/hal/tegra_hal.hpp
=> Use Carotene implementation of TEGRA_GaussianBlurBinomial 3x3 and 5x5 on ARM

modules/calib3d/include/opencv2/calib3d.hpp
=> calib3d: doc: enable line breaks in formulas

modules/imgcodecs/include/opencv2/imgcodecs.hpp
=> Update documentation cv::haveImageReader(), cv::haveImageWriter()

modules/dnn/src/cuda/eltwise_ops.cu, modules/dnn/src/cuda/functors.hpp, modules/dnn/src/cuda/math.hpp, modules/dnn/src/cuda4dnn/kernels/eltwise_ops.hpp, modules/dnn/src/cuda4dnn/primitives/eltwise.hpp, modules/dnn/src/layers/nary_eltwise_layers.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_conformance.cpp, modules/dnn/test/test_onnx_conformance_layer_filter__cuda_denylist.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_filter__cuda_fp16_denylist.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_filter__vulkan_denylist.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_filter_opencv_ocl_fp16_denylist.inl.hpp
Sync changes from https://github.com/opencv/opencv/pull/25630 to 5.x.
=> dnn: merge #25630 to 5.x

CMakeLists.txt, doc/tutorials/introduction/config_reference/config_reference.markdown, modules/core/include/opencv2/core.hpp, modules/core/include/opencv2/core/utility.hpp, modules/core/src/system.cpp, modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/smooth.dispatch.cpp, modules/imgproc/test/test_smooth_bitexact.cpp
Address post merge notes in https://github.com/opencv/opencv/pull/25792
=> Post-merge fixes for algorithm hint API

modules/calib3d/src/chessboard.cpp
Replacement for https://github.com/opencv/opencv/pull/25908
=> Use CV_LOG_DEBUG for debug logging in chessboard detector.

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/java/generator/src/cpp/listconverters.cpp, modules/java/generator/src/cpp/listconverters.hpp, samples/dnn/gpt2_inference.py
This PR adds sample for inferencing GPT-2 model. More specificly implementation of GPT-2 from [this repository](https://github.com/karpathy/build-nanogpt). Currently inference in OpenCV is only possible to do with fixed window size due to not supported dynamic shapes. 
=> Add sample for GPT2 inference

modules/dnn/CMakeLists.txt, modules/imgcodecs/src/rgbe.cpp
Align code and remove redundant CMake code
=> code clean

modules/core/src/minmax.simd.hpp
=> Fix "'/*' within block comment " warning

modules/core/src/hal_replacement.hpp, modules/core/src/matmul.dispatch.cpp
=> HAL for dot product added

modules/ts/src/ts.cpp
There more than one HAL implementation for ARM. It'll be useful to report it in tests.
=> Report used HAL to test log and xml

modules/core/src/persistence_xml.cpp, modules/core/test/test_io.cpp
=> core: FileStorage: detect invalid attribute value

modules/core/include/opencv2/core/mat.inl.hpp, modules/core/include/opencv2/core/types.hpp, modules/core/test/test_mat.cpp
=> Fix size() for 0d matrix

modules/core/test/test_utils.cpp, modules/python/test/test_misc.py
=> replace lena.jpg in find-existing-file tests

modules/dnn/src/layers/elementwise_layers.cpp
Fixes [issue 26000](https://github.com/opencv/opencv/issues/26000).
=> got rid of std prefix

samples/python/tracker.py
This PR removed unused arguments and updated existing argument placeholders to be more descriptive of what they are.
=> Improved samples/python/tracker.py docstring  

doc/tutorials/imgproc/basic_geometric_drawing/basic_geometric_drawing.markdown
=> doc: remove duplicated OpenCV Theory at ToC in Basic Drawing

platforms/android/aar-template/README.md
=> correct "enviroment" to "environment"

modules/imgproc/include/opencv2/imgproc.hpp
=> Fix typo in MorphShapes document

modules/dnn/src/cuda4dnn/csl/cublas.hpp, modules/dnn/test/test_onnx_importer.cpp
Merge with https://github.com/opencv/opencv_extra/pull/1202
Fixes https://github.com/opencv/opencv/issues/26021
=> dnn: fix matmul crash

samples/dnn/ldm_inpainting.py
This PR adds inpaiting sample that is based on [High-Resolution Image Synthesis with Latent Diffusion Models](https://arxiv.org/pdf/2112.10752) paper (reference github [repository](https://github.com/CompVis/latent-diffusion)). 
Steps to run the model: 
1. Firstly needs ONNX graph of the Latent Diffusion Model. You can get it in two different ways. 
> a. Generate the using this [repo](https://github.com/Abdurrahheem/latent-diffusion/tree/ash/export2onnx) and follow instructions below
```bash
git clone https://github.com/Abdurrahheem/latent-diffusion.git
cd latent-diffusion
conda env create -f environment.yaml
conda activate ldm
wget -O models/ldm/inpainting_big/last.ckpt https://heibox.uni-heidelberg.de/f/4d9ac7ea40c64582b7c9/?dl=1
python -m scripts.inpaint.py --indir …
```
=> Diffusion Inpainting Sample

doc/tutorials/imgproc/imgtrans/remap/remap.markdown
- Make x a math symbol
- Fix a typo
=> Update remap tutorial

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/gatherND.cpp, modules/dnn/src/onnx/onnx_importer.cpp, modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
This PR adds support for GatherND layer. The layer was in comformance deny list initially. 
=> Support for GatherND layer

modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
Fixes https://github.com/opencv/opencv/issues/26131
OpenCV Extra: https://github.com/opencv/opencv_extra/pull/1208
=> Leaky RELU support for TFLite.

samples/python/tracker.py
=> sample: tracker parameters updated

3rdparty/carotene/hal/tegra_hal.hpp, 3rdparty/carotene/include/carotene/functions.hpp, 3rdparty/carotene/src/opticalflow.cpp, modules/video/src/hal_replacement.hpp, modules/video/src/lkpyramid.cpp
=> Added HAL interface for Lukas-Kanade optical flow

3rdparty/carotene/hal/tegra_hal.hpp, modules/video/src/hal_replacement.hpp, modules/video/src/lkpyramid.cpp
=> HAL interface for Sharr derivatives needed for Lukas-Kanade algorithm

doc/js_tutorials/js_core/js_image_arithmetics/js_image_arithmetics.markdown
=> Fixed minor typos in JS tutorials

samples/cpp/multiview_calibration_sample.cpp
=> Add Charuco board support to multiview calibration sample (C++)

modules/3d/misc/js/gen_dict.json, modules/calib/misc/js/gen_dict.json
The merge issue was introduced in https://github.com/opencv/opencv/pull/26073 and relates to https://github.com/opencv/opencv/pull/25986
```
Xbuild_image:Docs=docs-js
build_image:Docs=docs-js:22.04-3.1.64
#build_image:Custom=javascript:3.1.64
buildworker:Docs=linux-4
```
=> Java Script config fix after 4.x merge.

modules/3d/src/rgbd/hash_tsdf_functions.cpp, modules/gapi/src/backends/fluid/gfluidimgproc_simd_avx2.hpp, modules/imgproc/src/resize.cpp
=> build: fix AVX2/AVX512 builds failed due to intrinsics operator usage (5.x)

modules/calib/test/test_multiview_calib.cpp
Related test data: https://github.com/opencv/opencv_extra/pull/1211
=> Multi-camera calibration tests with real cameras.

modules/calib/test/test_multiview_calib.cpp
The PR adds test for pinhole+fisheye case with real camera setup.
Test data: https://github.com/opencv/opencv_extra/pull/1212
Relates to:
- https://github.com/opencv/opencv/pull/25061
- https://github.com/opencv/opencv/pull/24052
=> RegisterCameras test for heterogenious pinhone + fisheye setup.

modules/features2d/src/mser.cpp
=> C-API cleanup: use AutoBuffer in MSER (4.x)

modules/photo/src/inpaint.cpp
=> C-API cleanup: inpaint algorithms in photo (4.x)

modules/calib/include/opencv2/calib.hpp, modules/calib/src/multiview_calibration.cpp, modules/calib/test/test_multiview_calib.cpp
Partially based on https://github.com/opencv/opencv/pull/24052
Credits: Linfei Pan
=> Heterogenious cameras support in multiview calibration.

modules/calib3d/src/sqpnp.cpp
Extra checks for corner cases in 3x3 matrix inversion
=> inversion checks

modules/3d/src/rgbd/hash_tsdf_functions.cpp
=> Fix hash_tsdf_functions.cpp compilation on some platforms.

modules/imgproc/src/opencl/warp_affine.cl
Relates https://github.com/opencv/opencv/pull/26242
```
```
=> imgproc: update warpAffine opencl kernel to be in sync with cpu one

modules/gapi/include/opencv2/gapi/infer/bindings_onnx.hpp, modules/gapi/include/opencv2/gapi/infer/onnx.hpp, modules/gapi/src/backends/onnx/bindings_onnx.cpp, modules/gapi/src/backends/onnx/gonnxbackend.cpp
=> G-API: Introduce level optimization flag for ONNXRT backend

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/grfmt_tiff.cpp, modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_avif.cpp, modules/imgcodecs/test/test_exr.impl.hpp, modules/imgcodecs/test/test_read_write.cpp
=> imgcodecs: implement imencodemulti()

modules/js/perf/package.json
=> fix: performance typo

modules/core/src/opengl.cpp
Issue: #26273
Supersedes: #26274
=> Rewrote OpenCL-OpenGL-interop device discovery routine without extensions and with Apple support

doc/tutorial-utils.js, doc/tutorials/imgproc/pyramids/pyramids.markdown
=> doc: fix the position of toggle button

modules/gapi/cmake/DownloadADE.cmake
=> ADE update to 0.1.2e

modules/dnn/src/ie_ngraph.cpp
=> OpenVINO friendly output names from non-compiled Model

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/net_impl.cpp
=> Added exception when calling forward to specified layer with the new dnn engine

cmake/OpenCVModule.cmake, modules/core/src/utils/datafile.cpp, modules/highgui/src/window_winrt.cpp, modules/highgui/src/window_winrt_bridge.cpp, modules/highgui/src/window_winrt_bridge.hpp, modules/objdetect/src/face_detect.cpp, modules/objdetect/src/face_recognize.cpp
For https://github.com/opencv/ci-gha-workflow/pull/188
**Note**: removed POST_BUILD custom commands, because they do not work with modern VS
**Note**: config parameters ` -DCMAKE_SYSTEM_NAME=WindowsStore  -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_VS_EFFECTIVE_PLATFORMS=x64 -DBUILD_opencv_gapi=OFF -DWITH_MSMF=OFF  -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF` - disabled broken features
=> WinRT/UWP build: fix some specific warnings

3rdparty/hal_rvv/hal_rvv_1p0/merge.hpp
=> Add the missing license header in hal_rvv.

modules/core/include/opencv2/core.hpp, modules/objdetect/include/opencv2/objdetect.hpp
Close https://github.com/opencv/opencv/issues/26372
=> doc: fix doxygen errors at Algorithm and QRCodeEncoder

modules/dnn/src/ie_ngraph.cpp
=> Hotfix ie_ngraph.cpp in Debug

modules/imgproc/test/test_drawing.cpp
=> Fix test typo.

.github/workflows/PR-4.x.yaml
Uses https://github.com/opencv/ci-gha-workflow/pull/188
=> Added Universal Windows Package build to CI.

modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp, modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/perf/perf_warp.cpp, modules/imgproc/src/imgwarp.cpp, modules/imgproc/src/opencl/remap.cl, modules/imgproc/src/warp_common.scalar.hpp, modules/imgproc/src/warp_common.vector.hpp, modules/imgproc/src/warp_kernels.simd.hpp, modules/imgproc/test/test_imgwarp_strict.cpp, modules/stitching/test/ocl/test_warpers.cpp
M2:
```
Name of Test                                        base  patch   patch   
vs    
base   
(x-factor)
WarpAffine::TestWarpAffine::(640x480, INTER_LINEAR, BORDER_CONSTANT, 8UC4)                0.213 0.185    1.15   
WarpAffine::TestWarpAffine::(640x480, INTER_LINEAR, BORDER_REPLICATE, 8UC4)               0.213 0.187    1.14   
WarpAffine::TestWarpAffine::(1280x720, INTER_LINEAR, BORDER_CONSTANT, 8UC4)               0.417 0.355    1.18   
WarpAffine::TestWarpAffine::(1280x720, INTER_LINEAR, BORDER_REPLICATE, 8UC4)              0.973 0.908    1.07   
WarpAffine::TestWarpAffine::(1920x1080, INTER_LINEAR, BORDER_CONSTANT, 8UC4)              0.563 0.507    1.11   
WarpAffine::TestWarpAffine::(1920x1080, INTER_LINEAR, BORDER_REPLICATE, 8UC4)             3.208 3.165 …
```
=> imgproc: add new remap kernels that align with the new warpAffine and warpPerspective kernels

modules/core/src/persistence_types.cpp, modules/core/test/test_io.cpp
=> Fix empty mat debug assertion

.github/workflows/PR-5.x.yaml
=> Windows UWP build in CI for 5.x

modules/core/src/opencl/runtime/opencl_core.cpp
Fixes compilation under Android with one-line fix
=> Build fix for opencl_core.cpp

modules/core/src/arithm.cpp, modules/core/src/hal_replacement.hpp
=> HAL added for add(array, scalar)

modules/core/src/matmul.dispatch.cpp, modules/core/src/matrix_expressions.cpp
Partial backport of https://github.com/opencv/opencv/pull/26458
=> Backport some of C API removal in core module implementation.

modules/calib/src/calibration.cpp
These were discovered when porting 4.x to C++
=> Fix minor bugs in calibration.

samples/dnn/edge_detection.cpp, samples/dnn/segmentation.cpp, samples/dnn/segmentation.py
=> Added cap.isOpened() check to edge detection and segmentation sample

samples/dnn/text_detection.cpp, samples/dnn/text_detection.py
=> Fixed sha1 issues with East model in Text Detection Sample

3rdparty/ffmpeg/ffmpeg.cmake, modules/videoio/src/backend_plugin.cpp, modules/videoio/src/cap_ffmpeg.cpp, modules/videoio/test/test_ffmpeg.cpp
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/89
- FFmpeg n7.1
- OpenH264 2.5.0
- libvpx 1.15.0
- aom 3.11.0
resolves #26465
<cut/>
<details><summary>FFmpeg config:</summary>
```
+ PKG_CONFIG_PATH=/build/openh264/install_x86_64/lib/pkgconfig:/build/libvpx_x64/install/lib/pkgconfig:/build/aom_x64/install/lib/pkgconfig
+ ./configure --enable-cross-compile --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --enable-static --enable-w32threads --enable-libopenh264 --enable-libvpx --disable-filters --disable-bsfs --disable-programs --disable-debug --disable-cuda --disable-cuvid --disable-nvenc --enable-libaom --prefix=/build/ffmpeg_x86_64/install
install prefix            /build/ffmpeg_x86_64/install
source path               . …
```
=> ffmpeg/5.x: update FFmpeg wrapper 2024.11

modules/dnn/test/test_layers.cpp
Address https://github.com/opencv/opencv/pull/26391#discussion_r1852255440
=> Fixed test LSTM warning.

modules/imgcodecs/include/opencv2/imgcodecs.hpp
Closed https://github.com/opencv/opencv/issues/26509
=> doc: fix to supported depth for TIFF

modules/gapi/test/gapi_sample_pipelines.cpp
Address https://github.com/opencv/opencv/issues/26526
=> Fixed missing include chrono in g-api tests

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/misc/java/test/DnnListRegressionTest.java, modules/dnn/misc/java/test/DnnTensorFlowTest.java, modules/dnn/misc/objc/gen_dict.json, modules/dnn/perf/perf_net.cpp, modules/dnn/src/dnn_read.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/reshape_layer.cpp, modules/dnn/src/model.cpp, modules/dnn/src/net_impl2.cpp, modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_graph_simplifier.hpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
=> Modified tensorflow parser for the new dnn engine

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/version.hpp, modules/python/package/setup.py, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
previous PR with version bump: #25615
=> pre: OpenCV 5.0.0-alpha (version++).

modules/stitching/include/opencv2/stitching.hpp
=> Document some stitching methods and enable bindings for them.

samples/dnn/common.hpp, samples/dnn/common.py, samples/dnn/models.yml, samples/dnn/object_detection.cpp, samples/dnn/object_detection.py
1. Changes to add findModel support for config file in models like yolov4, yolov4-tiny, yolov3, ssd_caffe, tiny-yolo-voc, ssd_tf and faster_rcnn_tf.
2. Added new model and config download links for ssd_caffe, as previous links were not working.
3. Switched to DNN ENGINE_CLASSIC for non-cpu convig as new engine does not support it.
4. Fixes in python sample related to yolov5 usage.
=> Code Fixes and changed post processing based on models.yml in Object Detection Sample

modules/core/doc/intro.markdown
Closed https://github.com/opencv/opencv/issues/26550
=> doc: update introduction for new MatDepth(5.x)

modules/core/include/opencv2/core/utility.hpp
=> fix typo in AlgorithmHint description

modules/core/misc/objc/common/CvType.mm, modules/core/misc/objc/common/CvTypeExt.swift, modules/core/misc/objc/common/Mat.mm, modules/core/misc/objc/test/MatTestObjc.m
Address comments in https://github.com/opencv/opencv/pull/26559
=> More data types support in Obj-C  and Swift bindings

modules/highgui/CMakeLists.txt
=> Missing include directories needed for wayland-util and xkbcommon

modules/imgproc/include/opencv2/imgproc.hpp
=> fix typo modfication

samples/dnn/gpt2_inference.py
This PR adds dynamic input support for `gpt2_inference.py` sample.
Fixes #26518
Fixes #26517
=> Fix gpt2 sample

doc/tutorials/introduction/macos_install/macos_install.markdown
=> Improvement of macOS installation guide in documentation

modules/photo/perf/perf_cuda.cpp
=> Fix typo: renamed 'search_widow_size' to 'search_window_size'

modules/ml/src/svm.cpp
=> Fix #25812: Add error handling for invalid nu parameter in SVM NU_SVC

modules/dnn/src/tensorflow/tf_importer.cpp
=> Replace structured binding for better compilers support

samples/dnn/gpt2_inference.py
This PR update how GPT2 prints its output
**Note**: As the length of the prompt increases while inference, the token generation time slows down. May be its right time to introduce QK cashing to speed up the inference
=> Update printingin GPT2 sample

doc/CMakeLists.txt, doc/Doxyfile.in, doc/footer.html, doc/header.html, modules/core/include/opencv2/core.hpp
Port #26598 to 5.x. Changes are mostly the same, though we don't need updated CSS provided by doxygen because we use doxygen-awesome stylesheet.
=> doc: upgraded for compatibility with doxygen 1.12 (5.x)

modules/dnn/src/layers/elementwise_layers.cpp
Fixes https://github.com/opencv/opencv/issues/26175 https://github.com/opencv/opencv/issues/26631
=> dnn: Fix CANN build

modules/calib3d/src/calibration.cpp
The CvLevMarq code has to be kept in order to keep the same accuracy (the C++ solver is not as good).
There are two ways to review this PR: by comparing to the old code, or by checking what is different from the 5.x version (which is the first commit).
=> Switch calibration.cpp to C++

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_android_camera.cpp, modules/videoio/src/cap_android_mediandk.cpp, modules/videoio/src/cap_interface.hpp
Closes https://github.com/opencv/opencv/issues/24687
=> Android camera feature enhancements

modules/js/generator/embindgen.py
```
Xbuild_image:Custom=javascript
Xbuild_image:Custom=javascript-simd:3.1.64
build_image:Custom=javascript:3.1.64
```
=> js: fix generation of "const const" in code

modules/calib3d/misc/js/gen_dict.json, modules/js/src/core_bindings.cpp, modules/photo/misc/js/gen_dict.json, platforms/js/opencv_js.config.py
This fixes #25239
```
Xbuild_image:Custom=javascript
Xbuild_image:Custom=javascript-simd:3.1.64
build_image:Custom=javascript:3.1.64
```
=> js: add types included in bound APIs

modules/js/src/core_bindings.cpp
=> js: Fix C preprocessor stringification

modules/dnn/test/test_ie_models.cpp
- _face-detection-0105_ and _face-detection-0106_ - are absent from download_models.py (and OMZ)
- _person-vehicle-bike-detection-2004_ - have incompatible output (i64)
See also: https://github.com/opencv/opencv_extra/pull/1227
=> dnn: remove obsolete OV models tests

doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/version.hpp, modules/python/package/setup.py, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
=> pre: OpenCV 4.11.0 (version++)

modules/java/generator/android-24/java/org/opencv/android/NativeCameraView.java, modules/videoio/src/cap_android_mediandk.cpp, samples/android/video-recorder/src/org/opencv/samples/recorder/RecorderActivity.java
- [ x] There is a reference to the original bug report and related work
=> AndroidMediaNdkCapture pixel format enhancement

modules/imgcodecs/src/grfmt_png.cpp
=> Fix flaky Imgcodecs_APNG.imwriteanimation_bgcolor

modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/src/grfmt_png.hpp
=> Fix leaks in cv::PngDecoder

modules/videoio/src/cap_android_mediandk.cpp, samples/android/video-recorder/src/org/opencv/samples/recorder/RecorderActivity.java
- [x ] The PR is proposed to the proper branch
=> AndroidMediaNdkVideoWriter pixel format enhancement

modules/imgcodecs/src/grfmt_avif.cpp, modules/imgcodecs/src/grfmt_avif.hpp, modules/imgcodecs/src/grfmt_base.cpp, modules/imgcodecs/src/grfmt_gif.cpp, modules/imgcodecs/src/grfmt_gif.hpp, modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/src/grfmt_png.hpp, modules/imgcodecs/src/grfmt_webp.cpp, modules/imgcodecs/src/grfmt_webp.hpp, modules/imgcodecs/test/test_animation.cpp
related issues https://github.com/opencv/opencv/issues/24855
=> Animated GIF APNG WEBP AVIF revisions

modules/imgcodecs/src/grfmt_png.cpp
=> Fixed some memory leaks in PNG/APNG implementation

modules/imgcodecs/src/grfmt_png.cpp
=> fix for png durations and memory leak

modules/imgcodecs/src/grfmt_png.cpp
=> Remove extra /* in /**/ comment

modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/src/grfmt_png.hpp
=> Use RAII to avoid leaks in PNG reader.

modules/imgcodecs/src/grfmt_png.cpp
=> Fix behavior change when PNG buffer is incomplete.

modules/imgcodecs/src/grfmt_png.cpp
=> Fixed fread size check for corrupted PNGs

modules/core/include/opencv2/core/version.hpp
Related: https://github.com/opencv/opencv/pull/26664
=> Release 4.11.0

modules/imgcodecs/src/grfmt_exr.cpp, modules/imgcodecs/test/test_exr.impl.hpp
Closed https://github.com/opencv/opencv/issues/26705
=> imgcodecs: fix EXR tests

modules/objc/generator/gen_objc.py
=> Ensure Obj-C header files are generated correctly if under /private/var

modules/calib3d/src/fundam.cpp
=> Bug fix for #25546 - Updating inliers for homography estimation

modules/objdetect/src/aruco/aruco_board.cpp, modules/objdetect/test/test_boarddetection.cpp
=> Fix rotated aruco marker board generation

modules/dnn/src/vkcom/src/context.cpp
Fixes https://github.com/opencv/opencv/issues/26759
=> Fixed Android build with Vulkan support.

modules/imgproc/include/opencv2/imgproc.hpp
=> Fix typo in matchTemplate description

modules/core/src/opencl/runtime/opencl_core.cpp
=> OpenCL: OpenBSD build fix

modules/imgproc/src/filter.dispatch.cpp
=> removal of unused variable `kernalDataUMat`

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/misc/java/test/ImgcodecsTest.java
=> add CV_WRAP to Animation struct

samples/cpp/tutorial_code/ImgTrans/HoughLines_Demo.cpp, samples/cpp/tutorial_code/objectDetection/aruco_samples_utility.hpp, samples/opengl/opengl_interop.cpp
=> Replaced sprintf with snprintf

modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/src/grfmt_png.hpp
This fixes https://oss-fuzz.com/testcase-detail/4923671881252864 and https://oss-fuzz.com/testcase-detail/5048650127966208
=> Fix potential READ memory access

modules/videoio/src/cap_android_camera.cpp
This patch set does not contain any functional changes. It just cleans up the code structure to improve readability and to prepare for future changes.
=> Android camera refactoring

modules/imgcodecs/src/grfmt_png.cpp
Only user chunks need to be compared to PNG_USER_CHUNK_MALLOC_MAX
Big PNGs with a big IDAT can fail because of this.
=> Move the checks to read_chunk.

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/fisheye.cpp, modules/calib3d/test/test_fisheye.cpp
Related: https://github.com/opencv/opencv/pull/25028
=> solvePnPRansac implementation for Fisheye camera model

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap_android_camera.cpp
- [x ] The PR is proposed to the proper branch
=> Zoom functionality for Android native camera capture

modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/test/test_animation.cpp
=> Corrections on bKGD chunk writing and reading in PNG

samples/data/data01.xml
=> Fix data01.xml file for example_cpp_logistic_regression

doc/opencv.bib, doc/tutorials/imgproc/out_of_focus_deblur_filter/out_of_focus_deblur_filter.markdown, doc/tutorials/imgproc/periodic_noise_removing_filter/periodic_noise_removing_filter.markdown, modules/stitching/include/opencv2/stitching/detail/seam_finders.hpp
Update and dd pdf links in the bibliography.
=> Add direct pdf links in the bibliography

modules/imgproc/src/filter.hpp
Fixes :
```
identifier "Mat" is undefinedC/C++(20)
namespace "std" has no member "vector"C/C++(135)
```
=> Update includes in filter.hpp

modules/python/src2/typing_stubs_generation/predefined_types.py
=> Workaround solution for isuue #26818

cmake/OpenCVFindWebP.cmake
=> Update OpenCVFindWebP.cmake with sturkmen72's suggestion

modules/imgproc/src/sumpixels.avx512_skx.hpp
=> minor change

.github/workflows/PR-4.x.yaml
=> CI: update GHA pipelines

.github/workflows/PR-5.x.yaml
Use unified Linux pipeline
see also #26607
=> CI: update GHA pipelines (5.x)

modules/highgui/src/window_w32.cpp, modules/imgcodecs/perf/perf_decode_encode.cpp, modules/imgcodecs/src/grfmt_avif.cpp, modules/imgcodecs/src/grfmt_avif.hpp, modules/imgcodecs/src/grfmt_base.cpp, modules/imgcodecs/src/grfmt_base.hpp, modules/imgcodecs/src/grfmt_gif.cpp, modules/imgcodecs/src/grfmt_gif.hpp, modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/src/loadsave.cpp
=> Performance tests for image encoders and decoders and code cleanup

samples/dnn/inpainting.cpp, samples/dnn/inpainting.py, samples/dnn/models.yml
=> Added lama inpainting onnx model sample

modules/core/src/persistence.cpp, modules/core/src/persistence_base64_encoding.cpp, modules/core/test/test_io.cpp, modules/python/src2/cv2_convert.cpp, modules/python/test/test_filestorage_io.py
OpenCV extra: https://github.com/opencv/opencv_extra/pull/1233
=> Support 32-bit unsigned type for FileStorage Base64

doc/tutorials/introduction/config_reference/config_reference.markdown
Close https://github.com/opencv/opencv/issues/26877
=> doc: update supporting imgcodec format settings

modules/core/test/test_io.cpp
OpenCV extra: https://github.com/opencv/opencv_extra/pull/1234
=> Remove code duplication from test for FileStorage Base64

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_tiff.cpp
=> imgcodecs: tiff: refactor Imgcodecs_Tiff_decode_Huge test

modules/core/src/hal_replacement.hpp
=> fix hal_replacement typos

modules/core/src/hal_replacement.hpp, modules/core/src/mean.dispatch.cpp
=> Use HAL for cv::mean function too

modules/imgcodecs/src/grfmt_png.cpp
Resolves #26913
Related(?): #25715 #26832
=> imgcodecs: fix PNG read on BE platforms (s390x)

3rdparty/openvx/hal/CMakeLists.txt, 3rdparty/openvx/hal/openvx_hal.cpp, 3rdparty/openvx/hal/openvx_hal.hpp, modules/features2d/src/fast.cpp, modules/features2d/test/test_fast.cpp
Depends on https://github.com/opencv/opencv/pull/26903
Regression data: https://github.com/opencv/opencv_extra/pull/1236
=> Migrate remaning OpenVX integrations to OpenVX HAL (features2d)

doc/tutorials/calib3d/camera_calibration/camera_calibration.markdown, doc/tutorials/calib3d/interactive_calibration/interactive_calibration.markdown, doc/tutorials/calib3d/real_time_pose/real_time_pose.markdown, doc/tutorials/calib3d/usac.markdown
=> fix minor issues in calib3d Docs

.github/workflows/PR-4.x.yaml
=> Squeeze several Windows pipelines into one with jobs

.github/workflows/PR-4.x.yaml
=> Removed Android test as it's broken for now

modules/highgui/src/window_cocoa.mm, modules/highgui/src/window_gtk.cpp, modules/highgui/src/window_w32.cpp, modules/videoio/src/cap_dshow.cpp
Related: https://github.com/opencv/opencv/pull/26939
=> Backported some C API cleanup from 5.x to 4.x to reduce conflicts in 4.x->5.x merge

modules/videoio/doc/videoio_overview.markdown
=> Some minor fixes

.github/workflows/PR-5.x.yaml, modules/videoio/test/test_audio.cpp, modules/videoio/test/test_ffmpeg.cpp, modules/videoio/test/test_gstreamer.cpp, modules/videoio/test/test_mfx.cpp, modules/videoio/test/test_orientation.cpp, modules/videoio/test/test_precomp.hpp, modules/videoio/test/test_video_io.cpp
=> videoio: print test params instead of indexes (5.x)

modules/calib3d/src/stereosgbm.cpp
=> fix Logical defect in FilterSpecklesImpl

modules/core/src/minmax.cpp
Related https://github.com/opencv/opencv/pull/26946
=> Backported some CALL_HAL improvements from 5.x #26946

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/perf/perf_decode_encode.cpp, modules/imgcodecs/perf/perf_png.cpp, modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/src/grfmt_png.hpp, modules/imgcodecs/src/grfmt_spng.cpp, modules/imgcodecs/src/grfmt_spng.hpp, modules/imgcodecs/test/test_animation.cpp, modules/imgcodecs/test/test_common.cpp, modules/imgcodecs/test/test_common.hpp, modules/imgcodecs/test/test_png.cpp
=> APNG encoding optimization

3rdparty/fastcv/src/fastcv_hal_imgproc.cpp
=> Fix gaussianBlur5x5 performance regression

modules/imgcodecs/src/grfmt_gif.cpp, modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/test/test_animation.cpp
=> Add a test to ensure ImageCollection class works good with animations

modules/objdetect/include/opencv2/objdetect/aruco_detector.hpp, modules/objdetect/misc/python/test/test_objdetect_aruco.py, modules/objdetect/src/aruco/aruco_detector.cpp, modules/objdetect/test/test_arucodetection.cpp, modules/objdetect/test/test_boarddetection.cpp, modules/python/src2/cv2.cpp
* Add constructor for multiple dictionaries
* Add get/set/remove/add functions for multiple dictionaries
* Add unit tests
TESTED=unit tests
=> Extend ArUcoDetector to run multiple dictionaries in an efficient manner.

modules/photo/src/contrast_preserve.hpp
=> Local decolor pipeline optimization

3rdparty/hal_rvv/hal_rvv_1p0/filter.hpp
Further optimization for #27026.
View the full perf table here: [optimize_sepfilter.pdf](https://github.com/user-attachments/files/19245636/optimize_sepfilter.pdf)
=> Optimize RISC-V HAL cv::sepFilter

modules/objdetect/test/test_arucodetection.cpp
=> Add test for ArucoDetector::detectMarkers

modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_animation.cpp
=> Fixing imread() function 16 bit APNG reading problem

modules/imgproc/src/imgwarp.cpp
=> When WARP_INVERSE_MAP is used, accelerate the calculation with multi-threading

doc/js_tutorials/js_imgproc/js_watershed/js_watershed.markdown, doc/py_tutorials/py_imgproc/py_watershed/py_watershed.markdown
=> Update old URL

modules/core/perf/perf_norm.cpp, modules/core/src/norm.dispatch.cpp, modules/core/src/norm.simd.hpp
Merge with https://github.com/opencv/opencv_extra/pull/1243
=> 5.x merge 4.x: vectorized normDiff

modules/calib3d/include/opencv2/calib3d.hpp
=> Add documentation for StereoBM parameters (fixes #26816)

modules/calib3d/test/test_solvepnp_ransac.cpp
=> Add planar accuracy tests for solvePnPRansac

modules/dnn/test/test_onnx_importer.cpp
Merge with test data: https://github.com/opencv/opencv_extra/pull/1245
=> Test gemm 3inputs

3rdparty/hal_rvv/hal_rvv.hpp, 3rdparty/hal_rvv/hal_rvv_1p0/common.hpp, 3rdparty/hal_rvv/hal_rvv_1p0/norm.hpp, 3rdparty/hal_rvv/hal_rvv_1p0/norm_diff.hpp, modules/core/src/norm.simd.hpp
Merge wtih https://github.com/opencv/opencv_extra/pull/1246.
=> core: refactored normDiff in hal_rvv and extended with support of more data types

3rdparty/hal_rvv/hal_rvv.hpp, 3rdparty/hal_rvv/hal_rvv_1p0/copy_mask.hpp, modules/core/src/copy.cpp, modules/core/src/hal_replacement.hpp
=> HAL: added copyToMask and implemented in hal_rvv

modules/calib3d/test/test_solvepnp_ransac.cpp
=> Specify DLS and UPnP mappings to EPnP in all places for solvePnP* tests

3rdparty/hal_rvv/hal_rvv.hpp, 3rdparty/hal_rvv/hal_rvv_1p0/common.hpp, 3rdparty/hal_rvv/hal_rvv_1p0/div.hpp
=> HAL: implemented cv_hal_div* and cv_hal_recip* in hal_rvv

3rdparty/ipphal/CMakeLists.txt, 3rdparty/ipphal/include/ipp_hal_core.hpp, 3rdparty/ipphal/src/cart_polar_ipp.cpp, modules/core/src/mathfuncs.cpp
=> Transfer IPP polarToCart to HAL

3rdparty/ipphal/CMakeLists.txt, 3rdparty/ipphal/include/ipp_hal_core.hpp, 3rdparty/ipphal/src/mean_ipp.cpp, 3rdparty/ipphal/src/minmax_ipp.cpp, 3rdparty/ipphal/src/norm_ipp.cpp, 3rdparty/ipphal/src/transforms_ipp.cpp, modules/core/src/matrix_transform.cpp
=> Migrated IPP impl for flip and transpose to HAL

3rdparty/fastcv/src/fastcv_hal_imgproc.cpp
=> Optimize gaussian blur performance in FastCV HAL

3rdparty/hal_rvv/hal_rvv.hpp, 3rdparty/hal_rvv/hal_rvv_1p0/dotprod.hpp
=> HAL: implemented cv_hal_dotProduct in hal_rvv

3rdparty/hal_rvv/hal_rvv.hpp, 3rdparty/hal_rvv/hal_rvv_1p0/integral.hpp, 3rdparty/hal_rvv/hal_rvv_1p0/types.hpp, modules/imgproc/perf/perf_integral.cpp, modules/imgproc/src/sumpixels.dispatch.cpp, modules/imgproc/test/test_filter.cpp
This patch introduces an RVV-optimized implementation of `cv::integral()` in hal_rvv, along with performance and accuracy tests for all valid input/output type combinations specified in `modules/imgproc/src/hal_replacement.hpp`:
https://github.com/opencv/opencv/blob/2a8d4b8e43f6e499c5553edd26056caed284d5a6/modules/imgproc/src/hal_replacement.hpp#L960-L974
The vectorized prefix sum algorithm follows the approach described in [Prefix Sum with SIMD - Algorithmica](https://en.algorithmica.org/hpc/algorithms/prefix/).
I intentionally omitted support for the following cases by returning `CV_HAL_ERROR_NOT_IMPLEMENTED`, as they are harder to implement or show limited performance gains:
1. **Tilted Sum**: The data access pattern for tilted sums requires multi-row operations, making effective …
=> [hal_rvv] Add cv::integral implementation and more types of input for test

doc/tutorials/calib3d/camera_calibration/camera_calibration.markdown, doc/tutorials/calib3d/camera_calibration_pattern/camera_calibration_pattern.markdown, doc/tutorials/calib3d/camera_calibration_square_chess/camera_calibration_square_chess.markdown
=> minor changes in calib3d docs for clarity

3rdparty/fastcv/include/fastcv_hal_core.hpp, 3rdparty/fastcv/src/fastcv_hal_core.cpp, modules/core/test/test_operations.cpp
=> FastCV gemm hal

hal/riscv-rvv/hal_rvv_1p0/flip.hpp
=> hal/riscv_rvv: implemented flip_inplace to boost cv::rotate

modules/core/perf/opencl/perf_arithm.cpp, modules/core/src/mathfuncs.cpp, modules/core/src/opencl/arithm.cl, modules/core/test/ocl/test_arithm.cpp
fixes #26328
Validated:
- ??? NVIDIA GPU
```
```
=> core(OCL): fix POWN OpenCL implementation

modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
Limited support of TFLite's StridedSlice with unit strides
resolves #26140
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1254/
=> TFLite StridedSlice

modules/highgui/src/window_QT.cpp
Partially reverts https://github.com/opencv/opencv/pull/24823
Fixes #26180
Fixes #26761
=> Fixed QT window resize logic

modules/imgcodecs/src/grfmt_gif.cpp
=> Fix a bug on rendering some animated gif

cmake/OpenCVPackaging.cmake
=> License update in CPack generated packages

modules/dnn/src/net_impl_fuse.cpp
Enables YOLO11n with CUDA backend
resolves #26566
=> CUDA: Handle fusion of conv+eltwise in case of multi-output node (i.e. Split)

modules/dnn/src/layers/concat_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/legacy_backend.hpp, modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
* Scalars support
* Better handling of 1D tensors
* New ops import: SUB, SQRT, DIV, NEG, SQUARED_DIFFERENCE, SUM
* Number of NHWC<->NCHW layouts compatibility improvements
resolves #27211
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1257
=> TFLite fixes for Face Blendshapes V2

hal/riscv-rvv/include/imgproc.hpp, hal/riscv-rvv/src/imgproc/histogram.cpp, modules/imgproc/src/hal_replacement.hpp, modules/imgproc/src/histogram.cpp
=> hal/imgproc: add hal for calcHist and implement in hal/riscv-rvv

modules/imgproc/src/histogram.cpp
=> imgproc: vectorize mode CHISQR and CHISQR_ALT in compareHist

modules/dnn/test/test_onnx_importer.cpp
=> Higher threshold for ViT on OpenVINO

hal/ipp/CMakeLists.txt, hal/ipp/include/ipp_hal_core.hpp, hal/ipp/src/sum_ipp.cpp, modules/core/src/hal_replacement.hpp, modules/core/src/sum.dispatch.cpp
=> New HAL entry for cv::sum and IPP adoption

hal/ipp/include/ipp_hal_core.hpp, hal/ipp/include/ipp_utils.hpp, hal/ipp/src/cart_polar_ipp.cpp, hal/ipp/src/mean_ipp.cpp, hal/ipp/src/minmax_ipp.cpp, hal/ipp/src/norm_ipp.cpp, hal/ipp/src/sum_ipp.cpp, hal/ipp/src/transforms_ipp.cpp
=> Added default copyright header to IPP HAL

doc/tutorials/introduction/building_fastcv/building_fastcv.markdown
Updating doc markdown to include API in  FastCV gemm HAL
=> Updating doc markdown to include API in FastCV gemm HAL

modules/imgcodecs/src/grfmt_jpegxl.cpp, modules/imgcodecs/test/test_jpegxl.cpp
Close https://github.com/opencv/opencv/issues/27382
=> imgcodecs: jpegxl: support lossless compression

modules/js/generator/CMakeLists.txt, modules/python/bindings/CMakeLists.txt, modules/python/src2/hdr_parser.py
The issue found in https://github.com/opencv/opencv/pull/27370
=> Fixed bug in ifdef state machine in header parser for bindings

modules/videoio/misc/java/test/VideoCaptureTest.java
required for https://github.com/opencv/opencv/pull/27370
=> Cover all seek directions in VideoCapture Java test

cmake/checks/cpu_neon.cpp, cmake/checks/cpu_neon_bf16.cpp, cmake/checks/cpu_neon_dotprod.cpp, cmake/checks/cpu_neon_fp16.cpp, modules/core/include/opencv2/core/cv_cpu_dispatch.h, modules/core/include/opencv2/core/cvdef.h, modules/core/include/opencv2/core/fast_math.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/src/matmul.simd.hpp, modules/core/src/parallel.cpp, modules/core/src/system.cpp, modules/dnn/src/op_inf_engine.cpp, modules/flann/include/opencv2/flann/dist.h, modules/highgui/src/window_w32.cpp, modules/ts/include/opencv2/ts/ts_ext.hpp
Close https://github.com/opencv/opencv/issues/27413
=> (experimental) support _M_ARM64EC for MSVS2022

modules/dnn/src/net_impl2.cpp, modules/dnn/src/tflite/tflite_importer.cpp, modules/dnn/test/test_tflite_importer.cpp
This PR covers updates from the following PRs:
#27273, #27307 (ported to 5.x by #27370)
resolves #27397
=> Adoptions of TFLife fixes to new engine

hal/kleidicv/kleidicv.cmake
=> KleidiCV update to version 0.5

modules/imgcodecs/src/grfmt_webp.cpp
=> fix for the issue #27456

modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/imgcodecs/src/grfmt_base.hpp, modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_animation.cpp
=> Changes about when APNG has a hidden frame

modules/imgcodecs/src/grfmt_png.cpp, modules/imgcodecs/test/test_animation.cpp
=> fix for #26825

modules/imgcodecs/include/opencv2/imgcodecs.hpp
Fixes https://github.com/opencv/opencv/issues/27431
=> Documentaion update for haveImageReader function

modules/core/misc/java/src/java/core+MatAt.kt
This PR related to issue #26129  to attempting to fix.
I would like to say that this issue not happen when we use maven package with same configuration stated in the issue with same JDK 17 and SDK 34 it just works. This is only hppens when we download  opencv android from website use as a module and add into gradle
=> fix(android): Kotlin 2.0 internal error for unsafe coercions

hal/ipp/src/warp_ipp.cpp
=> Fixed memory leak in ipp_warp function

apps/interactive-calibration/calibCommon.hpp, apps/interactive-calibration/main.cpp, apps/interactive-calibration/parametersController.cpp
=> More intrinsic calibration flags in integractive calibration tool

COPYRIGHT
=> Added OpenCV.AI copyright.

modules/imgcodecs/test/test_gif.cpp
Close https://github.com/opencv/opencv/issues/27648
=> test: gif: to test GIF codec at write_gif_flags

modules/imgproc/src/accum.cpp, modules/imgproc/src/featureselect.cpp, modules/imgproc/src/histogram.cpp, modules/imgproc/test/ocl/test_histogram.cpp, modules/imgproc/test/test_goodfeaturetotrack.cpp
=> Bool masks support in imgproc module.

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/size_layer.cpp, modules/dnn/src/onnx/onnx_importer2.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_filter_opencv_classic_denylist.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
Merge with https://github.com/opencv/opencv_extra/pull/1274
=> Added Size layer to new DNN engine

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/is_inf_layer.cpp, modules/dnn/src/onnx/onnx_importer2.cpp, modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_filter_opencv_classic_denylist.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
=> Added IsInf layer to new DNN engine

modules/calib3d/include/opencv2/calib3d.hpp
=> Wrap cicles grid GridType as settings structure is useless without it.

modules/dnn/src/layers/pooling_layer.cpp
Closes https://github.com/opencv/opencv/issues/27739
=> Build fix for Clang 21.

modules/videoio/doc/videoio_overview.markdown
=> Fix typos in documentation

doc/opencv.bib, modules/flann/include/opencv2/flann/general.h, modules/imgcodecs/include/opencv2/imgcodecs.hpp, modules/objdetect/doc/objdetect.bib
Close https://github.com/opencv/opencv/issues/27729
=> doc: fix doxygen warnings for imgcodecs, flann and objdetect

modules/python/src2/cv2.cpp
=> Optional 3D module dependency in Python

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/unique_layer.cpp, modules/dnn/src/onnx/onnx_importer2.cpp, modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_filter_opencv_classic_denylist.inl.hpp, modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
=> Added unique layer to new DNN engine

samples/python/multiview_calibration.py
=> Fixed cameras name loading in multiview camera visualization.

modules/calib/src/multiview_calibration.cpp, samples/python/multiview_calibration.py
=> Added info logs with intermediate values to multiview calibration and related script option

modules/objdetect/src/qrcode.cpp, modules/objdetect/test/test_qrcode.cpp
Close https://github.com/opencv/opencv/issues/27783
=> objdetect: enable setEpsY() for QRDetectMulti

modules/core/src/parallel/parallel.cpp
=> core: restore parallel name on failure attempt

modules/objdetect/src/aruco/charuco_detector.cpp
Fixes https://github.com/opencv/opencv/issues/25188
This speeds up processing a 132x128 board by more than 100 times. This methods return std::vectors<> which means lots of copies and allocations.
Before it took 40secs to process one image and now 0.16sec.
This is very similar to https://github.com/opencv/opencv/pull/25507 but fixes the same issue without changing the API.  I also see the same speedup with my patch and his but thought this one is maybe more likely to get accepted because its only an internal change...,
I encounter this issue here https://github.com/undingen/SkewCamera/pull/1 and it makes unfortunately currently my software unusable for this kind of board.
Patch to …
=> Speedup ChArUco by avoiding temporary copies

modules/ml/src/ann_mlp.cpp, modules/ml/src/em.cpp, modules/ml/src/precomp.hpp, modules/ml/src/svm.cpp
=> Remove more C code

modules/core/misc/python/pyopencv_cuda.hpp
Address https://github.com/opencv/opencv/pull/27581#issuecomment-3316217323
=> Warning fixes in DLpack integration on Win32
