- modules/dnn/include/opencv2/dnn/all_layers.hpp
- modules/dnn/perf/perf_layer.cpp
- modules/dnn/src/cuda/mvn.cu
- modules/dnn/src/cuda4dnn/kernels/mvn.hpp
- modules/dnn/src/cuda4dnn/primitives/group_norm.hpp
- modules/dnn/src/init.cpp
- modules/dnn/src/layers/cpu_kernels/fast_norm.cpp
- modules/dnn/src/layers/cpu_kernels/fast_norm.hpp
- modules/dnn/src/layers/group_norm_layer.cpp
- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/src/opencl/mvn.cl
- modules/dnn/test/test_onnx_conformance.cpp
- modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
dnn onnx: add group norm layer
Todo:
> dnn onnx: add group norm layer

- modules/core/include/opencv2/core/cvdef.h
- modules/dnn/include/opencv2/dnn/dnn.hpp
- modules/objdetect/include/opencv2/objdetect/barcode.hpp
- modules/objdetect/include/opencv2/objdetect/face.hpp
- modules/python/common.cmake
- modules/python/src2/cv2.hpp
- modules/python/src2/cv2_convert.cpp
- modules/python/src2/gen2.py
- modules/python/src2/hdr_parser.py
- modules/python/test/test_pathlike.py
Merry Christmas, all :christmas_tree: 
Implements #15731
Support is enabled for all arguments named `filename` or `filepath` (case-insensitive), or annotated with `CV_WRAP_FILE_PATH`.
Support is based on `PyOS_FSPath`, which is available in Python 3.6+. When running on older Python versions the arguments must have a `str` value as before.
> python: accept path-like objects wherever file names are expected

- modules/dnn/src/layers/cpu_kernels/conv_winograd_f63.cpp
`winofunc_AtXA_8x8_f32()` needs function call in both AVX and in AVX2. Prior to this change the function was called under `opt_AVX` , now its called under `opt_AVX2`.
Fixes #24677
> Use AVX2 overload instread on AVX in AVX2 scope

- modules/dnn/src/int8layers/convolution_layer.cpp
- modules/dnn/src/int8layers/fully_connected_layer.cpp
- modules/dnn/src/int8layers/layers_common.hpp
- modules/dnn/src/int8layers/layers_rvp052.cpp
- modules/dnn/src/int8layers/layers_rvp052.hpp
- platforms/linux/riscv64-andes-gcc.toolchain.cmake
Provides OpenCV optimizations for the RISC-V P extension (v0.5.2).
1. Added RVP as a new backend to the OpenCV build system;
2. Optimized some of the algorithms in the DNN, features2d (feature detection), and imgproc (image processing) modules using RVP Intrinsic functions;
3. Verified the correctness of the optimized algorithms using the QEMU simulator.
The writer of the code and the author of the PR is an intern at ISCAS (Institute of Software, Chinese Academy of Sciences).
- Optimization of **three convolution functions** for int8 layers of deep neural networks
```cpp
// modules/dnn/src/int8layers/layers_common.simd.hpp
void cv::dnn::fastConv( ... );
void cv::dnn::fastDepthwiseConv( ... );
void cv::dnn::fastGEMM1T( ... );
```
- Optimization of matrix **affine transformations**
```cpp …
```
> Optimization based on RISC-V P Packed SIMD Extension v0.5.2

- modules/core/src/system.cpp
- modules/ts/CMakeLists.txt
Based on https://github.com/opencv/opencv/issues/24567
Passing `-D OPENCV_SKIP_CMAKE_CXX_STANDARD=ON` during cmake configure. 100% build success with commit of 2791bb7062:
```
2791bb7062 2024-01-12 | Merge pull request #24773 from tailsu:sd/pathlike (origin/master) [Stefan Dragnev]
```
QNX SDP version: 7.1.0, which uses a C++ compiler version 8.3.0:
> CMAKE_CXX_COMPILER_VERSION=8.3.0
Due to QNX SDP license, I'm not sure if I can provide its installer.
The latest version of QNX SDP can be obtained from its website https://www.qnx.com/account/login.html (a registered account is required. Not tested with its latest QNX SDP yet).
This PR fixed …
> Fix QNX build

- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_onnx_conformance_layer_filter_opencv_all_denylist.inl.hpp
Fixes https://github.com/opencv/opencv/issues/24861
> Normalize axis parameter in DNN Concat to handle negative values

- modules/video/include/opencv2/video/tracking.hpp
- modules/video/src/dis_flow.cpp
- modules/video/src/variational_refinement.cpp
Resolves #24847 
I believe this is necessary to expose \epsilon parameter.
> Make \epsilon parameter accessible in VariationalRefinement

- modules/videoio/misc/objc/ios/CvPhotoCamera2.m
- modules/videoio/misc/objc/ios/CvVideoCamera2.mm
- modules/videoio/src/cap_avfoundation_mac.mm
Related: #24759 and #24634
These were deprecated in iOS 11 and their replacements, AVVideoCodecTypeH264 and AVVideoCodecTypeJPEG, map to the same string constants.
The changes in modules/videoio/src/cap_av_foundation_mac.mm match those already made in [cap_av_foundation.mm](https://github.com/opencv/opencv/blob/4.x/modules/videoio/src/cap_avfoundation.mm#L1303-L1309).
> Replace deprecated symbols AVVideoCodecH264 and AVVideoCodecJPEG

- cmake/OpenCVDetectPython.cmake
Fixes https://github.com/opencv/opencv/pull/24773#discussion_r1450650158
```
force_builders=Win64 OpenCL
```
> Downgrade LIMITED_API_VERSION, if python3 is older than 3.6

- modules/dnn/perf/perf_layer.cpp
- modules/dnn/src/layers/scatterND_layer.cpp
- modules/dnn/src/layers/scatter_layer.cpp
Benchmark was done on M1 Macbook Air (16G mem). Time is in milliseconds.
*: Shapes of input, indices, updates are all [2, 128, 64, 50].
| Operator | w/ this PR | w/o this PR | ORT |
| - | - | - | - |
| Scatter (Reduction=None, axis=0) | 2.04 | 7.36 | 6.81 |
| Scatter (Reduction=Add, axis=0) | 2.00 | 7.61 | 6.33 |
| ScatterND (Reduction=None) | 1.41 | 6.59 | 17.52 |
| ScatterND (Reduction=Add) | 1.37 | 6.83 | 16.34 |
Scripts for ORT benchmark: [ort_benchmark.zip](https://github.com/opencv/opencv/files/13856078/ort_benchmark.zip)
```
```
> dnn: improve scatter and scatterND speed with multi-threading

- modules/dnn/src/layers/scatterND_layer.cpp
- modules/dnn/src/layers/scatter_layer.cpp
Resolves https://github.com/opencv/opencv/pull/24813#issuecomment-1896014961
```
```
> dnn: fix ocl_fp16 support of scatter layer

- modules/core/src/system.cpp
based on https://github.com/opencv/opencv/pull/24864
When building with qnx-sdp-700 with code in this PR: https://github.com/opencv/opencv/pull/24864, 
there is compile error:
```
[ 38%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/trace.cpp.o
/builds/3rdparty/opencv-build/opencv/modules/core/src/system.cpp:131:20: error: expected primary-expression before 'auto'
constexpr decltype(auto) AT_HWCAP = NT_GNU_HWCAP;
^
```
`decltype(auto)` seems to be an C++14 introduced feature, intead of C++11.
`uint64_t` is OK when build locally.
[asmorkalov](https://github.com/asmorkalov)
> fix qnx-sdp-700 build

- modules/gapi/src/backends/ie/giebackend.cpp
- modules/gapi/src/backends/ie/giebackend.hpp
- modules/gapi/src/backends/ie/giebackend/giewrapper.cpp
- modules/gapi/test/infer/gapi_infer_ie_test.cpp
[OpenVINO](https://github.com/openvinotoolkit/openvino) introduced the new `API 2.0` since `2022.1.0` version and plan to completely remove the old API by `2024.0.0`. 
The suggestion is to check `INF_ENGINE_RELEASE < 2024000000` and if so, completely disable `IE` backend and its unit tests that rely on `API 1.0`.
> G-API: Ifdef OpenVINO API 1.0 functionality

- doc/tutorials/introduction/windows_install/windows_install.markdown
Added command to set opencv path for vc17.
> Update windows_install.markdown - add set opencv path for vc17

- modules/dnn/test/test_backends.cpp
Closes sporadic test failures in GHA and Buildbot
```
force_builders=Linux OpenCL,Linux AVX2,Linux32,Win32
```
> Relax test requirements for OpenCL in test DNNTestNetwork.FastNeuraStyle_eccv16

- modules/core/include/opencv2/core/cvdef.h
Warnings example: https://github.com/opencv/opencv/actions/runs/7585201114/job/20660514876
> Fixed type cast warning in CV_ELEM_SIZE1 for cv::Mat::type

- modules/dnn/src/layers/einsum_layer.cpp
- modules/dnn/test/test_onnx_importer.cpp
This PR resolves the issue #24883 related in Einsum layer inner product operation with 1D vectors. 
> Einsum Layer Inner Product Issue Solution 

- modules/objdetect/src/aruco/aruco_board.cpp
- modules/objdetect/test/test_charucodetection.cpp
Fixes https://github.com/opencv/opencv/issues/24806
The problem was only if the size of the image is not completely divided by the size of the square of the chessboard.
Now the corners of the chessboard are generated as closely as possible with the values of getChessboardCorners(), and now the error (between chessboard corners) is no more than 0.5 pixels.
Before fix:
After fix:
There are still some problems with ArUco markers.
> Fix generateImage for charuco chessboard

- modules/core/include/opencv2/core.hpp
- modules/core/include/opencv2/core/ocl.hpp
- modules/core/include/opencv2/core/opencl/opencl_info.hpp
- modules/core/perf/opencl/perf_matop.cpp
- modules/core/src/convert.dispatch.cpp
- modules/core/src/ocl.cpp
- modules/core/src/ocl_disabled.impl.hpp
- modules/core/src/opencl/convert.cl
- modules/core/src/umatrix.cpp
relates #24909
relates #24917
relates #24892
Performance changes:
|Name of Test|noOCL|convertFp16|convertTo BASE|convertTo PATCH|
|---|:-:|:-:|:-:|:-:|
|ConvertFP16FP32MatMat::OCL_Core|3.130|3.152|3.127|3.136|
|ConvertFP16FP32MatUMat::OCL_Core|3.030|3.996|3.007|2.671|
|ConvertFP16FP32UMatMat::OCL_Core|3.010|3.101|3.056|2.854|
|ConvertFP16FP32UMatUMat::OCL_Core|3.016|3.298|2.072|2.061|
|ConvertFP32FP16MatMat::OCL_Core|2.697|2.652|2.723|2.721|
|ConvertFP32FP16MatUMat::OCL_Core|2.752|4.268|2.662|2.947|
|ConvertFP32FP16UMatMat::OCL_Core|2.706|2.601|2.603|2.528|
|ConvertFP32FP16UMatUMat::OCL_Core|2.704|3.215|1.999|1.988|
Patched version is not worse than convertFp16 and convertTo baseline (except MatUMat 32->16, baseline uses CPU code+dst buffer map).
There are still gaps against noOpenCL(CPU …
> core(OpenCL): optimize convertTo() with CV_16F (convertFp16() replacement)

- modules/core/include/opencv2/core/hal/intrin_rvv071.hpp
In 0.7.1 RVV implementation multiplication had performed unnecessary operations unpacking and then packing values back again. Removed this part. Performance on LicheePi 4A with Xuantie 2.8.0 toolchain have increased 5.82 ms -> 1.06 ms (1920x1080 / CV_8UC1 - BinaryOpTest.multiply/20). Accuracy tests for core and imgproc pass with the same failures as before the fix.
```.cpp
vuint16m2_t res = vwmulu_vv_u16m2(a, b, 16);
// following calls are not needed - they unpack values and pack them back again
vuint16m1_t c = vget_v_u16m2_u16m1(res, 0);
vuint16m1_t d = vget_v_u16m2_u16m1(res, 1);
vuint16m2_t im = vundefined_u16m2();
im = vset_v_u16m1_u16m2(im, 0, c);
im = vset_v_u16m1_u16m2(im, 1, d);
// emd - we can pass 'res' directly to 'vnclipu'
vuint8m1_t fin = vnclipu_wx_u8m1(im, 0, 16);
``` …
> RISC-V: fix mul 8/16 bit for RVV 0.7

- modules/core/include/opencv2/core/hal/intrin_rvv071.hpp
Fixes performance of `convertTo` with multiplication on RISC-V RVV 0.7.1 (tested on LicheePi 4A with Xuantie 2.8.0 toolchain):
* use `madd/fmadd` (a = a * b + c) instead of `macc/fmacc` (c = a * b + c) - it helps to use v-registers efficiently
* modified `v_load/v_store` - for some reason 8-bit load/store instructions were used - avoid type transformations and extra instructions being added
Some tests slowed down (up to 5 times), but about a quarter of  core tests improved performance up to 10 times. Similar picture with imgproc, but about a half of tests improved up to 6 times. I'm going to improve other `v_load` intrinsics and investigate ways to fix slowed cases.
> RISC-V: fix scale64f performance for RVV 0.7

- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/src/loadsave.cpp
- modules/imgcodecs/test/test_grfmt.cpp
Replacement for https://github.com/opencv/opencv/pull/24800
> Do not release user-provided buffer, if image decoder failed

- modules/core/include/opencv2/core/types.hpp
- modules/python/src2/cv2_convert.cpp
- modules/python/src2/cv2_convert.hpp
- modules/python/src2/typing_stubs_generation/predefined_types.py
- modules/python/test/test_misc.py
Replaces https://github.com/opencv/opencv/pull/24857/
Point3i is not used in OpenCV API
Type hints are already there for both types
> Add python bindings for Rect2f and Point3i

- modules/objdetect/test/test_charucodetection.cpp
Fixes warning produced by default Android NDK compiler:
```
modules/objdetect/test/test_charucodetection.cpp:817:19: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
```
> Build warning fix for Charuco tests

- samples/android/tutorial-4-opencl/gradle/AndroidManifest.xml
Fixes warnings:
```
2024-01-31T09:16:51.4631930Z /Users/xperience/GHA-Actions-OpenCV/_work/opencv/opencv/opencv/samples/android/tutorial-4-opencl/gradle/AndroidManifest.xml:7:5-9:41 Warning:
2024-01-31T09:16:51.4632620Z 	uses-sdk:minSdkVersion value (14) specified in the manifest file is ignored. It is overridden by the value declared in the DSL or the variant API, or 1 if not declared/present. Current value is (21).
2024-01-31T09:16:51.4633130Z /Users/xperience/GHA-Actions-OpenCV/_work/opencv/opencv/opencv/samples/android/tutorial-4-opencl/gradle/AndroidManifest.xml:7:5-9:41 Warning:
2024-01-31T09:16:51.4633810Z 	uses-sdk:targetSdkVersion value (21) specified in the manifest file is ignored. It is overridden by the value declared in the DSL or the variant API, or 1 if not …
```
> Build warning fix in Tutorial4-OpenCL.

- CMakeLists.txt
Mainly to solve the problems caused by the PR of opencv_contrib: https://github.com/opencv/opencv_contrib/pull/3630
> Add CMake policy CMP0071 for AUTOMOC and AUTOUIC

- modules/core/include/opencv2/core/utils/plugin_loader.private.hpp
- modules/core/src/utils/filesystem.cpp
We are building OpenCV with Emscripten to include with Pyodide and we need this patch to enable the file system.
```
```
> Enable file system on Emscripten

- modules/dnn/perf/perf_net.cpp
Proto and weights files are swapped in some tests. 
The fixed tests are marked with large memory tag and are not covered by buildbot
Need to force OPENCV_TEST_REQUIRE_DATA in CI: https://github.com/opencv/ci-gha-workflow/pull/133
> Fix proto and weights mess in dnn performance tests

- modules/calib3d/src/usac/utils.cpp
> bug fix infinite loop

- modules/imgcodecs/test/test_tiff.cpp
Refactoring to use perf:MatType instead of redefined enum.
> imgcodecs: refix test for 23416 to use perf::MatType

- modules/ts/src/ts_func.cpp
Extended getTypeName() to support new types.
Close https://github.com/opencv/opencv/issues/24991
> ts: Extended getTypeName() to support new types

- modules/calib3d/src/calibinit.cpp
In some cases quadrangles can be separated already on first binary images and dilation is not needed on first iteration.
Following example was received on 3.2.0 code version with some modern patches. This is a histogram based binarization (first (new) part of algorithm).
> Do not dilate binary images on first iteration in findChessboardCorners

- modules/dnn/test/test_backends.cpp
Previous iteration with OpenCL: https://github.com/opencv/opencv/pull/24899
Related CI test failure: https://github.com/opencv/opencv/actions/runs/7869342400/job/21469344280?pr=24992
> Relax test requirements for CUDA in DNNTestNetwork.FastNeuraStyle_eccv16

- platforms/android/build_sdk.py
When building OpenCV for Android using `build_sdk.py` script it doesn't build tests not for even a single configuration.
The reason is in the wrong way the CMake variables are passed from the script to the command line args.
This PR fixes the problem replacing erroneous `append` calls.
> Fix for Android build script: CMake vars

- modules/objdetect/src/qrcode.cpp
- modules/objdetect/test/test_qrcode.cpp
Fixes https://github.com/opencv/opencv/issues/24679
Related PR for extra: https://github.com/opencv/opencv_extra/pull/1133
Alternative to https://github.com/opencv/opencv/pull/24758/
No regressions in QR code benchmark
> Alternative solution for QR code black/white balance computation

- modules/core/src/out.cpp
> Fixed possible out-of-bound access in cv::Mat output formatter

- modules/flann/include/opencv2/flann/dist.h
`/****` is `EF BB BF 2F 2A 2A 2A 2A` instead of `2F 2A 2A 2A 2A`.
> Remove 3 hidden leading chars in flann/dist.h

- modules/calib3d/src/calibinit.cpp
Should be merged after #24710
Idea was mentioned in `Section III-C. Adaptive Quadrangle Linking Distance` of `Rufli, Martin & Scaramuzza, Davide & Siegwart, Roland. (2008). Automatic Detection of Checkerboards on Blurred and Distorted Images. 2008 IEEE/RSJ International Conference on Intelligent Robots and Systems, IROS. 3121-3126. 10.1109/IROS.2008.4650703` (https://rpg.ifi.uzh.ch/docs/IROS08_scaramuzza_b.pdf):
```
As mentioned in Section II­A.5, quadrangles only get linked if their corners are less than a certain distance apart. In the original implementation, inaccurately, the shortest edge length of the two involved quadrangles was chosen for this distance limit. If the checkers are large w.r.t erosion, the error introduced is small. But for low resolution images, erosion has a large …
```
> Compensate edge length in ChessBoardDetector::generateQuads

- modules/calib3d/src/calibinit.cpp
Have to revert https://github.com/opencv/opencv/pull/24833 because it breaks existing tests. The original patch is treated as useful, but need to debug test failure and find correlation with other patches.
> Reverted Compensate edge length in ChessBoardDetector::generateQuads #24833

- modules/objdetect/src/qrcode.cpp
- modules/objdetect/test/test_qrcode.cpp
This PR fixes #22892, #24011 and #24450 and adds regression tests using the images provided. I've also verified with the [benchmark](https://github.com/opencv/opencv_benchmarks/tree/develop/python_benchmarks/qr_codes) that this doesn't break anything there.
resolves #22892
resolves #24011
resolves #24450
Replaces https://github.com/opencv/opencv/pull/23802
Requires extra: https://github.com/opencv/opencv_extra/pull/1148
> Fix qrcode bugs

- modules/stitching/include/opencv2/stitching/detail/warpers.hpp
- modules/stitching/include/opencv2/stitching/warpers.hpp
- modules/stitching/src/warpers.cpp
Patch to opencv_extra has the same branch name.~~
In my [PR](https://github.com/opencv/opencv/commit/d31b6c3480c601305fa1e153a819aad0bd247fe2) regarding `warpPointBackward`, I was asked by alalek to [add a bypass](https://github.com/opencv/opencv/pull/18607/files#r508423486) to python wrapper class, presumably to ship the changes in the newest patch release (4.5.1).
The bypass was not removed in 4.6.0 release, so please remove it in either 4.10.0 or 4.11.0. Thanks!
> remove bypass for ABI check in warpPointBackward

- modules/objdetect/perf/perf_barcode.cpp
- modules/objdetect/src/barcode.cpp
- modules/objdetect/test/test_barcode.cpp
The method `detectAndDecode()` in the `BarcodeDetector` class doesn't return the barcode corners.
This PR fixes the and add test for `detectAndDecode`.
> Fix barcode detectAndDecode

- modules/calib3d/src/fisheye.cpp
- modules/calib3d/test/test_fisheye.cpp
For the initialization of intrinsics for fisheye camera models, the assumption of the field of view is too drastic:  on the corner of the image, the calculated field of view would be larger than 180 degrees, which will cause numerical problems.
Discussion: https://github.com/opencv/opencv/issues/23962
> Changed initial estimation for F in fisheye calibration

- modules/calib3d/include/opencv2/calib3d.hpp
- modules/calib3d/misc/objc/gen_dict.json
- modules/calib3d/src/fisheye.cpp
- modules/calib3d/test/test_fisheye.cpp
**Warning:** The patch changes Obj-C generator behaviour and adds "fisheye_" prefix for all ObjC functions from namespace.
> solvePnP implementation for Fisheye camera model

- modules/objdetect/include/opencv2/objdetect.hpp
- modules/objdetect/src/qrcode.cpp
Minor fix
fixed `setArucoParameters()`, added const ref to `getArucoParameters()` in QRCodeDetectorAruco
> fix setArucoParameters in QRCodeDetectorAruco, add const to getArucoParameters 

- cmake/checks/cpu_neon.cpp
- modules/core/include/opencv2/core/cv_cpu_dispatch.h
- modules/core/include/opencv2/core/fast_math.hpp
- modules/core/src/system.cpp
- modules/flann/include/opencv2/flann/dist.h
Even ACLE 1.1 referes to __ARM_NEON
https://developer.arm.com/documentation/ihi0053/b/?lang=en
> Replace legacy __ARM_NEON__ by __ARM_NEON

- doc/DoxygenLayout.xml
relates #25047 part 1
Test page:
- http://pullrequest.opencv.org/buildbot/export/pr/25048/docs/d9/d0c/group__calib3d.html
```
```
> docs: move detail section of group to the top of the page

- modules/dnn/src/layers/eltwise_layer.cpp
- modules/dnn/test/test_layers.cpp
This PR is designed to add tests for 1D inputs for layer, which is required after introducing 1d support in 5.x. Currently tests are written for following layers: 
This list is to be extended for more layer such `gemm`, `conv` etc.
> Primitive 1D Tests

- platforms/android/aar-template/OpenCV/build.gradle.template
- platforms/android/aar-template/build.gradle
Added Kotlin classes to AAR
The resulting maven repo doesn't have kotlin-plugin dependency, and it works fine out of the box: Android Kotlin projects already have kotlin-plugin dependency, Android Java projects ignore kotlin classes.
Details on KGP versions: https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin
> Added kotlin classes to AAR

- cmake/android/android_gradle_projects.cmake
Removed hack introduced in https://github.com/opencv/opencv/pull/24752
The released AAR for 4.9.0 contains prefab part. The proposed hack is not relevant any more.
> Enable Android samples with native part with AAR package

- modules/videoio/include/opencv2/videoio.hpp
--------------------
Hi,
I stumbled over this function declaration.
I think a const declaration was just forgotten here.
This MR just adds it. 
It is in theory a interface change, but it does not break backward compatibility, does not restrict the usage of it. It just enhances the possibilities, where the funtion can be called (with `const VideoCapture&`)
Greetings
> Adds missing const in function declaration of VideoCapture

- modules/gapi/test/cpu/gapi_ocv_stateful_kernel_tests.cpp
- modules/gapi/test/streaming/gapi_streaming_tests.cpp
- modules/gapi/test/streaming/gapi_streaming_utils_test.cpp
G-API tests look running longer than tests for the rest of modules (e.g., 5m), and the analysis show that there's several outliers in G-API test suite which take a lot of time but don't improve the testing quality much:
In this PR I will cut the execution time to something reasonable.
- Marked some outliers as `verylong`:
- OneVPL barrier test - pure brute force
- Stateful test in stream - in fact BG Sub accuracy test clone
- Restructured parameters instantiation in Streaming tests to generate less test configurations (54 -> 36)
> G-API: Make test execution lighter (first attempt)

- modules/calib3d/include/opencv2/calib3d.hpp
Fixing the formula in the documentation of reprojectImageTo3D
fixes #25082
The documentation states correctly:
> Reprojects a disparity image to 3D space.
and
> The function transforms a single-channel disparity map to a 3-channel image representing a 3D surface. That is, for each pixel (x,y) and the corresponding disparity d=disparity(x,y) , it computes:
But then there is an error in the formula:
This does not make sense since the function wants to calculate $Z$, it makes no sense to have $z$ on the right side of the equation. It does not have any meaning in a disparity image. The value should be one at that coordinate, to reflect that this is a normalized homogenous coordinate in 3 dimensions.
I fixed it to 
which corresponds to the implementation which is (click permalink to get to …
> Fixing the formula in the documentation of reprojectImageTo3D

- modules/js/src/helpers.js
- platforms/js/build_js.py
I was following [this tutorial](https://docs.opencv.org/4.9.0/d4/da1/tutorial_js_setup.html) for building opencv with wasm target. The tutorial mentions that the last verified version of emscripten that is tested with opencv is 2.0.10, but I was curious if I could get it to work with more recent versions. I've run into a few issues with the latest version, for which fixes are included in this PR. I've found a few issues that have the same problems I encountered:
- https://github.com/opencv/opencv/issues/24620
- https://github.com/opencv/opencv/issues/20313
- https://stackoverflow.com/questions/77469603/custom-opencv-js-wasm-using-cv-matfromarray- …
> Add compatibility with latest (3.1.54) emsdk version

- modules/calib3d/src/calibinit.cpp
- modules/calib3d/test/test_cameracalibration.cpp
New attempt for #24833, which was reverted as #25036.
Locally I fixed `Calib3d_StereoCalibrate_CPP.regression` test by corners refinement using `cornerSubPix` function
> Compensate edge length in ChessBoardDetector::generateQuads (attempt 2)

- modules/python/package/cv2/__init__.py
resulting in an error in the judgment condition]
fixes #25078
relates #20611
> fix [use hasattr("cv2", "name") ,but first param is 'character string',

- 3rdparty/tbb/CMakeLists.txt
upgrade tbb from version 2020.0 to 2021.11.0
> upgrade tbb to version 2021.11.0

- modules/calib3d/include/opencv2/calib3d.hpp
Backport https://github.com/opencv/opencv/pull/25083 fix into 3.4 branch.
> Fix mistake into the reprojectImageTo3D doc. Backport from #25083 PR.

- modules/calib3d/src/calibration.cpp
- modules/calib3d/test/test_decompose_projection.cpp
The point of the Givens rotations here is to iteratively set the lower left matrix entries to zero. If an element is zero already, we don't need to do anything. This resolves #24330.
> Handle degenerate cases in RQDecomp3x3

- modules/objdetect/src/face_detect.cpp
Like mentioned in the issue #25056 , I think checking the condition with `scoreThreshold` and then assigning the bounding boxes can optimize the function pretty well. By doing this, we prevent allocating boxes to faces with scores below the threshold. It also reduces the amount of data that needs to be processed during the subsequent NMS step. Builds and passed locally.
> Fixes #25056 : Optimising postProcess(const std::vector<Mat>& output_blobs)

- 3rdparty/tbb/CMakeLists.txt
The issue introduced in https://github.com/opencv/opencv/pull/25098
> Fixed lcense and readme filenames after TBB update

- cmake/checks/cpu_fp16.cpp
Relates to https://github.com/opencv/opencv/issues/25052
> Disable fp16 instructions detection on Windows ARM64 because of build issues

- modules/dnn/src/layers/attention_layer.cpp
- modules/dnn/src/onnx/onnx_importer.cpp
Checklist:
Performance:
Performance test case is `Layer_Attention.VisionTransformer/0`, which has input of shape {1, 197, 768}, weight of shape {768, 2304} and bias {2304}.
Data is in millisecond.
| | macOS 14.2.1, Apple M1 | Ubuntu 22.04.2, Intel i7 12700K |
| - | - | - |
| Current | 10.96 | 1.58 |
| w/ Mat | 6.27 | 1.41 |
| w/ Internals | 5.87 | 1.38 |
| w/ fastGemmBatch | 6.12 | 2.14 |
> dnn: try improving performance of Attention layer

- modules/dnn/test/test_layers.cpp
This PR introduces 1D parametrized test for `scale` layer
> Scale layer 1d test

- modules/3d/include/opencv2/3d.hpp
- modules/3d/misc/python/test/test_octree.py
- modules/3d/src/octree.cpp
- modules/3d/src/octree.hpp
- modules/3d/src/pcc.h
- modules/3d/src/precomp.hpp
- modules/3d/test/test_octree.cpp
[Issue for GSoC 2023](https://github.com/opencv/opencv/issues/23624)
* We are **updating the Octree method create() by using OctreeKey**: Through voxelization, directly calculate the leaf nodes that the point cloud belongs to, and omit the judgment whether the point cloud is in the range when inserted. The index of the child node is calculated by bit operation.
* We are also **introducing a new header file pcc.h (Point Cloud Compression) with API framework**.
* We added tests for restoring point clouds from an octree.
* Currently, the features related to octree creation and point cloud compression are part of the internal API, which means they are not directly accessible to users. However, our plan for the future is to **include only the 'PointCloudCompression' class in the …
> [GSoC] Update octree methods and create frames for PCC

- modules/highgui/src/window_wayland.cpp
- modules/imgproc/src/approx.cpp
- modules/imgproc/src/contours.cpp
- modules/imgproc/src/distransform.cpp
- modules/imgproc/src/drawing.cpp
- modules/imgproc/src/emd.cpp
- modules/imgproc/src/histogram.cpp
- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/src/thresh.cpp
- modules/imgproc/test/test_convhull.cpp
- modules/imgproc/test/test_drawing.cpp
- modules/imgproc/test/test_imgwarp.cpp
- modules/imgproc/test/test_thresh.cpp
Related to https://github.com/opencv/opencv/pull/22754
> Partially backport C API removal in imgproc module to reduce conflicts with 5.x

- modules/photo/perf/perf_inpaint.cpp
- modules/photo/src/inpaint.cpp
In `cv::inpaint` implementation, it uses a priority queue with O(n) time linear search. For large images it is very slow.
I replaced it with C++'s standard library `std::priority_queue`, that uses O(log(n)) algorithm.
In my use case, it is x10 faster than the original.
> Use std::priority_queue in inpaint function for performance improvement

- modules/dnn/src/layers/reduce_layer.cpp
- modules/dnn/test/test_layers.cpp
https://github.com/microsoft/onnxruntime/blob/a93c31e3c9971063d8dfe45a627a80cbdcf99ed9/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc#L433-L443
> Fixed ReduceMean layer behaviour

- modules/core/include/opencv2/core/hal/intrin_neon.hpp
I see couple of warnings appear when building with Visual Studio + ARM64.
The full log is uploaded [here](https://gist.github.com/tomoaki0705/a0c690cd0747e1b63880998c5325460b)
Mainly they are from `carotene` module, so it's not really important, but I'd like to suppress them.
Most of them are implicit conversion from `double` to `float`, so I made them explicitly.
- summary
```
$ grep -i ' warning' log.txt  | sort | uniq -c
1 C:\opencv\cross_build\carotene\tegra_hal.hpp(1030,1): warning C4244: 'argument': conversion from 'const double' to 'carotene_o4t::f32', possible loss of data
48 C:\opencv\modules\core\include\opencv2\core\hal\intrin_neon.hpp(1646,12): warning C4244: 'return': conversion from 'uint64_t' to 'int', possible loss of data
1 …
```
> build: suppress warning ARM64 + Visual Studio build

- modules/dnn/src/layer.cpp
- modules/dnn/src/layers/permute_layer.cpp
- modules/dnn/src/layers/reorg_layer.cpp
- modules/dnn/src/layers/reshape_layer.cpp
- modules/dnn/src/layers/slice_layer.cpp
In Win64, 5.x branch makes build errors.
```
for ( auto input : inputs )
if ( cond1 )
statementA;
else if (cond2)
statementB;
else
statementC;
```
We expects `input` is available at stetementA, statementB and statementC.
However 'input' was undeclared identifier at statementB and statementC with Win64 build .
For fixing it, this patch adds `{ }` .
> dnn: fix to iteration variable scope

- doc/tutorials/others/_old/table_of_content_objdetect.markdown
- modules/gapi/doc/00-root.markdown
There are two files with same id after adding Aruco tutorials - old stub file and new one. We can remove old stub file now.
Related warning: `/opencv/doc/tutorials/others/_old/table_of_content_objdetect.markdown:1: warning: An automatically generated id already has the name 'tutorial_table_of_content_objdetect'!`
```
force_builders_only=docs-js
buildworker:Docs=linux-4
```
> doc: removed duplicated markdown file

- modules/dnn/src/onnx/onnx_importer.cpp
Initializing `graph` by value creates a copy of entire model. Use a pointer instead.
`readNet` top resident memory on `vit_b_32.onnx` (339MB file):
| 4.x | PR |
|---|---|
| 723MB | 375MB |
> Avoid copy of ONNX graph during import

- modules/calib3d/src/calibinit.cpp
Firstly, there were bugs/problems:
1) we always approximated contour at least once even if it was originally quadrangle
2) we broke loop only if `approx_contour.size() == 4`, which was wrong, `approx_contour.size() <= 4` - is correct
Secondly, approximation can be sped up. Before we approximated source contour twice on each loop iteration. But we can approximate source contour sequentially (on current iteration approximate output from previous iteration). The previous idea that for getting quadrangle we may need several approximations of source contour is taken into account here. And it will be much faster - because current countour size will decrease quite quickly with iterations.
I tested this PR (on `3.2.0` code version with some modern patches) on two private datasets and it sped up …
> Improve contours approximations in ChessBoardDetector::generateQuads

- modules/core/src/ocl.cpp
- modules/dnn/include/opencv2/dnn/all_layers.hpp
- modules/dnn/src/init.cpp
- modules/dnn/src/layers/cast_layer.cpp
- modules/dnn/src/layers/expand_layer.cpp
- modules/dnn/src/layers/gather_elements_layer.cpp
- modules/dnn/src/layers/gather_layer.cpp
- modules/dnn/src/layers/permute_layer.cpp
- modules/dnn/src/onnx/onnx_graph_simplifier.cpp
- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_int.cpp
- modules/dnn/test/test_misc.cpp
- modules/dnn/test/test_onnx_importer.cpp
**Modified ONNX parser:**
- Removed automatic int64 to int32 conversion in ONNX parser when reading blobs.
- Added int64 to int32 conversion only for layer arguments (axis, dims, etc.) in ONNX parser.
**Modified layers:**
- Added Cast layer
- Added any type support for Permute layer
- Fixed list of supported types for Gather layer
- Fixed list of supported types for Expand layer
**Enabled Tests:**
- Enabled RAFT test
Fixes https://github.com/opencv/opencv/issues/25102
```
```
> Allowed int64 constants in ONNX parser

- CMakeLists.txt
- doc/CMakeLists.txt
- doc/mymath.js
- modules/java/jar/build.xml.in
Restored variable defining MathJax path.
https://github.com/opencv/opencv/pull/25042/files#r1515290130
```
```
> doc: fix formulas in JavaDoc broken after Doxygen upgrade

- doc/CMakeLists.txt
Port of #25171
Fixes documentation issue on BuildBot CI:
```
warning: ignoring \dot command because HAVE_DOT is not set
...
```
> doc: auto-enabling DOT support (5.x)

- modules/dnn/src/cuda/permute.cu
- modules/dnn/src/cuda/slice.cu
- modules/dnn/src/layers/flatten_layer.cpp
- modules/dnn/src/layers/permute_layer.cpp
- modules/dnn/src/layers/reshape_layer.cpp
- modules/dnn/src/layers/slice_layer.cpp
- modules/dnn/test/test_int.cpp
Added int32 and int64 support to several dnn layers:
- Added int support to CPU version of **flatten** layer
- Added int support to CUDA versions of **flatten**, **permute**, **reshape** and **slice** layers
- Added int values tests for **flatten**, **permute**, **reshape** and **slice** layers
> Added int support to flatten, permute, reshape, slice layers

- modules/dnn/test/test_layers_1d.cpp
This PR introduces parametrized `0/1D` input support test for `Reshape` layer.
> 0D test for Reshape layer 

- modules/dnn/src/layers/convolution_layer.cpp
- modules/dnn/test/test_common.hpp
- modules/dnn/test/test_common.impl.hpp
- modules/dnn/test/test_onnx_importer.cpp
related (but not resolved): https://github.com/opencv/opencv/issues/24134
Minor memory footprint improvement. Also, adds a test for VmHWM.
RAM top memory usage (-230MB)
| YOLOv3 (237MB file) |   4.x   |    PR   |
|---------------------|---------|---------|
| no winograd         | 808 MB  | 581 MB  |
| winograd            | 1985 MB | 1750 MB |
> Release convolution weightsMat after usage

- doc/tutorial-utils.js
related #25042
Top level headers are `h1` in the new documentation, while in old we had `h2`. I decided to stick language toggle buttons to `h1` elements and omit more complex lower-level header matching, because in some tutorials hidden blocks contain headers too, which can cause matching issues.
```
```
> doc: fix toggle buttons in some tutorials

- modules/dnn/src/layers/gemm_layer.cpp
Gemm layer was refactored some time ago. Users found that the mobilenet example in https://github.com/opencv/opencv/wiki/Huawei-CANN-Backend does not work because of incorrect shape set for 1d bias in Gemm. This PR resolves this issue.
> dnn (CANN): Fix incorrect shape of 1d bias in Gemm

- modules/dnn/src/layers/cpu_kernels/convolution.cpp
Just an experiment to avoid extra usage of `memset`.
> Avoid extra memset

- modules/dnn/src/layers/max_unpooling_layer.cpp
- modules/dnn/src/layers/scatterND_layer.cpp
- modules/dnn/src/layers/scatter_layer.cpp
Added int64 values support to scatter, scatterND and maxunpool layers
The existing tests cover cases only with int indices and float values.
ONNX tests with int indices and int values will be added later in a separate PR.
> Added int64 values support to scatter, scatterND and maxunpool layers

- modules/dnn/src/layers/reduce_layer.cpp
- modules/dnn/src/layers/tile_layer.cpp
Allowed any Mat type in Tile layer.
Allowed int64 type in Reduce layer.
ONNX tests with int32 and int64 inputs will be added later in a separate PR
> Allowed int types in Tile and Reduce layers

- modules/dnn/test/test_layers_1d.cpp
This PR introduces parametrized `0/1D` input support test for `Split` layer.
> 0D test for split layer

- modules/core/include/opencv2/core/hal/hal.hpp
- modules/core/src/hal_replacement.hpp
- modules/core/src/mathfuncs.cpp
- modules/core/src/mathfuncs_core.dispatch.cpp
- modules/core/src/mathfuncs_core.simd.hpp
- modules/core/src/opencl/arithm.cl
- modules/core/test/test_arithm.cpp
- a fused hal::cartToPolar[32|64]f() is used instead of sequential hal::magnitude[32|64]f/hal::fastAtan[32|64]f
- ipp_polarToCart is skipped for in-place processing (it seems not to support it correctly)
relates to #24891
> added in-place support for cartToPolar and polarToCart

- modules/calib3d/src/circlesgrid.cpp
- modules/calib3d/src/circlesgrid.hpp
- modules/calib3d/test/test_chesscorners.cpp
Merge with https://github.com/opencv/opencv_extra/pull/1157
Fixes https://github.com/opencv/opencv/issues/24964
This PR fixes `isDetectionCorrect()` in `findCirclesGrid()` for SYMMETRIC_GRID.
To `isDetectionCorrect()` added check rotation of the grid and bool flag `rotatedGrid`. if `rotatedGrid` is true, `getHoles()` transpose the circle grid before return.
Detect pattern with Size(7, 6):
Detect pattern with Size(6, 7):
Tests in [benchmark](https://github.com/opencv/opencv_benchmarks/tree/develop/python_benchmarks/objdetect_benchmark
) with params `--configuration=generate_run --board_x=7 --board_y=6 --path=res_circle --synthetic_object=circle_sym_grid`:
before fix:
after fix:
Patch to …
> Fix detect rotated SYMMETRIC_GRID

- modules/imgproc/src/shapedescr.cpp
- modules/imgproc/test/test_boundingrect.cpp
Fix #24217 
Issue bug is reproduced when for filled row `offset == size.width`
We fully processed this row only in one loop and didn't go to branch `offset < size.width`
Problem was in that we were breaking out of loop after first non-zero value and thus couldn't update properly `xmax` value
> Fix bug in maskBoundingRect

- modules/videoio/src/cap_avfoundation.mm
- platforms/ios/Info.Dynamic.plist.in
A couple of small fixes:
1. remove visionos 1 from @available list as it is behind #if TARGET_OS_VISION check and 1 is the base version.
2. use IPHONEOS_DEPLOYMENT_TARGET env var to generate info.plist for dynamic library with correct properties.
> ios build fixes

- modules/calib3d/src/calibration.cpp
- modules/calib3d/test/test_decompose_projection.cpp
Fix #23733
It is checked before that `|s| > DBL_EPSILON` (if not, then `s` will be equal to `0`, but `c` will be equal to `1`, then `z` will be equal to `1` and there will be no any problems with small values), so `sqrt(c^2 + s^2) >= |s| > DBL_EPSILON` and thus small values are already taken into account before and there is no need to add `DBL_EPSILON` to `c^2 + s^2` (and I think adding `DBL_EPSILON^2` instead of `DBL_EPSILON` would be more correct).
I ran `Python` script from issue.
`NumPy` and `SciPy` results
```
*Numpy*
P (case 1): 
[[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]]
Numpy, R.T @ R - I: 
[[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]]
Numpy scaled 1e-6, R.T @ R - I: 
[[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]]
P (case 2): 
[[52. -7.  4. 12.]
[-6. 49. 12.  8.]
[ 4. 17.  1.  0.]]
Numpy, R.T @ R - I: …
```
> Increase decomposeProjectionMatrix precision for small scales

- platforms/android/build_sdk.py
Adding --disable flag to android sdk build script. The flag allows to exclude components from build by concatting -DWITH_XXX cmake flag to the build command. Example : --disable OPENEXR (uppercase).
> add component disable flag to android build

- modules/calib3d/src/calibinit.cpp
If `block_size` hasn't been changed between iterations for same `k`, then all `adaptiveThreshold` arguments will be same and we can reuse result from previous iteration.
I tested this PR with benchmark
```
python3 objdetect_benchmark.py --configuration=generate_run --board_x=7 --path=res_chessboard --synthetic_object=chessboard
```
PR speed up chessboards detection by `7.5/17%` without any changes in detected chessboards number:
```
cell_img_size = 100 (default)
before
category  detected chessboard  total detected chessboard  total chessboard  average detected error chessboard
all             0.904167                      13020             14400                           0.600512
Total detected time:  107.27875600000003 sec
after
category  detected chessboard  total detected chessboard …
```
> Speed up adaptive threshold in findChessboardCorners

- modules/calib3d/test/test_fisheye.cpp
JPEG is decoded differently with different libjpeg versions.
Required for https://github.com/opencv/opencv/pull/25092
OpenCV Extra: https://github.com/opencv/opencv_extra/pull/1162
> Added PNG instance of image for fisheye::undistort test

- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/src/grfmt_tiff.cpp
- modules/imgcodecs/test/test_tiff.cpp
Normaly, we set IMWRITE_* flags for imwrite() params. But imgcodecs expects to use some TIFFTAG_* directory. This patch introduce IMWRITE_TIFF_ROWSPERSTRIP and IMWRITE_TIFF_PREDICTOR instead of TIFFTAG_*.
> imgcodecs: tiff: to avoid using TIFFTAG_* directly for imwrite() params.

- modules/dnn/src/layers/einsum_layer.cpp
- modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
- modules/dnn/test/test_onnx_importer.cpp
On skipped tests:
```
[ RUN      ] Test_ONNX_layers.Einsum_2D_Ellipses/0, where GetParam() = NGRAPH/CPU
C++ exception with description "Check 'input_rank >= labels.size()' failed at src/core/shape_inference/include/einsum_shape_inference.hpp:41:
While validating node 'opset7::Einsum Einsum_2190 (0.0[0]:f32[4,5], 1.1[0]:f32[5,8]) -> (dynamic[...])' with friendly_name 'Einsum_2190':
Input rank must be greater or equal to a number of labels in the corresponding input subscript.
[  FAILED  ] Test_ONNX_layers.Einsum_2D_Ellipses/0, where GetParam() = NGRAPH/CPU (0 ms)
```
```
[ RUN      ] Test_ONNX_layers.Einsum_Batch_Diagonal/0, where GetParam() = NGRAPH/CPU
C++ exception with description "OpenCV(4.9.0-dev) …
```
> Einsum OpenVINO backend

- modules/gapi/test/infer/gapi_infer_ie_test.cpp
Workaround for https://github.com/opencv/opencv/issues/25053
> Skip InferROI.TestStreamingInfer as unstable as it hangs on CI time-to-time

- modules/imgcodecs/src/grfmt_jpeg.cpp
- modules/imgcodecs/test/test_jpeg.cpp
Close #25274 
OpenCV Extra: https://github.com/opencv/opencv_extra/pull/1163
> imgcodecs: jpeg: re-support to read CMYK Jpeg

- modules/core/src/parallel.cpp
The parallel code works out how many CPUs are on the system by checking the quota it has been assigned in the Linux cgroup. The existing code works under cgroups v1 but the file structure changed in cgroups v2. From [1]:
"cpu.cfs_quota_us" and "cpu.cfs_period_us" are replaced by "cpu.max"
which contains both quota and period.
This commit add support to parallel so it will read from the cgroups v2 location. v1 support is still retained.
Resolves #25284
[1] https://github.com/torvalds/linux/commit/0d5936344f30aba0f6ddb92b030cb6a05168efe6
> core: Add cgroupsv2 support to parallel.cpp

- modules/imgcodecs/test/test_jpeg.cpp
Comparing condition for rgb- and cmyk-jpeg is incorrect. When `norm()` returns less than 3, this may make false-positive error.
> imgcodecs: jpeg: (test) fix condition to compare rgb and cmyk jpeg

- modules/dnn/CMakeLists.txt
- modules/dnn/src/int8layers/convolution_layer.cpp
- modules/dnn/src/int8layers/fully_connected_layer.cpp
- modules/dnn/src/int8layers/layers_common.simd.hpp
This patch optimize 3 functions in the int8 layer by using RVV Native Intrinsic.
This patch was tested on QEMU using VLEN=128 and VLEN=256 on `./bin/opencv_test_dnn --gtest_filter="*Int8*"`;
On the real device (k230, VLEN=128), `EfficientDet_int8` in `opencv_perf_dnn` showed a performance improvement of 1.46x.
| Name of Test                               |  Original | optimized | Speed-up |
| ------------------------------------------ | -------- | ------------ | -------- |
| EfficientDet_int8::DNNTestNetwork::OCV/CPU | 2843.467 | 1947.013     | 1.46     |
> Optimize int8 layers in DNN modules by using RISC-V Vector intrinsic.

- modules/calib3d/src/calibinit.cpp
Idea is to make quad neighbors finding more simple (for understanding and debugging) and deterministic
And for that use initial quads corners, now they can be updated in
https://github.com/opencv/opencv/blob/4.x/modules/calib3d/src/calibinit.cpp#L1740
and then affect following finding, e.g. in
https://github.com/opencv/opencv/blob/4.x/modules/calib3d/src/calibinit.cpp#L1698
Before #24605 we also could use updated corners in nearest neighbors, but now we use k-d tree for it with copy of initial corners and what we use updated corners in following part of algorithm can be considered as something like logic divergence
I tested this PR with benchmark
```
python3 objdetect_benchmark.py --configuration=generate_run --board_x=7 --path=res_chessboard --synthetic_object=chessboard
```
There are no …
> Use initial quads corners in ChessBoardDetector::findQuadNeighbors

- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_onnx_importer.cpp
Resolves https://github.com/opencv/opencv/issues/25278
Merge with https://github.com/opencv/opencv_extra/pull/1165
In Gold-YOLO ,`Div` has a constant input `B=6` which is then parsed into a `Const` layer in the ONNX importer, but `Clip` also has the shared constant input `max=6` which is already a `Const` layer and then connected to `Elementwise` layer. This should not happen because in the `forward()` of `Elementwise` layer, the legacy code goes through and apply activation to each input. More details on https://github.com/opencv/opencv/issues/25278#issuecomment-2032199630.
> [BugFix] dnn (ONNX): Foce dropping constant inputs in `parseClip` if they are shared

- modules/objdetect/src/qrcode.cpp
https://pullrequest.opencv.org/buildbot/builders/4_x_valgrind-lin64-debug/builds/100068/steps/test_objdetect/logs/valgrind%20summary
> Resolve valgrind issue at QRCode detector

- modules/dnn/src/layers/concat_layer.cpp
- modules/dnn/test/test_layers_1d.cpp
This PR introduces parametrized `0/1D` input support test for `Concat` layer.
> Concat Layer 0/1D test

- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/test/test_tiff.cpp
> Export TIFF compression options as API and git rid of tiff.h.

- modules/videoio/src/cap_v4l.cpp
- modules/videoio/test/test_v4l2.cpp
---
See: https://github.com/opencv/opencv/pull/25249
@carabsc Does this change works for you?
If so, I believe it is better to use `cv::cvtColor()` function.
Warning, this is `GRBG` --> `BGR`.
BTW, can we do the same changes with
- [`bayer2rgb24()`](https://github.com/opencv/opencv/blob/f87e1efd2acc1d36791e0530a006e77dbd5c3a9e/modules/videoio/src/cap_v4l.cpp#L1331C13-L1331C24)
-  [`sgbrg2rgb24()`](https://github.com/opencv/opencv/blob/f87e1efd2acc1d36791e0530a006e77dbd5c3a9e/modules/videoio/src/cap_v4l.cpp#L1409)
> Use cvtColor() for Bayer image color demosaicing with V4L2_PIX_FMT_SGRBG8

- modules/dnn/src/layers/softmax_layer.cpp
- modules/dnn/test/test_layers_1d.cpp
This PR introduces parametrized 1D input support test for `softmax` layer. 
> 1D Input Softmax test

- modules/core/src/rand.cpp
problem is on 5.x only: https://pullrequest.opencv.org/buildbot/builders/5_x_valgrind-lin64-debug/builds/100059/steps/test_core/logs/valgrind%20summary
> Resolve out of bound write in RNG::fill

- modules/dnn/src/layers/scatterND_layer.cpp
- modules/dnn/src/layers/scatter_layer.cpp
- modules/dnn/src/layers/tile_layer.cpp
- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_int.cpp
- modules/dnn/test/test_onnx_importer.cpp
Added int tests for CumSum, Scatter, Tile and ReduceSum dnn layers
Fixed bug in tile layer.
Fixed bug in reduce layer by reimplementing the layer. 
Fixed types filter in Scatter and ScatterND layers
PR for extra: https://github.com/opencv/opencv_extra/pull/1161
> Added int tests for CumSum, Scatter, Tile and ReduceSum dnn layers

- modules/3d/src/rgbd/volume_impl.cpp
https://pullrequest.opencv.org/buildbot/builders/5_x_valgrind-lin64-debug/builds/100059/steps/test_3d/logs/stdio
> Resolve valgrind issue in 3d module

- modules/dnn/src/layers/arg_layer.cpp
- modules/dnn/src/layers/scatterND_layer.cpp
- modules/dnn/test/test_int.cpp
Added int tests for Const, Concat, ScatterND, NaryEltwise, Arg, Blank layers
> Added int tests for Const, Concat, ScatterND, NaryEltwise, Arg, Blank layers

- modules/videoio/test/test_v4l2.cpp
I see RGB-BGR color issue with NV12 and NV21 on Ubuntu 18.04 (kernel 5.4.0-150). I'll re-check with newer Ubuntu and file another patch to fix it.
> Added option to dump v4l2 test frame from virtual camera

- modules/dnn/test/test_layers_1d.cpp
This PR introduces parametrized `0/1D` input support test for `Permute` layer.
> Permute Layer Test 0D

- modules/core/test/test_arithm.cpp
- modules/dnn/src/layers/eltwise_layer.cpp
5.x related only
1. https://pullrequest.opencv.org/buildbot/builders/5_x_valgrind-lin64-debug/builds/100060/steps/test_core/logs/valgrind%20summary
2. https://pullrequest.opencv.org/buildbot/builders/5_x_valgrind-lin64-debug/builds/100060/steps/test_dnn/logs/valgrind%20summary
Related PRs:
- https://github.com/opencv/opencv/pull/24578
> Resolve valgrind warnings

- modules/imgproc/src/phasecorr.cpp
This pull request removes unnecessary floating point literal.
The "f" literal indicating float precision is unnecessary, because double precision is required in this line.
So, remove unnecessary literal from `coeff1` calculation to match `coeff0` calculation.
This change should not affect the calculation results.
> Remove unnecessary floating point literal

- modules/dnn/test/test_tflite_importer.cpp
This is separate from #25297. The main purpose is to fix the shape checker in tflite tests.
> Add a shape checker for tflite models

- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/include/opencv2/imgproc/detail/legacy.hpp
- modules/imgproc/src/contours.cpp
- modules/imgproc/src/contours_approx.cpp
- modules/imgproc/src/contours_common.cpp
- modules/imgproc/src/contours_common.hpp
- modules/imgproc/src/contours_link.cpp
- modules/imgproc/src/contours_new.cpp
- modules/imgproc/test/test_contours.cpp
- modules/imgproc/test/test_contours_new.cpp
What is done:
* rewritten `findContours` and `icvApproximateChainTC89` using C++ data structures
* extracted LINK_RUNS mode to separate new public functions - `findContoursLinkRuns` (it uses completely different algorithm)
* ~added new public `cv::approximateChainTC89`~ - **:x: decided to hide it**
* enabled chain code output (method = 0, no public enum value for this in C++ yet)
* kept old function as `findContours_old` (exported, but not exposed to user)
* added more tests for findContours (`test_contours_new.cpp`), some tests compare results of old function with new one. Following tests have been added:
* contours of random rectangle
* contours of many small (1-2px) blobs
* contours of random noise
* backport of old accuracy test
* separate test for LINK RUNS variant
What is left to be …
> Reworked findContours to reduce C-API usage

- modules/dnn/src/cuda/padding.cu
- modules/dnn/src/cuda4dnn/primitives/padding.hpp
- modules/dnn/src/layers/padding_layer.cpp
- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/src/tensorflow/tf_importer.cpp
- modules/dnn/test/test_int.cpp
Added int32 and int64 support to padding layer (CPU and CUDA).
ONNX parser doesn't convert non-zero padding value to float now.
> Added int support to padding layer

- modules/imgproc/test/test_filter.cpp
- modules/imgproc/test/test_thresh.cpp
Added tests for adaptiveThreshold and sepFilter2D
opencv_extra PR https://github.com/opencv/opencv_extra/pull/1167
Resolves issues #24742 #25283
> Added tests for adaptiveThreshold and sepFilter2D

- modules/dnn/src/layers/cpu_kernels/conv_depthwise.simd.hpp
This patch optimize `fastDepthwiseConv` in the f32 layer by using RVV Native Intrinsic.
This patch was tested on QEMU using VLEN=128 and VLEN=256 (`./bin/opencv_test_dnn`), both GCC (trunk) and Clang (16.0.6) are passed;
On the real device (k230, VLEN=128, Clang 16.0.6), For valid test cases in `conv::Conv_Depthwise`, `opencv_perf_dnn` showed the average acceleration of `5.74x` for strided cases (benefit from using stride load instead of buffer) and `1.55x` for non-strided cases (benefit from using more vector registers, m2 -> m8).
<details><summary>Test Result ( in descending order of acceleration ratio)</summary>
| Name of Test                                                 | origin  | optimized | vs   |
| ------------------------------------------------------------ | ------- | …
> Further optimize fastDepthwiseConv for RISC-V Vector.

- modules/imgproc/src/filter.simd.hpp
- modules/imgproc/src/fixedpoint.inl.hpp
- modules/imgproc/src/smooth.simd.hpp
* filter/SIMD: removed parts which casted 8u pointers to int causing unaligned memory access on RISC-V platform.
* GaussianBlur/fixed_point: replaced casts from s16 to u32 with union operations
Performance comparison:
Note: for some reason my performance results are quite unstable, unaffected functions show speedups and slowdowns in many cases. Filter2D and GaussianBlur seem to be OK.
Slightly related PR: https://github.com/opencv/ci-gha-workflow/pull/165
> imgproc: fix unaligned memory access in filters and Gaussian blur

- modules/calib3d/test/test_solvepnp_ransac.cpp
Partial backport of #25379
Test log:
```
[ RUN      ] AP3P.ctheta1p_nan_23607
/home/ci/opencv/modules/3d/test/test_solvepnp_ransac.cpp:2320: Failure
Expected: (cvtest::norm(res.colRange(0, 2), expected, NORM_INF)) <= (3e-16), actual: 3.33067e-16 vs 3e-16
[  FAILED  ] AP3P.ctheta1p_nan_23607 (1 ms)
```
Related CI PR: https://github.com/opencv/ci-gha-workflow/pull/165
> calib3d: increased AP3P test threshold for RISC-V platform

- modules/3d/test/test_rendering.cpp
- modules/3d/test/test_solvepnp_ransac.cpp
- modules/imgproc/src/filter.simd.hpp
- modules/imgproc/src/fixedpoint.inl.hpp
- modules/imgproc/src/smooth.simd.hpp
Port of #25364 to 5.x + minor changes in 3d tests to pass on RISC-V platform
Failed tests:
```
[ RUN      ] AP3P.ctheta1p_nan_23607
/home/ci/opencv/modules/3d/test/test_solvepnp_ransac.cpp:2320: Failure
Expected: (cvtest::norm(res.colRange(0, 2), expected, NORM_INF)) <= (3e-16), actual: 3.33067e-16 vs 3e-16
[  FAILED  ] AP3P.ctheta1p_nan_23607 (1 ms)
[ RUN      ] Rendering/RenderingTest.accuracy/4, where GetParam() = ((320, 240), Flat, CW, Color, CV_32F, CV_32S)
/home/ci/opencv/modules/3d/test/test_rendering.cpp:430: Failure
Expected: (normL2Depth) <= (normL2Threshold), actual: 0.00102317 vs 0.000989
[  FAILED  ] Rendering/RenderingTest.accuracy/4, where GetParam() = ((320, 240), Flat, CW, Color, CV_32F, CV_32S) (22 ms)
[ RUN      ] Rendering/RenderingTest.accuracy/5, where GetParam() = …
```
> Fix unaligned filters + increase test thresholds (5.x)

- modules/imgproc/src/contours_new.cpp
- modules/imgproc/test/test_contours.cpp
- modules/imgproc/test/test_contours_new.cpp
Introduced in https://github.com/opencv/opencv/pull/25146
> Removed old C API usage in new findContours implementation

- modules/core/test/test_io.cpp
Related https://github.com/opencv/opencv/pull/25351
Related https://github.com/opencv/opencv/pull/25387
Use hfloat instead of float16_t.
> core: persistence: use hfloat instead of float16_t

- modules/core/include/opencv2/core/cvdef.h
- modules/dnn/src/layers/cpu_kernels/conv_block.simd.hpp
- modules/dnn/src/layers/cpu_kernels/conv_winograd_f63.cpp
- modules/dnn/src/layers/cpu_kernels/conv_winograd_f63.simd.hpp
- modules/dnn/src/layers/cpu_kernels/convolution.cpp
- modules/dnn/src/layers/cpu_kernels/convolution.hpp
- modules/dnn/src/onnx/onnx_graph_simplifier.cpp
Resolves comment: https://github.com/opencv/opencv/pull/25217#discussion_r1547733187.
`std::float16_t` and `std::bfloat16_t` are introduced since c++23: https://en.cppreference.com/w/cpp/types/floating-point.
> Rename remaining float16_t for future proof

- modules/imgproc/test/test_contours.cpp
I've met issues when running `FindContours.accuracy` test (uses old C-API) on a machine with 512Mb memory (RISC-V CanMV K230). While test itself consumes ~400Mb, with the system and other tests' leftovers it often gets killed with OOM error. So I propose to mark this test with `512mb` tag to allow filtering it out on similar devices.
Below is memory consumption on x86_64 machine (GCC 11.4, Release build, with OCL):
Notes:
- Port to 5.x is not needed - this test will be removed with C-API there.
- Related CI PR: https://github.com/opencv/ci-gha-workflow/pull/165 (see failed checks)
- `free -h` shows `480Mi` _Total memory_ on this machine
> imgproc: add 512mb tag for FindContours.accuracy test

- modules/dnn/cmake/plugin.cmake
(This PR is recreated from #25340)
Fixes https://github.com/opencv/opencv/issues/24392.
I'm not sure this is the best practice, but looks working well for me with rev.https://github.com/opencv/opencv/commit/2c5b296ab2f970a2fff4ef519f412c1ec9920056
Any helps or advice are welcomed if this patch need to be modified.
> Fix dnn plugin build win32

- platforms/ios/PrivacyInfo.xcprivacy
- platforms/ios/build_framework.py
closes #24951
Testing:
- Build iOS framework
- Ensure that `PrivacyInfo.xcprivacy` is included to framework resources.
Expected iOS framework structure:
> feat: add PrivacyInfo file to iOS framework

- modules/core/misc/python/package/mat_wrapper/__init__.py
- modules/python/src2/typing_stubs_generation/predefined_types.py
closes #24803
`cv2/typing/__init__.py`:
```python
import typing as _typing
if _typing.TYPE_CHECKING:
NumPyArrayNumeric = numpy.ndarray[_typing.Any, numpy.dtype[numpy.integer[_typing.Any] | numpy.floating[_typing.Any]]]
else:
NumPyArrayNumeric = numpy.ndarray
MatLike = _typing.Union[cv2.mat_wrapper.Mat, NumPyArrayNumeric]
```
Test file (`test_numeric_ndarray.py`) content:
```python
import cv2
mask = np.zeros((4, 4), dtype=np.uint8)
contours, hierarchy = cv2.findContours(mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_KCOS)
contour = contours[0] * 2
```
`pyproject.toml` content
```toml
[tool.mypy]
strict = true
ignore_missing_imports = true
plugins = [
"numpy.typing.mypy_plugin"
]
```
```shell
$ mypy test_numeric_ndarray.py
Success: no issues found in 1 source file
```
See …
> feat: use numeric dtype for MatLike instead of generic

- modules/imgproc/doc/colors.markdown
Close #25401 
emoji command doesn't work well in section header, so this patch remove it.
( There are no other files which has emoji commands )
> imgproc: doc: fix arrow symbols in header

- modules/dnn/src/layers/fully_connected_layer.cpp
- modules/dnn/test/test_layers_1d.cpp
This PR introduces parametrized `0/1D` input support test for `Fullyconnected` layer.
> Fully connected 0D test. 

- modules/calib3d/src/calibinit.cpp
Neighbors are sorted by distance in ascending order.
```
if (min_dist < FLT_MAX)
CV_Assert(dist >= min_dist);
```
isn't triggered.
So, we always take first suitable neighbor and we can stop search after this.
> Take first suitable neighbor in ChessBoardDetector::findQuadNeighbors

- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_onnx_importer.cpp
Partially address https://github.com/opencv/opencv/issues/25363
Fixed ONNX range layer. It should support any input type.
Added tests (extra [PR](https://github.com/opencv/opencv_extra/pull/1170))
> Fixed ONNX range layer

- modules/core/include/opencv2/core/cvdef.h
Address https://github.com/opencv/opencv/pull/25422#discussion_r1568189851
> Drop float16_t alias in 5.x after 4.x merge

- modules/imgproc/src/hal_replacement.hpp
- modules/imgproc/src/imgwarp.cpp
Address https://github.com/opencv/opencv/issues/25392
> New HAL API for remap

- modules/dnn/test/test_layers_1d.cpp
This PR introduces `0/1D` test for `Constant` layer
> Constant layer 0/1D test.

- modules/features2d/test/ocl/test_feature2d.cpp
- modules/features2d/test/test_descriptors_invariance.cpp
- modules/features2d/test/test_descriptors_invariance.impl.hpp
- modules/features2d/test/test_detectors_invariance.cpp
- modules/features2d/test/test_detectors_invariance.impl.hpp
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/3722
I've observed high memory consumption in the `opencv_test_features2d` (x86_64, Ubuntu 22.04, Debug):
It's always more than 180 MiB with peak at 535 MiB
This was caused by pointers to the algorithm object instances stored in the tests parameters. I've replaced them with factory functions/lambdas with the following result:
Now peak is at 355 MiB and permanent consumption level is ~ 1-2 MiB
**Note:** current peak is caused by KAZE features allocating 8x image size utility buffers. Not sure if we can or should do anything about it: https://github.com/opencv/opencv/blob/66fb5021e9253e3decab376d00322eaf2b279c89/modules/features2d/src/kaze/KAZEFeatures.cpp#L61-L68
> features2d: reduce accuracy test avg memory consumption

- modules/imgproc/src/hal_replacement.hpp
- modules/imgproc/src/smooth.dispatch.cpp
Tries to address #24850
Previous trial: https://github.com/opencv/opencv/pull/25334
> Added HAL function for popular bit-exact branch of GaussianBlur with sigma=0

- modules/videoio/src/cap_ffmpeg.cpp
- modules/videoio/src/cap_ffmpeg_impl.hpp
initLogger_ does not check if the logger has been initizalized before and it might initialize it several times from different threads, racing with other threads that are logging.
> Fix race condition in InternalFFMpegRegister initialization.

- apps/CMakeLists.txt
- apps/createsamples/utility.cpp
> apps: createsamples: fix comment to remove last backslash

- modules/core/src/matmul.simd.hpp
Resolves https://github.com/opencv/opencv/issues/25302
Reproducer: https://github.com/opencv/ci-gha-workflow/actions/runs/8747714722/job/24006610667?pr=171#step:12:1041
> core: fix `Core_GEMM.accuracy` failure on recent macOS

- modules/imgcodecs/src/grfmt_tiff.cpp
No int64/uint64 is used in the code anymore.
grfmt_tiff.hpp includes the tiff.h header inside of the tiff_dummy_namespace declaration. One implication of this is that all namespaced declarations made in tiff.h become qualified with tiff_dummy_namespace::.
Because tiff.h includes standard library headers, the std namespace declarations are converted to tiff_dummy_namespace::std declarations.
Subsequently, grfmt_tiff.hpp declares using namespace tiff_dummy_namespace;.
This can lead to an ambiguity error during the resolution of the std namespace.
> Remove unnecessary FIXIT section in grfmt_tiff.cpp

- modules/imgcodecs/test/test_tiff.cpp
Related https://github.com/opencv/opencv/pull/25453
For Windows 10-x64 / Build And Test, test result is not expected.
However there are no information enoght to investigate.
- Add `ASSERT_NO_THROW()` for imwrite()/imread().
- Check `img2.empty()`
> imgcodecs: tiff: test: ASSERT_NO_THROW() for imwrite/imread

- modules/core/include/opencv2/core/cvdef.h
Sync changes that are missed in the last 4.x->5.x merge.
> 5.x core: sync changes that drop some member functions in class hfloat

- modules/dnn/src/layers/batch_norm_layer.cpp
- modules/dnn/test/test_layers_1d.cpp
This PR introduces support for 0/1D inputs in `BatchNorm` layer. 
> 0/1D test for `BatchNorm` layer

- modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter_opencv_all_denylist.inl.hpp
This PR add logs to test failures to  `test_onnx_conformance_layer_filter_opencv_all_denylist.inl.hpp` and it continuation of #25442
> Add logs of test failure to `test_onnx_conformance_layer_filter_opencv_all_denylist.inl.hpp`

- modules/calib3d/include/opencv2/calib3d.hpp
Documentation for findEssentialMat() incorrectly states that the method uses the same cameraMatrix for both lists of points even though there are two cameraMatrix and distCoeffs.
Checked the code and it does the right thing i.e. uses cameraMatrix1, distCoeffs1 for points1 and cameraMatrix2, distCoeffs2 for points2.
Updated the documentation for the method to clarify what it does. The code itself is not changed.
> Fix documentation for findEssentialMat to reflect how it actually works.

- modules/gapi/src/backends/ov/govbackend.cpp
Related patch: https://github.com/opencv/opencv/pull/24938
> Fixed build warnings introduced in #24938

- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_onnx_importer.cpp
Fixed ONNX Range layer to support any input type
Extra PR: https://github.com/opencv/opencv_extra/pull/1173
Fixes #25363 
> Fixed ONNX Range layer to support any input type

- modules/core/misc/python/pyopencv_umat.hpp
- modules/python/src2/cv2_convert.cpp
- modules/python/src2/cv2_numpy.cpp
- modules/python/src2/cv2_numpy.hpp
There is no bug with the current implementation.
But this change enables the numpy code to be its own library, in case some users want to (e.g. CLIF library) and have the Python wrapper link to it. It would not be possible without this change as there would be a static initialization order fiasco otherwise.
> Replace static numpy allocator by function containing static.

- modules/imgproc/src/stackblur.cpp
fix the issue: https://github.com/opencv/opencv/issues/25498
`kernelSize = radius*2 + 1`. If the kernel size is bigger then width, we need to set a bigger buffer for it.
> fix statckblur big kernel case

- modules/imgproc/include/opencv2/imgproc.hpp
It is said "see above" because calcBackProject is listed under calcHist function in source file, while it is listed before in generated documentation due to the lexicographic ordering.
> Fix doc about uniform parameter for imgproc calcBackProject function

- modules/highgui/src/window_wayland.cpp
> highgui: wayland: support imshow() without pre-calling namedWindow()

- modules/python/src2/hdr_parser.py
> Fixed SyntaxWarning: invalid escape sequence '\w' in header parser.

- modules/dnn/include/opencv2/dnn/dnn.hpp
- modules/dnn/src/model.cpp
- modules/dnn/test/imagenet_cls_test_alexnet.py
- modules/dnn/test/pascal_semsegm_test_fcn.py
- modules/dnn/test/test_model.cpp
**Merged with:** https://github.com/opencv/opencv_extra/pull/1171
Part of https://github.com/opencv/opencv/issues/25314
This PR aims to change the tests related to fcn8s-heavy-pascal from caffe framework to onnx. The new fcn models have different backbone and output.
new model link: https://github.com/onnx/models/blob/main/validated/vision/object_detection_segmentation/fcn/model/fcn-resnet50-12.onnx
> change fcn8s-heavy-pascal tests from caffe to onnx

- modules/imgcodecs/src/grfmt_exr.cpp
> Got rid of deprecated convertFp16 in imgcodecs module.

- modules/dnn/test/test_model.cpp
Introduced in https://github.com/opencv/opencv/pull/25435
> Made fcn-resnet50-12.onnx model optional.

- modules/python/test/test_misc.py
`float_` will be removed in NumPy 2.0 (https://github.com/numpy/numpy/blob/main/doc/source/release/2.0.0-notes.rst#numpy-20-python-api-removals)
> python: adapt test to NumPy 2.x

- doc/Doxyfile.in
- modules/imgproc/include/opencv2/imgproc.hpp
Resolves #25481
Some clas inheritance graphs are too big, so I decided to turn them off completely. Graphs for selected classes can be enabled using `inheritancegraph` command (https://www.doxygen.nl/manual/commands.html#cmdinheritancegraph).
I noticed that some collaboration diagrams can be quite large as well (see second diagram here: https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html), so we might need to disable them too (`COLLABORATION_GRAPH` option).
Extra change was needed to fix Javadoc documentation generation (version 17), for some reason two examples caused build issues.
> doc: disable inheritance graphs

- modules/imgproc/src/geometry.cpp
- modules/imgproc/test/test_boundingrect.cpp
This PR is intended to fix #25265. In order to do it we should:
1. Add proper reproducer as a test (done)
2. Fix implementation to use correct vector types (done)
Test for _boundingRect_ has been converted to modern scheme and parametrized. Also increased test boundaries and added separate alignment test. In order to reproduce the issue one needs to build and run this test on ARMv7 board or emulate using C++ intrinsics with alignment checks (`-DOPENCV_EXTRA_CXX_FLAGS="-DCV_STRONG_ALIGNMENT=1 -DCV_FORCE_SIMD128_CPP=1"`). To activate second changed block (`#if CV_SIMD_WIDTH > 16`) use `-DCPU_BASELINE=AVX2`.
> imgproc: improved test for boundingRect

- modules/videoio/src/cap.cpp
Resolves #17879 by decreasing log messages level from "ERROR" to "WARNING".
> videoio: decreased log level for failed backends in capture and writer open

- modules/imgproc/perf/perf_moments.cpp
> Tune sanity threshold in Moments performance test for Android aarch64

- modules/core/include/opencv2/core.hpp
- modules/core/src/hal_replacement.hpp
- modules/core/src/minmax.cpp
Fixes https://github.com/opencv/opencv/issues/25540
The original implementation call HAL with the same parameters independently from amount of channels. The patch uses HAL correctly for the case cn > 1.
> Fix HAL interface for hal_ni_minMaxIdx

- modules/core/src/hal_replacement.hpp
- modules/core/src/lut.cpp
> HAL for LUT added

- modules/core/src/minmax.cpp
- modules/core/test/test_arithm.cpp
Address comments in https://github.com/opencv/opencv/pull/25553
> Transform offset to indeces for MatND in minMaxIdx HAL

- modules/imgproc/src/hal_replacement.hpp
- modules/imgproc/src/histogram.cpp
> HAL for equalizeHist() added

- doc/tutorials/introduction/env_reference/env_reference.markdown
Resolves #25536
- fixed `os.environ` modification
- added a note regarding limitations of this approach
> doc: fix env change method in the environment reference

- modules/dnn/src/layers/einsum_layer.cpp
- modules/dnn/test/test_layers_1d.cpp
This PR introduces 0/1D test cases for Einsum layer. 
TODO: 
- Add support for 0D tensors to Einsum layer 
> 0/1D Einsum Layer Test

- cmake/OpenCVUtils.cmake
Currently, zlib-ng version is 'zlib ver #define ZLIB_VERSION "1.3.0.zlib-ng"'. Because ocv_parse_header_version only accepts dot and numbers and doesn't accepts 1.3.0.zlib-ng. This patch changes ocv_parse_header_version to accept all characters between parentheses.
> Fix zlib-ng version parse

- modules/imgproc/include/opencv2/imgproc.hpp
See https://github.com/opencv/opencv/blob/1f1ba7e40276043fe363102d34a0781920ff29f3/modules/imgproc/src/moments.cpp#L626
> Synchornized cv::moments documentation with actual implementation.

- modules/core/src/minmax.dispatch.cpp
- modules/dnn/src/layers/arg_layer.cpp
- modules/dnn/src/layers/eltwise_layer.cpp
- modules/dnn/src/layers/gather_layer.cpp
- modules/dnn/test/test_common.cpp
- modules/dnn/test/test_layers_1d.cpp
This has additional fixes requited for 0/1D tests. 
> Additional fixes to 0/1D tests

- modules/highgui/src/window_wayland.cpp
- modules/highgui/test/test_gui.cpp
> highgui: wayland: expand image width if title bar cannot be shown

- .github/workflows/PR-5.x.yaml
- modules/dnn/src/ie_ngraph.cpp
- modules/dnn/src/ie_ngraph.hpp
- modules/dnn/src/int8layers/convolution_layer.cpp
- modules/dnn/src/layer_internals.hpp
- modules/dnn/src/layers/blank_layer.cpp
- modules/dnn/src/layers/cast_layer.cpp
- modules/dnn/src/layers/const_layer.cpp
- modules/dnn/src/layers/cumsum_layer.cpp
- modules/dnn/src/layers/expand_layer.cpp
- modules/dnn/src/layers/gather_elements_layer.cpp
- modules/dnn/src/layers/gather_layer.cpp
- modules/dnn/src/layers/padding_layer.cpp
- modules/dnn/src/layers/scatterND_layer.cpp
- modules/dnn/src/layers/scatter_layer.cpp
- modules/dnn/src/layers/tile_layer.cpp
- modules/dnn/src/net_impl.cpp
- modules/dnn/src/op_inf_engine.cpp
- modules/dnn/test/test_int.cpp
- modules/dnn/test/test_layers.cpp
- modules/dnn/test/test_onnx_importer.cpp
- modules/dnn/test/test_tflite_importer.cpp
Modified dnn OpenVINO integration to support type inference and int operations.
Added OpenVINO support to Cast, CumSum, Expand, Gather, GatherElements, Scatter, ScatterND, Tile layers.
I tried to add Reduce layer, but looks like OpenVINO uses float values inside Reduce operation so it can't pass our int tests.
OpenVINO uses int32 precision for int64 operations, so I've modified input values for int64 tests when backend is OpenVINO.
OpenVINO has a strange behavior with custom layers and int64 values. After model compilation OpenVINO may change types, so the model can have different output type. That's why these tests were disabled:
- Test_ArgMax_Int.random/0, where GetParam() = (4, NGRAPH/CPU)
- Test_ArgMax_Int.random/6, where GetParam() = (11, NGRAPH/CPU)
- Test_Reduce_Int.random/6, where …
> Added int support for OpenVINO dnn backend

- modules/highgui/test/test_gui.cpp
My fault introduced in https://github.com/opencv/opencv/pull/25561
> Restored and extended Highgui test logic for small windows.

- modules/gapi/test/infer/gapi_infer_ie_test.cpp
Continues https://github.com/opencv/opencv/issues/25320
> Disable more streaming test in G-API due to instability.

- modules/dnn/src/tflite/tflite_importer.cpp
- modules/dnn/test/test_tflite_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1168
The purpose of this PR is to introduce support for the Transpose op in TFlite format and to add a shape comparison between the output tensors and the references. In some occasional cases, the shape of the output tensor is `[1,4,1,1]`, while the shape of the reference tensor is `[1,4]`. Consequently, the norm check incorrectly reports that the test has passed, as the residual is zero.
Below is a Python script for generating testing data. The generated data can be integrated into the repo `opencv_extra`.
```python
import tensorflow as tf
PREFIX_TFL = '/path/to/opencv_extra/testdata/dnn/tflite/'
def generator(input_tensor, model, saved_name):
converter = tf.lite.TFLiteConverter.from_keras_model(model) …
```
> Support Transpose op in TFlite

- modules/dnn/src/cuda/concat.cu
- modules/dnn/src/cuda/eltwise_ops.cu
- modules/dnn/src/cuda/fill_copy.cu
- modules/dnn/src/cuda/limits.hpp
- modules/dnn/src/cuda/max_unpooling.cu
- modules/dnn/src/cuda/padding.cu
- modules/dnn/src/cuda/permute.cu
- modules/dnn/src/cuda/slice.cu
- modules/dnn/src/layer_internals.hpp
- modules/dnn/src/layers/nary_eltwise_layers.cpp
- modules/dnn/src/legacy_backend.cpp
- modules/dnn/src/net_impl.cpp
- modules/dnn/src/net_impl_backend.cpp
- modules/dnn/src/onnx/onnx_graph_simplifier.cpp
- modules/dnn/src/onnx/onnx_graph_simplifier.hpp
- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/src/op_cuda.hpp
- modules/dnn/test/test_layers.cpp
- modules/dnn/test/test_misc.cpp
- modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter_opencv_all_denylist.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
In dnn 4.x usually any model's input is converted to float32 or float16 (except quantized models). Also mean and scale can be applied. In current dnn 5.x there is the same conversion except int32 and int64 types. I removed this conversion.
Here is how the pipeline works now:
- if input Mat type is float32, the pipeline applies mean and scale and may convert it to float16.
- if input Mat type is not float32, the pipeline preserves the input type and doesn't apply mean and scale
There was a conflict in protobuf parser between ONNX importer and tests. In ONNX importer any uint8 weight was handled as quantized weight and x = int8(x_uint8 - 128) conversion was used inside the protobuf parser. ONNX conformance tests used the same protobuf reader, so tests with uint8 inputs couldn't read the …
> Disabled conversion to float of model's input

- CMakeLists.txt
Currently, there is a warning when CMake >= 3.27,
CMake Warning (dev) at cmake/OpenCVUtils.cmake:144 (find_package):
Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
the cmake_policy command to set the policy and suppress this warning.
This patch sets policy 0148 explicitly to suppress the warning.
> set policy 0148 explicitly

- modules/core/src/arithm.cpp
- modules/core/src/channels.cpp
- modules/core/src/convert.simd.hpp
- modules/core/src/convert_scale.simd.hpp
- modules/core/src/count_non_zero.simd.hpp
- modules/core/src/has_non_zero.simd.hpp
- modules/core/src/lut.cpp
- modules/core/src/mathfuncs.cpp
- modules/core/src/matmul.dispatch.cpp
- modules/core/src/matmul.simd.hpp
- modules/core/src/matrix_operations.cpp
- modules/core/src/matrix_sparse.cpp
- modules/core/src/mean.simd.hpp
- modules/core/src/merge.dispatch.cpp
- modules/core/src/minmax.cpp
- modules/core/src/rand.cpp
- modules/core/src/split.dispatch.cpp
- modules/core/src/sum.simd.hpp
Address https://github.com/opencv/opencv/issues/24703
> Check range for type-dependant function tables

- apps/model-diagnostics/model_diagnostics.cpp
- modules/dnn/include/opencv2/dnn/dnn.hpp
- modules/dnn/src/net.cpp
- modules/dnn/src/net_impl.cpp
- modules/dnn/src/net_impl.hpp
Current net exporter `dump` and `dumpToFile` exports the network structure (and its params) to a .dot file which works with `graphviz`. This is hard to use and not friendly to new user. What's worse, the produced picture is not looking pretty.
This PR introduces new exporter `dumpToPbtxt` and uses this new exporter by default with environment variable `OPENCV_DNN_NETWORK_DUMP`. It mimics the string output of a onnx model but modified with dnn-specific changes, see below for an example.
Call `cv::dnn::Net::dumpToPbtxt`:
```cpp
TEST(DumpNet, dumpToPbtxt) {
std::string path = "/path/to/model.onnx";
auto net = readNet(path);
Mat input(std::vector<int>{1, 3, 640, 480}, CV_32F);
net.setInput(input);
net.dumpToPbtxt("yunet.pbtxt");
}
```
Set `export OPENCV_DNN_NETWORK_DUMP=1`
```cpp …
```
> dnn: better net exporter that works with netron

- modules/highgui/src/window_w32.cpp
- modules/imgcodecs/perf/perf_jpeg.cpp
- modules/imgcodecs/perf/perf_png.cpp
- modules/imgcodecs/test/test_grfmt.cpp
- modules/imgcodecs/test/test_read_write.cpp
[WIP] trivial improvements on tests of imagecodecs module
> improvements on tests of imagecodecs module

- modules/core/include/opencv2/core/cvdef.h
- modules/core/include/opencv2/core/types_c.h
- modules/imgproc/src/cornersubpix.cpp
- modules/imgproc/src/drawing.cpp
- modules/imgproc/src/grabcut.cpp
- modules/imgproc/src/moments.cpp
- modules/imgproc/src/precomp.hpp
- modules/imgproc/src/segmentation.cpp
- modules/imgproc/test/test_contours.cpp
- modules/imgproc/test/test_convhull.cpp
- modules/imgproc/test/test_drawing.cpp
Changes:
* moved several macros from types_c.h to cvdef.h (assuming we will continue using them)
* removed some cases of C-API usage in _imgproc_ module (`CV_TERMCRIT_*` and `CV_CMP_*`)
* refactored `drawContours` to use C++ API instead of calling `cvDrawContours` + test for filled contours with holes (case with non-filled contours is simpler and is covered in some other tests)
There is one case where old drawContours behavior doesn't match the new one - when `contourIdx == -1` (means "draw all contours") and `maxLevel == 0` (means draw only selected contours, but not what is inside).
From the docs:
> **contourIdx**	Parameter indicating a contour to draw. If it is negative, all the contours are drawn.
> **maxLevel**	Maximal level for drawn contours. If it is 0, only the specified contour …
> imgproc: C-API cleanup, drawContours refactor

- modules/core/src/arithm.cpp
- modules/core/src/hal_replacement.hpp
> HAL mul8x8to16 added

- modules/core/src/minmax.dispatch.cpp
- modules/dnn/src/layers/arg_layer.cpp
- modules/dnn/src/layers/gather_layer.cpp
- modules/dnn/test/test_layers_1d.cpp
This PR introduces 1D parametrized test for element wise layer. The means that the tests covers following layer: 
`Clip`, `ReLU6`, `ReLU`,
`GeLU`, `GeluApprox`, `TanH`,
`Swish`, `Mish`, `Sigmoid`,
`ELULayer`, `Abs`, `BNLL`,
`Ceil`, `Floor`, `LogLayer`,
`Round`, `Sqrt`, `Acos`,
`Acosh`, `Asin`, `Asinh`,
`Atan`, `Atanh`, `Cos`,
`Sin`, `Sinh`, `Tan`, `Erf`,
`Reciprocal`, `Cosh`, `HardSwish`,
`Softplus`, `Softsign`, `Celu`,
`HardSigmid`, `Selu`, `ThresholdedRelu`,
`Power`, `Exp`, `Sign`, `Shrink`,
`ChannelsPReLU`
Not sure if this is best way to implement this test.
> Element-wise test for 1D

- modules/core/include/opencv2/core/hal/intrin_rvv_compat_overloaded.hpp
- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
- modules/core/test/test_intrin_utils.hpp
- modules/core/test/test_operations.cpp
This may be a legacy issue from the previous PR #24325. I don't quite remember why the float 64 part of the unit test was not enabled at that time. 
Whatever, this patch enables the unit tests for scalable 64F type , and makes the necessary modifications to the RVV backend to make the tests pass.
This patch is compiled by GCC 14 and LLVM 17 &18, and tested on QEMU and k230.
> Fix `v_round` and enable unit tests for scalable universal intrinsic 64F type.

- cmake/OpenCVFindLAPACK.cmake
- cmake/checks/lapack_check.cpp
- modules/core/src/hal_internal.cpp
Resolves https://github.com/opencv/opencv/issues/24660
Apple's BLAS documentation: https://developer.apple.com/documentation/accelerate/blas?language=objc
New interface since macOS >= 13.3, iOS >= 16.4.
Todo:
> core: try to solve warnings caused by Apple's new LAPACK interface

- modules/dnn/src/layers/einsum_layer.cpp
This PR fixes Einsum layer 0D failure case for Openvino backend  
> Fixed out-of-bound access in Einsum layer for 0d

- modules/calib3d/test/test_homography.cpp
Otherwise, this test does not compile with C++20, which includes std::format.
> Disambiguate cv::format

- 3rdparty/libpng/CMakeLists.txt
- CMakeLists.txt
Error message with `-DBUILD_PNG=ON` on ARM64:
```
-- Configuring done
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_ASM_COMPILE_OBJECT
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
> Fixed CMake Missing variable is: CMAKE_ASM_COMPILE_OBJECT in PNG build

- cmake/templates/OpenCVConfig.root-WIN32.cmake.in
With 17.10.0 the MSVC toolset was set to 19.40.x which breaks the compatibility test in the OpenCV's CMake Config files.
> Support VS 2022 17.1x.y

- 3rdparty/ffmpeg/ffmpeg.cmake
- modules/videoio/test/test_ffmpeg.cpp
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/84
- FFmpeg 4.4.4
- OpenH264 version 1.8.0
- libVPX version 1.14.0
- libAOM version 3.9.0
previous update: #24767
```
```
> ffmpeg/4.x: update FFmpeg wrapper 2024.05

- modules/imgproc/test/test_filter.cpp
fixes #25448
The obsolete function `cvSmooth` has two modes in which it calls `cv::boxFilter()` inside with and without normalization.
This function is covered by tests exactly for that modes.
This means that by replacing `cvSmooth` call by `cv::boxFilter()` we will leave the coverage untouched (but more obvious) and remove that obsolete function from tests.
> Tests for cvSmooth -> tests for boxFilter

- modules/calib3d/include/opencv2/calib3d.hpp
- modules/calib3d/src/calibration_handeye.cpp
- modules/calib3d/test/test_calibration_hand_eye.cpp
Fixes to the hand-eye calibration methods, from #24871.
The Tsai method is sensitive to poses separated by small rotations, so I filter those out.
The Horaud and Daniilidis methods use quaternions (and dual quaternions), where $q$ and $-q$ represent the same transform. However, these methods depend on the gripper motion and camera motion having the same sign for the real part. The fix was simply to multiply the (dual) quaternions by -1 if their real part is negative.
> Fix handeye

- modules/imgproc/doc/colors.markdown
- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/src/color_yuv.dispatch.cpp
- modules/imgproc/src/color_yuv.simd.hpp
- modules/imgproc/src/hal_replacement.hpp
This PR contains descriptions for various RGB <-> YUV color conversion codes as well as detailed comments in the source code.
> YUV codes for cvtColor: descriptions added

- modules/flann/include/opencv2/flann/lsh_table.h
This can trigger some asan warning, though it is valid.
> Prevent signed integer overflow in LshTable

- cmake/OpenCVFindLAPACK.cmake
Attempt to fix https://github.com/opencv/opencv/pull/24804#discussion_r1609957747
We may need to explicitly add build option `-DCMAKE_OSX_DEPLOYMENT_TARGET=12.0` or environment variable (`export MACOSX_DEPLOYMENT_TARGET=12.0`) for mac builds (python package most probably) on builders with new macOS (>= 13.3).
> core: deployment compatibility for old mac after Accelerate New LAPACK fix

- modules/core/src/minmax.cpp
Fixes bug found in discussion https://github.com/opencv/opencv/pull/25563
Alternative to https://github.com/opencv/opencv/pull/25669
> Fixed offset computation for ND case in MinMaxIdx HAL.

- modules/dnn/src/onnx/onnx_importer.cpp
This PR fixes Slice Layer's parser to handle empty input cases (cases with initializer)
It fixed the issue rased in #24838
> Slice layer parser fix to support empty input case

- modules/objdetect/src/aruco/aruco_board.cpp
- modules/objdetect/test/test_charucodetection.cpp
When generating  Charuco board markers in `generateImage()`, a problem occurs as in https://github.com/opencv/opencv/issues/24806, https://github.com/opencv/opencv/pull/24873:
In low resolution:
In medium resolution:
This PR fixed this problems:
The test checks the inner and outer borders of the Aruco markers. In the outer border of Aruco marker, all pixels should be white. In the inner border of Aruco marker, all pixels should be black.
> fixed marker generation in charuco board

- modules/dnn/src/tflite/tflite_importer.cpp
- modules/dnn/test/test_tflite_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1180
This PR adds support for `GlobalAveragePooling2D` and `GlobalMaxPool2D` on the TFlite backend. When the k`eep_dims` option is enabled, the output is a 2D tensor, necessitating the inclusion of an additional flatten layer. Additionally, the names of these layers have been updated to match the output tensor names generated by `generate.py` from the opencv_extra repository.
> Support Global_Pool_2D ops in .tflite model

- modules/calib3d/src/fundam.cpp
- modules/calib3d/test/test_homography.cpp
The bug was introduced in https://github.com/opencv/opencv/pull/25308
I am sorry I do not have a proper test.
> Fix Homography computation.

- modules/core/perf/perf_arithm.cpp
- modules/core/src/arithm.cpp
- modules/core/test/test_arithm.cpp
- modules/ts/include/opencv2/ts.hpp
- modules/ts/src/ts_func.cpp
* added accuracy tests for mixed type arithmetic operations
_Note: div-by-zero values are removed from checking since the result is implementation-defined in common case_
* added perf tests for the same cases
* fixed a typo in `getMulExtTab()` function that lead to dead code
> Tests added for mixed type arithmetic operations

- modules/gapi/test/infer/gapi_infer_ie_test.cpp
Related to https://github.com/opencv/opencv/issues/25320
Continues https://github.com/opencv/opencv/pull/25592
> Disable more G-API streaming test due to unstability.

- modules/videoio/src/cap_android_mediandk.cpp
Added potential fix for Android H264 / H265 Encoding Bug #23570 that was proposed in the issue comments.
I can't reproduce the issue because on my Android phone both the old and the new versions works fine. 
To test the changed code you need to build the sdk and run Video-recorder Android sample. Make sure that the application uses mediandk and doesn't print "Can't record H264. Switching to MJPG" to the logcat.
> Added potential fix for Android H264 Encoding Bug

- modules/imgcodecs/src/grfmt_hdr.cpp
- modules/imgcodecs/src/loadsave.cpp
- modules/imgcodecs/test/test_png.cpp
- modules/imgcodecs/test/test_read_write.cpp
Resolves #25694
Replaces #25695
* Moved `OutputArray` down the call stack
* Allow output images with smaller or larger size - will be recreated if necessary
* Added check for recreated image in calls to backend, if this happens, original image will not be updated - backend should be fixed in this case
* Fixed gray output handling in HDR (RGBE) backend - use cvtColor to convert
* Extended and moved corresponding test
Note: we rely on decoders to not recreate the input Mat in their `readData(Mat & img)` method. Otherwise destination image will not be updated just like in the issue.
> imgproc: fixed imread with output image argument

- modules/dnn/include/opencv2/dnn/all_layers.hpp
- modules/dnn/src/ie_ngraph.cpp
- modules/dnn/src/layers/blank_layer.cpp
- modules/dnn/src/layers/elementwise_layers.cpp
- modules/dnn/src/layers/flatten_layer.cpp
- modules/dnn/src/layers/nary_eltwise_layers.cpp
- modules/dnn/src/layers/not_layer.cpp
- modules/dnn/src/layers/reshape_layer.cpp
- modules/dnn/src/legacy_backend.cpp
- modules/dnn/src/net_impl_backend.cpp
- modules/dnn/src/onnx/onnx_graph_simplifier.cpp
- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/src/op_cuda.hpp
- modules/dnn/src/op_inf_engine.cpp
- modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
- modules/ts/src/ts_func.cpp
Added bool support to dnn pipeline (CPU, OpenVINO and CUDA pipelines).
Added bool support to these layers(CPU and OpenVINO):
- Equal, Greater, GreaterOrEqual, Less, LessOrEqual
- Not
- And, Or, Xor
- Where
Enabled all the conformance tests for these layers.
> Added bool support to dnn

- modules/python/src2/typing_stubs_generation/api_refinement.py
closes #25714
Resulting `cv2/__init__.pyi` entries:
```py
@_typing.overload
def floodFill(
image: cv2.typing.MatLike,
mask: cv2.typing.MatLike | None,
seedPoint: cv2.typing.Point,
newVal: cv2.typing.Scalar,
loDiff: cv2.typing.Scalar = ...,
upDiff: cv2.typing.Scalar = ...,
flags: int = ...
) -> tuple[int, cv2.typing.MatLike, cv2.typing.MatLike, cv2.typing.Rect]: ...
@_typing.overload
def floodFill(
image: UMat,
mask: UMat | None,
seedPoint: cv2.typing.Point,
newVal: cv2.typing.Scalar,
loDiff: cv2.typing.Scalar = ...,
upDiff: cv2.typing.Scalar = ...,
flags: int = ...
) -> tuple[int, UMat, UMat, cv2.typing.Rect]: ...
```
> fix: mark floodFill mask as optional in Python typing stubs

- modules/objdetect/test/test_charucodetection.cpp
In 4.x `detectBoard()` returns the charuco corners in a 2D Mat with shape (N_corners, 1)
In 5.x, after PR #23473, `detectBoard()` returns the charuco corners in a 1D Mat with shape (1, N_corners)
To make the test universal and enable the test in 5.x, reshape was added.
> updated testSeveralBoardsWithCustomIds to enable in 5.x

- modules/core/test/test_math.cpp
- modules/ts/include/opencv2/ts.hpp
- modules/ts/src/ts.cpp
It seems that random number generator in the `TS` varies depending on test set being run, e.g. have one seed when single test case is filtered and different seed when whole module is tested. Trying to use `cv::theRNG` instance  in tests.
> test: use cv::theRNG instead of own generator

- modules/calib3d/src/calibinit.cpp
The basic idea of finding pair of corners neighbors is to find best candidate for first corner and check if first corner quite good candidate for its best candidate. And we test first corner for its best candidate less than best candidate for first corner.
Idea of changes is to make finding corner neighbor symmetrical - find best candidate for first corner, find best candidate for second corner and match them as pair iff they are both best candidates for each other.
Additional advantage - it simplifies code and removes some code duplication.
I tested this PR with benchmark
```
python3 objdetect_benchmark.py --configuration=generate_run --board_x=7 --path=res_chessboard --synthetic_object=chessboard
```
There are minor changes in results
```
cell_img_size = 100 (default)
before
category …
```
> Make finding corner neighbor symmetrical in ChessBoardDetector::findQuadNeighbors

- modules/imgproc/include/opencv2/imgproc.hpp
> Better doc for WARP_RELATIVE_MAP

- modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
This PR adds additional comments on conformance denylist. Once  BOOL type got support in 5.x, some test layer changed their failing issue.
> Additional Comments for Conformance Denylist

- modules/imgproc/src/phasecorr.cpp
- modules/imgproc/test/test_pc.cpp
Fix for #25737: perform arithmetics in CV_32F branch of divSpectrums() with doubles to prevent infs/NaNs (+ corresponding test). Previous code probably had the same intention.
> Fix arithmetics in CV_32F branch of divSpectrums()

- modules/imgproc/test/test_histograms.cpp
> Accuracy tests for equalizeHist() added

- modules/videoio/src/cap_gstreamer.cpp
Safer replacement for https://github.com/opencv/opencv/pull/25557
Jetson Orin provides BGRx stream in some cases.
> Handle BGRA streams in GStreamer backend

- modules/js/test/init_cv.js
tests: https://github.com/opencv/ci-gha-workflow/pull/174
```
```
> Use onRuntimeInitialized with OpenCV.js Node tests

- platforms/android/build_sdk.py
>  Android SDK build script: HWAsan flags added for release mode

- modules/gapi/src/backends/fluid/gfluidcore_func.simd.hpp
Fixes https://github.com/opencv/opencv/issues/25741
`vx_load` loads twice more items that we need at the very end of the buffer. It leads to reading overflow.
> Fixed input buffer read overflow in vectorized G-API convertTo implementation

- modules/imgproc/perf/perf_bilateral.cpp
- modules/imgproc/test/test_bilateral_filter.cpp
extra: https://github.com/opencv/opencv_extra/pull/1184
> Extended bilateralFilter test to cover more branches

- modules/core/include/opencv2/core/eigen.hpp
- modules/core/test/test_mat.cpp
Fixes #16606 
Add overloads to cv2eigen to handle eigen matrices of type
Eigen::Matrix<Tp_, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>
> Add missing cv2eigen overload

- cmake/OpenCVUtils.cmake
> cmake: support 10+ minor version(10,11,...)

- doc/py_tutorials/py_imgproc/py_template_matching/py_template_matching.markdown
The use of `eval()` should be avoided where possible. Functionally, this will make the suptitle no longer start with "cv.", but could be put back in if there is a desire for it.
> Replace use of "eval()" with "getattr()".

- modules/imgproc/src/color_hsv.simd.hpp
> Remove unused variables in rgb2hsv_b simd

- modules/dnn/src/layers/cumsum_layer.cpp
- modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
Fixed cumsum layer, enabled conformance tests for the layer.
Fixes #24437 (looks like some of the mentioned problems were already fixed)
> Fixed cumsum layer, enabled conformance tests

- modules/dnn/src/layers/blank_layer.cpp
Changed blank layer because it didn't work with old OpenVINO versions(2022.1). The blank layer was implemented using ConvertLike layer, now it is implemented using ShapeOf and Reshape layers.
> Fixed blank layer for OpenVINO 2022.1

- modules/imgproc/src/demosaicing.cpp
Brow variable isn't used in calculation. So, I think it can be removed.
> Remove unused brow variable

- modules/dnn/src/cuda/concat.cu
- modules/dnn/src/cuda/fill_copy.cu
- modules/dnn/src/cuda/padding.cu
- modules/dnn/src/cuda/permute.cu
- modules/dnn/src/cuda/slice.cu
- modules/dnn/src/layers/concat_layer.cpp
- modules/dnn/src/layers/const_layer.cpp
- modules/dnn/src/layers/expand_layer.cpp
- modules/dnn/src/layers/flatten_layer.cpp
- modules/dnn/src/layers/gather_elements_layer.cpp
- modules/dnn/src/layers/gather_layer.cpp
- modules/dnn/src/layers/max_unpooling_layer.cpp
- modules/dnn/src/layers/padding_layer.cpp
- modules/dnn/src/layers/permute_layer.cpp
- modules/dnn/src/layers/pooling_layer.cpp
- modules/dnn/src/layers/reduce_layer.cpp
- modules/dnn/src/layers/reorg_layer.cpp
- modules/dnn/src/layers/reshape_layer.cpp
- modules/dnn/src/layers/scatterND_layer.cpp
- modules/dnn/src/layers/scatter_layer.cpp
- modules/dnn/src/layers/slice_layer.cpp
- modules/dnn/src/layers/split_layer.cpp
- modules/dnn/src/op_cuda.hpp
- modules/dnn/test/test_int.cpp
Added support of more types to dnn layers for CPU, CUDA and OpenVINO backends.
Now most of the multi-type layers support uint8, int8, int32, int64, float32, float16, bool types.
> Added more types support to dnn layers

- modules/videoio/CMakeLists.txt
Fixes https://github.com/opencv/opencv/issues/4482
> Exclude cap_ios.h from installation where it's not needed

- modules/imgproc/test/test_histograms.cpp
The test was introduced in https://github.com/opencv/opencv/pull/25759
> Relax equalizeHist test for some HAL implementations

- .github/PULL_REQUEST_TEMPLATE.md
The implementation example: https://github.com/asmorkalov/opencv/pull/15
> Force contributors to define Apache 2.0 license for the new PRs.

- modules/imgcodecs/src/grfmt_hdr.cpp
For invalid input data there is an exception here:
https://github.com/opencv/opencv/blob/bbf65a166e027f079835920f117db5725d3ec030/modules/imgcodecs/src/grfmt_hdr.cpp#L79
which leads to missing `fclose` call. It's possible to wrap `RGBE_ReadHeader` with try-catch and call `fclose` in place, but I chose a more reliable way. Please let me know if another way is preferred for the fix.
> Fix file descriptor leak in HDR decoder

- modules/highgui/src/window_w32.cpp
Fixes https://github.com/opencv/opencv/issues/25833
Would it make sense to add a test case for this? It would be a pair of `setWindowProperty` / `getWindowProperty` to verify that `WND_PROP_TOPMOST` actually changes (one symptom of the bug). Unfortunately I can't seem to get the tests to even appear in the generated VS solution right now...
> Fix #25833: The correct way to disable top-most state is with HWND_NOTOPMOST, not HWND_TOP.

- 3rdparty/carotene/CMakeLists.txt
Added a definition for M_PI in the code to resolve a compilation error encountered when building OpenCV on the MSYS2 environment. The M_PI constant was not defined, causing the compilation to fail.
> Fix: compilation Issue on ARM64 (msys2 clangarm)

- modules/dnn/src/cuda4dnn/init.hpp
Fixes https://github.com/opencv/opencv/issues/25711
Fixed warning:
```
[ WARN:0@410.036] global init.hpp:32 checkVersions cuDNN reports version 90.1 which is not compatible with the version 9.1 with which OpenCV was built
```
CuDNN changed version multipliers since 9.0. The patch accommodates to it.
> Fixed CuDNN runtime version check for CuDNN 9+.

- modules/core/include/opencv2/core/hal/intrin.hpp
- modules/core/include/opencv2/core/hal/intrin_cpp.hpp
- modules/core/include/opencv2/core/hal/intrin_math.hpp
- modules/core/test/test_intrin_utils.hpp
- modules/dnn/src/layers/cpu_kernels/softmax.cpp
This PR aims to implement `v_exp(v_float16 x)`, `v_exp(v_float32 x)` and `v_exp(v_float64 x)`.
```
```
> Add support for v_exp (exponential)

- modules/videoio/cmake/detect_obsensor.cmake
Fixes https://github.com/opencv/opencv/issues/25693
This PR is to turn off the downloading OrbbecSDK on MacOS by default. Only a very small percentage of OpenCV users on Mac would be using Orbbec cameras, so it makes sense not to download the SDK by default every time building OpenCV from source on MacOS. 
Then in order to use Orbbec 3D cameras on MacOS via OpenCV, users need to build OpenCV with `-DOBSENSOR_USE_ORBBEC_SDK=ON` explicitly.
> Set using Orbbec SDK on MacOS OFF by default.

- doc/tutorials/dnn/dnn_yolo/dnn_yolo.markdown
- modules/dnn/test/test_onnx_importer.cpp
- samples/dnn/yolo_detector.cpp
This PR adds sample support of  [`YOLOv9`](https://github.com/WongKinYiu/yolov9) and [`YOLOv10`](https://github.com/THU-MIG/yolov10/tree/main)) in OpenCV. Models for this test are located in this [PR](https://github.com/opencv/opencv_extra/pull/1186). 
**Running YOLOv10 using OpenCV.** 
1. In oder to run `YOLOv10` one needs to cut off postporcessing with dynamic shapes from torch and then convert it to ONNX. If someone is looking for ready solution, there is [this forked branch](https://github.com/Abdurrahheem/yolov10/tree/ash/opencv-export) from official YOLOv10.  Particularty follow this proceduce. 
```bash
git clone git@github.com:Abdurrahheem/yolov10.git
conda create -n yolov10 python=3.9
conda activate yolov10
pip install -r requirements.txt
python export_opencv.py …
```
> Add sample support of `YOLOv9` and `YOLOv10` in OpenCV

- modules/dnn/src/cuda/eltwise_ops.cu
- modules/dnn/src/cuda/functors.hpp
- modules/dnn/src/cuda4dnn/kernels/eltwise_ops.hpp
- modules/dnn/src/cuda4dnn/primitives/eltwise.hpp
- modules/dnn/src/layers/nary_eltwise_layers.cpp
- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_onnx_conformance.cpp
- modules/dnn/test/test_onnx_conformance_layer_filter__cuda_denylist.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter__cuda_fp16_denylist.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter__vulkan_denylist.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter_opencv_all_denylist.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter_opencv_ocl_fp16_denylist.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
This PR introduces the following changes:
```
Name of Test                     opencv        opencv        opencv
perf          perf          perf
core.x64.0606 core.x64.0606 core.x64.0606
vs
opencv
perf
core.x64.0606
(x-factor)
NCHW_C_sum::Layer_NaryEltwise::OCV/CPU           16.116        11.161         1.44
NCHW_NCHW_add::Layer_NaryEltwise::OCV/CPU        17.469        11.446         1.53
NCHW_NCHW_div::Layer_NaryEltwise::OCV/CPU        17.531        11.469         1.53
NCHW_NCHW_equal::Layer_NaryEltwise::OCV/CPU      28.653        13.682         2.09
NCHW_NCHW_greater::Layer_NaryEltwise::OCV/CPU    21.899        13.422         1.63
NCHW_NCHW_less::Layer_NaryEltwise::OCV/CPU       21.738        13.185         1.65
NCHW_NCHW_max::Layer_NaryEltwise::OCV/CPU …
```
> dnn: parallelize nary elementwise forward implementation & enable related conformance tests

- modules/core/include/opencv2/core/hal/intrin_cpp.hpp
- modules/core/include/opencv2/core/hal/intrin_math.hpp
- modules/core/test/test_intrin_utils.hpp
This PR aims to implement `v_log(v_float16 x)`, `v_log(v_float32 x)` and `v_log(v_float64 x)`. 
Merged after https://github.com/opencv/opencv/pull/24941
TODO:
```
```
> Add support for v_log (Natural Logarithm) 

- .github/workflows/PR-5.x.yaml
Related CI pipeline: https://github.com/opencv/ci-gha-workflow/pull/175
Related warning fixes: https://github.com/opencv/opencv/pull/25848
> Added Ubuntu 24.04 pipeline for 5.x

- modules/core/include/opencv2/core/cvdef.h
- modules/dnn/include/opencv2/dnn/dnn.hpp
- modules/dnn/misc/python/test/test_dnn.py
- modules/python/src2/cv2.hpp
- modules/python/src2/cv2_convert.cpp
- modules/python/src2/cv2_convert.hpp
- modules/python/src2/gen2.py
- modules/python/src2/hdr_parser.py
Fixes https://github.com/opencv/opencv/issues/25762 https://github.com/opencv/opencv/issues/23242
Relates https://github.com/opencv/opencv/issues/25763 https://github.com/opencv/opencv/issues/19091
Although `cv.Mat` has already been introduced to workaround this problem, people do not know it and it kind of leads to confusion with `numpy.array`. This patch adds a "switch" to turn off the auto multichannel feature when the API is from cv::dnn::Net (more specifically, `setInput`) and the parameter is of type `Mat`. This patch only leads to changes of three places in `pyopencv_generated_types_content.h`:
```.diff
static PyObject* pyopencv_cv_dnn_dnn_Net_setInput(PyObject* self, PyObject* py_args, PyObject* kw)
{
...
- pyopencv_to_safe(pyobj_blob, blob, ArgInfo("blob", 0)) &&
+ …
```
> python: attempts to fix 3d mat parsing problem for dnn

- modules/java/android_sdk/build.gradle.in
Now OpenCV Android SDK doesn't always require kotlin plugin. Kotlin code is compiled only if the application uses kotlin plugin.
Fixes #24663 
> Fixed kotlin requirement in Android build.gradle

- modules/3d/src/octree.cpp
Error message example:
```
/home/ubuntu/Projects/opencv/modules/3d/src/octree.cpp: In member function ‘void cv::Octree::getPointCloudByOctree(cv::OutputArray, cv::OutputArray)’:
/home/ubuntu/Projects/opencv/modules/3d/src/octree.cpp:414:36: error: converting to ‘std::stack<std::tuple<cv::Ptr<cv::OctreeNode>, unsigned int, unsigned int, unsigned int> >::value_type {aka std::tuple<cv::Ptr<cv::OctreeNode>, unsigned int, unsigned int, unsigned int>}’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {cv::Ptr<cv::OctreeNode>&, unsigned int, unsigned int, unsigned int}; <template-parameter-2-2> = void; _Elements = {cv::Ptr<cv::OctreeNode>, unsigned int, unsigned int, unsigned int}]’ …
```
> Fixed 32-bit build with some GCC versions

- modules/dnn/src/layers/concat_layer.cpp
- modules/dnn/src/layers/slice_layer.cpp
- modules/dnn/test/test_onnx_importer.cpp
All test data and models for PR are located [#1190](https://github.com/opencv/opencv_extra/pull/1190)
This PR fixes issue reised when importing batched  vanilla `Attention` layer from `PyTorch` via ONNX. Currently batched version of `Attention` layer in PyTorch [has unflatten operation inside](https://github.com/pytorch/pytorch/blob/e3b3431c4203e9eeead48f96d4afd462f0b81de5/torch/nn/functional.py#L5500C17-L5500C31). `unflatten` operation causes issue in `reshape` layer (see the Reshape_2 in the graph below) due to incorrect output of `slice` layer. This PR particularly fixes `slice` and `concat` layers to handle `unflatten` operation. 
> Support for `Unflatten` operation requred by `Attention` layer - 4.x

- modules/imgproc/test/test_canny.cpp
- modules/imgproc/test/test_color.cpp
- modules/imgproc/test/test_convhull.cpp
- modules/imgproc/test/test_filter.cpp
- modules/imgproc/test/test_imgwarp.cpp
- modules/imgproc/test/test_pc.cpp
- modules/imgproc/test/test_templmatch.cpp
Final cleanup will be done in 5.x after regular merge.
Some tests have been reworked, some required only slight modifications.
> imgproc: remove C-API usage from tests

- modules/imgcodecs/src/grfmt_jpeg.cpp
In case of corrupted JPEG, imread would still return a JPEG of the proper size (as indicated by the header) but with some uninitialized values. I do not have a short reproducer I can add as a test as this was found by our fuzzers.
> Make sure all the lines of a JPEG are read

- modules/videoio/src/cap_ffmpeg_impl.hpp
This is an attempt to fix https://github.com/opencv/opencv/issues/4362; It probably needs discussion/review.
Similar to this issue originally reported in 2012 (but which also has comments from 2023), I have a video where it seems like OpenCV does not read all frames.
I put the problematic video file here: https://github.com/dietmar/opencv/blob/problem_video/samples/data/interviewsample.mp4
I received this file from a co-worker, unfortunately I don't know how exactly it was produced. It's the first 3.5 minutes of this video: https://www.youtube.com/watch?v=YawI85U7QtA
The problem I encounter is with looping the video's frames; OpenCV stops way …
> Don't rely on nb_frames to be correct

- modules/core/include/opencv2/core/hal/intrin_cpp.hpp
- modules/core/include/opencv2/core/hal/intrin_math.hpp
- modules/core/test/test_intrin_utils.hpp
This patch adds v_erf, which is needed by https://github.com/opencv/opencv/pull/25147.
```
```
> core: add v_erf

- modules/core/include/opencv2/core/cvdef.h
- modules/core/include/opencv2/core/hal/intrin.hpp
- modules/core/include/opencv2/core/hal/intrin_neon.hpp
- modules/core/test/test_intrin_utils.hpp
Related: #25743
Currently, the type for the half-precision floating point data in the OpenCV source code is `__fp16`, which is a unique(?) type supported by the ARM compiler. Other compilers have very limited support for `__fp16`, so in order to introduce more backends that support FP16 (such as RISC-V), we may need a the more general FP16 type.
In this patch, we use `hfloat` instead of `__fp16` in non-ARM code blocks, mainly affected parts are:
- `core/hal/intrin.hpp`: Type Traits, REG Traits and `vx_` interface.
- `core/hal/intrin_neon.hpp`: Universal Intrinsic API for FP16 type.
- `core/test/test_intrin_utils.hpp`: Usage of Univseral Intrinsic
- `core/include/opencv2/core/cvdef.h`: Definition of class `hfloat`
If I understand correctly, class `hfloat` acts as a wrapper around FP16 …
> Use `hfloat` instead of `__fp16`.

- modules/calib3d/src/chessboard.cpp
- modules/calib3d/test/test_chesscorners.cpp
This pull request closes the issue #25806.
The issue doesn't require any documentation - it's quite intuitive that the detection result shouldn't depend on the color of the marker's tile.
> Enable checkerboard detection with a  central / corner marker on a black tile

- modules/dnn/perf/perf_layer.cpp
- modules/dnn/src/layers/elementwise_layers.cpp
- modules/dnn/src/opencl/activations.cl
- modules/dnn/test/test_onnx_conformance.cpp
- modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
- modules/dnn/test/test_onnx_importer.cpp
Depends on https://github.com/opencv/opencv/pull/25872.
Merge wtih https://github.com/opencv/opencv_extra/pull/1189.
Part of the acceleration of ViTs inference with dnn.
Tested on Apple M1 with test case `Layer_Elementwise.elementwise/0`. Data in milliseconds.
```
Name of Test                                 gelu   gelu.patch gelu.patch
vs
gelu
(x-factor)
VIT_B_32::DNNTestNetwork::OCV/CPU                                       245.312   233.760      1.05
elementwise::Layer_Elementwise::({ 1, 50, 3072 }, "Gelu", OCV/CPU)       1.604     0.938       1.71
```
```
Name of Test                                gelu   gelu.patch gelu.patch
vs
gelu
(x-factor)
VIT_B_32::DNNTestNetwork::OCV/CPU                                       40.041    38.357      1.04 …
```
> dnn: accelerate gelu via vectorized erf

- doc/opencv.bib
- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/src/approx.cpp
- modules/imgproc/test/test_approxpoly.cpp
merge PR with <https://github.com/opencv/opencv_extra/pull/1179>
This PR is based on the paper [View Frustum Optimization To Maximize Object’s Image Area](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=1fbd43f3827fffeb76641a9c5ab5b625eb5a75ba).
I needed to reduce the number of vertices of the convex hull so that the additional area was minimal, andall vertices of the original contour enter the new contour.
Initially in the contour of n vertices, at each stage we consider the intersection points of the lines formed by each adjacent edges. Each of these intersection points will form a triangle with vertices through which lines pass. Let's choose a triangle with the minimum area and merge the two vertices at the intersection point. We continue until there are more vertices …
> Add a new function that approximates the polygon bounding a convex hull with a certain number of sides

- modules/dnn/src/cuda4dnn/init.hpp
- modules/dnn/src/net_impl_backend.cpp
- modules/dnn/src/registry.cpp
- modules/dnn/test/test_common.hpp
- modules/dnn/test/test_onnx_conformance.cpp
Fixes #21461
~This is a build-time solution that reflects https://github.com/opencv/opencv/blob/4.10.0/modules/dnn/src/cuda4dnn/init.hpp#L68-L82.~
~We shouldn't add an invalid target while building with `CUDA_ARCH_BIN` < 53.~
_(please see [this discussion](https://github.com/opencv/opencv/pull/25880#discussion_r1668074505))_
This is a run-time solution that basically reverts [these lines](https://github.com/opencv/opencv/commit/d0fe6ad10967fd2b007a4cf83b00d6f8446deb42#diff-757c5ab6ddf2f99cdd09f851e3cf17abff203aff4107d908c7ad3d0466f39604L245-R245).
I've debugged these changes, [coupled with other fixes](https://github.com/gentoo/gentoo/pull/37479), on [Gentoo Linux](https://www.gentoo.org/) and [related tests passed](https://github.com/user-attachments/files/16135391/opencv-4.10.0.20240708- …
> 🐛 Fix CUDA for old GPUs without FP16 support

- modules/imgproc/test/test_templmatch.cpp
Fix after #25842
New rewritten `templMatch` test takes too long on slow platforms (RISC-V via QEMU). Reduced template sizes to speed up the test (150 sec -> 25 sec with x86_64 Debug configuration).
> imgproc: reduce template sizes in templMatch test

- doc/tutorials/dnn/dnn_yolo/dnn_yolo.markdown
[](https://github.com/opencv/opencv/pull/25794)
I found there is a mistake in the document that how to use yolov10, which that the "--model" is miswrite to yolov8n.onnx
> Fix the mistake about yolov10 inference step in dnn_yolo.markdown

- modules/core/include/opencv2/core/hal/intrin_math.hpp
Resolves https://github.com/opencv/opencv/pull/25872#issuecomment-2213269289
```
```
> core: fix compilation problem with v_erf

- modules/gapi/src/backends/onnx/gonnxbackend.cpp
> handling I32/I64 data types in G-API ONNX back-end

- modules/core/include/opencv2/core/base.hpp
- modules/core/include/opencv2/core/mat.hpp
- modules/core/src/matrix.cpp
- modules/core/src/system.cpp
This fixes https://github.com/opencv/opencv/issues/25065
> Mark cv::Mat(Mat&&) as noexcept

- modules/core/include/opencv2/core/hal/intrin.hpp
_tzcnt_u32 is not supported for ARM64EC, so avoid to use it.
Close https://github.com/opencv/opencv_contrib/issues/3767
> core: hal: avoid to use _tzcnt_u32 for ARM64EC

- modules/calib3d/misc/python/test/test_calibration.py
- modules/calib3d/src/calibration.cpp
> calib3d: fix Rodrigues CV_32F and CV_64F type mismatch in projectPoints

- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_onnx_importer.cpp
This PR adds support for const inputs for reducing the layer. Particularly, it fixes the following case. The test model and data are located in [1194](https://github.com/opencv/opencv_extra/pull/1194)
> Fix Reduce layer for cosnt inputs

- modules/dnn/src/layers/reduce_layer.cpp
- modules/dnn/test/test_layers_1d.cpp
This PR introduces test for `Reduce` layer to test its functionality for 1D arrays
> 1D test for Reduce layer

- modules/core/include/opencv2/core.hpp
- modules/core/src/system.cpp
- modules/videoio/src/cap_gphoto2.cpp
`throw()` was deprecated in C++11 and eliminated in C++17. `noexcept` is the appropriate replacement.
> throw() -> noexcept

- modules/objc/generator/gen_objc.py
Fixes #25926
We should include namespaces when generating swift bindings to avoid name conflicts.
> Resolve Swift method name conflicts by adding missing namespace

- modules/objdetect/src/aruco/charuco_detector.cpp
- modules/objdetect/test/test_charucodetection.cpp
CharucoDetectorImpl::detectBoard finds temporary markers when none are provided but those are discarded when
charucoDetectorImpl::checkBoard is called.
> Properly check markers when none are provided.

- CMakeLists.txt
Fix https://github.com/opencv/opencv/issues/25920 by only respecting `CMAKE_CUDA_ARCHITECTURES` when it is specified by the user.
> `cuda`: prevent `CMAKE_CUDA_ARCHITECTURES` default from overiding OpenCV architecture search (issue 25920)

- modules/core/include/opencv2/core.hpp
- modules/core/include/opencv2/core/mat.hpp
- modules/core/src/arithm.cpp
- modules/core/src/copy.cpp
- modules/core/src/mean.dispatch.cpp
- modules/core/src/minmax.dispatch.cpp
- modules/core/src/norm.cpp
- modules/core/src/sum.dispatch.cpp
- modules/core/src/umatrix.cpp
- modules/core/test/test_arithm.cpp
- modules/ts/src/ts_func.cpp
Partially cover https://github.com/opencv/opencv/issues/25895
> Mask support with CV_Bool in ts and core

- modules/core/src/matrix_wrap.cpp
This fix is useless in 4.x and fixes harmless overflows in 5.x due to type being potentially bigger than 32.
This belongs to 4.x as it is closer to the intended meaning.
> Avoid future integer overflow in _OutputArray::create

- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/src/grfmt_avif.cpp
- modules/imgcodecs/src/grfmt_base.cpp
- modules/imgcodecs/src/grfmt_base.hpp
- modules/imgcodecs/src/grfmt_tiff.cpp
- modules/imgcodecs/src/loadsave.cpp
- modules/imgcodecs/test/test_avif.cpp
Related : #24855
adds `getFrameCount()` member function to BaseImageDecoder.
> add getFrameCount() member function to BaseImageDecoder

- modules/python/src2/gen2.py
> python: prefer cv::Mat over cv::UMat in python binding

- modules/js/perf/perf_64bits.js
- modules/js/perf/perf_helpfunc.js
- modules/js/perf/perf_imgproc/perf_blur.js
- modules/js/perf/perf_imgproc/perf_cvtcolor.js
- modules/js/perf/perf_imgproc/perf_dilate.js
- modules/js/perf/perf_imgproc/perf_erode.js
- modules/js/perf/perf_imgproc/perf_filter2D.js
- modules/js/perf/perf_imgproc/perf_gaussianBlur.js
- modules/js/perf/perf_imgproc/perf_medianBlur.js
- modules/js/perf/perf_imgproc/perf_pyrDown.js
- modules/js/perf/perf_imgproc/perf_remap.js
- modules/js/perf/perf_imgproc/perf_resize.js
- modules/js/perf/perf_imgproc/perf_scharr.js
- modules/js/perf/perf_imgproc/perf_sobel.js
- modules/js/perf/perf_imgproc/perf_threshold.js
- modules/js/perf/perf_imgproc/perf_warpAffine.js
- modules/js/perf/perf_imgproc/perf_warpPerspective.js
`modules/js/perf/perf_helpfunc.js` and target tests, e.g. perf_gaussianBlur.js, contain "const isNodeJs", leading to re-definition when using associated *.html files: 
```html
//... script above
<script src="https://cdnjs.cloudflare.com/ajax/libs/benchmark/2.1.4/benchmark.js"></script>$
<script src="../../opencv.js" type="text/javascript"></script>$
<script src="../base.js"></script>$
<script src="../perf_helpfunc.js"></script>$
<script src="./perf_gaussianBlur.js"></script>$
</body>$
</html>$
```
`perf_helpfunc.js` was imported (which globally defined `const isNodeJs`) and then `perf_gussianBlur.js` was imported (which globally defined `const isNodeJs`). Changing them to `var` resolves scoping issues when running in browser, while maintaining nodejs support. 
Special thanks to …
> fix: js/html perf tests

- modules/videoio/cmake/detect_obsensor.cmake
Current code using `CMAKE_SOURCE_DIR` and it works well if opencv is standalone CMake project, but in case of building OpenCV as part of a larger CMake project (e.g. one that includes `opencv` and `opencv_contrib`) this path is incorrect, unlike `OpenCV_SOURCE_DIR`
> Fix path to 3rdparty cmake.

- modules/dnn/src/layers/elementwise_layers.cpp
- modules/dnn/src/layers/nary_eltwise_layers.cpp
related: #25199
The regressions introduced in https://github.com/opencv/opencv/pull/25147 and https://github.com/opencv/opencv/pull/25630
> fix compilation errors caused by namespace

- modules/core/include/opencv2/core/cuda.hpp
- modules/core/src/cuda/gpu_mat.cu
- modules/core/src/cuda_gpu_mat.cpp
To be on par with `cv::Mat`, let's add `cv::cuda::GpuMat::getStdAllocator()` This is useful anyway, because when a user wants to use custom allocators, he might want to resort to the standard default allocator behaviour, not some other allocator that could have been set by `setDefaultAllocator()`
> Adding getStdAllocator() to cv::cuda::GpuMat

- modules/core/src/matrix.cpp
- modules/core/test/test_allocator.cpp
Current implementation does not initialize cv::Mat::allocator filed even, if non standard allocator is used globally.
> Set and check allocator pointer for all cv::Mat instances

- modules/calib3d/src/calibinit.cpp
Idea was mentioned in `Section III-B. New Heuristic for Quadrangle Linking` of `Rufli, Martin & Scaramuzza, Davide & Siegwart, Roland. (2008). Automatic Detection of Checkerboards on Blurred and Distorted Images. 2008 IEEE/RSJ International Conference on Intelligent Robots and Systems, IROS. 3121-3126. 10.1109/IROS.2008.4650703` (https://rpg.ifi.uzh.ch/docs/IROS08_scaramuzza_b.pdf):
```
* For each candidate pair, focus on the quadrangles they belong to and draw two straight lines passing through the midsections of the respective quadrangle edges (see Fig. 6).
* If the candidate corner and the source corner are on the same side of every of the four straight lines drawn this way (this corresponds to the yellow shaded area in Fig. 6), then the corners are successfully matched.
```
By …
> Improve corners matching in ChessBoardDetector::NeighborsFinder::findCornerNeighbor

- modules/calib3d/include/opencv2/calib3d.hpp
- modules/calib3d/src/fisheye.cpp
- modules/calib3d/test/test_fisheye.cpp
The function covered the case, when the fisheye image was undistorted with new camera matrix found with estimateNewCameraMatrixForUndistortRectify.
> Added fisheye::distortPoints with non-identity projection matrix

- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/src/color.cpp
- modules/imgproc/src/color.hpp
- modules/imgproc/src/color_yuv.dispatch.cpp
- modules/imgproc/src/hal_replacement.hpp
- modules/imgproc/test/test_color.cpp
The xxxApprox to implement HAL functions with less bits for arithmetic of FP.
The hint was introduced in #25792 and #25911
> Added xxxApprox overloads for YUV color conversions in HAL and AlgorithmHint to cvtColor

- modules/imgproc/src/hal_replacement.hpp
- modules/imgproc/src/pyramids.cpp
- modules/imgproc/test/test_filter.cpp
Resolves #25976
* HAL added for offset support so that border pixels can be fetched from outside of the image ROI (see `BORDER_ISOLATED` parameter)
* IPP removed since there is `pyrUp` instead of `pyrDown` and there's no easy way to fix this other than rewriting it from scratch
* replaced old C call by modern `cv::pyrDown`
> pyrDown: offset HAL added, IPP removed

- modules/imgproc/misc/python/test/test_imgproc.py
- modules/imgproc/src/drawing.cpp
Fixes https://github.com/opencv/opencv-python/issues/986
The PR changes checks in the function to disallow empty input.
> Fixed asserts in fillPoly

- modules/core/include/opencv2/core/check.hpp
- modules/core/src/check.cpp
- modules/imgproc/src/color.hpp
- modules/imgproc/src/color.simd_helpers.hpp
- modules/imgproc/test/test_color.cpp
> imgproc: add specific error code when cvtColor is used on an image with an invalid number of channels

- 3rdparty/openvx/README.md
Fix three typos and one trailing space.
> Fix typo in openvx readme

- doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown
fix #26035
The tutorial of basic image operations https://docs.opencv.org/4.10.0/d3/df2/tutorial_py_basic_ops.html is still recommending using itemset. However this is now a deprecated functionality in Numpy 2.+ and in 1.+ there is a deprecation warning (or at least that is what they say).  
We can still keep the warning about single pixel accessing as in the big picture that is still valid to not encourage people to access single pixels like this, but .itemset ain't a good option anymore.
> Docfix - Remove notice on using deprecated itemset

- modules/videoio/src/cap_dshow.cpp
> Fix: reduce redundant code by optimizing device name retrieval

- modules/ml/src/rtrees.cpp
Speedup `DTreesImplForRTrees::getVotes` method in about x2 times.
`Mat` objects are usually not expensive for creation or copying. But if algorithm itself is fast, operations on `Mat` objects start to take significant time. Naive extraction of loop invariant temporary `Mat` wrapper object creation allows to decrease `getVotes` method run time in about x2 times.
> speedup random forest getVotes method.

- modules/videoio/src/cap_dshow.cpp
Fixes https://github.com/opencv/opencv/issues/26044
> Free Variant variable after usage in DShow back-end

- modules/core/misc/python/pyopencv_core.hpp
- modules/dnn/misc/python/test/test_dnn.py
- modules/python/src2/cv2.cpp
- modules/python/src2/cv2_convert.cpp
- modules/python/src2/cv2_numpy.cpp
- modules/python/src2/typing_stubs_generation/api_refinement.py
- modules/python/test/test_misc.py
This PR add support boolean input/output binding in python. The issue what mention in ticket https://github.com/opencv/opencv/issues/26024 and the PR soleves it. Data and models are located in [here](https://github.com/opencv/opencv_extra/pull/1201)
> Add support for boolan input/outputs in python bindings

- modules/dnn/test/test_onnx_conformance_layer_filter__cuda_denylist.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter__cuda_fp16_denylist.inl.hpp
Introduced in: https://github.com/opencv/opencv/pull/25998
Related issue: https://github.com/opencv/opencv/issues/25999
> Supress more ONNX conformance test cases for quant-dequant with CUDA.

- modules/dnn/src/layers/concat_layer.cpp
- modules/dnn/src/layers/permute_layer.cpp
- modules/dnn/src/layers/pooling_layer.cpp
- modules/dnn/src/layers/reorg_layer.cpp
- modules/dnn/src/layers/reshape_layer.cpp
- modules/dnn/src/layers/slice_layer.cpp
- modules/dnn/src/ocl4dnn/include/common.hpp
- modules/dnn/src/ocl4dnn/src/common.cpp
- modules/dnn/src/opencl/ocl4dnn_pooling.cl
- modules/dnn/src/opencl/permute.cl
Added bool, int8, uint8, int32, int64 support for concat, permute, reorg, reshape, slice layers for OpenCL backend.
Added native int64 output indices support for maxpool layer for OpenCL backend.
Everything is already covered with tests. 
> Added integer and bool support to dnn OpenCL layers

- modules/core/test/test_operations.cpp
Ensure rounding mode for lrint to fix interference with 3rd party libraries
> Fix rounding mode for test

- modules/dnn/src/cuda4dnn/csl/tensor.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter__cuda_denylist.inl.hpp
This PR fixes CUDA backend to support matrixes with number of axes > 6
> Support Matrices with axes > 6 CUDA

- modules/imgproc/src/demosaicing.cpp
- modules/imgproc/test/test_color.cpp
SIMD version of CV_DESCALE is not correct. It should be implemented using v_dotprod.
What's more, the stop condition of vector operation should be `bayer < bayer_end - 14` because we just need to make sure result is safely stored into `dst`.
Closes: https://github.com/opencv/opencv/issues/25823
> Correct Bayer2Gray u8 SIMD

- modules/dnn/include/opencv2/dnn/all_layers.hpp
- modules/dnn/perf/perf_layer.cpp
- modules/dnn/src/init.cpp
- modules/dnn/src/layers/topk_layer.cpp
- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_onnx_importer.cpp
Merge with https://github.com/opencv/opencv_extra/pull/1200
Partially fixes #22890 and #20258
To-do:
Perf:
M1 (time in millisecond)
| input shape     | axis | dnn  | ort  |
| --------------- | ---- | ---- | ---- |
| (1000, 100)     | 0    | 1.68 | 4.07 |
| (1000, 100) K5  | 0    | 1.13 | 0.12 |
| (1000, 100)     | 1    | 0.96 | 0.77 |
| (100, 100, 100) | 0    | 10.00 | 31.13 |
| (100, 100, 100) | 1    | 7.33 | 9.17 |
| (100, 100, 100) | 2    | 7.52 | 9.48 |
M2 (time in milisecond)
| input shape     | axis | dnn  | ort  |
| --------------- | ---- | ---- | ---- |
| (1000, 100)     | 0    | 0.76 | 2.44 |
| (1000, 100) K5 | 0 | 0.68 | 0.07 |
| (1000, 100)     | 1    | 0.41 | 0.50 |
| (100, 100, 100) | 0    | 4.83 | 17.52|
| (100, 100, 100) | 1    | 3.60 | 5.08 |
| (100, 100, 100) | 2    | …
> dnn: add ONNX TopK

- modules/calib3d/src/calibinit.cpp
I didn't do everything right the way I wanted at #25991. I forgot that `edge_len` is edge **squared** length as well as `thresh_scale` is threshold for **squared** scale. So, I wanted to increase scale by `sqrt(2)` times (idea is to use quad diagonal instead of quad side) and therefore `thresh_scale` should be equal to `sqrt(2)^2 = 2`.
And refactor variables names to explicitly indicate that they are squared, so that no one else falls into this trap
I tested this PR with benchmark
```
python3 objdetect_benchmark.py --configuration=generate_run --board_x=7 --path=res_chessboard --synthetic_object=chessboard
```
PR increases detected chessboards number by `1/2%`:
```
cell_img_size = 100 (default)
before
category  detected chessboard  total detected chessboard  total chessboard  average …
```
> Increase neighbors search radius for corners in ChessBoardDetector:findQuadNeighbors

- modules/imgproc/perf/perf_warp.cpp
Also removed Android branch in tests. It's not relevant any more.
Extra: https://github.com/opencv/opencv_extra/pull/1204
> Extended perf tests for warpPerspective to cover channels too

- modules/core/include/opencv2/core/types.hpp
- modules/core/test/test_misc.cpp
- modules/features2d/src/keypoint.cpp
- modules/imgproc/src/cornersubpix.cpp
- modules/imgproc/test/test_cornersubpix.cpp
- modules/stitching/test/test_matchers.cpp
close #26016 
Related https://github.com/opencv/opencv_contrib/pull/3778
> imgproc: use double to determine whether the corners points are within src

- modules/dnn/src/layers/einsum_layer.cpp
This PR fixed buffer allocation issue in Einsum layer that causes segmentation fault on 32bit platforms. Related issue #26008 
> Einsum buffer allocation fix

- cmake/OpenCVCompilerOptimizations.cmake
- cmake/checks/cpu_fp16.cpp
- cmake/checks/cpu_rvv_fp16.cpp
- modules/core/include/opencv2/core/cv_cpu_dispatch.h
- modules/core/include/opencv2/core/cv_cpu_helper.h
- modules/core/include/opencv2/core/cvdef.h
- modules/core/include/opencv2/core/hal/intrin.hpp
- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
- modules/core/src/system.cpp
- modules/core/test/test_intrin_utils.hpp
This patch is going to add FP16 support for RISC-V, mainly includes the following:
- Introduce `zvfhmin` extension as FP16 backend
- Introduce `zvfh` extension as RVV_ZVFH backend
- Add FP16 related operations of RVV to Universal Intrinsic
More information about `zvfhmin` and `zvfh`: [RVV Spec 18.4 & 18.5](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#184-zvfhmin-vector-extension-for-minimal-half-precision-floating-point)
This path is tested on QEMU and k230, with ...
- Compiler: Clang ~18.1~ trunk and GCC ~14.0.1~ 14.1 & 14.2
At present, only Clang 18 and GCC 14 fully support `zvfhmin` and `zvfh`, see: 
|                  | Clang 18 | Clang 17   | GCC 14.1 | GCC 13.3 |
| ---------------- | -------- | ---------- | -------- | -------- |
| Vector Intrinsic | 12000    | 12000 …
> Add FP16 support for RISC-V

- modules/core/perf/opencl/perf_arithm.cpp
- modules/core/src/mathfuncs.cpp
Add the following cases in opencv_perf_core:
* OCL_PowFixture_iPow.iPow/0, where GetParam() = (640x480, 8UC1)
* OCL_PowFixture_iPow.iPow/2, where GetParam() = (640x480, 16UC1)
iPow8u and iPow16u failed to call to simd accelerating while executing.
Fix the bug by changing the input type of iPow_SIMD function.
> Fixed the simd bugs of iPow8u and iPow16u

- modules/imgproc/src/median_blur.simd.hpp
In the process of evolving Universal intrinsic from "wide" to "scalable", we have widly appended `|| CV_SIMD_SCALABLE` to the macro `CV_SIMD`. But it seems that we missed two macros in median blur, and this patch fixes this part.
> Enable `CV_SIMD_SCALABLE` for median blur.

- modules/core/src/mathfuncs.cpp
The issue was highlighted in https://github.com/opencv/opencv/pull/26061
> Removed duplicated code in Pow implementation that triggers wrong assert on Intel iGPU

- CMakeLists.txt
- doc/tutorials/introduction/config_reference/config_reference.markdown
- doc/tutorials/introduction/env_reference/env_reference.markdown
* Disabled `WITH_1394` option by default - this is not commonly used backend. I think it has been enabled by mistake for many years. It adds confusion and in many tutorials it either got disabled explicitly or is treated as required dependency (i.e. extra packages installed).
* Added missing documentation for config and environment variables for _highgui_ framebuffer backend
> build/doc: disabled libdc1394 by default, documented framebuffer options

- modules/imgcodecs/src/grfmt_avif.cpp
This is to increase the compatibility with AVIF files (especially older ones).
This fixes https://github.com/opencv/opencv/issues/26011
> Disable strict mode when reading avif files

- modules/videoio/src/cap_v4l.cpp
Wrong color conversion mode caused bad colors for NV12 camera input format (RGB instead of BGR).
> videoio: fix V4L backend with NV12 input format

- modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp
Workaround the #25795 Issue by adopting the solution from #21044 issue.
Relates #20914
> Workaround for division by zero, issue #25795

- modules/core/src/minmax.cpp
> Added offset for HAL as ofs2idx expects 1-based index

- modules/core/include/opencv2/core/hal/intrin_lasx.hpp
Fixed a bug that occurred when compiling with the clang18 compiler.
> Resolve compilation bug on LoongArch platform

- cmake/OpenCVCompilerOptimizations.cmake
Installation process has been broken due to extra options added for RISC-V in #25743. Weekly builds failed because the are using `ninja install` (https://github.com/opencv/ci-gha-workflow/actions/runs/10640797355).
It should be possible to add extra options in custom build by modifying `CMAKE_CXX_FLAGS` or `OPENCV_EXTRA_CXX_FLAGS`.
> RISC-V: fix installation process

- doc/opencv.bib
- modules/calib3d/include/opencv2/calib3d.hpp
---
Currently I see this:
To be check on documentation CI since my doxygen version is too old and formulas are not correctly rendered on my computer.
---
Fix link for "RANSAC for Dummies" tutorial.
> Fix typo with cameramatrix command for documentation

- modules/dnn/include/opencv2/dnn/all_layers.hpp
- modules/dnn/src/init.cpp
- modules/dnn/src/layers/harmax.cpp
- modules/dnn/src/onnx/onnx_importer.cpp
- modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
This PR add support for `Hardmax` layer, which as previously listed in conformance deny list. 
> Add Support for Hardmax Layer

- modules/core/test/test_intrin_utils.hpp
This PR try to fix https://github.com/opencv/opencv/issues/25922
Because the `hfloat` is defined as explicit conversion, the test code should be modified as it. The `vx_setall_f16` problem has already been fixed.
> Fix hfloat, float16_t, float collision in 5.x about v_exp and v_log

- doc/tutorials/imgproc/imgtrans/warp_affine/warp_affine.markdown
Currently, X is a math symbol while T is not. I think making T a math symbol is feels more consistent.
> Make T a math symbol

- modules/imgproc/src/color_rgb.simd.hpp
- modules/imgproc/src/imgwarp.cpp
(1) cv::convertMaps: the branch [else if( m1type == CV_32FC2 && dstm1type == CV_16SC2 ) if( nninterpolate )] is unreachable,
as the condition is satisfied in lines 1959 to 1961, calculated in advance and return directly.
(2) mRGBA2RGBA<uchar>: dst[0], dst[1], dst[2] and dst[3] is calculated repeatedly. Introduced in https://github.com/opencv/opencv/pull/13440
> Remove the redundant codes of cv::convertMaps and mRGBA2RGBA<uchar>

- cmake/OpenCVCompilerOptimizations.cmake
Fix specialized RISC-V builds after FP16 support integration (#25743). Leave multiple `-march` flags instead of combining them into one. This process is unreliable anyway and should be avoided (see related #25901).
Also explicitly defined `CPU_${XXX}_FLAGS_ON` flags.
Now there are four possible `CPU_BASELINE` configurations for mainline compilers (GCC, Clang):
- `DETECT` :arrow_right:  `-march=rv64gc` (default, no extra features)
- `RVV` :arrow_right:  `-march=rv64gc_v`
- `FP16`  :arrow_right:  `-march=rv64gc_v_zvfhmin`
- `RVV_ZVFH`  :arrow_right:  `-march=rv64gc_v_zvfhmin_zvfh`
Weekly build failures: https://github.com/opencv/ci-gha-workflow/actions/runs/10663654318
> RISC-V: fix XuanTie and Andes builds

- modules/imgproc/src/resize.cpp
When there is no point falling right, an hypothetical value is computed (but unused) using an uninitialized ofst. This triggers warnings in the sanitizers.
Including those values in the for loops is also possible but messy when SIMD is involved.
> Avoid uninitialized value read in resize.

- CMakeLists.txt
- cmake/OpenCVDetectCXXCompiler.cmake
- cmake/OpenCVDownload.cmake
* resolves #26099 - do not use `enable_language`
* removed some older code which seem to be unnecessary for modern systems (changes in `CMAKE_LIBRARY_PATH`/`CMAKE_INCLUDE_PATH`)
* use correct `GIT_EXECUTABLE` in `ocv_init_download_mirror`
* moved `CMAKE_SIZEOF_VOID_P` zero check to appropriate location (`DetectCXXCompiler.cmake`)
> build: minor changes for cmake 3.30 and some cleanup

- modules/imgproc/test/test_color.cpp
> Added bit-exact tests for RGB2Gray

- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
> RISC-V: remove statically initialized global RVV variables (4.x)

- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
Steps to reproduce:
* RISC-V build without baseline RVV support, but with dispatched RVV code
Actual behavior:
* Illegal instruction during library initialization
Solution:
* avoid global variables initialized using RVV instructions
**Note:** should fix weekly Andes build on 5.x branch (failed testing with qemu), because it has dispatched code enabled after FP16 PR integration to 5.x
> RISC-V: remove statically initialized global RVV variables (5.x)

- modules/core/perf/opencl/perf_arithm.cpp
Connected PR with updated sanity data: https://github.com/opencv/opencv_extra/pull/1206
> Added more data types to OCL flip() and rotate() perf tests

- modules/dnn/src/layers/hardmax.cpp
- modules/dnn/src/layers/harmax.cpp
- modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
Fix Hardmax Issue with backend mentioned in #26107 
>  Switch off OpenVINO backend for Hardmax

- modules/core/src/arithm.cpp
Solution similar to https://github.com/opencv/opencv/pull/12004
> Excluded nullptr leak to arithmetic HAL got from empty Mat.

- modules/imgproc/perf/perf_warp.cpp
Connected PR: https://github.com/opencv/opencv_extra/pull/1207
> Added more data types for warpAffine() perf tests

- modules/core/include/opencv2/core/cuda_types.hpp
- modules/core/include/opencv2/core/cvdef.h
According to [cppreference.com compiler support table](https://en.cppreference.com/w/cpp/compiler_support/17), `nvcc` supports `[[nodiscard]]` from version 11.
Related: https://github.com/opencv/opencv/pull/25659
> Add size() to CUDA PtrStepSz

- 3rdparty/ndsrvp/include/imgproc.hpp
- 3rdparty/ndsrvp/src/cvutils.cpp
- 3rdparty/ndsrvp/src/cvutils.hpp
- 3rdparty/ndsrvp/src/filter.cpp
From PR #25167: 
> #### Part 2 (Next PR)
> **Rough Estimate. Todo List May Change.**
> - [ImgProc](https://docs.opencv.org/4.x/dd/d8b/group__imgproc__hal__interface.html)
> - Filter
Filter implementation, further filter-applying functions would be based on this.
**The performance test sample may be lack of `CV_16U` in `src_type` and `dst_type`.**
|Name of Test|opencv perf imgproc TestFilter blank|opencv perf imgproc TestFilter rvp|opencv perf imgproc TestFilter blank vs opencv perf imgproc TestFilter rvp (x-factor)|
|Filter2d::TestFilter2d::(320x240, 3, BORDER_CONSTANT)|19.399|17.532|1.11|
|Filter2d::TestFilter2d::(320x240, 3, BORDER_REFLECT_101)|19.420|17.514|1.11|
|Filter2d::TestFilter2d::(320x240, 3, BORDER_REPLICATE)|19.358|17.465|1.11| …
> 3rdparty: NDSRVP - Part 2: Filter

- modules/core/include/opencv2/core/core_c.h
- modules/highgui/src/window_w32.cpp
- modules/highgui/src/window_winrt.cpp
Fixes https://github.com/opencv/opencv/issues/26142
Related to https://github.com/opencv/opencv/pull/26025
> Drop remaning C CV_FUNCTION_NAME as it's not used any more.

- modules/core/include/opencv2/core.hpp
Fixes #25784 
Update documentation for minMaxLoc to be more specific about when multi-channel images are and are not supported.
Testing:
Built documentation locally to check that updates were incorporated correctly.
> Documentation update for minMaxLoc

- modules/ts/include/opencv2/ts/ocl_perf.hpp
- modules/ts/include/opencv2/ts/ts_ext.hpp
- modules/ts/include/opencv2/ts/ts_gtest.h
- modules/ts/include/opencv2/ts/ts_perf.hpp
Modified both OpenCV part and GTest.
Used C++11 `override` in GTest code - I believe it's OK.
> ts: add some missing override markers

- modules/features2d/src/sift.simd.hpp
- modules/features2d/test/test_sift.cpp
Resolves #26139
Changes include:
* allocate `rawDst` with correct size - main change
* split `len` variable into multiple to avoid confusion
* add `const` modifiers to some variables for additional safety
* add reproducer test case from the issue
> features2d: fixed out of bounds access in SIFT

- modules/gapi/src/backends/fluid/gfluidimgproc_simd_avx2.hpp
- modules/imgproc/src/resize.cpp
* Build with AVX2 or AVX512 baseline, e.g. `-DCPU_BASELINE=AVX512_SKX`
* Build failed because of intrinsics using overloaded operators in specific code blocks
* use `v_add/v_sub` functions instead of `+/-` operators
> build: fix AVX2/AVX512 builds failed due to intrinsics operator usage

- doc/tutorials/dnn/dnn_yolo/dnn_yolo.markdown
- samples/dnn/object_detection.cpp
Looks like abandoned references to sample code were introduced here: https://github.com/opencv/opencv/pull/25710
> Fixed code snippets in Yolo tutorial.

- platforms/linux/flags-riscv64.cmake
Support RISC-V RVV FP16 after corresponding build changes from 4.x has been merged (shift options related to CPU features to the RISC-V/AArch64 toolchain files).
**Note:** option names are up to discussion
**Note:** [zvfhmin](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#184-zvfhmin-vector-extension-for-minimal-half-precision-floating-point) - conversions only, [zvfh](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#185-zvfh-vector-extension-for-half-precision-floating-point) - full arithmetic support.
> build: enable RISC-V FP16 support in the toolchain

- modules/calib3d/src/sqpnp.cpp
- modules/calib3d/src/sqpnp.hpp
Mirror most recent changes from https://github.com/terzakig/sqpnp/pull/24
- rank revealing QR in nullspace computation
- sqrt-free Cholesky (i.e., L*D*Lt) in the SQP solution
- replaced divisions with multiplications by inverses
- simplified checks in computeRowAndNullspace()
- removed unnecessary negations
- broke some dependency chains with parentheses
- minor other changes
> SQPnP solver updates

- modules/features2d/src/mser.cpp
cvAlloc/cvFree was the only use of C-API in _features2d_ source code.
> C-API cleanup: use AutoBuffer in MSER (5.x)

- modules/video/src/hal_replacement.hpp
- OpenCV and OpenCV/Carotene implementations are derived from the same root and expect +- winsize border around the actual image and its derivatives. The functions get cv::Mat with the padded buffer like ROI.
- OpenCV and OpenCV/Carotene Scharr derivatives have the same assumption in design and use +1 pixel border of the input image.
- The border is already taken into account during pyramid allocation. It's filled by the image pixels, if available or with copyMakeBorder. [CopyMakeBorder](https://docs.opencv.org/4.x/d2/de8/group__core__array.html#ga2ac1049c2c3dd25c2b41bffe17658a36) call has ticky logic and allows passing ROI of the original image as destination.  The function recognizes it and fills the border, but does not make a copy. So the current implementation is efficient in this …
> Added HAL documentation note for out-of-bound hack in optical flow LK.

- modules/calib/include/opencv2/calib.hpp
- modules/calib/src/multiview_calibration.cpp
- modules/calib/test/test_cameracalibration.cpp
- modules/calib/test/test_fisheye.cpp
- modules/calib/test/test_multiview_calib.cpp
- samples/cpp/multiview_calibration_sample.cpp
- samples/python/multiview_calibration.py
- Added function overload for the simple case
- Added CV_Bool type support for masks
- `parallel_for_` for intrinsics calibration for faster inference
- Homogenize parameters order with other calibrateXXX functions
4 tests from MultiViewTest 298912 ms total before and 234068 ms total after the patch.
> Multiple calibrateMultiview improvements.

- modules/core/include/opencv2/core/hal/intrin_rvv071.hpp
Issue introduced in #25891 (https://github.com/opencv/ci-gha-workflow/actions/runs/11188809334/job/31165423898)
```
/opencv/modules/core/include/opencv2/core/hal/intrin_rvv071.hpp:360:36: error: template-id 'v_setall_<>' for 'cv::hal_baseline::v_int8x16 cv::hal_baseline::v_setall_(char)' does not match any template declaration
360 | template <> inline v_##_Tp##x##num v_setall_(__Tp v) { return v_setall_##suffix(v); }
|                                    ^~~~~~~~~
/opencv/modules/core/include/opencv2/core/hal/intrin_rvv071.hpp:363:1: note: in expansion of macro 'OPENCV_HAL_IMPL_RISCVV_INIT_SET'
363 | OPENCV_HAL_IMPL_RISCVV_INIT_SET(char, int8, s8, i8, 16)
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opencv/modules/core/src/precomp.hpp:88,
from …
```
> RISC-V: fix build with RVV 0.7.1

- modules/calib/test/test_multiview_calib.cpp
Two cases takes too much time especially on slower devices. Skipping them reduces total test duration from 147 to 55 seconds (Linux, Release build, i5-11600).
Related RISC-V weekly build failure: https://github.com/opencv/ci-gha-workflow/actions/runs/11188809334/job/31165424632
> calib: mark some multiview tests verylong

- modules/imgproc/src/drawing.cpp
- modules/imgproc/test/test_drawing.cpp
Fixes the bug described in #26130 
> Fix fillPoly drawing over boundaries

- modules/core/include/opencv2/core/core_c.h
- modules/core/src/rand.cpp
- modules/core/test/test_io.cpp
- modules/core/test/test_mat.cpp
- modules/core/test/test_rand.cpp
- modules/imgproc/test/test_imgwarp.cpp
- replace CV_RAND_UNI and NORMAL to cv::RNG::UNIFORM and cv::RNG::NORMAL.
> core: C-API cleanup: RNG algorithms in core(4.x)

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/merge.hpp
We have seen some performance gains after refactoring the SIMD loop code in OpenCV to be compatible with the RISC-V Vector backend. However, we still see a lot of gaps where we can use the HAL to implement RVV-specific optimizations to further improve performance/eliminate performance losses.
In the Core module, we find that the performance of the `merge` on `32F`/`64F` when channel is `3` or `4` is reduced in compared to the scalar version, especially on the BPI-F3 board (~0.5x). This patch add the HAL implementation for the merge function on RISC-V Vector.
- Performance result: compiled by `GCC 14.2` and `Clang 19.1.0`, tested on `k230` and `BPI-F3`
Compared to using UI, this patch (named `native` in the figure) eliminates the above performance loss, and the acceleration ratio is …
> Add the HAL implementation for the merge function on RISC-V Vector.

- modules/core/include/opencv2/core/hal/intrin_avx.hpp
- modules/core/include/opencv2/core/hal/intrin_avx512.hpp
- modules/core/include/opencv2/core/hal/intrin_cpp.hpp
- modules/core/include/opencv2/core/hal/intrin_lasx.hpp
- modules/core/include/opencv2/core/hal/intrin_lsx.hpp
- modules/core/include/opencv2/core/hal/intrin_math.hpp
- modules/core/include/opencv2/core/hal/intrin_msa.hpp
- modules/core/include/opencv2/core/hal/intrin_neon.hpp
- modules/core/include/opencv2/core/hal/intrin_rvv071.hpp
- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
- modules/core/include/opencv2/core/hal/intrin_sse.hpp
- modules/core/include/opencv2/core/hal/intrin_vsx.hpp
- modules/core/include/opencv2/core/hal/intrin_wasm.hpp
- modules/core/test/test_intrin_utils.hpp
This PR aims to implement `v_sincos(v_float16 x)`, `v_sincos(v_float32 x)` and `v_sincos(v_float64 x)`. 
Merged after https://github.com/opencv/opencv/pull/25891 and https://github.com/opencv/opencv/pull/26023
**NOTE:** 
Also, the patch changes already added `v_exp`, `v_log` and `v_erf` to pass parameters by reference instead of by value, to match API of other universal intrinsics.
TODO:
> Add support for v_sin and v_cos (Sine and Cosine)

- modules/objdetect/include/opencv2/objdetect/face.hpp
- modules/objdetect/src/face_recognize.cpp
- Implemented a new `create` method in `FaceRecognizerSF` to allow model and configuration loading from memory buffers (std::vector<uchar>), similar to the existing functionality in `FaceDetectorYN`.
- Updated `face_recognize.cpp` with a new constructor in `FaceRecognizerSFImpl` that supports buffer-based loading for both model weights and network configuration.
- Ensured compatibility with both file-based and buffer-based model loading by maintaining consistent backend and target settings across both constructors.
- This change improves flexibility, allowing FaceRecognizerSF to be instantiated from memory buffers, which is useful for dynamic model loading scenarios such as embedded systems or applications where models are loaded in-memory.
See details at …
> Added buffer-based model loading to FaceRecognizerSF

- modules/core/src/count_non_zero.simd.hpp
In that function, the floats are cast to int to be compared to 0.
But a float can be -0 or +0, hence
define CHECK_NZ_FP(x) ((x)*2 != 0)
to remove the sign bit. Except that can trigger the sanitizer:
runtime error: signed integer overflow: -1082130432 * 2 cannot be represented in type 'int'
Doing everything in uint instead of int is properly defined by the
standard.
> Fix sanitizer issue in countNonZero32f

- modules/core/include/opencv2/core/utility.hpp
- samples/cpp/tutorial_code/snippets/core_various.cpp
- [N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
This PR introduces a new interface to collect the last iteration time of the `cv::TickMeter` class.
Besides, two more minor changes are included:
1. Reorder the variables inside the `cv::TickeMeter::reset()` method so that the order matches the declaration of the variables, which makes visual inspection easier.
2. `const` correctness inside the `cv::TickMeter::stop()` method.
When using the `cv::TickMeter` in a loop or in a continuous processing application, it is sometimes useful to also know the time that the last iteration took, not only …
> Enhance cv::TickMeter to be able to get the last elapsed time

- modules/3d/test/test_undistort.cpp
- modules/core/test/test_dxt.cpp
- modules/core/test/test_math.cpp
- modules/ts/include/opencv2/ts.hpp
- modules/ts/src/ts_arrtest.cpp
Base class `ArrayTest` had two parallel data storages: `test_array` (raw pointers) and `test_mat` (`cv::Mat`). In this PR we get rid of the first one and temporarily substitute class interface to catch all calls to `test_array` member and transform them to corresponding calls to `test_mat`. In future this proxy interface should be removed and replaced with separate methods. I did it this way to limit changes in this PR.
Other notable changes:
* removed SVD and Core_CovarMatrix tests - they have been set-up for C-API function and it would be easier to rewrite them completely to test new interface instead (see also: #24957)
* `mulTransposed` destination type depends on source type now, C-function additionally converted result to requested destination type
* `transform` doesn't have `shift` …
> C-API cleanup: rework ArrayTest to use new arrays only

- CMakeLists.txt
I've got a warning and an error with cmake 3.29 from MSVC:
Warning:
```
1> [CMake] CMake Warning (dev) at modules/python/python_loader.cmake:104 (if):
1> [CMake]   Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
1> [CMake]   --help-policy CMP0057" for policy details.  Use the cmake_policy command to
1> [CMake]   set the policy and suppress this warning.
1> [CMake] 
1> [CMake]   IN_LIST will be interpreted as an operator when the policy is set to NEW.
1> [CMake]   Since the policy is not set the OLD behavior will be used.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   modules/python/python_loader.cmake:118 (ocv_add_python_files_from_path)
1> [CMake]   modules/python/bindings/CMakeLists.txt:12 (include)
1> [CMake] This warning is for project …
```
> build: set cmake policy for if(IN_LIST) support

- modules/imgproc/src/imgwarp.cpp
> Use border value in ipp version of warp affine

- modules/core/include/opencv2/core/cvdef.h
- modules/core/include/opencv2/core/hal/intrin.hpp
- modules/core/test/test_math.cpp
There is a magic trick to make float => bfloat conversion more accurate (_original reference needed, is it done this way in PyTorch?_). In simplified form it looks like:
```
uint16_t f2bf(float x) {
union {
unsigned u;
float f;
} u;
u.f = x;
// return (uint16_t)(u.u >> 16); <== the old method before this patch
return (uint16_t)((u.u + 0x8000) >> 16);
} 
```
it works correctly for almost all valid floating-point values, positive, zero or negative, and even for some extreme cases, like `+/-inf`, `nan` etc. The addition of `0x8000` to integer representation of 32-bit float before retrieving the highest 16 bits reduces the rounding error by ~2x.
The slight problem with this improved method is that the numbers very close to or equal to `+/-FLT_MAX` are mistakenly converted to `+/-inf`, …
> 2x more accurate float => bfloat conversion

- modules/core/include/opencv2/core/mat.inl.hpp
Prefix enums with '+' to make clang c++26 add to them again.
> C++26 Deprecated Enum Arithmetic Conversion: Fix core/mat.inl.hpp

- modules/dnn/include/opencv2/dnn/dnn.hpp
- modules/dnn/misc/objc/gen_dict.json
- modules/dnn/src/tflite/tflite_importer.cpp
- modules/dnn/test/test_tflite_importer.cpp
The new dnn graph is creating just by defining input and output names of each layer.
Some TFLite layers has fused activation, which doesn't have layer name and input and output names. Also some layers require additional preprocessing layers (e.g. NHWC -> NCHW). All these layers should be added to the graph with some unique layer and input and output names. 
I solve this problem by adding additionalPreLayer and additionalPostLayer layers.
If a layer has a fused activation, I add additionalPostLayer and change input and output names this way:
**original**: conv_relu(conv123, conv123_input, conv123_output)
**new**: conv(conv123, conv123_input, conv123_output_additional_post_layer) + relu(conv123_relu,  conv1_output_additional_post_layer, conv123_output)
If a layer has additional …
> Modified TFLite parser for the new dnn engine

- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
- modules/core/src/matmul.simd.hpp
The modification of this patch involves the RVV backend of Universal Intrinsic, replacing `LMUL=1` with `LMUL=2`.
Now each Universal Intrinsic type actually corresponds to two RVV vector registers, and each Intrinsic function also operates two vector registers. Considering that algorithms written using Universal Intrinsic usually do not use the maximum number of registers, this can help the RVV backend utilize more register resources without modifying the algorithm implementation
This patch is generally beneficial in performance.
We compiled OpenCV with `Clang-19.1.1` and `GCC-14.2.0` , ran it on `CanMV-k230` and `Banana-Pi F3`. Then we have four scenarios on combinations of compilers and devices. In `opencv_perf_core`, there are 3363 cases, of which:
- 901 (26.8%) cases achieved more …
> Use LMUL=2 in the RISC-V Vector (RVV) backend of Universal Intrinsic.

- modules/core/include/opencv2/core/hal/intrin_math.hpp
- modules/core/include/opencv2/core/hal/intrin_neon.hpp
- modules/core/test/test_intrin_utils.hpp
This PR solves the conflicts in merging 4.x to 5.x https://github.com/opencv/opencv/pull/26358
1. Explicitly convert the inputs number for `v_setall_` to hfloat number
2. Loosens the threshold for `v_sincos` test. (related issue: https://github.com/opencv/opencv/issues/26362)
3. Remove the new but temp api `template <> inline v_float16x8 v_setall_(float v) { return v_setall_f16((hfloat)v); }`
> Fix hfloat conflicts of v_func in merging 4.x to 5.x

- modules/dnn/include/opencv2/dnn/dnn.hpp
- modules/dnn/misc/objc/gen_dict.json
- modules/dnn/misc/python/test/test_dnn.py
- modules/dnn/src/caffe/caffe_importer.cpp
- modules/dnn/src/dnn_read.cpp
- modules/dnn/src/model.cpp
- modules/dnn/test/test_backends.cpp
- modules/dnn/test/test_caffe_importer.cpp
- modules/dnn/test/test_common.hpp
- modules/dnn/test/test_googlenet.cpp
- modules/dnn/test/test_layers.cpp
- modules/dnn/test/test_misc.cpp
Now the Caffe parser supports both the old and the new engine. It can be selected using newEngine argument in PopulateNet.
All cpu Caffe tests work fine except:
- Test_Caffe_nets.Colorization
- Test_Caffe_layers.FasterRCNN_Proposal
Both these tests doesn't work because of the bug in the new net.forward function. The function takes the name of the desired target last layer, but uses this name as the name of the desired output tensor.
Also Colorization test contains a strange model with a Silence layer in the end, so it doesn't have outputs. The old parser just ignored it. I think, the proper solution is to run this model until the (number_of_layers - 2) layer using proper net.forward arguments in the test.
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good- …
> Modified Caffe parser to support the new dnn engine

- platforms/js/build_js.py
I accidentally met this small problem mentioned in https://github.com/opencv/opencv/pull/25084#discussion_r1710838120 when play with wasm build. It seems https://github.com/EDVTAZ didn't fix it yet, so I create this tiny pr.
Additionally, I remove a redundant argument in `add_argument` call. `'store_true'` already set the default, see https://docs.python.org/3/library/argparse.html#action.
> Fix incorrect string format in js build script

- cmake/templates/dllmain.cpp.in
- modules/videoio/src/cap_winrt/MediaStreamSink.cpp
- modules/videoio/src/cap_winrt_bridge.cpp
- modules/videoio/src/cap_winrt_capture.cpp
- modules/videoio/src/cap_winrt_video.cpp
Addition to #26370
For https://github.com/opencv/ci-gha-workflow/pull/188
More warnings had to be fixed.
> WinRT/UWP build: fix more warnings in media part

- 3rdparty/kleidicv/CMakeLists.txt
> Disable SME2 branches in KleidiCV as it's incompatible with some CLang versions, e.g. NDK 28b1

- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/src/imgwarp.hpp
- modules/imgproc/src/imgwarp.sse4_1.cpp
Closes: https://github.com/opencv/opencv/issues/26185
> Use generic SIMD in warpAffineBlocklineNN

- CMakeLists.txt
Several explicitly set cmake policy can be removed after upgrading cmake_minimum_required to 3.13
> Remove useless cmake policy after upgrading cmake_minimum_required

- modules/ts/src/ts_func.cpp
make sure that if both compared FP16/BF16 values are bitwise-equal, assume their difference to be 0 (zero), just like in the case of FP32 and FP64, don't try to compare them as floating-point numbers, because they can be NaN's.
**fixes** #24894
> fixed FP16 mat comparison in tests

- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
- modules/core/src/matmul.simd.hpp
The goal of this patch is porting #26318 to branch 5.x, so that the fp16 part of the RVV backend can also be upgraded from `m1` to `m2`.
This patch is built with clang 19.1.1 and gcc 14.2, and as same as #25743, there are still some accuracy issues:
<details> 
<summary> run on k230, test case for `v_div` failed </summary>
```
test_loadstore_fp16_f32 ...
/wafer/hanliutong/5opencv/modules/core/test/test_intrin_utils.hpp:582: Failure
Expected: (std::abs(float((dataA[i] / dataB[i]) - resC[i]))) < (2e-4), actual: 0.000217021 vs 0.0002
Google Test trace:
/wafer/hanliutong/5opencv/modules/core/test/test_intrin_utils.hpp:581: i=7
/wafer/hanliutong/5opencv/modules/core/test/test_intrin_utils.hpp:582: Failure
Expected: (std::abs(float((dataA[i] / dataB[i]) - resC[i]))) < (2e-4), actual: 0.000325561 …
```
> Use LMUL=2 in the RISC-V Vector (RVV) FP16 part. (5.x)

- 3rdparty/ndsrvp/include/imgproc.hpp
- 3rdparty/ndsrvp/src/bilateralFilter.cpp
- 3rdparty/ndsrvp/src/filter.cpp
- 3rdparty/ndsrvp/src/medianBlur.cpp
From PR #26088:
> Filter implementation, further filter-applying functions would be based on this.
- Median Blur @ `CV_8U`, `CV_8S`, `CV_16U`, `CV_16S`
- Bilateral FIlter @ `CV_8U`
|Name of Test|opencv perf imgproc MedianBlur blank|opencv perf imgproc MedianBlur|opencv perf imgproc MedianBlur vs opencv perf imgproc MedianBlur blank (x-factor)|
|Bilateral::OCL_MedianBlurFixture::(640x480, 3)|34.271|18.719|1.83|
|Bilateral::OCL_MedianBlurFixture::(640x480, 5)|64.742|65.875|0.98|
|Bilateral::OCL_MedianBlurFixture::(1280x720, 3)|102.507|56.310|1.82|
|Bilateral::OCL_MedianBlurFixture::(1280x720, 5)|206.591|208.401|0.99|
|Bilateral::OCL_MedianBlurFixture::(1920x1080, 3)|237.020|128.334|1.85|
|Bilateral::OCL_MedianBlurFixture::(1920x1080, …
> 3rdparty: NDSRVP - Part 2.1: Filter-Related Functions

- modules/core/src/persistence_types.cpp
- modules/core/test/test_io.cpp
> Support 0d/1d Mat in FileStorage

- 3rdparty/hal_rvv/hal_rvv_1p0/merge.hpp
- 3rdparty/kleidicv/CMakeLists.txt
- cmake/OpenCVModule.cmake
- cmake/templates/dllmain.cpp.in
- doc/py_tutorials/py_imgproc/py_thresholding/py_thresholding.markdown
- modules/core/src/utils/datafile.cpp
- modules/dnn/src/ie_ngraph.cpp
- modules/highgui/src/window_winrt.cpp
- modules/highgui/src/window_winrt_bridge.cpp
- modules/highgui/src/window_winrt_bridge.hpp
- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/src/imgwarp.hpp
- modules/imgproc/src/imgwarp.sse4_1.cpp
- modules/imgproc/test/test_drawing.cpp
- modules/objdetect/src/face_detect.cpp
- modules/objdetect/src/face_recognize.cpp
- modules/videoio/src/cap_winrt/MediaStreamSink.cpp
- modules/videoio/src/cap_winrt_bridge.cpp
- modules/videoio/src/cap_winrt_capture.cpp
- modules/videoio/src/cap_winrt_video.cpp
- platforms/js/build_js.py
OpenCV Contrib: https://github.com/opencv/opencv_contrib/pull/3819
OpenCV Extra: no changes
#26203 from FantasqueX:generic-simd-warpAffineBlocklineNN
#26318 from hanliutong:rvv-intrin-m2
#26356 from hardikkamboj:4.x
#26357 from dkurt:dkurt/ov_out_names_from_graph
#26368 from hanliutong:rvv-hal-license
#26370 from mshabunin:fix-winrt-warnings
#26374 from OrkWard:fix-js-build-script
#26381 from dkurt:dk/hotfix_dnn_debug
#26384 from mshabunin:fix-winrt-warnings-2
#26388 from vrabaud:4_8u
#26390 from asmorkalov:as/kleidicv_no_sme2
#26402 from asmorkalov:as/win_uwp_ci
Previous "Merge 4.x": #26358
> 5.x merge 4.x

- modules/core/include/opencv2/core/persistence.hpp
- modules/core/src/persistence.cpp
- modules/core/src/persistence.hpp
- modules/core/src/persistence_impl.hpp
- modules/core/src/persistence_json.cpp
- modules/core/src/persistence_xml.cpp
- modules/core/src/persistence_yml.cpp
- modules/core/test/test_io.cpp
- modules/python/src2/typing_stubs_generation/predefined_types.py
resolves #23333
Proposed approach is not perfect in terms of complexity and potential bugs. Instead of changing `INT` raw size from `4` to `8`, we check int64 value can be fitted to int32 or not.
Collections such as cv::Mat rely on data type symbol.
This PR is addressed to 5.x branch first to cover `CV_64S` Mat. Later, it can be backported to 4.x
> int64 data type in FileStorage

- modules/core/include/opencv2/core/persistence.hpp
- modules/core/src/persistence.cpp
- modules/core/src/persistence.hpp
- modules/core/src/persistence_impl.hpp
- modules/core/src/persistence_json.cpp
- modules/core/src/persistence_types.cpp
- modules/core/src/persistence_xml.cpp
- modules/core/src/persistence_yml.cpp
- modules/core/test/test_io.cpp
- modules/python/src2/typing_stubs_generation/predefined_types.py
Port of https://github.com/opencv/opencv/pull/26399 to 4.x branch
> int64 data type support for FileStorage. 1d and empty Mat with exact dimensions

- cmake/OpenCVDetectDirectML.cmake
DirectML was first included with 10.0.18362.0, but dxcore.lib necessary to make the check pass was first in 10.0.19041.0.
I authored this PR because an internal customer was complaining about vcpkg failing to build OpenCV, but they were using Windows SDK 10.0.18362.0, causing this error:
```console
-- No support for DirectML (d3d12, dxcore, directml libs are required)
[...]
-- Verifying WITH_DIRECTML=ON => 'HAVE_DIRECTML'=FALSE
CMake Warning at cmake/OpenCVUtils.cmake:785 (message):
Option WITH_DIRECTML is enabled but corresponding dependency have not been
found: "HAVE_DIRECTML" is FALSE
Call Stack (most recent call first):
CMakeLists.txt:1907 (ocv_verify_config)
[...]
CMake Error at cmake/OpenCVUtils.cmake:797 (message):
Some dependencies have not been found or have been forced, unset …
```
> Add note for people debugging DirectML detection failures to check their Windows SDK version.

- modules/3d/src/pointcloud/load_point_cloud.cpp
fixes warnings on documentation built
```
/build/5_x_docs-lin64/opencv/modules/3d/src/pointcloud/load_point_cloud.cpp:52:100: warning: unused parameter 'rgb' [-Wunused-parameter]
/build/5_x_docs-lin64/opencv/modules/3d/src/pointcloud/load_point_cloud.cpp:85:97: warning: unused parameter 'rgb' [-Wunused-parameter]
/build/5_x_docs-lin64/opencv/modules/3d/src/pointcloud/load_point_cloud.cpp:124:68: warning: unused parameter 'texCoords' [-Wunused-parameter]
/build/5_x_docs-lin64/opencv/modules/3d/src/pointcloud/load_point_cloud.cpp:251:65: warning: unused parameter 'texCoords' [-Wunused-parameter]
```
> Fix warnings on documentation built

- modules/imgcodecs/src/grfmt_exr.cpp
Regression from:
- https://github.com/opencv/opencv/pull/19998
Versioning macros are introduced in OpenEXR 2.0.1 (not even in 2.0.0) and some old system like CentOS 7 still has 1.7.1 in stock.
- https://github.com/AcademySoftwareFoundation/openexr/commit/60cdff8a6f5c4e25a374e5f366d6e9b4efd869b3#diff-c4bae0726aebe410e407db9abd406d9cf2684f82dd8a08f46d84e8b7c35cf22aR67
Resolve https://github.com/opencv/opencv/issues/19925
> Check existence of OpenEXR version macros before using.

- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
- modules/imgproc/src/warp_common.vector.hpp
- modules/imgproc/src/warp_kernels.simd.hpp
Previous performance regressions on c4 kernels are mainly on A311D https://github.com/opencv/opencv/pull/26348.
Regressions on c3 kernels on intel platform will be fixed in another pull request.
M2
```
Name of Test                                        base  patch   patch
vs
base
(x-factor)
WarpAffine::TestWarpAffine::(640x480, INTER_LINEAR, BORDER_CONSTANT, 16UC4)               0.338 0.163    2.08
WarpAffine::TestWarpAffine::(640x480, INTER_LINEAR, BORDER_CONSTANT, 32FC4)               0.310 0.107    2.90
WarpAffine::TestWarpAffine::(640x480, INTER_LINEAR, BORDER_REPLICATE, 16UC4)              0.344 0.162    2.13
WarpAffine::TestWarpAffine::(640x480, INTER_LINEAR, BORDER_REPLICATE, 32FC4)              0.313 0.111    2.83
WarpAffine::TestWarpAffine::(1280x720, …
```
> imgproc: fix perf regressions on the c4 kernels of warpAffine / warpPerspective / remap

- modules/core/src/arithm.cpp
- modules/core/src/hal_replacement.hpp
* HAL for `absdiff` when one of arguments is a scalar, including multichannel arrays and scalars
* several channels support for HAL `addScalar`
* proper data type check for `addScalar` when one of arguments is a scalar
> HAL added for absdiff(array, scalar) + related fixes

- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/src/grfmt_tiff.cpp
- modules/imgcodecs/test/test_tiff.cpp
Closed https://github.com/opencv/opencv/issues/26507
Note: Predictor 2 for 64-bit is only supported after libtiff 4.4.0. But Linux x64 Debug uses libtiff 4.1.0 (releases at 2019/11/3). I append fallback fix to NONE. I hope It works well.
> Support CV_32U, CV_64U and CV_64S for TIFF

- 3rdparty/clapack/CMakeLists.txt
**Compiler**: LLVM/Clang 19
**Warning**:
```
/home/ubuntu/opencv/3rdparty/clapack/runtime/cblas_wrap.c:286:13: warning: '&&' of a value and its negation always evaluates to false [-Wtautological-negation-compare]
```
**Location**:
https://github.com/opencv/opencv/blob/f7483cd97809217676bedf524c42c6ea064364e6/3rdparty/clapack/runtime/cblas_wrap.c#L286-L287
> build: disable clang  warning in clapack 3rdparty

- modules/calib3d/src/usac/fundamental_solver.cpp
Issue found with debug hardening mode of libc++ when runnig various USAC tests:
```
/usr/local/include/c++/v1/vector:1443: assertion __n < size() failed: vector[] index out of bounds
```
> calib3d: fix vector access in USAC

- modules/3d/src/usac/fundamental_solver.cpp
> calib3d: fix vector access in USAC (5.x)

- modules/core/test/ref_reduce_arg.impl.hpp
Compiling  and running core tests with libc++ with debug hardening mode produces following error (`Core_reduceArgMinMax`):
```
/usr/local/include/c++/v1/__algorithm/comp_ref_type.h:47: 
assertion !__comp_(__l, __r) failed: Comparator does not induce a strict weak ordering
```
Perhaps we should not [use](https://github.com/opencv/opencv/blob/fb422a62d28faeed5b97ee7da7e8272f8fab250a/modules/core/test/test_arithm.cpp#L1517-L1524) `std::min_element` with `std::less_equal`. E.g. C++-17 (?) (N4659) standard says:
> 28.7
>
> 3. For all algorithms that take Compare, there is a version that uses operator< instead.
> That is, comp(*i, *j) != false defaults to *i < *j != false. For algorithms other than those
> described in 28.7.3 (binary_search etc.), comp shall induce a strict weak ordering on the …
> test: fix technical issue with min_element in reduce tests

- modules/core/test/ref_reduce_arg.impl.hpp
> test: fix technical issue with min_element in reduce tests (5.x)

- modules/core/include/opencv2/core/hal/intrin_lasx.hpp
- modules/core/include/opencv2/core/hal/intrin_wasm.hpp
- Corrects typo in Emscripten-only intrinsics header (Fixes https://github.com/opencv/opencv/issues/26536)
- Updates deprecated intrinsic title (as per LLVM final intrinsic name).
```
Xbuild_image:Custom=javascript
Xbuild_image:Custom=javascript-simd:3.1.64
build_image:Custom=javascript:3.1.64
```
> Emscripten build fixes

- modules/python/src2/typing_stubs_generation/api_refinement.py
> Added some mssing type constants to python type stubs generator.

- modules/objdetect/src/qrcode_encoder.cpp
There might be cases when more bits are requested than available in the bitstream.
Partial stacktrace:
```
frame #6: 0x00007ffff7c598f8 libopencv_objdetect.so.410`std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>::operator[][abi:de190104](this=0x00005555557a9338 size=19, __n=19) at vector:1436:3
frame #7: 0x00007ffff7d51fe6 libopencv_objdetect.so.410`cv::QRCodeDecoderImpl::Bitstream::next(this=0x00005555557a9338, bits=3) at qrcode_encoder.cpp:1337:24
frame #8: 0x00007ffff7d50a89 libopencv_objdetect.so.410`cv::QRCodeDecoderImpl::decodeSymbols(this=0x00005555557a9318, result="59147068325914706832591470683259147068325") at qrcode_encoder.cpp:1739:74
frame #9: 0x00007ffff7d4f03e libopencv_objdetect.so.410`cv::QRCodeDecoderImpl::run(this=0x00005555557a9318, …
```
> objdetect: fix invalid vector access in QR de/encoder

- modules/objdetect/src/qrcode_encoder.cpp
> objdetect: fix invalid vector access in QR encoder (5.x)

- modules/core/include/opencv2/core/mat.hpp
relates #26543
```
/build/precommit_docs/4.x/opencv/modules/core/include/opencv2/core/mat.hpp:82: warning: Unsupported xml/html tag <T> found
```
Used `\ref` for explicit linking.
> doc: fixed issue with doxygen 1.12

- modules/imgproc/perf/perf_blur.cpp
Tests were rewritten to support different kernel sizes
Connected PR with sanity data: https://github.com/opencv/opencv_extra/pull/1221
> Perf tests for cv::boxFilter(): 5x5 added

- modules/core/src/stat.simd.hpp
- modules/imgcodecs/src/utils.hpp
- modules/imgproc/src/smooth.simd.hpp
Fixed several cases of casting from `uchar*` to wider pointer type (e.g. `uint64_t*`) which can cause unaligned access.
> Fixed several cases of unaligned pointer cast

- modules/core/misc/objc/common/CvTypeExt.swift
- modules/core/misc/objc/test/MatTestObjc.m
> Fixed cv::Mat type constants in ObjC and Swift.

- modules/core/misc/java/src/java/core+CvType.java
- modules/core/misc/java/test/CvTypeTest.java
> More type constants for Java bindings too.

- modules/videoio/test/test_video_io.cpp
- observed on Ubuntu 24.04
Fail or sporadically hang on these tests:
```
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] videoio/videoio_synthetic.write_read_position/9, where GetParam() = (640x480, FOURCC(MPEG), .avi, GSTREAMER, 28dB)
[  FAILED  ] videoio/videoio_synthetic.write_read_position/12, where GetParam() = (640x480, FOURCC(MPEG), .mkv, GSTREAMER, 28dB)
[  FAILED  ] videoio/videoio_synthetic.write_read_position/25, where GetParam() = (976x768, FOURCC(MPEG), .avi, GSTREAMER, 28dB)
[  FAILED  ] videoio/videoio_synthetic.write_read_position/28, where GetParam() = (976x768, FOURCC(MPEG), .mkv, GSTREAMER, 28dB)
[  FAILED  ] videoio/videowriter_acceleration.write/40, where GetParam() = (FOURCC(MPEG), .mkv, GSTREAMER, 29dB, NONE, false)
[  FAILED  ] …
```
> videoio(test): filter unstable GStreamer tests

- apps/createsamples/utility.cpp
- modules/highgui/include/opencv2/highgui.hpp
- samples/cpp/tutorial_code/HighGUI/AddingImagesTrackbar.cpp
This Fixes #26467
Description:
This pull request improve the OpenCV documentation regarding the Trackbar functionality. The current documentation does not provide clear guidance on certain aspects, such as handling the value pointer deprecation and utilizing callback arguments in C. This update addresses those gaps and provides an updated example for better clarity.
Changes:
Updated Documentation:
Clarified the usage of the value pointer and explained how to pass an initial value, since the value pointer is deprecated.
Added more detailed explanations about callback arguments in C, ensuring that users understand how to access and use them in Trackbar callbacks.
Added a note on how to properly handle initial value passing without relying on the deprecated value pointer.
Updated Tutorial …
> Updated trackbar callback function and improved documentation

- modules/dnn/src/caffe/caffe_importer.cpp
An upcoming change in Protobuf will change the return types of various methods like `Descriptor::name()` and `Message::GetTypeName()` from `const std::string&` or `std::string` to `absl::string_view`. This CL fixes users of those methods to work both before and after the change.
> Support string_view in caffe_importer

- .github/workflows/PR-4.x.yaml
Reverts opencv/opencv#26604
GHA is limited to 20 pipeline reference, that PR added 21'st. We need to develop another approach to pipeline usage.
> Revert "CI: enable AVX2 build"

- modules/dnn/test/test_onnx_importer.cpp
- samples/dnn/yolo_detector.cpp
Previously, the yoloPostProcessing function assumed that the number of classes (nc) was fixed at 80. This caused incorrect behavior when a different number of classes was specified, leading to mismatched output shapes.
This update modifies the code to use the provided `nc` value dynamically, ensuring that the output shapes are correctly calculated based on the specified number of classes. This prevents issues when `nc` is not equal to 80 and allows for greater flexibility in model configurations.
> Fix yoloPostProcessing to handle variable number of classes (nc)

- samples/dnn/yolo_detector.cpp
This branch and commit address an issue in the YOLO example (samples/dnn/yolo_detector.cpp) where the mean and scale parameters only affected the first channel (Blue) due to single-value input. The modification updates these parameters to accept multi-channel values, ensuring consistent preprocessing across all image channels.
> Fix normalization parameters in YOLO example to support multi-channel mean and scale factors

- 3rdparty/kleidicv/CMakeLists.txt
- 3rdparty/kleidicv/kleidicv.cmake
KleidiCV 0.3 release notes: https://gitlab.arm.com/kleidi/kleidicv/-/releases
> Update KleidiCV to version 0.3

- modules/imgcodecs/test/test_exif.cpp
When none of JPEG, PNG, AVIF is enabled, `exif_files` is a zero-length array, which is prohibited by C++ reference.
Reference: https://en.cppreference.com/w/cpp/language/array
CMake config: `cmake -GNinja -B opencv-build-4.x -S . -DWITH_PNG=OFF -DWITH_JPEG=OFF -DWITH_AVIF=OFF -DCMAKE_BUILD_TYPE=Debug`
build log
```
FAILED: modules/imgcodecs/CMakeFiles/opencv_test_imgcodecs.dir/test/test_exif.cpp.o
/usr/bin/ccache /usr/bin/c++ -DHAVE_IMGCODEC_HDR -DHAVE_IMGCODEC_PFM -DHAVE_IMGCODEC_PXM -DHAVE_IMGCODEC_SUNRASTER -DHAVE_WEBP -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__OPENCV_TESTS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/fanta/source/opencv/3rdparty/libwebp/src -I/home/fanta/source/opencv/opencv-build-4.x/3rdparty/ippicv/ippicv_lnx/icv/include …
```
> Fix test_exif compilation when none of JPEG, PNG, AVIF is enabled

- modules/ts/misc/summary.py
```
C:\Users\voidr\Documents\develop\source\opencv\modules\ts\misc\summary.py:41: SyntaxWarning: invalid escape sequence '\d'
numeric_re = re.compile("(\d+)")
C:\Users\voidr\Documents\develop\source\opencv\modules\ts\misc\summary.py:42: SyntaxWarning: invalid escape sequence '\d'
cvtype_re = re.compile("(8U|8S|16U|16S|32S|32F|64F)C(\d{1,3})")
```
Related: https://github.com/opencv/opencv/pull/26579
> Fix Syntax warning in ts summary.py

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/mean.hpp
`meanStdDev` benefits from the Universal Intrinsic backend of RVV, but we also found that the performance on the `8UC4` type is worse than the scalar version when there is a mask, and there is no optimization implementation on `32FC1`.
This patch implements `meanStdDev` function in RVV_HAL using native intrinsic, significantly optimizing the performance for `8UC1`, `8UC4` and `32FC1`.
This patch is tested on BPI-F3 for both gcc 14.2 and clang 19.1.
```
$ opencv_test_core --gtest_filter="*MeanStdDev*"
$ opencv_perf_core --gtest_filter="Size_MatType_meanStdDev*
```
> Add RISC-V HAL implementation for meanStdDev

- modules/videoio/src/cap_images.cpp
- modules/videoio/test/test_images.cpp
> Fix VideoCapture fails to read single image with digits in name

- modules/photo/include/opencv2/photo.hpp
- modules/photo/src/seamless_cloning.cpp
- modules/photo/src/seamless_cloning_impl.cpp
- modules/photo/test/test_cloning.cpp
suggested fix for #25947 #21902 #15928 RFC
personally i don't believe changes about shifting are not really needed. but i prepared this PR to be helpful on  discussions about related issue.
i will add more information on the issue.
> Add *_WIDE flags to cv::seamlessClone

- modules/js/generator/embindgen.py
enums were not taken into account
```
Xbuild_image:Custom=javascript
build_image:Custom=javascript-simd:3.1.64
```
> js: fix enum generation issues

- modules/videoio/src/cap_ffmpeg.cpp
Steps to reproduce:
* Build with FFmpeg and `-DVIDEOIO_PLUGIN_LIST=all`
* Run `opencv_test_videoio --gtest_filter=videoio_encapsulate.write/*`
Results: some tests fail on setProperty call because it was not implemented for plugin case.
> videoio: fixed writer setProperty with FFmpeg plugin

- modules/highgui/src/window_cocoa.mm
https://github.com/opencv/opencv/issues/26574 reported a memory leak occurring when calling `getWindowImageRect` on macOS. After investigation, it was found that the leak was caused by the `cvGetWindowRect_COCOA`, which created several NSObject instances without setting up a local autorelease pool. 
https://github.com/opencv/opencv/blob/1d4110884b3145f77281ec8402d5dc43da7b8634/modules/highgui/src/window_cocoa.mm#L665-L671
The patch has been compiled and tested on macOS 15.1.1, confirming that the bug is resolved.
> Cocoa/highgui: fix leak in cvGetWindowRect_COCOA

- modules/dnn/perf/perf_utils.cpp
- modules/dnn/src/dnn_utils.cpp
Faster implementation of blobFromImage and blobFromImages for
HWC cv::Mat images -> NCHW cv::Mat
case
Running time on my pc in ms:
**blobFromImage**
```
image size            old        new   speed-up
32x32x3             0.008      0.002       4.0x
64x64x3             0.021      0.009       2.3x
128x128x3           0.164      0.037       4.4x
256x256x3           0.728      0.158       4.6x
512x512x3           3.310      0.628       5.2x
1024x1024x3        14.503      3.124       4.6x
2048x2048x3        61.647     28.049       2.2x
```
**blobFromImages**
```
image size            old        new   speed-up
16x32x32x3          0.122      0.041       3.0x
16x64x64x3          0.790      0.165       4.8x
16x128x128x3        3.313      0.652       5.1x
16x256x256x3       13.495      3.127 …
```
> Faster implementation of blobFromImages for cpu nchw output

- modules/objdetect/src/qrcode.cpp
Closes: #26642 
Asan log
```
=================================================================
==41401==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fc55a02a3fc at pc 0x7fc58e304131 bp 0x7ffd54787b00 sp 0x7ffd54787af8
WRITE of size 4 at 0x7fc55a02a3fc thread T0
#0 0x7fc58e304130 in cv::QRDetectMulti::checkSets(std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > >&, std::vector<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >, std::allocator<std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > > >&, std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > >&) /home/fanta/source/opencv/modules/objdetect/src/qrcode.cpp:3726 …
```
> Use size_t when calculating size of all_points

- modules/core/src/matmul.simd.hpp
- modules/core/test/test_math.cpp
- modules/imgproc/test/test_histograms.cpp
> RISC-V: enabled intrinsics in dotProd, relaxed test thresholds

- modules/gapi/src/streaming/gstreamer/gstreamersource.cpp
There are new changes merged by https://github.com/microsoft/STL/pull/5105, which revealed a conformance issue. Add include `<chrono>` to fix.
```log
modules/gapi/src/streaming/gstreamer/gstreamersource.cpp(234): error C2039: 'system_clock': is not a member of 'std::chrono'
```
> Add include chrono gstreamersource.cpp

- modules/dnn/src/op_cuda.cpp
- modules/dnn/src/op_cuda.hpp
A minor improvement regarding the CUDA support is required. Currently, `haveCUDA()` is equivalent to using the `HAVE_CUDA` define. However, existing code combines both checks, which implies that it is intended to do a runtime instead of a compile time check. For example:
https://github.com/opencv/opencv/blob/f503890c2b2ba73f4f94971c1845ead941143262/modules/dnn/src/net_impl.cpp#L173
Instead, we should use a runtime check in `haveCUDA()`, similar to `haveVulkan()`. Doing so, we can use CUDA by default whenever available by setting `OPENCV_DNN_BACKEND_DEFAULT = DNN_BACKEND_CUDA`, cf. #25112. The feature is implemented by simply checking for a valid CUDA device using `cudaGetDevice()` and saving its return value such that this function is only called once.
See details at …
> Update haveCUDA() to detect CUDA support at runtime

- cmake/OpenCVCompilerOptions.cmake
According to GCC doc, -Wlong-long: Warn if long long type is used. This is enabled by either -Wpedantic or -Wtraditional in ISO C90 and C++98 modes. To inhibit the warning messages, use -Wno-long-long.
OpenCV 4.x requires C++11. As result, this option is useless.
Ref: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
> Remove useless -Wno-long-long option

- 3rdparty/ffmpeg/ffmpeg.cmake
- modules/imgproc/CMakeLists.txt
- modules/imgproc/src/color.cpp
- modules/imgproc/src/resize.cpp
- modules/videoio/test/test_ffmpeg.cpp
Merge with 3rdparty: https://github.com/opencv/opencv_3rdparty/pull/91
FFmpeg 4.4.5
OpenH264 version 1.8.0
libVPX version 1.15.0
libAOM version 3.11.0
previous update: https://github.com/opencv/opencv/pull/25619
```
```
> ffmpeg/4.x: update FFmpeg wrapper 2024.12

- 3rdparty/hal_rvv/hal_rvv_1p0/mean.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/merge.hpp
- modules/core/test/test_mat.cpp
We are in the process of adding more specific optimization functions to the RVV HAL, meanwhile, we took a look back and fixed some bugs in `mean` and `merge`:
- [merge] Fix stride mismatch in vector store segment instructions, and add tests for it.
We previously only considered the `cn` is 2,3,4, and it is actually wrong when cn>4 (this patch also adds vectorization for the part where cn>4)
```
[==========] 32 tests from 1 test case ran. (4 ms total)
[  PASSED  ] 24 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] Core_Mat_arrays.SplitMerge/16, where GetParam() = (5, 8UC1)
[  FAILED  ] Core_Mat_arrays.SplitMerge/17, where GetParam() = (5, 16UC1)
[  FAILED  ] Core_Mat_arrays.SplitMerge/20, where GetParam() = (6, 8UC1)
[  FAILED  ] Core_Mat_arrays.SplitMerge/21, where GetParam() = …
```
> Add test cases and fix bugs in the RISC-V Vector HAL.

- modules/dnn/test/test_tflite_importer.cpp
Sporadic CI failure:
```
[ RUN      ] Test_TFLite.face_landmark/0, where GetParam() = VKCOM/VULKAN
/Users/opencv-cn/GHA-OCV-1/_work/opencv/opencv/opencv/modules/dnn/test/test_common.impl.hpp:84: Failure
Expected: (normL1) <= (l1), actual: 2.13794e-05 vs 2e-05
conv2d_20  |ref| = 164.86170959472656
[  FAILED  ] Test_TFLite.face_landmark/0, where GetParam() = VKCOM/VULKAN (27 ms)
```
> Tune threshold to stabinlize test with Vulkan backend.

- modules/imgproc/src/contours_new.cpp
Related to #26683 
I ran reproducer from issue with one iteration.
Before
```
iteration 0 took 3.1967720985412598 seconds. Total process memory: 5,331,820,544
```
After
```
iteration 0 took 1.3795826435089111 seconds. Total process memory: 500,125,696
```
Speedup more than `2` times and memory consumption reduction more than `10` times
> Speed up and reduce memory consumption for findContours

- modules/imgcodecs/src/grfmt_png.cpp
If the condition is not fixed, the memcpy below can do an out of boundary read
Bug: oss-fuzz:386688710
> Fix heap buffer overflow in cv::PngDecoder::read_from_io

- doc/py_tutorials/py_calib3d/py_pose/py_pose.markdown
Patch to opencv_extra has the same branch name. (Not applicable)
> fix: cast coordinates to int32 for compatibility with line function

- modules/imgcodecs/src/grfmt_bmp.cpp
> Fix integer overflow in in cv::BmpDecoder::readHeader

- modules/imgproc/test/test_fitellipse_ams.cpp
- modules/imgproc/test/test_fitellipse_direct.cpp
Before comparison of ellipses was incomplete - only one point of test ellipse with index `j = 1` was involved in inner loop (instead of all for complete comparison)
Related to #26694 
> Fix tests for ellipse fitting

- modules/imgproc/test/test_fitellipse_ams.cpp
- modules/imgproc/test/test_fitellipse_direct.cpp
> Remove code duplication from tests for ellipse fitting

- modules/imgproc/test/test_fitellipse.cpp
> Fix comment for fitEllipse Java case accurracy test

- doc/opencv.bib
- modules/imgproc/include/opencv2/imgproc.hpp
- samples/cpp/fitellipse.cpp
I believe that implementation of fitEllipseDirect function does not correspond to fitzgibbon1999 but to its improvement oy1998NumericallySD
Several arguments in favor of this:
* fitzgibbon1999 suggests to calculate eigenvalues and eigenvectors for 6x6 matrix, but oy1998NumericallySD - for 3x3 matrix M. In implementation we calculate eigenvalues and eigenvectors for 3x3 matrix M
https://github.com/opencv/opencv/blob/d77dbbe7a0c791deaf7f9c612cbfaa36a5e55b0c/modules/imgproc/src/shapedescr.cpp#L782-L800
* fitzgibbon1999 suggests to take eigenvector for positive eigenvalue, but oy1998NumericallySD - for positive `cond = 4 * evec(1, :) .* evec(3, :) - evec(2, :) .ˆ 2`. In implementation we calculate this `cond` and take eigenvector accordingly …
> Change article for fitEllipseDirect function

- modules/imgcodecs/src/grfmt_png.cpp
- modules/imgcodecs/src/grfmt_png.hpp
Also fix a bug in read_chunk where we could end up with png_get_uint_32(len) + 12 < 4
> Add more boundary checks.

- modules/python/python_loader.cmake
This pull request resolves a build warning related to `add_custom_command` in `python_loader.cmake` by explicitly specifying `POST_BUILD`.
- **Operating System:** macOS
- **CMake Version:** 3.31.3
```
CMake Warning (dev) at modules/python/python_loader.cmake:140 (add_custom_command):
Exactly one of PRE_BUILD, PRE_LINK, or POST_BUILD must be given.
```
> added POST_BUILD to add_custom_command in python_loader.cmake to avoid warning

- modules/core/src/bindings_utils.cpp
- Applied format for vector element formatting to ensure consistent and clear output representation.  
- Moved `operator<<` to the `cv` namespace to align with OpenCV's coding standards and improve maintainability.  
- Enhanced error handling by including detailed exception messages using `e.what()` for better debugging.  
> Improved dumpVector, cv::Rect operator<< and exceptions

- modules/core/include/opencv2/core/hal/intrin_vsx.hpp
Resolves #26749
Reproduced with Ubuntu 22 (`g++-powerpc64le-linux-gnu` package) and basic cmake toolchain file:
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ppc64le)
set(CMAKE_C_COMPILER powerpc64le-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER powerpc64le-linux-gnu-g++)
set(CMAKE_LINKER powerpc64le-linux-gnu-ld)
set(CMAKE_AR powerpc64le-linux-gnu-ar)
set(CMAKE_FIND_ROOT_PATH "/usr/lib/powerpc64le-linux-gnu")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
> core: fixed VSX intrinsics implementation

- modules/imgcodecs/src/grfmt_png.cpp
- read information at the very beginning (if reading chunk fails, reading the info might not be possible after)
- do not try to allocate when the chunk is > PNG_USER_CHUNK_MALLOC_MAX
> Fix remaining bugs in PNG reader

- modules/imgcodecs/src/grfmt_gif.cpp
this is related to #25691 
i solved two bugs here:
1. the decoding setting:
according to [https://www.w3.org/Graphics/GIF/spec-gif89a.txt](https://www.w3.org/Graphics/GIF/spec-gif89a.txt)
```
DEFERRED CLEAR CODE IN LZW COMPRESSION
There has been confusion about where clear codes can be found in the
data stream.  As the specification says, they may appear at anytime.  There
is not a requirement to send a clear code when the string table is full.
It is the encoder's decision as to when the table should be cleared.  When
the table is full, the encoder can chose to use the table as is, making no
changes to it until the encoder chooses to clear it.  The encoder during
this time sends out codes that are of the maximum Code Size.
As we can see from the above, when the decoder's table is full, it …
```
> fix bugs in GIF decoding

- cmake/checks/cpu_avx.cpp
- cmake/checks/cpu_avx2.cpp
- modules/core/include/opencv2/core/cvstd_wrapper.hpp
- modules/imgproc/src/imgwarp.cpp
- modules/stitching/include/opencv2/stitching.hpp
- modules/stitching/src/stitcher.cpp
OpenCV 5.x requires MSVC >= 2017 15.7 and MSVS 2013 is EOF currently.
> Remove MSVS 2013 related

- modules/photo/test/test_hdr.cpp
> fix threshold for photo_calibratedebevec regression test

- modules/imgproc/src/hough.cpp
This PR resolves the bug #26086 .
In brief, when the images are too large either in height or width the int type can't store the values. So, those variables have been updated to int64. More details can be found inside bug issue.
Regards,
> Fix #26086 - Update types inside HoughLinesProbabilistic

- modules/imgproc/src/imgwarp.cpp
This undefined behavior can be avoided by postponing calculation until needed.
> Avoid adding value to nullptr

- modules/imgproc/src/imgwarp.cpp
In both cases we add negative value (as unsigned type), so pointer addition wraps, which is undefined behavior.
> Don't overflow pointer addition

- .github/workflows/PR-3.4.yaml
Related https://github.com/opencv/ci-gha-workflow/pull/209
Ubuntu 14 is not compatible with Node.js 20.x used by GHA.
> Disable obsolete GHA pipelines for 3.4

- modules/imgcodecs/src/grfmt_jpegxl.cpp
Fix #26766 
It should additionally fix issue itself (problem with `remove` on `Windows`), but I can't be completely sure - I can't test this on `Windows`
> Fix memory leaks for JpegXLDecoder

- modules/imgproc/src/shapedescr.cpp
- modules/imgproc/test/test_fitellipse.cpp
- modules/imgproc/test/test_fitellipse_ams.cpp
- modules/imgproc/test/test_fitellipse_direct.cpp
Related to #26694 
Current noise addition is not very good because for example it turns degenerate case of one horizontal line into degenerate case of two parallel horizontal lines
Improving noise addition leads to improved robustness of algorithms
> Improve robustness for ellipse fitting

- modules/imgproc/include/opencv2/imgproc.hpp
- Updated the documentation of the putText function to clarify the behavior of the fontScale parameter.
- Explained how fontScale affects text rendering: magnifying (>1), minimizing (<1), and mirroring (<0).
Fixes #26730 
> Added fontScale behavior description to putText() documentation

- modules/imgproc/src/shapedescr.cpp
- modules/imgproc/test/test_fitellipse_ams.cpp
Related to #26694 
Added functionality to add noise to points in degenerate cases and try again for `fitEllipseAMS`. `fitEllipseNoDirect` and `fitEllipseDirect` already have this
> Improve robustness for fitEllipseAMS

- modules/videoio/src/cap_interface.hpp
- modules/videoio/test/test_orientation.cpp
> fix default cap_prop_orientation_auto behaviour

- modules/videoio/src/cap_dshow.cpp
- modules/videoio/src/cap_dshow.hpp
- modules/videoio/src/cap_interface.hpp
Resolve the issue of slow camera opening when using dshow as the backend for VideoCapture.
[dshow-code.zip](https://github.com/user-attachments/files/18070514/dshow-code.zip)
[DSHOW_test.docx](https://github.com/user-attachments/files/18070504/DSHOW_test.docx)
> VideoCapture open camera slow

- modules/highgui/src/window_cocoa.mm
1. According to [Apple Developer Documentation](https://developer.apple.com/documentation/foundation/nsautoreleasepool#overview), `@autorelease` block is the preferred method over using an instance of NSAutoreleasePool directly. This is also discussed in https://github.com/opencv/opencv/pull/26625#discussion_r1886796039.
2. Starting from commit https://github.com/opencv/opencv/commit/4ec4cf687679cd39e154e00b349759f3885b95ab, `highgui_cocoa.mm` contained numerous debug lines that had been commented out, such as:
https://github.com/opencv/opencv/blob/dbb330d7be22b7d95dc2879f38cbe9816d47738a/modules/highgui/src/window_cocoa.mm#L172-L183
Such extraneous comments should be removed once debugging is complete and should not remain in the release environment. A previous commit …
> Cocoa/highgui: replace with `@autoreleasepool` blocks

- modules/imgcodecs/src/grfmt_png.cpp
- modules/imgcodecs/src/grfmt_png.hpp
The PR addresses the following improvements:
1.Improving member functions:
- Renaming `read_from_io `and `write_to_io `to more descriptive names for better clarity.
- Enhancing documentation for these functions to make their purpose, inputs, outputs, and edge-case handling explicit.
2.**RFC** Refactoring functions into the base class with the following considerations (**subject to undone**):
- This change allows decoders currently with `m_buf_supported = false` to potentially use these functions in the future to support buffer reading.
- Introducing the `m_f` variable in the base class, which potentially enables efficient handling of file …
> Imgcodecs minor improvements for better code readibility

- modules/core/include/opencv2/core/base.hpp
---
I have added the results of calling `copyMakeBorder()` for each `cv::BorderTypes` on a simple example in the documentation for better understanding.
- before:
---
- after:
> Add examples for each `cv::BorderTypes` enum types in the documentation

- modules/calib3d/src/chessboard.cpp
- modules/calib3d/test/test_chesscorners.cpp
Fix for proposed issue in https://github.com/opencv/opencv/issues/26830
> Fix bug different marker ordering with findChessboardCornersSBWithMeta and CALIB_CB_LARGER flag

- modules/imgproc/src/floodfill.cpp
`step` and `maskStep` are used to increase/decrease `pImage`. But it's done on unsigned type, relying on overflow, which is UB. (step is size_t but seed.y is int and can be negative, the result is therefore unsigned which can overflow)
> Fix overlow pointers.

- modules/core/src/persistence.cpp
- modules/core/test/test_io.cpp
Fix #26829, https://github.com/opencv/opencv-python/issues/1078
In current implementation of `int64` support raw size of recorded integer is variable (`4` or `8` bytes depending on value). But then we iterate over nodes we need to know it exact value
https://github.com/opencv/opencv/blob/dfad11aae7ef3b3a0643379266bc363b1a9c3d40/modules/core/src/persistence.cpp#L2596-L2609
Bug is that `rawSize` method still return `4` for any integer. I haven't figured out a way how to get variable raw size for integer in this method. I made raw size for integer is constant and equal to `8`.
Yes, after this patch memory consumption for integers will increase, but I don't know a better way to do it yet. At least this fixes bug and implementation becomes more correct
See details at …
> Fix bug with int64 support for FileStorage

- modules/photo/src/denoising.cpp
- modules/photo/test/test_denoising.cpp
- modules/photo/test/test_precomp.hpp
> added 16-bit support to fastNlMeansDenoising and updated tests

- modules/imgcodecs/src/grfmt_png.cpp
related  #22551
tEXt: chunk data size is being controlled by LibPNG
> fix related the issue 22551

- modules/core/test/test_math.cpp
See also #26666
To avoid test failures on LicheePi 4A (RVV 0.7.1):
```
[ RUN      ] Core_DotProduct.accuracy
/home/ci/opencv/modules/ts/src/ts.cpp:612: Failure
Failed
failure reason: Bad accuracy
test case #264
seed: 00000000000c5b64
-----------------------------------
LOG:
output: Too big difference (=2.48997e-05 > 1.7e-05) at element 0
input array 0 type=32fC2, size=(42, 453)
input array 1 type=32fC2, size=(42, 453)
ref output array 0 type=64fC1, size=(1, 4)
test_case_idx = 264
-----------------------------------
CONSOLE: ................................
-----------------------------------
[  FAILED  ] Core_DotProduct.accuracy (99 ms)
```
> RISC-V: increase DotProduct test threshold a bit

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/atan.hpp
Current universal intrinsic implementation of `fastAtan32f_` in `mathfuncs_core.simd.hpp` does not work for RVV (`CV_SIMD_SCALABLE`) so it falls back to scalar method.
This pull request adds an HAL implementation as a workaround allowing it to benefit form RVV vectorization.
Tested on Spacemit X60 cpu:
gcc version 14.2.1
```
Name of Test            perf  perf     perf   
scalar  rvv     rvv    
vs    
perf   
scalar  
(x-factor)
phase32f::VectorLength::128     0.007  0.002    3.20   
phase32f::VectorLength::1000    0.046  0.007    6.66   
phase32f::VectorLength::131072  5.995  0.740    8.10   
phase32f::VectorLength::524288  23.857 2.906    8.21   
phase32f::VectorLength::1048576 47.654 5.789    8.23   
phase64f::VectorLength::128     0.008  0.002    3.51   
phase64f::VectorLength::1000 …
```
> Add RISC-V HAL implementation for fastAtan32f/fastAtan64f

- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/src/grfmt_png.cpp
- fix a potential overflow in x0+w0
- use the proper function to deal with background color to deal with all cases of the spec
- use BGR layout for APNG background color
> Fix oss-fuzz bugs 391934081 and 392318892

- cmake/OpenCVFindWebP.cmake
Reverts opencv/opencv#26857
The patch breaks system package search at least on Ubuntu 20.04.
> Revert "Update OpenCVFindWebP.cmake with sturkmen72's suggestion"

- modules/gapi/src/compiler/gislandmodel.hpp
Add `<exception>`, `<string>`, and `<cstddef>` includes to `gislandmodel.hpp` which are required due to the usage of `std::exception_ptr`, `std::string`, and `size_t` in this header.
Notably one of those causes a build error on recent versions of Xcode: #26780 
- [N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
- [N/A] The feature is well documented and sample code can be built with the project CMake
> Add missing include in gislandmodel.hpp

- modules/core/perf/perf_mat.cpp
- modules/core/src/matmul.simd.hpp
```
Name of Test                       base  patch   patch
vs
base
(x-factor)
Mat_Transform::Size_MatType::(127x61, 8SC3)              0.017 0.004    4.64
Mat_Transform::Size_MatType::(127x61, 16SC3)             0.015 0.004    3.78
Mat_Transform::Size_MatType::(127x61, 32SC3)             0.015 0.007    2.03
Mat_Transform::Size_MatType::(127x61, 64FC3)             0.007 0.004    1.78
Mat_Transform::Size_MatType::(640x480, 8SC3)             0.673 0.140    4.80
Mat_Transform::Size_MatType::(640x480, 16SC3)            0.618 0.158    3.90
Mat_Transform::Size_MatType::(640x480, 32SC3)            0.579 0.278    2.08
Mat_Transform::Size_MatType::(640x480, 64FC3)            0.290 0.266    1.09
Mat_Transform::Size_MatType::(1280x720, 8SC3)            1.919 0.414    4.63 …
```
> core: vectorize cv::transform in terms of all data types

- modules/core/src/mean.dispatch.cpp
- modules/core/test/test_arithm.cpp
> fix meanStdDev overflow for large images

- modules/python/src2/typing_stubs_generation/api_refinement.py
Fixes :  #26811
Updated api_refinement.py to refine the return type of cv2.imread and cv2.imdecode.
- Previously, these functions were typed to always return a valid image.
- Now, they are correctly annotated as MatLike | None, ensuring static type checkers like mypy detect cases where the function might return None.
<details>
<summary>Fix details </summary>
```python
import tempfile
import cv2
with tempfile.TemporaryFile() as temp_file:
temp_file.write(b"Corrupted binary data. Not a image")
temp_file.seek(0)
image = cv2.imread(str(temp_file.name))
print(image.shape)
```
```bash
mypy test.py
```
Now, `mypy` correctly flags `None` access:
```bash
test.py:8: error: Item "None" of "ndarray[Any, dtype[...]] | None" has no attribute "shape"  [union-attr]
Found 1 error in 1 file (checked 1 …
```
> fix wrong python type hints for imread

- modules/core/test/test_io.cpp
OpenCV extra: https://github.com/opencv/opencv_extra/pull/1235
> Refactor test for FileStorage Base64

- samples/dnn/common.py
- samples/dnn/download_models.py
- samples/dnn/ldm_inpainting.py
- samples/dnn/models.yml
This PR adds and fixes following points in the ldm_inpainting sample on top of original PR #26605 by @Abdurrahheem 
DONE:
1. Added functionality to load models from a YAML configuration file, allowing for automatic downloading if models are not found locally.
2. Updated the script usage instructions to reflect the correct command format.
3. Improved user interaction by adding instructions to the image window for inpainting controls.
4. Introduced a new models.yml configuration section for inpainting models weights downloading, including placeholders for model SHA1 checksums.
5. Fixed input types and names of the onnx graph generation.
6. Added links to onnx graphs in models.yml
7. Support added for findModels and standarized the sample usage similar to other dnn samples
8. Fixes issue in …
> Extension to PR #26605 ldm inpainting sample

- modules/calib3d/src/solvepnp.cpp
- modules/core/include/opencv2/core/base.hpp
- modules/gapi/include/opencv2/gapi/own/assert.hpp
- modules/gapi/src/streaming/onevpl/cfg_param_device_selector.cpp
- modules/imgproc/test/test_color.cpp
Fixes : #26151
NDEBUG macro is standard and associated with assert(): https://en.cppreference.com/w/c/error/assert
> Fix _DEBUG/NDEBUG handling across modules 

- cmake/OpenCVDetectCUDAUtils.cmake
Continuing the work started in #26820, this corrects a bug in checking for deprecated capabilities: CMake's `MATCHES` operator accepts a regex and the value provided was not properly escaped. This results in configuration failing when specifying `CUDA_ARCH_BIN` containing the capability `100` (that's `10.0`), since the `.` in the regex `1.0` will match the middle zero in `100`. Example failure:
```console
opencv> -- CUDA: Using CUDA_ARCH_BIN=100
opencv> CMake Error at cmake/OpenCVDetectCUDAUtils.cmake:314 (message):
opencv>   CUDA: 1.0 compute capability is not supported - exclude it from ARCH/PTX
opencv>   list and re-run CMake
opencv> Call Stack (most recent call first):
opencv>   cmake/OpenCVDetectCUDAUtils.cmake:317 (ocv_wipeout_deprecated_cc)
opencv> …
```
> cmake/OpenCVDetectCUDAUtils.cmake: use IN_LIST to avoid regex matching valid capabilities

- 3rdparty/openvx/hal/openvx_hal.cpp
- 3rdparty/openvx/hal/openvx_hal.hpp
- 3rdparty/openvx/include/ivx.hpp
- modules/core/src/lut.cpp
- modules/core/src/mean.dispatch.cpp
- modules/core/src/minmax.cpp
Tested with OpenVX 1.2 & 1.3 sample implementation.
Steps to build and test:
```
git clone git@github.com:KhronosGroup/OpenVX-sample-impl.git
cd OpenVX-sample-impl
python3 Build.py --os=Linux --conf=Release
cd ..
mkdir build
cmake -DWITH_OPENVX=ON -DOPENVX_ROOT=/mnt/Projects/Projects/OpenVX-sample-impl/install/Linux/x64/Release/ ../opencv
make -j8
```
> Migrate remaning OpenVX integrations to OpenVX HAL (core)

- modules/java/generator/gen_java.py
- modules/python/test/tests_common.py
- modules/video/include/opencv2/video/tracking.hpp
- modules/video/misc/java/test/TrackerCreateTest.java
- modules/video/misc/python/test/test_tracking.py
- modules/video/src/tracking/tracker_dasiamrpn.cpp
- modules/video/src/tracking/tracker_goturn.cpp
- modules/video/src/tracking/tracker_nano.cpp
- modules/video/src/tracking/tracker_vit.cpp
Replaces https://github.com/opencv/opencv/pull/26295
Allows to substitute custom models or initialize tracker from in-memory model.
> Added trackers factory with pre-loaded dnn models

- modules/calib3d/misc/python/test/test_calibration.py
- modules/calib3d/src/fundam.cpp
> Fix assertion in cv2.sampsonDistance 

- 3rdparty/openvx/hal/openvx_hal.cpp
- 3rdparty/openvx/hal/openvx_hal.hpp
- 3rdparty/openvx/include/ivx.hpp
- modules/imgproc/src/box_filter.dispatch.cpp
- modules/imgproc/src/canny.cpp
- modules/imgproc/src/deriv.cpp
- modules/imgproc/src/histogram.cpp
- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/src/median_blur.dispatch.cpp
- modules/imgproc/src/pyramids.cpp
- modules/imgproc/src/smooth.dispatch.cpp
- modules/imgproc/src/thresh.cpp
Depends on https://github.com/opencv/opencv/pull/26903
Not covered with HAL:
> Migrate remaning OpenVX integrations to OpenVX HAL (imgproc)

- 3rdparty/hal_rvv/hal_rvv_1p0/merge.hpp
* Banana Pi BF3 (SpacemiT K1) RISC-V
* Compiler: Syntacore Clang 18.1.4 (build 2024.12)
```
Name of Test                       baseline   pr       pr
merge              vs    
baseline
merge
(x-factor)
merge::Size_SrcDepth_DstChannels::(127x61, 8UC1, 2)      0.013   0.003     3.76   
merge::Size_SrcDepth_DstChannels::(127x61, 8UC1, 3)      0.020   0.006     3.46   
merge::Size_SrcDepth_DstChannels::(127x61, 8UC1, 4)      0.026   0.010     2.61   
merge::Size_SrcDepth_DstChannels::(127x61, 8UC1, 5)      0.043   0.028     1.56   
merge::Size_SrcDepth_DstChannels::(127x61, 8UC1, 6)      0.054   0.035     1.53   
merge::Size_SrcDepth_DstChannels::(127x61, 8UC1, 7)      0.065   0.050     1.30   
merge::Size_SrcDepth_DstChannels::(127x61, 8UC1, 8)      0.070   0.036     1.95 …
```
> Further optimization of cv::merge RVV HAL for 8U and 16S

- modules/core/CMakeLists.txt
- modules/core/src/norm.cpp
- modules/core/src/norm.dispatch.cpp
- modules/core/src/norm.rvv1p0.hpp
- modules/core/src/norm.simd.hpp
Checklist:
|      | normInf | normL1 | normL2 |
| ---- | ------- | ------ | ------ |
| bool |    -    |   -    |   -    |
| 8u   |    √    |   √    |   √    |
| 8s   |    √    |   √    |   √    |
| 16u  |    √    |   √    |   √    |
| 16s  |    √    |   √    |   √    |
| 16f  |    -    |   -    |   -    |
| 16bf |    -    |   -    |   -    |
| 32u  |    -    |   -    |   -    |
| 32s  |    √    |   √    |   √    |
| 32f  |    √    |   √    |   √    |
| 64u  |    -    |   -    |   -    |
| 64s  |    -    |   -    |   -    |
| 64f  |    √    |   √    |   √    |
*: Vectorization of data type bool, 16f, 16bf, 32u, 64u and 64s needs to be done on 5.x.
Patch to opencv_extra has the same branch …
> core: vectorize cv::normalize / cv::norm

- modules/python/test/tests_common.py
Source : https://numpy.org/devdocs/reference/generated/numpy.fromstring.html
> replace deprecated np.fromstring() by np.frombuffer()

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/flip.hpp
- modules/core/perf/perf_flip.cpp
Implement through the existing `cv_hal_flip` interfaces.
Add perf test for `cv::flip`.
The reason why select these args for testing:
- **size**: copied from perf_lut
- **type**:
- U8C1: basic situation
- U8C3: unaligned element size
- U8C4: large element size
Tested on
- MUSE-PI (vlen=256)
- Compiler: gcc 14.2 (riscv-collab/riscv-gnu-toolchain Nightly: December 16, 2024)
```sh
$ opencv_test_core --gtest_filter="Core_Flip/ElemWiseTest.*"
$ opencv_perf_core --gtest_filter="Size_MatType_FlipCode*" --perf_min_samples=300 --perf_force_samples=300
```
```
Name of Test                       scalar   ui    rvv       ui        rvv    
vs         vs    
scalar     scalar  
(x-factor) (x-factor)
flip::Size_MatType_FlipCode::(320x240, 8UC1, FLIP_X)    0.026  0.033  0.031     0.81 …
```
> Impl RISC-V HAL for cv::flip | Add perf test for flip

- .github/workflows/PR-4.x.yaml
- modules/videoio/test/test_audio.cpp
- modules/videoio/test/test_ffmpeg.cpp
- modules/videoio/test/test_gstreamer.cpp
- modules/videoio/test/test_mfx.cpp
- modules/videoio/test/test_orientation.cpp
- modules/videoio/test/test_precomp.hpp
- modules/videoio/test/test_video_io.cpp
_videoio_ test names changed - use string instead of index.
E.g. `videoio_read.threads/0` is now `videoio_read.threads/h264_0_RAW`.
It allows to filter tests independently of the platform.
**Notes:**
- not all tests has been updated - only simpler ones and those which have varying parameters depending on platform
> videoio: print test params instead of indexes

- modules/gapi/src/backends/onnx/gonnxbackend.cpp
Workaround for successfull append of OpenVINO Execution Provider: Mov…ed creation of 'Ort::Env' before it
> G-API/ORT: Workaround exception during OV EP append

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/norm_hamming.hpp
- modules/core/src/norm.dispatch.cpp
Implement through the existing `cv_hal_normHamming8u` and `cv_hal_normHammingDiff8u` interfaces.
Modified `modules/core/src/norm.cpp:680` to ensure HAL calls are not bypassed.
Tested on
- MUSE-PI
- Compiler: gcc 14.2 (riscv-collab/riscv-gnu-toolchain Nightly: December 16, 2024)
```bash
$ opencv_test_core --gtest_filter="Core_Norm/ElemWiseTest*"
$ opencv_perf_core --gtest_filter="PerfHamming*" --perf_min_samples=300 --perf_force_samples=300
```
Compare with scalar:  
```bash
Name of Test                     scalar  hal      hal    
vs    
scalar  
(x-factor)
norm2::PerfHamming::(NORM_HAMMING2, 8UC1, 640x480)   0.962  0.128     7.52   
norm2::PerfHamming::(NORM_HAMMING2, 8UC1, 1920x1080) 6.506  0.803     8.10   
norm2::PerfHamming::(NORM_HAMMING, 8UC1, 640x480)    0.964 …
```
> Impl RISC-V HAL for norm_hamming

- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/test/test_imgwarp.cpp
> Fix getPerspectiveTransform for singular case

- modules/calib3d/src/fisheye.cpp
- modules/calib3d/src/undistort.dispatch.cpp
Skips unnecessary rotation with identity matrix if no R or P mats are given.
> Optimize undistort points

- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
- modules/core/src/convert.simd.hpp
- modules/core/src/convert_scale.simd.hpp
- modules/core/test/test_intrin_utils.hpp
This PR aims to make `opencv_test_core` pass on RVV, via following two parts:
1. Fix bug in Universal Intrinsic when VLEN >= 512:
- `max_nlanes` should be multiplied by 2, because we use LMUL=2 in RVV Universal Intrinsic since #26318.
- Related tests are also expanded to match longer registers
- Relax the precision threshold of `v_erf` to make the tests pass
2. Temporary fix  #26936
- Disable 3 Universal Intrinsic code blocks on GCC
- This is just a temporary fix until we figure out if it's our issue or GCC/something else's
This patch is tested under the following conditions:
- Compier: GCC 14.2, Clang 19.1.7
- Device: Muse-Pi (VLEN=256), QEMU (VLEN=512, 1024)
Patch to opencv_extra has the …
>  Fix issues in RISC-V Vector (RVV) Universal Intrinsic

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/cholesky.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/lu.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/qr.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/svd.hpp
This patch implements `cv_hal_LU/cv_hal_Cholesky/cv_hal_SVD/cv_hal_QR` function in RVV_HAL using native intrinsics, optimizing the performance for `cv::solve` with method `DECOMP_LU/DECOMP_SVD/DECOMP_CHOLESKY/DECOMP_QR` and data types `32FC1/64FC1`.
Tested on MUSE-PI (Spacemit X60) for both gcc 14.2 and clang 20.0.
```
$ ./opencv_test_core --gtest_filter="*Solve*:*SVD*:*Cholesky*"
$ ./opencv_perf_core --gtest_filter="*SolveTest*" --perf_min_samples=100 --perf_force_samples=100
```
The tail of the perf table is shown below since the table is too long.
View the full perf table here: [hal_rvv_solve.pdf](https://github.com/user-attachments/files/18725067/hal_rvv_solve.pdf)
Patch to opencv_extra …
> Add RISC-V HAL implementation for cv::solve

- 3rdparty/hal_rvv/hal_rvv_1p0/cholesky.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/dxt.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/flip.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/lu.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/lut.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/minmax.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/pyramids.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/qr.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/svd.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/types.hpp
This PR introduces a new helper file with utility types and templates to standardize function interfaces. This refactor allows us to avoid duplicate code when types differ but logic remains the same.
The `flip` and `minmax` implementations have been updated to use the new generic helpers, replacing the previously defined, redundant classes.
Due to the large number of functions, not all interfaces are unified yet. Future development can extend the types as needed. While the usage of function templates is currently limited, this will ease future development.
> [Refactor](HAL RVV): Consolidate Helpers for Code Reusability

- modules/imgproc/src/demosaicing.cpp
I tested this patch on my 14900K desktop with `-DCPU_BASELINE=AVX2`, performance doesn't go down.
```
Name of Test                               old-avx2  avx2      avx2
vs
old-avx2
(x-factor)
cvtColorBayer8u::Size_CvtMode_Bayer::(7680x4320, COLOR_BayerBG2BGR)      4.325    4.139     1.04
cvtColorBayer8u::Size_CvtMode_Bayer::(7680x4320, COLOR_BayerBG2BGRA)     4.419    4.393     1.01
cvtColorBayer8u::Size_CvtMode_Bayer::(7680x4320, COLOR_BayerBG2BGR_VNG) 101.168  101.138    1.00
cvtColorBayer8u::Size_CvtMode_Bayer::(7680x4320, COLOR_BayerBG2GRAY)     0.950    0.913     1.04
cvtColorBayer8u::Size_CvtMode_Bayer::(7680x4320, COLOR_BayerGB2BGR)      4.085    4.045     1.01
cvtColorBayer8u::Size_CvtMode_Bayer::(7680x4320, COLOR_BayerGB2BGRA)     4.354    4.406     0.99 …
```
> Use universal intrinsics in bayer2gray

- modules/imgproc/src/demosaicing.cpp
Introduced in https://github.com/opencv/opencv/pull/26868
Warning:
```
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\src\demosaicing.cpp(683): warning C4101: 'vecOp': unreferenced local variable [C:\build\precommit_windows64\build\modules\imgproc\opencv_imgproc.vcxproj]
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\src\demosaicing.cpp(682): note: while compiling class template member function 'void cv::Bayer2Gray_Invoker<T,SIMDInterpolator>::operator ()(const cv::Range &) const'
with
[
T=uchar,
SIMDInterpolator=cv::SIMDBayerInterpolator_8u
]
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\src\demosaicing.cpp(793): note: see reference to class template instantiation 'cv::Bayer2Gray_Invoker<T,SIMDInterpolator>' being compiled
with
[
T=uchar, …
```
> Warning fix on Windows.

- modules/calib3d/src/calibration_base.cpp
Use only image contour for camera matrix undistortion. \
For inner and outer rectangles of the undistorted image only the image border should be necessary when standard distortion models are used. Using inner image points notably slows down the process since more points need to be undistorted (81 vs 32).
> Optimize camera matrix undistortion

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/filter.hpp
This patch implements `cv_hal_filter`, `cv_hal_sepFilter` and `cv_hal_morph` using native intrinsics, optimizing the performance of `cv::filter2D/cv::sepFilter/cv::Sobel/cv::Scharr` for `3x3/5x5` kernels and `cv::erode/cv::dilate/cv::morphologyEx` for `3x3` kernels.
Tested on MUSE-PI (Spacemit X60) for both gcc 14.2 and clang 20.0.
```
$ ./opencv_test_imgproc --gtest_filter="*Filter*:*Sobel*:*Erode*:*Dilate*:*Morph*"
$ ./opencv_perf_imgproc --gtest_filter="*TestFilter2d*:*sobel*:*scharr*:*erode*:*dilate*" --perf_min_samples=500 --perf_force_samples=500
```
View the full perf table here: [hal_rvv_filter.pdf](https://github.com/user-attachments/files/19130178/hal_rvv_filter.pdf)
Patch to …
> Add RISC-V HAL implementation for cv::filter series

- modules/objdetect/src/aruco/aruco_detector.cpp
Related to #26968 
Made the `ArucoDetector::ArucoDetectorImpl::filterTooCloseCandidates` method more unified and easier to understand.
Before - contours after the grouping stage can be in two states:
1. contained in `groupedCandidates` and `isSelectedContour = false` (group of several contours)
2. `isSelectedContour = true` (one independent contour).
But we can create a separate group for one independent contour - all contours will be in the same state and further processing code is already adapted for this and will be more unified.
These changes will help me make it easier to make changes in #26968  to fix failed tests.
> Refactor ArucoDetector::ArucoDetectorImpl::filterTooCloseCandidates

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/sqrt.hpp
Implement through the existing interfaces `cv_hal_sqrt32f`, `cv_hal_sqrt64f`, `cv_hal_invSqrt32f`, `cv_hal_invSqrt64f`.
Perf test done on MUSE-PI and CanMV K230. Because the performance of scalar is much worse than universal intrinsic, only ui and hal rvv is compared.
In RVV's UI, `invSqrt` is computed using `1 / sqrt()`. This patch first uses `frsqrt` and then applies the Newton-Raphson method to achieve higher precision. For the initial value, I tried using the famous [fast inverse square root algorithm](https://en.wikipedia.org/wiki/Fast_inverse_square_root), which involves one bit shift and one subtraction. However, on both MUSE-PI and CanMV K230, the performance was slightly lower (about 3%), so I chose to use `frsqrt` for the initial value instead. 
BTW, I think this patch can …
> [HAL RVV] impl sqrt and invSqrt

- modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp
Fix #27003 by converting to f64 before reduction to avoid overflow.
tested on QEMU (VLEN=128 to 1024) and SpaceMIT K1
` ./bin/opencv_perf_core --gtest_filter="MatType_Length_dot.dot/2*"`
> RISC-V: Fix #27003.

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/magnitude.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/sqrt.hpp
- modules/core/perf/perf_math.cpp
- modules/core/src/mathfuncs_core.simd.hpp
Implement through the existing `cv_hal_magnitude32f` and `cv_hal_magnitude64f` interfaces.
**UPDATE**: UI is enabled. The only difference between UI and HAL now is HAL use a approximate `sqrt`.
Perf test done on MUSE-PI.
```sh
$ opencv_test_core --gtest_filter="*Magnitude*"
$ opencv_perf_core --gtest_filter="*Magnitude*" --perf_min_samples=300 --perf_force_samples=300
```
Test result between enabled UI and HAL:
```
Name of Test                     ui    rvv      rvv    
vs    
ui    
(x-factor)
Magnitude::MagnitudeFixture::(127x61, 32FC1)    0.029  0.016     1.75   
Magnitude::MagnitudeFixture::(127x61, 64FC1)    0.057  0.036     1.57   
Magnitude::MagnitudeFixture::(640x480, 32FC1)   1.063  0.648     1.64   
Magnitude::MagnitudeFixture::(640x480, 64FC1)   2.261  1.530     1.48 …
```
> [HAL RVV] impl magnitude | add perf test

- modules/core/src/matmul.simd.hpp
- modules/imgproc/src/color_lab.cpp
- modules/imgproc/src/resize.cpp
This patch relax the loop condition to process the final batch.
Example:
If and only if `length` is an integer multiple of `step`, the original code will miss the last batch of vectorizable data and use the following scalar loop, although the result will be correct.
```diff
--- for (int i = 0; i < length - step; i += step)
+++ for (int i = 0; i <= length - step; i += step)
```
> Fix some vectorized loop conditions.

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/atan.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/cart_to_polar.hpp
- modules/core/perf/perf_math.cpp
- modules/core/src/mathfuncs_core.simd.hpp
Implement through the existing `cv_hal_cartToPolar32f` and `cv_hal_cartToPolar64f` interfaces.
Add `cartToPolar` performance tests.
cv_hal_rvv::fast_atan is modified to make it more reusable because it's needed in cartToPolar.
**UPDATE**: UI enabled. Since the vec type of RVV can't be stored in struct. UI implementation of `v_atan_f32` is modified. Both `fastAtan` and `cartToPolar` are affected so the test result for `atan` is also appended. I have tested the modified UI on RVV and AVX2 and no regressions appears.
Perf test done on MUSE-PI. AVX2 test done on Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz.
```sh
$ opencv_test_core --gtest_filter="*CartToPolar*:*Core_CartPolar_reverse*:*Phase*" 
$ opencv_perf_core --gtest_filter="*CartToPolar*:*phase*" --perf_min_samples=300 …
```
> [HAL RVV] reuse atan | impl cart_to_polar | add perf test

- modules/imgcodecs/src/grfmt_gif.cpp
This is according to https://www.w3.org/Graphics/GIF/spec-gif89a.txt
> Move the CV_Assert above the << operation to not trigger the fuzzer

- modules/core/src/norm.simd.hpp
It should look like this
https://github.com/opencv/opencv/blob/14396b802947d69d3cc44f0e809977b891ef8f4a/modules/core/src/norm.simd.hpp#L1229-L1230
https://github.com/opencv/opencv/blob/14396b802947d69d3cc44f0e809977b891ef8f4a/modules/core/src/norm.simd.hpp#L1248-L1249
https://github.com/opencv/opencv/blob/14396b802947d69d3cc44f0e809977b891ef8f4a/modules/core/src/norm.simd.hpp#L1267-L1268
> Fix a missing in the last 5.x merge 4.x

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/atan.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/cholesky.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/convert_scale.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/dxt.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/exp.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/filter.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/flip.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/log.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/lu.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/lut.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/mean.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/merge.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/minmax.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/norm.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/norm_diff.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/norm_hamming.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/pyramids.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/qr.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/sqrt.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/svd.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/types.hpp
Add copyright and in RVV HAL, since other companies or teams may join the development and add their copyright.
And the '#pragma once' are replaced.
> [RVV HAL] Add copyright and replace '#pragma once'.

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/polar_to_cart.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/pyramids.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/sincos.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/types.hpp
- modules/core/perf/perf_math.cpp
- modules/core/src/mathfuncs.cpp
- modules/core/src/mathfuncs_core.dispatch.cpp
- modules/core/src/mathfuncs_core.simd.hpp
1. Implement through the existing `cv_hal_polarToCart32f` and `cv_hal_polarToCart64f` interfaces.
2. Add `polarToCart` performance tests
3. Make `cv::polarToCart` use CALL_HAL in the same way as `cv::cartToPolar`
4. To achieve the 3rd point, the original implementation was moved, and some modifications were made.
Tested through:
```sh
opencv_test_core --gtest_filter="*PolarToCart*:*Core_CartPolar_reverse*" 
opencv_perf_core --gtest_filter="*PolarToCart*" --perf_min_samples=300 --perf_force_samples=300
```
***UPDATE***: Current implementation is no more depending on vlen.
**NOTE**: Due to the 4th point in the summary above, the `scalar` and `ui` test is based on the modified code of this PR. The impact of this patch on `scalar` and `ui` is evaluated in the next section, `Effect of Point …
> [HAL RVV] unify and impl polar_to_cart | add perf test

- modules/highgui/src/window_QT.cpp
Fixes #26555
An overlay should be displayed atop an image and then disappear after `delayms` has timed out, but it doesn't. Also, `displayStatusBar` doesn't appear to set any text on the window.
The overlay appears but doesn't disappear unless a mouse move event happens on the image.
- Fixed the issue with `displayOverlay` not disappearing after the timeout.
> displayOverlay doesn't disappear after timeout

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/moments.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/types.hpp
This patch implements `cv_hal_imageMoments` using native intrinsics, optimizing the performance of `cv::moments` for data types `CV_16U/CV_16S/CV_32F/CV_64F`.
Tested on MUSE-PI (Spacemit X60) for both gcc 14.2 and clang 20.0.
```
$ ./opencv_test_imgproc --gtest_filter="*Moments*"
$ ./opencv_perf_imgproc --gtest_filter="*Moments*" --perf_min_samples=1000 --perf_force_samples=1000
```
> Add RISC-V HAL implementation for cv::moments

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/histogram.hpp
This patch implements `cv_hal_equalize_hist` using native intrinsics, optimizing the performance of `cv::equalizeHist`.
Tested on MUSE-PI (Spacemit X60) for both gcc 14.2 and clang 20.0.
```
$ ./opencv_test_imgproc --gtest_filter="*Equalize_Hist*"
$ ./opencv_perf_imgproc --gtest_filter="*equalizeHist*" --perf_min_samples=10000 --perf_force_samples=10000
```
> Add RISC-V HAL implementation for cv::equalizeHist

- modules/imgcodecs/src/grfmt_gif.cpp
This fixes https://g-issues.oss-fuzz.com/issues/403364362
> GIF: Make sure to resize lzwExtraTable before each block

- modules/video/test/test_trackers.cpp
- modules/video/test/test_trackers.impl.hpp
Avoid very long test cases runs on CI by default.
Before:
```
[ RUN      ] Tracking/DistanceAndOverlap.GOTURN/1, where GetParam() = ("dudek")
startFrame = 1
frame size = [720 x 480]
command timed out: 600 seconds without output
```
After:
```
[ RUN      ] Tracking/DistanceAndOverlap.GOTURN/1, where GetParam() = ("dudek", 0)
Number of frames in test data: 106
[     SKIP ] Test with tag 'debug_verylong' is skipped ('debug_verylong' is in skip list)
[       OK ] Tracking/DistanceAndOverlap.GOTURN/1 (779 ms)
...
[ RUN      ] Tracking5Frames/DistanceAndOverlap.GOTURN/1, where GetParam() = ("dudek", 5)
Number of frames in test data: 106
Number of frames to test: 5
startFrame = 1
frame size = [720 x 480]
[       OK ] Tracking5Frames/DistanceAndOverlap.GOTURN/1 (11305 ms)
```
> video(test): filter very long debug tests

- samples/python/mosse.py
- samples/python/turing.py
> minor changes : Replace ndarray.ptp() with np.ptp() for NumPy 2.0 Compatibility

- modules/imgproc/include/opencv2/imgproc.hpp
As requested from issue #26799 the docs regarding minAreaRect and boxPoints are extended specifying the order of the corners for boxPoints and the way the angle is computed for the rotated rect returned by minAreaRect
> fix minAreaRect and boxPoints docs (#26799)

- modules/calib3d/include/opencv2/calib3d.hpp
Fixes error:
```
2025-03-25T07:01:03.2173607Z Executing: ['javadoc', '-windowtitle', 'OpenCV 4.12.0-dev Java documentation', '-doctitle', 'OpenCV Java documentation (4.12.0-dev)', '-nodeprecated', '-public', '-sourcepath', '/home/ci/build/OpenCV-android-sdk/sdk/java/src', '-encoding', 'UTF-8', '-charset', 'UTF-8', '-docencoding', 'UTF-8', '--allow-script-in-comments', '-header', "\n            <script>\n              var url = window.location.href;\n              var pos = url.lastIndexOf('/javadoc/');\n              url = pos >= 0 ? (url.substring(0, pos) + '/javadoc/mymath.js') : (window.location.origin + '/mymath.js');\n              var script = document.createElement('script');\n              script.src = 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS- …
```
> Fixed JavaDoc generation for StereoBM.

- doc/js_tutorials/js_assets/js_setup_usage.html
- doc/js_tutorials/js_setup/js_setup/js_setup.markdown
- doc/js_tutorials/js_setup/js_usage/js_usage.markdown
> doc: js: unwrap promise-typed cv object

- modules/imgcodecs/src/grfmt_gif.cpp
- modules/imgcodecs/src/grfmt_png.cpp
This fixes
https://g-issues.oss-fuzz.com/issues/405243132
https://g-issues.oss-fuzz.com/issues/405456349
> Fix heap buffer overflow and use after free in imgcodecs

- CMakeLists.txt
Clarify the motivation for https://github.com/opencv/opencv/pull/25941 inside CMakeLists.txt to avoid unecessary Issues (https://github.com/opencv/opencv/issues/27076) and PRs (https://github.com/opencv/opencv/pull/27085) in the future.
> cuda:: Add comment describing code around enable_language(CUDA) in CMakeLists.txt 

- modules/core/include/opencv2/core/utils/logger.hpp
- modules/core/src/logger.cpp
- modules/core/test/test_logger_replace.cpp
This is a competing PR, an alternative to #27140 
Both functions accept C-style pointer to static functions. Both functions allow restoring the OpenCV built-in implementation by passing in a nullptr.
- replaceWriteLogMessage
- replaceWriteLogMessageEx
This implementation is not compatible with C++ log handler objects.
This implementation has minimal thread safety, in the sense that the function pointer are stored and read atomically. But otherwise, the user-defined static functions must accept calls at all times, even after having been deregistered, because some log calls may have started before deregistering.
> User-defined logger callback, C-style.

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/filter.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/norm_diff.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/resize.hpp
This patch implements `cv_hal_resize` using native intrinsics, optimizing the performance of `cv::resize` for `CV_INTER_NEAREST/CV_INTER_NEAREST_EXACT/CV_INTER_LINEAR/CV_INTER_LINEAR_EXACT/CV_INTER_AREA` modes.
Tested on MUSE-PI (Spacemit X60) for both gcc 14.2 and clang 20.1.
```
$ ./opencv_test_imgproc --gtest_filter="*Resize*:*resize*"
$ ./opencv_perf_imgproc --gtest_filter="*Resize*:*resize*" --perf_min_samples=300 --perf_force_samples=300
```
View the full perf table here: [hal_rvv_resize.pdf](https://github.com/user-attachments/files/19480756/hal_rvv_resize.pdf)
> Add RISC-V HAL implementation for cv::resize

- modules/highgui/src/window_QT.cpp
- modules/highgui/src/window_QT.h
Notify the main GUI thread upon receiving a close event instead of when
the windows is destroyed. Additionally there was a logic error in in
GuiReceiver::isLastWindow() that is corrected.
Fixes #6479 and #20822
> Fix closing of windows when using the Qt backend

- modules/calib3d/test/test_solvepnp_ransac.cpp
It's more unified - in one place (in one function instead of two before).
It gives clearer log:
```
mode: no distortion, method: SOLVEPNP_IPPE -> Skip for non-planar object
mode: no distortion, method: SOLVEPNP_IPPE_SQUARE -> Skip for non-planar tag object
```
instead of
```
mode: no distortion, method: SOLVEPNP_IPPE -> 100% (maxErrT: -1, maxErrR: -1, meanErrT: -1, meanErrR: -1, medErrT: -1, medErrR: -1)
approximate translation threshold for 0.7: -1, approximate rotation threshold for 0.7: -1
mode: no distortion, method: SOLVEPNP_IPPE_SQUARE -> 100% (maxErrT: -1, maxErrR: -1, meanErrT: -1, meanErrR: -1, medErrT: -1, medErrR: -1)
approximate translation threshold for 0.7: -1, approximate rotation threshold for 0.7: -1
```
See details at …
> More elegant skipping SOLVEPNP_IPPE* methods in non-planar accuracy tests for solvePnP*

- cmake/OpenCVFindLAPACK.cmake
- cmake/OpenCVFindOpenBLAS.cmake
Main change is rewritten `OpenCVFindOpenBLAS.cmake`:
- search cmake package first
- search using environment variables second
- search in system locations last
- additionally search for lapacke.h and append its path to the result header location
Other changes:
- use arguments syntax for `ocv_lapack_check`
- debug output
Test framework (Linux): https://github.com/mshabunin/opencv-blas-check
Should be merged with https://github.com/opencv/ci-gha-workflow/pull/237
> build: fix OpenBLAS detection on Linux

- modules/highgui/src/window_QT.h
-------------------------------------------------------------------------------------------------------------
issue: https://github.com/opencv/opencv/issues/27187
Some legacy data structures (including CvArr) were removed in the 5.x branch. CvArr is no longer defined, but one reference remains in:
modules/highgui/src/window_QT.h
`void updateImage(const CvArr* arr) CV_OVERRIDE;`
should be changed to:
`void updateImage(cv::InputArray arr) CV_OVERRIDE;`
> remove undefined/legacy CvArr reference in window_QT.h

- modules/videoio/src/cap_v4l.cpp
- modules/videoio/test/test_v4l2.cpp
Resolves #27166
* Restored image initialization process for non-BGR data
* Minor code style changes (`convertToRgb`)
* Use non-rounded value when setting `CAP_PROP_FOURCC` property (it prevented selecting BE fourcc)
* Changed expected dimensions in the test for XBGR32 and ABGR32 formats
* Changed dump file names in the test
Notes:
* Broken in #26224 (4.11.0)
Dumped test files (with BGR conversion):
> videoio: fixed V4L frame size for non-BGR output

- modules/core/include/opencv2/core/mat.hpp
- modules/core/src/matrix.cpp
- modules/core/src/matrix_wrap.cpp
- modules/core/test/test_mat.cpp
I have an idea to optimize the convertTo operation for a Mat object. When src and dst are the same variable and their elemSize are equal, it could perform the operation in-place.  Based on the suggestion of vpisarev, I added an `reinterpret` API for reinterpreting the Mat type. Now, We can perform the following operations to reuse memory.
origin : (This will allocate new memory)
```
cv::Mat src(3, 5, CV_8UC1, cv::Scalar(1));
src.convertTo(src, CV_8S);
```
optimization: （dst and src point to the same address, and the convertTo operation will not allocate new memory.）
```
cv::Mat src(3, 5, CV_8UC1, cv::Scalar(1));
cv::Mat dst = src.reinterpret(CV_8SC1);
src.convertTo(dst, CV_8S);
```
In the convertTo scenario, leaving the decision of whether to reuse memory to the user is a more reasonable …
> Added reinterpret() method to Mat to convert meta-data without actual data conversion

- modules/core/perf/perf_mat.cpp
- modules/core/src/copy.cpp
Merge with https://github.com/opencv/opencv_extra/pull/1247.
> core: further vectorize copyTo with mask

- modules/imgproc/src/histogram.cpp
- modules/imgproc/test/test_histograms.cpp
Close https://github.com/opencv/opencv/issues/24757
> imgproc: disable SIMD for compareHist(INTERSECT) if f64 is unsupported

- modules/objdetect/src/qrcode_encoder.cpp
- modules/objdetect/test/test_qrcode_encode.cpp
The autodetected version is not honored in the `QRCodeEncoderImpl::encode*` methods. This fixes #27183
> Fix QR code encoder with autoversion

- modules/dnn/include/opencv2/dnn/dnn.hpp
- modules/dnn/misc/java/test/DnnBlobFromImageWithParamsTest.java
- modules/objdetect/include/opencv2/objdetect.hpp
Changed DataLayout and ImagePaddingMode to dnn::DataLayout and dnn::ImagePaddingMode to explicitly specify their scopes. This allows gen_java.py to correctly register disc_type, preventing constructors and methods using these enum types from being skipped during Java wrapper generation.
Similarly updated QRCodeEncoder::CorrectionLevel and QRCodeEncoder::EncodeMode with explicit scope declarations.
Also added a new Java test class `DnnBlobFromImageWithParamsTest` based on: https://github.com/opencv/opencv/blob/4.x/modules/dnn/test/test_misc.cpp#L133-L243
Related issues
#23753 
> Explicitly specify enum type scopes to improve Java wrapper generation

- modules/features2d/misc/java/gen_dict.json
- modules/features2d/misc/java/test/SIMPLEBLOBFeatureDetectorTest.java
This PR adds a type_dict entry for SimpleBlobDetector::blobColor to gen_dict.json, enabling the blobColor property to be exposed in the Java bindings.
As a result, the Java wrapper will automatically generate get_blobColor() and set_blobColor() methods, allowing access to the blobColor field from Java.
> Enable Java bindings for SimpleBlobDetector::blobColor

- 3rdparty/hal_rvv/hal_rvv_1p0/norm_diff.hpp
This patch is intended for 4.x to fix sanity checks in performance testings.
**Do not port to 5.x.**
Reproducer:
1. Build latest 4.x.
2. Run on QEMU or SpaceMIT K1:
```
export OPENCV_TEST_DATA_PATH=/path/to/opencv_extra/test_data
./opencv_perf_core --gtest_filter="*norm2*" --perf_force_samples=1
```
Issue:
<details>
```
[  FAILED  ] 32 tests, listed below:
[  FAILED  ] Size_MatType_NormType_norm2.norm2/30, where GetParam() = (640x480, 32SC1, NORM_INF)
[  FAILED  ] Size_MatType_NormType_norm2.norm2/31, where GetParam() = (640x480, 32SC1, NORM_L1)
[  FAILED  ] Size_MatType_NormType_norm2.norm2/33, where GetParam() = (640x480, 32SC1, NORM_INF|NORM_RELATIVE)
[  FAILED  ] Size_MatType_NormType_norm2.norm2/34, where GetParam() = (640x480, 32SC1, NORM_L1|NORM_RELATIVE)
[  FAILED  ] …
```
> HAL: aligned behavior of normDiff 32s kernels in hal_rvv in 4.x

- 3rdparty/hal_rvv/hal_rvv.hpp
- 3rdparty/hal_rvv/hal_rvv_1p0/transpose.hpp
- modules/core/perf/perf_arithm.cpp
> HAL: implemented cv_hal_transpose in hal_rvv

- modules/dnn/include/opencv2/dnn/dnn.hpp
**Description:**
This pull request adds the CV_WRAP annotation to the cv::dnn::Net::registerOutput method to make it accessible from language bindings such as Python and Java.
**Background**
The methods getUnconnectedOutLayers and getUnconnectedOutLayersNames are deprecated, and registerOutput is the recommended alternative. However, it is currently not available from wrappers, making migration difficult.
**Changes**
Added CV_WRAP to Net::registerOutput in dnn.hpp.
**Notes**
This change does not affect existing functionality and only exposes the method to binding generators.
Please let me know if further adjustments are needed.
> Add CV_WRAP to registerOutput for language bindings support

- modules/dnn/src/layers/attention_layer.cpp
- modules/dnn/test/test_layers.cpp
Rotary positional embeddings let an attention block encode the relative position between tokens. Widely adopted in LLMs such as LLaMA—and equally applicable to Vision Transformers—the ONNX Runtime com.microsoft.Attention operator already exposes this via its `do_rotary` flag (see docs), and this PR adds support for that flag in OpenCV.
_Operator spec: https://github.com/microsoft/onnxruntime/blob/v1.16.1/docs/ContribOperators.md#com.microsoft.Attention_
Materials:
- RoFormer paper https://arxiv.org/abs/2104.09864
- RoPe for Vision Transformer https://github.com/naver-ai/rope-vit
- llama implementation https://github.com/meta-llama/llama/blob/main/llama/model.py#L80
Merge with https://github.com/opencv/opencv_extra/pull/1250
See details at …
> Rotary positional embeddings

- modules/js/src/core_bindings.cpp
- modules/js/test/test_objdetect.js
Fixes https://github.com/opencv/opencv/issues/26626
```
> Fixed std::vector<Point3f> handling in JS wrappers

- modules/imgproc/src/color_hsv.dispatch.cpp
Fixes https://github.com/opencv/opencv/issues/24443
Replaces https://github.com/opencv/opencv/pull/24444
C++11 and upper guaranties that local static variables are initialized once in thread safe way.
> Reworked HSV color conversion tables initialization for OpenCL branch

- modules/core/include/opencv2/core/hal/intrin_lasx.hpp
- modules/core/include/opencv2/core/hal/intrin_lsx.hpp
Fixes https://github.com/opencv/opencv/issues/26758
BTW: There is compiler segmentaion fault with `features` about annoy with GCC-8 (8.3.0-6.lnd.vec.31) on the Loongnix 20 OS (CPU: Loongson-3C5000LL). Tested with `-DBUILD_opencv_features=OFF` and the build was successful.
> loongson/build: added v_gt and v_lt with lsx and lasx to fix build

- modules/imgcodecs/src/grfmt_png.cpp
- modules/imgcodecs/test/test_png.cpp
Close https://github.com/opencv/opencv/issues/27295
To optimize for the native pixel format of the iPhone's early PowerVR GPUs, Apple implemented a non-standard PNG format.
Details: https://theapplewiki.com/wiki/PNG_CgBI_Format
> imgcodecs: png: add log if first chunk is not IHDR

- samples/python/tutorial_code/imgProc/match_template/match_template.py
shape has Y first, then X. See issue #27292
> Update match_template.py to fix doc bug

- 3rdparty/openjpeg/openjp2/jp2.c
Cherry-picked https://github.com/uclouvain/openjpeg/pull/1573
> Cherry-pick OpenJPEG deconding status fix.

- hal/ndsrvp/src/bilateralFilter.cpp
- modules/imgproc/src/bilateral_filter.dispatch.cpp
- modules/imgproc/test/test_bilateral_filter.cpp
The PR resolves the issue: https://github.com/opencv/opencv/issues/22886
> Fixed bilateral filter's sigma color and sigma space issue

- modules/calib3d/src/solvepnp.cpp
Camera distortion model is not well defined outside of the frame. It may significantly distort axes.
Address https://github.com/opencv/opencv/issues/25967
> Added warning if projected axes are out of camera frame in drawAxes

- platforms/android/build_sdk.py
- platforms/android/default.config.py
Workaround for https://github.com/opencv/opencv/issues/26072
The IPP conflict blocks NDK update and fixes for issues [#27310](https://github.com/opencv/opencv/issues/27310), [#27024](https://github.com/opencv/opencv/issues/27024).
> Disable IPP for x86 32bit Android as it's incompatible with modern NDK.

- modules/core/include/opencv2/core/private.cuda.hpp
fixes #27289
File: modules/core/include/opencv2/core/private.cuda.hpp
Starting with CUDA 12.9, NVIDIA removed the helper API nppGetStreamContext() from public headers.
As a result, any module (e.g., OpenCV’s CUDA parts) that attempted to build with CUDA 12.9+ would fail at compile time:
1.  🧯 Add version guard for legacy toolkits
```cpp
#if CUDA_VERSION < 12090
nppSafeCall(nppGetStreamContext(&nppStreamContext)); 
#else
// Manual context construction below
```
2.  🛠 Manually construct NppStreamContext for CUDA ≥ 12.9
```cpp
int device = 0;
cudaSafeCall(cudaGetDevice(&device));
cudaDeviceProp prop{};
cudaSafeCall(cudaGetDeviceProperties(&prop, device));
nppStreamContext.nCudaDeviceId = device;
nppStreamContext.nMultiProcessorCount = prop.multiProcessorCount; …
```
> CUDA 12.9 support: build NppStreamContext manually

- modules/core/include/opencv2/core/mat.inl.hpp
- modules/core/test/test_mat.cpp
> Add missing Mat_<_Tp>::zeros(int _ndims, const int* _sizes)

- modules/core/src/norm.dispatch.cpp
- modules/core/src/norm.simd.hpp
If the norm is outside the array (e.g. Hamming), memory is read outside of the array, which does not matter because the invalid pointer is not used oustide of the function (e.g. the Hamming path is taken) but it triggers the sanitizer.
> Make sure to not access outside normDiffTab

- modules/calib3d/src/stereosgbm.cpp
- modules/calib3d/test/test_stereomatching.cpp
Addresses #25828 
Users noticed that StereoSGBM would occasionally give non-deterministic results for `.compute(imgL, imgR)`.
I and others traced the cause to out-of-bounds access that was not being caught when the input images were not wide enough for the input block size and number of disparities to StereoSGBM. The specific math and logic can be found in the above issue's discussion.
This PR adds a CV_Check to make sure images are wider than 1/2 of the block size + the max disparity the algorithm will search.
The check was only added to the regular `compute` method for StereoSGBM and not to the other modes, as I did not observe the non-deterministic behavior with the other compute modes like HH.
In addition, this PR adds a test case to Calib3d to make sure the check is being thrown in …
> Add image dimension check to avoid StereoSGBM non-determinism

- modules/core/include/opencv2/core/hal/intrin_legacy_ops.h
resolves #27267
* New header with removed universal intrinsics operator overloads must be included manually by the user if necessary. Transition to operator-less API is recommended.
* Basic compilation test can be performed by defining OPENCV_ENABLE_INLINE_INTRIN_OPERATOR_TEST macro before header inclusion. It is not meant to be run
* shift operators have not been defined due to potential conflicts with io streams
* safety checks for opencv build, opencv version and risc-v platform would produce compiler warnings and errors
> Restored legacy intrinsics operators in a separate header

- modules/core/include/opencv2/core.hpp
- modules/core/src/mathfuncs.cpp
- modules/core/test/test_math.cpp
Related to #27323 
I found only randomized tests with number of roots always equal to `1` or `3`, `x^3 = 0` and some simple test for Java and Swift.
Obviously, they don't cover all cases (implementation has strong branching and number of roots can be equal to `-1`, `0` and `2` additionally).
So, I think it will be useful to try explicitly cover more cases (and implementation branches correspondingly)
> Add tests for solveCubic

- modules/photo/src/hdr_common.cpp
- modules/photo/test/test_hdr.cpp
The PR resolves the issue for triangle Weights used by debevec algorithm being non zero at extremes. 
It resolves #24966 
The fix needs ground truth data to be changed in order to pass existing tests. PR to opencv_extra: https://github.com/opencv/opencv_extra/pull/1253
> Bug fix unstable crf

- hal/riscv-rvv/src/core/copy_mask.cpp
- hal/riscv-rvv/src/core/dotprod.cpp
- hal/riscv-rvv/src/core/norm.cpp
- hal/riscv-rvv/src/core/norm_diff.cpp
- modules/core/test/test_intrin_utils.hpp
- modules/dnn/src/layers/cpu_kernels/softmax.cpp
- modules/imgproc/src/color_hsv.simd.hpp
- modules/imgproc/src/pyramids.cpp
This PR addresses the following found warnings:
Tested building with GCC 14.2 (RISC-V 64).
> build: fix warnings from recent gcc versions

- modules/core/test/test_math.cpp
In test `TEST(Core_SolvePoly, regression_5599)` function `checkRoot` is used for checking that obtained roots contain all expected roots. To properly check multiple roots (roots with multiplicity greater than `1`) it should check that some root is presented exactly several times. For this in function there is logic to assign found roots to `NaN` but it didn't work because it used root copy instead of reference for it.
> Fix bug in solvePoly test

- 3rdparty/libtiff/tif_hash_set.c
- hal/riscv-rvv/src/core/copy_mask.cpp
- hal/riscv-rvv/src/core/flip.cpp
- hal/riscv-rvv/src/core/transpose.cpp
- modules/core/test/test_intrin_utils.hpp
- modules/imgproc/src/accum.simd.hpp
More fixings after https://github.com/opencv/opencv/pull/27337
> build: fix more warnings from recent gcc versions after #27337

- hal/kleidicv/CMakeLists.txt
Related patch to KleidiCV itself: https://gitlab.arm.com/kleidi/kleidicv/-/merge_requests/475
Current version of KleidiCV adds all HAL functions to cv namespace to fix short function names resolution during macro substitution. The root cause was covered in https://github.com/opencv/opencv/pull/26878.
> Disabled cv namespace usage inside KleidiCV.

- modules/core/include/opencv2/core/hal/intrin_legacy_ops.h
Fix for #27327 ([comment](https://github.com/opencv/opencv/pull/27327#discussion_r2094518977))
> core: legacy intrin operators - fixed version warning condition

- hal/riscv-rvv/src/core/common.hpp
- hal/riscv-rvv/src/core/div.cpp
Previous optimization on div in hal/riscv-rvv: https://github.com/opencv/opencv/pull/27175
> hal/riscv-rvv: further optimize div

- modules/core/src/mathfuncs.cpp
- modules/core/test/test_math.cpp
Fix #27323 
```
2e-13 * x^3 + x^2 - 2 * x + 1 = 0 -> x^3 + 5e12 * x^2 - 1e13 * x + 5e12 = 0
```
The problem that coefficients have quite big magnitudes and current calculations are subject to round-off error
```
Q = (a1 * a1 - 3 * a2) * (1./9)
R = (2 * a1 * a1 * a1 - 9 * a1 * a2 + 27 * a3) * (1./54)
Qcubed = Q * Q * Q = a1^6/729 - (a1^4 a2)/81 + (a1^2 a2^2)/27 - a2^3/27
R * R = R^2 = a1^6/729 - (a1^4 a2)/81 + (a1^2 a2^2)/36 + (a1^3 a3)/27 - (a1 a2 a3)/6 + a3^2/4
d = Qcubed - R * R
```
Let `a1`, `a2`, `a3` have quite big same magnitudes, then we see that `Qcubed` and `R * R` have same terms `a1^6/729` and `-(a1^4 a2)/81` (which will be reduced in `d`), but they level out the other terms (these terms have `6`th and `5`th degree and other terms - less or equal than `4`th degree).
So, if …
> Improve solveCubic accuracy

- doc/tutorials/dnn/dnn_openvino/dnn_openvino.markdown
- modules/dnn/include/opencv2/dnn/dnn.hpp
- modules/dnn/src/ie_ngraph.cpp
- modules/dnn/src/net_openvino.cpp
- modules/dnn/src/op_inf_engine.cpp
- OpenVINO now supports inference on integrated NPU devices in intel's Core Ultra series processors.
- Sometimes as fast as GPU, but should use considerably less power.
- The NPU plugin is now available as "NPU" in openvino `ov::Core::get_available_devices()`.
- Removed the guards and checks for NPU in available targets for Inference Engine backend.
- Intel [Core Ultra series processor](https://www.intel.com/content/www/us/en/products/details/processors/core-ultra/edge.html#tab-blade-1-0)
- [Intel NPU driver](https://github.com/intel/linux-npu-driver/releases)
- OpenVINO 2023.3.0+ (Tested on 2025.1.0)
```cpp
#include <opencv2/dnn.hpp>
int main(){
cv::dnn::Net net = cv::dnn::readNet("../yolov8s-openvino/yolov8s.xml", "../yolov8s-openvino/yolov8s.bin");
cv::Size …
```
> Feature: Add OpenVINO NPU support

- doc/opencv.bib
- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/src/shapedescr.cpp
- modules/imgproc/test/test_fitellipse.cpp
Sorry, for some reason the GitHub CI was not run in the previous PR https://github.com/opencv/opencv/pull/26237 
I have opened this one to have at least results from the GitHub CI + `pullrequest.opencv.org`
---
Following https://github.com/opencv/opencv/issues/26078, I was thinking that a function to get for a considered 2d point the corresponding closest point (or maybe directly the distance?) on an ellipse could be useful.
This would allow computing the fitting error with `fitEllipse()` for instance.
Code is based from:
- https://stackoverflow.com/questions/22959698/distance-from-given-point-to-given-ellipse/46007540#46007540
- https://blog.chatfield.io/simple-method-for-distance-to-ellipse/
- https://github.com/0xfaded/ellipse_demo
---
Demo code:
<details>
<summary>code</summary> …
> Add getClosestEllipsePoints() function to get the closest point on an ellipse

- 3rdparty/fastcv/fastcv.cmake
Update hash for the fastcv libs for Linux
Updated libs PR: https://github.com/opencv/opencv_3rdparty/pull/97
> FastCV latest libs hash update

- modules/videoio/src/cap_ffmpeg.cpp
- modules/videoio/src/cap_ffmpeg_impl.hpp
- modules/videoio/src/cap_gstreamer.cpp
- modules/videoio/test/test_ffmpeg.cpp
When writing grayscale images (`isColor=false`), `cv::VideoWriter` failed as FFmpeg backend requires input frames to be in a grayscale format. Unlike other backends, FFmpeg doesn't perform this conversion internally and expects the input to be pre-converted. To fix this, I inserted a check in the `CvVideoWriter_FFMPEG_proxy::write` to convert input frames to grayscale when the input has more than 1 channel. If this is true, then the input is converted to a gray image using `cv::cvtColor` (with `cv::COLOR_BGR2GRAY`).
Additionally, as suggested in the issue comments, I have correctly propagated the return value of `CvVideoWriter_FFMPEG::writeFrame` back to the `CvVideoWriter_FFMPEG_proxy::write`. This return value wasn't being used, and `writeFrame` was always returning false since the …
> fix #26276: cv::VideoWriter fails writing colorless images

- samples/python/drawing.py
This PR fixes a logical error in the `samples/python/drawing.py` script where both X and Y coordinates for drawing primitives (`cv.circle`, `cv.putText`, `cv.ellipse`) were being sampled from the X-axis range `(x1, x2)`. This led to improper distribution and alignment of elements along the Y-axis.
- Updated the second coordinate in `center` and `org` lists to use `(y1, y2)` instead of mistakenly reusing `(x1, x2)`.
- Affected functions:
- `circles()`
- `string()`
- `ellipse()`
This ensures that all shapes and text are now placed randomly and correctly across the entire canvas using the proper X and Y ranges.
---
Let me know if you'd like help opening a corresponding issue or testing these changes further.
> Fix incorrect Y-coordinate sampling in drawing primitives (circle, text, ellipse)

- modules/java/generator/android-21/java/org/opencv/android/JavaCamera2View.java
Fixed camera switching issue on Android devices: When a device has more than two cameras, the setCameraIndex method failed to switch to non-default cameras.
Root cause: The original code only considered two default camera IDs when updating camera IDs, ignoring all others. This fix ensures all camera IDs are properly handled.
> Fixed Android setCameraIndex issue.

- samples/directx/d3d11_interop.cpp
- samples/dnn/yolo_detector.cpp
- samples/winrt/ImageManipulations/MediaExtensions/OcvTransform/OcvTransform.cpp
Description:  
This pull request corrects several typographical errors in comments and error messages in the following files:
- `samples/directx/d3d11_interop.cpp`: Fixed typo in the error message ("betweem" → "between").
- `samples/dnn/yolo_detector.cpp`: Fixed typo in a comment ("elemets" → "elements").
- `samples/winrt/ImageManipulations/MediaExtensions/OcvTransform.cpp`: Fixed typo in a comment ("peferred" → "preferred").
These changes improve code readability and maintain consistency in documentation and error reporting. No functional code was modified.
> Fix Typos in Comments and Error Messages Across Multiple Files

- samples/dnn/person_reid.py
Description:  
This pull request corrects a minor typo in the docstring of the run_net function within samples/dnn/person_reid.py. The word "Forword" has been changed to the correct spelling "Forward" in the phrase "Forward propagation for a batch of images."
> Fix Typo in Function Docstring: "Forword" → "Forward" in person_reid.py

- modules/flann/include/opencv2/flann/autotuned_index.h
- modules/flann/include/opencv2/flann/composite_index.h
- modules/flann/include/opencv2/flann/kmeans_index.h
This pull request fixes several `-Wfloat-conversion` warnings in the FLANN module of OpenCV. These were caused by using double literals (e.g., `0.2`) in contexts where `float` was expected.
- Changed `0.2` → `0.2f`, `0.8` → `0.8f`, etc. in:
- `kmeans_index.h`
- `composite_index.h`
- `autotuned_index.h`
This improves clarity and avoids compiler warnings when building with `-Wfloat-conversion` enabled. The changes are minimal, safe, and help clean up the build output especially in strict compilation environments.
- Build successful with GCC 9.4.0 and `-Wfloat-conversion` enabled.
- Tested with `opencv_test_core`.
```bash
[ SKIPSTAT ] 118 tests skipped
[ SKIPSTAT ] TAG='mem_6gb' skip 1 tests
[ SKIPSTAT ] TAG='verylong' skip 1 tests
[ SKIPSTAT ] …
```
> Fix float-conversion warnings in FLANN by using float literals

- samples/cpp/kmeans.cpp
- samples/cpp/tutorial_code/gpu/gpu-thrust-interop/main.cu
Description:
This pull request corrects minor typos in comments and documentation within the codebase:
- Replaces "representitive" with "representative" in kmeans.cpp.
- Replaces "indices" with the correct spelling in a comment in main.cu.
> Fix Typos in Comments and Documentation

- hal/ipp/include/ipp_hal_core.hpp
- hal/ipp/src/norm_ipp.cpp
Workaround for #27380. Fix will be available in the next ICV package update based on IPP 2022.2.0.
> Added define disabling ippiNorm_Inf_16u_C1MR

- modules/imgproc/src/templmatch.cpp
- modules/imgproc/test/test_templmatchmask.cpp
Fix #26389 
Problem is in using `Mat::mul` method when second argument is `Matx41d` - in the end it calls `arithm_op` but second argument is casted to `Mat` before, but in `arithm_op` there is logic which relies on arguments perfect forwarding and it stops working https://github.com/opencv/opencv/blob/4d26e16af8f45dc8d356770749ae273c8992aa4e/modules/core/src/arithm.cpp#L642-L644
`multiply` function is equivalent to `Mat::mul` method (I hope so) with second argument perfect forwarding, so necessary logic continues to work
> Fix matchTemplate with mask crash

- hal/riscv-rvv/include/imgproc.hpp
> hal/riscv-rvv: disable integral for now

- modules/core/include/opencv2/core/cuda.hpp
- modules/core/src/cuda/gpu_mat.cu
Fix https://github.com/opencv/opencv/issues/27373.
1. `GpuMat::convertTo` uses `convertToScale` due to incorrect overload.
2. There are no runtime checks to prevent the use of `CV_16U` data types in Release builds.
> cuda: Fix GpuMat::convertTo issues described in 27373

- modules/core/src/norm.dispatch.cpp
- modules/core/src/norm.simd.hpp
Fixes https://github.com/opencv/opencv/issues/27465
Similar to https://github.com/opencv/opencv/pull/27321
> Fixed out-of-bound access to function table in cv::norm for HORM_HAMING

- modules/imgcodecs/CMakeLists.txt
Fixes a likely copy-paste error from #26379.
There's both a
```cmake
if(HAVE_JPEGXL)
ocv_include_directories(${JPEGXL_INCLUDE_DIRS})
message(STATUS "JPEGXL_INCLUDE_DIRS: ${JPEGXL_INCLUDE_DIRS}")
list(APPEND GRFMT_LIBS ${JPEGXL_LIBRARIES})
endif()
```
and
```cmake
if(HAVE_OPENJPEG)
ocv_include_directories(${OPENJPEG_INCLUDE_DIRS})
list(APPEND GRFMT_LIBS ${OPENJPEG_LIBRARIES})
endif()
```
in the CMake file, so 
```cmake
if(HAVE_JPEGXL)
ocv_include_directories(${OPENJPEG_INCLUDE_DIRS})
list(APPEND GRFMT_LIBS ${OPENJPEG_LIBRARIES})
endif()
```
is probably unintentional and incorrect. JPEG-XL does not depend on OpenJPEG in any way.
> imgcodecs: fix a minor bug in CMake for JPEG-XL

- modules/python/src2/hdr_parser.py
Before the patch I got the following with Python 3.5.2 (Ubuntu 16.04):
```
[ 14%] Building CXX object hal/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/src/count_nonzero.cpp.o
WARNING! Typing stubs can be generated only with Python 3.6 or higher. Current version sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
WARNING! Typing stubs can be generated only with Python 3.6 or higher. Current version sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
File "/mnt/disk/opencv-next/modules/python/src2/hdr_parser.py", line 150, in evaluate_conditional_inclusion_directive
preprocessor_definitions)
File "<string>", line 1
True andand False
^
SyntaxError: invalid syntax
The above exception was the direct cause …
```
> Fixed ifdef logic operators evaluation with some old python versions.

- modules/core/include/opencv2/core.hpp
resolves #26588
Note about possible inexact range conformity of NORM_MINMAX when using CV_32F data.
> doc: added note to normalize function

- modules/core/src/system.cpp
PR #25899 added an `std::terminate()` call without a corresponding include for `<exception>`:
https://github.com/opencv/opencv/blob/31b0eeea0b44b370fd0712312df4214d4ae1b158/modules/core/src/system.cpp#L1318-L1322
This can cause a compilation error if the header is not coincidentally included elsewhere, as encountered here: https://github.com/conan-io/conan-center-index/issues/27787
```
modules/core/src/system.cpp:1321:10: error: no member named 'terminate' in namespace 'std'
1321 |     std::terminate();
|     ~~~~~^
```
> system.cpp: add missing #include <exception>

- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/include/opencv2/imgproc/types_c.h
- modules/imgproc/src/morph.dispatch.cpp
- modules/imgproc/test/test_structuring_element.cpp
**Overview**
This PR introduces support for a new diamond-shaped structuring element in OpenCV’s morphology module. The addition enables users to perform morphological operations (e.g., erosion, dilation, opening, closing) using a diamond-shaped kernel, which is defined by Manhattan distance from the center.
Detailed Changes
New Enum Values:
Added MORPH_DIAMOND to MorphShapes in modules/imgproc/include/opencv2/imgproc.hpp and CV_SHAPE_DIAMOND to MorphShapes_c in modules/imgproc/include/opencv2/imgproc/types_c.h.
Kernel Generation Logic:
Updated getStructuringElement in modules/imgproc/src/morph.dispatch.cpp to:
Accept MORPH_DIAMOND as a valid shape.
Generate a diamond-shaped mask, where each pixel is included if its Manhattan distance from the center is within the kernel radius.
Unit …
> Add Support for Diamond-Shaped Structuring Element in Morphological Operations

- modules/imgproc/src/geometry.cpp
- modules/imgproc/test/test_intersectconvexconvex.cpp
As outlined in https://github.com/opencv/opencv/issues/26972 the function `intersectConvexConvex()` may not work as expected in the corner case, where two polygons intersect at a corner. A concrete example is given that I added as unit test. The unit test would fail without the proposed bug fix. I recommend porting the fix to all versions.
Now concerning the fix: When digging into the implementation I found, that when the line intersections are computed, openCV currently does not apply floating point comparison syntax, but pretends that line end points are exact. Instead I replaced the formulation using the eps that is already used in another component of the function in line.277: `epx=1e-5`. IMO that is solid enough, definitely better than assuming an exact floating point comparison is …
> Issue 26972: Proper treatment of float values in intersectConvexConvex

- doc/js_tutorials/js_imgproc/js_morphological_ops/js_morphological_ops.markdown
- doc/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.markdown
- doc/tutorials/imgproc/erosion_dilatation/erosion_dilatation.markdown
- samples/cpp/morphology2.cpp
- samples/cpp/tutorial_code/ImgProc/Morphology_1.cpp
- samples/cpp/tutorial_code/ImgProc/Morphology_2.cpp
- samples/gpu/morphology.cpp
- samples/java/tutorial_code/ImgProc/erosion_dilatation/MorphologyDemo1.java
- samples/python/morphology.py
- samples/python/tutorial_code/imgProc/erosion_dilatation/morphology_1.py
- samples/python/tutorial_code/imgProc/opening_closing_hats/morphology_2.py
Fixes #27489
This PR updates existing morphological operation samples and tutorials to include support for the `MORPH_DIAMOND` structuring element that was added in PR #27441.
- **Python tutorial** (`doc/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.markdown`): Added diamond kernel example with expected output
- **C++ tutorial** (`doc/tutorials/imgproc/erosion_dilatation/erosion_dilatation.markdown`): Added MORPH_DIAMOND to the list of available shapes
- **JavaScript tutorial** (`doc/js_tutorials/js_imgproc/js_morphological_ops/js_morphological_ops.markdown`): Updated description to mention diamond-shaped kernels
- **Python samples** (3 files): Added diamond shape option to morphology demos
- **C++ samples** (4 files): Added diamond shape with 'd' hotkey and trackbar …
> Add MORPH_DIAMOND support to samples and tutorials

- modules/videoio/misc/java/src/cpp/videoio_converters.hpp
In my configuration with bazel, when building the Java bindings, it is not like building C++ and including videio/videoio.hpp triggers:
error this is a compatibility header which should not be used inside the OpenCV library
> Include opencv2/videoio.hpp

- hal/ipp/include/ipp_hal_imgproc.hpp
- hal/ipp/src/precomp_ipp.hpp
- hal/ipp/src/warp_ipp.cpp
- modules/imgproc/src/imgwarp.cpp
IPP implementation of remap was moved from imgproc to HAL
Currently it's disabled as produce test fails. And would be enabled separately.
> Move IPP Remap to HAL

- cmake/OpenCVFindLibsPerf.cmake
Close https://github.com/opencv/opencv/issues/27530
> eigen: fix to get version from eigen after v3.4.0

- modules/dnn/src/caffe/caffe_importer.cpp
It has been marked for inlining, cf
https://github.com/protocolbuffers/protobuf/blob/930036a8cf4a489521ea78ea47510a3a6fb9d7c0/src/google/protobuf/descriptor.h#L936
> Replace deprecated proto2::FieldDescriptor::is_optional

- modules/python/src2/typing_stubs_generation/api_refinement.py
Fixes #27543.
Before patch
```python
@_typing.overload
def detectAndCompute(
self,
image: cv2.typing.MatLike,
mask: cv2.typing.MatLike,
descriptors: cv2.typing.MatLike | None = ...,
useProvidedKeypoints: bool = ...,
) -> tuple[_typing.Sequence[KeyPoint], cv2.typing.MatLike]: ...
@_typing.overload
def detectAndCompute(
self,
image: UMat,
mask: UMat,
descriptors: UMat | None = ...,
useProvidedKeypoints: bool = ...,
) -> tuple[_typing.Sequence[KeyPoint], UMat]: ...
```
After patch
```python
@_typing.overload
def detectAndCompute(
self,
image: cv2.typing.MatLike,
mask: cv2.typing.MatLike | None,
descriptors: cv2.typing.MatLike | None = ...,
useProvidedKeypoints: bool = ...,
) -> tuple[_typing.Sequence[KeyPoint], cv2.typing.MatLike]: ...
@_typing.overload
def detectAndCompute(
self,
image: …
```
> fix: mark Feature2D.detectAndCompute mask as optional in Python type stubs

- modules/videoio/include/opencv2/videoio.hpp
- modules/videoio/src/cap_ffmpeg_hw.hpp
- modules/videoio/src/cap_interface.hpp
- modules/videoio/test/test_precomp.hpp
- modules/videoio/test/test_video_io.cpp
- samples/tapi/video_acceleration.cpp
This PR enables V4L2 stateless HEVC hardware acceleration for Raspberry Pi 5 within OpenCV's videoio module. It leverages FFmpeg's drm acceleration ([FFmpeg API changes](https://github.com/FFmpeg/FFmpeg/blob/ee1f79b0fa4c82da9c19328b049b593c71611402/doc/APIchanges#L1529)), significantly improving HEVC decoding performance on RPi5 for robotics and embedded vision applications.
I have a working proof-of-concept with local benchmarks showing clear gains.
Checklist Status:
Ready: License, branch (4.x), FFmpeg reference, and (linked) related issue (#27452).
Seeking Guidance: Need help with formal C++ performance/accuracy tests, opencv_extra integration, and full documentation/examples.
As a Python developer, I welcome C++ best practice feedback and assistance with testing setup.
See details at …
> Add Raspberry Pi 4 and 5 V4L2 Stateless HEVC Hardware Acceleration with FFmpeg

- CMakeLists.txt
- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/src/grfmt_png.cpp
- modules/imgcodecs/test/test_png.cpp
This patch enables users to set the internal zlib compression buffer size for PNG encoding
> Add enum IMWRITE_PNG_ZLIBBUFFER_SIZE

- modules/gapi/include/opencv2/gapi/infer/ov.hpp
- modules/gapi/src/backends/ov/govbackend.cpp
Added the option cfgEnsureNamedTensors to be applied on OpenVINO models with nameless tensors. If a tensor doesn't have a name, it sets a default one. The default name is created using OpenVINO's standard `make_default_tensor_name` . `make_default_tensor_name`  had to be rewritten because it is only available in OpenVINO's dev_api.
> G-API: Implement cfgEnsureNamedTensors option to OpenVINO Params

- modules/core/src/persistence.cpp
- modules/core/src/persistence_json.cpp
- modules/core/test/test_io.cpp
Fixes https://github.com/opencv/opencv/issues/27578
> core: support parsing null in json parser in FileStorage

- modules/core/include/opencv2/core/fast_math.hpp
- This PR adds ARM64 NEON intrinsics-based implementation for the cvRound function in fast_math.hpp for ARM64 targets (_MSC_VER && _M_ARM64).
- Both float and double overloads now use NEON intrinsics (vcntn_s32_f32, vcvtn_s64_f64, etc.) for efficient and accurate rounding.
- The implementation is consistent with platform-specific handling already present for SSE2 (x64) and does not affect non-ARM64 builds.
**Performance Improvements :** 
- The optimization significantly improves the performance of cvRound on Windows ARM64 targets. 
- The table below shows timing comparisons before and after the optimization:
> core: add ARM64 NEON support for cvRound in fast_math.hpp

- modules/dnn/include/opencv2/dnn/all_layers.hpp
- modules/dnn/src/init.cpp
- modules/dnn/src/layers/topk2_layer.cpp
- modules/dnn/src/onnx/onnx_importer2.cpp
- modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_filter_opencv_classic_denylist.inl.hpp
- modules/dnn/test/test_onnx_conformance_layer_parser_denylist.inl.hpp
This pull request adds TopK layer support to new DNN engine along with dynamic K support.
Initial version inherited from https://github.com/opencv/opencv/pull/26731. Credits to Abduragim.
Closes:
- https://github.com/opencv/opencv/issues/27061
- https://github.com/opencv/opencv/issues/25712
Also closes the topk issue for below issues but having (`Unsupported operations:        NonZero` for new dnn engine) which is unrelated to topk.
- https://github.com/opencv/opencv/issues/23663 
- https://github.com/opencv/opencv/issues/23297
> Added TopK layer with dynamic K support for new DNN engine

- modules/imgproc/src/connectedcomponents.cpp
- modules/imgproc/test/test_connectedcomponents.cpp
Fix #27568 
The problem was caused by a label type overflow (`debug_example.npy` contains `92103` labels, that doesn't fit in the `CV_16U` (`unsigned short`) type). If pass `CV_32S` instead of `CV_16U` as `ltype` - everything will be calculated successfully
Added overflow detection to throw exception with a clear error message instead of strange segfault/assertion error
> Take into account overflow for connected components

- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/src/grfmt_png.cpp
- modules/imgcodecs/src/grfmt_spng.cpp
- modules/imgcodecs/test/test_png.cpp
Close https://github.com/opencv/opencv/issues/27614
> imgcodecs: png: adjust value range for IMWRITE_PNG_ZLIBBUFFER_SIZE

- modules/gapi/include/opencv2/gapi/infer/ov.hpp
- modules/gapi/src/backends/ov/govbackend.cpp
Added the option `cfgClampOutputs` to control where output clamping is performed for OpenVINO models. When enabled, output values are clamped in the PrePostProcessor stage instead of by the device or plugin. This provides a consistent and standardized clamping method across devices, helping to maintain accuracy regardless of device-specific clamping behavior.
> G-API: Implement cfgClampOutputs option to OpenVINO Params

- modules/js/src/helpers.js
This PR adds support for the new `Symbol.dispose` proposal, allowing OpenCV.js objects such as `cv.Mat` and `cv.UMat` to be used with the upcoming `using` keyword in JavaScript (TC39 proposal) and TypeScript 5.2+.
- Adds `[Symbol.dispose]` as an alias to `.delete()` for resource-managed OpenCV.js classes
- Conditional logic ensures compatibility and no effect on environments without `Symbol.dispose`
- Minimal, easily extensible design for future OpenCV classes
Closes #26157.
**Motivation:**
Manual `.delete()` calls can be error-prone and verbose. Supporting the new `using` keyword will improve resource safety and developer ergonomics per the [TC39 proposal](https://github.com/tc39/proposal-explicit-resource-management) and [TypeScript …
> Support Symbol.dispose for using keyword in OpenCV.js (#26157)

- modules/videoio/src/cap_dshow.hpp
This aligns with other virtual method declarations in cap_dshow.hpp and silences compiler warnings (-Wsuggest-override) while improving compile-time safety.
> videoio: add missing CV_OVERRIDE to VideoCapture_DShow::isOpened()

- modules/python/test/test_cuda.py
This test initially passed in https://github.com/opencv/ci-gha-workflow/actions/runs/16959806127/job/48069609176
> Skip test_cuda_copyTo

- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/src/subdivision2d.cpp
- modules/imgproc/test/test_subdivision2d.cpp
Closes https://github.com/opencv/opencv/issues/27623
Changes:
- Added Subdiv2D(Rect2f) constructor overload
- Added initDelaunay(Rect2f) method overload
- No changes to the previous implementation to keep it backward compatible
- Added tests for init and testing with edge case of extremely small coordinates
See original pull request at : https://github.com/opencv/opencv/pull/27631
> Subdiv2d rect2f clean

- modules/dnn/src/layers/elementwise_layers.cpp
- modules/dnn/src/layers/fully_connected_layer.cpp
- modules/dnn/src/layers/permute_layer.cpp
- modules/dnn/src/layers/reshape_layer.cpp
- modules/dnn/src/layers/resize_layer.cpp
- modules/dnn/src/layers/scale_layer.cpp
- modules/dnn/src/layers/shuffle_channel_layer.cpp
- modules/dnn/src/layers/slice_layer.cpp
- modules/dnn/src/layers/split_layer.cpp
Discussion: https://stackoverflow.com/questions/39932391/should-i-use-virtual-override-or-both-keywords
> Fixed -Wunnecessary-virtual-specifier warning produced latest clang.

- modules/imgproc/include/opencv2/imgproc.hpp
Fixed regression:
```
/Users/opencv-cn/GHA-OCV-1/_work/opencv/opencv/ios/build/build-armv7-iphoneos/lib/Release/opencv2.framework/Headers/opencv2.h:80:9: note: in file included from /Users/opencv-cn/GHA-OCV-1/_work/opencv/opencv/ios/build/build-armv7-iphoneos/lib/Release/opencv2.framework/Headers/opencv2.h:80:
#import <opencv2/Subdiv2D.h>
^
/Users/opencv-cn/GHA-OCV-1/_work/opencv/opencv/ios/build/build-armv7-iphoneos/lib/Release/opencv2.framework/Headers/Subdiv2D.h:94:1: error: duplicate declaration of method 'initWithRect:'
- (instancetype)initWithRect:(Rect2f*)rect;
^
/Users/opencv-cn/GHA-OCV-1/_work/opencv/opencv/ios/build/build-armv7-iphoneos/lib/Release/opencv2.framework/Headers/Subdiv2D.h:88:1: note: previous declaration is here
- (instancetype)initWithRect:(Rect2i*)rect;
^ …
```
> Fixed duplicate declaration issue in Swift/ObjC bindings

- modules/dnn/src/layers/cpu_kernels/fast_gemm.cpp
- modules/dnn/src/layers/cpu_kernels/fast_gemm_kernels.default.hpp
- modules/dnn/src/layers/cpu_kernels/fast_gemm_kernels.simd.hpp
the gemm kernel fails on cpu for large weight mats (eg 2304 x 257216) .
This can be solved by indexing the arrays with `size_t` instead of `int`.
> DNN fix fastgemm kernel for large mats

- modules/core/misc/java/gen_dict.json
- modules/dnn/misc/java/test/DnnForwardAndRetrieve.java
- modules/java/generator/src/cpp/converters.cpp
- modules/java/generator/src/cpp/converters.h
- modules/java/generator/src/java/org/opencv/utils/Converters.java
- Added vector_vector_Mat to gen_dict.json
- Implemented Mat_to_vector_vector_Mat and vector_vector_Mat_to_Mat conversion functions in converters.h/cpp and Converters.java
- Added DnnForwardAndRetrieve.java test to verify List<List<Mat>> conversion : Reference: C++ test in modules/dnn/test/test_misc.cpp - TEST(Net, forwardAndRetrieve)
https://github.com/opencv/opencv/blob/4.12.0/modules/dnn/test/test_misc.cpp#L584-L616
> Add Java wrapper support for List<List<Mat>>

- modules/dnn/misc/java/gen_dict.json
- modules/dnn/misc/java/src/cpp/dnn_converters.cpp
- modules/dnn/misc/java/src/cpp/dnn_converters.hpp
- modules/dnn/misc/java/test/DnnListRegressionTest.java
- modules/java/generator/src/java/org/opencv/utils/Converters.java
- Added vector_MatShape and vector_vector_MatShape to gen_dict.json
- Implemented MatShape_to_vector_MatShape, vector_MatShape_to_MatShape, MatShape_to_vector_vector_MatShape, and vector_vector_MatShape_to_MatShape conversion functions in dnn_converters.h/cpp and Converters.java
- Added testGetLayersShapes test to verify List<List<MatShape>> conversion
> Add Java wrapper support for List<List<MatShape>>

- modules/imgproc/test/test_fitellipse.cpp
Previous `fit_and_check_ellipse` implementation was very weak - it only checks that points center lies inside ellipse.
Current implementation `fit_and_check_ellipse` checks that points RMS (Root Mean Square) algebraic distance is quite small. It means that on average points are near boundary of ellipse. Because for points on ellipse algebraic distance is equal to `0` and for points that are close to boundary of ellipse is quite small
> Improve fitEllipseDirect tests

- cmake/OpenCVDetectCUDAUtils.cmake
e.g.
contrib\modules\cudev\include\opencv2\cudev/ptr2d/warping.hpp(86): warning C4505: 'cv::cudev::affineMap': unreferenced function with internal linkage has been removed
contrib\modules\cudev\include\opencv2\cudev/ptr2d/warping.hpp(134): warning C4505: 'cv::cudev::perspectiveMap': unreferenced function with internal linkage has been removed
> [cuda] Silence unreferenced function with internal linkage has been removed warnings in Windows

- modules/stitching/include/opencv2/stitching/detail/exposure_compensate.hpp
- modules/stitching/src/exposure_compensate.cpp
closes https://github.com/opencv/opencv/issues/27752
> Renamed templated BlocksCompensator::feed method to exclude claches with base class pure virtual method

- modules/dnn/src/layers/einsum_layer.cpp
- modules/gapi/include/opencv2/gapi/core.hpp
Summary
- Corrected numerous spelling mistakes and improved clarity in the DNN Einsum layer, including renamed variables, refined comments, and clearer error messaging around output dimensions and broadcasting
- Fixed dimensionality typos in the G-API k-means documentation, ensuring accurate descriptions of N-dimensional inputs and outputs
> Fix typos in Einsum layer and G-API docs

- modules/videoio/src/cap_ffmpeg_impl.hpp
https://github.com/opencv/opencv/pull/27741 included a preprocessor directive inside the `CV_LOG_DEBUG` macro resulting in the following build errors on Windows with `OPENCV_FFMPEG_USE_FIND_PACKAGE=ON`
> D:\repos\opencv\opencv\modules\videoio\src\cap_ffmpeg_impl.hpp(1727): error C2121: '#': invalid character: possibly the result of a macro expansion
> D:\repos\opencv\opencv\modules\videoio\src\cap_ffmpeg_impl.hpp(1727): error C2143: syntax error: missing ';' before 'if'
> D:\repos\opencv\opencv\modules\videoio\src\cap_ffmpeg_impl.hpp(1727): error C2059: syntax error: '>='
PR moves the preprocessor directive outside of macro.
> [videoio][ffmpeg] Fix Windows build error

- modules/python/src2/typing_stubs_generation/__init__.py
- modules/python/src2/typing_stubs_generation/ast_utils.py
- modules/python/src2/typing_stubs_generation/nodes/__init__.py
- modules/python/src2/typing_stubs_generation/nodes/type_node.py
Closes #27727
Generated type hint example:
```python
@_typing.overload
def imread(filename: str | os.PathLike[str], flags: int = ...) -> cv2.typing.MatLike | None: ...
@_typing.overload
def imread(filename: str | os.PathLike[str], dst: cv2.typing.MatLike | None = ..., flags: int = ...) -> cv2.typing.MatLike | None: ...
@_typing.overload
def imread(filename: str | os.PathLike[str], dst: UMat | None = ..., flags: int = ...) -> UMat | None: ...
```
<details>
<summary>List of affected functions and arguments </summary>
```txt
Algorithm::save pathlike argument = filename
FileStorage::FileStorage pathlike argument = filename
FileStorage::open pathlike argument = filename
Index::save pathlike argument = filename
Index::load pathlike argument = filename
Index::load pathlike argument = filename …
```
> feat: add PathLike type hints for args annotated with CV_WRAP_FILE_PATH

- modules/dnn/src/layers/cpu_kernels/convolution.cpp
- modules/dnn/src/layers/cpu_kernels/convolution.hpp
We can see ~20% inference time reduction on local benchmark.
The local benchmark includes face detection with res10_300x300_ssd_iter_140000_fp16.caffemodel and image classification with squeezenet.onnx .
> dnn: Tune CONV_NR_FP32 size for WASM

- doc/pattern_tools/gen_pattern.py
- doc/pattern_tools/test_charuco_board.py
The index is needed to generate several different boards with the same dictionary.
> Added option to define Aruco index offset in pattern generator

- modules/dnn/src/layers/cpu_kernels/softmax.cpp
- This PR applies loop unrolling in the softmax function.
- The change does not affect functional correctness.
**Performance Improvements**
- The optimization significantly improves the performance of softmax_3d on Windows ARM64 targets.
> dnn: improve performance of softmax_3d with loop unrolling

- modules/3d/src/rgbd/hash_tsdf_functions.cpp
- modules/3d/src/rgbd/hash_tsdf_functions.hpp
- modules/3d/test/test_tsdf.cpp
HashTSDF should expand volume units during integration. It didn't happen in fact because of wrong Mat passing.
> Fixed HashTSDF expand bug

- modules/js/src/core_bindings.cpp
- platforms/js/build_js.py
Related patch in main repo: https://github.com/opencv/opencv_contrib/pull/4007
> Added option to wrap opencv_contrib into JS too.

- modules/objdetect/src/qrcode.cpp
- modules/objdetect/test/test_qrcode.cpp
This is fixing https://github.com/opencv/opencv/issues/27807
Changed decode to gracefully return an empty result instead of throwing on zero-area quads. This aligns with decodeMulti which already filters invalid quadrilaterals and avoids exceptions for degenerate inputs.
The scripts and images mentioned in https://github.com/opencv/opencv/issues/27807 were used to test the changes.
> Fix to prevent QR code decoding from throwing exception on degenerate quadrilaterals

- modules/imgcodecs/src/grfmt_bmp.cpp
The issue was introduced in https://github.com/opencv/opencv/pull/27559
> Fixed out-of-bound access during extra params handing in BMP encoder.

- modules/dnn/CMakeLists.txt
- modules/dnn/src/layers/fully_connected_layer.cpp
- modules/dnn/src/layers/layers_common.simd.hpp
- modules/dnn/src/layers/recurrent_layers.cpp
- This PR improves the performance of the LSTM function on ARM64 targets.
- Added a NEON intrinsics implementation of the fastGEMM1T function and enabled its use in fully connected and recurrent layers file. 
- As a result, ARM64 now benefits from vectorized matrix–vector multiplications, leading to measurable performance improvements in the LSTM layer.
- This change is limited to ARM64 and does not affect other architectures.
**Performance impact:**
- The optimization significantly improves the performance of lstm functions on ARM64 targets.
> dnn: added neon intrinsics implementation of fastGEMM1T function

- doc/tutorials/introduction/env_reference/env_reference.markdown
- modules/videoio/src/cap_ffmpeg_impl.hpp
OpenCV’s InternalFFMpegRegister overwrites av_log_set_callback, blocking custom FFmpeg log handlers in statically linked apps.
Add `OPENCV_FFMPEG_SKIP_LOG_CALLBACK` to let applications keep their own logging.
> Add OPENCV_FFMPEG_SKIP_LOG_CALLBACK to preserve custom FFmpeg logging

- apps/interactive-calibration/calibController.cpp
- doc/tutorials/calib3d/interactive_calibration/interactive_calibration.markdown
- doc/tutorials/objdetect/aruco_board_detection/aruco_board_detection.markdown
- doc/tutorials/objdetect/charuco_detection/charuco_detection.markdown
All subsequent scripts rely on `camera_matrix` and `distortion_coefficients` fields names. For example
> Rename fields in camera calibration results

- modules/imgproc/CMakeLists.txt
- modules/imgproc/src/box_filter.dispatch.cpp
- modules/imgproc/src/box_filter.simd.hpp
* Perform row and column filter operations in a single pass.
* Temporary storage of intermediate results are avoided.
* Impacts 32F and 64F inputs for ksize <=5.
> Improved blur
