opencv/opencv

- modules/core/include/opencv2/core/private.cuda.hpp
- modules/cudaimgproc/include/opencv2/cudaimgproc.hpp
- modules/cudaimgproc/perf/perf_histogram.cpp
- modules/cudaimgproc/src/canny.cpp
- modules/cudaimgproc/src/cuda/canny.cu
- modules/cudaimgproc/src/gftt.cpp
- modules/cudaimgproc/src/histogram.cpp
- modules/cudaimgproc/src/hough_circles.cpp
- modules/cudaimgproc/src/hough_lines.cpp
- modules/cudaimgproc/src/hough_segments.cpp
- modules/cudaimgproc/src/mssegmentation.cpp
- samples/gpu/performance/tests.cpp
* Added `stream` parameter to all routines.
* Removed buffered versions of histogram functions, used `BufferPool` mechanism instead.
> Finish cudaimgproc module refactoring

- modules/objdetect/src/opencl/objdetect_hog.cl
check_regression=*OCL*
test_modules=objdetect
test_filter=*OCL*
build_examples=OFF
Signed-off-by: Yan Wang <yan.wang@linux.intel.com>
> OCL: [objdetect_hog]Use hypot to do vector calculation.

- modules/videoio/src/cap_images.cpp
Add CV_CAP_PROP_POS_FRAMES property to CvCapture_Images
> Add CV_CAP_PROP_POS_FRAMES property to CvCapture_Images 

- modules/objdetect/src/cascadedetect.cpp
- modules/objdetect/src/opencl/cascadedetect.cl
Signed-off-by: Yan Wang <yan.wang@linux.intel.com>
> OCL: [objdetect]Avoid compile unnecessary OpenCL kernel.

- modules/core/src/arithm.cpp
```
addWeighted::Size_MatType::(640x480, 8SC1)              2.257 ms  0.166 ms    13.58   
addWeighted::Size_MatType::(640x480, 16SC1)             2.211 ms  0.162 ms    13.65   
addWeighted::Size_MatType::(1280x720, 8SC1)             6.750 ms  0.493 ms    13.69   
addWeighted::Size_MatType::(1280x720, 16SC1)            6.638 ms  0.448 ms    14.82   
addWeighted::Size_MatType::(1920x1080, 8SC1)            15.111 ms 1.156 ms    13.07   
addWeighted::Size_MatType::(1920x1080, 16SC1)           14.994 ms 1.135 ms    13.21  
```
> SSE2 optimization of addWeighted

- modules/features2d/include/opencv2/features2d.hpp
- samples/python2/calibrate.py
- samples/python2/common.py
- samples/python2/deconvolution.py
- samples/python2/digits_video.py
- samples/python2/edge.py
- samples/python2/find_obj.py
- samples/python2/fitline.py
- samples/python2/lappyr.py
- samples/python2/mosse.py
- samples/python2/mser.py
- samples/python2/plane_ar.py
- samples/python2/plane_tracker.py
- samples/python2/squares.py
- samples/python2/stereo_match.py
* images were moved to a data folder
* features2d classes and StereoBM/StereoSGBM need a _create() function
what could not be fixed, due to lack of ml wrappers:
digits.py, digits_adjust.py, digits_video.py, gaussian_mix.py letter_recog.py:
> python samples: fixes for latest changes in opencv3.0 api

- modules/imgproc/src/smooth.cpp
- modules/objdetect/src/cascadedetect.cpp
- modules/objdetect/src/cascadedetect.hpp
- modules/stitching/src/blenders.cpp
- Gaussian blur;
- CascadeClassifier;
- Blenders in stitching module;
- Laplacial pyramids in stitching module.
> OpenCV for Tegra compilation fix

- modules/core/src/system.cpp
http://code.opencv.org/issues/4145
> fixed compilation with -m32

- CMakeLists.txt
https://github.com/Itseez/opencv/pull/3639 for 2.4 branch
> Do not blacklist GStreamer on Apple

- modules/flann/include/opencv2/flann/any.h
> Make flann::anyimpl::get_policy thread-safe (backport)

- doc/tutorials/imgproc/histograms/template_matching/template_matching.rst
as described in http://code.opencv.org/issues/4154
> fixing tutorial errors for 2.4

- doc/opencv.bib
- modules/ml/doc/ml_intro.markdown
- modules/ml/include/opencv2/ml.hpp
- fixed one BiB record
- moved algorithms overview to separate page
- added docs for some enumerations
- fixed some small documentation errors
> Reorganized ML module documentation

- data/haarcascades/haarcascade_fullbody.xml
- data/haarcascades/haarcascade_lowerbody.xml
- data/haarcascades/haarcascade_smile.xml
- data/haarcascades/haarcascade_upperbody.xml
as suggested in http://code.opencv.org/issues/3637
do not mind naming of my branch, based it on master instead of 2.4 ...
> fixing wrong model sizes

- apps/traincascade/boost.cpp
Small fix in boost codes in traincascade application
> Fix small error in traincascade application

- modules/videoio/src/cap_ximea.cpp
See http://code.opencv.org/issues/4176 for more details
> Fixing XIMEA parameters mapping (issue #4176)

- doc/tutorials/imgproc/histograms/template_matching/template_matching.markdown
as described in http://code.opencv.org/issues/4154
> fixing tutorial errors master branch

- doc/py_tutorials/py_video/py_lucas_kanade/py_lucas_kanade.markdown
Just fixing a small error in the docs
> Fixed doc error in optical flow

- modules/core/src/conjugate_gradient.cpp
This minor defect was found with Cppcheck
> Reduce variable scope

- data/CMakeLists.txt
> Install data and test data on Windows

- doc/tutorials/ios/hello/hello.rst
Adding comments for newer xcode and ios versions: http://code.opencv.org/issues/4004
> add remarks for iOS tutorial

- apps/traincascade/cascadeclassifier.cpp
I noticed a lot of people are misguided by the automated message that appears always! Changed it so that it only displays when the actual data is loaded! This should remove confusion!
> fix message of preloaded parameters

- modules/imgproc/doc/structural_analysis_and_shape_descriptors.rst
http://code.opencv.org/issues/3028 added remark about which technique was selected.
> add fit ellipse technique notice

- modules/highgui/doc/user_interface.rst
fixing http://code.opencv.org/issues/3714 for 2.4 branch
> fix bug 3714 2.4 branch

- modules/highgui/include/opencv2/highgui.hpp
as suggested in http://code.opencv.org/issues/3714 for master branch
> fix error 3714

- apps/traincascade/cascadeclassifier.cpp
same as https://github.com/Itseez/opencv/pull/3708 but this was not yet added to the master branch!
> add same functionality as 2.4

- apps/annotation/opencv_annotation.cpp
This is a frequently asked application by many OpenCV Q&A forum users so I decided to make this interface publically available in the codebase.
> Universal OpenCV based annotation tool for making createsamples input data

- cmake/FindCUDA.cmake
- cmake/FindCUDA/make2cmake.cmake
- cmake/FindCUDA/parse_cubin.cmake
- cmake/FindCUDA/run_nvcc.cmake
- cmake/OpenCVDetectCUDA.cmake
these cmake scripts correctly find CUDA during cross-compilation
> FindCUDA.cmake backport from master

- modules/imgproc/src/drawing.cpp
> Same as PR #3309. Pushing to master

- modules/dynamicuda/src/cuda/matrix_operations.cu
Previous implementation was not thread/stream safe, since it used constant memory.
The new implementation doesn't use any global objects, so it is thread/stream safe.
> Fix GpuMat::setTo implementation

- doc/py_tutorials/py_imgproc/py_contours/py_contours_begin/py_contours_begin.markdown
http://code.opencv.org/issues/4151
> add extra output argument to tutorial

- modules/calib3d/src/posit.cpp
Too wide scope items were found with Cppcheck
> Reduce variables scope, move declaration to first use

- data/haarcascades/haarcascade_frontalcatface.xml
- data/haarcascades/haarcascade_frontalcatface_extended.xml
- data/lbpcascades/lbpcascade_frontalcatface.xml
This commit adds the following cascades for detecting frontal cat faces:
data/haarcascades/haarcascade_frontalcatface.xml
data/haarcascades/haarcascade_frontalcatface_extended.xml
data/lbpcascades/lbpcascade_frontalcatface.xml
The same cascades are already in the master (3.0) branch.
> Cat face detection cascades

- apps/CMakeLists.txt
- apps/annotation/CMakeLists.txt
- apps/annotation/opencv_annotation.cpp
same commit as https://github.com/Itseez/opencv/pull/3653
Video of workings in other PR!
> add annotation tool master branch

- doc/py_tutorials/py_imgproc/py_houghlines/py_houghlines.markdown
- samples/python2/houghlines.py
rows and cols in the lines Mat are swapped wrt. 2.4
> fix houghlines.py sample and tutorial

- modules/imgproc/src/canny.cpp
Generally a good speedup.
I did some tests in a quad core:
Measured 40-80% speedup compared to IPP.
Speedup compared to the pure serial code 2.4x
IPP cpu utilization was 100%
TBB cpu utilization was 265%
So IPP is more efficient, but TBB is faster. Also non-x86 platforms will benefit from TBB.
check_regression=*anny*
> Canny TBB Optimization

- modules/core/src/stat.cpp
- modules/core/test/ocl/test_arithm.cpp
- modules/features2d/perf/opencl/perf_orb.cpp
- modules/imgproc/src/morph.cpp
- modules/imgproc/src/smooth.cpp
- modules/imgproc/test/ocl/test_canny.cpp
- modules/imgproc/test/ocl/test_warp.cpp
* disabled some kernels
* increased eps for some functions
> OCL: disabled some kernels for Android && NVidia

- modules/core/src/matrix.cpp
> Fix potential null pointer dereference

- doc/tutorials/features2d/feature_flann_matcher/feature_flann_matcher.markdown
- doc/tutorials/features2d/feature_homography/feature_homography.markdown
2.4 api usage changed to 3.0 style.
> fix features2d tutorials

- apps/annotation/CMakeLists.txt
like suggested by @alalek in https://github.com/Itseez/opencv/pull/3654
> update cmakelists for annotation tool

- doc/py_tutorials/py_bindings/py_bindings_basics/py_bindings_basics.markdown
This is my first PR so I have kept it short. Addresses issue [#4219](http://code.opencv.org/issues/4219). Please review, I might have done it incorrectly.
> Fix documentation in python binding tutorial

- apps/annotation/CMakeLists.txt
like suggested by @alalek in https://github.com/Itseez/opencv/pull/3654
> update cmakelists of annotation tool

- modules/imgproc/src/imgwarp.cpp
> Double used as boolean for no reason

- modules/core/include/opencv2/core/cvdef.h
- modules/video/src/bgfg_KNN.cpp
Added ARM implementation in cvRound function
- note: uses VFPv3 instructions
- also added overloaded cvRound variants with float and int parameters
- thanks to Marina Kolpakova from Itseez for idea
- thanks to developers from #llvm IRC channel for help with inline asm
> Round on arm

- modules/ml/include/opencv2/ml.hpp
- modules/ml/src/lr.cpp
REG_NONE defined in ml.hpp conflicts with defined in Winnt.h
> Fixed compile error build with VisualStudio2013 on windows.

- modules/objdetect/src/cascadedetect.cpp
added a check to prevent illegal access to operator[] when vector is empty
> issue 3710

- platforms/winrt/setup_winrt.ps1
Replacing license headers per [PR-3700 feedback](https://github.com/Itseez/opencv/pull/3700).
> Replacing license headers per PR-3700 feedback.

- modules/calib3d/include/opencv2/calib3d.hpp
@vpisarev Please review.
Addresses issue [#4221](http://code.opencv.org/issues/4221).
> Add documentation for solvePnP in calib3d

- apps/traincascade/imagestorage.cpp
same as https://github.com/Itseez/opencv/pull/3783
> fixing universal location execution

- modules/highgui/src/window_QT.cpp
Fixing the problem reported in 
http://code.opencv.org/issues/4244
> Fixing the bug #4244 that I just reported in code.opencv.org

- modules/core/include/opencv2/core/persistence.hpp
Small error - object fs does not exist in this code example
> Fixed persistent.hpp documentation

- modules/core/include/opencv2/core/utility.hpp
- modules/core/src/precomp.hpp
- modules/core/src/system.cpp
Moved out of TLS to properly collect data from different threads;
Concurrent access guards were added to collection functions;
> Implementation collector update;

- modules/core/src/parallel.cpp
Performance test reports can be [found here](https://github.com/MSOpenTech/opencv/wiki/Performance)
Increase performance / reduces execution time for cases when tasks can be effectively paralleled and load is enough for the parallel execution to result into substantial benefit for example for [imgproc](http://rawgit.com/wiki/MSOpenTech/opencv/test/performance/test-concurrent/5e47f433bcbde27e916dc174f380751863bc71cc/imgproc-summary.html) and [features](http://rawgit.com/wiki/MSOpenTech/opencv/test/performance/test-concurrent/5e47f433bcbde27e916dc174f380751863bc71cc/features-summary.html) modules. No impact or [limited](https://software.intel.com/en-us/articles/amdahls-law-gustafsons-trend-and-the-performance-limits-of-parallel-applications) negative impact for cases when tasks are not …
> Added WinRT concurrency support.

- modules/androidcamera/camera_wrapper/camera_wrapper.cpp
Uninitialized members issue found with Cppcheck
> Fix uninitialized members, fix log output typo

- modules/core/include/opencv2/core/cvstd.hpp
I experienced the same problem as #4125 (http://code.opencv.org/issues/4125), and the proposed fix is valid to the best of my knowledge. I'd therefore like to submit a pull request for it here.
> Fix issue #4125: compiler error on std::swap with CUDA7.0/clang/OSX

- cmake/checks/winrttest.cpp
> Removing unused winrttest.cpp file

- samples/cpp/lkdemo.cpp
In MacOSx x64 it was getting a memory leak even without initializing points:
http://code.opencv.org/issues/4250
> Update lkdemo.cpp because of memory leak

- modules/core/include/opencv2/core.hpp
documentation for the hconcat and vconcat functionality. some code snippets are provided as well.
> documentation for the hconcat and vconcat functions

- apps/traincascade/traincascade.cpp
same as https://github.com/Itseez/opencv/pull/3810/files
> update traincascade assigned memory buffers

- doc/tutorials/introduction/table_of_content_introduction.markdown
- doc/tutorials/introduction/transition_guide/transition_guide.markdown
This document describes some aspects of 2.4->3.0 transition process.
> Transition guide

- modules/photo/src/fast_nlmeans_denoising_invoker_commons.hpp
> Fix build with MSVS2010 / MSVS2012

- modules/imgproc/src/emd.cpp
thanks to Daniel DeMenthon for the bug report!
> initialize the output flow in EMD

- modules/videoio/CMakeLists.txt
- modules/videoio/include/opencv2/videoio.hpp
- modules/videoio/src/cap.cpp
- modules/videoio/src/cap_dshow.hpp
- modules/videoio/src/cap_intelperc.hpp
- modules/videoio/src/cap_mjpeg_decoder.cpp
- modules/videoio/src/cap_mjpeg_encoder.cpp
- modules/videoio/src/precomp.hpp
filename should end with .avi; fourcc should be "MJPG". As some debugging logs show, the current tests already test this branch well.
> added self-contained motion jpeg encoder

- modules/core/src/pca.cpp
These minor defects were found with Cppcheck
> Reduce variables scope

- doc/tutorials/calib3d/camera_calibration/camera_calibration.markdown
- samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp
- update documentation
* correct the part about fixed aspect
* improve formatting
* add snippet markers to source
* replace inline code by @ snippet
- do not run calibration twice when using a imageList
- make output consistent in itself (CamelCase vs no_camel_case) as well as with old camera calibrate sample
- respect write extrinsic/ points flags
- set the aspectRatio value when specified
- fix writing of calibration settings. also update grammar.
> update camera_calibration sample

- modules/ml/src/svm.cpp
- modules/ml/test/test_svmtrainauto.cpp
Fixes http://code.opencv.org/issues/4030
> Bugfix: #4030 SVM auto-training.

- .gitignore
- 3rdparty/libjpeg/CMakeLists.txt
- 3rdparty/libtiff/CMakeLists.txt
- modules/imgcodecs/CMakeLists.txt
- samples/winrt/OcvImageProcessing/OcvImageProcessing/MainPage.xaml.cpp
- samples/winrt/OcvImageProcessing/OcvImageProcessing/MainPage.xaml.h
- samples/winrt/OcvImageProcessing/OcvImageProcessing/opencv.props
- Enabling 'imgcodecs' module
- Adding sample code
> Adding support for imgcodecs on WinRT

- modules/gpu/test/test_objdetect.cpp
Initialize HOG after CUDA device switch.
> Fix tests for gpu HOG

- apps/traincascade/cascadeclassifier.cpp
- apps/traincascade/cascadeclassifier.h
- apps/traincascade/traincascade.cpp
- doc/user_guide/ug_traincascade.rst
Same as https://github.com/Itseez/opencv/pull/3798
> add the possibility to add traincascade accuracy

- apps/traincascade/cascadeclassifier.cpp
like spotted by @vpisarev we made a clear mistake ...
more info see https://github.com/Itseez/opencv/pull/3798
> fixing wrong equation in accuracy break rule

- modules/highgui/src/cap_ximea.cpp
Fix for the Ximea cameras support (http://code.opencv.org/issues/4235)
> Ximea camera fix (see issue #4235)

- modules/python/src2/cv2.cpp
Add some `#ifdef`s such that python wrapper builds independent of other components.
> Remove python wrapper dependency to individual components

- doc/tutorials/introduction/linux_gcc_cmake/linux_gcc_cmake.markdown
- samples/cpp/example_cmake/CMakeLists.txt
- samples/cpp/example_cmake/example.cpp
The example project to use with cmake.
+ minor fix in cmake usage tutorial
> Add cpp sample project

- modules/imgcodecs/test/test_drawing.cpp
- modules/imgproc/src/drawing.cpp
> add Cyrillic support to 3.0; from #3265 #3336

- modules/imgproc/src/morph.cpp
I have changed the signature a bit. Hope that's not a problem.
> Fix for Bug4243

- modules/calib3d/include/opencv2/calib3d.hpp
> Fix typo in documentation. F = K^-T * E * K^-1

- modules/viz/src/vizimpl.cpp
Should fix #4191 (http://code.opencv.org/issues/4191)
> Null Pointer check in vizimpl.cpp (Bug #4191)

- cmake/OpenCVDetectCXXCompiler.cmake
- cmake/templates/OpenCVConfig.cmake.in
- doc/tutorials/imgproc/imgtrans/hough_lines/hough_lines.markdown
- samples/cpp/openni_capture.cpp
referencing PRs #81 #3923 #3824 #3721
edit: reordered PRs to commit list
> ports to master (part 1)

- CMakeLists.txt
- modules/highgui/doc/reading_and_writing_images_and_video.rst
- modules/highgui/src/grfmt_tiff.cpp
- modules/java/generator/src/java/android+AsyncServiceHelper.java
- samples/cpp/delaunay2.cpp
- samples/cpp/grabcut.cpp
- samples/cpp/houghcircles.cpp
- samples/cpp/kalman.cpp
- samples/cpp/lkdemo.cpp
- samples/cpp/openni_capture.cpp
- samples/cpp/starter_video.cpp
- samples/cpp/stereo_calib.cpp
- samples/cpp/tutorial_code/Histograms_Matching/MatchTemplate_Demo.cpp
- samples/cpp/tutorial_code/ShapeDescriptors/findContours_demo.cpp
sample references( #81 #3229 #823 #3217 #785 #841 #3867 #3615 #2850 #3925)
referencing needed backports #3906 #3744 #3729
edit: reordered PR list to commits
edit2: if needed i can also split this PR in more PRs please give then a max amount of commits to be used at once for one PR
> backports from master (part 1)

- modules/imgproc/src/drawing.cpp
- modules/imgproc/test/test_contours.cpp
> copying fix #3961 from 2.4

- modules/objdetect/src/hog.cpp
bugfix_for_hog_detectMultiScale_with_weights
issue : http://code.opencv.org/issues/4284
> bugfix_for_hog_detectMultiScale_with_weights

- doc/tutorials/core/adding_images/adding_images.rst
- doc/tutorials/core/basic_geometric_drawing/basic_geometric_drawing.rst
- doc/tutorials/core/random_generator_and_text/random_generator_and_text.rst
- modules/calib3d/doc/camera_calibration_and_3d_reconstruction.rst
#3954 - 9e29762
#3967 - 1a2880e
> backports to 2.4 (recent)

- modules/gpu/src/cuda/element_operations.cu
- modules/gpu/src/element_operations.cpp
- modules/gpu/test/test_core.cpp
http://code.opencv.org/issues/4315
> Bug #4315 : fix CUDA bitwise operations with mask

- doc/tutorials/features2d/feature_description/feature_description.markdown
- doc/tutorials/features2d/feature_flann_matcher/feature_flann_matcher.markdown
- doc/tutorials/features2d/feature_homography/feature_homography.markdown
- doc/tutorials/features2d/trackingmotion/good_features_to_track/good_features_to_track.markdown
* addtional Mask argument in detectAndCompute()
* setMinHessian() -> setHessianThreshold()
* cv::line is in imgproc nowadays
> small fixes for features2d tutorials

- modules/core/src/matrix.cpp
- modules/core/src/stat.cpp
- modules/core/test/test_mat.cpp
- modules/hal/src/matrix.cpp
- modules/imgproc/src/filter.cpp
- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/test/test_contours.cpp
- modules/imgproc/test/test_filter.cpp
- modules/imgproc/test/test_imgwarp.cpp
- modules/photo/src/calibrate.cpp
- modules/photo/src/denoising.cpp
- modules/photo/src/tonemap.cpp
- modules/photo/test/test_denoising.cpp
fixes
http://code.opencv.org/issues/2736 (there is no bug, but test added),
http://code.opencv.org/issues/3305,
http://code.opencv.org/issues/3519,
http://code.opencv.org/issues/3733,
http://code.opencv.org/issues/4190
and several other bugs - see comments to the subsequent commits
> Imgproc video fixes

- modules/objdetect/src/hog.cpp
- modules/videoio/src/cap_ximea.cpp
#3667 - f39d351
#3946 - b73894b
> ports to master (part 3)

- modules/core/misc/java/src/java/core+Mat.java
- modules/java/generator/gen_java.py
reverted from commit 52fa55a770cb07a6401aa6617b81f413d1165771 and commit 4743184
> Revert of "Merge pull request #4014" and "Merge pull request #4006"

- CMakeLists.txt
- cmake/OpenCVFindLibsVideo.cmake
- cmake/templates/cvconfig.h.in
- modules/videoio/CMakeLists.txt
- modules/videoio/include/opencv2/videoio.hpp
- modules/videoio/include/opencv2/videoio/videoio_c.h
- modules/videoio/src/cap.cpp
- modules/videoio/src/cap_gphoto2.cpp
- modules/videoio/src/precomp.hpp
- modules/videoio/test/test_precomp.hpp
- samples/cpp/autofocus.cpp
I've created connection to gPhoto2 library.
It supports plenty of digital cameras (list) for direct capture, liveview and configuration.
Example of usage - implementation of autofocus.
This is cleaned up pull request after mishmash in #3997
> Digital camera VideoCapture - connection to gPhoto2 library 

- modules/core/include/opencv2/core/persistence.hpp
- modules/core/src/persistence.cpp
- modules/features2d/src/mser.cpp
- modules/features2d/test/test_descriptors_regression.cpp
- modules/features2d/test/test_matchers_algorithmic.cpp
- modules/features2d/test/test_mser.cpp
fixed http://code.opencv.org/issues/4308
added test for http://code.opencv.org/issues/3943 (cannot reproduce the bug with ORB and SIFT)
> Features2d fixes

- modules/videoio/include/opencv2/videoio/cap_winrt.hpp
- modules/videoio/src/cap.cpp
- modules/videoio/src/cap_winrt/MediaStreamSink.cpp
- modules/videoio/src/cap_winrt_bridge.cpp
- modules/videoio/src/cap_winrt_bridge.hpp
- modules/videoio/src/cap_winrt_capture.cpp
- modules/videoio/src/cap_winrt_capture.hpp
- modules/videoio/src/cap_winrt_video.cpp
- modules/videoio/src/cap_winrt_video.hpp
A few refactoring changes simplifying inner structure of videoio for WinRT bits, comment improvements and overall code cleanup.
> Videoio for WinRT maintenance update

- modules/calib3d/src/triangulate.cpp
A more detailed description of the problem and its solution can be found here: http://nbviewer.ipython.org/gist/cr333/3669d59d99c2ed46c315
(This is the equivalent fix to #4008 for master.)
> Fixed triangulation bug http://code.opencv.org/issues/4334.

- modules/androidcamera/camera_wrapper/camera_wrapper.cpp
- modules/calib3d/include/opencv2/calib3d.hpp
- modules/calib3d/src/stereobm.cpp
- modules/core/doc/intro.markdown
- modules/core/include/opencv2/core/matx.hpp
- modules/core/src/matop.cpp
- modules/highgui/src/ppltasks_winrt.h
- modules/highgui/src/window_cocoa.mm
- modules/imgproc/include/opencv2/imgproc/types_c.h
- modules/imgproc/src/contours.cpp
- modules/imgproc/src/filterengine.hpp
- modules/java/generator/src/java/android+JavaCameraView.java
- modules/photo/include/opencv2/photo.hpp
- modules/photo/include/opencv2/photo/cuda.hpp
- modules/stitching/src/motion_estimators.cpp
- modules/ts/include/opencv2/ts.hpp
- modules/videoio/src/cap_gstreamer.cpp
- modules/videoio/src/cap_ios_abstract_camera.mm
- modules/videoio/src/cap_libv4l.cpp
- modules/videoio/src/cap_mjpeg_encoder.cpp
- modules/videoio/src/cap_v4l.cpp
- modules/videoio/src/ppltasks_winrt.hpp
commits found with command to find commits committed to 2.4 but not to master
```git log --no-merges master..2.4```
I will try to get more commits into the master branch in the future.
it's really sad to see so many bugs fixed in 2.4 which did not get merged yet.
#2558 - acbc736
#2691 - 22c0238
#2815 - 6a50a51
#2816 - e9bc9c4
#2827 - 25b4cfa
based on #2898 - 7ca0557
#2903 - 607d3b5
#2957 - 55a5e6b
#2967 - 4f95e6c
#2971 - 9c8255f
enough for this PR i think.
commits still missing: ~490
Edit: this PR should get built on iOS too is there a way i can trigger this is this triggered manually by the collaborators?
> ports to master (part 4)

- samples/cpp/tutorial_code/xfeatures2D/LATCH_match.cpp
Based on the following paper:
Gil Levi and Tal Hassner, "LATCH: Learned Arrangements of Three Patch Codes", arXiv preprint arXiv:1501.03719, 15 Jan. 2015
link:
http://arxiv.org/abs/1501.03719
Gil.
> Added sample code for LATCH

- doc/tutorials/introduction/transition_guide/transition_guide.markdown
As suggested here: http://code.opencv.org/issues/4346
> Transition guide: how to check library version

- modules/calib3d/src/calibration.cpp
- modules/calib3d/src/ptsetreg.cpp
- modules/calib3d/src/solvepnp.cpp
- modules/calib3d/test/test_cameracalibration.cpp
- modules/calib3d/test/test_fundam.cpp
- modules/calib3d/test/test_homography.cpp
- modules/calib3d/test/test_solvepnp_ransac.cpp
- modules/core/src/mathfuncs.cpp
fixed several bugs in calib3d, reported at code.opencv.org
> Calib3d fixes

- modules/core/include/opencv2/core/optim.hpp
See http://code.opencv.org/issues/4345
> Fixed doc typo

- modules/videoio/include/opencv2/videoio.hpp
See http://code.opencv.org/issues/4303
> Adding missing docs for VideoWriter::release

- modules/imgproc/src/opencl/canny.cl
Signed-off-by: Zhigang Gong <zhigang.gong@intel.com>
> Fixed the race condition between inc and dec on the l_counter.

- modules/objdetect/src/detection_based_tracker.cpp
Fix for a potential data race condition, reported in Coverity Scan
> Fix for a potential data race condition

- samples/winrt_universal/VideoCaptureXAML/video_capture_xaml/video_capture_xaml.Shared/main.cpp
Extending UAP WinRT application with the ability to detect human faces using OCV default Haar classifier.
> Added video face detection WinRT sample. Restructured code.

- cmake/OpenCVFindLibsPerf.cmake
- modules/objdetect/src/hog.cpp
- modules/superres/src/frame_source.cpp
- modules/videoio/include/opencv2/videoio/videoio_c.h
- modules/videoio/src/cap_dc1394_v2.cpp
- modules/videoio/src/cap_ximea.cpp
- samples/cpp/facial_features.cpp
commits found with command to find commits committed to 2.4 but not to master
```git log --no-merges master..2.4```
#3376 - e96b8ce
#3382 - 6aedd4f
#3412 - 8454a8f
#3425 - 83723c1
#3419 - e9c765e
#3498 - bb72206
#3683 - eb40dde
~110 commits to review
~130 commits need further attention later
> ports to master (part 6)

- samples/python2/digits.py
digits.py python sample contained opencv 2 code, refactored to work with 3.0.0-rc1 API
> fixed digits.py sample to work with opencv 3

- modules/calib3d/test/test_homography.cpp
- modules/core/test/test_hal_core.cpp
- modules/imgproc/src/sumpixels.cpp
- modules/objdetect/src/cascadedetect.cpp
- modules/objdetect/src/cascadedetect.hpp
- modules/objdetect/src/hog.cpp
- modules/objdetect/src/opencl/cascadedetect.cl
- modules/objdetect/test/test_cascadeandhog.cpp
- samples/python2/facedetect.py
fixes several bugs related to objdetect; as a side result, added/modified two more tests to core and calib3d
> Objdetect fixes

- samples/cpp/matchmethod_orb_akaze_brisk.cpp
see http://answers.opencv.org/question/61062/features2d-example/
> A sample program  : how to use ORB AKAZE BRISK descriptors for matching.

- modules/core/src/parallel_pthreads.cpp
- modules/video/src/ecc.cpp
ECC (comments from https://github.com/Itseez/opencv/pull/3845);
as well as minor tweak in pthread's based parallel for (num_threads = 2 on Android by default; check nstripes before going into parallel loop)
> made improvements in ECC code and parallel_for

- modules/imgproc/doc/feature_detection.rst
During my project, we see some typos in docs of cornerEigenValsAndVecs.
* Correct covariation matrix formula of Harris corner detector in function cornerEigenValsAndVecs.
* The correct formula can be found in [Computer Vision: Algorithms and Applications book] (http://szeliski.org/Book/drafts/SzeliskiBook_20100903_draft.pdf), and [wikipedia](http://en.wikipedia.org/wiki/Corner_detection).
> correct covariation matrix formula of Harris corner detector

- modules/calib3d/src/upnp.cpp
#4091 got closed when I deleted the old patch-1 branch.
Hence creating this new PR.
The PR fixes multiple resource leaks.
> Fixing resource leaks

- modules/python/src2/gen2.py
base classes will be searched after parsing all header files
(http://code.opencv.org/issues/4384)
> Python generator: moved base class handling to the generate step

- cmake/templates/OpenCVConfig.cmake.in
- samples/cpp/example_cmake/CMakeLists.txt
See: https://github.com/Itseez/opencv/pull/4125#issuecomment-112842255
> Interface.sample

- modules/videoio/src/cap_ffmpeg_impl.hpp
thanks @hackeron for the notice
introduced in #4051
> fix one dict parameter in ffmpeg implementation (introduced while porting)

- modules/features2d/src/matchers.cpp
- modules/python/src2/cv2.cpp
Issue with the analysis: http://code.opencv.org/issues/4385
> Flann based matcher python wrapper issue

- modules/core/include/opencv2/core/base.hpp
- modules/core/include/opencv2/core/private.hpp
- modules/core/src/convert.cpp
- modules/core/src/copy.cpp
- modules/core/src/matrix.cpp
- modules/core/src/precomp.hpp
- modules/core/src/stat.cpp
- modules/imgproc/src/accum.cpp
- modules/imgproc/src/color.cpp
- modules/imgproc/src/corner.cpp
- modules/imgproc/src/deriv.cpp
- modules/imgproc/src/filter.cpp
- modules/imgproc/src/histogram.cpp
- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/src/morph.cpp
- modules/imgproc/src/pyramids.cpp
- modules/imgproc/src/smooth.cpp
- modules/imgproc/src/sumpixels.cpp
- modules/imgproc/src/templmatch.cpp
- modules/imgproc/src/thresh.cpp
IPP code path  implemented as separate static functions to simplify future work with IPP code and make it more readable.
> IPP code refactored

- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/perf/perf_spatialgradient.cpp
- modules/imgproc/src/precomp.hpp
- modules/imgproc/src/spatialgradient.cpp
- modules/imgproc/test/test_filter.cpp
void spatialGradient( InputArray src, OutputArray dx, OutputArray dy, int ksize );
Equivalent in functionality to the following:
Sobel( src, dx, CV_16SC1, 1, 0, 3 );
Sobel( src, dy, CV_16SC1, 0, 1, 3 );
> spatialGradient (hal accelerated)

- modules/videoio/src/cap_mjpeg_encoder.cpp
Removing deadcode blocks, redudant variable & added initialization in constructor
> Fixing mjpeg_encoder Coverity found defects

- modules/ml/src/svm.cpp
http://code.opencv.org/issues/4464
> Fix SVM::trainAuto (Bug #4464)

- modules/core/include/opencv2/core/mat.inl.hpp
- modules/core/src/matop.cpp
- modules/core/test/test_mat.cpp
http://code.opencv.org/issues/4457
> Issue 4457

- modules/calib3d/test/test_chesscorners_timing.cpp
See also Itseez/opencv_extra#261.
> CV_ChessboardDetectorTimingTest: don't ignore missing test data

- modules/imgproc/src/rotcalipers.cpp
https://bugs.launchpad.net/ubuntu/+source/gcc-4.9/+bug/1474304
It needed a refactoring, anyway.
> Refactor a section of icvRotatingCalipers to work around a GCC bug

- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/src/grfmt_base.cpp
- modules/imgcodecs/src/grfmt_base.hpp
- modules/imgcodecs/src/grfmt_jpeg.cpp
- modules/imgcodecs/src/loadsave.cpp
- modules/imgcodecs/src/precomp.hpp
by this new function we can set libjpeg "scale_denom" parameter and load jpeg images scaled 1/2 - 1/4 - 1/8
other image formats resized after loading
> new function imread_reduced()

- modules/core/include/opencv2/core/opengl.hpp
- modules/core/src/opengl.cpp
- samples/opengl/opengl_interop.cpp
Previously added CL/GL interop core support & sample: added ogl::Buffer support.
> Opencl opengl buffer

- samples/opencl/opencl-opencv-interop.cpp
fix some issues reported by Dmitry Budnikov
> fix for opencl-opencv interop

- modules/calib3d/include/opencv2/calib3d.hpp
- modules/calib3d/perf/perf_stereosgbm.cpp
- modules/calib3d/src/stereosgbm.cpp
- modules/calib3d/test/test_stereomatching.cpp
- samples/cpp/stereo_match.cpp
Current speedup is around 2-3x with almost the same quality as MODE_SGBM.
> Adding new mode to StereoSGBM and introducing HAL acceleration

- cmake/OpenCVDetectDirectX.cmake
- cmake/checks/directx.cpp
- cmake/templates/cvconfig.h.in
- modules/core/src/directx.cpp
- samples/directx/d3d11_interop.cpp
```
error C2065: 'DXGI_FORMAT_NV12' : undeclared identifier
```
> Fix build with Win7 SDK

- samples/python2/digits.py
- samples/python2/digits_adjust.py
This removes picloud support from the digits_adjust sample (as picloud is discontinued). It also fixes the SVM wrapper to not reset C and gamma parameters to 1 when training.
> Fix python2 OCR / StatsModel examples

- modules/cudaimgproc/src/histogram.cpp
- modules/cudaoptflow/src/farneback.cpp
- modules/cudaoptflow/src/pyrlk.cpp
- modules/cudaoptflow/src/tvl1flow.cpp
Compilation errors were corrected when the CUDA SDK is not found and the BUILD_CUDA_STUBS flag in CMake is ON.
> Fixes compilation errors when BUILD_CUDA_STUBS is ON

- modules/core/src/ocl.cpp
- modules/core/src/umatrix.cpp
- modules/core/test/test_umat.cpp
- modules/imgproc/src/color.cpp
Replaces #4205
```
check_regression=*Mog2*
```
> OCL: Fix 4006

- samples/opengl/opengl_interop.cpp
- samples/opengl/winapp.hpp
updated code for PR 5099 (remove odd "no processing" branch)
> replace for 5099 (update)

- modules/imgproc/test/test_imgwarp.cpp
Added more resize_area tests to ensure right rounding behaviour for half and quarter downscaling
> Added more resize_area tests

- doc/header.html
> Documentation: adding Google Custom Search block to each header

- modules/core/include/opencv2/core/affine.hpp
@alalek very minor, can merge right now
> minor comment fix

- apps/annotation/opencv_annotation.cpp
Adding some checks to avoid problems like described here
https://github.com/Itseez/opencv/issues/5104#issuecomment-127357826
> add checks on input parameters for valid path and folder

- apps/annotation/opencv_annotation.cpp
Adding some checks to avoid problems like described here
https://github.com/Itseez/opencv/issues/5104
> add checks for valid input data given to parameters

- modules/core/test/test_umat.cpp
Enabled tests were passed:
http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/3369
> TAPI: add tests from issue 4468 (#5062)

- modules/ml/src/inner_functions.cpp
> ML: Fixing possible corruption for big training data sizes

- samples/android/CMakeLists.txt
- samples/android/face-detection/jni/Android.mk
- samples/android/tutorial-2-mixedprocessing/jni/Android.mk
- samples/android/tutorial-4-opencl/CMakeLists.txt
- samples/android/tutorial-4-opencl/jni/Android.mk
- samples/android/tutorial-4-opencl/jni/CLprocessor.cpp
- samples/android/tutorial-4-opencl/jni/GLrender.cpp
Enable Android sample from #4239
> Update Android samples

- modules/core/src/ocl.cpp
- modules/core/test/test_umat.cpp
fixes for non contiguous UMat download/upload
> fixed dynamic memory overrun in UMat download/upload methods for non contiguous umat

- modules/videoio/src/cap.cpp
- modules/videoio/src/cap_openni2.cpp
- modules/videoio/src/precomp.hpp
https://github.com/Itseez/opencv/issues/4918
> fix build error when both OpenNI and OpenNI2 are supported (issue 4918)

- modules/viz/include/opencv2/viz/types.hpp
- modules/viz/include/opencv2/viz/viz3d.hpp
- modules/viz/include/opencv2/viz/widgets.hpp
- modules/viz/src/precomp.hpp
- modules/viz/src/shapes.cpp
- modules/viz/src/types.cpp
- modules/viz/src/viz3d.cpp
- modules/viz/src/vizimpl.cpp
- modules/viz/src/vizimpl.hpp
- modules/viz/src/widget.cpp
- load OBJ file
- set offscreen rendering
- set roll angle of the camera
- get Mat screenshot of the current scene
- remove all lights from the scene
- add a custom light in the scene
- modify the size of the WImage3D widget
- added ambient property for the widget
> Added new functionalities to viz module

- modules/imgcodecs/src/rgbe.cpp
Header parsing loop has been updated
Following example of file header should be successfully parsed now:
```
00000000  23 3f 52 41 44 49 41 4e  43 45 0a 23 20 4d 61 64  |#?RADIANCE.# Mad|
00000010  65 20 77 69 74 68 20 46  72 65 65 49 6d 61 67 65  |e with FreeImage|
00000020  20 33 2e 31 33 2e 31 0a  46 4f 52 4d 41 54 3d 33  | 3.13.1.FORMAT=3|
00000030  32 2d 62 69 74 5f 72 6c  65 5f 72 67 62 65 0a 47  |2-bit_rle_rgbe.G|
00000040  41 4d 4d 41 3d 31 0a 45  58 50 4f 53 55 52 45 3d  |AMMA=1.EXPOSURE=|
00000050  30 0a 0a 2d 59 20 32 35  36 20 2b 58 20 35 31 32  |0..-Y 256 +X 512|
00000060  0a 02 02 02 00 ff 88 e4  88 ff 89 dd 89 c1 88 b8  |................|
```
> Fixed RGBE images header parsing (fixes #4885)

- modules/core/src/ocl.cpp
add contition to skip unmap for internally allocated memory
> fix for bug 4380 (map_unmap_counting)

- doc/py_tutorials/py_feature2d/py_matcher/py_matcher.markdown
Fixing issue https://github.com/Itseez/opencv/issues/4237
> fix py_matcher tutorial

- modules/core/include/opencv2/core/cvstd.hpp
- modules/core/test/test_misc.cpp
Problem is mentioned here: #5104
> fix some functions for valid processing of empty string content

- doc/tutorials/introduction/android_binary_package/android_ocl_intro.markdown
- doc/tutorials/introduction/table_of_content_introduction.markdown
description for android tutorial4
> Android OpenCL tutorial

- modules/core/src/system.cpp
> TLS: fix access to array (out of bounds)

- modules/core/src/umatrix.cpp
- modules/core/test/ocl/test_matrix_operation.cpp
> Fix issue #5234

- modules/video/src/ecc.cpp
As suggested in https://github.com/Itseez/opencv/issues/4230
> change as suggested by original programmer and user of ecc software

- modules/videoio/src/cap_ios_video_camera.mm
CvVideoCamera defaultFPS was using depreciated methods, which stopped the fps being changed and produced warnings.
Fixes issue #4822
> fix CvVideoCamera defaultfps

- modules/core/src/umatrix.cpp
http://code.opencv.org/issues/4461
#5057
> T-API: fix allocation fallback code path (issue 4461)

- modules/cudaobjdetect/src/cuda/hog.cu
- modules/cudaobjdetect/src/hog.cpp
- modules/cudaobjdetect/test/test_objdetect.cpp
- samples/gpu/hog.cpp
Changed hog to work with variable parameters, changed the hog sample to test it with more options, added comments and tests.
> Variable GPU Histogram of oriented gradients

- modules/highgui/src/window_QT.cpp
http://code.opencv.org/issues/3800
> Bug #3800 - Resize viewport when CV_WINDOW_KEEPRATIO was set (Qt)

- modules/videoio/src/cap_libv4l.cpp
Precisely to functions cvSetCapture and cvGetCaptureProperty.
In compliance with the Windows (DirectDraw) version autofocus is disabled when either of the abovementioned functions is called.
> Adds support for property CV_CAP_PROP_FOCUS to libV4L.

- modules/highgui/include/opencv2/highgui.hpp
- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgproc/include/opencv2/imgproc.hpp
https://github.com/Itseez/opencv/pull/5121
> documentation patch

- platforms/android/android.toolchain.cmake
Add Android HardFP support. Expose the "armeabi-v7a-hard with NEON"
ANDROID_ABI.
TEST= Add -DANDROID_NATIVE_API_LEVEL=21
-DANDROID_ABI="armeabi-v7a-hard with NEON -DENABLE_PRECOMPILED_HEADERS=OFF"
to compile with hardfp. Checked the output of make verbose to
confirm -lm_hard is being linked. Softfp also works. 
Update: tested functionality after compiling with hardfp and opencv works well.
> Add Android ARMEABI_V7A_HARD for Hardfp support

- modules/ml/include/opencv2/ml.hpp
Update docs according to merged PR #5127
> TrainData doc update

- modules/core/perf/perf_umat.cpp
Merge after #5292
```
check_regression=*UMatTest*CustomPtr*
```
> UMat: custom ptr perf test

- 3rdparty/tbb/CMakeLists.txt
proposed, stated as working patch by @psyill
additional info in issue #5041
confirmed as working again tested on a fresh linux mint installation 17.2
> fix for #5041

- cmake/OpenCVModule.cmake
- modules/core/src/datastructs.cpp
- modules/core/test/test_ds.cpp
- modules/features2d/test/test_descriptors_regression.cpp
- modules/features2d/test/test_nearestneighbors.cpp
- modules/flann/include/opencv2/flann/autotuned_index.h
- modules/flann/include/opencv2/flann/kmeans_index.h
- modules/imgproc/src/drawing.cpp
- modules/imgproc/src/rotcalipers.cpp
- modules/imgproc/test/test_cvtyuv.cpp
- modules/imgproc/test/test_floodfill.cpp
- modules/imgproc/test/test_imgwarp.cpp
- modules/imgproc/test/test_imgwarp_strict.cpp
- modules/ml/src/gbt.cpp
#4191 - e1be6d0
#5090 - a3b515c
#5094 - ec05082
#5193 - 11981c3
#5203 - 0303e80 to 7e26cf5 (47cee8715bb086f6b0ca0f5b301d2eec87ce9f2a not included since file got refactored in 3.0)
#5223 - e7ac52d
#5226 - d81a0df
#5274 - f7d36bbad5b9ea45636a8dee7854ef0539c98370 + cf0f47f589a8524c37eaabc0977abf79bb1d3be9
#5281 - 1d77d69
#5285 - ee2008a
#5299 - df21a24
#5297 - 3143f2f
#5290 - 5eb67cc
ready to be reviewed
> Ports to master

- modules/videoio/src/cap_ffmpeg_impl.hpp
Based on PR #5322
Migration have been done for these ffmpeg/libav changes:
2013-12-11 - 29c83d2 / b9fb59d,409a143 / 9431356,44967ab / d7b3ee9 - lavc 55.45.101 / 55.28.1 - avcodec.h
av_frame_alloc(), av_frame_unref() and av_frame_free() now can and should be
used instead of avcodec_alloc_frame(), avcodec_get_frame_defaults() and
avcodec_free_frame() respectively. The latter three functions are deprecated.
2012-10-08 - ae77266 / 78071a1 - lavu 51.74.100 / 51.42.0 - pixfmt.h
Rename PixelFormat to AVPixelFormat and all PIX_FMT_* to AV_PIX_FMT_*.
To provide backwards compatibility, PixelFormat is now #defined as
AVPixelFormat.
Note that this can break user code that includes pixfmt.h and uses the
'PixelFormat' identifier. Such code should either #undef PixelFormat
or stop using the PixelFormat …
> update ffmpeg support

- CONTRIBUTING.md
@vpisarev the file with the link for the master branch - will update the guidelines themselves a bit later, now that I have wiki access rights
> add link to contributing guidelines

- modules/imgproc/include/opencv2/imgproc.hpp
Documentation Improvements from this ticket: https://github.com/Itseez/opencv/issues/5326
> Improved documentation for connectedComponentsWithStats.

- modules/hal/include/opencv2/hal.hpp
- modules/hal/include/opencv2/hal/defs.h
- modules/hal/include/opencv2/hal/intrin.hpp
- modules/hal/include/opencv2/hal/intrin_cpp.hpp
- modules/hal/include/opencv2/hal/intrin_neon.hpp
- modules/hal/include/opencv2/hal/intrin_sse.hpp
- modules/hal/test/test_intrin.cpp
- modules/hal/test/test_intrin_utils.hpp
- modules/hal/test/test_main.cpp
- modules/hal/test/test_precomp.hpp
- added tests for all implemented functionality
- added brief documentation (in _intrin_cpp.hpp_)
- fixed some issues
> hal universal intrinsics tests

- modules/highgui/src/grfmt_tiff.cpp
As requested, this is
https://github.com/Itseez/opencv/pull/5352
against 2.4 branch.
> fix crash when reading bw TIF

- modules/calib3d/src/calibinit.cpp
Refer to issue #5145 for detail.
> Bugfix (to 2.4) - findChessboardCorners causes crash (Issue# 5145)

- samples/cpp/tutorial_code/calib3d/camera_calibration/in_VID5.xml
in documentation exact path is images/CameraCalibration/VID5
see also PR #5393
> XML file path correction

- modules/features2d/src/agast.cpp
This PR address https://github.com/Itseez/opencv/issues/5278.
* It replaces stupid  erase() against vector list.
* Some benchmark posted by @JefferyRPrice now looks like bellow.
* We got 2435ms instead of reported 27658ms for same number of points (~3715), also statement "AGAST Corner Detector: faster than FAST and even FAST-ER" is true if we have no SSE2 optimization FAST and no scoring enabled for AGAST (test case 4).
* I believe for now this would be fine, some SSE optimizations could be done for AGAST too. I believe AGAST scoring routines has much better quality than FAST.
@JefferyRPrice, Thanks for poing out !
-------------<<<<----------------
(1) $ ./gist 
AGAST, 3715, 2435 (+NONMAX)
FAST, 3735, 695 (+NONMAX)(+SSE2)
(2) $ ./gist 
AGAST, 3715, 2438 (+NONMAX)
FAST, 3735, 1663 …
> Speedup AGAST nonmax-suppression.

- modules/calib3d/src/stereosgbm.cpp
- modules/core/src/dxt.cpp
- modules/core/src/matrix.cpp
- modules/core/src/stat.cpp
- modules/imgproc/src/canny.cpp
- modules/imgproc/src/corner.cpp
- modules/imgproc/src/deriv.cpp
- modules/imgproc/src/histogram.cpp
- modules/imgproc/src/pyramids.cpp
- modules/imgproc/src/smooth.cpp
Minor changes to IPP implementations;
> Some IPP functions were encapsulated;

- 3rdparty/ippicv/downloader.cmake
3rdparty repo scripts: https://github.com/Itseez/opencv_3rdparty/pull/3
> Move IPPICV binaries to GitHub opencv_3rdparty repository

- modules/imgcodecs/include/opencv2/imgcodecs.hpp
- modules/imgcodecs/src/loadsave.cpp
@vpisarev i remind you your comment  "I would add another variant of imread (e.g. imread_reduced()). Adding a flag to imread might work too. But not in the form it's done now......" (https://github.com/Itseez/opencv/pull/4162).
what is your opinion about this solution.
> adding new flags to imread to load image reduced

- modules/videoio/src/cap_gstreamer.cpp
it is new'ed but never deleted. However it does not need to be global or
heap allocated in the first place.
> do not leak GstMapInfo

- modules/java/generator/src/java/android+CameraBridgeViewBase.java
Corrected typo and unused imports
> Typo in CameraBridgeViewBase.java

- modules/videoio/src/cap_ffmpeg_impl.hpp
> Fix ffmpeg frame creation

- modules/imgproc/src/drawing.cpp
> fix zero length std::string in putText()

- cmake/OpenCVDetectCXXCompiler.cmake
https://github.com/Itseez/opencv/pull/3794#issuecomment-145918948
> Workaround for 32-bit OS on 64-bit x86 CPU

- modules/videoio/src/cap_ffmpeg_impl.hpp
Currently, OpenCV's FFMPEG capture segfaults at frame size changes, e.g. when the video frame size changes from 640x360 to 1280x720. This patch fixes the problem.
> videoio: fixed segmentation fault at frame size change

- samples/gpu/super_resolution.cpp
As is it was not possible to use CUDA.
> CommandLineParser missing gpu option

- modules/ml/src/em.cpp
> Assert fix: allow one cluster as valid parameter

- cmake/OpenCVModule.cmake
- cmake/OpenCVUtils.cmake
> 2.4: export simple libs from OPENCV_LINKER_LIBS

- samples/python2/camshift.py
This patch fixes issue to fail draw sqaure in ubuntu 14.04. #5520
I have tested with the versions of python 2.7.6 and opencv 2.4.8
> Fix the issue in mouse click event

- doc/py_tutorials/py_feature2d/py_brief/py_brief.markdown
- doc/py_tutorials/py_feature2d/py_fast/py_fast.markdown
- doc/py_tutorials/py_feature2d/py_feature_homography/py_feature_homography.markdown
- doc/py_tutorials/py_feature2d/py_orb/py_orb.markdown
- doc/py_tutorials/py_feature2d/py_sift_intro/py_sift_intro.markdown
- doc/py_tutorials/py_feature2d/py_surf_intro/py_surf_intro.markdown
cv2.SIFT -> cv2.xfeatures2d.SIFT_create() and friends
also mention contrib repo
related issue:  #5540
> update python features2d tutorials

- samples/cpp/facedetect.cpp
- samples/cpp/smiledetect.cpp
- samples/tapi/ufacedetect.cpp
https://github.com/Itseez/opencv/issues/5354
> Update face detection samples

- modules/imgproc/src/grabcut.cpp
> mush -> must

- modules/ml/src/svm.cpp
- modules/ml/test/test_svmtrainauto.cpp
> initialize temp_train_samples in SVM::autoTrain

- modules/ts/misc/run.py
- modules/ts/misc/run_android.py
- modules/ts/misc/run_suite.py
- modules/ts/misc/run_utils.py
- platforms/scripts/valgrind.supp
run.py script has been refactored:
- extracted some parts into files
- added valgrind support
> run.py: split into parts and added some new features

- modules/imgcodecs/src/grfmt_tiff.cpp
Port of #5357 to master branch
FIxes issue #5579
> Fixed crash when reading b/w tif images (fixes #5579)

- modules/imgproc/src/smooth.cpp
> Condition update for 8u IPP in GaussianBlur

- modules/ts/misc/run.py
- modules/ts/misc/run_android.py
- modules/ts/misc/run_suite.py
- modules/ts/misc/run_utils.py
- platforms/scripts/valgrind.supp
> ts: refactor run.py script

- modules/imgcodecs/src/jpeg_exif.cpp
See issue https://github.com/Itseez/opencv/issues/5632 .
> check boundary in ExifReader

- modules/imgproc/doc/filtering.rst
- modules/imgproc/include/opencv2/imgproc/imgproc.hpp
- modules/imgproc/src/morph.cpp
PR for 2.4 version of #5515
I've had some problems installing Sphinx so I haven't checked docs. I hope they're fine since changes are minor, but if there is any problem just tell me and I'll re-try building docs
> Hit and Miss morphological op

- cmake/cl2cpp.cmake
- modules/calib3d/src/stereobm.cpp
- modules/core/src/mathfuncs.cpp
- modules/core/src/precomp.hpp
- modules/core/src/system.cpp
- modules/core/test/test_umat.cpp
- modules/features2d/src/fast.cpp
- modules/features2d/src/matchers.cpp
- modules/features2d/src/orb.cpp
- modules/objdetect/src/cascadedetect.cpp
- modules/objdetect/src/cascadedetect.hpp
- modules/stitching/src/warpers.cpp
- modules/video/src/bgfg_gaussmix2.cpp
- modules/video/src/lkpyramid.cpp
- modules/video/src/optflowgf.cpp
- modules/video/src/tvl1flow.cpp
Contrib: https://github.com/Itseez/opencv_contrib/pull/372
Same as #4102 , #4141 but without changes in ocl.cpp
> OCL: fix "off" mode

- modules/gpu/include/opencv2/gpu/stream_accessor.hpp
- modules/gpu/src/cudastream.cpp
- modules/gpu/test/test_stream.cpp
It allows to import existed CUDA stream to OpenCV.
> Add cv::gpu::StreamAccessor::wrapStream method

- modules/videoio/src/cap_mjpeg_decoder.cpp
> Fixed mjpeg frame size attribution

- modules/imgcodecs/src/jpeg_exif.cpp
Another boundary check, which I missed in last PR.
> check offset in ExifReader::getString

- modules/core/include/opencv2/core.hpp
Example with some sample usage for the normalize() method I wrote for myself (for clarification). If you like, you can add it.
> Added example to the documentation for the normalize() method

- samples/java/sbt/project/plugins.sbt
- samples/java/sbt/src/main/java/DetectFaceDemo.java
- samples/java/sbt/src/main/scala/ScalaCorrespondenceMatchingDemo.scala
- samples/java/sbt/src/main/scala/ScalaDetectFaceDemo.scala
1. Update sbteclipse-plugin version (sbt can't resolve plugin with version 2.1.0)
2. Add missed imports
> Fix build of Java-Sbt sample

- modules/core/include/opencv2/core/core.hpp
- modules/core/src/drawing.cpp
Matlab look-alike markers for OpenCV
> adding markers to OpenCV for 2.4 branch

- modules/core/src/convert.cpp
fix bug #5624, tested with the example on #5034
> fix bug #5624

- samples/cpp/tutorial_code/gpu/gpu-thrust-interop/Thrust_interop.hpp
Tutorial and helper files for making a thrust style iterator from a GpuMat.
> Thrust tutorial

- doc/opencv.bib
- modules/features2d/include/opencv2/features2d.hpp
corresponding [wiki article](https://github.com/Itseez/opencv/wiki/Mser) can be removed
> Added some documentation for MSER

- modules/imgcodecs/src/grfmt_bmp.cpp
#5707 Fixed - cannot attach file while github not support 32bit images, if required can post image on which i have got bug and fix it.
> 32bit BITFIELDS compresion codec support #5707 Fixed

- modules/imgproc/src/filter.cpp
- modules/imgproc/src/hough.cpp
- modules/imgproc/test/test_houghLines.cpp
Define typos and data comparison warnings;
> Fixed warnings for IPP9+ build;

- modules/core/src/mathfuncs.cpp
- modules/core/test/test_math.cpp
Solving equations x^4 - x^2 = 0, and x^2 - 2x + 1 = 0 returns "nan" roots.
> Fix solvePoly() 3.0.0

- modules/imgproc/src/featureselect.cpp
- modules/imgproc/test/test_goodfeaturetotrack.cpp
- modules/ts/include/opencv2/ts.hpp
- modules/ts/src/ts_func.cpp
Added missed accuracy test for goodFeaturesToTrack functions from opencv_imgproc module
> added test goodfeaturetotrack.cpp

- modules/imgproc/src/smooth.cpp
Same as PR #5521 without clutter
> Fixed histogram substraction bug with NEON instructions

- modules/core/CMakeLists.txt
- modules/videoio/CMakeLists.txt
C++ Native mode support coming back and C++/CX support fixed in core and made more flexible in videoio.  Next tasks to fully support Windows 10 Universal Apps and Visual Studio 2015 and resurrect some native C++ code that ended up deprecated due to conflicts.
> Build fixes for WinRT

- modules/features2d/test/test_descriptors_regression.cpp
- modules/imgcodecs/src/grfmt_exr.cpp
- modules/imgcodecs/src/grfmt_jpeg.cpp
- modules/imgcodecs/src/jpeg_exif.cpp
- modules/imgcodecs/src/jpeg_exif.hpp
- modules/imgproc/src/drawing.cpp
- modules/imgproc/test/test_goodfeaturetotrack.cpp
- modules/photo/src/tonemap.cpp
- modules/stitching/src/stitcher.cpp
- modules/video/src/tvl1flow.cpp
Several minor issues has been fixed
> Problems detected by coverity and valgrind

- modules/calib3d/src/fisheye.cpp
- modules/calib3d/src/fisheye.hpp
- modules/calib3d/test/test_fisheye.cpp
improves performance by factor 1.2 to 2.0
> clean up fisheye calibration code

- modules/objdetect/src/cascadedetect.cpp
Please see #5347 for more information.
> appropriate logic in cascade classifier when rejectLevels is true (#5347)

- modules/core/include/opencv2/core/mat.hpp
- modules/core/src/matrix.cpp
- modules/core/src/ocl.cpp
- modules/core/src/umatrix.cpp
Interface for setting default Mat allocator similar to cuda::GpuMat.
> Cpu mat memory allocator

- modules/stitching/src/seam_finders.cpp
> UMat access flags (fixes #5095)

- cmake/cl2cpp.cmake
- modules/hal/src/precomp.hpp
> include "cvconfig.h"

- samples/python2/digits.py
fixed digits.py to produce correct results with SVM
> fixed digits.py sample

- modules/java/CMakeLists.txt
- modules/python/common.cmake
> fixes #5019: python and java bindings become CMake modules

- modules/core/include/opencv2/core.hpp
> corrected cv::merge documentation

- modules/imgproc/src/deriv.cpp
> Fixes #5066: laplacian: "y" may contain negative values

- modules/imgproc/misc/java/src/java/imgproc+Moments.java
- modules/imgproc/misc/java/test/MomentsTest.java
- modules/java/generator/gen_java.py
> Simple Moments class for Java

- samples/android/15-puzzle/src/org/opencv/samples/puzzle15/Puzzle15Activity.java
- samples/android/face-detection/src/org/opencv/samples/facedetect/FdActivity.java
- samples/android/image-manipulations/src/org/opencv/samples/imagemanipulations/ImageManipulationsActivity.java
- samples/android/tutorial-2-mixedprocessing/src/org/opencv/samples/tutorial2/Tutorial2Activity.java
Fix other Android samples.
Related: #5812
> android samples: force setVisibility

- modules/core/src/ocl.cpp
> OCL: fix buffer pool small allocations issue

- modules/videoio/CMakeLists.txt
- samples/python/_run_winpack_demo_python27.cmd
- ffmpeg: install both 32/64-bit versions (required for java/python bindings)
- python: add launch script for winpack python demo
> Fix winpack

- doc/py_tutorials/py_gui/py_video_display/py_video_display.markdown
> Broken Link in python tutorial corrected

- modules/ml/src/em.cpp
> fix reshape call not being an inplace method

- modules/core/include/opencv2/core/types_c.h
- modules/features2d/doc/feature_detection_and_description.rst
- modules/ts/misc/run.py
- modules/ts/misc/run_suite.py
- modules/ts/misc/run_utils.py
- #3771 - inline round on ARM
- #5633 - documentation for MSER
- #5666 - run.py fixes
> Backport from master branch: round, MSER, run.py

- modules/imgproc/doc/colors.markdown
> fix probably copy paste like error in rgb2luv doc

- modules/ml/src/em.cpp
> fix uninitialized matrix in EM::predict fixes #5443

- cmake/OpenCVPCHSupport.cmake
> [master] Fixed PCH warning during ARM crosscompilation

- modules/calib3d/src/calibration.cpp
- modules/core/include/opencv2/core/affine.hpp
- easier to read
- less conversions
> calib3d: port Rodrigues to cpp primitives

- modules/videoio/src/cap_mjpeg_decoder.cpp
> MSVS2008 build fix

- modules/core/src/convert.cpp
- modules/core/test/ocl/test_arithm.cpp
- modules/core/test/test_arithm.cpp
> Fixed normalize (inplace case)

- samples/gpu/CMakeLists.txt
> gpu samples: fix REMOVE_ITEM error

- modules/imgproc/src/drawing.cpp
> fix cv::MARKER_TRIANGLE_UP

- modules/ml/src/nbayes.cpp
- modules/ml/test/test_mltests.cpp
> ml: fix NormalBayesClassifier bulk prediction

- modules/imgproc/src/convhull.cpp
> May be it can solve issue 5908

- modules/imgproc/test/test_convhull.cpp
- modules/ts/include/opencv2/ts.hpp
- modules/ts/include/opencv2/ts/cuda_test.hpp
- modules/ts/include/opencv2/ts/ocl_test.hpp
Issue: #5908
Fix is here: #5914
> Regression test for convexityDefects (#5908)

- modules/videoio/src/cap_ffmpeg_impl.hpp
> ffmpeg: fix buffer allocation for unaligned frame sizes

- platforms/android/android.toolchain.cmake
The Android NDK would be moving to Clang as its default compiler
in the future. [1] This patch allows OpenCV to build with the default
c++_shared / c++_static.
TEST=Builds OpenCV with -DANDROID_TOOLCHAIN_NAME=
aarch64-linux-android-clang3.6 -DANDROID_STL=c++_shared
There are still some linker issues with files in the 3rdparty directory but this should make it easy for anyone to atleast build with c++_shared.
[1] https://android.googlesource.com/platform/ndk.git/+/master/CHANGELOG.md
> Add LLVM c++_static c++_shared STL targets for Android 

- modules/calib3d/include/opencv2/calib3d.hpp
corresponding code:
Vec2d xd1 = x * cdist;
Vec2d xd3(xd1[0] + alpha*xd1[1], xd1[1]);
Vec2d final_point(xd3[0] * f[0] + c[0], xd3[1] * f[1] + c[1]);
> fisheye documentation typo

- modules/core/src/system.cpp
> Fix TLS implementation

- modules/ml/include/opencv2/ml.hpp
- modules/ml/src/ann_mlp.cpp
- modules/ml/src/svm.cpp
Someone forgot to wrap the load function for SVMs in the
corresponding ml python module. Hopefully fixed that.
fixes #5891
> fixing issue #5891 of Itseez/opencv.

- modules/imgproc/src/morph.cpp
Update call scheme used to invoke Tegra optimized morphology filtering. New call use improved Tegra filtering implementation.
> Update call to Tegra optimized morphology filtering

- doc/tutorials/features2d/feature_homography/feature_homography.markdown
> feature_homography correction

- modules/stitching/include/opencv2/stitching/detail/warpers.hpp
Added a comment on the scale parameter of the spherical warper class.
> Added a comment

- include/opencv2/opencv.hpp
> Fix include opencv (2.4)

- include/opencv2/opencv.hpp
> include available modules only

- modules/cudafilters/include/opencv2/cudafilters.hpp
- modules/cudafilters/perf/perf_filters.cpp
- modules/cudafilters/src/cuda/median_filter.cu
- modules/cudafilters/src/filtering.cpp
- modules/cudafilters/test/test_filters.cpp
- modules/cudaimgproc/include/opencv2/cudaimgproc.hpp
@jet47 , all previous commits have been squashed per your request.
#5888
> CUDA median filtering using histograms

- modules/core/src/opencl/runtime/opencl_core.cpp
> OCL: thread-safe OpenCL loading

- apps/traincascade/imagestorage.cpp
removed the dirname variable as needed...solves #5896 ....If any further changes needed...let me know....
> removed dirname variable

- modules/core/include/opencv2/core/mat.hpp
As discussed here: https://github.com/Itseez/opencv/pull/6068#issuecomment-180797723
> Added suggestions from PR6068

- README.md
This project is dead from the 1st September last year
> Removed gittip link in 2.4 branch

- README.md
This project is dead from 1st September last year
> Removed gittip link in master

- modules/imgcodecs/src/jpeg_exif.cpp
> ExifReader::getFormat : check buffer length

- modules/videoio/src/cap_qtkit.mm
> QTKit capture: fix invalid timer call

- cmake/OpenCVFindLibsVideo.cmake
> cmake: fix find_library() for bzip2

- modules/core/test/test_umat.cpp
> test: initialize test data in test_umat.cpp (6102)

- modules/ml/include/opencv2/ml.hpp
- modules/ml/src/data.cpp
> Add TestData::getTestSamples()

- modules/videoio/include/opencv2/videoio.hpp
- modules/videoio/include/opencv2/videoio/videoio_c.h
- modules/videoio/src/cap_ximea.cpp
- added CAP_PROP_XI_SENSOR_BOARD_TEMP parameter
- added acquisition resetting for paramters that require it
> ximea new param

- modules/calib3d/include/opencv2/calib3d.hpp
Fixing https://github.com/Itseez/opencv/issues/6128.
> Fisheye Camera model documentation

- modules/imgcodecs/src/jpeg_exif.cpp
> EXIF reader: fixed file descriptor leak in case of broken tags

- doc/tutorials/introduction/windows_visual_studio_Opencv/windows_visual_studio_Opencv.markdown
Fix for the issue [#6146](https://github.com/Itseez/opencv/issues/6146).
Updated the documentation [How to build applications with OpenCV inside the Microsoft Visual Studio](http://docs.opencv.org/2.4/doc/tutorials/introduction/windows_visual_studio_Opencv/windows_visual_studio_Opencv.html#windows-visual-studio-how-to).
> Fix for issue 6146

- doc/py_tutorials/py_ml/py_knn/py_knn_opencv/py_knn_opencv.markdown
- doc/py_tutorials/py_ml/py_knn/py_knn_understanding/py_knn_understanding.markdown
- doc/py_tutorials/py_ml/py_svm/py_svm_opencv/py_svm_opencv.markdown
> fix python ml tutorials

- modules/core/include/opencv2/core/utility.hpp
- modules/highgui/src/window_cocoa.mm
- modules/stitching/include/opencv2/stitching/detail/blenders.hpp
- modules/stitching/include/opencv2/stitching/detail/exposure_compensate.hpp
fixes #4519
Used proposed patch from the original issue (http://code.opencv.org/issues/2846) and extended to the whole file.
**Note**: not sure whether this way is the best
> Cocoa backend: added sliders checks

- modules/videoio/src/cap_gstreamer.cpp
The issue description is very starightforward about what to do, so fixed it.
Closes #6192
> Fix for #6192 (Mismatching delete)

- modules/core/include/opencv2/core/matx.hpp
Fixes https://github.com/Itseez/opencv/issues/4802.
> VS 2010 Za option compilation bug fix

- PULL_REQUEST_TEMPLATE.md
In addition to the Issue template #6144 which is far more important i would like to add this so issues will get closed after merging related PRs rather than being reliant on the reviewer.
Many people do not know that the keywords _close, resolve_ and _fix_ in their commits or initial PRs will result in such an action.
If someone want to add something here feel free.
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
> Create a Pull Request template

- ISSUE_TEMPLATE.md
Since we've got a new feature here on github i would like to use it to get all relevant information into the reported issues.
https://help.github.com/articles/creating-an-issue-template-for-your-repository/
I started a file but i would like to hear some other opinions about what to add.
I will add the file here as well so you can see the actual result:
=======================
This is a template helping you to create an issue which can be processes as quickly as possible. Feel free to add additional information or remove not relevant points if you do not need them.
If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.
- OpenCV version: 2.4 / 3.x
- Host OS: Linux (Ubuntu 14.04)  / Mac OS X 10.11.3 / Windows 10
- *(if …
> Add an Issue template for new issues

- modules/highgui/src/cap_ffmpeg_impl.hpp
> FFMPEG backport fixes from master

- modules/core/src/matrix.cpp
> Fix backport to 2.4

- modules/imgproc/include/opencv2/imgproc/hal/hal.hpp
- modules/imgproc/src/deriv.cpp
- modules/imgproc/src/filter.cpp
- modules/imgproc/src/filterengine.hpp
- modules/imgproc/src/hal_replacement.hpp
- modules/imgproc/src/morph.cpp
- modules/imgproc/src/precomp.hpp
- modules/imgproc/src/smooth.cpp
> Filter2D HAL interface

- modules/video/src/bgfg_gaussmix2.cpp
- modules/video/src/opencl/bgfg_mog2.cl
- modules/video/test/ocl/test_bgfg_mog2.cpp
this is my dirty fix for issue #6044, I am open to suggestions about how to make it look nicer
> fix: bg substraction for float images with OpenCL

- modules/ml/src/svmsgd.cpp
resolves #6248
add a cast to double, to make vs compilers happy
> svmsgd.cpp, fix #6248

- samples/cpp/train_svmsgd.cpp
response must be float, else we trigger an assertion in line 150
> train_svmsgd.cpp : float response

- modules/core/include/opencv2/core/cuda/utility.hpp
- modules/core/src/cuda/gpu_mat.cu
resolves #6251 
Fix for GCC pickiness.
> Linux bug fix for ThrustAllocator.

- samples/cpp/detect_mser.cpp
resolves #6264 
It fix bug on build opencv example AKAZE_tracking in vs 2010
> fix build sample in vc2010

- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/src/colormap.cpp
https://github.com/Itseez/opencv/issues/6149
> fix: 6149 (Incomplete description of applyColorMap parameters)

- doc/tutorials/features2d/akaze_tracking/akaze_tracking.markdown
- samples/cpp/tutorial_code/features2D/AKAZE_tracking/planar_tracking.cpp
- samples/cpp/tutorial_code/features2D/AKAZE_tracking/utils.h
> remove opencv_contrib dependancy from planar_tracking.cpp

- modules/python/test/test_facedetect.py
Fix for python facedetection test on ARM.
> Fixed face detection python test

- modules/videoio/src/cap_libv4l.cpp
- modules/videoio/src/cap_v4l.cpp
resolves #5746 
Change mainloop_v4l2 to be able to return an error code, return an error code when connection lost.
> return 0 from VideoCapture::read() when cannot connect to camera

- modules/videoio/src/cap_ffmpeg_impl.hpp
> Add support for ffmpeg 3.0.

- samples/python/camshift.py
- samples/python/feature_homography.py
- samples/python/lk_homography.py
- samples/python/plane_ar.py
- samples/python/plane_tracker.py
- samples/python/tst_scene_render.py
- samples/python/video.py
Replace some synthetic scenes in python samples to more informative
> Replace of some synthetic scenes in python samples

- modules/highgui/include/opencv2/highgui.hpp
> highgui: add CV_GUI_* flags to enum in cpp so they appear in bindings

- modules/ml/src/lr.cpp
This PR adds multi-threaded computation of gradients in LogisticRegression::compute_gradient method.
Nothing else changed.
> Added parallel implementation of LogisticRegression::compute_gradient.

- modules/videoio/src/cap_ffmpeg_impl.hpp
resolves #6356
Use timeout interrupt only for active waits (during `open` or `read` calls).
> ffmpeg: interrupt callback fix

- modules/core/src/persistence.cpp
- modules/core/test/test_io.cpp
> operator<< handles keys starting with underscore

- modules/core/src/persistence.cpp
- modules/core/test/test_io.cpp
> Backport 6381

- samples/python/plane_ar.py
A comment that explains the shape being rendered
> Added description of the AR model

- modules/videoio/src/cap_gstreamer.cpp
resolves the problem introduced by https://github.com/Itseez/opencv/pull/6298 on Ubuntu14.04
@alalek this is the proposed fix!
> fixing gstreamer cap

- 3rdparty/libjpeg/CMakeLists.txt
- 3rdparty/zlib/CMakeLists.txt
- silence warnings in zlib and libjpeg
> Updates for XCode 7.3

- modules/videoio/src/cap.cpp
> videoio: give chance for all enabled backends

- modules/imgproc/src/imgwarp.cpp
related #6377
Rewrite linearPolar & logPolar so that they do not depend on the
deprecated API CvMat. Issue 6377 is resolved in this way because the two
routines do not convert UMat to CvMat anymore.
> Bug Fix for Issue 6377

- modules/imgcodecs/src/grfmt_jpeg2000.cpp
resolves https://github.com/Itseez/opencv/issues/4645
> fix for writing 16-bit jpeg2000

- cmake/OpenCVUtils.cmake
> cmake: don't use -isystem for opencv_contrib paths

- modules/highgui/src/grfmt_jpeg2000.cpp
> Backport 6417: fix for writing 16-bit jpeg2000

- modules/videoio/src/cap_v4l.cpp
> cap_v4l: allow manually controlling exposure

- modules/core/include/opencv2/core/mat.hpp
image.forEachWithPosition does not exist
> Fixing doc for cv::Mat::forEach

- modules/core/include/opencv2/core/version.hpp
> OpenCV version++

- doc/CMakeLists.txt
- modules/core/include/opencv2/core/cvdef.h
- modules/core/include/opencv2/core/hal/hal.hpp
- modules/core/include/opencv2/core/hal/interface.h
- modules/core/src/arithm.cpp
- modules/core/src/arithm_core.hpp
- modules/core/src/dxt.cpp
- modules/core/src/hal_replacement.hpp
- modules/core/test/test_dxt.cpp
- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/include/opencv2/imgproc/hal/hal.hpp
- modules/imgproc/include/opencv2/imgproc/hal/interface.h
- modules/imgproc/src/hal_replacement.hpp
- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/src/morph.cpp
- modules/imgproc/src/templmatch.cpp
- interfaces for dft1D, dft2D, dct2D
- internal replacement interface
- new test: run forward, then inverse and compare with original data
> cv::hal DFT/DCT interface

- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/src/opencl/linearPolar.cl
- modules/imgproc/src/opencl/logPolar.cl
Add OpenCL  support for linearPolar & logPolar to improve performance.
> Add OpenCL  support to linearPolar & logPolar

- modules/imgproc/src/clahe.cpp
Resolves #5953 bug
There is no CLAHE crash for images with pixels value > 12 bit.
CLAHE outputs for 16 bit image and 16 bit image being transformed to 8 bit the same.
> Fixing CLAHE crash with pixels value > 12 bit

- modules/calib3d/src/fisheye.cpp
> simplify using fisheye calibration from python

- modules/videostab/include/opencv2/videostab.hpp
Corrects minor comment misspellings in videostab.hpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/itseez/opencv/6483)
> Fixes minor typos

- modules/core/test/test_intrin.cpp
resolves #6521
hal_intrin test fails on 64bit ARM
> fix for hal_intrin test on 64bit ARM

- cmake/OpenCVPCHSupport.cmake
> Backport 6541

- modules/cudafeatures2d/src/orb.cpp
resolves #6473
Enable "useProvidedKeypoints" flag on cuda::ORB's detectAndCompute function in order to able to describe provided keypoints.
* Seperate keypoints according to their octave
* Rearrange their merged locations based on scale factor.
* Upload keypoints into GPU
* Describe them
* additional author : Ender Tunç <endertunc@yahoo.com>
> Enable "useProvidedKeypoints" flag on cuda::ORB's detectAndCompute

- modules/ml/src/ann_mlp.cpp
Resolves #6562
Fix CV_64F values generate invalid results or nan.
> Fixed #6562: Incorrect CV_64F management in ANN

- doc/py_tutorials/py_calib3d/py_calibration/py_calibration.markdown
The code had a some typos.
I also added some whitespace between parameters to make it slightly more readable.
> fixed "corners2" to "corners" & nicer whitespace

- modules/core/include/opencv2/core.hpp
Minor additions to the documentation about mixChannels, insertChannel and extractChannel.
> Minor additions to the documentation.

- modules/core/include/opencv2/core/cvstd.hpp
> core: prevent changes in 'std' namespace

- cmake/OpenCVDetectAndroidSDK.cmake
> Backport #6690

- CMakeLists.txt
- cmake/OpenCVFindLibsPerf.cmake
- cmake/templates/cvconfig.h.in
- modules/core/include/opencv2/core/hal/hal.hpp
- modules/core/include/opencv2/core/hal/interface.h
- modules/core/include/opencv2/core/matx.hpp
- modules/core/src/hal_internal.cpp
- modules/core/src/hal_internal.hpp
- modules/core/src/hal_replacement.hpp
- modules/core/src/lapack.cpp
- modules/core/src/matmul.cpp
- modules/core/src/matrix_decomp.cpp
- modules/imgproc/src/hal_replacement.hpp
-  Add HAL interface for SVD and GEMM
- Implement internal HAL for gemm and matrix decomposition subroutines which uses Lapack
> Lapack hal

- CMakeLists.txt
https://cmake.org/cmake/help/v3.0/policy/CMP0042.html
> cmake: change CMP0042 policy value

- modules/core/src/hal_replacement.hpp
- modules/core/src/stat.cpp
- modules/imgproc/include/opencv2/imgproc/hal/hal.hpp
- modules/imgproc/src/color.cpp
- modules/imgproc/src/hal_replacement.hpp
> PR #6477 (Added HAL cvtColor interface)

- modules/python/src2/cv2.cpp
Adds python binding for int cv::createButton, 
argument defaults in python match C++ definition
> Python Binding: added createButton in highgui

- modules/videoio/src/cap_images.cpp
> VideoCapture compatibility for images with alpha channel

- modules/imgproc/src/smooth.cpp
- add NEON support check on ARM before executing
- clean up the code to have same style
> check NEON support before executing on ARM

- modules/core/include/opencv2/core/types.hpp
- samples/cpp/CMakeLists.txt
- samples/cpp/tutorial_code/viz/creating_widgets.cpp
- samples/cpp/tutorial_code/viz/launching_viz.cpp
> samples: repair viz tutorial

- modules/core/include/opencv2/core/operations.hpp
Fixed compilation with LLVM libc++ STL on Android
> Enabled build with LLVM libc++ for Android

- modules/imgproc/src/histogram.cpp
Intels IPP uses the term "number of levels" for its histogram methods, which ist "number of histogram bins" (256 for CV_8UC1) + 1 -> 257
In the original code this leads to writing one element beyond the end of the field in the loop around line 1245. histSize if 257, but the size of hist->data is only 256.
```
for (int i = 0; i < histSize; ++i)
CV_XADD((int *)(hist->data + i * hist->step), *(int *)(phist.data + i * phist.step));
}
```
The minimal fix would be to use (histSize - 1) here but I decided to change the misleading variable-names as well. 
With my fix histSize is 256 as one would expect and the new variable levelNum is 257 as intel wants it.
> fix for buffer-overflow in IPPCalcHistInvoker::operator()

- samples/cpp/neural_network.cpp
resolves #6780
Please add your changes here.
> Fix for #6780

- doc/py_tutorials/py_imgproc/py_contours/py_contour_features/py_contour_features.markdown
- doc/py_tutorials/py_imgproc/py_contours/py_contours_more_functions/py_contours_more_functions.markdown
resolves #6873
add missing returned img to contours tutorial
> py_tutorials: fix cv2.findContours return val

- modules/calib3d/include/opencv2/calib3d.hpp
- modules/calib3d/src/fisheye.cpp
> fisheye: add CALIB_FIX_PRINCIPAL_POINT

- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/test/test_imgwarp_strict.cpp
resolved https://github.com/opencv/opencv/issues/5191
> fixed empty image condition in resize

- modules/imgproc/src/thresh.cpp
- modules/imgproc/test/test_thresh.cpp
use SIMD and speed up #6546 
* speeds up the threshold function
* use NEON under aarch64 only
> speed up threshold of 64F version using NEON and SSE

- modules/core/src/persistence.cpp
- modules/core/test/test_io.cpp
**Resubmission of PR #6783**
resolves issue #6781
> persistence: fixing crash with space-only values

- apps/visualisation/opencv_visualisation.cpp
resolves #6875
add a check for -model and -image cmdline args, so users don't run into an exception
> opencv_visualization: check cmdline args

- modules/calib3d/src/stereosgbm.cpp
With a test image set of 2 x 1400x954 pixels on a Intel Core i7 5960X this improves runtime of MODE_HH with about 10%. (this particular replaced code segment is approx 3 times faster than the non-SSE2 variant). I was able to reduce runtime by 130 ms by this simple fix.
The second part of the SSE2 optimized part could probably be optimized further by using shift SSE2 operations, but I imagine this would improve performance 10-20 ms at best.
Restored #5933
> StereoSGBM.cpp - use SSE2 for pass 2 using MODE_HH

- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/src/emd.cpp
> provide better error messages

- platforms/scripts/valgrind.supp
resolved https://github.com/opencv/opencv/issues/5075
replaces https://github.com/opencv/opencv/pull/6843
Added suppression for TBB valgrind issue
> added suppression for TBB valgrind issue

- modules/java/generator/gen_java.py
- modules/ml/include/opencv2/ml.hpp
> Adding support for pointer generation. Fixes #6605

- modules/core/include/opencv2/core.hpp
- modules/core/test/test_mat.cpp
> Added note about cv::reduce output type for MIN/MAX

- modules/highgui/src/window_QT.cpp
> added condition for Qt5

- modules/core/src/matrix.cpp
- modules/core/test/test_mat.cpp
Consequence of https://github.com/opencv/opencv/issues/6670
> added some tests and error messages for Mat::push_back

- modules/core/include/opencv2/core/version.hpp
Resolves #6931
Update of the macro _CVAUX_STRW_EXP_
> Resolves issue #6931

- modules/imgproc/test/test_fitellipse.cpp
@mshabunin @snosov1 @apavlenko please review
Added tests for issues https://github.com/opencv/opencv/issues/6544 and https://github.com/opencv/opencv/issues/4515 and disabled them
> Added tests for issues ##4515, 6544

- modules/core/include/opencv2/core/ptr.inl.hpp
- modules/cudaoptflow/src/farneback.cpp
- modules/cudaoptflow/src/pyrlk.cpp
- modules/video/include/opencv2/video/tracking.hpp
- modules/video/src/lkpyramid.cpp
- modules/video/src/optflowgf.cpp
- modules/video/src/tvl1flow.cpp
- modules/video/test/test_tvl1optflow.cpp
- samples/cpp/tvl1_optical_flow.cpp
This PR create an interface similar to cudaoptflow for the cpp flow implementations.
> Add algorithmic interface to cpp flow computation

- modules/ml/src/svm.cpp
> incorrect error about k_fold parameter in svm.cpp corrected

- modules/imgproc/src/filter.cpp
I improve RowVec_8u32s().
I improve using too much register at "for( ; i <= width - 16; i += 16 )".
I remove wasted "_mm_mulhi_epi16()" at "for( ; i <= width - 4; i += 4 )".
I measured the clocks for RowVec_8u32s().
Please observe the following.
<tr><th>width</th><th>Average Clocks (original code)</th><th>Average Clocks (new code)</th><th>Faster Rate (compared with original code)</th></tr>
<tr><td>4</td><td>1254.6</td><td>1032.0</td><td>1.22</td></tr>
<tr><td>8</td><td>2493.4</td><td>1950.0</td><td>1.28</td></tr>
<tr><td>12</td><td>3693.2</td><td>2932.4</td><td>1.26</td></tr>
<tr><td>16</td><td>4547.6</td><td>3960.4</td><td>1.15</td></tr>
<tr><td>20</td><td>5694.2</td><td>4724.2</td><td>1.21</td></tr>
<tr><td>24</td><td>6919.0</td><td>5627.8</td><td>1.23</td></tr> …
> improve RowVec_8u32s().

- modules/objdetect/src/hog.cpp
- speed up HOG using NEON as well as SSE2
> speed up HOG using NEON as well as SSE2

- modules/core/include/opencv2/core/version.hpp
> Backport #6932

- modules/cudaoptflow/src/cuda/pyrlk.cu
> replaced static const members with static functions for msvc compatability

- modules/calib3d/include/opencv2/calib3d/calib3d.hpp
- modules/calib3d/src/calibinit.cpp
- modules/calib3d/src/checkchessboard.cpp
- modules/calib3d/test/test_chesscorners_timing.cpp
Ported from #4046 and #6851 by @HHI-VIT-IMC
>Modified and improved the method for chessboard detection. It is now faster and detects chessboards under difficult lighting condition as well as when the chessboard has strong out of plane rotations
Original PR has been transferred from 2.4 branch to master.
> Improved method for chessboard detection

- modules/core/test/test_mat.cpp
> fixed typo

- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/src/canny.cpp
- modules/imgproc/test/ocl/test_canny.cpp
- modules/imgproc/test/test_canny.cpp
- modules/ts/include/opencv2/ts/ocl_test.hpp
> Canny custom gradient

- modules/imgproc/src/smooth.cpp
* Accelarate bilateral filter using NEON as same as SSE3
* align some lines in SSE3 part
> accelerate bilateralFilter using NEON

- modules/imgproc/src/imgwarp.cpp
> imgproc: fix typo

- modules/stitching/include/opencv2/stitching/detail/util.hpp
- modules/stitching/src/precomp.hpp
- modules/stitching/src/util_log.hpp
- samples/cpp/stitching_detailed.cpp
> fix build: move LOG macro from stitching public headers

- modules/core/test/test_io.cpp
resolves #5029
Added test to write and read `Vec2i` to / from `FileStorage`
> Added test to prove that issue #5029 is invalid

- modules/calib3d/src/solvepnp.cpp
> calib3d: fix typo

- apps/visualisation/opencv_visualisation.cpp
adds the limits to the actual help info instead of letting it be in the file itself.
> add limits of tool to help message

- apps/annotation/opencv_annotation.cpp
Adds the more generic interface of CommandLineParser to parse the input arguments!
> change parameter input to the CommandLineParser interface

- doc/py_tutorials/py_feature2d/py_features_meaning/py_features_meaning.markdown
> Corrected tutorial grammar and sentences

- doc/tutorials/objdetect/traincascade.markdown
> doc: fix typo and grammar

- modules/core/include/opencv2/core/cuda.hpp
- modules/core/src/cuda/gpu_mat.cu
- modules/cudev/include/opencv2/cudev/functional/functional.hpp
- modules/cudev/include/opencv2/cudev/util/saturate_cast.hpp
- modules/cudev/test/test_cvt.cu
* GPU version of #6830, #6447
* add feature of Fp16 on GPU (cudev)
* add test, too
> cudev: add feature to convert FP32(float) from/to FP16(half) on GPU

- modules/calib3d/src/fisheye.cpp
- modules/calib3d/test/test_fisheye.cpp
Former #6396 by @mcbridejc:
resolves #6388
> Don't assume all images have the same number of calibration points

- apps/annotation/opencv_annotation.cpp
Adds the possibility to resize your input images to a maximum size that you prefer! 
Example usage: you have 2400 pixel images in height and only a 1200 pixel height resolution. You then pass for example `--maxWindowHeight=1000 --resizeFactor=2` to take half of the image dimensions, but your made annotations will still be stored as annotations on the original image. However your image will fit on your image screen!
> allow for screen size related resizing

- samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp
- samples/cpp/tutorial_code/calib3d/camera_calibration/in_VID5.xml
Add new parameters which controls distortion flags and some fixes in fisheye calibration mode
> Improvements in camera_calibration tutorial code

- modules/features2d/doc/common_interfaces_of_feature_detectors.rst
> fix small typo

- modules/imgproc/src/filter.cpp
- modules/imgproc/src/smooth.cpp
- modules/imgproc/test/ocl/test_filters.cpp
> Update PR #6967 (Prefer OCL calculation before IPP in GaussianBlur)

- modules/core/src/convert.cpp
* avoid using vld1_f16 and vst1_f16 which are not supported on gcc 4 series (Ubuntu 14.04)
Sorry for easy mistake, I forgot to confirm on Jetson TK1.  I realized that vst1_f16 and vld1_f16 are not supported on gcc 4 series.
This commit will fix this.
> core: fix build error on JetsonTK1

- modules/calib3d/test/test_cameracalibration.cpp
@vpisarev, @vicproon I've converted the reproducing sample from #6836 to a regression test
> add test for #6836

- samples/cpp/camshiftdemo.cpp
Transferred #6862 (previously #5929) and fixed whitespace issue
> Added comments to clarify sample code

- modules/imgproc/src/color.cpp
I eliminate wasted '_mm_deinterleave_epi8()' and '_mm_interleave_epi8()'.
<tr><th>_srccn</th><th>n</th><th>Average Clocks (original code)</th><th>Average Clocks (new code)</th><th>Faster Rate (compared with original code)</th></tr>
<tr><td>3</td><td>32</td><td>535.0</td><td>342.0</td><td>56.4%</td></tr>
<tr><td>3</td><td>64</td><td>1000.0</td><td>644.0</td><td>55.3%</td></tr>
<tr><td>3</td><td>96</td><td>1466.0</td><td>942.0</td><td>55.6%</td></tr>
<tr><td>4</td><td>32</td><td>552.4</td><td>327.8</td><td>68.5%</td></tr>
<tr><td>4</td><td>64</td><td>1035.0</td><td>627.0</td><td>65.1%</td></tr>
<tr><td>4</td><td>96</td><td>1519.0</td><td>891.4</td><td>70.4%</td></tr>
</table>
CPU …
> improve RGB2YCrCb_i<uchar>()

- modules/core/src/system.cpp
New check prevents IPP from enabling on runtime if it was disabled by environment variable;
Typo fixes;
> IPP enabling fix and typo fix;

- modules/core/include/opencv2/core/fast_math.hpp
> Port to master #6106 (fixed compilation warning)

- modules/core/src/matrix_decomp.cpp
- modules/core/test/test_math.cpp
- modules/ml/src/inner_functions.cpp
- modules/stitching/src/autocalib.cpp
resolves #7063
This pullrequest changes
Cholesky decompostion is now good. Change are agree with @sovrasov comments.  There is no change in code for linear solver.
> Solve Issue 7063

- modules/core/include/opencv2/core/private.hpp
- modules/core/src/mathfuncs.cpp
- modules/core/src/mathfuncs_core.cpp
- IPP was enabled for mathfuncs_core;
- Exp and Log IPP implementations are changed to hal interface;
> IPP was enabled in mathfuncs_core;

- modules/imgproc/src/accum.cpp
* use universal intrinsic instead of raw SSE/NEON implementation
* performance comparison is shown below
* for windows performance measurement, IPP has been switched off to use the universal intrinsic implementation
* please note that this modification is not for performance improvement, so some "after" numbers are slightly worse than "before" number, but basically similar value
|Platform                  | Windows    | Windows |ARM(32bit)|ARM(32bit)|ARM(64bit)|ARM(64bit)|
|--------------------------|------------|---------|----------|----------|----------|----------|
|implementation            | before     | after   |before    |after     |before    |after     |
|Video_Acc.accuracy        | 291 ms     | 256 ms  | 961 ms   | 870 ms   |  626 ms  | 623 ms   |
|Video_AccSquared.accuracy | 220 …
> imgproc: use universal intrinsic in accumulate series

- modules/calib3d/src/calibration.cpp
> Fix modified RFC (cvProjectPoints2 function)resloves #6921

- modules/core/src/hal_replacement.hpp
Fix description of step parameter in LU, SVD, Cholesky and GEMM functions.
> Fix HAL documentation

- modules/calib3d/src/calibration.cpp
image corner points fix as in #6836 for calibration functions (couple found by @snosov1, couple additional)
> fix calib3d changes in #6836 plus some others

- modules/highgui/include/opencv2/highgui.hpp
- modules/highgui/src/window_QT.cpp
> highgui: allow specifying that a button should create a new buttonbar

- modules/features2d/src/mser.cpp
- modules/features2d/test/test_mser.cpp
- modules/python/test/test_mser.py
1. an off-by-one bug in the preprocess2()
2. remove unnecessary histories from the ER tree
3. correct one test case
> some bugs in MSER

- modules/highgui/src/window_QT.cpp
- modules/highgui/src/window_QT.h
this is #6977 rebased.
resolves #7128.
> highgui: window_QT mousecallback code refactored and scaleView working again

- doc/tutorials/introduction/load_save_image/load_save_image.rst
resolves #6944 
add two more includes to make docs more complete
> add reqiured includes to the "Load, Modify, and Save an Image" tutorial

- modules/core/include/opencv2/core/private.hpp
- modules/core/src/copy.cpp
- modules/core/src/stat.cpp
- modules/imgproc/perf/perf_houghLines.cpp
- modules/imgproc/src/color.cpp
- modules/imgproc/src/deriv.cpp
- modules/imgproc/src/filter.cpp
- modules/imgproc/src/hough.cpp
- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/src/smooth.cpp
- modules/imgproc/src/sumpixels.cpp
- modules/imgproc/src/thresh.cpp
- modules/imgproc/test/test_houghLines.cpp
Removes outdated restrictions on ICV API, since ICV is in sync with IPP
> Outdated ICV restrictions were removed;

- apps/interactive-calibration/frameProcessor.cpp
resolves #7146 
Static cast to make vs2010 compiler happy
> casting to fix vs2010 compile error

- modules/imgproc/test/ocl/test_color.cpp
To pass T-API/OCL test on device:
iGPU: Intel(R) HD Graphics 520 (OpenCL 2.0 )
> imgproc: fix accuracy check for HLS cvtColor

- modules/videoio/src/cap_ios_abstract_camera.mm
> Fixes spelling in comment

- modules/highgui/CMakeLists.txt
- modules/highgui/include/opencv2/highgui.hpp
- modules/highgui/include/opencv2/highgui/highgui_c.h
- modules/highgui/src/precomp.hpp
- modules/highgui/test/test_precomp.hpp
**Merge with contrib https://github.com/opencv/opencv_contrib/pull/762**
resolves #7147
> Fix modules deps

- samples/cpp/tutorial_code/ShapeDescriptors/hull_demo.cpp
The Mat "src_copy" is never used in hull_demo.cpp
>  Update hull_demo.cpp

- doc/tutorials/imgproc/shapedescriptors/bounding_rects_circles/bounding_rects_circles.markdown
- samples/cpp/tutorial_code/ShapeDescriptors/generalContours_demo1.cpp
resolves #7136 
-  this one commit handles documentation only
-  add explanation to the Bounding Box and Circles tutorial
- also some minor changes to the respective sample cpp file
> add explanation to the Bounding Box and Circles tutorial

- apps/traincascade/imagestorage.cpp
Fixed traincascade issue resolves #6715
> Fixed traincascade read issue #6715

- modules/calib3d/test/test_cornerssubpix.cpp
- modules/imgproc/src/cornersubpix.cpp
- modules/imgproc/src/samplers.cpp
> Fix cornerSubPix

- cmake/OpenCVFindMatlab.cmake
> cmake: update matlab path

- modules/features2d/src/matchers.cpp
> respective changes added resolves #6366

- 3rdparty/libtiff/CMakeLists.txt
- cmake/OpenCVCompilerOptions.cmake
- modules/core/include/opencv2/core/utility.hpp
- modules/core/perf/perf_umat.cpp
- modules/core/test/test_ds.cpp
- modules/features2d/include/opencv2/features2d.hpp
- modules/flann/include/opencv2/flann.hpp
Fixing several GCC 5.x warnings.
> Fix GCC 5.x warnings

- modules/core/src/matrix.cpp
> Add support for GpuMat in InputArray::isContinuous()

- modules/imgproc/src/canny.cpp
Improve Canny using _mm_movemask_epi8 to find next pixel magnitude greater than lower threshold.
Parallelized finalPass is implemented in CannyImpl.
Some things changed in finalPass which were unneccessary and disturbed implementation in CannyImpl.
> Improve canny

- samples/cpp/peopledetect.cpp
the possibility to open a video stream with the peopledetect.cpp sample.
Feature suggested by @sturkmen72 in #6937.
> Add the possibility to use a video stream with the peopledetect.cpp sample.

- 3rdparty/carotene/hal/tegra_hal.hpp
- modules/imgproc/include/opencv2/imgproc/hal/hal.hpp
- modules/imgproc/src/filter.cpp
- modules/imgproc/src/hal_replacement.hpp
Change SepFilter2D HAL API to address that both kernels are vectors.
> Update HAL interface for separable filters

- modules/core/include/opencv2/core/hal/intrin_neon.hpp
- modules/core/include/opencv2/core/hal/intrin_sse.hpp
- modules/core/src/convert.cpp
- modules/core/test/test_intrin.cpp
* use v_float16x4 (universal intrinsic) instead of raw SSE/NEON implementation
* define v_load_f16/v_store_f16 since v_load can't be distinguished when short pointer passed
* brush up implementation on old compiler (guard correctly)
* add test for v_load_f16 and round trip conversion of v_float16x4
* fix conversion error
> core: use universal intrinsic for FP16

- doc/opencv.bib
- modules/calib3d/include/opencv2/calib3d.hpp
- modules/calib3d/src/calibration.cpp
- modules/core/include/opencv2/core/hal/hal.hpp
- modules/core/src/hal_internal.cpp
- modules/core/src/hal_internal.hpp
- modules/core/src/hal_replacement.hpp
- modules/core/src/lapack.cpp
- modules/core/src/matrix_decomp.cpp
- modules/core/test/test_math.cpp
> Add QR decomposition to HAL

- modules/core/src/matrix.cpp
Fixes indentation, moves local var declarations to places where they're used, uses NULL instead of 0 is assignments to pointer.
> Minor fixes in matrix.cpp

- modules/stitching/src/stitcher.cpp
> Reverted BORDER_CONSTANT to BORDER_REFLECT in stitcher.cpp

- modules/videoio/src/cap_ffmpeg_impl.hpp
resolves #7203
Windows binary package is not updated.
> ffmpeg: update get_fps()

- modules/viz/src/vtk/vtkCloudMatSink.cpp
- modules/viz/src/vtk/vtkCloudMatSource.cpp
- modules/viz/src/vtk/vtkImageMatSource.cpp
- modules/viz/src/vtk/vtkImageMatSource.h
- modules/viz/src/vtk/vtkOBJWriter.cpp
- modules/viz/src/vtk/vtkTrajectorySource.cpp
- modules/viz/src/vtk/vtkVizInteractorStyle.cpp
- modules/viz/src/vtk/vtkXYZReader.cpp
- modules/viz/src/vtk/vtkXYZWriter.cpp
> viz: use ../precomp.hpp in modules/viz/src/vtk/* files

- 3rdparty/libpng/CMakeLists.txt
> cmake: fix libpng build on MSVS2012

- modules/imgproc/perf/perf_blur.cpp
- modules/imgproc/src/smooth.cpp
this commit temporarily disables IPP implementation of the box filter, because it yields slower results; need to investigate it more carefully
> seriously improved performance of blur function, especially 3x3 and 5x5 cases

- 3rdparty/openvx/include/openvx_hal.hpp
- modules/imgproc/src/hal_replacement.hpp
Added a few more immediate mode calls to OpenVX HAL API implementation
> OpenVX HAL implementation extension

- apps/interactive-calibration/calibCommon.hpp
- apps/interactive-calibration/calibController.cpp
- apps/interactive-calibration/calibController.hpp
- apps/interactive-calibration/calibPipeline.cpp
- apps/interactive-calibration/calibPipeline.hpp
- apps/interactive-calibration/frameProcessor.cpp
- apps/interactive-calibration/frameProcessor.hpp
- apps/interactive-calibration/main.cpp
- apps/interactive-calibration/parametersController.cpp
- apps/interactive-calibration/parametersController.hpp
- apps/interactive-calibration/rotationConverters.cpp
- apps/interactive-calibration/rotationConverters.hpp
Add license to interactive-calibration app sources
> Add license to interactive-calibration app sources

- modules/core/src/precomp.hpp
resolves #7160 
code copied from PR [#3987](https://github.com/opencv/opencv/pull/3987)
> integer overflow fixed in getContinuousSize()

- modules/imgproc/include/opencv2/imgproc.hpp
This is a doc fix for #6643 , as discussed with @mshabunin. 
Do let me know if there is more to add!
Cheers!
> docs: adds note for python in docs related to moments, fix for #6643

- modules/videoio/include/opencv2/videoio/cap_ios.h
- modules/videoio/src/cap_ios_video_camera.mm
Cleans up ios stuff declaration removing not needed ivars backing properties
> Cleans up ios stuff declaration

- modules/videoio/src/cap_ios_abstract_camera.mm
Changes NSStringFromSelector(_cmd) for __FUNCTION__.
Changes [error localizedDescription] for [error description] in NSLog.
Fixes spelling in NSLog.
> Minor changes in iOS stuff

- modules/core/include/opencv2/core/utility.hpp
- modules/video/src/bgfg_KNN.cpp
- modules/videoio/src/precomp.hpp
Fixes clang -Wextra-semi warnings.
> Removed some extra semi-colons

- samples/python/houghcircles.py
- samples/python/houghlines.py
- samples/python/tst_scene_render.py
> supress numpy future warning with `None` comparison

- modules/objdetect/include/opencv2/objdetect.hpp
Otherwise this results in an error in my compilation
> bypass makro

- modules/imgproc/src/color.cpp
I improve RGB2Luv_b() for removing wasted _mm_interleave_epi8() and _mm_deinterleave_ps().
<tr><td>32</td><td>492.8</td><td>336.2</td><td>46.6%</td></tr>
<tr><td>64</td><td>934.0</td><td>569.8</td><td>63.9%</td></tr>
<tr><td>96</td><td>1279.6</td><td>798.6</td><td>60.3%</td></tr>
</table>
_srccn:3
> improve RGB2Luv_b()

- modules/imgproc/src/color.cpp
I improve RGB2HLS_b() for removing wasted _mm_interleave_epi8() and _mm_deinterleave_ps().
<tr><td>32</td><td>490.0</td><td>318.8</td><td>53.7%</td></tr>
<tr><td>64</td><td>864.2</td><td>537.6</td><td>60.8%</td></tr>
<tr><td>96</td><td>1235.0</td><td>748.4</td><td>65.0%</td></tr>
</table>
_srccn:3
> improve RGB2HLS_b()

- modules/imgproc/src/color.cpp
I improve HSV2RGB_b() for removing wasted _mm_interleave_ps() and _mm_deinterleave_epi8().
<tr><td>32</td><td>471.2</td><td>330.8</td><td>42.4%</td></tr>
<tr><td>64</td><td>856.0</td><td>561.2</td><td>52.5%</td></tr>
<tr><td>96</td><td>1226.2</td><td>811.6</td><td>51.1%</td></tr>
</table>
_dstcn:3
> improve HSV2RGB_b()

- modules/imgproc/src/color.cpp
Fixes improper array size in RGB2Gray optimization
> RGB2Gray array size fix;

- modules/imgproc/src/color.cpp
> fix Win32 build (2)

- modules/python/test/test_texture_flow.py
Make test_texture_flow.py more robust to prevent problems like with #7282
> Make test_texture_flow.py more robust

- cmake/OpenCVCompilerOptions.cmake
- modules/core/include/opencv2/core/cvdef.h
- modules/core/src/convert.cpp
- modules/core/test/test_intrin.cpp
* use GNUC_MINOR in correct place to check the version of GCC
* guard using ifdef correctly in case of various configuration
* use v_float16x4 correctly by including the right header file
* check FP16 compiler support using cmake correctly
> build: check FP16 build condition correctly

- modules/flann/include/opencv2/flann/lsh_table.h
Otherwise this will result in an error on windows
see more:
[http://stackoverflow.com/questions/5004858/stdmin-gives-error](url)
> bypass macro

- modules/calib3d/src/calibinit.cpp
- modules/calib3d/src/checkchessboard.cpp
- modules/calib3d/src/precomp.hpp
- modules/calib3d/test/test_chesscorners.cpp
- modules/python/test/test_calibration.py
Uninitialized memory access due to invalid address calculation and big memory leak when CV_CALIB_CB_FAST_CHECK flags is set and image does not pass these fast checks.
> Fixed two chessboard detector bugs

- doc/tutorials/introduction/windows_install/windows_install.markdown
> fix issue 7352

- modules/core/include/opencv2/core/cvdef.h
- modules/core/src/convert.cpp
Related #7317
http://pullrequest.opencv.org/buildbot/builders/master_ARMv8-lin/builds/12
> build: fix aarch64 build with aarch64-linux-gnu-g++-4.8

- modules/core/include/opencv2/core/cvdef.h
> cuda: fix fp16 compilation

- modules/java/generator/gen_java.py
resolves #7049
Add support for namespaces in gen_java.py
> Add namespaces and proper support of the pointers

- doc/py_tutorials/py_feature2d/py_brief/py_brief.markdown
- doc/py_tutorials/py_feature2d/py_fast/py_fast.markdown
* Algorithm related get/set methods changed to getThreshold(), etc
* BRIEF is in xfeatures2d now
> python tutorials: removed remainders of former Algorithm interface

- modules/highgui/src/cap_avfoundation_mac.mm
Related #7314
https://github.com/opencv/opencv/pull/7266#issuecomment-250911449
> (2.4) AVFoundation: remove 'const' from getProperty

- modules/core/include/opencv2/core/cuda/color.hpp
- modules/core/include/opencv2/core/cuda/detail/reduce_key_val.hpp
- modules/core/include/opencv2/core/cuda/reduce.hpp
- modules/core/include/opencv2/core/cuda/type_traits.hpp
- modules/core/include/opencv2/core/private.cuda.hpp
- modules/cudafilters/include/opencv2/cudafilters.hpp
> Fix defines typo

- cmake/OpenCVPCHSupport.cmake
- cmake/OpenCVUtils.cmake
> CMake: fix for GCC 6.x

- modules/imgproc/include/opencv2/imgproc/hal/hal.hpp
- modules/imgproc/src/hal_replacement.hpp
- modules/imgproc/src/precomp.hpp
- modules/imgproc/src/sumpixels.cpp
HAL interface for Integral Image
> HAL interface for integral

- modules/calib3d/src/stereobm.cpp
I fixed the difference of the calculation result for findStereoCorrespondenceBM_SSE2() and findStereoCorrespondenceBM_().
If variable 'thresh' is  SHRT_MAX(32767) and over at L527, the calculation result for variable 'mask' is invalid. I fixed its problem.
This pull request is not related to #7155.
>  fixed the difference of the calculation result for findStereoCorrespondenceBM_SSE2() and findStereoCorrespondenceBM_().

- cmake/OpenCVPCHSupport.cmake
- cmake/OpenCVUtils.cmake
> (2.4) CMake: fix for GCC 6.x

- cmake/OpenCVPCHSupport.cmake
- cmake/OpenCVUtils.cmake
1) fix include directories
2) don't use PCH for source file with custom COMPILE_FLAGS
> cmake: update PCH support

- modules/imgproc/src/color.cpp
I improve RGB2Luv_b() for adding simd code when scn equels 4.
<tr><td>32</td><td>849.6</td><td>548.4</td><td>54.9%</td></tr>
<tr><td>64</td><td>1582.6</td><td>995.6</td><td>59.0%</td></tr>
<tr><td>96</td><td>2220.0</td><td>1435.4</td><td>53.3%</td></tr>
</table>
_srccn:4
> add simd code when scn equals 4 at RGB2Luv_b().

- modules/imgproc/src/color.cpp
> improve RGB5x52Gray()

- modules/core/src/stat.cpp
this is augmented PR #6848 by @pi-squared. now it should compile fine with MSVC
> normHamming done with AVX 2 intrinsics (ver 2)

- modules/calib3d/include/opencv2/calib3d.hpp
> replace principle by principal

- doc/tutorials/introduction/windows_install/windows_install.rst
As suggested by @alalek 
backport of #7361
> backport of PR #7361

- modules/imgproc/src/color.cpp
I improve Lab2RGB_b() for adding simd code when dcn equels 4.
<tr><td>24</td><td>1169.2</td><td>376.4</td><td>310.6%</td></tr>
<tr><td>48</td><td>2235.6</td><td>655.2</td><td>341.2%</td></tr>
<tr><td>72</td><td>3351.6</td><td>919.2</td><td>364.6%</td></tr>
</table>
_dstcn:4
> add simd code when dcn equals 4 at Lab2RGB_b().

- modules/imgproc/include/opencv2/imgproc.hpp
> add border replicate note

- modules/core/src/opencl/runtime/opencl_core.cpp
> OCL: fix SVM code

- modules/core/include/opencv2/core/hal/intrin_sse.hpp
- modules/video/src/lkpyramid.cpp
* use universal intrinsic in ```calcSharrDeriv```
* SIMD optimization is done everywhere, so I'll work step by step
* performance test will be reported after
> video: use universal intrinsic implementation for calcSharrDeriv

- modules/imgproc/perf/perf_threshold.cpp
- modules/imgproc/src/thresh.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/315
* use universal intrinsic in threshold function
* add performance test for 32F and 64F threshold
I'll add performance test result later
> imgproc: use universal intrinsic in threshold

- 3rdparty/openvx/include/openvx_hal.hpp
Fix for OpenVX implementation of morphology and color conversion HAL API
> Fix for OpenVX HAL morphology and color conversion

- modules/highgui/include/opencv2/highgui.hpp
- modules/highgui/src/window.cpp
- modules/highgui/src/window_QT.cpp
> highgui: allow wrapping cv::addText

- modules/video/include/opencv2/video/tracking.hpp
resolves #7501 
tracking.hpp
Adding macro for proper wrapping generation of the following classes:
cv::video::DualTVL1OpticalFlow
cv::video::FarnebackOpticalFlow
cv::video::SparsePyrLKOpticalFlow
> fix for #7501

- 3rdparty/carotene/src/div.cpp
> core: let the performance test pass on ARM

- modules/core/src/array.cpp
fixes some overflow issues when creating a huge IplImage.
> Fix imageSize overflow in IplImage

- 3rdparty/carotene/src/div.cpp
related to #7524 
* use rounding to nearest same as divSaturateQ
> ARM: brush up divSaturate of carotene

- modules/imgproc/src/floodfill.cpp
- modules/imgproc/test/test_floodfill.cpp
> Fix wrong default mask value in floodFill

- modules/core/include/opencv2/core/operations.hpp
> (2.4) core: update CV_XADD

- modules/imgproc/src/deriv.cpp
- modules/imgproc/src/morph.cpp
- modules/imgproc/src/smooth.cpp
This allows to use BORDER_ISOLATED flag in morphology operations;
> Support for BORDER_ISOLATED in morphology;

- modules/calib3d/src/stereosgbm.cpp
- modules/core/include/opencv2/core/hal/intrin_neon.hpp
- modules/core/include/opencv2/core/hal/intrin_sse.hpp
- modules/core/test/test_intrin.cpp
* speed up stereo SGBM
* add 8 elements version of reduce operation
* add tests for new universal intrinsic
* performance measurement will follow afterward
> add universal intrinsic in StereoSGBM

- modules/core/include/opencv2/core/mat.hpp
> Correct the comment of Mat::diag(const Mat& d).

- modules/stitching/src/stitcher.cpp
> Compensate exposure before finding seams

- modules/calib3d/test/test_chesscorners.cpp
- modules/imgproc/include/opencv2/imgproc.hpp
- modules/imgproc/src/contours.cpp
- modules/imgproc/test/test_contours.cpp
> findContours: integrate workaround to allow contours detection on image border

- modules/videoio/src/cap_ios_abstract_camera.mm
- modules/videoio/src/cap_ios_video_camera.mm
resolves #7527
release the object created by start method
> fix the problem: leak memory when repeatedly start and stop

- modules/videoio/src/cap_ios_abstract_camera.mm
- modules/videoio/src/cap_ios_video_camera.mm
resolves #7570
check running state
> fix the problem :CvVideoCamera : repeatedly stop cause app crash

- modules/core/include/opencv2/core/hal/intrin_neon.hpp
- vget_lane_*\* accepts constant value, not variable
> core: fix build error on old compiler

- modules/imgproc/src/color.cpp
I add the SSE code for Luv2RGB_f().
<tr><th>dstcn</th><th>n</th><th>Average Clocks (original code)</th><th>Average Clocks (new code)</th><th>Faster Rate (compared with original code)</th></tr>
<tr><td>3</td><td>24</td><td>2709.6</td><td>820.2</td><td>330.4%</td></tr>
<tr><td>3</td><td>48</td><td>5576.4</td><td>1537.0</td><td>362.8%</td></tr>
<tr><td>3</td><td>72</td><td>8003.6</td><td>2399.8</td><td>333.5%</td></tr>
<tr><td>4</td><td>24</td><td>3266.8</td><td>891.8</td><td>366.3%</td></tr>
<tr><td>4</td><td>48</td><td>6538.2</td><td>1710.4</td><td>382.3%</td></tr>
<tr><td>4</td><td>72</td><td>9108.2</td><td>2437.2</td><td>373.7%</td></tr>
</table>
CPU : Intel(R) Core(TM)2 Duo …
> add SSE code for Luv2RGB_f.

- modules/calib3d/test/test_cameracalibration.cpp
- modules/calib3d/test/test_solvepnp_ransac.cpp
- modules/core/perf/opencl/perf_arithm.cpp
- modules/core/perf/perf_convertTo.cpp
- modules/core/perf/perf_merge.cpp
- modules/imgproc/perf/perf_houghLines.cpp
- modules/photo/test/test_decolor.cpp
- modules/ts/misc/run_suite.py
- modules/ts/misc/run_utils.py
> Fix ARM builds

- modules/calib3d/src/stereosgbm.cpp
- modules/core/include/opencv2/core/hal/intrin_cpp.hpp
- modules/core/include/opencv2/core/hal/intrin_neon.hpp
- modules/core/include/opencv2/core/hal/intrin_sse.hpp
- modules/core/src/arithm_simd.hpp
- modules/imgproc/src/canny.cpp
- modules/imgproc/src/spatialgradient.cpp
- use checkHalSimdSupport rather than calling checkHardwareSupport
- add SIMD check in spartialgradient.cpp
> core: add universal hardware support check function

- modules/core/include/opencv2/core.hpp
> Clarify documentation for cv::Algorithm::read

- modules/core/src/persistence.cpp
- modules/core/test/test_io.cpp
> Skip UTF-8 BOM in FileStorage

- modules/core/include/opencv2/core/hal/intrin_neon.hpp
> fp16: fix build error

- modules/calib3d/src/fundam.cpp
> convertPointsToHomogeneous: fix output type for depth == CV_32S

- 3rdparty/openvx/include/openvx_hal.hpp
Updated OpenVX1.0.1 guards and wrappers to enable functionality available both in 1.0.1 and 1.1, but with different API
> OpenVX 1.0.1 compliance update

- modules/imgproc/src/contours.cpp
> imgproc: fix trailingZeros for MSVS 2010

- modules/highgui/src/window_gtk.cpp
> Fix error for window_gtk

- modules/imgproc/test/test_contours.cpp
Tests #7458 . The updated test should fail until #7460 is merged.
Should perhaps have included this as part of #7460, however first thought this would test #7449 as well. But I guess it doesn't. (Also, nicely typoed even this into the branch name... This has nothing to do with 7409.)
> Change contour test images to be very wide

- 3rdparty/libpng/CMakeLists.txt
> cmake: fix libpng for AARCH64

- 3rdparty/openvx/CMakeLists.txt
- 3rdparty/openvx/README.md
- 3rdparty/openvx/include/ivx.hpp
> OpenVX C++ wrappers docs

- modules/videoio/include/opencv2/videoio.hpp
- modules/videoio/src/cap.cpp
> Fix api preferences changed

- modules/python/common.cmake
Also fixes issue with empty `PYTHON_PACKAGES_PATH` (cross-compilation mode)
> CMake: update python installation

- samples/cpp/detect_blob.cpp
- samples/cpp/detect_mser.cpp
> Solve issue 7676

- modules/imgproc/src/filter.cpp
* Adds filter2D IPP runtime check;
* Workaround for ippiFilterBorder bug with kernel of size 1x1 in IPP 2017;
> IPP 2017 filter2D fix;

- modules/core/test/test_dxt.cpp
PR #6561 
Issue #6536
Problem is reproduced via AARCH64 cross-compilation on Ubuntu 16.04
> (2.4) Backport 6561

- 3rdparty/libtiff/CMakeLists.txt
- 3rdparty/openexr/CMakeLists.txt
- modules/calib3d/src/homography_decomp.cpp
- modules/core/include/opencv2/core/hal/intrin_cpp.hpp
- modules/highgui/src/window_gtk.cpp
- modules/superres/src/optical_flow.cpp
- modules/videoio/src/cap_ffmpeg_impl.hpp
**Merge with contrib:** https://github.com/opencv/opencv_contrib/pull/849
GCC 6+
MacOSX 10.12 with Xcode 8
> Fix build warnings

- 3rdparty/openvx/include/openvx_hal.hpp
Temporary disabled OpenVX HAL API for resize and wraps.
> Disabled resize and wrapAffine OpenVX HAL API

- 3rdparty/openvx/include/ivx.hpp
- samples/CMakeLists.txt
- samples/openvx/CMakeLists.txt
- samples/openvx/no_wrappers.cpp
- samples/openvx/wrappers.cpp
- samples/openvx/wrappers_video.cpp
Basic version of OpenVX interoperability sample
> OpenVX sample

- modules/imgproc/src/color.cpp
Please wait for reviewing the code, until I write the measurement result for speed.
@alalek
I'm sorry to bother you.
Please build this request in ARMv7, ARMv8, and Android pack.
> add NEON code for RGB2Luv_f.

- 3rdparty/openvx/include/ivx.hpp
Added wrappers for vx_matrix and vx_convolution to ivx wrappers
> Added wrappers for vx_matrix and vx_convolution

- CMakeLists.txt
- cmake/OpenCVCompilerOptions.cmake
- cmake/OpenCVDetectCXXCompiler.cmake
> (2.4) cmake: ccache

- modules/java/android_test/src/org/opencv/test/OpenCVTestCase.java
- modules/java/android_test/src/org/opencv/test/calib3d/Calib3dTest.java
- modules/java/android_test/src/org/opencv/test/core/CoreTest.java
- modules/java/android_test/src/org/opencv/test/core/MatTest.java
- modules/java/android_test/src/org/opencv/test/imgproc/ImgprocTest.java
- modules/java/test/build.xml
- modules/java/test/src/org/opencv/test/OpenCVTestCase.java
#7709 
#3759 (junit report generation)
> (2.4) java: backport test changes from master

- modules/core/misc/java/test/CoreTest.java
- modules/core/src/arithm_core.hpp
- modules/imgproc/misc/java/test/ImgprocTest.java
- modules/java/android_test/src/org/opencv/test/OpenCVTestCase.java
- modules/java/pure_test/build.xml
- modules/java/pure_test/src/org/opencv/test/OpenCVTestCase.java
To pass without opencv_contrib and on "debug" build.
> Fix java tests

- modules/calib3d/include/opencv2/calib3d.hpp
> calibrateCamera: specifiy what kind of re-projection error is returned

- modules/viz/src/vtk/vtkCocoaInteractorFix.mm
- samples/cpp/tutorial_code/viz/creating_widgets.cpp
- samples/cpp/tutorial_code/viz/launching_viz.cpp
- samples/cpp/tutorial_code/viz/transformations.cpp
- samples/cpp/tutorial_code/viz/widget_pose.cpp
> (2.4) Backport viz fixes from 7536

- modules/imgproc/src/contours.cpp
https://github.com/opencv/opencv_contrib/issues/872 (partial fix)
> imgproc: fix findContours (submatrix input)

- modules/calib3d/src/fisheye.cpp
- modules/core/include/opencv2/core/mat.hpp
> (2.4) Backport 7710

- CMakeLists.txt
- cmake/OpenCVUtils.cmake
> (2.4) cmake: backport debug features

- modules/core/src/rand.cpp
> ARM: let the test Calib3d_StereoCalibrate_C pass on 64bit ARM

- modules/cudaarithm/perf/perf_arithm.cpp
- modules/cudaarithm/test/test_core.cpp
- modules/cudafeatures2d/test/test_features2d.cpp
- modules/cudafilters/test/test_filters.cpp
- modules/cudaimgproc/test/test_canny.cpp
- modules/cudaimgproc/test/test_histogram.cpp
- modules/cudaimgproc/test/test_hough.cpp
- modules/cudaobjdetect/test/test_objdetect.cpp
- modules/cudaoptflow/test/test_optflow.cpp
- modules/cudastereo/test/test_stereo.cpp
> test: fix cuda build

- 3rdparty/openvx/include/ivx.hpp
Added wrappers for OpenVX context attributes and setter for convolution scale attribute
> Added OpenVX context and convolution attribute wrappers

- 3rdparty/openvx/include/ivx.hpp
- modules/imgproc/src/deriv.cpp
Implemented Sobel computation via OpenVX Sobel3x3 immediate mode call
> Added OpenVX based processing to Sobel

- 3rdparty/openvx/include/ivx.hpp
Change node creation call to inline to avoid link conflict
> OpenVX wrappers linkage fix

- 3rdparty/openvx/include/ivx.hpp
- modules/core/src/stat.cpp
Implemented minMaxInd evaluation via OpenVX minMaxLoc immediate mode call
> Added OpenVX based processing to minMaxLoc

- modules/imgproc/src/histogram.cpp
> added OpenVX call to equalizeHist() function

- modules/core/src/convert.cpp
> Added OpenVX based processing to depth conversion

- 3rdparty/openvx/include/ivx.hpp
- modules/core/src/stat.cpp
Implemented meanStdDev computation via OpenVX meanStdDev immediate mode call
> Added OpenVX based processing to meanStdDev

- modules/imgproc/src/accum.cpp
Now ready for merge
Added OpenVX calls for accumulate(), accumulateSquare(), accumulateWeighted()
> Added OpenVX based processing to accumulate functions

- 3rdparty/openvx/include/ivx.hpp
- modules/imgproc/src/thresh.cpp
Implemented threshold image filtering via OpenVX threshold immediate mode call
> Added OpenVX based processing to threshold

- 3rdparty/openvx/include/ivx.hpp
- modules/imgproc/src/smooth.cpp
Implemented medianBlur image filtering via OpenVX median3x3 immediate mode call
> Added OpenVX based processing to medianBlur

- 3rdparty/openvx/include/openvx_hal.hpp
Added OpenVX based implementation of Gray2BGR HAL API call
> Added OpenVX based implementation for Gray2BGR conversion HAL API

- 3rdparty/openvx/include/ivx.hpp
- modules/imgproc/src/smooth.cpp
Implemented box image filtering via OpenVX box3x3 immediate mode call
> Added OpenVX based processing to boxFilter

- doc/tutorials/imgproc/imgtrans/canny_detector/canny_detector.markdown
a line in the documentation for the Canny edge detector.
> fix a typo in the canny docs

- 3rdparty/openvx/include/ivx.hpp
- modules/core/src/convert.cpp
Implemented LUT image processing via OpenVX TableLookup immediate mode call
> Added OpenVX based processing to LUT

- modules/imgproc/src/smooth.cpp
Implemented gaussianBlur image filtering via OpenVX gaussian3x3 immediate mode call
> Added OpenVX based processing to gaussianBlur

- 3rdparty/openvx/include/openvx_hal.hpp
Added OpenVX based implementation of cv_hal_integral
> OpenVX based implementation for integral image HAL API.

- modules/cudaarithm/test/test_arithm.cpp
> build: fix cuda tests

- cmake/OpenCVDetectCUDA.cmake
- modules/core/include/opencv2/core/cuda/reduce.hpp
- modules/cudaarithm/test/test_arithm.cpp
- modules/cudafilters/test/test_filters.cpp
- modules/cudaimgproc/src/generalized_hough.cpp
- modules/cudev/test/CMakeLists.txt
> build: cuda warnings

- modules/video/src/lkpyramid.cpp
Operations inside for loops are unnecessary. They are repeated anyway just below for loops
> Removed redundant calculations

- modules/java/test/build.xml
> (2.4) java: fix PATH environment variable

- modules/video/perf/perf_tvl1optflow.cpp
- modules/video/test/test_tvl1optflow.cpp
TVL1 test update.
Backport #7640
> (2.4) Backport 7640

- 3rdparty/openexr/CMakeLists.txt
- cmake/OpenCVDetectCXXCompiler.cmake
> (2.4) Fixed Intel C++ 17 build in VS2015

- samples/python/mser.py
> Update MSER python sample

- modules/features2d/src/akaze.cpp
- modules/features2d/src/kaze/AKAZEFeatures.cpp
- modules/features2d/src/kaze/AKAZEFeatures.h
- modules/features2d/test/test_detectors_regression.cpp
> Fix missing angles in AKAZE keypoints

- modules/calib3d/src/solvepnp.cpp
> Fix wrong threshold in SolvePnPRansac

- modules/core/src/mathfuncs_core.cpp
> core: exp/log workaround for MSVS

- 3rdparty/openvx/include/ivx.hpp
- modules/imgproc/src/histogram.cpp
Implemented calcHist evaluation via OpenVX Histogram immediate mode call
> Added OpenVX based processing to calcHist

- modules/core/include/opencv2/core/hal/intrin_cpp.hpp
Fixed warnings produced by new doxygen
> Documentation fixes for latest doxygen

- 3rdparty/openvx/include/ivx.hpp
Added vxTruncateArray wrapper to ivx::Array
> Added OpenVX vxTruncateArray wrapper to ivx::Array

- 3rdparty/openvx/include/ivx.hpp
> OpenVX wrappers for vx_pyramid added

- 3rdparty/openvx/include/ivx.hpp
- modules/imgproc/src/imgwarp.cpp
Implemented remap evaluation via OpenVX Remap immediate mode call
> Added OpenVX based processing to remap

- 3rdparty/openvx/include/ivx.hpp
Added wrapper for IMAGE_SPACE attribute setter
> Added wrapper for OpenVX image IMAGE_SPACE attribute setter

- modules/features2d/src/fast.cpp
> Added OpenVX based processing to FAST

- modules/ml/src/rtrees.cpp
> Disable training of RTrees when CVFolds > 0

- 3rdparty/ippicv/downloader.cmake
**Merge with**: https://github.com/opencv/opencv_contrib/pull/904
> cmake: unpack into binary directory

- samples/gpu/video_writer.cpp
> Bug fix for #7846

- modules/imgproc/src/featureselect.cpp
**Disabled due to bad accuracy and multiple differences in implementation**
> OpenVX Harris corners wrappers

- cmake/OpenCVUtils.cmake
**Merge with**: https://github.com/opencv/opencv_contrib/pull/908
resolves #7895
> cmake: fix CMake error

- modules/calib3d/src/calibinit.cpp
- modules/calib3d/src/calibration.cpp
- modules/calib3d/test/test_cameracalibration.cpp
- modules/photo/src/inpaint.cpp
Partially fixed #6377
There are still many similar cases in calib3d module which requires legacy code refactoring.
> Fix *Array -> CvMat conversion

- doc/tutorials/objdetect/cascade_classifier/cascade_classifier.markdown
resolves #7900
Fixes the broken links in the Cascade Classifier tutorial
> Fixed broken links in the cascade classifier tutorial

- modules/imgcodecs/CMakeLists.txt
- modules/videoio/CMakeLists.txt
> cmake(osx): fix CoreImage error

- doc/tutorials/introduction/windows_install/windows_install.markdown
- doc/tutorials/introduction/windows_visual_studio_Opencv/windows_visual_studio_Opencv.markdown
*No code changes.*
This fixes a couple dozen typos in the documentation, including an invalid path in a tutorial.
> Fix Documentation Typos

- modules/imgproc/src/drawing.cpp
> imgproc: fix using of uninitialized edge[] members in FillConvexPoly

- modules/calib3d/src/compat_ptsetreg.cpp
- modules/calib3d/src/fisheye.cpp
- modules/calib3d/src/triangulate.cpp
- modules/calib3d/test/test_chesscorners.cpp
> clean up unused #if

- modules/highgui/src/window.cpp
https://github.com/opencv/opencv/pull/7866#issuecomment-269322846
> highgui: preserve waitKey -1 return value

- modules/core/misc/java/src/java/core+MatOfRect2d.java
- modules/core/misc/java/src/java/core+Rect2d.java
- modules/java/generator/gen_java.py
- modules/java/generator/src/cpp/converters.cpp
- modules/java/generator/src/cpp/converters.h
- modules/java/generator/src/java/utils+Converters.java
I fixed this Issue.
https://github.com/opencv/opencv_contrib/issues/767
> Added Java wrapping for tracking module

- doc/pattern_tools/gen_pattern.py
- doc/pattern_tools/svgfig.py
Fixed `gen_pattern.py` and `svgfig.py` for Python 3 compatibility:
- Exception raising as functions (removed comma)
- Print statements as functions
- Removed long type checks (py3 uses int)
- Minor whitespace reformatting with respect to PEP 8
> Fixed exceptions, print statements, and long types for gen_pattern.py to be Python 3 compatible

- modules/ml/src/lr.cpp
misspelled class name in serialization
> ml: fix small typo in lr.cpp

- doc/tutorials/core/basic_linear_transform/basic_linear_transform.markdown
the tutorial code in the basic_linear_transform tutorial. Add some resource links.
> Fix tutorial code link in basic_linear_transform tutorial.

- modules/core/src/persistence.cpp
- modules/core/test/test_io.cpp
> Add support of type headings from YAML1.2

- doc/py_tutorials/py_imgproc/py_houghlines/py_houghlines.markdown
- samples/python/tutorial_code/imgProc/hough_line_transform/hough_line_transform.py
- samples/python/tutorial_code/imgProc/hough_line_transform/probabilistic_hough_line_transform.py
some typos in the py_houghlines tutorial, fix #8012
Python code is also extracted.
I made some changes in the documentation that sound better for me but I am not a native english speaker. So feel free to correct me.
> Fix typos in py_houghlines tutorial.

- modules/imgproc/src/corner.cpp
- use universal intrinsic in corner detection
- measurement result will follow shortly
> imgproc: use universal intrinsic in corner detection series

- cmake/OpenCVModule.cmake
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/947
Resolves https://github.com/opencv/opencv_contrib/issues/853
Related #7891
> cmake: add defines to enable useful macroses

- modules/features2d/src/fast.cpp
- use universal intrinsic in fast
- measurement will follow shortly
> use universal intrinsic in fast

- modules/cudaoptflow/src/cuda/pyrlk.cu
- modules/cudaoptflow/src/pyrlk.cpp
Attempts to resolve #7482.
Changed reference to unbound textures in dense Pyrlk algorithm.
> Fix #7482. Updated dense flow routine to reference bound textures.

- doc/tutorials/gpu/gpu-thrust-interop/gpu_thrust_interop.markdown
- doc/tutorials/gpu/table_of_content_gpu.markdown
the thrust tutorial in the GPU main page documentation.
> Add thrust tutorial in the GPU main page documentation.

- modules/calib3d/src/stereobm.cpp
- use universal intrinsic in stereo matching
- check SIMD availability before executing
- measurement result will follow shortly
> calib3d: use universal intrinsic in stereo matching

- modules/imgproc/src/spatialgradient.cpp
- use only universal intrinsic
> imgproc: remove pure SSE2 and use only universal intrinsic

- modules/imgproc/src/corner.cpp
- use AVX intrinsic in corner detection series
- measurement result will follow shortly
> imgproc: optimize corner detection series using AVX instructions

- modules/calib3d/misc/java/test/Calib3dTest.java
> java: force 64F in solvePnP test

- modules/core/src/stat.cpp
- make sure SIMD optimization works even when AVX is not available
> core: brush up AVX optimization in popcount

- modules/ml/include/opencv2/ml.hpp
- modules/ml/src/em.cpp
- modules/ml/src/lr.cpp
- modules/ml/src/nbayes.cpp
- modules/ml/src/svmsgd.cpp
Adds wrappers for load methods of EM, LR, SVMSGD and Normal Bayes Classifiers
> Wrappers for load methods of EM, LR, SVMSGD and Normal Bayes Classifier

- modules/ml/include/opencv2/ml.hpp
> ml::EM: add documentation for predict() method

- modules/video/include/opencv2/video/background_segm.hpp
> Clarify docs for MOG2::apply

- modules/imgproc/src/color.cpp
- modules/ocl/src/opencl/cvt_color.cl
backport of #7481 
resolves #4946
> fixed YUV channel equivalence

- modules/core/include/opencv2/core/hal/intrin_sse.hpp
- modules/core/src/lapack.cpp
- use universal intrinsic in VBLAS
- brush up ```v_reduce_sum``` of SSE version
> core: use universal intrinsic in VBLAS

- modules/core/include/opencv2/core/base.hpp
Allows export of these functions:
bool useIPP();
void setUseIPP(bool flag);
to language bindings.
> Adds IPP control functions to bindings export

- modules/imgproc/include/opencv2/imgproc.hpp
resolves #8136
change threshold doc
> Solve issue 8136 opencv doc of threshold

- doc/py_tutorials/py_imgproc/py_histograms/py_histogram_begins/py_histogram_begins.markdown
Fixes typo in py_tutorials py_histogram_begins
> Corrected typo in py_histogram_begins tutorial

- modules/core/include/opencv2/core/cvstd.hpp
- modules/core/test/test_misc.cpp
> core: fix String::end() implementation

- modules/ts/include/opencv2/ts/ts_gtest.h
Taken from https://github.com/google/googletest/pull/856 
Previous fix: https://github.com/opencv/opencv/pull/8123
> update fix for #8105 (compiling with mingw32)

- modules/core/include/opencv2/core/utility.hpp
Fix typos in the documentation for the class `AutoBuffer`.
> Fix typos in the documentation for AutoBuffer.

- modules/core/include/opencv2/core/core.hpp
- modules/core/src/drawing.cpp
- modules/highgui/test/test_drawing.cpp
Backport of line drawing implementation fix to handle coordinates above 32767 correctly
> Backport of PR #7161 fix for drawing beyond 32768 range

- modules/core/include/opencv2/core/base.hpp
Fix typos in the documentation.
> Fix typos.

- modules/core/include/opencv2/core/cvstd.inl.hpp
Support for printing out cv::Complex.
> Add support for printing out cv::Complex.

- doc/tutorials/imgproc/imgtrans/filter_2d/filter_2d.markdown
Fixes two typos in the Filter 2D tutorial
> Fixed two typos in the Filter2D tutorial

- cmake/OpenCVFindMKL.cmake
- modules/core/CMakeLists.txt
**Merge with:** https://github.com/opencv/opencv_contrib/pull/1002
> cmake: fix order of MKL libraries, don't pass additional libraries as modules

- modules/core/include/opencv2/core/cvstd.inl.hpp
- modules/core/include/opencv2/core/mat.hpp
Fix issue #8181
The comment for the method `cv::Mat::diag(int)`.
> Fix the documentation for Mat::diag(int).

- modules/stitching/include/opencv2/stitching/detail/blenders.hpp
- modules/stitching/src/blenders.cpp
- modules/stitching/src/cuda/multiband_blend.cu
- modules/stitching/test/test_blenders.cuda.cpp
Improve MultibandBlender by moving more work to cuda and reducing the number of upload/download. An accuracy test is added.
> Improve MultibandBlender cuda

- modules/core/include/opencv2/core/mat.hpp
Fix the error in the demo code for `cv::Mat::forEach`.
> Fix an error in the demo code for cv::Mat::forEach

- modules/core/include/opencv2/core.hpp
- modules/core/include/opencv2/core/core_c.h
- modules/core/include/opencv2/core/cvdef.h
- modules/core/include/opencv2/core/utility.hpp
- modules/core/src/system.cpp
Fix typos in the documentation.
> Fix typos in the documentation

- modules/stitching/src/cuda/multiband_blend.cu
resolves multiband_blend.cu build error in issue [#1012](https://github.com/opencv/opencv_contrib/issues/1012)
remove keyword static
> fix multiband_blend.cu build error in issue opencv_contrib#1012

- modules/core/src/hal_internal.cpp
> hal: replace round() with cvRound()

- CMakeLists.txt
- modules/imgcodecs/CMakeLists.txt
- modules/videoio/CMakeLists.txt
- platforms/ios/build_framework.py
resolves #8121
resolves #8227
- Don't disable opencv_world
- Append `-framework UIKit`
> Update IOS framework scripts

- modules/core/include/opencv2/core/hal/intrin_sse.hpp
- modules/imgproc/perf/opencl/perf_blend.cpp
- modules/imgproc/src/blend.cpp
**Merge with opencv_extra**: https://github.com/opencv/opencv_extra/pull/325
- optimize blend using universal intrinsic
- add more channels/depth performance test for blend
- performance test will follow shortly
> imgproc: optimize blend using universal intrinsic

- modules/core/src/matrix.cpp
- modules/core/src/umatrix.cpp
- modules/core/test/test_operations.cpp
- modules/core/test/test_umat.cpp
> core: fix adjustROI behavior on indexes overflow

- modules/imgproc/src/connectedcomponents.cpp
> imgproc: remove non ASCII character from comment

- samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp
> Backport #8267

- 3rdparty/openvx/hal/openvx_hal.cpp
- modules/core/include/opencv2/core/openvx/ovx_defs.hpp
- modules/core/include/opencv2/core/utility.hpp
- modules/core/src/convert.cpp
- modules/core/src/ovx.cpp
- modules/core/src/stat.cpp
- modules/core/src/system.cpp
- modules/features2d/src/fast.cpp
- modules/imgproc/src/accum.cpp
- modules/imgproc/src/canny.cpp
- modules/imgproc/src/deriv.cpp
- modules/imgproc/src/featureselect.cpp
- modules/imgproc/src/histogram.cpp
- modules/imgproc/src/imgwarp.cpp
- modules/imgproc/src/pyramids.cpp
- modules/imgproc/src/smooth.cpp
- modules/imgproc/src/thresh.cpp
- modules/video/src/lkpyramid.cpp
OpenVX HAL changed to reuse common per thread context to speedup execution
> OpenVX calls updated to use single common OpenVX context per thread

- modules/core/include/opencv2/core/persistence.hpp
- modules/core/src/persistence.cpp
- modules/core/test/test_io.cpp
> Fix DMatch and Keypoint I/O in FileStorage

- samples/cpp/tutorial_code/ImgProc/HitMiss.cpp
> Code cleanup, removed cv:: because using namespace cv is already used.

- modules/ml/include/opencv2/ml.hpp
- modules/ml/src/rtrees.cpp
- modules/ml/test/test_mltests.cpp
Finished with several samples support, need regression testing
resolves #6227 
the predictProb function, which receives several samples to be predicted and returns the amount of votes each class receives.
> Finished with several samples support, need regression testing

- modules/imgproc/include/opencv2/imgproc/hal/hal.hpp
- modules/imgproc/src/filter.cpp
- modules/imgproc/src/morph.cpp
Trying hal::morph function instead of hal::Morph class.
> Replaced hal::Morph class with hal::morph function

- samples/cpp/tutorial_code/core/AddingImages/AddingImages.cpp
Increase readability by using namespace std
using namespace std;
std::cout to cout
std::endl to endl
> Code easier to read now

- modules/core/src/persistence.cpp
Trivial fix for minor compilation warning and errors
> Portability

- doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown
ROI should be region of interest.
> Fix the description of ROI in python tutorials doc

- modules/calib3d/include/opencv2/calib3d.hpp
- modules/calib3d/src/five-point.cpp
Resolves #8034 
Resolves #8032
> calib3d: add a new overload for cv::recoverPose
