opencv/opencv

apps/traincascade/cascadeclassifier.cpp
#8207
Title says it all.
@alalek as requested in the other PR, backport of the timing fix.
=> backport of PR #8207

modules/core/include/opencv2/core/mat.hpp
Update comments for cv::InputArray.
=> Update comments for cv::InputArray.

modules/ml/include/opencv2/ml.hpp
=> ml: remove useless namespace identifiers in SVM

modules/core/include/opencv2/core/persistence.hpp, modules/core/test/test_io.cpp
=> core: add single DMatch/Keypoint I/O

modules/core/src/ocl.cpp
=> fix an error while setting kernel argument for a 3-D matrix.

modules/imgproc/include/opencv2/imgproc.hpp
Make it more clear for the type of input argument.
More understandable documentation for cv::accumulate.
=> Update documentation for cv::accumulate.

modules/core/include/opencv2/core/mat.hpp
Fix typos in the documentation for cv::Mat.
=> Fix typos in the documentation for cv::Mat.

modules/core/include/opencv2/core/mat.inl.hpp
Change the CV_DebugAssert() in Mat_<>::operator [] so that it supports 3d matrix now.
=> Fix the bug in Mat_<>::opeartor []

doc/py_tutorials/py_feature2d/py_features_meaning/py_features_meaning.markdown
Grammatical Error in py_features_meaning.markdown: Changed phrase on line 13 FROM "You get a lot of small pieces of a images," TO "You get a lot of small pieces of an image,".
=> Fix grammar error in py_features_meaning.markdown

modules/core/include/opencv2/core/mat.hpp
=> Fix an error in the documentation.

modules/core/include/opencv2/core/mat.hpp
=> Impove the documentation for Mat::diag.

modules/imgproc/include/opencv2/imgproc.hpp
=> Improve documentation.

modules/features2d/CMakeLists.txt, modules/features2d/test/test_precomp.hpp, modules/highgui/CMakeLists.txt, modules/highgui/src/precomp.hpp, modules/java/pure_test/CMakeLists.txt, modules/objdetect/CMakeLists.txt, modules/objdetect/src/precomp.hpp, modules/stitching/CMakeLists.txt, modules/superres/CMakeLists.txt
Linked PR: opencv/opencv_contrib#1063
Some of intermodule dependencies removed. 
Tested by building OpenCV with one module disabled.
=> Reduce modules dependencies

modules/core/src/precomp.hpp
=> Add more comments to the members of CoreTLSData related to OpenCL.

3rdparty/openvx/hal/openvx_hal.cpp, 3rdparty/openvx/include/ivx.hpp, cmake/FindOpenVX.cmake, cmake/checks/openvx_refenum_test.cpp
The change should detect and handle change of  vx_reference_attribute_e
=> Updated OpenVX wrappers to handle renamed Reference attributes

modules/imgcodecs/src/ios_conversions.mm
=> Fix MatToUIImage and UIImageToMat

modules/core/src/matrix.cpp
=> fix issue 8189.

modules/core/include/opencv2/core/fast_math.hpp
=> core: suppress warnings on Jetson TK1

modules/python/src2/cv2.cpp
#8497 was good, but not perfect. I believe this is the proper way to write it.
Minor fix to avoid memory leakage
=> Avoid memory leakage in smart pointers wrapper

doc/py_tutorials/py_imgproc/py_contours/py_contours_hierarchy/py_contours_hierarchy.markdown
=> Correcting issue #8431

modules/video/src/bgfg_gaussmix2.cpp
=> Update bgfg_gaussmix2.cpp to avoid divide by zero cases.

modules/core/src/mathfuncs_core.cpp
Pretty straight forward. I just translated the SSE code to AVX2.
=> Optimize exp32f with AVX2

cmake/OpenCVPCHSupport.cmake
Warnings: http://pullrequest.opencv.org/buildbot/builders/master-lin64-static/builds/10062
=> cmake: fix GCC precompiled headers warnings

cmake/OpenCVCompilerOptions.cmake, cmake/templates/cvconfig.h.in, modules/core/include/opencv2/core/cv_cpu_dispatch.h, modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/include/opencv2/core/private.hpp, modules/core/test/test_intrin.cpp
Fix build error: http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV_noSSE-win64-vc14-debug/builds/10062
=> cmake: fix fp16 support

modules/superres/CMakeLists.txt
=> superres: suppress warnings from cuda

modules/photo/CMakeLists.txt
=> photo: suppress warning on Jetson TK1

modules/core/include/opencv2/core.hpp
=> fix a typo in the documentation.

cmake/checks/ffmpeg_test.cpp
=> ffmpeg: add __STDC_CONSTANT_MACROS to check code

modules/calib3d/src/ap3p.cpp
=> calib3d: fix build error on VS2012

modules/calib3d/test/test_fisheye.cpp
=> calib3d: fix typo and align white spaces

cmake/OpenCVFindLAPACK.cmake
resolves #8599 
resolves #8507
=> fix build error on ODROID-X2

modules/core/include/opencv2/core/ocl.hpp, modules/core/src/intel_gpu_gemm.cpp, modules/core/src/intel_gpu_gemm.inl.hpp, modules/core/src/matmul.cpp, modules/core/src/ocl.cpp, modules/core/src/opencl/intel_gemm.cl
=> Gemm kernels for Intel GPU

modules/imgproc/include/opencv2/imgproc.hpp
=> Fix markdown format.

modules/calib3d/test/test_cameracalibration.cpp, modules/ml/src/lr.cpp, modules/ml/test/test_emknearestkmeans.cpp, modules/ml/test/test_lr.cpp, modules/shape/test/test_shape.cpp
Some unit tests segfaults due to empty data.
=> fixing segfaults occuring when launching those unit tests

modules/highgui/include/opencv2/highgui.hpp
=> Fixes typo

modules/core/include/opencv2/core/cvstd.inl.hpp, modules/core/include/opencv2/core/mat.hpp, modules/core/include/opencv2/core/mat.inl.hpp, modules/core/src/matrix.cpp
**WIP**
some changes in the core to assist refactoring of opencv_contrib's dnn module; see https://github.com/opencv/opencv_contrib/pull/1102
=> dnn refactoring

cmake/OpenCVCompilerOptimizations.cmake
=> cmake: dispatcher: add handling of include dirs

doc/tutorials/imgproc/imgtrans/hough_circle/hough_circle.markdown
Corrected the spelling which was used in explanation for parameters.
=> Spell correction

modules/core/test/test_io.cpp
=> fix test error on VS2012

platforms/ios/build_framework.py, platforms/osx/build_framework.py
Use all available cpu cores in iOS/OSX build procedure
=> Use all available cpu cores in iOS/OSX build procedure

modules/core/perf/perf_lut.cpp, modules/features2d/perf/perf_fast.cpp, modules/imgproc/perf/perf_accumulate.cpp, modules/imgproc/perf/perf_filter2d.cpp, modules/imgproc/perf/perf_pyramids.cpp, modules/imgproc/perf/perf_warp.cpp, modules/video/perf/perf_optflowpyrlk.cpp
WIP
Added a few tests that evaluate performance with parameters suitable to process data with OpenVX
depends on extra [PR331](https://github.com/opencv/opencv_extra/pull/331)
=> Extended set of existing performance test to OpenVX HAL suitable modes

modules/core/include/opencv2/core/mat.hpp, modules/core/include/opencv2/core/mat.inl.hpp
=> fix issue 8411.

3rdparty/ffmpeg/ffmpeg.cmake
ffmpeg 3.2.1 -> 3.3
libvpx 1.6.0 -> 1.6.1
https://github.com/opencv/opencv_3rdparty/pull/14
=> cmake: update FFmpeg Windows wrapper

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/stereosgbm.cpp, modules/calib3d/test/test_stereomatching.cpp
4-directional variation of SGBM is added and parallelized.
SIMD optimizations for that code isn't done. This will be next step.
=> Making sgbm parallel

doc/footer.html, doc/tutorials/imgproc/histograms/template_matching/template_matching.markdown, doc/tutorials/imgproc/table_of_content_imgproc.markdown, samples/cpp/tutorial_code/Histograms_Matching/MatchTemplate_Demo.cpp, samples/java/tutorial_code/ImgProc/tutorial_template_matching/MatchTemplateDemo.java, samples/python/tutorial_code/imgProc/match_template/match_template.py
=> Extending template_matching tutorial with Java

modules/videoio/src/cap_aravis.cpp
resolves #8707 
Corrects the code to use only std::fabs() function.
Adds support for 16-bit mono files.
Additionally reduces number of  internal buffers.
=> Aravis: Use of std::fabs, added support for 16-bit mono files and exposure compensation

modules/imgproc/src/color.cpp, modules/imgproc/test/test_color.cpp
=> imgproc: fix BGRA2BGRA conversion

doc/tutorials/introduction/building_tegra_cuda/building_tegra_cuda.markdown, doc/tutorials/introduction/java_eclipse/java_eclipse.markdown, doc/tutorials/introduction/linux_install/linux_install.markdown
Update broken downloads link in documentation
=> Update broken downloads link in documentation

modules/videoio/src/cap_v4l.cpp
=> Fix frame timestamp in VideoCapture::get

modules/photo/doc/denoising.rst
resolves #7899 
Corrected hForColorComponents to hColor in fastNlMeansDenoisingColored and fastNlMeansDenoisingColoredMulti
=> correct bug in fastmeans (ref #7899)

modules/videoio/src/cap_aravis.cpp
Support GigE (Aravis plugin) with bayer GR 8 raw format
Link: #8726
=> Aravis: support Bayer GR 8 raw format.

modules/core/src/stat.cpp, modules/core/test/test_countnonzero.cpp
- Fixed incorrect work of `countNonZero` IPP implementation for multidimensional arrays.
- Added CountNonZeroND test
=> Fixed countNonZero for N dimensions

modules/core/include/opencv2/core/base.hpp, modules/core/include/opencv2/core/cvdef.h, modules/core/include/opencv2/core/mat.inl.hpp, modules/core/include/opencv2/core/types.hpp, modules/core/src/arithm.cpp, modules/core/src/array.cpp, modules/core/src/copy.cpp, modules/core/src/matrix.cpp, modules/core/src/ocl.cpp, modules/core/src/out.cpp, modules/core/src/parallel_pthreads.cpp, modules/core/src/persistence.cpp, modules/core/src/rand.cpp, modules/core/src/stat.cpp, modules/core/src/umatrix.cpp, modules/imgproc/src/thresh.cpp
Added definitions, checks and assertions to help analysis tools.
=> core: issues found by static analysis

modules/features2d/src/kaze/AKAZEFeatures.cpp
replaces abandoned PR #6852
One of functions in AKAZE descriptor has been refactored to squash three similar code blocks into one.
=> AKAZE refactoring: modifications to reduce the code through a loop

modules/core/src/arithm.cpp, modules/core/test/test_arithm.cpp
replaces https://github.com/opencv/opencv/pull/7874
=> resolves https://github.com/opencv/opencv/issues/7792

modules/core/include/opencv2/core/ocl.hpp
resolves part of #7197
Corrected the existing documented T-API functions to match the doxygen format
=> Correct the existing documented T-API functions to match the doxygen format

doc/py_tutorials/py_gui/py_image_display/py_image_display.markdown, doc/py_tutorials/py_gui/py_video_display/py_video_display.markdown
Same as #7241
Addressed some comments from original PR
=> Python tutorials: add inline code backticks

modules/photo/include/opencv2/photo.hpp, modules/photo/src/inpaint.cpp, modules/photo/test/test_inpaint.cpp
replaces #8674 
resolves #4542
=> photo: add support of all types of 1c images in inpaint

modules/imgproc/src/min_enclosing_triangle.cpp
https://github.com/Itseez/opencv/issues/4992
to compare current and fixed results you can use https://github.com/sturkmen72/opencv_samples/blob/master/bugtest_minEnclosingTriangle.cpp
Restored #5331
=> bug fix min_enclosing_triangle.cpp

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/connectedcomponents.cpp, modules/video/include/opencv2/video/background_segm.hpp, modules/video/src/bgfg_KNN.cpp, modules/video/src/bgfg_gaussmix2.cpp
=> Parallel connected components

doc/tutorials/core/mat_operations.markdown, doc/tutorials/introduction/load_save_image/load_save_image.markdown
Change tutorial to use the enum name instead of its value.
=> change tutorial to use enum name instead of value

doc/py_tutorials/py_calib3d/py_calibration/py_calibration.markdown, doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown, doc/py_tutorials/py_core/py_image_arithmetics/py_image_arithmetics.markdown, doc/py_tutorials/py_core/py_optimization/py_optimization.markdown, doc/py_tutorials/py_feature2d/py_brief/py_brief.markdown, doc/py_tutorials/py_feature2d/py_fast/py_fast.markdown, doc/py_tutorials/py_feature2d/py_feature_homography/py_feature_homography.markdown, doc/py_tutorials/py_feature2d/py_surf_intro/py_surf_intro.markdown, doc/py_tutorials/py_gui/py_mouse_handling/py_mouse_handling.markdown, doc/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.markdown, doc/py_tutorials/py_imgproc/py_contours/py_contour_features/py_contour_features.markdown, doc/py_tutorials/py_imgproc/py_contours/py_contours_more_functions/py_contours_more_functions.markdown, doc/py_tutorials/py_imgproc/py_thresholding/py_thresholding.markdown, doc/py_tutorials/py_imgproc/py_transforms/py_fourier_transform/py_fourier_transform.markdown, doc/py_tutorials/py_ml/py_knn/py_knn_opencv/py_knn_opencv.markdown, doc/py_tutorials/py_ml/py_knn/py_knn_understanding/py_knn_understanding.markdown, doc/py_tutorials/py_setup/py_setup_in_fedora/py_setup_in_fedora.markdown, doc/py_tutorials/py_setup/py_setup_in_windows/py_setup_in_windows.markdown
#8808 (partly)
update the python tutorials for python 3, add proper braces around all print statements
=> py_tutorials: add print() braces for python3

modules/objdetect/src/hog.cpp
=> objdetect: fix in SSE code

modules/python/src2/cv2.cpp
=> fixed typo in pyopencv_from Point3d

modules/core/src/convert.cpp, modules/core/src/convert.fp16.cpp, modules/core/src/convert.hpp, modules/core/src/precomp.hpp
- follow the new CPU optimization mode for ```FP16```
=> core: update convertFp16 using CV_CPU_CALL_FP16

modules/calib3d/perf/perf_stereosgbm.cpp, modules/calib3d/src/stereosgbm.cpp
Optimizations trough SIMD operations are added for MODE_HH4 of SGBM.
And also some accuracy and performance tests are added too.
=> Sgbm modehh4 simd

3rdparty/tbb/arm_linux_stub.cpp
resolves #8837
Fix TBB build on ARM.
=> TBB: fix build on ARM

modules/videostab/test/test_main.cpp, modules/videostab/test/test_motion_estimation.cpp, modules/videostab/test/test_precomp.hpp
Add regression tests for videostab module
=> Tests for videostab

modules/core/include/opencv2/core/private.hpp, modules/core/src/lpsolver.cpp, modules/core/src/out.cpp, modules/core/src/precomp.hpp, modules/core/src/system.cpp
See #8771 for details
Should fix VS2013 build.
=> Fixed snprintf for VS 2013

3rdparty/cpufeatures/CMakeLists.txt, 3rdparty/cpufeatures/LICENSE, 3rdparty/cpufeatures/README.md, 3rdparty/cpufeatures/cpu-features.c, 3rdparty/cpufeatures/cpu-features.h, 3rdparty/libwebp/CMakeLists.txt, CMakeLists.txt, modules/core/CMakeLists.txt, modules/core/src/system.cpp
Not for merging.
**WIP**
```
#test_modules=videoio
#tests_filter=OCL.gemm_reuse_D
build_examples=OFF
docker_image-Linux x64=ubuntu:16.04
```
=> For various PR tests

modules/imgproc/src/imgwarp.cpp
Added AVX and SSE4 optimizations to Nearest Neighbor resize implementation
=> AVX and SSE optimizations for resize NN

modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/src/parallel.cpp
this is helper PR for the corresponding PR in opencv_contrib
=> added v_reduce_sum4() universal intrinsic; corrected the number of threads on Mac

modules/core/src/convert.cpp
- resolves #8898 
- there might be a better way to fix, and I'm happy to have discussion
=> core: suppress unreachable code warning

modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/test/test_intrin.cpp
=> build: fix v_reduce_sum4 compilation (requires SSE3)

modules/imgproc/perf/perf_accumulate.cpp
Updated in accordance with comments in #8739
=> Update for accumulate performance test fix

modules/photo/src/denoising.cpp
=> photo: add assertion on empty image in cv::fastNlMeansDenoising

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/include/opencv2/videoio/videoio_c.h, modules/videoio/src/cap.cpp, modules/videoio/src/precomp.hpp
=> video: add a constructor with API preference parameter for VideoWriter

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/calibration.cpp
=> calib3d: add a calibration flag to fix tangential distortion

CMakeLists.txt, cmake/OpenCVDetectMediaSDK.cmake, cmake/OpenCVFindLibsVideo.cmake, cmake/templates/cvconfig.h.in, modules/videoio/CMakeLists.txt, modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap.cpp, modules/videoio/src/cap_mfx_common.cpp, modules/videoio/src/cap_mfx_common.hpp, modules/videoio/src/cap_mfx_reader.cpp, modules/videoio/src/cap_mfx_reader.hpp, modules/videoio/src/cap_mfx_writer.cpp, modules/videoio/src/cap_mfx_writer.hpp, modules/videoio/test/test_mfx.cpp
Adds support to read and write video stream using MediaSDK.
=> MediaSDK initial support

modules/core/src/matrix.cpp, modules/core/test/test_operations.cpp, modules/ts/include/opencv2/ts.hpp, modules/ts/include/opencv2/ts/cuda_test.hpp, modules/ts/include/opencv2/ts/ocl_test.hpp
=> IPP: fix optimization of cv::sortIdx()

CMakeLists.txt, cmake/OpenCVDetectHalide.cmake, cmake/OpenCVUtils.cmake, cmake/templates/cvconfig.h.in, modules/core/CMakeLists.txt
Added looking for Halide library. Require flags `WITH_HALIDE` and `HALIDE_ROOT_DIR`.
If Halide was found, defines `HAVE_HALIDE` to 1. Otherwise defines to 0.
In code we should use `#if HAVE_HALIDE /*...*/ #endif` instead `#ifdef HAVE_HALIDE /*...*/ #endif`.
Installation guide might be found at dnn/tutorials/tutorial_dnn_halide.markdown.
TODO: Change `HALIDE_ROOT_DIR` to something more suitable. It might be `HALIDE_BUILD_DIR`.
=> Added Halide backend support for deep learning layers

cmake/OpenCVModule.cmake
=> cmake: fix typo

modules/highgui/src/cap_avfoundation_mac.mm
=> (2.4) highgui(macos): fix video file reading via AVFoundation

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap.cpp, modules/videoio/src/precomp.hpp
https://github.com/opencv/opencv/commit/f1c16f42b45f93498ed374d5a919c32b0c467fe3#commitcomment-22709617
/cc @PkLab @sovrasov
=> videoio: update VideoWriter apiPreference parameter position

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/include/opencv2/videoio/videoio_c.h, modules/videoio/misc/gen_dict.json, modules/videoio/src/cap.cpp, modules/videoio/src/cap_aravis.cpp, modules/videoio/src/precomp.hpp
Merge after #8984 
Static analyzers doesn't like mixed enum values.
=> videoio: APIs enum refactoring

modules/videoio/src/cap_avfoundation_mac.mm
resolves #8305
Port #8979 (with typo fix #8980)
=> videoio(macosx): fix array access exception in AVFoundation

modules/core/src/trace.cpp
=> Fixed build with enabled OpenVX

modules/core/src/trace.cpp
[Build with warnings](http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV-win32-vc14/builds/10138/)
=> build: eliminate warning

modules/dnn/src/halide_scheduler.cpp, modules/dnn/src/op_halide.cpp, modules/dnn/src/torch/THDiskFile.cpp, modules/dnn/src/torch/THFile.cpp, modules/dnn/src/torch/THFile.h, modules/dnn/src/torch/THGeneral.cpp, modules/dnn/src/torch/THGeneral.h
- winpack
- opencv_world
[Failed nightly build](http://pullrequest.opencv.org/buildbot/builders/master_winpack-build-win64-vc14/builds/10133)
=> dnn: fix winpack build

modules/videoio/src/cap_ffmpeg_impl.hpp
Workaround for crashed test:
```
[ RUN      ] Videoio_Video_parallel_writers_and_readers.accuracy
incorrect codes
*** Error in `/build/precommit_linux64/build/bin/opencv_test_videoio': free(): invalid pointer: 0x00007fc301fdf240 ***
Process returned: -11
```
or
```
[----------] 1 test from Videoio_Video_parallel_writers_and_readers
[ RUN      ] Videoio_Video_parallel_writers_and_readers.accuracy
Process returned: -11
```
Can be reproduced with Ubuntu 14.04 (libav 9.20).
Ubuntu 16.04 (ffmpeg) is fine.
GDB stacktrace:
```
#0  0x00007ffff5fbfc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5fc3028 in __GI_abort () at abort.c:89
#2  0x00007ffff50ed9ab in ?? () from /usr/lib/x86_64-linux-gnu/libavcodec.so.54
#3  0x00007ffff50ee0cc in ?? () from …
```
=> videoio: synchronize ffmpeg open() call

modules/dnn/src/layers/detection_output_layer.cpp, modules/dnn/src/layers/softmax_layer.cpp
Removed usage of std::map in DetectionOutput layer
=> Removed usage of std::map in DetectionOutput layer

modules/highgui/src/window_cocoa.mm
resolves #8885
resolves #8307
This pull request reverts #8307 and #7193. Both only make changes to cocoa_window.mm used for highgui support for Mac OSX/macOS running Cocoa. Though #7193 modernised the code given current objective-C compilers it broke 32-bit OSX support which only supported a legacy objective-C version. PR #8307 attempted to fix this to restore universal compiler support by using #defines to restore legacy code for 32-bit compilers. The 64-bit code was however broken, with the most obvious result being window autosize failed to work (windows remained as only titlebars). This was due to broken references between interface variables such as _image and image, with the non-underscore versions (used by functions such as cvShowImage) remaining null when using the 64-bit flagged …
=> remove ARC and auto synthesize assumptions in cocoa_window.mm

data/haarcascades/haarcascade_frontalcatface.xml, data/haarcascades/haarcascade_frontalcatface_extended.xml, data/haarcascades/haarcascade_smile.xml, data/haarcascades_cuda/haarcascade_smile.xml, data/lbpcascades/lbpcascade_frontalcatface.xml
resolves #8894
As suggested in issue #8894, this solves issues with XML style violation.
=> fixing models to resolve XML violation issue

modules/dnn/src/layers/convolution_layer.cpp
Return `.clone()` call after #9011 changes.
=> Keep origin convolution layer weights for Halide

samples/dnn/googlenet_python.py
Updated python googlenet sample to make it working
=> Fixed python sample for googlenet in dnn

modules/core/src/arithm.cpp, modules/core/test/test_arithm.cpp
=> core: fix infinite recursion in compare

modules/calib3d/src/ap3p.h, modules/calib3d/src/epnp.cpp, modules/calib3d/src/upnp.cpp, modules/core/include/opencv2/core/cvstd.hpp, modules/core/src/matrix.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/permute_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/torch/THDiskFile.cpp, modules/features2d/src/brisk.cpp, modules/imgcodecs/src/bitstrm.cpp, modules/imgproc/src/approx.cpp, modules/imgproc/src/color.cpp, modules/imgproc/src/contours.cpp, modules/imgproc/src/convhull.cpp, modules/imgproc/src/drawing.cpp, modules/imgproc/src/emd.cpp, modules/imgproc/src/histogram.cpp, modules/imgproc/src/thresh.cpp, modules/imgproc/src/undistort.cpp, modules/objdetect/include/opencv2/objdetect/objdetect_c.h, modules/objdetect/src/detection_based_tracker.cpp, modules/objdetect/src/haar.cpp, modules/objdetect/src/hog.cpp, modules/photo/src/fast_nlmeans_denoising_invoker_commons.hpp, modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/src/cap_mjpeg_decoder.cpp
=> Fixed some issues found by static analysis (4th round)

modules/calib3d/src/calibinit.cpp, modules/core/src/datastructs.cpp, modules/core/src/opencl/runtime/opencl_core.cpp, modules/imgproc/src/contours.cpp, modules/imgproc/src/convhull.cpp, modules/imgproc/src/hough.cpp, modules/imgproc/src/precomp.hpp, modules/imgproc/src/templmatch.cpp, modules/objdetect/src/haar.cpp, modules/photo/src/calibrate.cpp
=> Issues found by static analysis (5th round)

modules/imgproc/src/canny.cpp
resolves #8149
Replaces #8341
Related #8352
=> canny: disallow broken inplace arguments

cmake/OpenCVFindMKL.cmake
=> Fix MKL linkage with OpenMP parallel framework

doc/py_tutorials/py_imgproc/py_histograms/py_histogram_equalization/py_histogram_equalization.markdown
=> Fixed minor doc issue

modules/core/include/opencv2/core/version.hpp
=> version 3.3.0-rc

modules/core/src/opencl/runtime/opencl_core.cpp, modules/videoio/src/cap_dshow.cpp
should fix Windows specific issues found by static analysis
=> Fixed several issues found by static analysis (Windows specific)

modules/calib3d/src/calibration.cpp
=> calib3d: fix not working CALIB_FIX_TANGENT_DIST flag

modules/imgproc/src/undistort.avx2.cpp, modules/imgproc/src/undistort.cpp, modules/imgproc/src/undistort.hpp
Moved undistort AVX2 optimizations to separate file
=> AVX optimized implementation of undistort migrated

modules/imgproc/src/corner.avx.cpp, modules/imgproc/src/corner.cpp, modules/imgproc/src/corner.hpp
AVX optimized implementation of Harris corner detector migrated to separate file
=> AVX optimized implementation of Harris corner detector migrated

modules/objdetect/src/haar.avx.cpp, modules/objdetect/src/haar.cpp, modules/objdetect/src/haar.hpp
Haar AVX implementation migrated
=> AVX optimized implementation of haar migrated to separate file

doc/tutorials/features2d/trackingmotion/harris_detector/harris_detector.markdown
=> Fix typo in harris corner detection tutorial.

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/concat_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/test/test_halide_layers.cpp
=> optimize out scaleLayer & concatLayer whenever possible

modules/imgproc/src/imgwarp.avx2.cpp, modules/imgproc/src/imgwarp.cpp, modules/imgproc/src/imgwarp.hpp, modules/imgproc/src/imgwarp.sse4_1.cpp
AVX and SSE4.1 optimizations for resize and warp functions migrated to separate files
=> AVX and SSE4.1 optimized implementation of resize and warp functions migrated

modules/core/src/convert.avx2.cpp, modules/core/src/convert.cpp, modules/core/src/convert.hpp, modules/core/src/convert.sse4_1.cpp
Move AVX and SSE4.1 optimized conversion implementations to separate files
=> AVX and SSE4.1 optimized conversion migrated

modules/imgproc/src/filter.avx2.cpp, modules/imgproc/src/filter.cpp, modules/imgproc/src/filter.hpp
AVX implementation of SIMD row and column processors migrated to separate file
=> AVX optimized implementation of separable filters migrated

modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_halide_nets.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/350
Added tests for ResNet-50 and SqueezeNet v1.1
=> Added tests for ResNet-50 and SqueezeNet v1.1

modules/features2d/src/mser.cpp
The component's history's size is not be updated correctly. see also #8796.
=> fix the MSER history's size issue

3rdparty/carotene/src/channel_extract.cpp, 3rdparty/carotene/src/channels_combine.cpp, 3rdparty/carotene/src/flip.cpp, 3rdparty/carotene/src/resize.cpp, modules/core/src/opengl.cpp, modules/core/src/parallel.cpp, modules/core/src/parallel_pthreads.cpp, modules/core/src/stat.cpp, modules/core/src/system.cpp, modules/core/test/ocl/test_arithm.cpp, modules/features2d/test/ocl/test_brute_force_matcher.cpp, modules/imgcodecs/test/test_tiff.cpp, modules/imgproc/perf/perf_resize.cpp, modules/imgproc/perf/perf_warp.cpp, modules/imgproc/src/filter.cpp, modules/imgproc/src/morph.cpp, modules/imgproc/src/smooth.cpp, modules/imgproc/test/ocl/test_warp.cpp, modules/objdetect/src/detection_based_tracker.cpp, modules/stitching/src/util_log.hpp, modules/ts/include/opencv2/ts/ts_perf.hpp, modules/ts/src/cuda_perf.cpp, modules/ts/src/ts_perf.cpp, modules/video/src/optflowgf.cpp, modules/videoio/src/cap_ffmpeg_impl.hpp
https://sourceforge.net/p/predef/wiki/OperatingSystems
related #9113
=> build: detect Android via '__ANDROID__' macro

3rdparty/cpufeatures/CMakeLists.txt
It is configurable via OPENCV_CPUFEATURES_TARGET_NAME variable
resolves #9155
=> cmake: rename cpufeatures target

3rdparty/ffmpeg/ffmpeg.cmake, 3rdparty/ffmpeg/readme.txt, modules/videoio/test/test_ffmpeg.cpp
- ffmpeg 3.3 -> 3.3.2
- added VERSIONINFO
https://github.com/opencv/opencv_3rdparty/pull/17
resolves #8812
=> ffmpeg: update 3.3.2

modules/features2d/test/test_mser.cpp
Merge after #8910 and with https://github.com/opencv/opencv_extra/pull/351
=> mser: add a couple of new regression tests

modules/imgproc/include/opencv2/imgproc.hpp
Parameters doc of cv::LineSegmentDetector::drawSegments in imgproc/include/opencv2/imgproc.hpp
=> Fix typo in imgproc.hpp

modules/core/include/opencv2/core/mat.hpp
=> core: clarify documentation of cv::Mat::deallocate() method

modules/core/src/convert.cpp, modules/imgproc/src/imgwarp.avx2.cpp, modules/imgproc/src/imgwarp.sse4_1.cpp
=> Fix nightly builds

doc/pattern_tools/gen_pattern.py
=> Fix wrong patterns generation in gen_pattern tool

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/test/test_solvepnp_ransac.cpp
=> calib3d: fix the test fail on Calib3d_SolvePnP.accuracy

modules/dnn/src/precomp.hpp, modules/dnn/src/torch/THDiskFile.cpp
resolves #9193 
resolves #9167
=> dnn: fix build error on Visual Studio 2012

modules/core/include/opencv2/core/cvdef.h
=> build: fix build error on Visual Studio 2012 (C11, initializer_list)

cmake/OpenCVPCHSupport.cmake
=> cmake: fix build with CMake 3.9.0

modules/calib3d/test/test_undistort_points.cpp, modules/core/test/test_eigen.cpp, modules/core/test/test_ippasync.cpp, modules/dnn/test/test_halide_layers.cpp, modules/photo/test/test_hdr.cpp
=> test: remove some rand functions

modules/java/CMakeLists.txt, modules/java/android_test/src/org/opencv/test/OpenCVTestRunner.java, modules/java/generator/src/java/android+OpenCVLoader.java.in, modules/java/generator/src/java/android+sync.py, modules/java/generator/src/java/osgi+OpenCVNativeLoader.java.in, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv-it/src/test/java/org/opencv/osgi/DeployOpenCVTest.java, platforms/maven/opencv/pom.xml, platforms/maven/opencv/scripts/execstack_check, platforms/maven/pom.xml
=> java: update source files processing, maven stuff

modules/core/include/opencv2/core/persistence.hpp, modules/core/src/persistence.cpp, modules/core/test/test_io.cpp
=> Fix persistence format

modules/dnn/src/layers/layers_common.hpp
=> fix linker error when trying CPU_BASELINE=AVX

cmake/OpenCVModule.cmake
=> build: enable __STDC_FORMAT_MACROS macro

CMakeLists.txt, cmake/OpenCVModule.cmake, cmake/OpenCVPCHSupport.cmake, modules/highgui/src/cap_v4l.cpp
- #8345
- #8582
- #8773
- #9216
=> (2.4) Backport changes from master

modules/core/src/persistence.cpp, modules/core/test/test_io.cpp
Parsed JSON nodes were unnamed because of missed flag
=> Fix FileStorage JSON format

modules/core/include/opencv2/core/cvdef.h, modules/core/src/system.cpp
=> core(tls): don't use tlsSlots without synchronization

platforms/maven/opencv/pom.xml, platforms/maven/opencv/scripts/deb_package_check
Resolves #9211 
Updates the package dependencies and allows packages to be marked as optional e.g. python dependencies.
=> Maven build updated package dependency list & package check script.

doc/py_tutorials/py_gui/py_video_display/py_video_display.markdown
Add a list of tested codec's on OSX to python docs.
Also formated inline code.
=> Add tested codecs for OSX to Python Docs

samples/tapi/hog.cpp
The class `App` appears to have two unused methods: `message` and `checkRectSimilarity`. The is no definition or use of either of these methods. This appears to be dead code.
=> Remove unused method declarations in hog.cpp

modules/python/src2/cv2.cpp, modules/python/test/test_stitching.py
=> Python stitching

modules/core/include/opencv2/core/cv_cpu_dispatch.h
=> build: guad for CUDA correctly

modules/calib3d/src/calibration.cpp
about the same speed, but significatly more readable
=> calib3d: rewrite reprojectImageTo3D using Matx expressions

modules/dnn/src/layers/detection_output_layer.cpp, samples/data/dnn/MobileNetSSD_300x300.prototxt, samples/dnn/mobilenet_ssd_python.py, samples/dnn/ssd_mobilenet_object_detection.cpp
Added C++ and python samples for MobileNet-based SSD model
=> MobileNet SSD sample

modules/core/src/ocl.cpp
[Thanks](https://github.com/opencv/opencv/pull/9114/files#diff-ff67959a252bb213e2340f8557e16e84R1354) @pengli
Related: #7894
=> OCL: fix program cache key

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_layers.cpp
=> Added ELU and test for it

modules/core/include/opencv2/core/types.hpp, modules/core/misc/java/src/java/core+Rect.java, modules/core/misc/java/src/java/core+Rect2d.java, modules/core/misc/java/src/java/core+Size.java
=> core: empty() for Rect/Size templates

doc/py_tutorials/py_setup/py_setup_in_fedora/py_setup_in_fedora.markdown
=> A simple spelling change.

modules/features2d/src/kaze/AKAZEFeatures.cpp
Results are not stable with srand()
=> features2d: don't use rand(), because it is not thread-safe

modules/core/include/opencv2/core/utility.hpp, modules/core/src/matrix.cpp, modules/features2d/src/akaze.cpp, modules/features2d/src/kaze/AKAZEFeatures.cpp, modules/features2d/src/kaze/AKAZEFeatures.h, modules/features2d/src/kaze/KAZEFeatures.cpp, modules/features2d/src/kaze/fed.cpp, modules/features2d/src/kaze/nldiffusion_functions.cpp, modules/features2d/src/kaze/utils.h, modules/features2d/test/test_descriptors_invariance.cpp, modules/features2d/test/test_descriptors_regression.cpp, modules/features2d/test/test_detectors_invariance.cpp, modules/photo/src/fast_nlmeans_denoising_opencl.hpp, modules/stitching/perf/perf_stich.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/360
=> AKAZE: update

samples/gpu/super_resolution.cpp
* Remove "simple" flow estimation from help (because it was disabled by 653bca8b)
* Add `flush` after printing iteration number for better UX
=> Minor update for example-gpu-super_resolution

CMakeLists.txt, modules/core/include/opencv2/core/persistence.hpp, modules/imgproc/src/deriv.cpp
=> fix some typos in the documentation.

modules/imgproc/include/opencv2/imgproc.hpp, samples/cpp/warpPerspective_demo.cpp
An example program shows using cv::findHomography and cv::warpPerspective for image warping
based on a sample code http://study.marearts.com/2015/03/image-warping-using-opencv.html
=> New example - warpPerspective_demo.cpp

doc/tutorials/videoio/video-input-psnr-ssim/video_input_psnr_ssim.markdown
resolves #9359: add fix from the issue report
=> fix issue 9359

3rdparty/openexr/CMakeLists.txt
=> cmake: disable HAVE_POSIX_SEMAPHORES on Apple platform

doc/tutorials/highgui/video-input-psnr-ssim/video-input-psnr-ssim.rst
Backport of PR #9367
Resolves #9359
=> backport of PR 9367

modules/highgui/CMakeLists.txt, modules/highgui/misc/java/src/java/highgui+HighGui.java, modules/highgui/misc/java/src/java/highgui+ImageWindow.java
The objective is to:
*Reduce greatly the number of lines of code in the Java codes;
*Make it easy for Java users to add a trackbar and show the results;
*Get the code more similar between C++, Java and Python, making the tutorials more uniform.
=> GSoC - OpenCV Java Highgui Class

modules/highgui/src/window_gtk.cpp, samples/cpp/falsecolor.cpp
- eliminate legacy C code, unused fields
- fix mutex synchronization issues
- set trackbar min/max without unnecessary truncation; allow negative values
=> highgui: refactor GTK backend

samples/cpp/tutorial_code/core/mat_mask_operations/mat_mask_operations.cpp, samples/java/tutorial_code/core/mat_mask_operations/MatMaskOperations.java, samples/python/tutorial_code/core/mat_mask_operations/mat_mask_operations.py
*Fixing typos;
*Making codes more similar to the main one, in C++;
*Adding Grayscale option to the Python and Java codes;
*Fixing python identation, whitespaces and redundancies.
=> GSoC - Improving codes of the tutorial: mat_mask_oprations

modules/highgui/include/opencv2/highgui.hpp
=> fix description of setTrackbarMin

apps/interactive-calibration/CMakeLists.txt, apps/visualisation/CMakeLists.txt
=> cmake: drop INSTALL_NAME_DIR

modules/imgcodecs/src/bitstrm.cpp, modules/imgcodecs/src/bitstrm.hpp, modules/imgcodecs/src/grfmt_bmp.cpp, modules/imgcodecs/src/grfmt_pxm.cpp, modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_grfmt.cpp, modules/imgcodecs/test/test_jpeg.cpp, modules/imgcodecs/test/test_png.cpp, modules/imgcodecs/test/test_read_write.cpp, modules/imgcodecs/test/test_tiff.cpp, modules/imgcodecs/test/test_webp.cpp, modules/ts/src/cuda_test.cpp
resolves #9370
resolves #9371
resolves #9372 
resolves #9311
resolves #9309
=> imgcodecs refactoring

modules/core/include/opencv2/core/core.hpp, modules/core/include/opencv2/core/operations.hpp, modules/highgui/src/bitstrm.cpp, modules/highgui/src/bitstrm.hpp, modules/highgui/src/grfmt_bmp.cpp, modules/highgui/src/grfmt_pxm.cpp, modules/highgui/src/loadsave.cpp
backport #9376
resolves #9370
resolves #9371
resolves #9372 
resolves #9311
resolves #9309
=> (2.4) imgcodecs refactoring

CMakeLists.txt, cmake/OpenCVUtils.cmake, cmake/OpenCVVersion.cmake, modules/core/include/opencv2/core/utility.hpp
=> Improve the documentation.

samples/opengl/CMakeLists.txt
=> apple exclusion

modules/core/src/opencl/runtime/opencl_core.cpp
OpenCL runtime does not require OpenCL development file (libOpenCL.so),
just the "run" library (so.1).
This patch searches for the run library (so.1) if the dev library (.so)
is not found.
Web search shows that this error has been present since at least 2015
http://answers.opencv.org/question/80532/haveopencl-return-false/
Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>
=> ocl: Fix OpenCL library detection in Linux

3rdparty/carotene/src/channel_extract.cpp, 3rdparty/carotene/src/channels_combine.cpp, 3rdparty/carotene/src/colorconvert.cpp, 3rdparty/carotene/src/convert.cpp, 3rdparty/carotene/src/convert_scale.cpp, 3rdparty/carotene/src/gaussian_blur.cpp, 3rdparty/carotene/src/pyramid.cpp, 3rdparty/carotene/src/saturate_cast.hpp, 3rdparty/carotene/src/scharr.cpp
=> carotene: fix Android build with clang

samples/dnn/mobilenet_ssd_python.py, samples/dnn/ssd_mobilenet_object_detection.cpp
resolves https://github.com/opencv/opencv/issues/9322
* Replaced link to `.caffemodel` onto link to the origin repository. Updated default model name.
* Fix packages at python sample.
=> Update MobileNet object detection sample

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp, modules/java/generator/src/cpp/listconverters.cpp, modules/java/generator/src/cpp/listconverters.hpp, samples/dnn/ssd_mobilenet_object_detection.cpp
Added function to get tick counts for layers in model inference
=> Added function to get timings for layers

doc/faq.markdown
adds some real question in FAQ section of documentation
changes can be seen in [preview](http://pullrequest.opencv.org/buildbot/export/pr/9419/docs/d3/d2d/faq.html)
=> documentation_improvement

modules/objdetect/src/hog.cpp
=> Avoid HOGDescriptor with sigma = 0

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
Parse deconvolutional layer from TensorFlow models.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/363
=> Deconvolution layer from TensorFlow

samples/python/asift.py, samples/python/browse.py, samples/python/camshift.py, samples/python/common.py, samples/python/demo.py, samples/python/digits.py, samples/python/digits_video.py, samples/python/find_obj.py, samples/python/gaussian_mix.py, samples/python/lappyr.py, samples/python/letter_recog.py, samples/python/lk_homography.py, samples/python/lk_track.py, samples/python/mosse.py, samples/python/mouse_and_match.py, samples/python/opt_flow.py, samples/python/plane_ar.py, samples/python/squares.py, samples/python/texture_flow.py, samples/python/turing.py
samples/python :
* Unused variables
* Bad indentation
=> GSoC - Improve Samples Python

samples/python/tutorial_code/imgProc/match_template/match_template.py
Fixing Bad indentation. (line 18 to 96)
Adding _ to the unused variables for clarity. (line 77)
=> GSoC - Improving code match_template.py

CMakeLists.txt, modules/core/src/system.cpp
This PR adds a basic Haiku support.
=> Basic Haiku support

modules/highgui/src/window_w32.cpp
Replaces arbitrary position and size snapping by snapping to nearest monitor.
Fixes issue #8840
Windows only.
=> Correctly restore (registry saved) window position on multi-monitor systems. Fixes #8840

modules/core/src/persistence.cpp, modules/core/test/test_io.cpp
=> core: fix FS doesn't close input file after parse error

modules/imgcodecs/src/grfmt_bmp.cpp, modules/imgcodecs/test/test_read_write.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/369
#9376
=> imgcodecs: fix regression 9376

samples/directx/d3dsample.hpp
else none of the directx samples build.
=> fix missing std:: in d3dsample

modules/imgproc/src/opencl/canny.cl
=> OCL: imgproc: eliminate div by zero in Canny

samples/dnn/CMakeLists.txt, samples/dnn/face_detector/.gitignore, samples/dnn/face_detector/deploy.prototxt, samples/dnn/face_detector/how_to_train_face_detector.txt, samples/dnn/face_detector/solver.prototxt, samples/dnn/face_detector/test.prototxt, samples/dnn/face_detector/train.prototxt, samples/dnn/resnet_ssd_face_python.py
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/21
Added model and sample for a face detector. The detector is based on SSD framework with reduced ResNet-10 backbone.
=> Added files for face detector sample

doc/py_tutorials/py_feature2d/py_brief/py_brief.markdown
Corrected the Typo **Hasing** to **Hashing** in second item in Additional Resources section. Also added Wikipedia link for the LSH.
=> Corrected Typo in Additional Resources Section

doc/tutorials/introduction/windows_install/windows_install.markdown
Add another method to build opencv on windows using git-bash and cmake.
=> Another way to build opencv

modules/videoio/src/cap_mfx_common.hpp, modules/videoio/src/cap_mfx_writer.cpp, modules/videoio/test/test_mfx.cpp
Test did not reflect recent _videoio_ modifications, some warnings showed with new compiler.
=> Fixed MediaSDK tests and build warnings

modules/core/test/test_mat.cpp
=> core(test): regression test for 9507

modules/highgui/src/window_QT.cpp
=>  i9403: Removing checks from trackbar min/max set functions.

modules/objdetect/include/opencv2/objdetect/detection_based_tracker.hpp, modules/objdetect/src/detection_based_tracker.cpp
=> objdetect: fix wrong cxx11 features check

modules/core/include/opencv2/core/private.hpp, modules/core/src/copy.cpp, modules/core/src/system.cpp
Compatibility improvement for old IPP versions (tested on 9.0.1 and 2017.0.0);
Manual IPP dispatcher simplification;
=> Compatibility improvement for old IPP versions

modules/ml/src/precomp.hpp
=> ml: disable not implemented k-fold validation in RTrees

modules/objdetect/src/cascadedetect.cpp
=> fixing issue 9583 - issue in cascadeclassifier code clipObjects

modules/python/common.cmake, modules/python/src2/gen2.py
=> export Python signatures information

doc/tutorials/core/adding_images/adding_images.markdown, doc/tutorials/core/basic_geometric_drawing/basic_geometric_drawing.markdown, doc/tutorials/core/discrete_fourier_transform/discrete_fourier_transform.markdown, doc/tutorials/core/mat-mask-operations/mat_mask_operations.markdown, doc/tutorials/core/table_of_content_core.markdown, samples/cpp/tutorial_code/core/AddingImages/AddingImages.cpp, samples/cpp/tutorial_code/core/Matrix/Drawing_1.cpp, samples/cpp/tutorial_code/core/discrete_fourier_transform/discrete_fourier_transform.cpp, samples/java/tutorial_code/core/AddingImages/AddingImages.java, samples/java/tutorial_code/core/BasicGeometricDrawing/BasicGeometricDrawing.java, samples/java/tutorial_code/core/discrete_fourier_transform/DiscreteFourierTransform.java, samples/java/tutorial_code/core/mat_mask_operations/MatMaskOperations.java, samples/python/tutorial_code/core/AddingImages/adding_images.py, samples/python/tutorial_code/core/BasicGeometricDrawing/basic_geometric_drawing.py, samples/python/tutorial_code/core/discrete_fourier_transform/discrete_fourier_transform.py, samples/python/tutorial_code/core/mat_mask_operations/mat_mask_operations.py
Using the java Highgui, toggle buttons and other tools to update the Core tutorials.
Each commit will contain a separate tutorial.
=> GSoC - Updating Core Tutorials

modules/cudafilters/src/filtering.cpp
=> CUDA: cudafilters: don't modify "const" data

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/layers_common.cpp, modules/dnn/src/layers/layers_common.hpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
Dilated convolution from TensorFlow support (`tf.nn.atrous_conv2d`).
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/374
=> Dilated convolution import from TensorFlow

modules/core/include/opencv2/core.hpp
resolves #9629 
Added meaningful doc for cv::PSNR. Makes clear the restrictions on input images.
=> i9629 - Added actual documentation for cv::PSNR function

modules/calib3d/test/test_undistort_points.cpp, modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/undistort.cpp
=> imgproc: add stop criteria tuning in undistortPoints

modules/imgproc/include/opencv2/imgproc.hpp, modules/objdetect/include/opencv2/objdetect.hpp, samples/cpp/facedetect.cpp, samples/cpp/lsd_lines.cpp, samples/cpp/tutorial_code/ImgTrans/Sobel_Demo.cpp
related issue : #9520 
i want to add some more link in [examples page](http://docs.opencv.org/master/examples.html)
for a trial purpose i added related images top of code page. @mshabunin  i am not sure if it is a good idea. what is your opinion?
you can see changes on documentation
[contours2.cpp](http://pullrequest.opencv.org/buildbot/export/pr/9526/docs/d0/d2a/contours2_8cpp-example.html)
[facedetect.cpp](http://pullrequest.opencv.org/buildbot/export/pr/9526/docs/db/d3a/facedetect_8cpp-example.html)
[houghlines.cpp](http://pullrequest.opencv.org/buildbot/export/pr/9526/docs/d2/d7b/houghlines_8cpp-example.html)
[lsd_lines.cpp](http://pullrequest.opencv.org/buildbot/export/pr/9526/docs/d8/dd4/lsd_lines_8cpp-example.html)
[grabcut.cpp](http://pullrequest.opencv.org/buildbot/export/pr/9526/ …
=> improvement on documentation

modules/photo/src/seamless_cloning.cpp
resolves #5045 
The patch is taken from PR #7308.
To pass tests, reference images were updated.
=> Seamless clone: performance fixed

modules/dnn/test/npy_blob.cpp
resolves #9663 
my alternative solution was 76e25b554c4a4f197ffff2065eea45fba7bc104d
=> build: fix build on Visual Studio 2013 and earlier

modules/features2d/include/opencv2/features2d.hpp, modules/features2d/src/keypoint.cpp
to ensure stable output
Needed by opencv/opencv_contrib#1195
=> Add function to sort keypoints that are calculated in parallel

modules/highgui/src/grfmt_bmp.cpp, modules/highgui/src/grfmt_exr.cpp, modules/highgui/src/grfmt_jpeg.cpp, modules/highgui/src/grfmt_jpeg2000.cpp, modules/highgui/src/grfmt_sunras.cpp, modules/highgui/src/utils.cpp, modules/highgui/src/utils.hpp
=> (2.4) imgcodecs: backport 9448 9504

modules/imgproc/src/thresh.cpp, modules/imgproc/test/test_thresh.cpp
Continue PR https://github.com/opencv/opencv/pull/9104.
=> CV_16U images thresholding.

cmake/OpenCVDownload.cmake
Added new "f" flag to the tar unpack, because without it doesn't complete, an compile fails
=> Update OpenCVDownload.cmake unpack option

modules/features2d/src/fast_score.cpp
- switch to universal intrinsic implementation from pure ```SSE2``` implementation
=> features2d: use universal intrinsic in FAST

modules/imgproc/src/phasecorr.cpp, modules/imgproc/test/test_pc.cpp
=> imgproc: use matlab-style fftShift in phaseCorrelate

modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_googlenet.cpp, samples/android/mobilenet-objdetect/src/org/opencv/samples/opencv_mobilenet/MainActivity.java, samples/dnn/caffe_googlenet.cpp, samples/dnn/fcn_semsegm.cpp, samples/dnn/googlenet_python.py, samples/dnn/mobilenet_ssd_python.py, samples/dnn/resnet_ssd_face_python.py, samples/dnn/ssd_mobilenet_object_detection.cpp, samples/dnn/ssd_object_detection.cpp
Resolves #9625 
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1375
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/382
Set swapRB to false in Caffe tests and examples.
=> Set swapRB to false in Caffe tests and examples

modules/imgproc/perf/perf_resize.cpp
Added performance test for resizeNN
=> Added performance test for nearest neighbor resize

modules/imgproc/src/smooth.cpp
- replace raw SSE2/NEON implementation with universal intrinsic
=> imgproc: replace raw SSE2/NEON implementation with universal intrinsic

modules/core/src/arithm.cpp, modules/python/test/test_feature_homography.py, samples/python/plane_tracker.py
Fixes 'boundary' spelling in a couple of comments and error messages.
=> Fixed 'boundary' spelling

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/recurrent_layers.cpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_tf_importer.cpp
LSTM layer from TensorFlow.
Slice layer extension
resolves https://github.com/opencv/opencv/issues/9459
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/368
=> LSTM layer for TensorFlow importer

modules/core/src/arithm.cpp
* remove raw ```NEON```/```SSE2``` implementation as much as possible
* replace them to universal intrinsic in ```InRange```/```Compare```/```AddWeighted```
=> core: use universal intrinsic in arithm.cpp

modules/calib3d/src/fisheye.cpp, modules/core/src/command_line_parser.cpp, modules/core/src/ocl.cpp, modules/stitching/src/exposure_compensate.cpp
**Merge with**: https://github.com/opencv/opencv_contrib/pull/1389
=> build: fix MSVS2017 warning

modules/objdetect/include/opencv2/objdetect.hpp
resolves #4466 #4262
i will try to improve cv::HOGDescriptor documentation using http://docs.opencv.org/2.4/modules/gpu/doc/object_detection.html?highlight=hogdescriptor#gpu::HOGDescriptor
=> Update HOGDescriptor documentation

modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/9755
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/388
=> Fix TensorFlow split layer

modules/dnn/src/caffe/caffe_importer.cpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/scale_layer.cpp, modules/dnn/test/test_caffe_importer.cpp, samples/dnn/colorization.py
Colorization model from https://github.com/richzhang/colorization into DNN.
Source | Gray | Colorized
----------|--------------|------------
=> Deep learning colorization model

samples/dnn/googlenet_python.py, samples/dnn/mobilenet_ssd_python.py, samples/dnn/resnet_ssd_face_python.py
in samples/dnn/mobilenet_ssd_python.py, false should be False
=> in python, false should be False

3rdparty/libjpeg/CMakeLists.txt, modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/videoio/src/cap_dc1394_v2.cpp
- fixed two problems found by static analysis tool (uninitialized data members)
- fixed one problem found by GCC 6.3 (misleading indentation)
- suppressed warnings in libjpeg
=> Issues found by static analysis

modules/core/src/matrix.cpp
#9776 Fix a memory leak in the Mat copying constructor
resolves #9732
=> Port into master 9776

modules/highgui/CMakeLists.txt
=> QT5: fix non-world builds

3rdparty/ffmpeg/ffmpeg.cmake
https://github.com/opencv/opencv_3rdparty/pull/23
#9292
=> ffmpeg: update 3.3.4

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/caffe/caffe_importer.cpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/test/test_layers.cpp
resolves https://github.com/opencv/opencv/issues/9807
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/392
=> PReLU layer from Caffe

CMakeLists.txt, cmake/OpenCVUtils.cmake, cmake/OpenCVVersion.cmake, cmake/templates/OpenCVConfig.cmake.in, modules/core/doc/utility_and_system_functions_and_macros.rst, modules/highgui/CMakeLists.txt, modules/highgui/src/cap_ios_video_camera.mm, modules/highgui/src/grfmt_bmp.cpp
#9421
#9438
#9656
#9726
#9757
#9779
=> (2.4) backport fixes

modules/dnn/src/dnn.cpp
To avoid problem with reduced stack size of inner threads (TBB backend).
```
with_tbb=ON
```
=> dnn(halide): don't compile Halide via parallel_for_()

cmake/OpenCVFindIPPIW.cmake
Fixes OpenCV IW configuration with standalone IPP package.
=> Standalone IPP with IW fix;

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/min_enclosing_triangle.cpp, samples/cpp/minarea.cpp
a small improvement on minEnclosingTriangle
=> Updates min_enclosing_triangle.cpp

modules/dnn/src/layers/softmax_layer.cpp, modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_softmax.cpp, modules/dnn/src/opencl/softmax_loss.cl
dnn(ocl4dnn): support log softmax in ocl4dnn
=> dnn(ocl4dnn): support log softmax in ocl4dnn

modules/core/include/opencv2/core/mat.hpp
Fix a typo in `mat.hpp`. Thanks!
=> Fix typo in mat.hpp

doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown
Fixes some grammatical issues in the python core tutorial.
=> Fix up grammatical errors in python tutorial

modules/calib3d/src/circlesgrid.cpp, modules/calib3d/test/test_chesscorners.cpp, modules/features2d/CMakeLists.txt, modules/features2d/include/opencv2/features2d.hpp, modules/features2d/src/matchers.cpp, modules/features2d/test/test_matchers_algorithmic.cpp, modules/features2d/test/test_nearestneighbors.cpp, modules/stitching/CMakeLists.txt
It will allow to build features2d even if flann module is not available.
=> Made flann dependency for features2d optional

modules/core/src/mathfuncs.cpp
* replace the implementation by universal intrinsic
=> remove raw SSE2/NEON implementation from mathfuncs.cpp

modules/dnn/src/darknet/darknet_io.hpp, modules/dnn/src/layers/eltwise_layer.cpp
Addresses two issues detected by static analysis.
=> Several uninitialized class fields

doc/Doxyfile.in, doc/tutorials/calib3d/camera_calibration/camera_calibration.markdown, doc/tutorials/calib3d/real_time_pose/real_time_pose.markdown, doc/tutorials/core/file_input_output_with_xml_yml/file_input_output_with_xml_yml.markdown, doc/tutorials/core/how_to_scan_images/how_to_scan_images.markdown, doc/tutorials/core/interoperability_with_OpenCV_1/interoperability_with_OpenCV_1.markdown, doc/tutorials/core/mat_the_basic_image_container/mat_the_basic_image_container.markdown, doc/tutorials/gpu/gpu-basics-similarity/gpu_basics_similarity.markdown, doc/tutorials/introduction/display_image/display_image.markdown, doc/tutorials/introduction/windows_install/windows_install.markdown, doc/tutorials/ios/image_manipulation/image_manipulation.markdown, doc/tutorials/ml/non_linear_svms/non_linear_svms.markdown, doc/tutorials/videoio/video-input-psnr-ssim/video_input_psnr_ssim.markdown, doc/tutorials/videoio/video-write/video_write.markdown
To prevent errors like this:
> Mixed Content: The page at 'https://docs.opencv.org/master/d7/d37/tutorial_mat_mask_operations.html' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/7PF1tAU9se4?rel=0'. This request has been blocked; the content must be served over HTTPS.
=> doc: fix youtube videos handling

doc/tutorials/calib3d/camera_calibration/camera_calibration.rst, doc/tutorials/core/file_input_output_with_xml_yml/file_input_output_with_xml_yml.rst, doc/tutorials/core/how_to_scan_images/how_to_scan_images.rst, doc/tutorials/core/interoperability_with_OpenCV_1/interoperability_with_OpenCV_1.rst, doc/tutorials/core/mat-mask-operations/mat-mask-operations.rst, doc/tutorials/core/mat_the_basic_image_container/mat_the_basic_image_container.rst, doc/tutorials/gpu/gpu-basics-similarity/gpu-basics-similarity.rst, doc/tutorials/highgui/video-input-psnr-ssim/video-input-psnr-ssim.rst, doc/tutorials/highgui/video-write/video-write.rst, doc/tutorials/introduction/display_image/display_image.rst, doc/tutorials/introduction/how_to_write_a_tutorial/how_to_write_a_tutorial.rst, doc/tutorials/introduction/windows_install/windows_install.rst, doc/tutorials/ios/image_manipulation/image_manipulation.rst, doc/tutorials/ml/non_linear_svms/non_linear_svms.rst, samples/python2/feature_homography.py, samples/python2/plane_ar.py, samples/python2/plane_tracker.py
=> (2.4) doc: fix youtube videos handling

modules/imgcodecs/src/grfmt_gdal.cpp
=> Updates grfmt_gdal.cpp

CMakeLists.txt
=> cmake: disable generation of pkg-config file during Xcode build

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, platforms/android/build_sdk.py, platforms/android/service/engine/AndroidManifest.xml, platforms/android/service/engine/src/org/opencv/engine/OpenCVEngineService.java, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
Snapshot from 3.x master branch.
=> OpenCV 3.3.1

modules/highgui/src/grfmt_bmp.cpp
=> (2.4) Backport #9903: Fix out of bounds write

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp, modules/dnn/test/test_misc.cpp
=> dnn: handle 4-channel images in blobFromImage

modules/objdetect/src/cascadedetect.hpp
resolves #9925 
Remove double definitions and fix comment.
=> Fix double definitions, correct comment.

doc/py_tutorials/py_objdetect/py_face_detection/py_face_detection.markdown
clarify some passages, fix grammar errors
This PR changes the python tutorial on object (face) detection. It mainly corrects some grammar issues, and clarifies a few wordy passages.
=> copyediting on python object detection tutorial

modules/dnn/src/layers/permute_layer.cpp
Initialize output blobs in permute layer anyway.
=> Fix permute DNN layer

modules/python/src2/cv2.cpp
Added python wrappers for Vec and Matx
=> Python wrappers for Vec and Matx

modules/highgui/src/window_gtk.cpp
=> fix the possible bug for key mapping in Linux GTK library

cmake/OpenCVGenPkgconfig.cmake, cmake/OpenCVModule.cmake, cmake/OpenCVUtils.cmake, doc/CMakeLists.txt
**Merge with**: https://github.com/opencv/opencv_contrib/pull/1418
This feature has not been used for a long time
=> Removed cmake submodules and contrib_world references

modules/dnn/misc/caffe/caffe.pb.cc, modules/dnn/misc/caffe/caffe.pb.h, modules/dnn/src/caffe/caffe.proto, modules/dnn/test/test_caffe_importer.cpp
Ceil mode parameter of pooling layer for Caffe models. DenseNet model test (model that use it).
DenseNet repo: https://github.com/shicai/DenseNet-Caffe
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/397
=> ceil_mode of pooling layer for Caffe models. DenseNet model test.

modules/features2d/src/fast.avx2.cpp, modules/features2d/src/fast.cpp, modules/features2d/src/fast.hpp
AVX2 optimization for FAST corner tracking provided by Victoria Zhislina
=> FAST performance improvement

samples/dnn/resnet_ssd_face.cpp
Translate the Python sample [resnet_ssd_face_python.py](https://github.com/opencv/opencv/blob/master/samples/dnn/resnet_ssd_face_python.py) to C++.
=> Add C++ DNN face detection sample: resnet_ssd_face.cpp

modules/imgproc/src/smooth.cpp
=> imgproc: fix bilateral filter SIMD 32f optimization

doc/py_tutorials/py_video/py_bg_subtraction/py_bg_subtraction.markdown
Fix a couple grammar issues and clarify sentences.
=> fix and clarify several grammar issues

samples/dnn/ssd_mobilenet_object_detection.cpp, samples/dnn/ssd_object_detection.cpp, samples/dnn/yolo_object_detection.cpp
- Add camera/video/image input for C++ DNN object detection samples. 
- Add nice display and computation time.
- Add some information about the default network.
=> Improve C++ DNN object detection samples

doc/tutorials/introduction/windows_visual_studio_Opencv/windows_visual_studio_Opencv.markdown
Fixed my additions. For real this time. I think.
...Hopefully it works this time.
=> Added explanation for new opencv_world.lib file.

doc/tutorials/imgproc/gausian_median_blur_bilateral_filter/gausian_median_blur_bilateral_filter.markdown
resolves #9928
Symbol of variance in the docs.
=> Documentation Update

modules/calib3d/test/test_stereomatching.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/394
This pull request _adds stereomatching tests_ to the master branch for different settings of _StereoBM::minDisparity_.
- An additional parameter, minDisparities, is expected in the StereoBM test cases under opencv_extra/testdata
- The valid disparity region of interest (ROI) for both StereoBM and StereoSGBM is calculated and validated as well.
It requires a corresponding commit in the opencv_extra repository, commit id b201581e5f7bf303df750d8d6242c74ddc703583 (which will be the subject of another pull request, opencv/opencv_extra#394, same branch name, _test_stereo_min_disparity_master_).
This pull request is a follow up to pull request #9816 which fixed issue #9783 and was suggested by @alalek (thanks again).
=> test_stereomatching.cpp: validate min disparity affect on valid ROI

doc/tutorials/calib3d/real_time_pose/real_time_pose.markdown, doc/tutorials/calib3d/table_of_content_calib3d.markdown, modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/calibration.cpp, modules/calib3d/src/fundam.cpp, modules/calib3d/src/ptsetreg.cpp, modules/video/src/lkpyramid.cpp
=> improve doc.

modules/imgproc/src/moments.cpp, modules/imgproc/test/test_moments.cpp
=> OCL: fix moments

modules/dnn/src/op_halide.cpp
resolves https://github.com/opencv/opencv/issues/9982
=> Update Halide code

modules/dnn/src/layers/softmax_layer.cpp
=> dnn(ocl): fix softmax global/local size consistency

modules/core/src/ocl.cpp
=> OCL: verbose API errors

modules/python/src2/gen2.py
Adding python constants and classes to the `pyopencv_signatures.json` file.
=> Const and class to json

doc/tutorials/imgproc/gausian_median_blur_bilateral_filter/gausian_median_blur_bilateral_filter.rst
resolves #9928 
change from **variance** to **standard deviation** 
for 2.4 branch
=> change from variance to standard deviation

doc/js_tutorials/js_core/js_basic_ops/js_basic_ops.markdown
Fix a typo in a sample code that causes syntax error in js_tutorials.
=> Fix typo in js_tutorials

modules/core/include/opencv2/core/core_c.h, modules/core/include/opencv2/core/saturate.hpp, modules/imgproc/include/opencv2/imgproc.hpp, samples/cpp/falsecolor.cpp, samples/cpp/mask_tmpl.cpp
Some improvements on documentation and samples
=> Documentation updates

doc/js_tutorials/js_assets/js_face_detection.html
Fixed a sample code(face detection) embedded in js_tutorials.
=> Fix sample code in js_tutorials

modules/calib3d/include/opencv2/calib3d.hpp, modules/imgproc/include/opencv2/imgproc.hpp, modules/videostab/include/opencv2/videostab/global_motion.hpp, modules/viz/src/widget.cpp
=> Improve Documentation

cmake/OpenCVUtils.cmake
=> (2.4) cmake: fix pkg-config generation for MacOSX

cmake/OpenCVUtils.cmake
=> cmake: fix pkg-config generation for MacOSX

modules/imgproc/src/geometry.cpp
resolves #10044
intersectConvexConvex nested contours check fixed
=> Fix for intersectConvexConvex nested contours check

modules/ml/src/inner_functions.cpp
Improvement (ParallelLoopBody) of calcError function in StatModel
=> Parallel version of calcError in statmodel

modules/core/include/opencv2/core/hal/intrin_cpp.hpp, modules/core/include/opencv2/core/hal/intrin_neon.hpp, modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/include/opencv2/core/hal/intrin_vsx.hpp, modules/core/include/opencv2/core/vsx_utils.hpp, modules/core/test/test_intrin_utils.hpp
=> core(intrinsics): v_load_low

cmake/OpenCVUtils.cmake
As discussed here: https://github.com/opencv/opencv/pull/10048#issuecomment-344644908
=> cmake: fix pkg-config generation for mingw

modules/core/include/opencv2/core/mat.inl.hpp, modules/imgproc/test/test_filter.cpp
=> Test for GaussianBlur with border

modules/core/include/opencv2/core/vsx_utils.hpp
=> core:vsx Fix vec_packs in gcc-5

modules/core/include/opencv2/core/eigen.hpp
=> Eigen: fix Mat construction stride

modules/dnn/src/layers/detection_output_layer.cpp
=> Remove Caffe IO header from layer implementation

modules/core/include/opencv2/core/hal/intrin_sse.hpp, modules/core/include/opencv2/core/hal/intrin_vsx.hpp
=> core: fix compilation of intrinsic code

modules/python/test/test.py
- tests filter
- eliminate .pyc / __pycache__ files
```
```
=> Pytests update

samples/python/calibrate.py
This pull request add threading in the calibration.py sample script. The old script can take a lot of time to be executed on large images.
=> Adding threading in calibrate.py

modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_pool.cpp, modules/dnn/src/opencl/ocl4dnn_pooling.cl
=> dnn(ocl4dnn): refactor pooling

samples/dnn/mobilenet_ssd_accuracy.py, samples/dnn/mobilenet_ssd_python.py
resolves https://github.com/opencv/opencv/issues/10043
Replace general link to TensorFlow model zoo to specific MobileNet-SSD model archive.
There was an update that doesn't change an accuracy of the model but refresh it's serialization.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/406
=> Specify version of MobileNet-SSD from TensorFlow

samples/dnn/torch_enet.cpp
Updated ENet sample:
* Classes names and colors inside a sample.
* Fixed uninitialized segmentation mask
resolves https://github.com/opencv/opencv/issues/10045
=> Update Torch ENet sample

modules/core/include/opencv2/core/utils/filesystem.hpp, modules/core/include/opencv2/core/utils/logger.hpp, modules/core/src/glob.cpp, modules/core/src/ocl.cpp, modules/core/src/utils/filesystem.cpp
=> OCL: drop obsolete cache after upgrade of OpenCL driver

modules/imgproc/src/hal_replacement.hpp, modules/imgproc/src/smooth.cpp
1. Change border type for medianBlur to BORDER_ISOLATED
1. Add hal interface for medianBlur
```
```
=> medianBlur hal

modules/core/src/ocl.cpp
resolves https://github.com/opencv/opencv_contrib/issues/1467
=> OCL: fix null pointer access crash

cmake/OpenCVCompilerOptimizations.cmake
=> cmake: update optimization filter

modules/core/include/opencv2/core.hpp, modules/core/src/algorithm.cpp, modules/features2d/include/opencv2/features2d.hpp, modules/python/test/test_algorithm_rw.py
=> Python: wrap Algorithm::read and Algorithm::write

modules/dnn/misc/caffe/opencv-caffe.pb.cc, modules/dnn/misc/caffe/opencv-caffe.pb.h, modules/dnn/src/caffe/opencv-caffe.proto, modules/dnn/src/init.cpp, modules/dnn/src/layers/prior_box_layer.cpp
* Explicit `width` and `height` attributes of PriorBox layer
* General offsets parameters
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1468
=> Update PriorBox layer

modules/ml/include/opencv2/ml.hpp, modules/ml/src/ann_mlp.cpp, modules/ml/test/test_mltests2.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/409
Add ReLU and LeakyReLU activation function in ml module
=> Add ReLU and LeakyReLU activation function in ml module

modules/imgproc/include/opencv2/imgproc.hpp
resolves #5256
Added `drawContours` interrior filling details description
=> Add more details to drawContour description

modules/core/include/opencv2/core.hpp, modules/ml/src/ann_mlp.cpp
Insert CV_Assert in algorithm::load and mlp::load  to test if file exist.
resolves #10166
=> Try to solve issue 10166

CMakeLists.txt, cmake/OpenCVDetectVTK.cmake, modules/viz/CMakeLists.txt
Check commits messages for details
=> cmake: fix dependencies options

modules/videoio/src/cap_gstreamer.cpp, modules/videoio/test/test_video_io.cpp
```
buildworker:Linux x64 Debug=linux-2
docker_image:Linux x64 Debug=gstreamer:16.04
```
=> Tests for videio backend

modules/core/src/ocl.cpp, modules/core/src/stat.cpp, modules/imgproc/src/morph.cpp, modules/video/src/tvl1flow.cpp
Hopefully, with those changes OCL tests on Mac become "green" again
=> fixed OpenCL functions on Mac, so that the tests pass

modules/cudaarithm/test/test_reductions.cpp, modules/cudev/include/opencv2/cudev/grid/detail/integral.hpp
resolves #7378  and opencv/opencv_contrib#584
```
```
=> Fix CUDA integral

modules/imgproc/perf/perf_blur.cpp, modules/imgproc/src/filter.cpp, modules/imgproc/src/filter.hpp, modules/imgproc/src/hal_replacement.hpp, modules/imgproc/src/smooth.cpp
Add HAL interface for boxFilter and GaussianBlur
Sanity data for boxFilter CV8U to CV16U test  https://github.com/opencv/opencv_extra/pull/405
`test_modules=imgproc`
=> boxFilter and GaussianBlur HAL interface

modules/ts/include/opencv2/ts/ts_ext.hpp, modules/ts/misc/run.py, modules/ts/src/ts.cpp, modules/ts/src/ts_perf.cpp, modules/video/perf/opencl/perf_optflow_pyrlk.cpp, modules/video/test/ocl/test_optflowpyrlk.cpp
=> OCL: skip unstable tests

platforms/ios/build_framework.py, platforms/ios/cmake/Modules/Platform/iOS.cmake
Fix nightly [builds](http://pullrequest.opencv.org/buildbot/builders/master_iOS-mac/builds/10300)
Related #10185
=> build: fix iOS warnings with armv7s, switch precommit armv7 -> armv7s

modules/dnn/perf/perf_net.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp
resolves https://github.com/opencv/opencv/issues/10239
=> Fix conv/deconv layers FLOPS computation

samples/dnn/ssd_mobilenet_object_detection.cpp
=> dnn: add a check for webcam properties in ssd_mobilenet sample

apps/createsamples/utility.cpp
createsamples app utility functions changed to use new C++ OpenCV API instead of old C
=> updated createsamples app utility functions to new c++ API from old c

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/misc/caffe/opencv-caffe.pb.cc, modules/dnn/misc/caffe/opencv-caffe.pb.h, modules/dnn/src/caffe/opencv-caffe.proto, modules/dnn/src/init.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/test/test_layers.cpp
ROIPooling layer from Fast-RCNN topologies, https://github.com/rbgirshick/fast-rcnn.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/416
=> ROIPooling layer

modules/imgproc/src/deriv.cpp, modules/imgproc/src/hal_replacement.hpp, modules/imgproc/src/pyramids.cpp
Call HAL for:
* Sobel and Scharr filters
* pyrDown
=> HAL for Sobel, Scharr and pyrDown

doc/tutorials/dnn/dnn_googlenet/dnn_googlenet.markdown, samples/dnn/squeezenet_halide.cpp, samples/dnn/ssd_object_detection.cpp, samples/dnn/tf_inception.cpp, samples/dnn/torch_enet.cpp, samples/dnn/yolo_object_detection.cpp
resolves https://github.com/opencv/opencv/issues/9967
changed comments related to blobfromimage() in ssd_object_detection sample of DNN. Implemented associated preprocessing steps within blobfromimage().
=> added preprocessing in blobFromImage for SSD

modules/core/include/opencv2/core/ocl.hpp, modules/core/src/ocl.cpp, modules/core/src/ocl_deprecated.hpp, modules/core/test/ocl/test_opencl.cpp, samples/tapi/opencl_custom_kernel.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/415
Added low-level API to support OpenCL binary programs.
`allow_multiple_commits=1`
=> OCL: refactor Program API

cmake/OpenCVGenConfig.cmake, modules/calib3d/src/calibinit.cpp, modules/core/include/opencv2/core/base.hpp, modules/core/include/opencv2/core/hal/interface.h, modules/core/include/opencv2/core/softfloat.hpp, modules/core/src/command_line_parser.cpp, modules/core/src/glob.cpp, modules/core/src/lda.cpp, modules/core/src/matrix.cpp, modules/core/src/ocl.cpp, modules/core/src/persistence.cpp, modules/core/src/system.cpp, modules/core/src/umatrix.cpp, modules/imgcodecs/src/bitstrm.cpp, modules/imgcodecs/src/exif.cpp, modules/imgcodecs/src/grfmt_bmp.cpp, modules/imgcodecs/src/grfmt_pam.cpp, modules/imgcodecs/src/grfmt_pxm.cpp, modules/imgcodecs/src/grfmt_sunras.cpp, modules/imgcodecs/src/loadsave.cpp, modules/imgproc/src/color.cpp, modules/imgproc/src/contours.cpp, modules/objdetect/src/detection_based_tracker.cpp, modules/objdetect/src/hog.cpp, modules/videoio/src/cap.cpp
- allow to disable exceptions in some modules
- support building with [newlib](https://sourceware.org/newlib/)
Modules relying on RTTI and/or exceptions more heavily:
```
-DBUILD_opencv_java=OFF \
-DBUILD_opencv_python2=OFF \
-DBUILD_opencv_python3=OFF \
-DBUILD_opencv_dnn=OFF \
-DBUILD_opencv_ml=OFF \
-DBUILD_opencv_flann=OFF \
-DBUILD_opencv_shape=OFF \
-DBUILD_opencv_videostab=OFF \
```
=> Build for embedded systems

3rdparty/protobuf/src/google/protobuf/stubs/port.h, doc/tutorials/dnn/dnn_javascript/dnn_javascript.markdown, doc/tutorials/dnn/table_of_content_dnn.markdown, modules/dnn/CMakeLists.txt, modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/lrn_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/js/src/core_bindings.cpp, modules/js/src/embindgen.py, platforms/js/build_js.py, samples/dnn/js_face_recognition.html
=> JavaScript bindings for dnn module

modules/core/include/opencv2/core/softfloat.hpp, modules/core/src/softfloat.cpp, modules/core/test/test_math.cpp
Added implementation of softdouble rounding to int64_t and test for rounding and saturation_cast to int and int64
=> Implementation of softdouble rounding to int64_t

modules/dnn/src/layers/max_unpooling_layer.cpp
=> dnn: dump error information

modules/core/misc/java/test/CoreTest.java, modules/core/src/lapack.cpp, modules/core/test/test_eigen.cpp, modules/core/test/test_mat.cpp
CPU: Intel i7 6700k
Eigen version: 3.3.2
Memory: 16GB
With master
Core_Eigen.vector_32: ~1024ms
Core_Eigen.vector_64: ~1512ms
With my branch
Core_Eigen.vector_32: ~62ms
Core_Eigen.vector_64: ~91ms
```
```
=> Use Eigen::SelfAdjointEigenSolver in cv::eigen

CMakeLists.txt
=> (2.4) cmake: update timestamp status

modules/core/test/test_io.cpp
resolves #10254
```
force_builders=ARMv8
```
=> core(test): avoid filename duplicates in tests

modules/core/src/copy.cpp
=> core: fix copyTo(with mask) dst initialization

3rdparty/libpng/CMakeLists.txt, 3rdparty/libpng/powerpc/filter_vsx_intrinsics.c, 3rdparty/libpng/powerpc/powerpc_init.c, cmake/OpenCVDetectCXXCompiler.cmake
=> 3rdparty:libpng Add missing support for PowerPC/VSX

modules/core/include/opencv2/core/hal/intrin_vsx.hpp, modules/core/include/opencv2/core/vsx_utils.hpp
- fix conversion intrinsics compatibility with xlc
- implement odd-elements 2 to 4 conversion intrinsics
- improve implementation of universal intrinsic v_popcount
````
````
=> core:ppc Fix several issues for VSX

modules/dnn/src/layers/max_unpooling_layer.cpp
Related: #10147
**WIP**
```
```
=> dnn: more debug information

apps/createsamples/createsamples.cpp, apps/createsamples/utility.cpp
resolves #10267
adds command-line option -rngseed
replaces rand() -> theRNG()
*WIP*
```
```
=> Update createsamples app

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/misc/caffe/opencv-caffe.pb.cc, modules/dnn/misc/caffe/opencv-caffe.pb.h, modules/dnn/src/caffe/opencv-caffe.proto, modules/dnn/src/init.cpp, modules/dnn/src/layers/blank_layer.cpp, modules/dnn/src/layers/detection_output_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/src/layers/proposal_layer.cpp, modules/dnn/test/test_layers.cpp, samples/dnn/faster_rcnn.cpp
origin: https://github.com/rbgirshick/py-faster-rcnn
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/419
VGG16 model:
ZF model:
=> Faster-RCNN object detection model

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/imgproc/src/smooth.cpp
- uninitialized class fields
- missing NULL check
- invalid memory access
=> Fixed issues found by static analysis

modules/core/src/kmeans.cpp, samples/cpp/kmeans.cpp
=> kmeans: number of channels in _centers fixed

modules/ml/include/opencv2/ml.hpp, modules/ml/src/ann_mlp.cpp, modules/ml/test/test_mltests2.cpp, samples/cpp/travelsalesman.cpp
Move SimulatedAnnealingSolver::Impl in cpp file. Fix also some typos.
I use this [PImpl idiom](http://en.cppreference.com/w/cpp/language/pimpl) as reference.
My apologies if it breaks something.
related #10213
=> Move SimulatedAnnealingSolver::Impl in cpp file

3rdparty/libtiff/CMakeLists.txt, cmake/OpenCVModule.cmake, cmake/OpenCVUtils.cmake, modules/python/bindings/CMakeLists.txt
resolves #10035
resolves #10327
resolves https://github.com/opencv/opencv_contrib/issues/1485
```
build_world:Custom=ON
```
=> CMake fixes

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/java/generator/src/java/android+OpenCVLoader.java.in, platforms/android/build_sdk.py, platforms/android/service/engine/AndroidManifest.xml, platforms/android/service/engine/src/org/opencv/engine/OpenCVEngineService.java, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
=> OpenCV version++ (3.4.0-rc)

3rdparty/libtiff/CMakeLists.txt, 3rdparty/libtiff/snprintf.c
close   #10342 
- fix compilation error about "inline"
- fix linker error about "_TIFF_snprintf_f"
=> fix compilation error on Visual Studio 2013 and earlier

modules/imgproc/src/canny.cpp, modules/imgproc/src/hal_replacement.hpp
1. Add HAL for Canny
1. Fix work with submat - it always processed like isolated mat.
=> HAL for Canny

modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp, modules/dnn/src/opencl/conv_layer_spatial.cl, modules/dnn/src/opencl/prior_box.cl, modules/dnn/test/test_tf_importer.cpp
with depthwise convolution kernel, we can dramatically improve mobilenet ssd performance
```
```
=> add ocl accleration for prior box layer and depthwise convolution

modules/core/include/opencv2/core/version.hpp
=> (2.4) OpenCV version++ (2.4.13.5)

modules/ml/src/ann_mlp.cpp, modules/ml/src/inner_functions.cpp
Solves #10110
delete some useless coments in ANN_MLPImpl::settrainmethod
=> Calcerror uses now weighted samples

modules/dnn/include/opencv2/dnn/dnn.hpp
Changed wrapping mode for cv::dnn::Net::forward to avoid conflicts in python wrappers
=> Changed wrapping mode for dnn::Net::forward

modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp, modules/dnn/src/opencl/conv_layer_spatial.cl
=> update dnn convolution auto-tuning

modules/video/perf/opencl/perf_bgfg_mog2.cpp
* close #10349 
* confirmed test failure on Jetson TX1 and TX2
=> remove the test which is too strict

cmake/OpenCVCompilerOptions.cmake, modules/cudalegacy/test/NCVTest.hpp, modules/features2d/src/agast.cpp, modules/features2d/src/agast_score.cpp, modules/features2d/src/fast.cpp, modules/imgcodecs/src/grfmt_jpeg.cpp, modules/imgproc/src/canny.cpp, modules/ts/include/opencv2/ts.hpp, modules/ts/include/opencv2/ts/ts_gtest.h, modules/videoio/src/cap_ffmpeg_impl.hpp, modules/videoio/src/cap_msmf.hpp
* specify warning in CMake, not int the code using pragma
```
force_builders=Win64 MSVS2017
```
=> clean up the code

modules/dnn/src/darknet/darknet_io.cpp, modules/dnn/src/layers/region_layer.cpp
=> Refactor NMS procedure at RegionLayer

samples/gpu/super_resolution.cpp
resolves #10380 
add a check for the mandatory inputVideoName
=> samples: check for valid input in gpu/super_resolution.cpp

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/10235
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/424
=> TensorFlow weights dequantization

modules/ml/include/opencv2/ml.hpp, modules/ml/include/opencv2/ml/ml.inl.hpp, modules/ml/src/ann_mlp.cpp, samples/cpp/travelsalesman.cpp
- no need to wrap it into cv::Algorithm
- it uses custom non-cv::Mat objects (optimization system)
=> ml: simplify interfaces of SimulatedAnnealingSolver

modules/dnn/src/dnn.cpp, modules/dnn/test/test_layers.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/425
=> Limit Concat layer optimization

modules/core/src/matmul.cpp
=> (2.4 backport) Fixed #10433

doc/py_tutorials/py_feature2d/py_surf_intro/py_surf_intro.markdown, doc/py_tutorials/py_video/py_bg_subtraction/py_bg_subtraction.markdown
* ```createBackgroundSubtractorMOG()``` and ```createBackgroundSubtractorGMG()``` belong to class ```bgsegm```
https://docs.opencv.org/master/d2/dce/bgsegm_8hpp.html
* Use ```setExtended()``` to set attribute value
https://docs.opencv.org/master/d5/df7/classcv_1_1xfeatures2d_1_1SURF.html#a2809dee4e7cc6979b5d1e7523f73c075
=> Fix some documentation errors

modules/video/src/opencl/bgfg_mog2.cl
=> Optimize OpenCL BackgroundSubstractionMOG2

cmake/OpenCVCompilerOptimizations.cmake, cmake/checks/cpu_avx512skx.cpp, modules/core/include/opencv2/core/cv_cpu_dispatch.h, modules/core/include/opencv2/core/cv_cpu_helper.h, modules/core/include/opencv2/core/cvdef.h, modules/core/src/system.cpp, modules/dnn/CMakeLists.txt, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/layers_common.simd.hpp
Added "AVX512_SKX" (Skylake-X with AVX-512F/CD/BW/DQ/VL) optimization option.
Related #10416
Related #8974
=> cmake(opt): AVX512_SKX

samples/cpp/stitching.cpp
It resolves #10461 .   
Here **\n (newline)** is added so that **shell prompt** goes in the next line . 
@eugaz and @alalek Kindly review it .
=> Updating stiching.cpp to resolve new line issue #10461

modules/imgproc/src/rotcalipers.cpp
It resolves #10096 .
Updating the **comment** section of **rotcalipers.cpp** file .
@suijingfeng  @paroj  Kindly review it .
=> Updating comment of rotcalipers.cpp to resolve issue #10096

samples/dnn/ssd_mobilenet_object_detection.cpp
resolves https://github.com/opencv/opencv/issues/10482
=> Update C++ MobileNet-SSD object detection sample

samples/dnn/yolo_object_detection.cpp
Added style in the Yolo drawing.
Example below:
=> add style draw in yolo

modules/dnn/src/layers/proposal_layer.cpp, samples/dnn/resnet_ssd_face.cpp
=> add ocl implementation of proposal layer

modules/video/src/bgfg_KNN.cpp
Change from rand() to randu() outside the loop so it can be parallelized now.
=> Parallelization of BackgroundSubtractorKNN

modules/imgcodecs/src/grfmt_pam.cpp, modules/imgproc/src/thresh.cpp, modules/python/bindings/CMakeLists.txt
=> Eliminate build warnings

samples/dnn/caffe_googlenet.cpp
This pullrequest changes
Path to label name file can be give using command line
=> Add a parameter labels to command line

modules/core/include/opencv2/core.hpp, modules/core/include/opencv2/core/affine.hpp, modules/core/include/opencv2/core/matx.hpp
[Demo](http://pullrequest.opencv.org/buildbot/export/pr/10527/docs/dd/d99/classcv_1_1Affine3.html#details)
=> Improve the documentation for cv::Affine3.

modules/features2d/src/blobdetector.cpp
RGBA images are not accepted by BLOB!
- Converts RGBA to GRAY
=> BLOB - Support RGBA

modules/java/generator/src/java/android+AsyncServiceHelper.java, modules/java/generator/src/java/android+StaticHelper.java
Bitwise "and false" is always false.
=> Bitwise "and false"

modules/dnn/CMakeLists.txt, modules/dnn/src/dnn.cpp
replaces REUSE_DNN_MEMORY compile-time option
related #10439
=> dnn: add OPENCV_DNN_DISABLE_MEMORY_OPTIMIZATIONS runtime option

modules/dnn/misc/caffe/opencv-caffe.pb.cc, modules/dnn/misc/caffe/opencv-caffe.pb.h, modules/dnn/src/caffe/opencv-caffe.proto
resolves https://github.com/opencv/opencv/issues/10530
=> Replace Caffe's psroi_pooling_param tag from 10001 to 10002

samples/dnn/yolo_object_detection.cpp
I posted this patch for when we need it shows the result of processing.
=> Save video file

modules/calib3d/src/calibration.cpp
resolves #10519
Added assertion to fail if (count == 3 && !useExtrinsicGuess)
Removed condition count < 4 when useExtrinsicGuess == false
=> Issue10519

modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/blank_layer.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
=> ocl path for eltwise layer, normalize_bbox layer and batch_norm layer

modules/imgcodecs/src/bitstrm.cpp, modules/imgcodecs/src/grfmt_bmp.cpp, modules/imgcodecs/src/grfmt_pam.cpp, modules/imgcodecs/src/grfmt_sunras.cpp, modules/imgcodecs/src/precomp.hpp, modules/imgcodecs/src/utils.cpp
=> imgcodecs: replace assert() calls, add overflow checks

modules/imgcodecs/src/grfmt_jpeg2000.cpp
=> imgcodecs: add more Jasper checks for supported and tested cases

apps/createsamples/utility.cpp
resolves #10551
Fixed evaluation of ROI for extraction of generated distorted sample
=> Fixed createsample app exception

modules/core/src/utils/filesystem.cpp
=> core: fix unresolved symbols from utils::fs

modules/flann/src/miniflann.cpp
resolves #10548
- Prevent the user from using kNN values larger than the dataset size
=> `FLANN::knnSearch` kNN assertion

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/test/test_caffe_importer.cpp
=> Wrap UMat dnn blobs

modules/core/src/hal_replacement.hpp, modules/core/src/stat.cpp, modules/core/test/test_arithm.cpp
1. Add HAL for minMaxIdx
1. Add accuracy test for minMaxLoc `8UC1`
=> HAL for minMaxIdx

modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/dnn.cpp, modules/dnn/test/test_misc.cpp
Let call `blobFromImage` with pre-allocated blob.
=> dnn::blobFromImage with OutputArray

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/scale_layer.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_layers.cpp
resolves https://github.com/opencv/opencv/issues/10382
=> Untrainable version of Scale layer from Caffe

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/src/drawing.cpp
Adding a function to compute font scale for a desired font height in pixels
=> Added getFontScaleFromHeight()

3rdparty/protobuf/CMakeLists.txt, CMakeLists.txt, cmake/OpenCVCompilerOptions.cmake, modules/calib3d/src/fisheye.cpp, modules/core/include/opencv2/core/base.hpp, modules/core/src/array.cpp, modules/core/src/dxt.cpp, modules/features2d/src/agast.cpp, modules/imgcodecs/src/exif.cpp, modules/imgproc/src/deriv.cpp, modules/imgproc/src/morph.cpp, modules/imgproc/src/resize.cpp
resolves #10168
- fixes _CV_Assert_ macro for static analyzers
- disabled one warning in protobuf library
- added [ThinLTO](https://clang.llvm.org/docs/ThinLTO.html) compilation option
- some minor issues
```
```
=> A bunch of minor modifications

modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/layers/mvn_layer.cpp, modules/dnn/src/opencl/activations.cl, modules/dnn/src/opencl/batchnorm.cl, modules/dnn/src/opencl/mvn.cl, modules/dnn/test/test_layers.cpp
new layers including : mvn layer,  power layer , tanh layer and channels ReLU layer
also update batch_norm layer with a new ocl kernel.
```
```
=> ocl support for new layers in dnn module

modules/calib3d/src/precomp.hpp, modules/core/include/opencv2/core.hpp
- [Before change][1]
- [After change][2]
[1]: https://docs.opencv.org/master/d2/de8/group__core__array.html#gaa9d88dcd0e54b6d1af38d41f2a3e3d25
[2]: http://pullrequest.opencv.org/buildbot/export/pr/10609/docs/d2/de8/group__core__array.html#ga6847337c0c55769e115a70e0f011b5ca
=> Improve the documentation for cv::completeSymm.

modules/calib3d/src/ptsetreg.cpp
=> fix issue #10612.

modules/highgui/include/opencv2/highgui.hpp, modules/highgui/include/opencv2/highgui/highgui_c.h, modules/highgui/src/precomp.hpp, modules/highgui/src/window.cpp, modules/highgui/src/window_QT.cpp, modules/highgui/src/window_QT.h, modules/highgui/src/window_carbon.cpp, modules/highgui/src/window_cocoa.mm, modules/highgui/src/window_gtk.cpp, modules/highgui/src/window_w32.cpp, modules/highgui/test/test_gui.cpp
Add read only property retrieval (window width, height, position x and y) for enhanced rendering capabilities and more sophisticated research tools
=> Update to add window position and size retrieval to HighGUI

modules/video/src/bgfg_gaussmix2.cpp
resolves #10525
Do the UMat check on the output, not the input.
I am not sure if this is the best solution.
=> Fix #10525

modules/highgui/src/window_QT.cpp, modules/highgui/src/window_QT.h, modules/highgui/test/test_gui.cpp
resolves #10648
resolves https://github.com/opencv/opencv_contrib/issues/1529
Resolves QT issue introduced from previous PR.
=> Fix for QT image window rectangle

modules/imgproc/src/fixedpoint.inl.hpp, modules/imgproc/src/smooth.cpp, modules/imgproc/test/test_smooth_bitexact.cpp
bit-exact implementation of gaussianBlur smoothing
=> bitexact gaussianblur implementation

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/fundam.cpp, modules/calib3d/src/rho.h, modules/core/include/opencv2/core.hpp
=> Improve the doc for fundamental matrix.

modules/core/include/opencv2/core/mat.hpp, samples/cpp/tutorial_code/snippets/core_mat_checkVector.cpp
- [before change][1]
- [after change][2]
[1]: https://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#a167a8e0a3a3d86e84b70e33483af4466
[2]: http://pullrequest.opencv.org/buildbot/export/pr/10635/docs/d3/d63/classcv_1_1Mat.html#a167a8e0a3a3d86e84b70e33483af4466
=> Improve the doc for cv::Mat::checkVector.

modules/features2d/include/opencv2/features2d/hal/interface.h, modules/features2d/src/fast.cpp, modules/features2d/src/hal_replacement.hpp
Add HAL interface for FAST algorithm for corner detection. Call only for FAST_9_16 and threshold <= 20.
=> add HAL for FAST

samples/python/tutorial_code/ml/py_svm_opencv/hogsvm.py
I was trying hogsvm tutorial with python3 and it wasn't working well. Here are necessary changes. 
I have added list() call to map() to be able run tutorial with python3.
```
-hogdata = [map(hog,row) for row in deskewed]
+    hogdata = [list(map(hog,row)) for row in deskewed]
```
I have also added if __main__ and corresponding whitespaces:
```
if __name__ == "__main__":
```
please use "git diff -w" to see changes without whitespaces.
=> hogsvm compatibility with python3

cmake/OpenCVFindLAPACK.cmake, cmake/checks/lapack_check.cpp, modules/core/src/hal_internal.cpp
resolves #10668
/cc @nightsparc
=> core(lapack): fix build issues related to 'extern "C"'

doc/py_tutorials/py_core/py_image_arithmetics/py_image_arithmetics.markdown
a small error in file name in python tutorial https://docs.opencv.org/master/d0/d86/tutorial_py_image_arithmetics.html bitwise operation
resolves #10670
=> bad image file

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/mvn_layer.cpp, modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp, modules/dnn/src/opencl/conv_layer_spatial.cl, modules/dnn/src/opencl/mvn.cl
=> layer fusion patches for dnn module

modules/core/perf/perf_math.cpp, modules/core/src/kmeans.cpp
- Update perf tests (commit 1)
- Add nstripes (task granularity) parameter (commit 2)
```
```
=> core: fix kmeans multi-threading performance

modules/ts/misc/run.py, modules/ts/misc/run_android.py, modules/ts/misc/run_long.py, modules/ts/misc/run_suite.py, modules/ts/misc/run_utils.py
- fixed run.py execution when Java has been disabled during build
- removed complex functionality from run.py - long test log names, passing multiple build directories
- fixed PEP8 warnings
=> run.py improvements

modules/calib3d/include/opencv2/calib3d.hpp, modules/calib3d/src/calibration.cpp, modules/calib3d/test/test_cameracalibration.cpp
- allow CALIB_USE_EXTRINSIC_GUESS
- returns per view errors
TODO:
=>  calib3d: add stereoCalibrateExtended

modules/core/src/parallel.cpp
such that OpenCV's num threads setting only affects OpenCV.
```
```
=> Use Intel TBB's task arena if possible

modules/dnn/src/layers/mvn_layer.cpp
=> dnn(ocl): fix build options for Apple OpenCL

modules/core/src/parallel_impl.cpp
=> Add yield support for powerpc

modules/features2d/src/fast.cpp
=> features2d: fix build error on Visual Studio 2013 and earlier

modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/test/test_tf_importer.cpp
* Test for Inception v2 SSD from https://github.com/tensorflow/models/tree/master/research/object_detection
* Fix average pooling normalization for layers from TensorFlow. In case of AVE pooling with padding Caffe and Torch averages by kernel area so zero padding is used. However TensorFlow divides on number of real elements.
Close issues with retrained MobileNet-SSD and Inception v2 SSD models from TensorFlow because now it's usage question and each model is tested. Wiki: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API .
resolves https://github.com/opencv/opencv/issues/9977
resolves https://github.com/opencv/opencv/issues/10431
resolves https://github.com/opencv/opencv/issues/10601
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/433
=> Fix padding for average pooling from TensorFlow

modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/mvn_layer.cpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/opencl/eltwise.cl, modules/dnn/src/opencl/mvn.cl, modules/dnn/src/opencl/slice.cl, modules/dnn/test/test_layers.cpp
=> dnn patches for slice, eltwise  and mvn layer

modules/dnn/src/ocl4dnn/src/math_functions.cpp
resolves https://github.com/opencv/opencv/issues/10731
=> ocl4dnnGEMV in case of row_size < 4

modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
PR fixes 4-dimensional slice layer from TensorFlow
resolves https://github.com/opencv/opencv/issues/10739
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/436
=> Fix slice layer from TensorFlow

modules/dnn/test/test_caffe_importer.cpp
Tests for Faster-RCNN and RFCN networks.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/435
=> Faster-RCNN and RFCN tests

modules/features2d/include/opencv2/features2d.hpp, modules/features2d/src/orb.cpp
Fix for #10690 review comments
=> Fixed assertion in ORB::setFirstLevel()

modules/js/CMakeLists.txt
=> js: filterout OpenCL headers

modules/video/perf/opencl/perf_bgfg_knn.cpp, modules/video/src/bgfg_KNN.cpp, modules/video/src/opencl/bgfg_knn.cl
Add bgfg_knn.cl.
Work in progress.
TODO:
=> Add ocl version BackgroundSubtractorKNN

modules/core/include/opencv2/core/vsx_utils.hpp
=> core:ppc Fix compile issue with Eigen

modules/imgproc/test/test_histograms.cpp
* Tests added for issue #10687 fixed in #10688 (3+ dimensions are checked now in all interfaces)
* Obsolete types (like `IplImage*` and `CvMat*`) are not used anymore
=> Histogram tests updated

platforms/scripts/valgrind.supp
[Validated](http://pullrequest.opencv.org/buildbot/builders/master_valgrind-lin64-debug/builds/10072).
=> valgrind: update suppression rules

samples/dnn/tf_text_graph_ssd.py
Tool to generate a text graph for SSD models from TensorFlow Object Detection framework
Wiki: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API
=> Tool to generate text graphs for SSD models from TensorFlow

modules/viz/include/opencv2/viz/types.hpp
=> Fix issue #10781

samples/dnn/colorization.cpp, samples/dnn/colorization.py
add a cpp counterpart for the colorization.py sample, also fix some links in the python script
=> dnn: add colorization.cpp

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/src/opencl/slice.cl
=> dnn slice layer ocl update and fix for potential vector access violation

modules/dnn/test/test_caffe_importer.cpp, samples/dnn/js_face_recognition.html
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/438
=> FP16 OpenCV face detection network

modules/core/src/parallel_impl.cpp
Resolves assertion: `CV_Assert(threads[i]->job.empty());`
Related: #10691
```
```
=> core: parallel_for() update

cmake/OpenCVDetectInferenceEngine.cmake, modules/dnn/perf/perf_net.cpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/batch_norm_layer.cpp, modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_tf_importer.cpp
best observed time at 300x300 input images:
| Default OpenCV backend | Inference Engine @ OpenCV |  Inference Engine with Model Optimizer, standalone application |
|-----|-----|-----|
| 14.57ms | 11.49ms (x1.27) |  11.8972ms | 
L2-normalization layer from the model has default backend implementation.
=> OpenCV face detection network using Inference Engine backend

cmake/OpenCVDetectVTK.cmake, modules/calib3d/src/homography_decomp.cpp, modules/viz/include/opencv2/viz.hpp, modules/viz/include/opencv2/viz/types.hpp, modules/viz/include/opencv2/viz/viz3d.hpp, modules/viz/include/opencv2/viz/vizcore.hpp, modules/viz/include/opencv2/viz/widgets.hpp, modules/viz/src/clouds.cpp, modules/viz/src/vizcore.cpp, modules/viz/src/vtk/vtkCloudMatSink.h, modules/viz/src/vtk/vtkVizInteractorStyle.hpp, modules/viz/src/widget.cpp
=> improve the doc for the viz module.

modules/viz/src/vizimpl.cpp
resolves #9387 
resolves #9575.
=> fix issue #9387 and #9575

modules/viz/src/widget.cpp
=> Fix issue 10827.

modules/viz/src/widget.cpp
=> Fix issue 10826.

modules/viz/src/widget.cpp
resolves #9486
resolves #10829
=> fix issue #9486 and #10829.

modules/core/include/opencv2/core/cuda.hpp
Updated documentation for BufferReader with some example code.
=> Update BufferReader documentation with some example code

modules/core/src/system.cpp
=> core: generalize and fix x86 'cpuid' calls

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/mvn_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/10702
* Fixed bugs in deconvolution layer imported from TensorFlow.
* import batch normalization with mean-variance normalization from TensorFlow.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/440
=> Fix bugs in layers imported from TensorFlow

modules/core/src/persistence.hpp
=> fix build error on Visual Studio 2013 and earlier

modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp
=> Add const getInputsInfo method for Inference Engine network class

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/detection_output_layer.cpp, modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/src/opencl/detection_output.cl, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_tf_importer.cpp
=> Fixes for tensorflow MobileNetSSD ocl test

samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src/main_detection.cpp
=> fix tutorial on real time pose estimation

modules/calib3d/src/rho.cpp, modules/calib3d/src/rho.h, modules/core/include/opencv2/core/cvdef.h, modules/core/include/opencv2/core/softfloat.hpp, modules/core/src/persistence.hpp, modules/dnn/src/precomp.hpp, modules/imgcodecs/src/exif.cpp, modules/imgcodecs/src/exif.hpp, modules/imgproc/src/drawing.cpp
=> build: portable integer types

modules/core/src/parallel_impl.cpp
resolves #10881 
```
force_builders=ARMv7,ARMv8,Custom
```
=> core: fix parallel_for() data race

samples/cpp/bgfg_segm.cpp
- use `<iostream>` instead of _printf_
- moved mask smoothing option to interactive loop
- minor code refactoring
=> Samples: reworked bgfg_bgsegm

modules/core/test/test_io.cpp
resolves #10894 
same approach as #8671
=> core: fix test error on VS2013

modules/dnn/test/test_tf_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/442
=> Fix DNN flatten test

include/opencv2/opencv.hpp
=> add missing DNN header to opencv2/opencv.hpp

modules/highgui/src/bitstrm.cpp, modules/highgui/src/grfmt_bmp.cpp, modules/highgui/src/grfmt_jpeg2000.cpp, modules/highgui/src/grfmt_pxm.cpp, modules/highgui/src/grfmt_sunras.cpp, modules/highgui/src/precomp.hpp, modules/highgui/src/utils.cpp
backport #10369 (issue #10351)
backport #10563 (issue #10540) 
backport #10566 (issue #10541)
```
```
=> (2.4) backport imgcodecs fixes

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/elementwise_layers.cpp, modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp, modules/dnn/src/opencl/activations.cl, modules/dnn/src/opencl/conv_layer_spatial.cl
include relu6 ocl kernel and layer fusion support
=> ReLU6 layer ocl support

modules/ml/test/test_mltests2.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/443
Resolves test [timeout](http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV_noSSE-win64-vc14-debug/builds/10376) issue:
- split test by method parameters
- reduce train data size
[Validated](http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV_noSSE-win64-vc14-debug/builds/10378/steps/test_ml/logs/stdio).
=> ml: refactor ML_ANN test

modules/features2d/src/blobdetector.cpp
=> (port #10695): Add mask support to SimpleBlobDetector

modules/imgcodecs/src/grfmt_tiff.cpp
resolves #10703
Fixed vertical flipping of image in case it is required by orientation flag
=> Fix for vertically flipped tiff files reading

modules/core/perf/perf_mat.cpp, modules/core/src/copy.cpp
- replace raw intrinsics with universal intrinsics in copy.cpp
````
````
=> core: replace raw intrinsics with universal intrinsics in copy.cpp

modules/java/jar/CMakeLists.txt
about "BYPRODUCTS bin/opencv-340.jar"
=> cmake: fix Ninja warning

modules/imgcodecs/src/grfmt_base.cpp, modules/imgcodecs/src/grfmt_base.hpp, modules/imgcodecs/src/grfmt_tiff.cpp, modules/imgcodecs/src/grfmt_tiff.hpp, modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_tiff.cpp
resolves #8729
The old PR #8913 re-created, merge conflicts are fixed
=> imwrite multipage TIFF files

apps/createsamples/utility.cpp
=> createsamples: fix ROI in icvGetBackgroundImage()

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_tf_importer.cpp
=> Fix for tensorflow ocl testcase of MobileNetSSD and Inception_v2_SSD

modules/dnn/misc/face_detector_accuracy.py, modules/dnn/misc/quantize_face_detector.py, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
Face detection TensorFlow graph.
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/444
https://github.com/opencv/opencv_3rdparty branch: https://github.com/dkurt/opencv_3rdparty/commit/8033c2bc31b3256f0d461c919ecc01c2428ca03b
Accuracy metrics (the higher the better):
Caffe model accuracy (FDDB dataset, 300x300 inputs):
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.408
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.849 (target metric)
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.251
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.050
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.381
Average Precision  (AP) @[ IoU=0.50:0.95 | …
```
=> Face detection TensorFlow model

3rdparty/ffmpeg/ffmpeg.cmake
FFmpeg: 3.3.4 -> 3.4.2
LibVPX: 1.6.1 -> 1.7.0
OpenH264: 1.6.0 -> 1.7.0
```
buildworker:Win64=windows-2
buildworker:Win32=windows-2
buildworker:Win64 MSVS2017=windows-1
```
=> ffmpeg: update wrapper

modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_pool.cpp, modules/dnn/src/opencl/ocl4dnn_pooling.cl
support the padded area control in ave pooling
=> ave pooling ocl fix

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/test/test_tf_importer.cpp
=> deconvolution ocl fix

doc/tutorials/dnn/dnn_android/dnn_android.markdown, doc/tutorials/introduction/cross_referencing/tutorial_cross_referencing.markdown, modules/core/include/opencv2/core/version.hpp, modules/dnn/include/opencv2/dnn/dnn.hpp, platforms/android/build_sdk.py, platforms/android/service/engine/AndroidManifest.xml, platforms/android/service/engine/src/org/opencv/engine/OpenCVEngineService.java, platforms/android/service/readme.txt, platforms/maven/opencv-it/pom.xml, platforms/maven/opencv/pom.xml, platforms/maven/pom.xml
**DO NOT MERGE**
closes #10524
=> OpenCV version++ (3.4.1)

modules/dnn/src/layers/pooling_layer.cpp, modules/imgcodecs/src/grfmt_tiff.cpp
- missing TIFFClose
- implicit check in PoolingLayer
=> Fixed two issues found by static analysis

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp, modules/dnn/src/opencl/conv_layer_spatial.cl, modules/dnn/test/test_tf_importer.cpp
=> ocl4dnn: Fix SAME padding mode for convolve

3rdparty/protobuf/README.md
=> 3rdparty: fix protobuf version in README file

modules/dnn/src/caffe/caffe_io.cpp, modules/dnn/src/layers/layers_common.cpp, modules/dnn/src/ocl4dnn/include/common.hpp, modules/dnn/src/ocl4dnn/include/math_functions.hpp, modules/dnn/src/ocl4dnn/include/ocl4dnn.hpp, modules/dnn/src/op_halide.hpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/src/tensorflow/tf_io.cpp, modules/dnn/test/npy_blob.cpp, modules/dnn/test/npy_blob.hpp
- don't use in header files
- use it in all .cpp files
=> dnn: fix precomp.hpp usage

modules/photo/src/npr.cpp
Speedup npr functions by cleaning them of useless initializations.
=> clean npr functions of useless initializations (speed-up)

modules/imgproc/src/smooth.cpp
* avoid aggressive optimization on Visual Studio 2012 Update 5
resolves #11004
=> imgproc: let the test OCL_Filter/Bilateral pass

modules/photo/src/contrast_preserve.cpp, modules/photo/src/contrast_preserve.hpp
- Replaced `vector.push_back` into `vector.resize()` and `vector[i] = foo;` to improve performance.  In my environment it is accelerated by 30 to 50%.
- Removed redundant variable initialization
=> Optimize decolor in photo

modules/videoio/src/cap_v4l.cpp
resolves #10927
mainloop_v4l2 function returns -1 in case of timeout
=> Fix improper return code in case of timeout

modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/layers/lrn_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp, modules/dnn/src/layers/softmax_layer.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_caffe_importer.cpp, modules/dnn/test/test_googlenet.cpp, modules/dnn/test/test_precomp.hpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
* Replace `OCL_*` dnn tests to parametric tests.
* Fix SoftMax layer in case of OpenCL target and batch size changing.
resolves #10970
```
```
=> Parametric OpenCL deep learning tests

modules/photo/src/contrast_preserve.cpp, modules/photo/src/contrast_preserve.hpp, modules/photo/test/test_decolor.cpp
- refactored using ReSharper C++
- https://github.com/opencv/opencv/pull/10997#discussion_r172544613
- https://github.com/opencv/opencv/pull/10997#discussion_r172548335
- https://github.com/opencv/opencv/pull/10997#discussion_r172550501
=> Refactor decolor

modules/calib3d/src/ap3p.cpp
=> calib3d: avoid clang weird behavior

cmake/OpenCVCompilerDefenses.cmake, modules/core/include/opencv2/core/utils/filesystem.private.hpp, modules/core/src/parallel.cpp, modules/core/src/utils/filesystem.cpp, modules/videoio/src/cap_ffmpeg_impl.hpp
Basic Haiku OS support
Recipe already here:
https://github.com/haikuports/haikuports/pull/2281
=> Haiku supporting patches

modules/dnn/src/layers/lrn_layer.cpp, modules/dnn/test/test_googlenet.cpp
Add dummy input initialization at test.
related #11102
=> Fix #11102

modules/imgproc/src/min_enclosing_triangle.cpp
resolves #11116
Updated handling of collinear edges while searching for intersection.
=> Relaxed requirements to determinant magnitude in intersection check

modules/calib3d/src/ap3p.cpp
- close #11135
- apply workaround to correct range
=> calib3d: fix #11135

modules/core/include/opencv2/core/private.cuda.hpp, modules/cudaarithm/src/reductions.cpp, modules/cudaimgproc/src/histogram.cpp, modules/cudaimgproc/test/test_histogram.cpp
=> cudaarithm: make the asynchronous call to NPP safe

cmake/OpenCVModule.cmake
resolves #11172
related #11112
=> cmake: add module/src include dir in case of enabled precompiled headers

modules/core/src/persistence_c.cpp, modules/core/test/test_io.cpp
Check file size when FileStorage::APPEND mode is used and add signature when size is empty
resolves #11156
=> Solves #11156

modules/imgcodecs/src/loadsave.cpp, modules/imgcodecs/test/test_read_write.cpp
=> fix cv::imwrite to allow cv::UMat and vectors of it to be written

modules/videoio/src/cap_dshow.cpp
A fix for silent failures when getting and setting properties on capture devices. When a device doesn't support a property, the calls would fail silently (indicating success) and return junk values (in the case of getProperty()).
Moreover, an unsuccessful call to getVideoSettingFilter() inside getProperty() would cause property processing to incorrectly fall through to getVideoSettingCamera() due to missing switch statement breaks in getProperty().
=> [videoio / dshow] Fix for silent failures in getting and setting properties

samples/directx/d3d10_interop.cpp, samples/directx/d3d11_interop.cpp, samples/directx/d3d9_interop.cpp, samples/directx/d3d9ex_interop.cpp, samples/opengl/opengl_interop.cpp, samples/winrt/FaceDetection/FaceDetection/MainPage.xaml.cpp, samples/winrt/OcvImageProcessing/OcvImageProcessing/MainPage.xaml.cpp, samples/winrt_universal/PhoneTutorial/MainPage.xaml.cpp, samples/wp8/OcvImageManipulation/PhoneXamlDirect3DApp1/PhoneXamlDirect3DApp1Comp/Direct3DInterop.cpp, samples/wp8/OcvRotatingCube/PhoneXamlDirect3DApp1/PhoneXamlDirect3DApp1Comp/Direct3DInterop.cpp, samples/wp8/OpenCVXaml/OpenCVComponent/OpenCVComponent.cpp
=> samples: avoid using of legacy C-like API (part 2)

modules/highgui/src/window_QT.h, samples/opengl/opengl_interop.cpp
related #11093 #11189 
```
docker_image:Custom=qt:16.04
```
=> fix build issues with QT/OpenGL

samples/cpp/gstreamer_pipeline.cpp
```
docker_image:Linux x64 Debug=gstreamer:16.04
```
=> Create sample for gstreamer pipeline

samples/cpp/tutorial_code/viz/histo3D.cpp
=> samples: avoid using of legacy code constructions in viz sample

modules/dnn/test/test_torch_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/451
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1599
=> Update Torch testdata

modules/dnn/misc/face_detector_accuracy.py, samples/dnn/CMakeLists.txt, samples/dnn/README.md, samples/dnn/face_detector/opencv_face_detector.pbtxt, samples/dnn/js_face_recognition.html
* 2.7MB face detection network.
* Fix link to fp16 version at JavaScript tutorial sample. (issue https://github.com/opencv/opencv/issues/10965).
=> Put OpenCV face detection network into source tree

modules/core/src/matrix_expressions.cpp, modules/core/test/test_mat.cpp
resolves #9720
・resolves #9720
・add test code later.
=> Resolves #9720

modules/python/src2/cv2.cpp
Add missing DECREFs
resolves #11205
=> Solves #11205

modules/core/src/arithm_simd.hpp
=> core: fix AVX2 "min" implementation

CMakeLists.txt, modules/videoio/src/cap.cpp, modules/videoio/src/cap_msmf.cpp, modules/videoio/test/test_video_io.cpp
Fixed race condition and extended a set of supported formats for VideoCapture
Fixed top-bottom row ordering for VideoWriter
=> Update for MSMF-based VideoCapture and VideoWriter

modules/ml/src/knearest.cpp
Instead of doing bubble sort, this pullrequest uses the **std:sort**  O(n. log n) algorithm
=> Adds efficient sort algorithm to KNearest

modules/core/src/parallel.cpp, modules/core/test/test_misc.cpp
Unhandled exceptions in worker threads cause app crashes:
- std::threads: crash
- Linux pthreads: crash
- MacOS X GCD: crash
- TBB: propagated by backend
- Win32 Concurrent: propagated by backend
```
```
=> core: parallel_for() propagate exception

modules/python/src2/cv2.cpp
Keep track of past callback parameters and DECREF them when not needed anymore.
resolves #11206
=> Solves #11206

modules/core/src/convert.cpp
resolves https://github.com/opencv/opencv/issues/10965
```
```
=> Fix convertFp16 in JavaScript build

modules/videoio/src/cap_msmf.cpp
MSMF-based VideoCapture reworked to use SourceReader to support simultaneously reading of several files
=> MSMF-based VideoCapture reworked to use SourceReader

modules/photo/src/seamless_cloning.cpp
resolves #10627
Fixed mask reduction in seamless_clone.
Renamed a few variables to make the code more obvious.
=> Fixed mask reduction in seamless_clone

modules/core/include/opencv2/core/utility.hpp, modules/core/misc/java/src/java/core+Core.jcode.in, modules/core/misc/java/test/CoreTest.java, modules/core/src/system.cpp, modules/core/test/test_misc.cpp
Added four functions returning library version information in runtime.
=> Added interface to check library version during runtime

modules/core/test/test_misc.cpp
with implementation of functions with multiple output formats
related https://github.com/opencv/opencv/pull/11108/commits/6ffaae9c3b0dc74ef7113ec4065601e2eb8cfa05
=> core: test-sample for FIXED_TYPE demonstration

apps/traincascade/boost.cpp, cmake/OpenCVDetectTBB.cmake, modules/core/CMakeLists.txt, modules/core/include/opencv2/core/private.hpp, modules/imgproc/src/histogram.cpp, modules/videoio/src/cap_openni.cpp, modules/videoio/src/cap_openni2.cpp
Coupled with opencv/opencv_contrib#1604
Removed TBB from all modules dependencies, only _core_ module depends on TBB now. All direct calls to TBB have been removed.
Notes:
* OpenNI 1&2 has been built with TBB support but not tested
* calcHist performance has decreased for 2d and 3d cases
=> Reduced direct TBB dependencies

modules/imgproc/src/color_lab.cpp, modules/videoio/src/cap_msmf.cpp, modules/videoio/src/cap_msmf.hpp
with 'CL=/permissive-'
resolves #11281
[Errors example](http://pullrequest.opencv.org/buildbot/builders/precommit_windows64-vc15/builds/330).
=> build: fix MSVS build problems

modules/dnn/src/dnn.cpp, modules/dnn/test/test_layers.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/456
```
buildworker:Linux x64=linux-1
```
=> Fix multiple inputs models from Intel's Model Optimizer

modules/imgproc/src/fixedpoint.inl.hpp, modules/imgproc/src/smooth.cpp
Reworked evaluation of bit-exact GaussianBlur to improve performance for generic kernel size
=> Bit-exact GaussianBlur performance update

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/misc/quantize_face_detector.py, modules/dnn/src/layers/normalize_bbox_layer.cpp, modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp, samples/dnn/face_detector/opencv_face_detector.pbtxt
related https://github.com/opencv/opencv/issues/11223
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/454
=> Fuse tf.nn.l2_normalize layer

cmake/templates/cvconfig.h.in, doc/tutorials/gpu/gpu-basics-similarity/gpu_basics_similarity.markdown, modules/dnn/src/caffe/opencv-caffe.proto, modules/imgproc/src/deriv.cpp
* use correct name for NVIDIA
* remove "NVidia" and "Nvidia"
* keep the letters for API
=> typo: not nVidia nor NVidia, but NVIDIA

modules/core/include/opencv2/core/private.hpp, modules/imgproc/src/smooth.cpp
=> imgproc(ipp): disable parallel GaussianBlur

modules/dnn/test/test_caffe_importer.cpp
resolves #11293
```
buildworker:Linux x64=linux-3
buildworker:Linux x64 Debug=linux-3
```
=> dnn(test): update error tolerance for RCNN/RFCN tests

modules/dnn/include/opencv2/dnn/shape_utils.hpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/pooling_layer.cpp
resolves https://github.com/opencv/opencv/issues/11318
=> Fix bugs found by valgrind

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/11356
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/463
```
```
=> Fuse deconvolution layer subgraphs from Keras

modules/highgui/src/cap_ffmpeg_impl.hpp
Backport of https://github.com/opencv/opencv/pull/10011.
CC @jviney @alalek
RE: https://github.com/opencv/opencv/pull/10011#issuecomment-383283372
Ref: https://github.com/Homebrew/homebrew-core/pull/26882
=> Fix build with FFmpeg 4.0

cmake/OpenCVDetectInferenceEngine.cmake, modules/dnn/perf/perf_net.cpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/prior_box_layer.cpp, modules/dnn/src/op_inf_engine.cpp, modules/dnn/test/test_backends.cpp
Enable Intel Inference Engine's OpenCL fp16 target for some of models:
| | CPU | OpenCL GPU, fp32 | OpenCL GPU, fp16 |
|----|----|---|---|
| GoogLeNet | 8.88ms | 17.06ms | 12.50ms |
| ResNet-50 | 19.66ms | 42.60ms | 29.35ms |
| SqueezeNet v1.1 | 2.43ms | 5.66ms | 4.73ms |
CPU: Intel&reg; Core&trade; i7-6700K CPU @ 4.00GHz x 8
GPU: Intel&reg; HD Graphics 530 (Skylake GT2)
=> Enable some tests for clDNN plugin from Intel's Inference Engine

modules/core/src/system.cpp
=> core: disable errors dump

modules/python/src2/cv2.cpp
=> python: fix support of UI callbacks

modules/videoio/include/opencv2/videoio.hpp, modules/videoio/src/cap.cpp, modules/videoio/src/cap_xine.cpp, modules/videoio/src/precomp.hpp, modules/videoio/test/test_video_io.cpp
Depends on opencv/opencv_extra#462
* Refactored cap_xine.cpp to use C++ interface
* YV12 format stated by XINE seems to be I420 format (https://www.fourcc.org/pixel-format/yuv-i420/)
* Added two new test bunny videos containing raw streams encoded with H264 and H265 codecs (see corresponding opencv_extra PR)
=> Refactored XINE video backend

modules/core/include/opencv2/core/private.cuda.hpp, modules/core/src/cuda_gpu_mat.cpp, modules/core/src/cuda_host_mem.cpp, modules/core/src/cuda_info.cpp, modules/core/src/cuda_stream.cpp, modules/core/src/gl_core_3_1.cpp, modules/core/src/opengl.cpp, modules/stitching/src/blenders.cpp, modules/stitching/src/timelapsers.cpp, modules/stitching/src/warpers_cuda.cpp, modules/superres/src/btv_l1_cuda.cpp, modules/superres/src/frame_source.cpp, modules/superres/src/optical_flow.cpp, modules/videostab/src/global_motion.cpp, modules/videostab/src/inpainting.cpp
=> build: unreachable code after CV_Error()

modules/core/include/opencv2/core/hal/intrin_sse.hpp
Improved performance of `v_load_deinterleave()` and `v_store_interleave()` intrinsics on 8-bit 3-channel data when using SSSE3 instruction set. `v_load_deinterleave()` is ~1.5x faster, `v_store_interleave()` is up to 2x faster.
Requires `-DCPU_BASELINE=SSSE3` (or `-DCPU_BASELINE=SSE4_1` or `-DCPU_BASELINE=SSE4_2`)
=> Faster interleave deinterleave

modules/video/src/ecc.cpp
=> tab to space

modules/core/include/opencv2/core.hpp, modules/core/include/opencv2/core/base.hpp, modules/core/src/check.cpp, modules/core/src/opengl.cpp, modules/core/src/persistence.cpp, modules/core/src/system.cpp, modules/dnn/include/opencv2/dnn/dnn.inl.hpp, modules/highgui/src/window.cpp
=> core: drop cv::errorNoReturn()

modules/core/src/norm.cpp, modules/core/test/test_arithm.cpp
resolves #11399
Condition:
- AVX2
- sz.width < 16
```
```
=> ipp: disable normL1(a, b, mask) 16UC3

cmake/OpenCVDetectCUDA.cmake, modules/core/src/cuda_gpu_mat.cpp, modules/videoio/src/cap_openni2.cpp
=> build warnings

modules/imgproc/src/clahe.cpp, modules/imgproc/src/opencl/clahe.cl
* avoid the race condition in the reduce
* resolves #11408
=> Arm: fix the test failure of OCL_Imgproc/CLAHETest.Accuracy on ODROID-XU4

modules/core/src/convert_scale.cpp, modules/core/test/test_arithm.cpp
=> Solves #6125

doc/tutorials/core/interoperability_with_OpenCV_1/interoperability_with_OpenCV_1.markdown
resolves #11429
- An spelling error.
=> fix spelling error

samples/cpp/tutorial_code/dnn/custom_layers.cpp
=> samples: add C++11 override to virtual methods

modules/core/include/opencv2/core/hal/intrin_vsx.hpp, modules/core/test/test_intrin_utils.hpp, modules/photo/test/test_hdr.cpp
=>  core:ppc Several improvements on VSX(2)

doc/tutorials/dnn/dnn_yolo/dnn_yolo.markdown, samples/dnn/object_detection.cpp, samples/dnn/openpose.cpp, samples/dnn/segmentation.cpp
=> Select the device (video capture) in DNN

modules/stitching/include/opencv2/stitching/detail/blenders.hpp
=> cuda: fix build error of sample

modules/imgproc/src/color_hsv.cpp
I add universal intrinsics for HLS2RGB_f.
<br>
```
```
<br>
Intel measurement result
<tr><th>dstcn</th><th>n</th><th>Average Clocks (original code)</th><th>Average Clocks (new code)</th><th>Faster Rate (compared with original code)</th></tr>
<tr><td>3</td><td>24</td><td>940.2</td><td>741.4</td><td>126.8%</td></tr>
<tr><td>3</td><td>48</td><td>1834.0</td><td>1399.8</td><td>131.0%</td></tr>
<tr><td>3</td><td>72</td><td>2642.4</td><td>2129.2</td><td>124.1%</td></tr>
<tr><td>4</td><td>24</td><td>1006.0</td><td>749.0</td><td>134.3%</td></tr>
<tr><td>4</td><td>48</td><td>1900.0</td><td>1459.2</td><td>130.2%</td></tr>
<tr><td>4</td><td>72</td><td>2780.4</td><td>2143.8</td><td>129.7%</td></tr>
</table>
Measurement …
=> add universal intrinsics for HLS2RGB_f

samples/dnn/tf_text_graph_ssd.py
resolves https://github.com/opencv/opencv/issues/11455
=> Update script to generate MobileNet-SSD V2 text graph

CMakeLists.txt, cmake/FindFlake8.cmake, modules/dnn/misc/quantize_face_detector.py, modules/dnn/test/imagenet_cls_test_alexnet.py, modules/dnn/test/pascal_semsegm_test_fcn.py, modules/ts/misc/table_formatter.py, modules/ts/misc/testlog_parser.py, platforms/android/build_sdk.py, samples/python/deconvolution.py
resolves #11469
```
linter_checks=check_pylint,check_flake8
buildworker:Docs=linux-2
```
=> Check flake8

samples/cpp/gstreamer_pipeline.cpp
```
docker_image:Linux x64 Debug=gstreamer:16.04
docker_image:Custom=gstreamer:14.04
```
=> Remove command line argument related to container

samples/cpp/openni_capture.cpp
instead of an ad-hoc implementation of it
=> samples: openni_capture - use COLORMAP_JET for depth visualization

modules/core/src/cuda_stream.cpp
=> cuda: avoid unnecessary cudaStreamSynchronize() call

3rdparty/libtiff/CMakeLists.txt
related to #10344
- Revert the accidentally slipped in Tab
=> typo: remove Tab

modules/dnn/src/dnn.cpp
related #11493 
* fix Test_TensorFlow_layers.batch_norm
* fix Test_TensorFlow_layers.pooling
* let OpenCL kernel run only on Intel GPU
* BTW, probably this PR will conflict with #11397.  I won't mind solving the conflict after #11397 is merged.
=> dnn: work around of the test failure of opencv_test_dnn

modules/videoio/src/cap.cpp, modules/videoio/src/cap_ffmpeg.cpp, modules/videoio/src/precomp.hpp
VideoCapture and VideoWriter FMPEG backend updated to use C++ interface (IVideoCapture)
```
docker_image:Custom=ffmpeg-master
```
=> FFMPEG-based VideoCapture and VideoWriter backend changed to C++ interface

modules/photo/src/seamless_cloning_impl.cpp, modules/photo/test/test_cloning.cpp
- allow 5% of changed pixels with intensity difference <= 1
resolves #11518
```
```
=> photo(test): update test checks

doc/tutorials/dnn/dnn_custom_layers/dnn_custom_layers.md, modules/dnn/include/opencv2/dnn/dnn.hpp, modules/dnn/src/nms.cpp, modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp, modules/imgproc/src/intersection.cpp, modules/imgproc/test/test_intersection.cpp, samples/dnn/custom_layers.hpp, samples/dnn/text_detection.cpp
Added sample with deep learning text detection using EAST: An Efficient and Accurate Scene Text Detector.
paper: https://arxiv.org/abs/1704.03155v2
implementation: https://github.com/argman/EAST
* Move custom layers samples from `samples/cpp/tutorial_code/dnn/custom_layers.cpp` to `samples/dnn/custom_layers.hpp`
* Non-maximum suppression for rotated rectangles
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/467
```
```
=> Deep learning text detection sample 

modules/dnn/test/test_tf_importer.cpp
- make green Linux debug/Linux32/Win32 builders
=> dnn(text): update check threshols

modules/ts/misc/run.py
to allow pass `--test_bigdata` via run.py
```
```
=> ts: run.py passthrough --test_* args "as is"

modules/dnn/misc/python/pyopencv_dnn.hpp, modules/dnn/src/dnn.cpp, modules/dnn/src/layers/recurrent_layers.cpp, modules/dnn/src/ocl4dnn/src/math_functions.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_tf_importer.cpp, modules/imgproc/src/color.hpp, modules/imgproc/test/test_intersection.cpp
- ~block using of "rand()" in OpenCV tests (we want reproducible tests)~ - **postponed due requirement of contrib refactoring**
- replaced rand() calls to cv::theRNG()
- non initialized members/ variables
- unused return values
- missing/useless NULL checks
=> Fix issues reported by static code analysers

modules/imgproc/include/opencv2/imgproc.hpp, modules/imgproc/perf/perf_houghcircles.cpp, modules/imgproc/perf/perf_houghlines.cpp, modules/imgproc/src/hough.cpp, modules/imgproc/test/test_houghcircles.cpp, modules/imgproc/test/test_houghlines.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/460
resolves #4303
```
opencv_extra=hough4303
```
=> Resolves #4303

doc/tutorials/imgproc/histograms/back_projection/back_projection.markdown, doc/tutorials/imgproc/histograms/histogram_calculation/histogram_calculation.markdown, doc/tutorials/imgproc/histograms/histogram_comparison/histogram_comparison.markdown, doc/tutorials/imgproc/histograms/histogram_equalization/histogram_equalization.markdown, doc/tutorials/imgproc/imgtrans/warp_affine/warp_affine.markdown, doc/tutorials/imgproc/table_of_content_imgproc.markdown, samples/cpp/tutorial_code/Histograms_Matching/EqualizeHist_Demo.cpp, samples/cpp/tutorial_code/Histograms_Matching/calcBackProject_Demo1.cpp, samples/cpp/tutorial_code/Histograms_Matching/calcBackProject_Demo2.cpp, samples/cpp/tutorial_code/Histograms_Matching/calcHist_Demo.cpp, samples/cpp/tutorial_code/Histograms_Matching/compareHist_Demo.cpp, samples/cpp/tutorial_code/ImgTrans/Geometric_Transforms_Demo.cpp, samples/java/tutorial_code/Histograms_Matching/back_projection/CalcBackProjectDemo1.java, samples/java/tutorial_code/Histograms_Matching/back_projection/CalcBackProjectDemo2.java, samples/java/tutorial_code/Histograms_Matching/histogram_calculation/CalcHistDemo.java, samples/java/tutorial_code/Histograms_Matching/histogram_comparison/CompareHistDemo.java, samples/java/tutorial_code/Histograms_Matching/histogram_equalization/EqualizeHistDemo.java, samples/java/tutorial_code/ImgTrans/warp_affine/GeometricTransformsDemo.java, samples/python/tutorial_code/Histograms_Matching/back_projection/calcBackProject_Demo1.py, samples/python/tutorial_code/Histograms_Matching/back_projection/calcBackProject_Demo2.py, samples/python/tutorial_code/Histograms_Matching/histogram_calculation/calcHist_Demo.py, samples/python/tutorial_code/Histograms_Matching/histogram_comparison/compareHist_Demo.py, samples/python/tutorial_code/Histograms_Matching/histogram_equalization/EqualizeHist_Demo.py, samples/python/tutorial_code/ImgTrans/warp_affine/Geometric_Transforms_Demo.py
I have updated the following tutorials with Java and Python code:
- Affine Transformations
- Histogram Equalization
- Histogram Calculation
- Histogram Comparison
- Back Projection
=> Add Java and Python code for some imgproc tutorials (2)

modules/videoio/src/cap.cpp, modules/videoio/src/cap_msmf.cpp, modules/videoio/src/precomp.hpp
VideoCapture and VideoWriter MSMF backend updated to use C++ interface (IVideoCapture)
=> MSMF VideoCapture backend C++ interface

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/11584
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/471
=> Fix dilated convolution from Keras

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/crop_and_resize_layer.cpp, modules/dnn/src/layers/detection_output_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp, samples/dnn/README.md, samples/dnn/tf_text_graph_faster_rcnn.py
Script to create a config file for Faster-RCNN networks from TensorFlow.
resolves https://github.com/opencv/opencv/issues/10393
related:
http://answers.opencv.org/question/187943/opencv-python-34-error-in-loading-tensorflow-object-detection-model/
http://answers.opencv.org/question/188747/how-to-use-readnetfromtensorflow-with-resnet50-network/
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/455
=> Faster-RCNN object detection models from TensorFlow

modules/videoio/src/cap.cpp, modules/videoio/src/videoio_registry.cpp
=> videoio: fix isOpened() method for legacy APIs, fix "index" API list

modules/videoio/src/cap_v4l.cpp
resolves #10546
Skip review of the first commit (just indentation/whitespace changes).
```
```
=> videoio(V4L): don't pre-scan or cache list of available cameras

modules/calib3d/test/test_stereomatching.cpp, modules/core/include/opencv2/core/mat.inl.hpp, modules/core/src/arithm.cpp, modules/core/src/convert.cpp, modules/core/src/copy.cpp, modules/features2d/src/agast.cpp, modules/features2d/src/fast.cpp, modules/features2d/src/gftt.cpp, modules/imgproc/src/hough.cpp
this is a part of #11416 by @take1014
=> fixes handling of empty matrices in some functions

modules/imgproc/src/histogram.cpp, modules/imgproc/test/test_histograms.cpp
=> Resize histSize if IPP is enabled

platforms/android/android.toolchain.cmake
Fixed a typo in android toolchain documentation.
=> Fixed a typo in android toolchain documentation.

modules/videoio/test/test_ffmpeg.cpp
=> videoio(test): fixup information dump

modules/core/include/opencv2/core.hpp
If this seems too wordy, take into account a new user who tries to find out extent of FP16 support in OpenCV.
=> convertFp16 documentation edit (2)

modules/imgproc/include/opencv2/imgproc.hpp, samples/cpp/tutorial_code/snippets/imgproc_HoughLinesCircles.cpp, samples/cpp/tutorial_code/snippets/imgproc_HoughLinesP.cpp, samples/cpp/tutorial_code/snippets/imgproc_applyColorMap.cpp, samples/cpp/tutorial_code/snippets/imgproc_calcHist.cpp, samples/cpp/tutorial_code/snippets/imgproc_drawContours.cpp
=> add imgproc snippets

modules/viz/include/opencv2/viz/widgets.hpp
=> fix #11668.

modules/viz/src/shapes.cpp
=> fix #11673.

modules/dnn/src/op_inf_engine.cpp, modules/dnn/src/op_inf_engine.hpp, modules/dnn/test/test_layers.cpp
* Use an updated API to create separate inference requests.
* Load unique plugin per device.
=> Fix multiple networks with Intel's Inference Engine backend

modules/python/test/test_misc.py, samples/dnn/object_detection.py, samples/python/calibrate.py, samples/python/camera_calibration_show_extrinsics.py, samples/python/tutorial_code/Histograms_Matching/histogram_equalization/EqualizeHist_Demo.py, samples/python/tutorial_code/imgProc/Smoothing/smoothing.py, samples/python/tutorial_code/imgProc/threshold/threshold.py, samples/python/tutorial_code/imgProc/threshold_inRange/threshold_inRange.py
=> python: eliminate pylint warnings

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/perf/perf_net.cpp, modules/dnn/src/darknet/darknet_io.cpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/crop_and_resize_layer.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp, samples/dnn/text_detection.cpp
Added ResizeBilinear op for tensorflow importer.
=> Added ResizeBilinear op for tf

modules/imgproc/src/resize.cpp
=> Fixed Assertion error due to Size.area() overflowing

modules/videoio/src/cap_msmf.cpp
Fix setting of frame size properties for MSMF-based VideoCapture
=> Fixed setting of frame size properties for MSMF-based VideoCapture

modules/videoio/src/cap_msmf.cpp
- no behavior changes in `grabFrame()`
- added Lock2D() support into `retrieveFrame()`
=> videoio(MSMF): refactor grabFrame() / retrieveFrame() methods

.gitattributes, 3rdparty/ffmpeg/ffmpeg-download.ps1.in, 3rdparty/ffmpeg/ffmpeg.cmake
=> cmake: generate and install ffmpeg-download.ps1

apps/version/CMakeLists.txt, apps/version/opencv_version.cpp
Improve experience of launching app from explorer:
- application just flash (open/close) the console window
Suggested Win32 application flavor additionally shows MessageBox and waits User interaction.
=> apps: add Win32 friendly opencv_version app

samples/cpp/videocapture_camera.cpp
- show capturing information: width / height / fps
- show average FPS for capture.read()+imshow() via cv::getTickCount()
- optional frame processing code path
=> samples: add videocapture_camera sample

modules/dnn/src/layers/batch_norm_layer.cpp
Fuse subsequent layers with batch norm layer.
=> Fuse top layers to batch normalization

doc/tutorials/imgproc/shapedescriptors/bounding_rects_circles/bounding_rects_circles.markdown, doc/tutorials/imgproc/shapedescriptors/bounding_rotated_ellipses/bounding_rotated_ellipses.markdown, doc/tutorials/imgproc/shapedescriptors/find_contours/find_contours.markdown, doc/tutorials/imgproc/shapedescriptors/hull/hull.markdown, doc/tutorials/imgproc/shapedescriptors/moments/moments.markdown, doc/tutorials/imgproc/shapedescriptors/point_polygon_test/point_polygon_test.markdown, doc/tutorials/imgproc/table_of_content_imgproc.markdown, samples/cpp/tutorial_code/ShapeDescriptors/findContours_demo.cpp, samples/cpp/tutorial_code/ShapeDescriptors/generalContours_demo1.cpp, samples/cpp/tutorial_code/ShapeDescriptors/generalContours_demo2.cpp, samples/cpp/tutorial_code/ShapeDescriptors/hull_demo.cpp, samples/cpp/tutorial_code/ShapeDescriptors/moments_demo.cpp, samples/cpp/tutorial_code/ShapeDescriptors/pointPolygonTest_demo.cpp, samples/java/tutorial_code/ShapeDescriptors/bounding_rects_circles/GeneralContoursDemo1.java, samples/java/tutorial_code/ShapeDescriptors/bounding_rotated_ellipses/GeneralContoursDemo2.java, samples/java/tutorial_code/ShapeDescriptors/find_contours/FindContoursDemo.java, samples/java/tutorial_code/ShapeDescriptors/hull/HullDemo.java, samples/java/tutorial_code/ShapeDescriptors/moments/MomentsDemo.java, samples/java/tutorial_code/ShapeDescriptors/point_polygon_test/PointPolygonTestDemo.java, samples/python/tutorial_code/ShapeDescriptors/bounding_rects_circles/generalContours_demo1.py, samples/python/tutorial_code/ShapeDescriptors/bounding_rotated_ellipses/generalContours_demo2.py, samples/python/tutorial_code/ShapeDescriptors/find_contours/findContours_demo.py, samples/python/tutorial_code/ShapeDescriptors/hull/hull_demo.py, samples/python/tutorial_code/ShapeDescriptors/moments/moments_demo.py, samples/python/tutorial_code/ShapeDescriptors/point_polygon_test/pointPolygonTest_demo.py
I have updated the following tutorials with Java and Python code:
- Finding contours in your image
- Convex Hull
- Creating Bounding boxes and circles for contours
- Creating Bounding rotated boxes and ellipses for contours
- Image Moments
- Point Polygon Test
Note:
I have replaced `threshold` function by `Canny` function to detect edges in the images for the following tutorials: Convex Hull, Creating Bounding boxes and circles for contours, Creating Bounding rotated boxes and ellipses for contours.
=> Add Java and Python code for some imgproc tutorials (3)

modules/core/src/copy.cpp, modules/core/test/test_mat.cpp
=> resolves 10507

doc/py_tutorials/py_calib3d/py_calibration/py_calibration.markdown
Corrects some minor grammatical and idiomatic issues to improve readability.
=> Improved readability of documentation with grammatical edits

modules/videoio/src/cap_msmf.cpp
Also use Win32 TRUE/FALSE in SetUINT32() calls for bool parameters.
=> videoio(msmf): cleanup unused methods from ComPtr wrapper

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/11761
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/476
=> Import ClipByValue from Keras

modules/dnn/src/darknet/darknet_io.cpp, modules/dnn/test/test_darknet_importer.cpp
resolves https://github.com/opencv/opencv/issues/11568
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/477
=> Average pooling and softmax layers from Darknet

doc/py_tutorials/py_imgproc/py_thresholding/py_thresholding.markdown
Corrected formula for weighted within-class variance
=> Corrected formula

modules/videoio/src/cap_dshow.cpp
This pull request adds the ability to control autofocus of DirectShow webcams (assuming the webcam supports the property, no effect if not supported) via the setProperty interface.
```c++
CvCapture->set(cv::CAP_PROP_AUTOFOCUS, this->AutofocusEnabled ? 1.0 : 0.0);
```
=> videoio(camera): Adding the ability to toggle autofocus on/off for DirectShow webcams

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/crop_and_resize_layer.cpp, modules/dnn/src/layers/shuffle_channel_layer.cpp, modules/dnn/test/test_layers.cpp
resolves https://github.com/opencv/opencv/issues/11561
resolves https://github.com/opencv/opencv/issues/11789
=> Add ShuffleChannel layer

samples/opencl/opencl-opencv-interop.cpp
=> Arm: suppress warning while building the samples

modules/dnn/include/opencv2/dnn/all_layers.hpp, modules/dnn/src/init.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/test/test_layers.cpp
Use Resize layer implementation to forward Interp layer from https://github.com/cdmh/deeplab-public
=> Implement Interp layer using Resize layer

modules/core/src/system.cpp
=> Fix system.cpp includes on Fuchsia.

apps/CMakeLists.txt, apps/annotation/CMakeLists.txt, apps/createsamples/CMakeLists.txt, apps/interactive-calibration/CMakeLists.txt, apps/traincascade/CMakeLists.txt, apps/version/CMakeLists.txt, apps/version/opencv_version.cpp, apps/visualisation/CMakeLists.txt
to be merged after #11734
Added single cmake function for application (<opencv>/apps) creation.
=> cmake: function for application creation

modules/dnn/src/layers/fully_connected_layer.cpp, modules/dnn/src/ocl4dnn/include/default_kernel_config.hpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp, modules/dnn/src/opencl/conv_layer_spatial.cl
update convolution kernel cache config, cleanup the idlf kernel and extend tuning parameter range. 
```
force_builders=Docs,linux,ocllinux,windows,ocl,macosx,oclmacosx,linuxNoOpt
```
=> update convolution opencl kernels in dnn module

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/11809
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/479
=> Update TensorFlow importer

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/10875
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/480
=> Multiple inputs for TensorFlow models

modules/video/include/opencv2/video/tracking.hpp, modules/video/src/lkpyramid.cpp
This pull request changes estimateRigidTransform so it takes as input some RANSAC parameters instead of having them hardcoded in the function.
=> Pass RANSAC parameters as function input

modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/11770
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/481
=> NCHW convolution and pooling from TensorFlow

modules/videoio/src/cap_msmf.cpp
Synchronized reading from camera with heavy frame processing
provides bad effects (huge frame latency, processing frames from the past).
Generally, there is no way to process each frame and some frames will be dropped.
Allow preventive frame dropping to reduce lag of processed frames.
This mode is applied to cameras only (opened by 'index').
=> videoio: MSMF async reader for camera stream

doc/tutorials/imgproc/imgtrans/distance_transformation/distance_transform.markdown, doc/tutorials/imgproc/table_of_content_imgproc.markdown, samples/cpp/tutorial_code/ImgTrans/imageSegmentation.cpp, samples/java/tutorial_code/ImgTrans/distance_transformation/ImageSegmentationDemo.java, samples/python/tutorial_code/ImgTrans/distance_transformation/imageSegmentation.py, samples/python/tutorial_code/features2D/feature_flann_matcher/SURF_FLANN_matching_Demo.py, samples/python/tutorial_code/features2D/feature_homography/SURF_FLANN_matching_homography_Demo.py
I have added Java and Python code for the following tutorial:
- Image Segmentation with Distance Transform and Watershed Algorithm tutorial.
Use more Pythonic code.
=> Add Java and Python code for an imgproc tutorial (4)

modules/dnn/src/tensorflow/tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/11809
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/483
=> Add a planar data layout for TensorFlow importer

modules/videoio/src/cap_msmf.cpp
resolves #11858
OpenCV binaries are compiled on Win10 environment
=> videoio(MSMF): avoid OpenCV load failure on Win7 machines

modules/videoio/src/cap_msmf.cpp
https://github.com/opencv/opencv/pull/11768#discussion_r198152112
=> videoio(MSMF): remove "always true" check

cmake/OpenCVUtils.cmake
=> Remove a redundant option.

doc/tutorials/features2d/akaze_matching/akaze_matching.markdown, doc/tutorials/features2d/table_of_content_features2d.markdown, samples/cpp/tutorial_code/features2D/AKAZE_match.cpp, samples/cpp/tutorial_code/features2D/feature_flann_matcher/SURF_FLANN_matching_Demo.cpp, samples/cpp/tutorial_code/features2D/feature_homography/SURF_FLANN_matching_homography_Demo.cpp, samples/java/tutorial_code/ImgTrans/distance_transformation/ImageSegmentationDemo.java, samples/java/tutorial_code/features2D/akaze_matching/AKAZEMatchDemo.java, samples/java/tutorial_code/features2D/feature_flann_matcher/SURFFLANNMatchingDemo.java, samples/java/tutorial_code/features2D/feature_homography/SURFFLANNMatchingHomographyDemo.java, samples/java/tutorial_code/photo/hdr_imaging/HDRImagingDemo.java, samples/python/tutorial_code/features2D/akaze_matching/AKAZE_match.py, samples/python/tutorial_code/features2D/feature_flann_matcher/SURF_FLANN_matching_Demo.py, samples/python/tutorial_code/features2D/feature_homography/SURF_FLANN_matching_homography_Demo.py
- Add Java and Python code for AKAZE matching tutorial
- Fix incorrect uses of Mat.mul() in Java code.
- Uniform Lowe's ratio test in the code.
=> Add Java and Python code for AKAZE matching tutorial

modules/videoio/src/cap_msmf.cpp
=> videoio(MSMF): fix 32-bit build crash

samples/cpp/videocapture_camera.cpp
Not all backends support -1 index.
Related: #11880
=> samples: videocapture_camera use VideoCapture with 0 index

modules/dnn/src/layers/reshape_layer.cpp, modules/dnn/src/tensorflow/tf_importer.cpp, modules/dnn/src/torch/torch_importer.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_tf_importer.cpp
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/486
=> Add Reshape layer tests

modules/dnn/src/tensorflow/tf_graph_simplifier.cpp, modules/dnn/test/test_tf_importer.cpp
resolves https://github.com/opencv/opencv/issues/11886
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/487
=> Nearest neighbor resize from Keras

modules/dnn/src/dnn.cpp, modules/dnn/test/test_layers.cpp
resolves https://github.com/opencv/opencv/issues/11884
=> Disable fusion to networks output layers

modules/dnn/src/dnn.cpp, modules/dnn/src/layers/convolution_layer.cpp, modules/dnn/src/layers/eltwise_layer.cpp, modules/dnn/src/layers/reorg_layer.cpp, modules/dnn/src/layers/resize_layer.cpp, modules/dnn/src/layers/slice_layer.cpp, modules/dnn/test/test_backends.cpp, modules/dnn/test/test_darknet_importer.cpp, modules/dnn/test/test_halide_layers.cpp, modules/dnn/test/test_layers.cpp, modules/dnn/test/test_precomp.hpp, modules/dnn/test/test_tf_importer.cpp, modules/dnn/test/test_torch_importer.cpp
Enable more parametric tests varying deep learning backends and devices targets
see https://github.com/opencv/opencv/issues/11866 for skipped tests which should be fixed
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/484
=> Enable per-layer deep learning tests for different backends

modules/core/include/opencv2/core/types.hpp
resolves #11898
Add missing constructors and assignment operators to Complex, Point2, Point3, Size, Rect, Scalar.
```
```
=> Add missing constructors and operator=

modules/dnn/src/dnn.cpp
resolves https://github.com/opencv/opencv/issues/11918
=> Replace convertFp16 from dnn::Net::setInput()

modules/highgui/src/window_gtk.cpp
=> highgui: GTK threading issues from #9002

modules/calib3d/src/calib3d_c_api.cpp, modules/calib3d/src/calibinit.cpp, modules/calib3d/src/precomp.hpp, modules/calib3d/test/test_cameracalibration.cpp, modules/core/include/opencv2/core/types_c.h, modules/ts/src/ts.cpp
Review link: https://github.com/opencv/opencv/pull/11703/files?utf8=%E2%9C%93&diff=split&w=1
```
```
=> calib3d: chessboard detector - replace OpenCV C API

samples/dnn/object_detection.cpp
resolves #11947
fix duplicate `thr` param
=> dnn: fix typo in object_detection.cpp sample

modules/core/src/check.cpp
=> avoid negative index.

modules/calib3d/misc/java/gen_dict.json, modules/java/generator/gen_java.py
* Bind Java functions considering all the default parameters.
* Add namespaces for the comments with C++ declarations
* Add `fisheye_` prefixes for methods and enum from `cv::fisheye`
resolves https://github.com/opencv/opencv/issues/5026
resolves https://github.com/opencv/opencv/issues/5189
resolves https://github.com/opencv/opencv/issues/7046
before:
```java
//
// C++:  void resize(Mat src, Mat& dst, Size dsize, double fx = 0, double fy = 0, int interpolation = INTER_LINEAR)
//
//javadoc: resize(src, dst, dsize, fx, fy, interpolation)
public static void resize(Mat src, Mat dst, Size dsize, double fx, double fy, int interpolation)
{
resize_0(src.nativeObj, dst.nativeObj, dsize.width, dsize.height, fx, fy, interpolation);
return;
}
//javadoc: resize(src, dst, dsize)
public static void …
```
=> Add Java overloads for each default argument

modules/dnn/src/dnn.cpp, modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp, modules/dnn/src/opencl/conv_layer_spatial.cl
```
force_builders=Docs,linux,ocllinux,windows,ocl,macosx,oclmacosx,linuxNoOpt
```
=> enable concat layer fuse for OCL target

modules/videoio/include/opencv2/videoio/container_avi.private.hpp, modules/videoio/src/container_avi.cpp
Resolves #11841
* use C++ streams for file I/O
* added check for integer overflows in some places
Tested by writing and reading a file near 4 Gb limit.
=> AVI container fixes
